import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'forecastPage',
  content: {
    title: t({
      ru: 'Прогноз',
      en: 'Forecast',
      kk: 'Болжам',
      de: 'Prognose',
      fr: 'Prévisions',
      es: 'Previsión',
      pt: 'Previsão',
      tr: 'Tahmin',
      uk: 'Прогноз',
      zh: '预测',
      ar: 'التوقعات',
      pl: 'Prognoza',
      it: 'Previsione',
      sk: 'Prognóza',
      ja: '予測',
      ko: '예측',
      hi: 'पूर्वानुमान',
      nl: 'Prognose',
      sv: 'Prognos',
      vi: 'Dự báo',
      id: 'Perkiraan',
      da: 'Prognose',
      nb: 'Prognose',
      nn: 'Prognose',
      fi: 'Ennuste',
      is: 'Spá',
      fo: 'Forsøgn',
      cs: 'Prognóza',
      bg: 'Прогноза',
      hr: 'Prognoza',
      sr: 'Прогноза',
      sl: 'Napoved',
      mk: 'Прогноза',
      be: 'Прагноз',
      bs: 'Prognoza',
      hsb: 'Prognoza',
    }),
    subtitle: t({
      ru: 'Баланс на 30, 90 или 365 дней вперёд из счетов, подписок, инвойсов, целей и ваших привычек',
      en: 'Your balance 30, 90 or 365 days ahead, from bills, subscriptions, invoices, goals and your habits',
      kk: 'Шоттар, жазылымдар, инвойстар, мақсаттар және әдеттеріңізден 30, 90 немесе 365 күнге баланс',
      de: 'Ihr Saldo 30, 90 oder 365 Tage voraus – aus Rechnungen, Abos, Rechnungen an Kunden, Zielen und Gewohnheiten',
      fr: 'Votre solde à 30, 90 ou 365 jours, d’après factures, abonnements, objectifs et habitudes',
      es: 'Su saldo a 30, 90 o 365 días, según facturas, suscripciones, objetivos y hábitos',
      pt: 'O seu saldo a 30, 90 ou 365 dias, a partir de contas, subscrições, faturas, objetivos e hábitos',
      tr: 'Faturalar, abonelikler, hedefler ve alışkanlıklarınızdan 30, 90 veya 365 gün sonraki bakiyeniz',
      uk: 'Баланс на 30, 90 або 365 днів уперед із рахунків, підписок, інвойсів, цілей і звичок',
      zh: '根据账单、订阅、发票、目标和习惯预测 30、90 或 365 天后的余额',
      ar: 'رصيدك بعد 30 أو 90 أو 365 يومًا من الفواتير والاشتراكات والأهداف وعاداتك',
      pl: 'Saldo za 30, 90 lub 365 dni na podstawie rachunków, subskrypcji, faktur, celów i nawyków',
      it: 'Il tuo saldo tra 30, 90 o 365 giorni, da bollette, abbonamenti, fatture, obiettivi e abitudini',
      sk: 'Zostatok o 30, 90 alebo 365 dní z účtov, predplatných, faktúr, cieľov a návykov',
      ja: '請求・サブスク・インボイス・目標・習慣から 30/90/365 日後の残高',
      ko: '청구서, 구독, 인보이스, 목표, 습관으로 본 30/90/365일 후 잔액',
      hi: 'बिल, सदस्यता, इनवॉइस, लक्ष्य और आदतों से 30, 90 या 365 दिन बाद का बैलेंस',
      nl: 'Uw saldo over 30, 90 of 365 dagen, uit rekeningen, abonnementen, facturen, doelen en gewoonten',
      sv: 'Ditt saldo om 30, 90 eller 365 dagar, från räkningar, prenumerationer, fakturor, mål och vanor',
      vi: 'Số dư sau 30, 90 hoặc 365 ngày từ hóa đơn, đăng ký, mục tiêu và thói quen',
      id: 'Saldo 30, 90, atau 365 hari ke depan dari tagihan, langganan, faktur, target, dan kebiasaan',
      da: 'Din saldo 30, 90 eller 365 dage frem ud fra regninger, abonnementer, fakturaer, mål og dine vaner',
      nb: 'Saldoen din 30, 90 eller 365 dager frem, basert på regninger, abonnementer, fakturaer, mål og vanene dine',
      nn: 'Saldoen din 30, 90 eller 365 dagar fram, basert på rekningar, abonnement, fakturaer, mål og vanane dine',
      fi: 'Saldosi 30, 90 tai 365 päivää eteenpäin laskujen, tilausten, myyntilaskujen, tavoitteiden ja tottumustesi perusteella',
      is: 'Staðan þín eftir 30, 90 eða 365 daga, út frá reikningum, áskriftum, sölureikningum, markmiðum og venjum þínum',
      fo: 'Saldo títt 30, 90 ella 365 dagar fram, út frá rokningum, haldum, fakturum, málum og vanum tínum',
      cs: 'Váš zůstatek za 30, 90 nebo 365 dní podle účtů, předplatných, faktur, cílů a vašich návyků',
      bg: 'Вашият баланс след 30, 90 или 365 дни според сметки, абонаменти, фактури, цели и навиците ви',
      hr: 'Vaše stanje za 30, 90 ili 365 dana prema računima, pretplatama, fakturama, ciljevima i vašim navikama',
      sr: 'Ваше стање за 30, 90 или 365 дана према рачунима, претплатама, фактурама, циљевима и вашим навикама',
      sl: 'Vaše stanje čez 30, 90 ali 365 dni glede na račune, naročnine, fakture, cilje in vaše navade',
      mk: 'Вашето салдо за 30, 90 или 365 дена според сметки, претплати, фактури, цели и вашите навики',
      be: 'Ваш баланс праз 30, 90 або 365 дзён паводле рахункаў, падпісак, інвойсаў, мэт і вашых звычак',
      bs: 'Vaše stanje za 30, 90 ili 365 dana prema računima, pretplatama, fakturama, ciljevima i vašim navikama',
      hsb: 'Waš staw za 30, 90 abo 365 dnjow po zličbach, abonementach, fakturach, cilach a wašich zwučenosćach',
    }),
    safeToSpend: t({
      ru: 'Можно потратить',
      en: 'Safe to spend',
      kk: 'Жұмсауға болады',
      de: 'Verfügbar',
      fr: 'Dépensable',
      es: 'Disponible para gastar',
      pt: 'Seguro para gastar',
      tr: 'Harcanabilir',
      uk: 'Можна витратити',
      zh: '可安心花费',
      ar: 'آمن للإنفاق',
      pl: 'Do wydania',
      it: 'Spendibile',
      sk: 'Bezpečne minúť',
      ja: '使えるお金',
      ko: '써도 되는 금액',
      hi: 'खर्च के लिए सुरक्षित',
      nl: 'Veilig te besteden',
      sv: 'Säkert att spendera',
      vi: 'Có thể chi',
      id: 'Aman dibelanjakan',
      da: 'Kan bruges',
      nb: 'Trygt å bruke',
      nn: 'Trygt å bruke',
      fi: 'Turvallisesti käytettävissä',
      is: 'Óhætt að eyða',
      fo: 'Trygt at nýta',
      cs: 'Lze bezpečně utratit',
      bg: 'Може да похарчите',
      hr: 'Sigurno za potrošiti',
      sr: 'Безбедно за трошење',
      sl: 'Varno za porabo',
      mk: 'Безбедно за трошење',
      be: 'Можна выдаткаваць',
      bs: 'Sigurno za potrošiti',
      hsb: 'Móžeće wudać',
    }),
    safeUntil: t({
      ru: 'до {{date}}',
      en: 'until {{date}}',
      kk: '{{date}} дейін',
      de: 'bis {{date}}',
      fr: 'jusqu’au {{date}}',
      es: 'hasta {{date}}',
      pt: 'até {{date}}',
      tr: '{{date}} tarihine kadar',
      uk: 'до {{date}}',
      zh: '至 {{date}}',
      ar: 'حتى {{date}}',
      pl: 'do {{date}}',
      it: 'fino al {{date}}',
      sk: 'do {{date}}',
      ja: '{{date}} まで',
      ko: '{{date}}까지',
      hi: '{{date}} तक',
      nl: 'tot {{date}}',
      sv: 'till {{date}}',
      vi: 'đến {{date}}',
      id: 'hingga {{date}}',
      da: 'indtil {{date}}',
      nb: 'til {{date}}',
      nn: 'til {{date}}',
      fi: '{{date}} asti',
      is: 'til {{date}}',
      fo: 'til {{date}}',
      cs: 'do {{date}}',
      bg: 'до {{date}}',
      hr: 'do {{date}}',
      sr: 'до {{date}}',
      sl: 'do {{date}}',
      mk: 'до {{date}}',
      be: 'да {{date}}',
      bs: 'do {{date}}',
      hsb: 'hač do {{date}}',
    }),
    safeUntilPayday: t({
      ru: 'до зарплаты {{date}}',
      en: 'until payday {{date}}',
      kk: '{{date}} жалақыға дейін',
      de: 'bis zum Gehalt am {{date}}',
      fr: 'jusqu’à la paie du {{date}}',
      es: 'hasta la paga del {{date}}',
      pt: 'até ao salário de {{date}}',
      tr: '{{date}} maaşına kadar',
      uk: 'до зарплати {{date}}',
      zh: '至发薪日 {{date}}',
      ar: 'حتى الراتب في {{date}}',
      pl: 'do wypłaty {{date}}',
      it: 'fino allo stipendio del {{date}}',
      sk: 'do výplaty {{date}}',
      ja: '{{date}} の給料日まで',
      ko: '{{date}} 급여일까지',
      hi: '{{date}} की तनख्वाह तक',
      nl: 'tot salaris op {{date}}',
      sv: 'till lönen {{date}}',
      vi: 'đến ngày lương {{date}}',
      id: 'hingga gajian {{date}}',
      da: 'indtil lønningsdag {{date}}',
      nb: 'til lønningsdag {{date}}',
      nn: 'til lønningsdag {{date}}',
      fi: 'palkkapäivään {{date}} asti',
      is: 'til útborgunardags {{date}}',
      fo: 'til lønardag {{date}}',
      cs: 'do výplaty {{date}}',
      bg: 'до заплатата {{date}}',
      hr: 'do plaće {{date}}',
      sr: 'до плате {{date}}',
      sl: 'do plače {{date}}',
      mk: 'до платата {{date}}',
      be: 'да зарплаты {{date}}',
      bs: 'do plate {{date}}',
      hsb: 'hač do mzdy {{date}}',
    }),
    lowestBalance: t({
      ru: 'Минимум',
      en: 'Lowest point',
      kk: 'Ең төмен',
      de: 'Tiefpunkt',
      fr: 'Point bas',
      es: 'Mínimo',
      pt: 'Mínimo',
      tr: 'En düşük',
      uk: 'Мінімум',
      zh: '最低点',
      ar: 'أدنى نقطة',
      pl: 'Minimum',
      it: 'Minimo',
      sk: 'Minimum',
      ja: '最低点',
      ko: '최저점',
      hi: 'न्यूनतम',
      nl: 'Laagste punt',
      sv: 'Lägsta punkt',
      vi: 'Thấp nhất',
      id: 'Titik terendah',
      da: 'Laveste punkt',
      nb: 'Laveste punkt',
      nn: 'Lågaste punkt',
      fi: 'Alin kohta',
      is: 'Lægsta staða',
      fo: 'Lægsta støða',
      cs: 'Nejnižší bod',
      bg: 'Най-ниска точка',
      hr: 'Najniža točka',
      sr: 'Најнижа тачка',
      sl: 'Najnižja točka',
      mk: 'Најниска точка',
      be: 'Найніжэйшы пункт',
      bs: 'Najniža tačka',
      hsb: 'Najnišši dypk',
    }),
    onDate: t({
      ru: '{{date}}',
      en: 'on {{date}}',
      kk: '{{date}}',
      de: 'am {{date}}',
      fr: 'le {{date}}',
      es: 'el {{date}}',
      pt: 'a {{date}}',
      tr: '{{date}}',
      uk: '{{date}}',
      zh: '{{date}}',
      ar: 'في {{date}}',
      pl: '{{date}}',
      it: 'il {{date}}',
      sk: '{{date}}',
      ja: '{{date}}',
      ko: '{{date}}',
      hi: '{{date}} को',
      nl: 'op {{date}}',
      sv: '{{date}}',
      vi: 'ngày {{date}}',
      id: '{{date}}',
      da: 'den {{date}}',
      nb: '{{date}}',
      nn: '{{date}}',
      fi: '{{date}}',
      is: '{{date}}',
      fo: '{{date}}',
      cs: '{{date}}',
      bg: 'на {{date}}',
      hr: '{{date}}',
      sr: '{{date}}',
      sl: '{{date}}',
      mk: 'на {{date}}',
      be: '{{date}}',
      bs: '{{date}}',
      hsb: '{{date}}',
    }),
    shortfall: t({
      ru: 'Кассовый разрыв',
      en: 'Shortfall',
      kk: 'Ақша тапшылығы',
      de: 'Engpass',
      fr: 'Découvert',
      es: 'Descubierto',
      pt: 'Descoberto',
      tr: 'Açık',
      uk: 'Касовий розрив',
      zh: '资金缺口',
      ar: 'عجز',
      pl: 'Niedobór',
      it: 'Scoperto',
      sk: 'Nedostatok',
      ja: '資金ショート',
      ko: '부족',
      hi: 'कमी',
      nl: 'Tekort',
      sv: 'Underskott',
      vi: 'Thiếu hụt',
      id: 'Kekurangan',
      da: 'Underskud',
      nb: 'Underskudd',
      nn: 'Underskot',
      fi: 'Vaje',
      is: 'Halli',
      fo: 'Undirskot',
      cs: 'Schodek',
      bg: 'Недостиг',
      hr: 'Manjak',
      sr: 'Мањак',
      sl: 'Primanjkljaj',
      mk: 'Недостиг',
      be: 'Недахоп',
      bs: 'Manjak',
      hsb: 'Deficit',
    }),
    shortfallOn: t({
      ru: 'баланс уйдёт в минус {{date}}',
      en: 'balance goes negative on {{date}}',
      kk: '{{date}} баланс минусқа кетеді',
      de: 'Saldo wird am {{date}} negativ',
      fr: 'le solde devient négatif le {{date}}',
      es: 'el saldo será negativo el {{date}}',
      pt: 'o saldo fica negativo a {{date}}',
      tr: 'bakiye {{date}} tarihinde eksiye düşer',
      uk: 'баланс піде в мінус {{date}}',
      zh: '余额将在 {{date}} 变为负数',
      ar: 'يصبح الرصيد سالبًا في {{date}}',
      pl: 'saldo spadnie poniżej zera {{date}}',
      it: 'il saldo va in negativo il {{date}}',
      sk: 'zostatok pôjde do mínusu {{date}}',
      ja: '{{date}} に残高がマイナスになります',
      ko: '{{date}}에 잔액이 마이너스가 됩니다',
      hi: '{{date}} को बैलेंस माइनस में जाएगा',
      nl: 'saldo wordt negatief op {{date}}',
      sv: 'saldot blir negativt {{date}}',
      vi: 'số dư âm vào {{date}}',
      id: 'saldo negatif pada {{date}}',
      da: 'saldoen bliver negativ den {{date}}',
      nb: 'saldoen blir negativ {{date}}',
      nn: 'saldoen blir negativ {{date}}',
      fi: 'saldo menee miinukselle {{date}}',
      is: 'staðan fer í mínus {{date}}',
      fo: 'saldoin verður negativ {{date}}',
      cs: 'zůstatek klesne do minusu {{date}}',
      bg: 'балансът става отрицателен на {{date}}',
      hr: 'stanje postaje negativno {{date}}',
      sr: 'стање постаје негативно {{date}}',
      sl: 'stanje bo negativno {{date}}',
      mk: 'салдото станува негативно на {{date}}',
      be: 'баланс стане адмоўным {{date}}',
      bs: 'stanje postaje negativno {{date}}',
      hsb: 'staw budźe negatiwny {{date}}',
    }),
    noShortfall: t({
      ru: 'В горизонте не ожидается',
      en: 'None expected in this horizon',
      kk: 'Бұл мерзімде күтілмейді',
      de: 'In diesem Zeitraum nicht erwartet',
      fr: 'Aucun prévu sur cet horizon',
      es: 'No se espera en este horizonte',
      pt: 'Não se espera neste horizonte',
      tr: 'Bu dönemde beklenmiyor',
      uk: 'У горизонті не очікується',
      zh: '该时段内无预期',
      ar: 'غير متوقع في هذا الأفق',
      pl: 'Nie przewiduje się w tym horyzoncie',
      it: 'Non previsto in questo orizzonte',
      sk: 'V tomto horizonte sa nečaká',
      ja: 'この期間には見込まれません',
      ko: '이 기간에는 없을 예정',
      hi: 'इस अवधि में अपेक्षित नहीं',
      nl: 'Niet verwacht in deze periode',
      sv: 'Inget väntat inom horisonten',
      vi: 'Không dự kiến trong kỳ này',
      id: 'Tidak diperkirakan dalam rentang ini',
      da: 'Ingen forventet i denne periode',
      nb: 'Ingen forventet i denne perioden',
      nn: 'Ingen venta i denne perioden',
      fi: 'Ei odotettavissa tällä aikavälillä',
      is: 'Ekki væntanlegt á þessu tímabili',
      fo: 'Einki væntað í hesum tíðarskeiði',
      cs: 'V tomto období se nečeká',
      bg: 'Не се очаква в този период',
      hr: 'Nije očekivano u ovom razdoblju',
      sr: 'Није очекивано у овом периоду',
      sl: 'V tem obdobju ni pričakovano',
      mk: 'Не се очекува во овој период',
      be: 'У гэтым перыядзе не чакаецца',
      bs: 'Nije očekivano u ovom periodu',
      hsb: 'W tutej dobje so njewočakuje',
    }),
    closingBalance: t({
      ru: 'Через {{days}} дней',
      en: 'In {{days}} days',
      kk: '{{days}} күннен кейін',
      de: 'In {{days}} Tagen',
      fr: 'Dans {{days}} jours',
      es: 'En {{days}} días',
      pt: 'Daqui a {{days}} dias',
      tr: '{{days}} gün sonra',
      uk: 'Через {{days}} днів',
      zh: '{{days}} 天后',
      ar: 'بعد {{days}} يومًا',
      pl: 'Za {{days}} dni',
      it: 'Tra {{days}} giorni',
      sk: 'O {{days}} dní',
      ja: '{{days}} 日後',
      ko: '{{days}}일 후',
      hi: '{{days}} दिनों में',
      nl: 'Over {{days}} dagen',
      sv: 'Om {{days}} dagar',
      vi: 'Sau {{days}} ngày',
      id: 'Dalam {{days}} hari',
      da: 'Om {{days}} dage',
      nb: 'Om {{days}} dager',
      nn: 'Om {{days}} dagar',
      fi: '{{days}} päivän päästä',
      is: 'Eftir {{days}} daga',
      fo: 'Um {{days}} dagar',
      cs: 'Za {{days}} dní',
      bg: 'След {{days}} дни',
      hr: 'Za {{days}} dana',
      sr: 'За {{days}} дана',
      sl: 'Čez {{days}} dni',
      mk: 'За {{days}} дена',
      be: 'Праз {{days}} дзён',
      bs: 'Za {{days}} dana',
      hsb: 'Za {{days}} dnjow',
    }),
    runway: t({
      ru: 'Запас хода',
      en: 'Runway',
      kk: 'Қор',
      de: 'Reichweite',
      fr: 'Autonomie',
      es: 'Margen',
      pt: 'Autonomia',
      tr: 'Nefes payı',
      uk: 'Запас ходу',
      zh: '可支撑时间',
      ar: 'المدى',
      pl: 'Zapas',
      it: 'Autonomia',
      sk: 'Rezerva',
      ja: 'ランウェイ',
      ko: '런웨이',
      hi: 'रनवे',
      nl: 'Runway',
      sv: 'Runway',
      vi: 'Thời gian cầm cự',
      id: 'Daya tahan',
      da: 'Runway',
      nb: 'Runway',
      nn: 'Runway',
      fi: 'Kassan riittävyys',
      is: 'Endingartími',
      fo: 'Rekkivídd',
      cs: 'Finanční rezerva',
      bg: 'Финансов запас',
      hr: 'Financijska rezerva',
      sr: 'Финансијска резерва',
      sl: 'Finančna rezerva',
      mk: 'Финансиска резерва',
      be: 'Фінансавы запас',
      bs: 'Finansijska rezerva',
      hsb: 'Financna rezerwa',
    }),
    runwayMonths: t({
      ru: '{{months}} мес при текущем расходе',
      en: '{{months}} months at the current burn',
      kk: 'Қазіргі шығынмен {{months}} ай',
      de: '{{months}} Monate bei aktuellem Verbrauch',
      fr: '{{months}} mois au rythme actuel',
      es: '{{months}} meses al ritmo actual',
      pt: '{{months}} meses ao ritmo atual',
      tr: 'Mevcut hızla {{months}} ay',
      uk: '{{months}} міс при поточних витратах',
      zh: '按当前消耗可支撑 {{months}} 个月',
      ar: '{{months}} شهرًا بمعدل الإنفاق الحالي',
      pl: '{{months}} mies. przy obecnym tempie',
      it: '{{months}} mesi al ritmo attuale',
      sk: '{{months}} mes. pri súčasnom tempe',
      ja: '現在の消費ペースで {{months}} か月',
      ko: '현재 소진 속도로 {{months}}개월',
      hi: 'मौजूदा खर्च पर {{months}} महीने',
      nl: '{{months}} maanden bij het huidige tempo',
      sv: '{{months}} månader i nuvarande takt',
      vi: '{{months}} tháng với mức chi hiện tại',
      id: '{{months}} bulan pada laju saat ini',
      da: '{{months}} måneder ved det nuværende forbrug',
      nb: '{{months}} måneder med nåværende forbruk',
      nn: '{{months}} månader med noverande forbruk',
      fi: '{{months}} kuukautta nykyisellä kulutuksella',
      is: '{{months}} mánuðir miðað við núverandi eyðslu',
      fo: '{{months}} mánaðir við núverandi nýtslu',
      cs: '{{months}} měsíců při současném tempu výdajů',
      bg: '{{months}} месеца при сегашните разходи',
      hr: '{{months}} mjeseci uz trenutnu potrošnju',
      sr: '{{months}} месеци уз тренутну потрошњу',
      sl: '{{months}} mesecev ob trenutni porabi',
      mk: '{{months}} месеци со сегашното трошење',
      be: '{{months}} мес. пры цяперашніх выдатках',
      bs: '{{months}} mjeseci uz trenutnu potrošnju',
      hsb: '{{months}} měsacow při nětčišim wudawanju',
    }),
    runwayGrowing: t({
      ru: 'Баланс растёт',
      en: 'Balance is growing',
      kk: 'Баланс өсуде',
      de: 'Saldo wächst',
      fr: 'Le solde augmente',
      es: 'El saldo crece',
      pt: 'O saldo cresce',
      tr: 'Bakiye artıyor',
      uk: 'Баланс зростає',
      zh: '余额在增长',
      ar: 'الرصيد ينمو',
      pl: 'Saldo rośnie',
      it: 'Il saldo cresce',
      sk: 'Zostatok rastie',
      ja: '残高は増えています',
      ko: '잔액이 늘고 있습니다',
      hi: 'बैलेंस बढ़ रहा है',
      nl: 'Saldo groeit',
      sv: 'Saldot växer',
      vi: 'Số dư đang tăng',
      id: 'Saldo bertambah',
      da: 'Saldoen vokser',
      nb: 'Saldoen vokser',
      nn: 'Saldoen veks',
      fi: 'Saldo kasvaa',
      is: 'Staðan fer vaxandi',
      fo: 'Saldoin veksur',
      cs: 'Zůstatek roste',
      bg: 'Балансът расте',
      hr: 'Stanje raste',
      sr: 'Стање расте',
      sl: 'Stanje raste',
      mk: 'Салдото расте',
      be: 'Баланс расце',
      bs: 'Stanje raste',
      hsb: 'Staw rosće',
    }),
    scenarios: t({
      ru: 'Сценарии',
      en: 'Scenarios',
      kk: 'Сценарийлер',
      de: 'Szenarien',
      fr: 'Scénarios',
      es: 'Escenarios',
      pt: 'Cenários',
      tr: 'Senaryolar',
      uk: 'Сценарії',
      zh: '情景',
      ar: 'سيناريوهات',
      pl: 'Scenariusze',
      it: 'Scenari',
      sk: 'Scenáre',
      ja: 'シナリオ',
      ko: '시나리오',
      hi: 'परिदृश्य',
      nl: 'Scenario’s',
      sv: 'Scenarier',
      vi: 'Kịch bản',
      id: 'Skenario',
      da: 'Scenarier',
      nb: 'Scenarier',
      nn: 'Scenario',
      fi: 'Skenaariot',
      is: 'Sviðsmyndir',
      fo: 'Støður',
      cs: 'Scénáře',
      bg: 'Сценарии',
      hr: 'Scenariji',
      sr: 'Сценарији',
      sl: 'Scenariji',
      mk: 'Сценарија',
      be: 'Сцэнарыі',
      bs: 'Scenariji',
      hsb: 'Scenarije',
    }),
    incomeFactor: t({
      ru: 'Доход',
      en: 'Income',
      kk: 'Кіріс',
      de: 'Einkommen',
      fr: 'Revenus',
      es: 'Ingresos',
      pt: 'Rendimento',
      tr: 'Gelir',
      uk: 'Дохід',
      zh: '收入',
      ar: 'الدخل',
      pl: 'Dochód',
      it: 'Entrate',
      sk: 'Príjem',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomen',
      sv: 'Inkomst',
      vi: 'Thu nhập',
      id: 'Pendapatan',
      da: 'Indtægter',
      nb: 'Inntekter',
      nn: 'Inntekter',
      fi: 'Tulot',
      is: 'Tekjur',
      fo: 'Inntøkur',
      cs: 'Příjmy',
      bg: 'Приходи',
      hr: 'Prihodi',
      sr: 'Приходи',
      sl: 'Prihodki',
      mk: 'Приходи',
      be: 'Даходы',
      bs: 'Prihodi',
      hsb: 'Dochody',
    }),
    expenseFactor: t({
      ru: 'Расходы',
      en: 'Spending',
      kk: 'Шығыс',
      de: 'Ausgaben',
      fr: 'Dépenses',
      es: 'Gastos',
      pt: 'Despesas',
      tr: 'Harcama',
      uk: 'Витрати',
      zh: '支出',
      ar: 'الإنفاق',
      pl: 'Wydatki',
      it: 'Spese',
      sk: 'Výdavky',
      ja: '支出',
      ko: '지출',
      hi: 'खर्च',
      nl: 'Uitgaven',
      sv: 'Utgifter',
      vi: 'Chi tiêu',
      id: 'Pengeluaran',
      da: 'Udgifter',
      nb: 'Utgifter',
      nn: 'Utgifter',
      fi: 'Menot',
      is: 'Útgjöld',
      fo: 'Útreiðslur',
      cs: 'Výdaje',
      bg: 'Разходи',
      hr: 'Troškovi',
      sr: 'Трошкови',
      sl: 'Odhodki',
      mk: 'Трошоци',
      be: 'Выдаткі',
      bs: 'Troškovi',
      hsb: 'Wudawki',
    }),
    excludeHint: t({
      ru: 'Снимите галочку, чтобы посмотреть «а если без этого»',
      en: 'Untick an item to see “what if without it”',
      kk: '«Онсыз қалай болады» деп көру үшін белгіні алыңыз',
      de: 'Haken entfernen für „was wäre ohne“',
      fr: 'Décochez pour voir « et sans ça ? »',
      es: 'Desmarque para ver «¿y sin esto?»',
      pt: 'Desmarque para ver «e sem isto?»',
      tr: '“Bu olmasa” demek için işareti kaldırın',
      uk: 'Зніміть галочку, щоб побачити «а якщо без цього»',
      zh: '取消勾选可查看“如果没有它”',
      ar: 'أزل العلامة لترى «ماذا لو بدونه»',
      pl: 'Odznacz, by zobaczyć „a gdyby bez tego”',
      it: 'Deseleziona per vedere “e senza?”',
      sk: 'Odškrtnite, aby ste videli „a čo bez toho“',
      ja: '外すと「これがなければ」が見られます',
      ko: '체크를 해제해 “이게 없다면”을 확인',
      hi: '“इसके बिना” देखने के लिए अनचेक करें',
      nl: 'Vink uit om “wat als zonder” te zien',
      sv: 'Avmarkera för att se ”tänk om utan”',
      vi: 'Bỏ chọn để xem “nếu không có nó”',
      id: 'Hapus centang untuk melihat “bagaimana jika tanpa ini”',
      da: 'Fjern fluebenet ved en post for at se “hvad nu hvis uden den”',
      nb: 'Fjern haken ved en post for å se “hva om uten den”',
      nn: 'Fjern haken ved ein post for å sjå “kva om utan han”',
      fi: 'Poista valinta kohteesta nähdäksesi “entä ilman sitä”',
      is: 'Taktu hakið af lið til að sjá “hvað ef án hans”',
      fo: 'Tak hakið av einum lið fyri at síggja “hvat um uttan hann”',
      cs: 'Zrušte zaškrtnutí položky a uvidíte “co kdyby bez ní”',
      bg: 'Махнете отметката на позиция, за да видите “какво ако без нея”',
      hr: 'Odznačite stavku da vidite “što ako bez nje”',
      sr: 'Одзначите ставку да видите “шта ако без ње”',
      sl: 'Odznačite postavko in poglejte “kaj če brez nje”',
      mk: 'Отштиклирајте ставка за да видите “што ако без неа”',
      be: 'Зніміце адзнаку з пазіцыі, каб убачыць “што, калі без яе”',
      bs: 'Odznačite stavku da vidite “šta ako bez nje”',
      hsb: 'Wotstrońće hóčku pola zapiska, zo byšće widźeli “što, jeli bjez njeho”',
    }),
    upcoming: t({
      ru: 'Что впереди',
      en: 'What is ahead',
      kk: 'Алда не бар',
      de: 'Was ansteht',
      fr: 'À venir',
      es: 'Próximamente',
      pt: 'O que vem aí',
      tr: 'Önümüzde',
      uk: 'Що попереду',
      zh: '即将发生',
      ar: 'ما هو قادم',
      pl: 'Co przed nami',
      it: 'In arrivo',
      sk: 'Čo je pred nami',
      ja: 'この先の予定',
      ko: '다가오는 항목',
      hi: 'आगे क्या है',
      nl: 'Wat komt er',
      sv: 'Vad som väntar',
      vi: 'Sắp tới',
      id: 'Yang akan datang',
      da: 'Hvad venter forude',
      nb: 'Hva som venter',
      nn: 'Kva som ventar',
      fi: 'Mitä on edessä',
      is: 'Hvað er fram undan',
      fo: 'Hvat er í vændum',
      cs: 'Co nás čeká',
      bg: 'Какво предстои',
      hr: 'Što slijedi',
      sr: 'Шта следи',
      sl: 'Kaj sledi',
      mk: 'Што следува',
      be: 'Што наперадзе',
      bs: 'Šta slijedi',
      hsb: 'Što nas čaka',
    }),
    everydayNote: t({
      ru: 'Плюс ≈{{amount}} в месяц на повседневные траты по истории за {{months}} мес',
      en: 'Plus ≈{{amount}} a month of everyday spending, from the last {{months}} months',
      kk: 'Қоса {{months}} ай тарихы бойынша айына ≈{{amount}} күнделікті шығын',
      de: 'Plus ≈{{amount}} Alltagsausgaben im Monat, aus den letzten {{months}} Monaten',
      fr: 'Plus ≈{{amount}} par mois de dépenses courantes, d’après les {{months}} derniers mois',
      es: 'Más ≈{{amount}} al mes de gastos diarios, según los últimos {{months}} meses',
      pt: 'Mais ≈{{amount}} por mês de despesas do dia a dia, dos últimos {{months}} meses',
      tr: 'Artı son {{months}} aya göre ayda ≈{{amount}} günlük harcama',
      uk: 'Плюс ≈{{amount}} на місяць на повсякденні витрати за останні {{months}} міс',
      zh: '另加每月约 {{amount}} 的日常支出（基于最近 {{months}} 个月）',
      ar: 'زائد ≈{{amount}} شهريًا للإنفاق اليومي من آخر {{months}} أشهر',
      pl: 'Plus ≈{{amount}} miesięcznie codziennych wydatków z ostatnich {{months}} mies.',
      it: 'Più ≈{{amount}} al mese di spese quotidiane, dagli ultimi {{months}} mesi',
      sk: 'Plus ≈{{amount}} mesačne bežných výdavkov z posledných {{months}} mes.',
      ja: 'さらに過去 {{months}} か月から月 ≈{{amount}} の日常支出',
      ko: '추가로 최근 {{months}}개월 기준 월 ≈{{amount}} 일상 지출',
      hi: 'साथ ही पिछले {{months}} महीनों के आधार पर ≈{{amount}}/माह रोज़मर्रा खर्च',
      nl: 'Plus ≈{{amount}} per maand dagelijkse uitgaven, uit de laatste {{months}} maanden',
      sv: 'Plus ≈{{amount}} i månaden vardagsutgifter, från de senaste {{months}} månaderna',
      vi: 'Cộng ≈{{amount}}/tháng chi tiêu hằng ngày theo {{months}} tháng gần nhất',
      id: 'Ditambah ≈{{amount}} per bulan pengeluaran harian dari {{months}} bulan terakhir',
      da: 'Plus ≈{{amount}} om måneden i dagligt forbrug, ud fra de seneste {{months}} måneder',
      nb: 'Pluss ≈{{amount}} i måneden i dagligforbruk, basert på de siste {{months}} månedene',
      nn: 'Pluss ≈{{amount}} i månaden i dagleg forbruk, basert på dei siste {{months}} månadene',
      fi: 'Lisäksi ≈{{amount}} kuussa arkikuluja viimeisten {{months}} kuukauden perusteella',
      is: 'Auk ≈{{amount}} á mánuði í daglega eyðslu, miðað við síðustu {{months}} mánuði',
      fo: 'Harafturat ≈{{amount}} um mánaðin í gerandisnýtslu, út frá seinastu {{months}} mánaðunum',
      cs: 'Plus ≈{{amount}} měsíčně na běžné výdaje podle posledních {{months}} měsíců',
      bg: 'Плюс ≈{{amount}} месечно за ежедневни разходи според последните {{months}} месеца',
      hr: 'Plus ≈{{amount}} mjesečno svakodnevne potrošnje, prema zadnjih {{months}} mjeseci',
      sr: 'Плус ≈{{amount}} месечно свакодневне потрошње, према последњих {{months}} месеци',
      sl: 'Plus ≈{{amount}} na mesec za vsakdanje stroške glede na zadnjih {{months}} mesecev',
      mk: 'Плус ≈{{amount}} месечно за секојдневно трошење, според последните {{months}} месеци',
      be: 'Плюс ≈{{amount}} у месяц на штодзённыя выдаткі, паводле апошніх {{months}} месяцаў',
      bs: 'Plus ≈{{amount}} mjesečno svakodnevne potrošnje, prema zadnjih {{months}} mjeseci',
      hsb: 'Plus ≈{{amount}} wob měsac za wšědne wudawki po zańdźenych {{months}} měsacach',
    }),
    unscheduled: t({
      ru: 'Ещё {{amount}} по счетам без даты',
      en: 'Another {{amount}} in bills without a date',
      kk: 'Күнсіз шоттар бойынша тағы {{amount}}',
      de: 'Weitere {{amount}} in Rechnungen ohne Datum',
      fr: 'Encore {{amount}} de factures sans date',
      es: 'Otros {{amount}} en facturas sin fecha',
      pt: 'Mais {{amount}} em contas sem data',
      tr: 'Tarihsiz faturalarda {{amount}} daha',
      uk: 'Ще {{amount}} за рахунками без дати',
      zh: '另有 {{amount}} 无日期账单',
      ar: '{{amount}} إضافية في فواتير بلا تاريخ',
      pl: 'Kolejne {{amount}} w rachunkach bez daty',
      it: 'Altri {{amount}} in bollette senza data',
      sk: 'Ďalších {{amount}} v účtoch bez dátumu',
      ja: '日付なしの請求がさらに {{amount}}',
      ko: '날짜 없는 청구서 {{amount}} 추가',
      hi: 'बिना तारीख के बिलों में {{amount}} और',
      nl: 'Nog {{amount}} aan rekeningen zonder datum',
      sv: 'Ytterligare {{amount}} i räkningar utan datum',
      vi: 'Thêm {{amount}} hóa đơn chưa có ngày',
      id: 'Tambahan {{amount}} tagihan tanpa tanggal',
      da: 'Yderligere {{amount}} i regninger uden dato',
      nb: 'Ytterligere {{amount}} i regninger uten dato',
      nn: 'Ytterlegare {{amount}} i rekningar utan dato',
      fi: 'Lisäksi {{amount}} laskuja ilman päivämäärää',
      is: '{{amount}} til viðbótar í reikningum án dagsetningar',
      fo: 'Aðrar {{amount}} í rokningum uttan dato',
      cs: 'Dalších {{amount}} v účtech bez data',
      bg: 'Още {{amount}} в сметки без дата',
      hr: 'Još {{amount}} u računima bez datuma',
      sr: 'Још {{amount}} у рачунима без датума',
      sl: 'Še {{amount}} v računih brez datuma',
      mk: 'Уште {{amount}} во сметки без датум',
      be: 'Яшчэ {{amount}} у рахунках без даты',
      bs: 'Još {{amount}} u računima bez datuma',
      hsb: 'Hišće {{amount}} w zličbach bjez datuma',
    }),
    empty: t({
      ru: 'Нечего прогнозировать: добавьте счета, подписки или загрузите выписку',
      en: 'Nothing to forecast yet: add bills, subscriptions or import a statement',
      kk: 'Болжайтын ештеңе жоқ: шоттар, жазылымдар қосыңыз немесе үзінді жүктеңіз',
      de: 'Noch nichts zu prognostizieren: Rechnungen, Abos anlegen oder einen Auszug importieren',
      fr: 'Rien à prévoir : ajoutez des factures, des abonnements ou importez un relevé',
      es: 'Nada que prever aún: añada facturas, suscripciones o importe un extracto',
      pt: 'Nada para prever: adicione contas, subscrições ou importe um extrato',
      tr: 'Tahmin edilecek bir şey yok: fatura, abonelik ekleyin veya ekstre yükleyin',
      uk: 'Нічого прогнозувати: додайте рахунки, підписки або імпортуйте виписку',
      zh: '暂无可预测内容：添加账单、订阅或导入对账单',
      ar: 'لا شيء للتوقع بعد: أضف فواتير أو اشتراكات أو استورد كشفًا',
      pl: 'Nie ma czego prognozować: dodaj rachunki, subskrypcje lub zaimportuj wyciąg',
      it: 'Niente da prevedere: aggiungi bollette, abbonamenti o importa un estratto',
      sk: 'Nie je čo prognózovať: pridajte účty, predplatné alebo importujte výpis',
      ja: '予測するものがありません：請求やサブスクを追加するか明細を取り込んでください',
      ko: '예측할 항목이 없습니다. 청구서나 구독을 추가하거나 명세서를 가져오세요',
      hi: 'पूर्वानुमान के लिए कुछ नहीं: बिल, सदस्यता जोड़ें या स्टेटमेंट आयात करें',
      nl: 'Nog niets te voorspellen: voeg rekeningen, abonnementen toe of importeer een afschrift',
      sv: 'Inget att prognostisera än: lägg till räkningar, prenumerationer eller importera ett utdrag',
      vi: 'Chưa có gì để dự báo: thêm hóa đơn, đăng ký hoặc nhập sao kê',
      id: 'Belum ada yang bisa diperkirakan: tambah tagihan, langganan, atau impor laporan',
      da: 'Intet at forudsige endnu: tilføj regninger, abonnementer eller importer et kontoudtog',
      nb: 'Ingenting å forutsi ennå: legg til regninger, abonnementer eller importer et kontoutskrift',
      nn: 'Ingenting å føreseie enno: legg til rekningar, abonnement eller importer ei kontoutskrift',
      fi: 'Ei vielä ennustettavaa: lisää laskuja, tilauksia tai tuo tiliote',
      is: 'Ekkert að spá enn: bættu við reikningum, áskriftum eða fluttu inn yfirlit',
      fo: 'Einki at forsøgna enn: legg rokningar, hald afturat ella innles eitt kontoyvirlit',
      cs: 'Zatím není co předpovídat: přidejte účty, předplatná nebo importujte výpis',
      bg: 'Все още няма какво да се прогнозира: добавете сметки, абонаменти или импортирайте извлечение',
      hr: 'Još nema što predvidjeti: dodajte račune, pretplate ili uvezite izvod',
      sr: 'Још нема шта да се предвиди: додајте рачуне, претплате или увезите извод',
      sl: 'Še ni česa napovedati: dodajte račune, naročnine ali uvozite izpisek',
      mk: 'Сè уште нема што да се предвиди: додајте сметки, претплати или увезете извод',
      be: 'Пакуль няма чаго прагназаваць: дадайце рахункі, падпіскі або імпартуйце выпіску',
      bs: 'Još nema šta predvidjeti: dodajte račune, pretplate ili uvezite izvod',
      hsb: 'Hišće ničo za prognozu: přidajće zličby, abonementy abo importujće wućah',
    }),
    error: t({
      ru: 'Не удалось построить прогноз',
      en: 'Could not build the forecast',
      kk: 'Болжамды құру мүмкін болмады',
      de: 'Prognose konnte nicht erstellt werden',
      fr: 'Impossible de construire les prévisions',
      es: 'No se pudo generar la previsión',
      pt: 'Não foi possível criar a previsão',
      tr: 'Tahmin oluşturulamadı',
      uk: 'Не вдалося побудувати прогноз',
      zh: '无法生成预测',
      ar: 'تعذّر إنشاء التوقعات',
      pl: 'Nie udało się zbudować prognozy',
      it: 'Impossibile creare la previsione',
      sk: 'Prognózu sa nepodarilo zostaviť',
      ja: '予測を作成できませんでした',
      ko: '예측을 만들지 못했습니다',
      hi: 'पूर्वानुमान नहीं बन सका',
      nl: 'Prognose kon niet worden gemaakt',
      sv: 'Kunde inte skapa prognosen',
      vi: 'Không tạo được dự báo',
      id: 'Tidak dapat membuat perkiraan',
      da: 'Kunne ikke lave prognosen',
      nb: 'Kunne ikke lage prognosen',
      nn: 'Kunne ikkje lage prognosen',
      fi: 'Ennustetta ei voitu laatia',
      is: 'Ekki tókst að gera spána',
      fo: 'Tað bar ikki til at gera forsøgnina',
      cs: 'Prognózu se nepodařilo sestavit',
      bg: 'Прогнозата не можа да бъде изготвена',
      hr: 'Prognozu nije moguće izraditi',
      sr: 'Прогнозу није могуће израдити',
      sl: 'Napovedi ni bilo mogoče izdelati',
      mk: 'Прогнозата не можеше да се изготви',
      be: 'Не ўдалося пабудаваць прагноз',
      bs: 'Prognozu nije moguće izraditi',
      hsb: 'Prognozu njebě móžno wutworić',
    }),
    kindPayable: t({
      ru: 'счёт',
      en: 'bill',
      kk: 'шот',
      de: 'Rechnung',
      fr: 'facture',
      es: 'factura',
      pt: 'conta',
      tr: 'fatura',
      uk: 'рахунок',
      zh: '账单',
      ar: 'فاتورة',
      pl: 'rachunek',
      it: 'bolletta',
      sk: 'účet',
      ja: '請求',
      ko: '청구서',
      hi: 'बिल',
      nl: 'rekening',
      sv: 'räkning',
      vi: 'hóa đơn',
      id: 'tagihan',
      da: 'regning',
      nb: 'regning',
      nn: 'rekning',
      fi: 'lasku',
      is: 'reikningur',
      fo: 'rokning',
      cs: 'účet',
      bg: 'сметка',
      hr: 'račun',
      sr: 'рачун',
      sl: 'račun',
      mk: 'сметка',
      be: 'рахунак',
      bs: 'račun',
      hsb: 'zličba',
    }),
    kindSubscription: t({
      ru: 'подписка',
      en: 'subscription',
      kk: 'жазылым',
      de: 'Abo',
      fr: 'abonnement',
      es: 'suscripción',
      pt: 'subscrição',
      tr: 'abonelik',
      uk: 'підписка',
      zh: '订阅',
      ar: 'اشتراك',
      pl: 'subskrypcja',
      it: 'abbonamento',
      sk: 'predplatné',
      ja: 'サブスク',
      ko: '구독',
      hi: 'सदस्यता',
      nl: 'abonnement',
      sv: 'prenumeration',
      vi: 'đăng ký',
      id: 'langganan',
      da: 'abonnement',
      nb: 'abonnement',
      nn: 'abonnement',
      fi: 'tilaus',
      is: 'áskrift',
      fo: 'hald',
      cs: 'předplatné',
      bg: 'абонамент',
      hr: 'pretplata',
      sr: 'претплата',
      sl: 'naročnina',
      mk: 'претплата',
      be: 'падпіска',
      bs: 'pretplata',
      hsb: 'abonement',
    }),
    kindInvoice: t({
      ru: 'инвойс к получению',
      en: 'invoice due in',
      kk: 'алынатын инвойс',
      de: 'erwartete Zahlung',
      fr: 'facture à encaisser',
      es: 'factura por cobrar',
      pt: 'fatura a receber',
      tr: 'tahsilat',
      uk: 'інвойс до отримання',
      zh: '待收发票',
      ar: 'فاتورة مستحقة',
      pl: 'faktura do otrzymania',
      it: 'fattura in arrivo',
      sk: 'faktúra na príjem',
      ja: '入金予定',
      ko: '받을 인보이스',
      hi: 'प्राप्य इनवॉइस',
      nl: 'te ontvangen factuur',
      sv: 'faktura att få',
      vi: 'hóa đơn sẽ thu',
      id: 'faktur masuk',
      da: 'forventet indbetaling',
      nb: 'forventet innbetaling',
      nn: 'venta innbetaling',
      fi: 'odotettu maksu',
      is: 'væntanleg greiðsla',
      fo: 'væntað inngjald',
      cs: 'očekávaná platba',
      bg: 'очаквано плащане',
      hr: 'očekivana uplata',
      sr: 'очекивана уплата',
      sl: 'pričakovano plačilo',
      mk: 'очекувана уплата',
      be: 'чаканая аплата',
      bs: 'očekivana uplata',
      hsb: 'wočakowane zapłaćenje',
    }),
    kindGoal: t({
      ru: 'взнос в цель',
      en: 'goal contribution',
      kk: 'мақсатқа жарна',
      de: 'Beitrag zum Ziel',
      fr: 'versement objectif',
      es: 'aporte al objetivo',
      pt: 'contribuição para o objetivo',
      tr: 'hedef katkısı',
      uk: 'внесок у ціль',
      zh: '目标储蓄',
      ar: 'مساهمة في هدف',
      pl: 'wpłata na cel',
      it: 'contributo all’obiettivo',
      sk: 'vklad do cieľa',
      ja: '目標への積立',
      ko: '목표 저축',
      hi: 'लक्ष्य में योगदान',
      nl: 'bijdrage aan doel',
      sv: 'bidrag till mål',
      vi: 'góp cho mục tiêu',
      id: 'setoran target',
      da: 'bidrag til mål',
      nb: 'bidrag til mål',
      nn: 'bidrag til mål',
      fi: 'tavoitesäästö',
      is: 'framlag í markmið',
      fo: 'gjald til mál',
      cs: 'vklad do cíle',
      bg: 'вноска за цел',
      hr: 'uplata za cilj',
      sr: 'уплата за циљ',
      sl: 'vplačilo za cilj',
      mk: 'уплата за цел',
      be: 'унёсак у мэту',
      bs: 'uplata za cilj',
      hsb: 'zapłaćenje na cil',
    }),
    kindIncome: t({
      ru: 'зарплата',
      en: 'payday',
      kk: 'жалақы',
      de: 'Gehalt',
      fr: 'paie',
      es: 'paga',
      pt: 'salário',
      tr: 'maaş',
      uk: 'зарплата',
      zh: '发薪',
      ar: 'راتب',
      pl: 'wypłata',
      it: 'stipendio',
      sk: 'výplata',
      ja: '給料日',
      ko: '급여',
      hi: 'तनख्वाह',
      nl: 'salaris',
      sv: 'lön',
      vi: 'ngày lương',
      id: 'gajian',
      da: 'lønningsdag',
      nb: 'lønningsdag',
      nn: 'lønningsdag',
      fi: 'palkkapäivä',
      is: 'útborgunardagur',
      fo: 'lønardagur',
      cs: 'výplata',
      bg: 'заплата',
      hr: 'plaća',
      sr: 'плата',
      sl: 'plača',
      mk: 'плата',
      be: 'зарплата',
      bs: 'plata',
      hsb: 'mzda',
    }),
    kindScenario: t({
      ru: 'сценарий',
      en: 'scenario',
      kk: 'сценарий',
      de: 'Szenario',
      fr: 'scénario',
      es: 'escenario',
      pt: 'cenário',
      tr: 'senaryo',
      uk: 'сценарій',
      zh: '情景',
      ar: 'سيناريو',
      pl: 'scenariusz',
      it: 'scenario',
      sk: 'scenár',
      ja: 'シナリオ',
      ko: '시나리오',
      hi: 'परिदृश्य',
      nl: 'scenario',
      sv: 'scenario',
      vi: 'kịch bản',
      id: 'skenario',
      da: 'scenarie',
      nb: 'scenario',
      nn: 'scenario',
      fi: 'skenaario',
      is: 'sviðsmynd',
      fo: 'støða',
      cs: 'scénář',
      bg: 'сценарий',
      hr: 'scenarij',
      sr: 'сценарио',
      sl: 'scenarij',
      mk: 'сценарио',
      be: 'сцэнарый',
      bs: 'scenarij',
      hsb: 'scenarij',
    }),
    overdue: t({
      ru: 'просрочено',
      en: 'overdue',
      kk: 'мерзімі өтті',
      de: 'überfällig',
      fr: 'en retard',
      es: 'vencido',
      pt: 'vencido',
      tr: 'gecikmiş',
      uk: 'прострочено',
      zh: '逾期',
      ar: 'متأخر',
      pl: 'po terminie',
      it: 'scaduto',
      sk: 'po splatnosti',
      ja: '期限超過',
      ko: '연체',
      hi: 'अतिदेय',
      nl: 'te laat',
      sv: 'försenad',
      vi: 'quá hạn',
      id: 'terlambat',
      da: 'forfalden',
      nb: 'forfalt',
      nn: 'forfalle',
      fi: 'erääntynyt',
      is: 'gjaldfallið',
      fo: 'fallið til gjaldingar',
      cs: 'po splatnosti',
      bg: 'просрочено',
      hr: 'dospjelo',
      sr: 'доспело',
      sl: 'zapadlo',
      mk: 'доспеано',
      be: 'пратэрмінавана',
      bs: 'dospjelo',
      hsb: 'zapadnjene',
    }),
  },
} satisfies Dictionary;

export default content;
