import { TaxRateKind } from '../../entities/tax-jurisdiction-rate.entity';
import {
  TaxFilingPeriod,
  TaxScheme,
  TaxThresholdPeriod,
} from '../../entities/tax-jurisdiction.entity';

/**
 * Statutory reference data for the jurisdictions we support.
 *
 * ⚠ These figures encode tax law and MUST be reviewed by an accountant before
 * this feature is enabled in production. They are seeded by migration rather
 * than edited at runtime, so correcting one means shipping a migration. Only
 * jurisdictions with actual users belong here — do not pre-populate countries
 * nobody has asked for.
 *
 * `validFrom: '1900-01-01'` is a sentinel meaning "since before we care", which
 * keeps every point-in-time query a plain BETWEEN with no NULL special case.
 */

export interface SeedRate {
  code: string;
  name: string;
  rate: number;
  kind: TaxRateKind;
  isDefault: boolean;
  validFrom: string;
  validTo: string | null;
}

export interface SeedJurisdiction {
  code: string;
  name: string;
  taxName: string;
  currency: string;
  scheme: TaxScheme;
  isEu: boolean;
  filingPeriod: TaxFilingPeriod;
  registrationThreshold: number | null;
  thresholdPeriod: TaxThresholdPeriod | null;
  rates: SeedRate[];
}

const SINCE_ALWAYS = '1900-01-01';

export const JURISDICTION_SEED: SeedJurisdiction[] = [
  {
    code: 'KZ',
    name: 'Kazakhstan',
    taxName: 'НДС',
    currency: 'KZT',
    scheme: TaxScheme.VAT,
    isEu: false,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    // Denominated in MRP and re-set every year, so we do not track a number.
    registrationThreshold: null,
    thresholdPeriod: null,
    rates: [
      {
        code: 'KZ_STANDARD',
        name: 'НДС 12%',
        rate: 12,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: '2025-12-31',
      },
      {
        code: 'KZ_STANDARD',
        name: 'НДС 16%',
        rate: 16,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: '2026-01-01',
        validTo: null,
      },
      {
        code: 'KZ_ZERO',
        name: 'НДС 0% (экспорт)',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'KZ_EXEMPT',
        name: 'Без НДС',
        rate: 0,
        kind: TaxRateKind.EXEMPT,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'DE',
    name: 'Germany',
    taxName: 'USt',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 25000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'DE_STANDARD',
        name: 'USt 19%',
        rate: 19,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'DE_REDUCED',
        name: 'USt 7%',
        rate: 7,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'DE_ZERO',
        name: 'USt 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'PL',
    name: 'Poland',
    taxName: 'VAT',
    currency: 'PLN',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 200000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'PL_STANDARD',
        name: 'VAT 23%',
        rate: 23,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'PL_REDUCED_8',
        name: 'VAT 8%',
        rate: 8,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'PL_REDUCED_5',
        name: 'VAT 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'PL_ZERO',
        name: 'VAT 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'AT',
    name: 'Austria',
    taxName: 'USt',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 55000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'AT_STANDARD',
        name: 'USt 20%',
        rate: 20,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'AT_REDUCED_13',
        name: 'USt 13%',
        rate: 13,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'AT_REDUCED_10',
        name: 'USt 10%',
        rate: 10,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'AT_ZERO',
        name: 'USt 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'BE',
    name: 'Belgium',
    taxName: 'BTW/TVA',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 25000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'BE_STANDARD',
        name: 'BTW/TVA 21%',
        rate: 21,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'BE_REDUCED_12',
        name: 'BTW/TVA 12%',
        rate: 12,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'BE_REDUCED_6',
        name: 'BTW/TVA 6%',
        rate: 6,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'BE_ZERO',
        name: 'BTW/TVA 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    // Adopted the euro 1 Jan 2026; threshold is the euro-converted figure.
    code: 'BG',
    name: 'Bulgaria',
    taxName: 'ДДС',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 51130,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'BG_STANDARD',
        name: 'ДДС 20%',
        rate: 20,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'BG_REDUCED_9',
        name: 'ДДС 9%',
        rate: 9,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'BG_ZERO',
        name: 'ДДС 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'HR',
    name: 'Croatia',
    taxName: 'PDV',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 60000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'HR_STANDARD',
        name: 'PDV 25%',
        rate: 25,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'HR_REDUCED_13',
        name: 'PDV 13%',
        rate: 13,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'HR_REDUCED_5',
        name: 'PDV 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'HR_ZERO',
        name: 'PDV 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'CY',
    name: 'Cyprus',
    taxName: 'ΦΠΑ',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 15600,
    thresholdPeriod: TaxThresholdPeriod.ROLLING_12M,
    rates: [
      {
        code: 'CY_STANDARD',
        name: 'ΦΠΑ 19%',
        rate: 19,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'CY_REDUCED_9',
        name: 'ΦΠΑ 9%',
        rate: 9,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'CY_REDUCED_5',
        name: 'ΦΠΑ 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'CY_REDUCED_3',
        name: 'ΦΠΑ 3%',
        rate: 3,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'CY_ZERO',
        name: 'ΦΠΑ 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'CZ',
    name: 'Czechia',
    taxName: 'DPH',
    currency: 'CZK',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 2000000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'CZ_STANDARD',
        name: 'DPH 21%',
        rate: 21,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'CZ_REDUCED_12',
        name: 'DPH 12%',
        rate: 12,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'CZ_ZERO',
        name: 'DPH 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    // No intermediate reduced rate in Danish law — only standard and zero.
    code: 'DK',
    name: 'Denmark',
    taxName: 'Moms',
    currency: 'DKK',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 50000,
    thresholdPeriod: TaxThresholdPeriod.ROLLING_12M,
    rates: [
      {
        code: 'DK_STANDARD',
        name: 'Moms 25%',
        rate: 25,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'DK_ZERO',
        name: 'Moms 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'EE',
    name: 'Estonia',
    taxName: 'KM',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 40000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'EE_STANDARD',
        name: 'KM 24%',
        rate: 24,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'EE_REDUCED_13',
        name: 'KM 13%',
        rate: 13,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'EE_REDUCED_9',
        name: 'KM 9%',
        rate: 9,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'EE_ZERO',
        name: 'KM 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'FI',
    name: 'Finland',
    taxName: 'ALV',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 20000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'FI_STANDARD',
        name: 'ALV 25.5%',
        rate: 25.5,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'FI_REDUCED_13_5',
        name: 'ALV 13.5%',
        rate: 13.5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'FI_REDUCED_10',
        name: 'ALV 10%',
        rate: 10,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'FI_ZERO',
        name: 'ALV 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    // Most small/medium businesses default to the simplified annual regime
    // (one yearly return plus two installments), not monthly/quarterly filing.
    // Threshold shown is the lower services-activity tier; goods sellers get
    // a higher one (EUR 85,000) that this single-figure schema can't hold.
    code: 'FR',
    name: 'France',
    taxName: 'TVA',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.ANNUAL,
    registrationThreshold: 37500,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'FR_STANDARD',
        name: 'TVA 20%',
        rate: 20,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'FR_REDUCED_10',
        name: 'TVA 10%',
        rate: 10,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'FR_REDUCED_5_5',
        name: 'TVA 5.5%',
        rate: 5.5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'FR_REDUCED_2_1',
        name: 'TVA 2.1%',
        rate: 2.1,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'FR_ZERO',
        name: 'TVA 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'GR',
    name: 'Greece',
    taxName: 'ΦΠΑ',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 10000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'GR_STANDARD',
        name: 'ΦΠΑ 24%',
        rate: 24,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'GR_REDUCED_13',
        name: 'ΦΠΑ 13%',
        rate: 13,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'GR_REDUCED_6',
        name: 'ΦΠΑ 6%',
        rate: 6,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'GR_ZERO',
        name: 'ΦΠΑ 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'HU',
    name: 'Hungary',
    taxName: 'ÁFA',
    currency: 'HUF',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 20000000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'HU_STANDARD',
        name: 'ÁFA 27%',
        rate: 27,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'HU_REDUCED_18',
        name: 'ÁFA 18%',
        rate: 18,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'HU_REDUCED_5',
        name: 'ÁFA 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'HU_ZERO',
        name: 'ÁFA 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    // Actual cadence is bi-monthly (six 2-month periods/year), which this
    // schema has no enum for — mapped to the nearest bucket. Threshold shown
    // is the lower services tier; a goods-predominant business gets EUR 85,000.
    code: 'IE',
    name: 'Ireland',
    taxName: 'VAT',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 42500,
    thresholdPeriod: TaxThresholdPeriod.ROLLING_12M,
    rates: [
      {
        code: 'IE_STANDARD',
        name: 'VAT 23%',
        rate: 23,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'IE_REDUCED_13_5',
        name: 'VAT 13.5%',
        rate: 13.5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'IE_REDUCED_9',
        name: 'VAT 9%',
        rate: 9,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'IE_REDUCED_4_8',
        name: 'VAT 4.8%',
        rate: 4.8,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'IE_ZERO',
        name: 'VAT 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'IT',
    name: 'Italy',
    taxName: 'IVA',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 85000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'IT_STANDARD',
        name: 'IVA 22%',
        rate: 22,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'IT_REDUCED_10',
        name: 'IVA 10%',
        rate: 10,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'IT_REDUCED_5',
        name: 'IVA 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'IT_REDUCED_4',
        name: 'IVA 4%',
        rate: 4,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'IT_ZERO',
        name: 'IVA 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'LV',
    name: 'Latvia',
    taxName: 'PVN',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 50000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'LV_STANDARD',
        name: 'PVN 21%',
        rate: 21,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LV_REDUCED_12',
        name: 'PVN 12%',
        rate: 12,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LV_REDUCED_5',
        name: 'PVN 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LV_ZERO',
        name: 'PVN 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'LT',
    name: 'Lithuania',
    taxName: 'PVM',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 60000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'LT_STANDARD',
        name: 'PVM 21%',
        rate: 21,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LT_REDUCED_12',
        name: 'PVM 12%',
        rate: 12,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LT_REDUCED_5',
        name: 'PVM 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LT_ZERO',
        name: 'PVM 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    taxName: 'TVA',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 50000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'LU_STANDARD',
        name: 'TVA 17%',
        rate: 17,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LU_REDUCED_14',
        name: 'TVA 14%',
        rate: 14,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LU_REDUCED_8',
        name: 'TVA 8%',
        rate: 8,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LU_REDUCED_3',
        name: 'TVA 3%',
        rate: 3,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'LU_ZERO',
        name: 'TVA 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'MT',
    name: 'Malta',
    taxName: 'VAT',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 35000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'MT_STANDARD',
        name: 'VAT 18%',
        rate: 18,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'MT_REDUCED_12',
        name: 'VAT 12%',
        rate: 12,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'MT_REDUCED_7',
        name: 'VAT 7%',
        rate: 7,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'MT_REDUCED_5',
        name: 'VAT 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'MT_ZERO',
        name: 'VAT 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'NL',
    name: 'Netherlands',
    taxName: 'BTW',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 20000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'NL_STANDARD',
        name: 'BTW 21%',
        rate: 21,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'NL_REDUCED_9',
        name: 'BTW 9%',
        rate: 9,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'NL_ZERO',
        name: 'BTW 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'PT',
    name: 'Portugal',
    taxName: 'IVA',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 15000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'PT_STANDARD',
        name: 'IVA 23%',
        rate: 23,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'PT_REDUCED_13',
        name: 'IVA 13%',
        rate: 13,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'PT_REDUCED_6',
        name: 'IVA 6%',
        rate: 6,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'PT_ZERO',
        name: 'IVA 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    // Has not adopted the euro.
    code: 'RO',
    name: 'Romania',
    taxName: 'TVA',
    currency: 'RON',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 395000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'RO_STANDARD',
        name: 'TVA 21%',
        rate: 21,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'RO_REDUCED_11',
        name: 'TVA 11%',
        rate: 11,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'RO_ZERO',
        name: 'TVA 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'SK',
    name: 'Slovakia',
    taxName: 'DPH',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 50000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'SK_STANDARD',
        name: 'DPH 23%',
        rate: 23,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SK_REDUCED_19',
        name: 'DPH 19%',
        rate: 19,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SK_REDUCED_5',
        name: 'DPH 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SK_ZERO',
        name: 'DPH 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'SI',
    name: 'Slovenia',
    taxName: 'DDV',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.MONTHLY,
    registrationThreshold: 60000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'SI_STANDARD',
        name: 'DDV 22%',
        rate: 22,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SI_REDUCED_9_5',
        name: 'DDV 9.5%',
        rate: 9.5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SI_REDUCED_5',
        name: 'DDV 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SI_ZERO',
        name: 'DDV 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    // Spain never implemented the EU small-business VAT exemption: registration
    // is mandatory from the first euro of turnover, hence no threshold.
    code: 'ES',
    name: 'Spain',
    taxName: 'IVA',
    currency: 'EUR',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: null,
    thresholdPeriod: null,
    rates: [
      {
        code: 'ES_STANDARD',
        name: 'IVA 21%',
        rate: 21,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'ES_REDUCED_10',
        name: 'IVA 10%',
        rate: 10,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'ES_REDUCED_4',
        name: 'IVA 4%',
        rate: 4,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'ES_ZERO',
        name: 'IVA 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    // Has not adopted the euro.
    code: 'SE',
    name: 'Sweden',
    taxName: 'Moms',
    currency: 'SEK',
    scheme: TaxScheme.VAT,
    isEu: true,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 120000,
    thresholdPeriod: TaxThresholdPeriod.CALENDAR_YEAR,
    rates: [
      {
        code: 'SE_STANDARD',
        name: 'Moms 25%',
        rate: 25,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SE_REDUCED_12',
        name: 'Moms 12%',
        rate: 12,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SE_REDUCED_6',
        name: 'Moms 6%',
        rate: 6,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'SE_ZERO',
        name: 'Moms 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    taxName: 'VAT',
    currency: 'GBP',
    scheme: TaxScheme.VAT,
    isEu: false,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 90000,
    thresholdPeriod: TaxThresholdPeriod.ROLLING_12M,
    rates: [
      {
        code: 'GB_STANDARD',
        name: 'VAT 20%',
        rate: 20,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'GB_REDUCED',
        name: 'VAT 5%',
        rate: 5,
        kind: TaxRateKind.REDUCED,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'GB_ZERO',
        name: 'VAT 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    taxName: 'VAT',
    currency: 'AED',
    scheme: TaxScheme.VAT,
    isEu: false,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: 375000,
    thresholdPeriod: TaxThresholdPeriod.ROLLING_12M,
    rates: [
      {
        code: 'AE_STANDARD',
        name: 'VAT 5%',
        rate: 5,
        kind: TaxRateKind.STANDARD,
        isDefault: true,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
      {
        code: 'AE_ZERO',
        name: 'VAT 0%',
        rate: 0,
        kind: TaxRateKind.ZERO,
        isDefault: false,
        validFrom: SINCE_ALWAYS,
        validTo: null,
      },
    ],
  },
  {
    // Seeded so the country is selectable, but intentionally rate-less: US
    // sales tax depends on the buyer's state and county and grants no input
    // credit, so it does not fit the VAT model this engine implements.
    code: 'US',
    name: 'United States',
    taxName: 'Sales tax',
    currency: 'USD',
    scheme: TaxScheme.SALES_TAX,
    isEu: false,
    filingPeriod: TaxFilingPeriod.QUARTERLY,
    registrationThreshold: null,
    thresholdPeriod: null,
    rates: [],
  },
];
