/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'protocolIntegrationPage',
  content: {
    status: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Status',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Status',
      it: 'Stato',
      sk: 'Stav',
      ja: 'ステータス',
      ko: '상태',
      hi: 'स्थिति',
      nl: 'Status',
      sv: 'Status',
      vi: 'Trạng thái',
      id: 'Status',
    }),
    configured: t({
      ru: 'Настроено',
      en: 'Configured',
      kk: 'Бапталған',
      de: 'Eingerichtet',
      fr: 'Configuré',
      es: 'Configurado',
      pt: 'Configurado',
      tr: 'Yapılandırıldı',
      uk: 'Налаштовано',
      zh: '已配置',
      ar: 'تم الإعداد',
      pl: 'Skonfigurowano',
      it: 'Configurato',
      sk: 'Nastavené',
      ja: '設定済み',
      ko: '구성됨',
      hi: 'कॉन्फ़िगर किया गया',
      nl: 'Ingesteld',
      sv: 'Konfigurerad',
      vi: 'Đã cấu hình',
      id: 'Sudah diatur',
    }),
    notConfigured: t({
      ru: 'Не настроено',
      en: 'Not configured',
      kk: 'Бапталмаған',
      de: 'Nicht eingerichtet',
      fr: 'Non configuré',
      es: 'Sin configurar',
      pt: 'Não configurado',
      tr: 'Yapılandırılmadı',
      uk: 'Не налаштовано',
      zh: '未配置',
      ar: 'غير مُعد',
      pl: 'Nie skonfigurowano',
      it: 'Non configurato',
      sk: 'Nenastavené',
      ja: '未設定',
      ko: '구성되지 않음',
      hi: 'कॉन्फ़िगर नहीं किया गया',
      nl: 'Niet ingesteld',
      sv: 'Inte konfigurerad',
      vi: 'Chưa cấu hình',
      id: 'Belum diatur',
    }),
    connection: t({
      ru: 'Подключение',
      en: 'Connection',
      kk: 'Қосылым',
      de: 'Verbindung',
      fr: 'Connexion',
      es: 'Conexión',
      pt: 'Conexão',
      tr: 'Bağlantı',
      uk: 'Підключення',
      zh: '连接',
      ar: 'الاتصال',
      pl: 'Połączenie',
      it: 'Connessione',
      sk: 'Pripojenie',
      ja: '接続',
      ko: '연결',
      hi: 'कनेक्शन',
      nl: 'Verbinding',
      sv: 'Anslutning',
      vi: 'Kết nối',
      id: 'Koneksi',
    }),
    checking: t({
      ru: 'Проверка...',
      en: 'Checking...',
      kk: 'Тексерілуде...',
      de: 'Wird geprüft...',
      fr: 'Vérification...',
      es: 'Comprobando...',
      pt: 'Verificando...',
      tr: 'Kontrol ediliyor...',
      uk: 'Перевірка...',
      zh: '正在检查...',
      ar: 'جارٍ التحقق...',
      pl: 'Sprawdzanie...',
      it: 'Verifica in corso...',
      sk: 'Overuje sa...',
      ja: '確認中...',
      ko: '확인 중...',
      hi: 'जाँच हो रही है...',
      nl: 'Controleren...',
      sv: 'Kontrollerar...',
      vi: 'Đang kiểm tra...',
      id: 'Memeriksa...',
    }),
    updateConnection: t({
      ru: 'Обновить подключение',
      en: 'Update connection',
      kk: 'Қосылымды жаңарту',
      de: 'Verbindung aktualisieren',
      fr: 'Mettre à jour la connexion',
      es: 'Actualizar conexión',
      pt: 'Atualizar conexão',
      tr: 'Bağlantıyı güncelle',
      uk: 'Оновити підключення',
      zh: '更新连接',
      ar: 'تحديث الاتصال',
      pl: 'Aktualizuj połączenie',
      it: 'Aggiorna connessione',
      sk: 'Aktualizovať pripojenie',
      ja: '接続を更新',
      ko: '연결 업데이트',
      hi: 'कनेक्शन अपडेट करें',
      nl: 'Verbinding bijwerken',
      sv: 'Uppdatera anslutning',
      vi: 'Cập nhật kết nối',
      id: 'Perbarui koneksi',
    }),
    connect: t({
      ru: 'Подключить',
      en: 'Connect',
      kk: 'Қосу',
      de: 'Verbinden',
      fr: 'Connecter',
      es: 'Conectar',
      pt: 'Conectar',
      tr: 'Bağla',
      uk: 'Підключити',
      zh: '连接',
      ar: 'اتصال',
      pl: 'Połącz',
      it: 'Connetti',
      sk: 'Pripojiť',
      ja: '接続',
      ko: '연결',
      hi: 'कनेक्ट करें',
      nl: 'Verbinden',
      sv: 'Anslut',
      vi: 'Kết nối',
      id: 'Hubungkan',
    }),
    disconnect: t({
      ru: 'Отключить',
      en: 'Disconnect',
      kk: 'Ажырату',
      de: 'Trennen',
      fr: 'Déconnecter',
      es: 'Desconectar',
      pt: 'Desconectar',
      tr: 'Bağlantıyı kes',
      uk: 'Відключити',
      zh: '断开连接',
      ar: 'قطع الاتصال',
      pl: 'Rozłącz',
      it: 'Disconnetti',
      sk: 'Odpojiť',
      ja: '接続を解除',
      ko: '연결 해제',
      hi: 'डिस्कनेक्ट करें',
      nl: 'Verbinding verbreken',
      sv: 'Koppla från',
      vi: 'Ngắt kết nối',
      id: 'Putuskan',
    }),
    presets: t({
      ru: 'Пресеты',
      en: 'Presets',
      kk: 'Пресеттер',
      de: 'Vorlagen',
      fr: 'Préréglages',
      es: 'Preajustes',
      pt: 'Predefinições',
      tr: 'Hazır ayarlar',
      uk: 'Пресети',
      zh: '预设',
      ar: 'الإعدادات المسبقة',
      pl: 'Ustawienia wstępne',
      it: 'Preset',
      sk: 'Predvoľby',
      ja: 'プリセット',
      ko: '프리셋',
      hi: 'प्रीसेट',
      nl: 'Voorinstellingen',
      sv: 'Förinställningar',
      vi: 'Mẫu dựng sẵn',
      id: 'Preset',
    }),
    actions: t({
      ru: 'Действия',
      en: 'Actions',
      kk: 'Әрекеттер',
      de: 'Aktionen',
      fr: 'Actions',
      es: 'Acciones',
      pt: 'Ações',
      tr: 'İşlemler',
      uk: 'Дії',
      zh: '操作',
      ar: 'الإجراءات',
      pl: 'Działania',
      it: 'Azioni',
      sk: 'Akcie',
      ja: '操作',
      ko: '작업',
      hi: 'कार्रवाइयाँ',
      nl: 'Acties',
      sv: 'Åtgärder',
      vi: 'Thao tác',
      id: 'Tindakan',
    }),
    loading: t({
      ru: 'Загрузка...',
      en: 'Loading...',
      kk: 'Жүктелуде...',
      de: 'Wird geladen...',
      fr: 'Chargement...',
      es: 'Cargando...',
      pt: 'Carregando...',
      tr: 'Yükleniyor...',
      uk: 'Завантаження...',
      zh: '加载中...',
      ar: 'جارٍ التحميل...',
      pl: 'Ładowanie...',
      it: 'Caricamento...',
      sk: 'Načítava sa...',
      ja: '読み込み中...',
      ko: '불러오는 중...',
      hi: 'लोड हो रहा है...',
      nl: 'Laden...',
      sv: 'Läser in...',
      vi: 'Đang tải...',
      id: 'Memuat...',
    }),
    browseFiles: t({
      ru: 'Просмотреть файлы',
      en: 'Browse files',
      kk: 'Файлдарды қарау',
      de: 'Dateien durchsuchen',
      fr: 'Parcourir les fichiers',
      es: 'Explorar archivos',
      pt: 'Procurar arquivos',
      tr: 'Dosyalara göz at',
      uk: 'Переглянути файли',
      zh: '浏览文件',
      ar: 'تصفح الملفات',
      pl: 'Przeglądaj pliki',
      it: 'Sfoglia file',
      sk: 'Prehľadávať súbory',
      ja: 'ファイルを参照',
      ko: '파일 찾아보기',
      hi: 'फ़ाइलें ब्राउज़ करें',
      nl: 'Bestanden bekijken',
      sv: 'Bläddra bland filer',
      vi: 'Duyệt tệp',
      id: 'Telusuri file',
    }),
    syncNow: t({
      ru: 'Синхронизировать',
      en: 'Sync now',
      kk: 'Қазір синхрондау',
      de: 'Jetzt synchronisieren',
      fr: 'Synchroniser',
      es: 'Sincronizar ahora',
      pt: 'Sincronizar agora',
      tr: 'Şimdi eşitle',
      uk: 'Синхронізувати',
      zh: '立即同步',
      ar: 'مزامنة الآن',
      pl: 'Synchronizuj teraz',
      it: 'Sincronizza ora',
      sk: 'Synchronizovať teraz',
      ja: '今すぐ同期',
      ko: '지금 동기화',
      hi: 'अभी सिंक करें',
      nl: 'Nu synchroniseren',
      sv: 'Synkronisera nu',
      vi: 'Đồng bộ ngay',
      id: 'Sinkronkan sekarang',
    }),
    import: t({
      ru: 'Импортировать',
      en: 'Import',
      kk: 'Импорттау',
      de: 'Importieren',
      fr: 'Importer',
      es: 'Importar',
      pt: 'Importar',
      tr: 'İçe aktar',
      uk: 'Імпортувати',
      zh: '导入',
      ar: 'استيراد',
      pl: 'Importuj',
      it: 'Importa',
      sk: 'Importovať',
      ja: 'インポート',
      ko: '가져오기',
      hi: 'इंपोर्ट करें',
      nl: 'Importeren',
      sv: 'Importera',
      vi: 'Nhập',
      id: 'Impor',
    }),
    messages: {
      connected: t({
        ru: 'Подключено',
        en: 'Connected',
        kk: 'Қосылды',
        de: 'Verbunden',
        fr: 'Connecté',
        es: 'Conectado',
        pt: 'Conectado',
        tr: 'Bağlandı',
        uk: 'Підключено',
        zh: '已连接',
        ar: 'تم الاتصال',
        pl: 'Połączono',
        it: 'Connesso',
        sk: 'Pripojené',
        ja: '接続しました',
        ko: '연결됨',
        hi: 'कनेक्ट हो गया',
        nl: 'Verbonden',
        sv: 'Ansluten',
        vi: 'Đã kết nối',
        id: 'Terhubung',
      }),
      connectionFailed: t({
        ru: 'Не удалось подключиться. Проверьте поля и попробуйте ещё раз.',
        en: 'Connection failed. Check the fields and try again.',
        kk: 'Қосылу сәтсіз аяқталды. Өрістерді тексеріп, қайталап көріңіз.',
        de: 'Verbindung fehlgeschlagen. Prüfen Sie die Felder und versuchen Sie es erneut.',
        fr: 'Échec de la connexion. Vérifiez les champs et réessayez.',
        es: 'Error de conexión. Revisa los campos e inténtalo de nuevo.',
        pt: 'Falha na conexão. Verifique os campos e tente novamente.',
        tr: 'Bağlantı başarısız. Alanları kontrol edip tekrar deneyin.',
        uk: 'Не вдалося підключитися. Перевірте поля й спробуйте ще раз.',
        zh: '连接失败。请检查字段后重试。',
        ar: 'فشل الاتصال. تحقّق من الحقول وحاول مرة أخرى.',
        pl: 'Połączenie nie powiodło się. Sprawdź pola i spróbuj ponownie.',
        it: 'Connessione non riuscita. Controlla i campi e riprova.',
        sk: 'Pripojenie zlyhalo. Skontrolujte polia a skúste to znova.',
        ja: '接続に失敗しました。入力内容を確認して再試行してください。',
        ko: '연결에 실패했습니다. 입력란을 확인하고 다시 시도하세요.',
        hi: 'कनेक्शन विफल रहा। फ़ील्ड जाँचें और फिर से प्रयास करें।',
        nl: 'Verbinding mislukt. Controleer de velden en probeer het opnieuw.',
        sv: 'Anslutningen misslyckades. Kontrollera fälten och försök igen.',
        vi: 'Kết nối thất bại. Hãy kiểm tra các trường và thử lại.',
        id: 'Koneksi gagal. Periksa kolom lalu coba lagi.',
      }),
      disconnected: t({
        ru: 'Отключено',
        en: 'Disconnected',
        kk: 'Ажыратылды',
        de: 'Getrennt',
        fr: 'Déconnecté',
        es: 'Desconectado',
        pt: 'Desconectado',
        tr: 'Bağlantı kesildi',
        uk: 'Відключено',
        zh: '已断开连接',
        ar: 'تم قطع الاتصال',
        pl: 'Rozłączono',
        it: 'Disconnesso',
        sk: 'Odpojené',
        ja: '接続を解除しました',
        ko: '연결 해제됨',
        hi: 'डिस्कनेक्ट हो गया',
        nl: 'Verbinding verbroken',
        sv: 'Frånkopplad',
        vi: 'Đã ngắt kết nối',
        id: 'Terputus',
      }),
      disconnectFailed: t({
        ru: 'Не удалось отключить',
        en: 'Unable to disconnect',
        kk: 'Ажырату мүмкін болмады',
        de: 'Trennen nicht möglich',
        fr: 'Impossible de se déconnecter',
        es: 'No se pudo desconectar',
        pt: 'Não foi possível desconectar',
        tr: 'Bağlantı kesilemedi',
        uk: 'Не вдалося відключити',
        zh: '无法断开连接',
        ar: 'تعذّر قطع الاتصال',
        pl: 'Nie udało się rozłączyć',
        it: 'Impossibile disconnettere',
        sk: 'Odpojenie sa nepodarilo',
        ja: '接続を解除できませんでした',
        ko: '연결을 해제할 수 없습니다',
        hi: 'डिस्कनेक्ट नहीं हो सका',
        nl: 'Verbinding verbreken mislukt',
        sv: 'Det gick inte att koppla från',
        vi: 'Không thể ngắt kết nối',
        id: 'Tidak dapat memutuskan',
      }),
      loadFilesFailed: t({
        ru: 'Не удалось загрузить файлы',
        en: 'Unable to load files',
        kk: 'Файлдарды жүктеу мүмкін болмады',
        de: 'Dateien konnten nicht geladen werden',
        fr: 'Impossible de charger les fichiers',
        es: 'No se pudieron cargar los archivos',
        pt: 'Não foi possível carregar os arquivos',
        tr: 'Dosyalar yüklenemedi',
        uk: 'Не вдалося завантажити файли',
        zh: '无法加载文件',
        ar: 'تعذّر تحميل الملفات',
        pl: 'Nie udało się wczytać plików',
        it: 'Impossibile caricare i file',
        sk: 'Súbory sa nepodarilo načítať',
        ja: 'ファイルを読み込めませんでした',
        ko: '파일을 불러올 수 없습니다',
        hi: 'फ़ाइलें लोड नहीं हो सकीं',
        nl: 'Bestanden konden niet worden geladen',
        sv: 'Det gick inte att läsa in filerna',
        vi: 'Không thể tải tệp',
        id: 'Tidak dapat memuat file',
      }),
      imported: t({
        ru: 'Импортирован файл {name}',
        en: 'Imported {name}',
        kk: '{name} импортталды',
        de: '{name} importiert',
        fr: '{name} importé',
        es: '{name} importado',
        pt: '{name} importado',
        tr: '{name} içe aktarıldı',
        uk: 'Імпортовано файл {name}',
        zh: '已导入 {name}',
        ar: 'تم استيراد {name}',
        pl: 'Zaimportowano {name}',
        it: '{name} importato',
        sk: 'Súbor {name} bol importovaný',
        ja: '{name} をインポートしました',
        ko: '{name}을(를) 가져왔습니다',
        hi: '{name} इंपोर्ट किया गया',
        nl: '{name} geïmporteerd',
        sv: '{name} har importerats',
        vi: 'Đã nhập {name}',
        id: '{name} diimpor',
      }),
      importFailed: t({
        ru: 'Не удалось импортировать {name}',
        en: 'Unable to import {name}',
        kk: '{name} импорттау мүмкін болмады',
        de: '{name} konnte nicht importiert werden',
        fr: "Impossible d'importer {name}",
        es: 'No se pudo importar {name}',
        pt: 'Não foi possível importar {name}',
        tr: '{name} içe aktarılamadı',
        uk: 'Не вдалося імпортувати {name}',
        zh: '无法导入 {name}',
        ar: 'تعذّر استيراد {name}',
        pl: 'Nie udało się zaimportować {name}',
        it: 'Impossibile importare {name}',
        sk: 'Súbor {name} sa nepodarilo importovať',
        ja: '{name} をインポートできませんでした',
        ko: '{name}을(를) 가져올 수 없습니다',
        hi: '{name} इंपोर्ट नहीं हो सका',
        nl: '{name} kon niet worden geïmporteerd',
        sv: 'Det gick inte att importera {name}',
        vi: 'Không thể nhập {name}',
        id: 'Tidak dapat mengimpor {name}',
      }),
      browseFailed: t({
        ru: 'Не удалось загрузить варианты. Проверьте учётные данные выше.',
        en: 'Could not load options. Check the credentials above.',
        kk: 'Нұсқаларды жүктеу мүмкін болмады. Жоғарыдағы тіркелгі деректерін тексеріңіз.',
        de: 'Optionen konnten nicht geladen werden. Prüfen Sie die Zugangsdaten oben.',
        fr: 'Impossible de charger les options. Vérifiez les identifiants ci-dessus.',
        es: 'No se pudieron cargar las opciones. Revisa las credenciales de arriba.',
        pt: 'Não foi possível carregar as opções. Verifique as credenciais acima.',
        tr: 'Seçenekler yüklenemedi. Yukarıdaki kimlik bilgilerini kontrol edin.',
        uk: 'Не вдалося завантажити варіанти. Перевірте облікові дані вище.',
        zh: '无法加载选项。请检查上方的凭据。',
        ar: 'تعذّر تحميل الخيارات. تحقّق من بيانات الاعتماد أعلاه.',
        pl: 'Nie udało się wczytać opcji. Sprawdź dane logowania powyżej.',
        it: 'Impossibile caricare le opzioni. Controlla le credenziali qui sopra.',
        sk: 'Možnosti sa nepodarilo načítať. Skontrolujte prihlasovacie údaje vyššie.',
        ja: '選択肢を読み込めませんでした。上の認証情報を確認してください。',
        ko: '옵션을 불러올 수 없습니다. 위의 자격 증명을 확인하세요.',
        hi: 'विकल्प लोड नहीं हो सके। ऊपर दिए क्रेडेंशियल जाँचें।',
        nl: 'Opties konden niet worden geladen. Controleer de inloggegevens hierboven.',
        sv: 'Det gick inte att läsa in alternativen. Kontrollera inloggningsuppgifterna ovan.',
        vi: 'Không thể tải các tùy chọn. Hãy kiểm tra thông tin đăng nhập ở trên.',
        id: 'Tidak dapat memuat opsi. Periksa kredensial di atas.',
      }),
      syncComplete: t({
        ru: 'Синхронизация завершена: {count}',
        en: 'Sync complete: {count}',
        kk: 'Синхрондау аяқталды: {count}',
        de: 'Synchronisierung abgeschlossen: {count}',
        fr: 'Synchronisation terminée : {count}',
        es: 'Sincronización completada: {count}',
        pt: 'Sincronização concluída: {count}',
        tr: 'Eşitleme tamamlandı: {count}',
        uk: 'Синхронізацію завершено: {count}',
        zh: '同步完成：{count}',
        ar: 'اكتملت المزامنة: {count}',
        pl: 'Synchronizacja zakończona: {count}',
        it: 'Sincronizzazione completata: {count}',
        sk: 'Synchronizácia dokončená: {count}',
        ja: '同期完了: {count}',
        ko: '동기화 완료: {count}',
        hi: 'सिंक पूरा हुआ: {count}',
        nl: 'Synchronisatie voltooid: {count}',
        sv: 'Synkroniseringen är klar: {count}',
        vi: 'Đồng bộ hoàn tất: {count}',
        id: 'Sinkronisasi selesai: {count}',
      }),
      syncFailed: t({
        ru: 'Не удалось синхронизировать',
        en: 'Sync failed',
        kk: 'Синхрондау сәтсіз аяқталды',
        de: 'Synchronisierung fehlgeschlagen',
        fr: 'Échec de la synchronisation',
        es: 'Error de sincronización',
        pt: 'Falha na sincronização',
        tr: 'Eşitleme başarısız',
        uk: 'Не вдалося синхронізувати',
        zh: '同步失败',
        ar: 'فشلت المزامنة',
        pl: 'Synchronizacja nie powiodła się',
        it: 'Sincronizzazione non riuscita',
        sk: 'Synchronizácia zlyhala',
        ja: '同期に失敗しました',
        ko: '동기화 실패',
        hi: 'सिंक विफल रहा',
        nl: 'Synchronisatie mislukt',
        sv: 'Synkroniseringen misslyckades',
        vi: 'Đồng bộ thất bại',
        id: 'Sinkronisasi gagal',
      }),
    },
  },
} satisfies Dictionary;

export default content;
