/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'protocolIntegrationPage',
  content: {
    status: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Status',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Status',
      it: 'Stato',
      sk: 'Stav',
      ja: 'ステータス',
      ko: '상태',
      hi: 'स्थिति',
      nl: 'Status',
      sv: 'Status',
      vi: 'Trạng thái',
      id: 'Status',
      da: 'Status',
      nb: 'Status',
      nn: 'Status',
      fi: 'Tila',
      is: 'Staða',
      fo: 'Støða',
      cs: 'Stav',
      bg: 'Статус',
      hr: 'Status',
      sr: 'Статус',
      sl: 'Stanje',
      mk: 'Статус',
      be: 'Стан',
      bs: 'Status',
      hsb: 'Status',
    }),
    configured: t({
      ru: 'Настроено',
      en: 'Configured',
      kk: 'Бапталған',
      de: 'Eingerichtet',
      fr: 'Configuré',
      es: 'Configurado',
      pt: 'Configurado',
      tr: 'Yapılandırıldı',
      uk: 'Налаштовано',
      zh: '已配置',
      ar: 'تم الإعداد',
      pl: 'Skonfigurowano',
      it: 'Configurato',
      sk: 'Nastavené',
      ja: '設定済み',
      ko: '구성됨',
      hi: 'कॉन्फ़िगर किया गया',
      nl: 'Ingesteld',
      sv: 'Konfigurerad',
      vi: 'Đã cấu hình',
      id: 'Sudah diatur',
      da: 'Konfigureret',
      nb: 'Konfigurert',
      nn: 'Konfigurert',
      fi: 'Määritetty',
      is: 'Stillt',
      fo: 'Ásett',
      cs: 'Nastaveno',
      bg: 'Настроено',
      hr: 'Postavljeno',
      sr: 'Постављено',
      sl: 'Nastavljeno',
      mk: 'Поставено',
      be: 'Наладжана',
      bs: 'Postavljeno',
      hsb: 'Nastajene',
    }),
    notConfigured: t({
      ru: 'Не настроено',
      en: 'Not configured',
      kk: 'Бапталмаған',
      de: 'Nicht eingerichtet',
      fr: 'Non configuré',
      es: 'Sin configurar',
      pt: 'Não configurado',
      tr: 'Yapılandırılmadı',
      uk: 'Не налаштовано',
      zh: '未配置',
      ar: 'غير مُعد',
      pl: 'Nie skonfigurowano',
      it: 'Non configurato',
      sk: 'Nenastavené',
      ja: '未設定',
      ko: '구성되지 않음',
      hi: 'कॉन्फ़िगर नहीं किया गया',
      nl: 'Niet ingesteld',
      sv: 'Inte konfigurerad',
      vi: 'Chưa cấu hình',
      id: 'Belum diatur',
      da: 'Ikke konfigureret',
      nb: 'Ikke konfigurert',
      nn: 'Ikkje konfigurert',
      fi: 'Ei määritetty',
      is: 'Ekki stillt',
      fo: 'Ikki ásett',
      cs: 'Nenastaveno',
      bg: 'Не е настроено',
      hr: 'Nije postavljeno',
      sr: 'Није постављено',
      sl: 'Ni nastavljeno',
      mk: 'Не е поставено',
      be: 'Не наладжана',
      bs: 'Nije postavljeno',
      hsb: 'Njenastajene',
    }),
    connection: t({
      ru: 'Подключение',
      en: 'Connection',
      kk: 'Қосылым',
      de: 'Verbindung',
      fr: 'Connexion',
      es: 'Conexión',
      pt: 'Conexão',
      tr: 'Bağlantı',
      uk: 'Підключення',
      zh: '连接',
      ar: 'الاتصال',
      pl: 'Połączenie',
      it: 'Connessione',
      sk: 'Pripojenie',
      ja: '接続',
      ko: '연결',
      hi: 'कनेक्शन',
      nl: 'Verbinding',
      sv: 'Anslutning',
      vi: 'Kết nối',
      id: 'Koneksi',
      da: 'Forbindelse',
      nb: 'Tilkobling',
      nn: 'Tilkopling',
      fi: 'Yhteys',
      is: 'Tenging',
      fo: 'Samband',
      cs: 'Připojení',
      bg: 'Свързване',
      hr: 'Povezivanje',
      sr: 'Повезивање',
      sl: 'Povezava',
      mk: 'Поврзување',
      be: 'Падлучэнне',
      bs: 'Povezivanje',
      hsb: 'Zwjazanje',
    }),
    checking: t({
      ru: 'Проверка...',
      en: 'Checking...',
      kk: 'Тексерілуде...',
      de: 'Wird geprüft...',
      fr: 'Vérification...',
      es: 'Comprobando...',
      pt: 'Verificando...',
      tr: 'Kontrol ediliyor...',
      uk: 'Перевірка...',
      zh: '正在检查...',
      ar: 'جارٍ التحقق...',
      pl: 'Sprawdzanie...',
      it: 'Verifica in corso...',
      sk: 'Overuje sa...',
      ja: '確認中...',
      ko: '확인 중...',
      hi: 'जाँच हो रही है...',
      nl: 'Controleren...',
      sv: 'Kontrollerar...',
      vi: 'Đang kiểm tra...',
      id: 'Memeriksa...',
      da: 'Tjekker ...',
      nb: 'Sjekker ...',
      nn: 'Sjekkar ...',
      fi: 'Tarkistetaan ...',
      is: 'Athuga ...',
      fo: 'Kannar ...',
      cs: 'Kontroluje se ...',
      bg: 'Проверява се ...',
      hr: 'Provjerava se ...',
      sr: 'Проверава се ...',
      sl: 'Preverjanje ...',
      mk: 'Се проверува ...',
      be: 'Праверка ...',
      bs: 'Provjerava se ...',
      hsb: 'Přepruwuje so ...',
    }),
    updateConnection: t({
      ru: 'Обновить подключение',
      en: 'Update connection',
      kk: 'Қосылымды жаңарту',
      de: 'Verbindung aktualisieren',
      fr: 'Mettre à jour la connexion',
      es: 'Actualizar conexión',
      pt: 'Atualizar conexão',
      tr: 'Bağlantıyı güncelle',
      uk: 'Оновити підключення',
      zh: '更新连接',
      ar: 'تحديث الاتصال',
      pl: 'Aktualizuj połączenie',
      it: 'Aggiorna connessione',
      sk: 'Aktualizovať pripojenie',
      ja: '接続を更新',
      ko: '연결 업데이트',
      hi: 'कनेक्शन अपडेट करें',
      nl: 'Verbinding bijwerken',
      sv: 'Uppdatera anslutning',
      vi: 'Cập nhật kết nối',
      id: 'Perbarui koneksi',
      da: 'Opdatér forbindelsen',
      nb: 'Oppdater tilkoblingen',
      nn: 'Oppdater tilkoplinga',
      fi: 'Päivitä yhteys',
      is: 'Uppfæra tengingu',
      fo: 'Dagfør sambandið',
      cs: 'Aktualizovat připojení',
      bg: 'Обновяване на връзката',
      hr: 'Ažuriraj vezu',
      sr: 'Ажурирај везу',
      sl: 'Posodobi povezavo',
      mk: 'Ажурирај ја врската',
      be: 'Абнавіць злучэнне',
      bs: 'Ažuriraj vezu',
      hsb: 'Zwjazanje zaktualizować',
    }),
    connect: t({
      ru: 'Подключить',
      en: 'Connect',
      kk: 'Қосу',
      de: 'Verbinden',
      fr: 'Connecter',
      es: 'Conectar',
      pt: 'Conectar',
      tr: 'Bağla',
      uk: 'Підключити',
      zh: '连接',
      ar: 'اتصال',
      pl: 'Połącz',
      it: 'Connetti',
      sk: 'Pripojiť',
      ja: '接続',
      ko: '연결',
      hi: 'कनेक्ट करें',
      nl: 'Verbinden',
      sv: 'Anslut',
      vi: 'Kết nối',
      id: 'Hubungkan',
      da: 'Forbind',
      nb: 'Koble til',
      nn: 'Kople til',
      fi: 'Yhdistä',
      is: 'Tengja',
      fo: 'Set í samband',
      cs: 'Připojit',
      bg: 'Свързване',
      hr: 'Poveži',
      sr: 'Повежи',
      sl: 'Poveži',
      mk: 'Поврзи',
      be: 'Падлучыць',
      bs: 'Poveži',
      hsb: 'Zwjazać',
    }),
    disconnect: t({
      ru: 'Отключить',
      en: 'Disconnect',
      kk: 'Ажырату',
      de: 'Trennen',
      fr: 'Déconnecter',
      es: 'Desconectar',
      pt: 'Desconectar',
      tr: 'Bağlantıyı kes',
      uk: 'Відключити',
      zh: '断开连接',
      ar: 'قطع الاتصال',
      pl: 'Rozłącz',
      it: 'Disconnetti',
      sk: 'Odpojiť',
      ja: '接続を解除',
      ko: '연결 해제',
      hi: 'डिस्कनेक्ट करें',
      nl: 'Verbinding verbreken',
      sv: 'Koppla från',
      vi: 'Ngắt kết nối',
      id: 'Putuskan',
      da: 'Afbryd',
      nb: 'Koble fra',
      nn: 'Kople frå',
      fi: 'Katkaise yhteys',
      is: 'Aftengja',
      fo: 'Skilja frá',
      cs: 'Odpojit',
      bg: 'Изключи',
      hr: 'Odspoji',
      sr: 'Искључи',
      sl: 'Odklopi',
      mk: 'Исклучи',
      be: 'Адключыць',
      bs: 'Odspoji',
      hsb: 'Wotdźělić',
    }),
    presets: t({
      ru: 'Пресеты',
      en: 'Presets',
      kk: 'Пресеттер',
      de: 'Vorlagen',
      fr: 'Préréglages',
      es: 'Preajustes',
      pt: 'Predefinições',
      tr: 'Hazır ayarlar',
      uk: 'Пресети',
      zh: '预设',
      ar: 'الإعدادات المسبقة',
      pl: 'Ustawienia wstępne',
      it: 'Preset',
      sk: 'Predvoľby',
      ja: 'プリセット',
      ko: '프리셋',
      hi: 'प्रीसेट',
      nl: 'Voorinstellingen',
      sv: 'Förinställningar',
      vi: 'Mẫu dựng sẵn',
      id: 'Preset',
      da: 'Forudindstillinger',
      nb: 'Forhåndsinnstillinger',
      nn: 'Førehandsinnstillingar',
      fi: 'Esiasetukset',
      is: 'Forstillingar',
      fo: 'Fyrirstillingar',
      cs: 'Předvolby',
      bg: 'Шаблони',
      hr: 'Predlošci',
      sr: 'Шаблони',
      sl: 'Prednastavitve',
      mk: 'Шаблони',
      be: 'Шаблоны',
      bs: 'Šabloni',
      hsb: 'Přednastajenja',
    }),
    actions: t({
      ru: 'Действия',
      en: 'Actions',
      kk: 'Әрекеттер',
      de: 'Aktionen',
      fr: 'Actions',
      es: 'Acciones',
      pt: 'Ações',
      tr: 'İşlemler',
      uk: 'Дії',
      zh: '操作',
      ar: 'الإجراءات',
      pl: 'Działania',
      it: 'Azioni',
      sk: 'Akcie',
      ja: '操作',
      ko: '작업',
      hi: 'कार्रवाइयाँ',
      nl: 'Acties',
      sv: 'Åtgärder',
      vi: 'Thao tác',
      id: 'Tindakan',
      da: 'Handlinger',
      nb: 'Handlinger',
      nn: 'Handlingar',
      fi: 'Toiminnot',
      is: 'Aðgerðir',
      fo: 'Handlingar',
      cs: 'Akce',
      bg: 'Действия',
      hr: 'Radnje',
      sr: 'Радње',
      sl: 'Dejanja',
      mk: 'Дејства',
      be: 'Дзеянні',
      bs: 'Radnje',
      hsb: 'Akcije',
    }),
    loading: t({
      ru: 'Загрузка...',
      en: 'Loading...',
      kk: 'Жүктелуде...',
      de: 'Wird geladen...',
      fr: 'Chargement...',
      es: 'Cargando...',
      pt: 'Carregando...',
      tr: 'Yükleniyor...',
      uk: 'Завантаження...',
      zh: '加载中...',
      ar: 'جارٍ التحميل...',
      pl: 'Ładowanie...',
      it: 'Caricamento...',
      sk: 'Načítava sa...',
      ja: '読み込み中...',
      ko: '불러오는 중...',
      hi: 'लोड हो रहा है...',
      nl: 'Laden...',
      sv: 'Läser in...',
      vi: 'Đang tải...',
      id: 'Memuat...',
      da: 'Indlæser...',
      nb: 'Laster...',
      nn: 'Lastar...',
      fi: 'Ladataan...',
      is: 'Hleð...',
      fo: 'Lesi...',
      cs: 'Načítání...',
      bg: 'Зарежда...',
      hr: 'Učitavanje...',
      sr: 'Учитавање...',
      sl: 'Nalaganje...',
      mk: 'Се вчитува...',
      be: 'Загрузка...',
      bs: 'Učitavanje...',
      hsb: 'Začituje so...',
    }),
    browseFiles: t({
      ru: 'Просмотреть файлы',
      en: 'Browse files',
      kk: 'Файлдарды қарау',
      de: 'Dateien durchsuchen',
      fr: 'Parcourir les fichiers',
      es: 'Explorar archivos',
      pt: 'Procurar arquivos',
      tr: 'Dosyalara göz at',
      uk: 'Переглянути файли',
      zh: '浏览文件',
      ar: 'تصفح الملفات',
      pl: 'Przeglądaj pliki',
      it: 'Sfoglia file',
      sk: 'Prehľadávať súbory',
      ja: 'ファイルを参照',
      ko: '파일 찾아보기',
      hi: 'फ़ाइलें ब्राउज़ करें',
      nl: 'Bestanden bekijken',
      sv: 'Bläddra bland filer',
      vi: 'Duyệt tệp',
      id: 'Telusuri file',
      da: 'Gennemse filer',
      nb: 'Bla gjennom filer',
      nn: 'Bla gjennom filer',
      fi: 'Selaa tiedostoja',
      is: 'Skoða skrár',
      fo: 'Kanna fílur',
      cs: 'Procházet soubory',
      bg: 'Разглеждане на файлове',
      hr: 'Pregledaj datoteke',
      sr: 'Прегледај датотеке',
      sl: 'Prebrskaj datoteke',
      mk: 'Прегледај податотеки',
      be: 'Праглядзець файлы',
      bs: 'Pregledaj datoteke',
      hsb: 'Dataje přepytać',
    }),
    syncNow: t({
      ru: 'Синхронизировать',
      en: 'Sync now',
      kk: 'Қазір синхрондау',
      de: 'Jetzt synchronisieren',
      fr: 'Synchroniser',
      es: 'Sincronizar ahora',
      pt: 'Sincronizar agora',
      tr: 'Şimdi eşitle',
      uk: 'Синхронізувати',
      zh: '立即同步',
      ar: 'مزامنة الآن',
      pl: 'Synchronizuj teraz',
      it: 'Sincronizza ora',
      sk: 'Synchronizovať teraz',
      ja: '今すぐ同期',
      ko: '지금 동기화',
      hi: 'अभी सिंक करें',
      nl: 'Nu synchroniseren',
      sv: 'Synkronisera nu',
      vi: 'Đồng bộ ngay',
      id: 'Sinkronkan sekarang',
      da: 'Synkronisér nu',
      nb: 'Synkroniser nå',
      nn: 'Synkroniser no',
      fi: 'Synkronoi nyt',
      is: 'Samstilla núna',
      fo: 'Samstilla nú',
      cs: 'Synchronizovat nyní',
      bg: 'Синхронизиране сега',
      hr: 'Sinkroniziraj sada',
      sr: 'Синхронизуј сада',
      sl: 'Sinhroniziraj zdaj',
      mk: 'Синхронизирај сега',
      be: 'Сінхранізаваць зараз',
      bs: 'Sinhronizuj sada',
      hsb: 'Nětko synchronizować',
    }),
    import: t({
      ru: 'Импортировать',
      en: 'Import',
      kk: 'Импорттау',
      de: 'Importieren',
      fr: 'Importer',
      es: 'Importar',
      pt: 'Importar',
      tr: 'İçe aktar',
      uk: 'Імпортувати',
      zh: '导入',
      ar: 'استيراد',
      pl: 'Importuj',
      it: 'Importa',
      sk: 'Importovať',
      ja: 'インポート',
      ko: '가져오기',
      hi: 'इंपोर्ट करें',
      nl: 'Importeren',
      sv: 'Importera',
      vi: 'Nhập',
      id: 'Impor',
      da: 'Importér',
      nb: 'Importer',
      nn: 'Importer',
      fi: 'Tuo',
      is: 'Flytja inn',
      fo: 'Flyt inn',
      cs: 'Importovat',
      bg: 'Внасяне',
      hr: 'Uvezi',
      sr: 'Увези',
      sl: 'Uvozi',
      mk: 'Внеси',
      be: 'Імпартаваць',
      bs: 'Uvezi',
      hsb: 'Importować',
    }),
    messages: {
      connected: t({
        ru: 'Подключено',
        en: 'Connected',
        kk: 'Қосылды',
        de: 'Verbunden',
        fr: 'Connecté',
        es: 'Conectado',
        pt: 'Conectado',
        tr: 'Bağlandı',
        uk: 'Підключено',
        zh: '已连接',
        ar: 'تم الاتصال',
        pl: 'Połączono',
        it: 'Connesso',
        sk: 'Pripojené',
        ja: '接続しました',
        ko: '연결됨',
        hi: 'कनेक्ट हो गया',
        nl: 'Verbonden',
        sv: 'Ansluten',
        vi: 'Đã kết nối',
        id: 'Terhubung',
        da: 'Forbundet',
        nb: 'Tilkoblet',
        nn: 'Tilkopla',
        fi: 'Yhdistetty',
        is: 'Tengt',
        fo: 'Sambundið',
        cs: 'Připojeno',
        bg: 'Свързано',
        hr: 'Povezano',
        sr: 'Повезано',
        sl: 'Povezano',
        mk: 'Поврзано',
        be: 'Падлучана',
        bs: 'Povezano',
        hsb: 'Zwjazane',
      }),
      connectionFailed: t({
        ru: 'Не удалось подключиться. Проверьте поля и попробуйте ещё раз.',
        en: 'Connection failed. Check the fields and try again.',
        kk: 'Қосылу сәтсіз аяқталды. Өрістерді тексеріп, қайталап көріңіз.',
        de: 'Verbindung fehlgeschlagen. Prüfen Sie die Felder und versuchen Sie es erneut.',
        fr: 'Échec de la connexion. Vérifiez les champs et réessayez.',
        es: 'Error de conexión. Revisa los campos e inténtalo de nuevo.',
        pt: 'Falha na conexão. Verifique os campos e tente novamente.',
        tr: 'Bağlantı başarısız. Alanları kontrol edip tekrar deneyin.',
        uk: 'Не вдалося підключитися. Перевірте поля й спробуйте ще раз.',
        zh: '连接失败。请检查字段后重试。',
        ar: 'فشل الاتصال. تحقّق من الحقول وحاول مرة أخرى.',
        pl: 'Połączenie nie powiodło się. Sprawdź pola i spróbuj ponownie.',
        it: 'Connessione non riuscita. Controlla i campi e riprova.',
        sk: 'Pripojenie zlyhalo. Skontrolujte polia a skúste to znova.',
        ja: '接続に失敗しました。入力内容を確認して再試行してください。',
        ko: '연결에 실패했습니다. 입력란을 확인하고 다시 시도하세요.',
        hi: 'कनेक्शन विफल रहा। फ़ील्ड जाँचें और फिर से प्रयास करें।',
        nl: 'Verbinding mislukt. Controleer de velden en probeer het opnieuw.',
        sv: 'Anslutningen misslyckades. Kontrollera fälten och försök igen.',
        vi: 'Kết nối thất bại. Hãy kiểm tra các trường và thử lại.',
        id: 'Koneksi gagal. Periksa kolom lalu coba lagi.',
        da: 'Forbindelsen mislykkedes. Kontrollér felterne, og prøv igen.',
        nb: 'Tilkoblingen mislyktes. Kontroller feltene og prøv igjen.',
        nn: 'Tilkoplinga mislukkast. Kontroller felta og prøv igjen.',
        fi: 'Yhteys epäonnistui. Tarkista kentät ja yritä uudelleen.',
        is: 'Tenging mistókst. Athugaðu svæðin og prófaðu aftur.',
        fo: 'Sambandið miseydnaðist. Kanna teigarnar og royn aftur.',
        cs: 'Připojení se nezdařilo. Zkontrolujte pole a zkuste to znovu.',
        bg: 'Връзката не успя. Проверете полетата и опитайте отново.',
        hr: 'Veza nije uspjela. Provjerite polja i pokušajte ponovno.',
        sr: 'Веза није успела. Проверите поља и пробајте поново.',
        sl: 'Povezava ni uspela. Preverite polja in poskusite znova.',
        mk: 'Врската не успеа. Проверете ги полињата и обидете се повторно.',
        be: 'Злучэнне не ўдалося. Праверце полі і паспрабуйце зноў.',
        bs: 'Veza nije uspjela. Provjerite polja i pokušajte ponovo.',
        hsb: 'Zwjazanje je so njeporadźiło. Přepruwujće pola a spytajće znowa.',
      }),
      disconnected: t({
        ru: 'Отключено',
        en: 'Disconnected',
        kk: 'Ажыратылды',
        de: 'Getrennt',
        fr: 'Déconnecté',
        es: 'Desconectado',
        pt: 'Desconectado',
        tr: 'Bağlantı kesildi',
        uk: 'Відключено',
        zh: '已断开连接',
        ar: 'تم قطع الاتصال',
        pl: 'Rozłączono',
        it: 'Disconnesso',
        sk: 'Odpojené',
        ja: '接続を解除しました',
        ko: '연결 해제됨',
        hi: 'डिस्कनेक्ट हो गया',
        nl: 'Verbinding verbroken',
        sv: 'Frånkopplad',
        vi: 'Đã ngắt kết nối',
        id: 'Terputus',
        da: 'Forbindelsen er afbrudt',
        nb: 'Tilkoblingen er brutt',
        nn: 'Tilkoplinga er broten',
        fi: 'Yhteys katkaistu',
        is: 'Aftengt',
        fo: 'Sambandið er brotið',
        cs: 'Odpojeno',
        bg: 'Връзката е прекъсната',
        hr: 'Veza je prekinuta',
        sr: 'Веза је прекинута',
        sl: 'Povezava je prekinjena',
        mk: 'Врската е прекината',
        be: 'Злучэнне разарвана',
        bs: 'Veza je prekinuta',
        hsb: 'Zwjazanje přetorhnjene',
      }),
      disconnectFailed: t({
        ru: 'Не удалось отключить',
        en: 'Unable to disconnect',
        kk: 'Ажырату мүмкін болмады',
        de: 'Trennen nicht möglich',
        fr: 'Impossible de se déconnecter',
        es: 'No se pudo desconectar',
        pt: 'Não foi possível desconectar',
        tr: 'Bağlantı kesilemedi',
        uk: 'Не вдалося відключити',
        zh: '无法断开连接',
        ar: 'تعذّر قطع الاتصال',
        pl: 'Nie udało się rozłączyć',
        it: 'Impossibile disconnettere',
        sk: 'Odpojenie sa nepodarilo',
        ja: '接続を解除できませんでした',
        ko: '연결을 해제할 수 없습니다',
        hi: 'डिस्कनेक्ट नहीं हो सका',
        nl: 'Verbinding verbreken mislukt',
        sv: 'Det gick inte att koppla från',
        vi: 'Không thể ngắt kết nối',
        id: 'Tidak dapat memutuskan',
        da: 'Forbindelsen kunne ikke afbrydes',
        nb: 'Kunne ikke bryte tilkoblingen',
        nn: 'Kunne ikkje bryte tilkoplinga',
        fi: 'Yhteyttä ei voitu katkaista',
        is: 'Ekki var hægt að aftengja',
        fo: 'Sambandið kundi ikki brótast',
        cs: 'Nepodařilo se odpojit',
        bg: 'Връзката не можа да се прекъсне',
        hr: 'Vezu nije bilo moguće prekinuti',
        sr: 'Везу није било могуће прекинути',
        sl: 'Povezave ni bilo mogoče prekiniti',
        mk: 'Врската не можеше да се прекине',
        be: 'Не ўдалося разарваць злучэнне',
        bs: 'Vezu nije bilo moguće prekinuti',
        hsb: 'Zwjazanje njeda so přetorhnyć',
      }),
      loadFilesFailed: t({
        ru: 'Не удалось загрузить файлы',
        en: 'Unable to load files',
        kk: 'Файлдарды жүктеу мүмкін болмады',
        de: 'Dateien konnten nicht geladen werden',
        fr: 'Impossible de charger les fichiers',
        es: 'No se pudieron cargar los archivos',
        pt: 'Não foi possível carregar os arquivos',
        tr: 'Dosyalar yüklenemedi',
        uk: 'Не вдалося завантажити файли',
        zh: '无法加载文件',
        ar: 'تعذّر تحميل الملفات',
        pl: 'Nie udało się wczytać plików',
        it: 'Impossibile caricare i file',
        sk: 'Súbory sa nepodarilo načítať',
        ja: 'ファイルを読み込めませんでした',
        ko: '파일을 불러올 수 없습니다',
        hi: 'फ़ाइलें लोड नहीं हो सकीं',
        nl: 'Bestanden konden niet worden geladen',
        sv: 'Det gick inte att läsa in filerna',
        vi: 'Không thể tải tệp',
        id: 'Tidak dapat memuat file',
        da: 'Filerne kunne ikke indlæses',
        nb: 'Kunne ikke laste filene',
        nn: 'Kunne ikkje laste filene',
        fi: 'Tiedostoja ei voitu ladata',
        is: 'Ekki var hægt að hlaða skrár',
        fo: 'Fílurnar kundu ikki lesast inn',
        cs: 'Nepodařilo se načíst soubory',
        bg: 'Файловете не можаха да се заредят',
        hr: 'Datoteke nije bilo moguće učitati',
        sr: 'Датотеке није било могуће учитати',
        sl: 'Datotek ni bilo mogoče naložiti',
        mk: 'Податотеките не можеа да се вчитаат',
        be: 'Не ўдалося загрузіць файлы',
        bs: 'Datoteke nije bilo moguće učitati',
        hsb: 'Dataje njedachu so začitać',
      }),
      imported: t({
        ru: 'Импортирован файл {name}',
        en: 'Imported {name}',
        kk: '{name} импортталды',
        de: '{name} importiert',
        fr: '{name} importé',
        es: '{name} importado',
        pt: '{name} importado',
        tr: '{name} içe aktarıldı',
        uk: 'Імпортовано файл {name}',
        zh: '已导入 {name}',
        ar: 'تم استيراد {name}',
        pl: 'Zaimportowano {name}',
        it: '{name} importato',
        sk: 'Súbor {name} bol importovaný',
        ja: '{name} をインポートしました',
        ko: '{name}을(를) 가져왔습니다',
        hi: '{name} इंपोर्ट किया गया',
        nl: '{name} geïmporteerd',
        sv: '{name} har importerats',
        vi: 'Đã nhập {name}',
        id: '{name} diimpor',
        da: '{name} er importeret',
        nb: '{name} er importert',
        nn: '{name} er importert',
        fi: '{name} tuotu',
        is: '{name} flutt inn',
        fo: '{name} er flutt inn',
        cs: '{name} importováno',
        bg: '{name} е внесено',
        hr: '{name} uvezeno',
        sr: '{name} увезено',
        sl: '{name} uvoženo',
        mk: '{name} е внесено',
        be: '{name} імпартавана',
        bs: '{name} uvezeno',
        hsb: '{name} importowane',
      }),
      importFailed: t({
        ru: 'Не удалось импортировать {name}',
        en: 'Unable to import {name}',
        kk: '{name} импорттау мүмкін болмады',
        de: '{name} konnte nicht importiert werden',
        fr: "Impossible d'importer {name}",
        es: 'No se pudo importar {name}',
        pt: 'Não foi possível importar {name}',
        tr: '{name} içe aktarılamadı',
        uk: 'Не вдалося імпортувати {name}',
        zh: '无法导入 {name}',
        ar: 'تعذّر استيراد {name}',
        pl: 'Nie udało się zaimportować {name}',
        it: 'Impossibile importare {name}',
        sk: 'Súbor {name} sa nepodarilo importovať',
        ja: '{name} をインポートできませんでした',
        ko: '{name}을(를) 가져올 수 없습니다',
        hi: '{name} इंपोर्ट नहीं हो सका',
        nl: '{name} kon niet worden geïmporteerd',
        sv: 'Det gick inte att importera {name}',
        vi: 'Không thể nhập {name}',
        id: 'Tidak dapat mengimpor {name}',
        da: '{name} kunne ikke importeres',
        nb: 'Kunne ikke importere {name}',
        nn: 'Kunne ikkje importere {name}',
        fi: 'Kohdetta {name} ei voitu tuoda',
        is: 'Ekki var hægt að flytja {name} inn',
        fo: '{name} kundi ikki flytast inn',
        cs: 'Nepodařilo se importovat {name}',
        bg: '{name} не можа да се внесе',
        hr: '{name} nije bilo moguće uvesti',
        sr: '{name} није било могуће увезти',
        sl: '{name} ni bilo mogoče uvoziti',
        mk: '{name} не можеше да се внесе',
        be: 'Не ўдалося імпартаваць {name}',
        bs: '{name} nije bilo moguće uvesti',
        hsb: '{name} njeda so importować',
      }),
      browseFailed: t({
        ru: 'Не удалось загрузить варианты. Проверьте учётные данные выше.',
        en: 'Could not load options. Check the credentials above.',
        kk: 'Нұсқаларды жүктеу мүмкін болмады. Жоғарыдағы тіркелгі деректерін тексеріңіз.',
        de: 'Optionen konnten nicht geladen werden. Prüfen Sie die Zugangsdaten oben.',
        fr: 'Impossible de charger les options. Vérifiez les identifiants ci-dessus.',
        es: 'No se pudieron cargar las opciones. Revisa las credenciales de arriba.',
        pt: 'Não foi possível carregar as opções. Verifique as credenciais acima.',
        tr: 'Seçenekler yüklenemedi. Yukarıdaki kimlik bilgilerini kontrol edin.',
        uk: 'Не вдалося завантажити варіанти. Перевірте облікові дані вище.',
        zh: '无法加载选项。请检查上方的凭据。',
        ar: 'تعذّر تحميل الخيارات. تحقّق من بيانات الاعتماد أعلاه.',
        pl: 'Nie udało się wczytać opcji. Sprawdź dane logowania powyżej.',
        it: 'Impossibile caricare le opzioni. Controlla le credenziali qui sopra.',
        sk: 'Možnosti sa nepodarilo načítať. Skontrolujte prihlasovacie údaje vyššie.',
        ja: '選択肢を読み込めませんでした。上の認証情報を確認してください。',
        ko: '옵션을 불러올 수 없습니다. 위의 자격 증명을 확인하세요.',
        hi: 'विकल्प लोड नहीं हो सके। ऊपर दिए क्रेडेंशियल जाँचें।',
        nl: 'Opties konden niet worden geladen. Controleer de inloggegevens hierboven.',
        sv: 'Det gick inte att läsa in alternativen. Kontrollera inloggningsuppgifterna ovan.',
        vi: 'Không thể tải các tùy chọn. Hãy kiểm tra thông tin đăng nhập ở trên.',
        id: 'Tidak dapat memuat opsi. Periksa kredensial di atas.',
        da: 'Indstillingerne kunne ikke indlæses. Kontrollér loginoplysningerne ovenfor.',
        nb: 'Kunne ikke laste alternativene. Kontroller påloggingsdetaljene over.',
        nn: 'Kunne ikkje laste alternativa. Kontroller påloggingsdetaljane over.',
        fi: 'Vaihtoehtoja ei voitu ladata. Tarkista yllä olevat tunnukset.',
        is: 'Ekki var hægt að hlaða valkosti. Athugaðu aðgangsupplýsingarnar hér fyrir ofan.',
        fo: 'Møguleikarnir kundu ikki lesast inn. Kanna atgongdarupplýsingarnar omanfyri.',
        cs: 'Nepodařilo se načíst možnosti. Zkontrolujte přihlašovací údaje výše.',
        bg: 'Опциите не можаха да се заредят. Проверете данните за достъп по-горе.',
        hr: 'Mogućnosti nije bilo moguće učitati. Provjerite podatke za pristup iznad.',
        sr: 'Могућности није било могуће учитати. Проверите податке за приступ изнад.',
        sl: 'Možnosti ni bilo mogoče naložiti. Preverite podatke za dostop zgoraj.',
        mk: 'Опциите не можеа да се вчитаат. Проверете ги податоците за пристап погоре.',
        be: 'Не ўдалося загрузіць варыянты. Праверце даныя доступу вышэй.',
        bs: 'Mogućnosti nije bilo moguće učitati. Provjerite podatke za pristup iznad.',
        hsb: 'Opcije njedachu so začitać. Přepruwujće přistupne daty horjeka.',
      }),
      syncComplete: t({
        ru: 'Синхронизация завершена: {count}',
        en: 'Sync complete: {count}',
        kk: 'Синхрондау аяқталды: {count}',
        de: 'Synchronisierung abgeschlossen: {count}',
        fr: 'Synchronisation terminée : {count}',
        es: 'Sincronización completada: {count}',
        pt: 'Sincronização concluída: {count}',
        tr: 'Eşitleme tamamlandı: {count}',
        uk: 'Синхронізацію завершено: {count}',
        zh: '同步完成：{count}',
        ar: 'اكتملت المزامنة: {count}',
        pl: 'Synchronizacja zakończona: {count}',
        it: 'Sincronizzazione completata: {count}',
        sk: 'Synchronizácia dokončená: {count}',
        ja: '同期完了: {count}',
        ko: '동기화 완료: {count}',
        hi: 'सिंक पूरा हुआ: {count}',
        nl: 'Synchronisatie voltooid: {count}',
        sv: 'Synkroniseringen är klar: {count}',
        vi: 'Đồng bộ hoàn tất: {count}',
        id: 'Sinkronisasi selesai: {count}',
        da: 'Synkroniseringen er færdig: {count}',
        nb: 'Synkroniseringen er ferdig: {count}',
        nn: 'Synkroniseringa er ferdig: {count}',
        fi: 'Synkronointi valmis: {count}',
        is: 'Samstillingu lokið: {count}',
        fo: 'Samstillingin er liðug: {count}',
        cs: 'Synchronizace hotová: {count}',
        bg: 'Синхронизацията завърши: {count}',
        hr: 'Sinkronizacija je završena: {count}',
        sr: 'Синхронизација је завршена: {count}',
        sl: 'Sinhronizacija je končana: {count}',
        mk: 'Синхронизацијата е завршена: {count}',
        be: 'Сінхранізацыя завершана: {count}',
        bs: 'Sinhronizacija je završena: {count}',
        hsb: 'Synchronizacija dokónčena: {count}',
      }),
      syncFailed: t({
        ru: 'Не удалось синхронизировать',
        en: 'Sync failed',
        kk: 'Синхрондау сәтсіз аяқталды',
        de: 'Synchronisierung fehlgeschlagen',
        fr: 'Échec de la synchronisation',
        es: 'Error de sincronización',
        pt: 'Falha na sincronização',
        tr: 'Eşitleme başarısız',
        uk: 'Не вдалося синхронізувати',
        zh: '同步失败',
        ar: 'فشلت المزامنة',
        pl: 'Synchronizacja nie powiodła się',
        it: 'Sincronizzazione non riuscita',
        sk: 'Synchronizácia zlyhala',
        ja: '同期に失敗しました',
        ko: '동기화 실패',
        hi: 'सिंक विफल रहा',
        nl: 'Synchronisatie mislukt',
        sv: 'Synkroniseringen misslyckades',
        vi: 'Đồng bộ thất bại',
        id: 'Sinkronisasi gagal',
        da: 'Synkroniseringen mislykkedes',
        nb: 'Synkroniseringen mislyktes',
        nn: 'Synkroniseringa mislukkast',
        fi: 'Synkronointi epäonnistui',
        is: 'Samstilling mistókst',
        fo: 'Samstillingin miseydnaðist',
        cs: 'Synchronizace se nezdařila',
        bg: 'Синхронизацията не успя',
        hr: 'Sinkronizacija nije uspjela',
        sr: 'Синхронизација није успела',
        sl: 'Sinhronizacija ni uspela',
        mk: 'Синхронизацијата не успеа',
        be: 'Сінхранізацыя не ўдалася',
        bs: 'Sinhronizacija nije uspjela',
        hsb: 'Synchronizacija je so njeporadźiła',
      }),
    },
  },
} satisfies Dictionary;

export default content;
