import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'integrationsPage',
  content: {
    title: t({
      ru: 'Интеграции',
      en: 'Integrations',
      kk: 'Интеграциялар',
      de: 'Integrationen',
      fr: 'Intégrations',
      es: 'Integraciones',
      pt: 'Integrações',
      tr: 'Entegrasyonlar',
      uk: 'Інтеграції',
      zh: '集成',
      pl: 'Integracje',
      it: 'Integrazioni',
      sk: 'Integrácie',
      ja: 'インテグレーション',
      ko: '통합',
      hi: 'एकीकरण',
      nl: 'Integraties',
      sv: 'Integrationer',
      vi: 'Tích hợp',
      id: 'Integrasi',
      da: 'Integrationer',
      nb: 'Integrasjoner',
      nn: 'Integrasjonar',
      fi: 'Integraatiot',
      is: 'Samþættingar',
      fo: 'Samanknýti',
      cs: 'Integrace',
      bg: 'Интеграции',
      hr: 'Integracije',
      sr: 'Интеграције',
      sl: 'Integracije',
      mk: 'Интеграции',
      be: 'Інтэграцыі',
      bs: 'Integracije',
      hsb: 'Integracije',
    }),
    subtitle: t({
      ru: 'Подключайте внешние сервисы и автоматизируйте обмен данными.',
      en: 'Connect external services and automate data exchange.',
      kk: 'Сыртқы сервистерді қосып, деректер алмасуын автоматтандырыңыз.',
      de: 'Verbinden Sie externe Dienste und automatisieren Sie den Datenaustausch.',
      fr: 'Connectez des services externes et automatisez les échanges de données.',
      es: 'Conecta servicios externos y automatiza el intercambio de datos.',
      pt: 'Conecte serviços externos e automatize a troca de dados.',
      tr: 'Harici hizmetleri bağlayın ve veri alışverişini otomatikleştirin.',
      uk: 'Підключайте зовнішні сервіси та автоматизуйте обмін даними.',
      zh: '连接外部服务并自动化数据交换。',
      pl: 'Połącz zewnętrzne usługi i zautomatyzuj wymianę danych.',
      it: 'Connetti servizi esterni e automatizza lo scambio di dati.',
      sk: 'Pripojte externé služby a automatizujte výmenu údajov.',
      ja: '外部サービスを接続してデータ交換を自動化します。',
      ko: '외부 서비스를 연결하고 데이터 교환을 자동화하세요.',
      hi: 'बाहरी सेवाओं को कनेक्ट करें और डेटा एक्सचेंज को स्वचालित करें।',
      nl: 'Verbind externe diensten en automatiseer gegevensuitwisseling.',
      sv: 'Anslut externa tjänster och automatisera datautbyte.',
      vi: 'Kết nối các dịch vụ bên ngoài và tự động hóa trao đổi dữ liệu.',
      id: 'Hubungkan layanan eksternal dan otomatiskan pertukaran data.',
      da: 'Forbind eksterne tjenester, og automatisér dataudveksling.',
      nb: 'Koble til eksterne tjenester og automatiser datautveksling.',
      nn: 'Kople til eksterne tenester og automatiser datautveksling.',
      fi: 'Yhdistä ulkoisia palveluita ja automatisoi tiedonvaihto.',
      is: 'Tengdu utanaðkomandi þjónustur og gerðu gagnaskipti sjálfvirk.',
      fo: 'Set uttanhýsis tænastur í samband og ger dátuskifti sjálvvirkandi.',
      cs: 'Připojte externí služby a automatizujte výměnu dat.',
      bg: 'Свържете външни услуги и автоматизирайте обмена на данни.',
      hr: 'Povežite vanjske usluge i automatizirajte izmjenu podataka.',
      sr: 'Повежите спољне услуге и аутоматизујте измену података.',
      sl: 'Povežite zunanje storitve in avtomatizirajte izmenjavo podatkov.',
      mk: 'Поврзете надворешни услуги и автоматизирајте ја размената на податоци.',
      be: 'Падлучайце вонкавыя сэрвісы і аўтаматызуйце абмен данымі.',
      bs: 'Povežite vanjske usluge i automatizujte izmjenu podataka.',
      hsb: 'Zwjazajće eksterne posłužby a awtomatizujće wuměnu datow.',
    }),
    sections: {
      connected: t({
        ru: 'Подключено',
        en: 'Connected',
        kk: 'Қосылған',
        de: 'Verbunden',
        fr: 'Connecté',
        es: 'Conectado',
        pt: 'Conectado',
        tr: 'Bağlı',
        uk: 'Підключено',
        zh: '已连接',
        pl: 'Połączone',
        it: 'Connesso',
        sk: 'Pripojené',
        ja: '接続済み',
        ko: '연결됨',
        hi: 'कनेक्टेड',
        nl: 'Verbonden',
        sv: 'Ansluten',
        vi: 'Đã kết nối',
        id: 'Terhubung',
        da: 'Forbundet',
        nb: 'Tilkoblet',
        nn: 'Tilkopla',
        fi: 'Yhdistetty',
        is: 'Tengt',
        fo: 'Sambundið',
        cs: 'Připojeno',
        bg: 'Свързано',
        hr: 'Povezano',
        sr: 'Повезано',
        sl: 'Povezano',
        mk: 'Поврзано',
        be: 'Падлучана',
        bs: 'Povezano',
        hsb: 'Zwjazane',
      }),
      available: t({
        ru: 'Доступно к подключению',
        en: 'Available',
        kk: 'Қолжетімді',
        de: 'Verfügbar',
        fr: 'Disponible',
        es: 'Disponible',
        pt: 'Disponível',
        tr: 'Mevcut',
        uk: 'Доступно',
        zh: '可用',
        pl: 'Dostępne',
        it: 'Disponibile',
        sk: 'Dostupné',
        ja: '利用可能',
        ko: '사용 가능',
        hi: 'उपलब्ध',
        nl: 'Beschikbaar',
        sv: 'Tillgänglig',
        vi: 'Có sẵn',
        id: 'Tersedia',
        da: 'Tilgængelige',
        nb: 'Tilgjengelige',
        nn: 'Tilgjengelege',
        fi: 'Saatavilla',
        is: 'Í boði',
        fo: 'Tøkar',
        cs: 'Dostupné',
        bg: 'Налични',
        hr: 'Dostupni',
        sr: 'Доступни',
        sl: 'Na voljo',
        mk: 'Достапни',
        be: 'Даступныя',
        bs: 'Dostupni',
        hsb: 'K dispoziciji',
      }),
    },
    banner: t({
      ru: 'Начните отсюда: подключите Gmail или Google Диск для автоматического импорта чеков и выписок.',
      en: 'Start here: Connect Gmail or Google Drive to automatically import receipts and statements.',
      kk: 'Осыдан бастаңыз: түбіртектер мен үзінділерді автоматты түрде импорттау үшін Gmail немесе Google Drive қосыңыз.',
      de: 'Starten Sie hier: Verbinden Sie Gmail oder Google Drive, um Belege und Kontoauszüge automatisch zu importieren.',
      fr: 'Commencez ici : connectez Gmail ou Google Drive pour importer automatiquement les reçus et relevés.',
      es: 'Empieza aquí: conecta Gmail o Google Drive para importar automáticamente recibos y extractos.',
      pt: 'Comece aqui: conecte o Gmail ou o Google Drive para importar automaticamente recibos e extratos.',
      tr: "Buradan başlayın: Makbuz ve ekstreleri otomatik olarak içe aktarmak için Gmail veya Google Drive'ı bağlayın.",
      uk: 'Почніть тут: підключіть Gmail або Google Диск для автоматичного імпорту чеків та виписок.',
      zh: '从这里开始：连接 Gmail 或 Google Drive 以自动导入收据和账单。',
      pl: 'Zacznij tutaj: połącz Gmail lub Google Drive, aby automatycznie importować paragony i wyciągi.',
      it: 'Inizia qui: collega Gmail o Google Drive per importare automaticamente ricevute ed estratti conto.',
      sk: 'Začnite tu: pripojte Gmail alebo Google Drive na automatický import účteniek a výpisov.',
      ja: 'ここから始めましょう：GmailまたはGoogle Driveを接続してレシートや明細を自動インポートします。',
      ko: '여기서 시작하세요: Gmail 또는 Google Drive를 연결하여 영수증과 명세서를 자동으로 가져오세요.',
      hi: 'यहां से शुरू करें: रसीदें और विवरण स्वचालित रूप से आयात करने के लिए Gmail या Google Drive कनेक्ट करें।',
      nl: 'Begin hier: verbind Gmail of Google Drive om automatisch bonnen en afschriften te importeren.',
      sv: 'Börja här: Anslut Gmail eller Google Drive för att automatiskt importera kvitton och kontoutdrag.',
      vi: 'Bắt đầu tại đây: Kết nối Gmail hoặc Google Drive để tự động nhập biên lai và bản sao kê.',
      id: 'Mulai di sini: Hubungkan Gmail atau Google Drive untuk mengimpor tanda terima dan laporan secara otomatis.',
      da: 'Start her: Forbind Gmail eller Google Drive for automatisk at importere kvitteringer og kontoudtog.',
      nb: 'Start her: Koble til Gmail eller Google Drive for å importere kvitteringer og kontoutskrifter automatisk.',
      nn: 'Start her: Kople til Gmail eller Google Drive for å importere kvitteringar og kontoutskrifter automatisk.',
      fi: 'Aloita tästä: yhdistä Gmail tai Google Drive, niin kuitit ja tiliotteet tuodaan automaattisesti.',
      is: 'Byrjaðu hér: tengdu Gmail eða Google Drive til að flytja kvittanir og yfirlit inn sjálfkrafa.',
      fo: 'Byrja her: set Gmail ella Google Drive í samband fyri at flyta kvittanir og kontoyvirlit inn sjálvvirkandi.',
      cs: 'Začněte zde: připojte Gmail nebo Google Drive a účtenky i výpisy se budou importovat automaticky.',
      bg: 'Започнете оттук: свържете Gmail или Google Drive, за да се внасят касовите бележки и извлеченията автоматично.',
      hr: 'Počnite ovdje: povežite Gmail ili Google Drive da se računi i izvodi uvoze automatski.',
      sr: 'Почните овде: повежите Gmail или Google Drive да се рачуни и изводи увозе аутоматски.',
      sl: 'Začnite tukaj: povežite Gmail ali Google Drive, da se računi in izpiski uvažajo samodejno.',
      mk: 'Почнете тука: поврзете Gmail или Google Drive за сметките и извадоците да се внесуваат автоматски.',
      be: 'Пачніце тут: падлучыце Gmail або Google Drive, каб квітанцыі і выпіскі імпартаваліся аўтаматычна.',
      bs: 'Počnite ovdje: povežite Gmail ili Google Drive da se računi i izvodi uvoze automatski.',
      hsb: 'Započńće tu: zwjazajće Gmail abo Google Drive, zo bychu so kwitowanki a wupisy awtomatisce importowali.',
    }),
    recommendedBadge: t({
      ru: 'Рекомендуется',
      en: 'Recommended',
      kk: 'Ұсынылады',
      de: 'Empfohlen',
      fr: 'Recommandé',
      es: 'Recomendado',
      pt: 'Recomendado',
      tr: 'Önerilen',
      uk: 'Рекомендовано',
      zh: '推荐',
      pl: 'Polecane',
      it: 'Consigliato',
      sk: 'Odporúčané',
      ja: 'おすすめ',
      ko: '추천',
      hi: 'अनुशंसित',
      nl: 'Aanbevolen',
      sv: 'Rekommenderad',
      vi: 'Được đề xuất',
      id: 'Direkomendasikan',
      da: 'Anbefalet',
      nb: 'Anbefalt',
      nn: 'Tilrådd',
      fi: 'Suositeltu',
      is: 'Ráðlagt',
      fo: 'Ráðlagt',
      cs: 'Doporučeno',
      bg: 'Препоръчан',
      hr: 'Preporučeno',
      sr: 'Препоручено',
      sl: 'Priporočeno',
      mk: 'Препорачано',
      be: 'Рэкамендавана',
      bs: 'Preporučeno',
      hsb: 'Doporučene',
    }),
    empty: {
      connected: t({
        ru: 'Пока нет активных интеграций.',
        en: 'No active integrations yet.',
        kk: 'Әзірше белсенді интеграциялар жоқ.',
        de: 'Noch keine aktiven Integrationen.',
        fr: "Aucune intégration active pour l'instant.",
        es: 'Aún no hay integraciones activas.',
        pt: 'Nenhuma integração ativa ainda.',
        tr: 'Henüz aktif entegrasyon yok.',
        uk: 'Поки немає активних інтеграцій.',
        zh: '暂无活跃的集成。',
        pl: 'Brak aktywnych integracji.',
        it: 'Nessuna integrazione attiva ancora.',
        sk: 'Zatiaľ žiadne aktívne integrácie.',
        ja: 'まだアクティブな統合はありません。',
        ko: '아직 활성화된 통합이 없습니다.',
        hi: 'अभी तक कोई सक्रिय एकीकरण नहीं है।',
        nl: 'Nog geen actieve integraties.',
        sv: 'Inga aktiva integrationer ännu.',
        vi: 'Chưa có tích hợp hoạt động nào.',
        id: 'Belum ada integrasi aktif.',
        da: 'Der er endnu ingen aktive integrationer.',
        nb: 'Ingen aktive integrasjoner ennå.',
        nn: 'Ingen aktive integrasjonar enno.',
        fi: 'Ei vielä aktiivisia integraatioita.',
        is: 'Engar virkar samþættingar enn.',
        fo: 'Eingar virknar samanknýti enn.',
        cs: 'Zatím žádné aktivní integrace.',
        bg: 'Още няма активни интеграции.',
        hr: 'Još nema aktivnih integracija.',
        sr: 'Још нема активних интеграција.',
        sl: 'Zaenkrat ni aktivnih integracij.',
        mk: 'Сè уште нема активни интеграции.',
        be: 'Пакуль няма актыўных інтэграцый.',
        bs: 'Još nema aktivnih integracija.',
        hsb: 'Hišće žane aktiwne integracije.',
      }),
      available: t({
        ru: 'Нет доступных интеграций.',
        en: 'No integrations available.',
        kk: 'Қолжетімді интеграциялар жоқ.',
        de: 'Keine Integrationen verfügbar.',
        fr: 'Aucune intégration disponible.',
        es: 'No hay integraciones disponibles.',
        pt: 'Nenhuma integração disponível.',
        tr: 'Mevcut entegrasyon yok.',
        uk: 'Немає доступних інтеграцій.',
        zh: '没有可用的集成。',
        pl: 'Brak dostępnych integracji.',
        it: 'Nessuna integrazione disponibile.',
        sk: 'Nie sú dostupné žiadne integrácie.',
        ja: '利用可能な統合はありません。',
        ko: '사용 가능한 통합이 없습니다.',
        hi: 'कोई एकीकरण उपलब्ध नहीं है।',
        nl: 'Geen integraties beschikbaar.',
        sv: 'Inga integrationer tillgängliga.',
        vi: 'Không có tích hợp nào khả dụng.',
        id: 'Tidak ada integrasi yang tersedia.',
        da: 'Der er ingen tilgængelige integrationer.',
        nb: 'Ingen integrasjoner er tilgjengelige.',
        nn: 'Ingen integrasjonar er tilgjengelege.',
        fi: 'Integraatioita ei ole saatavilla.',
        is: 'Engar samþættingar í boði.',
        fo: 'Eingi samanknýti tøk.',
        cs: 'Žádné integrace nejsou dostupné.',
        bg: 'Няма налични интеграции.',
        hr: 'Nema dostupnih integracija.',
        sr: 'Нема доступних интеграција.',
        sl: 'Na voljo ni nobene integracije.',
        mk: 'Нема достапни интеграции.',
        be: 'Няма даступных інтэграцый.',
        bs: 'Nema dostupnih integracija.',
        hsb: 'Žane integracije k dispoziciji.',
      }),
    },
    categories: {
      ai: t({
        ru: 'ИИ',
        en: 'AI',
        kk: 'ЖИ',
        de: 'KI',
        fr: 'IA',
        es: 'IA',
        pt: 'IA',
        tr: 'Yapay zeka',
        uk: 'ШІ',
        zh: 'AI',
        pl: 'AI',
        it: 'IA',
        sk: 'AI',
        ja: 'AI',
        ko: 'AI',
        hi: 'AI',
        nl: 'AI',
        sv: 'AI',
        vi: 'AI',
        id: 'AI',
        da: 'AI',
        nb: 'KI',
        nn: 'KI',
        fi: 'Tekoäly',
        is: 'Gervigreind',
        fo: 'AI',
        cs: 'AI',
        bg: 'AI',
        hr: 'AI',
        sr: 'AI',
        sl: 'UI',
        mk: 'АИ',
        be: 'ШІ',
        bs: 'AI',
        hsb: 'AI',
      }),
      application: t({
        ru: 'Приложение',
        en: 'Application',
        kk: 'Қолданба',
        de: 'Anwendung',
        fr: 'Application',
        es: 'Aplicación',
        pt: 'Aplicativo',
        tr: 'Uygulama',
        uk: 'Застосунок',
        zh: '应用',
        pl: 'Aplikacja',
        it: 'Applicazione',
        sk: 'Aplikácia',
        ja: 'アプリケーション',
        ko: '애플리케이션',
        hi: 'एप्लिकेशन',
        nl: 'Applicatie',
        sv: 'Applikation',
        vi: 'Ứng dụng',
        id: 'Aplikasi',
        da: 'Applikation',
        nb: 'Applikasjon',
        nn: 'Applikasjon',
        fi: 'Sovellus',
        is: 'Forrit',
        fo: 'Appur',
        cs: 'Aplikace',
        bg: 'Приложение',
        hr: 'Aplikacija',
        sr: 'Апликација',
        sl: 'Aplikacija',
        mk: 'Апликација',
        be: 'Праграма',
        bs: 'Aplikacija',
        hsb: 'Aplikacija',
      }),
      storage: t({
        ru: 'Файловые хранилища',
        en: 'Storage',
        kk: 'Файл қоймалары',
        de: 'Datenspeicher',
        fr: 'Stockage',
        es: 'Almacenamiento',
        pt: 'Armazenamento',
        tr: 'Depolama',
        uk: 'Файлові сховища',
        zh: '存储',
        pl: 'Przechowywanie',
        it: 'Archiviazione',
        sk: 'Úložisko',
        ja: 'ストレージ',
        ko: '스토리지',
        hi: 'स्टोरेज',
        nl: 'Opslag',
        sv: 'Lagring',
        vi: 'Lưu trữ',
        id: 'Penyimpanan',
        da: 'Lagring',
        nb: 'Lagring',
        nn: 'Lagring',
        fi: 'Tallennus',
        is: 'Geymsla',
        fo: 'Goymsla',
        cs: 'Úložiště',
        bg: 'Хранилище',
        hr: 'Pohrana',
        sr: 'Складиште',
        sl: 'Shramba',
        mk: 'Складиште',
        be: 'Сховішча',
        bs: 'Pohrana',
        hsb: 'Skład',
      }),
      email: t({
        ru: 'Почта',
        en: 'Email',
        kk: 'Пошта',
        de: 'E-Mail',
        fr: 'E-mail',
        es: 'Correo electrónico',
        pt: 'E-mail',
        tr: 'E-posta',
        uk: 'Пошта',
        zh: '邮件',
        pl: 'Poczta',
        it: 'E-mail',
        sk: 'E-mail',
        ja: 'メール',
        ko: '이메일',
        hi: 'ईमेल',
        nl: 'E-mail',
        sv: 'E-post',
        vi: 'Email',
        id: 'Surel',
        da: 'E-mail',
        nb: 'E-post',
        nn: 'E-post',
        fi: 'Sähköposti',
        is: 'Netfang',
        fo: 'T-postur',
        cs: 'E-mail',
        bg: 'Имейл',
        hr: 'E-pošta',
        sr: 'Е-пошта',
        sl: 'E-naslov',
        mk: 'Е-пошта',
        be: 'Эл. пошта',
        bs: 'E-pošta',
        hsb: 'E-mejl',
      }),
      bank: t({
        ru: 'Банк',
        en: 'Bank',
        kk: 'Банк',
        de: 'Bank',
        fr: 'Banque',
        es: 'Banco',
        pt: 'Banco',
        tr: 'Banka',
        uk: 'Банк',
        zh: '银行',
        pl: 'Bank',
        it: 'Banca',
        sk: 'Banka',
        ja: '銀行',
        ko: '은행',
        hi: 'बैंक',
        nl: 'Bank',
        sv: 'Bank',
        vi: 'Ngân hàng',
        id: 'Bank',
        da: 'Bank',
        nb: 'Bank',
        nn: 'Bank',
        fi: 'Pankki',
        is: 'Banki',
        fo: 'Banki',
        cs: 'Banka',
        bg: 'Банка',
        hr: 'Banka',
        sr: 'Банка',
        sl: 'Banka',
        mk: 'Банка',
        be: 'Банк',
        bs: 'Banka',
        hsb: 'Banka',
      }),
      messaging: t({
        ru: 'Мессенджеры',
        en: 'Messaging',
        kk: 'Мессенджерлер',
        de: 'Messenger',
        fr: 'Messagerie',
        es: 'Mensajería',
        pt: 'Mensagens',
        tr: 'Mesajlaşma',
        uk: 'Месенджери',
        zh: '消息',
        pl: 'Komunikatory',
        it: 'Messaggistica',
        sk: 'Správy',
        ja: 'メッセージング',
        ko: '메시징',
        hi: 'मैसेजिंग',
        nl: 'Berichtenuitwisseling',
        sv: 'Meddelanden',
        vi: 'Nhắn tin',
        id: 'Pesan',
        da: 'Beskeder',
        nb: 'Meldinger',
        nn: 'Meldingar',
        fi: 'Viestintä',
        is: 'Skeyti',
        fo: 'Boð',
        cs: 'Zprávy',
        bg: 'Съобщения',
        hr: 'Poruke',
        sr: 'Поруке',
        sl: 'Sporočila',
        mk: 'Пораки',
        be: 'Паведамленні',
        bs: 'Poruke',
        hsb: 'Powěsće',
      }),
    },
    searchPlaceholder: t({
      ru: 'Поиск интеграций...',
      en: 'Search integrations...',
      kk: 'Интеграцияларды іздеу...',
      de: 'Integrationen suchen...',
      fr: 'Rechercher des intégrations...',
      es: 'Buscar integraciones...',
      pt: 'Pesquisar integrações...',
      tr: 'Entegrasyon ara...',
      uk: 'Пошук інтеграцій...',
      zh: '搜索集成...',
      pl: 'Szukaj integracji...',
      it: 'Cerca integrazioni...',
      sk: 'Hľadať integrácie...',
      ja: '統合を検索...',
      ko: '통합 검색...',
      hi: 'एकीकरण खोजें...',
      nl: 'Integraties zoeken...',
      sv: 'Sök integrationer...',
      vi: 'Tìm kiếm tích hợp...',
      id: 'Cari integrasi...',
      da: 'Søg i integrationer ...',
      nb: 'Søk i integrasjoner ...',
      nn: 'Søk i integrasjonar ...',
      fi: 'Etsi integraatioita ...',
      is: 'Leita í samþættingum ...',
      fo: 'Leita í samanknýtum ...',
      cs: 'Hledat integrace ...',
      bg: 'Търсене на интеграции ...',
      hr: 'Traži integracije ...',
      sr: 'Тражи интеграције ...',
      sl: 'Iskanje integracij ...',
      mk: 'Барај интеграции ...',
      be: 'Пошук інтэграцый ...',
      bs: 'Traži integracije ...',
      hsb: 'Integracije pytać ...',
    }),
    noResults: t({
      ru: 'Ничего не найдено',
      en: 'Nothing found',
      kk: 'Ештеңе табылмады',
      de: 'Nichts gefunden',
      fr: 'Aucun résultat',
      es: 'No se encontró nada',
      pt: 'Nada encontrado',
      tr: 'Hiçbir şey bulunamadı',
      uk: 'Нічого не знайдено',
      zh: '未找到任何内容',
      pl: 'Nic nie znaleziono',
      it: 'Nessun risultato',
      sk: 'Nič sa nenašlo',
      ja: '何も見つかりません',
      ko: '결과 없음',
      hi: 'कुछ नहीं मिला',
      nl: 'Niets gevonden',
      sv: 'Inget hittades',
      vi: 'Không tìm thấy gì',
      id: 'Tidak ditemukan',
      da: 'Intet fundet',
      nb: 'Ingenting funnet',
      nn: 'Ingenting funne',
      fi: 'Ei löytynyt mitään',
      is: 'Ekkert fannst',
      fo: 'Einki funnið',
      cs: 'Nic nenalezeno',
      bg: 'Няма намерено нищо',
      hr: 'Nije nađeno ništa',
      sr: 'Није нађено ништа',
      sl: 'Ni najdeno nič',
      mk: 'Не е најдено ништо',
      be: 'Нічога не знойдзена',
      bs: 'Nije nađeno ništa',
      hsb: 'Ničo namakane',
    }),
    noResultsDescription: t({
      ru: 'По запросу «{{query}}» нет подходящих интеграций.',
      en: 'No matching integrations found for "{{query}}".',
      kk: '«{{query}}» сұрауы бойынша сәйкес интеграциялар табылмады.',
      de: 'Keine passenden Integrationen für „{{query}}" gefunden.',
      fr: 'Aucune intégration correspondante trouvée pour « {{query}} ».',
      es: 'No se encontraron integraciones para "{{query}}".',
      pt: 'Nenhuma integração encontrada para "{{query}}".',
      tr: '"{{query}}" için eşleşen entegrasyon bulunamadı.',
      uk: 'За запитом «{{query}}» не знайдено відповідних інтеграцій.',
      zh: '未找到与"{{query}}"匹配的集成。',
      pl: 'Nie znaleziono integracji pasujących do „{{query}}".',
      it: 'Nessuna integrazione trovata per "{{query}}".',
      sk: 'Pre "{{query}}" sa nenašli žiadne zodpovedajúce integrácie.',
      ja: '"{{query}}"に一致する統合が見つかりませんでした。',
      ko: '"{{query}}"에 일치하는 통합이 없습니다.',
      hi: '"{{query}}" के लिए कोई मेल खाने वाला एकीकरण नहीं मिला।',
      nl: 'Geen overeenkomende integraties gevonden voor "{{query}}".',
      sv: 'Inga matchande integrationer hittades för "{{query}}".',
      vi: 'Không tìm thấy tích hợp nào khớp với "{{query}}".',
      id: 'Tidak ada integrasi yang cocok dengan "{{query}}".',
      da: 'Der blev ikke fundet integrationer, der matcher "{{query}}".',
      nb: 'Fant ingen integrasjoner som samsvarer med "{{query}}".',
      nn: 'Fann ingen integrasjonar som samsvarar med "{{query}}".',
      fi: 'Hakuun "{{query}}" ei löytynyt integraatioita.',
      is: 'Engar samþættingar fundust sem passa við "{{query}}".',
      fo: 'Eingi samanknýti funnin, sum passa til "{{query}}".',
      cs: 'Pro "{{query}}" nebyly nalezeny žádné integrace.',
      bg: 'Няма намерени интеграции, които да съответстват на "{{query}}".',
      hr: 'Nema integracija koje odgovaraju "{{query}}".',
      sr: 'Нема интеграција које одговарају "{{query}}".',
      sl: 'Ni integracij, ki bi ustrezale "{{query}}".',
      mk: 'Нема интеграции што одговараат на "{{query}}".',
      be: 'Няма інтэграцый, якія адпавядаюць "{{query}}".',
      bs: 'Nema integracija koje odgovaraju "{{query}}".',
      hsb: 'Žane integracije namakane, kotrež "{{query}}" wotpowěduja.',
    }),
    resetSearch: t({
      ru: 'Сбросить поиск',
      en: 'Reset search',
      kk: 'Іздеуді қалпына келтіру',
      de: 'Suche zurücksetzen',
      fr: 'Réinitialiser la recherche',
      es: 'Restablecer búsqueda',
      pt: 'Redefinir busca',
      tr: 'Aramayı sıfırla',
      uk: 'Скинути пошук',
      zh: '重置搜索',
      pl: 'Resetuj wyszukiwanie',
      it: 'Reimposta ricerca',
      sk: 'Zrušiť vyhľadávanie',
      ja: '検索をリセット',
      ko: '검색 초기화',
      hi: 'खोज रीसेट करें',
      nl: 'Zoekopdracht resetten',
      sv: 'Återställ sökning',
      vi: 'Đặt lại tìm kiếm',
      id: 'Atur ulang pencarian',
      da: 'Nulstil søgningen',
      nb: 'Nullstill søket',
      nn: 'Nullstill søket',
      fi: 'Tyhjennä haku',
      is: 'Endurstilla leit',
      fo: 'Nullstilla leitingina',
      cs: 'Zrušit hledání',
      bg: 'Изчистване на търсенето',
      hr: 'Očisti traženje',
      sr: 'Очисти тражење',
      sl: 'Počisti iskanje',
      mk: 'Исчисти го барањето',
      be: 'Ачысціць пошук',
      bs: 'Očisti traženje',
      hsb: 'Pytanje wuprózdnić',
    }),
    setUp: t({
      ru: 'Настроить',
      en: 'Set up',
      kk: 'Баптау',
      de: 'Einrichten',
      fr: 'Configurer',
      es: 'Configurar',
      pt: 'Configurar',
      tr: 'Kur',
      uk: 'Налаштувати',
      zh: '设置',
      pl: 'Skonfiguruj',
      it: 'Configura',
      sk: 'Nastaviť',
      ja: '設定する',
      ko: '설정하기',
      hi: 'सेट अप करें',
      nl: 'Instellen',
      sv: 'Konfigurera',
      vi: 'Thiết lập',
      id: 'Siapkan',
      da: 'Opsæt',
      nb: 'Sett opp',
      nn: 'Set opp',
      fi: 'Ota käyttöön',
      is: 'Setja upp',
      fo: 'Set upp',
      cs: 'Nastavit',
      bg: 'Настройване',
      hr: 'Postavi',
      sr: 'Постави',
      sl: 'Nastavi',
      mk: 'Постави',
      be: 'Наладзіць',
      bs: 'Postavi',
      hsb: 'Nastajić',
    }),
    nothingMatches: t({
      ru: 'Ничего не найдено по запросу «{query}».',
      en: 'Nothing matches "{query}".',
      kk: '«{query}» бойынша ештеңе табылмады.',
      de: 'Keine Treffer für „{query}“.',
      fr: 'Aucun résultat pour « {query} ».',
      es: 'Nada coincide con «{query}».',
      pt: 'Nada corresponde a "{query}".',
      tr: '"{query}" ile eşleşen sonuç yok.',
      uk: 'Нічого не знайдено за запитом «{query}».',
      zh: '没有与“{query}”匹配的结果。',
      pl: 'Brak wyników dla „{query}”.',
      it: 'Nessun risultato per "{query}".',
      sk: 'Pre „{query}“ sa nič nenašlo.',
      ja: '「{query}」に一致するものはありません。',
      ko: '"{query}"와(과) 일치하는 항목이 없습니다.',
      hi: '"{query}" से कुछ मेल नहीं खाता।',
      nl: 'Geen resultaten voor "{query}".',
      sv: 'Inget matchar "{query}".',
      vi: 'Không có kết quả phù hợp với "{query}".',
      id: 'Tidak ada yang cocok dengan "{query}".',
      da: 'Intet matcher "{query}".',
      nb: 'Ingenting samsvarer med "{query}".',
      nn: 'Ingenting samsvarar med "{query}".',
      fi: 'Mikään ei vastaa hakua "{query}".',
      is: 'Ekkert passar við "{query}".',
      fo: 'Einki passar til "{query}".',
      cs: 'Nic neodpovídá "{query}".',
      bg: 'Нищо не съответства на "{query}".',
      hr: 'Ništa ne odgovara "{query}".',
      sr: 'Ништа не одговара "{query}".',
      sl: 'Nič ne ustreza "{query}".',
      mk: 'Ништо не одговара на "{query}".',
      be: 'Нічога не адпавядае "{query}".',
      bs: 'Ništa ne odgovara "{query}".',
      hsb: 'Ničo njewotpowěduje "{query}".',
    }),
    docs: t({
      ru: 'Документация',
      en: 'Docs',
      kk: 'Құжаттама',
      de: 'Dokumentation',
      fr: 'Documentation',
      es: 'Documentación',
      pt: 'Documentação',
      tr: 'Belgeler',
      uk: 'Документація',
      zh: '文档',
      pl: 'Dokumentacja',
      it: 'Documentazione',
      sk: 'Dokumentácia',
      ja: 'ドキュメント',
      ko: '문서',
      hi: 'दस्तावेज़',
      nl: 'Documentatie',
      sv: 'Dokumentation',
      vi: 'Tài liệu',
      id: 'Dokumentasi',
      da: 'Dokumentation',
      nb: 'Dokumentasjon',
      nn: 'Dokumentasjon',
      fi: 'Dokumentaatio',
      is: 'Leiðbeiningar',
      fo: 'Skjalfesting',
      cs: 'Dokumentace',
      bg: 'Документация',
      hr: 'Dokumentacija',
      sr: 'Документација',
      sl: 'Dokumentacija',
      mk: 'Документација',
      be: 'Дакументацыя',
      bs: 'Dokumentacija',
      hsb: 'Dokumentacija',
    }),
    cards: {
      dropbox: {
        description: t({
          ru: 'Синхронизируйте выписки с Dropbox и импортируйте файлы за пару кликов.',
          en: 'Sync statements with Dropbox and import files in a few clicks.',
          kk: 'Үзінділерді Dropbox-пен синхрондап, файлдарды оңай импорттаңыз.',
          de: 'Synchronisieren Sie Kontoauszüge mit Dropbox und importieren Sie Dateien mit wenigen Klicks.',
          fr: 'Synchronisez les relevés avec Dropbox et importez des fichiers en quelques clics.',
          es: 'Sincroniza extractos con Dropbox e importa archivos en pocos clics.',
          pt: 'Sincronize extratos com o Dropbox e importe arquivos em poucos cliques.',
          tr: 'Ekstreleri Dropbox ile senkronize edin ve dosyaları birkaç tıkla içe aktarın.',
          uk: 'Синхронізуйте виписки з Dropbox та імпортуйте файли за кілька кліків.',
          zh: '将账单与 Dropbox 同步，几次点击即可导入文件。',
          pl: 'Synchronizuj wyciągi z Dropbox i importuj pliki za pomocą kilku kliknięć.',
          it: 'Sincronizza gli estratti con Dropbox e importa file in pochi clic.',
          sk: 'Synchronizujte výpisy s Dropboxom a importujte súbory na pár kliknutí.',
          ja: 'Dropboxで明細を同期し、数クリックでファイルをインポートします。',
          ko: 'Dropbox로 명세서를 동기화하고 몇 번의 클릭으로 파일을 가져오세요.',
          hi: 'Dropbox के साथ विवरण सिंक करें और कुछ क्लिक में फ़ाइलें आयात करें।',
          nl: 'Synchroniseer afschriften met Dropbox en importeer bestanden in een paar klikken.',
          sv: 'Synkronisera kontoutdrag med Dropbox och importera filer med några klick.',
          vi: 'Đồng bộ hóa bảng sao kê với Dropbox và nhập tệp chỉ với vài cú nhấp.',
          id: 'Sinkronkan laporan dengan Dropbox dan impor file hanya dengan beberapa klik.',
          da: 'Synkronisér kontoudtog med Dropbox, og importér filer med få klik.',
          nb: 'Synkroniser kontoutskrifter med Dropbox og importer filer med få klikk.',
          nn: 'Synkroniser kontoutskrifter med Dropbox og importer filer med få klikk.',
          fi: 'Synkronoi tiliotteet Dropboxiin ja tuo tiedostot parilla napsautuksella.',
          is: 'Samstilltu yfirlit við Dropbox og flyttu skrár inn með fáum klikkum.',
          fo: 'Samstilla kontoyvirlit við Dropbox og flyt fílur inn við nøkrum klikkum.',
          cs: 'Synchronizujte výpisy s Dropboxem a importujte soubory na několik kliknutí.',
          bg: 'Синхронизирайте извлеченията с Dropbox и внасяйте файлове с няколко щраквания.',
          hr: 'Sinkronizirajte izvode s Dropboxom i uvezite datoteke u nekoliko klikova.',
          sr: 'Синхронизујте изводе с Dropbox-ом и увезите датотеке у неколико кликова.',
          sl: 'Izpiske sinhronizirajte z Dropboxom in uvozite datoteke v nekaj klikih.',
          mk: 'Синхронизирајте извадоци со Dropbox и внесете податотеки со неколку кликови.',
          be: 'Сінхранізуйце выпіскі з Dropbox і імпартуйце файлы ў некалькі клікаў.',
          bs: 'Sinhronizujte izvode s Dropboxom i uvezite datoteke u nekoliko klikova.',
          hsb: 'Synchronizujće wupisy z Dropbox a importujće dataje z mało klikami.',
        }),
        badge: t({
          ru: 'Доступно',
          en: 'Available',
          kk: 'Қолжетімді',
          de: 'Verfügbar',
          fr: 'Disponible',
          es: 'Disponible',
          pt: 'Disponível',
          tr: 'Mevcut',
          uk: 'Доступно',
          zh: '可用',
          pl: 'Dostępne',
          it: 'Disponibile',
          sk: 'Dostupné',
          ja: '利用可能',
          ko: '사용 가능',
          hi: 'उपलब्ध',
          nl: 'Beschikbaar',
          sv: 'Tillgänglig',
          vi: 'Có sẵn',
          id: 'Tersedia',
          da: 'Tilgængelige',
          nb: 'Tilgjengelige',
          nn: 'Tilgjengelege',
          fi: 'Saatavilla',
          is: 'Í boði',
          fo: 'Tøkar',
          cs: 'Dostupné',
          bg: 'Налични',
          hr: 'Dostupni',
          sr: 'Доступни',
          sl: 'Na voljo',
          mk: 'Достапни',
          be: 'Даступныя',
          bs: 'Dostupni',
          hsb: 'K dispoziciji',
        }),
        actions: {
          connect: t({
            ru: 'Подключить',
            en: 'Connect',
            kk: 'Қосу',
            de: 'Verbinden',
            fr: 'Connecter',
            es: 'Conectar',
            pt: 'Conectar',
            tr: 'Bağlan',
            uk: 'Підключити',
            zh: '连接',
            pl: 'Połącz',
            it: 'Connetti',
            sk: 'Pripojiť',
            ja: '接続',
            ko: '연결',
            hi: 'कनेक्ट करें',
            nl: 'Verbinden',
            sv: 'Anslut',
            vi: 'Kết nối',
            id: 'Hubungkan',
            da: 'Forbind',
            nb: 'Koble til',
            nn: 'Kople til',
            fi: 'Yhdistä',
            is: 'Tengja',
            fo: 'Set í samband',
            cs: 'Připojit',
            bg: 'Свързване',
            hr: 'Poveži',
            sr: 'Повежи',
            sl: 'Poveži',
            mk: 'Поврзи',
            be: 'Падлучыць',
            bs: 'Poveži',
            hsb: 'Zwjazać',
          }),
          docs: t({
            ru: 'Документация',
            en: 'Documentation',
            kk: 'Құжаттама',
            de: 'Dokumentation',
            fr: 'Documentation',
            es: 'Documentación',
            pt: 'Documentação',
            tr: 'Belgeler',
            uk: 'Документація',
            zh: '文档',
            pl: 'Dokumentacja',
            it: 'Documentazione',
            sk: 'Dokumentácia',
            ja: 'ドキュメント',
            ko: '문서',
            hi: 'दस्तावेज़ीकरण',
            nl: 'Documentatie',
            sv: 'Dokumentation',
            vi: 'Tài liệu',
            id: 'Dokumentasi',
            da: 'Dokumentation',
            nb: 'Dokumentasjon',
            nn: 'Dokumentasjon',
            fi: 'Dokumentaatio',
            is: 'Leiðbeiningar',
            fo: 'Skjalfesting',
            cs: 'Dokumentace',
            bg: 'Документация',
            hr: 'Dokumentacija',
            sr: 'Документација',
            sl: 'Dokumentacija',
            mk: 'Документација',
            be: 'Дакументацыя',
            bs: 'Dokumentacija',
            hsb: 'Dokumentacija',
          }),
        },
      },
      googleDrive: {
        description: t({
          ru: 'Синхронизируйте выписки с Google Drive и импортируйте файлы за пару кликов.',
          en: 'Sync statements with Google Drive and import files in a few clicks.',
          kk: 'Үзінділерді Google Drive-пен синхрондап, файлдарды оңай импорттаңыз.',
          de: 'Synchronisieren Sie Kontoauszüge mit Google Drive und importieren Sie Dateien mit wenigen Klicks.',
          fr: 'Synchronisez les relevés avec Google Drive et importez des fichiers en quelques clics.',
          es: 'Sincroniza extractos con Google Drive e importa archivos en pocos clics.',
          pt: 'Sincronize extratos com o Google Drive e importe arquivos em poucos cliques.',
          tr: 'Ekstreleri Google Drive ile senkronize edin ve dosyaları birkaç tıkla içe aktarın.',
          uk: 'Синхронізуйте виписки з Google Drive та імпортуйте файли за кілька кліків.',
          zh: '将账单与 Google Drive 同步，几次点击即可导入文件。',
          pl: 'Synchronizuj wyciągi z Google Drive i importuj pliki za pomocą kilku kliknięć.',
          it: 'Sincronizza gli estratti con Google Drive e importa file in pochi clic.',
          sk: 'Synchronizujte výpisy s Google Drive a importujte súbory na pár kliknutí.',
          ja: 'Google Driveで明細を同期し、数クリックでファイルをインポートします。',
          ko: 'Google Drive로 명세서를 동기화하고 몇 번의 클릭으로 파일을 가져오세요.',
          hi: 'Google Drive के साथ विवरण सिंक करें और कुछ क्लिक में फ़ाइलें आयात करें।',
          nl: 'Synchroniseer afschriften met Google Drive en importeer bestanden in een paar klikken.',
          sv: 'Synkronisera kontoutdrag med Google Drive och importera filer med några klick.',
          vi: 'Đồng bộ hóa bảng sao kê với Google Drive và nhập tệp chỉ với vài cú nhấp.',
          id: 'Sinkronkan laporan dengan Google Drive dan impor file hanya dengan beberapa klik.',
          da: 'Synkronisér kontoudtog med Google Drive, og importér filer med få klik.',
          nb: 'Synkroniser kontoutskrifter med Google Drive og importer filer med få klikk.',
          nn: 'Synkroniser kontoutskrifter med Google Drive og importer filer med få klikk.',
          fi: 'Synkronoi tiliotteet Google Driveen ja tuo tiedostot parilla napsautuksella.',
          is: 'Samstilltu yfirlit við Google Drive og flyttu skrár inn með fáum klikkum.',
          fo: 'Samstilla kontoyvirlit við Google Drive og flyt fílur inn við nøkrum klikkum.',
          cs: 'Synchronizujte výpisy s Google Drive a importujte soubory na několik kliknutí.',
          bg: 'Синхронизирайте извлеченията с Google Drive и внасяйте файлове с няколко щраквания.',
          hr: 'Sinkronizirajte izvode s Google Driveom i uvezite datoteke u nekoliko klikova.',
          sr: 'Синхронизујте изводе с Google Drive-ом и увезите датотеке у неколико кликова.',
          sl: 'Izpiske sinhronizirajte z Google Drivom in uvozite datoteke v nekaj klikih.',
          mk: 'Синхронизирајте извадоци со Google Drive и внесете податотеки со неколку кликови.',
          be: 'Сінхранізуйце выпіскі з Google Drive і імпартуйце файлы ў некалькі клікаў.',
          bs: 'Sinhronizujte izvode s Google Driveom i uvezite datoteke u nekoliko klikova.',
          hsb: 'Synchronizujće wupisy z Google Drive a importujće dataje z mało klikami.',
        }),
        badge: t({
          ru: 'Доступно',
          en: 'Available',
          kk: 'Қолжетімді',
          de: 'Verfügbar',
          fr: 'Disponible',
          es: 'Disponible',
          pt: 'Disponível',
          tr: 'Mevcut',
          uk: 'Доступно',
          zh: '可用',
          pl: 'Dostępne',
          it: 'Disponibile',
          sk: 'Dostupné',
          ja: '利用可能',
          ko: '사용 가능',
          hi: 'उपलब्ध',
          nl: 'Beschikbaar',
          sv: 'Tillgänglig',
          vi: 'Có sẵn',
          id: 'Tersedia',
          da: 'Tilgængelige',
          nb: 'Tilgjengelige',
          nn: 'Tilgjengelege',
          fi: 'Saatavilla',
          is: 'Í boði',
          fo: 'Tøkar',
          cs: 'Dostupné',
          bg: 'Налични',
          hr: 'Dostupni',
          sr: 'Доступни',
          sl: 'Na voljo',
          mk: 'Достапни',
          be: 'Даступныя',
          bs: 'Dostupni',
          hsb: 'K dispoziciji',
        }),
        actions: {
          connect: t({
            ru: 'Подключить',
            en: 'Connect',
            kk: 'Қосу',
            de: 'Verbinden',
            fr: 'Connecter',
            es: 'Conectar',
            pt: 'Conectar',
            tr: 'Bağlan',
            uk: 'Підключити',
            zh: '连接',
            pl: 'Połącz',
            it: 'Connetti',
            sk: 'Pripojiť',
            ja: '接続',
            ko: '연결',
            hi: 'कनेक्ट करें',
            nl: 'Verbinden',
            sv: 'Anslut',
            vi: 'Kết nối',
            id: 'Hubungkan',
            da: 'Forbind',
            nb: 'Koble til',
            nn: 'Kople til',
            fi: 'Yhdistä',
            is: 'Tengja',
            fo: 'Set í samband',
            cs: 'Připojit',
            bg: 'Свързване',
            hr: 'Poveži',
            sr: 'Повежи',
            sl: 'Poveži',
            mk: 'Поврзи',
            be: 'Падлучыць',
            bs: 'Poveži',
            hsb: 'Zwjazać',
          }),
          docs: t({
            ru: 'Документация',
            en: 'Documentation',
            kk: 'Құжаттама',
            de: 'Dokumentation',
            fr: 'Documentation',
            es: 'Documentación',
            pt: 'Documentação',
            tr: 'Belgeler',
            uk: 'Документація',
            zh: '文档',
            pl: 'Dokumentacja',
            it: 'Documentazione',
            sk: 'Dokumentácia',
            ja: 'ドキュメント',
            ko: '문서',
            hi: 'दस्तावेज़ीकरण',
            nl: 'Documentatie',
            sv: 'Dokumentation',
            vi: 'Tài liệu',
            id: 'Dokumentasi',
            da: 'Dokumentation',
            nb: 'Dokumentasjon',
            nn: 'Dokumentasjon',
            fi: 'Dokumentaatio',
            is: 'Leiðbeiningar',
            fo: 'Skjalfesting',
            cs: 'Dokumentace',
            bg: 'Документация',
            hr: 'Dokumentacija',
            sr: 'Документација',
            sl: 'Dokumentacija',
            mk: 'Документација',
            be: 'Дакументацыя',
            bs: 'Dokumentacija',
            hsb: 'Dokumentacija',
          }),
        },
      },
      telegram: {
        description: t({
          ru: 'Получайте уведомления и отправляйте выписки через бота.',
          en: 'Receive notifications and send statements via a bot.',
          kk: 'Хабарламалар алып, үзінділерді бот арқылы жіберіңіз.',
          de: 'Erhalten Sie Benachrichtigungen und senden Sie Kontoauszüge über einen Bot.',
          fr: 'Recevez des notifications et envoyez des relevés via un bot.',
          es: 'Recibe notificaciones y envía extractos a través de un bot.',
          pt: 'Receba notificações e envie extratos por meio de um bot.',
          tr: 'Bildirim alın ve bir bot aracılığıyla ekstre gönderin.',
          uk: 'Отримуйте сповіщення та надсилайте виписки через бота.',
          zh: '通过机器人接收通知并发送账单。',
          pl: 'Otrzymuj powiadomienia i wysyłaj wyciągi przez bota.',
          it: 'Ricevi notifiche e invia estratti tramite un bot.',
          sk: 'Dostávajte upozornenia a posielajte výpisy cez bota.',
          ja: 'ボット経由で通知を受け取り、明細を送信します。',
          ko: '봇을 통해 알림을 받고 명세서를 보내세요.',
          hi: 'बॉट के माध्यम से सूचनाएं प्राप्त करें और विवरण भेजें।',
          nl: 'Ontvang meldingen en stuur afschriften via een bot.',
          sv: 'Ta emot aviseringar och skicka kontoutdrag via en bot.',
          vi: 'Nhận thông báo và gửi bảng sao kê qua bot.',
          id: 'Terima notifikasi dan kirim laporan melalui bot.',
          da: 'Modtag notifikationer, og send kontoudtog via en bot.',
          nb: 'Få varsler og send kontoutskrifter via en bot.',
          nn: 'Få varsel og send kontoutskrifter via ein bot.',
          fi: 'Vastaanota ilmoituksia ja lähetä tiliotteita botin kautta.',
          is: 'Fáðu tilkynningar og sendu yfirlit um róbót.',
          fo: 'Fá fráboðanir og send kontoyvirlit gjøgnum ein bot.',
          cs: 'Dostávejte oznámení a posílejte výpisy přes bota.',
          bg: 'Получавайте известия и изпращайте извлечения чрез бот.',
          hr: 'Primajte obavijesti i šaljite izvode preko bota.',
          sr: 'Примајте обавештења и шаљите изводе преко бота.',
          sl: 'Prejemajte obvestila in pošiljajte izpiske prek bota.',
          mk: 'Добивајте известувања и испраќајте извадоци преку бот.',
          be: 'Атрымлівайце апавяшчэнні і адпраўляйце выпіскі праз бота.',
          bs: 'Primajte obavještenja i šaljite izvode preko bota.',
          hsb: 'Dóstańće zdźělenki a sćelće wupisy přez bota.',
        }),
        badge: t({
          ru: 'Скоро',
          en: 'Coming soon',
          kk: 'Жақында',
          de: 'Demnächst',
          fr: 'Bientôt disponible',
          es: 'Próximamente',
          pt: 'Em breve',
          tr: 'Yakında',
          uk: 'Незабаром',
          zh: '即将推出',
          pl: 'Wkrótce',
          it: 'Prossimamente',
          sk: 'Už čoskoro',
          ja: '近日公開',
          ko: '출시 예정',
          hi: 'जल्द आ रहा है',
          nl: 'Binnenkort beschikbaar',
          sv: 'Kommer snart',
          vi: 'Sắp ra mắt',
          id: 'Segera hadir',
          da: 'Kommer snart',
          nb: 'Kommer snart',
          nn: 'Kjem snart',
          fi: 'Tulossa pian',
          is: 'Væntanlegt',
          fo: 'Kemur skjótt',
          cs: 'Již brzy',
          bg: 'Очаквайте скоро',
          hr: 'Dolazi uskoro',
          sr: 'Долази ускоро',
          sl: 'Prihaja kmalu',
          mk: 'Наскоро',
          be: 'Хутка будзе',
          bs: 'Dolazi uskoro',
          hsb: 'Přińdźe bórze',
        }),
        actions: {
          setup: t({
            ru: 'Настроить бота',
            en: 'Set up bot',
            kk: 'Ботты баптау',
            de: 'Bot einrichten',
            fr: 'Configurer le bot',
            es: 'Configurar bot',
            pt: 'Configurar bot',
            tr: 'Botu kur',
            uk: 'Налаштувати бота',
            zh: '设置机器人',
            pl: 'Skonfiguruj bota',
            it: 'Configura bot',
            sk: 'Nastaviť bota',
            ja: 'ボットを設定',
            ko: '봇 설정',
            hi: 'बॉट सेट अप करें',
            nl: 'Bot instellen',
            sv: 'Konfigurera bot',
            vi: 'Thiết lập bot',
            id: 'Atur bot',
            da: 'Opsæt bot',
            nb: 'Sett opp bot',
            nn: 'Set opp bot',
            fi: 'Ota botti käyttöön',
            is: 'Setja upp róbót',
            fo: 'Set bot upp',
            cs: 'Nastavit bota',
            bg: 'Настройване на бота',
            hr: 'Postavi bota',
            sr: 'Постави бота',
            sl: 'Nastavi bota',
            mk: 'Постави бот',
            be: 'Наладзіць бота',
            bs: 'Postavi bota',
            hsb: 'Bota nastajić',
          }),
          guide: t({
            ru: 'Руководство',
            en: 'Guide',
            kk: 'Нұсқаулық',
            de: 'Anleitung',
            fr: 'Guider',
            es: 'Guía',
            pt: 'Guia',
            tr: 'Kılavuz',
            uk: 'Посібник',
            zh: '指南',
            pl: 'Przewodnik',
            it: 'Guida',
            sk: 'Návod',
            ja: 'ガイド',
            ko: '가이드',
            hi: 'गाइड',
            nl: 'Handleiding',
            sv: 'Guide',
            vi: 'Hướng dẫn',
            id: 'Panduan',
            da: 'Vejledning',
            nb: 'Veiledning',
            nn: 'Rettleiing',
            fi: 'Opas',
            is: 'Leiðarvísir',
            fo: 'Vegleiðing',
            cs: 'Návod',
            bg: 'Ръководство',
            hr: 'Vodič',
            sr: 'Водич',
            sl: 'Vodnik',
            mk: 'Водич',
            be: 'Даведнік',
            bs: 'Vodič',
            hsb: 'Nawod',
          }),
        },
      },
    },
  },
} satisfies Dictionary;

export default content;
