import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'netWorthPage',
  content: {
    title: t({
      ru: 'Чистые активы',
      en: 'Net worth',
      kk: 'Таза активтер',
      de: 'Nettovermögen',
      fr: 'Valeur nette',
      es: 'Patrimonio neto',
      pt: 'Património líquido',
      tr: 'Net değer',
      uk: 'Чисті активи',
      zh: '净资产',
      pl: 'Wartość netto',
      it: 'Patrimonio netto',
      sk: 'Čisté imanie',
      ja: '純資産',
      ko: '순자산',
      hi: 'निवल संपत्ति',
      nl: 'Nettovermogen',
      sv: 'Nettoförmögenhet',
      vi: 'Giá trị ròng',
      id: 'Kekayaan bersih',
      da: 'Formue',
      nb: 'Formue',
      nn: 'Formue',
      fi: 'Nettovarallisuus',
      is: 'Eigið fé',
      fo: 'Ognarvirði',
      cs: 'Čisté jmění',
      bg: 'Нетна стойност',
      hr: 'Neto vrijednost',
      sr: 'Нето вредност',
      sl: 'Neto vrednost',
      mk: 'Нето вредност',
      be: 'Чысты капітал',
      bs: 'Neto vrijednost',
      hsb: 'Neto hódnota',
    }),
    subtitle: t({
      ru: 'Активы за вычетом обязательств, по данным баланса',
      en: 'Assets minus liabilities, from your balance sheet',
      kk: 'Баланс деректері бойынша активтер минус міндеттемелер',
      de: 'Vermögen abzüglich Schulden, aus Ihrer Bilanz',
      fr: 'Actifs moins passifs, d’après votre bilan',
      es: 'Activos menos pasivos, según su balance',
      pt: 'Ativos menos passivos, a partir do seu balanço',
      tr: 'Bilançonuza göre varlıklar eksi yükümlülükler',
      uk: 'Активи за вирахуванням зобов’язань, за даними балансу',
      zh: '资产减去负债，来自资产负债表',
      pl: 'Aktywa minus zobowiązania, wg bilansu',
      it: 'Attività meno passività, dal bilancio',
      sk: 'Aktíva mínus záväzky, podľa súvahy',
      ja: '貸借対照表に基づく資産から負債を差し引いた額',
      ko: '재무상태표 기준 자산에서 부채를 뺀 값',
      hi: 'बैलेंस शीट के अनुसार संपत्ति घटा देनदारियाँ',
      nl: 'Activa min verplichtingen, volgens uw balans',
      sv: 'Tillgångar minus skulder, enligt balansräkningen',
      vi: 'Tài sản trừ nợ phải trả, theo bảng cân đối',
      id: 'Aset dikurangi liabilitas, dari neraca',
      da: 'Aktiver minus passiver, fra din balance',
      nb: 'Eiendeler minus gjeld, fra balansen din',
      nn: 'Eigedelar minus gjeld, frå balansen din',
      fi: 'Varat miinus velat, taseestasi',
      is: 'Eignir að frádregnum skuldum, úr efnahagsyfirliti þínu',
      fo: 'Eignir frádrignar skuldir, úr fíggjarstøðuni tíni',
      cs: 'Aktiva minus pasiva, z vaší rozvahy',
      bg: 'Активи минус пасиви, от вашия баланс',
      hr: 'Imovina minus obveze, iz vaše bilance',
      sr: 'Актива минус обавезе, из вашег биланса',
      sl: 'Sredstva minus obveznosti, iz vaše bilance',
      mk: 'Актива минус обврски, од вашиот биланс',
      be: 'Актывы мінус пасівы, з вашага балансу',
      bs: 'Imovina minus obaveze, iz vaše bilanse',
      hsb: 'Aktiwa minus pasiwa, z wašeje bilancy',
    }),
    overPeriod: t({
      ru: 'за период',
      en: 'over period',
      kk: 'кезең ішінде',
      de: 'im Zeitraum',
      fr: 'sur la période',
      es: 'en el periodo',
      pt: 'no período',
      tr: 'dönem boyunca',
      uk: 'за період',
      zh: '期间变化',
      pl: 'w okresie',
      it: 'nel periodo',
      sk: 'za obdobie',
      ja: '期間中',
      ko: '기간 중',
      hi: 'अवधि में',
      nl: 'over de periode',
      sv: 'under perioden',
      vi: 'trong kỳ',
      id: 'selama periode',
      da: 'over perioden',
      nb: 'over perioden',
      nn: 'over perioden',
      fi: 'jaksolla',
      is: 'á tímabilinu',
      fo: 'um tíðarskeiðið',
      cs: 'za období',
      bg: 'за периода',
      hr: 'u razdoblju',
      sr: 'у периоду',
      sl: 'v obdobju',
      mk: 'во периодот',
      be: 'за перыяд',
      bs: 'u periodu',
      hsb: 'w periodźe',
    }),
    assets: t({
      ru: 'Активы',
      en: 'Assets',
      kk: 'Активтер',
      de: 'Vermögen',
      fr: 'Actifs',
      es: 'Activos',
      pt: 'Ativos',
      tr: 'Varlıklar',
      uk: 'Активи',
      zh: '资产',
      pl: 'Aktywa',
      it: 'Attività',
      sk: 'Aktíva',
      ja: '資産',
      ko: '자산',
      hi: 'संपत्ति',
      nl: 'Activa',
      sv: 'Tillgångar',
      vi: 'Tài sản',
      id: 'Aset',
      da: 'Aktiver',
      nb: 'Eiendeler',
      nn: 'Eigedelar',
      fi: 'Vastaavaa',
      is: 'Eignir',
      fo: 'Eignir',
      cs: 'Aktiva',
      bg: 'Активи',
      hr: 'Imovina',
      sr: 'Актива',
      sl: 'Sredstva',
      mk: 'Актива',
      be: 'Актывы',
      bs: 'Imovina',
      hsb: 'Aktiwa',
    }),
    liabilities: t({
      ru: 'Обязательства',
      en: 'Liabilities',
      kk: 'Міндеттемелер',
      de: 'Verbindlichkeiten',
      fr: 'Passifs',
      es: 'Pasivos',
      pt: 'Passivos',
      tr: 'Yükümlülükler',
      uk: 'Зобов’язання',
      zh: '负债',
      pl: 'Zobowiązania',
      it: 'Passività',
      sk: 'Záväzky',
      ja: '負債',
      ko: '부채',
      hi: 'देनदारियाँ',
      nl: 'Verplichtingen',
      sv: 'Skulder',
      vi: 'Nợ phải trả',
      id: 'Liabilitas',
      da: 'Passiver',
      nb: 'Gjeld',
      nn: 'Gjeld',
      fi: 'Vastattavaa',
      is: 'Skuldir',
      fo: 'Skuldir',
      cs: 'Pasiva',
      bg: 'Пасиви',
      hr: 'Obveze',
      sr: 'Обавезе',
      sl: 'Obveznosti',
      mk: 'Обврски',
      be: 'Пасівы',
      bs: 'Obaveze',
      hsb: 'Pasiwa',
    }),
    allocation: t({
      ru: 'Структура активов',
      en: 'Asset allocation',
      kk: 'Активтер құрылымы',
      de: 'Vermögensaufteilung',
      fr: 'Répartition des actifs',
      es: 'Distribución de activos',
      pt: 'Alocação de ativos',
      tr: 'Varlık dağılımı',
      uk: 'Структура активів',
      zh: '资产配置',
      pl: 'Struktura aktywów',
      it: 'Allocazione delle attività',
      sk: 'Štruktúra aktív',
      ja: '資産構成',
      ko: '자산 구성',
      hi: 'संपत्ति आवंटन',
      nl: 'Activaverdeling',
      sv: 'Tillgångsfördelning',
      vi: 'Cơ cấu tài sản',
      id: 'Alokasi aset',
      da: 'Aktivfordeling',
      nb: 'Fordeling av eiendeler',
      nn: 'Fordeling av eigedelar',
      fi: 'Varojen jakauma',
      is: 'Skipting eigna',
      fo: 'Býti av eignum',
      cs: 'Rozložení aktiv',
      bg: 'Разпределение на активите',
      hr: 'Raspodjela imovine',
      sr: 'Распоред активе',
      sl: 'Razporeditev sredstev',
      mk: 'Распределба на активата',
      be: 'Размеркаванне актываў',
      bs: 'Raspodjela imovine',
      hsb: 'Rozdźělenje aktiwow',
    }),
    empty: t({
      ru: 'Пока нечего показать. Заполните баланс, чтобы увидеть динамику чистых активов.',
      en: 'Nothing to show yet. Fill in the balance sheet to see net worth over time.',
      kk: 'Әзірге көрсететін дерек жоқ. Таза активтер динамикасын көру үшін балансты толтырыңыз.',
      de: 'Noch nichts anzuzeigen. Füllen Sie die Bilanz aus, um die Entwicklung zu sehen.',
      fr: 'Rien à afficher. Remplissez le bilan pour voir l’évolution.',
      es: 'Nada que mostrar todavía. Complete el balance para ver la evolución.',
      pt: 'Nada para mostrar ainda. Preencha o balanço para ver a evolução.',
      tr: 'Henüz gösterilecek bir şey yok. Gelişimi görmek için bilançoyu doldurun.',
      uk: 'Поки нічого показати. Заповніть баланс, щоб побачити динаміку.',
      zh: '暂无数据。填写资产负债表后即可查看净资产变化。',
      pl: 'Nie ma jeszcze czego pokazać. Wypełnij bilans, aby zobaczyć zmiany.',
      it: 'Non c’è ancora nulla da mostrare. Compila il bilancio per vedere l’andamento.',
      sk: 'Zatiaľ niet čo zobraziť. Vyplňte súvahu, aby ste videli vývoj.',
      ja: 'まだ表示できるデータがありません。貸借対照表を入力してください。',
      ko: '아직 표시할 데이터가 없습니다. 재무상태표를 입력해 주세요.',
      hi: 'दिखाने के लिए अभी कुछ नहीं है। बैलेंस शीट भरें।',
      nl: 'Nog niets te tonen. Vul de balans in om het verloop te zien.',
      sv: 'Inget att visa ännu. Fyll i balansräkningen för att se utvecklingen.',
      vi: 'Chưa có dữ liệu. Hãy điền bảng cân đối để xem biến động.',
      id: 'Belum ada data. Isi neraca untuk melihat perubahannya.',
      da: 'Intet at vise endnu. Udfyld balancen for at se formuen over tid.',
      nb: 'Ingenting å vise ennå. Fyll ut balansen for å se formuen over tid.',
      nn: 'Ingenting å vise enno. Fyll ut balansen for å sjå formuen over tid.',
      fi: 'Ei vielä mitään näytettävää. Täytä tase, niin näet nettovarallisuuden ajan myötä.',
      is: 'Ekkert að sýna enn. Fylltu út efnahagsyfirlitið til að sjá eigið fé yfir tíma.',
      fo: 'Einki at vísa enn. Fyll fíggjarstøðuna út fyri at síggja ognarvirðið um tíðina.',
      cs: 'Zatím není co zobrazit. Vyplňte rozvahu a uvidíte čisté jmění v čase.',
      bg: 'Още няма какво да се покаже. Попълнете баланса, за да видите нетната стойност във времето.',
      hr: 'Još nema što prikazati. Ispunite bilancu da vidite neto vrijednost kroz vrijeme.',
      sr: 'Још нема шта да се прикаже. Попуните биланс да видите нето вредност кроз време.',
      sl: 'Še ni kaj prikazati. Izpolnite bilanco, da vidite neto vrednost skozi čas.',
      mk: 'Сè уште нема што да се прикаже. Пополнете го билансот за да ја видите нето вредноста низ времето.',
      be: 'Паказваць пакуль нечага. Запоўніце баланс, каб бачыць чысты капітал у часе.',
      bs: 'Još nema šta prikazati. Ispunite bilansu da vidite neto vrijednost kroz vrijeme.',
      hsb: 'Hišće ničo za pokazanje. Wupjelńće bilancu, zo byšće neto hódnotu w času widźał.',
    }),
    error: t({
      ru: 'Не удалось загрузить чистые активы',
      en: 'Could not load net worth',
      kk: 'Таза активтерді жүктеу мүмкін болмады',
      de: 'Nettovermögen konnte nicht geladen werden',
      fr: 'Impossible de charger la valeur nette',
      es: 'No se pudo cargar el patrimonio neto',
      pt: 'Não foi possível carregar o património líquido',
      tr: 'Net değer yüklenemedi',
      uk: 'Не вдалося завантажити чисті активи',
      zh: '无法加载净资产',
      pl: 'Nie udało się wczytać wartości netto',
      it: 'Impossibile caricare il patrimonio netto',
      sk: 'Čisté imanie sa nepodarilo načítať',
      ja: '純資産を読み込めませんでした',
      ko: '순자산을 불러오지 못했습니다',
      hi: 'निवल संपत्ति लोड नहीं हो सकी',
      nl: 'Nettovermogen kon niet worden geladen',
      sv: 'Kunde inte läsa in nettoförmögenheten',
      vi: 'Không tải được giá trị ròng',
      id: 'Gagal memuat kekayaan bersih',
      da: 'Formuen kunne ikke indlæses',
      nb: 'Kunne ikke laste formuen',
      nn: 'Kunne ikkje laste formuen',
      fi: 'Nettovarallisuutta ei voitu ladata',
      is: 'Ekki var unnt að hlaða eigin fé',
      fo: 'Fekk ikki lisið ognarvirðið',
      cs: 'Čisté jmění se nepodařilo načíst',
      bg: 'Нетната стойност не можа да се зареди',
      hr: 'Neto vrijednost nije bilo moguće učitati',
      sr: 'Нето вредност није могуће учитати',
      sl: 'Neto vrednosti ni bilo mogoče naložiti',
      mk: 'Нето вредноста не можеше да се вчита',
      be: 'Не ўдалося загрузіць чысты капітал',
      bs: 'Neto vrijednost nije moguće učitati',
      hsb: 'Neto hódnota njeda so začitać',
    }),
    riskTitle: t({
      ru: 'Риск и роль капитала',
      en: 'Risk and capital role',
      kk: 'Тәуекел және капитал рөлі',
      de: 'Risiko und Kapitalrolle',
      fr: 'Risque et rôle du capital',
      es: 'Riesgo y rol del capital',
      pt: 'Risco e papel do capital',
      tr: 'Risk ve sermaye rolü',
      uk: 'Ризик і роль капіталу',
      zh: '风险与资本角色',
      pl: 'Ryzyko i rola kapitału',
      it: 'Rischio e ruolo del capitale',
      sk: 'Riziko a rola kapitálu',
      ja: 'リスクと資本の役割',
      ko: '위험과 자본 역할',
      hi: 'जोखिम और पूँजी की भूमिका',
      nl: 'Risico en kapitaalrol',
      sv: 'Risk och kapitalroll',
      vi: 'Rủi ro và vai trò vốn',
      id: 'Risiko dan peran modal',
      da: 'Risiko og kapitalens rolle',
      nb: 'Risiko og kapitalens rolle',
      nn: 'Risiko og rolla til kapitalen',
      fi: 'Riski ja pääoman rooli',
      is: 'Hætta og hlutverk fjármagns',
      fo: 'Vandi og rolla hjá kapitalinum',
      cs: 'Riziko a role kapitálu',
      bg: 'Риск и роля на капитала',
      hr: 'Rizik i uloga kapitala',
      sr: 'Ризик и улога капитала',
      sl: 'Tveganje in vloga kapitala',
      mk: 'Ризик и улога на капиталот',
      be: 'Рызыка і роля капіталу',
      bs: 'Rizik i uloga kapitala',
      hsb: 'Risiko a rola kapitala',
    }),
    riskyShare: t({
      ru: 'В риске',
      en: 'At risk',
      kk: 'Тәуекелде',
      de: 'Im Risiko',
      fr: 'À risque',
      es: 'En riesgo',
      pt: 'Em risco',
      tr: 'Risk altında',
      uk: 'У ризику',
      zh: '风险占比',
      pl: 'W ryzyku',
      it: 'A rischio',
      sk: 'V riziku',
      ja: 'リスク下',
      ko: '위험 자산',
      hi: 'जोखिम में',
      nl: 'In risico',
      sv: 'I risk',
      vi: 'Chịu rủi ro',
      id: 'Berisiko',
      da: 'I risiko',
      nb: 'I risiko',
      nn: 'I risiko',
      fi: 'Riskissä',
      is: 'Í hættu',
      fo: 'Í vanda',
      cs: 'V riziku',
      bg: 'В риск',
      hr: 'U riziku',
      sr: 'У ризику',
      sl: 'V tveganju',
      mk: 'Во ризик',
      be: 'У рызыцы',
      bs: 'U riziku',
      hsb: 'W risiku',
    }),
    riskyHint: t({
      ru: 'Правило 80/20: не более 20% капитала в среднем и высоком риске',
      en: 'The 80/20 rule: at most 20% of capital in medium or high risk',
      kk: '80/20 ережесі: капиталдың 20%-ынан аспайтыны орташа және жоғары тәуекелде',
      de: '80/20-Regel: höchstens 20% des Kapitals im mittleren oder hohen Risiko',
      fr: 'Règle des 80/20 : au plus 20% du capital à risque moyen ou élevé',
      es: 'Regla 80/20: como máximo el 20% del capital en riesgo medio o alto',
      pt: 'Regra 80/20: no máximo 20% do capital em risco médio ou alto',
      tr: '80/20 kuralı: sermayenin en fazla %20’si orta veya yüksek riskte',
      uk: 'Правило 80/20: не більше 20% капіталу в середньому та високому ризику',
      zh: '80/20 法则：中高风险资产不超过 20%',
      pl: 'Zasada 80/20: najwyżej 20% kapitału w średnim lub wysokim ryzyku',
      it: 'Regola 80/20: al massimo il 20% del capitale a rischio medio o alto',
      sk: 'Pravidlo 80/20: najviac 20% kapitálu v strednom alebo vysokom riziku',
      ja: '80/20ルール：中〜高リスクは資本の20%まで',
      ko: '80/20 규칙: 중·고위험은 자본의 20% 이내',
      hi: '80/20 नियम: अधिकतम 20% पूँजी मध्यम या उच्च जोखिम में',
      nl: '80/20-regel: hooguit 20% van het kapitaal in midden- of hoog risico',
      sv: '80/20-regeln: högst 20% av kapitalet i medel- eller hög risk',
      vi: 'Quy tắc 80/20: tối đa 20% vốn ở rủi ro trung bình hoặc cao',
      id: 'Aturan 80/20: maksimal 20% modal di risiko menengah atau tinggi',
      da: '80/20-reglen: højst 20 % af kapitalen i mellem eller høj risiko',
      nb: '80/20-regelen: høyst 20 % av kapitalen i middels eller høy risiko',
      nn: '80/20-regelen: høgst 20 % av kapitalen i middels eller høg risiko',
      fi: '80/20-sääntö: enintään 20 % pääomasta keski- tai korkeassa riskissä',
      is: '80/20-reglan: að hámarki 20 % fjármagns í miðlungs- eða mikilli hættu',
      fo: '80/20-reglan: í mesta lagi 20 % av kapitalinum í miðal- ella høgum vanda',
      cs: 'Pravidlo 80/20: nejvýše 20 % kapitálu ve středním nebo vysokém riziku',
      bg: 'Правилото 80/20: най-много 20 % от капитала в среден или висок риск',
      hr: 'Pravilo 80/20: najviše 20 % kapitala u srednjem ili visokom riziku',
      sr: 'Правило 80/20: највише 20 % капитала у средњем или високом ризику',
      sl: 'Pravilo 80/20: največ 20 % kapitala v srednjem ali visokem tveganju',
      mk: 'Правилото 80/20: највеќе 20 % од капиталот во среден или висок ризик',
      be: 'Правіла 80/20: не больш за 20 % капіталу ў сярэдняй або высокай рызыцы',
      bs: 'Pravilo 80/20: najviše 20 % kapitala u srednjem ili visokom riziku',
      hsb: 'Prawidło 80/20: najwjace 20 % kapitala w srjedźnym abo wysokim risiku',
    }),
    unclassified: t({
      ru: 'Без классификации',
      en: 'Unclassified',
      kk: 'Жіктелмеген',
      de: 'Nicht klassifiziert',
      fr: 'Non classé',
      es: 'Sin clasificar',
      pt: 'Sem classificação',
      tr: 'Sınıflandırılmamış',
      uk: 'Без класифікації',
      zh: '未分类',
      pl: 'Niesklasyfikowane',
      it: 'Non classificato',
      sk: 'Nezaradené',
      ja: '未分類',
      ko: '미분류',
      hi: 'अवर्गीकृत',
      nl: 'Niet geclassificeerd',
      sv: 'Oklassificerat',
      vi: 'Chưa phân loại',
      id: 'Belum diklasifikasi',
      da: 'Uklassificeret',
      nb: 'Uklassifisert',
      nn: 'Uklassifisert',
      fi: 'Luokittelematon',
      is: 'Óflokkað',
      fo: 'Óbólkað',
      cs: 'Nezařazené',
      bg: 'Некласифицирано',
      hr: 'Neklasificirano',
      sr: 'Неклассификовано',
      sl: 'Nerazvrščeno',
      mk: 'Неклассифицирано',
      be: 'Некласіфікавана',
      bs: 'Neklasifikovano',
      hsb: 'Njeklasifikowane',
    }),
    riskColumn: t({
      ru: 'Риск',
      en: 'Risk',
      kk: 'Тәуекел',
      de: 'Risiko',
      fr: 'Risque',
      es: 'Riesgo',
      pt: 'Risco',
      tr: 'Risk',
      uk: 'Ризик',
      zh: '风险',
      pl: 'Ryzyko',
      it: 'Rischio',
      sk: 'Riziko',
      ja: 'リスク',
      ko: '위험',
      hi: 'जोखिम',
      nl: 'Risico',
      sv: 'Risk',
      vi: 'Rủi ro',
      id: 'Risiko',
      da: 'Risiko',
      nb: 'Risiko',
      nn: 'Risiko',
      fi: 'Riski',
      is: 'Hætta',
      fo: 'Vandi',
      cs: 'Riziko',
      bg: 'Риск',
      hr: 'Rizik',
      sr: 'Ризик',
      sl: 'Tveganje',
      mk: 'Ризик',
      be: 'Рызыка',
      bs: 'Rizik',
      hsb: 'Risiko',
    }),
    roleColumn: t({
      ru: 'Роль',
      en: 'Role',
      kk: 'Рөлі',
      de: 'Rolle',
      fr: 'Rôle',
      es: 'Rol',
      pt: 'Papel',
      tr: 'Rol',
      uk: 'Роль',
      zh: '角色',
      pl: 'Rola',
      it: 'Ruolo',
      sk: 'Rola',
      ja: '役割',
      ko: '역할',
      hi: 'भूमिका',
      nl: 'Rol',
      sv: 'Roll',
      vi: 'Vai trò',
      id: 'Peran',
      da: 'Rolle',
      nb: 'Rolle',
      nn: 'Rolle',
      fi: 'Rooli',
      is: 'Hlutverk',
      fo: 'Rolla',
      cs: 'Role',
      bg: 'Роля',
      hr: 'Uloga',
      sr: 'Улога',
      sl: 'Vloga',
      mk: 'Улога',
      be: 'Роля',
      bs: 'Uloga',
      hsb: 'Rola',
    }),
    riskLow: t({
      ru: 'Низкий риск',
      en: 'Low risk',
      kk: 'Төмен тәуекел',
      de: 'Geringes Risiko',
      fr: 'Risque faible',
      es: 'Riesgo bajo',
      pt: 'Risco baixo',
      tr: 'Düşük risk',
      uk: 'Низький ризик',
      zh: '低风险',
      pl: 'Niskie ryzyko',
      it: 'Rischio basso',
      sk: 'Nízke riziko',
      ja: '低リスク',
      ko: '저위험',
      hi: 'कम जोखिम',
      nl: 'Laag risico',
      sv: 'Låg risk',
      vi: 'Rủi ro thấp',
      id: 'Risiko rendah',
      da: 'Lav risiko',
      nb: 'Lav risiko',
      nn: 'Låg risiko',
      fi: 'Matala riski',
      is: 'Lítil hætta',
      fo: 'Lágur vandi',
      cs: 'Nízké riziko',
      bg: 'Нисък риск',
      hr: 'Nizak rizik',
      sr: 'Низак ризик',
      sl: 'Nizko tveganje',
      mk: 'Низок ризик',
      be: 'Нізкая рызыка',
      bs: 'Nizak rizik',
      hsb: 'Niske risiko',
    }),
    riskMedium: t({
      ru: 'Средний риск',
      en: 'Medium risk',
      kk: 'Орташа тәуекел',
      de: 'Mittleres Risiko',
      fr: 'Risque moyen',
      es: 'Riesgo medio',
      pt: 'Risco médio',
      tr: 'Orta risk',
      uk: 'Середній ризик',
      zh: '中风险',
      pl: 'Średnie ryzyko',
      it: 'Rischio medio',
      sk: 'Stredné riziko',
      ja: '中リスク',
      ko: '중위험',
      hi: 'मध्यम जोखिम',
      nl: 'Middelmatig risico',
      sv: 'Medelrisk',
      vi: 'Rủi ro trung bình',
      id: 'Risiko menengah',
      da: 'Mellem risiko',
      nb: 'Middels risiko',
      nn: 'Middels risiko',
      fi: 'Keskitason riski',
      is: 'Miðlungshætta',
      fo: 'Miðal vandi',
      cs: 'Střední riziko',
      bg: 'Среден риск',
      hr: 'Srednji rizik',
      sr: 'Средњи ризик',
      sl: 'Srednje tveganje',
      mk: 'Среден ризик',
      be: 'Сярэдняя рызыка',
      bs: 'Srednji rizik',
      hsb: 'Srjedźne risiko',
    }),
    riskHigh: t({
      ru: 'Высокий риск',
      en: 'High risk',
      kk: 'Жоғары тәуекел',
      de: 'Hohes Risiko',
      fr: 'Risque élevé',
      es: 'Riesgo alto',
      pt: 'Risco alto',
      tr: 'Yüksek risk',
      uk: 'Високий ризик',
      zh: '高风险',
      pl: 'Wysokie ryzyko',
      it: 'Rischio alto',
      sk: 'Vysoké riziko',
      ja: '高リスク',
      ko: '고위험',
      hi: 'उच्च जोखिम',
      nl: 'Hoog risico',
      sv: 'Hög risk',
      vi: 'Rủi ro cao',
      id: 'Risiko tinggi',
      da: 'Høj risiko',
      nb: 'Høy risiko',
      nn: 'Høg risiko',
      fi: 'Korkea riski',
      is: 'Mikil hætta',
      fo: 'Høgur vandi',
      cs: 'Vysoké riziko',
      bg: 'Висок риск',
      hr: 'Visok rizik',
      sr: 'Висок ризик',
      sl: 'Visoko tveganje',
      mk: 'Висок ризик',
      be: 'Высокая рызыка',
      bs: 'Visok rizik',
      hsb: 'Wysoke risiko',
    }),
    roleIncome: t({
      ru: 'Доходный',
      en: 'Income',
      kk: 'Табысты',
      de: 'Ertragbringend',
      fr: 'Productif',
      es: 'Genera ingresos',
      pt: 'Gera rendimento',
      tr: 'Gelir getiren',
      uk: 'Дохідний',
      zh: '带来收入',
      pl: 'Dochodowy',
      it: 'Redditizio',
      sk: 'Výnosný',
      ja: '収益源',
      ko: '수익형',
      hi: 'आय देने वाला',
      nl: 'Inkomstengevend',
      sv: 'Inkomstbringande',
      vi: 'Sinh lời',
      id: 'Menghasilkan',
      da: 'Indtægt',
      nb: 'Inntekt',
      nn: 'Inntekt',
      fi: 'Tulo',
      is: 'Tekjur',
      fo: 'Inntøka',
      cs: 'Příjem',
      bg: 'Приход',
      hr: 'Prihod',
      sr: 'Приход',
      sl: 'Prihodek',
      mk: 'Приход',
      be: 'Прыбытак',
      bs: 'Prihod',
      hsb: 'Dochod',
    }),
    roleNeutral: t({
      ru: 'Нейтральный',
      en: 'Neutral',
      kk: 'Бейтарап',
      de: 'Neutral',
      fr: 'Neutre',
      es: 'Neutral',
      pt: 'Neutro',
      tr: 'Nötr',
      uk: 'Нейтральний',
      zh: '中性',
      pl: 'Neutralny',
      it: 'Neutro',
      sk: 'Neutrálny',
      ja: '中立',
      ko: '중립',
      hi: 'तटस्थ',
      nl: 'Neutraal',
      sv: 'Neutral',
      vi: 'Trung tính',
      id: 'Netral',
      da: 'Neutral',
      nb: 'Nøytral',
      nn: 'Nøytral',
      fi: 'Neutraali',
      is: 'Hlutlaust',
      fo: 'Neutralt',
      cs: 'Neutrální',
      bg: 'Неутрално',
      hr: 'Neutralno',
      sr: 'Неутрално',
      sl: 'Nevtralno',
      mk: 'Неутрално',
      be: 'Нейтральна',
      bs: 'Neutralno',
      hsb: 'Neutralne',
    }),
    roleDrain: t({
      ru: 'Убыточный',
      en: 'Drain',
      kk: 'Шығынды',
      de: 'Kostentreiber',
      fr: 'Coûteux',
      es: 'Genera gastos',
      pt: 'Gera custos',
      tr: 'Gider getiren',
      uk: 'Збитковий',
      zh: '消耗资金',
      pl: 'Kosztowny',
      it: 'In perdita',
      sk: 'Stratový',
      ja: 'コスト源',
      ko: '비용형',
      hi: 'खर्चीला',
      nl: 'Kostenpost',
      sv: 'Kostnadsdrivande',
      vi: 'Tốn kém',
      id: 'Menguras',
      da: 'Dræn',
      nb: 'Sluk',
      nn: 'Sluk',
      fi: 'Valuttaja',
      is: 'Niðurdráttur',
      fo: 'Dreni',
      cs: 'Odtok',
      bg: 'Източване',
      hr: 'Odvod',
      sr: 'Одвод',
      sl: 'Odtok',
      mk: 'Одвод',
      be: 'Сцёк',
      bs: 'Odvod',
      hsb: 'Wotwod',
    }),
    missingRates: t({
      ru: 'Нет курса валют, суммы не вошли в итоги',
      en: 'No exchange rate, left out of the totals',
      kk: 'Валюта бағамы жоқ, сомалар жиынтыққа кірмеді',
      de: 'Kein Wechselkurs, nicht in den Summen enthalten',
      fr: 'Aucun taux de change, exclu des totaux',
      es: 'Sin tipo de cambio, excluido de los totales',
      pt: 'Sem taxa de câmbio, excluído dos totais',
      tr: 'Döviz kuru yok, toplamlara dahil edilmedi',
      uk: 'Немає курсу валют, суми не увійшли до підсумків',
      zh: '缺少汇率，未计入合计',
      pl: 'Brak kursu walut, pominięto w sumach',
      it: 'Nessun tasso di cambio, escluso dai totali',
      sk: 'Chýba výmenný kurz, nezahrnuté do súčtov',
      ja: '為替レートがないため合計から除外',
      ko: '환율이 없어 합계에서 제외됨',
      hi: 'विनिमय दर नहीं मिली, योग में शामिल नहीं',
      nl: 'Geen wisselkoers, niet meegeteld in de totalen',
      sv: 'Växelkurs saknas, ingår inte i summorna',
      vi: 'Không có tỷ giá, không tính vào tổng',
      id: 'Tidak ada kurs, tidak dihitung dalam total',
      da: 'Ingen valutakurs, udeladt af totalerne',
      nb: 'Ingen valutakurs, holdt utenfor summene',
      nn: 'Ingen valutakurs, halden utanfor summane',
      fi: 'Ei valuuttakurssia, jätetty summien ulkopuolelle',
      is: 'Ekkert gengi, haldið utan samtalna',
      fo: 'Ongin gjaldoyrakursur, hildin uttan fyri samlaðu summurnar',
      cs: 'Žádný kurz, mimo součty',
      bg: 'Няма валутен курс, извън тоталите',
      hr: 'Nema tečaja, izostavljeno iz ukupnih iznosa',
      sr: 'Нема курса, изостављено из укупних износа',
      sl: 'Ni tečaja, izpuščeno iz seštevkov',
      mk: 'Нема курс, изоставено од вкупните суми',
      be: 'Няма курсу валюты, не ўлічана ў вынікі',
      bs: 'Nema kursa, izostavljeno iz ukupnih iznosa',
      hsb: 'Žadyn kurs, zwonka sumow',
    }),
    allTimeHigh: t({
      ru: 'Максимум за всё время {{value}} ({{date}})',
      en: 'All-time high {{value}} on {{date}}',
      kk: 'Барлық уақыттағы максимум {{value}} ({{date}})',
      de: 'Allzeithoch {{value}} am {{date}}',
      fr: 'Record historique {{value}} le {{date}}',
      es: 'Máximo histórico {{value}} el {{date}}',
      pt: 'Máximo histórico {{value}} a {{date}}',
      tr: 'Tüm zamanların en yükseği {{value}} ({{date}})',
      uk: 'Максимум за весь час {{value}} ({{date}})',
      zh: '历史最高 {{value}}（{{date}}）',
      pl: 'Rekord wszech czasów {{value}} ({{date}})',
      it: 'Massimo storico {{value}} il {{date}}',
      sk: 'Historické maximum {{value}} ({{date}})',
      ja: '過去最高 {{value}}（{{date}}）',
      ko: '사상 최고 {{value}} ({{date}})',
      hi: 'सर्वकालिक उच्च {{value}} ({{date}})',
      nl: 'Hoogste ooit {{value}} op {{date}}',
      sv: 'Rekordnivå {{value}} den {{date}}',
      vi: 'Cao nhất mọi thời đại {{value}} ({{date}})',
      id: 'Tertinggi sepanjang masa {{value}} ({{date}})',
      da: 'Rekord {{value}} den {{date}}',
      nb: 'Rekord {{value}} den {{date}}',
      nn: 'Rekord {{value}} den {{date}}',
      fi: 'Kaikkien aikojen huippu {{value}} ({{date}})',
      is: 'Hæsta gildi frá upphafi {{value}} ({{date}})',
      fo: 'Hægsta virði nakrantíð {{value}} ({{date}})',
      cs: 'Historické maximum {{value}} ({{date}})',
      bg: 'Исторически връх {{value}} ({{date}})',
      hr: 'Najviša vrijednost dosad {{value}} ({{date}})',
      sr: 'Највиша вредност досад {{value}} ({{date}})',
      sl: 'Najvišja vrednost doslej {{value}} ({{date}})',
      mk: 'Највисока вредност досега {{value}} ({{date}})',
      be: 'Максімум за ўвесь час {{value}} ({{date}})',
      bs: 'Najviša vrijednost dosad {{value}} ({{date}})',
      hsb: 'Najwyša hódnota hač dotal {{value}} ({{date}})',
    }),
    assetClasses: t({
      ru: 'По классам активов',
      en: 'By asset class',
      kk: 'Актив сыныптары бойынша',
      de: 'Nach Anlageklasse',
      fr: 'Par classe d’actifs',
      es: 'Por clase de activo',
      pt: 'Por classe de ativos',
      tr: 'Varlık sınıfına göre',
      uk: 'За класами активів',
      zh: '按资产类别',
      pl: 'Według klasy aktywów',
      it: 'Per classe di attivo',
      sk: 'Podľa triedy aktív',
      ja: '資産クラス別',
      ko: '자산군별',
      hi: 'संपत्ति वर्ग के अनुसार',
      nl: 'Per activaklasse',
      sv: 'Per tillgångsslag',
      vi: 'Theo loại tài sản',
      id: 'Menurut kelas aset',
      da: 'Efter aktivklasse',
      nb: 'Etter aktivaklasse',
      nn: 'Etter aktivaklasse',
      fi: 'Omaisuusluokittain',
      is: 'Eftir eignaflokkum',
      fo: 'Eftir ognarbólkum',
      cs: 'Podle tříd aktiv',
      bg: 'По класове активи',
      hr: 'Po klasama imovine',
      sr: 'По класама имовине',
      sl: 'Po razredih sredstev',
      mk: 'По класи на средства',
      be: 'Па класах актываў',
      bs: 'Po klasama imovine',
      hsb: 'Po klasach aktiwow',
    }),
    classStock: t({
      ru: 'Акции',
      en: 'Stocks',
      kk: 'Акциялар',
      de: 'Aktien',
      fr: 'Actions',
      es: 'Acciones',
      pt: 'Ações',
      tr: 'Hisseler',
      uk: 'Акції',
      zh: '股票',
      pl: 'Akcje',
      it: 'Azioni',
      sk: 'Akcie',
      ja: '株式',
      ko: '주식',
      hi: 'स्टॉक',
      nl: 'Aandelen',
      sv: 'Aktier',
      vi: 'Cổ phiếu',
      id: 'Saham',
      da: 'Aktier',
      nb: 'Aksjer',
      nn: 'Aksjar',
      fi: 'Osakkeet',
      is: 'Hlutabréf',
      fo: 'Partabrøv',
      cs: 'Akcie',
      bg: 'Акции',
      hr: 'Dionice',
      sr: 'Акције',
      sl: 'Delnice',
      mk: 'Акции',
      be: 'Акцыі',
      bs: 'Dionice',
      hsb: 'Akcije',
    }),
    classEtf: t({
      ru: 'ETF',
      en: 'ETFs',
      kk: 'ETF',
      de: 'ETFs',
      fr: 'ETF',
      es: 'ETF',
      pt: 'ETF',
      tr: 'ETF',
      uk: 'ETF',
      zh: 'ETF',
      pl: 'ETF',
      it: 'ETF',
      sk: 'ETF',
      ja: 'ETF',
      ko: 'ETF',
      hi: 'ETF',
      nl: 'ETF’s',
      sv: 'ETF:er',
      vi: 'ETF',
      id: 'ETF',
      da: "ETF'er",
      nb: 'ETF-er',
      nn: 'ETF-ar',
      fi: 'ETF:t',
      is: 'ETF-sjóðir',
      fo: 'ETF-grunnar',
      cs: 'ETF',
      bg: 'ETF',
      hr: 'ETF-ovi',
      sr: 'ЕТФ',
      sl: 'ETF-ji',
      mk: 'ЕТФ',
      be: 'ETF',
      bs: 'ETF-ovi',
      hsb: 'ETF',
    }),
    classFund: t({
      ru: 'Фонды',
      en: 'Funds',
      kk: 'Қорлар',
      de: 'Fonds',
      fr: 'Fonds',
      es: 'Fondos',
      pt: 'Fundos',
      tr: 'Fonlar',
      uk: 'Фонди',
      zh: '基金',
      pl: 'Fundusze',
      it: 'Fondi',
      sk: 'Fondy',
      ja: 'ファンド',
      ko: '펀드',
      hi: 'फंड',
      nl: 'Fondsen',
      sv: 'Fonder',
      vi: 'Quỹ',
      id: 'Reksa dana',
      da: 'Fonde',
      nb: 'Fond',
      nn: 'Fond',
      fi: 'Rahastot',
      is: 'Sjóðir',
      fo: 'Grunnar',
      cs: 'Fondy',
      bg: 'Фондове',
      hr: 'Fondovi',
      sr: 'Фондови',
      sl: 'Skladi',
      mk: 'Фондови',
      be: 'Фонды',
      bs: 'Fondovi',
      hsb: 'Fondsy',
    }),
    classBond: t({
      ru: 'Облигации',
      en: 'Bonds',
      kk: 'Облигациялар',
      de: 'Anleihen',
      fr: 'Obligations',
      es: 'Bonos',
      pt: 'Obrigações',
      tr: 'Tahviller',
      uk: 'Облігації',
      zh: '债券',
      pl: 'Obligacje',
      it: 'Obbligazioni',
      sk: 'Dlhopisy',
      ja: '債券',
      ko: '채권',
      hi: 'बॉन्ड',
      nl: 'Obligaties',
      sv: 'Obligationer',
      vi: 'Trái phiếu',
      id: 'Obligasi',
      da: 'Obligationer',
      nb: 'Obligasjoner',
      nn: 'Obligasjonar',
      fi: 'Joukkovelkakirjat',
      is: 'Skuldabréf',
      fo: 'Lánsbrøv',
      cs: 'Dluhopisy',
      bg: 'Облигации',
      hr: 'Obveznice',
      sr: 'Обвезнице',
      sl: 'Obveznice',
      mk: 'Обврзници',
      be: 'Аблігацыі',
      bs: 'Obveznice',
      hsb: 'Obligacije',
    }),
    classCrypto: t({
      ru: 'Крипто',
      en: 'Crypto',
      kk: 'Крипто',
      de: 'Krypto',
      fr: 'Crypto',
      es: 'Cripto',
      pt: 'Cripto',
      tr: 'Kripto',
      uk: 'Крипто',
      zh: '加密货币',
      pl: 'Krypto',
      it: 'Cripto',
      sk: 'Krypto',
      ja: '暗号資産',
      ko: '암호화폐',
      hi: 'क्रिप्टो',
      nl: 'Crypto',
      sv: 'Krypto',
      vi: 'Tiền mã hóa',
      id: 'Kripto',
      da: 'Krypto',
      nb: 'Krypto',
      nn: 'Krypto',
      fi: 'Krypto',
      is: 'Rafmynt',
      fo: 'Kryptogjaldoyra',
      cs: 'Kryptoměny',
      bg: 'Криптовалути',
      hr: 'Kripto',
      sr: 'Крипто',
      sl: 'Kripto',
      mk: 'Крипто',
      be: 'Крыпта',
      bs: 'Kripto',
      hsb: 'Krypto',
    }),
    classCash: t({
      ru: 'Деньги',
      en: 'Cash',
      kk: 'Ақша',
      de: 'Bargeld',
      fr: 'Liquidités',
      es: 'Efectivo',
      pt: 'Dinheiro',
      tr: 'Nakit',
      uk: 'Гроші',
      zh: '现金',
      pl: 'Gotówka',
      it: 'Liquidità',
      sk: 'Hotovosť',
      ja: '現金',
      ko: '현금',
      hi: 'नकद',
      nl: 'Contanten',
      sv: 'Kontanter',
      vi: 'Tiền mặt',
      id: 'Kas',
      da: 'Kontanter',
      nb: 'Kontanter',
      nn: 'Kontantar',
      fi: 'Käteinen',
      is: 'Reiðufé',
      fo: 'Kontantir',
      cs: 'Hotovost',
      bg: 'Пари в брой',
      hr: 'Gotovina',
      sr: 'Готовина',
      sl: 'Gotovina',
      mk: 'Готовина',
      be: 'Наяўныя',
      bs: 'Gotovina',
      hsb: 'Hotowe pjenjezy',
    }),
    classRealEstate: t({
      ru: 'Недвижимость',
      en: 'Real estate',
      kk: 'Жылжымайтын мүлік',
      de: 'Immobilien',
      fr: 'Immobilier',
      es: 'Inmuebles',
      pt: 'Imobiliário',
      tr: 'Gayrimenkul',
      uk: 'Нерухомість',
      zh: '房地产',
      pl: 'Nieruchomości',
      it: 'Immobili',
      sk: 'Nehnuteľnosti',
      ja: '不動産',
      ko: '부동산',
      hi: 'रियल एस्टेट',
      nl: 'Vastgoed',
      sv: 'Fastigheter',
      vi: 'Bất động sản',
      id: 'Properti',
      da: 'Fast ejendom',
      nb: 'Eiendom',
      nn: 'Eigedom',
      fi: 'Kiinteistöt',
      is: 'Fasteignir',
      fo: 'Fastogn',
      cs: 'Nemovitosti',
      bg: 'Недвижими имоти',
      hr: 'Nekretnine',
      sr: 'Некретнине',
      sl: 'Nepremičnine',
      mk: 'Недвижности',
      be: 'Нерухомасць',
      bs: 'Nekretnine',
      hsb: 'Imobilije',
    }),
    classOther: t({
      ru: 'Другое',
      en: 'Other',
      kk: 'Басқа',
      de: 'Sonstiges',
      fr: 'Autre',
      es: 'Otros',
      pt: 'Outros',
      tr: 'Diğer',
      uk: 'Інше',
      zh: '其他',
      pl: 'Inne',
      it: 'Altro',
      sk: 'Iné',
      ja: 'その他',
      ko: '기타',
      hi: 'अन्य',
      nl: 'Overig',
      sv: 'Övrigt',
      vi: 'Khác',
      id: 'Lainnya',
      da: 'Andet',
      nb: 'Annet',
      nn: 'Anna',
      fi: 'Muut',
      is: 'Annað',
      fo: 'Annað',
      cs: 'Ostatní',
      bg: 'Други',
      hr: 'Ostalo',
      sr: 'Остало',
      sl: 'Drugo',
      mk: 'Друго',
      be: 'Іншае',
      bs: 'Ostalo',
      hsb: 'Druhe',
    }),
    investmentsTitle: t({
      ru: 'Инвестиции и пенсия',
      en: 'Investments and retirement',
      kk: 'Инвестициялар мен зейнетақы',
      de: 'Anlagen und Altersvorsorge',
      fr: 'Placements et retraite',
      es: 'Inversiones y jubilación',
      pt: 'Investimentos e reforma',
      tr: 'Yatırımlar ve emeklilik',
      uk: 'Інвестиції та пенсія',
      zh: '投资与养老',
      pl: 'Inwestycje i emerytura',
      it: 'Investimenti e pensione',
      sk: 'Investície a dôchodok',
      ja: '投資と年金',
      ko: '투자와 은퇴',
      hi: 'निवेश और रिटायरमेंट',
      nl: 'Beleggingen en pensioen',
      sv: 'Investeringar och pension',
      vi: 'Đầu tư và hưu trí',
      id: 'Investasi dan pensiun',
      da: 'Investeringer og pension',
      nb: 'Investeringer og pensjon',
      nn: 'Investeringar og pensjon',
      fi: 'Sijoitukset ja eläke',
      is: 'Fjárfestingar og eftirlaun',
      fo: 'Íløgur og eftirløn',
      cs: 'Investice a důchod',
      bg: 'Инвестиции и пенсия',
      hr: 'Ulaganja i mirovina',
      sr: 'Улагања и пензија',
      sl: 'Naložbe in pokojnina',
      mk: 'Инвестиции и пензија',
      be: 'Інвестыцыі і пенсія',
      bs: 'Ulaganja i penzija',
      hsb: 'Inwesticije a wuměnk',
    }),
    investmentsHint: t({
      ru: 'Позиции вручную; цены по тикеру с бесплатного источника. Взносы со страницы транзакций считаются переводами.',
      en: 'Positions by hand; prices by ticker from a free source. Contributions marked on transactions count as transfers.',
      kk: 'Позициялар қолмен; бағалар тикер бойынша тегін көзден. Транзакцияларда белгіленген жарналар аударым болып саналады.',
      de: 'Positionen von Hand; Kurse per Ticker aus einer freien Quelle. Als Beitrag markierte Buchungen gelten als Umbuchung.',
      fr: 'Positions saisies à la main ; cours par ticker depuis une source gratuite. Les versements marqués sur les transactions comptent comme virements.',
      es: 'Posiciones a mano; precios por ticker de una fuente gratuita. Los aportes marcados en transacciones cuentan como transferencias.',
      pt: 'Posições à mão; preços por ticker de uma fonte gratuita. Contribuições marcadas nas transações contam como transferências.',
      tr: 'Pozisyonlar elle; fiyatlar ücretsiz kaynaktan sembolle. İşlemlerde işaretlenen katkılar transfer sayılır.',
      uk: 'Позиції вручну; ціни за тікером із безкоштовного джерела. Внески, позначені в транзакціях, рахуються переказами.',
      zh: '手动录入持仓；按代码从免费来源取价。在交易中标记的转入视为转账。',
      pl: 'Pozycje ręcznie; ceny po tickerze z darmowego źródła. Wpłaty oznaczone na transakcjach liczą się jako przelewy.',
      it: 'Posizioni a mano; prezzi per ticker da una fonte gratuita. I versamenti segnati sulle transazioni contano come trasferimenti.',
      sk: 'Pozície ručne; ceny podľa tickera z bezplatného zdroja. Vklady označené na transakciách sa počítajú ako prevody.',
      ja: 'ポジションは手入力、価格はティッカーで無料ソースから取得。取引で拠出とした分は振替扱い。',
      ko: '포지션은 직접 입력, 가격은 무료 소스에서 티커로. 거래에서 납입으로 표시한 건 이체로 계산.',
      hi: 'पोज़िशन हाथ से; टिकर से मुफ़्त स्रोत के भाव। लेन-देन में चिह्नित योगदान ट्रांसफर माने जाते हैं।',
      nl: 'Posities handmatig; koersen per ticker uit een gratis bron. Als bijdrage gemarkeerde transacties tellen als overboeking.',
      sv: 'Positioner manuellt; kurser per ticker från en gratis källa. Insättningar markerade på transaktioner räknas som överföringar.',
      vi: 'Vị thế nhập tay; giá theo mã từ nguồn miễn phí. Khoản góp đánh dấu ở giao dịch được tính là chuyển khoản.',
      id: 'Posisi manual; harga per ticker dari sumber gratis. Setoran yang ditandai di transaksi dihitung sebagai transfer.',
      da: 'Positioner manuelt; kurser efter ticker fra en gratis kilde. Indskud markeret på transaktioner tæller som overførsler.',
      nb: 'Posisjoner manuelt; kurser etter ticker fra en gratis kilde. Innskudd merket på transaksjoner regnes som overføringer.',
      nn: 'Posisjonar manuelt; kursar etter ticker frå ei gratis kjelde. Innskot merkte på transaksjonar vert rekna som overføringar.',
      fi: 'Positiot käsin; hinnat tickerin mukaan ilmaisesta lähteestä. Tapahtumiin merkityt sijoitukset lasketaan siirroiksi.',
      is: 'Stöður handvirkt; verð eftir auðkenni frá ókeypis heimild. Innlegg merkt á færslum teljast millifærslur.',
      fo: 'Støður við hond; prísir eftir auðkenni frá ókeypis keldu. Innskot merkt á flytingum teljast sum millumflytingar.',
      cs: 'Pozice ručně; ceny podle tickeru z bezplatného zdroje. Vklady označené u transakcí se počítají jako převody.',
      bg: 'Позиции ръчно; цени по тикер от безплатен източник. Вноските, отбелязани в транзакциите, се броят за преводи.',
      hr: 'Pozicije ručno; cijene po oznaci iz besplatnog izvora. Uplate označene na transakcijama računaju se kao prijenosi.',
      sr: 'Позиције ручно; цене по ознаци из бесплатног извора. Уплате означене на трансакцијама рачунају се као преноси.',
      sl: 'Pozicije ročno; cene po oznaki iz brezplačnega vira. Vplačila, označena pri transakcijah, štejejo kot prenosi.',
      mk: 'Позиции рачно; цени по ознака од бесплатен извор. Уплатите означени на трансакциите се сметаат за преноси.',
      be: 'Пазіцыі ўручную; цэны па тыкеры з бясплатнай крыніцы. Унёскі, адзначаныя ў транзакцыях, лічацца пераводамі.',
      bs: 'Pozicije ručno; cijene po oznaci iz besplatnog izvora. Uplate označene na transakcijama računaju se kao prijenosi.',
      hsb: 'Pozicije manuelnje; płaćizny po tickeru z darmotneho žórła. Zapłaty markěrowane při transakcijach so jako přepokazy liča.',
    }),
    addAccount: t({
      ru: 'Добавить счёт',
      en: 'Add account',
      kk: 'Шот қосу',
      de: 'Konto hinzufügen',
      fr: 'Ajouter un compte',
      es: 'Añadir cuenta',
      pt: 'Adicionar conta',
      tr: 'Hesap ekle',
      uk: 'Додати рахунок',
      zh: '添加账户',
      pl: 'Dodaj konto',
      it: 'Aggiungi conto',
      sk: 'Pridať účet',
      ja: '口座を追加',
      ko: '계좌 추가',
      hi: 'खाता जोड़ें',
      nl: 'Rekening toevoegen',
      sv: 'Lägg till konto',
      vi: 'Thêm tài khoản',
      id: 'Tambah akun',
      da: 'Tilføj konto',
      nb: 'Legg til konto',
      nn: 'Legg til konto',
      fi: 'Lisää tili',
      is: 'Bæta við reikningi',
      fo: 'Legg konto afturat',
      cs: 'Přidat účet',
      bg: 'Добави сметка',
      hr: 'Dodaj račun',
      sr: 'Додај рачун',
      sl: 'Dodaj račun',
      mk: 'Додај сметка',
      be: 'Дадаць рахунак',
      bs: 'Dodaj račun',
      hsb: 'Konto přidać',
    }),
    accountName: t({
      ru: 'Название счёта',
      en: 'Account name',
      kk: 'Шот атауы',
      de: 'Kontoname',
      fr: 'Nom du compte',
      es: 'Nombre de la cuenta',
      pt: 'Nome da conta',
      tr: 'Hesap adı',
      uk: 'Назва рахунку',
      zh: '账户名称',
      pl: 'Nazwa konta',
      it: 'Nome del conto',
      sk: 'Názov účtu',
      ja: '口座名',
      ko: '계좌 이름',
      hi: 'खाते का नाम',
      nl: 'Rekeningnaam',
      sv: 'Kontonamn',
      vi: 'Tên tài khoản',
      id: 'Nama akun',
      da: 'Kontonavn',
      nb: 'Kontonavn',
      nn: 'Kontonamn',
      fi: 'Tilin nimi',
      is: 'Heiti reiknings',
      fo: 'Kontunavn',
      cs: 'Název účtu',
      bg: 'Име на сметката',
      hr: 'Naziv računa',
      sr: 'Назив рачуна',
      sl: 'Ime računa',
      mk: 'Име на сметка',
      be: 'Назва рахунку',
      bs: 'Naziv računa',
      hsb: 'Mjeno konta',
    }),
    kindInvestment: t({
      ru: 'Инвестиционный',
      en: 'Investment',
      kk: 'Инвестициялық',
      de: 'Anlage',
      fr: 'Placement',
      es: 'Inversión',
      pt: 'Investimento',
      tr: 'Yatırım',
      uk: 'Інвестиційний',
      zh: '投资',
      pl: 'Inwestycyjne',
      it: 'Investimento',
      sk: 'Investičný',
      ja: '投資',
      ko: '투자',
      hi: 'निवेश',
      nl: 'Belegging',
      sv: 'Investering',
      vi: 'Đầu tư',
      id: 'Investasi',
      da: 'Investering',
      nb: 'Investering',
      nn: 'Investering',
      fi: 'Sijoitus',
      is: 'Fjárfesting',
      fo: 'Íløga',
      cs: 'Investice',
      bg: 'Инвестиция',
      hr: 'Ulaganje',
      sr: 'Улагање',
      sl: 'Naložba',
      mk: 'Инвестиција',
      be: 'Інвестыцыя',
      bs: 'Ulaganje',
      hsb: 'Inwesticija',
    }),
    kindRetirement: t({
      ru: 'Пенсионный',
      en: 'Retirement',
      kk: 'Зейнетақы',
      de: 'Altersvorsorge',
      fr: 'Retraite',
      es: 'Jubilación',
      pt: 'Reforma',
      tr: 'Emeklilik',
      uk: 'Пенсійний',
      zh: '养老',
      pl: 'Emerytalne',
      it: 'Pensione',
      sk: 'Dôchodkový',
      ja: '年金',
      ko: '은퇴',
      hi: 'रिटायरमेंट',
      nl: 'Pensioen',
      sv: 'Pension',
      vi: 'Hưu trí',
      id: 'Pensiun',
      da: 'Pension',
      nb: 'Pensjon',
      nn: 'Pensjon',
      fi: 'Eläke',
      is: 'Eftirlaun',
      fo: 'Eftirløn',
      cs: 'Důchod',
      bg: 'Пенсия',
      hr: 'Mirovina',
      sr: 'Пензија',
      sl: 'Pokojnina',
      mk: 'Пензија',
      be: 'Пенсія',
      bs: 'Penzija',
      hsb: 'Wuměnk',
    }),
    addHolding: t({
      ru: 'Добавить позицию',
      en: 'Add holding',
      kk: 'Позиция қосу',
      de: 'Position hinzufügen',
      fr: 'Ajouter une position',
      es: 'Añadir posición',
      pt: 'Adicionar posição',
      tr: 'Pozisyon ekle',
      uk: 'Додати позицію',
      zh: '添加持仓',
      pl: 'Dodaj pozycję',
      it: 'Aggiungi posizione',
      sk: 'Pridať pozíciu',
      ja: 'ポジションを追加',
      ko: '포지션 추가',
      hi: 'होल्डिंग जोड़ें',
      nl: 'Positie toevoegen',
      sv: 'Lägg till innehav',
      vi: 'Thêm vị thế',
      id: 'Tambah posisi',
      da: 'Tilføj beholdning',
      nb: 'Legg til beholdning',
      nn: 'Legg til behaldning',
      fi: 'Lisää omistus',
      is: 'Bæta við eign',
      fo: 'Legg ogn afturat',
      cs: 'Přidat pozici',
      bg: 'Добави позиция',
      hr: 'Dodaj poziciju',
      sr: 'Додај позицију',
      sl: 'Dodaj pozicijo',
      mk: 'Додај позиција',
      be: 'Дадаць пазіцыю',
      bs: 'Dodaj poziciju',
      hsb: 'Poziciju přidać',
    }),
    symbol: t({
      ru: 'Тикер',
      en: 'Ticker',
      kk: 'Тикер',
      de: 'Ticker',
      fr: 'Ticker',
      es: 'Ticker',
      pt: 'Ticker',
      tr: 'Sembol',
      uk: 'Тікер',
      zh: '代码',
      pl: 'Ticker',
      it: 'Ticker',
      sk: 'Ticker',
      ja: 'ティッカー',
      ko: '티커',
      hi: 'टिकर',
      nl: 'Ticker',
      sv: 'Ticker',
      vi: 'Mã',
      id: 'Ticker',
      da: 'Ticker',
      nb: 'Ticker',
      nn: 'Ticker',
      fi: 'Tunnus',
      is: 'Auðkenni',
      fo: 'Auðkenni',
      cs: 'Ticker',
      bg: 'Тикер',
      hr: 'Oznaka',
      sr: 'Ознака',
      sl: 'Oznaka',
      mk: 'Ознака',
      be: 'Тыкер',
      bs: 'Oznaka',
      hsb: 'Ticker',
    }),
    holdingName: t({
      ru: 'Название',
      en: 'Name',
      kk: 'Атауы',
      de: 'Name',
      fr: 'Nom',
      es: 'Nombre',
      pt: 'Nome',
      tr: 'Ad',
      uk: 'Назва',
      zh: '名称',
      pl: 'Nazwa',
      it: 'Nome',
      sk: 'Názov',
      ja: '名称',
      ko: '이름',
      hi: 'नाम',
      nl: 'Naam',
      sv: 'Namn',
      vi: 'Tên',
      id: 'Nama',
      da: 'Navn',
      nb: 'Navn',
      nn: 'Namn',
      fi: 'Nimi',
      is: 'Heiti',
      fo: 'Navn',
      cs: 'Název',
      bg: 'Име',
      hr: 'Naziv',
      sr: 'Назив',
      sl: 'Ime',
      mk: 'Име',
      be: 'Назва',
      bs: 'Naziv',
      hsb: 'Mjeno',
    }),
    assetClass: t({
      ru: 'Класс',
      en: 'Class',
      kk: 'Сынып',
      de: 'Klasse',
      fr: 'Classe',
      es: 'Clase',
      pt: 'Classe',
      tr: 'Sınıf',
      uk: 'Клас',
      zh: '类别',
      pl: 'Klasa',
      it: 'Classe',
      sk: 'Trieda',
      ja: 'クラス',
      ko: '자산군',
      hi: 'वर्ग',
      nl: 'Klasse',
      sv: 'Slag',
      vi: 'Loại',
      id: 'Kelas',
      da: 'Klasse',
      nb: 'Klasse',
      nn: 'Klasse',
      fi: 'Luokka',
      is: 'Flokkur',
      fo: 'Bólkur',
      cs: 'Třída',
      bg: 'Клас',
      hr: 'Klasa',
      sr: 'Класа',
      sl: 'Razred',
      mk: 'Класа',
      be: 'Клас',
      bs: 'Klasa',
      hsb: 'Klasa',
    }),
    quantity: t({
      ru: 'Кол-во',
      en: 'Quantity',
      kk: 'Саны',
      de: 'Menge',
      fr: 'Quantité',
      es: 'Cantidad',
      pt: 'Quantidade',
      tr: 'Adet',
      uk: 'Кількість',
      zh: '数量',
      pl: 'Ilość',
      it: 'Quantità',
      sk: 'Množstvo',
      ja: '数量',
      ko: '수량',
      hi: 'मात्रा',
      nl: 'Aantal',
      sv: 'Antal',
      vi: 'Số lượng',
      id: 'Jumlah',
      da: 'Antal',
      nb: 'Antall',
      nn: 'Tal',
      fi: 'Määrä',
      is: 'Magn',
      fo: 'Nøgd',
      cs: 'Množství',
      bg: 'Количество',
      hr: 'Količina',
      sr: 'Количина',
      sl: 'Količina',
      mk: 'Количина',
      be: 'Колькасць',
      bs: 'Količina',
      hsb: 'Mnóstwo',
    }),
    price: t({
      ru: 'Цена',
      en: 'Price',
      kk: 'Бағасы',
      de: 'Kurs',
      fr: 'Prix',
      es: 'Precio',
      pt: 'Preço',
      tr: 'Fiyat',
      uk: 'Ціна',
      zh: '价格',
      pl: 'Cena',
      it: 'Prezzo',
      sk: 'Cena',
      ja: '価格',
      ko: '가격',
      hi: 'भाव',
      nl: 'Koers',
      sv: 'Kurs',
      vi: 'Giá',
      id: 'Harga',
      da: 'Kurs',
      nb: 'Kurs',
      nn: 'Kurs',
      fi: 'Hinta',
      is: 'Verð',
      fo: 'Prísur',
      cs: 'Cena',
      bg: 'Цена',
      hr: 'Cijena',
      sr: 'Цена',
      sl: 'Cena',
      mk: 'Цена',
      be: 'Цана',
      bs: 'Cijena',
      hsb: 'Płaćizna',
    }),
    value: t({
      ru: 'Стоимость',
      en: 'Value',
      kk: 'Құны',
      de: 'Wert',
      fr: 'Valeur',
      es: 'Valor',
      pt: 'Valor',
      tr: 'Değer',
      uk: 'Вартість',
      zh: '市值',
      pl: 'Wartość',
      it: 'Valore',
      sk: 'Hodnota',
      ja: '評価額',
      ko: '평가액',
      hi: 'मूल्य',
      nl: 'Waarde',
      sv: 'Värde',
      vi: 'Giá trị',
      id: 'Nilai',
      da: 'Værdi',
      nb: 'Verdi',
      nn: 'Verdi',
      fi: 'Arvo',
      is: 'Virði',
      fo: 'Virði',
      cs: 'Hodnota',
      bg: 'Стойност',
      hr: 'Vrijednost',
      sr: 'Вредност',
      sl: 'Vrednost',
      mk: 'Вредност',
      be: 'Вартасць',
      bs: 'Vrijednost',
      hsb: 'Hódnota',
    }),
    contributed: t({
      ru: 'Внесено',
      en: 'Contributed',
      kk: 'Салынды',
      de: 'Eingezahlt',
      fr: 'Versé',
      es: 'Aportado',
      pt: 'Contribuído',
      tr: 'Yatırılan',
      uk: 'Внесено',
      zh: '已投入',
      pl: 'Wpłacono',
      it: 'Versato',
      sk: 'Vložené',
      ja: '拠出額',
      ko: '납입액',
      hi: 'योगदान',
      nl: 'Ingelegd',
      sv: 'Insatt',
      vi: 'Đã góp',
      id: 'Disetor',
      da: 'Indskudt',
      nb: 'Innskutt',
      nn: 'Innskote',
      fi: 'Sijoitettu',
      is: 'Lagt inn',
      fo: 'Lagt inn',
      cs: 'Vloženo',
      bg: 'Вложено',
      hr: 'Uloženo',
      sr: 'Уложено',
      sl: 'Vloženo',
      mk: 'Вложено',
      be: 'Укладзена',
      bs: 'Uloženo',
      hsb: 'Zapłaćene',
    }),
    gain: t({
      ru: 'Результат',
      en: 'Gain',
      kk: 'Нәтиже',
      de: 'Ergebnis',
      fr: 'Plus-value',
      es: 'Ganancia',
      pt: 'Ganho',
      tr: 'Kazanç',
      uk: 'Результат',
      zh: '收益',
      pl: 'Wynik',
      it: 'Risultato',
      sk: 'Výsledok',
      ja: '損益',
      ko: '손익',
      hi: 'लाभ',
      nl: 'Resultaat',
      sv: 'Resultat',
      vi: 'Lãi/lỗ',
      id: 'Hasil',
      da: 'Gevinst',
      nb: 'Gevinst',
      nn: 'Vinst',
      fi: 'Tuotto',
      is: 'Hagnaður',
      fo: 'Vinningur',
      cs: 'Zisk',
      bg: 'Печалба',
      hr: 'Dobit',
      sr: 'Добит',
      sl: 'Dobiček',
      mk: 'Добивка',
      be: 'Прыбытак',
      bs: 'Dobit',
      hsb: 'Dobyćk',
    }),
    refreshPrices: t({
      ru: 'Обновить цены',
      en: 'Refresh prices',
      kk: 'Бағаларды жаңарту',
      de: 'Kurse aktualisieren',
      fr: 'Actualiser les cours',
      es: 'Actualizar precios',
      pt: 'Atualizar preços',
      tr: 'Fiyatları yenile',
      uk: 'Оновити ціни',
      zh: '刷新价格',
      pl: 'Odśwież ceny',
      it: 'Aggiorna prezzi',
      sk: 'Obnoviť ceny',
      ja: '価格を更新',
      ko: '가격 새로고침',
      hi: 'भाव अपडेट करें',
      nl: 'Koersen vernieuwen',
      sv: 'Uppdatera kurser',
      vi: 'Cập nhật giá',
      id: 'Perbarui harga',
      da: 'Opdater kurser',
      nb: 'Oppdater kurser',
      nn: 'Oppdater kursar',
      fi: 'Päivitä hinnat',
      is: 'Uppfæra verð',
      fo: 'Dagfør prísir',
      cs: 'Aktualizovat ceny',
      bg: 'Обнови цените',
      hr: 'Osvježi cijene',
      sr: 'Освежи цене',
      sl: 'Osveži cene',
      mk: 'Освежи цени',
      be: 'Абнавіць цэны',
      bs: 'Osvježi cijene',
      hsb: 'Płaćizny aktualizować',
    }),
    pricesUpdated: t({
      ru: 'Обновлено позиций: {{count}}',
      en: 'Prices updated for {{count}} holdings',
      kk: '{{count}} позиция жаңартылды',
      de: 'Kurse für {{count}} Positionen aktualisiert',
      fr: 'Cours actualisés pour {{count}} positions',
      es: 'Precios actualizados en {{count}} posiciones',
      pt: 'Preços atualizados em {{count}} posições',
      tr: '{{count}} pozisyonun fiyatı güncellendi',
      uk: 'Оновлено позицій: {{count}}',
      zh: '已更新 {{count}} 个持仓的价格',
      pl: 'Zaktualizowano ceny {{count}} pozycji',
      it: 'Prezzi aggiornati per {{count}} posizioni',
      sk: 'Ceny aktualizované pre {{count}} pozícií',
      ja: '{{count}} 件の価格を更新',
      ko: '{{count}}개 포지션 가격 업데이트',
      hi: '{{count}} होल्डिंग के भाव अपडेट',
      nl: 'Koersen vernieuwd voor {{count}} posities',
      sv: 'Kurser uppdaterade för {{count}} innehav',
      vi: 'Đã cập nhật giá cho {{count}} vị thế',
      id: 'Harga diperbarui untuk {{count}} posisi',
      da: 'Kurser opdateret for {{count}} beholdninger',
      nb: 'Kurser oppdatert for {{count}} beholdninger',
      nn: 'Kursar oppdaterte for {{count}} behaldningar',
      fi: 'Hinnat päivitetty {{count}} omistukselle',
      is: 'Verð uppfært fyrir {{count}} eignir',
      fo: 'Prísir dagførdir fyri {{count}} ognir',
      cs: 'Ceny aktualizovány u {{count}} pozic',
      bg: 'Цените са обновени за {{count}} позиции',
      hr: 'Cijene ažurirane za {{count}} pozicija',
      sr: 'Цене ажуриране за {{count}} позиција',
      sl: 'Cene posodobljene za {{count}} pozicij',
      mk: 'Цените се ажурирани за {{count}} позиции',
      be: 'Цэны абноўлены для {{count}} пазіцый',
      bs: 'Cijene ažurirane za {{count}} pozicija',
      hsb: 'Płaćizny za {{count}} pozicijow aktualizowane',
    }),
    noAccounts: t({
      ru: 'Пока нет инвестиционных или пенсионных счетов',
      en: 'No investment or retirement accounts yet',
      kk: 'Әзірге инвестициялық немесе зейнетақы шоттары жоқ',
      de: 'Noch keine Anlage- oder Vorsorgekonten',
      fr: 'Pas encore de compte de placement ou de retraite',
      es: 'Aún no hay cuentas de inversión ni jubilación',
      pt: 'Ainda sem contas de investimento ou reforma',
      tr: 'Henüz yatırım veya emeklilik hesabı yok',
      uk: 'Поки немає інвестиційних чи пенсійних рахунків',
      zh: '还没有投资或养老账户',
      pl: 'Brak kont inwestycyjnych i emerytalnych',
      it: 'Nessun conto di investimento o pensione',
      sk: 'Zatiaľ žiadne investičné ani dôchodkové účty',
      ja: '投資・年金口座はまだありません',
      ko: '투자 또는 은퇴 계좌가 없습니다',
      hi: 'अभी कोई निवेश या रिटायरमेंट खाता नहीं',
      nl: 'Nog geen beleggings- of pensioenrekeningen',
      sv: 'Inga investerings- eller pensionskonton än',
      vi: 'Chưa có tài khoản đầu tư hay hưu trí',
      id: 'Belum ada akun investasi atau pensiun',
      da: 'Ingen investerings- eller pensionskonti endnu',
      nb: 'Ingen investerings- eller pensjonskontoer ennå',
      nn: 'Ingen investerings- eller pensjonskontoar enno',
      fi: 'Ei vielä sijoitus- tai eläketilejä',
      is: 'Engir fjárfestingar- eða eftirlaunareikningar enn',
      fo: 'Ongar íløgu- ella eftirlønarkontur enn',
      cs: 'Zatím žádné investiční ani důchodové účty',
      bg: 'Все още няма инвестиционни или пенсионни сметки',
      hr: 'Još nema investicijskih ni mirovinskih računa',
      sr: 'Још нема инвестиционих ни пензијских рачуна',
      sl: 'Še ni naložbenih ali pokojninskih računov',
      mk: 'Сè уште нема инвестициски или пензиски сметки',
      be: 'Пакуль няма інвестыцыйных або пенсійных рахункаў',
      bs: 'Još nema investicijskih ni penzionih računa',
      hsb: 'Hišće žane inwesticijske abo wuměnkowe konta',
    }),
    delete: t({
      ru: 'Удалить',
      en: 'Delete',
      kk: 'Жою',
      de: 'Löschen',
      fr: 'Supprimer',
      es: 'Eliminar',
      pt: 'Eliminar',
      tr: 'Sil',
      uk: 'Видалити',
      zh: '删除',
      pl: 'Usuń',
      it: 'Elimina',
      sk: 'Odstrániť',
      ja: '削除',
      ko: '삭제',
      hi: 'हटाएं',
      nl: 'Verwijderen',
      sv: 'Ta bort',
      vi: 'Xóa',
      id: 'Hapus',
      da: 'Slet',
      nb: 'Slett',
      nn: 'Slett',
      fi: 'Poista',
      is: 'Eyða',
      fo: 'Strika',
      cs: 'Smazat',
      bg: 'Изтрий',
      hr: 'Izbriši',
      sr: 'Избриши',
      sl: 'Izbriši',
      mk: 'Избриши',
      be: 'Выдаліць',
      bs: 'Izbriši',
      hsb: 'Zhašeć',
    }),
    save: t({
      ru: 'Сохранить',
      en: 'Save',
      kk: 'Сақтау',
      de: 'Speichern',
      fr: 'Enregistrer',
      es: 'Guardar',
      pt: 'Guardar',
      tr: 'Kaydet',
      uk: 'Зберегти',
      zh: '保存',
      pl: 'Zapisz',
      it: 'Salva',
      sk: 'Uložiť',
      ja: '保存',
      ko: '저장',
      hi: 'सहेजें',
      nl: 'Opslaan',
      sv: 'Spara',
      vi: 'Lưu',
      id: 'Simpan',
      da: 'Gem',
      nb: 'Lagre',
      nn: 'Lagre',
      fi: 'Tallenna',
      is: 'Vista',
      fo: 'Goym',
      cs: 'Uložit',
      bg: 'Запази',
      hr: 'Spremi',
      sr: 'Сачувај',
      sl: 'Shrani',
      mk: 'Зачувај',
      be: 'Захаваць',
      bs: 'Sačuvaj',
      hsb: 'Składować',
    }),
    manualPrice: t({
      ru: 'вручную',
      en: 'manual',
      kk: 'қолмен',
      de: 'manuell',
      fr: 'manuel',
      es: 'manual',
      pt: 'manual',
      tr: 'elle',
      uk: 'вручну',
      zh: '手动',
      pl: 'ręcznie',
      it: 'manuale',
      sk: 'ručne',
      ja: '手動',
      ko: '수동',
      hi: 'मैन्युअल',
      nl: 'handmatig',
      sv: 'manuellt',
      vi: 'thủ công',
      id: 'manual',
      da: 'manuel',
      nb: 'manuell',
      nn: 'manuell',
      fi: 'käsin',
      is: 'handvirkt',
      fo: 'við hond',
      cs: 'ručně',
      bg: 'ръчно',
      hr: 'ručno',
      sr: 'ручно',
      sl: 'ročno',
      mk: 'рачно',
      be: 'уручную',
      bs: 'ručno',
      hsb: 'manuelnje',
    }),
    failed: t({
      ru: 'Не удалось сохранить',
      en: 'Could not save',
      kk: 'Сақтау мүмкін болмады',
      de: 'Konnte nicht gespeichert werden',
      fr: 'Impossible d’enregistrer',
      es: 'No se pudo guardar',
      pt: 'Não foi possível guardar',
      tr: 'Kaydedilemedi',
      uk: 'Не вдалося зберегти',
      zh: '无法保存',
      pl: 'Nie udało się zapisać',
      it: 'Impossibile salvare',
      sk: 'Nepodarilo sa uložiť',
      ja: '保存できませんでした',
      ko: '저장하지 못했습니다',
      hi: 'सहेज नहीं सका',
      nl: 'Kon niet opslaan',
      sv: 'Kunde inte spara',
      vi: 'Không lưu được',
      id: 'Tidak dapat menyimpan',
      da: 'Kunne ikke gemme',
      nb: 'Kunne ikke lagre',
      nn: 'Kunne ikkje lagre',
      fi: 'Tallennus epäonnistui',
      is: 'Ekki tókst að vista',
      fo: 'Tað eydnaðist ikki at goyma',
      cs: 'Uložení se nezdařilo',
      bg: 'Не можа да се запази',
      hr: 'Spremanje nije uspjelo',
      sr: 'Чување није успело',
      sl: 'Shranjevanje ni uspelo',
      mk: 'Не може да се зачува',
      be: 'Не ўдалося захаваць',
      bs: 'Spremanje nije uspjelo',
      hsb: 'Składowanje njeje so poradźiło',
    }),
    rangeAll: t({
      ru: 'Всё время',
      en: 'All',
      kk: 'Барлығы',
      de: 'Gesamt',
      fr: 'Tout',
      es: 'Todo',
      pt: 'Tudo',
      tr: 'Tümü',
      uk: 'Увесь час',
      zh: '全部',
      pl: 'Całość',
      it: 'Tutto',
      sk: 'Všetko',
      ja: '全期間',
      ko: '전체',
      hi: 'सभी',
      nl: 'Alles',
      sv: 'Allt',
      vi: 'Tất cả',
      id: 'Semua',
      da: 'Alle',
      nb: 'Alle',
      nn: 'Alle',
      fi: 'Kaikki',
      is: 'Allt',
      fo: 'Allar',
      cs: 'Vše',
      bg: 'Всички',
      hr: 'Sve',
      sr: 'Све',
      sl: 'Vse',
      mk: 'Сите',
      be: 'Усе',
      bs: 'Sve',
      hsb: 'Wšě',
    }),
  },
} satisfies Dictionary;

export default content;
