// @vitest-environment jsdom
import { describe, expect, it, vi } from 'vitest';

vi.mock('intlayer', () => ({
  t: (value: unknown) => value,
}));

import { makeCloudStorageContent } from './make-cloud-storage-content';

describe('makeCloudStorageContent', () => {
  it('builds common integration content with provider-specific labels', () => {
    const dropbox = makeCloudStorageContent({
      key: 'dropboxIntegrationPage',
      name: {
        ru: 'Dropbox',
        en: 'Dropbox',
        kk: 'Dropbox',
        de: 'Dropbox',
        fr: 'Dropbox',
        es: 'Dropbox',
        pt: 'Dropbox',
        tr: 'Dropbox',
        uk: 'Dropbox',
        zh: 'Dropbox',
        ar: 'Dropbox',
        pl: 'Dropbox',
        it: 'Dropbox',
        sk: 'Dropbox',
        ja: 'Dropbox',
        ko: 'Dropbox',
        hi: 'Dropbox',
        nl: 'Dropbox',
        sv: 'Dropbox',
        vi: 'Dropbox',
        id: 'Dropbox',
      },
      folderLabel: {
        ru: 'Папка в Dropbox',
        en: 'Dropbox folder',
        kk: 'Dropbox қалтасы',
        de: 'Dropbox-Ordner',
        fr: 'Dossier Dropbox',
        es: 'Carpeta de Dropbox',
        pt: 'Pasta do Dropbox',
        tr: 'Dropbox klasörü',
        uk: 'Папка в Dropbox',
        zh: 'Dropbox 文件夹',
        ar: 'مجلد Dropbox',
        pl: 'Folder Dropbox',
        it: 'Cartella Dropbox',
        sk: 'Folder Dropbox',
        ja: 'Dropboxフォルダ',
        ko: 'Dropbox 폴더',
        hi: 'Dropbox फ़ोल्डर',
        nl: 'Dropbox-map',
        sv: 'Dropbox-mapp',
        vi: 'Thư mục Dropbox',
        id: 'Folder Dropbox',
      },
      connectingLabel: {
        ru: 'Открываем авторизацию Dropbox…',
        en: 'Opening Dropbox authorization…',
        kk: 'Dropbox авторизациясы ашылуда…',
        de: 'Dropbox-Autorisierung wird geöffnet…',
        fr: "Ouverture de l'autorisation Dropbox…",
        es: 'Abriendo autorización de Dropbox…',
        pt: 'Abrindo autorização do Dropbox…',
        tr: 'Dropbox yetkilendirmesi açılıyor…',
        uk: 'Відкриваємо авторизацію Dropbox…',
        zh: '正在打开 Dropbox 授权…',
        ar: 'جارٍ فتح تفويض Dropbox…',
        pl: 'Otwieranie autoryzacji Dropbox…',
        it: 'Apertura autorizzazione Dropbox…',
        sk: 'Otwieranie autoryzacji Dropbox…',
        ja: 'Dropbox認証を開いています…',
        ko: 'Dropbox 인증을 여는 중…',
        hi: 'Dropbox प्राधिकरण खोला जा रहा है…',
        nl: 'Dropbox-autorisatie openen…',
        sv: 'Öppnar Dropbox-auktorisering…',
        vi: 'Đang mở xác thực Dropbox…',
        id: 'Membuka otorisasi Dropbox…',
      },
      connectedLabel: {
        ru: 'Dropbox подключен',
        en: 'Dropbox connected',
        kk: 'Dropbox қосылды',
        de: 'Dropbox verbunden',
        fr: 'Dropbox connecté',
        es: 'Dropbox conectado',
        pt: 'Dropbox conectado',
        tr: 'Dropbox bağlandı',
        uk: 'Dropbox підключено',
        zh: 'Dropbox 已连接',
        ar: 'تم توصيل Dropbox',
        pl: 'Dropbox połączony',
        it: 'Dropbox connesso',
        sk: 'Dropbox połączony',
        ja: 'Dropboxが接続されました',
        ko: 'Dropbox 연결됨',
        hi: 'Dropbox कनेक्ट हो गया',
        nl: 'Dropbox verbonden',
        sv: 'Dropbox ansluten',
        vi: 'Dropbox đã kết nối',
        id: 'Dropbox terhubung',
      },
      pickerUnavailableLabel: {
        ru: 'Dropbox Chooser недоступен',
        en: 'Dropbox Chooser is unavailable',
        kk: 'Dropbox Chooser қолжетімсіз',
        de: 'Dropbox Chooser ist nicht verfügbar',
        fr: 'Dropbox Chooser est indisponible',
        es: 'Dropbox Chooser no está disponible',
        pt: 'Dropbox Chooser não está disponível',
        tr: 'Dropbox Chooser kullanılamıyor',
        uk: 'Dropbox Chooser недоступний',
        zh: 'Dropbox Chooser 不可用',
        ar: 'Dropbox Chooser غير متاح',
        pl: 'Dropbox Chooser jest niedostępny',
        it: 'Dropbox Chooser non disponibile',
        sk: 'Dropbox',
        ja: 'Dropbox Chooserは利用できません',
        ko: 'Dropbox Chooser를 사용할 수 없습니다',
        hi: 'Dropbox Chooser अनुपलब्ध है',
        nl: 'Dropbox Chooser is niet beschikbaar',
        sv: 'Dropbox Chooser är inte tillgänglig',
        vi: 'Dropbox Chooser không khả dụng',
        id: 'Dropbox Chooser tidak tersedia',
      },
    });

    const drive = makeCloudStorageContent({
      key: 'googleDriveIntegrationPage',
      name: {
        ru: 'Google Drive',
        en: 'Google Drive',
        kk: 'Google Drive',
        de: 'Google Drive',
        fr: 'Google Drive',
        es: 'Google Drive',
        pt: 'Google Drive',
        tr: 'Google Drive',
        uk: 'Google Drive',
        zh: 'Google Drive',
        ar: 'Google Drive',
        pl: 'Google Drive',
        it: 'Google Drive',
        sk: 'Google Drive',
        ja: 'Google Drive',
        ko: 'Google Drive',
        hi: 'Google Drive',
        nl: 'Google Drive',
        sv: 'Google Drive',
        vi: 'Google Drive',
        id: 'Google Drive',
      },
      folderLabel: {
        ru: 'Папка в Drive',
        en: 'Drive folder',
        kk: 'Drive қалтасы',
        de: 'Drive-Ordner',
        fr: 'Dossier Drive',
        es: 'Carpeta de Drive',
        pt: 'Pasta do Drive',
        tr: 'Drive klasörü',
        uk: 'Папка в Drive',
        zh: 'Drive 文件夹',
        ar: 'مجلد Drive',
        pl: 'Folder Drive',
        it: 'Cartella Drive',
        sk: 'Folder Drive',
        ja: 'Driveフォルダ',
        ko: 'Drive 폴더',
        hi: 'Drive फ़ोल्डर',
        nl: 'Drive-map',
        sv: 'Drive-mapp',
        vi: 'Thư mục Drive',
        id: 'Folder Drive',
      },
      connectingLabel: {
        ru: 'Открываем авторизацию Google…',
        en: 'Opening Google authorization…',
        kk: 'Google авторизациясы ашылуда…',
        de: 'Google-Autorisierung wird geöffnet…',
        fr: "Ouverture de l'autorisation Google…",
        es: 'Abriendo autorización de Google…',
        pt: 'Abrindo autorização do Google…',
        tr: 'Google yetkilendirmesi açılıyor…',
        uk: 'Відкриваємо авторизацію Google…',
        zh: '正在打开 Google 授权…',
        ar: 'جارٍ فتح تفويض Google…',
        pl: 'Otwieranie autoryzacji Google…',
        it: 'Apertura autorizzazione Google…',
        sk: 'Otwieranie autoryzacji Google…',
        ja: 'Google認証を開いています…',
        ko: 'Google 인증을 여는 중…',
        hi: 'Google प्राधिकरण खोला जा रहा है…',
        nl: 'Google-autorisatie openen…',
        sv: 'Öppnar Google-auktorisering…',
        vi: 'Đang mở xác thực Google…',
        id: 'Membuka otorisasi Google…',
      },
      connectedLabel: {
        ru: 'Google Drive подключен',
        en: 'Google Drive connected',
        kk: 'Google Drive қосылды',
        de: 'Google Drive verbunden',
        fr: 'Google Drive connecté',
        es: 'Google Drive conectado',
        pt: 'Google Drive conectado',
        tr: 'Google Drive bağlandı',
        uk: 'Google Drive підключено',
        zh: 'Google Drive 已连接',
        ar: 'تم توصيل Google Drive',
        pl: 'Google Drive połączony',
        it: 'Google Drive connesso',
        sk: 'Google Drive połączony',
        ja: 'Google Driveが接続されました',
        ko: 'Google Drive 연결됨',
        hi: 'Google Drive कनेक्ट हो गया',
        nl: 'Google Drive verbonden',
        sv: 'Google Drive ansluten',
        vi: 'Google Drive đã kết nối',
        id: 'Google Drive terhubung',
      },
      pickerUnavailableLabel: {
        ru: 'Google Picker недоступен',
        en: 'Google Picker is unavailable',
        kk: 'Google Picker қолжетімсіз',
        de: 'Google Picker ist nicht verfügbar',
        fr: 'Google Picker est indisponible',
        es: 'Google Picker no está disponible',
        pt: 'Google Picker não está disponível',
        tr: 'Google Picker kullanılamıyor',
        uk: 'Google Picker недоступний',
        zh: 'Google Picker 不可用',
        ar: 'Google Picker غير متاح',
        pl: 'Google Picker jest niedostępny',
        it: 'Google Picker non disponibile',
        sk: 'Google Drive',
        ja: 'Google Pickerは利用できません',
        ko: 'Google Picker를 사용할 수 없습니다',
        hi: 'Google Picker अनुपलब्ध है',
        nl: 'Google Picker is niet beschikbaar',
        sv: 'Google Picker är inte tillgänglig',
        vi: 'Google Picker không khả dụng',
        id: 'Google Picker tidak tersedia',
      },
    });

    expect(dropbox.key).toBe('dropboxIntegrationPage');
    expect(drive.key).toBe('googleDriveIntegrationPage');
    expect(dropbox.content.header.subtitle).toEqual({
      ru: 'Подключите Dropbox, чтобы синхронизировать выписки и импортировать файлы.',
      en: 'Connect Dropbox to sync statements and import files.',
      kk: 'Үзінділерді синхрондау және файлдарды импорттау үшін Dropbox қосыңыз.',
      de: 'Verbinden Sie Dropbox, um Kontoauszüge zu synchronisieren und Dateien zu importieren.',
      fr: 'Connectez Dropbox pour synchroniser les relevés et importer des fichiers.',
      es: 'Conecta Dropbox para sincronizar extractos e importar archivos.',
      pt: 'Conecte o Dropbox para sincronizar extratos e importar arquivos.',
      tr: "Ekstreleri senkronize etmek ve dosya içe aktarmak için Dropbox'ı bağlayın.",
      uk: 'Підключіть Dropbox, щоб синхронізувати виписки та імпортувати файли.',
      zh: '连接 Dropbox 以同步账单并导入文件。',
      ar: 'قم بتوصيل Dropbox لمزامنة الكشوفات واستيراد الملفات.',
      pl: 'Połącz Dropbox, aby synchronizować wyciągi i importować pliki.',
      it: 'Connetti Dropbox per sincronizzare gli estratti e importare file.',
      sk: 'Połącz Dropbox, aby synchronizować wyciągi i importować pliki.',
      ja: 'Connect Dropbox to sync statements and import files.',
      ko: 'Connect Dropbox to sync statements and import files.',
      hi: 'Connect Dropbox to sync statements and import files.',
      nl: 'Connect Dropbox to sync statements and import files.',
      sv: 'Connect Dropbox to sync statements and import files.',
      vi: 'Connect Dropbox to sync statements and import files.',
      id: 'Connect Dropbox to sync statements and import files.',
    });
    expect(drive.content.header.subtitle).toEqual({
      ru: 'Подключите Google Drive, чтобы синхронизировать выписки и импортировать файлы.',
      en: 'Connect Google Drive to sync statements and import files.',
      kk: 'Үзінділерді синхрондау және файлдарды импорттау үшін Google Drive қосыңыз.',
      de: 'Verbinden Sie Google Drive, um Kontoauszüge zu synchronisieren und Dateien zu importieren.',
      fr: 'Connectez Google Drive pour synchroniser les relevés et importer des fichiers.',
      es: 'Conecta Google Drive para sincronizar extractos e importar archivos.',
      pt: 'Conecte o Google Drive para sincronizar extratos e importar arquivos.',
      tr: "Ekstreleri senkronize etmek ve dosya içe aktarmak için Google Drive'ı bağlayın.",
      uk: 'Підключіть Google Drive, щоб синхронізувати виписки та імпортувати файли.',
      zh: '连接 Google Drive 以同步账单并导入文件。',
      ar: 'قم بتوصيل Google Drive لمزامنة الكشوفات واستيراد الملفات.',
      pl: 'Połącz Google Drive, aby synchronizować wyciągi i importować pliki.',
      it: 'Connetti Google Drive per sincronizzare gli estratti e importare file.',
      sk: 'Połącz Google Drive, aby synchronizować wyciągi i importować pliki.',
      ja: 'Connect Google Drive to sync statements and import files.',
      ko: 'Connect Google Drive to sync statements and import files.',
      hi: 'Connect Google Drive to sync statements and import files.',
      nl: 'Connect Google Drive to sync statements and import files.',
      sv: 'Connect Google Drive to sync statements and import files.',
      vi: 'Connect Google Drive to sync statements and import files.',
      id: 'Connect Google Drive to sync statements and import files.',
    });

    expect(dropbox.content.loading).toEqual(drive.content.loading);
    expect(dropbox.content.status.connected).toEqual(drive.content.status.connected);
    expect(dropbox.content.actions.syncNow).toEqual(drive.content.actions.syncNow);
    expect(dropbox.content.settings.folder).toEqual({
      ru: 'Папка в Dropbox',
      en: 'Dropbox folder',
      kk: 'Dropbox қалтасы',
      de: 'Dropbox-Ordner',
      fr: 'Dossier Dropbox',
      es: 'Carpeta de Dropbox',
      pt: 'Pasta do Dropbox',
      tr: 'Dropbox klasörü',
      uk: 'Папка в Dropbox',
      zh: 'Dropbox 文件夹',
      ar: 'مجلد Dropbox',
      pl: 'Folder Dropbox',
      it: 'Cartella Dropbox',
      sk: 'Folder Dropbox',
      ja: 'Dropboxフォルダ',
      ko: 'Dropbox 폴더',
      hi: 'Dropbox फ़ोल्डर',
      nl: 'Dropbox-map',
      sv: 'Dropbox-mapp',
      vi: 'Thư mục Dropbox',
      id: 'Folder Dropbox',
    });
    expect(drive.content.settings.folder).toEqual({
      ru: 'Папка в Drive',
      en: 'Drive folder',
      kk: 'Drive қалтасы',
      de: 'Drive-Ordner',
      fr: 'Dossier Drive',
      es: 'Carpeta de Drive',
      pt: 'Pasta do Drive',
      tr: 'Drive klasörü',
      uk: 'Папка в Drive',
      zh: 'Drive 文件夹',
      ar: 'مجلد Drive',
      pl: 'Folder Drive',
      it: 'Cartella Drive',
      sk: 'Folder Drive',
      ja: 'Driveフォルダ',
      ko: 'Drive 폴더',
      hi: 'Drive फ़ोल्डर',
      nl: 'Drive-map',
      sv: 'Drive-mapp',
      vi: 'Thư mục Drive',
      id: 'Folder Drive',
    });
    expect(dropbox.content.toasts.connecting).toEqual({
      ru: 'Открываем авторизацию Dropbox…',
      en: 'Opening Dropbox authorization…',
      kk: 'Dropbox авторизациясы ашылуда…',
      de: 'Dropbox-Autorisierung wird geöffnet…',
      fr: "Ouverture de l'autorisation Dropbox…",
      es: 'Abriendo autorización de Dropbox…',
      pt: 'Abrindo autorização do Dropbox…',
      tr: 'Dropbox yetkilendirmesi açılıyor…',
      uk: 'Відкриваємо авторизацію Dropbox…',
      zh: '正在打开 Dropbox 授权…',
      ar: 'جارٍ فتح تفويض Dropbox…',
      pl: 'Otwieranie autoryzacji Dropbox…',
      it: 'Apertura autorizzazione Dropbox…',
      sk: 'Otwieranie autoryzacji Dropbox…',
      ja: 'Dropbox認証を開いています…',
      ko: 'Dropbox 인증을 여는 중…',
      hi: 'Dropbox प्राधिकरण खोला जा रहा है…',
      nl: 'Dropbox-autorisatie openen…',
      sv: 'Öppnar Dropbox-auktorisering…',
      vi: 'Đang mở xác thực Dropbox…',
      id: 'Membuka otorisasi Dropbox…',
    });
    expect(drive.content.errors.pickerUnavailable).toEqual({
      ru: 'Google Picker недоступен',
      en: 'Google Picker is unavailable',
      kk: 'Google Picker қолжетімсіз',
      de: 'Google Picker ist nicht verfügbar',
      fr: 'Google Picker est indisponible',
      es: 'Google Picker no está disponible',
      pt: 'Google Picker não está disponível',
      tr: 'Google Picker kullanılamıyor',
      uk: 'Google Picker недоступний',
      zh: 'Google Picker 不可用',
      ar: 'Google Picker غير متاح',
      pl: 'Google Picker jest niedostępny',
      it: 'Google Picker non disponibile',
      sk: 'Google Drive',
      ja: 'Google Pickerは利用できません',
      ko: 'Google Picker를 사용할 수 없습니다',
      hi: 'Google Picker अनुपलब्ध है',
      nl: 'Google Picker is niet beschikbaar',
      sv: 'Google Picker är inte tillgänglig',
      vi: 'Google Picker không khả dụng',
      id: 'Google Picker tidak tersedia',
    });
  });
});
