import { type Dictionary, t } from 'intlayer';

type LocalizedLabel = {
  ru: string;
  en: string;
  kk: string;
  de: string;
  fr: string;
  es: string;
  pt: string;
  tr: string;
  uk: string;
  zh: string;
  ar: string;
  pl: string;
  it: string;
  sk: string;
  ja: string;
  ko: string;
  hi: string;
  nl: string;
  sv: string;
  vi: string;
  id: string;
  da: string;
  nb: string;
  nn: string;
  fi: string;
  is: string;
  fo: string;
  cs: string;
  bg: string;
  hr: string;
  sr: string;
  sl: string;
  mk: string;
  be: string;
  bs: string;
  hsb: string;
};

type CloudStorageProvider = {
  key: string;
  name: LocalizedLabel;
  folderLabel: LocalizedLabel;
  connectingLabel: LocalizedLabel;
  connectedLabel: LocalizedLabel;
  pickerUnavailableLabel: LocalizedLabel;
};

// eslint-disable-next-line max-lines-per-function, @typescript-eslint/explicit-function-return-type, @typescript-eslint/explicit-module-boundary-types
export const makeCloudStorageContent = (provider: CloudStorageProvider) => {
  return {
    key: provider.key,
    content: {
      loading: t({
        ru: 'Загрузка...',
        en: 'Loading...',
        kk: 'Жүктелуде...',
        de: 'Laden...',
        fr: 'Chargement...',
        es: 'Cargando...',
        pt: 'Carregando...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '加载中...',
        ar: 'جارٍ التحميل...',
        pl: 'Ładowanie...',
        it: 'Caricamento...',
        sk: 'Načítava sa...',
        ja: '読み込み中...',
        ko: '불러오는 중...',
        hi: 'लोड हो रहा है...',
        nl: 'Laden...',
        sv: 'Laddar...',
        vi: 'Đang tải...',
        id: 'Memuat...',
        da: 'Indlæser...',
        nb: 'Laster...',
        nn: 'Lastar...',
        fi: 'Ladataan...',
        is: 'Hleð...',
        fo: 'Lesi...',
        cs: 'Načítání...',
        bg: 'Зарежда...',
        hr: 'Učitavanje...',
        sr: 'Учитавање...',
        sl: 'Nalaganje...',
        mk: 'Се вчитува...',
        be: 'Загрузка...',
        bs: 'Učitavanje...',
        hsb: 'Začituje so...',
      }),
      header: {
        title: t(provider.name),
        subtitle: t({
          ru: `Подключите ${provider.name.ru}, чтобы синхронизировать выписки и импортировать файлы.`,
          en: `Connect ${provider.name.en} to sync statements and import files.`,
          kk: `Үзінділерді синхрондау және файлдарды импорттау үшін ${provider.name.kk} қосыңыз.`,
          de: `Verbinden Sie ${provider.name.de}, um Kontoauszüge zu synchronisieren und Dateien zu importieren.`,
          fr: `Connectez ${provider.name.fr} pour synchroniser les relevés et importer des fichiers.`,
          es: `Conecta ${provider.name.es} para sincronizar extractos e importar archivos.`,
          pt: `Conecte o ${provider.name.pt} para sincronizar extratos e importar arquivos.`,
          tr: `Ekstreleri senkronize etmek ve dosya içe aktarmak için ${provider.name.tr}'ı bağlayın.`,
          uk: `Підключіть ${provider.name.uk}, щоб синхронізувати виписки та імпортувати файли.`,
          zh: `连接 ${provider.name.zh} 以同步账单并导入文件。`,
          ar: `قم بتوصيل ${provider.name.ar} لمزامنة الكشوفات واستيراد الملفات.`,
          pl: `Połącz ${provider.name.pl}, aby synchronizować wyciągi i importować pliki.`,
          it: `Connetti ${provider.name.it} per sincronizzare gli estratti e importare file.`,
          sk: `Pripojte ${provider.name.sk}, aby ste mohli synchronizovať výpisy a importovať súbory.`,
          ja: `${provider.name.ja} を接続して、明細を同期しファイルをインポートします。`,
          ko: `${provider.name.ko}을(를) 연결하여 명세서를 동기화하고 파일을 가져오세요.`,
          hi: `स्टेटमेंट सिंक करने और फ़ाइलें आयात करने के लिए ${provider.name.hi} कनेक्ट करें।`,
          nl: `Koppel ${provider.name.nl} om afschriften te synchroniseren en bestanden te importeren.`,
          sv: `Anslut ${provider.name.sv} för att synkronisera kontoutdrag och importera filer.`,
          vi: `Kết nối ${provider.name.vi} để đồng bộ sao kê và nhập tệp.`,
          id: `Hubungkan ${provider.name.id} untuk menyinkronkan laporan mutasi dan mengimpor file.`,
          da: `Forbind ${provider.name.da} for at synkronisere kontoudtog og importere filer.`,
          nb: `Koble til ${provider.name.nb} for å synkronisere kontoutskrifter og importere filer.`,
          nn: `Kople til ${provider.name.nn} for å synkronisere kontoutskrifter og importere filer.`,
          fi: `Yhdistä ${provider.name.fi} tiliotteiden synkronointiin ja tiedostojen tuontiin.`,
          is: `Tengdu ${provider.name.is} til að samstilla yfirlit og flytja inn skrár.`,
          fo: `Knýt ${provider.name.fo} fyri at samstilla kontoúrtøk og flyta fílur inn.`,
          cs: `Připojte ${provider.name.cs} pro synchronizaci výpisů a import souborů.`,
          bg: `Свържете ${provider.name.bg}, за да синхронизирате извлечения и импортирате файлове.`,
          hr: `Povežite ${provider.name.hr} za sinkronizaciju izvoda i uvoz datoteka.`,
          sr: `Повежите ${provider.name.sr} за синхронизацију извода и увоз датотека.`,
          sl: `Povežite ${provider.name.sl} za sinhronizacijo izpiskov in uvoz datotek.`,
          mk: `Поврзете ${provider.name.mk} за синхронизација на изводи и увоз на датотеки.`,
          be: `Падключыце ${provider.name.be}, каб сінхранізаваць выпіскі і імпартаваць файлы.`,
          bs: `Povežite ${provider.name.bs} za sinhronizaciju izvoda i uvoz datoteka.`,
          hsb: `Zwjazajće ${provider.name.hsb}, zo byšće wupisy synchronizował a dataje importował.`,
        }),
      },
      status: {
        connected: t({
          ru: 'Подключено',
          en: 'Connected',
          kk: 'Қосылған',
          de: 'Verbunden',
          fr: 'Connecté',
          es: 'Conectado',
          pt: 'Conectado',
          tr: 'Bağlı',
          uk: 'Підключено',
          zh: '已连接',
          ar: 'متصل',
          pl: 'Połączone',
          it: 'Connesso',
          sk: 'Pripojené',
          ja: '接続済み',
          ko: '연결됨',
          hi: 'कनेक्टेड',
          nl: 'Verbonden',
          sv: 'Ansluten',
          vi: 'Đã kết nối',
          id: 'Terhubung',
          da: 'Forbundet',
          nb: 'Tilkoblet',
          nn: 'Tilkopla',
          fi: 'Yhdistetty',
          is: 'Tengt',
          fo: 'Knýtt',
          cs: 'Připojeno',
          bg: 'Свързано',
          hr: 'Povezano',
          sr: 'Повезано',
          sl: 'Povezano',
          mk: 'Поврзано',
          be: 'Падключана',
          bs: 'Povezano',
          hsb: 'Zwjazane',
        }),
        disconnected: t({
          ru: 'Не подключено',
          en: 'Not connected',
          kk: 'Қосылмаған',
          de: 'Nicht verbunden',
          fr: 'Non connecté',
          es: 'No conectado',
          pt: 'Não conectado',
          tr: 'Bağlı değil',
          uk: 'Не підключено',
          zh: '未连接',
          ar: 'غير متصل',
          pl: 'Niepołączone',
          it: 'Non connesso',
          sk: 'Nepripojené',
          ja: '未接続',
          ko: '연결되지 않음',
          hi: 'कनेक्ट नहीं है',
          nl: 'Niet verbonden',
          sv: 'Inte ansluten',
          vi: 'Chưa kết nối',
          id: 'Tidak terhubung',
          da: 'Ikke forbundet',
          nb: 'Ikke tilkoblet',
          nn: 'Ikkje tilkopla',
          fi: 'Ei yhdistetty',
          is: 'Ekki tengt',
          fo: 'Ikki knýtt',
          cs: 'Nepřipojeno',
          bg: 'Не е свързано',
          hr: 'Nije povezano',
          sr: 'Није повезано',
          sl: 'Ni povezano',
          mk: 'Не е поврзано',
          be: 'Не падключана',
          bs: 'Nije povezano',
          hsb: 'Njezwjazane',
        }),
        needsReauth: t({
          ru: 'Требуется повторная авторизация',
          en: 'Reauthorization required',
          kk: 'Қайта авторизация қажет',
          de: 'Erneute Autorisierung erforderlich',
          fr: 'Réautorisation requise',
          es: 'Reautorización requerida',
          pt: 'Reautorização necessária',
          tr: 'Yeniden yetkilendirme gerekiyor',
          uk: 'Потрібна повторна авторизація',
          zh: '需要重新授权',
          ar: 'يتطلب إعادة التفويض',
          pl: 'Wymagana ponowna autoryzacja',
          it: 'Riautorizzazione richiesta',
          sk: 'Vyžaduje sa opätovná autorizácia',
          ja: '再認証が必要です',
          ko: '재인증이 필요합니다',
          hi: 'फिर से प्राधिकरण आवश्यक है',
          nl: 'Opnieuw autoriseren vereist',
          sv: 'Ny auktorisering krävs',
          vi: 'Cần xác thực lại',
          id: 'Perlu otorisasi ulang',
          da: 'Ny godkendelse påkrævet',
          nb: 'Ny autorisasjon kreves',
          nn: 'Ny autorisasjon krevst',
          fi: 'Uusi valtuutus vaaditaan',
          is: 'Ný heimild þarf',
          fo: 'Ný heimild krevst',
          cs: 'Je potřeba nová autorizace',
          bg: 'Нужна е нова оторизация',
          hr: 'Potrebna je nova autorizacija',
          sr: 'Потребна је нова ауторизација',
          sl: 'Potrebna je nova pooblastitev',
          mk: 'Потребно е ново овластување',
          be: 'Патрэбна новая аўтарызацыя',
          bs: 'Potrebna je nova autorizacija',
          hsb: 'Nowa awtorizacija trěbna',
        }),
      },
      actions: {
        connect: t({
          ru: 'Подключить',
          en: 'Connect',
          kk: 'Қосу',
          de: 'Verbinden',
          fr: 'Connecter',
          es: 'Conectar',
          pt: 'Conectar',
          tr: 'Bağlan',
          uk: 'Підключити',
          zh: '连接',
          ar: 'اتصال',
          pl: 'Połącz',
          it: 'Connetti',
          sk: 'Pripojiť',
          ja: '接続',
          ko: '연결',
          hi: 'कनेक्ट करें',
          nl: 'Verbinden',
          sv: 'Anslut',
          vi: 'Kết nối',
          id: 'Hubungkan',
          da: 'Forbind',
          nb: 'Koble til',
          nn: 'Kople til',
          fi: 'Yhdistä',
          is: 'Tengja',
          fo: 'Knýt',
          cs: 'Připojit',
          bg: 'Свържи',
          hr: 'Poveži',
          sr: 'Повежи',
          sl: 'Poveži',
          mk: 'Поврзи',
          be: 'Падключыць',
          bs: 'Poveži',
          hsb: 'Zwjazać',
        }),
        reconnect: t({
          ru: 'Переподключить',
          en: 'Reconnect',
          kk: 'Қайта қосу',
          de: 'Erneut verbinden',
          fr: 'Reconnecter',
          es: 'Reconectar',
          pt: 'Reconectar',
          tr: 'Yeniden bağlan',
          uk: 'Перепідключити',
          zh: '重新连接',
          ar: 'إعادة الاتصال',
          pl: 'Połącz ponownie',
          it: 'Riconnetti',
          sk: 'Znova pripojiť',
          ja: '再接続',
          ko: '다시 연결',
          hi: 'फिर से कनेक्ट करें',
          nl: 'Opnieuw verbinden',
          sv: 'Anslut igen',
          vi: 'Kết nối lại',
          id: 'Hubungkan ulang',
          da: 'Forbind igen',
          nb: 'Koble til på nytt',
          nn: 'Kople til på nytt',
          fi: 'Yhdistä uudelleen',
          is: 'Tengja aftur',
          fo: 'Knýt aftur',
          cs: 'Připojit znovu',
          bg: 'Свържи отново',
          hr: 'Poveži ponovno',
          sr: 'Повежи поново',
          sl: 'Poveži znova',
          mk: 'Поврзи повторно',
          be: 'Падключыць зноў',
          bs: 'Poveži ponovo',
          hsb: 'Zaso zwjazać',
        }),
        disconnect: t({
          ru: 'Отключить',
          en: 'Disconnect',
          kk: 'Ажырату',
          de: 'Trennen',
          fr: 'Déconnecter',
          es: 'Desconectar',
          pt: 'Desconectar',
          tr: 'Bağlantıyı kes',
          uk: 'Відключити',
          zh: '断开连接',
          ar: 'قطع الاتصال',
          pl: 'Rozłącz',
          it: 'Disconnetti',
          sk: 'Odpojiť',
          ja: '接続解除',
          ko: '연결 해제',
          hi: 'डिस्कनेक्ट करें',
          nl: 'Verbinding verbreken',
          sv: 'Koppla från',
          vi: 'Ngắt kết nối',
          id: 'Putuskan',
          da: 'Afbryd',
          nb: 'Koble fra',
          nn: 'Kople frå',
          fi: 'Katkaise yhteys',
          is: 'Aftengja',
          fo: 'Skilja frá',
          cs: 'Odpojit',
          bg: 'Изключи',
          hr: 'Odspoji',
          sr: 'Искључи',
          sl: 'Odklopi',
          mk: 'Исклучи',
          be: 'Адключыць',
          bs: 'Odspoji',
          hsb: 'Wotdźělić',
        }),
        syncNow: t({
          ru: 'Синхронизировать сейчас',
          en: 'Sync now',
          kk: 'Қазір синхрондау',
          de: 'Jetzt synchronisieren',
          fr: 'Synchroniser maintenant',
          es: 'Sincronizar ahora',
          pt: 'Sincronizar agora',
          tr: 'Şimdi senkronize et',
          uk: 'Синхронізувати зараз',
          zh: '立即同步',
          ar: 'مزامنة الآن',
          pl: 'Synchronizuj teraz',
          it: 'Sincronizza ora',
          sk: 'Synchronizovať teraz',
          ja: '今すぐ同期',
          ko: '지금 동기화',
          hi: 'अभी सिंक करें',
          nl: 'Nu synchroniseren',
          sv: 'Synka nu',
          vi: 'Đồng bộ ngay',
          id: 'Sinkronkan sekarang',
          da: 'Synkronisér nu',
          nb: 'Synkroniser nå',
          nn: 'Synkroniser no',
          fi: 'Synkronoi nyt',
          is: 'Samstilla núna',
          fo: 'Samstilla nú',
          cs: 'Synchronizovat nyní',
          bg: 'Синхронизирай сега',
          hr: 'Sinkroniziraj sada',
          sr: 'Синхронизуј сада',
          sl: 'Sinhroniziraj zdaj',
          mk: 'Синхронизирај сега',
          be: 'Сінхранізаваць зараз',
          bs: 'Sinhronizuj sada',
          hsb: 'Nětko synchronizować',
        }),
        pickFolder: t({
          ru: 'Выбрать папку',
          en: 'Choose folder',
          kk: 'Қалта таңдау',
          de: 'Ordner auswählen',
          fr: 'Choisir un dossier',
          es: 'Elegir carpeta',
          pt: 'Escolher pasta',
          tr: 'Klasör seç',
          uk: 'Вибрати папку',
          zh: '选择文件夹',
          ar: 'اختر مجلدًا',
          pl: 'Wybierz folder',
          it: 'Scegli cartella',
          sk: 'Vybrať priečinok',
          ja: 'フォルダを選択',
          ko: '폴더 선택',
          hi: 'फ़ोल्डर चुनें',
          nl: 'Map kiezen',
          sv: 'Välj mapp',
          vi: 'Chọn thư mục',
          id: 'Pilih folder',
          da: 'Vælg mappe',
          nb: 'Velg mappe',
          nn: 'Vel mappe',
          fi: 'Valitse kansio',
          is: 'Velja möppu',
          fo: 'Vel skjáttu',
          cs: 'Vybrat složku',
          bg: 'Избери папка',
          hr: 'Odaberi mapu',
          sr: 'Изабери фасциклу',
          sl: 'Izberi mapo',
          mk: 'Избери папка',
          be: 'Выбраць папку',
          bs: 'Odaberi folder',
          hsb: 'Rjadowak wuzwolić',
        }),
      },
      settings: {
        title: t({
          ru: 'Настройки синхронизации',
          en: 'Sync settings',
          kk: 'Синхрондау баптаулары',
          de: 'Synchronisierungseinstellungen',
          fr: 'Paramètres de synchronisation',
          es: 'Configuración de sincronización',
          pt: 'Configurações de sincronização',
          tr: 'Senkronizasyon ayarları',
          uk: 'Налаштування синхронізації',
          zh: '同步设置',
          ar: 'إعدادات المزامنة',
          pl: 'Ustawienia synchronizacji',
          it: 'Impostazioni sincronizzazione',
          sk: 'Nastavenia synchronizácie',
          ja: '同期設定',
          ko: '동기화 설정',
          hi: 'सिंक सेटिंग्स',
          nl: 'Synchronisatie-instellingen',
          sv: 'Synkinställningar',
          vi: 'Cài đặt đồng bộ',
          id: 'Pengaturan sinkronisasi',
          da: 'Synkroniseringsindstillinger',
          nb: 'Synkroniseringsinnstillinger',
          nn: 'Synkroniseringsinnstillingar',
          fi: 'Synkronoinnin asetukset',
          is: 'Stillingar samstillingar',
          fo: 'Samstillingarinnstillingar',
          cs: 'Nastavení synchronizace',
          bg: 'Настройки на синхронизацията',
          hr: 'Postavke sinkronizacije',
          sr: 'Подешавања синхронизације',
          sl: 'Nastavitve sinhronizacije',
          mk: 'Поставки за синхронизација',
          be: 'Налады сінхранізацыі',
          bs: 'Postavke sinhronizacije',
          hsb: 'Nastajenja synchronizacije',
        }),
        syncEnabled: t({
          ru: 'Ежедневная синхронизация',
          en: 'Daily sync',
          kk: 'Күнделікті синхрондау',
          de: 'Tägliche Synchronisierung',
          fr: 'Synchronisation quotidienne',
          es: 'Sincronización diaria',
          pt: 'Sincronização diária',
          tr: 'Günlük senkronizasyon',
          uk: 'Щоденна синхронізація',
          zh: '每日同步',
          ar: 'مزامنة يومية',
          pl: 'Codzienna synchronizacja',
          it: 'Sincronizzazione giornaliera',
          sk: 'Denná synchronizácia',
          ja: '毎日同期',
          ko: '매일 동기화',
          hi: 'दैनिक सिंक',
          nl: 'Dagelijkse synchronisatie',
          sv: 'Daglig synkning',
          vi: 'Đồng bộ hằng ngày',
          id: 'Sinkronisasi harian',
          da: 'Daglig synkronisering',
          nb: 'Daglig synkronisering',
          nn: 'Dagleg synkronisering',
          fi: 'Päivittäinen synkronointi',
          is: 'Dagleg samstilling',
          fo: 'Daglig samstilling',
          cs: 'Denní synchronizace',
          bg: 'Ежедневна синхронизация',
          hr: 'Dnevna sinkronizacija',
          sr: 'Дневна синхронизација',
          sl: 'Dnevna sinhronizacija',
          mk: 'Дневна синхронизација',
          be: 'Штодзённая сінхранізацыя',
          bs: 'Dnevna sinhronizacija',
          hsb: 'Dnjowa synchronizacija',
        }),
        syncTime: t({
          ru: 'Время синхронизации',
          en: 'Sync time',
          kk: 'Синхрондау уақыты',
          de: 'Synchronisierungszeit',
          fr: 'Heure de synchronisation',
          es: 'Hora de sincronización',
          pt: 'Hora de sincronização',
          tr: 'Senkronizasyon saati',
          uk: 'Час синхронізації',
          zh: '同步时间',
          ar: 'وقت المزامنة',
          pl: 'Czas synchronizacji',
          it: 'Orario sincronizzazione',
          sk: 'Čas synchronizácie',
          ja: '同期時刻',
          ko: '동기화 시간',
          hi: 'सिंक समय',
          nl: 'Synchronisatietijd',
          sv: 'Synktid',
          vi: 'Thời gian đồng bộ',
          id: 'Waktu sinkronisasi',
          da: 'Synkroniseringstid',
          nb: 'Synkroniseringstid',
          nn: 'Synkroniseringstid',
          fi: 'Synkronointiaika',
          is: 'Tími samstillingar',
          fo: 'Samstillingartíð',
          cs: 'Čas synchronizace',
          bg: 'Час на синхронизация',
          hr: 'Vrijeme sinkronizacije',
          sr: 'Време синхронизације',
          sl: 'Čas sinhronizacije',
          mk: 'Време на синхронизација',
          be: 'Час сінхранізацыі',
          bs: 'Vrijeme sinhronizacije',
          hsb: 'Čas synchronizacije',
        }),
        timeZone: t({
          ru: 'Часовой пояс',
          en: 'Time zone',
          kk: 'Уақыт белдеуі',
          de: 'Zeitzone',
          fr: 'Fuseau horaire',
          es: 'Zona horaria',
          pt: 'Fuso horário',
          tr: 'Saat dilimi',
          uk: 'Часовий пояс',
          zh: '时区',
          ar: 'المنطقة الزمنية',
          pl: 'Strefa czasowa',
          it: 'Fuso orario',
          sk: 'Časové pásmo',
          ja: 'タイムゾーン',
          ko: '시간대',
          hi: 'समय क्षेत्र',
          nl: 'Tijdzone',
          sv: 'Tidszon',
          vi: 'Múi giờ',
          id: 'Zona waktu',
          da: 'Tidszone',
          nb: 'Tidssone',
          nn: 'Tidssone',
          fi: 'Aikavyöhyke',
          is: 'Tímasvæði',
          fo: 'Tíðarsona',
          cs: 'Časové pásmo',
          bg: 'Часова зона',
          hr: 'Vremenska zona',
          sr: 'Временска зона',
          sl: 'Časovni pas',
          mk: 'Временска зона',
          be: 'Часавы пояс',
          bs: 'Vremenska zona',
          hsb: 'Časowe pasmo',
        }),
        folder: t(provider.folderLabel),
        folderPlaceholder: t({
          ru: 'Не выбрана (будет создана Lumio)',
          en: 'Not selected (Lumio will create one)',
          kk: 'Таңдалмаған (Lumio құрады)',
          de: 'Nicht ausgewählt (Lumio erstellt einen)',
          fr: 'Non sélectionné (Lumio en créera un)',
          es: 'No seleccionada (Lumio creará una)',
          pt: 'Não selecionada (Lumio criará uma)',
          tr: 'Seçilmedi (Lumio oluşturacak)',
          uk: 'Не вибрано (Lumio створить)',
          zh: '未选择（Lumio 将自动创建）',
          ar: 'غير محدد (سيقوم Lumio بإنشائه)',
          pl: 'Nie wybrano (Lumio utworzy)',
          it: 'Non selezionata (Lumio ne creerà una)',
          sk: 'Nevybrané (Lumio ho vytvorí)',
          ja: '未選択（Lumioが作成します）',
          ko: '선택 안 됨(Lumio가 생성합니다)',
          hi: 'चयनित नहीं (Lumio एक बनाएगा)',
          nl: 'Niet geselecteerd (Lumio maakt er een aan)',
          sv: 'Inte vald (Lumio skapar en)',
          vi: 'Chưa chọn (Lumio sẽ tạo)',
          id: 'Belum dipilih (Lumio akan membuatnya)',
          da: 'Ikke valgt (Lumio opretter en)',
          nb: 'Ikke valgt (Lumio oppretter en)',
          nn: 'Ikkje vald (Lumio opprettar ei)',
          fi: 'Ei valittu (Lumio luo kansion)',
          is: 'Ekki valið (Lumio búi til eina)',
          fo: 'Ikki valt (Lumio stovnar eina)',
          cs: 'Nevybráno (Lumio ji vytvoří)',
          bg: 'Не е избрана (Lumio ще създаде)',
          hr: 'Nije odabrana (Lumio će je napraviti)',
          sr: 'Није изабрана (Lumio ће је направити)',
          sl: 'Ni izbrana (Lumio jo bo ustvaril)',
          mk: 'Не е избрана (Lumio ќе создаде)',
          be: 'Не выбрана (Lumio створыць)',
          bs: 'Nije odabran (Lumio će ga napraviti)',
          hsb: 'Njewuzwoleny (Lumio jedyn załoži)',
        }),
        lastSync: t({
          ru: 'Последняя синхронизация',
          en: 'Last sync',
          kk: 'Соңғы синхрондау',
          de: 'Letzte Synchronisierung',
          fr: 'Dernière synchronisation',
          es: 'Última sincronización',
          pt: 'Última sincronização',
          tr: 'Son senkronizasyon',
          uk: 'Остання синхронізація',
          zh: '最后同步',
          ar: 'آخر مزامنة',
          pl: 'Ostatnia synchronizacja',
          it: 'Ultima sincronizzazione',
          sk: 'Posledná synchronizácia',
          ja: '最終同期',
          ko: '마지막 동기화',
          hi: 'अंतिम सिंक',
          nl: 'Laatste synchronisatie',
          sv: 'Senaste synkning',
          vi: 'Lần đồng bộ cuối',
          id: 'Sinkronisasi terakhir',
          da: 'Seneste synkronisering',
          nb: 'Siste synkronisering',
          nn: 'Siste synkronisering',
          fi: 'Viimeisin synkronointi',
          is: 'Síðasta samstilling',
          fo: 'Síðsta samstilling',
          cs: 'Poslední synchronizace',
          bg: 'Последна синхронизация',
          hr: 'Zadnja sinkronizacija',
          sr: 'Последња синхронизација',
          sl: 'Zadnja sinhronizacija',
          mk: 'Последна синхронизација',
          be: 'Апошняя сінхранізацыя',
          bs: 'Zadnja sinhronizacija',
          hsb: 'Poslednja synchronizacija',
        }),
      },
      toasts: {
        connecting: t(provider.connectingLabel),
        connected: t(provider.connectedLabel),
        disconnected: t({
          ru: 'Интеграция отключена',
          en: 'Integration disconnected',
          kk: 'Интеграция ажыратылды',
          de: 'Integration getrennt',
          fr: 'Intégration déconnectée',
          es: 'Integración desconectada',
          pt: 'Integração desconectada',
          tr: 'Entegrasyon bağlantısı kesildi',
          uk: 'Інтеграцію відключено',
          zh: '集成已断开',
          ar: 'تم قطع اتصال التكامل',
          pl: 'Integracja rozłączona',
          it: 'Integrazione disconnessa',
          sk: 'Integrácia bola odpojená',
          ja: '連携を解除しました',
          ko: '연동이 해제되었습니다',
          hi: 'इंटीग्रेशन डिस्कनेक्ट हो गया',
          nl: 'Integratie ontkoppeld',
          sv: 'Integrationen har kopplats från',
          vi: 'Đã ngắt kết nối tích hợp',
          id: 'Integrasi diputuskan',
          da: 'Integrationen er afbrudt',
          nb: 'Integrasjonen er koblet fra',
          nn: 'Integrasjonen er kopla frå',
          fi: 'Integraatio katkaistu',
          is: 'Samþættingin var aftengd',
          fo: 'Samanknýtingin er skild frá',
          cs: 'Integrace odpojena',
          bg: 'Интеграцията е изключена',
          hr: 'Integracija je odspojena',
          sr: 'Интеграција је искључена',
          sl: 'Integracija je odklopljena',
          mk: 'Интеграцијата е исклучена',
          be: 'Інтэграцыя адключана',
          bs: 'Integracija je odspojena',
          hsb: 'Integracija je wotdźělena',
        }),
        syncStarted: t({
          ru: 'Синхронизация запущена',
          en: 'Sync started',
          kk: 'Синхрондау басталды',
          de: 'Synchronisierung gestartet',
          fr: 'Synchronisation démarrée',
          es: 'Sincronización iniciada',
          pt: 'Sincronização iniciada',
          tr: 'Senkronizasyon başlatıldı',
          uk: 'Синхронізацію розпочато',
          zh: '同步已开始',
          ar: 'بدأت المزامنة',
          pl: 'Synchronizacja rozpoczęta',
          it: 'Sincronizzazione avviata',
          sk: 'Synchronizácia sa spustila',
          ja: '同期を開始しました',
          ko: '동기화가 시작되었습니다',
          hi: 'सिंक शुरू हो गया',
          nl: 'Synchronisatie gestart',
          sv: 'Synkningen har startat',
          vi: 'Đã bắt đầu đồng bộ',
          id: 'Sinkronisasi dimulai',
          da: 'Synkroniseringen er startet',
          nb: 'Synkroniseringen er startet',
          nn: 'Synkroniseringa er starta',
          fi: 'Synkronointi aloitettu',
          is: 'Samstilling hafin',
          fo: 'Samstillingin er byrjað',
          cs: 'Synchronizace spuštěna',
          bg: 'Синхронизацията е стартирана',
          hr: 'Sinkronizacija je pokrenuta',
          sr: 'Синхронизација је покренута',
          sl: 'Sinhronizacija se je začela',
          mk: 'Синхронизацијата е започната',
          be: 'Сінхранізацыя пачата',
          bs: 'Sinhronizacija je pokrenuta',
          hsb: 'Synchronizacija je startowana',
        }),
        settingsSaved: t({
          ru: 'Настройки сохранены',
          en: 'Settings saved',
          kk: 'Баптаулар сақталды',
          de: 'Einstellungen gespeichert',
          fr: 'Paramètres enregistrés',
          es: 'Configuración guardada',
          pt: 'Configurações salvas',
          tr: 'Ayarlar kaydedildi',
          uk: 'Налаштування збережено',
          zh: '设置已保存',
          ar: 'تم حفظ الإعدادات',
          pl: 'Ustawienia zapisane',
          it: 'Impostazioni salvate',
          sk: 'Nastavenia boli uložené',
          ja: '設定を保存しました',
          ko: '설정이 저장되었습니다',
          hi: 'सेटिंग्स सहेजी गईं',
          nl: 'Instellingen opgeslagen',
          sv: 'Inställningarna har sparats',
          vi: 'Đã lưu cài đặt',
          id: 'Pengaturan disimpan',
          da: 'Indstillingerne er gemt',
          nb: 'Innstillingene er lagret',
          nn: 'Innstillingane er lagra',
          fi: 'Asetukset tallennettu',
          is: 'Stillingar vistaðar',
          fo: 'Innstillingarnar eru goymdar',
          cs: 'Nastavení uloženo',
          bg: 'Настройките са запазени',
          hr: 'Postavke su spremljene',
          sr: 'Подешавања су сачувана',
          sl: 'Nastavitve so shranjene',
          mk: 'Поставките се зачувани',
          be: 'Налады захаваны',
          bs: 'Postavke su sačuvane',
          hsb: 'Nastajenja su składowane',
        }),
      },
      errors: {
        loadStatus: t({
          ru: 'Не удалось загрузить статус интеграции',
          en: 'Failed to load integration status',
          kk: 'Интеграция статусын жүктеу мүмкін болмады',
          de: 'Integrationsstatus konnte nicht geladen werden',
          fr: "Impossible de charger le statut d'intégration",
          es: 'No se pudo cargar el estado de integración',
          pt: 'Falha ao carregar o status de integração',
          tr: 'Entegrasyon durumu yüklenemedi',
          uk: 'Не вдалося завантажити статус інтеграції',
          zh: '无法加载集成状态',
          ar: 'فشل تحميل حالة التكامل',
          pl: 'Nie udało się załadować statusu integracji',
          it: 'Impossibile caricare lo stato di integrazione',
          sk: 'Nepodarilo sa načítať stav integrácie',
          ja: '連携ステータスを読み込めませんでした',
          ko: '연동 상태를 불러오지 못했습니다',
          hi: 'इंटीग्रेशन स्थिति लोड नहीं हो सकी',
          nl: 'Kan integratiestatus niet laden',
          sv: 'Det gick inte att läsa in integrationsstatus',
          vi: 'Không thể tải trạng thái tích hợp',
          id: 'Gagal memuat status integrasi',
          da: 'Integrationens status kunne ikke indlæses',
          nb: 'Kunne ikke laste integrasjonsstatusen',
          nn: 'Kunne ikkje laste integrasjonsstatusen',
          fi: 'Integraation tilaa ei voitu ladata',
          is: 'Ekki var unnt að hlaða stöðu samþættingarinnar',
          fo: 'Fekk ikki lisið støðuna á samanknýtingini',
          cs: 'Stav integrace se nepodařilo načíst',
          bg: 'Състоянието на интеграцията не можа да се зареди',
          hr: 'Stanje integracije nije bilo moguće učitati',
          sr: 'Стање интеграције није могуће учитати',
          sl: 'Stanja integracije ni bilo mogoče naložiti',
          mk: 'Состојбата на интеграцијата не можеше да се вчита',
          be: 'Не ўдалося загрузіць стан інтэграцыі',
          bs: 'Stanje integracije nije moguće učitati',
          hsb: 'Staw integracije njeda so začitać',
        }),
        connectFailed: t({
          ru: 'Не удалось начать подключение',
          en: 'Failed to start connection',
          kk: 'Қосылымды бастау мүмкін болмады',
          de: 'Verbindungsaufbau fehlgeschlagen',
          fr: 'Impossible de démarrer la connexion',
          es: 'No se pudo iniciar la conexión',
          pt: 'Falha ao iniciar conexão',
          tr: 'Bağlantı başlatılamadı',
          uk: 'Не вдалося розпочати підключення',
          zh: '无法启动连接',
          ar: 'فشل بدء الاتصال',
          pl: 'Nie udało się rozpocząć połączenia',
          it: 'Impossibile avviare la connessione',
          sk: 'Nepodarilo sa spustiť pripojenie',
          ja: '接続を開始できませんでした',
          ko: '연결을 시작하지 못했습니다',
          hi: 'कनेक्शन शुरू नहीं हो सका',
          nl: 'Kan verbinding niet starten',
          sv: 'Det gick inte att starta anslutningen',
          vi: 'Không thể bắt đầu kết nối',
          id: 'Gagal memulai koneksi',
          da: 'Forbindelsen kunne ikke startes',
          nb: 'Kunne ikke starte tilkoblingen',
          nn: 'Kunne ikkje starte tilkoplinga',
          fi: 'Yhteyden muodostusta ei voitu aloittaa',
          is: 'Ekki var unnt að hefja tenginguna',
          fo: 'Fekk ikki byrjað sambandið',
          cs: 'Připojení se nepodařilo spustit',
          bg: 'Връзката не можа да се стартира',
          hr: 'Povezivanje nije bilo moguće pokrenuti',
          sr: 'Повезивање није могуће покренути',
          sl: 'Povezave ni bilo mogoče zagnati',
          mk: 'Поврзувањето не можеше да се започне',
          be: 'Не ўдалося пачаць падключэнне',
          bs: 'Povezivanje nije moguće pokrenuti',
          hsb: 'Zwjazanje njeda so startować',
        }),
        disconnectFailed: t({
          ru: 'Не удалось отключить интеграцию',
          en: 'Failed to disconnect integration',
          kk: 'Интеграцияны ажырату мүмкін болмады',
          de: 'Integration konnte nicht getrennt werden',
          fr: "Impossible de déconnecter l'intégration",
          es: 'No se pudo desconectar la integración',
          pt: 'Falha ao desconectar a integração',
          tr: 'Entegrasyon bağlantısı kesilemedi',
          uk: 'Не вдалося відключити інтеграцію',
          zh: '无法断开集成连接',
          ar: 'فشل قطع اتصال التكامل',
          pl: 'Nie udało się rozłączyć integracji',
          it: "Impossibile disconnettere l'integrazione",
          sk: 'Integráciu sa nepodarilo odpojiť',
          ja: '連携を解除できませんでした',
          ko: '연동을 해제하지 못했습니다',
          hi: 'इंटीग्रेशन डिस्कनेक्ट नहीं हो सका',
          nl: 'Kan integratie niet ontkoppelen',
          sv: 'Det gick inte att koppla från integrationen',
          vi: 'Không thể ngắt kết nối tích hợp',
          id: 'Gagal memutuskan integrasi',
          da: 'Integrationen kunne ikke afbrydes',
          nb: 'Kunne ikke koble fra integrasjonen',
          nn: 'Kunne ikkje kople frå integrasjonen',
          fi: 'Integraation katkaisu ei onnistunut',
          is: 'Ekki var unnt að aftengja samþættinguna',
          fo: 'Fekk ikki skilt samanknýtingina frá',
          cs: 'Integraci se nepodařilo odpojit',
          bg: 'Интеграцията не можа да бъде изключена',
          hr: 'Integraciju nije bilo moguće odspojiti',
          sr: 'Интеграцију није могуће искључити',
          sl: 'Integracije ni bilo mogoče odklopiti',
          mk: 'Интеграцијата не можеше да се исклучи',
          be: 'Не ўдалося адключыць інтэграцыю',
          bs: 'Integraciju nije moguće odspojiti',
          hsb: 'Integracija njeda so wotdźělić',
        }),
        pickerUnavailable: t(provider.pickerUnavailableLabel),
      },
    },
  } satisfies Dictionary;
};
