import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'cashFlowCard',
  content: {
    title: t({
      ru: 'Движение денег',
      en: 'Cash flow',
      kk: 'Ақша ағыны',
      de: 'Cashflow',
      fr: 'Flux de trésorerie',
      es: 'Flujo de caja',
      pt: 'Fluxo de caixa',
      tr: 'Nakit akışı',
      uk: 'Рух коштів',
      zh: '现金流',
      ar: 'التدفق النقدي',
      pl: 'Przepływy pieniężne',
      it: 'Flusso di cassa',
      sk: 'Peňažný tok',
      ja: 'キャッシュフロー',
      ko: '현금 흐름',
      hi: 'नकदी प्रवाह',
      nl: 'Cashflow',
      sv: 'Kassaflöde',
      vi: 'Dòng tiền',
      id: 'Arus kas',
    }),
    subtitle: t({
      ru: 'Доходы и расходы · {range}',
      en: 'Income vs. expenses · {range}',
      kk: 'Табыс пен шығын · {range}',
      de: 'Einnahmen vs. Ausgaben · {range}',
      fr: 'Revenus vs dépenses · {range}',
      es: 'Ingresos frente a gastos · {range}',
      pt: 'Receitas vs. despesas · {range}',
      tr: 'Gelir ve gider · {range}',
      uk: 'Доходи й витрати · {range}',
      zh: '收入与支出 · {range}',
      ar: 'الدخل مقابل المصروفات · {range}',
      pl: 'Przychody i wydatki · {range}',
      it: 'Entrate vs uscite · {range}',
      sk: 'Príjmy a výdavky · {range}',
      ja: '収入と支出 · {range}',
      ko: '수입 대 지출 · {range}',
      hi: 'आय बनाम व्यय · {range}',
      nl: 'Inkomsten vs. uitgaven · {range}',
      sv: 'Inkomster vs. utgifter · {range}',
      vi: 'Thu nhập và chi tiêu · {range}',
      id: 'Pendapatan vs pengeluaran · {range}',
    }),
    empty: t({
      ru: 'Пока нет данных о движении денег',
      en: 'No cash flow data yet',
      kk: 'Ақша ағыны туралы деректер әлі жоқ',
      de: 'Noch keine Cashflow-Daten',
      fr: 'Pas encore de données de trésorerie',
      es: 'Aún no hay datos de flujo de caja',
      pt: 'Ainda não há dados de fluxo de caixa',
      tr: 'Henüz nakit akışı verisi yok',
      uk: 'Поки немає даних про рух коштів',
      zh: '暂无现金流数据',
      ar: 'لا توجد بيانات تدفق نقدي بعد',
      pl: 'Brak jeszcze danych o przepływach pieniężnych',
      it: 'Ancora nessun dato sul flusso di cassa',
      sk: 'Zatiaľ žiadne údaje o peňažnom toku',
      ja: 'キャッシュフローデータはまだありません',
      ko: '아직 현금 흐름 데이터가 없습니다',
      hi: 'अभी तक नकदी प्रवाह डेटा नहीं है',
      nl: 'Nog geen cashflowgegevens',
      sv: 'Inga kassaflödesdata ännu',
      vi: 'Chưa có dữ liệu dòng tiền',
      id: 'Belum ada data arus kas',
    }),
    income: t({
      ru: 'Доход',
      en: 'Income',
      kk: 'Табыс',
      de: 'Einnahmen',
      fr: 'Revenus',
      es: 'Ingresos',
      pt: 'Receitas',
      tr: 'Gelir',
      uk: 'Дохід',
      zh: '收入',
      ar: 'الدخل',
      pl: 'Przychód',
      it: 'Entrate',
      sk: 'Príjem',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomsten',
      sv: 'Inkomster',
      vi: 'Thu nhập',
      id: 'Pendapatan',
    }),
    expense: t({
      ru: 'Расход',
      en: 'Expense',
      kk: 'Шығын',
      de: 'Ausgaben',
      fr: 'Dépenses',
      es: 'Gastos',
      pt: 'Despesas',
      tr: 'Gider',
      uk: 'Витрати',
      zh: '支出',
      ar: 'المصروفات',
      pl: 'Wydatki',
      it: 'Uscite',
      sk: 'Výdavky',
      ja: '支出',
      ko: '지출',
      hi: 'व्यय',
      nl: 'Uitgaven',
      sv: 'Utgifter',
      vi: 'Chi tiêu',
      id: 'Pengeluaran',
    }),
  },
} satisfies Dictionary;

export default content;
