import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'cashFlowCard',
  content: {
    title: t({
      ru: 'Движение денег',
      en: 'Cash flow',
      kk: 'Ақша ағыны',
      de: 'Cashflow',
      fr: 'Flux de trésorerie',
      es: 'Flujo de caja',
      pt: 'Fluxo de caixa',
      tr: 'Nakit akışı',
      uk: 'Рух коштів',
      zh: '现金流',
      ar: 'التدفق النقدي',
      pl: 'Przepływy pieniężne',
      it: 'Flusso di cassa',
      sk: 'Peňažný tok',
      ja: 'キャッシュフロー',
      ko: '현금 흐름',
      hi: 'नकदी प्रवाह',
      nl: 'Cashflow',
      sv: 'Kassaflöde',
      vi: 'Dòng tiền',
      id: 'Arus kas',
    }),
    empty: t({
      ru: 'Пока нет данных о движении денег',
      en: 'No cash flow data yet',
      kk: 'Ақша ағыны туралы деректер әлі жоқ',
      de: 'Noch keine Cashflow-Daten',
      fr: 'Pas encore de données de trésorerie',
      es: 'Aún no hay datos de flujo de caja',
      pt: 'Ainda não há dados de fluxo de caixa',
      tr: 'Henüz nakit akışı verisi yok',
      uk: 'Поки немає даних про рух коштів',
      zh: '暂无现金流数据',
      ar: 'لا توجد بيانات تدفق نقدي بعد',
      pl: 'Brak jeszcze danych o przepływach pieniężnych',
      it: 'Ancora nessun dato sul flusso di cassa',
      sk: 'Zatiaľ žiadne údaje o peňažnom toku',
      ja: 'キャッシュフローデータはまだありません',
      ko: '아직 현금 흐름 데이터가 없습니다',
      hi: 'अभी तक नकदी प्रवाह डेटा नहीं है',
      nl: 'Nog geen cashflowgegevens',
      sv: 'Inga kassaflödesdata ännu',
      vi: 'Chưa có dữ liệu dòng tiền',
      id: 'Belum ada data arus kas',
    }),
    income: t({
      ru: 'Доход',
      en: 'Income',
      kk: 'Табыс',
      de: 'Einnahmen',
      fr: 'Revenus',
      es: 'Ingresos',
      pt: 'Receitas',
      tr: 'Gelir',
      uk: 'Дохід',
      zh: '收入',
      ar: 'الدخل',
      pl: 'Przychód',
      it: 'Entrate',
      sk: 'Príjem',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomsten',
      sv: 'Inkomster',
      vi: 'Thu nhập',
      id: 'Pendapatan',
    }),
    expense: t({
      ru: 'Расход',
      en: 'Expense',
      kk: 'Шығын',
      de: 'Ausgaben',
      fr: 'Dépenses',
      es: 'Gastos',
      pt: 'Despesas',
      tr: 'Gider',
      uk: 'Витрати',
      zh: '支出',
      ar: 'المصروفات',
      pl: 'Wydatki',
      it: 'Uscite',
      sk: 'Výdavky',
      ja: '支出',
      ko: '지출',
      hi: 'व्यय',
      nl: 'Uitgaven',
      sv: 'Utgifter',
      vi: 'Chi tiêu',
      id: 'Pengeluaran',
    }),
    net: t({
      ru: 'Итог',
      en: 'Net',
      kk: 'Таза',
      de: 'Netto',
      fr: 'Net',
      es: 'Neto',
      pt: 'Líquido',
      tr: 'Net',
      uk: 'Підсумок',
      zh: '净额',
      ar: 'الصافي',
      pl: 'Netto',
      it: 'Netto',
      sk: 'Netto',
      ja: '純額',
      ko: '순액',
      hi: 'शुद्ध',
      nl: 'Netto',
      sv: 'Netto',
      vi: 'Ròng',
      id: 'Bersih',
    }),
    rangeAll: t({
      ru: 'Всё время',
      en: 'All time',
      kk: 'Барлық уақыт',
      de: 'Gesamt',
      fr: 'Tout',
      es: 'Todo',
      pt: 'Tudo',
      tr: 'Tüm zamanlar',
      uk: 'Весь час',
      zh: '全部',
      ar: 'كل الوقت',
      pl: 'Cały okres',
      it: 'Sempre',
      sk: 'Celé obdobie',
      ja: '全期間',
      ko: '전체',
      hi: 'सभी समय',
      nl: 'Alles',
      sv: 'All tid',
      vi: 'Tất cả',
      id: 'Semua',
    }),
    range5y: t({
      ru: '5 лет',
      en: '5 years',
      kk: '5 жыл',
      de: '5 Jahre',
      fr: '5 ans',
      es: '5 años',
      pt: '5 anos',
      tr: '5 yıl',
      uk: '5 років',
      zh: '5 年',
      ar: '5 سنوات',
      pl: '5 lat',
      it: '5 anni',
      sk: '5 rokov',
      ja: '5年',
      ko: '5년',
      hi: '5 वर्ष',
      nl: '5 jaar',
      sv: '5 år',
      vi: '5 năm',
      id: '5 tahun',
    }),
    range12m: t({
      ru: '12 мес',
      en: '12 mo',
      kk: '12 ай',
      de: '12 Mon.',
      fr: '12 mois',
      es: '12 meses',
      pt: '12 meses',
      tr: '12 ay',
      uk: '12 міс',
      zh: '12 个月',
      ar: '12 شهرًا',
      pl: '12 mies.',
      it: '12 mesi',
      sk: '12 mes.',
      ja: '12か月',
      ko: '12개월',
      hi: '12 महीने',
      nl: '12 mnd',
      sv: '12 mån',
      vi: '12 tháng',
      id: '12 bln',
    }),
    rangeThisYear: t({
      ru: 'Этот год',
      en: 'This year',
      kk: 'Биыл',
      de: 'Dieses Jahr',
      fr: 'Cette année',
      es: 'Este año',
      pt: 'Este ano',
      tr: 'Bu yıl',
      uk: 'Цей рік',
      zh: '今年',
      ar: 'هذا العام',
      pl: 'Ten rok',
      it: "Quest'anno",
      sk: 'Tento rok',
      ja: '今年',
      ko: '올해',
      hi: 'इस वर्ष',
      nl: 'Dit jaar',
      sv: 'I år',
      vi: 'Năm nay',
      id: 'Tahun ini',
    }),
  },
} satisfies Dictionary;

export default content;
