import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'dataHealthTab',
  content: {
    uploadParse: t({
      ru: 'Загрузить / Обработать',
      en: 'Upload / Parse',
      kk: 'Жүктеу / Өңдеу',
      de: 'Hochladen / Verarbeiten',
      fr: 'Importer / Traiter',
      es: 'Subir / Procesar',
      pt: 'Enviar / Processar',
      tr: 'Yükle / İşle',
      uk: 'Завантажити / Обробити',
      zh: '上传 / 解析',
      ar: 'رفع / معالجة',
      pl: 'Prześlij / Przetwórz',
      it: 'Carica / Elabora',
      sk: 'Nahrať / Spracovať',
      ja: 'アップロード / 解析',
      ko: '업로드 / 처리',
      hi: 'अपलोड / प्रोसेस',
      nl: 'Uploaden / Verwerken',
      sv: 'Ladda upp / Bearbeta',
      vi: 'Tải lên / Xử lý',
      id: 'Unggah / Proses',
    }),
    reviewQueue: t({
      ru: 'Очередь проверки ({count})',
      en: 'Review Queue ({count})',
      kk: 'Тексеру кезегі ({count})',
      de: 'Prüfwarteschlange ({count})',
      fr: 'File de révision ({count})',
      es: 'Cola de revisión ({count})',
      pt: 'Fila de revisão ({count})',
      tr: 'İnceleme sırası ({count})',
      uk: 'Черга перевірки ({count})',
      zh: '待审核队列（{count}）',
      ar: 'قائمة المراجعة ({count})',
      pl: 'Kolejka do sprawdzenia ({count})',
      it: 'Coda di revisione ({count})',
      sk: 'Fronta na kontrolu ({count})',
      ja: 'レビュー待ち（{count}）',
      ko: '검토 대기열 ({count})',
      hi: 'समीक्षा कतार ({count})',
      nl: 'Beoordelingswachtrij ({count})',
      sv: 'Granskningskö ({count})',
      vi: 'Hàng chờ duyệt ({count})',
      id: 'Antrean tinjauan ({count})',
    }),
    exportButton: t({
      ru: 'Экспорт',
      en: 'Export',
      kk: 'Экспорт',
      de: 'Exportieren',
      fr: 'Exporter',
      es: 'Exportar',
      pt: 'Exportar',
      tr: 'Dışa aktar',
      uk: 'Експорт',
      zh: '导出',
      ar: 'تصدير',
      pl: 'Eksportuj',
      it: 'Esporta',
      sk: 'Exportovať',
      ja: 'エクスポート',
      ko: '내보내기',
      hi: 'निर्यात',
      nl: 'Exporteren',
      sv: 'Exportera',
      vi: 'Xuất',
      id: 'Ekspor',
    }),
    dataQualityMetrics: t({
      ru: 'КАЧЕСТВО ДАННЫХ',
      en: 'DATA QUALITY METRICS',
      kk: 'ДЕРЕКТЕР САПАСЫ',
      de: 'DATENQUALITÄT',
      fr: 'QUALITÉ DES DONNÉES',
      es: 'CALIDAD DE LOS DATOS',
      pt: 'QUALIDADE DOS DADOS',
      tr: 'VERİ KALİTESİ',
      uk: 'ЯКІСТЬ ДАНИХ',
      zh: '数据质量指标',
      ar: 'مقاييس جودة البيانات',
      pl: 'JAKOŚĆ DANYCH',
      it: 'QUALITÀ DEI DATI',
      sk: 'KVALITA ÚDAJOV',
      ja: 'データ品質指標',
      ko: '데이터 품질 지표',
      hi: 'डेटा गुणवत्ता मेट्रिक्स',
      nl: 'DATAKWALITEIT',
      sv: 'DATAKVALITET',
      vi: 'CHỈ SỐ CHẤT LƯỢNG DỮ LIỆU',
      id: 'METRIK KUALITAS DATA',
    }),
    uncategorizedLabel: t({
      ru: 'Без категории',
      en: 'Uncategorized',
      kk: 'Санатсыз',
      de: 'Nicht kategorisiert',
      fr: 'Non catégorisé',
      es: 'Sin categorizar',
      pt: 'Sem categoria',
      tr: 'Kategorisiz',
      uk: 'Без категорії',
      zh: '未分类',
      ar: 'غير مصنف',
      pl: 'Bez kategorii',
      it: 'Non categorizzato',
      sk: 'Nezaradené',
      ja: '未分類',
      ko: '미분류',
      hi: 'बिना श्रेणी',
      nl: 'Niet gecategoriseerd',
      sv: 'Ej kategoriserad',
      vi: 'Chưa phân loại',
      id: 'Belum dikategorikan',
    }),
    statementErrorsLabel: t({
      ru: 'Ошибки выписок',
      en: 'Statement errors',
      kk: 'Үзінді қателері',
      de: 'Kontoauszugsfehler',
      fr: 'Erreurs de relevé',
      es: 'Errores de extracto',
      pt: 'Erros de extrato',
      tr: 'Ekstre hataları',
      uk: 'Помилки виписок',
      zh: '对账单错误',
      ar: 'أخطاء كشوف الحساب',
      pl: 'Błędy wyciągów',
      it: 'Errori negli estratti conto',
      sk: 'Chyby výpisov',
      ja: '明細のエラー',
      ko: '명세서 오류',
      hi: 'स्टेटमेंट त्रुटियाँ',
      nl: 'Afschriftfouten',
      sv: 'Kontoutdragsfel',
      vi: 'Lỗi sao kê',
      id: 'Kesalahan laporan',
    }),
    pendingReviewLabel: t({
      ru: 'Ожидают проверки',
      en: 'Pending review',
      kk: 'Тексеруді күтуде',
      de: 'Prüfung ausstehend',
      fr: 'En attente de révision',
      es: 'Pendiente de revisión',
      pt: 'Pendente de revisão',
      tr: 'İncelemesi bekleyen',
      uk: 'Очікують перевірки',
      zh: '待审核',
      ar: 'بانتظار المراجعة',
      pl: 'Oczekuje na sprawdzenie',
      it: 'In attesa di revisione',
      sk: 'Čaká na kontrolu',
      ja: 'レビュー待ち',
      ko: '검토 대기',
      hi: 'समीक्षा लंबित',
      nl: 'In afwachting van beoordeling',
      sv: 'Väntar på granskning',
      vi: 'Chờ duyệt',
      id: 'Menunggu tinjauan',
    }),
    receiptsPendingLabel: t({
      ru: 'Чеки на проверке',
      en: 'Receipts pending',
      kk: 'Түбіртектер тексеруде',
      de: 'Belege ausstehend',
      fr: 'Reçus en attente',
      es: 'Recibos pendientes',
      pt: 'Recibos pendentes',
      tr: 'Bekleyen fişler',
      uk: 'Чеки на перевірці',
      zh: '待处理收据',
      ar: 'إيصالات معلقة',
      pl: 'Oczekujące paragony',
      it: 'Ricevute in sospeso',
      sk: 'Čakajúce doklady',
      ja: '未処理の領収書',
      ko: '대기 중인 영수증',
      hi: 'लंबित रसीदें',
      nl: 'Bonnetjes in behandeling',
      sv: 'Väntande kvitton',
      vi: 'Biên lai đang chờ',
      id: 'Struk tertunda',
    }),
    parsingWarningsLabel: t({
      ru: 'Предупреждения обработки',
      en: 'Parsing warnings',
      kk: 'Өңдеу ескертулері',
      de: 'Verarbeitungswarnungen',
      fr: "Avertissements d'analyse",
      es: 'Advertencias de análisis',
      pt: 'Avisos de processamento',
      tr: 'Ayrıştırma uyarıları',
      uk: 'Попередження обробки',
      zh: '解析警告',
      ar: 'تحذيرات التحليل',
      pl: 'Ostrzeżenia przetwarzania',
      it: 'Avvisi di analisi',
      sk: 'Upozornenia pri spracovaní',
      ja: '解析の警告',
      ko: '파싱 경고',
      hi: 'पार्सिंग चेतावनियाँ',
      nl: 'Verwerkingswaarschuwingen',
      sv: 'Tolkningsvarningar',
      vi: 'Cảnh báo phân tích',
      id: 'Peringatan pemrosesan',
    }),
    allGood: t({
      ru: 'Всё в порядке',
      en: 'All good',
      kk: 'Бәрі жақсы',
      de: 'Alles in Ordnung',
      fr: 'Tout va bien',
      es: 'Todo en orden',
      pt: 'Tudo certo',
      tr: 'Her şey yolunda',
      uk: 'Усе гаразд',
      zh: '一切正常',
      ar: 'كل شيء على ما يرام',
      pl: 'Wszystko w porządku',
      it: 'Tutto a posto',
      sk: 'Všetko v poriadku',
      ja: '問題ありません',
      ko: '문제 없음',
      hi: 'सब ठीक है',
      nl: 'Alles in orde',
      sv: 'Allt är bra',
      vi: 'Mọi thứ đều ổn',
      id: 'Semua baik-baik saja',
    }),
    metricNeedsAttention: t({
      ru: 'Требуют внимания: {value}',
      en: '{value} need attention',
      kk: 'Назар аудару қажет: {value}',
      de: '{value} benötigen Aufmerksamkeit',
      fr: '{value} à traiter',
      es: '{value} requieren atención',
      pt: '{value} precisam de atenção',
      tr: '{value} dikkat gerektiriyor',
      uk: 'Потребують уваги: {value}',
      zh: '{value} 项需要处理',
      ar: '{value} بحاجة إلى المراجعة',
      pl: '{value} wymaga uwagi',
      it: '{value} richiedono attenzione',
      sk: '{value} si vyžaduje pozornosť',
      ja: '{value} 件の対応が必要です',
      ko: '{value}건 확인 필요',
      hi: '{value} पर ध्यान देने की आवश्यकता है',
      nl: '{value} vereisen aandacht',
      sv: '{value} kräver åtgärd',
      vi: '{value} cần được xử lý',
      id: '{value} perlu perhatian',
    }),
    lastUpload: t({
      ru: 'Последняя загрузка',
      en: 'Last upload',
      kk: 'Соңғы жүктеу',
      de: 'Letzter Upload',
      fr: 'Dernier import',
      es: 'Última subida',
      pt: 'Último envio',
      tr: 'Son yükleme',
      uk: 'Останнє завантаження',
      zh: '最近上传',
      ar: 'آخر تحميل',
      pl: 'Ostatni przesył',
      it: 'Ultimo caricamento',
      sk: 'Posledné nahratie',
      ja: '最終アップロード',
      ko: '마지막 업로드',
      hi: 'अंतिम अपलोड',
      nl: 'Laatste upload',
      sv: 'Senaste uppladdning',
      vi: 'Lần tải lên gần nhất',
      id: 'Unggahan terakhir',
    }),
    relativeToday: t({
      ru: 'Сегодня',
      en: 'Today',
      kk: 'Бүгін',
      de: 'Heute',
      fr: "Aujourd'hui",
      es: 'Hoy',
      pt: 'Hoje',
      tr: 'Bugün',
      uk: 'Сьогодні',
      zh: '今天',
      ar: 'اليوم',
      pl: 'Dzisiaj',
      it: 'Oggi',
      sk: 'Dnes',
      ja: '今日',
      ko: '오늘',
      hi: 'आज',
      nl: 'Vandaag',
      sv: 'Idag',
      vi: 'Hôm nay',
      id: 'Hari ini',
    }),
    relativeYesterday: t({
      ru: 'Вчера',
      en: 'Yesterday',
      kk: 'Кеше',
      de: 'Gestern',
      fr: 'Hier',
      es: 'Ayer',
      pt: 'Ontem',
      tr: 'Dün',
      uk: 'Вчора',
      zh: '昨天',
      ar: 'أمس',
      pl: 'Wczoraj',
      it: 'Ieri',
      sk: 'Včera',
      ja: '昨日',
      ko: '어제',
      hi: 'कल',
      nl: 'Gisteren',
      sv: 'Igår',
      vi: 'Hôm qua',
      id: 'Kemarin',
    }),
    relativeDaysAgo: t({
      ru: '{n} дн. назад',
      en: '{n} days ago',
      kk: '{n} күн бұрын',
      de: 'vor {n} Tagen',
      fr: 'il y a {n} jours',
      es: 'hace {n} días',
      pt: 'há {n} dias',
      tr: '{n} gün önce',
      uk: '{n} дн. тому',
      zh: '{n} 天前',
      ar: 'قبل {n} يوم',
      pl: '{n} dni temu',
      it: '{n} giorni fa',
      sk: 'pred {n} dňami',
      ja: '{n} 日前',
      ko: '{n}일 전',
      hi: '{n} दिन पहले',
      nl: '{n} dagen geleden',
      sv: 'för {n} dagar sedan',
      vi: '{n} ngày trước',
      id: '{n} hari lalu',
    }),
    relativeOneWeekAgo: t({
      ru: 'Неделю назад',
      en: '1 week ago',
      kk: 'Бір апта бұрын',
      de: 'Vor 1 Woche',
      fr: 'Il y a 1 semaine',
      es: 'Hace 1 semana',
      pt: 'Há 1 semana',
      tr: '1 hafta önce',
      uk: 'Тиждень тому',
      zh: '1 周前',
      ar: 'قبل أسبوع',
      pl: 'Tydzień temu',
      it: '1 settimana fa',
      sk: 'Pred 1 týždňom',
      ja: '1週間前',
      ko: '1주 전',
      hi: '1 सप्ताह पहले',
      nl: '1 week geleden',
      sv: 'För 1 vecka sedan',
      vi: '1 tuần trước',
      id: '1 minggu lalu',
    }),
    relativeWeeksAgo: t({
      ru: '{n} нед. назад',
      en: '{n} weeks ago',
      kk: '{n} апта бұрын',
      de: 'vor {n} Wochen',
      fr: 'il y a {n} semaines',
      es: 'hace {n} semanas',
      pt: 'há {n} semanas',
      tr: '{n} hafta önce',
      uk: '{n} тижн. тому',
      zh: '{n} 周前',
      ar: 'قبل {n} أسابيع',
      pl: '{n} tyg. temu',
      it: '{n} settimane fa',
      sk: 'pred {n} týždňami',
      ja: '{n} 週間前',
      ko: '{n}주 전',
      hi: '{n} सप्ताह पहले',
      nl: '{n} weken geleden',
      sv: 'för {n} veckor sedan',
      vi: '{n} tuần trước',
      id: '{n} minggu lalu',
    }),
    relativeOneMonthAgo: t({
      ru: 'Месяц назад',
      en: '1 month ago',
      kk: 'Бір ай бұрын',
      de: 'Vor 1 Monat',
      fr: 'Il y a 1 mois',
      es: 'Hace 1 mes',
      pt: 'Há 1 mês',
      tr: '1 ay önce',
      uk: 'Місяць тому',
      zh: '1 个月前',
      ar: 'قبل شهر',
      pl: 'Miesiąc temu',
      it: '1 mese fa',
      sk: 'Pred 1 mesiacom',
      ja: '1か月前',
      ko: '1개월 전',
      hi: '1 महीने पहले',
      nl: '1 maand geleden',
      sv: 'För 1 månad sedan',
      vi: '1 tháng trước',
      id: '1 bulan lalu',
    }),
    relativeMonthsAgo: t({
      ru: '{n} мес. назад',
      en: '{n} months ago',
      kk: '{n} ай бұрын',
      de: 'vor {n} Monaten',
      fr: 'il y a {n} mois',
      es: 'hace {n} meses',
      pt: 'há {n} meses',
      tr: '{n} ay önce',
      uk: '{n} міс. тому',
      zh: '{n} 个月前',
      ar: 'قبل {n} أشهر',
      pl: '{n} mies. temu',
      it: '{n} mesi fa',
      sk: 'pred {n} mesiacmi',
      ja: '{n} か月前',
      ko: '{n}개월 전',
      hi: '{n} महीने पहले',
      nl: '{n} maanden geleden',
      sv: 'för {n} månader sedan',
      vi: '{n} tháng trước',
      id: '{n} bulan lalu',
    }),
    noDataYet: t({
      ru: 'Пока нет данных',
      en: 'No data yet',
      kk: 'Әзірге деректер жоқ',
      de: 'Noch keine Daten',
      fr: 'Pas encore de données',
      es: 'Aún no hay datos',
      pt: 'Ainda sem dados',
      tr: 'Henüz veri yok',
      uk: 'Поки немає даних',
      zh: '暂无数据',
      ar: 'لا توجد بيانات بعد',
      pl: 'Brak danych',
      it: 'Nessun dato ancora',
      sk: 'Zatiaľ žiadne údaje',
      ja: 'まだデータがありません',
      ko: '아직 데이터가 없습니다',
      hi: 'अभी तक कोई डेटा नहीं',
      nl: 'Nog geen gegevens',
      sv: 'Ingen data ännu',
      vi: 'Chưa có dữ liệu',
      id: 'Belum ada data',
    }),
    uploadFirstStatement: t({
      ru: 'Загрузить первую выписку →',
      en: 'Upload your first statement →',
      kk: 'Алғашқы үзіндіні жүктеу →',
      de: 'Ersten Kontoauszug hochladen →',
      fr: 'Importer votre premier relevé →',
      es: 'Sube tu primer extracto →',
      pt: 'Envie seu primeiro extrato →',
      tr: 'İlk ekstrenizi yükleyin →',
      uk: 'Завантажити першу виписку →',
      zh: '上传第一份对账单 →',
      ar: 'ارفع كشف حسابك الأول ←',
      pl: 'Prześlij pierwszy wyciąg →',
      it: 'Carica il tuo primo estratto conto →',
      sk: 'Nahrajte prvý výpis →',
      ja: '最初の明細をアップロード →',
      ko: '첫 명세서 업로드 →',
      hi: 'अपना पहला स्टेटमेंट अपलोड करें →',
      nl: 'Upload je eerste afschrift →',
      sv: 'Ladda upp ditt första kontoutdrag →',
      vi: 'Tải lên sao kê đầu tiên →',
      id: 'Unggah laporan pertama Anda →',
    }),
    unapprovedCash: t({
      ru: 'Неподтверждённые остатки',
      en: 'Unapproved cash',
      kk: 'Расталмаған қолма-қол ақша',
      de: 'Nicht genehmigtes Bargeld',
      fr: 'Espèces non approuvées',
      es: 'Efectivo sin aprobar',
      pt: 'Dinheiro não aprovado',
      tr: 'Onaylanmamış nakit',
      uk: 'Непідтверджені готівкові кошти',
      zh: '未确认现金',
      ar: 'نقد غير معتمد',
      pl: 'Niezatwierdzona gotówka',
      it: 'Contanti non approvati',
      sk: 'Neschválená hotovosť',
      ja: '未承認の現金',
      ko: '미승인 현금',
      hi: 'अस्वीकृत नकद',
      nl: 'Niet-goedgekeurd contant geld',
      sv: 'Ej godkända kontanter',
      vi: 'Tiền mặt chưa duyệt',
      id: 'Kas belum disetujui',
    }),
    allCashApproved: t({
      ru: 'ВСЯ НАЛИЧНОСТЬ ПОДТВЕРЖДЕНА',
      en: 'ALL CASH APPROVED',
      kk: 'БАРЛЫҚ ҚОЛМА-ҚОЛ АҚША РАСТАЛДЫ',
      de: 'GESAMTES BARGELD GENEHMIGT',
      fr: 'TOUTES LES ESPÈCES APPROUVÉES',
      es: 'TODO EL EFECTIVO APROBADO',
      pt: 'TODO O DINHEIRO APROVADO',
      tr: 'TÜM NAKİT ONAYLANDI',
      uk: 'УСЯ ГОТІВКА ПІДТВЕРДЖЕНА',
      zh: '现金已全部确认',
      ar: 'تمت الموافقة على جميع النقد',
      pl: 'CAŁA GOTÓWKA ZATWIERDZONA',
      it: 'TUTTI I CONTANTI APPROVATI',
      sk: 'HOTOVOSŤ SCHVÁLENÁ',
      ja: 'すべての現金が承認済み',
      ko: '모든 현금 승인 완료',
      hi: 'सभी नकद स्वीकृत',
      nl: 'AL HET CONTANT GELD GOEDGEKEURD',
      sv: 'ALL KONTANT GODKÄND',
      vi: 'TẤT CẢ TIỀN MẶT ĐÃ ĐƯỢC DUYỆT',
      id: 'SEMUA KAS DISETUJUI',
    }),
    reviewApproveCash: t({
      ru: 'Проверить и подтвердить →',
      en: 'Review & approve cash →',
      kk: 'Тексеру және растау →',
      de: 'Bargeld prüfen & genehmigen →',
      fr: 'Vérifier et approuver →',
      es: 'Revisar y aprobar efectivo →',
      pt: 'Revisar e aprovar dinheiro →',
      tr: 'Nakdi incele ve onayla →',
      uk: 'Перевірити й підтвердити →',
      zh: '审核并确认现金 →',
      ar: 'مراجعة النقد واعتماده ←',
      pl: 'Sprawdź i zatwierdź gotówkę →',
      it: 'Rivedi e approva i contanti →',
      sk: 'Skontrolovať a schváliť hotovosť →',
      ja: '現金を確認して承認 →',
      ko: '현금 검토 및 승인 →',
      hi: 'नकद की समीक्षा और स्वीकृति करें →',
      nl: 'Contant geld beoordelen en goedkeuren →',
      sv: 'Granska och godkänn kontanter →',
      vi: 'Xem xét & duyệt tiền mặt →',
      id: 'Tinjau & setujui kas →',
    }),
    actionRequired: t({
      ru: 'Требуется действие',
      en: 'Action required',
      kk: 'Әрекет қажет',
      de: 'Handlung erforderlich',
      fr: 'Action requise',
      es: 'Acción requerida',
      pt: 'Ação necessária',
      tr: 'Eylem gerekiyor',
      uk: 'Потрібна дія',
      zh: '需要处理',
      ar: 'إجراء مطلوب',
      pl: 'Wymagane działanie',
      it: 'Azione richiesta',
      sk: 'Vyžaduje sa akcia',
      ja: '対応が必要です',
      ko: '조치 필요',
      hi: 'कार्रवाई आवश्यक',
      nl: 'Actie vereist',
      sv: 'Åtgärd krävs',
      vi: 'Cần thực hiện hành động',
      id: 'Tindakan diperlukan',
    }),
    quickLinkUncategorized: t({
      ru: 'Проверить неразмеченные операции: {count}',
      en: 'Review {count} uncategorized transactions',
      kk: 'Санатсыз операцияларды тексеру: {count}',
      de: '{count} unkategorisierte Transaktionen prüfen',
      fr: 'Vérifier {count} transactions non catégorisées',
      es: 'Revisar {count} transacciones sin categorizar',
      pt: 'Revisar {count} transações sem categoria',
      tr: '{count} kategorisiz işlemi incele',
      uk: 'Перевірити некатегоризовані операції: {count}',
      zh: '查看 {count} 笔未分类交易',
      ar: 'مراجعة {count} معاملة غير مصنفة',
      pl: 'Sprawdź {count} niekategoryzowanych transakcji',
      it: 'Rivedi {count} transazioni non categorizzate',
      sk: 'Skontrolovať {count} nezaradených transakcií',
      ja: '未分類の取引を確認（{count}件）',
      ko: '미분류 거래 {count}건 검토',
      hi: '{count} बिना श्रेणी लेनदेन की समीक्षा करें',
      nl: '{count} niet-gecategoriseerde transacties beoordelen',
      sv: 'Granska {count} okategoriserade transaktioner',
      vi: 'Xem {count} giao dịch chưa phân loại',
      id: 'Tinjau {count} transaksi belum dikategorikan',
    }),
    quickLinkStatementErrors: t({
      ru: 'Исправить ошибки выписок: {count}',
      en: 'Fix {count} statement errors',
      kk: 'Үзінді қателерін түзету: {count}',
      de: '{count} Kontoauszugsfehler beheben',
      fr: 'Corriger {count} erreurs de relevé',
      es: 'Corregir {count} errores de extracto',
      pt: 'Corrigir {count} erros de extrato',
      tr: '{count} ekstre hatasını düzelt',
      uk: 'Виправити помилки виписок: {count}',
      zh: '修复 {count} 个对账单错误',
      ar: 'إصلاح {count} خطأ في كشف الحساب',
      pl: 'Napraw {count} błędów wyciągu',
      it: "Correggi {count} errori nell'estratto conto",
      sk: 'Opraviť {count} chýb výpisu',
      ja: '明細のエラーを修正（{count}件）',
      ko: '명세서 오류 {count}건 수정',
      hi: '{count} स्टेटमेंट त्रुटियाँ ठीक करें',
      nl: '{count} afschriftfouten oplossen',
      sv: 'Åtgärda {count} kontoutdragsfel',
      vi: 'Sửa {count} lỗi sao kê',
      id: 'Perbaiki {count} kesalahan laporan',
    }),
    quickLinkPendingStatements: t({
      ru: 'Проверить выписки в очереди: {count}',
      en: 'Review {count} pending statements',
      kk: 'Кезектегі үзінділерді тексеру: {count}',
      de: '{count} ausstehende Kontoauszüge prüfen',
      fr: 'Vérifier {count} relevés en attente',
      es: 'Revisar {count} extractos pendientes',
      pt: 'Revisar {count} extratos pendentes',
      tr: '{count} bekleyen ekstreyi incele',
      uk: 'Перевірити виписки в черзі: {count}',
      zh: '查看 {count} 份待处理对账单',
      ar: 'مراجعة {count} كشف حساب معلق',
      pl: 'Sprawdź {count} oczekujących wyciągów',
      it: 'Rivedi {count} estratti conto in sospeso',
      sk: 'Skontrolovať {count} čakajúcich výpisov',
      ja: '保留中の明細を確認（{count}件）',
      ko: '대기 중인 명세서 {count}건 검토',
      hi: '{count} लंबित स्टेटमेंट की समीक्षा करें',
      nl: '{count} openstaande afschriften beoordelen',
      sv: 'Granska {count} väntande kontoutdrag',
      vi: 'Xem {count} sao kê đang chờ',
      id: 'Tinjau {count} laporan tertunda',
    }),
    quickLinkReceipts: t({
      ru: 'Проверить чеки: {count}',
      en: 'Review {count} receipts',
      kk: 'Түбіртектерді тексеру: {count}',
      de: '{count} Belege prüfen',
      fr: 'Vérifier {count} reçus',
      es: 'Revisar {count} recibos',
      pt: 'Revisar {count} recibos',
      tr: '{count} fişi incele',
      uk: 'Перевірити чеки: {count}',
      zh: '查看 {count} 张收据',
      ar: 'مراجعة {count} إيصال',
      pl: 'Sprawdź {count} paragonów',
      it: 'Rivedi {count} ricevute',
      sk: 'Skontrolovať {count} dokladov',
      ja: '領収書を確認（{count}件）',
      ko: '영수증 {count}건 검토',
      hi: '{count} रसीदों की समीक्षा करें',
      nl: '{count} bonnetjes beoordelen',
      sv: 'Granska {count} kvitton',
      vi: 'Xem {count} biên lai',
      id: 'Tinjau {count} struk',
    }),
  },
} satisfies Dictionary;

export default content;
