import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'overviewTab',
  content: {
    emptyTitle: t({
      ru: 'Загрузите первую выписку',
      en: 'Upload your first statement',
      kk: 'Алғашқы үзінді көшірмені жүктеңіз',
      de: 'Laden Sie Ihren ersten Kontoauszug hoch',
      fr: 'Importez votre premier relevé',
      es: 'Suba su primer extracto',
      pt: 'Envie o seu primeiro extrato',
      tr: 'İlk ekstrenizi yükleyin',
      uk: 'Завантажте першу виписку',
      zh: '上传您的第一份对账单',
      pl: 'Prześlij pierwszy wyciąg',
      it: 'Carica il tuo primo estratto conto',
      sk: 'Nahrajte svoj prvý výpis',
      ja: '最初の明細書をアップロード',
      ko: '첫 명세서를 업로드하세요',
      hi: 'अपना पहला स्टेटमेंट अपलोड करें',
      nl: 'Upload uw eerste afschrift',
      sv: 'Ladda upp ditt första kontoutdrag',
      vi: 'Tải lên sao kê đầu tiên của bạn',
      id: 'Unggah rekening koran pertama Anda',
      da: 'Upload dit første kontoudtog',
      nb: 'Last opp din første kontoutskrift',
      nn: 'Last opp den første kontoutskrifta di',
      fi: 'Lataa ensimmäinen tiliotteesi',
      is: 'Sendu inn fyrsta yfirlitið þitt',
      fo: 'Send inn títt fyrsta kontoyvirlit',
      cs: 'Nahrajte svůj první výpis',
      bg: 'Качете първото си извлечение',
      hr: 'Učitajte svoj prvi izvod',
      sr: 'Учитајте свој први извод',
      sl: 'Naložite svoj prvi izpisek',
      mk: 'Поставете го својот прв извадок',
      be: 'Загрузіце сваю першую выпіску',
      bs: 'Učitajte svoj prvi izvod',
      hsb: 'Nahrajće swój prěni wupis',
    }),
    emptyDescription: t({
      ru: 'Начните отслеживать финансы, загрузив банковскую выписку. Мы автоматически распознаем её и покажем движение денег, категории и советы.',
      en: "Start tracking your finances by uploading a bank statement. We'll parse it automatically and show your cash flow, categories, and insights.",
      kk: 'Банк үзінді көшірмесін жүктеп, қаржыңызды бақылауды бастаңыз. Біз оны автоматты түрде талдап, ақша ағынын, санаттарды және кеңестерді көрсетеміз.',
      de: 'Beginnen Sie mit der Verfolgung Ihrer Finanzen, indem Sie einen Kontoauszug hochladen. Wir werten ihn automatisch aus und zeigen Cashflow, Kategorien und Erkenntnisse.',
      fr: 'Commencez à suivre vos finances en important un relevé bancaire. Nous l’analysons automatiquement et affichons vos flux de trésorerie, catégories et informations.',
      es: 'Empiece a controlar sus finanzas subiendo un extracto bancario. Lo analizaremos automáticamente y mostraremos su flujo de caja, categorías e información.',
      pt: 'Comece a acompanhar as suas finanças enviando um extrato bancário. Vamos analisá-lo automaticamente e mostrar o seu fluxo de caixa, categorias e informações.',
      tr: 'Banka ekstresi yükleyerek finansal takibinize başlayın. Ekstrenizi otomatik olarak işleyip nakit akışınızı, kategorilerinizi ve içgörülerinizi gösteririz.',
      uk: 'Почніть відстежувати фінанси, завантаживши банківську виписку. Ми автоматично розберемо її та покажемо рух коштів, категорії та поради.',
      zh: '上传银行对账单，开始追踪您的财务状况。我们会自动解析并展示现金流、分类和洞察。',
      pl: 'Zacznij śledzić swoje finanse, przesyłając wyciąg bankowy. Automatycznie go przeanalizujemy i pokażemy przepływy pieniężne, kategorie i wnioski.',
      it: 'Inizia a monitorare le tue finanze caricando un estratto conto bancario. Lo analizzeremo automaticamente mostrando flusso di cassa, categorie e approfondimenti.',
      sk: 'Začnite sledovať svoje financie nahraním bankového výpisu. Automaticky ho spracujeme a zobrazíme peňažný tok, kategórie a prehľady.',
      ja: '銀行の明細書をアップロードして、財務管理を始めましょう。自動的に解析し、キャッシュフロー、カテゴリ、インサイトを表示します。',
      ko: '은행 명세서를 업로드하여 재무 관리를 시작하세요. 자동으로 분석하여 현금 흐름, 카테고리, 인사이트를 보여드립니다.',
      hi: 'बैंक स्टेटमेंट अपलोड करके अपने वित्त पर नज़र रखना शुरू करें। हम इसे स्वचालित रूप से पढ़ेंगे और नकदी प्रवाह, श्रेणियाँ और जानकारियाँ दिखाएँगे।',
      nl: 'Begin met het bijhouden van uw financiën door een bankafschrift te uploaden. We verwerken het automatisch en tonen uw cashflow, categorieën en inzichten.',
      sv: 'Börja följa din ekonomi genom att ladda upp ett kontoutdrag. Vi analyserar det automatiskt och visar ditt kassaflöde, kategorier och insikter.',
      vi: 'Bắt đầu theo dõi tài chính bằng cách tải lên sao kê ngân hàng. Chúng tôi sẽ tự động phân tích và hiển thị dòng tiền, danh mục và thông tin chi tiết.',
      id: 'Mulai lacak keuangan Anda dengan mengunggah rekening koran bank. Kami akan menganalisisnya secara otomatis dan menampilkan arus kas, kategori, dan wawasan.',
      da: 'Begynd at følge din økonomi ved at uploade et kontoudtog. Vi læser det automatisk og viser dine pengestrømme, kategorier og indsigter.',
      nb: 'Begynn å følge økonomien din ved å laste opp en kontoutskrift. Vi tolker den automatisk og viser kontantstrøm, kategorier og innsikt.',
      nn: 'Byrja å følgje økonomien din ved å laste opp ei kontoutskrift. Vi tolkar henne automatisk og viser kontantstraum, kategoriar og innsikt.',
      fi: 'Aloita talouden seuranta lataamalla tiliote. Luemme sen automaattisesti ja näytämme kassavirtasi, luokat ja havainnot.',
      is: 'Byrjaðu að fylgjast með fjármálum þínum með því að senda inn bankayfirlit. Við lesum það sjálfkrafa og sýnum fjárflæði, flokka og innsýn.',
      fo: 'Byrja at fylgja tínari fíggj við at senda eitt kontoyvirlit upp. Vit lesa tað automatiskt og vísa tín pengastreym, bólkar og innlit.',
      cs: 'Začněte sledovat své finance nahráním bankovního výpisu. Automaticky ho načteme a ukážeme vaše cash flow, kategorie a poznatky.',
      bg: 'Започнете да следите финансите си, като качите банково извлечение. Ще го разчетем автоматично и ще покажем паричния ви поток, категории и изводи.',
      hr: 'Počnite pratiti svoje financije učitavanjem bankovnog izvatka. Pročitat ćemo ga automatski i prikazati vaš novčani tok, kategorije i uvide.',
      sr: 'Почните да пратите своје финансије отпремањем банковног извода. Прочитаћемо га аутоматски и приказати ваш новчани ток, категорије и увиде.',
      sl: 'Začnite spremljati svoje finance z nalaganjem bančnega izpiska. Samodejno ga bomo prebrali in prikazali vaš denarni tok, kategorije in vpoglede.',
      mk: 'Почнете да ги следите вашите финансии со прикачување на банкарски извод. Ќе го прочитаме автоматски и ќе го прикажеме вашиот паричен тек, категориите и сознанијата.',
      be: 'Пачніце сачыць за сваімі фінансамі, запампаваўшы банкаўскую выпіску. Мы прачытаем яе аўтаматычна і пакажам ваш грашовы паток, катэгорыі і высновы.',
      bs: 'Počnite pratiti svoje finansije otpremanjem bankovnog izvoda. Pročitat ćemo ga automatski i prikazati vaš novčani tok, kategorije i uvide.',
      hsb: 'Započńće swoje financy slědować, mjeztym zo bankowy wujimk nahrajeće. Čitamy jón awtomatisce a pokazujemy waš pjenježny tok, kategorije a spóznaća.',
    }),
    emptyCta: t({
      ru: 'Разобрать выписку',
      en: 'Parse statement',
      kk: 'Үзінді көшірмені талдау',
      de: 'Kontoauszug auswerten',
      fr: 'Analyser le relevé',
      es: 'Analizar extracto',
      pt: 'Analisar extrato',
      tr: 'Ekstreyi işle',
      uk: 'Розібрати виписку',
      zh: '解析对账单',
      pl: 'Przeanalizuj wyciąg',
      it: 'Analizza l’estratto conto',
      sk: 'Spracovať výpis',
      ja: '明細書を解析',
      ko: '명세서 분석',
      hi: 'स्टेटमेंट पढ़ें',
      nl: 'Afschrift verwerken',
      sv: 'Analysera kontoutdrag',
      vi: 'Phân tích sao kê',
      id: 'Uraikan rekening koran',
      da: 'Læs kontoudtog',
      nb: 'Tolk kontoutskrift',
      nn: 'Tolk kontoutskrift',
      fi: 'Lue tiliote',
      is: 'Lesa yfirlit',
      fo: 'Les kontoyvirlit',
      cs: 'Načíst výpis',
      bg: 'Разчитане на извлечение',
      hr: 'Pročitaj izvadak',
      sr: 'Прочитај извод',
      sl: 'Preberi izpisek',
      mk: 'Прочитај извод',
      be: 'Прачытаць выпіску',
      bs: 'Pročitaj izvod',
      hsb: 'Wujimk čitać',
    }),
    income: t({
      ru: 'Доход',
      en: 'Income',
      kk: 'Табыс',
      de: 'Einnahmen',
      fr: 'Revenus',
      es: 'Ingresos',
      pt: 'Receitas',
      tr: 'Gelir',
      uk: 'Дохід',
      zh: '收入',
      pl: 'Przychód',
      it: 'Entrate',
      sk: 'Príjem',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomsten',
      sv: 'Inkomster',
      vi: 'Thu nhập',
      id: 'Pendapatan',
      da: 'Indtægt',
      nb: 'Inntekt',
      nn: 'Inntekt',
      fi: 'Tulo',
      is: 'Tekjur',
      fo: 'Inntøka',
      cs: 'Příjem',
      bg: 'Приход',
      hr: 'Prihod',
      sr: 'Приход',
      sl: 'Prihodek',
      mk: 'Приход',
      be: 'Прыбытак',
      bs: 'Prihod',
      hsb: 'Dochod',
    }),
    spentLabel: t({
      ru: 'Потрачено',
      en: 'Spent',
      kk: 'Жұмсалды',
      de: 'Ausgegeben',
      fr: 'Dépensé',
      es: 'Gastado',
      pt: 'Gasto',
      tr: 'Harcanan',
      uk: 'Витрачено',
      zh: '已花费',
      pl: 'Wydano',
      it: 'Speso',
      sk: 'Minuté',
      ja: '支出額',
      ko: '지출액',
      hi: 'खर्च किया गया',
      nl: 'Uitgegeven',
      sv: 'Spenderat',
      vi: 'Đã chi',
      id: 'Dibelanjakan',
      da: 'Brugt',
      nb: 'Brukt',
      nn: 'Brukt',
      fi: 'Käytetty',
      is: 'Eytt',
      fo: 'Brúkt',
      cs: 'Utraceno',
      bg: 'Похарчено',
      hr: 'Potrošeno',
      sr: 'Потрошено',
      sl: 'Porabljeno',
      mk: 'Потрошено',
      be: 'Выдаткавана',
      bs: 'Potrošeno',
      hsb: 'Wudate',
    }),
    netLabel: t({
      ru: 'Итог',
      en: 'Net',
      kk: 'Таза сома',
      de: 'Saldo',
      fr: 'Solde net',
      es: 'Neto',
      pt: 'Líquido',
      tr: 'Net',
      uk: 'Підсумок',
      zh: '净额',
      pl: 'Wynik netto',
      it: 'Netto',
      sk: 'Čistý zostatok',
      ja: '純額',
      ko: '순액',
      hi: 'शुद्ध',
      nl: 'Netto',
      sv: 'Netto',
      vi: 'Số dư ròng',
      id: 'Bersih',
      da: 'Netto',
      nb: 'Netto',
      nn: 'Netto',
      fi: 'Netto',
      is: 'Nettó',
      fo: 'Netto',
      cs: 'Čistý tok',
      bg: 'Нето',
      hr: 'Neto',
      sr: 'Нето',
      sl: 'Neto',
      mk: 'Нето',
      be: 'Нета',
      bs: 'Neto',
      hsb: 'Netto',
    }),
    savingsRateLabel: t({
      ru: 'Норма сбережений',
      en: 'Savings rate',
      kk: 'Жинақ нормасы',
      de: 'Sparquote',
      fr: 'Taux d’épargne',
      es: 'Tasa de ahorro',
      pt: 'Taxa de poupança',
      tr: 'Tasarruf oranı',
      uk: 'Норма заощаджень',
      zh: '储蓄率',
      pl: 'Stopa oszczędności',
      it: 'Tasso di risparmio',
      sk: 'Miera úspor',
      ja: '貯蓄率',
      ko: '저축률',
      hi: 'बचत दर',
      nl: 'Spaarquote',
      sv: 'Sparkvot',
      vi: 'Tỷ lệ tiết kiệm',
      id: 'Tingkat tabungan',
      da: 'Opsparingsrate',
      nb: 'Sparerate',
      nn: 'Sparerate',
      fi: 'Säästöaste',
      is: 'Sparnaðarhlutfall',
      fo: 'Sparingarstig',
      cs: 'Míra spoření',
      bg: 'Норма на спестяване',
      hr: 'Stopa štednje',
      sr: 'Стопа штедње',
      sl: 'Stopnja varčevanja',
      mk: 'Стапка на штедење',
      be: 'Норма ашчаджэння',
      bs: 'Stopa štednje',
      hsb: 'Kwota zalutowanja',
    }),
    topCategoriesTitle: t({
      ru: 'Топ категорий',
      en: 'Top categories',
      kk: 'Үздік санаттар',
      de: 'Top-Kategorien',
      fr: 'Catégories principales',
      es: 'Categorías principales',
      pt: 'Principais categorias',
      tr: 'En çok harcanan kategoriler',
      uk: 'Топ категорій',
      zh: '主要分类',
      pl: 'Najważniejsze kategorie',
      it: 'Categorie principali',
      sk: 'Najvýznamnejšie kategórie',
      ja: '上位カテゴリ',
      ko: '상위 카테고리',
      hi: 'शीर्ष श्रेणियाँ',
      nl: 'Topcategorieën',
      sv: 'Toppkategorier',
      vi: 'Danh mục hàng đầu',
      id: 'Kategori teratas',
      da: 'Kontoudtog',
      nb: 'Kontoutskrifter',
      nn: 'Kontoutskrifter',
      fi: 'Tiliotteet',
      is: 'Yfirlit',
      fo: 'Kontoúrtøk',
      cs: 'Výpisy',
      bg: 'Извлечения',
      hr: 'Izvodi',
      sr: 'Изводи',
      sl: 'Izpiski',
      mk: 'Изводи',
      be: 'Выпіскі',
      bs: 'Izvodi',
      hsb: 'Wupisy',
    }),
    viewAll: t({
      ru: 'Все',
      en: 'View all',
      kk: 'Барлығын көру',
      de: 'Alle anzeigen',
      fr: 'Tout afficher',
      es: 'Ver todos',
      pt: 'Ver todos',
      tr: 'Tümünü görüntüle',
      uk: 'Переглянути всі',
      zh: '查看全部',
      pl: 'Zobacz wszystkie',
      it: 'Vedi tutti',
      sk: 'Zobraziť všetky',
      ja: 'すべて表示',
      ko: '전체 보기',
      hi: 'सभी देखें',
      nl: 'Alles bekijken',
      sv: 'Visa alla',
      vi: 'Xem tất cả',
      id: 'Lihat semua',
      da: 'Vis alle',
      nb: 'Vis alle',
      nn: 'Vis alle',
      fi: 'Näytä kaikki',
      is: 'Sýna allt',
      fo: 'Vís allar',
      cs: 'Zobrazit vše',
      bg: 'Виж всички',
      hr: 'Prikaži sve',
      sr: 'Прикажи све',
      sl: 'Pokaži vse',
      mk: 'Прикажи сите',
      be: 'Паказаць усе',
      bs: 'Prikaži sve',
      hsb: 'Wšě pokazać',
    }),
    goalsViewAll: t({
      ru: 'Все цели',
      en: 'View all goals',
      kk: 'Барлық мақсаттар',
      de: 'Alle Ziele anzeigen',
      fr: 'Voir tous les objectifs',
      es: 'Ver todas las metas',
      pt: 'Ver todos os objetivos',
      tr: 'Tüm hedefleri görüntüle',
      uk: 'Усі цілі',
      zh: '查看全部目标',
      pl: 'Zobacz wszystkie cele',
      it: 'Vedi tutti gli obiettivi',
      sk: 'Zobraziť všetky ciele',
      ja: 'すべての目標を表示',
      ko: '모든 목표 보기',
      hi: 'सभी लक्ष्य देखें',
      nl: 'Alle doelen bekijken',
      sv: 'Visa alla mål',
      vi: 'Xem tất cả mục tiêu',
      id: 'Lihat semua target',
      da: 'Vis alle mål',
      nb: 'Vis alle mål',
      nn: 'Vis alle mål',
      fi: 'Näytä kaikki tavoitteet',
      is: 'Sýna öll markmið',
      fo: 'Vís øll mál',
      cs: 'Zobrazit všechny cíle',
      bg: 'Виж всички цели',
      hr: 'Prikaži sve ciljeve',
      sr: 'Прикажи све циљеве',
      sl: 'Pokaži vse cilje',
      mk: 'Прикажи ги сите цели',
      be: 'Паказаць усе мэты',
      bs: 'Prikaži sve ciljeve',
      hsb: 'Wšě cile pokazać',
    }),
    goalsSavedInMonth: t({
      ru: 'отложено за месяц',
      en: 'saved this month',
      kk: 'осы айда жиналды',
      de: 'in diesem Monat gespart',
      fr: 'épargné ce mois-ci',
      es: 'ahorrado este mes',
      pt: 'poupado este mês',
      tr: 'bu ay biriktirildi',
      uk: 'відкладено за місяць',
      zh: '本月已存入',
      pl: 'odłożone w tym miesiącu',
      it: 'risparmiato questo mese',
      sk: 'odložené tento mesiac',
      ja: '今月の積立',
      ko: '이번 달 저축',
      hi: 'इस महीने बचाया',
      nl: 'deze maand gespaard',
      sv: 'sparat denna månad',
      vi: 'đã tiết kiệm trong tháng này',
      id: 'ditabung bulan ini',
      da: 'sparet op denne måned',
      nb: 'spart denne måneden',
      nn: 'spart denne månaden',
      fi: 'säästetty tässä kuussa',
      is: 'lagt til hliðar í þessum mánuði',
      fo: 'goymt henda mánaðin',
      cs: 'odloženo tento měsíc',
      bg: 'спестено този месец',
      hr: 'ušteđeno ovaj mjesec',
      sr: 'уштеђено овог месеца',
      sl: 'prihranjeno ta mesec',
      mk: 'заштедено овој месец',
      be: 'адкладзена за месяц',
      bs: 'ušteđeno ovaj mjesec',
      hsb: 'tutón měsac založene',
    }),
    goalsEmptyInMonth: t({
      ru: 'В этом месяце вы ещё не продвинули ни одной цели',
      en: "You haven't moved any goal forward this month",
      kk: 'Бұл айда сіз әлі бірде-бір мақсатты алға жылжытқан жоқсыз',
      de: 'In diesem Monat haben Sie noch kein Ziel vorangebracht',
      fr: "Ce mois-ci, vous n'avez encore fait avancer aucun objectif",
      es: 'Este mes aún no ha avanzado ninguna meta',
      pt: 'Este mês ainda não avançou nenhum objetivo',
      tr: 'Bu ay henüz hiçbir hedefi ilerletmediniz',
      uk: 'Цього місяця ви ще не просунули жодної цілі',
      zh: '本月您还没有为任何目标存入资金',
      pl: 'W tym miesiącu nie posunąłeś jeszcze żadnego celu',
      it: 'Questo mese non hai ancora fatto progressi su nessun obiettivo',
      sk: 'Tento mesiac ste zatiaľ neposunuli žiadny cieľ',
      ja: '今月はまだどの目標も進んでいません',
      ko: '이번 달에는 아직 진행한 목표가 없습니다',
      hi: 'इस महीने आपने अभी तक किसी लक्ष्य की ओर कुछ नहीं जोड़ा',
      nl: 'Deze maand hebt u nog geen doel vooruitgeholpen',
      sv: 'Den här månaden har du ännu inte fört något mål framåt',
      vi: 'Tháng này bạn chưa tiến thêm cho mục tiêu nào',
      id: 'Bulan ini Anda belum memajukan target apa pun',
      da: 'Denne måned har du endnu ikke rykket et mål fremad',
      nb: 'Denne måneden har du ennå ikke flyttet noe mål framover',
      nn: 'Denne månaden har du enno ikkje flytta noko mål framover',
      fi: 'Tässä kuussa et ole vielä edistänyt yhtään tavoitetta',
      is: 'Í þessum mánuði hefurðu ekki enn komið neinu markmiði áleiðis',
      fo: 'Henda mánaðin hevur tú enn ikki flutt nakað mál fram',
      cs: 'Tento měsíc jste zatím neposunuli žádný cíl',
      bg: 'Този месец още не сте придвижили нито една цел',
      hr: 'Ovaj mjesec još niste pomaknuli nijedan cilj',
      sr: 'Овог месеца још нисте помакли ниједан циљ',
      sl: 'Ta mesec še niste premaknili nobenega cilja',
      mk: 'Овој месец сè уште не сте придвижиле ниту една цел',
      be: 'У гэтым месяцы вы яшчэ не прасунулі ніводнай мэты',
      bs: 'Ovaj mjesec još niste pomakli nijedan cilj',
      hsb: 'Tutón měsac njejsće hišće žadyn cil doprědka sunyli',
    }),
    netCaption: t({
      ru: 'Доход минус расходы',
      en: 'Income minus spending',
      kk: 'Кіріс минус шығыс',
      de: 'Einnahmen minus Ausgaben',
      fr: 'Revenus moins dépenses',
      es: 'Ingresos menos gastos',
      pt: 'Receitas menos despesas',
      tr: 'Gelir eksi harcama',
      uk: 'Дохід мінус витрати',
      zh: '收入减去支出',
      pl: 'Przychody minus wydatki',
      it: 'Entrate meno spese',
      sk: 'Príjmy mínus výdavky',
      ja: '収入から支出を引いた額',
      ko: '수입에서 지출을 뺀 금액',
      hi: 'आय घटा खर्च',
      nl: 'Inkomsten min uitgaven',
      sv: 'Inkomst minus utgifter',
      vi: 'Thu nhập trừ chi tiêu',
      id: 'Pendapatan dikurangi pengeluaran',
      da: 'Andel af indtægten, der er tilbage efter udgifter',
      nb: 'Andel av inntekten som er igjen etter utgifter',
      nn: 'Del av inntekta som er att etter utgifter',
      fi: 'Osuus tuloista, joka jää kulujen jälkeen',
      is: 'Hlutfall tekna sem eftir stendur þegar útgjöld eru dregin frá',
      fo: 'Partur av inntøkuni, sum er eftir, tá útreiðslurnar eru rindaðar',
      cs: 'Podíl příjmů, který zbude po výdajích',
      bg: 'Дял от дохода, който остава след разходите',
      hr: 'Dio dohotka koji ostaje nakon troškova',
      sr: 'Део дохотка који остаје након трошкова',
      sl: 'Delež dohodka, ki ostane po stroških',
      mk: 'Дел од доходот што останува по трошоците',
      be: 'Доля прыбытку, якая застаецца пасля выдаткаў',
      bs: 'Dio dohotka koji ostaje nakon troškova',
      hsb: 'Dźěl dochoda, kotryž po wudawkach wostanje',
    }),
    savingsRateCaption: t({
      ru: 'Доля дохода, оставшаяся после расходов',
      en: 'Share of income left after spending',
      kk: 'Шығыстардан кейін қалған кіріс үлесі',
      de: 'Anteil des Einkommens, der nach Ausgaben bleibt',
      fr: 'Part du revenu restant après dépenses',
      es: 'Parte de los ingresos que queda tras los gastos',
      pt: 'Parte da receita que sobra após as despesas',
      tr: 'Harcamalardan sonra kalan gelir payı',
      uk: 'Частка доходу, що лишилася після витрат',
      zh: '支出后剩余的收入占比',
      pl: 'Udział dochodu pozostały po wydatkach',
      it: 'Quota di reddito rimasta dopo le spese',
      sk: 'Podiel príjmu, ktorý zostal po výdavkoch',
      ja: '支出後に残る収入の割合',
      ko: '지출 후 남은 수입 비율',
      hi: 'खर्च के बाद बची आय का हिस्सा',
      nl: 'Aandeel van het inkomen dat overblijft na uitgaven',
      sv: 'Andel av inkomsten som återstår efter utgifter',
      vi: 'Phần thu nhập còn lại sau chi tiêu',
      id: 'Bagian pendapatan yang tersisa setelah pengeluaran',
      da: 'Andel af indtægten, der er tilbage efter udgifter',
      nb: 'Andel av inntekten som er igjen etter utgifter',
      nn: 'Del av inntekta som er att etter utgifter',
      fi: 'Osuus tuloista, joka jää kulujen jälkeen',
      is: 'Hlutfall tekna sem eftir stendur þegar útgjöld eru dregin frá',
      fo: 'Partur av inntøkuni, sum er eftir, tá útreiðslurnar eru rindaðar',
      cs: 'Podíl příjmů, který zbude po výdajích',
      bg: 'Дял от дохода, който остава след разходите',
      hr: 'Dio dohotka koji ostaje nakon troškova',
      sr: 'Део дохотка који остаје након трошкова',
      sl: 'Delež dohodka, ki ostane po stroških',
      mk: 'Дел од доходот што останува по трошоците',
      be: 'Доля прыбытку, якая застаецца пасля выдаткаў',
      bs: 'Dio dohotka koji ostaje nakon troškova',
      hsb: 'Dźěl dochoda, kotryž po wudawkach wostanje',
    }),
  },
} satisfies Dictionary;

export default content;
