import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'recentTransactionsCard',
  content: {
    title: t({
      ru: 'Последние транзакции',
      en: 'Recent transactions',
      kk: 'Соңғы транзакциялар',
      de: 'Letzte Transaktionen',
      fr: 'Transactions récentes',
      es: 'Transacciones recientes',
      pt: 'Transações recentes',
      tr: 'Son işlemler',
      uk: 'Останні транзакції',
      zh: '最近交易',
      ar: 'المعاملات الأخيرة',
      pl: 'Ostatnie transakcje',
      it: 'Transazioni recenti',
      sk: 'Nedávne transakcie',
      ja: '最近の取引',
      ko: '최근 거래',
      hi: 'हाल के लेनदेन',
      nl: 'Recente transacties',
      sv: 'Senaste transaktioner',
      vi: 'Giao dịch gần đây',
      id: 'Transaksi terbaru',
    }),
    viewAll: t({
      ru: 'Все транзакции',
      en: 'All transactions',
      kk: 'Барлық транзакциялар',
      de: 'Alle Transaktionen',
      fr: 'Toutes les transactions',
      es: 'Todas las transacciones',
      pt: 'Todas as transações',
      tr: 'Tüm işlemler',
      uk: 'Усі транзакції',
      zh: '所有交易',
      ar: 'جميع المعاملات',
      pl: 'Wszystkie transakcje',
      it: 'Tutte le transazioni',
      sk: 'Všetky transakcie',
      ja: 'すべての取引',
      ko: '모든 거래',
      hi: 'सभी लेनदेन',
      nl: 'Alle transacties',
      sv: 'Alla transaktioner',
      vi: 'Tất cả giao dịch',
      id: 'Semua transaksi',
    }),
    empty: t({
      ru: 'Нет транзакций за этот период',
      en: 'No transactions this period',
      kk: 'Бұл кезеңде транзакциялар жоқ',
      de: 'Keine Transaktionen in diesem Zeitraum',
      fr: 'Aucune transaction sur cette période',
      es: 'No hay transacciones en este período',
      pt: 'Sem transações neste período',
      tr: 'Bu dönemde işlem yok',
      uk: 'Немає транзакцій за цей період',
      zh: '本期间无交易',
      ar: 'لا توجد معاملات في هذه الفترة',
      pl: 'Brak transakcji w tym okresie',
      it: 'Nessuna transazione in questo periodo',
      sk: 'V tomto období žiadne transakcie',
      ja: 'この期間の取引はありません',
      ko: '이 기간에는 거래가 없습니다',
      hi: 'इस अवधि में कोई लेनदेन नहीं',
      nl: 'Geen transacties in deze periode',
      sv: 'Inga transaktioner denna period',
      vi: 'Không có giao dịch trong kỳ này',
      id: 'Tidak ada transaksi periode ini',
    }),
    uncategorized: t({
      ru: 'Без категории',
      en: 'Uncategorized',
      kk: 'Санатсыз',
      de: 'Nicht kategorisiert',
      fr: 'Non catégorisé',
      es: 'Sin categoría',
      pt: 'Sem categoria',
      tr: 'Kategorisiz',
      uk: 'Без категорії',
      zh: '未分类',
      ar: 'غير مصنّف',
      pl: 'Bez kategorii',
      it: 'Senza categoria',
      sk: 'Bez kategórie',
      ja: '未分類',
      ko: '미분류',
      hi: 'अवर्गीकृत',
      nl: 'Niet gecategoriseerd',
      sv: 'Okategoriserat',
      vi: 'Chưa phân loại',
      id: 'Belum dikategorikan',
    }),
  },
} satisfies Dictionary;

export default content;
