import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'trendsTab',
  content: {
    showingPeriodPrefix: t({
      ru: 'Показан последний доступный период:',
      en: 'Showing latest available period:',
      kk: 'Соңғы қолжетімді кезең көрсетілген:',
      de: 'Zeigt den letzten verfügbaren Zeitraum:',
      fr: 'Affichage de la dernière période disponible :',
      es: 'Mostrando el último período disponible:',
      pt: 'Mostrando o último período disponível:',
      tr: 'Son kullanılabilir dönem gösteriliyor:',
      uk: 'Показано останній доступний період:',
      zh: '显示最近可用的时间段：',
      ar: 'عرض آخر فترة متاحة:',
      pl: 'Wyświetlono ostatni dostępny okres:',
      it: "Visualizzazione dell'ultimo periodo disponibile:",
      sk: 'Zobrazuje sa posledné dostupné obdobie:',
      ja: '利用可能な最新期間を表示中：',
      ko: '최신 사용 가능 기간을 표시 중:',
      hi: 'नवीनतम उपलब्ध अवधि दिखाई जा रही है:',
      nl: 'Meest recente beschikbare periode wordt weergegeven:',
      sv: 'Visar senaste tillgängliga period:',
      vi: 'Đang hiển thị khoảng thời gian gần nhất có sẵn:',
      id: 'Menampilkan periode terbaru yang tersedia:',
    }),
    noTrendDataForPeriod: t({
      ru: 'Нет данных о трендах за этот период.',
      en: 'No trend data available for this period.',
      kk: 'Бұл кезең үшін тренд деректері жоқ.',
      de: 'Für diesen Zeitraum sind keine Trenddaten verfügbar.',
      fr: 'Aucune donnée de tendance disponible pour cette période.',
      es: 'No hay datos de tendencias disponibles para este período.',
      pt: 'Não há dados de tendência disponíveis para este período.',
      tr: 'Bu dönem için trend verisi bulunmuyor.',
      uk: 'Немає даних про тренди за цей період.',
      zh: '该时间段暂无趋势数据。',
      ar: 'لا توجد بيانات اتجاهات متاحة لهذه الفترة.',
      pl: 'Brak danych o trendach dla tego okresu.',
      it: 'Nessun dato sulle tendenze disponibile per questo periodo.',
      sk: 'Pre toto obdobie nie sú k dispozícii žiadne údaje o trendoch.',
      ja: 'この期間のトレンドデータはありません。',
      ko: '이 기간에 대한 트렌드 데이터가 없습니다.',
      hi: 'इस अवधि के लिए कोई ट्रेंड डेटा उपलब्ध नहीं है।',
      nl: 'Geen trendgegevens beschikbaar voor deze periode.',
      sv: 'Ingen trenddata tillgänglig för den här perioden.',
      vi: 'Không có dữ liệu xu hướng cho khoảng thời gian này.',
      id: 'Tidak ada data tren yang tersedia untuk periode ini.',
    }),
    statementsTitle: t({
      ru: 'ВЫПИСКИ',
      en: 'STATEMENTS',
      kk: 'ҮЗІНДІЛЕР',
      de: 'KONTOAUSZÜGE',
      fr: 'RELEVÉS',
      es: 'EXTRACTOS',
      pt: 'EXTRATOS',
      tr: 'EKSTRELER',
      uk: 'ВИПИСКИ',
      zh: '对账单',
      ar: 'كشوف الحساب',
      pl: 'WYCIĄGI',
      it: 'ESTRATTI CONTO',
      sk: 'VÝPISY',
      ja: '明細書',
      ko: '명세서',
      hi: 'विवरण',
      nl: 'AFSCHRIFTEN',
      sv: 'KONTOUTDRAG',
      vi: 'SAO KÊ',
      id: 'LAPORAN REKENING',
    }),
    netFlowTitle: t({
      ru: 'ЧИСТЫЙ ПОТОК',
      en: 'NET FLOW',
      kk: 'ТАЗА АҒЫН',
      de: 'NETTOFLUSS',
      fr: 'FLUX NET',
      es: 'FLUJO NETO',
      pt: 'FLUXO LÍQUIDO',
      tr: 'NET AKIŞ',
      uk: 'ЧИСТИЙ ПОТІК',
      zh: '净现金流',
      ar: 'صافي التدفق',
      pl: 'PRZEPŁYW NETTO',
      it: 'FLUSSO NETTO',
      sk: 'ČISTÝ TOK',
      ja: '純収支',
      ko: '순 흐름',
      hi: 'शुद्ध प्रवाह',
      nl: 'NETTOSTROOM',
      sv: 'NETTOFLÖDE',
      vi: 'DÒNG TIỀN RÒNG',
      id: 'ARUS BERSIH',
    }),
    counterpartiesTitle: t({
      ru: 'КОНТРАГЕНТЫ',
      en: 'COUNTERPARTIES',
      kk: 'КОНТРАГЕНТТЕР',
      de: 'GESCHÄFTSPARTNER',
      fr: 'CONTREPARTIES',
      es: 'CONTRAPARTES',
      pt: 'CONTRAPARTES',
      tr: 'KARŞI TARAFLAR',
      uk: 'КОНТРАГЕНТИ',
      zh: '交易对手',
      ar: 'الأطراف المقابلة',
      pl: 'KONTRAHENCI',
      it: 'CONTROPARTI',
      sk: 'PROTISTRANY',
      ja: '取引先',
      ko: '거래 상대방',
      hi: 'प्रतिपक्ष',
      nl: 'TEGENPARTIJEN',
      sv: 'MOTPARTER',
      vi: 'ĐỐI TÁC',
      id: 'REKANAN',
    }),
    income: t({
      ru: 'Приход',
      en: 'Income',
      kk: 'Кіріс',
      de: 'Einnahme',
      fr: 'Revenu',
      es: 'Ingreso',
      pt: 'Receita',
      tr: 'Gelir',
      uk: 'Прихід',
      zh: '收入',
      ar: 'دخل',
      pl: 'Przychód',
      it: 'Entrata',
      sk: 'Príjem',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomsten',
      sv: 'Inkomst',
      vi: 'Thu nhập',
      id: 'Pendapatan',
    }),
    expense: t({
      ru: 'Расход',
      en: 'Expense',
      kk: 'Шығыс',
      de: 'Ausgabe',
      fr: 'Dépense',
      es: 'Gasto',
      pt: 'Despesa',
      tr: 'Gider',
      uk: 'Витрата',
      zh: '支出',
      ar: 'مصروف',
      pl: 'Wydatek',
      it: 'Spesa',
      sk: 'Výdavok',
      ja: '支出',
      ko: '지출',
      hi: 'व्यय',
      nl: 'Uitgave',
      sv: 'Utgift',
      vi: 'Chi phí',
      id: 'Pengeluaran',
    }),
    categories: t({
      ru: 'Категории',
      en: 'Categories',
      kk: 'Санаттар',
      de: 'Kategorien',
      fr: 'Catégories',
      es: 'Categorías',
      pt: 'Categorias',
      tr: 'Kategoriler',
      uk: 'Категорії',
      zh: '类别',
      ar: 'الفئات',
      pl: 'Kategorie',
      it: 'Categorie',
      sk: 'Kategórie',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणियाँ',
      nl: 'Categorieën',
      sv: 'Kategorier',
      vi: 'Danh mục',
      id: 'Kategori',
    }),
    totalFound: t({
      ru: 'Всего найдено',
      en: 'Total found',
      kk: 'Барлығы табылды',
      de: 'Insgesamt gefunden',
      fr: 'Total trouvé',
      es: 'Total encontrado',
      pt: 'Total encontrado',
      tr: 'Toplam bulunan',
      uk: 'Всього знайдено',
      zh: '共找到',
      ar: 'الإجمالي الموجود',
      pl: 'Łącznie znaleziono',
      it: 'Totale trovato',
      sk: 'Celkovo nájdených',
      ja: '検出件数',
      ko: '총 발견 수',
      hi: 'कुल पाए गए',
      nl: 'Totaal gevonden',
      sv: 'Totalt hittade',
      vi: 'Tổng số tìm thấy',
      id: 'Total ditemukan',
    }),
    spendTrendTitle: t({
      ru: 'Динамика расходов',
      en: 'Spend trend',
      kk: 'Шығыс динамикасы',
      de: 'Ausgabentrend',
      fr: 'Tendance des dépenses',
      es: 'Tendencia de gastos',
      pt: 'Tendência de gastos',
      tr: 'Harcama trendi',
      uk: 'Динаміка витрат',
      zh: '支出趋势',
      ar: 'اتجاه الإنفاق',
      pl: 'Trend wydatków',
      it: 'Andamento della spesa',
      sk: 'Trend výdavkov',
      ja: '支出トレンド',
      ko: '지출 추세',
      hi: 'खर्च का रुझान',
      nl: 'Uitgaventrend',
      sv: 'Utgiftstrend',
      vi: 'Xu hướng chi tiêu',
      id: 'Tren pengeluaran',
    }),
    categoryBreakdownTitle: t({
      ru: 'Разбивка по категориям',
      en: 'Category breakdown',
      kk: 'Санаттар бойынша бөлу',
      de: 'Kategorienübersicht',
      fr: 'Répartition par catégorie',
      es: 'Desglose por categoría',
      pt: 'Detalhamento por categoria',
      tr: 'Kategori dağılımı',
      uk: 'Розподіл за категоріями',
      zh: '类别明细',
      ar: 'توزيع الفئات',
      pl: 'Podział na kategorie',
      it: 'Ripartizione per categoria',
      sk: 'Rozdelenie podľa kategórií',
      ja: 'カテゴリ内訳',
      ko: '카테고리별 분류',
      hi: 'श्रेणी के अनुसार विवरण',
      nl: 'Categorieverdeling',
      sv: 'Kategoriuppdelning',
      vi: 'Phân tích theo danh mục',
      id: 'Rincian kategori',
    }),
    noTrendDataForRange: t({
      ru: 'Нет данных о трендах за выбранный период',
      en: 'No trend data available for selected range',
      kk: 'Таңдалған кезең үшін тренд деректері жоқ',
      de: 'Für den ausgewählten Zeitraum sind keine Trenddaten verfügbar',
      fr: 'Aucune donnée de tendance disponible pour la période sélectionnée',
      es: 'No hay datos de tendencias disponibles para el rango seleccionado',
      pt: 'Não há dados de tendência disponíveis para o intervalo selecionado',
      tr: 'Seçilen aralık için trend verisi bulunmuyor',
      uk: 'Немає даних про тренди за вибраний період',
      zh: '所选时间范围内暂无趋势数据',
      ar: 'لا توجد بيانات اتجاهات متاحة للنطاق المحدد',
      pl: 'Brak danych o trendach dla wybranego zakresu',
      it: "Nessun dato sulle tendenze disponibile per l'intervallo selezionato",
      sk: 'Pre vybrané obdobie nie sú k dispozícii žiadne údaje o trendoch',
      ja: '選択した範囲のトレンドデータはありません',
      ko: '선택한 범위에 대한 트렌드 데이터가 없습니다',
      hi: 'चयनित सीमा के लिए कोई ट्रेंड डेटा उपलब्ध नहीं है',
      nl: 'Geen trendgegevens beschikbaar voor de geselecteerde periode',
      sv: 'Ingen trenddata tillgänglig för det valda intervallet',
      vi: 'Không có dữ liệu xu hướng cho khoảng đã chọn',
      id: 'Tidak ada data tren untuk rentang yang dipilih',
    }),
    noCategorizedTransactions: t({
      ru: 'Нет категоризированных транзакций для визуализации',
      en: 'No categorized transactions to visualize',
      kk: 'Визуализациялау үшін санатталған транзакциялар жоқ',
      de: 'Keine kategorisierten Transaktionen zum Visualisieren',
      fr: 'Aucune transaction catégorisée à visualiser',
      es: 'No hay transacciones categorizadas para visualizar',
      pt: 'Não há transações categorizadas para visualizar',
      tr: 'Görselleştirilecek kategorilendirilmiş işlem yok',
      uk: 'Немає категоризованих транзакцій для візуалізації',
      zh: '没有可供可视化的已分类交易',
      ar: 'لا توجد معاملات مصنّفة لعرضها',
      pl: 'Brak skategoryzowanych transakcji do wizualizacji',
      it: 'Nessuna transazione categorizzata da visualizzare',
      sk: 'Žiadne kategorizované transakcie na vizualizáciu',
      ja: '可視化できるカテゴリ分類済みの取引がありません',
      ko: '시각화할 분류된 거래가 없습니다',
      hi: 'विज़ुअलाइज़ करने के लिए कोई श्रेणीबद्ध लेनदेन नहीं है',
      nl: 'Geen gecategoriseerde transacties om te visualiseren',
      sv: 'Inga kategoriserade transaktioner att visualisera',
      vi: 'Không có giao dịch đã phân loại để hiển thị',
      id: 'Tidak ada transaksi berkategori untuk divisualisasikan',
    }),
    forecastSuffix: t({
      ru: ' (прогноз)',
      en: ' (forecast)',
      kk: ' (болжам)',
      de: ' (Prognose)',
      fr: ' (prévision)',
      es: ' (previsión)',
      pt: ' (previsão)',
      tr: ' (tahmin)',
      uk: ' (прогноз)',
      zh: '（预测）',
      ar: ' (توقع)',
      pl: ' (prognoza)',
      it: ' (previsione)',
      sk: ' (prognóza)',
      ja: '（予測）',
      ko: ' (예측)',
      hi: ' (पूर्वानुमान)',
      nl: ' (prognose)',
      sv: ' (prognos)',
      vi: ' (dự báo)',
      id: ' (perkiraan)',
    }),
    forecastLabel: t({
      ru: 'Прогноз →',
      en: 'Forecast →',
      kk: 'Болжам →',
      de: 'Prognose →',
      fr: 'Prévision →',
      es: 'Previsión →',
      pt: 'Previsão →',
      tr: 'Tahmin →',
      uk: 'Прогноз →',
      zh: '预测 →',
      ar: 'توقع →',
      pl: 'Prognoza →',
      it: 'Previsione →',
      sk: 'Prognóza →',
      ja: '予測 →',
      ko: '예측 →',
      hi: 'पूर्वानुमान →',
      nl: 'Prognose →',
      sv: 'Prognos →',
      vi: 'Dự báo →',
      id: 'Perkiraan →',
    }),
    expenseCategoriesSeriesName: t({
      ru: 'Категории расходов',
      en: 'Expense categories',
      kk: 'Шығыс санаттары',
      de: 'Ausgabenkategorien',
      fr: 'Catégories de dépenses',
      es: 'Categorías de gastos',
      pt: 'Categorias de despesas',
      tr: 'Gider kategorileri',
      uk: 'Категорії витрат',
      zh: '支出类别',
      ar: 'فئات المصروفات',
      pl: 'Kategorie wydatków',
      it: 'Categorie di spesa',
      sk: 'Kategórie výdavkov',
      ja: '支出カテゴリ',
      ko: '지출 카테고리',
      hi: 'व्यय श्रेणियाँ',
      nl: 'Uitgavencategorieën',
      sv: 'Utgiftskategorier',
      vi: 'Danh mục chi tiêu',
      id: 'Kategori pengeluaran',
    }),
  },
} satisfies Dictionary;

export default content;
