import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'payableMarkPaid',
  content: {
    titlePaid: t({
      ru: 'Отметить оплату',
      en: 'Mark as paid',
      kk: 'Төлемді белгілеу',
      de: 'Als bezahlt markieren',
      fr: 'Marquer comme payé',
      es: 'Marcar como pagado',
      pt: 'Marcar como pago',
      tr: 'Ödendi olarak işaretle',
      uk: 'Позначити оплату',
      zh: '标记为已付款',
      ar: 'وضع علامة مدفوع',
      pl: 'Oznacz jako zapłacone',
      it: 'Segna come pagato',
      sk: 'Označiť ako zaplatené',
      ja: '支払済みにする',
      ko: '지급 완료로 표시',
      hi: 'भुगतान के रूप में चिह्नित करें',
      nl: 'Markeren als betaald',
      sv: 'Markera som betald',
      vi: 'Đánh dấu đã thanh toán',
      id: 'Tandai sudah dibayar',
    }),
    titleReceived: t({
      ru: 'Отметить поступление',
      en: 'Mark as received',
      kk: 'Түсімді белгілеу',
      de: 'Als erhalten markieren',
      fr: 'Marquer comme reçu',
      es: 'Marcar como cobrado',
      pt: 'Marcar como recebido',
      tr: 'Tahsil edildi olarak işaretle',
      uk: 'Позначити надходження',
      zh: '标记为已收款',
      ar: 'وضع علامة مستلم',
      pl: 'Oznacz jako otrzymane',
      it: 'Segna come incassato',
      sk: 'Označiť ako prijaté',
      ja: '入金済みにする',
      ko: '수금 완료로 표시',
      hi: 'प्राप्त के रूप में चिह्नित करें',
      nl: 'Markeren als ontvangen',
      sv: 'Markera som mottagen',
      vi: 'Đánh dấu đã nhận',
      id: 'Tandai sudah diterima',
    }),
    modeMatch: t({
      ru: 'Операция из выписки',
      en: 'Bank transaction',
      kk: 'Үзіндідегі операция',
      de: 'Banktransaktion',
      fr: 'Opération bancaire',
      es: 'Movimiento bancario',
      pt: 'Transação bancária',
      tr: 'Banka işlemi',
      uk: 'Операція з виписки',
      zh: '银行交易',
      ar: 'معاملة بنكية',
      pl: 'Transakcja bankowa',
      it: 'Movimento bancario',
      sk: 'Bankový pohyb',
      ja: '銀行取引',
      ko: '은행 거래',
      hi: 'बैंक लेनदेन',
      nl: 'Banktransactie',
      sv: 'Banktransaktion',
      vi: 'Giao dịch ngân hàng',
      id: 'Transaksi bank',
    }),
    modeCash: t({
      ru: 'Наличными из кошелька',
      en: 'Cash from a wallet',
      kk: 'Әмияннан қолма-қол',
      de: 'Bar aus einer Wallet',
      fr: 'En espèces depuis un portefeuille',
      es: 'En efectivo desde una billetera',
      pt: 'Em dinheiro de uma carteira',
      tr: 'Cüzdandan nakit',
      uk: 'Готівкою з гаманця',
      zh: '从钱包付现金',
      ar: 'نقدًا من محفظة',
      pl: 'Gotówką z portfela',
      it: 'In contanti da un portafoglio',
      sk: 'Hotovosťou z peňaženky',
      ja: 'ウォレットから現金',
      ko: '지갑에서 현금',
      hi: 'वॉलेट से नकद',
      nl: 'Contant uit een portemonnee',
      sv: 'Kontant från en plånbok',
      vi: 'Tiền mặt từ ví',
      id: 'Tunai dari dompet',
    }),
    modePlain: t({
      ru: 'Просто отметить',
      en: 'Just mark it',
      kk: 'Жай белгілеу',
      de: 'Nur markieren',
      fr: 'Marquer seulement',
      es: 'Solo marcar',
      pt: 'Apenas marcar',
      tr: 'Sadece işaretle',
      uk: 'Просто позначити',
      zh: '仅标记',
      ar: 'وضع علامة فقط',
      pl: 'Tylko oznacz',
      it: 'Segna soltanto',
      sk: 'Iba označiť',
      ja: 'マークのみ',
      ko: '표시만 하기',
      hi: 'केवल चिह्नित करें',
      nl: 'Alleen markeren',
      sv: 'Markera bara',
      vi: 'Chỉ đánh dấu',
      id: 'Tandai saja',
    }),
    matchHint: t({
      ru: 'Выберите операцию, которой закрыт счёт. Она уже есть в выписке, новая транзакция не создаётся.',
      en: 'Pick the transaction that settled the bill. It is already on a statement, so no new transaction is created.',
      kk: 'Шотты жапқан операцияны таңдаңыз. Ол үзіндіде бар, жаңа транзакция жасалмайды.',
      de: 'Wählen Sie die Transaktion, mit der die Rechnung beglichen wurde. Sie steht bereits im Auszug, es wird keine neue angelegt.',
      fr: 'Choisissez l’opération qui a réglé la facture. Elle figure déjà sur un relevé : aucune nouvelle opération n’est créée.',
      es: 'Elija el movimiento que saldó la factura. Ya está en un extracto, así que no se crea uno nuevo.',
      pt: 'Escolha a transação que liquidou a fatura. Ela já está num extrato, por isso nenhuma nova é criada.',
      tr: 'Faturayı kapatan işlemi seçin. Zaten bir ekstrede olduğu için yeni işlem oluşturulmaz.',
      uk: 'Виберіть операцію, якою закрито рахунок. Вона вже є у виписці, нова транзакція не створюється.',
      zh: '选择结清该账单的交易。它已在对账单中，不会新建交易。',
      ar: 'اختر المعاملة التي سددت الفاتورة. إنها موجودة في كشف الحساب، لذا لن تُنشأ معاملة جديدة.',
      pl: 'Wybierz transakcję, którą opłacono rachunek. Jest już na wyciągu, więc nowa nie powstanie.',
      it: 'Scegli il movimento che ha saldato la fattura. È già in un estratto, quindi non ne viene creato uno nuovo.',
      sk: 'Vyberte pohyb, ktorým bol účet uhradený. Už je vo výpise, nový sa nevytvorí.',
      ja: '請求を精算した取引を選んでください。明細に既にあるため、新しい取引は作成されません。',
      ko: '청구서를 정산한 거래를 선택하세요. 이미 명세서에 있으므로 새 거래는 만들어지지 않습니다.',
      hi: 'बिल चुकाने वाला लेनदेन चुनें। यह पहले से स्टेटमेंट में है, इसलिए नया लेनदेन नहीं बनेगा।',
      nl: 'Kies de transactie waarmee de rekening is betaald. Die staat al op een afschrift, er wordt geen nieuwe aangemaakt.',
      sv: 'Välj transaktionen som betalade räkningen. Den finns redan på ett kontoutdrag, så ingen ny skapas.',
      vi: 'Chọn giao dịch đã thanh toán hóa đơn. Giao dịch đã có trong sao kê nên không tạo mới.',
      id: 'Pilih transaksi yang melunasi tagihan. Transaksi itu sudah ada di rekening koran, jadi tidak dibuat yang baru.',
    }),
    noCandidates: t({
      ru: 'Подходящих операций нет: та же сумма и валюта, не раньше чем за 30 дней до срока.',
      en: 'No matching transactions: same amount and currency, from 30 days before the due date.',
      kk: 'Сәйкес операциялар жоқ: сол сома мен валюта, мерзімнен 30 күн бұрын бастап.',
      de: 'Keine passenden Transaktionen: gleicher Betrag und gleiche Währung, ab 30 Tage vor Fälligkeit.',
      fr: 'Aucune opération correspondante : même montant et même devise, à partir de 30 jours avant l’échéance.',
      es: 'No hay movimientos que coincidan: mismo importe y moneda, desde 30 días antes del vencimiento.',
      pt: 'Nenhuma transação correspondente: mesmo valor e moeda, a partir de 30 dias antes do vencimento.',
      tr: 'Eşleşen işlem yok: aynı tutar ve para birimi, vadeden 30 gün öncesinden itibaren.',
      uk: 'Відповідних операцій немає: та сама сума й валюта, не раніше ніж за 30 днів до строку.',
      zh: '没有匹配的交易：金额和币种相同，且在到期日前 30 天之内。',
      ar: 'لا توجد معاملات مطابقة: نفس المبلغ والعملة، بدءًا من 30 يومًا قبل الاستحقاق.',
      pl: 'Brak pasujących transakcji: ta sama kwota i waluta, od 30 dni przed terminem.',
      it: 'Nessun movimento corrispondente: stesso importo e valuta, da 30 giorni prima della scadenza.',
      sk: 'Žiadne zodpovedajúce pohyby: rovnaká suma a mena, od 30 dní pred splatnosťou.',
      ja: '一致する取引はありません（同じ金額・通貨、期日の30日前以降）。',
      ko: '일치하는 거래가 없습니다(같은 금액과 통화, 기한 30일 전부터).',
      hi: 'कोई मिलता लेनदेन नहीं: वही राशि और मुद्रा, नियत तिथि से 30 दिन पहले से।',
      nl: 'Geen passende transacties: zelfde bedrag en valuta, vanaf 30 dagen voor de vervaldatum.',
      sv: 'Inga matchande transaktioner: samma belopp och valuta, från 30 dagar före förfallodagen.',
      vi: 'Không có giao dịch phù hợp: cùng số tiền và tiền tệ, từ 30 ngày trước hạn.',
      id: 'Tidak ada transaksi yang cocok: jumlah dan mata uang sama, sejak 30 hari sebelum jatuh tempo.',
    }),
    vendorMatch: t({
      ru: 'Контрагент совпадает',
      en: 'Names the vendor',
      kk: 'Контрагент сәйкес',
      de: 'Nennt den Empfänger',
      fr: 'Mentionne le tiers',
      es: 'Menciona al proveedor',
      pt: 'Menciona o fornecedor',
      tr: 'Karşı tarafı içeriyor',
      uk: 'Контрагент збігається',
      zh: '包含对方名称',
      ar: 'يذكر الطرف المقابل',
      pl: 'Zawiera kontrahenta',
      it: 'Cita la controparte',
      sk: 'Obsahuje protistranu',
      ja: '相手先名を含む',
      ko: '거래처 이름 포함',
      hi: 'पक्ष का नाम शामिल',
      nl: 'Noemt de tegenpartij',
      sv: 'Nämner motparten',
      vi: 'Có tên đối tác',
      id: 'Menyebut pihak lawan',
    }),
    wallet: t({
      ru: 'Кошелёк',
      en: 'Wallet',
      kk: 'Әмиян',
      de: 'Wallet',
      fr: 'Portefeuille',
      es: 'Billetera',
      pt: 'Carteira',
      tr: 'Cüzdan',
      uk: 'Гаманець',
      zh: '钱包',
      ar: 'المحفظة',
      pl: 'Portfel',
      it: 'Portafoglio',
      sk: 'Peňaženka',
      ja: 'ウォレット',
      ko: '지갑',
      hi: 'वॉलेट',
      nl: 'Portemonnee',
      sv: 'Plånbok',
      vi: 'Ví',
      id: 'Dompet',
    }),
    noWallets: t({
      ru: 'Нет кошелька в валюте {currency}',
      en: 'No wallet in {currency}',
      kk: '{currency} валютасында әмиян жоқ',
      de: 'Keine Wallet in {currency}',
      fr: 'Aucun portefeuille en {currency}',
      es: 'No hay billetera en {currency}',
      pt: 'Nenhuma carteira em {currency}',
      tr: '{currency} cinsinden cüzdan yok',
      uk: 'Немає гаманця у валюті {currency}',
      zh: '没有 {currency} 钱包',
      ar: 'لا توجد محفظة بعملة {currency}',
      pl: 'Brak portfela w {currency}',
      it: 'Nessun portafoglio in {currency}',
      sk: 'Žiadna peňaženka v {currency}',
      ja: '{currency} のウォレットがありません',
      ko: '{currency} 지갑이 없습니다',
      hi: '{currency} में कोई वॉलेट नहीं',
      nl: 'Geen portemonnee in {currency}',
      sv: 'Ingen plånbok i {currency}',
      vi: 'Không có ví bằng {currency}',
      id: 'Tidak ada dompet dalam {currency}',
    }),
    paidOn: t({
      ru: 'Дата оплаты',
      en: 'Paid on',
      kk: 'Төлем күні',
      de: 'Bezahlt am',
      fr: 'Payé le',
      es: 'Pagado el',
      pt: 'Pago em',
      tr: 'Ödeme tarihi',
      uk: 'Дата оплати',
      zh: '付款日期',
      ar: 'تاريخ الدفع',
      pl: 'Data zapłaty',
      it: 'Pagato il',
      sk: 'Zaplatené dňa',
      ja: '支払日',
      ko: '지급일',
      hi: 'भुगतान तिथि',
      nl: 'Betaald op',
      sv: 'Betald den',
      vi: 'Ngày thanh toán',
      id: 'Dibayar pada',
    }),
    category: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '类别',
      ar: 'الفئة',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategória',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
    }),
    noCategory: t({
      ru: 'Без категории',
      en: 'No category',
      kk: 'Санатсыз',
      de: 'Ohne Kategorie',
      fr: 'Sans catégorie',
      es: 'Sin categoría',
      pt: 'Sem categoria',
      tr: 'Kategorisiz',
      uk: 'Без категорії',
      zh: '无类别',
      ar: 'بدون فئة',
      pl: 'Bez kategorii',
      it: 'Nessuna categoria',
      sk: 'Bez kategórie',
      ja: 'カテゴリなし',
      ko: '카테고리 없음',
      hi: 'कोई श्रेणी नहीं',
      nl: 'Geen categorie',
      sv: 'Ingen kategori',
      vi: 'Không có danh mục',
      id: 'Tanpa kategori',
    }),
    cashHint: t({
      ru: 'В кошельке появится новая транзакция, и она попадёт в учёт. Если потом снять отметку, транзакция останется.',
      en: 'A new transaction is recorded in the wallet and reaches the books. Marking the bill unpaid later keeps that transaction.',
      kk: 'Әмиянда жаңа транзакция пайда болып, есепке түседі. Кейін белгіні алып тастасаңыз, транзакция қалады.',
      de: 'In der Wallet wird eine neue Transaktion erfasst und verbucht. Wird die Markierung später entfernt, bleibt sie bestehen.',
      fr: 'Une nouvelle opération est enregistrée dans le portefeuille et comptabilisée. Si vous retirez la marque plus tard, elle reste.',
      es: 'Se registra un nuevo movimiento en la billetera y se contabiliza. Si luego desmarca la factura, el movimiento se mantiene.',
      pt: 'Uma nova transação é registada na carteira e contabilizada. Se depois desmarcar a fatura, a transação permanece.',
      tr: 'Cüzdana yeni bir işlem kaydedilir ve muhasebeye geçer. İşareti sonra kaldırırsanız işlem kalır.',
      uk: 'У гаманці з’явиться нова транзакція, і вона потрапить до обліку. Якщо потім зняти позначку, транзакція залишиться.',
      zh: '将在钱包中记录一笔新交易并入账。之后取消标记，该交易仍会保留。',
      ar: 'ستُسجَّل معاملة جديدة في المحفظة وتدخل الدفاتر. إذا ألغيت العلامة لاحقًا تبقى المعاملة.',
      pl: 'W portfelu zostanie zapisana nowa transakcja i trafi do ksiąg. Jeśli później cofniesz oznaczenie, transakcja zostanie.',
      it: 'Nel portafoglio viene registrato un nuovo movimento, che entra in contabilità. Se in seguito togli il segno, il movimento resta.',
      sk: 'V peňaženke sa zaznamená nový pohyb a zaúčtuje sa. Ak neskôr označenie zrušíte, pohyb zostane.',
      ja: 'ウォレットに新しい取引が記録され、帳簿に反映されます。後でマークを外しても取引は残ります。',
      ko: '지갑에 새 거래가 기록되어 장부에 반영됩니다. 나중에 표시를 해제해도 거래는 남습니다.',
      hi: 'वॉलेट में नया लेनदेन दर्ज होगा और खातों में जाएगा। बाद में चिह्न हटाने पर भी लेनदेन रहेगा।',
      nl: 'Er wordt een nieuwe transactie in de portemonnee geboekt. Haalt u de markering later weg, dan blijft die transactie staan.',
      sv: 'En ny transaktion registreras i plånboken och bokförs. Tar du bort markeringen senare finns transaktionen kvar.',
      vi: 'Một giao dịch mới được ghi vào ví và vào sổ sách. Nếu sau đó bỏ đánh dấu, giao dịch vẫn giữ nguyên.',
      id: 'Transaksi baru dicatat di dompet dan masuk pembukuan. Jika tanda dilepas nanti, transaksi tetap ada.',
    }),
    plainHint: t({
      ru: 'Изменится только статус: в учёте оплата не появится.',
      en: 'Only the status changes: the payment does not reach the books.',
      kk: 'Тек мәртебе өзгереді: төлем есепке түспейді.',
      de: 'Nur der Status ändert sich: Die Zahlung wird nicht verbucht.',
      fr: 'Seul le statut change : le paiement n’est pas comptabilisé.',
      es: 'Solo cambia el estado: el pago no se contabiliza.',
      pt: 'Só o estado muda: o pagamento não é contabilizado.',
      tr: 'Yalnızca durum değişir: ödeme muhasebeye geçmez.',
      uk: 'Зміниться лише статус: в обліку оплата не з’явиться.',
      zh: '仅更改状态：付款不会入账。',
      ar: 'تتغير الحالة فقط: لا تدخل الدفعة الدفاتر.',
      pl: 'Zmieni się tylko status: płatność nie trafi do ksiąg.',
      it: 'Cambia solo lo stato: il pagamento non entra in contabilità.',
      sk: 'Zmení sa iba stav: platba sa nezaúčtuje.',
      ja: 'ステータスのみ変わります。支払は帳簿に反映されません。',
      ko: '상태만 바뀌며 지급은 장부에 반영되지 않습니다.',
      hi: 'केवल स्थिति बदलेगी: भुगतान खातों में नहीं जाएगा।',
      nl: 'Alleen de status verandert: de betaling wordt niet geboekt.',
      sv: 'Bara statusen ändras: betalningen bokförs inte.',
      vi: 'Chỉ trạng thái thay đổi: khoản thanh toán không vào sổ sách.',
      id: 'Hanya status yang berubah: pembayaran tidak masuk pembukuan.',
    }),
    confirm: t({
      ru: 'Отметить',
      en: 'Confirm',
      kk: 'Белгілеу',
      de: 'Bestätigen',
      fr: 'Confirmer',
      es: 'Confirmar',
      pt: 'Confirmar',
      tr: 'Onayla',
      uk: 'Позначити',
      zh: '确认',
      ar: 'تأكيد',
      pl: 'Potwierdź',
      it: 'Conferma',
      sk: 'Potvrdiť',
      ja: '確定',
      ko: '확인',
      hi: 'पुष्टि करें',
      nl: 'Bevestigen',
      sv: 'Bekräfta',
      vi: 'Xác nhận',
      id: 'Konfirmasi',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Болдырмау',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      ar: 'إلغاء',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
    }),
    loading: t({
      ru: 'Загрузка…',
      en: 'Loading…',
      kk: 'Жүктелуде…',
      de: 'Wird geladen…',
      fr: 'Chargement…',
      es: 'Cargando…',
      pt: 'A carregar…',
      tr: 'Yükleniyor…',
      uk: 'Завантаження…',
      zh: '加载中…',
      ar: 'جارٍ التحميل…',
      pl: 'Ładowanie…',
      it: 'Caricamento…',
      sk: 'Načítava sa…',
      ja: '読み込み中…',
      ko: '불러오는 중…',
      hi: 'लोड हो रहा है…',
      nl: 'Laden…',
      sv: 'Laddar…',
      vi: 'Đang tải…',
      id: 'Memuat…',
    }),
  },
} satisfies Dictionary;

export default content;
