import { type DeclarationContent, t } from 'intlayer';

/** Invoicing settings: the number prefix and the reminder schedule. */
export default {
  key: 'invoiceSettings',
  content: {
    paymentTerms: t({
      ru: 'Срок оплаты по умолчанию, дней',
      en: 'Default payment terms, days',
      kk: 'Әдепкі төлем мерзімі, күн',
      de: 'Standard-Zahlungsziel, Tage',
      fr: 'Délai de paiement par défaut, jours',
      es: 'Plazo de pago por defecto, días',
      pt: 'Prazo de pagamento padrão, dias',
      tr: 'Varsayılan ödeme vadesi, gün',
      uk: 'Строк оплати за замовчуванням, днів',
      zh: '默认付款期限（天）',
      pl: 'Domyślny termin płatności, dni',
      it: 'Termini di pagamento predefiniti, giorni',
      sk: 'Predvolená splatnosť, dni',
      ja: '既定の支払期限（日）',
      ko: '기본 결제 기한(일)',
      hi: 'डिफ़ॉल्ट भुगतान अवधि, दिन',
      nl: 'Standaard betaaltermijn, dagen',
      sv: 'Standardbetalningsvillkor, dagar',
      vi: 'Hạn thanh toán mặc định, ngày',
      id: 'Jangka waktu pembayaran default, hari',
      da: 'Standardbetalingsfrist, dage',
      nb: 'Standard betalingsfrist, dager',
      nn: 'Standard betalingsfrist, dagar',
      fi: 'Oletusmaksuaika, päivää',
      is: 'Sjálfgefinn greiðslufrestur, dagar',
      fo: 'Standard rindingarfreist, dagar',
      cs: 'Výchozí platební podmínky, dny',
      bg: 'Срок за плащане по подразбиране, дни',
      hr: 'Zadani rok plaćanja, dana',
      sr: 'Подразумевани рок плаћања, дана',
      sl: 'Privzeti rok plačila, dni',
      mk: 'Стандарден рок за плаќање, дена',
      be: 'Прадвызначаны тэрмін аплаты, дзён',
      bs: 'Podrazumijevani rok plaćanja, dana',
      hsb: 'Standardny płaćenski termin, dny',
    }),
    lateFee: t({
      ru: 'Пеня за просрочку, %',
      en: 'Late fee, %',
      kk: 'Мерзімі өткені үшін өсімпұл, %',
      de: 'Verzugsgebühr, %',
      fr: 'Pénalité de retard, %',
      es: 'Recargo por demora, %',
      pt: 'Juros de mora, %',
      tr: 'Gecikme bedeli, %',
      uk: 'Пеня за прострочення, %',
      zh: '逾期费用（%）',
      pl: 'Odsetki za zwłokę, %',
      it: 'Penale di ritardo, %',
      sk: 'Penále z omeškania, %',
      ja: '遅延損害金（%）',
      ko: '연체료(%)',
      hi: 'विलंब शुल्क, %',
      nl: 'Vertragingsrente, %',
      sv: 'Dröjsmålsavgift, %',
      vi: 'Phí trả chậm, %',
      id: 'Denda keterlambatan, %',
      da: 'Morarente, %',
      nb: 'Forsinkelsesrente, %',
      nn: 'Forseinkingsrente, %',
      fi: 'Viivästyskorko, %',
      is: 'Vanskilavextir, %',
      fo: 'Seinkanarrenta, %',
      cs: 'Úrok z prodlení, %',
      bg: 'Лихва за забава, %',
      hr: 'Zatezna kamata, %',
      sr: 'Затезна камата, %',
      sl: 'Zamudne obresti, %',
      mk: 'Затезна камата, %',
      be: 'Пеня за пратэрміноўку, %',
      bs: 'Zatezna kamata, %',
      hsb: 'Zapozdźenske procenty, %',
    }),
    clientPaymentTerms: t({
      ru: 'Срок оплаты, дней',
      en: 'Payment terms, days',
      kk: 'Төлем мерзімі, күн',
      de: 'Zahlungsziel, Tage',
      fr: 'Délai de paiement, jours',
      es: 'Plazo de pago, días',
      pt: 'Prazo de pagamento, dias',
      tr: 'Ödeme vadesi, gün',
      uk: 'Строк оплати, днів',
      zh: '付款期限（天）',
      pl: 'Termin płatności, dni',
      it: 'Termini di pagamento, giorni',
      sk: 'Splatnosť, dni',
      ja: '支払期限（日）',
      ko: '결제 기한(일)',
      hi: 'भुगतान अवधि, दिन',
      nl: 'Betaaltermijn, dagen',
      sv: 'Betalningsvillkor, dagar',
      vi: 'Hạn thanh toán, ngày',
      id: 'Jangka waktu pembayaran, hari',
      da: 'Betalingsfrist, dage',
      nb: 'Betalingsfrist, dager',
      nn: 'Betalingsfrist, dagar',
      fi: 'Maksuaika, päivää',
      is: 'Greiðslufrestur, dagar',
      fo: 'Rindingarfreist, dagar',
      cs: 'Platební podmínky, dny',
      bg: 'Срок за плащане, дни',
      hr: 'Rok plaćanja, dana',
      sr: 'Рок плаћања, дана',
      sl: 'Rok plačila, dni',
      mk: 'Рок за плаќање, дена',
      be: 'Тэрмін аплаты, дзён',
      bs: 'Rok plaćanja, dana',
      hsb: 'Płaćenski termin, dny',
    }),
    title: t({
      ru: 'Счета: нумерация и напоминания',
      en: 'Invoices: numbering and reminders',
      kk: 'Шоттар: нөмірлеу және еске салу',
      de: 'Rechnungen: Nummerierung und Erinnerungen',
      fr: 'Factures : numérotation et rappels',
      es: 'Facturas: numeración y recordatorios',
      pt: 'Faturas: numeração e lembretes',
      tr: 'Faturalar: numaralandırma ve hatırlatmalar',
      uk: 'Рахунки: нумерація та нагадування',
      zh: '发票：编号与提醒',
      pl: 'Faktury: numeracja i przypomnienia',
      it: 'Fatture: numerazione e promemoria',
      sk: 'Faktúry: číslovanie a pripomienky',
      ja: '請求書：番号とリマインダー',
      ko: '청구서: 번호와 알림',
      hi: 'इनवॉइस: नंबरिंग और स्मरण',
      nl: 'Facturen: nummering en herinneringen',
      sv: 'Fakturor: numrering och påminnelser',
      vi: 'Hóa đơn: số và nhắc nhở',
      id: 'Faktur: penomoran dan pengingat',
      da: 'Fakturaer: nummerering og påmindelser',
      nb: 'Fakturaer: nummerering og påminnelser',
      nn: 'Fakturaer: nummerering og påminningar',
      fi: 'Laskut: numerointi ja muistutukset',
      is: 'Reikningar: númering og áminningar',
      fo: 'Fakturar: talmerking og áminningar',
      cs: 'Faktury: číslování a upomínky',
      bg: 'Фактури: номерация и напомняния',
      hr: 'Fakture: numeriranje i podsjetnici',
      sr: 'Фактуре: нумерисање и подсетници',
      sl: 'Računi: številčenje in opomniki',
      mk: 'Фактури: нумерирање и потсетници',
      be: 'Рахункі: нумарацыя і напаміны',
      bs: 'Fakture: numerisanje i podsjetnici',
      hsb: 'Faktury: čisłowanje a dopomnjenja',
    }),
    description: t({
      ru: 'Префикс номера и напоминания клиентам о неоплаченных счетах. Напоминания выключены, пока вы их не включите.',
      en: 'The number prefix, and reminders to clients about unpaid invoices. Reminders stay off until you turn them on.',
      kk: 'Нөмір префиксі және клиенттерге төленбеген шоттар туралы еске салу. Еске салу өзіңіз қоспағанша өшірулі.',
      de: 'Das Nummernpräfix und Erinnerungen an Kunden über offene Rechnungen. Erinnerungen bleiben aus, bis Sie sie einschalten.',
      fr: 'Le préfixe des numéros et les rappels aux clients pour les factures impayées. Les rappels restent désactivés jusqu’à ce que vous les activiez.',
      es: 'El prefijo del número y los recordatorios a clientes sobre facturas impagadas. Los recordatorios siguen desactivados hasta que los activas.',
      pt: 'O prefixo do número e os lembretes aos clientes sobre faturas não pagas. Os lembretes ficam desligados até os ligar.',
      tr: 'Numara ön eki ve ödenmemiş faturalar için müşteri hatırlatmaları. Siz açana kadar hatırlatmalar kapalı kalır.',
      uk: 'Префікс номера та нагадування клієнтам про неоплачені рахунки. Нагадування вимкнені, доки ви їх не ввімкнете.',
      zh: '编号前缀，以及对未付发票的客户提醒。提醒默认关闭，直到您开启。',
      pl: 'Prefiks numeru i przypomnienia dla klientów o nieopłaconych fakturach. Przypomnienia są wyłączone, dopóki ich nie włączysz.',
      it: 'Il prefisso del numero e i promemoria ai clienti sulle fatture non pagate. I promemoria restano spenti finché non li attivi.',
      sk: 'Predvoľba čísla a pripomienky zákazníkom o nezaplatených faktúrach. Pripomienky sú vypnuté, kým ich nezapnete.',
      ja: '番号の接頭辞と、未払い請求書についての顧客へのリマインダー。リマインダーは有効にするまで送信されません。',
      ko: '번호 접두사와 미결제 청구서에 대한 고객 알림. 알림은 켜기 전까지 보내지 않습니다.',
      hi: 'नंबर उपसर्ग और अनुपयुक्त इनवॉइस के बारे में ग्राहकों को स्मरण। जब तक आप चालू न करें, स्मरण बंद रहते हैं।',
      nl: 'Het nummervoorvoegsel en herinneringen aan klanten over onbetaalde facturen. Herinneringen blijven uit tot je ze aanzet.',
      sv: 'Nummerprefixet och påminnelser till kunder om obetalda fakturor. Påminnelser är avstängda tills du slår på dem.',
      vi: 'Tiền tố số và nhắc nhở khách hàng về hóa đơn chưa thanh toán. Nhắc nhở tắt cho đến khi bạn bật.',
      id: 'Awalan nomor dan pengingat ke klien tentang faktur belum dibayar. Pengingat nonaktif sampai Anda menyalakannya.',
      da: 'Nummerpræfikset og påmindelser til kunder om ubetalte fakturaer. Påmindelser er slået fra, indtil du slår dem til.',
      nb: 'Nummerprefikset og påminnelser til kunder om ubetalte fakturaer. Påminnelser er av til du slår dem på.',
      nn: 'Nummerprefikset og påminningar til kundar om ubetalte fakturaer. Påminningar er av til du slår dei på.',
      fi: 'Numeron etuliite ja muistutukset asiakkaille maksamattomista laskuista. Muistutukset ovat pois päältä, kunnes otat ne käyttöön.',
      is: 'Forskeyti númersins og áminningar til viðskiptavina um ógreidda reikninga. Áminningar eru óvirkar þar til þú kveikir á þeim.',
      fo: 'Talforskeytið og áminningar til kundar um ógoldnar fakturar. Áminningar eru avtiknar, til tú setir tær á.',
      cs: 'Předčíslí a upomínky klientům na nezaplacené faktury. Upomínky jsou vypnuté, dokud je nezapnete.',
      bg: 'Префиксът на номера и напомняния до клиентите за неплатени фактури. Напомнянията са изключени, докато не ги включите.',
      hr: 'Predbroj i podsjetnici klijentima na neplaćene fakture. Podsjetnici su isključeni dok ih ne uključite.',
      sr: 'Предброј и подсетници клијентима на неплаћене фактуре. Подсетници су искључени док их не укључите.',
      sl: 'Predpona številke in opomniki strankam na neplačane račune. Opomniki so izklopljeni, dokler jih ne vklopite.',
      mk: 'Префиксот на бројот и потсетници до клиентите за неплатени фактури. Потсетниците се исклучени додека не ги вклучите.',
      be: 'Прэфікс нумара і напаміны кліентам пра неаплачаныя рахункі. Напаміны выключаны, пакуль вы іх не ўключыце.',
      bs: 'Predbroj i podsjetnici klijentima na neplaćene fakture. Podsjetnici su isključeni dok ih ne uključite.',
      hsb: 'Prefiks čisła a dopomnjenja klientam na njezapłaćene faktury. Dopomnjenja su wupinjene, doniž je njezapinjeće.',
    }),
    prefix: t({
      ru: 'Префикс номера',
      en: 'Number prefix',
      kk: 'Нөмір префиксі',
      de: 'Nummernpräfix',
      fr: 'Préfixe du numéro',
      es: 'Prefijo del número',
      pt: 'Prefixo do número',
      tr: 'Numara ön eki',
      uk: 'Префікс номера',
      zh: '编号前缀',
      pl: 'Prefiks numeru',
      it: 'Prefisso del numero',
      sk: 'Predvoľba čísla',
      ja: '番号の接頭辞',
      ko: '번호 접두사',
      hi: 'नंबर उपसर्ग',
      nl: 'Nummervoorvoegsel',
      sv: 'Nummerprefix',
      vi: 'Tiền tố số',
      id: 'Awalan nomor',
      da: 'Nummerpræfiks',
      nb: 'Nummerprefiks',
      nn: 'Nummerprefiks',
      fi: 'Numeron etuliite',
      is: 'Forskeyti númers',
      fo: 'Talforskeyti',
      cs: 'Předčíslí',
      bg: 'Префикс на номера',
      hr: 'Predbroj',
      sr: 'Предброј',
      sl: 'Predpona številke',
      mk: 'Префикс на бројот',
      be: 'Прэфікс нумара',
      bs: 'Predbroj',
      hsb: 'Prefiks čisła',
    }),
    reminders: t({
      ru: 'Напоминать клиентам',
      en: 'Remind clients',
      kk: 'Клиенттерге еске салу',
      de: 'Kunden erinnern',
      fr: 'Relancer les clients',
      es: 'Recordar a los clientes',
      pt: 'Lembrar os clientes',
      tr: 'Müşterilere hatırlat',
      uk: 'Нагадувати клієнтам',
      zh: '提醒客户',
      pl: 'Przypominaj klientom',
      it: 'Ricorda ai clienti',
      sk: 'Pripomínať zákazníkom',
      ja: '顧客にリマインドする',
      ko: '고객에게 알림 보내기',
      hi: 'ग्राहकों को स्मरण भेजें',
      nl: 'Klanten herinneren',
      sv: 'Påminn kunder',
      vi: 'Nhắc khách hàng',
      id: 'Ingatkan klien',
      da: 'Påmind kunder',
      nb: 'Påminn kunder',
      nn: 'Påminn kundar',
      fi: 'Muistuta asiakkaita',
      is: 'Minna viðskiptavini á',
      fo: 'Ámin kundar',
      cs: 'Upomínat klienty',
      bg: 'Напомняне на клиентите',
      hr: 'Podsjećaj klijente',
      sr: 'Подсећај клијенте',
      sl: 'Opominjaj stranke',
      mk: 'Потсетувај клиенти',
      be: 'Напамінаць кліентам',
      bs: 'Podsjećaj klijente',
      hsb: 'Klientow dopomnjeć',
    }),
    offsets: t({
      ru: 'Дни относительно срока',
      en: 'Days from the due date',
      kk: 'Мерзімге қатысты күндер',
      de: 'Tage zum Fälligkeitsdatum',
      fr: 'Jours par rapport à l’échéance',
      es: 'Días respecto al vencimiento',
      pt: 'Dias em relação ao vencimento',
      tr: 'Vadeye göre günler',
      uk: 'Дні відносно терміну',
      zh: '相对到期日的天数',
      pl: 'Dni względem terminu',
      it: 'Giorni rispetto alla scadenza',
      sk: 'Dni voči splatnosti',
      ja: '期限からの日数',
      ko: '기한 기준 일수',
      hi: 'नियत तिथि से दिन',
      nl: 'Dagen t.o.v. de vervaldatum',
      sv: 'Dagar från förfallodatum',
      vi: 'Số ngày so với hạn',
      id: 'Hari dari jatuh tempo',
      da: 'Dage fra forfaldsdatoen',
      nb: 'Dager fra forfallsdatoen',
      nn: 'Dagar frå forfallsdatoen',
      fi: 'Päiviä eräpäivästä',
      is: 'Dagar frá greiðsludegi',
      fo: 'Dagar frá gjaldsdeginum',
      cs: 'Dnů od data splatnosti',
      bg: 'Дни от крайния срок',
      hr: 'Dana od roka plaćanja',
      sr: 'Дана од рока плаћања',
      sl: 'Dni od roka plačila',
      mk: 'Дена од рокот на плаќање',
      be: 'Дзён ад тэрміну аплаты',
      bs: 'Dana od roka plaćanja',
      hsb: 'Dnjow wot płaćenskeho termina',
    }),
    offsetsHint: t({
      ru: 'Через запятую. Минус — до срока, плюс — после: −3, 0, 7, 14.',
      en: 'Comma separated. Negative is before the due date, positive after: −3, 0, 7, 14.',
      kk: 'Үтір арқылы. Минус — мерзімге дейін, плюс — кейін: −3, 0, 7, 14.',
      de: 'Durch Komma getrennt. Minus vor der Fälligkeit, Plus danach: −3, 0, 7, 14.',
      fr: 'Séparés par des virgules. Négatif avant l’échéance, positif après : −3, 0, 7, 14.',
      es: 'Separados por comas. Negativo antes del vencimiento, positivo después: −3, 0, 7, 14.',
      pt: 'Separados por vírgulas. Negativo antes do vencimento, positivo depois: −3, 0, 7, 14.',
      tr: 'Virgülle ayırın. Eksi vadeden önce, artı sonra: −3, 0, 7, 14.',
      uk: 'Через кому. Мінус — до терміну, плюс — після: −3, 0, 7, 14.',
      zh: '用逗号分隔。负数表示到期前，正数表示到期后：−3、0、7、14。',
      pl: 'Rozdzielone przecinkami. Minus przed terminem, plus po: −3, 0, 7, 14.',
      it: 'Separati da virgole. Negativo prima della scadenza, positivo dopo: −3, 0, 7, 14.',
      sk: 'Oddelené čiarkami. Mínus pred splatnosťou, plus po: −3, 0, 7, 14.',
      ja: 'カンマ区切り。マイナスは期限前、プラスは期限後：−3、0、7、14。',
      ko: '쉼표로 구분합니다. 음수는 기한 전, 양수는 기한 후: −3, 0, 7, 14.',
      hi: 'कॉमा से अलग करें। ऋण का अर्थ तिथि से पहले, धन का बाद: −3, 0, 7, 14।',
      nl: 'Door komma’s gescheiden. Negatief is voor de vervaldatum, positief erna: −3, 0, 7, 14.',
      sv: 'Kommaseparerade. Minus före förfallodatum, plus efter: −3, 0, 7, 14.',
      vi: 'Phân tách bằng dấu phẩy. Số âm là trước hạn, số dương là sau: −3, 0, 7, 14.',
      id: 'Dipisahkan koma. Negatif sebelum jatuh tempo, positif sesudahnya: −3, 0, 7, 14.',
      da: 'Adskilt med komma. Negativt er før forfaldsdatoen, positivt efter: −3, 0, 7, 14.',
      nb: 'Skilt med komma. Negativt er før forfallsdatoen, positivt etter: −3, 0, 7, 14.',
      nn: 'Skilde med komma. Negativt er før forfallsdatoen, positivt etter: −3, 0, 7, 14.',
      fi: 'Pilkulla erotettuna. Negatiivinen on ennen eräpäivää, positiivinen sen jälkeen: −3, 0, 7, 14.',
      is: 'Aðgreint með kommu. Neikvætt er fyrir greiðsludag, jákvætt eftir: −3, 0, 7, 14.',
      fo: 'Skilt við kommu. Negativt er fyri gjaldsdagin, positivt eftir: −3, 0, 7, 14.',
      cs: 'Oddělené čárkou. Záporné je před splatností, kladné po: −3, 0, 7, 14.',
      bg: 'Разделени със запетая. Отрицателно е преди крайния срок, положително след него: −3, 0, 7, 14.',
      hr: 'Odvojeno zarezom. Negativno je prije roka, pozitivno nakon: −3, 0, 7, 14.',
      sr: 'Раздвојено запетом. Негативно је пре рока, позитивно након: −3, 0, 7, 14.',
      sl: 'Ločeno z vejico. Negativno je pred rokom, pozitivno po njem: −3, 0, 7, 14.',
      mk: 'Одделено со запирка. Негативно е пред рокот, позитивно по него: −3, 0, 7, 14.',
      be: 'Раздзеленыя коскай. Адмоўнае — да тэрміну, дадатнае — пасля: −3, 0, 7, 14.',
      bs: 'Odvojeno zapetom. Negativno je prije roka, pozitivno nakon: −3, 0, 7, 14.',
      hsb: 'Z komu dźěleno. Negatiwne je do termina, pozitiwne po nim: −3, 0, 7, 14.',
    }),
    clientReminders: t({
      ru: 'Напоминать этому клиенту',
      en: 'Remind this client',
      kk: 'Бұл клиентке еске салу',
      de: 'Diesen Kunden erinnern',
      fr: 'Relancer ce client',
      es: 'Recordar a este cliente',
      pt: 'Lembrar este cliente',
      tr: 'Bu müşteriye hatırlat',
      uk: 'Нагадувати цьому клієнту',
      zh: '提醒该客户',
      pl: 'Przypominaj temu klientowi',
      it: 'Ricorda a questo cliente',
      sk: 'Pripomínať tomuto zákazníkovi',
      ja: 'この顧客にリマインドする',
      ko: '이 고객에게 알림 보내기',
      hi: 'इस ग्राहक को स्मरण भेजें',
      nl: 'Deze klant herinneren',
      sv: 'Påminn den här kunden',
      vi: 'Nhắc khách hàng này',
      id: 'Ingatkan klien ini',
      da: 'Påmind denne kunde',
      nb: 'Påminn denne kunden',
      nn: 'Påminn denne kunden',
      fi: 'Muistuta tätä asiakasta',
      is: 'Minna þennan viðskiptavin á',
      fo: 'Ámin henda kundan',
      cs: 'Upomínat tohoto klienta',
      bg: 'Напомняне на този клиент',
      hr: 'Podsjećaj ovog klijenta',
      sr: 'Подсећај овог клијента',
      sl: 'Opominjaj to stranko',
      mk: 'Потсетувај го овој клиент',
      be: 'Напамінаць гэтаму кліенту',
      bs: 'Podsjećaj ovog klijenta',
      hsb: 'Tutoho klienta dopomnjeć',
    }),
    viewed: t({
      ru: 'Клиент открыл счёт',
      en: 'The client opened it',
      kk: 'Клиент шотты ашты',
      de: 'Der Kunde hat sie geöffnet',
      fr: 'Le client l’a ouverte',
      es: 'El cliente la abrió',
      pt: 'O cliente abriu-a',
      tr: 'Müşteri açtı',
      uk: 'Кліент відкрив рахунок',
      zh: '客户已打开',
      pl: 'Klient ją otworzył',
      it: 'Il cliente l’ha aperta',
      sk: 'Zákazník ju otvoril',
      ja: '顧客が開封しました',
      ko: '고객이 열어봤습니다',
      hi: 'ग्राहक ने खोला',
      nl: 'De klant heeft hem geopend',
      sv: 'Kunden har öppnat den',
      vi: 'Khách hàng đã mở',
      id: 'Klien telah membukanya',
      da: 'Kunden har åbnet den',
      nb: 'Kunden har åpnet den',
      nn: 'Kunden har opna han',
      fi: 'Asiakas avasi sen',
      is: 'Viðskiptavinurinn opnaði hann',
      fo: 'Kundin hevur latið hana upp',
      cs: 'Klient ji otevřel',
      bg: 'Клиентът я отвори',
      hr: 'Klijent ju je otvorio',
      sr: 'Клијент ју је отворио',
      sl: 'Stranka ga je odprla',
      mk: 'Клиентот ја отвори',
      be: 'Кліент яго адкрыў',
      bs: 'Klijent ju je otvorio',
      hsb: 'Klient ju je wočinił',
    }),
    notViewed: t({
      ru: 'Клиент ещё не открывал счёт',
      en: 'The client has not opened it yet',
      kk: 'Клиент шотты әлі ашпаған',
      de: 'Der Kunde hat sie noch nicht geöffnet',
      fr: 'Le client ne l’a pas encore ouverte',
      es: 'El cliente aún no la ha abierto',
      pt: 'O cliente ainda não a abriu',
      tr: 'Müşteri henüz açmadı',
      uk: 'Кліент ще не відкривав рахунок',
      zh: '客户尚未打开',
      pl: 'Klient jeszcze jej nie otworzył',
      it: 'Il cliente non l’ha ancora aperta',
      sk: 'Zákazník ju ešte neotvoril',
      ja: '顧客はまだ開封していません',
      ko: '고객이 아직 열어보지 않았습니다',
      hi: 'ग्राहक ने अभी नहीं खोला',
      nl: 'De klant heeft hem nog niet geopend',
      sv: 'Kunden har inte öppnat den än',
      vi: 'Khách hàng chưa mở',
      id: 'Klien belum membukanya',
      da: 'Kunden har endnu ikke åbnet den',
      nb: 'Kunden har ikke åpnet den ennå',
      nn: 'Kunden har ikkje opna han enno',
      fi: 'Asiakas ei ole vielä avannut sitä',
      is: 'Viðskiptavinurinn hefur ekki opnað hann enn',
      fo: 'Kundin hevur enn ikki latið hana upp',
      cs: 'Klient ji ještě neotevřel',
      bg: 'Клиентът още не я е отворил',
      hr: 'Klijent ju još nije otvorio',
      sr: 'Клијент ју још није отворио',
      sl: 'Stranka ga še ni odprla',
      mk: 'Клиентот сè уште не ја отворил',
      be: 'Кліент яго пакуль не адкрыў',
      bs: 'Klijent ju još nije otvorio',
      hsb: 'Klient ju hišće njeje wočinił',
    }),
  },
} satisfies DeclarationContent;
