/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'receiptDocumentPage',
  content: {
    preparingPreview: t({
      ru: 'Готовим превью...',
      en: 'Preparing preview...',
      kk: 'Алдын ала қарау дайындалуда...',
      de: 'Vorschau wird vorbereitet...',
      fr: "Préparation de l'aperçu...",
      es: 'Preparando vista previa...',
      pt: 'Preparando pré-visualização...',
      tr: 'Önizleme hazırlanıyor...',
      uk: 'Готуємо попередній перегляд...',
      zh: '正在准备预览...',
      ar: 'جارٍ تجهيز المعاينة...',
      pl: 'Przygotowywanie podglądu...',
      it: 'Preparazione anteprima...',
      sk: 'Pripravuje sa náhľad...',
      ja: 'プレビューを準備中...',
      ko: '미리보기 준비 중...',
      hi: 'पूर्वावलोकन तैयार हो रहा है...',
      nl: 'Voorbeeld wordt voorbereid...',
      sv: 'Förbereder förhandsgranskning...',
      vi: 'Đang chuẩn bị bản xem trước...',
      id: 'Menyiapkan pratinjau...',
    }),
    previewUnavailable: t({
      ru: 'Превью недоступно',
      en: 'Preview unavailable',
      kk: 'Алдын ала қарау қолжетімсіз',
      de: 'Vorschau nicht verfügbar',
      fr: 'Aperçu indisponible',
      es: 'Vista previa no disponible',
      pt: 'Pré-visualização indisponível',
      tr: 'Önizleme kullanılamıyor',
      uk: 'Попередній перегляд недоступний',
      zh: '预览不可用',
      ar: 'المعاينة غير متاحة',
      pl: 'Podgląd niedostępny',
      it: 'Anteprima non disponibile',
      sk: 'Náhľad nie je k dispozícii',
      ja: 'プレビューを表示できません',
      ko: '미리보기를 사용할 수 없습니다',
      hi: 'पूर्वावलोकन उपलब्ध नहीं है',
      nl: 'Voorbeeld niet beschikbaar',
      sv: 'Förhandsgranskning inte tillgänglig',
      vi: 'Không có bản xem trước',
      id: 'Pratinjau tidak tersedia',
    }),
    loadFailed: t({
      ru: 'Не удалось загрузить чек',
      en: 'Failed to load receipt',
      kk: 'Чекті жүктеу мүмкін болмады',
      de: 'Beleg konnte nicht geladen werden',
      fr: 'Impossible de charger le reçu',
      es: 'No se pudo cargar el recibo',
      pt: 'Falha ao carregar o recibo',
      tr: 'Fiş yüklenemedi',
      uk: 'Не вдалося завантажити чек',
      zh: '无法加载收据',
      ar: 'تعذر تحميل الإيصال',
      pl: 'Nie udało się wczytać paragonu',
      it: 'Impossibile caricare la ricevuta',
      sk: 'Nepodarilo sa načítať doklad',
      ja: 'レシートを読み込めませんでした',
      ko: '영수증을 불러오지 못했습니다',
      hi: 'रसीद लोड नहीं हो सकी',
      nl: 'Bon kon niet worden geladen',
      sv: 'Det gick inte att läsa in kvittot',
      vi: 'Không thể tải hóa đơn',
      id: 'Gagal memuat struk',
    }),
    notFound: t({
      ru: 'Чек не найден',
      en: 'Receipt not found',
      kk: 'Чек табылмады',
      de: 'Beleg nicht gefunden',
      fr: 'Reçu introuvable',
      es: 'Recibo no encontrado',
      pt: 'Recibo não encontrado',
      tr: 'Fiş bulunamadı',
      uk: 'Чек не знайдено',
      zh: '未找到收据',
      ar: 'لم يتم العثور على الإيصال',
      pl: 'Nie znaleziono paragonu',
      it: 'Ricevuta non trovata',
      sk: 'Doklad sa nenašiel',
      ja: 'レシートが見つかりません',
      ko: '영수증을 찾을 수 없습니다',
      hi: 'रसीद नहीं मिली',
      nl: 'Bon niet gevonden',
      sv: 'Kvittot hittades inte',
      vi: 'Không tìm thấy hóa đơn',
      id: 'Struk tidak ditemukan',
    }),
    autosaveFailed: t({
      ru: 'Не удалось автоматически сохранить изменения чека.',
      en: 'Failed to autosave receipt changes.',
      kk: 'Чектегі өзгерістерді автоматты сақтау мүмкін болмады.',
      de: 'Änderungen am Beleg konnten nicht automatisch gespeichert werden.',
      fr: "Impossible d'enregistrer automatiquement les modifications du reçu.",
      es: 'No se pudieron guardar automáticamente los cambios del recibo.',
      pt: 'Falha ao salvar automaticamente as alterações do recibo.',
      tr: 'Fiş değişiklikleri otomatik kaydedilemedi.',
      uk: 'Не вдалося автоматично зберегти зміни чека.',
      zh: '无法自动保存收据更改。',
      ar: 'تعذر الحفظ التلقائي لتغييرات الإيصال.',
      pl: 'Nie udało się automatycznie zapisać zmian paragonu.',
      it: 'Impossibile salvare automaticamente le modifiche alla ricevuta.',
      sk: 'Zmeny dokladu sa nepodarilo automaticky uložiť.',
      ja: 'レシートの変更を自動保存できませんでした。',
      ko: '영수증 변경 사항을 자동 저장하지 못했습니다.',
      hi: 'रसीद के बदलाव अपने-आप सहेजे नहीं जा सके।',
      nl: 'Wijzigingen in de bon konden niet automatisch worden opgeslagen.',
      sv: 'Det gick inte att autospara ändringarna i kvittot.',
      vi: 'Không thể tự động lưu thay đổi của hóa đơn.',
      id: 'Gagal menyimpan otomatis perubahan struk.',
    }),
    approved: t({
      ru: 'Чек подтверждён.',
      en: 'Receipt approved.',
      kk: 'Чек расталды.',
      de: 'Beleg freigegeben.',
      fr: 'Reçu approuvé.',
      es: 'Recibo aprobado.',
      pt: 'Recibo aprovado.',
      tr: 'Fiş onaylandı.',
      uk: 'Чек підтверджено.',
      zh: '收据已批准。',
      ar: 'تمت الموافقة على الإيصال.',
      pl: 'Paragon zatwierdzony.',
      it: 'Ricevuta approvata.',
      sk: 'Doklad bol schválený.',
      ja: 'レシートを承認しました。',
      ko: '영수증이 승인되었습니다.',
      hi: 'रसीद स्वीकृत हो गई।',
      nl: 'Bon goedgekeurd.',
      sv: 'Kvittot har godkänts.',
      vi: 'Đã duyệt hóa đơn.',
      id: 'Struk disetujui.',
    }),
    approveFailed: t({
      ru: 'Не удалось подтвердить чек.',
      en: 'Failed to approve receipt.',
      kk: 'Чекті растау мүмкін болмады.',
      de: 'Beleg konnte nicht freigegeben werden.',
      fr: "Impossible d'approuver le reçu.",
      es: 'No se pudo aprobar el recibo.',
      pt: 'Falha ao aprovar o recibo.',
      tr: 'Fiş onaylanamadı.',
      uk: 'Не вдалося підтвердити чек.',
      zh: '无法批准收据。',
      ar: 'تعذرت الموافقة على الإيصال.',
      pl: 'Nie udało się zatwierdzić paragonu.',
      it: 'Impossibile approvare la ricevuta.',
      sk: 'Doklad sa nepodarilo schváliť.',
      ja: 'レシートを承認できませんでした。',
      ko: '영수증을 승인하지 못했습니다.',
      hi: 'रसीद स्वीकृत नहीं हो सकी।',
      nl: 'Bon kon niet worden goedgekeurd.',
      sv: 'Det gick inte att godkänna kvittot.',
      vi: 'Không thể duyệt hóa đơn.',
      id: 'Gagal menyetujui struk.',
    }),
    downloadFailed: t({
      ru: 'Не удалось скачать чек',
      en: 'Failed to download receipt',
      kk: 'Чекті жүктеп алу мүмкін болмады',
      de: 'Beleg konnte nicht heruntergeladen werden',
      fr: 'Impossible de télécharger le reçu',
      es: 'No se pudo descargar el recibo',
      pt: 'Falha ao baixar o recibo',
      tr: 'Fiş indirilemedi',
      uk: 'Не вдалося завантажити чек',
      zh: '无法下载收据',
      ar: 'تعذر تنزيل الإيصال',
      pl: 'Nie udało się pobrać paragonu',
      it: 'Impossibile scaricare la ricevuta',
      sk: 'Doklad sa nepodarilo stiahnuť',
      ja: 'レシートをダウンロードできませんでした',
      ko: '영수증을 다운로드하지 못했습니다',
      hi: 'रसीद डाउनलोड नहीं हो सकी',
      nl: 'Bon kon niet worden gedownload',
      sv: 'Det gick inte att ladda ned kvittot',
      vi: 'Không thể tải xuống hóa đơn',
      id: 'Gagal mengunduh struk',
    }),
    exportUnavailable: t({
      ru: 'Экспорт в таблицу пока недоступен для этого чека',
      en: 'Export to table is unavailable for this receipt yet',
      kk: 'Бұл чек үшін кестеге экспорттау әзірге қолжетімсіз',
      de: 'Export in eine Tabelle ist für diesen Beleg noch nicht verfügbar',
      fr: "L'export vers un tableau n'est pas encore disponible pour ce reçu",
      es: 'La exportación a tabla aún no está disponible para este recibo',
      pt: 'A exportação para tabela ainda não está disponível para este recibo',
      tr: 'Bu fiş için tabloya aktarma henüz kullanılamıyor',
      uk: 'Експорт до таблиці поки недоступний для цього чека',
      zh: '此收据暂不支持导出到表格',
      ar: 'التصدير إلى جدول غير متاح لهذا الإيصال بعد',
      pl: 'Eksport do tabeli nie jest jeszcze dostępny dla tego paragonu',
      it: "L'esportazione in tabella non è ancora disponibile per questa ricevuta",
      sk: 'Export do tabuľky zatiaľ nie je pre tento doklad dostupný',
      ja: 'このレシートはまだテーブルにエクスポートできません',
      ko: '이 영수증은 아직 표로 내보낼 수 없습니다',
      hi: 'इस रसीद के लिए तालिका में निर्यात अभी उपलब्ध नहीं है',
      nl: 'Exporteren naar tabel is nog niet beschikbaar voor deze bon',
      sv: 'Export till tabell är ännu inte tillgänglig för det här kvittot',
      vi: 'Chưa thể xuất hóa đơn này ra bảng',
      id: 'Ekspor ke tabel belum tersedia untuk struk ini',
    }),
    exportNoFields: t({
      ru: 'Пока нет распознанных полей чека для экспорта',
      en: 'There are no parsed receipt fields to export yet',
      kk: 'Экспорттау үшін чектің танылған өрістері әзірге жоқ',
      de: 'Es gibt noch keine erkannten Belegfelder zum Exportieren',
      fr: "Aucun champ de reçu analysé à exporter pour l'instant",
      es: 'Aún no hay campos del recibo reconocidos para exportar',
      pt: 'Ainda não há campos do recibo reconhecidos para exportar',
      tr: 'Henüz aktarılacak tanınmış fiş alanı yok',
      uk: 'Поки немає розпізнаних полів чека для експорту',
      zh: '暂无可导出的已识别收据字段',
      ar: 'لا توجد بعد حقول مستخرجة من الإيصال للتصدير',
      pl: 'Brak jeszcze rozpoznanych pól paragonu do eksportu',
      it: 'Non ci sono ancora campi della ricevuta riconosciuti da esportare',
      sk: 'Zatiaľ nie sú k dispozícii žiadne rozpoznané polia dokladu na export',
      ja: 'エクスポートできる読み取り済みの項目がまだありません',
      ko: '아직 내보낼 인식된 영수증 항목이 없습니다',
      hi: 'निर्यात के लिए अभी रसीद के कोई पहचाने गए फ़ील्ड नहीं हैं',
      nl: 'Er zijn nog geen herkende bonvelden om te exporteren',
      sv: 'Det finns ännu inga tolkade kvittofält att exportera',
      vi: 'Chưa có trường nào của hóa đơn được nhận diện để xuất',
      id: 'Belum ada kolom struk yang terbaca untuk diekspor',
    }),
    exportFailed: t({
      ru: 'Не удалось экспортировать в таблицу',
      en: 'Failed to export to table',
      kk: 'Кестеге экспорттау мүмкін болмады',
      de: 'Export in Tabelle fehlgeschlagen',
      fr: "Échec de l'exportation vers le tableau",
      es: 'Error al exportar a tabla',
      pt: 'Falha ao exportar para tabela',
      tr: 'Tabloya aktarma başarısız',
      uk: 'Не вдалося експортувати до таблиці',
      zh: '导出到表格失败',
      ar: 'فشل التصدير إلى جدول',
      pl: 'Nie udało się wyeksportować do tabeli',
      it: 'Impossibile esportare in tabella',
      sk: 'Export do tabuľky zlyhal',
      ja: 'テーブルへのエクスポートに失敗しました',
      ko: '표로 내보내기 실패',
      hi: 'तालिका में निर्यात करने में विफल',
      nl: 'Exporteren naar tabel mislukt',
      sv: 'Det gick inte att exportera till tabellen',
      vi: 'Không thể xuất ra bảng',
      id: 'Gagal mengekspor ke tabel',
    }),
    exportSuccess: t({
      ru: 'Таблица создана успешно',
      en: 'Table created successfully',
      kk: 'Кесте сәтті құрылды',
      de: 'Tabelle erfolgreich erstellt',
      fr: 'Tableau créé avec succès',
      es: 'Tabla creada correctamente',
      pt: 'Tabela criada com sucesso',
      tr: 'Tablo başarıyla oluşturuldu',
      uk: 'Таблицю успішно створено',
      zh: '表格创建成功',
      ar: 'تم إنشاء الجدول بنجاح',
      pl: 'Tabela została utworzona',
      it: 'Tabella creata con successo',
      sk: 'Tabuľka bola úspešne vytvorená',
      ja: 'テーブルを作成しました',
      ko: '표가 생성되었습니다',
      hi: 'तालिका सफलतापूर्वक बनाई गई',
      nl: 'Tabel succesvol aangemaakt',
      sv: 'Tabellen har skapats',
      vi: 'Tạo bảng thành công',
      id: 'Tabel berhasil dibuat',
    }),
    back: t({
      ru: 'Назад',
      en: 'Back',
      kk: 'Артқа',
      de: 'Zurück',
      fr: 'Retour',
      es: 'Volver',
      pt: 'Voltar',
      tr: 'Geri',
      uk: 'Назад',
      zh: '返回',
      ar: 'رجوع',
      pl: 'Wstecz',
      it: 'Indietro',
      sk: 'Späť',
      ja: '戻る',
      ko: '뒤로',
      hi: 'वापस',
      nl: 'Terug',
      sv: 'Tillbaka',
      vi: 'Quay lại',
      id: 'Kembali',
    }),
    eyebrow: t({
      ru: 'Детали чека',
      en: 'Receipt details',
      kk: 'Чек мәліметтері',
      de: 'Belegdetails',
      fr: 'Détails du reçu',
      es: 'Detalles del recibo',
      pt: 'Detalhes do recibo',
      tr: 'Fiş ayrıntıları',
      uk: 'Деталі чека',
      zh: '收据详情',
      ar: 'تفاصيل الإيصال',
      pl: 'Szczegóły paragonu',
      it: 'Dettagli ricevuta',
      sk: 'Podrobnosti dokladu',
      ja: 'レシートの詳細',
      ko: '영수증 세부정보',
      hi: 'रसीद का विवरण',
      nl: 'Bongegevens',
      sv: 'Kvittouppgifter',
      vi: 'Chi tiết hóa đơn',
      id: 'Detail struk',
    }),
    displayTitle: t({
      ru: 'Чек {vendor} — {date}',
      en: '{vendor} Receipt — {date}',
      kk: '{vendor} чегі — {date}',
      de: 'Beleg {vendor} — {date}',
      fr: 'Reçu {vendor} — {date}',
      es: 'Recibo de {vendor} — {date}',
      pt: 'Recibo {vendor} — {date}',
      tr: '{vendor} fişi — {date}',
      uk: 'Чек {vendor} — {date}',
      zh: '{vendor} 收据 — {date}',
      ar: 'إيصال {vendor} — {date}',
      pl: 'Paragon {vendor} — {date}',
      it: 'Ricevuta {vendor} — {date}',
      sk: 'Doklad {vendor} — {date}',
      ja: '{vendor} のレシート — {date}',
      ko: '{vendor} 영수증 — {date}',
      hi: '{vendor} रसीद — {date}',
      nl: 'Bon {vendor} — {date}',
      sv: 'Kvitto {vendor} — {date}',
      vi: 'Hóa đơn {vendor} — {date}',
      id: 'Struk {vendor} — {date}',
    }),
    download: t({
      ru: 'Скачать',
      en: 'Download',
      kk: 'Жүктеп алу',
      de: 'Herunterladen',
      fr: 'Télécharger',
      es: 'Descargar',
      pt: 'Baixar',
      tr: 'İndir',
      uk: 'Завантажити',
      zh: '下载',
      ar: 'تنزيل',
      pl: 'Pobierz',
      it: 'Scarica',
      sk: 'Stiahnuť',
      ja: 'ダウンロード',
      ko: '다운로드',
      hi: 'डाउनलोड करें',
      nl: 'Downloaden',
      sv: 'Ladda ned',
      vi: 'Tải xuống',
      id: 'Unduh',
    }),
    exportToTable: t({
      ru: 'Экспорт в таблицу',
      en: 'Export to table',
      kk: 'Кестеге экспорттау',
      de: 'In Tabelle exportieren',
      fr: 'Exporter vers un tableau',
      es: 'Exportar a tabla',
      pt: 'Exportar para tabela',
      tr: 'Tabloya aktar',
      uk: 'Експорт до таблиці',
      zh: '导出到表格',
      ar: 'تصدير إلى جدول',
      pl: 'Eksportuj do tabeli',
      it: 'Esporta in tabella',
      sk: 'Exportovať do tabuľky',
      ja: 'テーブルにエクスポート',
      ko: '표로 내보내기',
      hi: 'तालिका में निर्यात करें',
      nl: 'Exporteren naar tabel',
      sv: 'Exportera till tabell',
      vi: 'Xuất ra bảng',
      id: 'Ekspor ke tabel',
    }),
    approve: t({
      ru: 'Подтвердить чек',
      en: 'Approve receipt',
      kk: 'Чекті растау',
      de: 'Beleg freigeben',
      fr: 'Approuver le reçu',
      es: 'Aprobar recibo',
      pt: 'Aprovar recibo',
      tr: 'Fişi onayla',
      uk: 'Підтвердити чек',
      zh: '批准收据',
      ar: 'الموافقة على الإيصال',
      pl: 'Zatwierdź paragon',
      it: 'Approva ricevuta',
      sk: 'Schváliť doklad',
      ja: 'レシートを承認',
      ko: '영수증 승인',
      hi: 'रसीद स्वीकृत करें',
      nl: 'Bon goedkeuren',
      sv: 'Godkänn kvitto',
      vi: 'Duyệt hóa đơn',
      id: 'Setujui struk',
    }),
    originalDocument: t({
      ru: 'Исходный документ',
      en: 'Original document',
      kk: 'Бастапқы құжат',
      de: 'Originaldokument',
      fr: 'Document original',
      es: 'Documento original',
      pt: 'Documento original',
      tr: 'Orijinal belge',
      uk: 'Оригінальний документ',
      zh: '原始文件',
      ar: 'المستند الأصلي',
      pl: 'Oryginalny dokument',
      it: 'Documento originale',
      sk: 'Pôvodný dokument',
      ja: '元のドキュメント',
      ko: '원본 문서',
      hi: 'मूल दस्तावेज़',
      nl: 'Origineel document',
      sv: 'Originaldokument',
      vi: 'Tài liệu gốc',
      id: 'Dokumen asli',
    }),
    parsedFields: t({
      ru: 'Распознанные поля',
      en: 'Parsed fields',
      kk: 'Танылған өрістер',
      de: 'Erkannte Felder',
      fr: 'Champs extraits',
      es: 'Campos reconocidos',
      pt: 'Campos reconhecidos',
      tr: 'Tanınan alanlar',
      uk: 'Розпізнані поля',
      zh: '识别的字段',
      ar: 'الحقول المستخرجة',
      pl: 'Rozpoznane pola',
      it: 'Campi riconosciuti',
      sk: 'Rozpoznané polia',
      ja: '読み取った項目',
      ko: '인식된 항목',
      hi: 'पहचाने गए फ़ील्ड',
      nl: 'Herkende velden',
      sv: 'Tolkade fält',
      vi: 'Các trường đã nhận diện',
      id: 'Kolom yang terbaca',
    }),
    parsedFieldsHint: t({
      ru: 'Проверьте и исправьте распознанные данные чека перед подтверждением.',
      en: 'Review and correct the extracted receipt data before approval.',
      kk: 'Растау алдында чектің танылған деректерін тексеріп, түзетіңіз.',
      de: 'Prüfen und korrigieren Sie die erkannten Belegdaten vor der Freigabe.',
      fr: "Vérifiez et corrigez les données extraites du reçu avant l'approbation.",
      es: 'Revise y corrija los datos extraídos del recibo antes de aprobarlo.',
      pt: 'Revise e corrija os dados extraídos do recibo antes da aprovação.',
      tr: 'Onaylamadan önce fişten çıkarılan verileri kontrol edip düzeltin.',
      uk: 'Перевірте й виправте розпізнані дані чека перед підтвердженням.',
      zh: '批准前请检查并更正提取的收据数据。',
      ar: 'راجع بيانات الإيصال المستخرجة وصححها قبل الموافقة.',
      pl: 'Sprawdź i popraw odczytane dane paragonu przed zatwierdzeniem.',
      it: "Controlla e correggi i dati estratti dalla ricevuta prima dell'approvazione.",
      sk: 'Pred schválením skontrolujte a opravte rozpoznané údaje dokladu.',
      ja: '承認する前に、読み取ったレシートのデータを確認・修正してください。',
      ko: '승인하기 전에 추출된 영수증 데이터를 검토하고 수정하세요.',
      hi: 'स्वीकृति से पहले रसीद से निकाले गए डेटा की जाँच करें और सुधारें।',
      nl: 'Controleer en corrigeer de uitgelezen bongegevens vóór goedkeuring.',
      sv: 'Granska och korrigera de tolkade kvittouppgifterna innan du godkänner.',
      vi: 'Kiểm tra và chỉnh sửa dữ liệu trích xuất từ hóa đơn trước khi duyệt.',
      id: 'Tinjau dan perbaiki data struk yang terbaca sebelum disetujui.',
    }),
    confirmExportTitle: t({
      ru: 'Подтвердите экспорт',
      en: 'Confirm export',
      kk: 'Экспортты растау',
      de: 'Export bestätigen',
      fr: "Confirmer l'exportation",
      es: 'Confirmar exportación',
      pt: 'Confirmar exportação',
      tr: 'Dışa aktarmayı onayla',
      uk: 'Підтвердіть експорт',
      zh: '确认导出',
      ar: 'تأكيد التصدير',
      pl: 'Potwierdź eksport',
      it: 'Conferma esportazione',
      sk: 'Potvrdiť export',
      ja: 'エクスポートを確認',
      ko: '내보내기 확인',
      hi: 'निर्यात की पुष्टि करें',
      nl: 'Export bevestigen',
      sv: 'Bekräfta export',
      vi: 'Xác nhận xuất',
      id: 'Konfirmasi ekspor',
    }),
    confirmExportBody: t({
      ru: 'Вы уверены, что хотите экспортировать эту выписку в пользовательскую таблицу?',
      en: 'Are you sure you want to export this statement to a custom table?',
      kk: 'Бұл үзіндіні пайдаланушы кестесіне экспорттағыңыз келетініне сенімдісіз бе?',
      de: 'Möchten Sie diesen Auszug wirklich in eine benutzerdefinierte Tabelle exportieren?',
      fr: 'Voulez-vous vraiment exporter ce relevé vers un tableau personnalisé ?',
      es: '¿Seguro que desea exportar este extracto a una tabla personalizada?',
      pt: 'Tem certeza de que deseja exportar este extrato para uma tabela personalizada?',
      tr: 'Bu ekstreyi özel bir tabloya aktarmak istediğinizden emin misiniz?',
      uk: 'Ви впевнені, що хочете експортувати цю виписку в користувацьку таблицю?',
      zh: '确定要将此对账单导出到自定义表格吗？',
      ar: 'هل أنت متأكد من رغبتك في تصدير هذا الكشف إلى جدول مخصص؟',
      pl: 'Czy na pewno chcesz wyeksportować ten wyciąg do niestandardowej tabeli?',
      it: 'Vuoi davvero esportare questo estratto conto in una tabella personalizzata?',
      sk: 'Naozaj chcete exportovať tento výpis do vlastnej tabuľky?',
      ja: 'この明細をカスタムテーブルにエクスポートしてもよろしいですか？',
      ko: '이 명세서를 사용자 정의 표로 내보내시겠습니까?',
      hi: 'क्या आप वाकई इस विवरण को कस्टम तालिका में निर्यात करना चाहते हैं?',
      nl: 'Weet u zeker dat u dit afschrift naar een aangepaste tabel wilt exporteren?',
      sv: 'Är du säker på att du vill exportera detta utdrag till en anpassad tabell?',
      vi: 'Bạn có chắc muốn xuất sao kê này sang bảng tùy chỉnh không?',
      id: 'Yakin ingin mengekspor laporan ini ke tabel kustom?',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Бас тарту',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      ar: 'إلغاء',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
    }),
    confirmExport: t({
      ru: 'Экспортировать',
      en: 'Export',
      kk: 'Экспорттау',
      de: 'Exportieren',
      fr: 'Exporter',
      es: 'Exportar',
      pt: 'Exportar',
      tr: 'Dışa aktar',
      uk: 'Експортувати',
      zh: '导出',
      ar: 'تصدير',
      pl: 'Eksportuj',
      it: 'Esporta',
      sk: 'Exportovať',
      ja: 'エクスポート',
      ko: '내보내기',
      hi: 'निर्यात करें',
      nl: 'Exporteren',
      sv: 'Exportera',
      vi: 'Xuất',
      id: 'Ekspor',
    }),
    tableName: t({
      ru: 'Чек {subject}',
      en: 'Receipt {subject}',
      kk: 'Чек {subject}',
      de: 'Beleg {subject}',
      fr: 'Reçu {subject}',
      es: 'Recibo {subject}',
      pt: 'Recibo {subject}',
      tr: 'Fiş {subject}',
      uk: 'Чек {subject}',
      zh: '收据 {subject}',
      ar: 'إيصال {subject}',
      pl: 'Paragon {subject}',
      it: 'Ricevuta {subject}',
      sk: 'Doklad {subject}',
      ja: 'レシート {subject}',
      ko: '영수증 {subject}',
      hi: 'रसीद {subject}',
      nl: 'Bon {subject}',
      sv: 'Kvitto {subject}',
      vi: 'Hóa đơn {subject}',
      id: 'Struk {subject}',
    }),
    tableDescription: t({
      ru: 'Экспортировано из отсканированного чека от {date}',
      en: 'Exported from scanned receipt on {date}',
      kk: '{date} күнгі сканерленген чектен экспортталды',
      de: 'Aus gescanntem Beleg vom {date} exportiert',
      fr: 'Exporté depuis un reçu numérisé du {date}',
      es: 'Exportado desde un recibo escaneado el {date}',
      pt: 'Exportado de um recibo digitalizado em {date}',
      tr: '{date} tarihli taranmış fişten aktarıldı',
      uk: 'Експортовано з відсканованого чека від {date}',
      zh: '从 {date} 扫描的收据导出',
      ar: 'تم التصدير من إيصال ممسوح ضوئيًا بتاريخ {date}',
      pl: 'Wyeksportowano z zeskanowanego paragonu z dnia {date}',
      it: 'Esportato da una ricevuta scansionata il {date}',
      sk: 'Exportované z naskenovaného dokladu zo dňa {date}',
      ja: '{date} にスキャンしたレシートからエクスポート',
      ko: '{date}에 스캔한 영수증에서 내보냄',
      hi: '{date} को स्कैन की गई रसीद से निर्यात किया गया',
      nl: 'Geëxporteerd uit gescande bon van {date}',
      sv: 'Exporterat från skannat kvitto den {date}',
      vi: 'Xuất từ hóa đơn đã quét ngày {date}',
      id: 'Diekspor dari struk yang dipindai pada {date}',
    }),
    columns: {
      item: t({
        ru: 'Позиция',
        en: 'Item',
        kk: 'Позиция',
        de: 'Position',
        fr: 'Article',
        es: 'Artículo',
        pt: 'Item',
        tr: 'Kalem',
        uk: 'Позиція',
        zh: '项目',
        ar: 'البند',
        pl: 'Pozycja',
        it: 'Voce',
        sk: 'Položka',
        ja: '明細',
        ko: '품목',
        hi: 'मद',
        nl: 'Regel',
        sv: 'Rad',
        vi: 'Mục',
        id: 'Item',
      }),
      vendor: t({
        ru: 'Продавец',
        en: 'Vendor',
        kk: 'Сатушы',
        de: 'Händler',
        fr: 'Commerçant',
        es: 'Comercio',
        pt: 'Fornecedor',
        tr: 'Satıcı',
        uk: 'Продавець',
        zh: '商家',
        ar: 'البائع',
        pl: 'Sprzedawca',
        it: 'Esercente',
        sk: 'Predajca',
        ja: '店舗',
        ko: '판매처',
        hi: 'विक्रेता',
        nl: 'Verkoper',
        sv: 'Säljare',
        vi: 'Người bán',
        id: 'Penjual',
      }),
      date: t({
        ru: 'Дата',
        en: 'Date',
        kk: 'Күні',
        de: 'Datum',
        fr: 'Date',
        es: 'Fecha',
        pt: 'Data',
        tr: 'Tarih',
        uk: 'Дата',
        zh: '日期',
        ar: 'التاريخ',
        pl: 'Data',
        it: 'Data',
        sk: 'Dátum',
        ja: '日付',
        ko: '날짜',
        hi: 'तारीख',
        nl: 'Datum',
        sv: 'Datum',
        vi: 'Ngày',
        id: 'Tanggal',
      }),
      amount: t({
        ru: 'Сумма',
        en: 'Amount',
        kk: 'Сома',
        de: 'Betrag',
        fr: 'Montant',
        es: 'Importe',
        pt: 'Valor',
        tr: 'Tutar',
        uk: 'Сума',
        zh: '金额',
        ar: 'المبلغ',
        pl: 'Kwota',
        it: 'Importo',
        sk: 'Suma',
        ja: '金額',
        ko: '금액',
        hi: 'राशि',
        nl: 'Bedrag',
        sv: 'Belopp',
        vi: 'Số tiền',
        id: 'Jumlah',
      }),
      currency: t({
        ru: 'Валюта',
        en: 'Currency',
        kk: 'Валюта',
        de: 'Währung',
        fr: 'Devise',
        es: 'Moneda',
        pt: 'Moeda',
        tr: 'Para birimi',
        uk: 'Валюта',
        zh: '货币',
        ar: 'العملة',
        pl: 'Waluta',
        it: 'Valuta',
        sk: 'Mena',
        ja: '通貨',
        ko: '통화',
        hi: 'मुद्रा',
        nl: 'Valuta',
        sv: 'Valuta',
        vi: 'Tiền tệ',
        id: 'Mata uang',
      }),
      source: t({
        ru: 'Источник',
        en: 'Source',
        kk: 'Дереккөз',
        de: 'Quelle',
        fr: 'Source',
        es: 'Origen',
        pt: 'Origem',
        tr: 'Kaynak',
        uk: 'Джерело',
        zh: '来源',
        ar: 'المصدر',
        pl: 'Źródło',
        it: 'Origine',
        sk: 'Zdroj',
        ja: 'ソース',
        ko: '출처',
        hi: 'स्रोत',
        nl: 'Bron',
        sv: 'Källa',
        vi: 'Nguồn',
        id: 'Sumber',
      }),
      status: t({
        ru: 'Статус',
        en: 'Status',
        kk: 'Күйі',
        de: 'Status',
        fr: 'Statut',
        es: 'Estado',
        pt: 'Status',
        tr: 'Durum',
        uk: 'Статус',
        zh: '状态',
        ar: 'الحالة',
        pl: 'Status',
        it: 'Stato',
        sk: 'Stav',
        ja: 'ステータス',
        ko: '상태',
        hi: 'स्थिति',
        nl: 'Status',
        sv: 'Status',
        vi: 'Trạng thái',
        id: 'Status',
      }),
    },
  },
} satisfies Dictionary;

export default content;
