import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementViewPage',
  content: {
    errors: {
      loadFailed: t({
        ru: 'Не удалось загрузить данные выписки',
        en: 'Failed to load statement data',
        kk: 'Үзінді деректерін жүктеу мүмкін болмады',
        de: 'Kontoauszugsdaten konnten nicht geladen werden',
        fr: 'Impossible de charger les données du relevé',
        es: 'Error al cargar los datos del extracto',
        pt: 'Falha ao carregar dados do extrato',
        tr: 'Ekstre verileri yüklenemedi',
        uk: 'Не вдалося завантажити дані виписки',
        zh: '无法加载对账单数据',
        ar: 'فشل تحميل بيانات الكشف',
        pl: 'Nie udało się załadować danych wyciągu',
        it: "Impossibile caricare i dati dell'estratto conto",
        sk: 'Nepodarilo sa načítať údaje výpisu',
        ja: '明細書データの読み込みに失敗しました',
        ko: '명세서 데이터를 불러오지 못했습니다',
        hi: 'विवरण डेटा लोड करने में विफल',
        nl: 'Kon afschriftgegevens niet laden',
        sv: 'Misslyckades med att ladda kontoutdragsdata',
        vi: 'Không thể tải dữ liệu sao kê',
        id: 'Gagal memuat data laporan',
      }),
    },
    loading: t({
      ru: 'Загрузка файла...',
      en: 'Loading file...',
      kk: 'Файл жүктелуде...',
      de: 'Datei wird geladen...',
      fr: 'Chargement du fichier...',
      es: 'Cargando archivo...',
      pt: 'Carregando arquivo...',
      tr: 'Dosya yükleniyor...',
      uk: 'Завантаження файлу...',
      zh: '正在加载文件...',
      ar: 'جارٍ تحميل الملف...',
      pl: 'Ładowanie pliku...',
      it: 'Caricamento file...',
      sk: 'Načítava sa súbor...',
      ja: 'ファイルを読み込んでいます...',
      ko: '파일 로딩 중...',
      hi: 'फ़ाइल लोड हो रही है...',
      nl: 'Bestand laden...',
      sv: 'Laddar fil...',
      vi: 'Đang tải tệp...',
      id: 'Memuat file...',
    }),
    fileLoaded: t({
      ru: 'Файл загружен',
      en: 'File loaded',
      kk: 'Файл жүктелді',
      de: 'Datei geladen',
      fr: 'Fichier chargé',
      es: 'Archivo cargado',
      pt: 'Arquivo carregado',
      tr: 'Dosya yüklendi',
      uk: 'Файл завантажено',
      zh: '文件已加载',
      ar: 'تم تحميل الملف',
      pl: 'Plik załadowany',
      it: 'File caricato',
      sk: 'Súbor bol načítaný',
      ja: 'ファイルが読み込まれました',
      ko: '파일이 로드되었습니다',
      hi: 'फ़ाइल लोड हो गई',
      nl: 'Bestand geladen',
      sv: 'Fil laddad',
      vi: 'Tệp đã được tải',
      id: 'File berhasil dimuat',
    }),
    fileLoadFailed: t({
      ru: 'Не удалось загрузить файл',
      en: 'Failed to load file',
      kk: 'Файлды жүктеу мүмкін болмады',
      de: 'Datei konnte nicht geladen werden',
      fr: 'Impossible de charger le fichier',
      es: 'Error al cargar el archivo',
      pt: 'Falha ao carregar o arquivo',
      tr: 'Dosya yüklenemedi',
      uk: 'Не вдалося завантажити файл',
      zh: '无法加载文件',
      ar: 'فشل تحميل الملف',
      pl: 'Nie udało się załadować pliku',
      it: 'Impossibile caricare il file',
      sk: 'Nepodarilo sa načítať súbor',
      ja: 'ファイルの読み込みに失敗しました',
      ko: '파일을 불러오지 못했습니다',
      hi: 'फ़ाइल लोड करने में विफल',
      nl: 'Kon bestand niet laden',
      sv: 'Misslyckades med att ladda filen',
      vi: 'Không thể tải tệp',
      id: 'Gagal memuat file',
    }),
    statementNotFound: t({
      ru: 'Выписка не найдена',
      en: 'Statement not found',
      kk: 'Үзінді табылмады',
      de: 'Kontoauszug nicht gefunden',
      fr: 'Relevé introuvable',
      es: 'Extracto no encontrado',
      pt: 'Extrato não encontrado',
      tr: 'Ekstre bulunamadı',
      uk: 'Виписку не знайдено',
      zh: '未找到对账单',
      ar: 'الكشف غير موجود',
      pl: 'Wyciąg nie znaleziony',
      it: 'Estratto conto non trovato',
      sk: 'Výpis sa nenašiel',
      ja: '明細書が見つかりません',
      ko: '명세서를 찾을 수 없습니다',
      hi: 'विवरण नहीं मिला',
      nl: 'Afschrift niet gevonden',
      sv: 'Kontoutdraget hittades inte',
      vi: 'Không tìm thấy sao kê',
      id: 'Laporan tidak ditemukan',
    }),
    back: t({
      ru: 'Назад',
      en: 'Back',
      kk: 'Артқа',
      de: 'Zurück',
      fr: 'Retour',
      es: 'Atrás',
      pt: 'Voltar',
      tr: 'Geri',
      uk: 'Назад',
      zh: '返回',
      ar: 'رجوع',
      pl: 'Wstecz',
      it: 'Indietro',
      sk: 'Späť',
      ja: '戻る',
      ko: '뒤로',
      hi: 'वापस',
      nl: 'Terug',
      sv: 'Tillbaka',
      vi: 'Quay lại',
      id: 'Kembali',
    }),
    backToStatements: t({
      ru: 'Назад к списку выписок',
      en: 'Back to statements',
      kk: 'Үзінділер тізіміне оралу',
      de: 'Zurück zu den Kontoauszügen',
      fr: 'Retour aux relevés',
      es: 'Volver a extractos',
      pt: 'Voltar aos extratos',
      tr: 'Ekstreler listesine dön',
      uk: 'Назад до списку виписок',
      zh: '返回对账单列表',
      ar: 'العودة إلى الكشوفات',
      pl: 'Wróć do wyciągów',
      it: 'Torna agli estratti conto',
      sk: 'Späť na výpisy',
      ja: '明細書一覧に戻る',
      ko: '명세서 목록으로 돌아가기',
      hi: 'विवरण सूची पर वापस जाएं',
      nl: 'Terug naar afschriften',
      sv: 'Tillbaka till kontoutdrag',
      vi: 'Quay lại danh sách sao kê',
      id: 'Kembali ke laporan',
    }),
  },
} satisfies Dictionary;

export default content;
