import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementViewPage',
  content: {
    errors: {
      loadFailed: t({
        ru: 'Не удалось загрузить данные выписки',
        en: 'Failed to load statement data',
        kk: 'Үзінді деректерін жүктеу мүмкін болмады',
        de: 'Kontoauszugsdaten konnten nicht geladen werden',
        fr: 'Impossible de charger les données du relevé',
        es: 'Error al cargar los datos del extracto',
        pt: 'Falha ao carregar dados do extrato',
        tr: 'Ekstre verileri yüklenemedi',
        uk: 'Не вдалося завантажити дані виписки',
        zh: '无法加载对账单数据',
        pl: 'Nie udało się załadować danych wyciągu',
        it: "Impossibile caricare i dati dell'estratto conto",
        sk: 'Nepodarilo sa načítať údaje výpisu',
        ja: '明細書データの読み込みに失敗しました',
        ko: '명세서 데이터를 불러오지 못했습니다',
        hi: 'विवरण डेटा लोड करने में विफल',
        nl: 'Kon afschriftgegevens niet laden',
        sv: 'Misslyckades med att ladda kontoutdragsdata',
        vi: 'Không thể tải dữ liệu sao kê',
        id: 'Gagal memuat data laporan',
        da: 'Kontoudtogets data kunne ikke indlæses',
        nb: 'Kunne ikke laste kontoutskriftens data',
        nn: 'Kunne ikkje laste data for kontoutskrifta',
        fi: 'Tiliotteen tietojen lataus epäonnistui',
        fo: 'Fekk ikki lisið dátur úr kontoyvirlitinum',
        is: 'Ekki tókst að hlaða gögnum yfirlitsins',
        cs: 'Data výpisu se nepodařilo načíst',
        bg: 'Данните на извлечението не можаха да се заредят',
        hr: 'Podatke izvatka nije moguće učitati',
        sr: 'Податке извода није могуће учитати',
        sl: 'Podatkov izpiska ni bilo mogoče naložiti',
        mk: 'Податоците на изводот не можеа да се вчитаат',
        be: 'Не ўдалося загрузіць дадзеныя выпіскі',
        bs: 'Podatke izvoda nije moguće učitati',
        hsb: 'Daty wujimka njedadźa so začitać',
      }),
    },
    loading: t({
      ru: 'Загрузка файла...',
      en: 'Loading file...',
      kk: 'Файл жүктелуде...',
      de: 'Datei wird geladen...',
      fr: 'Chargement du fichier...',
      es: 'Cargando archivo...',
      pt: 'Carregando arquivo...',
      tr: 'Dosya yükleniyor...',
      uk: 'Завантаження файлу...',
      zh: '正在加载文件...',
      pl: 'Ładowanie pliku...',
      it: 'Caricamento file...',
      sk: 'Načítava sa súbor...',
      ja: 'ファイルを読み込んでいます...',
      ko: '파일 로딩 중...',
      hi: 'फ़ाइल लोड हो रही है...',
      nl: 'Bestand laden...',
      sv: 'Laddar fil...',
      vi: 'Đang tải tệp...',
      id: 'Memuat file...',
      da: 'Indlæser fil ...',
      nb: 'Laster fil ...',
      nn: 'Lastar fil ...',
      fi: 'Ladataan tiedostoa ...',
      fo: 'Lesur fílu ...',
      is: 'Hleð skrá ...',
      cs: 'Načítání souboru ...',
      bg: 'Зареждане на файла ...',
      hr: 'Učitavanje datoteke ...',
      sr: 'Учитавање датотеке ...',
      sl: 'Nalaganje datoteke ...',
      mk: 'Вчитување на податотеката ...',
      be: 'Загрузка файла ...',
      bs: 'Učitavanje datoteke ...',
      hsb: 'Dataja so čita ...',
    }),
    fileLoaded: t({
      ru: 'Файл загружен',
      en: 'File loaded',
      kk: 'Файл жүктелді',
      de: 'Datei geladen',
      fr: 'Fichier chargé',
      es: 'Archivo cargado',
      pt: 'Arquivo carregado',
      tr: 'Dosya yüklendi',
      uk: 'Файл завантажено',
      zh: '文件已加载',
      pl: 'Plik załadowany',
      it: 'File caricato',
      sk: 'Súbor bol načítaný',
      ja: 'ファイルが読み込まれました',
      ko: '파일이 로드되었습니다',
      hi: 'फ़ाइल लोड हो गई',
      nl: 'Bestand geladen',
      sv: 'Fil laddad',
      vi: 'Tệp đã được tải',
      id: 'File berhasil dimuat',
      da: 'Filen er indlæst',
      nb: 'Filen er lastet',
      nn: 'Fila er lasta',
      fi: 'Tiedosto ladattu',
      fo: 'Fílan er lisin',
      is: 'Skrá hlaðin',
      cs: 'Soubor načten',
      bg: 'Файлът е зареден',
      hr: 'Datoteka učitana',
      sr: 'Датотека учитана',
      sl: 'Datoteka naložena',
      mk: 'Податотеката е вчитана',
      be: 'Файл загружаны',
      bs: 'Datoteka učitana',
      hsb: 'Dataja začitana',
    }),
    fileLoadFailed: t({
      ru: 'Не удалось загрузить файл',
      en: 'Failed to load file',
      kk: 'Файлды жүктеу мүмкін болмады',
      de: 'Datei konnte nicht geladen werden',
      fr: 'Impossible de charger le fichier',
      es: 'Error al cargar el archivo',
      pt: 'Falha ao carregar o arquivo',
      tr: 'Dosya yüklenemedi',
      uk: 'Не вдалося завантажити файл',
      zh: '无法加载文件',
      pl: 'Nie udało się załadować pliku',
      it: 'Impossibile caricare il file',
      sk: 'Nepodarilo sa načítať súbor',
      ja: 'ファイルの読み込みに失敗しました',
      ko: '파일을 불러오지 못했습니다',
      hi: 'फ़ाइल लोड करने में विफल',
      nl: 'Kon bestand niet laden',
      sv: 'Misslyckades med att ladda filen',
      vi: 'Không thể tải tệp',
      id: 'Gagal memuat file',
      da: 'Filen kunne ikke indlæses',
      nb: 'Kunne ikke laste filen',
      nn: 'Kunne ikkje laste fila',
      fi: 'Tiedoston lataus epäonnistui',
      is: 'Ekki tókst að hlaða skrá',
      fo: 'Fílan kundi ikki lesast inn',
      cs: 'Soubor se nepodařilo načíst',
      bg: 'Файлът не можа да се зареди',
      hr: 'Datoteku nije bilo moguće učitati',
      sr: 'Датотеку није било могуће учитати',
      sl: 'Datoteke ni bilo mogoče naložiti',
      mk: 'Податотеката не можеше да се вчита',
      be: 'Не ўдалося загрузіць файл',
      bs: 'Datoteku nije bilo moguće učitati',
      hsb: 'Dataja njeda so začitać',
    }),
    statementNotFound: t({
      ru: 'Выписка не найдена',
      en: 'Statement not found',
      kk: 'Үзінді табылмады',
      de: 'Kontoauszug nicht gefunden',
      fr: 'Relevé introuvable',
      es: 'Extracto no encontrado',
      pt: 'Extrato não encontrado',
      tr: 'Ekstre bulunamadı',
      uk: 'Виписку не знайдено',
      zh: '未找到对账单',
      pl: 'Wyciąg nie znaleziony',
      it: 'Estratto conto non trovato',
      sk: 'Výpis sa nenašiel',
      ja: '明細書が見つかりません',
      ko: '명세서를 찾을 수 없습니다',
      hi: 'विवरण नहीं मिला',
      nl: 'Afschrift niet gevonden',
      sv: 'Kontoutdraget hittades inte',
      vi: 'Không tìm thấy sao kê',
      id: 'Laporan tidak ditemukan',
      da: 'Kontoudtoget blev ikke fundet',
      nb: 'Kontoutskriften ble ikke funnet',
      nn: 'Kontoutskrifta vart ikkje funnen',
      fi: 'Tiliotetta ei löytynyt',
      is: 'Yfirlit fannst ekki',
      fo: 'Kontoyvirlitið varð ikki funnið',
      cs: 'Výpis nebyl nalezen',
      bg: 'Извлечението не е намерено',
      hr: 'Izvod nije nađen',
      sr: 'Извод није нађен',
      sl: 'Izpiska ni bilo mogoče najti',
      mk: 'Извадокот не е најден',
      be: 'Выпіска не знойдзена',
      bs: 'Izvod nije nađen',
      hsb: 'Wupis njeje so namakał',
    }),
    back: t({
      ru: 'Назад',
      en: 'Back',
      kk: 'Артқа',
      de: 'Zurück',
      fr: 'Retour',
      es: 'Atrás',
      pt: 'Voltar',
      tr: 'Geri',
      uk: 'Назад',
      zh: '返回',
      pl: 'Wstecz',
      it: 'Indietro',
      sk: 'Späť',
      ja: '戻る',
      ko: '뒤로',
      hi: 'वापस',
      nl: 'Terug',
      sv: 'Tillbaka',
      vi: 'Quay lại',
      id: 'Kembali',
      da: 'Tilbage',
      nb: 'Tilbake',
      nn: 'Tilbake',
      fi: 'Takaisin',
      is: 'Til baka',
      fo: 'Aftur',
      cs: 'Zpět',
      bg: 'Назад',
      hr: 'Natrag',
      sr: 'Назад',
      sl: 'Nazaj',
      mk: 'Назад',
      be: 'Назад',
      bs: 'Nazad',
      hsb: 'Wróćo',
    }),
    backToStatements: t({
      ru: 'Назад к списку выписок',
      en: 'Back to statements',
      kk: 'Үзінділер тізіміне оралу',
      de: 'Zurück zu den Kontoauszügen',
      fr: 'Retour aux relevés',
      es: 'Volver a extractos',
      pt: 'Voltar aos extratos',
      tr: 'Ekstreler listesine dön',
      uk: 'Назад до списку виписок',
      zh: '返回对账单列表',
      pl: 'Wróć do wyciągów',
      it: 'Torna agli estratti conto',
      sk: 'Späť na výpisy',
      ja: '明細書一覧に戻る',
      ko: '명세서 목록으로 돌아가기',
      hi: 'विवरण सूची पर वापस जाएं',
      nl: 'Terug naar afschriften',
      sv: 'Tillbaka till kontoutdrag',
      vi: 'Quay lại danh sách sao kê',
      id: 'Kembali ke laporan',
      da: 'Tilbage til kontoudtog',
      nb: 'Tilbake til kontoutskrifter',
      nn: 'Tilbake til kontoutskrifter',
      fi: 'Takaisin tiliotteisiin',
      fo: 'Aftur til kontoyvirlit',
      is: 'Til baka í yfirlit',
      cs: 'Zpět na výpisy',
      bg: 'Назад към извлеченията',
      hr: 'Natrag na izvatke',
      sr: 'Назад на изводе',
      sl: 'Nazaj na izpiske',
      mk: 'Назад кон изводите',
      be: 'Назад да выпісак',
      bs: 'Nazad na izvode',
      hsb: 'Wróćo k wujimkam',
    }),
  },
} satisfies Dictionary;

export default content;
