import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'permissionsPanel',
  content: {
    title: t({
      ru: 'Права доступа',
      en: 'Permissions',
      kk: 'Қолжетімділік құқықтары',
      de: 'Berechtigungen',
      fr: 'Autorisations',
      es: 'Permisos',
      pt: 'Permissões',
      tr: 'İzinler',
      uk: 'Права доступу',
      zh: '权限',
      ar: 'الأذونات',
      pl: 'Uprawnienia',
      it: 'Autorizzazioni',
      sk: 'Oprávnenia',
      ja: '権限',
      ko: '권한',
      hi: 'अनुमतियां',
      nl: 'Machtigingen',
      sv: 'Behörigheter',
      vi: 'Quyền truy cập',
      id: 'Izin',
      da: 'Tilladelser',
      nb: 'Tillatelser',
      nn: 'Løyve',
      fi: 'Käyttöoikeudet',
      is: 'Heimildir',
      fo: 'Loyvi',
      cs: 'Oprávnění',
      bg: 'Права',
      hr: 'Dopuštenja',
      sr: 'Дозволе',
      sl: 'Dovoljenja',
      mk: 'Дозволи',
      be: 'Дазволы',
      bs: 'Dozvole',
      hsb: 'Prawa',
    }),
    grantAccess: t({
      ru: 'Предоставить доступ',
      en: 'Grant access',
      kk: 'Қолжетімділік беру',
      de: 'Zugriff gewähren',
      fr: "Accorder l'accès",
      es: 'Conceder acceso',
      pt: 'Conceder acesso',
      tr: 'Erişim ver',
      uk: 'Надати доступ',
      zh: '授予访问权限',
      ar: 'منح الوصول',
      pl: 'Przyznaj dostęp',
      it: 'Concedi accesso',
      sk: 'Udeliť prístup',
      ja: 'アクセスを許可',
      ko: '접근 권한 부여',
      hi: 'पहुंच प्रदान करें',
      nl: 'Toegang verlenen',
      sv: 'Bevilja åtkomst',
      vi: 'Cấp quyền truy cập',
      id: 'Berikan akses',
      da: 'Giv adgang',
      nb: 'Gi tilgang',
      nn: 'Gje tilgang',
      fi: 'Myönnä oikeus',
      is: 'Veita aðgang',
      cs: 'Udělit přístup',
      bg: 'Предоставяне на достъп',
      hr: 'Dodijeli pristup',
      sr: 'Додели приступ',
      sl: 'Dodeli dostop',
      mk: 'Додели пристап',
      be: 'Даць доступ',
      bs: 'Dodijeli pristup',
      hsb: 'Přistup dać',
      fo: 'Veit atgongd',
    }),
    empty: t({
      ru: 'Пока никому не предоставлен доступ к этому файлу',
      en: 'No one has been granted access to this file yet',
      kk: 'Бұл файлға әзірге ешкімге қолжетімділік берілген жоқ',
      de: 'Noch niemandem wurde Zugriff auf diese Datei gewährt',
      fr: "Personne n'a encore eu accès à ce fichier",
      es: 'Nadie ha recibido acceso a este archivo aún',
      pt: 'Ninguém recebeu acesso a este arquivo ainda',
      tr: 'Bu dosyaya henüz kimseye erişim verilmedi',
      uk: 'Нікому ще не надано доступ до цього файлу',
      zh: '尚未授予任何人访问此文件的权限',
      ar: 'لم يتم منح أي شخص حق الوصول إلى هذا الملف بعد',
      pl: 'Nikt nie otrzymał jeszcze dostępu do tego pliku',
      it: 'Nessuno ha ancora ricevuto accesso a questo file',
      sk: 'K tomuto súboru zatiaľ nikto nemá udelený prístup',
      ja: 'このファイルへのアクセスはまだ誰にも許可されていません',
      ko: '아직 이 파일에 대한 접근 권한이 부여된 사람이 없습니다',
      hi: 'अभी तक किसी को भी इस फ़ाइल तक पहुंच नहीं दी गई है',
      nl: 'Niemand heeft nog toegang gekregen tot dit bestand',
      sv: 'Ingen har ännu beviljats åtkomst till den här filen',
      vi: 'Chưa có ai được cấp quyền truy cập vào tệp này',
      id: 'Belum ada yang diberikan akses ke file ini',
      da: 'Der er endnu ikke givet nogen adgang til denne fil',
      nb: 'Ingen har fått tilgang til denne filen ennå',
      nn: 'Ingen har fått tilgang til denne fila enno',
      fi: 'Tähän tiedostoon ei ole vielä myönnetty oikeuksia kenellekään',
      is: 'Enginn hefur fengið aðgang að þessari skrá enn',
      cs: 'K tomuto souboru dosud nebyl nikomu udělen přístup',
      bg: 'Още никой не е получил достъп до този файл',
      hr: 'Nikomu još nije dodijeljen pristup ovoj datoteci',
      sr: 'Никоме још није додељен приступ овој датотеци',
      sl: 'Nikomur še ni dodeljen dostop do te datoteke',
      mk: 'Сè уште никому не е доделен пристап до оваа податотека',
      be: 'Нікому пакуль не дадзены доступ да гэтага файла',
      bs: 'Nikome još nije dodijeljen pristup ovoj datoteci',
      hsb: 'Nichtó hišće nima přistup k tutej dataji',
      fo: 'Ongum er enn givin atgongd til hesa fílu',
    }),
    confirmRevoke: t({
      ru: 'Вы уверены, что хотите отозвать права доступа?',
      en: 'Are you sure you want to revoke access?',
      kk: 'Қолжетімділікті қайтарып алғыңыз келетініне сенімдісіз бе?',
      de: 'Sind Sie sicher, dass Sie den Zugriff widerrufen möchten?',
      fr: "Êtes-vous sûr de vouloir révoquer l'accès ?",
      es: '¿Está seguro de que desea revocar el acceso?',
      pt: 'Tem certeza de que deseja revogar o acesso?',
      tr: 'Erişimi iptal etmek istediğinizden emin misiniz?',
      uk: 'Ви впевнені, що хочете відкликати права доступу?',
      zh: '您确定要撤销访问权限吗？',
      ar: 'هل أنت متأكد أنك تريد إلغاء الوصول؟',
      pl: 'Czy na pewno chcesz odwołać dostęp?',
      it: "Sei sicuro di voler revocare l'accesso?",
      sk: 'Naozaj chcete odobrať prístup?',
      ja: 'アクセス権を取り消してもよろしいですか？',
      ko: '접근 권한을 취소하시겠습니까?',
      hi: 'क्या आप वाकई पहुंच रद्द करना चाहते हैं?',
      nl: 'Weet u zeker dat u de toegang wilt intrekken?',
      sv: 'Är du säker på att du vill återkalla åtkomsten?',
      vi: 'Bạn có chắc chắn muốn thu hồi quyền truy cập không?',
      id: 'Apakah Anda yakin ingin mencabut akses?',
      da: 'Er du sikker på, at du vil tilbagekalde adgangen?',
      nb: 'Er du sikker på at du vil oppheve tilgangen?',
      nn: 'Er du sikker på at du vil oppheve tilgangen?',
      fi: 'Haluatko varmasti peruuttaa oikeuden?',
      is: 'Ertu viss um að þú vilt afturkalla aðganginn?',
      cs: 'Opravdu chcete přístup odebrat?',
      bg: 'Наистина ли искате да отнемете достъпа?',
      hr: 'Jeste li sigurni da želite ukinuti pristup?',
      sr: 'Да ли сте сигурни да желите да укинете приступ?',
      sl: 'Ali ste prepričani, da želite preklicati dostop?',
      mk: 'Дали сте сигурни дека сакате да го одземете пристапот?',
      be: 'Ці сапраўды хочаце адабраць доступ?',
      bs: 'Jeste li sigurni da želite ukinuti pristup?',
      hsb: 'Sće woprawdźe wěsty, zo chceće přistup wotwołać?',
      fo: 'Ert tú vís/ur í, at tú vilt taka atgongdina av?',
    }),
    errors: {
      grantFailed: t({
        ru: 'Не удалось предоставить доступ',
        en: 'Failed to grant access',
        kk: 'Қолжетімділік беру мүмкін болмады',
        de: 'Zugriff konnte nicht gewährt werden',
        fr: "Impossible d'accorder l'accès",
        es: 'No se pudo conceder el acceso',
        pt: 'Falha ao conceder acesso',
        tr: 'Erişim verilemedi',
        uk: 'Не вдалося надати доступ',
        zh: '授予访问权限失败',
        ar: 'فشل منح الوصول',
        pl: 'Nie udało się przyznać dostępu',
        it: "Impossibile concedere l'accesso",
        sk: 'Nepodarilo sa udeliť prístup',
        ja: 'アクセスの許可に失敗しました',
        ko: '접근 권한 부여에 실패했습니다',
        hi: 'पहुंच प्रदान करने में विफल',
        nl: 'Toegang verlenen mislukt',
        sv: 'Det gick inte att bevilja åtkomst',
        vi: 'Không thể cấp quyền truy cập',
        id: 'Gagal memberikan akses',
        da: 'Adgangen kunne ikke gives',
        nb: 'Kunne ikke gi tilgang',
        nn: 'Kunne ikkje gje tilgang',
        fi: 'Oikeuden myöntäminen epäonnistui',
        is: 'Ekki tókst að veita aðgang',
        cs: 'Přístup se nepodařilo udělit',
        bg: 'Достъпът не можа да бъде предоставен',
        hr: 'Pristup nije moguće dodijeliti',
        sr: 'Приступ није могуће доделити',
        sl: 'Dostopa ni bilo mogoče dodeliti',
        mk: 'Пристапот не можеше да се додели',
        be: 'Не ўдалося даць доступ',
        bs: 'Pristup nije moguće dodijeliti',
        hsb: 'Přistup njeda so dać',
        fo: 'Fekk ikki givið atgongd',
      }),
      updateFailed: t({
        ru: 'Не удалось обновить права',
        en: 'Failed to update permissions',
        kk: 'Құқықтарды жаңарту мүмкін болмады',
        de: 'Berechtigungen konnten nicht aktualisiert werden',
        fr: 'Impossible de mettre à jour les autorisations',
        es: 'No se pudieron actualizar los permisos',
        pt: 'Falha ao atualizar permissões',
        tr: 'İzinler güncellenemedi',
        uk: 'Не вдалося оновити права',
        zh: '更新权限失败',
        ar: 'فشل تحديث الأذونات',
        pl: 'Nie udało się zaktualizować uprawnień',
        it: 'Impossibile aggiornare le autorizzazioni',
        sk: 'Nepodarilo sa aktualizovať oprávnenia',
        ja: '権限の更新に失敗しました',
        ko: '권한 업데이트에 실패했습니다',
        hi: 'अनुमतियां अपडेट करने में विफल',
        nl: 'Machtigingen bijwerken mislukt',
        sv: 'Det gick inte att uppdatera behörigheter',
        vi: 'Không thể cập nhật quyền',
        id: 'Gagal memperbarui izin',
        da: 'Tilladelserne kunne ikke opdateres',
        nb: 'Kunne ikke oppdatere tillatelsene',
        nn: 'Kunne ikkje oppdatere løyva',
        fi: 'Oikeuksien päivitys epäonnistui',
        is: 'Ekki tókst að uppfæra heimildir',
        cs: 'Oprávnění se nepodařilo aktualizovat',
        bg: 'Правата не можаха да бъдат обновени',
        hr: 'Dopuštenja nije moguće ažurirati',
        sr: 'Дозволе није могуће ажурирати',
        sl: 'Dovoljenj ni bilo mogoče posodobiti',
        mk: 'Дозволите не можеа да се ажурираат',
        be: 'Не ўдалося абнавіць дазволы',
        bs: 'Dozvole nije moguće ažurirati',
        hsb: 'Dowolnosće njedadźa so aktualizować',
        fo: 'Fekk ikki dagført loyvini',
      }),
    },
    table: {
      user: t({
        ru: 'Пользователь',
        en: 'User',
        kk: 'Пайдаланушы',
        de: 'Benutzer',
        fr: 'Utilisateur',
        es: 'Usuario',
        pt: 'Usuário',
        tr: 'Kullanıcı',
        uk: 'Користувач',
        zh: '用户',
        ar: 'المستخدم',
        pl: 'Użytkownik',
        it: 'Utente',
        sk: 'Používateľ',
        ja: 'ユーザー',
        ko: '사용자',
        hi: 'उपयोगकर्ता',
        nl: 'Gebruiker',
        sv: 'Användare',
        vi: 'Người dùng',
        id: 'Pengguna',
        da: 'Bruger',
        nb: 'Bruker',
        nn: 'Brukar',
        fi: 'Käyttäjä',
        is: 'Notandi',
        fo: 'Brúkari',
        cs: 'Uživatel',
        bg: 'Потребител',
        hr: 'Korisnik',
        sr: 'Корисник',
        sl: 'Uporabnik',
        mk: 'Корисник',
        be: 'Карыстальнік',
        bs: 'Korisnik',
        hsb: 'Wužiwar',
      }),
      rights: t({
        ru: 'Права',
        en: 'Rights',
        kk: 'Құқықтар',
        de: 'Rechte',
        fr: 'Droits',
        es: 'Derechos',
        pt: 'Direitos',
        tr: 'Haklar',
        uk: 'Права',
        zh: '权限',
        ar: 'الحقوق',
        pl: 'Prawa',
        it: 'Diritti',
        sk: 'Práva',
        ja: '権利',
        ko: '권리',
        hi: 'अधिकार',
        nl: 'Rechten',
        sv: 'Rättigheter',
        vi: 'Quyền',
        id: 'Hak',
        da: 'Rettigheder',
        nb: 'Rettigheter',
        nn: 'Rettar',
        fi: 'Oikeudet',
        is: 'Réttindi',
        cs: 'Práva',
        bg: 'Права',
        hr: 'Prava',
        sr: 'Права',
        sl: 'Pravice',
        mk: 'Права',
        be: 'Правы',
        bs: 'Prava',
        hsb: 'Prawa',
        fo: 'Rættindi',
      }),
      canReshare: t({
        ru: 'Может поделиться',
        en: 'Can reshare',
        kk: 'Бөлісе алады',
        de: 'Kann teilen',
        fr: 'Peut repartager',
        es: 'Puede compartir',
        pt: 'Pode compartilhar',
        tr: 'Yeniden paylaşabilir',
        uk: 'Може поділитися',
        zh: '可以重新分享',
        ar: 'يمكنه إعادة المشاركة',
        pl: 'Może udostępnić',
        it: 'Può ricondividere',
        sk: 'Môže ďalej zdieľať',
        ja: '再共有可能',
        ko: '재공유 가능',
        hi: 'पुनः साझा कर सकते हैं',
        nl: 'Kan opnieuw delen',
        sv: 'Kan dela vidare',
        vi: 'Có thể chia sẻ lại',
        id: 'Dapat berbagi ulang',
        da: 'Kan videredele',
        nb: 'Kan dele videre',
        nn: 'Kan dele vidare',
        fi: 'Voi jakaa edelleen',
        is: 'Má deila áfram',
        cs: 'Může sdílet dál',
        bg: 'Може да споделя нататък',
        hr: 'Može dalje dijeliti',
        sr: 'Може даље да дели',
        sl: 'Lahko deli naprej',
        mk: 'Може да дели понатаму',
        be: 'Можа дзяліцца далей',
        bs: 'Može dalje dijeliti',
        hsb: 'Móže dale dźělić',
        fo: 'Kann deila víðari',
      }),
      expires: t({
        ru: 'Срок действия',
        en: 'Expires',
        kk: 'Мерзімі',
        de: 'Läuft ab',
        fr: 'Expire',
        es: 'Vence',
        pt: 'Expira',
        tr: 'Sona erer',
        uk: 'Термін дії',
        zh: '到期',
        ar: 'ينتهي',
        pl: 'Wygasa',
        it: 'Scade',
        sk: 'Platnosť do',
        ja: '有効期限',
        ko: '만료',
        hi: 'समाप्त होता है',
        nl: 'Verloopt',
        sv: 'Utgår',
        vi: 'Hết hạn',
        id: 'Kedaluwarsa',
        da: 'Udløber',
        nb: 'Utløper',
        nn: 'Går ut',
        fi: 'Vanhenee',
        is: 'Gildir til',
        fo: 'Fer út',
        cs: 'Vyprší',
        bg: 'Изтича',
        hr: 'Istječe',
        sr: 'Истиче',
        sl: 'Poteče',
        mk: 'Истекува',
        be: 'Сканчаецца',
        bs: 'Istječe',
        hsb: 'Spadnje',
      }),
      grantedBy: t({
        ru: 'Предоставил',
        en: 'Granted by',
        kk: 'Берген',
        de: 'Gewährt von',
        fr: 'Accordé par',
        es: 'Concedido por',
        pt: 'Concedido por',
        tr: 'Veren',
        uk: 'Надано',
        zh: '授权人',
        ar: 'منح بواسطة',
        pl: 'Przyznane przez',
        it: 'Concesso da',
        sk: 'Udelil',
        ja: '付与者',
        ko: '권한 부여자',
        hi: 'किसके द्वारा प्रदान किया',
        nl: 'Verleend door',
        sv: 'Beviljad av',
        vi: 'Được cấp bởi',
        id: 'Diberikan oleh',
        da: 'Givet af',
        nb: 'Gitt av',
        nn: 'Gjeve av',
        fi: 'Myönsi',
        is: 'Veitt af',
        cs: 'Udělil',
        bg: 'Предоставен от',
        hr: 'Dodijelio',
        sr: 'Доделио',
        sl: 'Dodelil',
        mk: 'Доделил',
        be: 'Даў',
        bs: 'Dodijelio',
        hsb: 'Dał je',
        fo: 'Givin av',
      }),
      createdAt: t({
        ru: 'Создано',
        en: 'Created',
        kk: 'Құрылған',
        de: 'Erstellt',
        fr: 'Créé',
        es: 'Creado',
        pt: 'Criado',
        tr: 'Oluşturuldu',
        uk: 'Створено',
        zh: '创建时间',
        ar: 'تاريخ الإنشاء',
        pl: 'Utworzono',
        it: 'Creato',
        sk: 'Vytvorené',
        ja: '作成日時',
        ko: '생성일',
        hi: 'बनाया गया',
        nl: 'Aangemaakt',
        sv: 'Skapad',
        vi: 'Ngày tạo',
        id: 'Dibuat pada',
        da: 'Oprettet',
        nb: 'Opprettet',
        nn: 'Oppretta',
        fi: 'Luotu',
        is: 'Búið til',
        fo: 'Stovnað',
        cs: 'Vytvořeno',
        bg: 'Създаден',
        hr: 'Izrađeno',
        sr: 'Направљено',
        sl: 'Ustvarjeno',
        mk: 'Создадено',
        be: 'Створана',
        bs: 'Napravljeno',
        hsb: 'Wutworjene',
      }),
      actions: t({
        ru: 'Действия',
        en: 'Actions',
        kk: 'Әрекеттер',
        de: 'Aktionen',
        fr: 'Actions',
        es: 'Acciones',
        pt: 'Ações',
        tr: 'İşlemler',
        uk: 'Дії',
        zh: '操作',
        ar: 'الإجراءات',
        pl: 'Akcje',
        it: 'Azioni',
        sk: 'Akcie',
        ja: 'アクション',
        ko: '작업',
        hi: 'क्रियाएं',
        nl: 'Acties',
        sv: 'Åtgärder',
        vi: 'Hành động',
        id: 'Tindakan',
        da: 'Handlinger',
        nb: 'Handlinger',
        nn: 'Handlingar',
        fi: 'Toiminnot',
        is: 'Aðgerðir',
        fo: 'Handlingar',
        cs: 'Akce',
        bg: 'Действия',
        hr: 'Radnje',
        sr: 'Радње',
        sl: 'Dejanja',
        mk: 'Дејства',
        be: 'Дзеянні',
        bs: 'Radnje',
        hsb: 'Akcije',
      }),
    },
    values: {
      yes: t({
        ru: 'Да',
        en: 'Yes',
        kk: 'Иә',
        de: 'Ja',
        fr: 'Oui',
        es: 'Sí',
        pt: 'Sim',
        tr: 'Evet',
        uk: 'Так',
        zh: '是',
        ar: 'نعم',
        pl: 'Tak',
        it: 'Sì',
        sk: 'Áno',
        ja: 'はい',
        ko: '예',
        hi: 'हां',
        nl: 'Ja',
        sv: 'Ja',
        vi: 'Có',
        id: 'Ya',
        da: 'Ja',
        nb: 'Ja',
        nn: 'Ja',
        fi: 'Kyllä',
        is: 'Já',
        fo: 'Ja',
        cs: 'Ano',
        bg: 'Да',
        hr: 'Da',
        sr: 'Да',
        sl: 'Da',
        mk: 'Да',
        be: 'Так',
        bs: 'Da',
        hsb: 'Haj',
      }),
      no: t({
        ru: 'Нет',
        en: 'No',
        kk: 'Жоқ',
        de: 'Nein',
        fr: 'Non',
        es: 'No',
        pt: 'Não',
        tr: 'Hayır',
        uk: 'Ні',
        zh: '否',
        ar: 'لا',
        pl: 'Nie',
        it: 'No',
        sk: 'Nie',
        ja: 'いいえ',
        ko: '아니오',
        hi: 'नहीं',
        nl: 'Nee',
        sv: 'Nej',
        vi: 'Không',
        id: 'Tidak',
        da: 'Nej',
        nb: 'Nei',
        nn: 'Nei',
        fi: 'Ei',
        is: 'Nei',
        fo: 'Nei',
        cs: 'Ne',
        bg: 'Не',
        hr: 'Ne',
        sr: 'Не',
        sl: 'Ne',
        mk: 'Не',
        be: 'Не',
        bs: 'Ne',
        hsb: 'Ně',
      }),
      forever: t({
        ru: 'Бессрочно',
        en: 'Forever',
        kk: 'Мерзімсіз',
        de: 'Unbegrenzt',
        fr: 'Pour toujours',
        es: 'Sin límite',
        pt: 'Sem prazo',
        tr: 'Süresiz',
        uk: 'Безстроково',
        zh: '永久',
        ar: 'للأبد',
        pl: 'Na zawsze',
        it: 'Per sempre',
        sk: 'Navždy',
        ja: '無期限',
        ko: '영구',
        hi: 'हमेशा के लिए',
        nl: 'Voor altijd',
        sv: 'För alltid',
        vi: 'Mãi mãi',
        id: 'Selamanya',
        da: 'For altid',
        nb: 'For alltid',
        nn: 'For alltid',
        fi: 'Ikuisesti',
        is: 'Að eilífu',
        cs: 'Navždy',
        bg: 'Завинаги',
        hr: 'Zauvijek',
        sr: 'Заувек',
        sl: 'Za vedno',
        mk: 'Засекогаш',
        be: 'Назаўсёды',
        bs: 'Zauvijek',
        hsb: 'Na přeco',
        fo: 'Altíð',
      }),
    },
    tooltips: {
      edit: t({
        ru: 'Редактировать',
        en: 'Edit',
        kk: 'Өзгерту',
        de: 'Bearbeiten',
        fr: 'Modifier',
        es: 'Editar',
        pt: 'Editar',
        tr: 'Düzenle',
        uk: 'Редагувати',
        zh: '编辑',
        ar: 'تعديل',
        pl: 'Edytuj',
        it: 'Modifica',
        sk: 'Upraviť',
        ja: '編集',
        ko: '편집',
        hi: 'संपादित करें',
        nl: 'Bewerken',
        sv: 'Redigera',
        vi: 'Chỉnh sửa',
        id: 'Sunting',
        da: 'Redigér',
        nb: 'Rediger',
        nn: 'Rediger',
        fi: 'Muokkaa',
        is: 'Breyta',
        fo: 'Broyt',
        cs: 'Upravit',
        bg: 'Редактирай',
        hr: 'Uredi',
        sr: 'Уреди',
        sl: 'Uredi',
        mk: 'Уреди',
        be: 'Рэдагаваць',
        bs: 'Uredi',
        hsb: 'Wobdźěłać',
      }),
      revoke: t({
        ru: 'Отозвать',
        en: 'Revoke',
        kk: 'Қайтарып алу',
        de: 'Widerrufen',
        fr: 'Révoquer',
        es: 'Revocar',
        pt: 'Revogar',
        tr: 'İptal et',
        uk: 'Відкликати',
        zh: '撤销',
        ar: 'إلغاء',
        pl: 'Odwołaj',
        it: 'Revoca',
        sk: 'Odobrať',
        ja: '取り消す',
        ko: '취소',
        hi: 'रद्द करें',
        nl: 'Intrekken',
        sv: 'Återkalla',
        vi: 'Thu hồi',
        id: 'Cabut',
        da: 'Tilbagekald',
        nb: 'Opphev',
        nn: 'Oppheve',
        fi: 'Mitätöi',
        is: 'Afturkalla',
        fo: 'Tak aftur',
        cs: 'Zneplatnit',
        bg: 'Отнемане',
        hr: 'Opozovi',
        sr: 'Опозови',
        sl: 'Prekliči',
        mk: 'Отповикај',
        be: 'Адклікаць',
        bs: 'Opozovi',
        hsb: 'Wotwołać',
      }),
    },
    permission: {
      owner: t({
        ru: 'Владелец',
        en: 'Owner',
        kk: 'Иесі',
        de: 'Eigentümer',
        fr: 'Propriétaire',
        es: 'Propietario',
        pt: 'Proprietário',
        tr: 'Sahip',
        uk: 'Власник',
        zh: '所有者',
        ar: 'المالك',
        pl: 'Właściciel',
        it: 'Proprietario',
        sk: 'Vlastník',
        ja: '所有者',
        ko: '소유자',
        hi: 'स्वामी',
        nl: 'Eigenaar',
        sv: 'Ägare',
        vi: 'Chủ sở hữu',
        id: 'Pemilik',
        da: 'Ejer',
        nb: 'Eier',
        nn: 'Eigar',
        fi: 'Omistaja',
        is: 'Eigandi',
        fo: 'Eigari',
        cs: 'Vlastník',
        bg: 'Собственик',
        hr: 'Vlasnik',
        sr: 'Власник',
        sl: 'Lastnik',
        mk: 'Сопственик',
        be: 'Уладальнік',
        bs: 'Vlasnik',
        hsb: 'Wobsedźer',
      }),
      editor: t({
        ru: 'Редактор',
        en: 'Editor',
        kk: 'Өңдеуші',
        de: 'Bearbeiter',
        fr: 'Éditeur',
        es: 'Redactor',
        pt: 'Editor',
        tr: 'Düzenleyici',
        uk: 'Редактор',
        zh: '编辑者',
        ar: 'المحرر',
        pl: 'Edytor',
        it: 'Editore',
        sk: 'Editor',
        ja: '編集者',
        ko: '편집자',
        hi: 'संपादक',
        nl: 'Bewerker',
        sv: 'Redigerare',
        vi: 'Người chỉnh sửa',
        id: 'Penyunting',
        da: 'Redaktør',
        nb: 'Redaktør',
        nn: 'Redaktør',
        fi: 'Muokkaaja',
        is: 'Breytandi',
        fo: 'Rættari',
        cs: 'Editor',
        bg: 'Редактор',
        hr: 'Urednik',
        sr: 'Уредник',
        sl: 'Urejevalec',
        mk: 'Уредник',
        be: 'Рэдактар',
        bs: 'Urednik',
        hsb: 'Redaktor',
      }),
      viewer: t({
        ru: 'Просмотр',
        en: 'Viewer',
        kk: 'Қараушы',
        de: 'Betrachter',
        fr: 'Lecteur',
        es: 'Lector',
        pt: 'Visualizador',
        tr: 'Görüntüleyici',
        uk: 'Перегляд',
        zh: '查看者',
        ar: 'عارض',
        pl: 'Przeglądający',
        it: 'Visualizzatore',
        sk: 'Čitateľ',
        ja: '閲覧者',
        ko: '뷰어',
        hi: 'दर्शक',
        nl: 'Kijker',
        sv: 'Läsare',
        vi: 'Người xem',
        id: 'Penampil',
        da: 'Læser',
        nb: 'Leser',
        nn: 'Lesar',
        fi: 'Katsoja',
        is: 'Lesandi',
        fo: 'Lesari',
        cs: 'Čtenář',
        bg: 'Четец',
        hr: 'Čitatelj',
        sr: 'Читач',
        sl: 'Bralec',
        mk: 'Читач',
        be: 'Чытач',
        bs: 'Čitalac',
        hsb: 'Čitar',
      }),
      downloader: t({
        ru: 'Скачивание',
        en: 'Download',
        kk: 'Жүктеу',
        de: 'Herunterladen',
        fr: 'Téléchargement',
        es: 'Descarga',
        pt: 'Baixar',
        tr: 'İndirme',
        uk: 'Завантаження',
        zh: '下载',
        ar: 'تنزيل',
        pl: 'Pobieranie',
        it: 'Scarica',
        sk: 'Sťahovanie',
        ja: 'ダウンロード',
        ko: '다운로드',
        hi: 'डाउनलोड',
        nl: 'Downloaden',
        sv: 'Nedladdning',
        vi: 'Tải xuống',
        id: 'Unduhan',
        da: 'Download',
        nb: 'Last ned',
        nn: 'Last ned',
        fi: 'Lataa',
        is: 'Hlaða niður',
        fo: 'Tak niður',
        cs: 'Stáhnout',
        bg: 'Изтегли',
        hr: 'Preuzmi',
        sr: 'Преузми',
        sl: 'Prenesi',
        mk: 'Симни',
        be: 'Спампаваць',
        bs: 'Preuzmi',
        hsb: 'Sćahnyć',
      }),
      editorLong: t({
        ru: 'Редактирование',
        en: 'Editing',
        kk: 'Өңдеу',
        de: 'Bearbeitung',
        fr: 'Édition',
        es: 'Edición',
        pt: 'Edição',
        tr: 'Düzenleme',
        uk: 'Редагування',
        zh: '编辑',
        ar: 'التحرير',
        pl: 'Edycja',
        it: 'Modifica',
        sk: 'Úpravy',
        ja: '編集',
        ko: '편집',
        hi: 'संपादन',
        nl: 'Bewerken',
        sv: 'Redigering',
        vi: 'Chỉnh sửa',
        id: 'Pengeditan',
        da: 'Redigering',
        nb: 'Redigering',
        nn: 'Redigering',
        fi: 'Muokkaus',
        is: 'Breyting',
        cs: 'Úpravy',
        bg: 'Редактиране',
        hr: 'Uređivanje',
        sr: 'Уређивање',
        sl: 'Urejanje',
        mk: 'Уредување',
        be: 'Рэдагаванне',
        bs: 'Uređivanje',
        hsb: 'Wobdźěłowanje',
        fo: 'Rætting',
      }),
      viewDownloadLong: t({
        ru: 'Просмотр и скачивание',
        en: 'View and download',
        kk: 'Қарау және жүктеу',
        de: 'Ansehen und herunterladen',
        fr: 'Voir et télécharger',
        es: 'Ver y descargar',
        pt: 'Visualizar e baixar',
        tr: 'Görüntüle ve indir',
        uk: 'Перегляд і завантаження',
        zh: '查看和下载',
        ar: 'عرض وتنزيل',
        pl: 'Przeglądaj i pobieraj',
        it: 'Visualizza e scarica',
        sk: 'Zobrazenie a sťahovanie',
        ja: '表示とダウンロード',
        ko: '보기 및 다운로드',
        hi: 'देखें और डाउनलोड करें',
        nl: 'Bekijken en downloaden',
        sv: 'Visa och ladda ner',
        vi: 'Xem và tải xuống',
        id: 'Lihat dan unduh',
        da: 'Se og hent',
        nb: 'Se og last ned',
        nn: 'Sjå og last ned',
        fi: 'Katselu ja lataus',
        is: 'Skoða og hala niður',
        fo: 'Sí og tak niður',
        cs: 'Zobrazení a stažení',
        bg: 'Преглед и изтегляне',
        hr: 'Pregled i preuzimanje',
        sr: 'Преглед и преузимање',
        sl: 'Ogled in prenos',
        mk: 'Приказ и преземање',
        be: 'Прагляд і спампоўка',
        bs: 'Pregled i preuzimanje',
        hsb: 'Pokazać a sćahnyć',
      }),
      default: t({
        ru: 'Права',
        en: 'Permissions',
        kk: 'Құқықтар',
        de: 'Berechtigungen',
        fr: 'Autorisations',
        es: 'Permisos',
        pt: 'Permissões',
        tr: 'İzinler',
        uk: 'Права',
        zh: '权限',
        ar: 'الأذونات',
        pl: 'Uprawnienia',
        it: 'Autorizzazioni',
        sk: 'Oprávnenia',
        ja: '権限',
        ko: '권한',
        hi: 'अनुमतियां',
        nl: 'Machtigingen',
        sv: 'Behörigheter',
        vi: 'Quyền',
        id: 'Izin',
        da: 'Tilladelser',
        nb: 'Tillatelser',
        nn: 'Løyve',
        fi: 'Käyttöoikeudet',
        is: 'Heimildir',
        fo: 'Loyvi',
        cs: 'Oprávnění',
        bg: 'Права',
        hr: 'Dopuštenja',
        sr: 'Дозволе',
        sl: 'Dovoljenja',
        mk: 'Дозволи',
        be: 'Дазволы',
        bs: 'Dozvole',
        hsb: 'Prawa',
      }),
    },
    dialogs: {
      grantTitle: t({
        ru: 'Предоставить доступ',
        en: 'Grant access',
        kk: 'Қолжетімділік беру',
        de: 'Zugriff gewähren',
        fr: "Accorder l'accès",
        es: 'Conceder acceso',
        pt: 'Conceder acesso',
        tr: 'Erişim ver',
        uk: 'Надати доступ',
        zh: '授予访问权限',
        ar: 'منح الوصول',
        pl: 'Przyznaj dostęp',
        it: 'Concedi accesso',
        sk: 'Udeliť prístup',
        ja: 'アクセスを許可',
        ko: '접근 권한 부여',
        hi: 'पहुंच प्रदान करें',
        nl: 'Toegang verlenen',
        sv: 'Bevilja åtkomst',
        vi: 'Cấp quyền truy cập',
        id: 'Berikan akses',
        da: 'Giv adgang',
        nb: 'Gi tilgang',
        nn: 'Gje tilgang',
        fi: 'Myönnä oikeus',
        is: 'Veita aðgang',
        cs: 'Udělit přístup',
        bg: 'Предоставяне на достъп',
        hr: 'Dodijeli pristup',
        sr: 'Додели приступ',
        sl: 'Dodeli dostop',
        mk: 'Додели пристап',
        be: 'Даць доступ',
        bs: 'Dodijeli pristup',
        hsb: 'Přistup dać',
        fo: 'Veit atgongd',
      }),
      editTitle: t({
        ru: 'Редактировать права доступа',
        en: 'Edit permissions',
        kk: 'Қолжетімділік құқықтарын өзгерту',
        de: 'Berechtigungen bearbeiten',
        fr: 'Modifier les autorisations',
        es: 'Editar permisos',
        pt: 'Editar permissões',
        tr: 'İzinleri düzenle',
        uk: 'Редагувати права доступу',
        zh: '编辑权限',
        ar: 'تعديل الأذونات',
        pl: 'Edytuj uprawnienia',
        it: 'Modifica autorizzazioni',
        sk: 'Upraviť oprávnenia',
        ja: '権限を編集',
        ko: '권한 편집',
        hi: 'अनुमतियां संपादित करें',
        nl: 'Machtigingen bewerken',
        sv: 'Redigera behörigheter',
        vi: 'Chỉnh sửa quyền',
        id: 'Edit izin',
        da: 'Redigér tilladelser',
        nb: 'Rediger tillatelser',
        nn: 'Rediger løyve',
        fi: 'Muokkaa oikeuksia',
        is: 'Breyta heimildum',
        cs: 'Upravit oprávnění',
        bg: 'Редактиране на правата',
        hr: 'Uredi dopuštenja',
        sr: 'Уреди дозволе',
        sl: 'Uredi dovoljenja',
        mk: 'Уреди дозволи',
        be: 'Рэдагаваць дазволы',
        bs: 'Uredi dozvole',
        hsb: 'Dowolnosće wobdźěłać',
        fo: 'Rætta loyvi',
      }),
      userIdOrEmail: t({
        ru: 'Email или ID пользователя',
        en: 'User email or ID',
        kk: 'Пайдаланушы email немесе ID',
        de: 'Benutzer-E-Mail oder ID',
        fr: "E-mail ou ID de l'utilisateur",
        es: 'Email o ID del usuario',
        pt: 'E-mail ou ID do usuário',
        tr: 'Kullanıcı e-postası veya ID',
        uk: 'Email або ID користувача',
        zh: '用户邮箱或ID',
        ar: 'البريد الإلكتروني أو معرف المستخدم',
        pl: 'E-mail lub ID użytkownika',
        it: 'Email o ID utente',
        sk: 'Email alebo ID používateľa',
        ja: 'ユーザーのメールまたはID',
        ko: '사용자 이메일 또는 ID',
        hi: 'उपयोगकर्ता ईमेल या आईडी',
        nl: 'Gebruikers-e-mail of ID',
        sv: 'Användarens e-post eller ID',
        vi: 'Email hoặc ID người dùng',
        id: 'Email atau ID pengguna',
        da: 'Brugerens e-mail eller ID',
        nb: 'Brukerens e-post eller ID',
        nn: 'Brukaren sin e-post eller ID',
        fi: 'Käyttäjän sähköposti tai tunnus',
        is: 'Tölvupóstur eða kenni notanda',
        cs: 'E-mail nebo ID uživatele',
        bg: 'Имейл или идентификатор на потребителя',
        hr: 'E-pošta ili ID korisnika',
        sr: 'Е-пошта или ИД корисника',
        sl: 'E-pošta ali ID uporabnika',
        mk: 'Е-пошта или ИД на корисникот',
        be: 'Электронная пошта або ID карыстальніка',
        bs: 'E-pošta ili ID korisnika',
        hsb: 'E-mejl abo ID wužiwarja',
        fo: 'Teldupostur ella ID hjá brúkaranum',
      }),
      userIdOrEmailHelp: t({
        ru: 'Введите email пользователя, которому хотите предоставить доступ',
        en: 'Enter the email of the user you want to grant access to',
        kk: 'Қолжетімділік бергіңіз келетін пайдаланушының email енгізіңіз',
        de: 'Geben Sie die E-Mail des Benutzers ein, dem Sie Zugriff gewähren möchten',
        fr: "Entrez l'e-mail de l'utilisateur auquel vous souhaitez accorder l'accès",
        es: 'Ingrese el email del usuario al que desea conceder acceso',
        pt: 'Digite o e-mail do usuário ao qual deseja conceder acesso',
        tr: 'Erişim vermek istediğiniz kullanıcının e-postasını girin',
        uk: 'Введіть email користувача, якому хочете надати доступ',
        zh: '输入您要授予访问权限的用户的邮箱',
        ar: 'أدخل البريد الإلكتروني للمستخدم الذي تريد منحه الوصول',
        pl: 'Wprowadź e-mail użytkownika, któremu chcesz przyznać dostęp',
        it: "Inserisci l'email dell'utente a cui vuoi concedere l'accesso",
        sk: 'Zadajte email používateľa, ktorému chcete udeliť prístup',
        ja: 'アクセスを許可するユーザーのメールを入力してください',
        ko: '접근 권한을 부여할 사용자의 이메일을 입력하세요',
        hi: 'उस उपयोगकर्ता का ईमेल दर्ज करें जिसे आप पहुंच देना चाहते हैं',
        nl: 'Voer het e-mailadres in van de gebruiker aan wie u toegang wilt verlenen',
        sv: 'Ange e-postadressen till den användare du vill bevilja åtkomst',
        vi: 'Nhập email của người dùng bạn muốn cấp quyền truy cập',
        id: 'Masukkan email pengguna yang ingin Anda beri akses',
        da: 'Indtast e-mailen på den bruger, du vil give adgang',
        nb: 'Skriv inn e-posten til brukeren du vil gi tilgang',
        nn: 'Skriv inn e-posten til brukaren du vil gje tilgang',
        fi: 'Anna sen käyttäjän sähköposti, jolle haluat myöntää oikeuden',
        is: 'Sláðu inn tölvupóst notandans sem þú vilt veita aðgang',
        cs: 'Zadejte e-mail uživatele, kterému chcete udělit přístup',
        bg: 'Въведете имейла на потребителя, на когото искате да дадете достъп',
        hr: 'Unesite e-poštu korisnika kojem želite dodijeliti pristup',
        sr: 'Унесите е-пошту корисника коме желите да доделите приступ',
        sl: 'Vnesite e-pošto uporabnika, ki mu želite dodeliti dostop',
        mk: 'Внесете ја е-поштата на корисникот на кој сакате да му доделите пристап',
        be: 'Увядзіце электронную пошту карыстальніка, якому хочаце даць доступ',
        bs: 'Unesite e-poštu korisnika kojem želite dodijeliti pristup',
        hsb: 'Zapodajće e-mejl wužiwarja, komuž chceće přistup dać',
        fo: 'Skriva teldupostin hjá brúkaranum, sum tú vilt veita atgongd',
      }),
      accessLevel: t({
        ru: 'Уровень доступа',
        en: 'Access level',
        kk: 'Қолжетімділік деңгейі',
        de: 'Zugriffsstufe',
        fr: "Niveau d'accès",
        es: 'Nivel de acceso',
        pt: 'Nível de acesso',
        tr: 'Erişim seviyesi',
        uk: 'Рівень доступу',
        zh: '访问级别',
        ar: 'مستوى الوصول',
        pl: 'Poziom dostępu',
        it: 'Livello di accesso',
        sk: 'Úroveň prístupu',
        ja: 'アクセスレベル',
        ko: '접근 수준',
        hi: 'पहुंच स्तर',
        nl: 'Toegangsniveau',
        sv: 'Åtkomstnivå',
        vi: 'Mức truy cập',
        id: 'Tingkat akses',
        da: 'Adgangsniveau',
        nb: 'Tilgangsnivå',
        nn: 'Tilgangsnivå',
        fi: 'Käyttöoikeuden taso',
        is: 'Aðgangsstig',
        cs: 'Úroveň přístupu',
        bg: 'Ниво на достъп',
        hr: 'Razina pristupa',
        sr: 'Ниво приступа',
        sl: 'Raven dostopa',
        mk: 'Ниво на пристап',
        be: 'Узровень доступу',
        bs: 'Nivo pristupa',
        hsb: 'Runina přistupa',
        fo: 'Atgongustøði',
      }),
      expiresAt: t({
        ru: 'Срок действия (опционально)',
        en: 'Expiration (optional)',
        kk: 'Жарамдылық мерзімі (міндетті емес)',
        de: 'Ablaufdatum (optional)',
        fr: 'Expiration (facultatif)',
        es: 'Vencimiento (opcional)',
        pt: 'Expiração (opcional)',
        tr: 'Son kullanma tarihi (isteğe bağlı)',
        uk: "Термін дії (необов'язково)",
        zh: '到期时间（可选）',
        ar: 'تاريخ الانتهاء (اختياري)',
        pl: 'Data wygaśnięcia (opcjonalnie)',
        it: 'Scadenza (opzionale)',
        sk: 'Platnosť (voliteľné)',
        ja: '有効期限（任意）',
        ko: '만료일 (선택)',
        hi: 'समाप्ति तिथि (वैकल्पिक)',
        nl: 'Vervaldatum (optioneel)',
        sv: 'Utgångsdatum (valfritt)',
        vi: 'Ngày hết hạn (tùy chọn)',
        id: 'Tanggal kedaluwarsa (opsional)',
        da: 'Udløb (valgfrit)',
        nb: 'Utløp (valgfritt)',
        nn: 'Utløp (valfritt)',
        fi: 'Vanheneminen (valinnainen)',
        is: 'Gildistími (valfrjáls)',
        cs: 'Platnost (volitelné)',
        bg: 'Изтичане (по избор)',
        hr: 'Istek (neobavezno)',
        sr: 'Истек (необавезно)',
        sl: 'Veljavnost (izbirno)',
        mk: 'Истекување (изборно)',
        be: 'Тэрмін дзеяння (неабавязкова)',
        bs: 'Istek (opcionalno)',
        hsb: 'Spadnjenje (opcionalnje)',
        fo: 'Útlop (valfrítt)',
      }),
      expiresAtHelp: t({
        ru: 'Оставьте пустым для бессрочного доступа',
        en: 'Leave empty for no expiration',
        kk: 'Мерзімсіз қолжетімділік үшін бос қалдырыңыз',
        de: 'Leer lassen für unbegrenzte Gültigkeit',
        fr: 'Laisser vide pour une durée illimitée',
        es: 'Dejar en blanco para acceso sin límite',
        pt: 'Deixe em branco para acesso sem prazo',
        tr: 'Süresiz erişim için boş bırakın',
        uk: 'Залиште порожнім для безстрокового доступу',
        zh: '留空则永不过期',
        ar: 'اتركه فارغاً للوصول غير المحدود',
        pl: 'Pozostaw puste dla nieograniczonego dostępu',
        it: 'Lascia vuoto per accesso senza scadenza',
        sk: 'Ponechajte prázdne pre neobmedzenú platnosť',
        ja: '期限なしの場合は空白のままにしてください',
        ko: '만료 없음은 비워두세요',
        hi: 'बिना समाप्ति के पहुंच के लिए खाली छोड़ें',
        nl: 'Leeg laten voor geen vervaldatum',
        sv: 'Lämna tomt för ingen utgångstid',
        vi: 'Để trống để không có hạn',
        id: 'Biarkan kosong untuk tanpa kedaluwarsa',
        da: 'Lad feltet være tomt for ingen udløb',
        nb: 'La feltet stå tomt for ingen utløp',
        nn: 'Lat feltet stå tomt for ingen utløp',
        fi: 'Jätä tyhjäksi, niin oikeus ei vanhene',
        is: 'Skildu eftir tómt fyrir engan gildistíma',
        cs: 'Nechte prázdné, pokud nemá vypršet',
        bg: 'Оставете празно, за да не изтича',
        hr: 'Ostavite prazno ako ne treba isteći',
        sr: 'Оставите празно ако не треба да истекне',
        sl: 'Pustite prazno, če naj ne poteče',
        mk: 'Оставете празно ако не треба да истече',
        be: 'Пакіньце пустым, калі не павінен сканчацца',
        bs: 'Ostavite prazno ako ne treba isteći',
        hsb: 'Wostajće prózdne, jeli njeměło spadnyć',
        fo: 'Lat teigin vera tóman fyri einki útlop',
      }),
      reshare: t({
        ru: 'Разрешить делиться с другими',
        en: 'Allow sharing with others',
        kk: 'Басқалармен бөлісуге рұқсат беру',
        de: 'Teilen mit anderen erlauben',
        fr: "Autoriser le partage avec d'autres",
        es: 'Permitir compartir con otros',
        pt: 'Permitir compartilhamento com outros',
        tr: 'Diğerleriyle paylaşmaya izin ver',
        uk: 'Дозволити ділитися з іншими',
        zh: '允许与他人共享',
        ar: 'السماح بالمشاركة مع الآخرين',
        pl: 'Zezwól na udostępnianie innym',
        it: 'Consenti la condivisione con altri',
        sk: 'Povoliť zdieľanie s ďalšími',
        ja: '他のユーザーとの共有を許可',
        ko: '다른 사람과 공유 허용',
        hi: 'दूसरों के साथ साझा करने की अनुमति दें',
        nl: 'Delen met anderen toestaan',
        sv: 'Tillåt delning med andra',
        vi: 'Cho phép chia sẻ với người khác',
        id: 'Izinkan berbagi dengan orang lain',
        da: 'Tillad deling med andre',
        nb: 'Tillat deling med andre',
        nn: 'Tillat deling med andre',
        fi: 'Salli jakaminen muille',
        is: 'Leyfa deilingu með öðrum',
        cs: 'Povolit sdílení s dalšími',
        bg: 'Разрешаване на споделяне с други',
        hr: 'Dopusti dijeljenje s drugima',
        sr: 'Дозволи дељење са другима',
        sl: 'Dovoli deljenje z drugimi',
        mk: 'Дозволи споделување со други',
        be: 'Дазволіць дзяліцца з іншымі',
        bs: 'Dozvoli dijeljenje s drugima',
        hsb: 'Dowolić dźělenje z druhimi',
        fo: 'Loyv deiling við øðrum',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Zrušiť',
        ja: 'キャンセル',
        ko: '취소',
        hi: 'रद्द करें',
        nl: 'Annuleren',
        sv: 'Avbryt',
        vi: 'Hủy',
        id: 'Batal',
        da: 'Annuller',
        nb: 'Avbryt',
        nn: 'Avbryt',
        fi: 'Peruuta',
        is: 'Hætta',
        fo: 'Avbrót',
        cs: 'Zrušit',
        bg: 'Отказ',
        hr: 'Odustani',
        sr: 'Откажи',
        sl: 'Prekliči',
        mk: 'Откажи',
        be: 'Скасаваць',
        bs: 'Otkaži',
        hsb: 'Přetorhnyć',
      }),
      save: t({
        ru: 'Сохранить',
        en: 'Save',
        kk: 'Сақтау',
        de: 'Speichern',
        fr: 'Enregistrer',
        es: 'Guardar',
        pt: 'Salvar',
        tr: 'Kaydet',
        uk: 'Зберегти',
        zh: '保存',
        ar: 'حفظ',
        pl: 'Zapisz',
        it: 'Salva',
        sk: 'Uložiť',
        ja: '保存',
        ko: '저장',
        hi: 'सहेजें',
        nl: 'Opslaan',
        sv: 'Spara',
        vi: 'Lưu',
        id: 'Simpan',
        da: 'Gem',
        nb: 'Lagre',
        nn: 'Lagre',
        fi: 'Tallenna',
        is: 'Vista',
        fo: 'Goym',
        cs: 'Uložit',
        bg: 'Запази',
        hr: 'Spremi',
        sr: 'Сачувај',
        sl: 'Shrani',
        mk: 'Зачувај',
        be: 'Захаваць',
        bs: 'Sačuvaj',
        hsb: 'Składować',
      }),
      grant: t({
        ru: 'Предоставить доступ',
        en: 'Grant access',
        kk: 'Қолжетімділік беру',
        de: 'Zugriff gewähren',
        fr: "Accorder l'accès",
        es: 'Conceder acceso',
        pt: 'Conceder acesso',
        tr: 'Erişim ver',
        uk: 'Надати доступ',
        zh: '授予访问权限',
        ar: 'منح الوصول',
        pl: 'Przyznaj dostęp',
        it: 'Concedi accesso',
        sk: 'Udeliť prístup',
        ja: 'アクセスを許可',
        ko: '접근 권한 부여',
        hi: 'पहुंच प्रदान करें',
        nl: 'Toegang verlenen',
        sv: 'Bevilja åtkomst',
        vi: 'Cấp quyền truy cập',
        id: 'Berikan akses',
        da: 'Giv adgang',
        nb: 'Gi tilgang',
        nn: 'Gje tilgang',
        fi: 'Myönnä oikeus',
        is: 'Veita aðgang',
        cs: 'Udělit přístup',
        bg: 'Предоставяне на достъп',
        hr: 'Dodijeli pristup',
        sr: 'Додели приступ',
        sl: 'Dodeli dostop',
        mk: 'Додели пристап',
        be: 'Даць доступ',
        bs: 'Dodijeli pristup',
        hsb: 'Přistup dać',
        fo: 'Veit atgongd',
      }),
    },
  },
} satisfies Dictionary;

export default content;
