import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionDocumentViewer',
  content: {
    bankNotDetected: t({
      ru: 'Банк не определен',
      en: 'Bank not detected',
      kk: 'Банк анықталмаған',
      de: 'Bank nicht erkannt',
      fr: 'Banque non détectée',
      es: 'Banco no detectado',
      pt: 'Banco não detectado',
      tr: 'Banka tespit edilemedi',
      uk: 'Банк не визначено',
      zh: '未检测到银行',
      pl: 'Nie wykryto banku',
      it: 'Banca non rilevata',
      sk: 'Banka nebola rozpoznaná',
      ja: '銀行が検出されませんでした',
      ko: '은행이 감지되지 않았습니다',
      hi: 'बैंक नहीं पहचाना गया',
      nl: 'Bank niet gedetecteerd',
      sv: 'Banken kunde inte identifieras',
      vi: 'Không phát hiện được ngân hàng',
      id: 'Bank tidak terdeteksi',
      da: 'Banken blev ikke registreret',
      nb: 'Banken ble ikke gjenkjent',
      nn: 'Banken vart ikkje attkjend',
      fi: 'Pankkia ei tunnistettu',
      is: 'Banki greindist ekki',
      fo: 'Bankin varð ikki kendur',
      cs: 'Banka nebyla rozpoznána',
      bg: 'Банката не беше разпозната',
      hr: 'Banka nije prepoznana',
      sr: 'Банка није препозната',
      sl: 'Banka ni bila prepoznana',
      mk: 'Банката не беше препознаена',
      be: 'Банк не распазнаны',
      bs: 'Banka nije prepoznana',
      hsb: 'Banka njeje so spóznała',
    }),
    bankStatement: t({
      ru: 'Банковская выписка',
      en: 'Bank statement',
      kk: 'Банк үзіндісі',
      de: 'Kontoauszug',
      fr: 'Relevé bancaire',
      es: 'Extracto bancario',
      pt: 'Extrato bancário',
      tr: 'Banka ekstresi',
      uk: 'Банківська виписка',
      zh: '银行对账单',
      pl: 'Wyciąg bankowy',
      it: 'Estratto conto bancario',
      sk: 'Bankový výpis',
      ja: '銀行明細書',
      ko: '은행 명세서',
      hi: 'बैंक विवरण',
      nl: 'Bankafschrift',
      sv: 'Kontoutdrag',
      vi: 'Sao kê ngân hàng',
      id: 'Laporan bank',
      da: 'Kontoudtog',
      nb: 'Kontoutskrift',
      nn: 'Kontoutskrift',
      fi: 'Tiliote',
      is: 'Bankayfirlit',
      fo: 'Kontoyvirlit',
      cs: 'Bankovní výpis',
      bg: 'Банково извлечение',
      hr: 'Bankovni izvod',
      sr: 'Банковни извод',
      sl: 'Bančni izpisek',
      mk: 'Банкарски извадок',
      be: 'Банкаўская выпіска',
      bs: 'Bankovni izvod',
      hsb: 'Bankowy wupis',
    }),
    accountNumber: t({
      ru: 'Номер счета',
      en: 'Account number',
      kk: 'Есепшот нөмірі',
      de: 'Kontonummer',
      fr: 'Numéro de compte',
      es: 'Número de cuenta',
      pt: 'Número da conta',
      tr: 'Hesap numarası',
      uk: 'Номер рахунку',
      zh: '账号',
      pl: 'Numer konta',
      it: 'Numero di conto',
      sk: 'Číslo účtu',
      ja: '口座番号',
      ko: '계좌 번호',
      hi: 'खाता संख्या',
      nl: 'Rekeningnummer',
      sv: 'Kontonummer',
      vi: 'Số tài khoản',
      id: 'Nomor rekening',
      da: 'Kontonummer',
      nb: 'Kontonummer',
      nn: 'Kontonummer',
      fi: 'Tilinumero',
      is: 'Reikningsnúmer',
      fo: 'Kontunummar',
      cs: 'Číslo účtu',
      bg: 'Номер на сметка',
      hr: 'Broj računa',
      sr: 'Број рачуна',
      sl: 'Številka računa',
      mk: 'Број на сметка',
      be: 'Нумар рахунка',
      bs: 'Broj računa',
      hsb: 'Čisło konta',
    }),
    statementPeriod: t({
      ru: 'Период выписки',
      en: 'Statement period',
      kk: 'Үзінді кезеңі',
      de: 'Auszugszeitraum',
      fr: 'Période du relevé',
      es: 'Período del extracto',
      pt: 'Período do extrato',
      tr: 'Ekstre dönemi',
      uk: 'Період виписки',
      zh: '账单周期',
      pl: 'Okres wyciągu',
      it: 'Periodo del estratto',
      sk: 'Obdobie výpisu',
      ja: '明細期間',
      ko: '명세서 기간',
      hi: 'विवरण अवधि',
      nl: 'Overzichtperiode',
      sv: 'Kontoutdragsperiod',
      vi: 'Kỳ sao kê',
      id: 'Periode laporan',
      da: 'Kontoudtogets periode',
      nb: 'Kontoutskriftens periode',
      nn: 'Perioden til kontoutskrifta',
      fi: 'Tiliotteen jakso',
      is: 'Tímabil yfirlits',
      fo: 'Tíðarskeið hjá kontoyvirlitinum',
      cs: 'Období výpisu',
      bg: 'Период на извлечението',
      hr: 'Razdoblje izvoda',
      sr: 'Период извода',
      sl: 'Obdobje izpiska',
      mk: 'Период на извадокот',
      be: 'Перыяд выпіскі',
      bs: 'Period izvoda',
      hsb: 'Doba wupisa',
    }),
    statementFile: t({
      ru: 'Файл выписки',
      en: 'Statement file',
      kk: 'Үзінді файлы',
      de: 'Auszugsdatei',
      fr: 'Fichier de relevé',
      es: 'Archivo de extracto',
      pt: 'Arquivo de extrato',
      tr: 'Ekstre dosyası',
      uk: 'Файл виписки',
      zh: '账单文件',
      pl: 'Plik wyciągu',
      it: 'File estratto',
      sk: 'Súbor výpisu',
      ja: '明細ファイル',
      ko: '명세서 파일',
      hi: 'विवरण फ़ाइल',
      nl: 'Overzichtbestand',
      sv: 'Kontoutdragsfil',
      vi: 'Tệp sao kê',
      id: 'File laporan',
      da: 'Kontoudtogets fil',
      nb: 'Kontoutskriftens fil',
      nn: 'Fila til kontoutskrifta',
      fi: 'Tiliotetiedosto',
      is: 'Yfirlitsskrá',
      fo: 'Kontoyvirlitsfíla',
      cs: 'Soubor výpisu',
      bg: 'Файл на извлечението',
      hr: 'Datoteka izvoda',
      sr: 'Датотека извода',
      sl: 'Datoteka izpiska',
      mk: 'Податотека на извадокот',
      be: 'Файл выпіскі',
      bs: 'Datoteka izvoda',
      hsb: 'Dataja wupisa',
    }),
    openingBalance: t({
      ru: 'Начальный баланс',
      en: 'Opening balance',
      kk: 'Бастапқы қалдық',
      de: 'Anfangssaldo',
      fr: "Solde d'ouverture",
      es: 'Saldo inicial',
      pt: 'Saldo inicial',
      tr: 'Açılış bakiyesi',
      uk: 'Початковий баланс',
      zh: '期初余额',
      pl: 'Saldo otwarcia',
      it: 'Saldo iniziale',
      sk: 'Počiatočný zostatok',
      ja: '期首残高',
      ko: '기초 잔액',
      hi: 'प्रारंभिक शेष',
      nl: 'Beginsaldo',
      sv: 'Ingående saldo',
      vi: 'Số dư đầu kỳ',
      id: 'Saldo awal',
      da: 'Åbningsbalance',
      nb: 'Åpningsbalanse',
      nn: 'Opningsbalanse',
      fi: 'Alkusaldo',
      is: 'Upphafsstaða',
      fo: 'Byrjanarstøða',
      cs: 'Počáteční stav',
      bg: 'Начално салдо',
      hr: 'Početno stanje',
      sr: 'Почетно стање',
      sl: 'Začetno stanje',
      mk: 'Почетно салдо',
      be: 'Пачатковае сальда',
      bs: 'Početno stanje',
      hsb: 'Započatkowy staw',
    }),
    income: t({
      ru: 'Поступления',
      en: 'Income',
      kk: 'Кіріс',
      de: 'Einnahmen',
      fr: 'Revenus',
      es: 'Ingresos',
      pt: 'Receitas',
      tr: 'Gelir',
      uk: 'Надходження',
      zh: '收入',
      pl: 'Przychody',
      it: 'Entrate',
      sk: 'Príjmy',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomsten',
      sv: 'Inkomst',
      vi: 'Thu nhập',
      id: 'Pendapatan',
      da: 'Indtægt',
      nb: 'Inntekt',
      nn: 'Inntekt',
      fi: 'Tulo',
      is: 'Tekjur',
      fo: 'Inntøka',
      cs: 'Příjem',
      bg: 'Приход',
      hr: 'Prihod',
      sr: 'Приход',
      sl: 'Prihodek',
      mk: 'Приход',
      be: 'Прыбытак',
      bs: 'Prihod',
      hsb: 'Dochod',
    }),
    expenses: t({
      ru: 'Списания',
      en: 'Expenses',
      kk: 'Шығыс',
      de: 'Ausgaben',
      fr: 'Dépenses',
      es: 'Gastos',
      pt: 'Despesas',
      tr: 'Giderler',
      uk: 'Списання',
      zh: '支出',
      pl: 'Wydatki',
      it: 'Spese',
      sk: 'Výdavky',
      ja: '支出',
      ko: '지출',
      hi: 'व्यय',
      nl: 'Uitgaven',
      sv: 'Utgifter',
      vi: 'Chi phí',
      id: 'Pengeluaran',
      da: 'Udgifter',
      nb: 'Kostnader',
      nn: 'Kostnader',
      fi: 'Kulut',
      is: 'Gjöld',
      fo: 'Kostnaðir',
      cs: 'Náklady',
      bg: 'Разходи',
      hr: 'Troškovi',
      sr: 'Трошкови',
      sl: 'Stroški',
      mk: 'Трошоци',
      be: 'Выдаткі',
      bs: 'Troškovi',
      hsb: 'Kóšty',
    }),
    closingBalance: t({
      ru: 'Конечный баланс',
      en: 'Closing balance',
      kk: 'Соңғы қалдық',
      de: 'Schlusssaldo',
      fr: 'Solde de clôture',
      es: 'Saldo final',
      pt: 'Saldo final',
      tr: 'Kapanış bakiyesi',
      uk: 'Кінцевий баланс',
      zh: '期末余额',
      pl: 'Saldo zamknięcia',
      it: 'Saldo finale',
      sk: 'Konečný zostatok',
      ja: '期末残高',
      ko: '기말 잔액',
      hi: 'समापन शेष',
      nl: 'Eindsaldo',
      sv: 'Utgående saldo',
      vi: 'Số dư cuối kỳ',
      id: 'Saldo akhir',
      da: 'Slutsaldo',
      nb: 'Sluttsaldo',
      nn: 'Sluttsaldo',
      fi: 'Loppusaldo',
      is: 'Lokastaða',
      fo: 'Endastøða',
      cs: 'Konečný zůstatek',
      bg: 'Крайно салдо',
      hr: 'Završno stanje',
      sr: 'Завршно стање',
      sl: 'Končno stanje',
      mk: 'Завршно салдо',
      be: 'Канчатковае сальда',
      bs: 'Završno stanje',
      hsb: 'Kónčny staw',
    }),
    balanceChange: t({
      ru: 'Изменение баланса за период',
      en: 'Balance change for the period',
      kk: 'Кезең ішіндегі қалдық өзгерісі',
      de: 'Saldoänderung für den Zeitraum',
      fr: 'Variation du solde sur la période',
      es: 'Cambio de saldo para el período',
      pt: 'Variação de saldo no período',
      tr: 'Dönem bakiye değişimi',
      uk: 'Зміна балансу за період',
      zh: '期间余额变动',
      pl: 'Zmiana salda za okres',
      it: 'Variazione del saldo nel periodo',
      sk: 'Zmena zostatku za obdobie',
      ja: '期間残高変動',
      ko: '기간 잔액 변동',
      hi: 'अवधि के लिए शेष परिवर्तन',
      nl: 'Saldowijziging voor de periode',
      sv: 'Saldoändring för perioden',
      vi: 'Thay đổi số dư trong kỳ',
      id: 'Perubahan saldo untuk periode',
      da: 'Ændring i saldo i perioden',
      nb: 'Endring i saldo for perioden',
      nn: 'Endring i saldo for perioden',
      fi: 'Saldon muutos jaksolla',
      is: 'Breyting á stöðu á tímabilinu',
      fo: 'Broyting í støðuni fyri tíðarskeiðið',
      cs: 'Změna zůstatku za období',
      bg: 'Промяна на салдото за периода',
      hr: 'Promjena stanja za razdoblje',
      sr: 'Промена стања за период',
      sl: 'Sprememba stanja v obdobju',
      mk: 'Промена на состојбата за периодот',
      be: 'Змена сальда за перыяд',
      bs: 'Promjena stanja za period',
      hsb: 'Změna salda za dobu',
    }),
    totalTransactions: t({
      ru: 'Всего транзакций',
      en: 'Total transactions',
      kk: 'Барлық транзакциялар',
      de: 'Transaktionen gesamt',
      fr: 'Total des transactions',
      es: 'Total de transacciones',
      pt: 'Total de transações',
      tr: 'Toplam işlem',
      uk: 'Всього транзакцій',
      zh: '交易总数',
      pl: 'Łączna liczba transakcji',
      it: 'Transazioni totali',
      sk: 'Transakcie celkom',
      ja: '総取引数',
      ko: '총 거래',
      hi: 'कुल लेनदेन',
      nl: 'Totale transacties',
      sv: 'Totalt antal transaktioner',
      vi: 'Tổng giao dịch',
      id: 'Total transaksi',
      da: 'Transaktioner i alt',
      nb: 'Transaksjoner totalt',
      nn: 'Transaksjonar totalt',
      fi: 'Tapahtumia yhteensä',
      is: 'Færslur í heild',
      fo: 'Posteringar í alt',
      cs: 'Transakcí celkem',
      bg: 'Общо транзакции',
      hr: 'Ukupno transakcija',
      sr: 'Укупно трансакција',
      sl: 'Transakcij skupaj',
      mk: 'Вкупно трансакции',
      be: 'Усяго транзакцый',
      bs: 'Ukupno transakcija',
      hsb: 'Transakcijow dohromady',
    }),
    transactionList: t({
      ru: 'Список транзакций',
      en: 'Transaction list',
      kk: 'Транзакциялар тізімі',
      de: 'Transaktionsliste',
      fr: 'Liste des transactions',
      es: 'Lista de transacciones',
      pt: 'Lista de transações',
      tr: 'İşlem listesi',
      uk: 'Список транзакцій',
      zh: '交易列表',
      pl: 'Lista transakcji',
      it: 'Elenco transazioni',
      sk: 'Zoznam transakcií',
      ja: '取引一覧',
      ko: '거래 목록',
      hi: 'लेनदेन सूची',
      nl: 'Transactielijst',
      sv: 'Transaktionslista',
      vi: 'Danh sách giao dịch',
      id: 'Daftar transaksi',
      da: 'Transaktionsliste',
      nb: 'Transaksjonsliste',
      nn: 'Transaksjonsliste',
      fi: 'Tapahtumaluettelo',
      is: 'Færslulisti',
      fo: 'Posteringarlisti',
      cs: 'Seznam transakcí',
      bg: 'Списък с транзакции',
      hr: 'Popis transakcija',
      sr: 'Списак трансакција',
      sl: 'Seznam transakcij',
      mk: 'Список на трансакции',
      be: 'Спіс транзакцый',
      bs: 'Spisak transakcija',
      hsb: 'Lisćina transakcijow',
    }),
    transactionListDescription: t({
      ru: 'Детальная информация по всем операциям',
      en: 'Detailed information on all transactions',
      kk: 'Барлық операциялар бойынша толық ақпарат',
      de: 'Detaillierte Informationen zu allen Transaktionen',
      fr: 'Informations détaillées sur toutes les transactions',
      es: 'Información detallada sobre todas las transacciones',
      pt: 'Informações detalhadas sobre todas as transações',
      tr: 'Tüm işlemler hakkında ayrıntılı bilgi',
      uk: 'Детальна інформація по всіх операціях',
      zh: '所有交易的详细信息',
      pl: 'Szczegółowe informacje o wszystkich operacjach',
      it: 'Informazioni dettagliate su tutte le transazioni',
      sk: 'Podrobné informácie o všetkých transakciách',
      ja: 'すべての取引の詳細情報',
      ko: '모든 거래에 대한 상세 정보',
      hi: 'सभी लेनदेन की विस्तृत जानकारी',
      nl: 'Gedetailleerde informatie over alle transacties',
      sv: 'Detaljerad information om alla transaktioner',
      vi: 'Thông tin chi tiết về tất cả giao dịch',
      id: 'Informasi rinci tentang semua transaksi',
      da: 'Detaljerede oplysninger om alle transaktioner',
      nb: 'Detaljerte opplysninger om alle transaksjoner',
      nn: 'Detaljerte opplysningar om alle transaksjonar',
      fi: 'Yksityiskohtaiset tiedot kaikista tapahtumista',
      is: 'Nákvæmar upplýsingar um allar færslur',
      fo: 'Nágreiniligar upplýsingar um allar posteringar',
      cs: 'Podrobné informace o všech transakcích',
      bg: 'Подробна информация за всички транзакции',
      hr: 'Podrobne informacije o svim transakcijama',
      sr: 'Подробне информације о свим трансакцијама',
      sl: 'Podrobni podatki o vseh transakcijah',
      mk: 'Подробни информации за сите трансакции',
      be: 'Падрабязная інфармацыя пра ўсе транзакцыі',
      bs: 'Podrobne informacije o svim transakcijama',
      hsb: 'Podrobne informacije wo wšěch transakcijach',
    }),
    columns: {
      date: t({
        ru: 'Дата',
        en: 'Date',
        kk: 'Күні',
        de: 'Datum',
        fr: 'Date',
        es: 'Fecha',
        pt: 'Data',
        tr: 'Tarih',
        uk: 'Дата',
        zh: '日期',
        pl: 'Data',
        it: 'Data',
        sk: 'Dátum',
        ja: '日付',
        ko: '날짜',
        hi: 'तारीख',
        nl: 'Datum',
        sv: 'Datum',
        vi: 'Ngày',
        id: 'Tanggal',
        da: 'Dato',
        nb: 'Dato',
        nn: 'Dato',
        fi: 'Päivämäärä',
        is: 'Dagsetning',
        fo: 'Dato',
        cs: 'Datum',
        bg: 'Дата',
        hr: 'Datum',
        sr: 'Датум',
        sl: 'Datum',
        mk: 'Датум',
        be: 'Дата',
        bs: 'Datum',
        hsb: 'Datum',
      }),
      documentNumber: t({
        ru: 'Номер документа',
        en: 'Document number',
        kk: 'Құжат нөмірі',
        de: 'Dokumentnummer',
        fr: 'Numéro de document',
        es: 'Número de documento',
        pt: 'Número do documento',
        tr: 'Belge numarası',
        uk: 'Номер документа',
        zh: '单据号',
        pl: 'Numer dokumentu',
        it: 'Numero documento',
        sk: 'Číslo dokladu',
        ja: '文書番号',
        ko: '문서 번호',
        hi: 'दस्तावेज़ संख्या',
        nl: 'Documentnummer',
        sv: 'Dokumentnummer',
        vi: 'Số tài liệu',
        id: 'Nomor dokumen',
        da: 'Dokumentnummer',
        nb: 'Dokumentnummer',
        nn: 'Dokumentnummer',
        fi: 'Tositenumero',
        is: 'Skjalsnúmer',
        fo: 'Skjalanummar',
        cs: 'Číslo dokladu',
        bg: 'Номер на документ',
        hr: 'Broj dokumenta',
        sr: 'Број документа',
        sl: 'Številka dokumenta',
        mk: 'Број на документ',
        be: 'Нумар дакумента',
        bs: 'Broj dokumenta',
        hsb: 'Čisło dokumenta',
      }),
      counterparty: t({
        ru: 'Контрагент',
        en: 'Counterparty',
        kk: 'Контрагент',
        de: 'Gegenpartei',
        fr: 'Contrepartie',
        es: 'Contraparte',
        pt: 'Contraparte',
        tr: 'Karşı taraf',
        uk: 'Контрагент',
        zh: '对方',
        pl: 'Kontrahent',
        it: 'Controparte',
        sk: 'Protistrana',
        ja: '取引相手',
        ko: '거래 상대방',
        hi: 'प्रतिपक्ष',
        nl: 'Tegenpartij',
        sv: 'Motpart',
        vi: 'Đối tác',
        id: 'Pihak lawan',
        da: 'Modpart',
        nb: 'Motpart',
        nn: 'Motpart',
        fi: 'Vastapuoli',
        is: 'Gagnaðili',
        fo: 'Mótpartur',
        cs: 'Protistrana',
        bg: 'Контрагент',
        hr: 'Druga strana',
        sr: 'Друга страна',
        sl: 'Nasprotna stranka',
        mk: 'Другата страна',
        be: 'Кантрагент',
        bs: 'Druga strana',
        hsb: 'Přećiwna strona',
      }),
      bin: t({
        ru: 'БИН',
        en: 'BIN',
        kk: 'БСН',
        de: 'BIN',
        fr: 'BIN',
        es: 'BIN',
        pt: 'BIN',
        tr: 'BIN',
        uk: 'БІН',
        zh: 'BIN',
        pl: 'BIN',
        it: 'BIN',
        sk: 'BIN',
        ja: 'BIN',
        ko: 'BIN',
        hi: 'BIN',
        nl: 'BIN',
        sv: 'BIN',
        vi: 'BIN',
        id: 'BIN',
        da: 'Reg.nr.',
        nb: 'Org.nr.',
        nn: 'Org.nr.',
        fi: 'Y-tunnus',
        is: 'Kennitala',
        fo: 'V-tal',
        cs: 'IČO',
        bg: 'ЕИК',
        hr: 'OIB',
        sr: 'ПИБ',
        sl: 'Davčna številka',
        mk: 'Даночен број',
        be: 'УНП',
        bs: 'ID broj',
        hsb: 'Dawkowe čisło',
      }),
      paymentPurpose: t({
        ru: 'Назначение платежа',
        en: 'Payment purpose',
        kk: 'Төлем мақсаты',
        de: 'Verwendungszweck',
        fr: 'Objet du paiement',
        es: 'Concepto de pago',
        pt: 'Finalidade do pagamento',
        tr: 'Ödeme amacı',
        uk: 'Призначення платежу',
        zh: '付款用途',
        pl: 'Tytuł płatności',
        it: 'Causale del pagamento',
        sk: 'Účel platby',
        ja: '支払い目的',
        ko: '결제 목적',
        hi: 'भुगतान का उद्देश्य',
        nl: 'Betalingsdoel',
        sv: 'Betalningsändamål',
        vi: 'Mục đích thanh toán',
        id: 'Tujuan pembayaran',
        da: 'Betalingsformål',
        nb: 'Betalingsformål',
        nn: 'Betalingsformål',
        fi: 'Maksun tarkoitus',
        is: 'Tilgangur greiðslu',
        fo: 'Endamál við gjaldinum',
        cs: 'Účel platby',
        bg: 'Основание за плащане',
        hr: 'Namjena plaćanja',
        sr: 'Намена плаћања',
        sl: 'Namen plačila',
        mk: 'Намена на плаќањето',
        be: 'Прызначэнне плацяжу',
        bs: 'Namjena plaćanja',
        hsb: 'Zaměr zapłaćenja',
      }),
      debit: t({
        ru: 'Дебет',
        en: 'Debit',
        kk: 'Дебет',
        de: 'Soll',
        fr: 'Débit',
        es: 'Débito',
        pt: 'Débito',
        tr: 'Borç',
        uk: 'Дебет',
        zh: '借方',
        pl: 'Debet',
        it: 'Debito',
        sk: 'Debet',
        ja: '借方',
        ko: '차변',
        hi: 'डेबिट',
        nl: 'Debet',
        sv: 'Debet',
        vi: 'Ghi nợ',
        id: 'Debit',
        da: 'Debet',
        nb: 'Debet',
        nn: 'Debet',
        fi: 'Debet',
        is: 'Debet',
        fo: 'Debet',
        cs: 'Debet',
        bg: 'Дебит',
        hr: 'Duguje',
        sr: 'Дугује',
        sl: 'Debet',
        mk: 'Должи',
        be: 'Дэбет',
        bs: 'Duguje',
        hsb: 'Debet',
      }),
      credit: t({
        ru: 'Кредит',
        en: 'Credit',
        kk: 'Кредит',
        de: 'Haben',
        fr: 'Crédit',
        es: 'Crédito',
        pt: 'Crédito',
        tr: 'Alacak',
        uk: 'Кредит',
        zh: '贷方',
        pl: 'Kredyt',
        it: 'Credito',
        sk: 'Kredit',
        ja: '貸方',
        ko: '대변',
        hi: 'क्रेडिट',
        nl: 'Krediet',
        sv: 'Kredit',
        vi: 'Ghi có',
        id: 'Kredit',
        da: 'Kredit',
        nb: 'Kredit',
        nn: 'Kredit',
        fi: 'Kredit',
        is: 'Kredit',
        fo: 'Kredit',
        cs: 'Kredit',
        bg: 'Кредит',
        hr: 'Potražuje',
        sr: 'Потражује',
        sl: 'Kredit',
        mk: 'Побарува',
        be: 'Крэдыт',
        bs: 'Potražuje',
        hsb: 'Kredit',
      }),
      currency: t({
        ru: 'Валюта',
        en: 'Currency',
        kk: 'Валюта',
        de: 'Währung',
        fr: 'Devise',
        es: 'Moneda',
        pt: 'Moeda',
        tr: 'Para birimi',
        uk: 'Валюта',
        zh: '货币',
        pl: 'Waluta',
        it: 'Valuta',
        sk: 'Mena',
        ja: '通貨',
        ko: '통화',
        hi: 'मुद्रा',
        nl: 'Valuta',
        sv: 'Valuta',
        vi: 'Tiền tệ',
        id: 'Mata uang',
        da: 'Valuta',
        nb: 'Valuta',
        nn: 'Valuta',
        fi: 'Valuutta',
        is: 'Mynt',
        fo: 'Gjaldoyra',
        cs: 'Měna',
        bg: 'Валута',
        hr: 'Valuta',
        sr: 'Валута',
        sl: 'Valuta',
        mk: 'Валута',
        be: 'Валюта',
        bs: 'Valuta',
        hsb: 'Waluta',
      }),
    },
    total: t({
      ru: 'ИТОГО:',
      en: 'TOTAL:',
      kk: 'БАРЛЫҒЫ:',
      de: 'GESAMT:',
      fr: 'TOTAL :',
      es: 'TOTALES:',
      pt: 'TOTAL:',
      tr: 'TOPLAM:',
      uk: 'РАЗОМ:',
      zh: '合计：',
      pl: 'ŁĄCZNIE:',
      it: 'TOTALE:',
      sk: 'SPOLU:',
      ja: '合計：',
      ko: '합계:',
      hi: 'कुल:',
      nl: 'TOTAAL:',
      sv: 'TOTALT:',
      vi: 'TỔNG:',
      id: 'JUMLAH:',
      da: 'I ALT:',
      nb: 'TOTALT:',
      nn: 'TOTALT:',
      fi: 'YHTEENSÄ:',
      is: 'SAMTALS:',
      fo: 'Í ALT:',
      cs: 'CELKEM:',
      bg: 'ОБЩО:',
      hr: 'UKUPNO:',
      sr: 'УКУПНО:',
      sl: 'SKUPAJ:',
      mk: 'ВКУПНО:',
      be: 'УСЯГО:',
      bs: 'UKUPNO:',
      hsb: 'DOHROMADY:',
    }),
    totalExpenses: t({
      ru: 'Всего списаний',
      en: 'Total expenses',
      kk: 'Барлық шығыстар',
      de: 'Ausgaben gesamt',
      fr: 'Total des dépenses',
      es: 'Total de gastos',
      pt: 'Total de despesas',
      tr: 'Toplam giderler',
      uk: 'Всього списань',
      zh: '支出合计',
      pl: 'Łączne wydatki',
      it: 'Totale spese',
      sk: 'Výdavky celkom',
      ja: '総支出',
      ko: '총 지출',
      hi: 'कुल व्यय',
      nl: 'Totale uitgaven',
      sv: 'Totala utgifter',
      vi: 'Tổng chi phí',
      id: 'Total pengeluaran',
      da: 'Udgifter i alt',
      nb: 'Utgifter totalt',
      nn: 'Utgifter totalt',
      fi: 'Menot yhteensä',
      is: 'Útgjöld samtals',
      fo: 'Útreiðslur í alt',
      cs: 'Výdaje celkem',
      bg: 'Общо разходи',
      hr: 'Ukupno troškova',
      sr: 'Укупно трошкова',
      sl: 'Stroški skupaj',
      mk: 'Вкупно трошоци',
      be: 'Усяго выдаткаў',
      bs: 'Ukupno troškova',
      hsb: 'Wudawki dohromady',
    }),
    totalIncome: t({
      ru: 'Всего поступлений',
      en: 'Total income',
      kk: 'Барлық кірістер',
      de: 'Einnahmen gesamt',
      fr: 'Total des revenus',
      es: 'Total de ingresos',
      pt: 'Total de receitas',
      tr: 'Toplam gelir',
      uk: 'Всього надходжень',
      zh: '收入合计',
      pl: 'Łączne przychody',
      it: 'Totale entrate',
      sk: 'Príjmy celkom',
      ja: '総収入',
      ko: '총 수입',
      hi: 'कुल आय',
      nl: 'Totale inkomsten',
      sv: 'Totala inkomster',
      vi: 'Tổng thu nhập',
      id: 'Total pendapatan',
      da: 'Kilde',
      nb: 'Kilde',
      nn: 'Kjelde',
      fi: 'Lähde',
      is: 'Heimild',
      fo: 'Kelda',
      cs: 'Zdroj',
      bg: 'Източник',
      hr: 'Izvor',
      sr: 'Извор',
      sl: 'Vir',
      mk: 'Извор',
      be: 'Крыніца',
      bs: 'Izvor',
      hsb: 'Žórło',
    }),
    footer: t({
      ru: 'Документ сформирован автоматически • Lumio Parse Ledger',
      en: 'Document generated automatically • Lumio Parse Ledger',
      kk: 'Құжат автоматты түрде қалыптастырылды • Lumio Parse Ledger',
      de: 'Dokument automatisch erstellt • Lumio Parse Ledger',
      fr: 'Document généré automatiquement • Lumio Parse Ledger',
      es: 'Documento generado automáticamente • Lumio Parse Ledger',
      pt: 'Documento gerado automaticamente • Lumio Parse Ledger',
      tr: 'Belge otomatik olarak oluşturuldu • Lumio Parse Ledger',
      uk: 'Документ сформований автоматично • Lumio Parse Ledger',
      zh: '文档自动生成 • Lumio Parse Ledger',
      pl: 'Dokument wygenerowany automatycznie • Lumio Parse Ledger',
      it: 'Documento generato automaticamente • Lumio Parse Ledger',
      sk: 'Dokument vygenerovaný automaticky • Lumio Parse Ledger',
      ja: 'ドキュメントは自動的に生成されました • Lumio Parse Ledger',
      ko: '문서가 자동으로 생성되었습니다 • Lumio Parse Ledger',
      hi: 'दस्तावेज़ स्वचालित रूप से उत्पन्न • Lumio Parse Ledger',
      nl: 'Document automatisch gegenereerd • Lumio Parse Ledger',
      sv: 'Dokument automatiskt genererat • Lumio Parse Ledger',
      vi: 'Tài liệu được tạo tự động • Lumio Parse Ledger',
      id: 'Dokumen dibuat secara otomatis • Lumio Parse Ledger',
      da: 'Dokumentet er genereret automatisk • Lumio Parse Ledger',
      nb: 'Dokumentet er generert automatisk • Lumio Parse Ledger',
      nn: 'Dokumentet er generert automatisk • Lumio Parse Ledger',
      fi: 'Asiakirja on luotu automaattisesti • Lumio Parse Ledger',
      is: 'Skjalið var búið til sjálfkrafa • Lumio Parse Ledger',
      fo: 'Skjalið er gjørt sjálvvirkandi • Lumio Parse Ledger',
      cs: 'Dokument byl vygenerován automaticky • Lumio Parse Ledger',
      bg: 'Документът е създаден автоматично • Lumio Parse Ledger',
      hr: 'Dokument je izrađen automatski • Lumio Parse Ledger',
      sr: 'Документ је направљен аутоматски • Lumio Parse Ledger',
      sl: 'Dokument je ustvarjen samodejno • Lumio Parse Ledger',
      mk: 'Документот е создаден автоматски • Lumio Parse Ledger',
      be: 'Дакумент створаны аўтаматычна • Lumio Parse Ledger',
      bs: 'Dokument je napravljen automatski • Lumio Parse Ledger',
      hsb: 'Dokument je so awtomatisce wutworił • Lumio Parse Ledger',
    }),
  },
} satisfies Dictionary;

export default content;
