import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'updateButton',
  content: {
    update: t({
      ru: 'Обновить',
      en: 'Update',
      kk: 'Жаңарту',
      de: 'Aktualisieren',
      fr: 'Mettre à jour',
      es: 'Actualizar',
      pt: 'Atualizar',
      tr: 'Güncelle',
      uk: 'Оновити',
      zh: '更新',
      ar: 'تحديث',
      pl: 'Aktualizuj',
      it: 'Aggiorna',
      sk: 'Aktualizovať',
      ja: '更新',
      ko: '업데이트',
      hi: 'अपडेट करें',
      nl: 'Bijwerken',
      sv: 'Uppdatera',
      vi: 'Cập nhật',
      id: 'Perbarui',
      da: 'Opdatér',
      nb: 'Oppdater',
      nn: 'Oppdater',
      fi: 'Päivitä',
      is: 'Uppfæra',
      fo: 'Dagfør',
      cs: 'Aktualizovat',
      bg: 'Обновяване',
      hr: 'Ažuriraj',
      sr: 'Ажурирај',
      sl: 'Posodobi',
      mk: 'Ажурирај',
      be: 'Абнавіць',
      bs: 'Ažuriraj',
      hsb: 'Zaktualizować',
    }),
    releaseAvailable: t({
      ru: 'Доступна версия {tag}. Обновление: git pull && docker compose up -d --build',
      en: 'Release {tag} is available. Update with: git pull && docker compose up -d --build',
      kk: '{tag} нұсқасы қолжетімді. Жаңарту: git pull && docker compose up -d --build',
      de: 'Version {tag} ist verfügbar. Aktualisieren mit: git pull && docker compose up -d --build',
      fr: 'La version {tag} est disponible. Mise à jour : git pull && docker compose up -d --build',
      es: 'La versión {tag} está disponible. Actualiza con: git pull && docker compose up -d --build',
      pt: 'A versão {tag} está disponível. Atualize com: git pull && docker compose up -d --build',
      tr: '{tag} sürümü yayında. Güncellemek için: git pull && docker compose up -d --build',
      uk: 'Доступна версія {tag}. Оновлення: git pull && docker compose up -d --build',
      zh: '版本 {tag} 已发布。更新命令：git pull && docker compose up -d --build',
      ar: 'الإصدار {tag} متاح. للتحديث: git pull && docker compose up -d --build',
      pl: 'Dostępna jest wersja {tag}. Aktualizacja: git pull && docker compose up -d --build',
      it: 'La versione {tag} è disponibile. Aggiorna con: git pull && docker compose up -d --build',
      sk: 'K dispozícii je verzia {tag}. Aktualizácia: git pull && docker compose up -d --build',
      ja: 'バージョン {tag} が利用可能です。更新方法: git pull && docker compose up -d --build',
      ko: '{tag} 버전을 사용할 수 있습니다. 업데이트: git pull && docker compose up -d --build',
      hi: 'रिलीज़ {tag} उपलब्ध है। अपडेट करें: git pull && docker compose up -d --build',
      nl: 'Versie {tag} is beschikbaar. Bijwerken met: git pull && docker compose up -d --build',
      sv: 'Version {tag} finns tillgänglig. Uppdatera med: git pull && docker compose up -d --build',
      vi: 'Đã có phiên bản {tag}. Cập nhật bằng: git pull && docker compose up -d --build',
      id: 'Rilis {tag} tersedia. Perbarui dengan: git pull && docker compose up -d --build',
      da: 'Udgivelse {tag} er tilgængelig. Opdatér med: git pull && docker compose up -d --build',
      nb: 'Utgivelse {tag} er tilgjengelig. Oppdater med: git pull && docker compose up -d --build',
      nn: 'Utgjeving {tag} er tilgjengeleg. Oppdater med: git pull && docker compose up -d --build',
      fi: 'Julkaisu {tag} on saatavilla. Päivitä komennolla: git pull && docker compose up -d --build',
      is: 'Útgáfa {tag} er í boði. Uppfærðu með: git pull && docker compose up -d --build',
      fo: 'Útgáva {tag} er tøk. Dagfør við: git pull && docker compose up -d --build',
      cs: 'Je dostupné vydání {tag}. Aktualizujte příkazem: git pull && docker compose up -d --build',
      bg: 'Налична е версия {tag}. Обновете с: git pull && docker compose up -d --build',
      hr: 'Dostupno je izdanje {tag}. Ažurirajte naredbom: git pull && docker compose up -d --build',
      sr: 'Доступно је издање {tag}. Ажурирајте командом: git pull && docker compose up -d --build',
      sl: 'Na voljo je izdaja {tag}. Posodobite z: git pull && docker compose up -d --build',
      mk: 'Достапно е издание {tag}. Ажурирајте со: git pull && docker compose up -d --build',
      be: 'Даступны выпуск {tag}. Абнавіце камандай: git pull && docker compose up -d --build',
      bs: 'Dostupno je izdanje {tag}. Ažurirajte komandom: git pull && docker compose up -d --build',
      hsb: 'Wudaće {tag} je k dispoziciji. Zaktualizujće z: git pull && docker compose up -d --build',
    }),
  },
} satisfies Dictionary;

export default content;
