/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementsCreateExpenseDrawer',
  content: {
    closeDrawer: t({
      ru: 'Закрыть окно создания расхода',
      en: 'Close create expense drawer',
      kk: 'Шығын жасау терезесін жабу',
      de: 'Ausgabe-Erstellung schließen',
      fr: 'Fermer la création de dépense',
      es: 'Cerrar creación de gasto',
      pt: 'Fechar criação de despesa',
      tr: 'Gider oluşturmayı kapat',
      uk: 'Закрити створення витрати',
      zh: '关闭创建支出面板',
      ar: 'إغلاق إنشاء المصروف',
      pl: 'Zamknij tworzenie wydatku',
      it: 'Chiudi creazione spesa',
      sk: 'Zavrieť vytváranie výdavku',
      ja: '経費作成を閉じる',
      ko: '비용 생성 닫기',
      hi: 'खर्च बनाना बंद करें',
      nl: 'Uitgave aanmaken sluiten',
      sv: 'Stäng skapa utgift',
      vi: 'Đóng tạo chi phí',
      id: 'Tutup pembuatan pengeluaran',
    }),
    confirmDetails: t({
      ru: 'Подтвердите данные',
      en: 'Confirm details',
      kk: 'Деректерді растаңыз',
      de: 'Details bestätigen',
      fr: 'Confirmer les détails',
      es: 'Confirmar detalles',
      pt: 'Confirmar detalhes',
      tr: 'Ayrıntıları onaylayın',
      uk: 'Підтвердьте дані',
      zh: '确认详情',
      ar: 'تأكيد التفاصيل',
      pl: 'Potwierdź szczegóły',
      it: 'Conferma i dettagli',
      sk: 'Potvrďte údaje',
      ja: '詳細を確認',
      ko: '세부 정보 확인',
      hi: 'विवरण की पुष्टि करें',
      nl: 'Gegevens bevestigen',
      sv: 'Bekräfta uppgifter',
      vi: 'Xác nhận chi tiết',
      id: 'Konfirmasi detail',
    }),
    createExpense: t({
      ru: 'Создать расход',
      en: 'Create expense',
      kk: 'Шығын жасау',
      de: 'Ausgabe erstellen',
      fr: 'Créer une dépense',
      es: 'Crear gasto',
      pt: 'Criar despesa',
      tr: 'Gider oluştur',
      uk: 'Створити витрату',
      zh: '创建支出',
      ar: 'إنشاء مصروف',
      pl: 'Utwórz wydatek',
      it: 'Crea spesa',
      sk: 'Vytvoriť výdavok',
      ja: '経費を作成',
      ko: '비용 생성',
      hi: 'खर्च बनाएं',
      nl: 'Uitgave aanmaken',
      sv: 'Skapa utgift',
      vi: 'Tạo chi phí',
      id: 'Buat pengeluaran',
    }),
    manualTab: t({
      ru: 'Вручную',
      en: 'Manual',
      kk: 'Қолмен',
      de: 'Manuell',
      fr: 'Manuel',
      es: 'Manual',
      pt: 'Manual',
      tr: 'Manuel',
      uk: 'Вручну',
      zh: '手动',
      ar: 'يدوي',
      pl: 'Ręcznie',
      it: 'Manuale',
      sk: 'Ručne',
      ja: '手動',
      ko: '수동',
      hi: 'मैनुअल',
      nl: 'Handmatig',
      sv: 'Manuellt',
      vi: 'Thủ công',
      id: 'Manual',
    }),
    scanTab: t({
      ru: 'Сканировать',
      en: 'Scan',
      kk: 'Сканерлеу',
      de: 'Scannen',
      fr: 'Scanner',
      es: 'Escanear',
      pt: 'Digitalizar',
      tr: 'Tara',
      uk: 'Сканувати',
      zh: '扫描',
      ar: 'مسح',
      pl: 'Skanuj',
      it: 'Scansiona',
      sk: 'Skenovať',
      ja: 'スキャン',
      ko: '스캔',
      hi: 'स्कैन',
      nl: 'Scannen',
      sv: 'Skanna',
      vi: 'Quét',
      id: 'Pindai',
    }),
    takePhoto: t({
      ru: 'Сделать фото',
      en: 'Take photo',
      kk: 'Суретке түсіру',
      de: 'Foto aufnehmen',
      fr: 'Prendre une photo',
      es: 'Tomar foto',
      pt: 'Tirar foto',
      tr: 'Fotoğraf çek',
      uk: 'Зробити фото',
      zh: '拍照',
      ar: 'التقاط صورة',
      pl: 'Zrób zdjęcie',
      it: 'Scatta foto',
      sk: 'Odfotiť',
      ja: '写真を撮る',
      ko: '사진 촬영',
      hi: 'फ़ोटो लें',
      nl: 'Foto maken',
      sv: 'Ta foto',
      vi: 'Chụp ảnh',
      id: 'Ambil foto',
    }),
    chooseFromGallery: t({
      ru: 'Выбрать из галереи',
      en: 'Choose from gallery',
      kk: 'Галереядан таңдау',
      de: 'Aus Galerie wählen',
      fr: 'Choisir dans la galerie',
      es: 'Elegir de la galería',
      pt: 'Escolher da galeria',
      tr: 'Galeriden seç',
      uk: 'Вибрати з галереї',
      zh: '从相册选择',
      ar: 'اختر من المعرض',
      pl: 'Wybierz z galerii',
      it: 'Scegli dalla galleria',
      sk: 'Vybrať z galérie',
      ja: 'ギャラリーから選択',
      ko: '갤러리에서 선택',
      hi: 'गैलरी से चुनें',
      nl: 'Kiezen uit galerij',
      sv: 'Välj från galleriet',
      vi: 'Chọn từ thư viện',
      id: 'Pilih dari galeri',
    }),
    uploadReceipts: t({
      ru: 'Загрузите чеки',
      en: 'Upload receipts',
      kk: 'Чектерді жүктеңіз',
      de: 'Belege hochladen',
      fr: 'Importer des reçus',
      es: 'Subir recibos',
      pt: 'Enviar recibos',
      tr: 'Fiş yükle',
      uk: 'Завантажте чеки',
      zh: '上传收据',
      ar: 'رفع الإيصالات',
      pl: 'Prześlij paragony',
      it: 'Carica ricevute',
      sk: 'Nahrajte doklady',
      ja: 'レシートをアップロード',
      ko: '영수증 업로드',
      hi: 'रसीदें अपलोड करें',
      nl: 'Bonnen uploaden',
      sv: 'Ladda upp kvitton',
      vi: 'Tải lên biên lai',
      id: 'Unggah struk',
    }),
    dragAndDrop: t({
      ru: 'или перетащите их сюда',
      en: 'or drag and drop them here',
      kk: 'немесе оларды осында сүйреңіз',
      de: 'oder hierher ziehen und ablegen',
      fr: 'ou glissez-déposez-les ici',
      es: 'o arrástralos y suéltalos aquí',
      pt: 'ou arraste e solte-os aqui',
      tr: 'veya buraya sürükleyip bırakın',
      uk: 'або перетягніть їх сюди',
      zh: '或将其拖放到此处',
      ar: 'أو اسحبها وأفلتها هنا',
      pl: 'lub przeciągnij je i upuść tutaj',
      it: 'o trascinali qui',
      sk: 'alebo ich sem presuňte',
      ja: 'またはここにドラッグ＆ドロップ',
      ko: '또는 여기로 끌어다 놓으세요',
      hi: 'या उन्हें यहाँ खींचकर छोड़ें',
      nl: 'of sleep ze hierheen',
      sv: 'eller dra och släpp dem här',
      vi: 'hoặc kéo và thả vào đây',
      id: 'atau seret dan lepas di sini',
    }),
    chooseFiles: t({
      ru: 'Выбрать файлы',
      en: 'Choose files',
      kk: 'Файлдарды таңдау',
      de: 'Dateien auswählen',
      fr: 'Choisir des fichiers',
      es: 'Elegir archivos',
      pt: 'Escolher arquivos',
      tr: 'Dosya seç',
      uk: 'Вибрати файли',
      zh: '选择文件',
      ar: 'اختر الملفات',
      pl: 'Wybierz pliki',
      it: 'Scegli file',
      sk: 'Vybrať súbory',
      ja: 'ファイルを選択',
      ko: '파일 선택',
      hi: 'फ़ाइलें चुनें',
      nl: 'Bestanden kiezen',
      sv: 'Välj filer',
      vi: 'Chọn tệp',
      id: 'Pilih file',
    }),
    amount: t({
      ru: 'Сумма',
      en: 'Amount',
      kk: 'Сома',
      de: 'Betrag',
      fr: 'Montant',
      es: 'Importe',
      pt: 'Valor',
      tr: 'Tutar',
      uk: 'Сума',
      zh: '金额',
      ar: 'المبلغ',
      pl: 'Kwota',
      it: 'Importo',
      sk: 'Suma',
      ja: '金額',
      ko: '금액',
      hi: 'राशि',
      nl: 'Bedrag',
      sv: 'Belopp',
      vi: 'Số tiền',
      id: 'Jumlah',
    }),
    description: t({
      ru: 'Описание',
      en: 'Description',
      kk: 'Сипаттама',
      de: 'Beschreibung',
      fr: 'Description',
      es: 'Descripción',
      pt: 'Descrição',
      tr: 'Açıklama',
      uk: 'Опис',
      zh: '描述',
      ar: 'الوصف',
      pl: 'Opis',
      it: 'Descrizione',
      sk: 'Popis',
      ja: '説明',
      ko: '설명',
      hi: 'विवरण',
      nl: 'Omschrijving',
      sv: 'Beskrivning',
      vi: 'Mô tả',
      id: 'Deskripsi',
    }),
    merchant: t({
      ru: 'Продавец',
      en: 'Merchant',
      kk: 'Сатушы',
      de: 'Händler',
      fr: 'Commerçant',
      es: 'Comercio',
      pt: 'Estabelecimento',
      tr: 'Satıcı',
      uk: 'Продавець',
      zh: '商户',
      ar: 'التاجر',
      pl: 'Sprzedawca',
      it: 'Esercente',
      sk: 'Obchodník',
      ja: '加盟店',
      ko: '가맹점',
      hi: 'व्यापारी',
      nl: 'Handelaar',
      sv: 'Handlare',
      vi: 'Người bán',
      id: 'Merchant',
    }),
    category: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '类别',
      ar: 'الفئة',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategória',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
    }),
    date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
    }),
    tax: t({
      ru: 'Налог',
      en: 'Tax',
      kk: 'Салық',
      de: 'Steuer',
      fr: 'Taxe',
      es: 'Impuesto',
      pt: 'Imposto',
      tr: 'Vergi',
      uk: 'Податок',
      zh: '税',
      ar: 'الضريبة',
      pl: 'Podatek',
      it: 'Imposta',
      sk: 'Daň',
      ja: '税',
      ko: '세금',
      hi: 'कर',
      nl: 'Belasting',
      sv: 'Skatt',
      vi: 'Thuế',
      id: 'Pajak',
    }),
    optional: t({
      ru: 'Необязательно',
      en: 'Optional',
      kk: 'Міндетті емес',
      de: 'Optional',
      fr: 'Facultatif',
      es: 'Opcional',
      pt: 'Opcional',
      tr: 'İsteğe bağlı',
      uk: 'Необов’язково',
      zh: '可选',
      ar: 'اختياري',
      pl: 'Opcjonalnie',
      it: 'Facoltativo',
      sk: 'Voliteľné',
      ja: '任意',
      ko: '선택 사항',
      hi: 'वैकल्पिक',
      nl: 'Optioneel',
      sv: 'Valfritt',
      vi: 'Tùy chọn',
      id: 'Opsional',
    }),
    attachFile: t({
      ru: 'Прикрепить чек или счёт',
      en: 'Attach receipt or invoice',
      kk: 'Чек немесе шот тіркеу',
      de: 'Beleg oder Rechnung anhängen',
      fr: 'Joindre un reçu ou une facture',
      es: 'Adjuntar recibo o factura',
      pt: 'Anexar recibo ou fatura',
      tr: 'Fiş veya fatura ekle',
      uk: 'Прикріпити чек або рахунок',
      zh: '附加收据或发票',
      ar: 'إرفاق إيصال أو فاتورة',
      pl: 'Dołącz paragon lub fakturę',
      it: 'Allega ricevuta o fattura',
      sk: 'Priložiť bloček alebo faktúru',
      ja: 'レシートや請求書を添付',
      ko: '영수증 또는 청구서 첨부',
      hi: 'रसीद या चालान संलग्न करें',
      nl: 'Bon of factuur bijvoegen',
      sv: 'Bifoga kvitto eller faktura',
      vi: 'Đính kèm biên lai hoặc hóa đơn',
      id: 'Lampirkan struk atau faktur',
    }),
    attachFileHint: t({
      ru: 'Фото, PDF или таблица',
      en: 'Photo, PDF or spreadsheet',
      kk: 'Фото, PDF немесе кесте',
      de: 'Foto, PDF oder Tabelle',
      fr: 'Photo, PDF ou tableur',
      es: 'Foto, PDF u hoja de cálculo',
      pt: 'Foto, PDF ou planilha',
      tr: 'Fotoğraf, PDF veya tablo',
      uk: 'Фото, PDF або таблиця',
      zh: '照片、PDF 或表格',
      ar: 'صورة أو PDF أو جدول بيانات',
      pl: 'Zdjęcie, PDF lub arkusz',
      it: 'Foto, PDF o foglio di calcolo',
      sk: 'Fotka, PDF alebo tabuľka',
      ja: '写真、PDF、表計算ファイル',
      ko: '사진, PDF 또는 스프레드시트',
      hi: 'फ़ोटो, PDF या स्प्रेडशीट',
      nl: 'Foto, pdf of spreadsheet',
      sv: 'Foto, PDF eller kalkylblad',
      vi: 'Ảnh, PDF hoặc bảng tính',
      id: 'Foto, PDF, atau spreadsheet',
    }),
    merchantPlaceholder: t({
      ru: 'Например, Acme Corp',
      en: 'e.g. Acme Corp',
      kk: 'Мысалы, Acme Corp',
      de: 'z. B. Acme Corp',
      fr: 'ex. Acme Corp',
      es: 'p. ej., Acme Corp',
      pt: 'ex.: Acme Corp',
      tr: 'örn. Acme Corp',
      uk: 'Наприклад, Acme Corp',
      zh: '例如 Acme Corp',
      ar: 'مثال: Acme Corp',
      pl: 'np. Acme Corp',
      it: 'es. Acme Corp',
      sk: 'napr. Acme Corp',
      ja: '例: Acme Corp',
      ko: '예: Acme Corp',
      hi: 'जैसे Acme Corp',
      nl: 'bijv. Acme Corp',
      sv: 't.ex. Acme Corp',
      vi: 'VD: Acme Corp',
      id: 'mis. Acme Corp',
    }),
    selectCategory: t({
      ru: 'Выберите категорию…',
      en: 'Select category…',
      kk: 'Санатты таңдаңыз…',
      de: 'Kategorie wählen…',
      fr: 'Choisir une catégorie…',
      es: 'Selecciona una categoría…',
      pt: 'Selecione uma categoria…',
      tr: 'Kategori seçin…',
      uk: 'Виберіть категорію…',
      zh: '选择类别…',
      ar: 'اختر فئة…',
      pl: 'Wybierz kategorię…',
      it: 'Seleziona una categoria…',
      sk: 'Vyberte kategóriu…',
      ja: 'カテゴリを選択…',
      ko: '카테고리 선택…',
      hi: 'श्रेणी चुनें…',
      nl: 'Kies een categorie…',
      sv: 'Välj kategori…',
      vi: 'Chọn danh mục…',
      id: 'Pilih kategori…',
    }),
    fieldRequired: t({
      ru: 'Это поле обязательно',
      en: 'This field is required',
      kk: 'Бұл өріс міндетті',
      de: 'Dieses Feld ist erforderlich',
      fr: 'Ce champ est obligatoire',
      es: 'Este campo es obligatorio',
      pt: 'Este campo é obrigatório',
      tr: 'Bu alan zorunludur',
      uk: 'Це поле обов’язкове',
      zh: '此字段为必填项',
      ar: 'هذا الحقل مطلوب',
      pl: 'To pole jest wymagane',
      it: 'Questo campo è obbligatorio',
      sk: 'Toto pole je povinné',
      ja: 'この項目は必須です',
      ko: '필수 입력 항목입니다',
      hi: 'यह फ़ील्ड आवश्यक है',
      nl: 'Dit veld is verplicht',
      sv: 'Detta fält är obligatoriskt',
      vi: 'Trường này là bắt buộc',
      id: 'Kolom ini wajib diisi',
    }),
    defaultSuffix: t({
      ru: ' — по умолчанию',
      en: ' - Default',
      kk: ' — әдепкі',
      de: ' – Standard',
      fr: ' – Par défaut',
      es: ' - Predeterminado',
      pt: ' - Padrão',
      tr: ' - Varsayılan',
      uk: ' — типово',
      zh: ' - 默认',
      ar: ' - افتراضي',
      pl: ' – domyślny',
      it: ' - Predefinita',
      sk: ' – predvolená',
      ja: ' - デフォルト',
      ko: ' - 기본값',
      hi: ' - डिफ़ॉल्ट',
      nl: ' - Standaard',
      sv: ' – Standard',
      vi: ' - Mặc định',
      id: ' - Default',
    }),
    defaultTag: t({
      ru: 'По умолчанию',
      en: 'Default',
      kk: 'Әдепкі',
      de: 'Standard',
      fr: 'Par défaut',
      es: 'Predeterminado',
      pt: 'Padrão',
      tr: 'Varsayılan',
      uk: 'За замовчуванням',
      zh: '默认',
      ar: 'افتراضي',
      pl: 'Domyślna',
      it: 'Predefinita',
      sk: 'Predvolená',
      ja: 'デフォルト',
      ko: '기본값',
      hi: 'डिफ़ॉल्ट',
      nl: 'Standaard',
      sv: 'Standard',
      vi: 'Mặc định',
      id: 'Bawaan',
    }),
    selectedFiles: t({
      ru: 'Выбранные файлы',
      en: 'Selected files',
      kk: 'Таңдалған файлдар',
      de: 'Ausgewählte Dateien',
      fr: 'Fichiers sélectionnés',
      es: 'Archivos seleccionados',
      pt: 'Arquivos selecionados',
      tr: 'Seçili dosyalar',
      uk: 'Вибрані файли',
      zh: '已选文件',
      ar: 'الملفات المحددة',
      pl: 'Wybrane pliki',
      it: 'File selezionati',
      sk: 'Vybrané súbory',
      ja: '選択したファイル',
      ko: '선택한 파일',
      hi: 'चयनित फ़ाइलें',
      nl: 'Geselecteerde bestanden',
      sv: 'Valda filer',
      vi: 'Tệp đã chọn',
      id: 'File terpilih',
    }),
    saving: t({
      ru: 'Сохранение...',
      en: 'Saving...',
      kk: 'Сақталуда...',
      de: 'Wird gespeichert...',
      fr: 'Enregistrement...',
      es: 'Guardando...',
      pt: 'Salvando...',
      tr: 'Kaydediliyor...',
      uk: 'Збереження...',
      zh: '正在保存...',
      ar: 'جارٍ الحفظ...',
      pl: 'Zapisywanie...',
      it: 'Salvataggio...',
      sk: 'Ukladá sa...',
      ja: '保存中...',
      ko: '저장 중...',
      hi: 'सहेजा जा रहा है...',
      nl: 'Opslaan...',
      sv: 'Sparar...',
      vi: 'Đang lưu...',
      id: 'Menyimpan...',
    }),
    uploadReceipt: t({
      ru: 'Загрузить чек',
      en: 'Upload receipt',
      kk: 'Чекті жүктеу',
      de: 'Beleg hochladen',
      fr: 'Importer le reçu',
      es: 'Subir recibo',
      pt: 'Enviar recibo',
      tr: 'Fişi yükle',
      uk: 'Завантажити чек',
      zh: '上传收据',
      ar: 'رفع الإيصال',
      pl: 'Prześlij paragon',
      it: 'Carica ricevuta',
      sk: 'Nahrať doklad',
      ja: 'レシートをアップロード',
      ko: '영수증 업로드',
      hi: 'रसीद अपलोड करें',
      nl: 'Bon uploaden',
      sv: 'Ladda upp kvitto',
      vi: 'Tải lên biên lai',
      id: 'Unggah struk',
    }),
    next: t({
      ru: 'Далее',
      en: 'Next',
      kk: 'Келесі',
      de: 'Weiter',
      fr: 'Suivant',
      es: 'Siguiente',
      pt: 'Próximo',
      tr: 'İleri',
      uk: 'Далі',
      zh: '下一步',
      ar: 'التالي',
      pl: 'Dalej',
      it: 'Avanti',
      sk: 'Ďalej',
      ja: '次へ',
      ko: '다음',
      hi: 'आगे',
      nl: 'Volgende',
      sv: 'Nästa',
      vi: 'Tiếp',
      id: 'Berikutnya',
    }),
    createAmountExpense: t({
      ru: 'Создать расход {amount}',
      en: 'Create {amount} expense',
      kk: '{amount} шығынын жасау',
      de: 'Ausgabe über {amount} erstellen',
      fr: 'Créer une dépense de {amount}',
      es: 'Crear gasto de {amount}',
      pt: 'Criar despesa de {amount}',
      tr: '{amount} tutarında gider oluştur',
      uk: 'Створити витрату {amount}',
      zh: '创建 {amount} 支出',
      ar: 'إنشاء مصروف بقيمة {amount}',
      pl: 'Utwórz wydatek {amount}',
      it: 'Crea spesa di {amount}',
      sk: 'Vytvoriť výdavok {amount}',
      ja: '{amount} の経費を作成',
      ko: '{amount} 비용 생성',
      hi: '{amount} का खर्च बनाएं',
      nl: 'Uitgave van {amount} aanmaken',
      sv: 'Skapa utgift på {amount}',
      vi: 'Tạo chi phí {amount}',
      id: 'Buat pengeluaran {amount}',
    }),
    searchCategories: t({
      ru: 'Поиск категорий',
      en: 'Search categories',
      kk: 'Санаттарды іздеу',
      de: 'Kategorien suchen',
      fr: 'Rechercher des catégories',
      es: 'Buscar categorías',
      pt: 'Pesquisar categorias',
      tr: 'Kategori ara',
      uk: 'Пошук категорій',
      zh: '搜索类别',
      ar: 'البحث في الفئات',
      pl: 'Szukaj kategorii',
      it: 'Cerca categorie',
      sk: 'Hľadať kategórie',
      ja: 'カテゴリを検索',
      ko: '카테고리 검색',
      hi: 'श्रेणियाँ खोजें',
      nl: 'Categorieën zoeken',
      sv: 'Sök kategorier',
      vi: 'Tìm danh mục',
      id: 'Cari kategori',
    }),
    noCategory: t({
      ru: 'Без категории',
      en: 'No category',
      kk: 'Санатсыз',
      de: 'Keine Kategorie',
      fr: 'Aucune catégorie',
      es: 'Sin categoría',
      pt: 'Sem categoria',
      tr: 'Kategori yok',
      uk: 'Без категорії',
      zh: '无类别',
      ar: 'بدون فئة',
      pl: 'Brak kategorii',
      it: 'Nessuna categoria',
      sk: 'Bez kategórie',
      ja: 'カテゴリなし',
      ko: '카테고리 없음',
      hi: 'कोई श्रेणी नहीं',
      nl: 'Geen categorie',
      sv: 'Ingen kategori',
      vi: 'Không có danh mục',
      id: 'Tanpa kategori',
    }),
    noCategoriesFound: t({
      ru: 'Категории не найдены',
      en: 'No categories found',
      kk: 'Санаттар табылмады',
      de: 'Keine Kategorien gefunden',
      fr: 'Aucune catégorie trouvée',
      es: 'No se encontraron categorías',
      pt: 'Nenhuma categoria encontrada',
      tr: 'Kategori bulunamadı',
      uk: 'Категорії не знайдено',
      zh: '未找到类别',
      ar: 'لم يتم العثور على فئات',
      pl: 'Nie znaleziono kategorii',
      it: 'Nessuna categoria trovata',
      sk: 'Nenašli sa žiadne kategórie',
      ja: 'カテゴリが見つかりません',
      ko: '카테고리를 찾을 수 없습니다',
      hi: 'कोई श्रेणी नहीं मिली',
      nl: 'Geen categorieën gevonden',
      sv: 'Inga kategorier hittades',
      vi: 'Không tìm thấy danh mục',
      id: 'Kategori tidak ditemukan',
    }),
    closeTaxRateDrawer: t({
      ru: 'Закрыть выбор налоговой ставки',
      en: 'Close tax rate drawer',
      kk: 'Салық мөлшерлемесін таңдауды жабу',
      de: 'Steuersatz-Auswahl schließen',
      fr: 'Fermer le choix du taux de taxe',
      es: 'Cerrar selección de tipo impositivo',
      pt: 'Fechar seleção de alíquota',
      tr: 'Vergi oranı seçimini kapat',
      uk: 'Закрити вибір податкової ставки',
      zh: '关闭税率面板',
      ar: 'إغلاق اختيار نسبة الضريبة',
      pl: 'Zamknij wybór stawki podatku',
      it: 'Chiudi selezione aliquota',
      sk: 'Zavrieť výber sadzby dane',
      ja: '税率の選択を閉じる',
      ko: '세율 선택 닫기',
      hi: 'कर दर चयन बंद करें',
      nl: 'Btw-tarief sluiten',
      sv: 'Stäng val av skattesats',
      vi: 'Đóng chọn thuế suất',
      id: 'Tutup pilihan tarif pajak',
    }),
    taxRate: t({
      ru: 'Налоговая ставка',
      en: 'Tax rate',
      kk: 'Салық мөлшерлемесі',
      de: 'Steuersatz',
      fr: 'Taux de taxe',
      es: 'Tipo impositivo',
      pt: 'Alíquota',
      tr: 'Vergi oranı',
      uk: 'Податкова ставка',
      zh: '税率',
      ar: 'نسبة الضريبة',
      pl: 'Stawka podatku',
      it: 'Aliquota',
      sk: 'Sadzba dane',
      ja: '税率',
      ko: '세율',
      hi: 'कर दर',
      nl: 'Belastingtarief',
      sv: 'Skattesats',
      vi: 'Thuế suất',
      id: 'Tarif pajak',
    }),
    taxRateName: t({
      ru: 'Название налоговой ставки',
      en: 'Tax rate name',
      kk: 'Салық мөлшерлемесінің атауы',
      de: 'Name des Steuersatzes',
      fr: 'Nom du taux de taxe',
      es: 'Nombre del tipo impositivo',
      pt: 'Nome da alíquota',
      tr: 'Vergi oranı adı',
      uk: 'Назва податкової ставки',
      zh: '税率名称',
      ar: 'اسم نسبة الضريبة',
      pl: 'Nazwa stawki podatku',
      it: 'Nome aliquota',
      sk: 'Názov sadzby dane',
      ja: '税率名',
      ko: '세율 이름',
      hi: 'कर दर का नाम',
      nl: 'Naam belastingtarief',
      sv: 'Namn på skattesats',
      vi: 'Tên thuế suất',
      id: 'Nama tarif pajak',
    }),
    taxRateNamePlaceholder: t({
      ru: 'НДС 12%',
      en: 'VAT 12%',
      kk: 'ҚҚС 12%',
      de: 'MwSt. 12%',
      fr: 'TVA 12 %',
      es: 'IVA 12%',
      pt: 'IVA 12%',
      tr: 'KDV %12',
      uk: 'ПДВ 12%',
      zh: '增值税 12%',
      ar: 'ضريبة القيمة المضافة 12%',
      pl: 'VAT 12%',
      it: 'IVA 12%',
      sk: 'DPH 12 %',
      ja: '消費税 12%',
      ko: '부가세 12%',
      hi: 'GST 12%',
      nl: 'Btw 12%',
      sv: 'Moms 12 %',
      vi: 'VAT 12%',
      id: 'PPN 12%',
    }),
    taxPercentage: t({
      ru: 'Процент налога',
      en: 'Tax percentage',
      kk: 'Салық пайызы',
      de: 'Steuersatz in Prozent',
      fr: 'Pourcentage de taxe',
      es: 'Porcentaje de impuesto',
      pt: 'Percentual do imposto',
      tr: 'Vergi yüzdesi',
      uk: 'Відсоток податку',
      zh: '税率百分比',
      ar: 'نسبة الضريبة المئوية',
      pl: 'Procent podatku',
      it: 'Percentuale imposta',
      sk: 'Percento dane',
      ja: '税率（%）',
      ko: '세율(%)',
      hi: 'कर प्रतिशत',
      nl: 'Belastingpercentage',
      sv: 'Skatteprocent',
      vi: 'Phần trăm thuế',
      id: 'Persentase pajak',
    }),
    saveTaxRate: t({
      ru: 'Сохранить налоговую ставку',
      en: 'Save tax rate',
      kk: 'Салық мөлшерлемесін сақтау',
      de: 'Steuersatz speichern',
      fr: 'Enregistrer le taux de taxe',
      es: 'Guardar tipo impositivo',
      pt: 'Salvar alíquota',
      tr: 'Vergi oranını kaydet',
      uk: 'Зберегти податкову ставку',
      zh: '保存税率',
      ar: 'حفظ نسبة الضريبة',
      pl: 'Zapisz stawkę podatku',
      it: 'Salva aliquota',
      sk: 'Uložiť sadzbu dane',
      ja: '税率を保存',
      ko: '세율 저장',
      hi: 'कर दर सहेजें',
      nl: 'Belastingtarief opslaan',
      sv: 'Spara skattesats',
      vi: 'Lưu thuế suất',
      id: 'Simpan tarif pajak',
    }),
    noTaxRates: t({
      ru: 'Налоговые ставки не найдены',
      en: 'No tax rates found',
      kk: 'Салық мөлшерлемелері табылмады',
      de: 'Keine Steuersätze gefunden',
      fr: 'Aucun taux de taxe trouvé',
      es: 'No se encontraron tipos impositivos',
      pt: 'Nenhuma alíquota encontrada',
      tr: 'Vergi oranı bulunamadı',
      uk: 'Податкові ставки не знайдено',
      zh: '未找到税率',
      ar: 'لم يتم العثور على نسب ضريبية',
      pl: 'Nie znaleziono stawek podatku',
      it: 'Nessuna aliquota trovata',
      sk: 'Nenašli sa žiadne sadzby dane',
      ja: '税率が見つかりません',
      ko: '세율을 찾을 수 없습니다',
      hi: 'कोई कर दर नहीं मिली',
      nl: 'Geen belastingtarieven gevonden',
      sv: 'Inga skattesatser hittades',
      vi: 'Không tìm thấy thuế suất',
      id: 'Tarif pajak tidak ditemukan',
    }),
    taxRateNameRequired: t({
      ru: 'Укажите название налоговой ставки',
      en: 'Tax rate name is required',
      kk: 'Салық мөлшерлемесінің атауын көрсетіңіз',
      de: 'Name des Steuersatzes ist erforderlich',
      fr: 'Le nom du taux de taxe est obligatoire',
      es: 'El nombre del tipo impositivo es obligatorio',
      pt: 'O nome da alíquota é obrigatório',
      tr: 'Vergi oranı adı zorunludur',
      uk: 'Вкажіть назву податкової ставки',
      zh: '请输入税率名称',
      ar: 'اسم نسبة الضريبة مطلوب',
      pl: 'Nazwa stawki podatku jest wymagana',
      it: 'Il nome dell’aliquota è obbligatorio',
      sk: 'Názov sadzby dane je povinný',
      ja: '税率名は必須です',
      ko: '세율 이름은 필수입니다',
      hi: 'कर दर का नाम आवश्यक है',
      nl: 'Naam van het belastingtarief is verplicht',
      sv: 'Namn på skattesats krävs',
      vi: 'Tên thuế suất là bắt buộc',
      id: 'Nama tarif pajak wajib diisi',
    }),
    taxPercentageRange: t({
      ru: 'Процент налога должен быть от 0 до 100',
      en: 'Tax percentage must be between 0 and 100',
      kk: 'Салық пайызы 0 мен 100 аралығында болуы керек',
      de: 'Der Steuersatz muss zwischen 0 und 100 liegen',
      fr: 'Le pourcentage de taxe doit être compris entre 0 et 100',
      es: 'El porcentaje de impuesto debe estar entre 0 y 100',
      pt: 'O percentual do imposto deve estar entre 0 e 100',
      tr: 'Vergi yüzdesi 0 ile 100 arasında olmalıdır',
      uk: 'Відсоток податку має бути від 0 до 100',
      zh: '税率百分比必须介于 0 到 100 之间',
      ar: 'يجب أن تكون نسبة الضريبة بين 0 و100',
      pl: 'Procent podatku musi mieścić się w przedziale od 0 do 100',
      it: 'La percentuale dell’imposta deve essere compresa tra 0 e 100',
      sk: 'Percento dane musí byť medzi 0 a 100',
      ja: '税率は 0〜100 の範囲で入力してください',
      ko: '세율은 0에서 100 사이여야 합니다',
      hi: 'कर प्रतिशत 0 और 100 के बीच होना चाहिए',
      nl: 'Belastingpercentage moet tussen 0 en 100 liggen',
      sv: 'Skatteprocenten måste vara mellan 0 och 100',
      vi: 'Phần trăm thuế phải từ 0 đến 100',
      id: 'Persentase pajak harus antara 0 dan 100',
    }),
    taxRateUnavailable: t({
      ru: 'Создание налоговых ставок недоступно',
      en: 'Tax rate creation is unavailable',
      kk: 'Салық мөлшерлемесін жасау қолжетімсіз',
      de: 'Erstellen von Steuersätzen ist nicht verfügbar',
      fr: 'La création de taux de taxe est indisponible',
      es: 'La creación de tipos impositivos no está disponible',
      pt: 'A criação de alíquotas não está disponível',
      tr: 'Vergi oranı oluşturma kullanılamıyor',
      uk: 'Створення податкових ставок недоступне',
      zh: '无法创建税率',
      ar: 'إنشاء نسب الضريبة غير متاح',
      pl: 'Tworzenie stawek podatku jest niedostępne',
      it: 'La creazione di aliquote non è disponibile',
      sk: 'Vytváranie sadzieb dane nie je dostupné',
      ja: '税率を作成できません',
      ko: '세율을 생성할 수 없습니다',
      hi: 'कर दर बनाना उपलब्ध नहीं है',
      nl: 'Belastingtarieven aanmaken is niet beschikbaar',
      sv: 'Det går inte att skapa skattesatser',
      vi: 'Không thể tạo thuế suất',
      id: 'Pembuatan tarif pajak tidak tersedia',
    }),
    taxRateSaveFailed: t({
      ru: 'Не удалось сохранить налоговую ставку',
      en: 'Failed to save tax rate',
      kk: 'Салық мөлшерлемесін сақтау мүмкін болмады',
      de: 'Steuersatz konnte nicht gespeichert werden',
      fr: 'Échec de l’enregistrement du taux de taxe',
      es: 'No se pudo guardar el tipo impositivo',
      pt: 'Falha ao salvar a alíquota',
      tr: 'Vergi oranı kaydedilemedi',
      uk: 'Не вдалося зберегти податкову ставку',
      zh: '保存税率失败',
      ar: 'فشل حفظ نسبة الضريبة',
      pl: 'Nie udało się zapisać stawki podatku',
      it: 'Impossibile salvare l’aliquota',
      sk: 'Sadzbu dane sa nepodarilo uložiť',
      ja: '税率を保存できませんでした',
      ko: '세율을 저장하지 못했습니다',
      hi: 'कर दर सहेजने में विफल',
      nl: 'Belastingtarief opslaan mislukt',
      sv: 'Det gick inte att spara skattesatsen',
      vi: 'Không lưu được thuế suất',
      id: 'Gagal menyimpan tarif pajak',
    }),
  },
} satisfies Dictionary;

export default content;
