/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementsListUi',
  content: {
    groupLabel: t({
      ru: 'Группа {label}',
      en: 'Group {label}',
      kk: '{label} тобы',
      de: 'Gruppe {label}',
      fr: 'Groupe {label}',
      es: 'Grupo {label}',
      pt: 'Grupo {label}',
      tr: 'Grup {label}',
      uk: 'Група {label}',
      zh: '{label} 组',
      pl: 'Grupa {label}',
      it: 'Gruppo {label}',
      sk: 'Skupina {label}',
      ja: 'グループ {label}',
      ko: '그룹 {label}',
      hi: 'समूह {label}',
      nl: 'Groep {label}',
      sv: 'Grupp {label}',
      vi: 'Nhóm {label}',
      id: 'Grup {label}',
      da: 'Gruppe {label}',
      nb: 'Gruppe {label}',
      nn: 'Gruppe {label}',
      fi: 'Ryhmä {label}',
      fo: 'Bólkur {label}',
      is: 'Hópur {label}',
      cs: 'Skupina {label}',
      bg: 'Група {label}',
      hr: 'Grupa {label}',
      sr: 'Група {label}',
      sl: 'Skupina {label}',
      mk: 'Група {label}',
      be: 'Група {label}',
      bs: 'Grupa {label}',
      hsb: 'Skupina {label}',
    }),
    group: t({
      ru: 'Группа',
      en: 'Group',
      kk: 'Топ',
      de: 'Gruppe',
      fr: 'Groupe',
      es: 'Grupo',
      pt: 'Grupo',
      tr: 'Grup',
      uk: 'Група',
      zh: '组',
      pl: 'Grupa',
      it: 'Gruppo',
      sk: 'Skupina',
      ja: 'グループ',
      ko: '그룹',
      hi: 'समूह',
      nl: 'Groep',
      sv: 'Grupp',
      vi: 'Nhóm',
      id: 'Grup',
      da: 'Gruppe',
      nb: 'Gruppe',
      nn: 'Gruppe',
      fi: 'Ryhmä',
      fo: 'Bólkur',
      is: 'Hópur',
      cs: 'Skupina',
      bg: 'Група',
      hr: 'Grupa',
      sr: 'Група',
      sl: 'Skupina',
      mk: 'Група',
      be: 'Група',
      bs: 'Grupa',
      hsb: 'Skupina',
    }),
    groupManual: t({
      ru: 'Ручная группа',
      en: 'Manual group',
      kk: 'Қолмен жасалған топ',
      de: 'Manuelle Gruppe',
      fr: 'Groupe manuel',
      es: 'Grupo manual',
      pt: 'Grupo manual',
      tr: 'Manuel grup',
      uk: 'Ручна група',
      zh: '手动组',
      pl: 'Grupa ręczna',
      it: 'Gruppo manuale',
      sk: 'Manuálna skupina',
      ja: '手動グループ',
      ko: '수동 그룹',
      hi: 'मैनुअल समूह',
      nl: 'Handmatige groep',
      sv: 'Manuell grupp',
      vi: 'Nhóm thủ công',
      id: 'Grup manual',
      da: 'Manuel gruppe',
      nb: 'Manuell gruppe',
      nn: 'Manuell gruppe',
      fi: 'Käsin tehty ryhmä',
      fo: 'Handgjørdur bólkur',
      is: 'Handvirkur hópur',
      cs: 'Ruční skupina',
      bg: 'Ръчна група',
      hr: 'Ručna grupa',
      sr: 'Ручна група',
      sl: 'Ročna skupina',
      mk: 'Рачна група',
      be: 'Ручная група',
      bs: 'Ručna grupa',
      hsb: 'Ručna skupina',
    }),
    duplicateReasonSame: t({
      ru: 'Тот же продавец · та же дата · та же сумма',
      en: 'Same merchant · same date · same amount',
      kk: 'Сол сатушы · сол күн · сол сома',
      de: 'Gleicher Händler · gleiches Datum · gleicher Betrag',
      fr: 'Même marchand · même date · même montant',
      es: 'Mismo comercio · misma fecha · mismo importe',
      pt: 'Mesmo comerciante · mesma data · mesmo valor',
      tr: 'Aynı satıcı · aynı tarih · aynı tutar',
      uk: 'Той самий продавець · та сама дата · та сама сума',
      zh: '同一商户 · 同一日期 · 同一金额',
      pl: 'Ten sam sprzedawca · ta sama data · ta sama kwota',
      it: 'Stesso esercente · stessa data · stesso importo',
      sk: 'Rovnaký obchodník · rovnaký dátum · rovnaká suma',
      ja: '同じ加盟店 · 同じ日付 · 同じ金額',
      ko: '같은 가맹점 · 같은 날짜 · 같은 금액',
      hi: 'वही व्यापारी · वही तारीख · वही राशि',
      nl: 'Zelfde handelaar · zelfde datum · zelfde bedrag',
      sv: 'Samma handlare · samma datum · samma belopp',
      vi: 'Cùng người bán · cùng ngày · cùng số tiền',
      id: 'Pedagang sama · tanggal sama · jumlah sama',
      da: 'Samme forhandler · samme dato · samme beløb',
      nb: 'Samme forhandler · samme dato · samme beløp',
      nn: 'Same forhandlar · same dato · same sum',
      fi: 'Sama kauppias · sama päivä · sama summa',
      fo: 'Sami handlari · sami dagur · sama upphædd',
      is: 'Sami seljandi · sama dagsetning · sama fjárhæð',
      cs: 'Stejný obchodník · stejné datum · stejná částka',
      bg: 'Същият търговец · същата дата · същата сума',
      hr: 'Isti trgovac · isti datum · isti iznos',
      sr: 'Исти трговац · исти датум · исти износ',
      sl: 'Isti trgovec · isti datum · isti znesek',
      mk: 'Истиот трговец · истиот датум · истиот износ',
      be: 'Тая ж крама · тая ж дата · тая ж сума',
      bs: 'Isti trgovac · isti datum · isti iznos',
      hsb: 'Samsny wikowar · samsny datum · samsna suma',
    }),
    duplicateReasonManual: t({
      ru: 'Отмечено как дубликат вручную',
      en: 'Marked manually as duplicate',
      kk: 'Қолмен көшірме деп белгіленген',
      de: 'Manuell als Duplikat markiert',
      fr: 'Marqué manuellement comme doublon',
      es: 'Marcado manualmente como duplicado',
      pt: 'Marcado manualmente como duplicado',
      tr: 'Manuel olarak kopya işaretlendi',
      uk: 'Позначено як дублікат вручну',
      zh: '已手动标记为重复',
      pl: 'Oznaczono ręcznie jako duplikat',
      it: 'Contrassegnato manualmente come duplicato',
      sk: 'Ručne označené ako duplikát',
      ja: '手動で重複としてマーク',
      ko: '수동으로 중복 표시됨',
      hi: 'मैन्युअल रूप से डुप्लिकेट चिह्नित',
      nl: 'Handmatig gemarkeerd als duplicaat',
      sv: 'Manuellt markerad som dubblett',
      vi: 'Đã đánh dấu trùng lặp thủ công',
      id: 'Ditandai manual sebagai duplikat',
      da: 'Markeret manuelt som dublet',
      nb: 'Merket manuelt som duplikat',
      nn: 'Merkt manuelt som duplikat',
      fi: 'Merkitty käsin kaksoiskappaleeksi',
      fo: 'Handgjørt merkt sum avrit',
      is: 'Merkt handvirkt sem tvítak',
      cs: 'Ručně označeno jako duplicita',
      bg: 'Ръчно отбелязано като дублирано',
      hr: 'Ručno označeno kao duplikat',
      sr: 'Ручно означено као дупликат',
      sl: 'Ročno označeno kot dvojnik',
      mk: 'Рачно означено како дупликат',
      be: 'Пазначана ўручную як дублікат',
      bs: 'Ručno označeno kao duplikat',
      hsb: 'Ručnje jako dwójnik markěrowane',
    }),
    rolePrimary: t({
      ru: 'ОСНОВНОЙ',
      en: 'PRIMARY',
      kk: 'НЕГІЗГІ',
      de: 'PRIMÄR',
      fr: 'PRINCIPAL',
      es: 'PRINCIPAL',
      pt: 'PRINCIPAL',
      tr: 'BİRİNCİL',
      uk: 'ОСНОВНИЙ',
      zh: '主记录',
      pl: 'GŁÓWNY',
      it: 'PRINCIPALE',
      sk: 'HLAVNÝ',
      ja: 'プライマリ',
      ko: '기본',
      hi: 'प्राथमिक',
      nl: 'PRIMAIR',
      sv: 'PRIMÄR',
      vi: 'CHÍNH',
      id: 'UTAMA',
      da: 'PRIMÆR',
      nb: 'PRIMÆR',
      nn: 'PRIMÆR',
      fi: 'ENSISIJAINEN',
      fo: 'HØVUÐS',
      is: 'AÐAL',
      cs: 'HLAVNÍ',
      bg: 'ОСНОВЕН',
      hr: 'GLAVNI',
      sr: 'ГЛАВНИ',
      sl: 'GLAVNI',
      mk: 'ГЛАВЕН',
      be: 'АСНОЎНЫ',
      bs: 'GLAVNI',
      hsb: 'HŁOWNY',
    }),
    roleSuspected: t({
      ru: 'ВОЗМОЖНЫЙ',
      en: 'SUSPECTED',
      kk: 'КҮДІКТІ',
      de: 'VERDÄCHTIG',
      fr: 'SUSPECT',
      es: 'SOSPECHOSO',
      pt: 'SUSPEITO',
      tr: 'ŞÜPHELİ',
      uk: 'ЙМОВІРНИЙ',
      zh: '疑似',
      pl: 'PODEJRZANY',
      it: 'SOSPETTO',
      sk: 'PODOZRIVÝ',
      ja: '疑い',
      ko: '의심',
      hi: 'संदिग्ध',
      nl: 'VERDACHT',
      sv: 'MISSTÄNKT',
      vi: 'NGHI NGỜ',
      id: 'DIDUGA',
      da: 'FORMODET',
      nb: 'ANTATT',
      nn: 'ANTEKEN',
      fi: 'EPÄILTY',
      fo: 'VÆNTAÐ',
      is: 'ÆTLAÐ',
      cs: 'PODEZŘELÁ',
      bg: 'ПРЕДПОЛАГАЕМ',
      hr: 'PRETPOSTAVLJENI',
      sr: 'ПРЕТПОСТАВЉЕНИ',
      sl: 'DOMNEVNI',
      mk: 'ПРЕТПОСТАВЕН',
      be: 'ВЕРАГОДНЫ',
      bs: 'PRETPOSTAVLJENI',
      hsb: 'PŘEDPOKLADANY',
    }),
    review: t({
      ru: 'Проверить',
      en: 'Review',
      kk: 'Тексеру',
      de: 'Prüfen',
      fr: 'Vérifier',
      es: 'Revisar',
      pt: 'Revisar',
      tr: 'İncele',
      uk: 'Перевірити',
      zh: '审核',
      pl: 'Sprawdź',
      it: 'Verifica',
      sk: 'Skontrolovať',
      ja: '確認',
      ko: '검토',
      hi: 'समीक्षा',
      nl: 'Controleren',
      sv: 'Granska',
      vi: 'Xem xét',
      id: 'Tinjau',
      da: 'Gennemgå',
      nb: 'Gjennomgå',
      nn: 'Gå gjennom',
      fi: 'Tarkista',
      fo: 'Eftirlit',
      is: 'Skoða',
      cs: 'Zkontrolovat',
      bg: 'Преглед',
      hr: 'Pregledaj',
      sr: 'Прегледај',
      sl: 'Preglej',
      mk: 'Прегледај',
      be: 'Праверыць',
      bs: 'Pregledaj',
      hsb: 'Přepruwować',
    }),
    typeReceipt: t({
      ru: 'Чек',
      en: 'Receipt',
      kk: 'Чек',
      de: 'Beleg',
      fr: 'Reçu',
      es: 'Recibo',
      pt: 'Recibo',
      tr: 'Fiş',
      uk: 'Чек',
      zh: '收据',
      pl: 'Paragon',
      it: 'Ricevuta',
      sk: 'Doklad',
      ja: 'レシート',
      ko: '영수증',
      hi: 'रसीद',
      nl: 'Bon',
      sv: 'Kvitto',
      vi: 'Hóa đơn',
      id: 'Struk',
      da: 'Beløb',
      nb: 'Beløp',
      nn: 'Beløp',
      fi: 'Summa',
      is: 'Fjárhæð',
      fo: 'Sum',
      cs: 'Částka',
      bg: 'Сума',
      hr: 'Iznos',
      sr: 'Износ',
      sl: 'Znesek',
      mk: 'Сума',
      be: 'Сума',
      bs: 'Iznos',
      hsb: 'Suma',
    }),
    user: t({
      ru: 'Пользователь',
      en: 'User',
      kk: 'Пайдаланушы',
      de: 'Benutzer',
      fr: 'Utilisateur',
      es: 'Usuario',
      pt: 'Usuário',
      tr: 'Kullanıcı',
      uk: 'Користувач',
      zh: '用户',
      pl: 'Użytkownik',
      it: 'Utente',
      sk: 'Používateľ',
      ja: 'ユーザー',
      ko: '사용자',
      hi: 'उपयोगकर्ता',
      nl: 'Gebruiker',
      sv: 'Användare',
      vi: 'Người dùng',
      id: 'Pengguna',
      da: 'Bruger',
      nb: 'Bruker',
      nn: 'Brukar',
      fi: 'Käyttäjä',
      is: 'Notandi',
      fo: 'Brúkari',
      cs: 'Uživatel',
      bg: 'Потребител',
      hr: 'Korisnik',
      sr: 'Корисник',
      sl: 'Uporabnik',
      mk: 'Корисник',
      be: 'Карыстальнік',
      bs: 'Korisnik',
      hsb: 'Wužiwar',
    }),
    statusError: t({
      ru: 'Ошибка',
      en: 'Error',
      kk: 'Қате',
      de: 'Fehler',
      fr: 'Erreur',
      es: 'Error',
      pt: 'Erro',
      tr: 'Hata',
      uk: 'Помилка',
      zh: '错误',
      pl: 'Błąd',
      it: 'Errore',
      sk: 'Chyba',
      ja: 'エラー',
      ko: '오류',
      hi: 'त्रुटि',
      nl: 'Fout',
      sv: 'Fel',
      vi: 'Lỗi',
      id: 'Kesalahan',
      da: 'Fejl',
      nb: 'Feil',
      nn: 'Feil',
      fi: 'Virhe',
      is: 'Villa',
      fo: 'Feilur',
      cs: 'Chyba',
      bg: 'Грешка',
      hr: 'Pogreška',
      sr: 'Грешка',
      sl: 'Napaka',
      mk: 'Грешка',
      be: 'Памылка',
      bs: 'Greška',
      hsb: 'Zmylk',
    }),
    statusPending: t({
      ru: 'В обработке',
      en: 'Pending',
      kk: 'Өңделуде',
      de: 'Ausstehend',
      fr: 'En attente',
      es: 'Pendiente',
      pt: 'Pendente',
      tr: 'Beklemede',
      uk: 'В обробці',
      zh: '待处理',
      pl: 'Oczekuje',
      it: 'In attesa',
      sk: 'Čaká',
      ja: '保留中',
      ko: '대기 중',
      hi: 'लंबित',
      nl: 'In behandeling',
      sv: 'Väntar',
      vi: 'Đang chờ',
      id: 'Tertunda',
      da: 'Afventer',
      nb: 'Venter',
      nn: 'Ventar',
      fi: 'Odottaa',
      is: 'Í bið',
      fo: 'Bíðar',
      cs: 'Čeká',
      bg: 'Изчаква',
      hr: 'Na čekanju',
      sr: 'На чекању',
      sl: 'V čakanju',
      mk: 'Чека',
      be: 'Чакае',
      bs: 'Na čekanju',
      hsb: 'Čaka',
    }),
    statusNeedsReview: t({
      ru: 'Требует проверки',
      en: 'Needs review',
      kk: 'Тексеруді қажет етеді',
      de: 'Prüfung nötig',
      fr: 'À vérifier',
      es: 'Requiere revisión',
      pt: 'Precisa de revisão',
      tr: 'İnceleme gerekli',
      uk: 'Потребує перевірки',
      zh: '需要审核',
      pl: 'Wymaga sprawdzenia',
      it: 'Da verificare',
      sk: 'Vyžaduje kontrolu',
      ja: '要確認',
      ko: '검토 필요',
      hi: 'समीक्षा आवश्यक',
      nl: 'Controle nodig',
      sv: 'Behöver granskas',
      vi: 'Cần xem xét',
      id: 'Perlu ditinjau',
      da: 'Kræver gennemgang',
      nb: 'Krever gjennomgang',
      nn: 'Krev gjennomgang',
      fi: 'Vaatii tarkistusta',
      is: 'Þarf yfirferð',
      fo: 'Krevur eftirlit',
      cs: 'Vyžaduje kontrolu',
      bg: 'Нужен е преглед',
      hr: 'Potreban pregled',
      sr: 'Потребан преглед',
      sl: 'Potrebuje pregled',
      mk: 'Потребен е преглед',
      be: 'Патрэбна праверка',
      bs: 'Potreban pregled',
      hsb: 'Trjeba přepruwowanje',
    }),
    toReview: t({
      ru: 'К проверке',
      en: 'To review',
      kk: 'Тексеруге',
      de: 'Zu prüfen',
      fr: 'À vérifier',
      es: 'Por revisar',
      pt: 'Para revisar',
      tr: 'İncelenecek',
      uk: 'До перевірки',
      zh: '待审核',
      pl: 'Do sprawdzenia',
      it: 'Da verificare',
      sk: 'Na kontrolu',
      ja: '要確認',
      ko: '검토 대기',
      hi: 'समीक्षा बाकी',
      nl: 'Te controleren',
      sv: 'Att granska',
      vi: 'Chờ xem xét',
      id: 'Perlu ditinjau',
      da: 'Til gennemgang',
      nb: 'Til gjennomgang',
      nn: 'Til gjennomgang',
      fi: 'Tarkistettavana',
      is: 'Til yfirferðar',
      fo: 'Til eftirlits',
      cs: 'Ke kontrole',
      bg: 'За преглед',
      hr: 'Za pregled',
      sr: 'За преглед',
      sl: 'Za pregled',
      mk: 'За преглед',
      be: 'Да праверкі',
      bs: 'Za pregled',
      hsb: 'K přepruwowanju',
    }),
    statusCompleted: t({
      ru: 'Завершено',
      en: 'Completed',
      kk: 'Аяқталды',
      de: 'Abgeschlossen',
      fr: 'Terminé',
      es: 'Completado',
      pt: 'Concluído',
      tr: 'Tamamlandı',
      uk: 'Завершено',
      zh: '已完成',
      pl: 'Zakończono',
      it: 'Completato',
      sk: 'Dokončené',
      ja: '完了',
      ko: '완료',
      hi: 'पूर्ण',
      nl: 'Voltooid',
      sv: 'Slutförd',
      vi: 'Hoàn tất',
      id: 'Selesai',
      da: 'Færdig',
      nb: 'Fullført',
      nn: 'Fullført',
      fi: 'Valmis',
      is: 'Lokið',
      fo: 'Liðugt',
      cs: 'Hotovo',
      bg: 'Готово',
      hr: 'Dovršeno',
      sr: 'Завршено',
      sl: 'Zaključeno',
      mk: 'Завршено',
      be: 'Завершана',
      bs: 'Završeno',
      hsb: 'Dokónčene',
    }),
    yes: t({
      ru: 'Да',
      en: 'Yes',
      kk: 'Иә',
      de: 'Ja',
      fr: 'Oui',
      es: 'Sí',
      pt: 'Sim',
      tr: 'Evet',
      uk: 'Так',
      zh: '是',
      pl: 'Tak',
      it: 'Sì',
      sk: 'Áno',
      ja: 'はい',
      ko: '예',
      hi: 'हाँ',
      nl: 'Ja',
      sv: 'Ja',
      vi: 'Có',
      id: 'Ya',
      da: 'Ja',
      nb: 'Ja',
      nn: 'Ja',
      fi: 'Kyllä',
      is: 'Já',
      fo: 'Ja',
      cs: 'Ano',
      bg: 'Да',
      hr: 'Da',
      sr: 'Да',
      sl: 'Da',
      mk: 'Да',
      be: 'Так',
      bs: 'Da',
      hsb: 'Haj',
    }),
    no: t({
      ru: 'Нет',
      en: 'No',
      kk: 'Жоқ',
      de: 'Nein',
      fr: 'Non',
      es: 'No',
      pt: 'Não',
      tr: 'Hayır',
      uk: 'Ні',
      zh: '否',
      pl: 'Nie',
      it: 'No',
      sk: 'Nie',
      ja: 'いいえ',
      ko: '아니요',
      hi: 'नहीं',
      nl: 'Nee',
      sv: 'Nej',
      vi: 'Không',
      id: 'Tidak',
      da: 'Nej',
      nb: 'Nei',
      nn: 'Nei',
      fi: 'Ei',
      is: 'Nei',
      fo: 'Nei',
      cs: 'Ne',
      bg: 'Не',
      hr: 'Ne',
      sr: 'Не',
      sl: 'Ne',
      mk: 'Не',
      be: 'Не',
      bs: 'Ne',
      hsb: 'Ně',
    }),
    mixed: t({
      ru: 'Разные',
      en: 'Mixed',
      kk: 'Аралас',
      de: 'Gemischt',
      fr: 'Mixte',
      es: 'Mixto',
      pt: 'Misto',
      tr: 'Karışık',
      uk: 'Різні',
      zh: '混合',
      pl: 'Mieszane',
      it: 'Misto',
      sk: 'Zmiešané',
      ja: '混在',
      ko: '혼합',
      hi: 'मिश्रित',
      nl: 'Gemengd',
      sv: 'Blandat',
      vi: 'Hỗn hợp',
      id: 'Campuran',
      da: 'Blandet',
      nb: 'Blandet',
      nn: 'Blanda',
      fi: 'Sekalainen',
      fo: 'Blandað',
      is: 'Blandað',
      cs: 'Smíšené',
      bg: 'Смесено',
      hr: 'Mješovito',
      sr: 'Мешовито',
      sl: 'Mešano',
      mk: 'Мешано',
      be: 'Змешана',
      bs: 'Miješano',
      hsb: 'Měšane',
    }),
    processing: t({
      ru: 'Обработка...',
      en: 'Processing...',
      kk: 'Өңделуде...',
      de: 'Wird verarbeitet...',
      fr: 'Traitement...',
      es: 'Procesando...',
      pt: 'Processando...',
      tr: 'İşleniyor...',
      uk: 'Обробка...',
      zh: '处理中...',
      pl: 'Przetwarzanie...',
      it: 'Elaborazione...',
      sk: 'Spracúva sa...',
      ja: '処理中...',
      ko: '처리 중...',
      hi: 'प्रोसेस हो रहा है...',
      nl: 'Verwerken...',
      sv: 'Bearbetar...',
      vi: 'Đang xử lý...',
      id: 'Memproses...',
      da: 'Behandler ...',
      nb: 'Behandler ...',
      nn: 'Handsamar ...',
      fi: 'Käsitellään ...',
      fo: 'Viðgerð ...',
      is: 'Vinnur ...',
      cs: 'Zpracování ...',
      bg: 'Обработване ...',
      hr: 'Obrada ...',
      sr: 'Обрада ...',
      sl: 'Obdelava ...',
      mk: 'Обработка ...',
      be: 'Апрацоўка ...',
      bs: 'Obrada ...',
      hsb: 'Předźěłanje ...',
    }),
    selectAllStatements: t({
      ru: 'Выбрать все выписки',
      en: 'Select all statements',
      kk: 'Барлық үзінділерді таңдау',
      de: 'Alle Kontoauszüge auswählen',
      fr: 'Sélectionner tous les relevés',
      es: 'Seleccionar todos los extractos',
      pt: 'Selecionar todos os extratos',
      tr: 'Tüm ekstreleri seç',
      uk: 'Вибрати всі виписки',
      zh: '选择所有对账单',
      pl: 'Zaznacz wszystkie wyciągi',
      it: 'Seleziona tutti gli estratti',
      sk: 'Vybrať všetky výpisy',
      ja: 'すべての明細書を選択',
      ko: '모든 명세서 선택',
      hi: 'सभी स्टेटमेंट चुनें',
      nl: 'Alle afschriften selecteren',
      sv: 'Välj alla utdrag',
      vi: 'Chọn tất cả sao kê',
      id: 'Pilih semua laporan',
      da: 'Vælg alle kontoudtog',
      nb: 'Velg alle kontoutskrifter',
      nn: 'Vel alle kontoutskrifter',
      fi: 'Valitse kaikki tiliotteet',
      fo: 'Vel øll kontoyvirlit',
      is: 'Velja öll yfirlit',
      cs: 'Vybrat všechny výpisy',
      bg: 'Избор на всички извлечения',
      hr: 'Odaberi sve izvatke',
      sr: 'Изабери све изводе',
      sl: 'Izberi vse izpiske',
      mk: 'Избери ги сите изводи',
      be: 'Выбраць усе выпіскі',
      bs: 'Izaberi sve izvode',
      hsb: 'Wšě wujimki wubrać',
    }),
    sortByDateAsc: t({
      ru: 'Сортировать по дате по возрастанию',
      en: 'Sort by date ascending',
      kk: 'Күні бойынша өсу ретімен сұрыптау',
      de: 'Nach Datum aufsteigend sortieren',
      fr: 'Trier par date croissante',
      es: 'Ordenar por fecha ascendente',
      pt: 'Ordenar por data crescente',
      tr: 'Tarihe göre artan sırala',
      uk: 'Сортувати за датою за зростанням',
      zh: '按日期升序排序',
      pl: 'Sortuj według daty rosnąco',
      it: 'Ordina per data crescente',
      sk: 'Zoradiť podľa dátumu vzostupne',
      ja: '日付の昇順で並べ替え',
      ko: '날짜 오름차순 정렬',
      hi: 'तारीख के अनुसार आरोही क्रम में',
      nl: 'Sorteren op datum oplopend',
      sv: 'Sortera efter datum stigande',
      vi: 'Sắp xếp theo ngày tăng dần',
      id: 'Urutkan menurut tanggal naik',
      da: 'Sortér efter dato stigende',
      nb: 'Sorter etter dato stigende',
      nn: 'Sorter etter dato stigande',
      fi: 'Järjestä päivän mukaan nousevasti',
      fo: 'Raðfest eftir degi hækkandi',
      is: 'Raða eftir dagsetningu hækkandi',
      cs: 'Řadit podle data vzestupně',
      bg: 'Подреждане по дата възходящо',
      hr: 'Sortiraj po datumu rastuće',
      sr: 'Сортирај по датуму растуће',
      sl: 'Razvrsti po datumu naraščajoče',
      mk: 'Сортирај по датум растечки',
      be: 'Сартаваць па даце па ўзрастанні',
      bs: 'Sortiraj po datumu rastuće',
      hsb: 'Po datumje postupowacy rjadować',
    }),
    sortByDateDesc: t({
      ru: 'Сортировать по дате по убыванию',
      en: 'Sort by date descending',
      kk: 'Күні бойынша кему ретімен сұрыптау',
      de: 'Nach Datum absteigend sortieren',
      fr: 'Trier par date décroissante',
      es: 'Ordenar por fecha descendente',
      pt: 'Ordenar por data decrescente',
      tr: 'Tarihe göre azalan sırala',
      uk: 'Сортувати за датою за спаданням',
      zh: '按日期降序排序',
      pl: 'Sortuj według daty malejąco',
      it: 'Ordina per data decrescente',
      sk: 'Zoradiť podľa dátumu zostupne',
      ja: '日付の降順で並べ替え',
      ko: '날짜 내림차순 정렬',
      hi: 'तारीख के अनुसार अवरोही क्रम में',
      nl: 'Sorteren op datum aflopend',
      sv: 'Sortera efter datum fallande',
      vi: 'Sắp xếp theo ngày giảm dần',
      id: 'Urutkan menurut tanggal turun',
      da: 'Sortér efter dato faldende',
      nb: 'Sorter etter dato synkende',
      nn: 'Sorter etter dato fallande',
      fi: 'Järjestä päivän mukaan laskevasti',
      fo: 'Raðfest eftir degi fallandi',
      is: 'Raða eftir dagsetningu lækkandi',
      cs: 'Řadit podle data sestupně',
      bg: 'Подреждане по дата низходящо',
      hr: 'Sortiraj po datumu padajuće',
      sr: 'Сортирај по датуму опадајуће',
      sl: 'Razvrsti po datumu padajoče',
      mk: 'Сортирај по датум опаѓачки',
      be: 'Сартаваць па даце па змяншэнні',
      bs: 'Sortiraj po datumu opadajuće',
      hsb: 'Po datumje spadowacy rjadować',
    }),
    selectedCount: t({
      ru: 'Выбрано: {count}',
      en: '{count} selected',
      kk: 'Таңдалды: {count}',
      de: '{count} ausgewählt',
      fr: '{count} sélectionné(s)',
      es: '{count} seleccionados',
      pt: '{count} selecionados',
      tr: '{count} seçildi',
      uk: 'Вибрано: {count}',
      zh: '已选择 {count} 项',
      pl: 'Zaznaczono: {count}',
      it: '{count} selezionati',
      sk: 'Vybrané: {count}',
      ja: '{count} 件選択中',
      ko: '{count}개 선택됨',
      hi: '{count} चयनित',
      nl: '{count} geselecteerd',
      sv: '{count} valda',
      vi: 'Đã chọn {count}',
      id: '{count} dipilih',
      da: '{count} valgt',
      nb: '{count} valgt',
      nn: '{count} valde',
      fi: '{count} valittu',
      fo: '{count} vald',
      is: '{count} valin',
      cs: 'Vybráno: {count}',
      bg: 'Избрани: {count}',
      hr: 'Odabrano: {count}',
      sr: 'Изабрано: {count}',
      sl: 'Izbranih: {count}',
      mk: 'Избрани: {count}',
      be: 'Выбрана: {count}',
      bs: 'Izabrano: {count}',
      hsb: 'Wubrane: {count}',
    }),
    export: t({
      ru: 'Экспорт',
      en: 'Export',
      kk: 'Экспорт',
      de: 'Exportieren',
      fr: 'Exporter',
      es: 'Exportar',
      pt: 'Exportar',
      tr: 'Dışa aktar',
      uk: 'Експорт',
      zh: '导出',
      pl: 'Eksportuj',
      it: 'Esporta',
      sk: 'Exportovať',
      ja: 'エクスポート',
      ko: '내보내기',
      hi: 'निर्यात',
      nl: 'Exporteren',
      sv: 'Exportera',
      vi: 'Xuất',
      id: 'Ekspor',
      da: 'Eksportér',
      nb: 'Eksporter',
      nn: 'Eksporter',
      fi: 'Vie',
      is: 'Flytja út',
      fo: 'Flyt út',
      cs: 'Exportovat',
      bg: 'Експортирай',
      hr: 'Izvezi',
      sr: 'Извези',
      sl: 'Izvozi',
      mk: 'Извези',
      be: 'Экспартаваць',
      bs: 'Izvezi',
      hsb: 'Eksportować',
    }),
    delete: t({
      ru: 'Удалить',
      en: 'Delete',
      kk: 'Жою',
      de: 'Löschen',
      fr: 'Supprimer',
      es: 'Eliminar',
      pt: 'Excluir',
      tr: 'Sil',
      uk: 'Видалити',
      zh: '删除',
      pl: 'Usuń',
      it: 'Elimina',
      sk: 'Odstrániť',
      ja: '削除',
      ko: '삭제',
      hi: 'हटाएँ',
      nl: 'Verwijderen',
      sv: 'Ta bort',
      vi: 'Xóa',
      id: 'Hapus',
      da: 'Slet',
      nb: 'Slett',
      nn: 'Slett',
      fi: 'Poista',
      is: 'Eyða',
      fo: 'Strika',
      cs: 'Smazat',
      bg: 'Изтрий',
      hr: 'Izbriši',
      sr: 'Избриши',
      sl: 'Izbriši',
      mk: 'Избриши',
      be: 'Выдаліць',
      bs: 'Izbriši',
      hsb: 'Zhašeć',
    }),
    submit: t({
      ru: 'Отправить',
      en: 'Submit',
      kk: 'Жіберу',
      de: 'Einreichen',
      fr: 'Soumettre',
      es: 'Enviar',
      pt: 'Enviar',
      tr: 'Gönder',
      uk: 'Надіслати',
      zh: '提交',
      pl: 'Wyślij',
      it: 'Invia',
      sk: 'Odoslať',
      ja: '提出',
      ko: '제출',
      hi: 'सबमिट करें',
      nl: 'Indienen',
      sv: 'Skicka in',
      vi: 'Gửi',
      id: 'Kirim',
      da: 'Indsend',
      nb: 'Send inn',
      nn: 'Send inn',
      fi: 'Lähetä',
      is: 'Senda',
      fo: 'Lat inn',
      cs: 'Odeslat',
      bg: 'Подай',
      hr: 'Predaj',
      sr: 'Поднеси',
      sl: 'Oddaj',
      mk: 'Поднеси',
      be: 'Падаць',
      bs: 'Predaj',
      hsb: 'Zapodać',
    }),
    unapprove: t({
      ru: 'Отменить одобрение',
      en: 'Unapprove',
      kk: 'Мақұлдауды болдырмау',
      de: 'Genehmigung aufheben',
      fr: "Annuler l'approbation",
      es: 'Anular aprobación',
      pt: 'Cancelar aprovação',
      tr: 'Onayı kaldır',
      uk: 'Скасувати схвалення',
      zh: '取消批准',
      pl: 'Cofnij zatwierdzenie',
      it: 'Annulla approvazione',
      sk: 'Zrušiť schválenie',
      ja: '承認を取り消す',
      ko: '승인 취소',
      hi: 'स्वीकृति रद्द करें',
      nl: 'Goedkeuring intrekken',
      sv: 'Återkalla godkännande',
      vi: 'Hủy phê duyệt',
      id: 'Batalkan persetujuan',
      da: 'Træk godkendelsen tilbage',
      nb: 'Trekk tilbake godkjenningen',
      nn: 'Trekk tilbake godkjenninga',
      fi: 'Peru hyväksyntä',
      is: 'Afturkalla samþykki',
      fo: 'Tak góðkenningina aftur',
      cs: 'Zrušit schválení',
      bg: 'Оттегли одобрението',
      hr: 'Povuci odobrenje',
      sr: 'Повуци одобрење',
      sl: 'Prekliči odobritev',
      mk: 'Повлечи одобрување',
      be: 'Адклікаць узгадненне',
      bs: 'Povuci odobrenje',
      hsb: 'Přizwolenje cofnyć',
    }),
    manualExpenseCreated: t({
      ru: 'Ручной расход создан',
      en: 'Manual expense created',
      kk: 'Қолмен енгізілген шығыс жасалды',
      de: 'Manuelle Ausgabe erstellt',
      fr: 'Dépense manuelle créée',
      es: 'Gasto manual creado',
      pt: 'Despesa manual criada',
      tr: 'Manuel gider oluşturuldu',
      uk: 'Ручну витрату створено',
      zh: '已创建手动支出',
      pl: 'Utworzono wydatek ręczny',
      it: 'Spesa manuale creata',
      sk: 'Manuálny výdavok bol vytvorený',
      ja: '手動の経費を作成しました',
      ko: '수동 지출이 생성되었습니다',
      hi: 'मैनुअल खर्च बनाया गया',
      nl: 'Handmatige uitgave aangemaakt',
      sv: 'Manuell utgift skapad',
      vi: 'Đã tạo chi phí thủ công',
      id: 'Pengeluaran manual dibuat',
      da: 'Manuel udgift oprettet',
      nb: 'Manuell utgift opprettet',
      nn: 'Manuell utgift oppretta',
      fi: 'Käsin lisätty kulu luotiin',
      fo: 'Handgjørd útreiðsla stovnað',
      is: 'Handvirkt útgjald búið til',
      cs: 'Ruční výdaj byl vytvořen',
      bg: 'Ръчният разход е създаден',
      hr: 'Ručni trošak je stvoren',
      sr: 'Ручни трошак је направљен',
      sl: 'Ročni strošek je ustvarjen',
      mk: 'Рачниот трошок е создаден',
      be: 'Ручны выдатак створаны',
      bs: 'Ručni trošak je napravljen',
      hsb: 'Ručny wudawk je wutworjeny',
    }),
    manualExpenseFailed: t({
      ru: 'Не удалось создать ручной расход',
      en: 'Failed to create manual expense',
      kk: 'Қолмен енгізілген шығысты жасау мүмкін болмады',
      de: 'Manuelle Ausgabe konnte nicht erstellt werden',
      fr: 'Impossible de créer la dépense manuelle',
      es: 'No se pudo crear el gasto manual',
      pt: 'Não foi possível criar a despesa manual',
      tr: 'Manuel gider oluşturulamadı',
      uk: 'Не вдалося створити ручну витрату',
      zh: '无法创建手动支出',
      pl: 'Nie udało się utworzyć wydatku ręcznego',
      it: 'Impossibile creare la spesa manuale',
      sk: 'Manuálny výdavok sa nepodarilo vytvoriť',
      ja: '手動の経費を作成できませんでした',
      ko: '수동 지출을 생성하지 못했습니다',
      hi: 'मैनुअल खर्च नहीं बनाया जा सका',
      nl: 'Handmatige uitgave aanmaken mislukt',
      sv: 'Det gick inte att skapa manuell utgift',
      vi: 'Không thể tạo chi phí thủ công',
      id: 'Gagal membuat pengeluaran manual',
      da: 'Den manuelle udgift kunne ikke oprettes',
      nb: 'Kunne ikke opprette den manuelle utgiften',
      nn: 'Kunne ikkje opprette den manuelle utgifta',
      fi: 'Käsin lisätyn kulun luonti epäonnistui',
      fo: 'Fekk ikki stovnað handgjørdu útreiðsluna',
      is: 'Ekki tókst að búa til handvirkt útgjald',
      cs: 'Ruční výdaj se nepodařilo vytvořit',
      bg: 'Ръчният разход не можа да бъде създаден',
      hr: 'Ručni trošak nije moguće stvoriti',
      sr: 'Ручни трошак није могуће направити',
      sl: 'Ročnega stroška ni bilo mogoče ustvariti',
      mk: 'Рачниот трошок не можеше да се создаде',
      be: 'Не ўдалося стварыць ручны выдатак',
      bs: 'Ručni trošak nije moguće napraviti',
      hsb: 'Ručny wudawk njeda so wutworić',
    }),
    manualExpenseUnavailable: t({
      ru: 'Создание ручных расходов пока недоступно',
      en: 'Manual expense creation is not available yet',
      kk: 'Қолмен шығыс жасау әзірге қолжетімсіз',
      de: 'Manuelle Ausgaben sind noch nicht verfügbar',
      fr: "La création de dépenses manuelles n'est pas encore disponible",
      es: 'La creación de gastos manuales aún no está disponible',
      pt: 'A criação de despesas manuais ainda não está disponível',
      tr: 'Manuel gider oluşturma henüz kullanılamıyor',
      uk: 'Створення ручних витрат поки недоступне',
      zh: '暂不支持创建手动支出',
      pl: 'Tworzenie wydatków ręcznych nie jest jeszcze dostępne',
      it: 'La creazione di spese manuali non è ancora disponibile',
      sk: 'Vytváranie manuálnych výdavkov zatiaľ nie je dostupné',
      ja: '手動の経費作成はまだ利用できません',
      ko: '수동 지출 생성은 아직 사용할 수 없습니다',
      hi: 'मैनुअल खर्च बनाना अभी उपलब्ध नहीं है',
      nl: 'Handmatige uitgaven aanmaken is nog niet beschikbaar',
      sv: 'Det går ännu inte att skapa manuella utgifter',
      vi: 'Chưa thể tạo chi phí thủ công',
      id: 'Pembuatan pengeluaran manual belum tersedia',
      da: 'Det er endnu ikke muligt at oprette manuelle udgifter',
      nb: 'Det er ennå ikke mulig å opprette manuelle utgifter',
      nn: 'Det er enno ikkje mogleg å opprette manuelle utgifter',
      fi: 'Käsin lisättyjen kulujen luonti ei ole vielä käytettävissä',
      fo: 'Tað er enn ikki møguligt at stovna handgjørdar útreiðslur',
      is: 'Ekki er enn unnt að búa til handvirk útgjöld',
      cs: 'Vytvářet ruční výdaje zatím není možné',
      bg: 'Създаването на ръчни разходи още не е достъпно',
      hr: 'Stvaranje ručnih troškova još nije dostupno',
      sr: 'Стварање ручних трошкова још није доступно',
      sl: 'Ustvarjanje ročnih stroškov še ni na voljo',
      mk: 'Создавањето на рачни трошоци уште не е достапно',
      be: 'Стварэнне ручных выдаткаў пакуль недаступнае',
      bs: 'Stvaranje ručnih troškova još nije dostupno',
      hsb: 'Wutworjenje ručnych wudawkow hišće k dispoziciji njeje',
    }),
    refreshing: t({
      ru: 'Обновление...',
      en: 'Refreshing...',
      kk: 'Жаңартылуда...',
      de: 'Wird aktualisiert...',
      fr: 'Actualisation...',
      es: 'Actualizando...',
      pt: 'Atualizando...',
      tr: 'Yenileniyor...',
      uk: 'Оновлення...',
      zh: '正在刷新...',
      pl: 'Odświeżanie...',
      it: 'Aggiornamento...',
      sk: 'Obnovuje sa...',
      ja: '更新中...',
      ko: '새로 고치는 중...',
      hi: 'रीफ़्रेश हो रहा है...',
      nl: 'Vernieuwen...',
      sv: 'Uppdaterar...',
      vi: 'Đang làm mới...',
      id: 'Menyegarkan...',
      da: 'Opdaterer ...',
      nb: 'Oppdaterer ...',
      nn: 'Oppdaterer ...',
      fi: 'Päivitetään ...',
      is: 'Uppfæri ...',
      fo: 'Dagførir ...',
      cs: 'Obnovuje se ...',
      bg: 'Обновява се ...',
      hr: 'Osvježava se ...',
      sr: 'Освежава се ...',
      sl: 'Osveževanje ...',
      mk: 'Се освежува ...',
      be: 'Абнаўленне ...',
      bs: 'Osvježava se ...',
      hsb: 'Aktualizuje so ...',
    }),
    releaseToRefresh: t({
      ru: 'Отпустите для обновления',
      en: 'Release to refresh',
      kk: 'Жаңарту үшін жіберіңіз',
      de: 'Loslassen zum Aktualisieren',
      fr: 'Relâchez pour actualiser',
      es: 'Suelta para actualizar',
      pt: 'Solte para atualizar',
      tr: 'Yenilemek için bırakın',
      uk: 'Відпустіть для оновлення',
      zh: '松开即可刷新',
      pl: 'Puść, aby odświeżyć',
      it: 'Rilascia per aggiornare',
      sk: 'Pustite na obnovenie',
      ja: '離して更新',
      ko: '놓아서 새로 고침',
      hi: 'रीफ़्रेश करने के लिए छोड़ें',
      nl: 'Loslaten om te vernieuwen',
      sv: 'Släpp för att uppdatera',
      vi: 'Thả để làm mới',
      id: 'Lepaskan untuk menyegarkan',
      da: 'Slip for at opdatere',
      nb: 'Slipp for å oppdatere',
      nn: 'Slepp for å oppdatere',
      fi: 'Vapauta päivittääksesi',
      is: 'Slepptu til að uppfæra',
      fo: 'Slepp fyri at dagføra',
      cs: 'Uvolněním obnovíte',
      bg: 'Пуснете, за да обновите',
      hr: 'Pustite za osvježavanje',
      sr: 'Пустите за освежавање',
      sl: 'Spustite za osvežitev',
      mk: 'Пуштете за освежување',
      be: 'Адпусціце, каб абнавіць',
      bs: 'Pustite za osvježavanje',
      hsb: 'Pušćće, zo byšće aktualizował',
    }),
    pullToRefresh: t({
      ru: 'Потяните для обновления',
      en: 'Pull to refresh',
      kk: 'Жаңарту үшін тартыңыз',
      de: 'Zum Aktualisieren ziehen',
      fr: 'Tirez pour actualiser',
      es: 'Desliza para actualizar',
      pt: 'Puxe para atualizar',
      tr: 'Yenilemek için çekin',
      uk: 'Потягніть для оновлення',
      zh: '下拉刷新',
      pl: 'Pociągnij, aby odświeżyć',
      it: 'Trascina per aggiornare',
      sk: 'Potiahnite na obnovenie',
      ja: '引っ張って更新',
      ko: '당겨서 새로 고침',
      hi: 'रीफ़्रेश करने के लिए खींचें',
      nl: 'Trek om te vernieuwen',
      sv: 'Dra för att uppdatera',
      vi: 'Kéo để làm mới',
      id: 'Tarik untuk menyegarkan',
      da: 'Træk for at opdatere',
      nb: 'Trekk for å oppdatere',
      nn: 'Dra for å oppdatere',
      fi: 'Vedä päivittääksesi',
      is: 'Dragðu til að uppfæra',
      fo: 'Trekk fyri at dagføra',
      cs: 'Přetažením obnovíte',
      bg: 'Плъзнете, за да обновите',
      hr: 'Povucite za osvježavanje',
      sr: 'Повуците за освежавање',
      sl: 'Povlecite za osvežitev',
      mk: 'Повлечете за освежување',
      be: 'Пацягніце, каб абнавіць',
      bs: 'Povucite za osvježavanje',
      hsb: 'Ćehńće, zo byšće aktualizował',
    }),
    mergeSummary: t({
      ru: 'Основные записи сохраняются. Дубликатов будет перемещено в корзину: {count}; их можно восстановить оттуда.',
      en: 'Primary records are kept. {count} duplicate item(s) will be moved to trash and can be restored from there.',
      kk: 'Негізгі жазбалар сақталады. Себетке жылжытылатын көшірмелер: {count}; оларды сол жерден қалпына келтіруге болады.',
      de: 'Primäre Datensätze bleiben erhalten. {count} Duplikat(e) werden in den Papierkorb verschoben und können dort wiederhergestellt werden.',
      fr: 'Les enregistrements principaux sont conservés. {count} doublon(s) seront déplacés dans la corbeille et pourront y être restaurés.',
      es: 'Los registros principales se conservan. {count} duplicado(s) se moverán a la papelera y podrán restaurarse desde allí.',
      pt: 'Os registros principais são mantidos. {count} duplicado(s) serão movidos para a lixeira e poderão ser restaurados de lá.',
      tr: 'Birincil kayıtlar korunur. {count} kopya çöp kutusuna taşınacak ve oradan geri yüklenebilecek.',
      uk: 'Основні записи зберігаються. Дублікатів буде переміщено до кошика: {count}; їх можна відновити звідти.',
      zh: '主记录将保留。{count} 个重复项将移至回收站，可从回收站恢复。',
      pl: 'Rekordy główne zostaną zachowane. Duplikaty ({count}) zostaną przeniesione do kosza, skąd można je przywrócić.',
      it: 'I record principali vengono mantenuti. {count} duplicato/i verranno spostati nel cestino e potranno essere ripristinati da lì.',
      sk: 'Hlavné záznamy sa zachovajú. Duplikáty ({count}) sa presunú do koša, odkiaľ ich možno obnoviť.',
      ja: 'プライマリレコードは保持されます。{count} 件の重複はゴミ箱に移動され、そこから復元できます。',
      ko: '기본 레코드는 유지됩니다. 중복 항목 {count}개가 휴지통으로 이동되며 거기서 복원할 수 있습니다.',
      hi: 'प्राथमिक रिकॉर्ड रखे जाते हैं। {count} डुप्लिकेट आइटम ट्रैश में ले जाए जाएँगे और वहाँ से पुनर्स्थापित किए जा सकते हैं।',
      nl: 'Primaire records blijven behouden. {count} duplica(a)t(en) worden naar de prullenbak verplaatst en kunnen daar worden hersteld.',
      sv: 'Primära poster behålls. {count} dubblett(er) flyttas till papperskorgen och kan återställas därifrån.',
      vi: 'Bản ghi chính được giữ lại. {count} mục trùng lặp sẽ được chuyển vào thùng rác và có thể khôi phục từ đó.',
      id: 'Catatan utama tetap disimpan. {count} item duplikat akan dipindahkan ke sampah dan dapat dipulihkan dari sana.',
      da: 'Hovedposterne bevares. {count} dubletelement(er) flyttes til papirkurven og kan gendannes derfra.',
      nb: 'Hovedpostene beholdes. {count} duplikatelement(er) flyttes til papirkurven og kan gjenopprettes derfra.',
      nn: 'Hovudpostane vert haldne. {count} duplikatelement vert flytte til papirkorga og kan hentast attende derifrå.',
      fi: 'Päätietueet säilytetään. {count} kaksoiskappaletta siirretään roskakoriin, josta ne voi palauttaa.',
      fo: 'Høvuðsskrásetingarnar verða varðveittar. {count} avritslutir verða fluttir til ruskspannina og kunnu endurskapast haðani.',
      is: 'Aðalskráningunum er haldið. {count} tvítaksatriði færast í ruslið og má endurheimta þaðan.',
      cs: 'Hlavní záznamy se zachovají. {count} duplicitních položek se přesune do koše a lze je odtud obnovit.',
      bg: 'Основните записи се запазват. {count} дублирани елемента ще бъдат преместени в кошчето и могат да се възстановят оттам.',
      hr: 'Glavni zapisi se zadržavaju. {count} duplikata premjestit će se u smeće i može se odatle vratiti.',
      sr: 'Главни записи се задржавају. {count} дупликата биће премештено у смеће и може се одатле вратити.',
      sl: 'Glavni zapisi se ohranijo. {count} dvojnikov bo premaknjenih v smetnjak in jih je mogoče od tam obnoviti.',
      mk: 'Главните записи се задржуваат. {count} дупликати ќе бидат преместени во корпата и можат да се вратат оттаму.',
      be: 'Галоўныя запісы захоўваюцца. {count} дублікатаў будзе перамешчана ў сметніцу, адкуль іх можна аднавіць.',
      bs: 'Glavni zapisi se zadržavaju. {count} duplikata bit će premješteno u smeće i može se odatle vratiti.',
      hsb: 'Hłowne zapisy so wobchowaja. {count} dwójnikow so do papjernika přesunje a da so wottam wobnowić.',
    }),
    mergeGmailMarked: t({
      ru: 'Чеков Gmail будет отмечено как дубликаты: {count}.',
      en: '{count} Gmail receipt(s) will be marked as duplicate.',
      kk: 'Gmail чектері көшірме ретінде белгіленеді: {count}.',
      de: '{count} Gmail-Beleg(e) werden als Duplikat markiert.',
      fr: '{count} reçu(s) Gmail seront marqués comme doublons.',
      es: '{count} recibo(s) de Gmail se marcarán como duplicados.',
      pt: '{count} recibo(s) do Gmail serão marcados como duplicados.',
      tr: '{count} Gmail fişi kopya olarak işaretlenecek.',
      uk: 'Чеків Gmail буде позначено як дублікати: {count}.',
      zh: '{count} 张 Gmail 收据将被标记为重复。',
      pl: 'Paragony Gmail ({count}) zostaną oznaczone jako duplikaty.',
      it: '{count} ricevuta/e Gmail verranno contrassegnate come duplicati.',
      sk: 'Doklady z Gmailu ({count}) budú označené ako duplikáty.',
      ja: '{count} 件の Gmail レシートが重複としてマークされます。',
      ko: 'Gmail 영수증 {count}개가 중복으로 표시됩니다.',
      hi: '{count} Gmail रसीदें डुप्लिकेट के रूप में चिह्नित की जाएँगी।',
      nl: '{count} Gmail-bon(nen) worden als duplicaat gemarkeerd.',
      sv: '{count} Gmail-kvitto/kvitton markeras som dubbletter.',
      vi: '{count} hóa đơn Gmail sẽ được đánh dấu là trùng lặp.',
      id: '{count} struk Gmail akan ditandai sebagai duplikat.',
      da: '{count} Gmail-kvittering(er) markeres som dublet.',
      nb: '{count} Gmail-kvittering(er) merkes som duplikat.',
      nn: '{count} Gmail-kvittering(ar) vert merkte som duplikat.',
      fi: '{count} Gmail-kuittia merkitään kaksoiskappaleeksi.',
      fo: '{count} Gmail-kvittanir verða merktar sum avrit.',
      is: '{count} Gmail-kvittanir verða merktar sem tvítak.',
      cs: '{count} účtenek z Gmailu bude označeno jako duplicita.',
      bg: '{count} бележки от Gmail ще бъдат отбелязани като дублирани.',
      hr: '{count} računa iz Gmaila bit će označeno kao duplikat.',
      sr: '{count} рачуна из Gmail-а биће означено као дупликат.',
      sl: '{count} računov iz Gmaila bo označenih kot dvojnik.',
      mk: '{count} сметки од Gmail ќе бидат означени како дупликат.',
      be: '{count} чэкаў з Gmail будзе пазначана як дублікат.',
      bs: '{count} računa iz Gmaila bit će označeno kao duplikat.',
      hsb: '{count} pokazkow z Gmail so jako dwójnik markěruje.',
    }),
    mergeReceiptsTrash: t({
      ru: 'Чеков будет перемещено в корзину: {count}.',
      en: '{count} receipt(s) will be moved to trash.',
      kk: 'Себетке жылжытылатын чектер: {count}.',
      de: '{count} Beleg(e) werden in den Papierkorb verschoben.',
      fr: '{count} reçu(s) seront déplacés dans la corbeille.',
      es: '{count} recibo(s) se moverán a la papelera.',
      pt: '{count} recibo(s) serão movidos para a lixeira.',
      tr: '{count} fiş çöp kutusuna taşınacak.',
      uk: 'Чеків буде переміщено до кошика: {count}.',
      zh: '{count} 张收据将移至回收站。',
      pl: 'Paragony ({count}) zostaną przeniesione do kosza.',
      it: '{count} ricevuta/e verranno spostate nel cestino.',
      sk: 'Doklady ({count}) sa presunú do koša.',
      ja: '{count} 件のレシートがゴミ箱に移動されます。',
      ko: '영수증 {count}개가 휴지통으로 이동됩니다.',
      hi: '{count} रसीदें ट्रैश में ले जाई जाएँगी।',
      nl: '{count} bon(nen) worden naar de prullenbak verplaatst.',
      sv: '{count} kvitto/kvitton flyttas till papperskorgen.',
      vi: '{count} hóa đơn sẽ được chuyển vào thùng rác.',
      id: '{count} struk akan dipindahkan ke sampah.',
      da: '{count} kvittering(er) flyttes til papirkurven.',
      nb: '{count} kvittering(er) flyttes til papirkurven.',
      nn: '{count} kvittering(ar) vert flytte til papirkorga.',
      fi: '{count} kuittia siirretään roskakoriin.',
      fo: '{count} kvittanir verða fluttar til ruskspannina.',
      is: '{count} kvittanir færast í ruslið.',
      cs: '{count} účtenek se přesune do koše.',
      bg: '{count} бележки ще бъдат преместени в кошчето.',
      hr: '{count} računa premjestit će se u smeće.',
      sr: '{count} рачуна биће премештено у смеће.',
      sl: '{count} računov bo premaknjenih v smetnjak.',
      mk: '{count} сметки ќе бидат преместени во корпата.',
      be: '{count} чэкаў будзе перамешчана ў сметніцу.',
      bs: '{count} računa bit će premješteno u smeće.',
      hsb: '{count} pokazkow so do papjernika přesunje.',
    }),
    mergeStatementsTrash: t({
      ru: 'Выписок будет перемещено в корзину: {count}.',
      en: '{count} statement(s) will be moved to trash.',
      kk: 'Себетке жылжытылатын үзінділер: {count}.',
      de: '{count} Kontoauszug/-auszüge werden in den Papierkorb verschoben.',
      fr: '{count} relevé(s) seront déplacés dans la corbeille.',
      es: '{count} extracto(s) se moverán a la papelera.',
      pt: '{count} extrato(s) serão movidos para a lixeira.',
      tr: '{count} ekstre çöp kutusuna taşınacak.',
      uk: 'Виписок буде переміщено до кошика: {count}.',
      zh: '{count} 份对账单将移至回收站。',
      pl: 'Wyciągi ({count}) zostaną przeniesione do kosza.',
      it: '{count} estratto/i verranno spostati nel cestino.',
      sk: 'Výpisy ({count}) sa presunú do koša.',
      ja: '{count} 件の明細書がゴミ箱に移動されます。',
      ko: '명세서 {count}개가 휴지통으로 이동됩니다.',
      hi: '{count} स्टेटमेंट ट्रैश में ले जाए जाएँगे।',
      nl: '{count} afschrift(en) worden naar de prullenbak verplaatst.',
      sv: '{count} utdrag flyttas till papperskorgen.',
      vi: '{count} sao kê sẽ được chuyển vào thùng rác.',
      id: '{count} laporan akan dipindahkan ke sampah.',
      da: '{count} kontoudtog flyttes til papirkurven.',
      nb: '{count} kontoutskrift(er) flyttes til papirkurven.',
      nn: '{count} kontoutskrift(er) vert flytte til papirkorga.',
      fi: '{count} tiliotetta siirretään roskakoriin.',
      fo: '{count} kontoyvirlit verða flutt til ruskspannina.',
      is: '{count} yfirlit færast í ruslið.',
      cs: '{count} výpisů se přesune do koše.',
      bg: '{count} извлечения ще бъдат преместени в кошчето.',
      hr: '{count} izvataka premjestit će se u smeće.',
      sr: '{count} извода биће премештено у смеће.',
      sl: '{count} izpiskov bo premaknjenih v smetnjak.',
      mk: '{count} изводи ќе бидат преместени во корпата.',
      be: '{count} выпісак будзе перамешчана ў сметніцу.',
      bs: '{count} izvoda bit će premješteno u smeće.',
      hsb: '{count} wujimkow so do papjernika přesunje.',
    }),
    mergeGmailSkipped: t({
      ru: 'Элементов Gmail будет пропущено, потому что основная запись не является чеком Gmail: {count}.',
      en: '{count} Gmail item(s) will be skipped because the primary record is not a Gmail receipt.',
      kk: 'Негізгі жазба Gmail чегі емес болғандықтан, өткізіп жіберілетін Gmail элементтері: {count}.',
      de: '{count} Gmail-Element(e) werden übersprungen, weil der primäre Datensatz kein Gmail-Beleg ist.',
      fr: "{count} élément(s) Gmail seront ignorés car l'enregistrement principal n'est pas un reçu Gmail.",
      es: 'Se omitirán {count} elemento(s) de Gmail porque el registro principal no es un recibo de Gmail.',
      pt: '{count} item(ns) do Gmail serão ignorados porque o registro principal não é um recibo do Gmail.',
      tr: 'Birincil kayıt bir Gmail fişi olmadığı için {count} Gmail öğesi atlanacak.',
      uk: 'Елементів Gmail буде пропущено, бо основний запис не є чеком Gmail: {count}.',
      zh: '由于主记录不是 Gmail 收据，将跳过 {count} 个 Gmail 项目。',
      pl: 'Elementy Gmail ({count}) zostaną pominięte, ponieważ rekord główny nie jest paragonem Gmail.',
      it: '{count} elemento/i Gmail verranno saltati perché il record principale non è una ricevuta Gmail.',
      sk: 'Položky z Gmailu ({count}) sa preskočia, pretože hlavný záznam nie je doklad z Gmailu.',
      ja: 'プライマリレコードが Gmail レシートではないため、{count} 件の Gmail 項目はスキップされます。',
      ko: '기본 레코드가 Gmail 영수증이 아니므로 Gmail 항목 {count}개를 건너뜁니다.',
      hi: 'प्राथमिक रिकॉर्ड Gmail रसीद नहीं है, इसलिए {count} Gmail आइटम छोड़ दिए जाएँगे।',
      nl: '{count} Gmail-item(s) worden overgeslagen omdat het primaire record geen Gmail-bon is.',
      sv: '{count} Gmail-objekt hoppas över eftersom den primära posten inte är ett Gmail-kvitto.',
      vi: '{count} mục Gmail sẽ bị bỏ qua vì bản ghi chính không phải là hóa đơn Gmail.',
      id: '{count} item Gmail akan dilewati karena catatan utama bukan struk Gmail.',
      da: '{count} Gmail-element(er) springes over, fordi hovedposten ikke er en Gmail-kvittering.',
      nb: '{count} Gmail-element(er) hoppes over fordi hovedposten ikke er en Gmail-kvittering.',
      nn: '{count} Gmail-element vert hoppa over fordi hovudposten ikkje er ein Gmail-kvittering.',
      fi: '{count} Gmail-kohdetta ohitetaan, koska päätietue ei ole Gmail-kuitti.',
      fo: '{count} Gmail-lutir verða sleptir, tí høvuðsskrásetingin ikki er ein Gmail-kvittan.',
      is: '{count} Gmail-atriðum verður sleppt því aðalskráningin er ekki Gmail-kvittun.',
      cs: '{count} položek z Gmailu bude přeskočeno, protože hlavní záznam není účtenka z Gmailu.',
      bg: '{count} елемента от Gmail ще бъдат пропуснати, защото основният запис не е бележка от Gmail.',
      hr: '{count} stavki iz Gmaila bit će preskočeno jer glavni zapis nije račun iz Gmaila.',
      sr: '{count} ставки из Gmail-а биће прескочено јер главни запис није рачун из Gmail-а.',
      sl: '{count} elementov iz Gmaila bo preskočenih, ker glavni zapis ni račun iz Gmaila.',
      mk: '{count} ставки од Gmail ќе бидат прескокнати бидејќи главниот запис не е сметка од Gmail.',
      be: '{count} элементаў з Gmail будзе прапушчана, бо галоўны запіс не чэк з Gmail.',
      bs: '{count} stavki iz Gmaila bit će preskočeno jer glavni zapis nije račun iz Gmaila.',
      hsb: '{count} elementow z Gmail so přeskoči, dokelž hłowny zapis pokazk z Gmail njeje.',
    }),
    categoryLink: t({
      ru: 'Траты по категории «{category}»',
      en: 'Spending in {category}',
      kk: '«{category}» санаты бойынша шығыстар',
      de: 'Ausgaben in {category}',
      fr: 'Dépenses dans {category}',
      es: 'Gastos en {category}',
      pt: 'Gastos em {category}',
      tr: '{category} harcamaları',
      uk: 'Витрати за категорією «{category}»',
      zh: '{category} 的支出',
      pl: 'Wydatki w kategorii {category}',
      it: 'Spese in {category}',
      sk: 'Výdavky v kategórii {category}',
      ja: '{category} の支出',
      ko: '{category} 지출',
      hi: '{category} में खर्च',
      nl: 'Uitgaven in {category}',
      sv: 'Utgifter i {category}',
      vi: 'Chi tiêu trong {category}',
      id: 'Pengeluaran di {category}',
      da: 'Udgifter i {category}',
      nb: 'Utgifter i {category}',
      nn: 'Utgifter i {category}',
      fi: 'Kulut luokassa {category}',
      fo: 'Útreiðslur í {category}',
      is: 'Útgjöld í {category}',
      cs: 'Výdaje v kategorii {category}',
      bg: 'Разходи в {category}',
      hr: 'Troškovi u {category}',
      sr: 'Трошкови у {category}',
      sl: 'Stroški v {category}',
      mk: 'Трошоци во {category}',
      be: 'Выдаткі ў {category}',
      bs: 'Troškovi u {category}',
      hsb: 'Wudawki w {category}',
    }),
    transactionsCount: t({
      ru: 'Операции: {count}',
      en: 'Transactions: {count}',
      kk: 'Операциялар: {count}',
      de: 'Buchungen: {count}',
      fr: 'Opérations : {count}',
      es: 'Transacciones: {count}',
      pt: 'Transações: {count}',
      tr: 'İşlemler: {count}',
      uk: 'Операції: {count}',
      zh: '交易：{count}',
      pl: 'Transakcje: {count}',
      it: 'Transazioni: {count}',
      sk: 'Transakcie: {count}',
      ja: '取引: {count}',
      ko: '거래: {count}',
      hi: 'लेनदेन: {count}',
      nl: 'Transacties: {count}',
      sv: 'Transaktioner: {count}',
      vi: 'Giao dịch: {count}',
      id: 'Transaksi: {count}',
      da: 'Posteringer: {count}',
      nb: 'Transaksjoner: {count}',
      nn: 'Transaksjonar: {count}',
      fi: 'Tapahtumat: {count}',
      fo: 'Posteringar: {count}',
      is: 'Færslur: {count}',
      cs: 'Transakce: {count}',
      bg: 'Транзакции: {count}',
      hr: 'Transakcije: {count}',
      sr: 'Трансакције: {count}',
      sl: 'Transakcije: {count}',
      mk: 'Трансакции: {count}',
      be: 'Аперацыі: {count}',
      bs: 'Transakcije: {count}',
      hsb: 'Transakcije: {count}',
    }),
  },
} satisfies Dictionary;

export default content;
