import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementsSidePanelSync',
  content: {
    dropboxImportStarted: t({
      ru: 'Импорт из Dropbox запущен',
      en: 'Dropbox import started',
      kk: 'Dropbox-тан импорт басталды',
      de: 'Dropbox-Import gestartet',
      fr: 'Import depuis Dropbox lancé',
      es: 'Importación de Dropbox iniciada',
      pt: 'Importação do Dropbox iniciada',
      tr: 'Dropbox içe aktarımı başladı',
      uk: 'Імпорт із Dropbox запущено',
      zh: 'Dropbox 导入已开始',
      ar: 'بدأ الاستيراد من Dropbox',
      pl: 'Rozpoczęto import z Dropbox',
      it: 'Importazione da Dropbox avviata',
      sk: 'Import z Dropboxu sa začal',
      ja: 'Dropbox からのインポートを開始しました',
      ko: 'Dropbox 가져오기가 시작되었습니다',
      hi: 'Dropbox आयात शुरू हुआ',
      nl: 'Dropbox-import gestart',
      sv: 'Import från Dropbox har startat',
      vi: 'Đã bắt đầu nhập từ Dropbox',
      id: 'Impor Dropbox dimulai',
    }),
    googleDriveImportStarted: t({
      ru: 'Импорт из Google Drive запущен',
      en: 'Google Drive import started',
      kk: 'Google Drive-тан импорт басталды',
      de: 'Google-Drive-Import gestartet',
      fr: 'Import depuis Google Drive lancé',
      es: 'Importación de Google Drive iniciada',
      pt: 'Importação do Google Drive iniciada',
      tr: 'Google Drive içe aktarımı başladı',
      uk: 'Імпорт із Google Drive запущено',
      zh: 'Google Drive 导入已开始',
      ar: 'بدأ الاستيراد من Google Drive',
      pl: 'Rozpoczęto import z Google Drive',
      it: 'Importazione da Google Drive avviata',
      sk: 'Import z Google Drive sa začal',
      ja: 'Google Drive からのインポートを開始しました',
      ko: 'Google Drive 가져오기가 시작되었습니다',
      hi: 'Google Drive आयात शुरू हुआ',
      nl: 'Google Drive-import gestart',
      sv: 'Import från Google Drive har startat',
      vi: 'Đã bắt đầu nhập từ Google Drive',
      id: 'Impor Google Drive dimulai',
    }),
    dropboxImportFailed: t({
      ru: 'Не удалось импортировать из Dropbox',
      en: 'Failed to import from Dropbox',
      kk: 'Dropbox-тан импорттау мүмкін болмады',
      de: 'Import aus Dropbox fehlgeschlagen',
      fr: 'Échec de l’import depuis Dropbox',
      es: 'No se pudo importar desde Dropbox',
      pt: 'Falha ao importar do Dropbox',
      tr: 'Dropbox’tan içe aktarılamadı',
      uk: 'Не вдалося імпортувати з Dropbox',
      zh: '从 Dropbox 导入失败',
      ar: 'فشل الاستيراد من Dropbox',
      pl: 'Nie udało się zaimportować z Dropbox',
      it: 'Importazione da Dropbox non riuscita',
      sk: 'Import z Dropboxu zlyhal',
      ja: 'Dropbox からのインポートに失敗しました',
      ko: 'Dropbox에서 가져오지 못했습니다',
      hi: 'Dropbox से आयात विफल',
      nl: 'Importeren uit Dropbox mislukt',
      sv: 'Det gick inte att importera från Dropbox',
      vi: 'Không thể nhập từ Dropbox',
      id: 'Gagal mengimpor dari Dropbox',
    }),
    googleDriveImportFailed: t({
      ru: 'Не удалось импортировать из Google Drive',
      en: 'Failed to import from Google Drive',
      kk: 'Google Drive-тан импорттау мүмкін болмады',
      de: 'Import aus Google Drive fehlgeschlagen',
      fr: 'Échec de l’import depuis Google Drive',
      es: 'No se pudo importar desde Google Drive',
      pt: 'Falha ao importar do Google Drive',
      tr: 'Google Drive’dan içe aktarılamadı',
      uk: 'Не вдалося імпортувати з Google Drive',
      zh: '从 Google Drive 导入失败',
      ar: 'فشل الاستيراد من Google Drive',
      pl: 'Nie udało się zaimportować z Google Drive',
      it: 'Importazione da Google Drive non riuscita',
      sk: 'Import z Google Drive zlyhal',
      ja: 'Google Drive からのインポートに失敗しました',
      ko: 'Google Drive에서 가져오지 못했습니다',
      hi: 'Google Drive से आयात विफल',
      nl: 'Importeren uit Google Drive mislukt',
      sv: 'Det gick inte att importera från Google Drive',
      vi: 'Không thể nhập từ Google Drive',
      id: 'Gagal mengimpor dari Google Drive',
    }),
    inboxImportedOne: t({
      ru: 'Синхронизация почты: импортирован 1 чек',
      en: 'Inbox sync imported 1 receipt',
      kk: 'Пошта синхрондалды: 1 чек импортталды',
      de: 'Postfach-Synchronisierung: 1 Beleg importiert',
      fr: 'Synchronisation de la boîte : 1 reçu importé',
      es: 'Sincronización del buzón: 1 recibo importado',
      pt: 'Sincronização da caixa: 1 recibo importado',
      tr: 'Gelen kutusu senkronizasyonu: 1 fiş içe aktarıldı',
      uk: 'Синхронізація пошти: імпортовано 1 чек',
      zh: '收件箱同步：已导入 1 张收据',
      ar: 'مزامنة البريد: تم استيراد إيصال واحد',
      pl: 'Synchronizacja skrzynki: zaimportowano 1 paragon',
      it: 'Sincronizzazione casella: 1 ricevuta importata',
      sk: 'Synchronizácia schránky: importovaný 1 doklad',
      ja: '受信トレイ同期：レシート 1 件をインポートしました',
      ko: '받은편지함 동기화: 영수증 1개를 가져왔습니다',
      hi: 'इनबॉक्स सिंक: 1 रसीद आयात की गई',
      nl: 'Inboxsynchronisatie: 1 bon geïmporteerd',
      sv: 'Inkorgssynk: 1 kvitto importerat',
      vi: 'Đồng bộ hộp thư: đã nhập 1 biên lai',
      id: 'Sinkronisasi kotak masuk: 1 struk diimpor',
    }),
    inboxImportedMany: t({
      ru: 'Синхронизация почты: импортировано чеков — {count}',
      en: 'Inbox sync imported {count} receipts',
      kk: 'Пошта синхрондалды: {count} чек импортталды',
      de: 'Postfach-Synchronisierung: {count} Belege importiert',
      fr: 'Synchronisation de la boîte : {count} reçus importés',
      es: 'Sincronización del buzón: {count} recibos importados',
      pt: 'Sincronização da caixa: {count} recibos importados',
      tr: 'Gelen kutusu senkronizasyonu: {count} fiş içe aktarıldı',
      uk: 'Синхронізація пошти: імпортовано чеків — {count}',
      zh: '收件箱同步：已导入 {count} 张收据',
      ar: 'مزامنة البريد: تم استيراد {count} إيصالات',
      pl: 'Synchronizacja skrzynki: zaimportowano paragony ({count})',
      it: 'Sincronizzazione casella: {count} ricevute importate',
      sk: 'Synchronizácia schránky: importované doklady ({count})',
      ja: '受信トレイ同期：レシート {count} 件をインポートしました',
      ko: '받은편지함 동기화: 영수증 {count}개를 가져왔습니다',
      hi: 'इनबॉक्स सिंक: {count} रसीदें आयात की गईं',
      nl: 'Inboxsynchronisatie: {count} bonnen geïmporteerd',
      sv: 'Inkorgssynk: {count} kvitton importerade',
      vi: 'Đồng bộ hộp thư: đã nhập {count} biên lai',
      id: 'Sinkronisasi kotak masuk: {count} struk diimpor',
    }),
    noUnreadEmails: t({
      ru: 'В ящике IMAP нет непрочитанных писем',
      en: 'No unread emails found in IMAP inbox',
      kk: 'IMAP жәшігінде оқылмаған хаттар жоқ',
      de: 'Keine ungelesenen E-Mails im IMAP-Postfach',
      fr: 'Aucun e-mail non lu dans la boîte IMAP',
      es: 'No hay correos sin leer en el buzón IMAP',
      pt: 'Nenhum e-mail não lido na caixa IMAP',
      tr: 'IMAP gelen kutusunda okunmamış e-posta yok',
      uk: 'У скриньці IMAP немає непрочитаних листів',
      zh: 'IMAP 收件箱中没有未读邮件',
      ar: 'لا توجد رسائل غير مقروءة في صندوق IMAP',
      pl: 'Brak nieprzeczytanych wiadomości w skrzynce IMAP',
      it: 'Nessuna email non letta nella casella IMAP',
      sk: 'V schránke IMAP nie sú žiadne neprečítané e-maily',
      ja: 'IMAP 受信トレイに未読メールはありません',
      ko: 'IMAP 받은편지함에 읽지 않은 이메일이 없습니다',
      hi: 'IMAP इनबॉक्स में कोई अपठित ईमेल नहीं मिला',
      nl: 'Geen ongelezen e-mails in de IMAP-inbox',
      sv: 'Inga olästa e-postmeddelanden i IMAP-inkorgen',
      vi: 'Không có email chưa đọc trong hộp thư IMAP',
      id: 'Tidak ada email belum dibaca di kotak masuk IMAP',
    }),
    noNewAttachments: t({
      ru: 'В ящике IMAP нет новых вложений с чеками',
      en: 'No new receipt attachments found in IMAP inbox',
      kk: 'IMAP жәшігінде чектері бар жаңа тіркемелер жоқ',
      de: 'Keine neuen Beleganhänge im IMAP-Postfach',
      fr: 'Aucune nouvelle pièce jointe de reçu dans la boîte IMAP',
      es: 'No hay nuevos adjuntos de recibos en el buzón IMAP',
      pt: 'Nenhum novo anexo de recibo na caixa IMAP',
      tr: 'IMAP gelen kutusunda yeni fiş eki yok',
      uk: 'У скриньці IMAP немає нових вкладень із чеками',
      zh: 'IMAP 收件箱中没有新的收据附件',
      ar: 'لا توجد مرفقات إيصالات جديدة في صندوق IMAP',
      pl: 'Brak nowych załączników z paragonami w skrzynce IMAP',
      it: 'Nessun nuovo allegato di ricevuta nella casella IMAP',
      sk: 'V schránke IMAP nie sú žiadne nové prílohy s dokladmi',
      ja: 'IMAP 受信トレイに新しいレシート添付ファイルはありません',
      ko: 'IMAP 받은편지함에 새 영수증 첨부 파일이 없습니다',
      hi: 'IMAP इनबॉक्स में कोई नई रसीद अटैचमेंट नहीं मिली',
      nl: 'Geen nieuwe bonbijlagen in de IMAP-inbox',
      sv: 'Inga nya kvittobilagor i IMAP-inkorgen',
      vi: 'Không có tệp đính kèm biên lai mới trong hộp thư IMAP',
      id: 'Tidak ada lampiran struk baru di kotak masuk IMAP',
    }),
    syncInboxFailed: t({
      ru: 'Не удалось синхронизировать почту',
      en: 'Failed to sync inbox',
      kk: 'Поштаны синхрондау мүмкін болмады',
      de: 'Postfach konnte nicht synchronisiert werden',
      fr: 'Échec de la synchronisation de la boîte',
      es: 'No se pudo sincronizar el buzón',
      pt: 'Falha ao sincronizar a caixa de entrada',
      tr: 'Gelen kutusu senkronize edilemedi',
      uk: 'Не вдалося синхронізувати пошту',
      zh: '收件箱同步失败',
      ar: 'فشلت مزامنة البريد الوارد',
      pl: 'Nie udało się zsynchronizować skrzynki',
      it: 'Sincronizzazione della casella non riuscita',
      sk: 'Schránku sa nepodarilo synchronizovať',
      ja: '受信トレイを同期できませんでした',
      ko: '받은편지함을 동기화하지 못했습니다',
      hi: 'इनबॉक्स सिंक करने में विफल',
      nl: 'Inbox synchroniseren mislukt',
      sv: 'Det gick inte att synkronisera inkorgen',
      vi: 'Không thể đồng bộ hộp thư',
      id: 'Gagal menyinkronkan kotak masuk',
    }),
  },
} satisfies Dictionary;

export default content;
