import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementsUploadMenu',
  content: {
    closeUploadActions: t({
      ru: 'Закрыть меню загрузки',
      en: 'Close upload actions',
      kk: 'Жүктеу мәзірін жабу',
      de: 'Upload-Aktionen schließen',
      fr: 'Fermer les actions d’import',
      es: 'Cerrar acciones de carga',
      pt: 'Fechar ações de envio',
      tr: 'Yükleme işlemlerini kapat',
      uk: 'Закрити меню завантаження',
      zh: '关闭上传操作',
      ar: 'إغلاق إجراءات الرفع',
      pl: 'Zamknij akcje przesyłania',
      it: 'Chiudi azioni di caricamento',
      sk: 'Zavrieť akcie nahrávania',
      ja: 'アップロード操作を閉じる',
      ko: '업로드 작업 닫기',
      hi: 'अपलोड क्रियाएँ बंद करें',
      nl: 'Uploadacties sluiten',
      sv: 'Stäng uppladdningsåtgärder',
      vi: 'Đóng thao tác tải lên',
      id: 'Tutup tindakan unggah',
      da: 'Luk upload-handlinger',
      nb: 'Lukk opplastingshandlinger',
      nn: 'Lat att opplastingshandlingar',
      fi: 'Sulje lataustoiminnot',
      fo: 'Lat upplegg-gerðir aftur',
      is: 'Loka innsendingaraðgerðum',
      cs: 'Zavřít akce nahrávání',
      bg: 'Затваряне на действията за качване',
      hr: 'Zatvori radnje učitavanja',
      sr: 'Затвори радње отпремања',
      sl: 'Zapri dejanja nalaganja',
      mk: 'Затвори ги дејствата за прикачување',
      be: 'Закрыць дзеянні запампоўкі',
      bs: 'Zatvori radnje otpremanja',
      hsb: 'Akcije nahrawanja začinić',
    }),
    importFromDropbox: t({
      ru: 'Импорт из Dropbox',
      en: 'Import from Dropbox',
      kk: 'Dropbox-тан импорттау',
      de: 'Aus Dropbox importieren',
      fr: 'Importer depuis Dropbox',
      es: 'Importar desde Dropbox',
      pt: 'Importar do Dropbox',
      tr: "Dropbox'tan içe aktar",
      uk: 'Імпорт із Dropbox',
      zh: '从 Dropbox 导入',
      ar: 'الاستيراد من Dropbox',
      pl: 'Importuj z Dropbox',
      it: 'Importa da Dropbox',
      sk: 'Importovať z Dropboxu',
      ja: 'Dropbox からインポート',
      ko: 'Dropbox에서 가져오기',
      hi: 'Dropbox से आयात करें',
      nl: 'Importeren uit Dropbox',
      sv: 'Importera från Dropbox',
      vi: 'Nhập từ Dropbox',
      id: 'Impor dari Dropbox',
      da: 'Importér fra Dropbox',
      nb: 'Importer fra Dropbox',
      nn: 'Importer frå Dropbox',
      fi: 'Tuo Dropboxista',
      is: 'Flytja inn úr Dropbox',
      fo: 'Flyt inn úr Dropbox',
      cs: 'Importovat z Dropboxu',
      bg: 'Внасяне от Dropbox',
      hr: 'Uvezi s Dropboxa',
      sr: 'Увези с Dropbox-а',
      sl: 'Uvozi z Dropboxa',
      mk: 'Внеси од Dropbox',
      be: 'Імпартаваць з Dropbox',
      bs: 'Uvezi s Dropboxa',
      hsb: 'Z Dropbox importować',
    }),
    importFromGoogleDrive: t({
      ru: 'Импорт из Google Drive',
      en: 'Import from Google Drive',
      kk: 'Google Drive-тан импорттау',
      de: 'Aus Google Drive importieren',
      fr: 'Importer depuis Google Drive',
      es: 'Importar desde Google Drive',
      pt: 'Importar do Google Drive',
      tr: "Google Drive'dan içe aktar",
      uk: 'Імпорт із Google Drive',
      zh: '从 Google Drive 导入',
      ar: 'الاستيراد من Google Drive',
      pl: 'Importuj z Google Drive',
      it: 'Importa da Google Drive',
      sk: 'Importovať z Google Drive',
      ja: 'Google Drive からインポート',
      ko: 'Google Drive에서 가져오기',
      hi: 'Google Drive से आयात करें',
      nl: 'Importeren uit Google Drive',
      sv: 'Importera från Google Drive',
      vi: 'Nhập từ Google Drive',
      id: 'Impor dari Google Drive',
      da: 'Importér fra Google Drive',
      nb: 'Importer fra Google Drive',
      nn: 'Importer frå Google Drive',
      fi: 'Tuo Google Drivesta',
      fo: 'Innfør frá Google Drive',
      is: 'Flytja inn frá Google Drive',
      cs: 'Importovat z Google Drive',
      bg: 'Внасяне от Google Drive',
      hr: 'Uvezi s Google Drivea',
      sr: 'Увези с Google Drive-а',
      sl: 'Uvozi iz Google Drivea',
      mk: 'Увези од Google Drive',
      be: 'Імпартаваць з Google Drive',
      bs: 'Uvezi s Google Drivea',
      hsb: 'Z Google Drive importować',
    }),
    cloud: t({
      ru: 'Облако',
      en: 'Cloud',
      kk: 'Бұлт',
      de: 'Cloud',
      fr: 'Cloud',
      es: 'Nube',
      pt: 'Nuvem',
      tr: 'Bulut',
      uk: 'Хмара',
      zh: '云端',
      ar: 'السحابة',
      pl: 'Chmura',
      it: 'Cloud',
      sk: 'Cloud',
      ja: 'クラウド',
      ko: '클라우드',
      hi: 'क्लाउड',
      nl: 'Cloud',
      sv: 'Moln',
      vi: 'Đám mây',
      id: 'Cloud',
      da: 'Sky',
      nb: 'Sky',
      nn: 'Sky',
      fi: 'Pilvi',
      fo: 'Skýggj',
      is: 'Ský',
      cs: 'Cloud',
      bg: 'Облак',
      hr: 'Oblak',
      sr: 'Облак',
      sl: 'Oblak',
      mk: 'Облак',
      be: 'Воблака',
      bs: 'Oblak',
      hsb: 'Mróčel',
    }),
    syncInbox: t({
      ru: 'Синхронизировать почту',
      en: 'Sync inbox',
      kk: 'Поштаны синхрондау',
      de: 'Posteingang synchronisieren',
      fr: 'Synchroniser la boîte de réception',
      es: 'Sincronizar bandeja de entrada',
      pt: 'Sincronizar caixa de entrada',
      tr: 'Gelen kutusunu eşitle',
      uk: 'Синхронізувати пошту',
      zh: '同步收件箱',
      ar: 'مزامنة البريد الوارد',
      pl: 'Synchronizuj skrzynkę',
      it: 'Sincronizza posta in arrivo',
      sk: 'Synchronizovať doručenú poštu',
      ja: '受信トレイを同期',
      ko: '받은편지함 동기화',
      hi: 'इनबॉक्स सिंक करें',
      nl: 'Inbox synchroniseren',
      sv: 'Synka inkorgen',
      vi: 'Đồng bộ hộp thư đến',
      id: 'Sinkronkan kotak masuk',
      da: 'Synkronisér indbakke',
      nb: 'Synkroniser innboks',
      nn: 'Synkroniser innboks',
      fi: 'Synkronoi saapuneet',
      fo: 'Samstilla innbakka',
      is: 'Samstilla pósthólf',
      cs: 'Synchronizovat doručenou poštu',
      bg: 'Синхронизиране на пощенската кутия',
      hr: 'Sinkroniziraj sandučić',
      sr: 'Синхронизуј сандуче',
      sl: 'Sinhroniziraj nabiralnik',
      mk: 'Синхронизирај го сандачето',
      be: 'Сінхранізаваць скрыню',
      bs: 'Sinhronizuj sandučić',
      hsb: 'Póstowy kašćik synchronizować',
    }),
    mailbox: t({
      ru: 'Почта',
      en: 'Mailbox',
      kk: 'Пошта',
      de: 'Postfach',
      fr: 'Boîte mail',
      es: 'Buzón',
      pt: 'Caixa de correio',
      tr: 'Posta kutusu',
      uk: 'Пошта',
      zh: '邮箱',
      ar: 'صندوق البريد',
      pl: 'Skrzynka pocztowa',
      it: 'Casella di posta',
      sk: 'Poštová schránka',
      ja: 'メールボックス',
      ko: '메일함',
      hi: 'मेलबॉक्स',
      nl: 'Postvak',
      sv: 'Brevlåda',
      vi: 'Hộp thư',
      id: 'Kotak surat',
      da: 'Postkasse',
      nb: 'Postboks',
      nn: 'Postboks',
      fi: 'Postilaatikko',
      is: 'Pósthólf',
      fo: 'Postkassi',
      cs: 'Poštovní schránka',
      bg: 'Пощенска кутия',
      hr: 'Poštanski sandučić',
      sr: 'Поштанско сандуче',
      sl: 'Poštni predal',
      mk: 'Поштенско сандаче',
      be: 'Паштовая скрыня',
      bs: 'Poštanski sandučić',
      hsb: 'Póstowy kašćik',
    }),
    createExpense: t({
      ru: 'Создать расход',
      en: 'Create expense',
      kk: 'Шығын жасау',
      de: 'Ausgabe erstellen',
      fr: 'Créer une dépense',
      es: 'Crear gasto',
      pt: 'Criar despesa',
      tr: 'Gider oluştur',
      uk: 'Створити витрату',
      zh: '创建支出',
      ar: 'إنشاء مصروف',
      pl: 'Utwórz wydatek',
      it: 'Crea spesa',
      sk: 'Vytvoriť výdavok',
      ja: '経費を作成',
      ko: '비용 생성',
      hi: 'खर्च बनाएं',
      nl: 'Uitgave aanmaken',
      sv: 'Skapa utgift',
      vi: 'Tạo chi phí',
      id: 'Buat pengeluaran',
      da: 'Opret udgift',
      nb: 'Opprett utgift',
      nn: 'Opprett utgift',
      fi: 'Luo kulu',
      fo: 'Stovna útreiðslu',
      is: 'Búa til útgjald',
      cs: 'Vytvořit výdaj',
      bg: 'Създаване на разход',
      hr: 'Stvori trošak',
      sr: 'Направи трошак',
      sl: 'Ustvari strošek',
      mk: 'Создај трошок',
      be: 'Стварыць выдатак',
      bs: 'Napravi trošak',
      hsb: 'Wudawk wutworić',
    }),
    scan: t({
      ru: 'Сканировать',
      en: 'Scan',
      kk: 'Сканерлеу',
      de: 'Scannen',
      fr: 'Scanner',
      es: 'Escanear',
      pt: 'Digitalizar',
      tr: 'Tara',
      uk: 'Сканувати',
      zh: '扫描',
      ar: 'مسح',
      pl: 'Skanuj',
      it: 'Scansiona',
      sk: 'Skenovať',
      ja: 'スキャン',
      ko: '스캔',
      hi: 'स्कैन',
      nl: 'Scannen',
      sv: 'Skanna',
      vi: 'Quét',
      id: 'Pindai',
      da: 'Scan',
      nb: 'Skann',
      nn: 'Skann',
      fi: 'Skannaa',
      is: 'Skanna',
      fo: 'Skanna',
      cs: 'Skenovat',
      bg: 'Сканиране',
      hr: 'Skeniraj',
      sr: 'Скенирај',
      sl: 'Skeniraj',
      mk: 'Скенирај',
      be: 'Сканаваць',
      bs: 'Skeniraj',
      hsb: 'Skenować',
    }),
    openUploadActions: t({
      ru: 'Открыть меню загрузки',
      en: 'Open upload actions',
      kk: 'Жүктеу мәзірін ашу',
      de: 'Upload-Aktionen öffnen',
      fr: 'Ouvrir les actions d’import',
      es: 'Abrir acciones de carga',
      pt: 'Abrir ações de envio',
      tr: 'Yükleme işlemlerini aç',
      uk: 'Відкрити меню завантаження',
      zh: '打开上传操作',
      ar: 'فتح إجراءات الرفع',
      pl: 'Otwórz akcje przesyłania',
      it: 'Apri azioni di caricamento',
      sk: 'Otvoriť akcie nahrávania',
      ja: 'アップロード操作を開く',
      ko: '업로드 작업 열기',
      hi: 'अपलोड क्रियाएँ खोलें',
      nl: 'Uploadacties openen',
      sv: 'Öppna uppladdningsåtgärder',
      vi: 'Mở thao tác tải lên',
      id: 'Buka tindakan unggah',
      da: 'Åbn upload-handlinger',
      nb: 'Åpne opplastingshandlinger',
      nn: 'Opne opplastingshandlingar',
      fi: 'Avaa lataustoiminnot',
      fo: 'Lat upplegg-gerðir upp',
      is: 'Opna innsendingaraðgerðir',
      cs: 'Otevřít akce nahrávání',
      bg: 'Отваряне на действията за качване',
      hr: 'Otvori radnje učitavanja',
      sr: 'Отвори радње отпремања',
      sl: 'Odpri dejanja nalaganja',
      mk: 'Отвори ги дејствата за прикачување',
      be: 'Адкрыць дзеянні запампоўкі',
      bs: 'Otvori radnje otpremanja',
      hsb: 'Akcije nahrawanja wočinić',
    }),
  },
} satisfies Dictionary;

export default content;
