/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementsTablesReports',
  content: {
    title: t({
      ru: 'Отчёты по таблицам',
      en: 'Tables reports',
      kk: 'Кестелер бойынша есептер',
      de: 'Tabellenberichte',
      fr: 'Rapports des tableaux',
      es: 'Informes de tablas',
      pt: 'Relatórios de tabelas',
      tr: 'Tablo raporları',
      uk: 'Звіти за таблицями',
      zh: '表格报告',
      ar: 'تقارير الجداول',
      pl: 'Raporty tabel',
      it: 'Report delle tabelle',
      sk: 'Prehľady tabuliek',
      ja: 'テーブルレポート',
      ko: '테이블 보고서',
      hi: 'तालिका रिपोर्ट',
      nl: 'Tabelrapporten',
      sv: 'Tabellrapporter',
      vi: 'Báo cáo bảng',
      id: 'Laporan tabel',
    }),
    subtitle: t({
      ru: 'Сводная аналитика по вашим пользовательским таблицам',
      en: 'Aggregated insights from your custom tables',
      kk: 'Жеке кестелеріңіз бойынша жиынтық талдау',
      de: 'Zusammengefasste Auswertungen Ihrer eigenen Tabellen',
      fr: 'Analyses agrégées de vos tableaux personnalisés',
      es: 'Información agregada de tus tablas personalizadas',
      pt: 'Análises agregadas das suas tabelas personalizadas',
      tr: 'Özel tablolarınızdan toplu içgörüler',
      uk: 'Зведена аналітика за вашими власними таблицями',
      zh: '来自自定义表格的汇总洞察',
      ar: 'رؤى مجمّعة من جداولك المخصصة',
      pl: 'Zbiorcze statystyki z Twoich własnych tabel',
      it: 'Analisi aggregate delle tue tabelle personalizzate',
      sk: 'Súhrnné prehľady z vašich vlastných tabuliek',
      ja: 'カスタムテーブルの集計インサイト',
      ko: '사용자 지정 테이블의 집계 인사이트',
      hi: 'आपकी कस्टम तालिकाओं से समेकित जानकारी',
      nl: 'Samengevatte inzichten uit je eigen tabellen',
      sv: 'Sammanställda insikter från dina egna tabeller',
      vi: 'Thông tin tổng hợp từ các bảng tùy chỉnh của bạn',
      id: 'Ringkasan wawasan dari tabel kustom Anda',
    }),
    flowAll: t({
      ru: 'Все',
      en: 'All',
      kk: 'Барлығы',
      de: 'Alle',
      fr: 'Tout',
      es: 'Todo',
      pt: 'Tudo',
      tr: 'Tümü',
      uk: 'Усі',
      zh: '全部',
      ar: 'الكل',
      pl: 'Wszystkie',
      it: 'Tutti',
      sk: 'Všetko',
      ja: 'すべて',
      ko: '전체',
      hi: 'सभी',
      nl: 'Alles',
      sv: 'Alla',
      vi: 'Tất cả',
      id: 'Semua',
    }),
    flowExpenses: t({
      ru: 'Расходы',
      en: 'Expenses',
      kk: 'Шығыстар',
      de: 'Ausgaben',
      fr: 'Dépenses',
      es: 'Gastos',
      pt: 'Despesas',
      tr: 'Giderler',
      uk: 'Витрати',
      zh: '支出',
      ar: 'المصروفات',
      pl: 'Wydatki',
      it: 'Spese',
      sk: 'Výdavky',
      ja: '支出',
      ko: '지출',
      hi: 'खर्च',
      nl: 'Uitgaven',
      sv: 'Utgifter',
      vi: 'Chi tiêu',
      id: 'Pengeluaran',
    }),
    flowIncome: t({
      ru: 'Доходы',
      en: 'Income',
      kk: 'Кірістер',
      de: 'Einnahmen',
      fr: 'Revenus',
      es: 'Ingresos',
      pt: 'Receitas',
      tr: 'Gelirler',
      uk: 'Доходи',
      zh: '收入',
      ar: 'الدخل',
      pl: 'Przychody',
      it: 'Entrate',
      sk: 'Príjmy',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomsten',
      sv: 'Inkomster',
      vi: 'Thu nhập',
      id: 'Pemasukan',
    }),
    searchPlaceholder: t({
      ru: 'Поиск по контрагентам, категориям, таблицам...',
      en: 'Search counterparties, categories, tables...',
      kk: 'Контрагенттер, санаттар, кестелер бойынша іздеу...',
      de: 'Gegenparteien, Kategorien, Tabellen suchen...',
      fr: 'Rechercher des contreparties, catégories, tableaux...',
      es: 'Buscar contrapartes, categorías, tablas...',
      pt: 'Pesquisar contrapartes, categorias, tabelas...',
      tr: 'Karşı taraf, kategori, tablo ara...',
      uk: 'Пошук за контрагентами, категоріями, таблицями...',
      zh: '搜索交易对方、类别、表格...',
      ar: 'ابحث عن الأطراف المقابلة والفئات والجداول...',
      pl: 'Szukaj kontrahentów, kategorii, tabel...',
      it: 'Cerca controparti, categorie, tabelle...',
      sk: 'Hľadať protistrany, kategórie, tabuľky...',
      ja: '取引先、カテゴリ、テーブルを検索...',
      ko: '거래 상대, 카테고리, 테이블 검색...',
      hi: 'प्रतिपक्ष, श्रेणियाँ, तालिकाएँ खोजें...',
      nl: 'Zoek tegenpartijen, categorieën, tabellen...',
      sv: 'Sök motparter, kategorier, tabeller...',
      vi: 'Tìm đối tác, danh mục, bảng...',
      id: 'Cari pihak lawan, kategori, tabel...',
    }),
    tables: t({
      ru: 'Таблицы',
      en: 'Tables',
      kk: 'Кестелер',
      de: 'Tabellen',
      fr: 'Tableaux',
      es: 'Tablas',
      pt: 'Tabelas',
      tr: 'Tablolar',
      uk: 'Таблиці',
      zh: '表格',
      ar: 'الجداول',
      pl: 'Tabele',
      it: 'Tabelle',
      sk: 'Tabuľky',
      ja: 'テーブル',
      ko: '테이블',
      hi: 'तालिकाएँ',
      nl: 'Tabellen',
      sv: 'Tabeller',
      vi: 'Bảng',
      id: 'Tabel',
    }),
    allTables: t({
      ru: 'Все таблицы',
      en: 'All tables',
      kk: 'Барлық кестелер',
      de: 'Alle Tabellen',
      fr: 'Tous les tableaux',
      es: 'Todas las tablas',
      pt: 'Todas as tabelas',
      tr: 'Tüm tablolar',
      uk: 'Усі таблиці',
      zh: '所有表格',
      ar: 'جميع الجداول',
      pl: 'Wszystkie tabele',
      it: 'Tutte le tabelle',
      sk: 'Všetky tabuľky',
      ja: 'すべてのテーブル',
      ko: '모든 테이블',
      hi: 'सभी तालिकाएँ',
      nl: 'Alle tabellen',
      sv: 'Alla tabeller',
      vi: 'Tất cả bảng',
      id: 'Semua tabel',
    }),
    selectTable: t({
      ru: 'Выбрать таблицу {name}',
      en: 'Select table {name}',
      kk: '{name} кестесін таңдау',
      de: 'Tabelle {name} auswählen',
      fr: 'Sélectionner le tableau {name}',
      es: 'Seleccionar tabla {name}',
      pt: 'Selecionar tabela {name}',
      tr: '{name} tablosunu seç',
      uk: 'Вибрати таблицю {name}',
      zh: '选择表格 {name}',
      ar: 'اختر الجدول {name}',
      pl: 'Wybierz tabelę {name}',
      it: 'Seleziona tabella {name}',
      sk: 'Vybrať tabuľku {name}',
      ja: 'テーブル {name} を選択',
      ko: '{name} 테이블 선택',
      hi: 'तालिका {name} चुनें',
      nl: 'Tabel {name} selecteren',
      sv: 'Välj tabell {name}',
      vi: 'Chọn bảng {name}',
      id: 'Pilih tabel {name}',
    }),
    last7Days: t({
      ru: 'Последние 7 дней',
      en: 'Last 7 days',
      kk: 'Соңғы 7 күн',
      de: 'Letzte 7 Tage',
      fr: '7 derniers jours',
      es: 'Últimos 7 días',
      pt: 'Últimos 7 dias',
      tr: 'Son 7 gün',
      uk: 'Останні 7 днів',
      zh: '最近 7 天',
      ar: 'آخر 7 أيام',
      pl: 'Ostatnie 7 dni',
      it: 'Ultimi 7 giorni',
      sk: 'Posledných 7 dní',
      ja: '過去 7 日間',
      ko: '최근 7일',
      hi: 'पिछले 7 दिन',
      nl: 'Laatste 7 dagen',
      sv: 'Senaste 7 dagarna',
      vi: '7 ngày qua',
      id: '7 hari terakhir',
    }),
    last30Days: t({
      ru: 'Последние 30 дней',
      en: 'Last 30 days',
      kk: 'Соңғы 30 күн',
      de: 'Letzte 30 Tage',
      fr: '30 derniers jours',
      es: 'Últimos 30 días',
      pt: 'Últimos 30 dias',
      tr: 'Son 30 gün',
      uk: 'Останні 30 днів',
      zh: '最近 30 天',
      ar: 'آخر 30 يومًا',
      pl: 'Ostatnie 30 dni',
      it: 'Ultimi 30 giorni',
      sk: 'Posledných 30 dní',
      ja: '過去 30 日間',
      ko: '최근 30일',
      hi: 'पिछले 30 दिन',
      nl: 'Laatste 30 dagen',
      sv: 'Senaste 30 dagarna',
      vi: '30 ngày qua',
      id: '30 hari terakhir',
    }),
    last90Days: t({
      ru: 'Последние 90 дней',
      en: 'Last 90 days',
      kk: 'Соңғы 90 күн',
      de: 'Letzte 90 Tage',
      fr: '90 derniers jours',
      es: 'Últimos 90 días',
      pt: 'Últimos 90 dias',
      tr: 'Son 90 gün',
      uk: 'Останні 90 днів',
      zh: '最近 90 天',
      ar: 'آخر 90 يومًا',
      pl: 'Ostatnie 90 dni',
      it: 'Ultimi 90 giorni',
      sk: 'Posledných 90 dní',
      ja: '過去 90 日間',
      ko: '최근 90일',
      hi: 'पिछले 90 दिन',
      nl: 'Laatste 90 dagen',
      sv: 'Senaste 90 dagarna',
      vi: '90 ngày qua',
      id: '90 hari terakhir',
    }),
    last365Days: t({
      ru: 'Последние 365 дней',
      en: 'Last 365 days',
      kk: 'Соңғы 365 күн',
      de: 'Letzte 365 Tage',
      fr: '365 derniers jours',
      es: 'Últimos 365 días',
      pt: 'Últimos 365 dias',
      tr: 'Son 365 gün',
      uk: 'Останні 365 днів',
      zh: '最近 365 天',
      ar: 'آخر 365 يومًا',
      pl: 'Ostatnie 365 dni',
      it: 'Ultimi 365 giorni',
      sk: 'Posledných 365 dní',
      ja: '過去 365 日間',
      ko: '최근 365일',
      hi: 'पिछले 365 दिन',
      nl: 'Laatste 365 dagen',
      sv: 'Senaste 365 dagarna',
      vi: '365 ngày qua',
      id: '365 hari terakhir',
    }),
    yearToDate: t({
      ru: 'С начала года',
      en: 'Year to date',
      kk: 'Жыл басынан бері',
      de: 'Seit Jahresbeginn',
      fr: 'Depuis le début de l’année',
      es: 'En lo que va del año',
      pt: 'Desde o início do ano',
      tr: 'Yılbaşından bugüne',
      uk: 'З початку року',
      zh: '年初至今',
      ar: 'منذ بداية العام',
      pl: 'Od początku roku',
      it: 'Da inizio anno',
      sk: 'Od začiatku roka',
      ja: '年初来',
      ko: '연초부터 현재까지',
      hi: 'वर्ष की शुरुआत से',
      nl: 'Sinds begin van het jaar',
      sv: 'Hittills i år',
      vi: 'Từ đầu năm',
      id: 'Sejak awal tahun',
    }),
    noData: t({
      ru: 'Нет данных за выбранный период.',
      en: 'No data found for the selected period.',
      kk: 'Таңдалған кезеңде деректер жоқ.',
      de: 'Für den ausgewählten Zeitraum wurden keine Daten gefunden.',
      fr: 'Aucune donnée pour la période sélectionnée.',
      es: 'No hay datos para el período seleccionado.',
      pt: 'Nenhum dado encontrado para o período selecionado.',
      tr: 'Seçilen dönem için veri bulunamadı.',
      uk: 'Немає даних за вибраний період.',
      zh: '所选期间没有数据。',
      ar: 'لا توجد بيانات للفترة المحددة.',
      pl: 'Brak danych dla wybranego okresu.',
      it: 'Nessun dato per il periodo selezionato.',
      sk: 'Pre vybrané obdobie sa nenašli žiadne údaje.',
      ja: '選択した期間のデータはありません。',
      ko: '선택한 기간에 데이터가 없습니다.',
      hi: 'चयनित अवधि के लिए कोई डेटा नहीं मिला।',
      nl: 'Geen gegevens gevonden voor de geselecteerde periode.',
      sv: 'Inga data hittades för den valda perioden.',
      vi: 'Không có dữ liệu cho khoảng thời gian đã chọn.',
      id: 'Tidak ada data untuk periode yang dipilih.',
    }),
    total: t({
      ru: 'Итого',
      en: 'Total',
      kk: 'Барлығы',
      de: 'Gesamt',
      fr: 'Total',
      es: 'Total',
      pt: 'Total',
      tr: 'Toplam',
      uk: 'Разом',
      zh: '总计',
      ar: 'الإجمالي',
      pl: 'Łącznie',
      it: 'Totale',
      sk: 'Spolu',
      ja: '合計',
      ko: '합계',
      hi: 'कुल',
      nl: 'Totaal',
      sv: 'Totalt',
      vi: 'Tổng',
      id: 'Total',
    }),
    manualTables: t({
      ru: 'Ручные таблицы',
      en: 'Manual tables',
      kk: 'Қолмен толтырылатын кестелер',
      de: 'Manuelle Tabellen',
      fr: 'Tableaux manuels',
      es: 'Tablas manuales',
      pt: 'Tabelas manuais',
      tr: 'Manuel tablolar',
      uk: 'Ручні таблиці',
      zh: '手动表格',
      ar: 'الجداول اليدوية',
      pl: 'Tabele ręczne',
      it: 'Tabelle manuali',
      sk: 'Manuálne tabuľky',
      ja: '手動テーブル',
      ko: '수동 테이블',
      hi: 'मैनुअल तालिकाएँ',
      nl: 'Handmatige tabellen',
      sv: 'Manuella tabeller',
      vi: 'Bảng thủ công',
      id: 'Tabel manual',
    }),
    sourceManual: t({
      ru: 'Вручную',
      en: 'Manual',
      kk: 'Қолмен',
      de: 'Manuell',
      fr: 'Manuel',
      es: 'Manual',
      pt: 'Manual',
      tr: 'Manuel',
      uk: 'Вручну',
      zh: '手动',
      ar: 'يدوي',
      pl: 'Ręczne',
      it: 'Manuale',
      sk: 'Manuálne',
      ja: '手動',
      ko: '수동',
      hi: 'मैनुअल',
      nl: 'Handmatig',
      sv: 'Manuell',
      vi: 'Thủ công',
      id: 'Manual',
    }),
    operations: t({
      ru: 'Операции',
      en: 'Operations',
      kk: 'Операциялар',
      de: 'Vorgänge',
      fr: 'Opérations',
      es: 'Operaciones',
      pt: 'Operações',
      tr: 'İşlemler',
      uk: 'Операції',
      zh: '交易笔数',
      ar: 'العمليات',
      pl: 'Operacje',
      it: 'Operazioni',
      sk: 'Operácie',
      ja: '取引数',
      ko: '거래 수',
      hi: 'लेन-देन',
      nl: 'Transacties',
      sv: 'Transaktioner',
      vi: 'Giao dịch',
      id: 'Transaksi',
    }),
    trend: t({
      ru: 'Динамика',
      en: 'Trend',
      kk: 'Динамика',
      de: 'Verlauf',
      fr: 'Tendance',
      es: 'Tendencia',
      pt: 'Tendência',
      tr: 'Eğilim',
      uk: 'Динаміка',
      zh: '趋势',
      ar: 'الاتجاه',
      pl: 'Trend',
      it: 'Andamento',
      sk: 'Trend',
      ja: '推移',
      ko: '추세',
      hi: 'रुझान',
      nl: 'Trend',
      sv: 'Trend',
      vi: 'Xu hướng',
      id: 'Tren',
    }),
    sourceSplit: t({
      ru: 'Распределение по источникам',
      en: 'Source split',
      kk: 'Дереккөздер бойынша бөліну',
      de: 'Aufteilung nach Quelle',
      fr: 'Répartition par source',
      es: 'Distribución por origen',
      pt: 'Distribuição por origem',
      tr: 'Kaynak dağılımı',
      uk: 'Розподіл за джерелами',
      zh: '来源分布',
      ar: 'التوزيع حسب المصدر',
      pl: 'Podział według źródła',
      it: 'Ripartizione per fonte',
      sk: 'Rozdelenie podľa zdroja',
      ja: 'ソース別内訳',
      ko: '출처별 분포',
      hi: 'स्रोत अनुसार विभाजन',
      nl: 'Verdeling per bron',
      sv: 'Fördelning per källa',
      vi: 'Phân bổ theo nguồn',
      id: 'Pembagian sumber',
    }),
    topCounterparties: t({
      ru: 'Топ контрагентов',
      en: 'Top counterparties',
      kk: 'Үздік контрагенттер',
      de: 'Top-Gegenparteien',
      fr: 'Principales contreparties',
      es: 'Principales contrapartes',
      pt: 'Principais contrapartes',
      tr: 'En çok işlem yapılan karşı taraflar',
      uk: 'Топ контрагентів',
      zh: '主要交易对方',
      ar: 'أبرز الأطراف المقابلة',
      pl: 'Najwięksi kontrahenci',
      it: 'Controparti principali',
      sk: 'Najväčšie protistrany',
      ja: '主な取引先',
      ko: '주요 거래 상대',
      hi: 'शीर्ष प्रतिपक्ष',
      nl: 'Belangrijkste tegenpartijen',
      sv: 'Största motparter',
      vi: 'Đối tác hàng đầu',
      id: 'Pihak lawan teratas',
    }),
    amount: t({
      ru: 'Сумма',
      en: 'Amount',
      kk: 'Сома',
      de: 'Betrag',
      fr: 'Montant',
      es: 'Importe',
      pt: 'Valor',
      tr: 'Tutar',
      uk: 'Сума',
      zh: '金额',
      ar: 'المبلغ',
      pl: 'Kwota',
      it: 'Importo',
      sk: 'Suma',
      ja: '金額',
      ko: '금액',
      hi: 'राशि',
      nl: 'Bedrag',
      sv: 'Belopp',
      vi: 'Số tiền',
      id: 'Jumlah',
    }),
    average: t({
      ru: 'Среднее',
      en: 'Average',
      kk: 'Орташа',
      de: 'Durchschnitt',
      fr: 'Moyenne',
      es: 'Promedio',
      pt: 'Média',
      tr: 'Ortalama',
      uk: 'Середнє',
      zh: '平均值',
      ar: 'المتوسط',
      pl: 'Średnia',
      it: 'Media',
      sk: 'Priemer',
      ja: '平均',
      ko: '평균',
      hi: 'औसत',
      nl: 'Gemiddelde',
      sv: 'Genomsnitt',
      vi: 'Trung bình',
      id: 'Rata-rata',
    }),
    counterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı taraf',
      uk: 'Контрагент',
      zh: '交易对方',
      ar: 'الطرف المقابل',
      pl: 'Kontrahent',
      it: 'Controparte',
      sk: 'Protistrana',
      ja: '取引先',
      ko: '거래 상대',
      hi: 'प्रतिपक्ष',
      nl: 'Tegenpartij',
      sv: 'Motpart',
      vi: 'Đối tác',
      id: 'Pihak lawan',
    }),
    source: t({
      ru: 'Источник',
      en: 'Source',
      kk: 'Дереккөз',
      de: 'Quelle',
      fr: 'Source',
      es: 'Origen',
      pt: 'Origem',
      tr: 'Kaynak',
      uk: 'Джерело',
      zh: '来源',
      ar: 'المصدر',
      pl: 'Źródło',
      it: 'Fonte',
      sk: 'Zdroj',
      ja: 'ソース',
      ko: '출처',
      hi: 'स्रोत',
      nl: 'Bron',
      sv: 'Källa',
      vi: 'Nguồn',
      id: 'Sumber',
    }),
    table: t({
      ru: 'Таблица',
      en: 'Table',
      kk: 'Кесте',
      de: 'Tabelle',
      fr: 'Tableau',
      es: 'Tabla',
      pt: 'Tabela',
      tr: 'Tablo',
      uk: 'Таблиця',
      zh: '表格',
      ar: 'الجدول',
      pl: 'Tabela',
      it: 'Tabella',
      sk: 'Tabuľka',
      ja: 'テーブル',
      ko: '테이블',
      hi: 'तालिका',
      nl: 'Tabel',
      sv: 'Tabell',
      vi: 'Bảng',
      id: 'Tabel',
    }),
    lastOperation: t({
      ru: 'Последняя операция',
      en: 'Last operation',
      kk: 'Соңғы операция',
      de: 'Letzter Vorgang',
      fr: 'Dernière opération',
      es: 'Última operación',
      pt: 'Última operação',
      tr: 'Son işlem',
      uk: 'Остання операція',
      zh: '最近一笔',
      ar: 'آخر عملية',
      pl: 'Ostatnia operacja',
      it: 'Ultima operazione',
      sk: 'Posledná operácia',
      ja: '最終取引',
      ko: '마지막 거래',
      hi: 'अंतिम लेन-देन',
      nl: 'Laatste transactie',
      sv: 'Senaste transaktion',
      vi: 'Giao dịch gần nhất',
      id: 'Transaksi terakhir',
    }),
    drillDownTitle: t({
      ru: '{counterparty} — детализация',
      en: '{counterparty} — Drill-down',
      kk: '{counterparty} — толығырақ',
      de: '{counterparty} — Details',
      fr: '{counterparty} — Détail',
      es: '{counterparty} — Detalle',
      pt: '{counterparty} — Detalhamento',
      tr: '{counterparty} — Ayrıntılar',
      uk: '{counterparty} — деталізація',
      zh: '{counterparty} — 明细',
      ar: '{counterparty} — التفاصيل',
      pl: '{counterparty} — szczegóły',
      it: '{counterparty} — Dettaglio',
      sk: '{counterparty} — podrobnosti',
      ja: '{counterparty} — 詳細',
      ko: '{counterparty} — 상세',
      hi: '{counterparty} — विवरण',
      nl: '{counterparty} — Details',
      sv: '{counterparty} — Detaljer',
      vi: '{counterparty} — Chi tiết',
      id: '{counterparty} — Rincian',
    }),
    close: t({
      ru: 'Закрыть',
      en: 'Close',
      kk: 'Жабу',
      de: 'Schließen',
      fr: 'Fermer',
      es: 'Cerrar',
      pt: 'Fechar',
      tr: 'Kapat',
      uk: 'Закрити',
      zh: '关闭',
      ar: 'إغلاق',
      pl: 'Zamknij',
      it: 'Chiudi',
      sk: 'Zavrieť',
      ja: '閉じる',
      ko: '닫기',
      hi: 'बंद करें',
      nl: 'Sluiten',
      sv: 'Stäng',
      vi: 'Đóng',
      id: 'Tutup',
    }),
    date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
    }),
    category: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '类别',
      ar: 'الفئة',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategória',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
    }),
    noRecords: t({
      ru: 'Записи не найдены',
      en: 'No records found',
      kk: 'Жазбалар табылмады',
      de: 'Keine Einträge gefunden',
      fr: 'Aucun enregistrement trouvé',
      es: 'No se encontraron registros',
      pt: 'Nenhum registro encontrado',
      tr: 'Kayıt bulunamadı',
      uk: 'Записів не знайдено',
      zh: '未找到记录',
      ar: 'لم يتم العثور على سجلات',
      pl: 'Nie znaleziono rekordów',
      it: 'Nessun record trovato',
      sk: 'Nenašli sa žiadne záznamy',
      ja: 'レコードが見つかりません',
      ko: '기록이 없습니다',
      hi: 'कोई रिकॉर्ड नहीं मिला',
      nl: 'Geen records gevonden',
      sv: 'Inga poster hittades',
      vi: 'Không tìm thấy bản ghi',
      id: 'Tidak ada catatan',
    }),
  },
} satisfies Dictionary;

export default content;
