import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'insights',
  content: {
    adviceTitle: t({
      ru: 'Советы',
      en: 'Advice',
      kk: 'Кеңестер',
      de: 'Empfehlungen',
      fr: 'Conseils',
      es: 'Consejos',
      pt: 'Conselhos',
      tr: 'Öneriler',
      uk: 'Поради',
      zh: '建议',
      ar: 'نصائح',
      pl: 'Porady',
      it: 'Consigli',
      sk: 'Rady',
      ja: 'アドバイス',
      ko: '조언',
      hi: 'सलाह',
      nl: 'Advies',
      sv: 'Råd',
      vi: 'Lời khuyên',
      id: 'Saran',
    }),
    adviceSubtitle: t({
      ru: 'Что ваши траты говорят о ваших намерениях. Мерило — ваш собственный план: похвала там, где он держится, и слово там, где нет.',
      en: 'What your spending says about your intentions. Measured by your own plan — praise where it holds, a word where it slips.',
      kk: 'Шығындарыңыз ниеттеріңіз туралы не айтады. Өлшем — өз жоспарыңыз: сақталса — мақтау, бұзылса — бір ауыз сөз.',
      de: 'Was Ihre Ausgaben über Ihre Absichten sagen. Gemessen an Ihrem eigenen Plan — Lob, wo er hält, ein Wort, wo er wankt.',
      fr: 'Ce que vos dépenses disent de vos intentions. Mesuré à votre propre plan — un éloge quand il tient, un mot quand il flanche.',
      es: 'Lo que sus gastos dicen de sus intenciones. La medida es su propio plan: elogio donde se cumple, una palabra donde falla.',
      pt: 'O que os seus gastos dizem sobre as suas intenções. A medida é o seu próprio plano — elogio onde ele se cumpre, uma palavra onde falha.',
      tr: 'Harcamalarınızın niyetleriniz hakkında söyledikleri. Ölçü kendi planınız — tuttuğu yerde övgü, kaydığı yerde bir söz.',
      uk: 'Що ваші витрати кажуть про ваші наміри. Мірило — ваш власний план: похвала там, де він тримається, і слово там, де ні.',
      zh: '你的支出透露了你的意图。以你自己的计划为尺度——守住时给予肯定，偏离时提醒一句。',
      ar: 'ما يقوله إنفاقك عن نواياك. المقياس خطتك أنت — ثناء حيث تصمد، وكلمة حيث تنزلق.',
      pl: 'Co Twoje wydatki mówią o Twoich zamiarach. Miarą jest Twój własny plan — pochwała, gdy się trzyma, słowo, gdy się chwieje.',
      it: 'Cosa dicono le tue spese sulle tue intenzioni. Il metro è il tuo stesso piano — una lode dove regge, una parola dove cede.',
      sk: 'Čo vaše výdavky hovoria o vašich zámeroch. Meradlom je váš vlastný plán — pochvala, kde drží, slovo, kde nie.',
      ja: '支出があなたの意図について語ること。ものさしはあなた自身の計画です。守れていれば称賛を、崩れていればひと言を。',
      ko: '지출이 당신의 의도에 대해 말해 주는 것. 기준은 당신 자신의 계획입니다. 지켜지면 칭찬을, 흔들리면 한마디를.',
      hi: 'आपका खर्च आपके इरादों के बारे में क्या कहता है। पैमाना आपकी अपनी योजना है — जहाँ वह टिकी रहे वहाँ सराहना, जहाँ फिसले वहाँ एक बात।',
      nl: 'Wat je uitgaven zeggen over je voornemens. Gemeten aan je eigen plan — lof waar het standhoudt, een woord waar het wankelt.',
      sv: 'Vad dina utgifter säger om dina avsikter. Måttstocken är din egen plan — beröm där den håller, ett ord där den glider.',
      vi: 'Chi tiêu của bạn nói gì về ý định của bạn. Thước đo là kế hoạch của chính bạn — lời khen khi giữ được, một lời nhắc khi chệch hướng.',
      id: 'Apa yang dikatakan pengeluaran Anda tentang niat Anda. Diukur dengan rencana Anda sendiri — pujian saat terjaga, sepatah kata saat tergelincir.',
    }),
    adviceEmpty: t({
      ru: 'Пока судить не о чем — задайте бюджеты и оцените траты во вкладке «Бюджеты».',
      en: 'Nothing to judge yet — set budgets and classify your spending on the Budgets page.',
      kk: 'Әзірге бағалайтын ештеңе жоқ — бюджеттер қойып, «Бюджеттер» бетінде шығындарыңызды сыныптаңыз.',
      de: 'Noch nichts zu beurteilen — legen Sie Budgets fest und ordnen Sie Ihre Ausgaben auf der Seite „Budgets“ ein.',
      fr: "Rien à juger pour l'instant — définissez des budgets et classez vos dépenses sur la page Budgets.",
      es: 'Aún no hay nada que juzgar: defina presupuestos y clasifique sus gastos en la página Presupuestos.',
      pt: 'Ainda nada a avaliar — defina orçamentos e classifique os seus gastos na página Orçamentos.',
      tr: 'Henüz tartılacak bir şey yok — bütçe belirleyin ve harcamalarınızı Bütçeler sayfasında sınıflandırın.',
      uk: 'Поки що нема про що судити — задайте бюджети й оцініть витрати на вкладці «Бюджети».',
      zh: '暂时还没有可评判的——请设置预算，并在“预算”页面为支出归类。',
      ar: 'لا شيء للحكم عليه بعد — حدّد ميزانيات وصنّف إنفاقك في صفحة الميزانيات.',
      pl: 'Na razie nie ma czego oceniać — ustal budżety i sklasyfikuj wydatki na stronie Budżety.',
      it: 'Ancora niente da giudicare — imposta i budget e classifica le spese nella pagina Budget.',
      sk: 'Zatiaľ nie je čo posudzovať — nastavte rozpočty a zaraďte výdavky na stránke Rozpočty.',
      ja: 'まだ判断する材料がありません。予算を設定し、「予算」ページで支出を分類しましょう。',
      ko: '아직 판단할 것이 없습니다. 예산을 설정하고 예산 페이지에서 지출을 분류하세요.',
      hi: 'अभी आकलन के लिए कुछ नहीं है — बजट सेट करें और बजट पेज पर अपने खर्च को वर्गीकृत करें।',
      nl: 'Nog niets om te beoordelen — stel budgetten in en deel je uitgaven in op de pagina Budgetten.',
      sv: 'Inget att bedöma ännu — sätt budgetar och klassa dina utgifter på sidan Budgetar.',
      vi: 'Chưa có gì để đánh giá — hãy đặt ngân sách và phân loại chi tiêu ở trang Ngân sách.',
      id: 'Belum ada yang bisa dinilai — tetapkan anggaran dan klasifikasikan pengeluaran Anda di halaman Anggaran.',
    }),
    openLabel: t({
      ru: 'Открыть',
      en: 'Open',
      kk: 'Ашу',
      de: 'Öffnen',
      fr: 'Ouvrir',
      es: 'Abrir',
      pt: 'Abrir',
      tr: 'Aç',
      uk: 'Відкрити',
      zh: '打开',
      ar: 'فتح',
      pl: 'Otwórz',
      it: 'Apri',
      sk: 'Otvoriť',
      ja: '開く',
      ko: '열기',
      hi: 'खोलें',
      nl: 'Openen',
      sv: 'Öppna',
      vi: 'Mở',
      id: 'Buka',
    }),
    dismiss: t({
      ru: 'Скрыть',
      en: 'Dismiss',
      kk: 'Жасыру',
      de: 'Ausblenden',
      fr: 'Masquer',
      es: 'Descartar',
      pt: 'Dispensar',
      tr: 'Kapat',
      uk: 'Приховати',
      zh: '忽略',
      ar: 'إخفاء',
      pl: 'Ukryj',
      it: 'Ignora',
      sk: 'Skryť',
      ja: '閉じる',
      ko: '숨기기',
      hi: 'हटाएँ',
      nl: 'Sluiten',
      sv: 'Dölj',
      vi: 'Ẩn',
      id: 'Tutup',
    }),
    quoteLabel: t({
      ru: 'Цитата дня',
      en: 'Quote of the day',
      kk: 'Күннің дәйексөзі',
      de: 'Zitat des Tages',
      fr: 'Citation du jour',
      es: 'Cita del día',
      pt: 'Citação do dia',
      tr: 'Günün sözü',
      uk: 'Цитата дня',
      zh: '每日名言',
      ar: 'اقتباس اليوم',
      pl: 'Cytat dnia',
      it: 'Citazione del giorno',
      sk: 'Citát dňa',
      ja: '今日の言葉',
      ko: '오늘의 명언',
      hi: 'आज का उद्धरण',
      nl: 'Citaat van de dag',
      sv: 'Dagens citat',
      vi: 'Câu nói trong ngày',
      id: 'Kutipan hari ini',
    }),
    quoteWhy: t({
      ru: 'К совету:',
      en: 'For your advice:',
      kk: 'Кеңеске:',
      de: 'Zu Ihrer Empfehlung:',
      fr: 'Pour votre conseil :',
      es: 'Para tu consejo:',
      pt: 'Para o seu conselho:',
      tr: 'Tavsiyeniz için:',
      uk: 'До поради:',
      zh: '针对您的建议：',
      ar: 'لنصيحتك:',
      pl: 'Do Twojej porady:',
      it: 'Per il tuo consiglio:',
      sk: 'K vašej rade:',
      ja: 'アドバイスに寄せて：',
      ko: '조언과 함께:',
      hi: 'आपकी सलाह के लिए:',
      nl: 'Bij je advies:',
      sv: 'Till ditt råd:',
      vi: 'Cho lời khuyên của bạn:',
      id: 'Untuk saran Anda:',
    }),
    quoteDismiss: t({
      ru: 'Скрыть до завтра',
      en: 'Hide until tomorrow',
      kk: 'Ертеңге дейін жасыру',
      de: 'Bis morgen ausblenden',
      fr: "Masquer jusqu'à demain",
      es: 'Ocultar hasta mañana',
      pt: 'Ocultar até amanhã',
      tr: 'Yarına kadar gizle',
      uk: 'Сховати до завтра',
      zh: '隐藏至明天',
      ar: 'إخفاء حتى الغد',
      pl: 'Ukryj do jutra',
      it: 'Nascondi fino a domani',
      sk: 'Skryť do zajtra',
      ja: '明日まで非表示',
      ko: '내일까지 숨기기',
      hi: 'कल तक छिपाएँ',
      nl: 'Verbergen tot morgen',
      sv: 'Dölj till i morgon',
      vi: 'Ẩn đến ngày mai',
      id: 'Sembunyikan sampai besok',
    }),
    expertLabel: t({
      ru: 'Принцип эксперта',
      en: 'Expert principle',
      kk: 'Сарапшы қағидасы',
      de: 'Expertenprinzip',
      fr: "Principe d'expert",
      es: 'Principio de experto',
      pt: 'Princípio de especialista',
      tr: 'Uzman ilkesi',
      uk: 'Принцип експерта',
      zh: '专家原则',
      ar: 'مبدأ خبير',
      pl: 'Zasada eksperta',
      it: "Principio dell'esperto",
      sk: 'Princíp odborníka',
      ja: '専門家の原則',
      ko: '전문가의 원칙',
      hi: 'विशेषज्ञ का सिद्धांत',
      nl: 'Principe van een expert',
      sv: 'Expertprincip',
      vi: 'Nguyên tắc chuyên gia',
      id: 'Prinsip ahli',
    }),
  },
} satisfies Dictionary;

export default content;
