import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'cryptoPage',
  content: {
    title: t({
      ru: 'Криптокошельки',
      en: 'Crypto wallets',
      kk: 'Криптоәмияндар',
      de: 'Krypto-Wallets',
      fr: 'Portefeuilles crypto',
      es: 'Carteras cripto',
      pt: 'Carteiras cripto',
      tr: 'Kripto cüzdanlar',
      uk: 'Криптогаманці',
      zh: '加密钱包',
      pl: 'Portfele krypto',
      it: 'Portafogli cripto',
      sk: 'Krypto peňaženky',
      ja: '暗号資産ウォレット',
      ko: '암호화폐 지갑',
      hi: 'क्रिप्टो वॉलेट',
      nl: 'Crypto-wallets',
      sv: 'Kryptoplånböcker',
      vi: 'Ví tiền mã hóa',
      id: 'Dompet kripto',
      da: 'Kryptowallets',
      nb: 'Kryptolommebøker',
      nn: 'Kryptolommebøker',
      fi: 'Kryptolompakot',
      is: 'Rafmyntaveski',
      fo: 'Kryptopungar',
      cs: 'Krypto peněženky',
      bg: 'Крипто портфейли',
      hr: 'Kripto novčanici',
      sr: 'Крипто новчаници',
      sl: 'Kriptodenarnice',
      mk: 'Крипто паричници',
      be: 'Крыпта-гаманцы',
      bs: 'Kripto novčanici',
      hsb: 'Kryptomóšnje',
    }),
    subtitle: t({
      ru: 'Доходы и расходы по кошелькам попадают в общую статистику автоматически',
      en: 'Wallet income and spending flow into your regular statistics automatically',
      kk: 'Әмиян бойынша кірістер мен шығыстар жалпы статистикаға автоматты түрде түседі',
      de: 'Einnahmen und Ausgaben der Wallet fließen automatisch in Ihre Statistik ein',
      fr: 'Les entrées et sorties du portefeuille alimentent automatiquement vos statistiques',
      es: 'Los ingresos y gastos de la cartera entran automáticamente en tus estadísticas',
      pt: 'As receitas e despesas da carteira entram automaticamente nas suas estatísticas',
      tr: 'Cüzdan gelir ve giderleri istatistiklerinize otomatik olarak akar',
      uk: 'Доходи та витрати гаманця автоматично потрапляють до загальної статистики',
      zh: '钱包的收入与支出会自动计入常规统计',
      pl: 'Przychody i wydatki portfela trafiają do statystyk automatycznie',
      it: 'Entrate e uscite del portafoglio confluiscono automaticamente nelle statistiche',
      sk: 'Príjmy a výdavky peňaženky sa automaticky započítajú do štatistík',
      ja: 'ウォレットの収入と支出は自動的に通常の統計に反映されます',
      ko: '지갑의 수입과 지출이 자동으로 일반 통계에 반영됩니다',
      hi: 'वॉलेट की आय और व्यय स्वतः आपके सामान्य आँकड़ों में जुड़ जाते हैं',
      nl: 'Inkomsten en uitgaven van de wallet komen automatisch in je statistieken',
      sv: 'Plånbokens inkomster och utgifter förs automatiskt in i din statistik',
      vi: 'Thu nhập và chi tiêu của ví tự động được tính vào thống kê chung',
      id: 'Pemasukan dan pengeluaran dompet otomatis masuk ke statistik Anda',
      da: 'Indtægter og udgifter fra wallets flyder automatisk ind i din almindelige statistik',
      nb: 'Inntekter og utgifter fra lommebøker går automatisk inn i den vanlige statistikken',
      nn: 'Inntekter og utgifter frå lommebøker går automatisk inn i den vanlege statistikken',
      fi: 'Lompakoiden tulot ja menot siirtyvät automaattisesti tavallisiin tilastoihisi',
      is: 'Tekjur og útgjöld veskja fara sjálfkrafa inn í venjulegu tölfræðina þína',
      fo: 'Inntøkur og útgjøld úr pungum fara sjálvvirkandi inn í vanligu hagtølini tín',
      cs: 'Příjmy a výdaje peněženek automaticky vstupují do vašich běžných statistik',
      bg: 'Приходите и разходите от портфейлите влизат автоматично в обичайната ви статистика',
      hr: 'Primici i troškovi novčanika automatski ulaze u vašu uobičajenu statistiku',
      sr: 'Приходи и трошкови новчаника аутоматски улазе у вашу уобичајену статистику',
      sl: 'Prejemki in izdatki denarnic samodejno pridejo v vašo običajno statistiko',
      mk: 'Приходите и трошоците од паричниците автоматски влегуваат во вашата обична статистика',
      be: 'Прыбыткі і выдаткі гаманцоў аўтаматычна трапляюць у вашу звычайную статыстыку',
      bs: 'Primici i troškovi novčanika automatski ulaze u vašu uobičajenu statistiku',
      hsb: 'Dochody a wudawki móšnjow so awtomatisce do wašeje normalneje statistiki dóstanu',
    }),
    readOnly: t({
      ru: 'Только чтение: мы запрашиваем публичный адрес и никогда — приватные ключи или seed-фразу',
      en: 'Read-only: we ask for a public address and never for private keys or a seed phrase',
      kk: 'Тек оқу: біз тек ашық мекенжайды сұраймыз, жеке кілттерді немесе seed-фразаны ешқашан',
      de: 'Nur lesend: Wir fragen nach einer öffentlichen Adresse, nie nach Schlüsseln oder Seed',
      fr: 'Lecture seule : nous demandons une adresse publique, jamais vos clés ou votre phrase',
      es: 'Solo lectura: pedimos una dirección pública, nunca claves privadas ni frase semilla',
      pt: 'Apenas leitura: pedimos um endereço público, nunca chaves privadas ou frase-semente',
      tr: 'Salt okunur: yalnızca genel adres isteriz, özel anahtar veya kurtarma ifadesi asla',
      uk: 'Лише читання: ми просимо публічну адресу і ніколи — приватні ключі чи seed-фразу',
      zh: '只读：我们只索取公开地址，绝不索取私钥或助记词',
      pl: 'Tylko odczyt: prosimy o adres publiczny, nigdy o klucze prywatne ani frazę seed',
      it: 'Sola lettura: chiediamo un indirizzo pubblico, mai chiavi private o seed phrase',
      sk: 'Iba na čítanie: pýtame si verejnú adresu, nikdy súkromné kľúče ani seed frázu',
      ja: '読み取り専用：公開アドレスのみを求め、秘密鍵やシードフレーズは求めません',
      ko: '읽기 전용: 공개 주소만 요청하며 개인 키나 시드 문구는 요구하지 않습니다',
      hi: 'केवल पढ़ने के लिए: हम सार्वजनिक पता माँगते हैं, निजी कुंजी या सीड फ़्रेज़ कभी नहीं',
      nl: 'Alleen-lezen: we vragen een openbaar adres, nooit privésleutels of een seed phrase',
      sv: 'Skrivskyddat: vi ber om en publik adress, aldrig privata nycklar eller seed-fras',
      vi: 'Chỉ đọc: chúng tôi chỉ hỏi địa chỉ công khai, không bao giờ khóa riêng hay seed phrase',
      id: 'Hanya baca: kami meminta alamat publik, tidak pernah kunci privat atau seed phrase',
      da: 'Kun læseadgang: vi beder om en offentlig adresse og aldrig om private nøgler eller en seed-sætning',
      nb: 'Kun lesetilgang: vi ber om en offentlig adresse og aldri om private nøkler eller en seed-frase',
      nn: 'Berre lesetilgang: vi ber om ei offentleg adresse og aldri om private nøklar eller ei seed-frase',
      fi: 'Vain luku: pyydämme julkisen osoitteen, emme koskaan yksityisiä avaimia tai siemenlausetta',
      is: 'Aðeins lestur: við biðjum um opinbert vistfang og aldrei um einkalykla eða seed-setningu',
      fo: 'Bert lesturin: vit spyrja um eina almenna adressu og aldri um privatar nykla ella eina seed-setning',
      cs: 'Jen pro čtení: žádáme veřejnou adresu, nikdy ne privátní klíče ani seed frázi',
      bg: 'Само за четене: искаме публичен адрес и никога частни ключове или seed фраза',
      hr: 'Samo za čitanje: tražimo javnu adresu i nikada privatne ključeve ni seed izraz',
      sr: 'Само за читање: тражимо јавну адресу и никада приватне кључеве ни seed израз',
      sl: 'Samo za branje: prosimo za javni naslov in nikoli za zasebne ključe ali seed frazo',
      mk: 'Само за читање: бараме јавна адреса и никогаш приватни клучеви или seed фраза',
      be: 'Толькі чытанне: мы просім публічны адрас і ніколі прыватныя ключы ці seed-фразу',
      bs: 'Samo za čitanje: tražimo javnu adresu i nikada privatne ključeve ni seed izraz',
      hsb: 'Jenož čitać: prosymy wo zjawnu adresu a nihdy wo priwatne kluče abo seed-frazu',
    }),
    connect: t({
      ru: 'Подключить кошелёк',
      en: 'Connect wallet',
      kk: 'Әмиянды қосу',
      de: 'Wallet verbinden',
      fr: 'Connecter un portefeuille',
      es: 'Conectar cartera',
      pt: 'Ligar carteira',
      tr: 'Cüzdan bağla',
      uk: 'Підключити гаманець',
      zh: '连接钱包',
      pl: 'Połącz portfel',
      it: 'Collega portafoglio',
      sk: 'Pripojiť peňaženku',
      ja: 'ウォレットを接続',
      ko: '지갑 연결',
      hi: 'वॉलेट जोड़ें',
      nl: 'Wallet verbinden',
      sv: 'Anslut plånbok',
      vi: 'Kết nối ví',
      id: 'Hubungkan dompet',
      da: 'Tilslut wallet',
      nb: 'Koble til lommebok',
      nn: 'Kople til lommebok',
      fi: 'Yhdistä lompakko',
      is: 'Tengja veski',
      fo: 'Knýt pung',
      cs: 'Připojit peněženku',
      bg: 'Свържи портфейл',
      hr: 'Poveži novčanik',
      sr: 'Повежи новчаник',
      sl: 'Poveži denarnico',
      mk: 'Поврзи паричник',
      be: 'Падключыць гаманец',
      bs: 'Poveži novčanik',
      hsb: 'Móšnju zwjazać',
    }),
    walletsLabel: t({
      ru: 'Подключить кошелёк из браузера',
      en: 'Connect a browser wallet',
      kk: 'Браузер әмиянын қосу',
      de: 'Browser-Wallet verbinden',
      fr: 'Connecter un portefeuille du navigateur',
      es: 'Conectar una billetera del navegador',
      pt: 'Ligar uma carteira do navegador',
      tr: 'Tarayıcı cüzdanı bağla',
      uk: 'Підключити гаманець із браузера',
      zh: '连接浏览器钱包',
      pl: 'Połącz portfel z przeglądarki',
      it: 'Collega un wallet del browser',
      sk: 'Pripojiť peňaženku z prehliadača',
      ja: 'ブラウザのウォレットを接続',
      ko: '브라우저 지갑 연결',
      hi: 'ब्राउज़र वॉलेट जोड़ें',
      nl: 'Browserwallet verbinden',
      sv: 'Anslut en webbläsarplånbok',
      vi: 'Kết nối ví trên trình duyệt',
      id: 'Hubungkan dompet browser',
      da: 'Tilslut en browser-wallet',
      nb: 'Koble til en nettleserlommebok',
      nn: 'Kople til ei nettlesarlommebok',
      fi: 'Yhdistä selainlompakko',
      is: 'Tengja vafraveski',
      fo: 'Knýt ein kagara-pung',
      cs: 'Připojit peněženku v prohlížeči',
      bg: 'Свържи портфейл в браузъра',
      hr: 'Poveži novčanik u pregledniku',
      sr: 'Повежи новчаник у прегледачу',
      sl: 'Poveži denarnico v brskalniku',
      mk: 'Поврзи паричник во прелистувачот',
      be: 'Падключыць гаманец у браўзеры',
      bs: 'Poveži novčanik u pretraživaču',
      hsb: 'Móšnju we wobhladowaku zwjazać',
    }),
    install: t({
      ru: 'Установить',
      en: 'Install',
      kk: 'Орнату',
      de: 'Installieren',
      fr: 'Installer',
      es: 'Instalar',
      pt: 'Instalar',
      tr: 'Yükle',
      uk: 'Встановити',
      zh: '安装',
      pl: 'Zainstaluj',
      it: 'Installa',
      sk: 'Nainštalovať',
      ja: 'インストール',
      ko: '설치',
      hi: 'इंस्टॉल करें',
      nl: 'Installeren',
      sv: 'Installera',
      vi: 'Cài đặt',
      id: 'Pasang',
      da: 'Installér',
      nb: 'Installer',
      nn: 'Installer',
      fi: 'Asenna',
      is: 'Setja upp',
      fo: 'Set upp',
      cs: 'Nainstalovat',
      bg: 'Инсталирай',
      hr: 'Instaliraj',
      sr: 'Инсталирај',
      sl: 'Namesti',
      mk: 'Инсталирај',
      be: 'Устанавіць',
      bs: 'Instaliraj',
      hsb: 'Instalować',
    }),
    manualHint: t({
      ru: 'или вставьте публичный адрес вручную',
      en: 'or paste a public address',
      kk: 'немесе ашық мекенжайды қолмен енгізіңіз',
      de: 'oder eine öffentliche Adresse einfügen',
      fr: 'ou collez une adresse publique',
      es: 'o pega una dirección pública',
      pt: 'ou cole um endereço público',
      tr: 'veya genel bir adres yapıştırın',
      uk: 'або вставте публічну адресу',
      zh: '或粘贴一个公开地址',
      pl: 'lub wklej adres publiczny',
      it: 'oppure incolla un indirizzo pubblico',
      sk: 'alebo vložte verejnú adresu',
      ja: 'または公開アドレスを貼り付け',
      ko: '또는 공개 주소를 붙여넣으세요',
      hi: 'या सार्वजनिक पता चिपकाएँ',
      nl: 'of plak een openbaar adres',
      sv: 'eller klistra in en publik adress',
      vi: 'hoặc dán một địa chỉ công khai',
      id: 'atau tempel alamat publik',
      da: 'eller indsæt en offentlig adresse',
      nb: 'eller lim inn en offentlig adresse',
      nn: 'eller lim inn ei offentleg adresse',
      fi: 'tai liitä julkinen osoite',
      is: 'eða límdu inn opinbert vistfang',
      fo: 'ella lim inn eina almenna adressu',
      cs: 'nebo vložte veřejnou adresu',
      bg: 'или поставете публичен адрес',
      hr: 'ili zalijepite javnu adresu',
      sr: 'или залепите јавну адресу',
      sl: 'ali prilepite javni naslov',
      mk: 'или вметнете јавна адреса',
      be: 'або ўстаўце публічны адрас',
      bs: 'ili zalijepite javnu adresu',
      hsb: 'abo zasaďće zjawnu adresu',
    }),
    addressLabel: t({
      ru: 'Адрес кошелька',
      en: 'Wallet address',
      kk: 'Әмиян мекенжайы',
      de: 'Wallet-Adresse',
      fr: 'Adresse du portefeuille',
      es: 'Dirección de la cartera',
      pt: 'Endereço da carteira',
      tr: 'Cüzdan adresi',
      uk: 'Адреса гаманця',
      zh: '钱包地址',
      pl: 'Adres portfela',
      it: 'Indirizzo del portafoglio',
      sk: 'Adresa peňaženky',
      ja: 'ウォレットアドレス',
      ko: '지갑 주소',
      hi: 'वॉलेट पता',
      nl: 'Walletadres',
      sv: 'Plånboksadress',
      vi: 'Địa chỉ ví',
      id: 'Alamat dompet',
      da: 'Wallet-adresse',
      nb: 'Lommebokadresse',
      nn: 'Lommebokadresse',
      fi: 'Lompakon osoite',
      is: 'Vistfang veskis',
      fo: 'Pungsadressa',
      cs: 'Adresa peněženky',
      bg: 'Адрес на портфейла',
      hr: 'Adresa novčanika',
      sr: 'Адреса новчаника',
      sl: 'Naslov denarnice',
      mk: 'Адреса на паричникот',
      be: 'Адрас гаманца',
      bs: 'Adresa novčanika',
      hsb: 'Adresa móšnje',
    }),
    nameLabel: t({
      ru: 'Название (необязательно)',
      en: 'Name (optional)',
      kk: 'Атауы (міндетті емес)',
      de: 'Name (optional)',
      fr: 'Nom (facultatif)',
      es: 'Nombre (opcional)',
      pt: 'Nome (opcional)',
      tr: 'Ad (isteğe bağlı)',
      uk: 'Назва (необов’язково)',
      zh: '名称（可选）',
      pl: 'Nazwa (opcjonalnie)',
      it: 'Nome (facoltativo)',
      sk: 'Názov (voliteľné)',
      ja: '名前（任意）',
      ko: '이름 (선택)',
      hi: 'नाम (वैकल्पिक)',
      nl: 'Naam (optioneel)',
      sv: 'Namn (valfritt)',
      vi: 'Tên (không bắt buộc)',
      id: 'Nama (opsional)',
      da: 'Navn (valgfrit)',
      nb: 'Navn (valgfritt)',
      nn: 'Namn (valfritt)',
      fi: 'Nimi (valinnainen)',
      is: 'Nafn (valfrjálst)',
      fo: 'Navn (valfrítt)',
      cs: 'Název (nepovinné)',
      bg: 'Име (по избор)',
      hr: 'Naziv (neobavezno)',
      sr: 'Назив (необавезно)',
      sl: 'Ime (neobvezno)',
      mk: 'Име (опционално)',
      be: 'Назва (неабавязкова)',
      bs: 'Naziv (nije obavezno)',
      hsb: 'Mjeno (opcionalne)',
    }),
    invalidAddress: t({
      ru: 'Это не похоже на адрес Ethereum/EVM, Tron, Bitcoin или Solana',
      en: 'That does not look like an Ethereum/EVM, Tron, Bitcoin or Solana address',
      kk: 'Бұл Ethereum/EVM, Tron, Bitcoin немесе Solana мекенжайына ұқсамайды',
      de: 'Das sieht nicht nach einer Ethereum/EVM-, Tron-, Bitcoin- oder Solana-Adresse aus',
      fr: 'Cela ne ressemble pas à une adresse Ethereum/EVM, Tron, Bitcoin ou Solana',
      es: 'No parece una dirección de Ethereum/EVM, Tron, Bitcoin ni Solana',
      pt: 'Isso não parece um endereço Ethereum/EVM, Tron, Bitcoin ou Solana',
      tr: 'Bu bir Ethereum/EVM, Tron, Bitcoin veya Solana adresine benzemiyor',
      uk: 'Це не схоже на адресу Ethereum/EVM, Tron, Bitcoin або Solana',
      zh: '这不像是 Ethereum/EVM、Tron、Bitcoin 或 Solana 地址',
      pl: 'To nie wygląda na adres Ethereum/EVM, Tron, Bitcoin ani Solana',
      it: 'Non sembra un indirizzo Ethereum/EVM, Tron, Bitcoin o Solana',
      sk: 'Toto nevyzerá ako adresa Ethereum/EVM, Tron, Bitcoin ani Solana',
      ja: 'Ethereum/EVM、Tron、Bitcoin、Solana のいずれのアドレスでもないようです',
      ko: 'Ethereum/EVM, Tron, Bitcoin, Solana 주소가 아닌 것 같습니다',
      hi: 'यह Ethereum/EVM, Tron, Bitcoin या Solana पता नहीं लगता',
      nl: 'Dit lijkt geen Ethereum/EVM-, Tron-, Bitcoin- of Solana-adres',
      sv: 'Det ser inte ut som en Ethereum/EVM-, Tron-, Bitcoin- eller Solana-adress',
      vi: 'Đây không giống địa chỉ Ethereum/EVM, Tron, Bitcoin hay Solana',
      id: 'Ini tidak terlihat seperti alamat Ethereum/EVM, Tron, Bitcoin, atau Solana',
      da: 'Det ser ikke ud som en Ethereum/EVM-, Tron-, Bitcoin- eller Solana-adresse',
      nb: 'Det ser ikke ut som en Ethereum/EVM-, Tron-, Bitcoin- eller Solana-adresse',
      nn: 'Det ser ikkje ut som ei Ethereum/EVM-, Tron-, Bitcoin- eller Solana-adresse',
      fi: 'Tämä ei näytä Ethereum/EVM-, Tron-, Bitcoin- tai Solana-osoitteelta',
      is: 'Þetta lítur ekki út eins og Ethereum/EVM-, Tron-, Bitcoin- eða Solana-vistfang',
      fo: 'Hetta sær ikki út sum ein Ethereum/EVM-, Tron-, Bitcoin- ella Solana-adressa',
      cs: 'Tohle nevypadá jako adresa Ethereum/EVM, Tron, Bitcoin ani Solana',
      bg: 'Това не изглежда като адрес на Ethereum/EVM, Tron, Bitcoin или Solana',
      hr: 'To ne izgleda kao Ethereum/EVM, Tron, Bitcoin ili Solana adresa',
      sr: 'То не изгледа као Ethereum/EVM, Tron, Bitcoin или Solana адреса',
      sl: 'To ni videti kot naslov Ethereum/EVM, Tron, Bitcoin ali Solana',
      mk: 'Ова не изгледа како адреса на Ethereum/EVM, Tron, Bitcoin или Solana',
      be: 'Гэта не падобна на адрас Ethereum/EVM, Tron, Bitcoin ці Solana',
      bs: 'To ne izgleda kao Ethereum/EVM, Tron, Bitcoin ili Solana adresa',
      hsb: 'To njewupada kaž adresa Ethereum/EVM, Tron, Bitcoin abo Solana',
    }),
    networksHint: t({
      ru: 'Поддерживаются Ethereum, Base, Arbitrum, Optimism, Polygon (адрес 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) и Solana. Сеть определяется по адресу; для 0x-адреса отметьте нужные сети. Кошелёк передаёт адрес своей сети; кошельки других сетей подключите отдельно или вставьте адрес вручную.',
      en: 'Supported: Ethereum, Base, Arbitrum, Optimism, Polygon (0x… address), Tron (T…), Bitcoin (bc1…, 1…, 3…) and Solana. The network is read from the address; for a 0x address, tick the networks you use. A wallet shares the address of its own network; connect the others separately or paste them by hand.',
      kk: 'Ethereum, Base, Arbitrum, Optimism, Polygon (0x… мекенжайы), Tron (T…), Bitcoin (bc1…, 1…, 3…) және Solana қолдау көрсетіледі. Желі мекенжай бойынша анықталады; 0x мекенжайы үшін қажетті желілерді белгілеңіз. Әмиян өз желісінің мекенжайын береді; басқаларын бөлек қосыңыз немесе қолмен қойыңыз.',
      de: 'Unterstützt: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-Adresse), Tron (T…), Bitcoin (bc1…, 1…, 3…) und Solana. Das Netzwerk wird an der Adresse erkannt; bei einer 0x-Adresse die genutzten Netzwerke anhaken. Eine Wallet gibt die Adresse ihres eigenen Netzwerks weiter; die anderen separat verbinden oder manuell einfügen.',
      fr: 'Pris en charge : Ethereum, Base, Arbitrum, Optimism, Polygon (adresse 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) et Solana. Le réseau est déduit de l’adresse ; pour une adresse 0x, cochez les réseaux utilisés. Un portefeuille transmet l’adresse de son propre réseau ; connectez les autres séparément ou collez-les à la main.',
      es: 'Compatibles: Ethereum, Base, Arbitrum, Optimism, Polygon (dirección 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) y Solana. La red se detecta por la dirección; para una dirección 0x, marca las redes que usas. Una billetera comparte la dirección de su propia red; conecta las demás por separado o pégalas a mano.',
      pt: 'Suportados: Ethereum, Base, Arbitrum, Optimism, Polygon (endereço 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) e Solana. A rede é identificada pelo endereço; para um endereço 0x, marque as redes que usa. Uma carteira compartilha o endereço da sua própria rede; ligue as outras separadamente ou cole-as manualmente.',
      tr: 'Desteklenenler: Ethereum, Base, Arbitrum, Optimism, Polygon (0x… adresi), Tron (T…), Bitcoin (bc1…, 1…, 3…) ve Solana. Ağ adresten anlaşılır; 0x adresi için kullandığınız ağları işaretleyin. Cüzdan yalnızca kendi ağının adresini paylaşır; diğerlerini ayrıca bağlayın veya elle yapıştırın.',
      uk: 'Підтримуються Ethereum, Base, Arbitrum, Optimism, Polygon (адреса 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) і Solana. Мережа визначається за адресою; для 0x-адреси позначте потрібні мережі. Гаманець передає адресу своєї мережі; інші підключіть окремо або вставте вручну.',
      zh: '支持 Ethereum、Base、Arbitrum、Optimism、Polygon（0x… 地址）、Tron（T…）、Bitcoin（bc1…、1…、3…）和 Solana。网络由地址识别；0x 地址请勾选所用网络。钱包只提供其所在网络的地址；其他地址请另行连接或手动粘贴。',
      pl: 'Obsługiwane: Ethereum, Base, Arbitrum, Optimism, Polygon (adres 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) i Solana. Sieć rozpoznajemy po adresie; dla adresu 0x zaznacz używane sieci. Portfel udostępnia adres swojej sieci; pozostałe połącz osobno lub wklej ręcznie.',
      it: 'Supportati: Ethereum, Base, Arbitrum, Optimism, Polygon (indirizzo 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) e Solana. La rete si ricava dall’indirizzo; per un indirizzo 0x spunta le reti che usi. Un wallet condivide l’indirizzo della propria rete: collega gli altri a parte o incollali a mano.',
      sk: 'Podporované: Ethereum, Base, Arbitrum, Optimism, Polygon (adresa 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) a Solana. Sieť sa určí podľa adresy; pri adrese 0x označte používané siete. Peňaženka poskytne adresu svojej siete; ostatné pripojte samostatne alebo vložte ručne.',
      ja: '対応: Ethereum、Base、Arbitrum、Optimism、Polygon（0x… アドレス）、Tron（T…）、Bitcoin（bc1…、1…、3…）、Solana。ネットワークはアドレスから判別します。0x アドレスは使うネットワークにチェックを入れてください。ウォレットが渡すのは自分のネットワークのアドレスだけです。ほかは別途接続するか、手動で貼り付けてください。',
      ko: '지원: Ethereum, Base, Arbitrum, Optimism, Polygon(0x… 주소), Tron(T…), Bitcoin(bc1…, 1…, 3…), Solana. 네트워크는 주소로 판별하며, 0x 주소는 사용하는 네트워크를 체크하세요. 지갑은 자기 네트워크의 주소만 전달하므로 나머지는 따로 연결하거나 직접 붙여 넣으세요.',
      hi: 'समर्थित: Ethereum, Base, Arbitrum, Optimism, Polygon (0x… पता), Tron (T…), Bitcoin (bc1…, 1…, 3…) और Solana। नेटवर्क पते से पहचाना जाता है; 0x पते के लिए इस्तेमाल होने वाले नेटवर्क चुनें। वॉलेट केवल अपने नेटवर्क का पता देता है; बाकी अलग से जोड़ें या हाथ से चिपकाएँ।',
      nl: 'Ondersteund: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-adres), Tron (T…), Bitcoin (bc1…, 1…, 3…) en Solana. Het netwerk volgt uit het adres; vink bij een 0x-adres de netwerken aan die je gebruikt. Een wallet deelt het adres van zijn eigen netwerk; verbind de andere apart of plak ze zelf.',
      sv: 'Stöds: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-adress), Tron (T…), Bitcoin (bc1…, 1…, 3…) och Solana. Nätverket avgörs av adressen; bocka för de nätverk du använder för en 0x-adress. En plånbok delar adressen för sitt eget nätverk; anslut de andra separat eller klistra in dem manuellt.',
      vi: 'Hỗ trợ: Ethereum, Base, Arbitrum, Optimism, Polygon (địa chỉ 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) và Solana. Mạng được nhận diện theo địa chỉ; với địa chỉ 0x, hãy chọn các mạng bạn dùng. Ví chỉ chia sẻ địa chỉ trên mạng của nó; hãy kết nối các ví khác riêng hoặc dán địa chỉ thủ công.',
      id: 'Didukung: Ethereum, Base, Arbitrum, Optimism, Polygon (alamat 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…), dan Solana. Jaringan dikenali dari alamat; untuk alamat 0x, centang jaringan yang Anda pakai. Dompet hanya membagikan alamat jaringannya sendiri; hubungkan yang lain terpisah atau tempel secara manual.',
      da: 'Understøttet: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-adresse), Tron (T…), Bitcoin (bc1…, 1…, 3…) og Solana. Netværket læses ud af adressen; for en 0x-adresse skal du markere de netværk, du bruger. En wallet deler kun adressen for sit eget netværk; tilslut de øvrige separat eller indsæt dem manuelt.',
      nb: 'Støttet: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-adresse), Tron (T…), Bitcoin (bc1…, 1…, 3…) og Solana. Nettverket leses ut av adressen; for en 0x-adresse må du krysse av nettverkene du bruker. En lommebok deler bare adressen for sitt eget nettverk; koble til de andre separat eller lim dem inn manuelt.',
      nn: 'Støtta: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-adresse), Tron (T…), Bitcoin (bc1…, 1…, 3…) og Solana. Nettverket blir lese ut av adressa; for ei 0x-adresse må du krysse av nettverka du bruker. Ei lommebok deler berre adressa for sitt eige nettverk; kople til dei andre separat eller lim dei inn manuelt.',
      fi: 'Tuetut: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-osoite), Tron (T…), Bitcoin (bc1…, 1…, 3…) ja Solana. Verkko luetaan osoitteesta; 0x-osoitteella valitse käyttämäsi verkot. Lompakko jakaa vain oman verkkonsa osoitteen; yhdistä muut erikseen tai liitä ne käsin.',
      is: 'Styður: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-vistfang), Tron (T…), Bitcoin (bc1…, 1…, 3…) og Solana. Netið er lesið úr vistfanginu; fyrir 0x-vistfang skaltu haka við netin sem þú notar. Veski gefur aðeins vistfang eigin nets; tengdu önnur sérstaklega eða límdu þau inn sjálfur.',
      fo: 'Stuðlað: Ethereum, Base, Arbitrum, Optimism, Polygon (0x…-adressa), Tron (T…), Bitcoin (bc1…, 1…, 3…) og Solana. Netið verður lisið úr adressuni; fyri eina 0x-adressu merk tey net tú brúkar. Ein pungur gevur bert adressuna fyri sítt egna net; knýt tey onnur sær ella lim tey inn við hond.',
      cs: 'Podporováno: Ethereum, Base, Arbitrum, Optimism, Polygon (adresa 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) a Solana. Síť se vyčte z adresy; u adresy 0x zaškrtněte sítě, které používáte. Peněženka vydá jen adresu své vlastní sítě; ostatní připojte zvlášť nebo je vložte ručně.',
      bg: 'Поддържани: Ethereum, Base, Arbitrum, Optimism, Polygon (адрес 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) и Solana. Мрежата се чете от адреса; за адрес 0x отметнете мрежите, които ползвате. Портфейлът дава само адреса на собствената си мрежа; свържете останалите отделно или ги поставете ръчно.',
      hr: 'Podržano: Ethereum, Base, Arbitrum, Optimism, Polygon (adresa 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) i Solana. Mreža se čita iz adrese; za adresu 0x označite mreže koje koristite. Novčanik daje samo adresu svoje mreže; ostale povežite zasebno ili ih zalijepite ručno.',
      sr: 'Подржано: Ethereum, Base, Arbitrum, Optimism, Polygon (адреса 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) и Solana. Мрежа се чита из адресе; за адресу 0x означите мреже које користите. Новчаник даје само адресу своје мреже; остале повежите засебно или их залепите ручно.',
      sl: 'Podprto: Ethereum, Base, Arbitrum, Optimism, Polygon (naslov 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) in Solana. Omrežje se prebere iz naslova; pri naslovu 0x označite omrežja, ki jih uporabljate. Denarnica da le naslov svojega omrežja; druga povežite posebej ali jih prilepite ročno.',
      mk: 'Поддржано: Ethereum, Base, Arbitrum, Optimism, Polygon (адреса 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) и Solana. Мрежата се чита од адресата; за адреса 0x означете ги мрежите што ги користите. Паричникот дава само адреса на својата мрежа; другите поврзете ги одделно или вметнете ги рачно.',
      be: 'Падтрымліваюцца: Ethereum, Base, Arbitrum, Optimism, Polygon (адрас 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) і Solana. Сетка чытаецца з адраса; для адраса 0x адзначце сеткі, якія вы выкарыстоўваеце. Гаманец дае толькі адрас сваёй сеткі; астатнія падключыце асобна або ўстаўце ўручную.',
      bs: 'Podržano: Ethereum, Base, Arbitrum, Optimism, Polygon (adresa 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) i Solana. Mreža se čita iz adrese; za adresu 0x označite mreže koje koristite. Novčanik daje samo adresu svoje mreže; ostale povežite zasebno ili ih zalijepite ručno.',
      hsb: 'Podpěrane: Ethereum, Base, Arbitrum, Optimism, Polygon (adresa 0x…), Tron (T…), Bitcoin (bc1…, 1…, 3…) a Solana. Syć so z adresy čita; při adresy 0x markujće syće, kotrež wužiwaće. Móšnja da jenož adresu swojeje syće; druhe zwjazajće separatnje abo zasaďće je z ruku.',
    }),
    networksLabel: t({
      ru: 'Сети',
      en: 'Networks',
      kk: 'Желілер',
      de: 'Netzwerke',
      fr: 'Réseaux',
      es: 'Redes',
      pt: 'Redes',
      tr: 'Ağlar',
      uk: 'Мережі',
      zh: '网络',
      pl: 'Sieci',
      it: 'Reti',
      sk: 'Siete',
      ja: 'ネットワーク',
      ko: '네트워크',
      hi: 'नेटवर्क',
      nl: 'Netwerken',
      sv: 'Nätverk',
      vi: 'Mạng',
      id: 'Jaringan',
      da: 'Netværk',
      nb: 'Nettverk',
      nn: 'Nettverk',
      fi: 'Verkot',
      is: 'Net',
      fo: 'Net',
      cs: 'Sítě',
      bg: 'Мрежи',
      hr: 'Mreže',
      sr: 'Мреже',
      sl: 'Omrežja',
      mk: 'Мрежи',
      be: 'Сеткі',
      bs: 'Mreže',
      hsb: 'Syće',
    }),
    networkDetected: t({
      ru: 'Сеть:',
      en: 'Network:',
      kk: 'Желі:',
      de: 'Netzwerk:',
      fr: 'Réseau :',
      es: 'Red:',
      pt: 'Rede:',
      tr: 'Ağ:',
      uk: 'Мережа:',
      zh: '网络：',
      pl: 'Sieć:',
      it: 'Rete:',
      sk: 'Sieť:',
      ja: 'ネットワーク：',
      ko: '네트워크:',
      hi: 'नेटवर्क:',
      nl: 'Netwerk:',
      sv: 'Nätverk:',
      vi: 'Mạng:',
      id: 'Jaringan:',
      da: 'Netværk:',
      nb: 'Nettverk:',
      nn: 'Nettverk:',
      fi: 'Verkko:',
      is: 'Net:',
      fo: 'Net:',
      cs: 'Síť:',
      bg: 'Мрежа:',
      hr: 'Mreža:',
      sr: 'Мрежа:',
      sl: 'Omrežje:',
      mk: 'Мрежа:',
      be: 'Сетка:',
      bs: 'Mreža:',
      hsb: 'Syć:',
    }),
    noNetworkSelected: t({
      ru: 'Отметьте хотя бы одну сеть',
      en: 'Tick at least one network',
      kk: 'Кемінде бір желіні белгілеңіз',
      de: 'Mindestens ein Netzwerk anhaken',
      fr: 'Cochez au moins un réseau',
      es: 'Marca al menos una red',
      pt: 'Marque pelo menos uma rede',
      tr: 'En az bir ağ işaretleyin',
      uk: 'Позначте принаймні одну мережу',
      zh: '请至少勾选一个网络',
      pl: 'Zaznacz co najmniej jedną sieć',
      it: 'Spunta almeno una rete',
      sk: 'Označte aspoň jednu sieť',
      ja: 'ネットワークを 1 つ以上選んでください',
      ko: '네트워크를 하나 이상 선택하세요',
      hi: 'कम से कम एक नेटवर्क चुनें',
      nl: 'Vink minstens één netwerk aan',
      sv: 'Bocka för minst ett nätverk',
      vi: 'Chọn ít nhất một mạng',
      id: 'Centang setidaknya satu jaringan',
      da: 'Markér mindst ét netværk',
      nb: 'Kryss av minst ett nettverk',
      nn: 'Kryss av minst eitt nettverk',
      fi: 'Valitse vähintään yksi verkko',
      is: 'Hakaðu við að minnsta kosti eitt net',
      fo: 'Merk í minsta lagi eitt net',
      cs: 'Zaškrtněte alespoň jednu síť',
      bg: 'Отметнете поне една мрежа',
      hr: 'Označite najmanje jednu mrežu',
      sr: 'Означите најмање једну мрежу',
      sl: 'Označite vsaj eno omrežje',
      mk: 'Означете барем една мрежа',
      be: 'Адзначце прынамсі адну сетку',
      bs: 'Označite najmanje jednu mrežu',
      hsb: 'Markujće znajmjeńša jednu syć',
    }),
    noWallet: t({
      ru: 'Браузерный кошелёк не найден — вставьте адрес вручную',
      en: 'No browser wallet found — paste an address instead',
      kk: 'Браузер әмияны табылмады — мекенжайды қолмен енгізіңіз',
      de: 'Keine Browser-Wallet gefunden — fügen Sie stattdessen eine Adresse ein',
      fr: 'Aucun portefeuille détecté — collez plutôt une adresse',
      es: 'No se encontró cartera en el navegador: pega una dirección',
      pt: 'Nenhuma carteira no navegador — cole um endereço',
      tr: 'Tarayıcı cüzdanı bulunamadı — bunun yerine bir adres yapıştırın',
      uk: 'Гаманець у браузері не знайдено — вставте адресу вручну',
      zh: '未检测到浏览器钱包 — 请改为粘贴地址',
      pl: 'Nie znaleziono portfela w przeglądarce — wklej adres',
      it: 'Nessun portafoglio nel browser: incolla un indirizzo',
      sk: 'Peňaženka v prehliadači sa nenašla — vložte adresu',
      ja: 'ブラウザウォレットが見つかりません。アドレスを貼り付けてください',
      ko: '브라우저 지갑을 찾을 수 없습니다 — 주소를 붙여넣으세요',
      hi: 'ब्राउज़र वॉलेट नहीं मिला — इसके बजाय पता चिपकाएँ',
      nl: 'Geen browserwallet gevonden — plak in plaats daarvan een adres',
      sv: 'Ingen webbläsarplånbok hittades — klistra in en adress i stället',
      vi: 'Không tìm thấy ví trình duyệt — hãy dán địa chỉ',
      id: 'Dompet browser tidak ditemukan — tempel alamat saja',
      da: 'Ingen browser-wallet fundet — indsæt en adresse i stedet',
      nb: 'Ingen nettleserlommebok funnet — lim inn en adresse i stedet',
      nn: 'Ingen nettlesarlommebok funnen — lim inn ei adresse i staden',
      fi: 'Selainlompakkoa ei löytynyt — liitä osoite sen sijaan',
      is: 'Ekkert vafraveski fannst — límdu inn vistfang í staðinn',
      fo: 'Eingin kagara-pungur funnin — lim inn eina adressu í staðin',
      cs: 'Peněženka v prohlížeči nenalezena — vložte místo toho adresu',
      bg: 'Не е намерен портфейл в браузъра — поставете адрес вместо това',
      hr: 'Novčanik u pregledniku nije nađen — zalijepite adresu',
      sr: 'Новчаник у прегледачу није нађен — залепите адресу',
      sl: 'Denarnice v brskalniku ni — prilepite naslov',
      mk: 'Не е најден паричник во прелистувачот — вметнете адреса',
      be: 'Гаманец у браўзеры не знойдзены — устаўце адрас',
      bs: 'Novčanik u pretraživaču nije nađen — zalijepite adresu',
      hsb: 'Žana móšnja we wobhladowaku namakana — zasaďće adresu',
    }),
    duplicate: t({
      ru: 'Этот адрес уже подключён',
      en: 'This address is already connected',
      kk: 'Бұл мекенжай әлдеқашан қосылған',
      de: 'Diese Adresse ist bereits verbunden',
      fr: 'Cette adresse est déjà connectée',
      es: 'Esta dirección ya está conectada',
      pt: 'Este endereço já está ligado',
      tr: 'Bu adres zaten bağlı',
      uk: 'Ця адреса вже підключена',
      zh: '该地址已连接',
      pl: 'Ten adres jest już połączony',
      it: 'Questo indirizzo è già collegato',
      sk: 'Táto adresa je už pripojená',
      ja: 'このアドレスは既に接続されています',
      ko: '이 주소는 이미 연결되어 있습니다',
      hi: 'यह पता पहले से जुड़ा है',
      nl: 'Dit adres is al verbonden',
      sv: 'Den här adressen är redan ansluten',
      vi: 'Địa chỉ này đã được kết nối',
      id: 'Alamat ini sudah terhubung',
      da: 'Denne adresse er allerede tilsluttet',
      nb: 'Denne adressen er allerede tilkoblet',
      nn: 'Denne adressa er allereie tilkopla',
      fi: 'Tämä osoite on jo yhdistetty',
      is: 'Þetta vistfang er þegar tengt',
      fo: 'Henda adressan er longu knýtt',
      cs: 'Tato adresa je už připojená',
      bg: 'Този адрес вече е свързан',
      hr: 'Ta je adresa već povezana',
      sr: 'Та адреса је већ повезана',
      sl: 'Ta naslov je že povezan',
      mk: 'Таа адреса е веќе поврзана',
      be: 'Гэты адрас ужо падключаны',
      bs: 'Ta adresa je već povezana',
      hsb: 'Tuta adresa je hižo zwjazana',
    }),
    error: t({
      ru: 'Не удалось загрузить данные',
      en: 'Could not load the data',
      kk: 'Деректерді жүктеу мүмкін болмады',
      de: 'Daten konnten nicht geladen werden',
      fr: 'Impossible de charger les données',
      es: 'No se pudieron cargar los datos',
      pt: 'Não foi possível carregar os dados',
      tr: 'Veriler yüklenemedi',
      uk: 'Не вдалося завантажити дані',
      zh: '无法加载数据',
      pl: 'Nie udało się wczytać danych',
      it: 'Impossibile caricare i dati',
      sk: 'Údaje sa nepodarilo načítať',
      ja: 'データを読み込めませんでした',
      ko: '데이터를 불러오지 못했습니다',
      hi: 'डेटा लोड नहीं हो सका',
      nl: 'Kon de gegevens niet laden',
      sv: 'Kunde inte läsa in data',
      vi: 'Không thể tải dữ liệu',
      id: 'Tidak dapat memuat data',
      da: 'Dataene kunne ikke indlæses',
      nb: 'Kunne ikke laste dataene',
      nn: 'Kunne ikkje laste dataa',
      fi: 'Tietoja ei voitu ladata',
      is: 'Ekki var unnt að hlaða gögnunum',
      fo: 'Fekk ikki lisið dáturnar',
      cs: 'Data se nepodařilo načíst',
      bg: 'Данните не можаха да се заредят',
      hr: 'Podatke nije bilo moguće učitati',
      sr: 'Податке није могуће учитати',
      sl: 'Podatkov ni bilo mogoče naložiti',
      mk: 'Податоците не можеа да се вчитаат',
      be: 'Не ўдалося загрузіць даныя',
      bs: 'Podatke nije moguće učitati',
      hsb: 'Daty njedadźa so začitać',
    }),
    errorHint: t({
      ru: 'Проверьте подключение к интернету и попробуйте ещё раз.',
      en: 'Check your connection and try again.',
      kk: 'Интернет байланысын тексеріп, қайталап көріңіз.',
      de: 'Prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
      fr: 'Vérifiez votre connexion et réessayez.',
      es: 'Comprueba tu conexión e inténtalo de nuevo.',
      pt: 'Verifique sua conexão e tente novamente.',
      tr: 'Bağlantınızı kontrol edip tekrar deneyin.',
      uk: 'Перевірте з’єднання та спробуйте ще раз.',
      zh: '请检查网络连接后重试。',
      pl: 'Sprawdź połączenie i spróbuj ponownie.',
      it: 'Controlla la connessione e riprova.',
      sk: 'Skontrolujte pripojenie a skúste to znova.',
      ja: '接続を確認して、もう一度お試しください。',
      ko: '연결을 확인한 후 다시 시도하세요.',
      hi: 'अपना कनेक्शन जाँचें और फिर से कोशिश करें।',
      nl: 'Controleer je verbinding en probeer het opnieuw.',
      sv: 'Kontrollera anslutningen och försök igen.',
      vi: 'Kiểm tra kết nối và thử lại.',
      id: 'Periksa koneksi Anda dan coba lagi.',
      da: 'Kontrollér din forbindelse og prøv igen.',
      nb: 'Sjekk tilkoblingen og prøv igjen.',
      nn: 'Sjekk tilkoplinga og prøv igjen.',
      fi: 'Tarkista yhteytesi ja yritä uudelleen.',
      is: 'Athugaðu nettenginguna og reyndu aftur.',
      fo: 'Kanna sambandið og royn aftur.',
      cs: 'Zkontrolujte připojení a zkuste to znovu.',
      bg: 'Проверете връзката си и опитайте отново.',
      hr: 'Provjerite vezu i pokušajte ponovno.',
      sr: 'Проверите везу и пробајте поново.',
      sl: 'Preverite povezavo in poskusite znova.',
      mk: 'Проверете ја врската и обидете се повторно.',
      be: 'Праверце злучэнне і паспрабуйце зноў.',
      bs: 'Provjerite vezu i pokušajte ponovo.',
      hsb: 'Přepruwujće swoje zwjazanje a spytajće hišće raz.',
    }),
    retry: t({
      ru: 'Повторить',
      en: 'Try again',
      kk: 'Қайталау',
      de: 'Erneut versuchen',
      fr: 'Réessayer',
      es: 'Reintentar',
      pt: 'Tentar novamente',
      tr: 'Tekrar dene',
      uk: 'Повторити',
      zh: '重试',
      pl: 'Spróbuj ponownie',
      it: 'Riprova',
      sk: 'Skúsiť znova',
      ja: '再試行',
      ko: '다시 시도',
      hi: 'फिर से कोशिश करें',
      nl: 'Opnieuw proberen',
      sv: 'Försök igen',
      vi: 'Thử lại',
      id: 'Coba lagi',
      da: 'Prøv igen',
      nb: 'Prøv igjen',
      nn: 'Prøv igjen',
      fi: 'Yritä uudelleen',
      is: 'Reyna aftur',
      fo: 'Royn aftur',
      cs: 'Zkusit znovu',
      bg: 'Опитай отново',
      hr: 'Pokušaj ponovno',
      sr: 'Пробај поново',
      sl: 'Poskusi znova',
      mk: 'Обиди се повторно',
      be: 'Паспрабаваць зноў',
      bs: 'Pokušaj ponovo',
      hsb: 'Hišće raz spytać',
    }),
    empty: t({
      ru: 'Пока нет подключённых кошельков',
      en: 'No wallets connected yet',
      kk: 'Әзірге қосылған әмиян жоқ',
      de: 'Noch keine Wallets verbunden',
      fr: 'Aucun portefeuille connecté pour l’instant',
      es: 'Aún no hay carteras conectadas',
      pt: 'Ainda não há carteiras ligadas',
      tr: 'Henüz bağlı cüzdan yok',
      uk: 'Поки немає підключених гаманців',
      zh: '尚未连接任何钱包',
      pl: 'Brak połączonych portfeli',
      it: 'Nessun portafoglio collegato',
      sk: 'Zatiaľ žiadne pripojené peňaženky',
      ja: '接続済みのウォレットはありません',
      ko: '연결된 지갑이 없습니다',
      hi: 'अभी कोई वॉलेट नहीं जुड़ा',
      nl: 'Nog geen wallets verbonden',
      sv: 'Inga plånböcker anslutna än',
      vi: 'Chưa có ví nào được kết nối',
      id: 'Belum ada dompet yang terhubung',
      da: 'Ingen wallets tilsluttet endnu',
      nb: 'Ingen lommebøker tilkoblet ennå',
      nn: 'Ingen lommebøker tilkopla enno',
      fi: 'Ei vielä yhdistettyjä lompakoita',
      is: 'Engin veski tengd enn',
      fo: 'Ongir pungar knýttir enn',
      cs: 'Zatím nejsou připojené žádné peněženky',
      bg: 'Още няма свързани портфейли',
      hr: 'Još nema povezanih novčanika',
      sr: 'Још нема повезаних новчаника',
      sl: 'Še ni povezanih denarnic',
      mk: 'Сè уште нема поврзани паричници',
      be: 'Падключаных гаманцоў пакуль няма',
      bs: 'Još nema povezanih novčanika',
      hsb: 'Hišće žane zwjazane móšnje',
    }),
    portfolio: t({
      ru: 'Стоимость портфеля',
      en: 'Portfolio value',
      kk: 'Портфель құны',
      de: 'Portfoliowert',
      fr: 'Valeur du portefeuille',
      es: 'Valor de la cartera',
      pt: 'Valor da carteira',
      tr: 'Portföy değeri',
      uk: 'Вартість портфеля',
      zh: '投资组合价值',
      pl: 'Wartość portfela',
      it: 'Valore del portafoglio',
      sk: 'Hodnota portfólia',
      ja: 'ポートフォリオ評価額',
      ko: '포트폴리오 가치',
      hi: 'पोर्टफोलियो मूल्य',
      nl: 'Portefeuillewaarde',
      sv: 'Portföljvärde',
      vi: 'Giá trị danh mục',
      id: 'Nilai portofolio',
      da: 'Porteføljeværdi',
      nb: 'Porteføljeverdi',
      nn: 'Porteføljeverdi',
      fi: 'Salkun arvo',
      is: 'Verðmæti eignasafns',
      fo: 'Virði av eignasavni',
      cs: 'Hodnota portfolia',
      bg: 'Стойност на портфолиото',
      hr: 'Vrijednost portfelja',
      sr: 'Вредност портфолија',
      sl: 'Vrednost portfelja',
      mk: 'Вредност на портфолиото',
      be: 'Вартасць партфеля',
      bs: 'Vrijednost portfelja',
      hsb: 'Hódnota portfolija',
    }),
    income: t({
      ru: 'Поступления за 30 дней',
      en: 'Received in 30 days',
      kk: '30 күндегі түсімдер',
      de: 'Eingegangen in 30 Tagen',
      fr: 'Reçu sur 30 jours',
      es: 'Recibido en 30 días',
      pt: 'Recebido em 30 dias',
      tr: '30 günde gelen',
      uk: 'Надходження за 30 днів',
      zh: '30 天内收入',
      pl: 'Wpływy w 30 dni',
      it: 'Ricevuto in 30 giorni',
      sk: 'Prijaté za 30 dní',
      ja: '30日間の受取額',
      ko: '30일간 수령액',
      hi: '30 दिनों में प्राप्त',
      nl: 'Ontvangen in 30 dagen',
      sv: 'Mottaget på 30 dagar',
      vi: 'Nhận trong 30 ngày',
      id: 'Diterima dalam 30 hari',
      da: 'Modtaget i 30 dage',
      nb: 'Mottatt på 30 dager',
      nn: 'Motteke på 30 dagar',
      fi: 'Vastaanotettu 30 päivässä',
      is: 'Móttekið á 30 dögum',
      fo: 'Móttikið í 30 dagar',
      cs: 'Přijato za 30 dní',
      bg: 'Получено за 30 дни',
      hr: 'Primljeno u 30 dana',
      sr: 'Примљено у 30 дана',
      sl: 'Prejeto v 30 dneh',
      mk: 'Примено за 30 дена',
      be: 'Атрымана за 30 дзён',
      bs: 'Primljeno u 30 dana',
      hsb: 'Dóstate za 30 dnjow',
    }),
    expense: t({
      ru: 'Списания за 30 дней',
      en: 'Spent in 30 days',
      kk: '30 күндегі шығыстар',
      de: 'Ausgegeben in 30 Tagen',
      fr: 'Dépensé sur 30 jours',
      es: 'Gastado en 30 días',
      pt: 'Gasto em 30 dias',
      tr: '30 günde harcanan',
      uk: 'Списання за 30 днів',
      zh: '30 天内支出',
      pl: 'Wydatki w 30 dni',
      it: 'Speso in 30 giorni',
      sk: 'Minuté za 30 dní',
      ja: '30日間の支出額',
      ko: '30일간 지출액',
      hi: '30 दिनों में खर्च',
      nl: 'Uitgegeven in 30 dagen',
      sv: 'Spenderat på 30 dagar',
      vi: 'Chi trong 30 ngày',
      id: 'Dibelanjakan dalam 30 hari',
      da: 'Brugt i 30 dage',
      nb: 'Brukt på 30 dager',
      nn: 'Brukt på 30 dagar',
      fi: 'Käytetty 30 päivässä',
      is: 'Eytt á 30 dögum',
      fo: 'Brúkt í 30 dagar',
      cs: 'Utraceno za 30 dní',
      bg: 'Похарчено за 30 дни',
      hr: 'Potrošeno u 30 dana',
      sr: 'Потрошено у 30 дана',
      sl: 'Porabljeno v 30 dneh',
      mk: 'Потрошено за 30 дена',
      be: 'Выдаткавана за 30 дзён',
      bs: 'Potrošeno u 30 dana',
      hsb: 'Wudate za 30 dnjow',
    }),
    holdings: t({
      ru: 'Активы',
      en: 'Holdings',
      kk: 'Активтер',
      de: 'Bestände',
      fr: 'Actifs',
      es: 'Activos',
      pt: 'Ativos',
      tr: 'Varlıklar',
      uk: 'Активи',
      zh: '持仓',
      pl: 'Aktywa',
      it: 'Asset',
      sk: 'Aktíva',
      ja: '保有資産',
      ko: '보유 자산',
      hi: 'होल्डिंग्स',
      nl: 'Bezittingen',
      sv: 'Innehav',
      vi: 'Tài sản nắm giữ',
      id: 'Aset',
      da: 'Beholdninger',
      nb: 'Beholdninger',
      nn: 'Behaldningar',
      fi: 'Omistukset',
      is: 'Eignir',
      fo: 'Eignir',
      cs: 'Držená aktiva',
      bg: 'Наличности',
      hr: 'Posjedi',
      sr: 'Поседи',
      sl: 'Imetje',
      mk: 'Поседи',
      be: 'Актывы',
      bs: 'Posjedi',
      hsb: 'Wobsedźenja',
    }),
    sync: t({
      ru: 'Обновить',
      en: 'Sync',
      kk: 'Жаңарту',
      de: 'Aktualisieren',
      fr: 'Actualiser',
      es: 'Sincronizar',
      pt: 'Sincronizar',
      tr: 'Eşitle',
      uk: 'Оновити',
      zh: '同步',
      pl: 'Synchronizuj',
      it: 'Sincronizza',
      sk: 'Synchronizovať',
      ja: '同期',
      ko: '동기화',
      hi: 'सिंक करें',
      nl: 'Synchroniseren',
      sv: 'Synka',
      vi: 'Đồng bộ',
      id: 'Sinkronkan',
      da: 'Synkronisér',
      nb: 'Synkroniser',
      nn: 'Synkroniser',
      fi: 'Synkronoi',
      is: 'Samstilla',
      fo: 'Samstilla',
      cs: 'Synchronizovat',
      bg: 'Синхронизирай',
      hr: 'Sinkroniziraj',
      sr: 'Синхронизуј',
      sl: 'Sinhroniziraj',
      mk: 'Синхронизирај',
      be: 'Сінхранізаваць',
      bs: 'Sinhronizuj',
      hsb: 'Synchronizować',
    }),
    remove: t({
      ru: 'Отключить',
      en: 'Disconnect',
      kk: 'Ажырату',
      de: 'Trennen',
      fr: 'Déconnecter',
      es: 'Desconectar',
      pt: 'Desligar',
      tr: 'Bağlantıyı kes',
      uk: 'Відключити',
      zh: '断开连接',
      pl: 'Odłącz',
      it: 'Disconnetti',
      sk: 'Odpojiť',
      ja: '接続を解除',
      ko: '연결 해제',
      hi: 'हटाएँ',
      nl: 'Loskoppelen',
      sv: 'Koppla från',
      vi: 'Ngắt kết nối',
      id: 'Putuskan',
      da: 'Afbryd',
      nb: 'Koble fra',
      nn: 'Kople frå',
      fi: 'Katkaise yhteys',
      is: 'Aftengja',
      fo: 'Skilja frá',
      cs: 'Odpojit',
      bg: 'Изключи',
      hr: 'Odspoji',
      sr: 'Искључи',
      sl: 'Odklopi',
      mk: 'Исклучи',
      be: 'Адключыць',
      bs: 'Odspoji',
      hsb: 'Wotdźělić',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Болдырмау',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
      da: 'Annuller',
      nb: 'Avbryt',
      nn: 'Avbryt',
      fi: 'Peruuta',
      is: 'Hætta',
      fo: 'Avbrót',
      cs: 'Zrušit',
      bg: 'Отказ',
      hr: 'Odustani',
      sr: 'Откажи',
      sl: 'Prekliči',
      mk: 'Откажи',
      be: 'Скасаваць',
      bs: 'Otkaži',
      hsb: 'Přetorhnyć',
    }),
    transactions: t({
      ru: 'операций',
      en: 'transactions',
      kk: 'операция',
      de: 'Transaktionen',
      fr: 'transactions',
      es: 'transacciones',
      pt: 'transações',
      tr: 'işlem',
      uk: 'операцій',
      zh: '笔交易',
      pl: 'transakcji',
      it: 'transazioni',
      sk: 'transakcií',
      ja: '件の取引',
      ko: '건의 거래',
      hi: 'लेनदेन',
      nl: 'transacties',
      sv: 'transaktioner',
      vi: 'giao dịch',
      id: 'transaksi',
      da: 'posteringer',
      nb: 'transaksjoner',
      nn: 'transaksjonar',
      fi: 'tapahtumaa',
      is: 'færslur',
      fo: 'posteringar',
      cs: 'transakcí',
      bg: 'транзакции',
      hr: 'transakcija',
      sr: 'трансакција',
      sl: 'transakcij',
      mk: 'трансакции',
      be: 'транзакцый',
      bs: 'transakcija',
      hsb: 'transakcijow',
    }),
    neverSynced: t({
      ru: 'Ещё не синхронизирован',
      en: 'Not synced yet',
      kk: 'Әлі синхрондалмаған',
      de: 'Noch nicht synchronisiert',
      fr: 'Pas encore synchronisé',
      es: 'Aún no sincronizado',
      pt: 'Ainda não sincronizado',
      tr: 'Henüz eşitlenmedi',
      uk: 'Ще не синхронізовано',
      zh: '尚未同步',
      pl: 'Jeszcze nie zsynchronizowano',
      it: 'Non ancora sincronizzato',
      sk: 'Zatiaľ nesynchronizované',
      ja: '未同期',
      ko: '아직 동기화되지 않음',
      hi: 'अभी सिंक नहीं हुआ',
      nl: 'Nog niet gesynchroniseerd',
      sv: 'Inte synkad än',
      vi: 'Chưa đồng bộ',
      id: 'Belum disinkronkan',
      da: 'Ikke synkroniseret endnu',
      nb: 'Ikke synkronisert ennå',
      nn: 'Ikkje synkronisert enno',
      fi: 'Ei vielä synkronoitu',
      is: 'Ekki samstillt enn',
      fo: 'Ikki samstillað enn',
      cs: 'Zatím nesynchronizováno',
      bg: 'Още не е синхронизиран',
      hr: 'Još nije sinkronizirano',
      sr: 'Још није синхронизовано',
      sl: 'Še ni sinhronizirano',
      mk: 'Сè уште не е синхронизирано',
      be: 'Пакуль не сінхранізавана',
      bs: 'Još nije sinhronizovano',
      hsb: 'Hišće njesynchronizowane',
    }),
    asset: t({
      ru: 'Актив',
      en: 'Asset',
      kk: 'Актив',
      de: 'Asset',
      fr: 'Actif',
      es: 'Activo',
      pt: 'Ativo',
      tr: 'Varlık',
      uk: 'Актив',
      zh: '资产',
      pl: 'Aktywo',
      it: 'Asset',
      sk: 'Aktívum',
      ja: '資産',
      ko: '자산',
      hi: 'एसेट',
      nl: 'Asset',
      sv: 'Tillgång',
      vi: 'Tài sản',
      id: 'Aset',
      da: 'Aktiv',
      nb: 'Aktivum',
      nn: 'Aktivum',
      fi: 'Omaisuuserä',
      is: 'Eign',
      fo: 'Eign',
      cs: 'Aktivum',
      bg: 'Актив',
      hr: 'Sredstvo',
      sr: 'Средство',
      sl: 'Sredstvo',
      mk: 'Средство',
      be: 'Актыў',
      bs: 'Sredstvo',
      hsb: 'Aktiwum',
    }),
    balance: t({
      ru: 'Количество',
      en: 'Balance',
      kk: 'Саны',
      de: 'Bestand',
      fr: 'Solde',
      es: 'Saldo',
      pt: 'Saldo',
      tr: 'Bakiye',
      uk: 'Кількість',
      zh: '余额',
      pl: 'Saldo',
      it: 'Saldo',
      sk: 'Zostatok',
      ja: '残高',
      ko: '잔액',
      hi: 'बैलेंस',
      nl: 'Saldo',
      sv: 'Saldo',
      vi: 'Số dư',
      id: 'Saldo',
      da: 'Saldo',
      nb: 'Saldo',
      nn: 'Saldo',
      fi: 'Saldo',
      is: 'Staða',
      fo: 'Støða',
      cs: 'Zůstatek',
      bg: 'Салдо',
      hr: 'Stanje',
      sr: 'Стање',
      sl: 'Stanje',
      mk: 'Салдо',
      be: 'Баланс',
      bs: 'Stanje',
      hsb: 'Staw',
    }),
    price: t({
      ru: 'Цена',
      en: 'Price',
      kk: 'Бағасы',
      de: 'Preis',
      fr: 'Prix',
      es: 'Precio',
      pt: 'Preço',
      tr: 'Fiyat',
      uk: 'Ціна',
      zh: '价格',
      pl: 'Cena',
      it: 'Prezzo',
      sk: 'Cena',
      ja: '価格',
      ko: '가격',
      hi: 'मूल्य',
      nl: 'Prijs',
      sv: 'Pris',
      vi: 'Giá',
      id: 'Harga',
      da: 'Pris',
      nb: 'Pris',
      nn: 'Pris',
      fi: 'Hinta',
      is: 'Verð',
      fo: 'Prísur',
      cs: 'Cena',
      bg: 'Цена',
      hr: 'Cijena',
      sr: 'Цена',
      sl: 'Cena',
      mk: 'Цена',
      be: 'Цана',
      bs: 'Cijena',
      hsb: 'Płaćizna',
    }),
    worth: t({
      ru: 'Стоимость',
      en: 'Value',
      kk: 'Құны',
      de: 'Wert',
      fr: 'Valeur',
      es: 'Valor',
      pt: 'Valor',
      tr: 'Değer',
      uk: 'Вартість',
      zh: '价值',
      pl: 'Wartość',
      it: 'Valore',
      sk: 'Hodnota',
      ja: '評価額',
      ko: '가치',
      hi: 'मूल्यांकन',
      nl: 'Waarde',
      sv: 'Värde',
      vi: 'Giá trị',
      id: 'Nilai',
      da: 'Værdi',
      nb: 'Verdi',
      nn: 'Verdi',
      fi: 'Arvo',
      is: 'Verðmæti',
      fo: 'Virði',
      cs: 'Hodnota',
      bg: 'Стойност',
      hr: 'Vrijednost',
      sr: 'Вредност',
      sl: 'Vrednost',
      mk: 'Вредност',
      be: 'Вартасць',
      bs: 'Vrijednost',
      hsb: 'Hódnota',
    }),
    connectedWallets: t({
      ru: 'Подключённые кошельки',
      en: 'Connected wallets',
      kk: 'Қосылған әмияндар',
      de: 'Verbundene Wallets',
      fr: 'Portefeuilles connectés',
      es: 'Carteras conectadas',
      pt: 'Carteiras conectadas',
      tr: 'Bağlı cüzdanlar',
      uk: 'Підключені гаманці',
      zh: '已连接的钱包',
      pl: 'Połączone portfele',
      it: 'Portafogli collegati',
      sk: 'Pripojené peňaženky',
      ja: '接続済みウォレット',
      ko: '연결된 지갑',
      hi: 'जुड़े हुए वॉलेट',
      nl: 'Gekoppelde wallets',
      sv: 'Anslutna plånböcker',
      vi: 'Ví đã kết nối',
      id: 'Dompet terhubung',
      da: 'Tilsluttede wallets',
      nb: 'Tilkoblede lommebøker',
      nn: 'Tilkopla lommebøker',
      fi: 'Yhdistetyt lompakot',
      is: 'Tengd veski',
      fo: 'Knýttir pungar',
      cs: 'Připojené peněženky',
      bg: 'Свързани портфейли',
      hr: 'Povezani novčanici',
      sr: 'Повезани новчаници',
      sl: 'Povezane denarnice',
      mk: 'Поврзани паричници',
      be: 'Падключаныя гаманцы',
      bs: 'Povezani novčanici',
      hsb: 'Zwjazane móšnje',
    }),
    recentTransactions: t({
      ru: 'Последние транзакции',
      en: 'Recent transactions',
      kk: 'Соңғы транзакциялар',
      de: 'Letzte Transaktionen',
      fr: 'Transactions récentes',
      es: 'Transacciones recientes',
      pt: 'Transações recentes',
      tr: 'Son işlemler',
      uk: 'Останні транзакції',
      zh: '最近交易',
      pl: 'Ostatnie transakcje',
      it: 'Transazioni recenti',
      sk: 'Posledné transakcie',
      ja: '最近の取引',
      ko: '최근 거래',
      hi: 'हाल के लेन-देन',
      nl: 'Recente transacties',
      sv: 'Senaste transaktioner',
      vi: 'Giao dịch gần đây',
      id: 'Transaksi terbaru',
      da: 'Seneste posteringer',
      nb: 'Siste transaksjoner',
      nn: 'Siste transaksjonar',
      fi: 'Viimeisimmät tapahtumat',
      is: 'Nýjustu færslur',
      fo: 'Nýggjastu posteringar',
      cs: 'Poslední transakce',
      bg: 'Последни транзакции',
      hr: 'Nedavne transakcije',
      sr: 'Недавне трансакције',
      sl: 'Nedavne transakcije',
      mk: 'Неодамнешни трансакции',
      be: 'Нядаўнія транзакцыі',
      bs: 'Nedavne transakcije',
      hsb: 'Najnowše transakcije',
    }),
    noTransactions: t({
      ru: 'Транзакций пока нет — они появятся после синхронизации кошелька',
      en: 'No transactions yet — they appear after a wallet sync',
      kk: 'Әзірге транзакциялар жоқ — олар әмиян синхрондалғаннан кейін пайда болады',
      de: 'Noch keine Transaktionen — sie erscheinen nach einer Wallet-Synchronisierung',
      fr: 'Aucune transaction pour l’instant — elles apparaissent après une synchronisation',
      es: 'Aún no hay transacciones: aparecen tras sincronizar la cartera',
      pt: 'Ainda não há transações — elas aparecem após sincronizar a carteira',
      tr: 'Henüz işlem yok — cüzdan eşitlendikten sonra görünür',
      uk: 'Транзакцій ще немає — вони з’являться після синхронізації гаманця',
      zh: '暂无交易——同步钱包后显示',
      pl: 'Brak transakcji — pojawią się po synchronizacji portfela',
      it: 'Nessuna transazione — compaiono dopo la sincronizzazione del portafoglio',
      sk: 'Zatiaľ žiadne transakcie — zobrazia sa po synchronizácii peňaženky',
      ja: '取引はまだありません。ウォレットを同期すると表示されます',
      ko: '아직 거래가 없습니다. 지갑을 동기화하면 표시됩니다',
      hi: 'अभी कोई लेन-देन नहीं — वॉलेट सिंक होने के बाद दिखेंगे',
      nl: 'Nog geen transacties — ze verschijnen na een wallet-synchronisatie',
      sv: 'Inga transaktioner ännu — de visas efter en synkning',
      vi: 'Chưa có giao dịch — sẽ hiển thị sau khi đồng bộ ví',
      id: 'Belum ada transaksi — muncul setelah dompet disinkronkan',
      da: 'Ingen posteringer endnu — de kommer efter en wallet-synkronisering',
      nb: 'Ingen transaksjoner ennå — de kommer etter en synkronisering av lommeboken',
      nn: 'Ingen transaksjonar enno — dei kjem etter ei synkronisering av lommeboka',
      fi: 'Ei vielä tapahtumia — ne ilmestyvät lompakon synkronoinnin jälkeen',
      is: 'Engar færslur enn — þær birtast eftir samstillingu veskis',
      fo: 'Ongar posteringar enn — tær koma eftir eina samstilling av punginum',
      cs: 'Zatím žádné transakce — objeví se po synchronizaci peněženky',
      bg: 'Още няма транзакции — те се появяват след синхронизация на портфейла',
      hr: 'Još nema transakcija — pojavljuju se nakon sinkronizacije novčanika',
      sr: 'Још нема трансакција — појављују се после синхронизације новчаника',
      sl: 'Še ni transakcij — pojavijo se po sinhronizaciji denarnice',
      mk: 'Сè уште нема трансакции — се појавуваат по синхронизација на паричникот',
      be: 'Транзакцый пакуль няма — яны з’явяцца пасля сінхранізацыі гаманца',
      bs: 'Još nema transakcija — pojavljuju se nakon sinhronizacije novčanika',
      hsb: 'Hišće žane transakcije — jewja so po synchronizaciji móšnje',
    }),
    date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
      da: 'Dato',
      nb: 'Dato',
      nn: 'Dato',
      fi: 'Päivämäärä',
      is: 'Dagsetning',
      fo: 'Dato',
      cs: 'Datum',
      bg: 'Дата',
      hr: 'Datum',
      sr: 'Датум',
      sl: 'Datum',
      mk: 'Датум',
      be: 'Дата',
      bs: 'Datum',
      hsb: 'Datum',
    }),
    wallet: t({
      ru: 'Кошелёк',
      en: 'Wallet',
      kk: 'Әмиян',
      de: 'Wallet',
      fr: 'Portefeuille',
      es: 'Cartera',
      pt: 'Carteira',
      tr: 'Cüzdan',
      uk: 'Гаманець',
      zh: '钱包',
      pl: 'Portfel',
      it: 'Portafoglio',
      sk: 'Peňaženka',
      ja: 'ウォレット',
      ko: '지갑',
      hi: 'वॉलेट',
      nl: 'Wallet',
      sv: 'Plånbok',
      vi: 'Ví',
      id: 'Dompet',
      da: 'Wallet',
      nb: 'Lommebok',
      nn: 'Lommebok',
      fi: 'Lompakko',
      is: 'Veski',
      fo: 'Pungur',
      cs: 'Peněženka',
      bg: 'Портфейл',
      hr: 'Novčanik',
      sr: 'Новчаник',
      sl: 'Denarnica',
      mk: 'Паричник',
      be: 'Гаманец',
      bs: 'Novčanik',
      hsb: 'Móšnja',
    }),
    counterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı taraf',
      uk: 'Контрагент',
      zh: '对方',
      pl: 'Kontrahent',
      it: 'Controparte',
      sk: 'Protistrana',
      ja: '取引相手',
      ko: '거래 상대',
      hi: 'प्रतिपक्ष',
      nl: 'Tegenpartij',
      sv: 'Motpart',
      vi: 'Đối tác',
      id: 'Pihak lawan',
      da: 'Modpart',
      nb: 'Motpart',
      nn: 'Motpart',
      fi: 'Vastapuoli',
      is: 'Gagnaðili',
      fo: 'Mótpartur',
      cs: 'Protistrana',
      bg: 'Контрагент',
      hr: 'Druga strana',
      sr: 'Друга страна',
      sl: 'Nasprotna stranka',
      mk: 'Другата страна',
      be: 'Кантрагент',
      bs: 'Druga strana',
      hsb: 'Přećiwna strona',
    }),
    amount: t({
      ru: 'Сумма',
      en: 'Amount',
      kk: 'Сомасы',
      de: 'Betrag',
      fr: 'Montant',
      es: 'Importe',
      pt: 'Quantia',
      tr: 'Tutar',
      uk: 'Сума',
      zh: '数量',
      pl: 'Kwota',
      it: 'Importo',
      sk: 'Suma',
      ja: '数量',
      ko: '수량',
      hi: 'राशि',
      nl: 'Bedrag',
      sv: 'Belopp',
      vi: 'Số lượng',
      id: 'Jumlah',
      da: 'Beløb',
      nb: 'Beløp',
      nn: 'Beløp',
      fi: 'Summa',
      is: 'Fjárhæð',
      fo: 'Sum',
      cs: 'Částka',
      bg: 'Сума',
      hr: 'Iznos',
      sr: 'Износ',
      sl: 'Znesek',
      mk: 'Сума',
      be: 'Сума',
      bs: 'Iznos',
      hsb: 'Suma',
    }),
    received: t({
      ru: 'Получено',
      en: 'Received',
      kk: 'Алынды',
      de: 'Empfangen',
      fr: 'Reçu',
      es: 'Recibido',
      pt: 'Recebido',
      tr: 'Alındı',
      uk: 'Отримано',
      zh: '收到',
      pl: 'Otrzymano',
      it: 'Ricevuto',
      sk: 'Prijaté',
      ja: '受取',
      ko: '받음',
      hi: 'प्राप्त',
      nl: 'Ontvangen',
      sv: 'Mottaget',
      vi: 'Đã nhận',
      id: 'Diterima',
      da: 'Modtaget',
      nb: 'Mottatt',
      nn: 'Motteke',
      fi: 'Vastaanotettu',
      is: 'Móttekið',
      fo: 'Móttikið',
      cs: 'Přijato',
      bg: 'Получено',
      hr: 'Primljeno',
      sr: 'Примљено',
      sl: 'Prejeto',
      mk: 'Примено',
      be: 'Атрымана',
      bs: 'Primljeno',
      hsb: 'Dóstate',
    }),
    sent: t({
      ru: 'Отправлено',
      en: 'Sent',
      kk: 'Жіберілді',
      de: 'Gesendet',
      fr: 'Envoyé',
      es: 'Enviado',
      pt: 'Enviado',
      tr: 'Gönderildi',
      uk: 'Надіслано',
      zh: '发送',
      pl: 'Wysłano',
      it: 'Inviato',
      sk: 'Odoslané',
      ja: '送金',
      ko: '보냄',
      hi: 'भेजा',
      nl: 'Verzonden',
      sv: 'Skickat',
      vi: 'Đã gửi',
      id: 'Dikirim',
      da: 'Sendt',
      nb: 'Sendt',
      nn: 'Sendt',
      fi: 'Lähetetty',
      is: 'Sent',
      fo: 'Sent',
      cs: 'Odesláno',
      bg: 'Изпратено',
      hr: 'Poslano',
      sr: 'Послато',
      sl: 'Poslano',
      mk: 'Испратено',
      be: 'Адпраўлена',
      bs: 'Poslano',
      hsb: 'Pósłane',
    }),
    sinceYesterday: t({
      ru: 'со вчера',
      en: 'since yesterday',
      kk: 'кешеден бері',
      de: 'seit gestern',
      fr: 'depuis hier',
      es: 'desde ayer',
      pt: 'desde ontem',
      tr: 'dünden beri',
      uk: 'з учора',
      zh: '较昨日',
      pl: 'od wczoraj',
      it: 'da ieri',
      sk: 'od včera',
      ja: '昨日比',
      ko: '어제 대비',
      hi: 'कल से',
      nl: 'sinds gisteren',
      sv: 'sedan igår',
      vi: 'so với hôm qua',
      id: 'sejak kemarin',
      da: 'siden i går',
      nb: 'siden i går',
      nn: 'sidan i går',
      fi: 'eilisestä',
      is: 'síðan í gær',
      fo: 'síðan í gjár',
      cs: 'od včerejška',
      bg: 'от вчера',
      hr: 'od jučer',
      sr: 'од јуче',
      sl: 'od včeraj',
      mk: 'од вчера',
      be: 'з учарашняга дня',
      bs: 'od juče',
      hsb: 'wot wčerawšeho',
    }),
  },
} satisfies Dictionary;

export default content;
