import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementFilterControls',
  content: {
    category: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '类别',
      ar: 'الفئة',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategória',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
      da: 'Kategori',
      nb: 'Kategori',
      nn: 'Kategori',
      fi: 'Kategoria',
      is: 'Kategoría',
      fo: 'Bólkur',
      cs: 'Kategorie',
      bg: 'Категория',
      hr: 'Kategorija',
      sr: 'Категорија',
      sl: 'Kategorija',
      mk: 'Категорија',
      be: 'Катэгорыя',
      bs: 'Kategorija',
      hsb: 'Kategorija',
    }),
    startDate: t({
      ru: 'Дата начала',
      en: 'Start date',
      kk: 'Басталу күні',
      de: 'Startdatum',
      fr: 'Date de début',
      es: 'Fecha de inicio',
      pt: 'Data de início',
      tr: 'Başlangıç tarihi',
      uk: 'Дата початку',
      zh: '开始日期',
      ar: 'تاريخ البدء',
      pl: 'Data początkowa',
      it: 'Data di inizio',
      sk: 'Dátum začiatku',
      ja: '開始日',
      ko: '시작일',
      hi: 'आरंभ तिथि',
      nl: 'Begindatum',
      sv: 'Startdatum',
      vi: 'Ngày bắt đầu',
      id: 'Tanggal mulai',
      da: 'Startdato',
      nb: 'Startdato',
      nn: 'Startdato',
      fi: 'Alkamispäivä',
      is: 'Upphafsdagsetning',
      fo: 'Byrjanardagur',
      cs: 'Datum začátku',
      bg: 'Начална дата',
      hr: 'Datum početka',
      sr: 'Датум почетка',
      sl: 'Datum začetka',
      mk: 'Датум на почеток',
      be: 'Дата пачатку',
      bs: 'Datum početka',
      hsb: 'Datum započatka',
    }),
    endDate: t({
      ru: 'Дата окончания',
      en: 'End date',
      kk: 'Аяқталу күні',
      de: 'Enddatum',
      fr: 'Date de fin',
      es: 'Fecha de fin',
      pt: 'Data de término',
      tr: 'Bitiş tarihi',
      uk: 'Дата завершення',
      zh: '结束日期',
      ar: 'تاريخ الانتهاء',
      pl: 'Data końcowa',
      it: 'Data di fine',
      sk: 'Dátum konca',
      ja: '終了日',
      ko: '종료일',
      hi: 'अंतिम तिथि',
      nl: 'Einddatum',
      sv: 'Slutdatum',
      vi: 'Ngày kết thúc',
      id: 'Tanggal akhir',
      da: 'Slutdato',
      nb: 'Sluttdato',
      nn: 'Sluttdato',
      fi: 'Päättymispäivä',
      is: 'Lokadagsetning',
      fo: 'Endadagur',
      cs: 'Datum konce',
      bg: 'Крайна дата',
      hr: 'Datum završetka',
      sr: 'Датум завршетка',
      sl: 'Datum konca',
      mk: 'Датум на завршување',
      be: 'Дата канца',
      bs: 'Datum završetka',
      hsb: 'Datum kónca',
    }),
    min: t({
      ru: 'Мин.',
      en: 'Min',
      kk: 'Мин.',
      de: 'Min.',
      fr: 'Min.',
      es: 'Mín.',
      pt: 'Mín.',
      tr: 'Min.',
      uk: 'Мін.',
      zh: '最小',
      ar: 'الحد الأدنى',
      pl: 'Min.',
      it: 'Min.',
      sk: 'Min.',
      ja: '最小',
      ko: '최소',
      hi: 'न्यूनतम',
      nl: 'Min.',
      sv: 'Min.',
      vi: 'Tối thiểu',
      id: 'Min.',
      da: 'Min.',
      nb: 'Min.',
      nn: 'Min.',
      fi: 'Pienin',
      is: 'Lágmark',
      fo: 'Minst',
      cs: 'Min.',
      bg: 'Мин.',
      hr: 'Min.',
      sr: 'Мин.',
      sl: 'Min.',
      mk: 'Мин.',
      be: 'Мін.',
      bs: 'Min.',
      hsb: 'Min.',
    }),
    max: t({
      ru: 'Макс.',
      en: 'Max',
      kk: 'Макс.',
      de: 'Max.',
      fr: 'Max.',
      es: 'Máx.',
      pt: 'Máx.',
      tr: 'Maks.',
      uk: 'Макс.',
      zh: '最大',
      ar: 'الحد الأقصى',
      pl: 'Maks.',
      it: 'Max.',
      sk: 'Max.',
      ja: '最大',
      ko: '최대',
      hi: 'अधिकतम',
      nl: 'Max.',
      sv: 'Max.',
      vi: 'Tối đa',
      id: 'Maks.',
      da: 'Maks.',
      nb: 'Maks.',
      nn: 'Maks.',
      fi: 'Suurin',
      is: 'Hámark',
      fo: 'Mest',
      cs: 'Max.',
      bg: 'Макс.',
      hr: 'Maks.',
      sr: 'Макс.',
      sl: 'Maks.',
      mk: 'Макс.',
      be: 'Макс.',
      bs: 'Maks.',
      hsb: 'Maks.',
    }),
  },
} satisfies Dictionary;

export default content;
