import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementStageErrors',
  content: {
    noExpenseAmount: t({
      ru: 'Нет суммы расхода для создания платежа',
      en: 'No expense amount available to create payable',
      kk: 'Төлем жасау үшін шығыс сомасы жоқ',
      de: 'Kein Ausgabenbetrag zum Erstellen einer Verbindlichkeit vorhanden',
      fr: 'Aucun montant de dépense disponible pour créer un paiement à effectuer',
      es: 'No hay importe de gasto para crear el pago',
      pt: 'Nenhum valor de despesa disponível para criar a conta a pagar',
      tr: 'Ödeme oluşturmak için gider tutarı yok',
      uk: 'Немає суми витрати для створення платежу',
      zh: '没有可用于创建应付款的支出金额',
      ar: 'لا يوجد مبلغ مصروف لإنشاء مستحق الدفع',
      pl: 'Brak kwoty wydatku do utworzenia zobowiązania',
      it: 'Nessun importo di spesa disponibile per creare il pagamento',
      sk: 'Nie je k dispozícii suma výdavku na vytvorenie záväzku',
      ja: '支払を作成するための経費金額がありません',
      ko: '지급 항목을 만들 지출 금액이 없습니다',
      hi: 'देय बनाने के लिए कोई खर्च राशि उपलब्ध नहीं है',
      nl: 'Geen uitgavenbedrag beschikbaar om een betaling aan te maken',
      sv: 'Inget utgiftsbelopp finns för att skapa en betalning',
      vi: 'Không có số tiền chi để tạo khoản phải trả',
      id: 'Tidak ada jumlah pengeluaran untuk membuat utang',
      da: 'Der er intet udgiftsbeløb til at oprette en kreditorpost',
      nb: 'Det finnes ingen utgiftsbeløp for å opprette leverandørgjeld',
      nn: 'Det finst ingen utgiftsbeløp for å opprette leverandørgjeld',
      fi: 'Ei menosummaa, josta luoda ostovelka',
      is: 'Engin útgjaldafjárhæð til að búa til skuld',
      fo: 'Ongin útgjaldssumma at stovna skuld við',
      cs: 'Není k dispozici částka výdaje pro vytvoření závazku',
      bg: 'Няма сума на разход, с която да се създаде задължение',
      hr: 'Nema iznosa troška za stvaranje obveze',
      sr: 'Нема износа трошка за стварање обавезе',
      sl: 'Ni zneska stroška za ustvarjanje obveznosti',
      mk: 'Нема сума на трошок за создавање обврска',
      be: 'Няма сумы выдатку, каб стварыць плацёж',
      bs: 'Nema iznosa troška za stvaranje obaveze',
      hsb: 'Žana suma wudawka, zo by so dołh załožił',
    }),
    createPayableFailed: t({
      ru: 'Не удалось создать платёж',
      en: 'Failed to create payable',
      kk: 'Төлемді жасау мүмкін болмады',
      de: 'Verbindlichkeit konnte nicht erstellt werden',
      fr: 'Impossible de créer le paiement à effectuer',
      es: 'No se pudo crear el pago',
      pt: 'Falha ao criar a conta a pagar',
      tr: 'Ödeme oluşturulamadı',
      uk: 'Не вдалося створити платіж',
      zh: '创建应付款失败',
      ar: 'تعذّر إنشاء مستحق الدفع',
      pl: 'Nie udało się utworzyć zobowiązania',
      it: 'Impossibile creare il pagamento',
      sk: 'Záväzok sa nepodarilo vytvoriť',
      ja: '支払を作成できませんでした',
      ko: '지급 항목을 만들지 못했습니다',
      hi: 'देय बनाने में विफल',
      nl: 'Betaling aanmaken mislukt',
      sv: 'Det gick inte att skapa betalningen',
      vi: 'Không thể tạo khoản phải trả',
      id: 'Gagal membuat utang',
      da: 'Kreditorposten kunne ikke oprettes',
      nb: 'Kunne ikke opprette leverandørgjeld',
      nn: 'Kunne ikkje opprette leverandørgjeld',
      fi: 'Ostovelan luonti ei onnistunut',
      is: 'Ekki var unnt að búa til skuldina',
      fo: 'Fekk ikki stovnað skuldina',
      cs: 'Závazek se nepodařilo vytvořit',
      bg: 'Задължението не можа да бъде създадено',
      hr: 'Obvezu nije bilo moguće stvoriti',
      sr: 'Обавезу није могуће направити',
      sl: 'Obveznosti ni bilo mogoče ustvariti',
      mk: 'Обврската не можеше да се создаде',
      be: 'Не ўдалося стварыць плацёж',
      bs: 'Obavezu nije moguće stvoriti',
      hsb: 'Dołh njeda so załožić',
    }),
    updateStageFailed: t({
      ru: 'Не удалось обновить этап',
      en: 'Failed to update stage',
      kk: 'Кезеңді жаңарту мүмкін болмады',
      de: 'Phase konnte nicht aktualisiert werden',
      fr: "Impossible de mettre à jour l'étape",
      es: 'No se pudo actualizar la etapa',
      pt: 'Falha ao atualizar a etapa',
      tr: 'Aşama güncellenemedi',
      uk: 'Не вдалося оновити етап',
      zh: '更新阶段失败',
      ar: 'تعذّر تحديث المرحلة',
      pl: 'Nie udało się zaktualizować etapu',
      it: 'Impossibile aggiornare la fase',
      sk: 'Fázu sa nepodarilo aktualizovať',
      ja: 'ステージを更新できませんでした',
      ko: '단계를 업데이트하지 못했습니다',
      hi: 'चरण अपडेट करने में विफल',
      nl: 'Fase bijwerken mislukt',
      sv: 'Det gick inte att uppdatera steget',
      vi: 'Không thể cập nhật giai đoạn',
      id: 'Gagal memperbarui tahap',
      da: 'Stadiet kunne ikke opdateres',
      nb: 'Kunne ikke oppdatere trinnet',
      nn: 'Kunne ikkje oppdatere trinnet',
      fi: 'Vaiheen päivitys ei onnistunut',
      is: 'Ekki var unnt að uppfæra þrepið',
      fo: 'Fekk ikki dagført stigið',
      cs: 'Fázi se nepodařilo aktualizovat',
      bg: 'Етапът не можа да бъде обновен',
      hr: 'Fazu nije bilo moguće ažurirati',
      sr: 'Фазу није могуће ажурирати',
      sl: 'Faze ni bilo mogoče posodobiti',
      mk: 'Фазата не можеше да се ажурира',
      be: 'Не ўдалося абнавіць этап',
      bs: 'Fazu nije moguće ažurirati',
      hsb: 'Faza njeda so aktualizować',
    }),
  },
} satisfies Dictionary;

export default content;
