import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionsSummaryBar',
  content: {
    uploadedAt: t({
      ru: 'Загружено',
      en: 'Uploaded',
      kk: 'Жүктелген',
      de: 'Hochgeladen',
      fr: 'Téléchargé',
      es: 'Subido',
      pt: 'Enviado',
      tr: 'Yüklendi',
      uk: 'Завантажено',
      zh: '已上传',
      pl: 'Przesłano',
      it: 'Caricato',
      sk: 'Nahrané',
      ja: 'アップロード済み',
      ko: '업로드됨',
      hi: 'अपलोड किया गया',
      nl: 'Geüpload',
      sv: 'Uppladdad',
      vi: 'Đã tải lên',
      id: 'Diunggah',
      da: 'Uploadet',
      nb: 'Lastet opp',
      nn: 'Lasta opp',
      fi: 'Ladattu',
      is: 'Innsend',
      fo: 'Innsend',
      cs: 'Nahráno',
      bg: 'Качен',
      hr: 'Učitano',
      sr: 'Учитано',
      sl: 'Naloženo',
      mk: 'Поставено',
      be: 'Загружана',
      bs: 'Učitano',
      hsb: 'Nahraće',
    }),
    parsed: t({
      ru: 'Распознано',
      en: 'Parsed',
      kk: 'Танылды',
      de: 'Verarbeitet',
      fr: 'Analysé',
      es: 'Procesado',
      pt: 'Processado',
      tr: 'İşlendi',
      uk: 'Розпізнано',
      zh: '已解析',
      pl: 'Przetworzone',
      it: 'Analizzato',
      sk: 'Spracované',
      ja: '解析済み',
      ko: '파싱됨',
      hi: 'पार्स किया गया',
      nl: 'Verwerkt',
      sv: 'Tolkad',
      vi: 'Đã phân tích',
      id: 'Diuraikan',
      da: 'Behandlet',
      nb: 'Tolket',
      nn: 'Tolka',
      fi: 'Luettu',
      is: 'Úrlesin',
      fo: 'Útlisin',
      cs: 'Zpracováno',
      bg: 'Разчетен',
      hr: 'Obrađeno',
      sr: 'Обрађено',
      sl: 'Obdelano',
      mk: 'Обработено',
      be: 'Распазнана',
      bs: 'Obrađeno',
      hsb: 'Rozeznate',
    }),
    warnings: t({
      ru: 'Предупреждения',
      en: 'Warnings',
      kk: 'Ескертулер',
      de: 'Warnungen',
      fr: 'Avertissements',
      es: 'Advertencias',
      pt: 'Avisos',
      tr: 'Uyarılar',
      uk: 'Попередження',
      zh: '警告',
      pl: 'Ostrzeżenia',
      it: 'Avvisi',
      sk: 'Upozornenia',
      ja: '警告',
      ko: '경고',
      hi: 'चेतावनियां',
      nl: 'Waarschuwingen',
      sv: 'Varningar',
      vi: 'Cảnh báo',
      id: 'Peringatan',
      da: 'Advarsler',
      nb: 'Advarsler',
      nn: 'Åtvaringar',
      fi: 'Varoitukset',
      is: 'Viðvaranir',
      fo: 'Ávaringar',
      cs: 'Varování',
      bg: 'Предупреждения',
      hr: 'Upozorenja',
      sr: 'Упозорења',
      sl: 'Opozorila',
      mk: 'Предупредувања',
      be: 'Папярэджанні',
      bs: 'Upozorenja',
      hsb: 'Warnowanja',
    }),
    errors: t({
      ru: 'Ошибки',
      en: 'Errors',
      kk: 'Қателер',
      de: 'Fehler',
      fr: 'Erreurs',
      es: 'Errores',
      pt: 'Erros',
      tr: 'Hatalar',
      uk: 'Помилки',
      zh: '错误',
      pl: 'Błędy',
      it: 'Errori',
      sk: 'Chyby',
      ja: 'エラー',
      ko: '오류',
      hi: 'त्रुटियां',
      nl: 'Fouten',
      sv: 'Fel',
      vi: 'Lỗi',
      id: 'Kesalahan',
      da: 'Fejl',
      nb: 'Feil',
      nn: 'Feil',
      fi: 'Virheet',
      is: 'Villur',
      fo: 'Feilir',
      cs: 'Chyby',
      bg: 'Грешки',
      hr: 'Greške',
      sr: 'Грешке',
      sl: 'Napake',
      mk: 'Грешки',
      be: 'Памылкі',
      bs: 'Greške',
      hsb: 'Zmylki',
    }),
    uncategorized: t({
      ru: 'Без категории',
      en: 'Uncategorized',
      kk: 'Санатсыз',
      de: 'Unkategorisiert',
      fr: 'Non catégorisé',
      es: 'Sin categorizar',
      pt: 'Sem categoria',
      tr: 'Kategorisiz',
      uk: 'Без категорії',
      zh: '未分类',
      pl: 'Bez kategorii',
      it: 'Non categorizzato',
      sk: 'Bez kategórie',
      ja: '未分類',
      ko: '미분류',
      hi: 'बिना श्रेणी के',
      nl: 'Zonder categorie',
      sv: 'Okategoriserad',
      vi: 'Chưa phân loại',
      id: 'Tanpa kategori',
      da: 'Ukategoriseret',
      nb: 'Ukategorisert',
      nn: 'Ukategorisert',
      fi: 'Luokittelematon',
      is: 'Óflokkað',
      fo: 'Óbólkað',
      cs: 'Nezařazeno',
      bg: 'Некатегоризирано',
      hr: 'Nekategorizirano',
      sr: 'Некатегоризовано',
      sl: 'Nerazvrščeno',
      mk: 'Некатегоризирано',
      be: 'Некатэгарызавана',
      bs: 'Nekategorizirano',
      hsb: 'Nikategorizowane',
    }),
    debitTotal: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Débito',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      pl: 'Debet',
      it: 'Addebito',
      sk: 'Debet',
      ja: '借方',
      ko: '차변',
      hi: 'डेबिट',
      nl: 'Debet',
      sv: 'Debet',
      vi: 'Ghi nợ',
      id: 'Debit',
      da: 'Debet',
      nb: 'Debet',
      nn: 'Debet',
      fi: 'Debet',
      is: 'Debet',
      fo: 'Debet',
      cs: 'Debet',
      bg: 'Дебит',
      hr: 'Duguje',
      sr: 'Дугује',
      sl: 'Debet',
      mk: 'Должи',
      be: 'Дэбет',
      bs: 'Duguje',
      hsb: 'Debet',
    }),
    creditTotal: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Crédito',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      pl: 'Kredyt',
      it: 'Credito',
      sk: 'Kredit',
      ja: '貸方',
      ko: '대변',
      hi: 'क्रेडिट',
      nl: 'Krediet',
      sv: 'Kredit',
      vi: 'Ghi có',
      id: 'Kredit',
      da: 'Kredit',
      nb: 'Kredit',
      nn: 'Kredit',
      fi: 'Kredit',
      is: 'Kredit',
      fo: 'Kredit',
      cs: 'Kredit',
      bg: 'Кредит',
      hr: 'Potražuje',
      sr: 'Потражује',
      sl: 'Kredit',
      mk: 'Побарува',
      be: 'Крэдыт',
      bs: 'Potražuje',
      hsb: 'Kredit',
    }),
    fixIssues: t({
      ru: 'Исправить проблемы',
      en: 'Fix Issues',
      kk: 'Мәселелерді шешу',
      de: 'Probleme beheben',
      fr: 'Corriger les problèmes',
      es: 'Corregir problemas',
      pt: 'Corrigir problemas',
      tr: 'Sorunları Düzelt',
      uk: 'Виправити проблеми',
      zh: '修复问题',
      pl: 'Napraw problemy',
      it: 'Risolvi i problemi',
      sk: 'Opraviť problémy',
      ja: '問題を修正',
      ko: '문제 해결',
      hi: 'समस्याएं ठीक करें',
      nl: 'Problemen oplossen',
      sv: 'Åtgärda problem',
      vi: 'Sửa vấn đề',
      id: 'Perbaiki masalah',
      da: 'Ret problemer',
      nb: 'Rett problemer',
      nn: 'Rett problem',
      fi: 'Korjaa ongelmat',
      is: 'Leysa vandamál',
      fo: 'Rætta trupulleikar',
      cs: 'Vyřešit problémy',
      bg: 'Отстраняване на проблемите',
      hr: 'Riješi probleme',
      sr: 'Реши проблеме',
      sl: 'Odpravi težave',
      mk: 'Реши ги проблемите',
      be: 'Выправіць праблемы',
      bs: 'Riješi probleme',
      hsb: 'Problemy rozrisać',
    }),
    showErrors: t({
      ru: 'Показать ошибки',
      en: 'Show Errors',
      kk: 'Қателерді көрсету',
      de: 'Fehler anzeigen',
      fr: 'Afficher les erreurs',
      es: 'Mostrar errores',
      pt: 'Mostrar erros',
      tr: 'Hataları Göster',
      uk: 'Показати помилки',
      zh: '显示错误',
      pl: 'Pokaż błędy',
      it: 'Mostra errori',
      sk: 'Zobraziť chyby',
      ja: 'エラーを表示',
      ko: '오류 표시',
      hi: 'त्रुटियां दिखाएं',
      nl: 'Fouten weergeven',
      sv: 'Visa fel',
      vi: 'Hiển thị lỗi',
      id: 'Tampilkan kesalahan',
      da: 'Vis fejl',
      nb: 'Vis feil',
      nn: 'Vis feil',
      fi: 'Näytä virheet',
      is: 'Sýna villur',
      fo: 'Vís feilir',
      cs: 'Zobrazit chyby',
      bg: 'Показване на грешките',
      hr: 'Prikaži pogreške',
      sr: 'Прикажи грешке',
      sl: 'Prikaži napake',
      mk: 'Прикажи ги грешките',
      be: 'Паказаць памылкі',
      bs: 'Prikaži greške',
      hsb: 'Zmylki pokazać',
    }),
    export: t({
      ru: 'Экспорт',
      en: 'Export',
      kk: 'Экспорт',
      de: 'Exportieren',
      fr: 'Exporter',
      es: 'Exportar',
      pt: 'Exportar',
      tr: 'Dışa Aktar',
      uk: 'Експорт',
      zh: '导出',
      pl: 'Eksportuj',
      it: 'Esporta',
      sk: 'Exportovať',
      ja: 'エクスポート',
      ko: '내보내기',
      hi: 'निर्यात',
      nl: 'Exporteren',
      sv: 'Exportera',
      vi: 'Xuất',
      id: 'Ekspor',
      da: 'Eksportér',
      nb: 'Eksporter',
      nn: 'Eksporter',
      fi: 'Vie',
      is: 'Flytja út',
      fo: 'Flyt út',
      cs: 'Exportovat',
      bg: 'Експортирай',
      hr: 'Izvezi',
      sr: 'Извези',
      sl: 'Izvozi',
      mk: 'Извези',
      be: 'Экспартаваць',
      bs: 'Izvezi',
      hsb: 'Eksportować',
    }),
    download: t({
      ru: 'Скачать',
      en: 'Download',
      kk: 'Жүктеу',
      de: 'Herunterladen',
      fr: 'Télécharger',
      es: 'Descargar',
      pt: 'Baixar',
      tr: 'İndir',
      uk: 'Завантажити',
      zh: '下载',
      pl: 'Pobierz',
      it: 'Scarica',
      sk: 'Stiahnuť',
      ja: 'ダウンロード',
      ko: '다운로드',
      hi: 'डाउनलोड करें',
      nl: 'Downloaden',
      sv: 'Ladda ned',
      vi: 'Tải xuống',
      id: 'Unduh',
      da: 'Download',
      nb: 'Last ned',
      nn: 'Last ned',
      fi: 'Lataa',
      is: 'Hlaða niður',
      fo: 'Tak niður',
      cs: 'Stáhnout',
      bg: 'Изтегли',
      hr: 'Preuzmi',
      sr: 'Преузми',
      sl: 'Prenesi',
      mk: 'Симни',
      be: 'Спампаваць',
      bs: 'Preuzmi',
      hsb: 'Sćahnyć',
    }),
    share: t({
      ru: 'Поделиться',
      en: 'Share',
      kk: 'Бөлісу',
      de: 'Teilen',
      fr: 'Partager',
      es: 'Compartir',
      pt: 'Compartilhar',
      tr: 'Paylaş',
      uk: 'Поділитися',
      zh: '分享',
      pl: 'Udostępnij',
      it: 'Condividi',
      sk: 'Zdieľať',
      ja: '共有',
      ko: '공유',
      hi: 'साझा करें',
      nl: 'Delen',
      sv: 'Dela',
      vi: 'Chia sẻ',
      id: 'Bagikan',
      da: 'Del',
      nb: 'Del',
      nn: 'Del',
      fi: 'Jaa',
      is: 'Deila',
      fo: 'Deil',
      cs: 'Sdílet',
      bg: 'Споделяне',
      hr: 'Podijeli',
      sr: 'Подели',
      sl: 'Deli',
      mk: 'Сподели',
      be: 'Падзяліцца',
      bs: 'Podijeli',
      hsb: 'Dźělić',
    }),
  },
} satisfies Dictionary;

export default content;
