import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionsTable',
  content: {
    searchPlaceholder: t({
      ru: 'Поиск по контрагенту, назначению, БИН или номеру  документа...',
      en: 'Search by counterparty, purpose, BIN or document number...',
      kk: 'Контрагент, мақсат, БСН немесе құжат нөмірі бойынша іздеу...',
      de: 'Nach Gegenpartei, Zweck, BIN oder Dokumentnummer suchen...',
      fr: 'Rechercher par contrepartie, objet, BIN ou numéro de document...',
      es: 'Buscar por contraparte, propósito, BIN o número de documento...',
      pt: 'Pesquisar por contraparte, finalidade, BIN ou número do documento...',
      tr: 'Karşı taraf, amaç, BIN veya belge numarasına göre ara...',
      uk: 'Пошук за контрагентом, призначенням, БІН або номером документа...',
      zh: '按交易对手、用途、BIN或文件编号搜索...',
      ar: 'البحث بالطرف المقابل أو الغرض أو BIN أو رقم الوثيقة...',
      pl: 'Szukaj po kontrahencie, celu, BIN lub numerze dokumentu...',
      it: 'Cerca per controparte, scopo, BIN o numero documento...',
      sk: 'Szukaj po kontrahencie, celu, BIN lub numerze dokumentu...',
      ja: '取引先、目的、BINまたは書類番号で検索...',
      ko: '거래처, 목적, BIN 또는 문서 번호로 검색...',
      hi: 'प्रतिपक्ष, उद्देश्य, BIN या दस्तावेज़ संख्या से खोजें...',
      nl: 'Zoeken op tegenpartij, doel, BIN of documentnummer...',
      sv: 'Sök på motpart, syfte, BIN eller dokumentnummer...',
      vi: 'Tìm kiếm theo đối tác, mục đích, BIN hoặc số tài liệu...',
      id: 'Cari berdasarkan pihak lawan, tujuan, BIN atau nomor dokumen...',
    }),
    filters: t({
      ru: 'Фильтры',
      en: 'Filters',
      kk: 'Сүзгілер',
      de: 'Filter',
      fr: 'Filtres',
      es: 'Filtros',
      pt: 'Filtros',
      tr: 'Filtreler',
      uk: 'Фільтри',
      zh: '筛选',
      ar: 'المرشحات',
      pl: 'Filtry',
      it: 'Filtri',
      sk: 'Filtry',
      ja: 'フィルター',
      ko: '필터',
      hi: 'फ़िल्टर',
      nl: 'Filters',
      sv: 'Filter',
      vi: 'Bộ lọc',
      id: 'Filter',
    }),
    statusFilter: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Estado',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Stan',
      it: 'Stato',
      sk: 'Stav',
      ja: 'ステータス',
      ko: '상태',
      hi: 'स्थिति',
      nl: 'Status',
      sv: 'Status',
      vi: 'Trạng thái',
      id: 'Status',
    }),
    statusAll: t({
      ru: 'Все',
      en: 'All',
      kk: 'Барлығы',
      de: 'Alle',
      fr: 'Tous',
      es: 'Todos',
      pt: 'Todos',
      tr: 'Tümü',
      uk: 'Всі',
      zh: '全部',
      ar: 'الكل',
      pl: 'Wszystkie',
      it: 'Tutti',
      sk: 'Wszystkie',
      ja: 'すべて',
      ko: '전체',
      hi: 'सभी',
      nl: 'Alle',
      sv: 'Alla',
      vi: 'Tất cả',
      id: 'Semua',
    }),
    statusWarnings: t({
      ru: 'С предупреждениями',
      en: 'With Warnings',
      kk: 'Ескертулермен',
      de: 'Mit Warnungen',
      fr: 'Avec avertissements',
      es: 'Con advertencias',
      pt: 'Com avisos',
      tr: 'Uyarılı',
      uk: 'З попередженнями',
      zh: '有警告',
      ar: 'بتحذيرات',
      pl: 'Z ostrzeżeniami',
      it: 'Con avvisi',
      sk: 'Z ostrzeżeniami',
      ja: '警告あり',
      ko: '경고 있음',
      hi: 'चेतावनियों के साथ',
      nl: 'Met waarschuwingen',
      sv: 'Med varningar',
      vi: 'Có cảnh báo',
      id: 'Dengan peringatan',
    }),
    statusErrors: t({
      ru: 'С ошибками',
      en: 'With Errors',
      kk: 'Қателермен',
      de: 'Mit Fehlern',
      fr: 'Avec erreurs',
      es: 'Con errores',
      pt: 'Com erros',
      tr: 'Hatalı',
      uk: 'З помилками',
      zh: '有错误',
      ar: 'بأخطاء',
      pl: 'Z błędami',
      it: 'Con errori',
      sk: 'Z błędami',
      ja: 'エラーあり',
      ko: '오류 있음',
      hi: 'त्रुटियों के साथ',
      nl: 'Met fouten',
      sv: 'Med fel',
      vi: 'Có lỗi',
      id: 'Dengan kesalahan',
    }),
    statusUncategorized: t({
      ru: 'Без категории',
      en: 'Uncategorized',
      kk: 'Санатсыз',
      de: 'Unkategorisiert',
      fr: 'Non catégorisé',
      es: 'Sin categorizar',
      pt: 'Sem categoria',
      tr: 'Kategorisiz',
      uk: 'Без категорії',
      zh: '未分类',
      ar: 'غير مصنف',
      pl: 'Bez kategorii',
      it: 'Non categorizzato',
      sk: 'Bez kategorii',
      ja: '未分類',
      ko: '미분류',
      hi: 'बिना श्रेणी के',
      nl: 'Zonder categorie',
      sv: 'Okategoriserad',
      vi: 'Chưa phân loại',
      id: 'Tanpa kategori',
    }),
    categoryFilter: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '分类',
      ar: 'الفئة',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategoria',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
    }),
    categoryAll: t({
      ru: 'Все категории',
      en: 'All Categories',
      kk: 'Барлық санаттар',
      de: 'Alle Kategorien',
      fr: 'Toutes les catégories',
      es: 'Todas las categorías',
      pt: 'Todas as categorias',
      tr: 'Tüm Kategoriler',
      uk: 'Всі категорії',
      zh: '所有分类',
      ar: 'جميع الفئات',
      pl: 'Wszystkie kategorie',
      it: 'Tutte le categorie',
      sk: 'Wszystkie kategorie',
      ja: 'すべてのカテゴリ',
      ko: '모든 카테고리',
      hi: 'सभी श्रेणियां',
      nl: 'Alle categorieën',
      sv: 'Alla kategorier',
      vi: 'Tất cả danh mục',
      id: 'Semua kategori',
    }),
    clearFilters: t({
      ru: 'Очистить',
      en: 'Clear',
      kk: 'Тазалау',
      de: 'Löschen',
      fr: 'Effacer',
      es: 'Limpiar',
      pt: 'Limpar',
      tr: 'Temizle',
      uk: 'Очистити',
      zh: '清除',
      ar: 'مسح',
      pl: 'Wyczyść',
      it: 'Cancella',
      sk: 'Wyczyść',
      ja: 'クリア',
      ko: '초기화',
      hi: 'साफ़ करें',
      nl: 'Wissen',
      sv: 'Rensa',
      vi: 'Xóa bộ lọc',
      id: 'Hapus',
    }),
    columnDate: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
      sk: 'Data',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
    }),
    columnCounterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı Taraf',
      uk: 'Контрагент',
      zh: '交易对手',
      ar: 'الطرف المقابل',
      pl: 'Kontrahent',
      it: 'Controparte',
      sk: 'Kontrahent',
      ja: '取引先',
      ko: '거래처',
      hi: 'प्रतिपक्ष',
      nl: 'Tegenpartij',
      sv: 'Motpart',
      vi: 'Đối tác',
      id: 'Pihak lawan',
    }),
    columnBin: t({
      ru: 'БИН',
      en: 'BIN',
      kk: 'БСН',
      de: 'BIN',
      fr: 'BIN',
      es: 'BIN',
      pt: 'BIN',
      tr: 'BIN',
      uk: 'БІН',
      zh: 'BIN',
      ar: 'رقم BIN',
      pl: 'BIN',
      it: 'BIN',
      sk: 'BIN',
      ja: 'BIN',
      ko: 'BIN',
      hi: 'BIN',
      nl: 'BIN',
      sv: 'BIN',
      vi: 'BIN',
      id: 'BIN',
    }),
    columnPurpose: t({
      ru: 'Назначение',
      en: 'Purpose',
      kk: 'Мақсаты',
      de: 'Zweck',
      fr: 'Objet',
      es: 'Propósito',
      pt: 'Finalidade',
      tr: 'Amaç',
      uk: 'Призначення',
      zh: '用途',
      ar: 'الغرض',
      pl: 'Cel',
      it: 'Scopo',
      sk: 'Cel',
      ja: '目的',
      ko: '목적',
      hi: 'उद्देश्य',
      nl: 'Doel',
      sv: 'Syfte',
      vi: 'Mục đích',
      id: 'Tujuan',
    }),
    columnDebit: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Débito',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      ar: 'مدين',
      pl: 'Debet',
      it: 'Addebito',
      sk: 'Debet',
      ja: '借方',
      ko: '차변',
      hi: 'डेबिट',
      nl: 'Debet',
      sv: 'Debet',
      vi: 'Ghi nợ',
      id: 'Debit',
    }),
    columnCredit: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Crédito',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      ar: 'دائن',
      pl: 'Kredyt',
      it: 'Credito',
      sk: 'Kredyt',
      ja: '貸方',
      ko: '대변',
      hi: 'क्रेडिट',
      nl: 'Krediet',
      sv: 'Kredit',
      vi: 'Ghi có',
      id: 'Kredit',
    }),
    columnCategory: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '分类',
      ar: 'الفئة',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategoria',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
    }),
    noResults: t({
      ru: 'Транзакции не найдены',
      en: 'No transactions found',
      kk: 'Транзакциялар табылмады',
      de: 'Keine Transaktionen gefunden',
      fr: 'Aucune transaction trouvée',
      es: 'No se encontraron transacciones',
      pt: 'Nenhuma transação encontrada',
      tr: 'İşlem bulunamadı',
      uk: 'Транзакції не знайдені',
      zh: '未找到交易',
      ar: 'لم يتم العثور على معاملات',
      pl: 'Nie znaleziono transakcji',
      it: 'Nessuna transazione trovata',
      sk: 'Nie znaleziono transakcji',
      ja: '取引が見つかりません',
      ko: '거래 내역이 없습니다',
      hi: 'कोई लेनदेन नहीं मिला',
      nl: 'Geen transacties gevonden',
      sv: 'Inga transaktioner hittades',
      vi: 'Không tìm thấy giao dịch',
      id: 'Tidak ada transaksi ditemukan',
    }),
    rowsPerPage: t({
      ru: 'Строк на странице:',
      en: 'Rows per page:',
      kk: 'Беттегі жолдар:',
      de: 'Zeilen pro Seite:',
      fr: 'Lignes par page :',
      es: 'Filas por página:',
      pt: 'Linhas por página:',
      tr: 'Sayfa başına satır:',
      uk: 'Рядків на сторінці:',
      zh: '每页行数：',
      ar: 'صفوف في الصفحة:',
      pl: 'Wierszy na stronę:',
      it: 'Righe per pagina:',
      sk: 'Wierszy na stronę:',
      ja: '1ページの行数：',
      ko: '페이지당 행 수:',
      hi: 'प्रति पृष्ठ पंक्तियाँ:',
      nl: 'Rijen per pagina:',
      sv: 'Rader per sida:',
      vi: 'Hàng mỗi trang:',
      id: 'Baris per halaman:',
    }),
    of: t({
      ru: 'из',
      en: 'of',
      kk: '/',
      de: 'von',
      fr: 'sur',
      es: 'de',
      pt: 'de',
      tr: '/',
      uk: 'з',
      zh: '/',
      ar: 'من',
      pl: 'z',
      it: 'di',
      sk: 'z',
      ja: '/',
      ko: '/',
      hi: 'में से',
      nl: 'van',
      sv: 'av',
      vi: '/',
      id: 'dari',
    }),
    previous: t({
      ru: 'Назад',
      en: 'Previous',
      kk: 'Артқа',
      de: 'Zurück',
      fr: 'Précédent',
      es: 'Anterior',
      pt: 'Anterior',
      tr: 'Önceki',
      uk: 'Назад',
      zh: '上一页',
      ar: 'السابق',
      pl: 'Poprzednia',
      it: 'Precedente',
      sk: 'Poprzednia',
      ja: '前へ',
      ko: '이전',
      hi: 'पिछला',
      nl: 'Vorige',
      sv: 'Föregående',
      vi: 'Trước',
      id: 'Sebelumnya',
    }),
    next: t({
      ru: 'Вперед',
      en: 'Next',
      kk: 'Алға',
      de: 'Weiter',
      fr: 'Suivant',
      es: 'Siguiente',
      pt: 'Próximo',
      tr: 'Sonraki',
      uk: 'Вперед',
      zh: '下一页',
      ar: 'التالي',
      pl: 'Następna',
      it: 'Successivo',
      sk: 'Następna',
      ja: '次へ',
      ko: '다음',
      hi: 'अगला',
      nl: 'Volgende',
      sv: 'Nästa',
      vi: 'Tiếp theo',
      id: 'Berikutnya',
    }),
  },
} satisfies Dictionary;

export default content;
