import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionsPageView',
  content: {
    notImplemented: t({
      ru: 'Еще не реализовано',
      en: 'Not implemented yet',
      kk: 'Әлі іске асырылмаған',
      de: 'Noch nicht implementiert',
      fr: 'Pas encore implémenté',
      es: 'Aún no implementado',
      pt: 'Ainda não implementado',
      tr: 'Henüz uygulanmadı',
      uk: 'Ще не реалізовано',
      zh: '尚未实现',
      ar: 'لم يتم التنفيذ بعد',
      pl: 'Jeszcze nie zaimplementowano',
      it: 'Non ancora implementato',
      sk: 'Zatiaľ nie je implementované',
      ja: 'まだ実装されていません',
      ko: '아직 구현되지 않았습니다',
      hi: 'अभी तक लागू नहीं किया गया',
      nl: 'Nog niet geïmplementeerd',
      sv: 'Inte implementerat ännu',
      vi: 'Chưa được triển khai',
      id: 'Belum diimplementasikan',
      da: 'Ikke implementeret endnu',
      nb: 'Ikke implementert ennå',
      nn: 'Ikkje implementert enno',
      fi: 'Ei vielä toteutettu',
      is: 'Ekki enn útfært',
      fo: 'Ikki gjørt enn',
      cs: 'Zatím není hotové',
      bg: 'Още не е направено',
      hr: 'Još nije napravljeno',
      sr: 'Још није направљено',
      sl: 'Še ni izvedeno',
      mk: 'Сè уште не е направено',
      be: 'Пакуль не зроблена',
      bs: 'Još nije napravljeno',
      hsb: 'Hišće njeje zwoprawdźene',
    }),
    categoryUpdated: t({
      ru: 'Категория обновлена успешно',
      en: 'Category updated successfully',
      kk: 'Санат сәтті жаңартылды',
      de: 'Kategorie erfolgreich aktualisiert',
      fr: 'Catégorie mise à jour avec succès',
      es: 'Categoría actualizada correctamente',
      pt: 'Categoria atualizada com sucesso',
      tr: 'Kategori başarıyla güncellendi',
      uk: 'Категорію успішно оновлено',
      zh: '分类更新成功',
      ar: 'تم تحديث الفئة بنجاح',
      pl: 'Kategoria zaktualizowana pomyślnie',
      it: 'Categoria aggiornata con successo',
      sk: 'Kategória bola úspešne aktualizovaná',
      ja: 'カテゴリが正常に更新されました',
      ko: '카테고리가 성공적으로 업데이트되었습니다',
      hi: 'श्रेणी सफलतापूर्वक अपडेट की गई',
      nl: 'Categorie succesvol bijgewerkt',
      sv: 'Kategorin uppdaterades framgångsrikt',
      vi: 'Danh mục đã được cập nhật thành công',
      id: 'Kategori berhasil diperbarui',
      da: 'Kategorien er opdateret',
      nb: 'Kategorien er oppdatert',
      nn: 'Kategorien er oppdatert',
      fi: 'Luokka päivitettiin',
      is: 'Flokkur uppfærður',
      fo: 'Bólkurin er dagførdur',
      cs: 'Kategorie byla aktualizována',
      bg: 'Категорията е обновена',
      hr: 'Kategorija je promijenjena',
      sr: 'Категорија је промењена',
      sl: 'Kategorija je spremenjena',
      mk: 'Категоријата е променета',
      be: 'Катэгорыя абноўлена',
      bs: 'Kategorija je promijenjena',
      hsb: 'Kategorija je zaktualizowana',
    }),
    categoryUpdateFailed: t({
      ru: 'Не удалось обновить категорию',
      en: 'Failed to update category',
      kk: 'Санатты жаңарту сәтсіз аяқталды',
      de: 'Kategorie konnte nicht aktualisiert werden',
      fr: 'Échec de la mise à jour de la catégorie',
      es: 'Error al actualizar la categoría',
      pt: 'Falha ao atualizar a categoria',
      tr: 'Kategori güncellenemedi',
      uk: 'Не вдалося оновити категорію',
      zh: '更新分类失败',
      ar: 'فشل تحديث الفئة',
      pl: 'Nie udało się zaktualizować kategorii',
      it: 'Impossibile aggiornare la categoria',
      sk: 'Nepodarilo sa aktualizovať kategóriu',
      ja: 'カテゴリの更新に失敗しました',
      ko: '카테고리 업데이트에 실패했습니다',
      hi: 'श्रेणी अपडेट करने में विफल',
      nl: 'Categorie bijwerken mislukt',
      sv: 'Det gick inte att uppdatera kategorin',
      vi: 'Cập nhật danh mục thất bại',
      id: 'Gagal memperbarui kategori',
      da: 'Kategorien kunne ikke opdateres',
      nb: 'Kunne ikke oppdatere kategorien',
      nn: 'Kunne ikkje oppdatere kategorien',
      fi: 'Luokan päivitys epäonnistui',
      is: 'Ekki tókst að uppfæra flokk',
      fo: 'Bólkurin kundi ikki dagførast',
      cs: 'Kategorii se nepodařilo aktualizovat',
      bg: 'Категорията не можа да се обнови',
      hr: 'Kategoriju nije bilo moguće promijeniti',
      sr: 'Категорију није било могуће променити',
      sl: 'Kategorije ni bilo mogoče spremeniti',
      mk: 'Категоријата не можеше да се промени',
      be: 'Не ўдалося абнавіць катэгорыю',
      bs: 'Kategoriju nije bilo moguće promijeniti',
      hsb: 'Kategorija njeda so zaktualizować',
    }),
    categoriesUpdated: t({
      ru: 'Категория назначена транзакциям',
      en: 'Category assigned to transactions',
      kk: 'Санат транзакцияларға тағайындалды',
      de: 'Kategorie den Transaktionen zugewiesen',
      fr: 'Catégorie attribuée aux transactions',
      es: 'Categoría asignada a las transacciones',
      pt: 'Categoria atribuída às transações',
      tr: 'Kategori işlemlere atandı',
      uk: 'Категорію призначено транзакціям',
      zh: '分类已分配给交易',
      ar: 'تم تعيين الفئة للمعاملات',
      pl: 'Kategoria przypisana do transakcji',
      it: 'Categoria assegnata alle transazioni',
      sk: 'Kategória bola priradená transakciám',
      ja: '取引にカテゴリが割り当てられました',
      ko: '거래에 카테고리가 할당되었습니다',
      hi: 'लेनदेन को श्रेणी सौंपी गई',
      nl: 'Categorie toegewezen aan transacties',
      sv: 'Kategori tilldelad transaktioner',
      vi: 'Danh mục đã được gán cho giao dịch',
      id: 'Kategori ditetapkan ke transaksi',
      da: 'Kategorien er tildelt transaktionerne',
      nb: 'Kategorien er tilordnet transaksjonene',
      nn: 'Kategorien er tilordna transaksjonane',
      fi: 'Luokka määritettiin tapahtumille',
      is: 'Flokki úthlutað á færslurnar',
      fo: 'Bólkur er latin til posteringarnar',
      cs: 'Kategorie byla přiřazena transakcím',
      bg: 'Категорията е зададена на транзакциите',
      hr: 'Kategorija je dodijeljena transakcijama',
      sr: 'Категорија је додељена трансакцијама',
      sl: 'Kategorija je dodeljena transakcijam',
      mk: 'Категоријата е доделена на трансакциите',
      be: 'Катэгорыя прызначана транзакцыям',
      bs: 'Kategorija je dodijeljena transakcijama',
      hsb: 'Kategorija je transakcijam připokazana',
    }),
    bulkUpdateFailed: t({
      ru: 'Не удалось обновить категории',
      en: 'Failed to update categories',
      kk: 'Санаттарды жаңарту сәтсіз аяқталды',
      de: 'Kategorien konnten nicht aktualisiert werden',
      fr: 'Échec de la mise à jour des catégories',
      es: 'Error al actualizar las categorías',
      pt: 'Falha ao atualizar as categorias',
      tr: 'Kategoriler güncellenemedi',
      uk: 'Не вдалося оновити категорії',
      zh: '批量更新分类失败',
      ar: 'فشل تحديث الفئات',
      pl: 'Nie udało się zaktualizować kategorii',
      it: 'Impossibile aggiornare le categorie',
      sk: 'Nepodarilo sa aktualizovať kategórie',
      ja: 'カテゴリの一括更新に失敗しました',
      ko: '카테고리 일괄 업데이트에 실패했습니다',
      hi: 'श्रेणियां अपडेट करने में विफल',
      nl: 'Categorieën bijwerken mislukt',
      sv: 'Det gick inte att uppdatera kategorier',
      vi: 'Cập nhật danh mục hàng loạt thất bại',
      id: 'Gagal memperbarui kategori',
      da: 'Kategorierne kunne ikke opdateres',
      nb: 'Kunne ikke oppdatere kategoriene',
      nn: 'Kunne ikkje oppdatere kategoriane',
      fi: 'Luokkien päivitys epäonnistui',
      is: 'Ekki tókst að uppfæra flokkana',
      fo: 'Bólkarnir kundu ikki dagførast',
      cs: 'Kategorie se nepodařilo aktualizovat',
      bg: 'Категориите не можаха да се обновят',
      hr: 'Kategorije nije bilo moguće promijeniti',
      sr: 'Категорије није било могуће променити',
      sl: 'Kategorij ni bilo mogoče spremeniti',
      mk: 'Категориите не можеа да се променат',
      be: 'Не ўдалося абнавіць катэгорыі',
      bs: 'Kategorije nije bilo moguće promijeniti',
      hsb: 'Kategorije njedachu so zaktualizować',
    }),
    exportComingSoon: t({
      ru: 'Экспорт скоро будет доступен',
      en: 'Export feature coming soon',
      kk: 'Экспорт мүмкіндігі жақын арада',
      de: 'Exportfunktion demnächst verfügbar',
      fr: "Fonctionnalité d'export bientôt disponible",
      es: 'Función de exportación próximamente',
      pt: 'Função de exportação em breve',
      tr: 'Dışa aktarma özelliği yakında',
      uk: 'Функція експорту незабаром буде доступна',
      zh: '导出功能即将推出',
      ar: 'ميزة التصدير قادمة قريباً',
      pl: 'Funkcja eksportu wkrótce',
      it: 'Funzione di esportazione in arrivo',
      sk: 'Funkcia exportu už čoskoro',
      ja: 'エクスポート機能は近日公開',
      ko: '내보내기 기능 곧 출시',
      hi: 'निर्यात सुविधा जल्द आ रही है',
      nl: 'Exportfunctie binnenkort beschikbaar',
      sv: 'Exportfunktion kommer snart',
      vi: 'Tính năng xuất sắp ra mắt',
      id: 'Fitur ekspor segera hadir',
      da: 'Eksportfunktionen kommer snart',
      nb: 'Eksportfunksjonen kommer snart',
      nn: 'Eksportfunksjonen kjem snart',
      fi: 'Vientitoiminto tulossa pian',
      is: 'Útflutningsaðgerð væntanleg',
      fo: 'Útflutningsvirkið kemur skjótt',
      cs: 'Export bude k dispozici brzy',
      bg: 'Експортът идва скоро',
      hr: 'Izvoz dolazi uskoro',
      sr: 'Извоз долази ускоро',
      sl: 'Izvoz prihaja kmalu',
      mk: 'Извозот доаѓа наскоро',
      be: 'Экспарт будзе хутка',
      bs: 'Izvoz dolazi uskoro',
      hsb: 'Eksport přińdźe bórze',
    }),
    shareComingSoon: t({
      ru: 'Функция поделиться скоро будет доступна',
      en: 'Share feature coming soon',
      kk: 'Бөлісу мүмкіндігі жақын арада',
      de: 'Teilfunktion demnächst verfügbar',
      fr: 'Fonctionnalité de partage bientôt disponible',
      es: 'Función de compartir próximamente',
      pt: 'Função de compartilhamento em breve',
      tr: 'Paylaşma özelliği yakında',
      uk: 'Функція поділитися незабаром буде доступна',
      zh: '分享功能即将推出',
      ar: 'ميزة المشاركة قادمة قريباً',
      pl: 'Funkcja udostępniania wkrótce',
      it: 'Funzione di condivisione in arrivo',
      sk: 'Funkcia zdieľania už čoskoro',
      ja: '共有機能は近日公開',
      ko: '공유 기능 곧 출시',
      hi: 'शेयर सुविधा जल्द आ रही है',
      nl: 'Deelfunctie binnenkort beschikbaar',
      sv: 'Delningsfunktion kommer snart',
      vi: 'Tính năng chia sẻ sắp ra mắt',
      id: 'Fitur berbagi segera hadir',
      da: 'Delefunktionen kommer snart',
      nb: 'Delefunksjonen kommer snart',
      nn: 'Delefunksjonen kjem snart',
      fi: 'Jakotoiminto tulossa pian',
      is: 'Deiliaðgerð væntanleg',
      fo: 'Deilingarvirkið kemur skjótt',
      cs: 'Sdílení bude k dispozici brzy',
      bg: 'Споделянето идва скоро',
      hr: 'Dijeljenje dolazi uskoro',
      sr: 'Дељење долази ускоро',
      sl: 'Deljenje prihaja kmalu',
      mk: 'Споделувањето доаѓа наскоро',
      be: 'Падзяленне будзе хутка',
      bs: 'Dijeljenje dolazi uskoro',
      hsb: 'Dźělenje přińdźe bórze',
    }),
    fixIssuesHint: t({
      ru: 'Используйте фильтры для поиска и исправления проблем',
      en: 'Use filters to find and fix issues',
      kk: 'Мәселелерді табу және шешу үшін сүзгілерді пайдаланыңыз',
      de: 'Verwenden Sie Filter, um Probleme zu finden und zu beheben',
      fr: 'Utilisez les filtres pour trouver et corriger les problèmes',
      es: 'Use filtros para encontrar y corregir problemas',
      pt: 'Use filtros para encontrar e corrigir problemas',
      tr: 'Sorunları bulmak ve düzeltmek için filtreleri kullanın',
      uk: 'Використовуйте фільтри для пошуку та виправлення проблем',
      zh: '使用筛选器查找并修复问题',
      ar: 'استخدم المرشحات للعثور على المشكلات وإصلاحها',
      pl: 'Użyj filtrów, aby znaleźć i naprawić problemy',
      it: 'Usa i filtri per trovare e risolvere i problemi',
      sk: 'Pomocou filtrov nájdite a opravte problémy',
      ja: 'フィルターを使用して問題を見つけて修正してください',
      ko: '필터를 사용하여 문제를 찾고 수정하세요',
      hi: 'समस्याओं को खोजने और ठीक करने के लिए फ़िल्टर का उपयोग करें',
      nl: 'Gebruik filters om problemen te vinden en op te lossen',
      sv: 'Använd filter för att hitta och åtgärda problem',
      vi: 'Sử dụng bộ lọc để tìm và sửa vấn đề',
      id: 'Gunakan filter untuk menemukan dan memperbaiki masalah',
      da: 'Brug filtre til at finde og rette problemer',
      nb: 'Bruk filtre for å finne og rette problemer',
      nn: 'Bruk filter for å finne og rette problem',
      fi: 'Käytä suodattimia ongelmien löytämiseen ja korjaamiseen',
      is: 'Notaðu síur til að finna og leysa vandamál',
      fo: 'Brúka sílur til at finna og rætta trupulleikar',
      cs: 'Pomocí filtrů najděte a vyřešte problémy',
      bg: 'Използвайте филтрите, за да откриете и отстраните проблемите',
      hr: 'Pomoću filtara nađite i riješite probleme',
      sr: 'Помоћу филтера нађите и решите проблеме',
      sl: 'S filtri poiščite in odpravite težave',
      mk: 'Со филтрите најдете и решете ги проблемите',
      be: 'Карыстайцеся фільтрамі, каб знайсці і выправіць праблемы',
      bs: 'Pomoću filtera nađite i riješite probleme',
      hsb: 'Wužiwajće filtry, zo byšće problemy namakał a rozrisał',
    }),
    selected: t({
      ru: 'выбрано',
      en: 'selected',
      kk: 'таңдалды',
      de: 'ausgewählt',
      fr: 'sélectionné',
      es: 'seleccionado',
      pt: 'selecionado',
      tr: 'seçildi',
      uk: 'вибрано',
      zh: '已选择',
      ar: 'محدد',
      pl: 'zaznaczono',
      it: 'selezionato',
      sk: 'vybrané',
      ja: '選択済み',
      ko: '선택됨',
      hi: 'चयनित',
      nl: 'geselecteerd',
      sv: 'markerade',
      vi: 'đã chọn',
      id: 'dipilih',
      da: 'valgt',
      nb: 'valgt',
      nn: 'vald',
      fi: 'valittu',
      is: 'valið',
      fo: 'valt',
      cs: 'vybráno',
      bg: 'избрани',
      hr: 'odabrano',
      sr: 'изабрано',
      sl: 'izbrano',
      mk: 'избрано',
      be: 'выбрана',
      bs: 'odabrano',
      hsb: 'wubrane',
    }),
    selectCategory: t({
      ru: 'Выберите категорию...',
      en: 'Select category...',
      kk: 'Санат таңдаңыз...',
      de: 'Kategorie auswählen...',
      fr: 'Sélectionner une catégorie...',
      es: 'Seleccionar categoría...',
      pt: 'Selecionar categoria...',
      tr: 'Kategori seçin...',
      uk: 'Оберіть категорію...',
      zh: '选择分类...',
      ar: 'اختر الفئة...',
      pl: 'Wybierz kategorię...',
      it: 'Seleziona categoria...',
      sk: 'Vyberte kategóriu...',
      ja: 'カテゴリを選択...',
      ko: '카테고리 선택...',
      hi: 'श्रेणी चुनें...',
      nl: 'Selecteer categorie...',
      sv: 'Välj kategori...',
      vi: 'Chọn danh mục...',
      id: 'Pilih kategori...',
      da: 'Vælg kategori ...',
      nb: 'Velg kategori ...',
      nn: 'Vel kategori ...',
      fi: 'Valitse luokka ...',
      is: 'Veldu flokk ...',
      fo: 'Vel bólk ...',
      cs: 'Vyberte kategorii ...',
      bg: 'Изберете категория ...',
      hr: 'Odaberite kategoriju ...',
      sr: 'Изаберите категорију ...',
      sl: 'Izberite kategorijo ...',
      mk: 'Изберете категорија ...',
      be: 'Выберыце катэгорыю ...',
      bs: 'Odaberite kategoriju ...',
      hsb: 'Wubjerće kategoriju ...',
    }),
    apply: t({
      ru: 'Применить',
      en: 'Apply',
      kk: 'Қолдану',
      de: 'Anwenden',
      fr: 'Appliquer',
      es: 'Aplicar',
      pt: 'Aplicar',
      tr: 'Uygula',
      uk: 'Застосувати',
      zh: '应用',
      ar: 'تطبيق',
      pl: 'Zastosuj',
      it: 'Applica',
      sk: 'Použiť',
      ja: '適用',
      ko: '적용',
      hi: 'लागू करें',
      nl: 'Toepassen',
      sv: 'Tillämpa',
      vi: 'Áp dụng',
      id: 'Terapkan',
      da: 'Anvend',
      nb: 'Bruk',
      nn: 'Bruk',
      fi: 'Käytä',
      is: 'Nota',
      fo: 'Nýt',
      cs: 'Použít',
      bg: 'Приложи',
      hr: 'Primijeni',
      sr: 'Примени',
      sl: 'Uporabi',
      mk: 'Примени',
      be: 'Прымяніць',
      bs: 'Primijeni',
      hsb: 'Nałožić',
    }),
    clearSelection: t({
      ru: 'Очистить',
      en: 'Clear',
      kk: 'Тазалау',
      de: 'Löschen',
      fr: 'Effacer',
      es: 'Limpiar',
      pt: 'Limpar',
      tr: 'Temizle',
      uk: 'Очистити',
      zh: '清除',
      ar: 'مسح',
      pl: 'Wyczyść',
      it: 'Cancella',
      sk: 'Zrušiť výber',
      ja: 'クリア',
      ko: '초기화',
      hi: 'साफ़ करें',
      nl: 'Wissen',
      sv: 'Rensa',
      vi: 'Xóa',
      id: 'Hapus',
      da: 'Ryd',
      nb: 'Tøm',
      nn: 'Tøm',
      fi: 'Tyhjennä',
      is: 'Hreinsa',
      fo: 'Reinsa',
      cs: 'Vymazat',
      bg: 'Изчисти',
      hr: 'Očisti',
      sr: 'Очисти',
      sl: 'Počisti',
      mk: 'Исчисти',
      be: 'Ачысціць',
      bs: 'Očisti',
      hsb: 'Wuprózdnić',
    }),
    allCategorized: t({
      ru: 'Все транзакции уже категоризированы',
      en: 'All transactions are already categorized',
      kk: 'Барлық транзакциялар санатталған',
      de: 'Alle Transaktionen sind bereits kategorisiert',
      fr: 'Toutes les transactions sont déjà catégorisées',
      es: 'Todas las transacciones ya están categorizadas',
      pt: 'Todas as transações já estão categorizadas',
      tr: 'Tüm işlemler zaten kategorize edildi',
      uk: 'Всі транзакції вже категоризовані',
      zh: '所有交易已分类',
      ar: 'جميع المعاملات مصنفة بالفعل',
      pl: 'Wszystkie transakcje są już skategoryzowane',
      it: 'Tutte le transazioni sono già categorizzate',
      sk: 'Všetky transakcie už majú kategóriu',
      ja: 'すべての取引はすでに分類されています',
      ko: '모든 거래가 이미 분류되었습니다',
      hi: 'सभी लेनदेन पहले से वर्गीकृत हैं',
      nl: 'Alle transacties zijn al gecategoriseerd',
      sv: 'Alla transaktioner är redan kategoriserade',
      vi: 'Tất cả giao dịch đã được phân loại',
      id: 'Semua transaksi sudah dikategorikan',
      da: 'Alle transaktioner er allerede kategoriseret',
      nb: 'Alle transaksjoner er allerede kategorisert',
      nn: 'Alle transaksjonar er alt kategoriserte',
      fi: 'Kaikki tapahtumat on jo luokiteltu',
      is: 'Allar færslur eru þegar flokkaðar',
      fo: 'Allar posteringar eru longu bólkaðar',
      cs: 'Všechny transakce už jsou zařazené',
      bg: 'Всички транзакции вече са категоризирани',
      hr: 'Sve transakcije su već kategorizirane',
      sr: 'Све трансакције су већ категоризоване',
      sl: 'Vse transakcije so že razvrščene',
      mk: 'Сите трансакции се веќе категоризирани',
      be: 'Усе транзакцыі ўжо катэгарызаваны',
      bs: 'Sve transakcije su već kategorizirane',
      hsb: 'Wšě transakcije su hižo kategorizowane',
    }),
    categorizingProgress: t({
      ru: 'Категоризация {{count}} транзакций...',
      en: 'Categorizing {{count}} transactions...',
      kk: '{{count}} транзакция санатталуда...',
      de: '{{count}} Transaktionen werden kategorisiert...',
      fr: 'Catégorisation de {{count}} transactions...',
      es: 'Categorizando {{count}} transacciones...',
      pt: 'Categorizando {{count}} transações...',
      tr: '{{count}} işlem kategorize ediliyor...',
      uk: 'Категоризація {{count}} транзакцій...',
      zh: '正在分类 {{count}} 笔交易...',
      ar: 'جارٍ تصنيف {{count}} معاملة...',
      pl: 'Kategoryzowanie {{count}} transakcji...',
      it: 'Categorizzazione di {{count}} transazioni...',
      sk: 'Kategorizuje sa {{count}} transakcií...',
      ja: '{{count}} 件の取引を分類中...',
      ko: '{{count}}개 거래 분류 중...',
      hi: '{{count}} लेनदेन वर्गीकृत हो रहे हैं...',
      nl: '{{count}} transacties categoriseren...',
      sv: 'Kategoriserar {{count}} transaktioner...',
      vi: 'Đang phân loại {{count}} giao dịch...',
      id: 'Mengkategorikan {{count}} transaksi...',
      da: 'Kategoriserer {{count}} transaktioner ...',
      nb: 'Kategoriserer {{count}} transaksjoner ...',
      nn: 'Kategoriserer {{count}} transaksjonar ...',
      fi: 'Luokitellaan {{count}} tapahtumaa ...',
      is: 'Flokka {{count}} færslur ...',
      fo: 'Bólkar {{count}} posteringar ...',
      cs: 'Zařazuje se {{count}} transakcí ...',
      bg: 'Категоризират се {{count}} транзакции ...',
      hr: 'Kategorizira se {{count}} transakcija ...',
      sr: 'Категоризује се {{count}} трансакција ...',
      sl: 'Razvrščanje {{count}} transakcij ...',
      mk: 'Се категоризираат {{count}} трансакции ...',
      be: 'Катэгарызуецца {{count}} транзакцый ...',
      bs: 'Kategorizira se {{count}} transakcija ...',
      hsb: '{{count}} transakcijow so kategorizuje ...',
    }),
    categorizeSuccess: t({
      ru: 'Успешно категоризировано {{count}} транзакций',
      en: 'Successfully categorized {{count}} transactions',
      kk: '{{count}} транзакция сәтті санатталды',
      de: '{{count}} Transaktionen erfolgreich kategorisiert',
      fr: '{{count}} transactions catégorisées avec succès',
      es: '{{count}} transacciones categorizadas correctamente',
      pt: '{{count}} transações categorizadas com sucesso',
      tr: '{{count}} işlem başarıyla kategorize edildi',
      uk: 'Успішно категоризовано {{count}} транзакцій',
      zh: '已成功分类 {{count}} 笔交易',
      ar: 'تم تصنيف {{count}} معاملة بنجاح',
      pl: 'Pomyślnie skategoryzowano {{count}} transakcji',
      it: '{{count}} transazioni categorizzate con successo',
      sk: 'Úspešne kategorizovaných {{count}} transakcií',
      ja: '{{count}} 件の取引を正常に分類しました',
      ko: '{{count}}개 거래가 성공적으로 분류되었습니다',
      hi: '{{count}} लेनदेन सफलतापूर्वक वर्गीकृत',
      nl: '{{count}} transacties succesvol gecategoriseerd',
      sv: '{{count}} transaktioner kategoriserades framgångsrikt',
      vi: 'Đã phân loại thành công {{count}} giao dịch',
      id: 'Berhasil mengkategorikan {{count}} transaksi',
      da: '{{count}} transaktioner blev kategoriseret',
      nb: '{{count}} transaksjoner ble kategorisert',
      nn: '{{count}} transaksjonar vart kategoriserte',
      fi: '{{count}} tapahtumaa luokiteltiin',
      is: '{{count}} færslur voru flokkaðar',
      fo: '{{count}} posteringar vórðu bólkaðar',
      cs: 'Zařazeno {{count}} transakcí',
      bg: 'Категоризирани са {{count}} транзакции',
      hr: 'Kategorizirano je {{count}} transakcija',
      sr: 'Категоризовано је {{count}} трансакција',
      sl: 'Razvrščenih je {{count}} transakcij',
      mk: 'Категоризирани се {{count}} трансакции',
      be: 'Катэгарызавана {{count}} транзакцый',
      bs: 'Kategorizirano je {{count}} transakcija',
      hsb: '{{count}} transakcijow je kategorizowanych',
    }),
    categorizePartial: t({
      ru: 'Категоризировано {{successful}} из {{total}}. Ошибок: {{failed}}',
      en: 'Categorized {{successful}} of {{total}}. Errors: {{failed}}',
      kk: '{{total}} ішінен {{successful}} санатталды. Қателер: {{failed}}',
      de: '{{successful}} von {{total}} kategorisiert. Fehler: {{failed}}',
      fr: '{{successful}} sur {{total}} catégorisés. Erreurs : {{failed}}',
      es: '{{successful}} de {{total}} categorizados. Errores: {{failed}}',
      pt: '{{successful}} de {{total}} categorizados. Erros: {{failed}}',
      tr: '{{total}} içinden {{successful}} kategorize edildi. Hatalar: {{failed}}',
      uk: 'Категоризовано {{successful}} з {{total}}. Помилок: {{failed}}',
      zh: '已分类 {{total}} 中的 {{successful}} 笔。错误：{{failed}}',
      ar: 'تم تصنيف {{successful}} من {{total}}. أخطاء: {{failed}}',
      pl: 'Skategoryzowano {{successful}} z {{total}}. Błędy: {{failed}}',
      it: '{{successful}} di {{total}} categorizzati. Errori: {{failed}}',
      sk: 'Kategorizovaných {{successful}} z {{total}}. Chyby: {{failed}}',
      ja: '{{total}} 件中 {{successful}} 件を分類しました。エラー：{{failed}}',
      ko: '{{total}}개 중 {{successful}}개 분류됨. 오류: {{failed}}',
      hi: '{{total}} में से {{successful}} वर्गीकृत। त्रुटियां: {{failed}}',
      nl: '{{successful}} van {{total}} gecategoriseerd. Fouten: {{failed}}',
      sv: '{{successful}} av {{total}} kategoriserade. Fel: {{failed}}',
      vi: 'Đã phân loại {{successful}} trong {{total}}. Lỗi: {{failed}}',
      id: '{{successful}} dari {{total}} dikategorikan. Kesalahan: {{failed}}',
      da: '{{successful}} af {{total}} kategoriseret. Fejl: {{failed}}',
      nb: '{{successful}} av {{total}} kategorisert. Feil: {{failed}}',
      nn: '{{successful}} av {{total}} kategoriserte. Feil: {{failed}}',
      fi: '{{successful}} / {{total}} luokiteltu. Virheet: {{failed}}',
      is: '{{successful}} af {{total}} flokkaðar. Villur: {{failed}}',
      fo: '{{successful}} av {{total}} bólkaðar. Feilir: {{failed}}',
      cs: 'Zařazeno {{successful}} z {{total}}. Chyby: {{failed}}',
      bg: 'Категоризирани са {{successful}} от {{total}}. Грешки: {{failed}}',
      hr: 'Kategorizirano {{successful}} od {{total}}. Pogreške: {{failed}}',
      sr: 'Категоризовано {{successful}} од {{total}}. Грешке: {{failed}}',
      sl: 'Razvrščenih {{successful}} od {{total}}. Napake: {{failed}}',
      mk: 'Категоризирани {{successful}} од {{total}}. Грешки: {{failed}}',
      be: 'Катэгарызавана {{successful}} з {{total}}. Памылкі: {{failed}}',
      bs: 'Kategorizirano {{successful}} od {{total}}. Greške: {{failed}}',
      hsb: '{{successful}} z {{total}} kategorizowanych. Zmylki: {{failed}}',
    }),
    categorizeFailed: t({
      ru: 'Не удалось категоризировать (ошибок: {{count}})',
      en: 'Failed to categorize (errors: {{count}})',
      kk: 'Санаттау мүмкін болмады (қателер: {{count}})',
      de: 'Kategorisierung fehlgeschlagen (Fehler: {{count}})',
      fr: 'Échec de la catégorisation (erreurs : {{count}})',
      es: 'Error al categorizar (errores: {{count}})',
      pt: 'Falha ao categorizar (erros: {{count}})',
      tr: 'Kategorize edilemedi (hatalar: {{count}})',
      uk: 'Не вдалося категоризувати (помилок: {{count}})',
      zh: '分类失败（错误：{{count}}）',
      ar: 'فشل التصنيف (أخطاء: {{count}})',
      pl: 'Nie udało się skategoryzować (błędy: {{count}})',
      it: 'Impossibile categorizzare (errori: {{count}})',
      sk: 'Kategorizácia zlyhala (chyby: {{count}})',
      ja: '分類に失敗しました（エラー：{{count}}）',
      ko: '분류 실패 (오류: {{count}})',
      hi: 'वर्गीकरण विफल (त्रुटियां: {{count}})',
      nl: 'Categoriseren mislukt (fouten: {{count}})',
      sv: 'Det gick inte att kategorisera (fel: {{count}})',
      vi: 'Phân loại thất bại (lỗi: {{count}})',
      id: 'Gagal mengkategorikan (kesalahan: {{count}})',
      da: 'Kategoriseringen mislykkedes (fejl: {{count}})',
      nb: 'Kategoriseringen mislyktes (feil: {{count}})',
      nn: 'Kategoriseringa mislukkast (feil: {{count}})',
      fi: 'Luokittelu epäonnistui (virheitä: {{count}})',
      is: 'Flokkun mistókst (villur: {{count}})',
      fo: 'Bólkingin miseydnaðist (feilir: {{count}})',
      cs: 'Zařazení se nezdařilo (chyby: {{count}})',
      bg: 'Категоризирането не успя (грешки: {{count}})',
      hr: 'Kategorizacija nije uspjela (pogreške: {{count}})',
      sr: 'Категоризација није успела (грешке: {{count}})',
      sl: 'Razvrščanje ni uspelo (napake: {{count}})',
      mk: 'Категоризирањето не успеа (грешки: {{count}})',
      be: 'Катэгарызацыя не ўдалася (памылкі: {{count}})',
      bs: 'Kategorizacija nije uspjela (greške: {{count}})',
      hsb: 'Kategorizowanje je so njeporadźiło (zmylki: {{count}})',
    }),
    autoFixFailed: t({
      ru: 'Не удалось автоматически исправить проблемы',
      en: 'Failed to automatically fix issues',
      kk: 'Мәселелерді автоматты түрде түзету мүмкін болмады',
      de: 'Probleme konnten nicht automatisch behoben werden',
      fr: 'Échec de la correction automatique des problèmes',
      es: 'Error al corregir problemas automáticamente',
      pt: 'Falha ao corrigir problemas automaticamente',
      tr: 'Sorunlar otomatik olarak düzeltilemedi',
      uk: 'Не вдалося автоматично виправити проблеми',
      zh: '自动修复问题失败',
      ar: 'فشل إصلاح المشكلات تلقائياً',
      pl: 'Nie udało się automatycznie naprawić problemów',
      it: 'Impossibile correggere automaticamente i problemi',
      sk: 'Nepodarilo sa automaticky opraviť problémy',
      ja: '問題の自動修正に失敗しました',
      ko: '문제 자동 수정에 실패했습니다',
      hi: 'समस्याओं को स्वचालित रूप से ठीक करने में विफल',
      nl: 'Automatisch oplossen van problemen mislukt',
      sv: 'Det gick inte att åtgärda problem automatiskt',
      vi: 'Tự động sửa vấn đề thất bại',
      id: 'Gagal memperbaiki masalah secara otomatis',
      da: 'Problemerne kunne ikke rettes automatisk',
      nb: 'Kunne ikke rette problemene automatisk',
      nn: 'Kunne ikkje rette problema automatisk',
      fi: 'Ongelmia ei voitu korjata automaattisesti',
      is: 'Ekki var hægt að leysa vandamálin sjálfkrafa',
      fo: 'Trupulleikarnir kundu ikki rættast sjálvvirkandi',
      cs: 'Problémy se nepodařilo vyřešit automaticky',
      bg: 'Проблемите не можаха да се отстранят автоматично',
      hr: 'Probleme nije bilo moguće riješiti automatski',
      sr: 'Проблеме није било могуће решити аутоматски',
      sl: 'Težav ni bilo mogoče odpraviti samodejno',
      mk: 'Проблемите не можеа да се решат автоматски',
      be: 'Не ўдалося выправіць праблемы аўтаматычна',
      bs: 'Probleme nije bilo moguće riješiti automatski',
      hsb: 'Problemy njedachu so awtomatisce rozrisać',
    }),
    exportToTable: t({
      ru: 'Экспорт в таблицу: функционал в разработке',
      en: 'Export to table: feature in development',
      kk: 'Кестеге экспорт: функционал әзірленуде',
      de: 'Export in Tabelle: Funktion in Entwicklung',
      fr: 'Export en tableau : fonctionnalité en développement',
      es: 'Exportar a tabla: función en desarrollo',
      pt: 'Exportar para tabela: recurso em desenvolvimento',
      tr: 'Tabloya aktar: özellik geliştiriliyor',
      uk: 'Експорт у таблицю: функціонал у розробці',
      zh: '导出到表格：功能开发中',
      ar: 'التصدير إلى جدول: الميزة قيد التطوير',
      pl: 'Eksport do tabeli: funkcja w trakcie tworzenia',
      it: 'Esporta in tabella: funzionalità in sviluppo',
      sk: 'Export do tabuľky: funkcia je vo vývoji',
      ja: 'テーブルへのエクスポート：機能開発中',
      ko: '테이블로 내보내기: 기능 개발 중',
      hi: 'तालिका में निर्यात: सुविधा विकास में',
      nl: 'Exporteren naar tabel: functie in ontwikkeling',
      sv: 'Exportera till tabell: funktion under utveckling',
      vi: 'Xuất sang bảng: tính năng đang phát triển',
      id: 'Ekspor ke tabel: fitur sedang dikembangkan',
      da: 'Eksport til tabel: funktionen er under udvikling',
      nb: 'Eksport til tabell: funksjonen er under utvikling',
      nn: 'Eksport til tabell: funksjonen er under utvikling',
      fi: 'Vienti taulukkoon: toiminto on kehityksessä',
      is: 'Útflutningur í töflu: aðgerð í þróun',
      fo: 'Útflutningur til talvu: virki í menning',
      cs: 'Export do tabulky: funkce ve vývoji',
      bg: 'Експорт в таблица: функцията е в разработка',
      hr: 'Izvoz u tablicu: funkcija je u izradi',
      sr: 'Извоз у табелу: функција је у изради',
      sl: 'Izvoz v tabelo: funkcija je v razvoju',
      mk: 'Извоз во табела: функцијата е во развој',
      be: 'Экспарт у табліцу: функцыя ў распрацоўцы',
      bs: 'Izvoz u tabelu: funkcija je u izradi',
      hsb: 'Eksport do tabele: funkcija je w rozwiću',
    }),
    exportFormat: t({
      ru: 'Экспорт в {{type}}: функционал в разработке',
      en: 'Export to {{type}}: feature in development',
      kk: '{{type}} экспорты: функционал әзірленуде',
      de: 'Export nach {{type}}: Funktion in Entwicklung',
      fr: 'Export en {{type}} : fonctionnalité en développement',
      es: 'Exportar a {{type}}: función en desarrollo',
      pt: 'Exportar para {{type}}: recurso em desenvolvimento',
      tr: '{{type}} formatına aktar: özellik geliştiriliyor',
      uk: 'Експорт у {{type}}: функціонал у розробці',
      zh: '导出为 {{type}}：功能开发中',
      ar: 'التصدير إلى {{type}}: الميزة قيد التطوير',
      pl: 'Eksport do {{type}}: funkcja w trakcie tworzenia',
      it: 'Esporta in {{type}}: funzionalità in sviluppo',
      sk: 'Export do {{type}}: funkcia je vo vývoji',
      ja: '{{type}} にエクスポート：機能開発中',
      ko: '{{type}}으로 내보내기: 기능 개발 중',
      hi: '{{type}} में निर्यात: सुविधा विकास में',
      nl: 'Exporteren naar {{type}}: functie in ontwikkeling',
      sv: 'Exportera till {{type}}: funktion under utveckling',
      vi: 'Xuất sang {{type}}: tính năng đang phát triển',
      id: 'Ekspor ke {{type}}: fitur sedang dikembangkan',
      da: 'Eksport til {{type}}: funktionen er under udvikling',
      nb: 'Eksport til {{type}}: funksjonen er under utvikling',
      nn: 'Eksport til {{type}}: funksjonen er under utvikling',
      fi: 'Vienti muotoon {{type}}: toiminto on kehityksessä',
      is: 'Útflutningur í {{type}}: aðgerð í þróun',
      fo: 'Útflutningur til {{type}}: virki í menning',
      cs: 'Export do {{type}}: funkce ve vývoji',
      bg: 'Експорт в {{type}}: функцията е в разработка',
      hr: 'Izvoz u {{type}}: funkcija je u izradi',
      sr: 'Извоз у {{type}}: функција је у изради',
      sl: 'Izvoz v {{type}}: funkcija je v razvoju',
      mk: 'Извоз во {{type}}: функцијата е во развој',
      be: 'Экспарт у {{type}}: функцыя ў распрацоўцы',
      bs: 'Izvoz u {{type}}: funkcija je u izradi',
      hsb: 'Eksport do {{type}}: funkcija je w rozwiću',
    }),
  },
} satisfies Dictionary;

export default content;
