import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'layout',
  content: {
    title: t({
      ru: 'Lumio — Обработка банковских выписок',
      en: 'Lumio — Bank statement processing',
      kk: 'Lumio — Банктік үзінділерді өңдеу',
      de: 'Lumio — Kontoauszugsverarbeitung',
      fr: 'Lumio — Traitement des relevés bancaires',
      es: 'Lumio — Procesamiento de extractos bancarios',
      pt: 'Lumio — Processamento de extratos bancários',
      tr: 'Lumio — Banka ekstresi işleme',
      uk: 'Lumio — Обробка банківських виписок',
      zh: 'Lumio — 银行对账单处理',
      ar: 'Lumio — معالجة كشوف الحسابات البنكية',
      pl: 'Lumio — Przetwarzanie wyciągów bankowych',
      it: 'Lumio — Elaborazione degli estratti conto bancari',
      sk: 'Lumio — Przetwarzanie wyciągów bankowych',
      ja: 'Lumio — 銀行取引明細書処理',
      ko: 'Lumio — 은행 명세서 처리',
      hi: 'Lumio — बैंक स्टेटमेंट प्रोसेसिंग',
      nl: 'Lumio — Bankrekeningverwerking',
      sv: 'Lumio — Behandling av kontoutdrag',
      vi: 'Lumio — Xử lý sao kê ngân hàng',
      id: 'Lumio — Pemrosesan rekening koran',
    }),
    description: t({
      ru: 'Система автоматической обработки банковских выписок',
      en: 'Automatic bank statement processing system',
      kk: 'Банктік үзінділерді автоматты өңдеу жүйесі',
      de: 'System zur automatischen Verarbeitung von Kontoauszügen',
      fr: 'Système de traitement automatique des relevés bancaires',
      es: 'Sistema de procesamiento automático de extractos bancarios',
      pt: 'Sistema de processamento automático de extratos bancários',
      tr: 'Otomatik banka ekstresi işleme sistemi',
      uk: 'Система автоматичної обробки банківських виписок',
      zh: '自动银行对账单处理系统',
      ar: 'نظام معالجة كشوف الحسابات البنكية تلقائياً',
      pl: 'System automatycznego przetwarzania wyciągów bankowych',
      it: 'Sistema di elaborazione automatica degli estratti conto bancari',
      sk: 'System automatycznego przetwarzania wyciągów bankowych',
      ja: '自動銀行取引明細書処理システム',
      ko: '자동 은행 명세서 처리 시스템',
      hi: 'स्वचालित बैंक स्टेटमेंट प्रोसेसिंग सिस्टम',
      nl: 'Automatisch bankrekeningverwerkingssysteem',
      sv: 'Automatiskt system för behandling av kontoutdrag',
      vi: 'Hệ thống xử lý sao kê ngân hàng tự động',
      id: 'Sistem pemrosesan rekening koran otomatis',
    }),
    skipToContent: t({
      ru: 'Перейти к содержимому',
      en: 'Skip to content',
      kk: 'Мазмұнға өту',
      de: 'Zum Inhalt springen',
      fr: 'Aller au contenu',
      es: 'Saltar al contenido',
      pt: 'Pular para o conteúdo',
      tr: 'İçeriğe geç',
      uk: 'Перейти до вмісту',
      zh: '跳到主要内容',
      ar: 'انتقل إلى المحتوى',
      pl: 'Przejdź do treści',
      it: 'Vai al contenuto',
      sk: 'Preskočiť na obsah',
      ja: 'コンテンツへスキップ',
      ko: '본문으로 건너뛰기',
      hi: 'सामग्री पर जाएं',
      nl: 'Naar inhoud springen',
      sv: 'Hoppa till innehållet',
      vi: 'Chuyển đến nội dung',
      id: 'Lewati ke konten',
    }),
  },
} satisfies Dictionary;

export default content;
