import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'notFoundPage',
  content: {
    title: t({
      ru: 'Ошибка при загрузке страницы',
      en: 'Could not load this page',
      kk: 'Бетті жүктеу кезінде қате',
      de: 'Die Seite konnte nicht geladen werden',
      fr: 'Impossible de charger cette page',
      es: 'No se pudo cargar esta página',
      pt: 'Não foi possível carregar esta página',
      tr: 'Bu sayfa yüklenemedi',
      uk: 'Помилка під час завантаження сторінки',
      zh: '无法加载此页面',
      ar: 'تعذّر تحميل هذه الصفحة',
      pl: 'Nie udało się wczytać tej strony',
      it: 'Impossibile caricare questa pagina',
      sk: 'Túto stránku sa nepodarilo načítať',
      ja: 'このページを読み込めませんでした',
      ko: '이 페이지를 불러올 수 없습니다',
      hi: 'यह पेज लोड नहीं हो सका',
      nl: 'Deze pagina kon niet worden geladen',
      sv: 'Sidan kunde inte läsas in',
      vi: 'Không thể tải trang này',
      id: 'Halaman ini tidak dapat dimuat',
      da: 'Siden kunne ikke indlæses',
      nb: 'Kunne ikke laste denne siden',
      nn: 'Kunne ikkje laste denne sida',
      fi: 'Tämän sivun lataus ei onnistunut',
      is: 'Ekki tókst að hlaða þessa síðu',
      fo: 'Henda síða kundi ikki lesast inn',
      cs: 'Tuto stránku se nepodařilo načíst',
      bg: 'Тази страница не можа да се зареди',
      hr: 'Ovu stranicu nije bilo moguće učitati',
      sr: 'Ову страницу није било могуће учитати',
      sl: 'Te strani ni bilo mogoče naložiti',
      mk: 'Оваа страница не можеше да се вчита',
      be: 'Не ўдалося загрузіць гэтую сторонку',
      bs: 'Ovu stranicu nije bilo moguće učitati',
      hsb: 'Tuta strona njeda so začitać',
    }),
    description: t({
      ru: 'Такой страницы нет, или ссылка устарела. Если вы думаете, что это ошибка, свяжитесь со мной:',
      en: 'This page does not exist, or the link is out of date. If you think this is a mistake, get in touch:',
      kk: 'Мұндай бет жоқ немесе сілтеме ескірген. Қате деп ойласаңыз, менімен байланысыңыз:',
      de: 'Diese Seite gibt es nicht, oder der Link ist veraltet. Wenn Sie einen Fehler vermuten, schreiben Sie mir:',
      fr: 'Cette page n’existe pas ou le lien est périmé. Si vous pensez qu’il s’agit d’une erreur, contactez-moi :',
      es: 'Esta página no existe o el enlace está desactualizado. Si crees que es un error, escríbeme:',
      pt: 'Esta página não existe ou o link está desatualizado. Se acha que é um erro, fale comigo:',
      tr: 'Böyle bir sayfa yok ya da bağlantı eskimiş. Bunun bir hata olduğunu düşünüyorsanız bana yazın:',
      uk: 'Такої сторінки немає, або посилання застаріло. Якщо ви вважаєте, що це помилка, зв’яжіться зі мною:',
      zh: '该页面不存在，或链接已失效。如果你认为这是个错误，请联系我：',
      ar: 'هذه الصفحة غير موجودة أو أن الرابط قديم. إذا كنت تظن أن هذا خطأ، تواصل معي:',
      pl: 'Taka strona nie istnieje albo link jest nieaktualny. Jeśli uważasz, że to błąd, napisz do mnie:',
      it: 'Questa pagina non esiste o il link non è più valido. Se pensi che sia un errore, scrivimi:',
      sk: 'Taká stránka neexistuje alebo je odkaz zastaraný. Ak si myslíte, že ide o chybu, napíšte mi:',
      ja: 'このページは存在しないか、リンクが古くなっています。不具合だと思われる場合はご連絡ください：',
      ko: '존재하지 않는 페이지이거나 링크가 오래되었습니다. 오류라고 생각되면 연락해 주세요:',
      hi: 'यह पेज मौजूद नहीं है या लिंक पुराना है। अगर आपको लगता है कि यह गलती है, तो मुझसे संपर्क करें:',
      nl: 'Deze pagina bestaat niet of de link is verouderd. Denk je dat dit een fout is, neem dan contact op:',
      sv: 'Sidan finns inte eller så är länken inaktuell. Om du tror att det är ett fel, hör av dig:',
      vi: 'Trang này không tồn tại hoặc liên kết đã cũ. Nếu bạn cho rằng đây là lỗi, hãy liên hệ với tôi:',
      id: 'Halaman ini tidak ada atau tautannya sudah usang. Jika menurut Anda ini kesalahan, hubungi saya:',
      da: 'Denne side findes ikke, eller linket er forældet. Hvis du mener, at det er en fejl, kan du kontakte os:',
      nb: 'Denne siden finnes ikke, eller lenken er utdatert. Mener du at dette er en feil, kan du ta kontakt:',
      nn: 'Denne sida finst ikkje, eller lenka er utdatert. Meiner du at dette er ein feil, kan du ta kontakt:',
      fi: 'Tätä sivua ei ole, tai linkki on vanhentunut. Jos arvelet tämän olevan virhe, ota yhteyttä:',
      is: 'Þessi síða er ekki til, eða tengillinn er útrunninn. Ef þú telur þetta vera villu máttu hafa samband:',
      fo: 'Henda síða er ikki til, ella leinkjan er forðað. Heldur tú, at hetta er ein feilur, kanst tú seta tær í samband:',
      cs: 'Tato stránka neexistuje, nebo je odkaz zastaralý. Pokud si myslíte, že jde o chybu, napište nám:',
      bg: 'Тази страница не съществува или връзката е остаряла. Ако смятате, че това е грешка, свържете се с нас:',
      hr: 'Ova stranica ne postoji ili je veza zastarjela. Ako mislite da je ovo pogreška, javite nam se:',
      sr: 'Ова страница не постоји или је веза застарела. Ако мислите да је ово грешка, јавите нам се:',
      sl: 'Ta stran ne obstaja ali pa je povezava zastarela. Če menite, da je to napaka, nam sporočite:',
      mk: 'Оваа страница не постои или врската е застарена. Ако мислите дека ова е грешка, пишете ни:',
      be: 'Гэтай сторонкі не існуе, або сасылка састарэла. Калі вы думаеце, што гэта памылка, звярніцеся да нас:',
      bs: 'Ova stranica ne postoji ili je veza zastarjela. Ako mislite da je ovo greška, javite nam se:',
      hsb: 'Tuta strona njeeksistuje abo zwjazk je stary. Jeli měniće, zo je to zmylk, stajće so z nami do zwiska:',
    }),
    backHome: t({
      ru: 'Вернуться на главную',
      en: 'Back to home',
      kk: 'Басты бетке оралу',
      de: 'Zur Startseite',
      fr: 'Retour à l’accueil',
      es: 'Volver al inicio',
      pt: 'Voltar ao início',
      tr: 'Ana sayfaya dön',
      uk: 'Повернутися на головну',
      zh: '返回首页',
      ar: 'العودة إلى الرئيسية',
      pl: 'Wróć na stronę główną',
      it: 'Torna alla home',
      sk: 'Späť na úvod',
      ja: 'ホームに戻る',
      ko: '홈으로 돌아가기',
      hi: 'होम पर लौटें',
      nl: 'Terug naar home',
      sv: 'Tillbaka till start',
      vi: 'Về trang chủ',
      id: 'Kembali ke beranda',
      da: 'Tilbage til startsiden',
      nb: 'Tilbake til startsiden',
      nn: 'Tilbake til startsida',
      fi: 'Takaisin etusivulle',
      is: 'Til baka á forsíðu',
      fo: 'Aftur til forsíðu',
      cs: 'Zpět na úvod',
      bg: 'Към началната страница',
      hr: 'Natrag na početnu',
      sr: 'Назад на почетну',
      sl: 'Nazaj na začetno stran',
      mk: 'Назад на почетната',
      be: 'Назад на галоўную',
      bs: 'Natrag na početnu',
      hsb: 'Wróćo na startowu stronu',
    }),
  },
} satisfies Dictionary;

export default content;
