import { type DeclarationContent, t } from 'intlayer';

const adminTourContent = {
  key: 'admin-tour-content',
  content: {
    name: t({
      ru: 'Тур по админ-панели',
      en: 'Admin Panel Tour',
      kk: 'Әкімші панелі туры',
      de: 'Admin-Panel-Tour',
      fr: "Visite du panneau d'administration",
      es: 'Tour del panel de administración',
      pt: 'Tour do painel de administração',
      tr: 'Yönetici Paneli Turu',
      uk: 'Тур по адмін-панелі',
      zh: '管理面板导览',
      ar: 'جولة لوحة الإدارة',
      pl: 'Tour panelu administracyjnego',
      it: 'Tour del pannello di amministrazione',
      sk: 'Tour panelu administracyjnego',
      ja: 'Admin Panel Tour',
      ko: 'Admin Panel Tour',
      hi: 'Admin Panel Tour',
      nl: 'Admin Panel Tour',
      sv: 'Admin Panel Tour',
      vi: 'Admin Panel Tour',
      id: 'Admin Panel Tour',
    }),
    description: t({
      ru: 'Обзор административных инструментов',
      en: 'Overview of administrative tools',
      kk: 'Әкімшілік құралдарға шолу',
      de: 'Übersicht der Verwaltungswerkzeuge',
      fr: 'Aperçu des outils administratifs',
      es: 'Descripción general de las herramientas administrativas',
      pt: 'Visão geral das ferramentas administrativas',
      tr: 'Yönetim araçlarına genel bakış',
      uk: 'Огляд адміністративних інструментів',
      zh: '管理工具概览',
      ar: 'نظرة عامة على أدوات الإدارة',
      pl: 'Przegląd narzędzi administracyjnych',
      it: 'Panoramica degli strumenti di amministrazione',
      sk: 'Przegląd narzędzi administracyjnych',
      ja: 'Overview of administrative tools',
      ko: 'Overview of administrative tools',
      hi: 'Overview of administrative tools',
      nl: 'Overview of administrative tools',
      sv: 'Overview of administrative tools',
      vi: 'Overview of administrative tools',
      id: 'Overview of administrative tools',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Добро пожаловать в админ-панель',
          en: 'Welcome to Admin Panel',
          kk: 'Әкімші панеліне қош келдіңіз',
          de: 'Willkommen im Admin-Panel',
          fr: "Bienvenue dans le panneau d'administration",
          es: 'Bienvenido al panel de administración',
          pt: 'Bem-vindo ao painel de administração',
          tr: 'Yönetici Paneline Hoş Geldiniz',
          uk: 'Ласкаво просимо до адмін-панелі',
          zh: '欢迎使用管理面板',
          ar: 'مرحباً بك في لوحة الإدارة',
          pl: 'Witaj w panelu administracyjnym',
          it: 'Benvenuto nel pannello di amministrazione',
          sk: 'Witaj w panelu administracyjnym',
          ja: 'Welcome to Admin Panel',
          ko: 'Welcome to Admin Panel',
          hi: 'Welcome to Admin Panel',
          nl: 'Welcome to Admin Panel',
          sv: 'Welcome to Admin Panel',
          vi: 'Welcome to Admin Panel',
          id: 'Welcome to Admin Panel',
        }),
        description: t({
          ru: 'Админ-панель помогает просматривать системные данные, переходить к управлению пользователями и анализировать аудит действий.',
          en: 'The admin panel gives you access to system-level data, user management entry points, and audit review tools.',
          kk: 'Әкімші панелі жүйелік деректерді көруге, пайдаланушыларды басқару бөліміне өтуге және әрекеттер аудитін талдауға мүмкіндік береді.',
          de: 'Das Admin-Panel gibt Ihnen Zugang zu Systemdaten, Benutzerverwaltungs-Einstiegspunkten und Audit-Überprüfungstools.',
          fr: "Le panneau d'administration vous donne accès aux données système, aux points d'entrée de gestion des utilisateurs et aux outils d'audit.",
          es: 'El panel de administración le da acceso a datos del sistema, puntos de entrada de gestión de usuarios y herramientas de revisión de auditoría.',
          pt: 'O painel de administração dá acesso a dados do sistema, pontos de entrada de gerenciamento de usuários e ferramentas de revisão de auditoria.',
          tr: 'Yönetici paneli size sistem düzeyindeki verilere, kullanıcı yönetimi giriş noktalarına ve denetim inceleme araçlarına erişim sağlar.',
          uk: 'Адмін-панель надає доступ до системних даних, управління користувачами та інструментів аудиту дій.',
          zh: '管理面板为您提供系统级数据、用户管理入口和审计审查工具的访问权限。',
          ar: 'يمنحك لوحة الإدارة الوصول إلى البيانات على مستوى النظام ونقاط دخول إدارة المستخدمين وأدوات مراجعة التدقيق.',
          pl: 'Panel administracyjny daje dostęp do danych systemowych, punktów wejścia zarządzania użytkownikami i narzędzi przeglądu audytu.',
          it: 'Il pannello di amministrazione ti dà accesso ai dati di sistema, ai punti di accesso per la gestione degli utenti e agli strumenti di revisione audit.',
          sk: 'Panel administracyjny daje dostęp do danych systemowych, punktów wejścia zarządzania użytkownikami i narzędzi przeglądu audytu.',
          ja: 'The admin panel gives you access to system-level data, user management entry points, and audit review tools.',
          ko: 'The admin panel gives you access to system-level data, user management entry points, and audit review tools.',
          hi: 'The admin panel gives you access to system-level data, user management entry points, and audit review tools.',
          nl: 'The admin panel gives you access to system-level data, user management entry points, and audit review tools.',
          sv: 'The admin panel gives you access to system-level data, user management entry points, and audit review tools.',
          vi: 'The admin panel gives you access to system-level data, user management entry points, and audit review tools.',
          id: 'The admin panel gives you access to system-level data, user management entry points, and audit review tools.',
        }),
      },
      tabs: {
        title: t({
          ru: 'Основные вкладки',
          en: 'Main tabs',
          kk: 'Негізгі қойындылар',
          de: 'Hauptregisterkarten',
          fr: 'Onglets principaux',
          es: 'Pestañas principales',
          pt: 'Abas principais',
          tr: 'Ana sekmeler',
          uk: 'Основні вкладки',
          zh: '主要选项卡',
          ar: 'علامات التبويب الرئيسية',
          pl: 'Główne zakładki',
          it: 'Schede principali',
          sk: 'Główne zakładki',
          ja: 'Main tabs',
          ko: 'Main tabs',
          hi: 'Main tabs',
          nl: 'Main tabs',
          sv: 'Main tabs',
          vi: 'Main tabs',
          id: 'Main tabs',
        }),
        description: t({
          ru: 'Верхние вкладки переключают между журналом выписок, разделом пользователей и аудитом. Это основная навигация внутри админки.',
          en: 'These top tabs switch between statements log, users, and audit. They are the main navigation points inside the admin area.',
          kk: 'Жоғарғы қойындылар үзінділер журналы, пайдаланушылар және аудит арасында ауыстырады. Бұл әкімші аймағындағы негізгі навигация.',
          de: 'Diese oberen Registerkarten wechseln zwischen Kontoauszugsprotokoll, Benutzern und Audit. Sie sind die Hauptnavigationspunkte im Adminbereich.',
          fr: "Ces onglets du haut basculent entre le journal des relevés, les utilisateurs et l'audit. Ce sont les principaux points de navigation dans la zone d'administration.",
          es: 'Estas pestañas superiores cambian entre el registro de extractos, usuarios y auditoría. Son los principales puntos de navegación dentro del área de administración.',
          pt: 'Estas abas superiores alternam entre o registro de extratos, usuários e auditoria. São os principais pontos de navegação dentro da área de administração.',
          tr: 'Bu üst sekmeler ekstre günlüğü, kullanıcılar ve denetim arasında geçiş yapar. Admin alanındaki ana navigasyon noktalarıdır.',
          uk: 'Верхні вкладки перемикають між журналом виписок, розділом користувачів та аудитом. Це основна навігація всередині адмінки.',
          zh: '这些顶部选项卡在账单日志、用户和审计之间切换。它们是管理区域内的主要导航点。',
          ar: 'تتبدل علامات التبويب العلوية هذه بين سجل كشوف الحسابات والمستخدمين والتدقيق. وهي نقاط التنقل الرئيسية داخل منطقة الإدارة.',
          pl: 'Te górne zakładki przełączają między dziennikiem wyciągów, użytkownikami i audytem. Są to główne punkty nawigacji w obszarze administracyjnym.',
          it: "Queste schede superiori passano tra il registro degli estratti conto, gli utenti e l'audit. Sono i principali punti di navigazione nell'area admin.",
          sk: 'Te górne zakładki przełączają między dziennikiem wyciągów, użytkownikami i audytem. Są to główne punkty nawigacji w obszarze administracyjnym.',
          ja: 'These top tabs switch between statements log, users, and audit. They are the main navigation points inside the admin area.',
          ko: 'These top tabs switch between statements log, users, and audit. They are the main navigation points inside the admin area.',
          hi: 'These top tabs switch between statements log, users, and audit. They are the main navigation points inside the admin area.',
          nl: 'These top tabs switch between statements log, users, and audit. They are the main navigation points inside the admin area.',
          sv: 'These top tabs switch between statements log, users, and audit. They are the main navigation points inside the admin area.',
          vi: 'These top tabs switch between statements log, users, and audit. They are the main navigation points inside the admin area.',
          id: 'These top tabs switch between statements log, users, and audit. They are the main navigation points inside the admin area.',
        }),
      },
      statementsLog: {
        title: t({
          ru: 'Поиск по журналу выписок',
          en: 'Statements log search',
          kk: 'Үзінділер журналы бойынша іздеу',
          de: 'Kontoauszugsprotokoll-Suche',
          fr: 'Recherche dans le journal des relevés',
          es: 'Búsqueda en el registro de extractos',
          pt: 'Pesquisa no registro de extratos',
          tr: 'Ekstre günlüğü araması',
          uk: 'Пошук по журналу виписок',
          zh: '账单日志搜索',
          ar: 'البحث في سجل كشوف الحسابات',
          pl: 'Wyszukiwanie w dzienniku wyciągów',
          it: 'Ricerca nel registro degli estratti conto',
          sk: 'Wyszukiwanie w dzienniku wyciągów',
          ja: 'Statements log search',
          ko: 'Statements log search',
          hi: 'Statements log search',
          nl: 'Statements log search',
          sv: 'Statements log search',
          vi: 'Statements log search',
          id: 'Statements log search',
        }),
        description: t({
          ru: 'Через поиск можно быстро находить загруженные выписки по названию файла или банку и затем разбирать ошибки, повторную обработку или удаление.',
          en: 'Use this search to quickly find uploaded statements by file name or bank before reviewing errors, reprocessing, or deletion.',
          kk: 'Бұл іздеу арқылы жүктелген үзінділерді файл атауы немесе банк бойынша тез тауып, содан кейін қателерді, қайта өңдеуді немесе жоюды қарауға болады.',
          de: 'Verwenden Sie diese Suche, um hochgeladene Auszüge schnell nach Dateiname oder Bank zu finden, bevor Sie Fehler überprüfen, neu verarbeiten oder löschen.',
          fr: 'Utilisez cette recherche pour trouver rapidement les relevés téléchargés par nom de fichier ou banque avant de vérifier les erreurs, de retraiter ou de supprimer.',
          es: 'Use esta búsqueda para encontrar rápidamente extractos cargados por nombre de archivo o banco antes de revisar errores, reprocesar o eliminar.',
          pt: 'Use esta pesquisa para encontrar rapidamente extratos carregados por nome de arquivo ou banco antes de revisar erros, reprocessar ou excluir.',
          tr: 'Hataları incelemeden, yeniden işlemeden veya silmeden önce yüklenen ekstreleri dosya adına veya bankaya göre hızlıca bulmak için bu aramayı kullanın.',
          uk: 'Через пошук можна швидко знайти завантажені виписки за назвою файлу або банком, а потім розібратися з помилками, повторною обробкою або видаленням.',
          zh: '在审查错误、重新处理或删除之前，使用此搜索按文件名或银行快速找到已上传的账单。',
          ar: 'استخدم هذا البحث للعثور بسرعة على الكشوفات المرفوعة حسب اسم الملف أو البنك قبل مراجعة الأخطاء أو إعادة المعالجة أو الحذف.',
          pl: 'Użyj tego wyszukiwania, aby szybko znaleźć przesłane wyciągi według nazwy pliku lub banku przed przeglądaniem błędów, ponownym przetwarzaniem lub usuwaniem.',
          it: 'Usa questa ricerca per trovare rapidamente gli estratti conto caricati per nome file o banca prima di esaminare errori, rielaborare o eliminare.',
          sk: 'Użyj tego wyszukiwania, aby szybko znaleźć przesłane wyciągi według nazwy pliku lub banku przed przeglądaniem błędów, ponownym przetwarzaniem lub usuwaniem.',
          ja: 'Use this search to quickly find uploaded statements by file name or bank before reviewing errors, reprocessing, or deletion.',
          ko: 'Use this search to quickly find uploaded statements by file name or bank before reviewing errors, reprocessing, or deletion.',
          hi: 'Use this search to quickly find uploaded statements by file name or bank before reviewing errors, reprocessing, or deletion.',
          nl: 'Use this search to quickly find uploaded statements by file name or bank before reviewing errors, reprocessing, or deletion.',
          sv: 'Use this search to quickly find uploaded statements by file name or bank before reviewing errors, reprocessing, or deletion.',
          vi: 'Use this search to quickly find uploaded statements by file name or bank before reviewing errors, reprocessing, or deletion.',
          id: 'Use this search to quickly find uploaded statements by file name or bank before reviewing errors, reprocessing, or deletion.',
        }),
      },
      usersLink: {
        title: t({
          ru: 'Переход к пользователям',
          en: 'Open users management',
          kk: 'Пайдаланушылар бөліміне өту',
          de: 'Benutzerverwaltung öffnen',
          fr: 'Ouvrir la gestion des utilisateurs',
          es: 'Abrir gestión de usuarios',
          pt: 'Abrir gerenciamento de usuários',
          tr: 'Kullanıcı yönetimini aç',
          uk: 'Перехід до користувачів',
          zh: '打开用户管理',
          ar: 'فتح إدارة المستخدمين',
          pl: 'Otwórz zarządzanie użytkownikami',
          it: 'Apri gestione utenti',
          sk: 'Otwórz zarządzanie użytkownikami',
          ja: 'Open users management',
          ko: 'Open users management',
          hi: 'Open users management',
          nl: 'Open users management',
          sv: 'Open users management',
          vi: 'Open users management',
          id: 'Open users management',
        }),
        description: t({
          ru: 'Кнопка открывает отдельный административный экран управления пользователями, где доступны роли, статусы и права.',
          en: 'This button opens the dedicated admin users screen where roles, statuses, and permissions are managed.',
          kk: 'Бұл батырма рөлдер, күйлер және рұқсаттар басқарылатын бөлек әкімшілік пайдаланушылар экранын ашады.',
          de: 'Diese Schaltfläche öffnet den dedizierten Admin-Benutzerbildschirm, auf dem Rollen, Status und Berechtigungen verwaltet werden.',
          fr: "Ce bouton ouvre l'écran dédié aux utilisateurs admin où les rôles, statuts et permissions sont gérés.",
          es: 'Este botón abre la pantalla de administración de usuarios dedicada donde se gestionan roles, estados y permisos.',
          pt: 'Este botão abre a tela dedicada de administração de usuários onde funções, status e permissões são gerenciadas.',
          tr: 'Bu düğme, rollerin, durumların ve izinlerin yönetildiği özel yönetici kullanıcılar ekranını açar.',
          uk: 'Кнопка відкриває окремий адміністративний екран управління користувачами з ролями, статусами та правами.',
          zh: '此按钮打开专用的管理员用户界面，在那里管理角色、状态和权限。',
          ar: 'يفتح هذا الزر شاشة إدارة المستخدمين المخصصة حيث تُدار الأدوار والحالات والصلاحيات.',
          pl: 'Ten przycisk otwiera dedykowany ekran zarządzania użytkownikami admina, gdzie zarządzane są role, statusy i uprawnienia.',
          it: 'Questo pulsante apre la schermata dedicata agli utenti admin dove vengono gestiti ruoli, stati e permessi.',
          sk: 'Ten przycisk otwiera dedykowany ekran zarządzania użytkownikami admina, gdzie zarządzane są role, statusy i uprawnienia.',
          ja: 'This button opens the dedicated admin users screen where roles, statuses, and permissions are managed.',
          ko: 'This button opens the dedicated admin users screen where roles, statuses, and permissions are managed.',
          hi: 'This button opens the dedicated admin users screen where roles, statuses, and permissions are managed.',
          nl: 'This button opens the dedicated admin users screen where roles, statuses, and permissions are managed.',
          sv: 'This button opens the dedicated admin users screen where roles, statuses, and permissions are managed.',
          vi: 'This button opens the dedicated admin users screen where roles, statuses, and permissions are managed.',
          id: 'This button opens the dedicated admin users screen where roles, statuses, and permissions are managed.',
        }),
      },
      auditFilters: {
        title: t({
          ru: 'Фильтры аудита',
          en: 'Audit filters',
          kk: 'Аудит сүзгілері',
          de: 'Audit-Filter',
          fr: "Filtres d'audit",
          es: 'Filtros de auditoría',
          pt: 'Filtros de auditoria',
          tr: 'Denetim filtreleri',
          uk: 'Фільтри аудиту',
          zh: '审计筛选器',
          ar: 'فلاتر التدقيق',
          pl: 'Filtry audytu',
          it: 'Filtri di audit',
          sk: 'Filtry audytu',
          ja: 'Audit filters',
          ko: 'Audit filters',
          hi: 'Audit filters',
          nl: 'Audit filters',
          sv: 'Audit filters',
          vi: 'Audit filters',
          id: 'Audit filters',
        }),
        description: t({
          ru: 'В аудит-разделе фильтры помогают сузить список событий по сущности, пользователю, действию, severity и периоду времени.',
          en: 'In the audit section, these filters narrow events by entity, user, action, severity, and time range.',
          kk: 'Аудит бөлімінде бұл сүзгілер оқиғаларды мән, пайдаланушы, әрекет, severity және уақыт аралығы бойынша қысқартады.',
          de: 'Im Audit-Bereich grenzen diese Filter Ereignisse nach Entität, Benutzer, Aktion, Schweregrad und Zeitraum ein.',
          fr: "Dans la section d'audit, ces filtres réduisent les événements par entité, utilisateur, action, gravité et plage de temps.",
          es: 'En la sección de auditoría, estos filtros reducen los eventos por entidad, usuario, acción, gravedad y rango de tiempo.',
          pt: 'Na seção de auditoria, esses filtros restringem eventos por entidade, usuário, ação, severidade e intervalo de tempo.',
          tr: 'Denetim bölümünde bu filtreler olayları varlık, kullanıcı, eylem, önem düzeyi ve zaman aralığına göre daraltır.',
          uk: 'У розділі аудиту фільтри допомагають звузити список подій за сутністю, користувачем, дією, severity та часовим проміжком.',
          zh: '在审计部分，这些筛选器按实体、用户、操作、严重性和时间范围缩小事件范围。',
          ar: 'في قسم التدقيق تساعد هذه الفلاتر على تضييق الأحداث حسب الكيان والمستخدم والإجراء والخطورة والنطاق الزمني.',
          pl: 'W sekcji audytu filtry te zawężają zdarzenia według encji, użytkownika, akcji, ważności i zakresu czasu.',
          it: 'Nella sezione audit, questi filtri restringono gli eventi per entità, utente, azione, gravità e intervallo di tempo.',
          sk: 'W sekcji audytu filtry te zawężają zdarzenia według encji, użytkownika, akcji, ważności i zakresu czasu.',
          ja: 'In the audit section, these filters narrow events by entity, user, action, severity, and time range.',
          ko: 'In the audit section, these filters narrow events by entity, user, action, severity, and time range.',
          hi: 'In the audit section, these filters narrow events by entity, user, action, severity, and time range.',
          nl: 'In the audit section, these filters narrow events by entity, user, action, severity, and time range.',
          sv: 'In the audit section, these filters narrow events by entity, user, action, severity, and time range.',
          vi: 'In the audit section, these filters narrow events by entity, user, action, severity, and time range.',
          id: 'In the audit section, these filters narrow events by entity, user, action, severity, and time range.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'All set',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Pronto',
          tr: 'Hazır',
          uk: 'Готово',
          zh: '完成',
          ar: 'تم',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Gotowe',
          ja: 'All set',
          ko: 'All set',
          hi: 'All set',
          nl: 'All set',
          sv: 'All set',
          vi: 'All set',
          id: 'All set',
        }),
        description: t({
          ru: 'Теперь вы знаете базовую структуру админ-панели. Дальше можно перейти в нужную вкладку и работать уже с конкретными административными задачами.',
          en: 'You now know the basic structure of the admin panel. From here you can move into the right tab and work on the specific administrative task you need.',
          kk: 'Енді әкімші панелінің негізгі құрылымын білесіз. Осы жерден қажетті қойындыға өтіп, нақты әкімшілік міндетпен жұмыс істей аласыз.',
          de: 'Sie kennen jetzt die grundlegende Struktur des Admin-Panels. Von hier aus können Sie zur richtigen Registerkarte wechseln und an der spezifischen Verwaltungsaufgabe arbeiten.',
          fr: "Vous connaissez maintenant la structure de base du panneau d'administration. De là, vous pouvez aller dans le bon onglet et travailler sur la tâche administrative spécifique dont vous avez besoin.",
          es: 'Ahora conoce la estructura básica del panel de administración. Desde aquí puede ir a la pestaña correcta y trabajar en la tarea administrativa específica que necesita.',
          pt: 'Agora você conhece a estrutura básica do painel de administração. Daqui você pode ir para a aba certa e trabalhar na tarefa administrativa específica que precisa.',
          tr: 'Artık yönetici panelinin temel yapısını biliyorsunuz. Buradan doğru sekmeye geçip ihtiyacınız olan belirli yönetim görevi üzerinde çalışabilirsiniz.',
          uk: 'Тепер ви знаєте базову структуру адмін-панелі. Далі можна перейти до потрібної вкладки та працювати з конкретними адміністративними завданнями.',
          zh: '您现在了解了管理面板的基本结构。从这里可以进入正确的选项卡并处理所需的具体管理任务。',
          ar: 'أنت تعرف الآن الهيكل الأساسي للوحة الإدارة. من هنا يمكنك الانتقال إلى علامة التبويب الصحيحة والعمل على المهمة الإدارية المحددة التي تحتاجها.',
          pl: 'Znasz teraz podstawową strukturę panelu administracyjnego. Stąd możesz przejść do właściwej zakładki i pracować nad konkretnym zadaniem administracyjnym.',
          it: "Ora conosci la struttura di base del pannello di amministrazione. Da qui puoi spostarti nella scheda giusta e lavorare sull'attività amministrativa specifica di cui hai bisogno.",
          sk: 'Znasz teraz podstawową strukturę panelu administracyjnego. Stąd możesz przejść do właściwej zakładki i pracować nad konkretnym zadaniem administracyjnym.',
          ja: 'You now know the basic structure of the admin panel. From here you can move into the right tab and work on the specific administrative task you need.',
          ko: 'You now know the basic structure of the admin panel. From here you can move into the right tab and work on the specific administrative task you need.',
          hi: 'You now know the basic structure of the admin panel. From here you can move into the right tab and work on the specific administrative task you need.',
          nl: 'You now know the basic structure of the admin panel. From here you can move into the right tab and work on the specific administrative task you need.',
          sv: 'You now know the basic structure of the admin panel. From here you can move into the right tab and work on the specific administrative task you need.',
          vi: 'You now know the basic structure of the admin panel. From here you can move into the right tab and work on the specific administrative task you need.',
          id: 'You now know the basic structure of the admin panel. From here you can move into the right tab and work on the specific administrative task you need.',
        }),
      },
    },
  },
} satisfies DeclarationContent;

export default adminTourContent;
