import { type DeclarationContent, t } from 'intlayer';

const categoriesTourContent = {
  key: 'categories-tour-content',
  content: {
    name: t({
      ru: 'Тур по категориям',
      en: 'Categories Tour',
      kk: 'Санаттар туры',
      de: 'Kategorien-Tour',
      fr: 'Visite des catégories',
      es: 'Tour de categorías',
      pt: 'Tour de categorias',
      tr: 'Kategoriler Turu',
      uk: 'Тур по категоріях',
      zh: '分类导览',
      ar: 'جولة الفئات',
      pl: 'Tour kategorii',
      it: 'Tour delle categorie',
      sk: 'Tour kategorii',
      ja: 'カテゴリーツアー',
      ko: '카테고리 투어',
      hi: 'श्रेणियाँ यात्रा',
      nl: 'Categorieën Rondleiding',
      sv: 'Kategorier Tour',
      vi: 'Danh mục Tour',
      id: 'Kategori Tur',
    }),
    description: t({
      ru: 'Управление рабочими категориями',
      en: 'Manage workspace categories',
      kk: 'Жұмыс кеңістігі санаттарын басқару',
      de: 'Arbeitsbereichskategorien verwalten',
      fr: "Gérer les catégories de l'espace de travail",
      es: 'Gestionar categorías del espacio de trabajo',
      pt: 'Gerenciar categorias do espaço de trabalho',
      tr: 'Çalışma alanı kategorilerini yönet',
      uk: 'Управління категоріями робочого простору',
      zh: '管理工作区分类',
      ar: 'إدارة فئات مساحة العمل',
      pl: 'Zarządzaj kategoriami obszaru roboczego',
      it: "Gestisci le categorie dell'area di lavoro",
      sk: 'Zarządzaj kategoriami obszaru roboczego',
      ja: 'ワークスペースのカテゴリを管理する',
      ko: '작업공간 카테고리 관리',
      hi: 'कार्यस्थान श्रेणियां प्रबंधित करें',
      nl: 'Beheer werkruimtecategorieën',
      sv: 'Hantera arbetsytakategorier',
      vi: 'Quản lý danh mục không gian làm việc',
      id: 'Kelola kategori ruang kerja',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Добро пожаловать в категории',
          en: 'Welcome to Categories',
          kk: 'Санаттарға қош келдіңіз',
          de: 'Willkommen bei den Kategorien',
          fr: 'Bienvenue dans les catégories',
          es: 'Bienvenido a Categorías',
          pt: 'Bem-vindo às Categorias',
          tr: 'Kategorilere Hoş Geldiniz',
          uk: 'Ласкаво просимо до Категорій',
          zh: '欢迎使用分类',
          ar: 'مرحباً بك في الفئات',
          pl: 'Witaj w Kategoriach',
          it: 'Benvenuto nelle Categorie',
          sk: 'Witaj w Kategoriach',
          ja: 'カテゴリへようこそ',
          ko: '카테고리에 오신 것을 환영합니다',
          hi: 'श्रेणियों में आपका स्वागत है',
          nl: 'Welkom bij Categorieën',
          sv: 'Välkommen till kategorier',
          vi: 'Chào mừng đến với chuyên mục',
          id: 'Selamat datang di Kategori',
        }),
        description: t({
          ru: 'На этой странице вы управляете категориями рабочего пространства: создаете новые, ищете существующие и включаете или отключаете их для использования в системе.',
          en: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
          kk: 'Бұл бетте жұмыс кеңістігі санаттарын басқарасыз: жаңаларын жасайсыз, барларын іздейсіз және жүйеде қолдану үшін қосып не өшіресіз.',
          de: 'Auf dieser Seite verwalten Sie Arbeitsbereichskategorien: neue erstellen, vorhandene suchen und sie für die Verwendung im Produkt aktivieren oder deaktivieren.',
          fr: "Sur cette page, vous gérez les catégories de l'espace de travail : en créer de nouvelles, rechercher les existantes et les activer ou désactiver pour une utilisation dans le produit.",
          es: 'En esta página gestiona las categorías del espacio de trabajo: cree nuevas, busque las existentes y habilítelas o deshabilítelas para su uso en el producto.',
          pt: 'Nesta página você gerencia as categorias do espaço de trabalho: crie novas, pesquise as existentes e habilite ou desabilite-as para uso no produto.',
          tr: 'Bu sayfa çalışma alanı kategorilerini yönettiğiniz yerdir: yenilerini oluşturun, mevcutları arayın ve ürün genelinde kullanmak için etkinleştirin veya devre dışı bırakın.',
          uk: 'На цій сторінці ви управляєте категоріями робочого простору: створюєте нові, шукаєте існуючі та вмикаєте або вимикаєте їх для використання в системі.',
          zh: '在此页面，您管理工作区分类：创建新分类、搜索现有分类，以及启用或禁用它们在产品中的使用。',
          ar: 'في هذه الصفحة تدير فئات مساحة العمل: إنشاء فئات جديدة والبحث في الموجودة وتفعيلها أو تعطيلها للاستخدام في المنتج.',
          pl: 'Na tej stronie zarządzasz kategoriami obszaru roboczego: tworzysz nowe, szukasz istniejących i włączasz lub wyłączasz je do użytku w produkcie.',
          it: "In questa pagina gestisci le categorie dell'area di lavoro: crea nuove, cerca quelle esistenti e abilitale o disabilitale per l'uso nel prodotto.",
          sk: 'Na tej stronie zarządzasz kategoriami obszaru roboczego: tworzysz nowe, szukasz istniejących i włączasz lub wyłączasz je do użytku w produkcie.',
          ja: 'このページでは、ワークスペース カテゴリを管理します。新しいカテゴリの作成、既存のカテゴリの検索、製品全体での使用の有効化または無効化を行います。',
          ko: '이 페이지에서는 작업공간 카테고리를 관리합니다. 새 카테고리를 생성하고, 기존 카테고리를 검색하고, 제품 전체에서 사용할 수 있도록 활성화 또는 비활성화합니다.',
          hi: 'यह पृष्ठ वह स्थान है जहां आप कार्यस्थान श्रेणियां प्रबंधित करते हैं: नई श्रेणियां बनाएं, मौजूदा श्रेणियां खोजें, और पूरे उत्पाद में उपयोग के लिए उन्हें सक्षम या अक्षम करें।',
          nl: 'Op deze pagina beheert u werkruimtecategorieën: maak nieuwe, doorzoek bestaande categorieën en schakel ze in of uit voor gebruik in het hele product.',
          sv: 'Den här sidan är där du hanterar arbetsytekategorier: skapa nya, söka efter befintliga och aktivera eller inaktivera dem för användning i hela produkten.',
          vi: 'Trang này là nơi bạn quản lý các danh mục không gian làm việc: tạo danh mục mới, tìm kiếm danh mục hiện có và bật hoặc tắt chúng để sử dụng trên toàn bộ sản phẩm.',
          id: 'Halaman ini adalah tempat Anda mengelola kategori ruang kerja: membuat kategori baru, mencari kategori yang sudah ada, dan mengaktifkan atau menonaktifkannya untuk digunakan di seluruh produk.',
        }),
      },
      addButton: {
        title: t({
          ru: 'Добавить категорию',
          en: 'Add category',
          kk: 'Санат қосу',
          de: 'Kategorie hinzufügen',
          fr: 'Ajouter une catégorie',
          es: 'Agregar categoría',
          pt: 'Adicionar categoria',
          tr: 'Kategori ekle',
          uk: 'Додати категорію',
          zh: '添加分类',
          ar: 'إضافة فئة',
          pl: 'Dodaj kategorię',
          it: 'Aggiungi categoria',
          sk: 'Dodaj kategorię',
          ja: 'カテゴリを追加',
          ko: '카테고리 추가',
          hi: 'श्रेणी जोड़ें',
          nl: 'Categorie toevoegen',
          sv: 'Lägg till kategori',
          vi: 'Thêm danh mục',
          id: 'Tambahkan kategori',
        }),
        description: t({
          ru: 'Эта кнопка открывает форму создания категории. Используйте ее, когда нужно добавить новый способ группировки транзакций, файлов или данных.',
          en: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
          kk: 'Бұл батырма санат жасау формасын ашады. Оны транзакцияларды, файлдарды немесе байланысты деректерді жаңа түрде топтау қажет болғанда пайдаланыңыз.',
          de: 'Diese Schaltfläche öffnet das Formular zur Kategorieerstellung. Verwenden Sie es, wenn Sie eine neue Möglichkeit benötigen, Transaktionen, Dateien oder verwandte Daten zu gruppieren.',
          fr: "Ce bouton ouvre le formulaire de création de catégorie. Utilisez-le lorsque vous avez besoin d'un nouveau moyen de regrouper des transactions, des fichiers ou des données associées.",
          es: 'Este botón abre el formulario de creación de categoría. Úselo cuando necesite una nueva forma de agrupar transacciones, archivos o datos relacionados.',
          pt: 'Este botão abre o formulário de criação de categoria. Use-o quando precisar de uma nova forma de agrupar transações, arquivos ou dados relacionados.',
          tr: 'Bu düğme kategori oluşturma formunu açar. İşlemleri, dosyaları veya ilgili verileri gruplandırmanın yeni bir yoluna ihtiyaç duyduğunuzda kullanın.',
          uk: 'Ця кнопка відкриває форму створення категорії. Використовуйте її, коли потрібно додати новий спосіб групування транзакцій, файлів або даних.',
          zh: '此按钮打开分类创建表单。当您需要一种新的方式来对交易、文件或相关数据进行分组时使用它。',
          ar: 'يفتح هذا الزر نموذج إنشاء الفئة. استخدمه عندما تحتاج إلى طريقة جديدة لتجميع المعاملات أو الملفات أو البيانات ذات الصلة.',
          pl: 'Ten przycisk otwiera formularz tworzenia kategorii. Użyj go, gdy potrzebujesz nowego sposobu grupowania transakcji, plików lub powiązanych danych.',
          it: 'Questo pulsante apre il modulo di creazione della categoria. Usalo quando hai bisogno di un nuovo modo per raggruppare transazioni, file o dati correlati.',
          sk: 'Ten przycisk otwiera formularz tworzenia kategorii. Użyj go, gdy potrzebujesz nowego sposobu grupowania transakcji, plików lub powiązanych danych.',
          ja: 'このボタンをクリックすると、カテゴリ作成フォームが開きます。トランザクション、ファイル、または関連データをグループ化する新しい方法が必要な場合に使用します。',
          ko: '이 버튼을 누르면 카테고리 생성 양식이 열립니다. 트랜잭션, 파일 또는 관련 데이터를 그룹화하는 새로운 방법이 필요할 때 사용하세요.',
          hi: 'यह बटन श्रेणी निर्माण प्रपत्र खोलता है। जब आपको लेन-देन, फ़ाइलों या संबंधित डेटा को समूहीकृत करने के लिए नए तरीके की आवश्यकता हो तो इसका उपयोग करें।',
          nl: 'Deze knop opent het formulier voor het aanmaken van categorieën. Gebruik het wanneer u een nieuwe manier nodig heeft om transacties, bestanden of gerelateerde gegevens te groeperen.',
          sv: 'Den här knappen öppnar formuläret för att skapa kategori. Använd den när du behöver ett nytt sätt att gruppera transaktioner, filer eller relaterad data.',
          vi: 'Nút này mở biểu mẫu tạo danh mục. Hãy sử dụng nó khi bạn cần một cách mới để nhóm các giao dịch, tệp hoặc dữ liệu liên quan.',
          id: 'Tombol ini membuka formulir pembuatan kategori. Gunakan saat Anda memerlukan cara baru untuk mengelompokkan transaksi, file, atau data terkait.',
        }),
      },
      search: {
        title: t({
          ru: 'Поиск категории',
          en: 'Search categories',
          kk: 'Санаттарды іздеу',
          de: 'Kategorien suchen',
          fr: 'Rechercher des catégories',
          es: 'Buscar categorías',
          pt: 'Pesquisar categorias',
          tr: 'Kategori ara',
          uk: 'Пошук категорії',
          zh: '搜索分类',
          ar: 'البحث في الفئات',
          pl: 'Szukaj kategorii',
          it: 'Cerca categorie',
          sk: 'Szukaj kategorii',
          ja: 'カテゴリを検索する',
          ko: '카테고리 검색',
          hi: 'श्रेणियां खोजें',
          nl: 'Zoek categorieën',
          sv: 'Sök kategorier',
          vi: 'Tìm kiếm danh mục',
          id: 'Kategori pencarian',
        }),
        description: t({
          ru: 'Поиск помогает быстро находить нужные категории по названию, особенно если список уже большой и включает системные и пользовательские элементы.',
          en: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
          kk: 'Іздеу санатты атауы бойынша тез табуға көмектеседі, әсіресе тізімде жүйелік те, қолданушы жасаған элементтер де көп болғанда.',
          de: 'Die Suche hilft Ihnen, eine Kategorie schnell nach Namen zu finden, besonders wenn die Liste sowohl System- als auch benutzerdefinierte Einträge enthält.',
          fr: 'La recherche vous aide à localiser rapidement une catégorie par nom, surtout quand la liste inclut des entrées système et personnalisées.',
          es: 'La búsqueda le ayuda a localizar rápidamente una categoría por nombre, especialmente cuando la lista crece para incluir entradas del sistema y personalizadas.',
          pt: 'A pesquisa ajuda a localizar rapidamente uma categoria por nome, especialmente quando a lista cresce para incluir entradas do sistema e personalizadas.',
          tr: 'Arama, liste hem sistem hem de özel girişleri içerecek şekilde büyüdüğünde bir kategoriyi ada göre hızlıca bulmanıza yardımcı olur.',
          uk: 'Пошук допомагає швидко знайти потрібну категорію за назвою, особливо коли список уже великий і включає системні та користувацькі елементи.',
          zh: '搜索可帮助您按名称快速找到分类，尤其是当列表增长到包含系统和自定义条目时。',
          ar: 'يساعدك البحث على تحديد موقع فئة بسرعة حسب الاسم، خاصة عندما تنمو القائمة لتشمل إدخالات النظام والمخصصة.',
          pl: 'Wyszukiwanie pomaga szybko znaleźć kategorię według nazwy, zwłaszcza gdy lista rośnie i obejmuje zarówno wpisy systemowe, jak i niestandardowe.',
          it: 'La ricerca ti aiuta a trovare rapidamente una categoria per nome, specialmente quando la lista cresce per includere sia voci di sistema che personalizzate.',
          sk: 'Wyszukiwanie pomaga szybko znaleźć kategorię według nazwy, zwłaszcza gdy lista rośnie i obejmuje zarówno wpisy systemowe, jak i niestandardowe.',
          ja: '検索は、特にリストがシステム エントリとカスタム エントリの両方を含むようになった場合に、名前でカテゴリをすばやく見つけるのに役立ちます。',
          ko: '검색을 사용하면 특히 목록이 시스템 항목과 사용자 정의 항목을 모두 포함하도록 커질 때 이름별로 카테고리를 빠르게 찾을 수 있습니다.',
          hi: 'खोज आपको नाम के आधार पर किसी श्रेणी का शीघ्रता से पता लगाने में मदद करती है, विशेषकर तब जब सूची सिस्टम और कस्टम प्रविष्टियों दोनों को शामिल करने के लिए बढ़ जाती है।',
          nl: 'Met Zoeken kunt u snel een categorie op naam vinden, vooral als de lijst groeit en zowel systeem- als aangepaste vermeldingen bevat.',
          sv: 'Sökning hjälper dig att snabbt hitta en kategori efter namn, särskilt när listan växer och inkluderar både systemposter och anpassade poster.',
          vi: 'Tìm kiếm giúp bạn nhanh chóng định vị một danh mục theo tên, đặc biệt khi danh sách phát triển để bao gồm cả mục hệ thống và mục tùy chỉnh.',
          id: 'Pencarian membantu Anda dengan cepat menemukan kategori berdasarkan nama, terutama setelah daftar bertambah hingga mencakup entri sistem dan kustom.',
        }),
      },
      categoriesList: {
        title: t({
          ru: 'Список категорий',
          en: 'Categories list',
          kk: 'Санаттар тізімі',
          de: 'Kategorieliste',
          fr: 'Liste des catégories',
          es: 'Lista de categorías',
          pt: 'Lista de categorias',
          tr: 'Kategoriler listesi',
          uk: 'Список категорій',
          zh: '分类列表',
          ar: 'قائمة الفئات',
          pl: 'Lista kategorii',
          it: 'Elenco categorie',
          sk: 'Lista kategorii',
          ja: 'カテゴリ一覧',
          ko: '카테고리 목록',
          hi: 'श्रेणियाँ सूची',
          nl: 'Categorieën lijst',
          sv: 'Lista över kategorier',
          vi: 'Danh sách danh mục',
          id: 'Daftar kategori',
        }),
        description: t({
          ru: 'Здесь показаны все категории с их названием, статусом использования и служебными метками. Это основная область для обзора и управления списком.',
          en: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
          kk: 'Мұнда әр санат атауымен, қолданылу күйімен және жүйелік белгілерімен бірге көрсетіледі. Бұл толық тізімді қарап, басқаруға арналған негізгі аймақ.',
          de: 'Diese Liste zeigt jede Kategorie mit ihrem Namen, Nutzungsstatus und Systemabzeichen. Es ist der Hauptbereich für das Überprüfen und Verwalten aller Kategorien.',
          fr: "Cette liste affiche chaque catégorie avec son nom, son état d'utilisation et ses badges système. C'est la zone principale pour examiner et gérer l'ensemble complet.",
          es: 'Esta lista muestra cada categoría con su nombre, estado de uso e insignias del sistema. Es el área principal para revisar y gestionar el conjunto completo.',
          pt: 'Esta lista mostra cada categoria com seu nome, estado de uso e badges do sistema. É a área principal para revisar e gerenciar o conjunto completo.',
          tr: 'Bu liste her kategoriyi adı, kullanım durumu ve sistem rozetleriyle gösterir. Tam seti incelemek ve yönetmek için ana alandır.',
          uk: 'Тут показані всі категорії з їх назвою, статусом використання та службовими мітками. Це основна область для перегляду та управління списком.',
          zh: '此列表显示每个分类的名称、使用状态和系统徽章。这是查看和管理完整集合的主要区域。',
          ar: 'تعرض هذه القائمة كل فئة باسمها وحالة الاستخدام وشارات النظام. إنها المنطقة الرئيسية لمراجعة المجموعة الكاملة وإدارتها.',
          pl: 'Ta lista pokazuje każdą kategorię z jej nazwą, stanem użycia i odznaczeniami systemowymi. Jest to główny obszar do przeglądania i zarządzania pełnym zestawem.',
          it: "Questo elenco mostra ogni categoria con il suo nome, stato di utilizzo e badge di sistema. È l'area principale per esaminare e gestire l'intero insieme.",
          sk: 'Ta lista pokazuje każdą kategorię z jej nazwą, stanem użycia i odznaczeniami systemowymi. Jest to główny obszar do przeglądania i zarządzania pełnym zestawem.',
          ja: 'このリストには、すべてのカテゴリとその名前、使用状況、およびシステム バッジが表示されます。これは、フルセットをレビューおよび管理するためのメインエリアです。',
          ko: '이 목록에는 이름, 사용 상태 및 시스템 배지와 함께 모든 범주가 표시됩니다. 전체 세트를 검토하고 관리하는 주요 영역입니다.',
          hi: 'यह सूची प्रत्येक श्रेणी को उसके नाम, उपयोग की स्थिति और सिस्टम बैज के साथ दिखाती है। यह संपूर्ण सेट की समीक्षा और प्रबंधन का मुख्य क्षेत्र है।',
          nl: 'Deze lijst toont elke categorie met zijn naam, gebruiksstatus en systeembadges. Het is het belangrijkste gebied voor het beoordelen en beheren van de volledige set.',
          sv: 'Den här listan visar varje kategori med dess namn, användningstillstånd och systemmärken. Det är huvudområdet för att granska och hantera hela uppsättningen.',
          vi: 'Danh sách này hiển thị mọi danh mục cùng với tên, trạng thái sử dụng và huy hiệu hệ thống. Đây là khu vực chính để xem xét và quản lý toàn bộ.',
          id: 'Daftar ini menampilkan setiap kategori beserta namanya, status penggunaan, dan lencana sistemnya. Ini adalah area utama untuk meninjau dan mengelola set lengkap.',
        }),
      },
      categoryToggle: {
        title: t({
          ru: 'Включение и отключение',
          en: 'Enable or disable',
          kk: 'Қосу немесе өшіру',
          de: 'Aktivieren oder deaktivieren',
          fr: 'Activer ou désactiver',
          es: 'Habilitar o deshabilitar',
          pt: 'Habilitar ou desabilitar',
          tr: 'Etkinleştir veya devre dışı bırak',
          uk: 'Увімкнення та вимкнення',
          zh: '启用或禁用',
          ar: 'تفعيل أو تعطيل',
          pl: 'Włącz lub wyłącz',
          it: 'Abilita o disabilita',
          sk: 'Włącz lub wyłącz',
          ja: '有効または無効にする',
          ko: '활성화 또는 비활성화',
          hi: 'सक्षम या अक्षम करें',
          nl: 'In- of uitschakelen',
          sv: 'Aktivera eller inaktivera',
          vi: 'Bật hoặc tắt',
          id: 'Aktifkan atau nonaktifkan',
        }),
        description: t({
          ru: 'Переключатель управляет доступностью категории в интерфейсах выписок и отчетов. Если конкретной строки нет, тур пропустит этот шаг без ошибки.',
          en: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
          kk: 'Бұл ауыстырғыш санаттың үзінділер мен есептер интерфейсінде қолжетімді болуын басқарады. Егер тиісті жол қазір көрінбесе, тур бұл қадамды қате шығармай өткізіп жібереді.',
          de: 'Dieser Schalter steuert, ob eine Kategorie in Auszügen und Berichtsabläufen verfügbar bleibt. Wenn keine Kategoriezeile sichtbar ist, überspringt die Tour diesen Schritt sicher.',
          fr: "Cette bascule contrôle si une catégorie reste disponible dans les flux de relevés et de rapports. Si aucune ligne de catégorie n'est visible, la visite saute cette étape en toute sécurité.",
          es: 'Este interruptor controla si una categoría permanece disponible en los flujos de extractos e informes. Si no hay ninguna fila de categoría visible, el tour omite este paso de forma segura.',
          pt: 'Este toggle controla se uma categoria permanece disponível nos fluxos de extratos e relatórios. Se nenhuma linha de categoria estiver visível, o tour pula esta etapa com segurança.',
          tr: 'Bu geçiş, bir kategorinin ekstre ve raporlama akışlarında mevcut kalıp kalmadığını kontrol eder. Hiçbir kategori satırı görünmüyorsa tur bu adımı güvenli bir şekilde atlar.',
          uk: 'Перемикач керує доступністю категорії в інтерфейсах виписок та звітів. Якщо відповідного рядка немає, тур пропустить цей крок без помилки.',
          zh: '此开关控制分类是否在账单和报告流程中保持可用。如果当前没有可见的分类行，导览将安全跳过此步骤。',
          ar: 'يتحكم هذا المفتاح في ما إذا كانت الفئة تبقى متاحة في سير عمل كشوف الحسابات والتقارير. إذا لم يكن صف الفئة مرئياً حالياً، تتخطى الجولة هذه الخطوة بأمان.',
          pl: 'Ten przełącznik kontroluje, czy kategoria pozostaje dostępna w przepływach wyciągów i raportów. Jeśli żaden wiersz kategorii nie jest widoczny, przewodnik bezpiecznie pomija ten krok.',
          it: 'Questo toggle controlla se una categoria rimane disponibile nei flussi di estratti conto e reportistica. Se non è visibile nessuna riga di categoria, il tour salta questo passaggio in modo sicuro.',
          sk: 'Ten przełącznik kontroluje, czy kategoria pozostaje dostępna w przepływach wyciągów i raportów. Jeśli żaden wiersz kategorii nie jest widoczny, przewodnik bezpiecznie pomija ten krok.',
          ja: 'この切り替えは、カテゴリをステートメントおよびレポート フローで引き続き使用できるかどうかを制御します。現在表示されているカテゴリ行がない場合、ツアーはこのステップを安全にスキップします。',
          ko: '이 토글은 명세서 및 보고 흐름에서 카테고리를 계속 사용할 수 있는지 여부를 제어합니다. 현재 카테고리 행이 표시되지 않으면 둘러보기에서는 이 단계를 안전하게 건너뜁니다.',
          hi: 'यह टॉगल नियंत्रित करता है कि कोई श्रेणी कथनों और रिपोर्टिंग प्रवाहों में उपलब्ध रहती है या नहीं। यदि वर्तमान में कोई श्रेणी पंक्ति दिखाई नहीं दे रही है, तो टूर इस चरण को सुरक्षित रूप से छोड़ देता है।',
          nl: 'Met deze schakelaar bepaalt u of een categorie beschikbaar blijft in overzichten en rapportagestromen. Als er momenteel geen categorierij zichtbaar is, slaat de tour deze stap veilig over.',
          sv: 'Denna växling styr om en kategori förblir tillgänglig i uttalanden och rapporteringsflöden. Om ingen kategorirad för närvarande är synlig, hoppar rundturen över detta steg på ett säkert sätt.',
          vi: 'Nút chuyển đổi này kiểm soát xem một danh mục có sẵn dùng trong báo cáo và luồng báo cáo hay không. Nếu hiện tại không có hàng danh mục nào hiển thị thì chuyến tham quan sẽ bỏ qua bước này một cách an toàn.',
          id: 'Tombol ini mengontrol apakah suatu kategori tetap tersedia dalam laporan dan alur pelaporan. Jika tidak ada baris kategori yang terlihat, tur akan melewati langkah ini dengan aman.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'All set',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Pronto',
          tr: 'Hazır',
          uk: 'Готово',
          zh: '完成',
          ar: 'تم',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Gotowe',
          ja: '準備完了',
          ko: '모든 세트',
          hi: 'सब तैयार',
          nl: 'Helemaal klaar',
          sv: 'Allt klart',
          vi: 'Đã hoàn tất',
          id: 'Semua siap',
        }),
        description: t({
          ru: 'Теперь вы знаете, где создавать, искать и переключать категории рабочего пространства. Дальше можно открыть нужную категорию и настроить ее подробнее.',
          en: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
          kk: 'Енді жұмыс кеңістігі санаттарын қайдан жасау, табу және ауыстыру керегін білесіз. Келесі қадамда қажетті санатты ашып, оны тереңірек баптай аласыз.',
          de: 'Sie wissen jetzt, wo Sie Arbeitsbereichskategorien erstellen, finden und umschalten können. Von hier aus können Sie die richtige Kategorie öffnen und weiter verfeinern.',
          fr: "Vous savez maintenant où créer, trouver et basculer les catégories de l'espace de travail. De là vous pouvez ouvrir la bonne catégorie et l'affiner davantage.",
          es: 'Ahora sabe dónde crear, encontrar y alternar las categorías del espacio de trabajo. Desde aquí puede abrir la categoría correcta y refinarla más.',
          pt: 'Agora você sabe onde criar, encontrar e alternar as categorias do espaço de trabalho. Daqui pode abrir a categoria certa e refiná-la ainda mais.',
          tr: 'Artık çalışma alanı kategorilerini nerede oluşturacağınızı, bulacağınızı ve değiştireceğinizi biliyorsunuz. Buradan doğru kategoriyi açıp daha da geliştirebilirsiniz.',
          uk: 'Тепер ви знаєте, де створювати, шукати та перемикати категорії робочого простору. Далі можна відкрити потрібну категорію та налаштувати її детальніше.',
          zh: '您现在知道在哪里创建、查找和切换工作区分类。从这里可以打开正确的分类并进一步完善它。',
          ar: 'أنت تعرف الآن أين تنشئ وتجد وتبدّل فئات مساحة العمل. من هنا يمكنك فتح الفئة الصحيحة وتحسينها أكثر.',
          pl: 'Teraz wiesz, gdzie tworzyć, znajdować i przełączać kategorie obszaru roboczego. Stąd możesz otworzyć właściwą kategorię i dopracować ją dalej.',
          it: "Ora sai dove creare, trovare e attivare/disattivare le categorie dell'area di lavoro. Da qui puoi aprire la categoria giusta e perfezionarla ulteriormente.",
          sk: 'Teraz wiesz, gdzie tworzyć, znajdować i przełączać kategorie obszaru roboczego. Stąd możesz otworzyć właściwą kategorię i dopracować ją dalej.',
          ja: 'これで、ワークスペース カテゴリを作成、検索、切り替えられる場所がわかりました。ここから、適切なカテゴリを開いてさらに絞り込むことができます。',
          ko: '이제 작업공간 범주를 생성하고 찾고 전환하는 위치를 알았습니다. 여기에서 올바른 카테고리를 열고 더 세부적으로 분류할 수 있습니다.',
          hi: 'अब आप जानते हैं कि कार्यक्षेत्र श्रेणियाँ कहाँ बनानी, ढूँढनी और टॉगल करनी हैं। यहां से आप सही कैटेगरी को खोल सकते हैं और उसे और परिष्कृत कर सकते हैं।',
          nl: 'U weet nu waar u werkruimtecategorieën kunt maken, vinden en schakelen. Vanaf hier kunt u de juiste categorie openen en verder verfijnen.',
          sv: 'Du vet nu var du ska skapa, hitta och växla arbetsytekategorier. Härifrån kan du öppna rätt kategori och förfina den ytterligare.',
          vi: 'Bây giờ bạn đã biết nơi tạo, tìm và chuyển đổi các danh mục không gian làm việc. Từ đây bạn có thể mở danh mục phù hợp và tinh chỉnh thêm.',
          id: 'Anda sekarang tahu di mana membuat, menemukan, dan beralih kategori ruang kerja. Dari sini Anda dapat membuka kategori yang tepat dan menyempurnakannya lebih lanjut.',
        }),
      },
    },
  },
} satisfies DeclarationContent;

export default categoriesTourContent;
