import { type DeclarationContent, t } from 'intlayer';

const categoriesTourContent = {
  key: 'categories-tour-content',
  content: {
    name: t({
      ru: 'Тур по категориям',
      en: 'Categories Tour',
      kk: 'Санаттар туры',
      de: 'Kategorien-Tour',
      fr: 'Visite des catégories',
      es: 'Tour de categorías',
      pt: 'Tour de categorias',
      tr: 'Kategoriler Turu',
      uk: 'Тур по категоріях',
      zh: '分类导览',
      ar: 'جولة الفئات',
      pl: 'Tour kategorii',
      it: 'Tour delle categorie',
      sk: 'Tour kategorii',
      ja: 'Categories Tour',
      ko: 'Categories Tour',
      hi: 'Categories Tour',
      nl: 'Categories Tour',
      sv: 'Categories Tour',
      vi: 'Categories Tour',
      id: 'Categories Tour',
    }),
    description: t({
      ru: 'Управление рабочими категориями',
      en: 'Manage workspace categories',
      kk: 'Жұмыс кеңістігі санаттарын басқару',
      de: 'Arbeitsbereichskategorien verwalten',
      fr: "Gérer les catégories de l'espace de travail",
      es: 'Gestionar categorías del espacio de trabajo',
      pt: 'Gerenciar categorias do espaço de trabalho',
      tr: 'Çalışma alanı kategorilerini yönet',
      uk: 'Управління категоріями робочого простору',
      zh: '管理工作区分类',
      ar: 'إدارة فئات مساحة العمل',
      pl: 'Zarządzaj kategoriami obszaru roboczego',
      it: "Gestisci le categorie dell'area di lavoro",
      sk: 'Zarządzaj kategoriami obszaru roboczego',
      ja: 'Manage workspace categories',
      ko: 'Manage workspace categories',
      hi: 'Manage workspace categories',
      nl: 'Manage workspace categories',
      sv: 'Manage workspace categories',
      vi: 'Manage workspace categories',
      id: 'Manage workspace categories',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Добро пожаловать в категории',
          en: 'Welcome to Categories',
          kk: 'Санаттарға қош келдіңіз',
          de: 'Willkommen bei den Kategorien',
          fr: 'Bienvenue dans les catégories',
          es: 'Bienvenido a Categorías',
          pt: 'Bem-vindo às Categorias',
          tr: 'Kategorilere Hoş Geldiniz',
          uk: 'Ласкаво просимо до Категорій',
          zh: '欢迎使用分类',
          ar: 'مرحباً بك في الفئات',
          pl: 'Witaj w Kategoriach',
          it: 'Benvenuto nelle Categorie',
          sk: 'Witaj w Kategoriach',
          ja: 'Welcome to Categories',
          ko: 'Welcome to Categories',
          hi: 'Welcome to Categories',
          nl: 'Welcome to Categories',
          sv: 'Welcome to Categories',
          vi: 'Welcome to Categories',
          id: 'Welcome to Categories',
        }),
        description: t({
          ru: 'На этой странице вы управляете категориями рабочего пространства: создаете новые, ищете существующие и включаете или отключаете их для использования в системе.',
          en: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
          kk: 'Бұл бетте жұмыс кеңістігі санаттарын басқарасыз: жаңаларын жасайсыз, барларын іздейсіз және жүйеде қолдану үшін қосып не өшіресіз.',
          de: 'Auf dieser Seite verwalten Sie Arbeitsbereichskategorien: neue erstellen, vorhandene suchen und sie für die Verwendung im Produkt aktivieren oder deaktivieren.',
          fr: "Sur cette page, vous gérez les catégories de l'espace de travail : en créer de nouvelles, rechercher les existantes et les activer ou désactiver pour une utilisation dans le produit.",
          es: 'En esta página gestiona las categorías del espacio de trabajo: cree nuevas, busque las existentes y habilítelas o deshabilítelas para su uso en el producto.',
          pt: 'Nesta página você gerencia as categorias do espaço de trabalho: crie novas, pesquise as existentes e habilite ou desabilite-as para uso no produto.',
          tr: 'Bu sayfa çalışma alanı kategorilerini yönettiğiniz yerdir: yenilerini oluşturun, mevcutları arayın ve ürün genelinde kullanmak için etkinleştirin veya devre dışı bırakın.',
          uk: 'На цій сторінці ви управляєте категоріями робочого простору: створюєте нові, шукаєте існуючі та вмикаєте або вимикаєте їх для використання в системі.',
          zh: '在此页面，您管理工作区分类：创建新分类、搜索现有分类，以及启用或禁用它们在产品中的使用。',
          ar: 'في هذه الصفحة تدير فئات مساحة العمل: إنشاء فئات جديدة والبحث في الموجودة وتفعيلها أو تعطيلها للاستخدام في المنتج.',
          pl: 'Na tej stronie zarządzasz kategoriami obszaru roboczego: tworzysz nowe, szukasz istniejących i włączasz lub wyłączasz je do użytku w produkcie.',
          it: "In questa pagina gestisci le categorie dell'area di lavoro: crea nuove, cerca quelle esistenti e abilitale o disabilitale per l'uso nel prodotto.",
          sk: 'Na tej stronie zarządzasz kategoriami obszaru roboczego: tworzysz nowe, szukasz istniejących i włączasz lub wyłączasz je do użytku w produkcie.',
          ja: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
          ko: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
          hi: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
          nl: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
          sv: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
          vi: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
          id: 'This page is where you manage workspace categories: create new ones, search existing ones, and enable or disable them for use across the product.',
        }),
      },
      addButton: {
        title: t({
          ru: 'Добавить категорию',
          en: 'Add category',
          kk: 'Санат қосу',
          de: 'Kategorie hinzufügen',
          fr: 'Ajouter une catégorie',
          es: 'Agregar categoría',
          pt: 'Adicionar categoria',
          tr: 'Kategori ekle',
          uk: 'Додати категорію',
          zh: '添加分类',
          ar: 'إضافة فئة',
          pl: 'Dodaj kategorię',
          it: 'Aggiungi categoria',
          sk: 'Dodaj kategorię',
          ja: 'Add category',
          ko: 'Add category',
          hi: 'Add category',
          nl: 'Add category',
          sv: 'Add category',
          vi: 'Add category',
          id: 'Add category',
        }),
        description: t({
          ru: 'Эта кнопка открывает форму создания категории. Используйте ее, когда нужно добавить новый способ группировки транзакций, файлов или данных.',
          en: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
          kk: 'Бұл батырма санат жасау формасын ашады. Оны транзакцияларды, файлдарды немесе байланысты деректерді жаңа түрде топтау қажет болғанда пайдаланыңыз.',
          de: 'Diese Schaltfläche öffnet das Formular zur Kategorieerstellung. Verwenden Sie es, wenn Sie eine neue Möglichkeit benötigen, Transaktionen, Dateien oder verwandte Daten zu gruppieren.',
          fr: "Ce bouton ouvre le formulaire de création de catégorie. Utilisez-le lorsque vous avez besoin d'un nouveau moyen de regrouper des transactions, des fichiers ou des données associées.",
          es: 'Este botón abre el formulario de creación de categoría. Úselo cuando necesite una nueva forma de agrupar transacciones, archivos o datos relacionados.',
          pt: 'Este botão abre o formulário de criação de categoria. Use-o quando precisar de uma nova forma de agrupar transações, arquivos ou dados relacionados.',
          tr: 'Bu düğme kategori oluşturma formunu açar. İşlemleri, dosyaları veya ilgili verileri gruplandırmanın yeni bir yoluna ihtiyaç duyduğunuzda kullanın.',
          uk: 'Ця кнопка відкриває форму створення категорії. Використовуйте її, коли потрібно додати новий спосіб групування транзакцій, файлів або даних.',
          zh: '此按钮打开分类创建表单。当您需要一种新的方式来对交易、文件或相关数据进行分组时使用它。',
          ar: 'يفتح هذا الزر نموذج إنشاء الفئة. استخدمه عندما تحتاج إلى طريقة جديدة لتجميع المعاملات أو الملفات أو البيانات ذات الصلة.',
          pl: 'Ten przycisk otwiera formularz tworzenia kategorii. Użyj go, gdy potrzebujesz nowego sposobu grupowania transakcji, plików lub powiązanych danych.',
          it: 'Questo pulsante apre il modulo di creazione della categoria. Usalo quando hai bisogno di un nuovo modo per raggruppare transazioni, file o dati correlati.',
          sk: 'Ten przycisk otwiera formularz tworzenia kategorii. Użyj go, gdy potrzebujesz nowego sposobu grupowania transakcji, plików lub powiązanych danych.',
          ja: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
          ko: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
          hi: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
          nl: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
          sv: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
          vi: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
          id: 'This button opens the category creation form. Use it when you need a new way to group transactions, files, or related data.',
        }),
      },
      search: {
        title: t({
          ru: 'Поиск категории',
          en: 'Search categories',
          kk: 'Санаттарды іздеу',
          de: 'Kategorien suchen',
          fr: 'Rechercher des catégories',
          es: 'Buscar categorías',
          pt: 'Pesquisar categorias',
          tr: 'Kategori ara',
          uk: 'Пошук категорії',
          zh: '搜索分类',
          ar: 'البحث في الفئات',
          pl: 'Szukaj kategorii',
          it: 'Cerca categorie',
          sk: 'Szukaj kategorii',
          ja: 'Search categories',
          ko: 'Search categories',
          hi: 'Search categories',
          nl: 'Search categories',
          sv: 'Search categories',
          vi: 'Search categories',
          id: 'Search categories',
        }),
        description: t({
          ru: 'Поиск помогает быстро находить нужные категории по названию, особенно если список уже большой и включает системные и пользовательские элементы.',
          en: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
          kk: 'Іздеу санатты атауы бойынша тез табуға көмектеседі, әсіресе тізімде жүйелік те, қолданушы жасаған элементтер де көп болғанда.',
          de: 'Die Suche hilft Ihnen, eine Kategorie schnell nach Namen zu finden, besonders wenn die Liste sowohl System- als auch benutzerdefinierte Einträge enthält.',
          fr: 'La recherche vous aide à localiser rapidement une catégorie par nom, surtout quand la liste inclut des entrées système et personnalisées.',
          es: 'La búsqueda le ayuda a localizar rápidamente una categoría por nombre, especialmente cuando la lista crece para incluir entradas del sistema y personalizadas.',
          pt: 'A pesquisa ajuda a localizar rapidamente uma categoria por nome, especialmente quando a lista cresce para incluir entradas do sistema e personalizadas.',
          tr: 'Arama, liste hem sistem hem de özel girişleri içerecek şekilde büyüdüğünde bir kategoriyi ada göre hızlıca bulmanıza yardımcı olur.',
          uk: 'Пошук допомагає швидко знайти потрібну категорію за назвою, особливо коли список уже великий і включає системні та користувацькі елементи.',
          zh: '搜索可帮助您按名称快速找到分类，尤其是当列表增长到包含系统和自定义条目时。',
          ar: 'يساعدك البحث على تحديد موقع فئة بسرعة حسب الاسم، خاصة عندما تنمو القائمة لتشمل إدخالات النظام والمخصصة.',
          pl: 'Wyszukiwanie pomaga szybko znaleźć kategorię według nazwy, zwłaszcza gdy lista rośnie i obejmuje zarówno wpisy systemowe, jak i niestandardowe.',
          it: 'La ricerca ti aiuta a trovare rapidamente una categoria per nome, specialmente quando la lista cresce per includere sia voci di sistema che personalizzate.',
          sk: 'Wyszukiwanie pomaga szybko znaleźć kategorię według nazwy, zwłaszcza gdy lista rośnie i obejmuje zarówno wpisy systemowe, jak i niestandardowe.',
          ja: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
          ko: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
          hi: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
          nl: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
          sv: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
          vi: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
          id: 'Search helps you quickly locate a category by name, especially once the list grows to include both system and custom entries.',
        }),
      },
      categoriesList: {
        title: t({
          ru: 'Список категорий',
          en: 'Categories list',
          kk: 'Санаттар тізімі',
          de: 'Kategorieliste',
          fr: 'Liste des catégories',
          es: 'Lista de categorías',
          pt: 'Lista de categorias',
          tr: 'Kategoriler listesi',
          uk: 'Список категорій',
          zh: '分类列表',
          ar: 'قائمة الفئات',
          pl: 'Lista kategorii',
          it: 'Elenco categorie',
          sk: 'Lista kategorii',
          ja: 'Categories list',
          ko: 'Categories list',
          hi: 'Categories list',
          nl: 'Categories list',
          sv: 'Categories list',
          vi: 'Categories list',
          id: 'Categories list',
        }),
        description: t({
          ru: 'Здесь показаны все категории с их названием, статусом использования и служебными метками. Это основная область для обзора и управления списком.',
          en: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
          kk: 'Мұнда әр санат атауымен, қолданылу күйімен және жүйелік белгілерімен бірге көрсетіледі. Бұл толық тізімді қарап, басқаруға арналған негізгі аймақ.',
          de: 'Diese Liste zeigt jede Kategorie mit ihrem Namen, Nutzungsstatus und Systemabzeichen. Es ist der Hauptbereich für das Überprüfen und Verwalten aller Kategorien.',
          fr: "Cette liste affiche chaque catégorie avec son nom, son état d'utilisation et ses badges système. C'est la zone principale pour examiner et gérer l'ensemble complet.",
          es: 'Esta lista muestra cada categoría con su nombre, estado de uso e insignias del sistema. Es el área principal para revisar y gestionar el conjunto completo.',
          pt: 'Esta lista mostra cada categoria com seu nome, estado de uso e badges do sistema. É a área principal para revisar e gerenciar o conjunto completo.',
          tr: 'Bu liste her kategoriyi adı, kullanım durumu ve sistem rozetleriyle gösterir. Tam seti incelemek ve yönetmek için ana alandır.',
          uk: 'Тут показані всі категорії з їх назвою, статусом використання та службовими мітками. Це основна область для перегляду та управління списком.',
          zh: '此列表显示每个分类的名称、使用状态和系统徽章。这是查看和管理完整集合的主要区域。',
          ar: 'تعرض هذه القائمة كل فئة باسمها وحالة الاستخدام وشارات النظام. إنها المنطقة الرئيسية لمراجعة المجموعة الكاملة وإدارتها.',
          pl: 'Ta lista pokazuje każdą kategorię z jej nazwą, stanem użycia i odznaczeniami systemowymi. Jest to główny obszar do przeglądania i zarządzania pełnym zestawem.',
          it: "Questo elenco mostra ogni categoria con il suo nome, stato di utilizzo e badge di sistema. È l'area principale per esaminare e gestire l'intero insieme.",
          sk: 'Ta lista pokazuje każdą kategorię z jej nazwą, stanem użycia i odznaczeniami systemowymi. Jest to główny obszar do przeglądania i zarządzania pełnym zestawem.',
          ja: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
          ko: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
          hi: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
          nl: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
          sv: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
          vi: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
          id: 'This list shows every category with its name, usage state, and system badges. It is the main area for reviewing and managing the full set.',
        }),
      },
      categoryToggle: {
        title: t({
          ru: 'Включение и отключение',
          en: 'Enable or disable',
          kk: 'Қосу немесе өшіру',
          de: 'Aktivieren oder deaktivieren',
          fr: 'Activer ou désactiver',
          es: 'Habilitar o deshabilitar',
          pt: 'Habilitar ou desabilitar',
          tr: 'Etkinleştir veya devre dışı bırak',
          uk: 'Увімкнення та вимкнення',
          zh: '启用或禁用',
          ar: 'تفعيل أو تعطيل',
          pl: 'Włącz lub wyłącz',
          it: 'Abilita o disabilita',
          sk: 'Włącz lub wyłącz',
          ja: 'Enable or disable',
          ko: 'Enable or disable',
          hi: 'Enable or disable',
          nl: 'Enable or disable',
          sv: 'Enable or disable',
          vi: 'Enable or disable',
          id: 'Enable or disable',
        }),
        description: t({
          ru: 'Переключатель управляет доступностью категории в интерфейсах выписок и отчетов. Если конкретной строки нет, тур пропустит этот шаг без ошибки.',
          en: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
          kk: 'Бұл ауыстырғыш санаттың үзінділер мен есептер интерфейсінде қолжетімді болуын басқарады. Егер тиісті жол қазір көрінбесе, тур бұл қадамды қате шығармай өткізіп жібереді.',
          de: 'Dieser Schalter steuert, ob eine Kategorie in Auszügen und Berichtsabläufen verfügbar bleibt. Wenn keine Kategoriezeile sichtbar ist, überspringt die Tour diesen Schritt sicher.',
          fr: "Cette bascule contrôle si une catégorie reste disponible dans les flux de relevés et de rapports. Si aucune ligne de catégorie n'est visible, la visite saute cette étape en toute sécurité.",
          es: 'Este interruptor controla si una categoría permanece disponible en los flujos de extractos e informes. Si no hay ninguna fila de categoría visible, el tour omite este paso de forma segura.',
          pt: 'Este toggle controla se uma categoria permanece disponível nos fluxos de extratos e relatórios. Se nenhuma linha de categoria estiver visível, o tour pula esta etapa com segurança.',
          tr: 'Bu geçiş, bir kategorinin ekstre ve raporlama akışlarında mevcut kalıp kalmadığını kontrol eder. Hiçbir kategori satırı görünmüyorsa tur bu adımı güvenli bir şekilde atlar.',
          uk: 'Перемикач керує доступністю категорії в інтерфейсах виписок та звітів. Якщо відповідного рядка немає, тур пропустить цей крок без помилки.',
          zh: '此开关控制分类是否在账单和报告流程中保持可用。如果当前没有可见的分类行，导览将安全跳过此步骤。',
          ar: 'يتحكم هذا المفتاح في ما إذا كانت الفئة تبقى متاحة في سير عمل كشوف الحسابات والتقارير. إذا لم يكن صف الفئة مرئياً حالياً، تتخطى الجولة هذه الخطوة بأمان.',
          pl: 'Ten przełącznik kontroluje, czy kategoria pozostaje dostępna w przepływach wyciągów i raportów. Jeśli żaden wiersz kategorii nie jest widoczny, przewodnik bezpiecznie pomija ten krok.',
          it: 'Questo toggle controlla se una categoria rimane disponibile nei flussi di estratti conto e reportistica. Se non è visibile nessuna riga di categoria, il tour salta questo passaggio in modo sicuro.',
          sk: 'Ten przełącznik kontroluje, czy kategoria pozostaje dostępna w przepływach wyciągów i raportów. Jeśli żaden wiersz kategorii nie jest widoczny, przewodnik bezpiecznie pomija ten krok.',
          ja: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
          ko: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
          hi: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
          nl: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
          sv: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
          vi: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
          id: 'This toggle controls whether a category stays available in statements and reporting flows. If no category row is currently visible, the tour skips this step safely.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'All set',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Pronto',
          tr: 'Hazır',
          uk: 'Готово',
          zh: '完成',
          ar: 'تم',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Gotowe',
          ja: 'All set',
          ko: 'All set',
          hi: 'All set',
          nl: 'All set',
          sv: 'All set',
          vi: 'All set',
          id: 'All set',
        }),
        description: t({
          ru: 'Теперь вы знаете, где создавать, искать и переключать категории рабочего пространства. Дальше можно открыть нужную категорию и настроить ее подробнее.',
          en: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
          kk: 'Енді жұмыс кеңістігі санаттарын қайдан жасау, табу және ауыстыру керегін білесіз. Келесі қадамда қажетті санатты ашып, оны тереңірек баптай аласыз.',
          de: 'Sie wissen jetzt, wo Sie Arbeitsbereichskategorien erstellen, finden und umschalten können. Von hier aus können Sie die richtige Kategorie öffnen und weiter verfeinern.',
          fr: "Vous savez maintenant où créer, trouver et basculer les catégories de l'espace de travail. De là vous pouvez ouvrir la bonne catégorie et l'affiner davantage.",
          es: 'Ahora sabe dónde crear, encontrar y alternar las categorías del espacio de trabajo. Desde aquí puede abrir la categoría correcta y refinarla más.',
          pt: 'Agora você sabe onde criar, encontrar e alternar as categorias do espaço de trabalho. Daqui pode abrir a categoria certa e refiná-la ainda mais.',
          tr: 'Artık çalışma alanı kategorilerini nerede oluşturacağınızı, bulacağınızı ve değiştireceğinizi biliyorsunuz. Buradan doğru kategoriyi açıp daha da geliştirebilirsiniz.',
          uk: 'Тепер ви знаєте, де створювати, шукати та перемикати категорії робочого простору. Далі можна відкрити потрібну категорію та налаштувати її детальніше.',
          zh: '您现在知道在哪里创建、查找和切换工作区分类。从这里可以打开正确的分类并进一步完善它。',
          ar: 'أنت تعرف الآن أين تنشئ وتجد وتبدّل فئات مساحة العمل. من هنا يمكنك فتح الفئة الصحيحة وتحسينها أكثر.',
          pl: 'Teraz wiesz, gdzie tworzyć, znajdować i przełączać kategorie obszaru roboczego. Stąd możesz otworzyć właściwą kategorię i dopracować ją dalej.',
          it: "Ora sai dove creare, trovare e attivare/disattivare le categorie dell'area di lavoro. Da qui puoi aprire la categoria giusta e perfezionarla ulteriormente.",
          sk: 'Teraz wiesz, gdzie tworzyć, znajdować i przełączać kategorie obszaru roboczego. Stąd możesz otworzyć właściwą kategorię i dopracować ją dalej.',
          ja: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
          ko: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
          hi: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
          nl: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
          sv: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
          vi: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
          id: 'You now know where to create, find, and toggle workspace categories. From here you can open the right category and refine it further.',
        }),
      },
    },
  },
} satisfies DeclarationContent;

export default categoriesTourContent;
