import { type DeclarationContent, t } from 'intlayer';

const customTablesTourContent = {
  key: 'custom-tables-tour-content',
  content: {
    name: t({
      ru: 'Тур по кастомным таблицам',
      en: 'Custom Tables Tour',
      kk: 'Жекелендірілген кестелер туры',
      de: 'Benutzerdefinierte Tabellen-Tour',
      fr: 'Visite des tableaux personnalisés',
      es: 'Tour de tablas personalizadas',
      pt: 'Tour de tabelas personalizadas',
      tr: 'Özel Tablolar Turu',
      uk: 'Тур по кастомних таблицях',
      zh: '自定义表格导览',
      ar: 'جولة الجداول المخصصة',
      pl: 'Tour niestandardowych tabel',
      it: 'Tour delle tabelle personalizzate',
      sk: 'Tour niestandardowych tabel',
      ja: 'カスタムテーブルツアー',
      ko: '사용자 정의 테이블 둘러보기',
      hi: 'कस्टम टेबल्स टूर',
      nl: 'Rondleiding door aangepaste tafels',
      sv: 'Anpassade bordsrundtur',
      vi: 'Tham quan bàn tùy chỉnh',
      id: 'Tur Meja Khusus',
    }),
    description: t({
      ru: 'Создание и управление таблицами для экспорта',
      en: 'Create and manage export-ready tables',
      kk: 'Экспортқа дайын кестелерді жасау және басқару',
      de: 'Exportfertige Tabellen erstellen und verwalten',
      fr: "Créer et gérer des tableaux prêts à l'exportation",
      es: 'Crear y gestionar tablas listas para exportar',
      pt: 'Criar e gerenciar tabelas prontas para exportação',
      tr: 'Dışa aktarmaya hazır tablolar oluşturun ve yönetin',
      uk: 'Створення та управління таблицями для експорту',
      zh: '创建和管理可导出的表格',
      ar: 'إنشاء وإدارة الجداول الجاهزة للتصدير',
      pl: 'Twórz tabele gotowe do eksportu i zarządzaj nimi',
      it: "Crea e gestisci tabelle pronte per l'esportazione",
      sk: 'Twórz tabele gotowe do eksportu i zarządzaj nimi',
      ja: 'エクスポート可能なテーブルの作成と管理',
      ko: '내보내기 가능한 테이블 생성 및 관리',
      hi: 'निर्यात-तैयार तालिकाएँ बनाएँ और प्रबंधित करें',
      nl: 'Maak en beheer exportklare tabellen',
      sv: 'Skapa och hantera exportklara tabeller',
      vi: 'Tạo và quản lý các bảng sẵn sàng xuất',
      id: 'Membuat dan mengelola tabel siap ekspor',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Добро пожаловать в кастомные таблицы',
          en: 'Welcome to Custom Tables',
          kk: 'Реттелетін кестелерге қош келдіңіз',
          de: 'Willkommen bei den benutzerdefinierten Tabellen',
          fr: 'Bienvenue dans les tableaux personnalisés',
          es: 'Bienvenido a Tablas personalizadas',
          pt: 'Bem-vindo às Tabelas personalizadas',
          tr: 'Özel Tablolara Hoş Geldiniz',
          uk: 'Ласкаво просимо до кастомних таблиць',
          zh: '欢迎使用自定义表格',
          ar: 'مرحباً بك في الجداول المخصصة',
          pl: 'Witaj w niestandardowych tabelach',
          it: 'Benvenuto nelle Tabelle personalizzate',
          sk: 'Witaj w niestandardowych tabelach',
          ja: 'カスタムテーブルへようこそ',
          ko: '맞춤 표에 오신 것을 환영합니다.',
          hi: 'कस्टम टेबल्स में आपका स्वागत है',
          nl: 'Welkom bij Aangepaste Tabellen',
          sv: 'Välkommen till Custom Tables',
          vi: 'Chào mừng đến với Bảng tùy chỉnh',
          id: 'Selamat datang di Tabel Kustom',
        }),
        description: t({
          ru: 'Здесь вы собираете таблицы для экспорта и отчетности: из выписок, вручную или через Google Sheets. Тур покажет основные элементы текущей страницы.',
          en: 'This page lets you build tables for exports and reporting from statements, manually, or through Google Sheets. This tour shows the key parts of the current workflow.',
          kk: 'Бұл бетте экспорт пен есептілікке арналған кестелерді үзінділерден, қолмен немесе Google Sheets арқылы жасайсыз. Тур ағымдағы беттің негізгі элементтерін көрсетеді.',
          de: 'Auf dieser Seite erstellen Sie Tabellen für Exporte und Berichte aus Auszügen, manuell oder über Google Sheets. Diese Tour zeigt die wichtigsten Teile des aktuellen Workflows.',
          fr: 'Cette page vous permet de créer des tableaux pour les exports et les rapports à partir de relevés, manuellement ou via Google Sheets. Cette visite montre les éléments clés du flux de travail actuel.',
          es: 'Esta página le permite crear tablas para exportaciones e informes a partir de extractos, manualmente o a través de Google Sheets. Este tour muestra las partes clave del flujo de trabajo actual.',
          pt: 'Esta página permite criar tabelas para exportações e relatórios a partir de extratos, manualmente ou pelo Google Sheets. Este tour mostra as partes principais do fluxo de trabalho atual.',
          tr: 'Bu sayfa ekstre, manuel veya Google Sheets yoluyla dışa aktarma ve raporlama için tablolar oluşturmanıza olanak tanır. Bu tur mevcut iş akışının temel bölümlerini gösterir.',
          uk: 'Тут ви збираєте таблиці для експорту та звітності: з виписок, вручну або через Google Sheets. Тур покаже основні елементи поточної сторінки.',
          zh: '此页面让您从账单、手动或通过 Google Sheets 构建用于导出和报告的表格。本导览展示当前工作流程的关键部分。',
          ar: 'تتيح لك هذه الصفحة إنشاء جداول للتصدير والتقارير من كشوف الحسابات يدوياً أو عبر Google Sheets. تعرض هذه الجولة الأجزاء الرئيسية من سير العمل الحالي.',
          pl: 'Ta strona pozwala tworzyć tabele do eksportu i raportowania z wyciągów, ręcznie lub przez Google Sheets. Ten przewodnik pokazuje kluczowe elementy bieżącego przepływu pracy.',
          it: 'Questa pagina ti permette di costruire tabelle per esportazioni e reportistica da estratti conto, manualmente o tramite Google Sheets. Questo tour mostra le parti chiave del flusso di lavoro attuale.',
          sk: 'Ta strona pozwala tworzyć tabele do eksportu i raportowania z wyciągów, ręcznie lub przez Google Sheets. Ten przewodnik pokazuje kluczowe elementy bieżącego przepływu pracy.',
          ja: 'このページでは、手動または Google スプレッドシートを使用して、ステートメントからエクスポートおよびレポートするためのテーブルを作成できます。このツアーでは、現在のワークフローの主要な部分を示します。',
          ko: '이 페이지에서는 수동으로 또는 Google Sheets를 통해 명세서에서 내보내기 및 보고용 테이블을 작성할 수 있습니다. 이 둘러보기에서는 현재 워크플로의 주요 부분을 보여줍니다.',
          hi: 'यह पेज आपको मैन्युअल रूप से या Google शीट के माध्यम से स्टेटमेंट से निर्यात और रिपोर्टिंग के लिए तालिकाएँ बनाने की सुविधा देता है। यह दौरा वर्तमान वर्कफ़्लो के प्रमुख भागों को दर्शाता है।',
          nl: 'Op deze pagina kunt u handmatig of via Google Spreadsheets tabellen maken voor export en rapportage van afschriften. Deze rondleiding toont de belangrijkste onderdelen van de huidige workflow.',
          sv: 'Den här sidan låter dig bygga tabeller för export och rapportering från uttalanden, manuellt eller via Google Kalkylark. Den här rundturen visar nyckeldelarna i det aktuella arbetsflödet.',
          vi: 'Trang này cho phép bạn tạo bảng để xuất và báo cáo từ các bảng sao kê theo cách thủ công hoặc thông qua Google Trang tính. Chuyến tham quan này hiển thị các phần chính của quy trình làm việc hiện tại.',
          id: 'Halaman ini memungkinkan Anda membuat tabel untuk ekspor dan pelaporan dari laporan, secara manual, atau melalui Google Spreadsheet. Tur ini menunjukkan bagian penting dari alur kerja saat ini.',
        }),
      },
      createExport: {
        title: t({
          ru: 'Создать экспортную таблицу',
          en: 'Create export table',
          kk: 'Экспорт кестесін жасау',
          de: 'Exporttabelle erstellen',
          fr: "Créer un tableau d'exportation",
          es: 'Crear tabla de exportación',
          pt: 'Criar tabela de exportação',
          tr: 'Dışa aktarma tablosu oluştur',
          uk: 'Створити експортну таблицю',
          zh: '创建导出表格',
          ar: 'إنشاء جدول التصدير',
          pl: 'Utwórz tabelę eksportu',
          it: 'Crea tabella di esportazione',
          sk: 'Utwórz tabelę eksportu',
          ja: 'エクスポートテーブルの作成',
          ko: '내보내기 테이블 생성',
          hi: 'निर्यात तालिका बनाएं',
          nl: 'Exporttabel maken',
          sv: 'Skapa exporttabell',
          vi: 'Tạo bảng xuất',
          id: 'Buat tabel ekspor',
        }),
        description: t({
          ru: 'Основная кнопка сразу открывает сценарий создания таблицы из выписок. Это быстрый путь, если вам нужна таблица для выгрузки или дальнейшей обработки.',
          en: 'The primary action opens the flow for building a table from statements. Use it when you need a fast export-ready table for further work.',
          kk: 'Негізгі батырма үзінділерден кесте жасау сценарийін ашады. Оны әрі қарай жұмыс істеуге арналған экспорт кестесін тез дайындау үшін пайдаланыңыз.',
          de: 'Die primäre Aktion öffnet den Ablauf zum Erstellen einer Tabelle aus Auszügen. Verwenden Sie sie, wenn Sie schnell eine exportfertige Tabelle für weitere Arbeiten benötigen.',
          fr: "L'action principale ouvre le flux pour construire un tableau à partir de relevés. Utilisez-le lorsque vous avez besoin d'un tableau prêt à l'exportation rapidement pour un travail ultérieur.",
          es: 'La acción principal abre el flujo para construir una tabla a partir de extractos. Úsela cuando necesite una tabla lista para exportar rápidamente para trabajos posteriores.',
          pt: 'A ação principal abre o fluxo para construir uma tabela a partir de extratos. Use-a quando precisar de uma tabela pronta para exportação rapidamente para trabalho posterior.',
          tr: 'Birincil eylem ekstrelerden tablo oluşturma akışını açar. Sonraki çalışmalar için hızlı bir dışa aktarma tablosuna ihtiyaç duyduğunuzda kullanın.',
          uk: 'Основна кнопка відразу відкриває сценарій створення таблиці з виписок. Це швидкий шлях, якщо вам потрібна таблиця для вивантаження або подальшої обробки.',
          zh: '主要操作打开从账单构建表格的流程。当您需要快速生成可导出表格以供进一步工作时使用它。',
          ar: 'يفتح الإجراء الرئيسي تدفق إنشاء جدول من كشوف الحسابات. استخدمه عندما تحتاج إلى جدول جاهز للتصدير بسرعة لمزيد من العمل.',
          pl: 'Główna akcja otwiera przepływ tworzenia tabeli z wyciągów. Użyj jej, gdy potrzebujesz szybkiej tabeli gotowej do eksportu do dalszej pracy.',
          it: "L'azione principale apre il flusso per costruire una tabella dagli estratti conto. Usala quando hai bisogno di una tabella pronta per l'esportazione rapidamente per lavori successivi.",
          sk: 'Główna akcja otwiera przepływ tworzenia tabeli z wyciągów. Użyj jej, gdy potrzebujesz szybkiej tabeli gotowej do eksportu do dalszej pracy.',
          ja: 'プライマリ アクションは、ステートメントからテーブルを構築するフローを開きます。今後の作業のために、高速にエクスポートできるテーブルが必要な場合に使用します。',
          ko: '기본 작업은 문에서 테이블을 작성하기 위한 흐름을 엽니다. 추가 작업을 위해 빠르게 내보낼 수 있는 테이블이 필요할 때 사용하세요.',
          hi: 'प्राथमिक क्रिया कथनों से तालिका बनाने के लिए प्रवाह खोलती है। जब आपको आगे के काम के लिए तेजी से निर्यात के लिए तैयार तालिका की आवश्यकता हो तो इसका उपयोग करें।',
          nl: 'De primaire actie opent de stroom voor het bouwen van een tabel op basis van instructies. Gebruik het wanneer u een snelle exportklare tabel nodig heeft voor verder werk.',
          sv: 'Den primära åtgärden öppnar flödet för att bygga en tabell från satser. Använd den när du behöver en snabb exportklar tabell för vidare arbete.',
          vi: 'Hành động chính mở ra quy trình xây dựng bảng từ các câu lệnh. Hãy sử dụng nó khi bạn cần một bảng sẵn sàng xuất nhanh để làm việc tiếp.',
          id: 'Tindakan utama membuka alur untuk membuat tabel dari pernyataan. Gunakan saat Anda membutuhkan tabel cepat siap ekspor untuk pekerjaan lebih lanjut.',
        }),
      },
      createDropdown: {
        title: t({
          ru: 'Другие способы создания',
          en: 'Other creation options',
          kk: 'Жасаудың басқа жолдары',
          de: 'Weitere Erstellungsoptionen',
          fr: 'Autres options de création',
          es: 'Otras opciones de creación',
          pt: 'Outras opções de criação',
          tr: 'Diğer oluşturma seçenekleri',
          uk: 'Інші способи створення',
          zh: '其他创建选项',
          ar: 'خيارات إنشاء أخرى',
          pl: 'Inne opcje tworzenia',
          it: 'Altre opzioni di creazione',
          sk: 'Inne opcje tworzenia',
          ja: 'その他の作成オプション',
          ko: '기타 생성 옵션',
          hi: 'अन्य निर्माण विकल्प',
          nl: 'Andere creatiemogelijkheden',
          sv: 'Andra skapande alternativ',
          vi: 'Các tùy chọn tạo khác',
          id: 'Opsi pembuatan lainnya',
        }),
        description: t({
          ru: 'Через это меню можно создать пустую таблицу с нуля или перейти к импорту из Google Sheets, если данные уже подготовлены в другом источнике.',
          en: 'This menu gives you the alternate creation paths: start with a blank table or import from Google Sheets when the source data already exists elsewhere.',
          kk: 'Бұл мәзір арқылы бос кестені нөлден жасай аласыз немесе деректер басқа жерде дайын болса, Google Sheets импортын аша аласыз.',
          de: 'Dieses Menü bietet die alternativen Erstellungspfade: mit einer leeren Tabelle beginnen oder aus Google Sheets importieren, wenn die Quelldaten bereits woanders vorhanden sind.',
          fr: 'Ce menu vous offre les chemins de création alternatifs : commencer avec un tableau vide ou importer depuis Google Sheets lorsque les données source existent déjà ailleurs.',
          es: 'Este menú le ofrece los caminos de creación alternativos: comenzar con una tabla en blanco o importar desde Google Sheets cuando los datos de origen ya existen en otro lugar.',
          pt: 'Este menu oferece os caminhos de criação alternativos: começar com uma tabela em branco ou importar do Google Sheets quando os dados de origem já existem em outro lugar.',
          tr: "Bu menü alternatif oluşturma yollarını sunar: boş bir tabloyla başlayın veya kaynak veriler başka bir yerde mevcutsa Google Sheets'ten içe aktarın.",
          uk: 'Через це меню можна створити порожню таблицю з нуля або перейти до імпорту з Google Sheets, якщо дані вже підготовлені в іншому джерелі.',
          zh: '此菜单提供其他创建路径：从空白表格开始，或在源数据已存在于其他位置时从 Google Sheets 导入。',
          ar: 'يمنحك هذا القائمة مسارات الإنشاء البديلة: ابدأ بجدول فارغ أو استورد من Google Sheets عندما تكون بيانات المصدر موجودة بالفعل في مكان آخر.',
          pl: 'To menu oferuje alternatywne ścieżki tworzenia: zacznij od pustej tabeli lub zaimportuj z Google Sheets, gdy dane źródłowe już istnieją gdzie indziej.',
          it: 'Questo menu offre i percorsi di creazione alternativi: inizia con una tabella vuota o importa da Google Sheets quando i dati sorgente esistono già altrove.',
          sk: 'To menu oferuje alternatywne ścieżki tworzenia: zacznij od pustej tabeli lub zaimportuj z Google Sheets, gdy dane źródłowe już istnieją gdzie indziej.',
          ja: 'このメニューでは、代替の作成パスを提供します。空のテーブルから始めるか、ソース データがすでに別の場所に存在する場合は Google スプレッドシートからインポートします。',
          ko: '이 메뉴는 대체 생성 경로를 제공합니다. 빈 테이블로 시작하거나 소스 데이터가 이미 다른 곳에 있는 경우 Google Sheets에서 가져옵니다.',
          hi: 'यह मेनू आपको वैकल्पिक निर्माण पथ देता है: एक रिक्त तालिका से प्रारंभ करें या Google शीट से आयात करें जब स्रोत डेटा पहले से ही कहीं और मौजूद हो।',
          nl: 'Dit menu biedt u de alternatieve aanmaakpaden: begin met een lege tabel of importeer vanuit Google Spreadsheets als de brongegevens al elders bestaan.',
          sv: 'Den här menyn ger dig de alternativa skapelsevägarna: börja med en tom tabell eller importera från Google Sheets när källdata redan finns någon annanstans.',
          vi: 'Menu này cung cấp cho bạn các đường dẫn tạo thay thế: bắt đầu bằng một bảng trống hoặc nhập từ Google Trang tính khi dữ liệu nguồn đã tồn tại ở nơi khác.',
          id: 'Menu ini memberi Anda jalur pembuatan alternatif: mulai dengan tabel kosong atau impor dari Google Spreadsheet ketika sumber data sudah ada di tempat lain.',
        }),
      },
      search: {
        title: t({
          ru: 'Поиск по таблицам',
          en: 'Search tables',
          kk: 'Кестелерді іздеу',
          de: 'Tabellen durchsuchen',
          fr: 'Rechercher des tableaux',
          es: 'Buscar tablas',
          pt: 'Pesquisar tabelas',
          tr: 'Tablo ara',
          uk: 'Пошук по таблицях',
          zh: '搜索表格',
          ar: 'البحث في الجداول',
          pl: 'Szukaj tabel',
          it: 'Cerca tabelle',
          sk: 'Szukaj tabel',
          ja: '検索テーブル',
          ko: '테이블 검색',
          hi: 'तालिकाएँ खोजें',
          nl: 'Zoek tabellen',
          sv: 'Sök tabeller',
          vi: 'Tìm kiếm bảng',
          id: 'Cari tabel',
        }),
        description: t({
          ru: 'Поиск помогает быстро находить нужные таблицы по названию, особенно когда у вас уже несколько экспортов под разные задачи и периоды.',
          en: 'Search helps you quickly find a table by name, especially once you have multiple exports for different workflows and periods.',
          kk: 'Іздеу атауы бойынша қажетті кестені тез табуға көмектеседі, әсіресе әртүрлі кезеңдер мен міндеттерге арналған экспорттар көбейген кезде.',
          de: 'Die Suche hilft Ihnen, eine Tabelle schnell nach Namen zu finden, besonders wenn Sie mehrere Exporte für verschiedene Workflows und Zeiträume haben.',
          fr: 'La recherche vous aide à trouver rapidement un tableau par nom, surtout lorsque vous avez plusieurs exports pour différents workflows et périodes.',
          es: 'La búsqueda le ayuda a encontrar rápidamente una tabla por nombre, especialmente cuando tiene múltiples exportaciones para diferentes flujos de trabajo y períodos.',
          pt: 'A pesquisa ajuda a encontrar rapidamente uma tabela por nome, especialmente quando você tem múltiplas exportações para diferentes fluxos de trabalho e períodos.',
          tr: 'Arama, farklı iş akışları ve dönemler için birden fazla dışa aktarmanız olduğunda bir tabloyu ada göre hızlıca bulmanıza yardımcı olur.',
          uk: 'Пошук допомагає швидко знайти потрібну таблицю за назвою, особливо коли у вас вже кілька експортів для різних завдань та періодів.',
          zh: '搜索可帮助您按名称快速找到表格，尤其是当您有多个针对不同工作流程和时间段的导出时。',
          ar: 'يساعدك البحث على العثور بسرعة على جدول حسب الاسم، خاصة عندما يكون لديك عدة تصديرات لسير عمل وفترات مختلفة.',
          pl: 'Wyszukiwanie pomaga szybko znaleźć tabelę według nazwy, zwłaszcza gdy masz wiele eksportów dla różnych przepływów pracy i okresów.',
          it: 'La ricerca ti aiuta a trovare rapidamente una tabella per nome, specialmente quando hai più esportazioni per diversi flussi di lavoro e periodi.',
          sk: 'Wyszukiwanie pomaga szybko znaleźć tabelę według nazwy, zwłaszcza gdy masz wiele eksportów dla różnych przepływów pracy i okresów.',
          ja: '検索を使用すると、特にワークフローや期間が異なる複数のエクスポートがある場合に、名前でテーブルをすばやく見つけることができます。',
          ko: '검색을 사용하면 특히 다양한 워크플로 및 기간에 대한 내보내기가 여러 개 있는 경우 이름으로 테이블을 빠르게 찾을 수 있습니다.',
          hi: 'खोज आपको नाम के आधार पर शीघ्रता से तालिका ढूंढने में सहायता करती है, विशेष रूप से तब जब आपके पास विभिन्न वर्कफ़्लो और अवधियों के लिए एकाधिक निर्यात हों।',
          nl: 'Met Zoeken kunt u snel een tabel op naam vinden, vooral als u meerdere exports heeft voor verschillende workflows en perioden.',
          sv: 'Sökning hjälper dig att snabbt hitta en tabell efter namn, särskilt när du har flera exporter för olika arbetsflöden och perioder.',
          vi: 'Tìm kiếm giúp bạn nhanh chóng tìm thấy bảng theo tên, đặc biệt khi bạn có nhiều lần xuất cho các quy trình làm việc và giai đoạn khác nhau.',
          id: 'Pencarian membantu Anda menemukan tabel berdasarkan nama dengan cepat, terutama setelah Anda memiliki beberapa ekspor untuk alur kerja dan periode berbeda.',
        }),
      },
      sourceFilter: {
        title: t({
          ru: 'Фильтр по источнику',
          en: 'Source filter',
          kk: 'Дереккөз сүзгісі',
          de: 'Quellfilter',
          fr: 'Filtre par source',
          es: 'Filtro por origen',
          pt: 'Filtro por origem',
          tr: 'Kaynak filtresi',
          uk: 'Фільтр за джерелом',
          zh: '来源筛选',
          ar: 'فلتر المصدر',
          pl: 'Filtr źródła',
          it: 'Filtro per sorgente',
          sk: 'Filtr źródła',
          ja: 'ソースフィルター',
          ko: '소스 필터',
          hi: 'स्रोत फ़िल्टर',
          nl: 'Bronfilter',
          sv: 'Källfilter',
          vi: 'Bộ lọc nguồn',
          id: 'Penyaring sumber',
        }),
        description: t({
          ru: 'Фильтруйте таблицы по происхождению: ручные, из Google Sheets или созданные из выписок. Это упрощает навигацию по рабочим наборам данных.',
          en: 'Filter tables by where they came from: manual, Google Sheets, or statement-based. It is the quickest way to narrow the list to one workflow.',
          kk: 'Кестелерді шығу көзі бойынша сүзіңіз: қолмен жасалған, Google Sheets-тен келген немесе үзінділерден құрылған. Бұл тізімді бір жұмыс ағынына тез қысқартады.',
          de: 'Filtern Sie Tabellen nach ihrer Herkunft: manuell, Google Sheets oder auszugsbasiert. Dies ist der schnellste Weg, die Liste auf einen Workflow zu reduzieren.',
          fr: "Filtrez les tableaux selon leur origine : manuel, Google Sheets ou basé sur des relevés. C'est la façon la plus rapide de réduire la liste à un seul flux de travail.",
          es: 'Filtre tablas por su origen: manual, Google Sheets o basado en extractos. Es la forma más rápida de reducir la lista a un flujo de trabajo.',
          pt: 'Filtre tabelas pela origem: manual, Google Sheets ou baseada em extratos. É a forma mais rápida de reduzir a lista a um fluxo de trabalho.',
          tr: 'Tabloları nereden geldiklerine göre filtreleyin: manuel, Google Sheets veya ekstreye dayalı. Listeyi tek bir iş akışına daraltmanın en hızlı yoludur.',
          uk: 'Фільтруйте таблиці за походженням: ручні, з Google Sheets або створені з виписок. Це спрощує навігацію по робочих наборах даних.',
          zh: '按来源筛选表格：手动、Google Sheets 或基于账单。这是将列表缩小到一个工作流程的最快方式。',
          ar: 'فلتر الجداول حسب مصدرها: يدوي أو Google Sheets أو مستند إلى كشوف الحسابات. إنها أسرع طريقة لتضييق القائمة إلى سير عمل واحد.',
          pl: 'Filtruj tabele według ich pochodzenia: ręcznie, Google Sheets lub na podstawie wyciągów. To najszybszy sposób zawężenia listy do jednego przepływu pracy.',
          it: 'Filtra le tabelle in base alla loro provenienza: manuale, Google Sheets o basata su estratti conto. È il modo più rapido per restringere la lista a un flusso di lavoro.',
          sk: 'Filtruj tabele według ich pochodzenia: ręcznie, Google Sheets lub na podstawie wyciągów. To najszybszy sposób zawężenia listy do jednego przepływu pracy.',
          ja: '手動、Google スプレッドシート、またはステートメントベースなど、テーブルの取得元に基づいてテーブルをフィルタリングします。これは、リストを 1 つのワークフローに絞り込む最も簡単な方法です。',
          ko: '수동, Google 스프레드시트, 명령문 기반 등 테이블의 출처를 기준으로 테이블을 필터링합니다. 목록을 하나의 워크플로로 좁히는 가장 빠른 방법입니다.',
          hi: 'तालिकाएँ इस आधार पर फ़िल्टर करें कि वे कहाँ से आई हैं: मैन्युअल, Google शीट्स, या कथन-आधारित। यह सूची को एक वर्कफ़्लो तक सीमित करने का सबसे तेज़ तरीका है।',
          nl: 'Filter tabellen op basis van waar ze vandaan komen: handmatig, Google Spreadsheets of op basis van verklaringen. Het is de snelste manier om de lijst te beperken tot één workflow.',
          sv: 'Filtrera tabeller efter var de kom ifrån: manuell, Google Kalkylark eller uttalandebaserad. Det är det snabbaste sättet att begränsa listan till ett arbetsflöde.',
          vi: 'Lọc các bảng theo nguồn gốc của chúng: thủ công, Google Trang tính hoặc dựa trên câu lệnh. Đó là cách nhanh nhất để thu hẹp danh sách thành một quy trình công việc.',
          id: 'Filter tabel berdasarkan asalnya: manual, Google Spreadsheet, atau berbasis pernyataan. Ini adalah cara tercepat untuk mempersempit daftar menjadi satu alur kerja.',
        }),
      },
      tablesList: {
        title: t({
          ru: 'Список таблиц',
          en: 'Tables list',
          kk: 'Кестелер тізімі',
          de: 'Tabellenliste',
          fr: 'Liste des tableaux',
          es: 'Lista de tablas',
          pt: 'Lista de tabelas',
          tr: 'Tablolar listesi',
          uk: 'Список таблиць',
          zh: '表格列表',
          ar: 'قائمة الجداول',
          pl: 'Lista tabel',
          it: 'Elenco tabelle',
          sk: 'Lista tabel',
          ja: 'テーブルリスト',
          ko: '테이블 목록',
          hi: 'तालिकाओं की सूची',
          nl: 'Tabellen lijst',
          sv: 'Tabeller lista',
          vi: 'Danh sách bảng',
          id: 'Daftar tabel',
        }),
        description: t({
          ru: 'Здесь собраны все созданные таблицы. В каждой строке видны назначение, источник, количество строк, дата обновления и быстрые действия.',
          en: 'This area shows every table you have created. Each row surfaces the purpose, source, row count, last update, and quick actions.',
          kk: 'Мұнда барлық жасалған кестелер көрсетіледі. Әр жолда мақсаты, дереккөзі, жол саны, соңғы жаңартылуы және жылдам әрекеттер беріледі.',
          de: 'Dieser Bereich zeigt jede von Ihnen erstellte Tabelle. Jede Zeile zeigt den Zweck, die Quelle, die Zeilenanzahl, das letzte Update und schnelle Aktionen.',
          fr: "Cette zone affiche chaque tableau que vous avez créé. Chaque ligne montre l'objectif, la source, le nombre de lignes, la dernière mise à jour et les actions rapides.",
          es: 'Esta área muestra cada tabla que ha creado. Cada fila muestra el propósito, origen, recuento de filas, última actualización y acciones rápidas.',
          pt: 'Esta área mostra cada tabela que você criou. Cada linha mostra o propósito, origem, contagem de linhas, última atualização e ações rápidas.',
          tr: 'Bu alan oluşturduğunuz her tabloyu gösterir. Her satır amacı, kaynağı, satır sayısını, son güncellemeyi ve hızlı eylemleri gösterir.',
          uk: 'Тут зібрані всі створені таблиці. В кожному рядку видно призначення, джерело, кількість рядків, дату оновлення та швидкі дії.',
          zh: '此区域显示您创建的每个表格。每行显示用途、来源、行数、最后更新和快速操作。',
          ar: 'تعرض هذه المنطقة كل جدول أنشأته. يعرض كل صف الغرض والمصدر وعدد الصفوف وآخر تحديث والإجراءات السريعة.',
          pl: 'Ten obszar pokazuje każdą utworzoną przez ciebie tabelę. Każdy wiersz pokazuje cel, źródło, liczbę wierszy, ostatnią aktualizację i szybkie akcje.',
          it: "Quest'area mostra ogni tabella che hai creato. Ogni riga mostra lo scopo, la sorgente, il conteggio righe, l'ultimo aggiornamento e le azioni rapide.",
          sk: 'Ten obszar pokazuje każdą utworzoną przez ciebie tabelę. Każdy wiersz pokazuje cel, źródło, liczbę wierszy, ostatnią aktualizację i szybkie akcje.',
          ja: 'この領域には、作成したすべてのテーブルが表示されます。各行には、目的、ソース、行数、最終更新、クイック アクションが表示されます。',
          ko: '이 영역에는 생성한 모든 테이블이 표시됩니다. 각 행에는 목적, 소스, 행 수, 마지막 업데이트 및 빠른 작업이 표시됩니다.',
          hi: 'यह क्षेत्र आपके द्वारा बनाई गई प्रत्येक तालिका दिखाता है। प्रत्येक पंक्ति में उद्देश्य, स्रोत, पंक्ति संख्या, अंतिम अद्यतन और त्वरित कार्रवाइयां सामने आती हैं।',
          nl: 'In dit gebied wordt elke tabel weergegeven die u hebt gemaakt. Elke rij geeft het doel, de bron, het aantal rijen, de laatste update en snelle acties weer.',
          sv: 'Det här området visar varje tabell du har skapat. Varje rad visar syfte, källa, radantal, senaste uppdatering och snabba åtgärder.',
          vi: 'Khu vực này hiển thị mọi bảng bạn đã tạo. Mỗi hàng hiển thị mục đích, nguồn, số lượng hàng, cập nhật gần đây nhất và các hành động nhanh.',
          id: 'Area ini menunjukkan setiap tabel yang Anda buat. Setiap baris menampilkan tujuan, sumber, jumlah baris, pembaruan terakhir, dan tindakan cepat.',
        }),
      },
      pagination: {
        title: t({
          ru: 'Навигация по списку',
          en: 'List navigation',
          kk: 'Тізім навигациясы',
          de: 'Listennavigation',
          fr: 'Navigation dans la liste',
          es: 'Navegación de lista',
          pt: 'Navegação na lista',
          tr: 'Liste navigasyonu',
          uk: 'Навігація по списку',
          zh: '列表导航',
          ar: 'التنقل في القائمة',
          pl: 'Nawigacja po liście',
          it: 'Navigazione lista',
          sk: 'Nawigacja po liście',
          ja: 'リストナビゲーション',
          ko: '목록 탐색',
          hi: 'सूची नेविगेशन',
          nl: 'Lijstnavigatie',
          sv: 'Lista navigering',
          vi: 'Danh sách điều hướng',
          id: 'Navigasi daftar',
        }),
        description: t({
          ru: 'Если таблиц много, используйте пагинацию, чтобы переходить между страницами результатов и контролировать текущий диапазон отображения.',
          en: 'When the list grows, use pagination to move through result pages and keep track of the visible range.',
          kk: 'Кестелер көбейгенде, беттеу арқылы нәтижелер беттері арасында ауысып, көрсетіліп тұрған ауқымды бақылаңыз.',
          de: 'Wenn die Liste größer wird, verwenden Sie die Paginierung, um durch Ergebnisseiten zu navigieren und den sichtbaren Bereich im Blick zu behalten.',
          fr: "Quand la liste s'agrandit, utilisez la pagination pour naviguer entre les pages de résultats et suivre la plage visible.",
          es: 'Cuando la lista crece, use la paginación para moverse por las páginas de resultados y realizar un seguimiento del rango visible.',
          pt: 'Quando a lista cresce, use a paginação para percorrer as páginas de resultados e controlar o intervalo visível.',
          tr: 'Liste büyüdüğünde, sonuç sayfaları arasında gezinmek ve görünür aralığı takip etmek için sayfalamayı kullanın.',
          uk: 'Якщо таблиць багато, використовуйте пагінацію для переходу між сторінками результатів та контролю поточного діапазону відображення.',
          zh: '当列表增长时，使用分页在结果页面之间移动并跟踪可见范围。',
          ar: 'عندما تنمو القائمة استخدم التصفح لتتنقل بين صفحات النتائج وتتابع النطاق المرئي.',
          pl: 'Gdy lista rośnie, użyj paginacji, aby poruszać się po stronach wyników i śledzić widoczny zakres.',
          it: "Quando la lista cresce, usa la paginazione per spostarti tra le pagine dei risultati e tenere traccia dell'intervallo visibile.",
          sk: 'Gdy lista rośnie, użyj paginacji, aby poruszać się po stronach wyników i śledzić widoczny zakres.',
          ja: 'リストが大きくなった場合は、ページネーションを使用して結果ページ間を移動し、表示範囲を追跡します。',
          ko: '목록이 커지면 페이지 매김을 사용하여 결과 페이지를 이동하고 가시 범위를 추적하세요.',
          hi: 'जब सूची बढ़ती है, तो परिणाम पृष्ठों पर जाने और दृश्यमान सीमा का ट्रैक रखने के लिए पेजिनेशन का उपयोग करें।',
          nl: "Wanneer de lijst groter wordt, kunt u paginering gebruiken om door de resultatenpagina's te bladeren en het zichtbare bereik bij te houden.",
          sv: 'När listan växer, använd sidnumrering för att gå igenom resultatsidor och hålla reda på det synliga intervallet.',
          vi: 'Khi danh sách phát triển, hãy sử dụng tính năng phân trang để di chuyển qua các trang kết quả và theo dõi phạm vi hiển thị.',
          id: 'Saat daftar bertambah, gunakan penomoran halaman untuk menelusuri halaman hasil dan melacak rentang yang terlihat.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'All set',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Pronto',
          tr: 'Hazır',
          uk: 'Готово',
          zh: '完成',
          ar: 'تم',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Gotowe',
          ja: '準備完了',
          ko: '모든 세트',
          hi: 'सब तैयार',
          nl: 'Helemaal klaar',
          sv: 'Allt klart',
          vi: 'Đã hoàn tất',
          id: 'Semua siap',
        }),
        description: t({
          ru: 'Теперь вы знаете, где создавать, искать и фильтровать кастомные таблицы. Дальше можно открыть нужную таблицу и работать уже с ее структурой и данными.',
          en: 'You now know where to create, find, and filter custom tables. From here you can open the right table and work with its structure and data.',
          kk: 'Енді сіз реттелетін кестелерді қайдан жасау, табу және сүзу керегін білесіз. Келесі қадамда қажетті кестені ашып, оның құрылымы мен деректерімен жұмыс істей аласыз.',
          de: 'Sie wissen jetzt, wo Sie benutzerdefinierte Tabellen erstellen, finden und filtern können. Von hier aus können Sie die richtige Tabelle öffnen und mit ihrer Struktur und ihren Daten arbeiten.',
          fr: 'Vous savez maintenant où créer, trouver et filtrer des tableaux personnalisés. De là vous pouvez ouvrir le bon tableau et travailler avec sa structure et ses données.',
          es: 'Ahora sabe dónde crear, encontrar y filtrar tablas personalizadas. Desde aquí puede abrir la tabla correcta y trabajar con su estructura y datos.',
          pt: 'Agora você sabe onde criar, encontrar e filtrar tabelas personalizadas. Daqui pode abrir a tabela certa e trabalhar com sua estrutura e dados.',
          tr: 'Artık özel tabloların nerede oluşturulacağını, bulunacağını ve filtreleneceğini biliyorsunuz. Buradan doğru tabloyu açıp yapısı ve verileriyle çalışabilirsiniz.',
          uk: 'Тепер ви знаєте, де створювати, шукати та фільтрувати кастомні таблиці. Далі можна відкрити потрібну таблицю та працювати з її структурою та даними.',
          zh: '您现在知道在哪里创建、查找和筛选自定义表格。从这里可以打开正确的表格并处理其结构和数据。',
          ar: 'أنت تعرف الآن أين تنشئ وتجد وتفلتر الجداول المخصصة. من هنا يمكنك فتح الجدول الصحيح والعمل على بنيته وبياناته.',
          pl: 'Teraz wiesz, gdzie tworzyć, znajdować i filtrować niestandardowe tabele. Stąd możesz otworzyć właściwą tabelę i pracować z jej strukturą i danymi.',
          it: 'Ora sai dove creare, trovare e filtrare le tabelle personalizzate. Da qui puoi aprire la tabella giusta e lavorare con la sua struttura e i suoi dati.',
          sk: 'Teraz wiesz, gdzie tworzyć, znajdować i filtrować niestandardowe tabele. Stąd możesz otworzyć właściwą tabelę i pracować z jej strukturą i danymi.',
          ja: 'これで、カスタム テーブルを作成、検索、フィルタリングする場所がわかりました。ここから、適切なテーブルを開いて、その構造とデータを操作できます。',
          ko: '이제 사용자 정의 테이블을 생성, 검색, 필터링할 수 있는 위치를 알게 되었습니다. 여기에서 올바른 테이블을 열고 해당 테이블의 구조와 데이터로 작업할 수 있습니다.',
          hi: 'अब आप जानते हैं कि कस्टम टेबल कहां बनाना, ढूंढना और फ़िल्टर करना है। यहां से आप सही तालिका खोल सकते हैं और उसकी संरचना और डेटा के साथ काम कर सकते हैं।',
          nl: 'U weet nu waar u aangepaste tabellen kunt maken, vinden en filteren. Vanaf hier kunt u de juiste tabel openen en met de structuur en gegevens ervan werken.',
          sv: 'Du vet nu var du ska skapa, hitta och filtrera anpassade tabeller. Härifrån kan du öppna rätt tabell och arbeta med dess struktur och data.',
          vi: 'Bây giờ bạn đã biết nơi tạo, tìm và lọc các bảng tùy chỉnh. Từ đây bạn có thể mở bảng bên phải và làm việc với cấu trúc và dữ liệu của nó.',
          id: 'Anda kini mengetahui tempat membuat, menemukan, dan memfilter tabel khusus. Dari sini Anda dapat membuka tabel kanan dan bekerja dengan struktur dan datanya.',
        }),
      },
    },
  },
} satisfies DeclarationContent;

export default customTablesTourContent;
