import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'google-sheets-integration-tour-content',
  content: {
    name: t({
      ru: 'Тур по подключению Google Sheets',
      en: 'Google Sheets Connection Tour',
      kk: 'Google Sheets қосу туры',
      de: 'Google Sheets Verbindungs-Tour',
      fr: 'Visite de connexion Google Sheets',
      es: 'Tour de conexión de Google Sheets',
      pt: 'Tour de conexão do Google Sheets',
      tr: 'Google Sheets Bağlantı Turu',
      uk: 'Тур по підключенню Google Sheets',
      zh: 'Google Sheets 连接导览',
      ar: 'جولة اتصال Google Sheets',
      pl: 'Tour połączenia Google Sheets',
      it: 'Tour connessione Google Sheets',
      sk: 'Tour połączenia Google Sheets',
      ja: 'Google Sheets Connection Tour',
      ko: 'Google Sheets Connection Tour',
      hi: 'Google Sheets Connection Tour',
      nl: 'Google Sheets Connection Tour',
      sv: 'Google Sheets Connection Tour',
      vi: 'Google Sheets Connection Tour',
      id: 'Google Sheets Connection Tour',
    }),
    description: t({
      ru: 'Пошаговый гайд по подключению таблицы и настройке синхронизации.',
      en: 'Step-by-step guide to connect a sheet and configure sync.',
      kk: 'Кестені қосу және синхрондауды баптау бойынша қадамдық нұсқаулық.',
      de: 'Schritt-für-Schritt-Anleitung zum Verbinden einer Tabelle und Konfigurieren der Synchronisierung.',
      fr: 'Guide étape par étape pour connecter une feuille et configurer la synchronisation.',
      es: 'Guía paso a paso para conectar una hoja y configurar la sincronización.',
      pt: 'Guia passo a passo para conectar uma planilha e configurar a sincronização.',
      tr: 'Bir sayfa bağlamak ve senkronizasyonu yapılandırmak için adım adım kılavuz.',
      uk: 'Покроковий посібник з підключення таблиці та налаштування синхронізації.',
      zh: '连接工作表和配置同步的分步指南。',
      ar: 'دليل خطوة بخطوة لتوصيل جدول بيانات وضبط المزامنة.',
      pl: 'Przewodnik krok po kroku do połączenia arkusza i konfiguracji synchronizacji.',
      it: 'Guida passo dopo passo per connettere un foglio e configurare la sincronizzazione.',
      sk: 'Przewodnik krok po kroku do połączenia arkusza i konfiguracji synchronizacji.',
      ja: 'Step-by-step guide to connect a sheet and configure sync.',
      ko: 'Step-by-step guide to connect a sheet and configure sync.',
      hi: 'Step-by-step guide to connect a sheet and configure sync.',
      nl: 'Step-by-step guide to connect a sheet and configure sync.',
      sv: 'Step-by-step guide to connect a sheet and configure sync.',
      vi: 'Step-by-step guide to connect a sheet and configure sync.',
      id: 'Step-by-step guide to connect a sheet and configure sync.',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Подключение Google Sheets',
          en: 'Google Sheets connection',
          kk: 'Google Sheets қосылуы',
          de: 'Google Sheets-Verbindung',
          fr: 'Connexion Google Sheets',
          es: 'Conexión de Google Sheets',
          pt: 'Conexão do Google Sheets',
          tr: 'Google Sheets bağlantısı',
          uk: 'Підключення Google Sheets',
          zh: 'Google Sheets 连接',
          ar: 'اتصال Google Sheets',
          pl: 'Połączenie Google Sheets',
          it: 'Connessione Google Sheets',
          sk: 'Połączenie Google Sheets',
          ja: 'Google Sheets connection',
          ko: 'Google Sheets connection',
          hi: 'Google Sheets connection',
          nl: 'Google Sheets connection',
          sv: 'Google Sheets connection',
          vi: 'Google Sheets connection',
          id: 'Google Sheets connection',
        }),
        description: t({
          ru: 'Этот тур объяснит, как подключить таблицу, настроить Apps Script и управлять синхронизацией.',
          en: 'This tour explains how to connect a sheet, set up Apps Script, and manage sync.',
          kk: 'Бұл тур кестені қосу, Apps Script баптау және синхрондауды басқаруды түсіндіреді.',
          de: 'Diese Tour erklärt, wie Sie eine Tabelle verbinden, Apps Script einrichten und die Synchronisierung verwalten.',
          fr: 'Cette visite explique comment connecter une feuille, configurer Apps Script et gérer la synchronisation.',
          es: 'Este tour explica cómo conectar una hoja, configurar Apps Script y gestionar la sincronización.',
          pt: 'Este tour explica como conectar uma planilha, configurar o Apps Script e gerenciar a sincronização.',
          tr: "Bu tur, bir sayfanın nasıl bağlanacağını, Apps Script'in nasıl kurulacağını ve senkronizasyonun nasıl yönetileceğini açıklar.",
          uk: 'Цей тур пояснює, як підключити таблицю, налаштувати Apps Script та керувати синхронізацією.',
          zh: '本导览解释如何连接工作表、设置 Apps Script 和管理同步。',
          ar: 'تشرح هذه الجولة كيفية توصيل جدول بيانات وإعداد Apps Script وإدارة المزامنة.',
          pl: 'Ten przewodnik wyjaśnia, jak połączyć arkusz, skonfigurować Apps Script i zarządzać synchronizacją.',
          it: 'Questo tour spiega come connettere un foglio, configurare Apps Script e gestire la sincronizzazione.',
          sk: 'Ten przewodnik wyjaśnia, jak połączyć arkusz, skonfigurować Apps Script i zarządzać synchronizacją.',
          ja: 'This tour explains how to connect a sheet, set up Apps Script, and manage sync.',
          ko: 'This tour explains how to connect a sheet, set up Apps Script, and manage sync.',
          hi: 'This tour explains how to connect a sheet, set up Apps Script, and manage sync.',
          nl: 'This tour explains how to connect a sheet, set up Apps Script, and manage sync.',
          sv: 'This tour explains how to connect a sheet, set up Apps Script, and manage sync.',
          vi: 'This tour explains how to connect a sheet, set up Apps Script, and manage sync.',
          id: 'This tour explains how to connect a sheet, set up Apps Script, and manage sync.',
        }),
      },
      step1Card: {
        title: t({
          ru: 'Шаг 1: Добавить таблицу',
          en: 'Step 1: Add a sheet',
          kk: '1-қадам: Кесте қосу',
          de: 'Schritt 1: Tabelle hinzufügen',
          fr: 'Étape 1 : Ajouter une feuille',
          es: 'Paso 1: Agregar una hoja',
          pt: 'Passo 1: Adicionar uma planilha',
          tr: 'Adım 1: Sayfa ekle',
          uk: 'Крок 1: Додати таблицю',
          zh: '第 1 步：添加工作表',
          ar: 'الخطوة 1: إضافة جدول بيانات',
          pl: 'Krok 1: Dodaj arkusz',
          it: 'Passo 1: Aggiungi un foglio',
          sk: 'Krok 1: Dodaj arkusz',
          ja: 'Step 1: Add a sheet',
          ko: 'Step 1: Add a sheet',
          hi: 'Step 1: Add a sheet',
          nl: 'Step 1: Add a sheet',
          sv: 'Step 1: Add a sheet',
          vi: 'Step 1: Add a sheet',
          id: 'Step 1: Add a sheet',
        }),
        description: t({
          ru: 'Выберите таблицу через Google picker, затем при необходимости задайте имя подключения и конкретный лист.',
          en: 'Choose a spreadsheet through the Google picker, then set a connection name and worksheet if needed.',
          kk: 'Кестені Google picker арқылы таңдаңыз, содан кейін қажет болса қосылым атауы мен нақты парақты орнатыңыз.',
          de: 'Wählen Sie eine Tabelle über den Google Picker aus, legen Sie dann bei Bedarf einen Verbindungsnamen und ein Arbeitsblatt fest.',
          fr: 'Choisissez une feuille de calcul via le sélecteur Google, puis définissez un nom de connexion et une feuille si nécessaire.',
          es: 'Elija una hoja de cálculo a través del selector de Google, luego establezca un nombre de conexión y hoja si es necesario.',
          pt: 'Escolha uma planilha pelo seletor do Google, depois defina um nome de conexão e planilha se necessário.',
          tr: 'Google seçici aracılığıyla bir elektronik tablo seçin, ardından gerekirse bir bağlantı adı ve çalışma sayfası ayarlayın.',
          uk: 'Оберіть таблицю через Google picker, потім за потреби вкажіть назву підключення та конкретний аркуш.',
          zh: '通过 Google 选择器选择电子表格，然后根据需要设置连接名称和工作表。',
          ar: 'اختر جدول بيانات عبر منتقي Google، ثم حدد اسم الاتصال وورقة العمل إذا لزم الأمر.',
          pl: 'Wybierz arkusz kalkulacyjny przez selektor Google, a następnie ustaw nazwę połączenia i arkusz roboczy w razie potrzeby.',
          it: 'Scegli un foglio di calcolo tramite il selettore Google, poi imposta un nome di connessione e foglio di lavoro se necessario.',
          sk: 'Wybierz arkusz kalkulacyjny przez selektor Google, a następnie ustaw nazwę połączenia i arkusz roboczy w razie potrzeby.',
          ja: 'Choose a spreadsheet through the Google picker, then set a connection name and worksheet if needed.',
          ko: 'Choose a spreadsheet through the Google picker, then set a connection name and worksheet if needed.',
          hi: 'Choose a spreadsheet through the Google picker, then set a connection name and worksheet if needed.',
          nl: 'Choose a spreadsheet through the Google picker, then set a connection name and worksheet if needed.',
          sv: 'Choose a spreadsheet through the Google picker, then set a connection name and worksheet if needed.',
          vi: 'Choose a spreadsheet through the Google picker, then set a connection name and worksheet if needed.',
          id: 'Choose a spreadsheet through the Google picker, then set a connection name and worksheet if needed.',
        }),
      },
      sheetUrl: {
        title: t({
          ru: 'Выбор таблицы',
          en: 'Spreadsheet picker',
          kk: 'Кестені таңдау',
          de: 'Tabellenauswahl',
          fr: 'Sélecteur de feuille de calcul',
          es: 'Selector de hoja de cálculo',
          pt: 'Seletor de planilha',
          tr: 'Elektronik tablo seçici',
          uk: 'Вибір таблиці',
          zh: '电子表格选择器',
          ar: 'منتقي جدول البيانات',
          pl: 'Selektor arkusza kalkulacyjnego',
          it: 'Selettore foglio di calcolo',
          sk: 'Selektor arkusza kalkulacyjnego',
          ja: 'Spreadsheet picker',
          ko: 'Spreadsheet picker',
          hi: 'Spreadsheet picker',
          nl: 'Spreadsheet picker',
          sv: 'Spreadsheet picker',
          vi: 'Spreadsheet picker',
          id: 'Spreadsheet picker',
        }),
        description: t({
          ru: 'Здесь открывается Google picker для выбора нужной таблицы из вашего аккаунта и перехода к следующему шагу подключения.',
          en: 'This control opens the Google picker so you can choose the right spreadsheet from your account and continue setup.',
          kk: 'Бұл басқару элементі Google picker-ді ашып, аккаунтыңыздан қажетті кестені таңдап, баптауды жалғастыруға мүмкіндік береді.',
          de: 'Dieses Steuerelement öffnet den Google Picker, damit Sie die richtige Tabelle aus Ihrem Konto auswählen und die Einrichtung fortsetzen können.',
          fr: 'Ce contrôle ouvre le sélecteur Google pour que vous puissiez choisir la bonne feuille de calcul depuis votre compte et continuer la configuration.',
          es: 'Este control abre el selector de Google para que pueda elegir la hoja de cálculo correcta de su cuenta y continuar la configuración.',
          pt: 'Este controle abre o seletor do Google para que você possa escolher a planilha correta da sua conta e continuar a configuração.',
          tr: 'Bu kontrol, hesabınızdan doğru elektronik tabloyu seçmek ve kuruluma devam etmek için Google seçiciyi açar.',
          uk: 'Цей елемент відкриває Google picker для вибору потрібної таблиці з вашого облікового запису та продовження налаштування.',
          zh: '此控件打开 Google 选择器，供您从账户中选择正确的电子表格并继续设置。',
          ar: 'يفتح هذا الضبط منتقي Google حتى تتمكن من اختيار جدول البيانات المناسب من حسابك ومتابعة الإعداد.',
          pl: 'Ten element otwiera selektor Google, aby wybrać właściwy arkusz kalkulacyjny z konta i kontynuować konfigurację.',
          it: 'Questo controllo apre il selettore Google per scegliere il foglio di calcolo corretto dal tuo account e continuare la configurazione.',
          sk: 'Ten element otwiera selektor Google, aby wybrać właściwy arkusz kalkulacyjny z konta i kontynuować konfigurację.',
          ja: 'This control opens the Google picker so you can choose the right spreadsheet from your account and continue setup.',
          ko: 'This control opens the Google picker so you can choose the right spreadsheet from your account and continue setup.',
          hi: 'This control opens the Google picker so you can choose the right spreadsheet from your account and continue setup.',
          nl: 'This control opens the Google picker so you can choose the right spreadsheet from your account and continue setup.',
          sv: 'This control opens the Google picker so you can choose the right spreadsheet from your account and continue setup.',
          vi: 'This control opens the Google picker so you can choose the right spreadsheet from your account and continue setup.',
          id: 'This control opens the Google picker so you can choose the right spreadsheet from your account and continue setup.',
        }),
      },
      sheetName: {
        title: t({
          ru: 'Название в системе',
          en: 'Name in Lumio',
          kk: 'Lumio атауы',
          de: 'Name in Lumio',
          fr: 'Nom dans Lumio',
          es: 'Nombre en Lumio',
          pt: 'Nome no Lumio',
          tr: "Lumio'daki adı",
          uk: 'Назва в системі',
          zh: 'Lumio 中的名称',
          ar: 'الاسم في Lumio',
          pl: 'Nazwa w Lumio',
          it: 'Nome in Lumio',
          sk: 'Nazwa w Lumio',
          ja: 'Name in Lumio',
          ko: 'Name in Lumio',
          hi: 'Name in Lumio',
          nl: 'Name in Lumio',
          sv: 'Name in Lumio',
          vi: 'Name in Lumio',
          id: 'Name in Lumio',
        }),
        description: t({
          ru: 'Это имя будет отображаться в списке подключений.',
          en: 'This name will appear in the connections list.',
          kk: 'Бұл атау қосылымдар тізімінде көрсетіледі.',
          de: 'Dieser Name wird in der Verbindungsliste angezeigt.',
          fr: 'Ce nom apparaîtra dans la liste des connexions.',
          es: 'Este nombre aparecerá en la lista de conexiones.',
          pt: 'Este nome aparecerá na lista de conexões.',
          tr: 'Bu ad bağlantılar listesinde görünecektir.',
          uk: "Це ім'я відображатиметься в списку підключень.",
          zh: '此名称将显示在连接列表中。',
          ar: 'سيظهر هذا الاسم في قائمة الاتصالات.',
          pl: 'Ta nazwa będzie widoczna na liście połączeń.',
          it: "Questo nome apparirà nell'elenco delle connessioni.",
          sk: 'Ta nazwa będzie widoczna na liście połączeń.',
          ja: 'This name will appear in the connections list.',
          ko: 'This name will appear in the connections list.',
          hi: 'This name will appear in the connections list.',
          nl: 'This name will appear in the connections list.',
          sv: 'This name will appear in the connections list.',
          vi: 'This name will appear in the connections list.',
          id: 'This name will appear in the connections list.',
        }),
      },
      worksheet: {
        title: t({
          ru: 'Имя листа',
          en: 'Worksheet name',
          kk: 'Парақ атауы',
          de: 'Blattname',
          fr: 'Nom de la feuille',
          es: 'Nombre de la hoja',
          pt: 'Nome da planilha',
          tr: 'Sayfa adı',
          uk: 'Назва аркуша',
          zh: '工作表名称',
          ar: 'اسم ورقة العمل',
          pl: 'Nazwa arkusza',
          it: 'Nome foglio di lavoro',
          sk: 'Nazwa arkusza',
          ja: 'Worksheet name',
          ko: 'Worksheet name',
          hi: 'Worksheet name',
          nl: 'Worksheet name',
          sv: 'Worksheet name',
          vi: 'Worksheet name',
          id: 'Worksheet name',
        }),
        description: t({
          ru: 'Укажите конкретный лист, если данных несколько.',
          en: 'Specify a worksheet if the spreadsheet has multiple tabs.',
          kk: 'Кестеде бірнеше парақ болса, қажеттісін көрсетіңіз.',
          de: 'Geben Sie ein Arbeitsblatt an, wenn die Tabelle mehrere Registerkarten hat.',
          fr: 'Spécifiez une feuille de calcul si le classeur comporte plusieurs onglets.',
          es: 'Especifique una hoja de cálculo si el archivo tiene varias pestañas.',
          pt: 'Especifique uma planilha se o arquivo tiver várias guias.',
          tr: 'Elektronik tabloda birden fazla sekme varsa bir çalışma sayfası belirtin.',
          uk: 'Вкажіть конкретний аркуш, якщо даних декілька.',
          zh: '如果电子表格有多个标签，请指定工作表。',
          ar: 'حدد ورقة عمل إذا كان جدول البيانات يحتوي على علامات تبويب متعددة.',
          pl: 'Podaj arkusz roboczy, jeśli arkusz kalkulacyjny ma wiele kart.',
          it: 'Specifica un foglio di lavoro se il foglio di calcolo ha più schede.',
          sk: 'Podaj arkusz roboczy, jeśli arkusz kalkulacyjny ma wiele kart.',
          ja: 'Specify a worksheet if the spreadsheet has multiple tabs.',
          ko: 'Specify a worksheet if the spreadsheet has multiple tabs.',
          hi: 'Specify a worksheet if the spreadsheet has multiple tabs.',
          nl: 'Specify a worksheet if the spreadsheet has multiple tabs.',
          sv: 'Specify a worksheet if the spreadsheet has multiple tabs.',
          vi: 'Specify a worksheet if the spreadsheet has multiple tabs.',
          id: 'Specify a worksheet if the spreadsheet has multiple tabs.',
        }),
      },
      connectButton: {
        title: t({
          ru: 'Авторизация и подключение',
          en: 'Authorize and connect',
          kk: 'Авторизация және қосу',
          de: 'Autorisieren und verbinden',
          fr: 'Autoriser et connecter',
          es: 'Autorizar y conectar',
          pt: 'Autorizar e conectar',
          tr: 'Yetkilendir ve bağlan',
          uk: 'Авторизація та підключення',
          zh: '授权并连接',
          ar: 'التفويض والاتصال',
          pl: 'Autoryzuj i połącz',
          it: 'Autorizza e connetti',
          sk: 'Autoryzuj i połącz',
          ja: 'Authorize and connect',
          ko: 'Authorize and connect',
          hi: 'Authorize and connect',
          nl: 'Authorize and connect',
          sv: 'Authorize and connect',
          vi: 'Authorize and connect',
          id: 'Authorize and connect',
        }),
        description: t({
          ru: 'Запускает OAuth для доступа к Google Sheets.',
          en: 'Starts OAuth to grant Google Sheets access.',
          kk: 'Google Sheets қолжетімділігін беру үшін OAuth іске қосады.',
          de: 'Startet OAuth, um Google Sheets-Zugriff zu gewähren.',
          fr: "Lance OAuth pour accorder l'accès à Google Sheets.",
          es: 'Inicia OAuth para otorgar acceso a Google Sheets.',
          pt: 'Inicia OAuth para conceder acesso ao Google Sheets.',
          tr: "Google Sheets erişimi vermek için OAuth'ı başlatır.",
          uk: 'Запускає OAuth для надання доступу до Google Sheets.',
          zh: '启动 OAuth 以授予 Google Sheets 访问权限。',
          ar: 'يبدأ OAuth لمنح الوصول إلى Google Sheets.',
          pl: 'Uruchamia OAuth, aby udzielić dostępu do Google Sheets.',
          it: "Avvia OAuth per concedere l'accesso a Google Sheets.",
          sk: 'Uruchamia OAuth, aby udzielić dostępu do Google Sheets.',
          ja: 'Starts OAuth to grant Google Sheets access.',
          ko: 'Starts OAuth to grant Google Sheets access.',
          hi: 'Starts OAuth to grant Google Sheets access.',
          nl: 'Starts OAuth to grant Google Sheets access.',
          sv: 'Starts OAuth to grant Google Sheets access.',
          vi: 'Starts OAuth to grant Google Sheets access.',
          id: 'Starts OAuth to grant Google Sheets access.',
        }),
      },
      step2Card: {
        title: t({
          ru: 'Шаг 2: Apps Script',
          en: 'Step 2: Apps Script',
          kk: '2-қадам: Apps Script',
          de: 'Schritt 2: Apps Script',
          fr: 'Étape 2 : Apps Script',
          es: 'Paso 2: Apps Script',
          pt: 'Passo 2: Apps Script',
          tr: 'Adım 2: Apps Script',
          uk: 'Крок 2: Apps Script',
          zh: '第 2 步：Apps Script',
          ar: 'الخطوة 2: Apps Script',
          pl: 'Krok 2: Apps Script',
          it: 'Passo 2: Apps Script',
          sk: 'Krok 2: Apps Script',
          ja: 'Step 2: Apps Script',
          ko: 'Step 2: Apps Script',
          hi: 'Step 2: Apps Script',
          nl: 'Step 2: Apps Script',
          sv: 'Step 2: Apps Script',
          vi: 'Step 2: Apps Script',
          id: 'Step 2: Apps Script',
        }),
        description: t({
          ru: 'Добавьте Apps Script, чтобы отправлять вебхуки при изменениях.',
          en: 'Add Apps Script to send webhooks on changes.',
          kk: 'Өзгерістерде вебхук жіберу үшін Apps Script қосыңыз.',
          de: 'Fügen Sie Apps Script hinzu, um Webhooks bei Änderungen zu senden.',
          fr: 'Ajoutez Apps Script pour envoyer des webhooks lors des modifications.',
          es: 'Agregue Apps Script para enviar webhooks ante cambios.',
          pt: 'Adicione o Apps Script para enviar webhooks em alterações.',
          tr: 'Değişikliklerde webhook göndermek için Apps Script ekleyin.',
          uk: 'Додайте Apps Script для відправки вебхуків при змінах.',
          zh: '添加 Apps Script 以在更改时发送 webhook。',
          ar: 'أضف Apps Script لإرسال webhooks عند التغييرات.',
          pl: 'Dodaj Apps Script, aby wysyłać webhooki przy zmianach.',
          it: 'Aggiungi Apps Script per inviare webhook in caso di modifiche.',
          sk: 'Dodaj Apps Script, aby wysyłać webhooki przy zmianach.',
          ja: 'Add Apps Script to send webhooks on changes.',
          ko: 'Add Apps Script to send webhooks on changes.',
          hi: 'Add Apps Script to send webhooks on changes.',
          nl: 'Add Apps Script to send webhooks on changes.',
          sv: 'Add Apps Script to send webhooks on changes.',
          vi: 'Add Apps Script to send webhooks on changes.',
          id: 'Add Apps Script to send webhooks on changes.',
        }),
      },
      appsScript: {
        title: t({
          ru: 'Инструкция Apps Script',
          en: 'Apps Script guide',
          kk: 'Apps Script нұсқаулығы',
          de: 'Apps Script-Anleitung',
          fr: 'Guide Apps Script',
          es: 'Guía de Apps Script',
          pt: 'Guia do Apps Script',
          tr: 'Apps Script kılavuzu',
          uk: 'Інструкція Apps Script',
          zh: 'Apps Script 指南',
          ar: 'دليل Apps Script',
          pl: 'Przewodnik Apps Script',
          it: 'Guida Apps Script',
          sk: 'Przewodnik Apps Script',
          ja: 'Apps Script guide',
          ko: 'Apps Script guide',
          hi: 'Apps Script guide',
          nl: 'Apps Script guide',
          sv: 'Apps Script guide',
          vi: 'Apps Script guide',
          id: 'Apps Script guide',
        }),
        description: t({
          ru: 'Откройте документацию и следуйте шагам настройки.',
          en: 'Open the documentation and follow the setup steps.',
          kk: 'Құжаттаманы ашып, баптау қадамдарын орындаңыз.',
          de: 'Öffnen Sie die Dokumentation und folgen Sie den Einrichtungsschritten.',
          fr: 'Ouvrez la documentation et suivez les étapes de configuration.',
          es: 'Abra la documentación y siga los pasos de configuración.',
          pt: 'Abra a documentação e siga os passos de configuração.',
          tr: 'Belgeleri açın ve kurulum adımlarını izleyin.',
          uk: 'Відкрийте документацію та дотримуйтесь кроків налаштування.',
          zh: '打开文档并按照设置步骤操作。',
          ar: 'افتح الوثائق واتبع خطوات الإعداد.',
          pl: 'Otwórz dokumentację i postępuj zgodnie z krokami konfiguracji.',
          it: 'Apri la documentazione e segui i passaggi di configurazione.',
          sk: 'Otwórz dokumentację i postępuj zgodnie z krokami konfiguracji.',
          ja: 'Open the documentation and follow the setup steps.',
          ko: 'Open the documentation and follow the setup steps.',
          hi: 'Open the documentation and follow the setup steps.',
          nl: 'Open the documentation and follow the setup steps.',
          sv: 'Open the documentation and follow the setup steps.',
          vi: 'Open the documentation and follow the setup steps.',
          id: 'Open the documentation and follow the setup steps.',
        }),
      },
      listCard: {
        title: t({
          ru: 'Подключённые таблицы',
          en: 'Connected sheets',
          kk: 'Қосылған кестелер',
          de: 'Verbundene Tabellen',
          fr: 'Feuilles connectées',
          es: 'Hojas conectadas',
          pt: 'Planilhas conectadas',
          tr: 'Bağlı sayfalar',
          uk: 'Підключені таблиці',
          zh: '已连接的工作表',
          ar: 'جداول البيانات المتصلة',
          pl: 'Połączone arkusze',
          it: 'Fogli connessi',
          sk: 'Połączone arkusze',
          ja: 'Connected sheets',
          ko: 'Connected sheets',
          hi: 'Connected sheets',
          nl: 'Connected sheets',
          sv: 'Connected sheets',
          vi: 'Connected sheets',
          id: 'Connected sheets',
        }),
        description: t({
          ru: 'Здесь отображаются все активные подключения.',
          en: 'All active connections are listed here.',
          kk: 'Барлық белсенді қосылымдар осында көрсетіледі.',
          de: 'Alle aktiven Verbindungen werden hier aufgelistet.',
          fr: 'Toutes les connexions actives sont listées ici.',
          es: 'Todas las conexiones activas se listan aquí.',
          pt: 'Todas as conexões ativas estão listadas aqui.',
          tr: 'Tüm aktif bağlantılar burada listelenir.',
          uk: 'Тут відображаються всі активні підключення.',
          zh: '所有活动连接均在此列出。',
          ar: 'جميع الاتصالات النشطة مدرجة هنا.',
          pl: 'Wszystkie aktywne połączenia są tutaj wymienione.',
          it: 'Tutte le connessioni attive sono elencate qui.',
          sk: 'Wszystkie aktywne połączenia są tutaj wymienione.',
          ja: 'All active connections are listed here.',
          ko: 'All active connections are listed here.',
          hi: 'All active connections are listed here.',
          nl: 'All active connections are listed here.',
          sv: 'All active connections are listed here.',
          vi: 'All active connections are listed here.',
          id: 'All active connections are listed here.',
        }),
      },
      connectionCard: {
        title: t({
          ru: 'Карточка подключения',
          en: 'Connection card',
          kk: 'Қосылым карточкасы',
          de: 'Verbindungskarte',
          fr: 'Carte de connexion',
          es: 'Tarjeta de conexión',
          pt: 'Cartão de conexão',
          tr: 'Bağlantı kartı',
          uk: 'Картка підключення',
          zh: '连接卡片',
          ar: 'بطاقة الاتصال',
          pl: 'Karta połączenia',
          it: 'Scheda connessione',
          sk: 'Karta połączenia',
          ja: 'Connection card',
          ko: 'Connection card',
          hi: 'Connection card',
          nl: 'Connection card',
          sv: 'Connection card',
          vi: 'Connection card',
          id: 'Connection card',
        }),
        description: t({
          ru: 'Показывает статус OAuth, ID таблицы и дату синхронизации.',
          en: 'Shows OAuth status, sheet ID, and last sync.',
          kk: 'OAuth күйі, кесте ID және соңғы синхрон уақыты көрсетіледі.',
          de: 'Zeigt OAuth-Status, Tabellen-ID und letzte Synchronisierung.',
          fr: "Affiche le statut OAuth, l'ID de la feuille et la dernière synchronisation.",
          es: 'Muestra el estado OAuth, ID de la hoja y la última sincronización.',
          pt: 'Mostra o status OAuth, ID da planilha e última sincronização.',
          tr: 'OAuth durumunu, sayfa kimliğini ve son senkronizasyonu gösterir.',
          uk: 'Показує статус OAuth, ID таблиці та дату синхронізації.',
          zh: '显示 OAuth 状态、工作表 ID 和上次同步时间。',
          ar: 'يعرض حالة OAuth ومعرف جدول البيانات وآخر مزامنة.',
          pl: 'Pokazuje status OAuth, ID arkusza i ostatnią synchronizację.',
          it: "Mostra lo stato OAuth, l'ID del foglio e l'ultima sincronizzazione.",
          sk: 'Pokazuje status OAuth, ID arkusza i ostatnią synchronizację.',
          ja: 'Shows OAuth status, sheet ID, and last sync.',
          ko: 'Shows OAuth status, sheet ID, and last sync.',
          hi: 'Shows OAuth status, sheet ID, and last sync.',
          nl: 'Shows OAuth status, sheet ID, and last sync.',
          sv: 'Shows OAuth status, sheet ID, and last sync.',
          vi: 'Shows OAuth status, sheet ID, and last sync.',
          id: 'Shows OAuth status, sheet ID, and last sync.',
        }),
      },
      authorize: {
        title: t({
          ru: 'Повторная авторизация',
          en: 'Re-authorize',
          kk: 'Қайта авторизациялау',
          de: 'Erneut autorisieren',
          fr: 'Ré-autoriser',
          es: 'Volver a autorizar',
          pt: 'Reautorizar',
          tr: 'Yeniden yetkilendir',
          uk: 'Повторна авторизація',
          zh: '重新授权',
          ar: 'إعادة التفويض',
          pl: 'Ponowna autoryzacja',
          it: 'Ri-autorizza',
          sk: 'Ponowna autoryzacja',
          ja: 'Re-authorize',
          ko: 'Re-authorize',
          hi: 'Re-authorize',
          nl: 'Re-authorize',
          sv: 'Re-authorize',
          vi: 'Re-authorize',
          id: 'Re-authorize',
        }),
        description: t({
          ru: 'Появляется, если OAuth требуется повторно.',
          en: 'Appears when OAuth needs to be refreshed.',
          kk: 'OAuth қайта қажет болғанда шығады.',
          de: 'Erscheint, wenn OAuth aktualisiert werden muss.',
          fr: "Apparaît lorsqu'OAuth doit être actualisé.",
          es: 'Aparece cuando OAuth necesita ser actualizado.',
          pt: 'Aparece quando o OAuth precisa ser atualizado.',
          tr: "OAuth'ın yenilenmesi gerektiğinde görünür.",
          uk: "З'являється, якщо OAuth потребує повторного підтвердження.",
          zh: '当 OAuth 需要刷新时显示。',
          ar: 'يظهر عند الحاجة إلى تحديث OAuth.',
          pl: 'Pojawia się gdy OAuth wymaga odświeżenia.',
          it: 'Appare quando OAuth deve essere aggiornato.',
          sk: 'Pojawia się gdy OAuth wymaga odświeżenia.',
          ja: 'Appears when OAuth needs to be refreshed.',
          ko: 'Appears when OAuth needs to be refreshed.',
          hi: 'Appears when OAuth needs to be refreshed.',
          nl: 'Appears when OAuth needs to be refreshed.',
          sv: 'Appears when OAuth needs to be refreshed.',
          vi: 'Appears when OAuth needs to be refreshed.',
          id: 'Appears when OAuth needs to be refreshed.',
        }),
      },
      sync: {
        title: t({
          ru: 'Синхронизация',
          en: 'Sync',
          kk: 'Синхрондау',
          de: 'Synchronisierung',
          fr: 'Synchronisation',
          es: 'Sincronización',
          pt: 'Sincronização',
          tr: 'Senkronizasyon',
          uk: 'Синхронізація',
          zh: '同步',
          ar: 'المزامنة',
          pl: 'Synchronizacja',
          it: 'Sincronizzazione',
          sk: 'Synchronizacja',
          ja: 'Sync',
          ko: 'Sync',
          hi: 'Sync',
          nl: 'Sync',
          sv: 'Sync',
          vi: 'Sync',
          id: 'Sync',
        }),
        description: t({
          ru: 'Запускает принудительную синхронизацию данных.',
          en: 'Triggers a manual sync of data.',
          kk: 'Деректерді қолмен синхрондауды іске қосады.',
          de: 'Löst eine manuelle Datensynchronisierung aus.',
          fr: 'Déclenche une synchronisation manuelle des données.',
          es: 'Activa una sincronización manual de datos.',
          pt: 'Aciona uma sincronização manual dos dados.',
          tr: 'Manuel veri senkronizasyonunu tetikler.',
          uk: 'Запускає примусову синхронізацію даних.',
          zh: '触发手动数据同步。',
          ar: 'يُشغّل مزامنة يدوية للبيانات.',
          pl: 'Uruchamia ręczną synchronizację danych.',
          it: 'Attiva una sincronizzazione manuale dei dati.',
          sk: 'Uruchamia ręczną synchronizację danych.',
          ja: 'Triggers a manual sync of data.',
          ko: 'Triggers a manual sync of data.',
          hi: 'Triggers a manual sync of data.',
          nl: 'Triggers a manual sync of data.',
          sv: 'Triggers a manual sync of data.',
          vi: 'Triggers a manual sync of data.',
          id: 'Triggers a manual sync of data.',
        }),
      },
      disconnect: {
        title: t({
          ru: 'Отключить',
          en: 'Disconnect',
          kk: 'Ажырату',
          de: 'Trennen',
          fr: 'Déconnecter',
          es: 'Desconectar',
          pt: 'Desconectar',
          tr: 'Bağlantıyı kes',
          uk: 'Відключити',
          zh: '断开连接',
          ar: 'قطع الاتصال',
          pl: 'Rozłącz',
          it: 'Disconnetti',
          sk: 'Rozłącz',
          ja: 'Disconnect',
          ko: 'Disconnect',
          hi: 'Disconnect',
          nl: 'Disconnect',
          sv: 'Disconnect',
          vi: 'Disconnect',
          id: 'Disconnect',
        }),
        description: t({
          ru: 'Удаляет подключение и останавливает синхронизацию.',
          en: 'Removes the connection and stops syncing.',
          kk: 'Қосылымды жояды және синхрондауды тоқтатады.',
          de: 'Entfernt die Verbindung und stoppt die Synchronisierung.',
          fr: 'Supprime la connexion et arrête la synchronisation.',
          es: 'Elimina la conexión y detiene la sincronización.',
          pt: 'Remove a conexão e para a sincronização.',
          tr: 'Bağlantıyı kaldırır ve senkronizasyonu durdurur.',
          uk: 'Видаляє підключення і зупиняє синхронізацію.',
          zh: '移除连接并停止同步。',
          ar: 'يزيل الاتصال ويوقف المزامنة.',
          pl: 'Usuwa połączenie i zatrzymuje synchronizację.',
          it: 'Rimuove la connessione e interrompe la sincronizzazione.',
          sk: 'Usuwa połączenie i zatrzymuje synchronizację.',
          ja: 'Removes the connection and stops syncing.',
          ko: 'Removes the connection and stops syncing.',
          hi: 'Removes the connection and stops syncing.',
          nl: 'Removes the connection and stops syncing.',
          sv: 'Removes the connection and stops syncing.',
          vi: 'Removes the connection and stops syncing.',
          id: 'Removes the connection and stops syncing.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'Done',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Concluído',
          tr: 'Tamamlandı',
          uk: 'Готово',
          zh: '完成',
          ar: 'تم',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Gotowe',
          ja: 'Done',
          ko: 'Done',
          hi: 'Done',
          nl: 'Done',
          sv: 'Done',
          vi: 'Done',
          id: 'Done',
        }),
        description: t({
          ru: 'Теперь вы можете подключать и управлять Google Sheets.',
          en: 'You can now connect and manage Google Sheets.',
          kk: 'Енді Google Sheets-ті қосып, басқара аласыз.',
          de: 'Sie können jetzt Google Sheets verbinden und verwalten.',
          fr: 'Vous pouvez maintenant connecter et gérer Google Sheets.',
          es: 'Ahora puede conectar y gestionar Google Sheets.',
          pt: 'Agora você pode conectar e gerenciar o Google Sheets.',
          tr: "Artık Google Sheets'i bağlayabilir ve yönetebilirsiniz.",
          uk: 'Тепер ви можете підключати Google Sheets та керувати ними.',
          zh: '您现在可以连接和管理 Google Sheets。',
          ar: 'يمكنك الآن توصيل Google Sheets وإدارتها.',
          pl: 'Możesz teraz łączyć i zarządzać Google Sheets.',
          it: 'Ora puoi connettere e gestire Google Sheets.',
          sk: 'Możesz teraz łączyć i zarządzać Google Sheets.',
          ja: 'You can now connect and manage Google Sheets.',
          ko: 'You can now connect and manage Google Sheets.',
          hi: 'You can now connect and manage Google Sheets.',
          nl: 'You can now connect and manage Google Sheets.',
          sv: 'You can now connect and manage Google Sheets.',
          vi: 'You can now connect and manage Google Sheets.',
          id: 'You can now connect and manage Google Sheets.',
        }),
      },
    },
  },
} satisfies Dictionary;

export default content;
