import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'google-sheets-import-tour-content',
  content: {
    name: t({
      ru: 'Тур по импорту из Google Sheets',
      en: 'Google Sheets Import Tour',
      kk: 'Google Sheets импорт туры',
      de: 'Google Sheets Import-Tour',
      fr: "Visite d'importation Google Sheets",
      es: 'Tour de importación de Google Sheets',
      pt: 'Tour de importação do Google Sheets',
      tr: 'Google Sheets İçe Aktarma Turu',
      uk: 'Тур по імпорту з Google Sheets',
      zh: 'Google Sheets 导入导览',
      ar: 'جولة استيراد Google Sheets',
      pl: 'Tour importu Google Sheets',
      it: 'Tour importazione Google Sheets',
      sk: 'Tour importu Google Sheets',
      ja: 'Google Sheets Import Tour',
      ko: 'Google Sheets Import Tour',
      hi: 'Google Sheets Import Tour',
      nl: 'Google Sheets Import Tour',
      sv: 'Google Sheets Import Tour',
      vi: 'Google Sheets Import Tour',
      id: 'Google Sheets Import Tour',
    }),
    description: t({
      ru: 'Пошаговый обзор настроек импорта и создания таблицы.',
      en: 'A step-by-step overview of import settings and table creation.',
      kk: 'Импорт баптаулары мен кесте құрудың қадамдық шолуы.',
      de: 'Eine schrittweise Übersicht der Importeinstellungen und Tabellenerstellung.',
      fr: "Un aperçu étape par étape des paramètres d'importation et de la création de tableau.",
      es: 'Una descripción paso a paso de la configuración de importación y la creación de tablas.',
      pt: 'Uma visão passo a passo das configurações de importação e criação de tabelas.',
      tr: 'İçe aktarma ayarları ve tablo oluşturmanın adım adım genel bakışı.',
      uk: 'Покроковий огляд налаштувань імпорту та створення таблиці.',
      zh: '导入设置和表格创建的逐步概览。',
      ar: 'نظرة عامة خطوة بخطوة على إعدادات الاستيراد وإنشاء الجدول.',
      pl: 'Przegląd krok po kroku ustawień importu i tworzenia tabeli.',
      it: 'Una panoramica passo dopo passo delle impostazioni di importazione e della creazione di tabelle.',
      sk: 'Przegląd krok po kroku ustawień importu i tworzenia tabeli.',
      ja: 'A step-by-step overview of import settings and table creation.',
      ko: 'A step-by-step overview of import settings and table creation.',
      hi: 'A step-by-step overview of import settings and table creation.',
      nl: 'A step-by-step overview of import settings and table creation.',
      sv: 'A step-by-step overview of import settings and table creation.',
      vi: 'A step-by-step overview of import settings and table creation.',
      id: 'A step-by-step overview of import settings and table creation.',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Импорт из Google Sheets',
          en: 'Import from Google Sheets',
          kk: 'Google Sheets-тен импорт',
          de: 'Import aus Google Sheets',
          fr: 'Importer depuis Google Sheets',
          es: 'Importar desde Google Sheets',
          pt: 'Importar do Google Sheets',
          tr: "Google Sheets'ten İçe Aktar",
          uk: 'Імпорт з Google Sheets',
          zh: '从 Google Sheets 导入',
          ar: 'الاستيراد من Google Sheets',
          pl: 'Importuj z Google Sheets',
          it: 'Importa da Google Sheets',
          sk: 'Importuj z Google Sheets',
          ja: 'Import from Google Sheets',
          ko: 'Import from Google Sheets',
          hi: 'Import from Google Sheets',
          nl: 'Import from Google Sheets',
          sv: 'Import from Google Sheets',
          vi: 'Import from Google Sheets',
          id: 'Import from Google Sheets',
        }),
        description: t({
          ru: 'Этот тур объяснит все шаги: подключение, превью, выбор колонок и импорт.',
          en: 'This tour explains all steps: connection, preview, column setup, and import.',
          kk: 'Бұл тур барлық қадамдарды түсіндіреді: қосылу, превью, бағандар және импорт.',
          de: 'Diese Tour erklärt alle Schritte: Verbindung, Vorschau, Spalteneinrichtung und Import.',
          fr: 'Cette visite explique toutes les étapes : connexion, aperçu, configuration des colonnes et importation.',
          es: 'Este tour explica todos los pasos: conexión, vista previa, configuración de columnas e importación.',
          pt: 'Este tour explica todos os passos: conexão, pré-visualização, configuração de colunas e importação.',
          tr: 'Bu tur tüm adımları açıklar: bağlantı, önizleme, sütun kurulumu ve içe aktarma.',
          uk: 'Цей тур пояснить усі кроки: підключення, попередній перегляд, вибір стовпців та імпорт.',
          zh: '本导览解释所有步骤：连接、预览、列设置和导入。',
          ar: 'تشرح هذه الجولة جميع الخطوات: الاتصال والمعاينة وإعداد الأعمدة والاستيراد.',
          pl: 'Ten przewodnik wyjaśnia wszystkie kroki: połączenie, podgląd, konfigurację kolumn i import.',
          it: 'Questo tour spiega tutti i passaggi: connessione, anteprima, configurazione colonne e importazione.',
          sk: 'Ten przewodnik wyjaśnia wszystkie kroki: połączenie, podgląd, konfigurację kolumn i import.',
          ja: 'This tour explains all steps: connection, preview, column setup, and import.',
          ko: 'This tour explains all steps: connection, preview, column setup, and import.',
          hi: 'This tour explains all steps: connection, preview, column setup, and import.',
          nl: 'This tour explains all steps: connection, preview, column setup, and import.',
          sv: 'This tour explains all steps: connection, preview, column setup, and import.',
          vi: 'This tour explains all steps: connection, preview, column setup, and import.',
          id: 'This tour explains all steps: connection, preview, column setup, and import.',
        }),
      },
      backLink: {
        title: t({
          ru: 'Назад к таблицам',
          en: 'Back to tables',
          kk: 'Кестелерге оралу',
          de: 'Zurück zu den Tabellen',
          fr: 'Retour aux tableaux',
          es: 'Volver a las tablas',
          pt: 'Voltar às tabelas',
          tr: 'Tablolara dön',
          uk: 'Повернутись до таблиць',
          zh: '返回表格',
          ar: 'العودة إلى الجداول',
          pl: 'Powrót do tabel',
          it: 'Torna alle tabelle',
          sk: 'Powrót do tabel',
          ja: 'Back to tables',
          ko: 'Back to tables',
          hi: 'Back to tables',
          nl: 'Back to tables',
          sv: 'Back to tables',
          vi: 'Back to tables',
          id: 'Back to tables',
        }),
        description: t({
          ru: 'Ссылка возвращает в список пользовательских таблиц.',
          en: 'This link returns to the custom tables list.',
          kk: 'Бұл сілтеме пайдаланушы кестелері тізіміне қайтарады.',
          de: 'Dieser Link kehrt zur Liste der benutzerdefinierten Tabellen zurück.',
          fr: 'Ce lien revient à la liste des tableaux personnalisés.',
          es: 'Este enlace regresa a la lista de tablas personalizadas.',
          pt: 'Este link retorna à lista de tabelas personalizadas.',
          tr: 'Bu bağlantı özel tablolar listesine geri döner.',
          uk: 'Це посилання повертає до списку користувацьких таблиць.',
          zh: '此链接返回自定义表格列表。',
          ar: 'يعود هذا الرابط إلى قائمة الجداول المخصصة.',
          pl: 'Ten link wraca do listy niestandardowych tabel.',
          it: "Questo link torna all'elenco delle tabelle personalizzate.",
          sk: 'Ten link wraca do listy niestandardowych tabel.',
          ja: 'This link returns to the custom tables list.',
          ko: 'This link returns to the custom tables list.',
          hi: 'This link returns to the custom tables list.',
          nl: 'This link returns to the custom tables list.',
          sv: 'This link returns to the custom tables list.',
          vi: 'This link returns to the custom tables list.',
          id: 'This link returns to the custom tables list.',
        }),
      },
      sourceCard: {
        title: t({
          ru: 'Источник данных',
          en: 'Data source',
          kk: 'Дерек көзі',
          de: 'Datenquelle',
          fr: 'Source de données',
          es: 'Fuente de datos',
          pt: 'Fonte de dados',
          tr: 'Veri kaynağı',
          uk: 'Джерело даних',
          zh: '数据源',
          ar: 'مصدر البيانات',
          pl: 'Źródło danych',
          it: 'Sorgente dati',
          sk: 'Źródło danych',
          ja: 'Data source',
          ko: 'Data source',
          hi: 'Data source',
          nl: 'Data source',
          sv: 'Data source',
          vi: 'Data source',
          id: 'Data source',
        }),
        description: t({
          ru: 'Здесь выбирается подключение и параметры чтения листа.',
          en: 'Select a connection and sheet reading parameters here.',
          kk: 'Мұнда қосылым мен парақ оқу параметрлері таңдалады.',
          de: 'Hier werden Verbindung und Blatt-Leseparameter ausgewählt.',
          fr: 'Sélectionnez ici une connexion et les paramètres de lecture de feuille.',
          es: 'Seleccione aquí una conexión y los parámetros de lectura de hoja.',
          pt: 'Selecione aqui uma conexão e os parâmetros de leitura da planilha.',
          tr: 'Buradan bir bağlantı ve sayfa okuma parametreleri seçin.',
          uk: 'Тут обирається підключення та параметри зчитування аркуша.',
          zh: '在此选择连接和工作表读取参数。',
          ar: 'حدد هنا اتصالاً ومعلمات قراءة الورقة.',
          pl: 'Tutaj wybierz połączenie i parametry odczytu arkusza.',
          it: 'Seleziona qui una connessione e i parametri di lettura del foglio.',
          sk: 'Tutaj wybierz połączenie i parametry odczytu arkusza.',
          ja: 'Select a connection and sheet reading parameters here.',
          ko: 'Select a connection and sheet reading parameters here.',
          hi: 'Select a connection and sheet reading parameters here.',
          nl: 'Select a connection and sheet reading parameters here.',
          sv: 'Select a connection and sheet reading parameters here.',
          vi: 'Select a connection and sheet reading parameters here.',
          id: 'Select a connection and sheet reading parameters here.',
        }),
      },
      connection: {
        title: t({
          ru: 'Подключение',
          en: 'Connection',
          kk: 'Қосылым',
          de: 'Verbindung',
          fr: 'Connexion',
          es: 'Conexión',
          pt: 'Conexão',
          tr: 'Bağlantı',
          uk: 'Підключення',
          zh: '连接',
          ar: 'الاتصال',
          pl: 'Połączenie',
          it: 'Connessione',
          sk: 'Połączenie',
          ja: 'Connection',
          ko: 'Connection',
          hi: 'Connection',
          nl: 'Connection',
          sv: 'Connection',
          vi: 'Connection',
          id: 'Connection',
        }),
        description: t({
          ru: 'Выберите Google Sheets подключение, которое хотите импортировать.',
          en: 'Choose the Google Sheets connection you want to import.',
          kk: 'Импорттағыңыз келетін Google Sheets қосылымын таңдаңыз.',
          de: 'Wählen Sie die Google Sheets-Verbindung, die Sie importieren möchten.',
          fr: 'Choisissez la connexion Google Sheets que vous souhaitez importer.',
          es: 'Elija la conexión de Google Sheets que desea importar.',
          pt: 'Escolha a conexão do Google Sheets que deseja importar.',
          tr: 'İçe aktarmak istediğiniz Google Sheets bağlantısını seçin.',
          uk: 'Оберіть підключення Google Sheets, яке хочете імпортувати.',
          zh: '选择您要导入的 Google Sheets 连接。',
          ar: 'اختر اتصال Google Sheets الذي تريد استيراده.',
          pl: 'Wybierz połączenie Google Sheets, które chcesz zaimportować.',
          it: 'Scegli la connessione Google Sheets che vuoi importare.',
          sk: 'Wybierz połączenie Google Sheets, które chcesz zaimportować.',
          ja: 'Choose the Google Sheets connection you want to import.',
          ko: 'Choose the Google Sheets connection you want to import.',
          hi: 'Choose the Google Sheets connection you want to import.',
          nl: 'Choose the Google Sheets connection you want to import.',
          sv: 'Choose the Google Sheets connection you want to import.',
          vi: 'Choose the Google Sheets connection you want to import.',
          id: 'Choose the Google Sheets connection you want to import.',
        }),
      },
      worksheet: {
        title: t({
          ru: 'Лист',
          en: 'Worksheet',
          kk: 'Парақ',
          de: 'Arbeitsblatt',
          fr: 'Feuille de calcul',
          es: 'Hoja de cálculo',
          pt: 'Planilha',
          tr: 'Çalışma sayfası',
          uk: 'Аркуш',
          zh: '工作表',
          ar: 'ورقة العمل',
          pl: 'Arkusz',
          it: 'Foglio di lavoro',
          sk: 'Arkusz',
          ja: 'Worksheet',
          ko: 'Worksheet',
          hi: 'Worksheet',
          nl: 'Worksheet',
          sv: 'Worksheet',
          vi: 'Worksheet',
          id: 'Worksheet',
        }),
        description: t({
          ru: 'Укажите имя листа (worksheet). Если оставить пустым, будет выбран лист по умолчанию.',
          en: 'Enter a worksheet name. Leave empty to use the default sheet.',
          kk: 'Парақ атауын енгізіңіз. Бос қалдырсаңыз, әдепкі парақ алынады.',
          de: 'Geben Sie einen Arbeitsblattnamen ein. Leer lassen, um das Standardblatt zu verwenden.',
          fr: 'Entrez un nom de feuille. Laissez vide pour utiliser la feuille par défaut.',
          es: 'Ingrese un nombre de hoja. Déjelo vacío para usar la hoja predeterminada.',
          pt: 'Digite um nome de planilha. Deixe em branco para usar a planilha padrão.',
          tr: 'Bir çalışma sayfası adı girin. Varsayılan sayfayı kullanmak için boş bırakın.',
          uk: 'Вкажіть назву аркуша. Залиште порожнім, щоб використати аркуш за замовчуванням.',
          zh: '输入工作表名称。留空则使用默认工作表。',
          ar: 'أدخل اسم ورقة العمل. اتركه فارغاً لاستخدام الورقة الافتراضية.',
          pl: 'Podaj nazwę arkusza. Zostaw puste, aby użyć domyślnego arkusza.',
          it: 'Inserisci un nome foglio di lavoro. Lascia vuoto per usare il foglio predefinito.',
          sk: 'Podaj nazwę arkusza. Zostaw puste, aby użyć domyślnego arkusza.',
          ja: 'Enter a worksheet name. Leave empty to use the default sheet.',
          ko: 'Enter a worksheet name. Leave empty to use the default sheet.',
          hi: 'Enter a worksheet name. Leave empty to use the default sheet.',
          nl: 'Enter a worksheet name. Leave empty to use the default sheet.',
          sv: 'Enter a worksheet name. Leave empty to use the default sheet.',
          vi: 'Enter a worksheet name. Leave empty to use the default sheet.',
          id: 'Enter a worksheet name. Leave empty to use the default sheet.',
        }),
      },
      range: {
        title: t({
          ru: 'Диапазон',
          en: 'Range',
          kk: 'Диапазон',
          de: 'Bereich',
          fr: 'Plage',
          es: 'Rango',
          pt: 'Intervalo',
          tr: 'Aralık',
          uk: 'Діапазон',
          zh: '范围',
          ar: 'النطاق',
          pl: 'Zakres',
          it: 'Intervallo',
          sk: 'Zakres',
          ja: 'Range',
          ko: 'Range',
          hi: 'Range',
          nl: 'Range',
          sv: 'Range',
          vi: 'Range',
          id: 'Range',
        }),
        description: t({
          ru: 'Определите диапазон данных (например A1:Z200), чтобы ограничить импорт.',
          en: 'Define a data range (e.g., A1:Z200) to limit the import.',
          kk: 'Импортты шектеу үшін деректер диапазонын көрсетіңіз (мысалы A1:Z200).',
          de: 'Definieren Sie einen Datenbereich (z. B. A1:Z200), um den Import zu begrenzen.',
          fr: "Définissez une plage de données (par ex. A1:Z200) pour limiter l'importation.",
          es: 'Defina un rango de datos (p. ej., A1:Z200) para limitar la importación.',
          pt: 'Defina um intervalo de dados (ex.: A1:Z200) para limitar a importação.',
          tr: 'İçe aktarmayı sınırlamak için bir veri aralığı tanımlayın (örn. A1:Z200).',
          uk: 'Визначте діапазон даних (наприклад A1:Z200), щоб обмежити імпорт.',
          zh: '定义数据范围（例如 A1:Z200）以限制导入范围。',
          ar: 'حدد نطاق البيانات (مثلاً A1:Z200) لتقييد الاستيراد.',
          pl: 'Zdefiniuj zakres danych (np. A1:Z200), aby ograniczyć import.',
          it: "Definisci un intervallo di dati (es. A1:Z200) per limitare l'importazione.",
          sk: 'Zdefiniuj zakres danych (np. A1:Z200), aby ograniczyć import.',
          ja: 'Define a data range (e.g., A1:Z200) to limit the import.',
          ko: 'Define a data range (e.g., A1:Z200) to limit the import.',
          hi: 'Define a data range (e.g., A1:Z200) to limit the import.',
          nl: 'Define a data range (e.g., A1:Z200) to limit the import.',
          sv: 'Define a data range (e.g., A1:Z200) to limit the import.',
          vi: 'Define a data range (e.g., A1:Z200) to limit the import.',
          id: 'Define a data range (e.g., A1:Z200) to limit the import.',
        }),
      },
      headerOffset: {
        title: t({
          ru: 'Смещение заголовка',
          en: 'Header offset',
          kk: 'Тақырып ығысуы',
          de: 'Kopfzeilenversatz',
          fr: "Décalage d'en-tête",
          es: 'Desplazamiento de encabezado',
          pt: 'Deslocamento do cabeçalho',
          tr: 'Başlık ofseti',
          uk: 'Зміщення заголовка',
          zh: '标题偏移',
          ar: 'إزاحة الرأس',
          pl: 'Przesunięcie nagłówka',
          it: 'Offset intestazione',
          sk: 'Przesunięcie nagłówka',
          ja: 'Header offset',
          ko: 'Header offset',
          hi: 'Header offset',
          nl: 'Header offset',
          sv: 'Header offset',
          vi: 'Header offset',
          id: 'Header offset',
        }),
        description: t({
          ru: 'Укажите номер строки заголовка, чтобы корректно определить названия колонок.',
          en: 'Set the header row index to detect column names correctly.',
          kk: 'Баған атауларын дұрыс анықтау үшін тақырып жолын көрсетіңіз.',
          de: 'Legen Sie den Kopfzeilenindex fest, um Spaltennamen korrekt zu erkennen.',
          fr: "Définissez l'index de la ligne d'en-tête pour détecter correctement les noms de colonnes.",
          es: 'Establezca el índice de fila de encabezado para detectar correctamente los nombres de columnas.',
          pt: 'Defina o índice da linha de cabeçalho para detectar os nomes das colunas corretamente.',
          tr: 'Sütun adlarını doğru algılamak için başlık satırı dizinini ayarlayın.',
          uk: 'Вкажіть номер рядка заголовка для коректного визначення назв стовпців.',
          zh: '设置标题行索引以正确检测列名。',
          ar: 'حدد فهرس صف الرأس للكشف عن أسماء الأعمدة بشكل صحيح.',
          pl: 'Ustaw indeks wiersza nagłówka, aby poprawnie wykryć nazwy kolumn.',
          it: "Imposta l'indice della riga di intestazione per rilevare correttamente i nomi delle colonne.",
          sk: 'Ustaw indeks wiersza nagłówka, aby poprawnie wykryć nazwy kolumn.',
          ja: 'Set the header row index to detect column names correctly.',
          ko: 'Set the header row index to detect column names correctly.',
          hi: 'Set the header row index to detect column names correctly.',
          nl: 'Set the header row index to detect column names correctly.',
          sv: 'Set the header row index to detect column names correctly.',
          vi: 'Set the header row index to detect column names correctly.',
          id: 'Set the header row index to detect column names correctly.',
        }),
      },
      layout: {
        title: t({
          ru: 'Тип раскладки',
          en: 'Layout type',
          kk: 'Орналасу түрі',
          de: 'Layout-Typ',
          fr: 'Type de disposition',
          es: 'Tipo de diseño',
          pt: 'Tipo de layout',
          tr: 'Düzen türü',
          uk: 'Тип розкладки',
          zh: '布局类型',
          ar: 'نوع التخطيط',
          pl: 'Typ układu',
          it: 'Tipo di layout',
          sk: 'Typ układu',
          ja: 'Layout type',
          ko: 'Layout type',
          hi: 'Layout type',
          nl: 'Layout type',
          sv: 'Layout type',
          vi: 'Layout type',
          id: 'Layout type',
        }),
        description: t({
          ru: 'Выберите раскладку данных для корректной интерпретации таблицы.',
          en: 'Choose a layout so the data is interpreted correctly.',
          kk: 'Деректер дұрыс түсіндірілуі үшін орналасу түрін таңдаңыз.',
          de: 'Wählen Sie ein Layout, damit die Daten korrekt interpretiert werden.',
          fr: 'Choisissez une disposition pour que les données soient interprétées correctement.',
          es: 'Elija un diseño para que los datos se interpreten correctamente.',
          pt: 'Escolha um layout para que os dados sejam interpretados corretamente.',
          tr: 'Verilerin doğru yorumlanması için bir düzen seçin.',
          uk: 'Оберіть тип розкладки для коректної інтерпретації таблиці.',
          zh: '选择布局以便正确解析数据。',
          ar: 'اختر تخطيطاً حتى يتم تفسير البيانات بشكل صحيح.',
          pl: 'Wybierz układ, aby dane były poprawnie interpretowane.',
          it: 'Scegli un layout affinché i dati vengano interpretati correttamente.',
          sk: 'Wybierz układ, aby dane były poprawnie interpretowane.',
          ja: 'Choose a layout so the data is interpreted correctly.',
          ko: 'Choose a layout so the data is interpreted correctly.',
          hi: 'Choose a layout so the data is interpreted correctly.',
          nl: 'Choose a layout so the data is interpreted correctly.',
          sv: 'Choose a layout so the data is interpreted correctly.',
          vi: 'Choose a layout so the data is interpreted correctly.',
          id: 'Choose a layout so the data is interpreted correctly.',
        }),
      },
      previewButton: {
        title: t({
          ru: 'Сделать превью',
          en: 'Generate preview',
          kk: 'Превью жасау',
          de: 'Vorschau generieren',
          fr: 'Générer un aperçu',
          es: 'Generar vista previa',
          pt: 'Gerar pré-visualização',
          tr: 'Önizleme oluştur',
          uk: 'Згенерувати попередній перегляд',
          zh: '生成预览',
          ar: 'إنشاء معاينة',
          pl: 'Generuj podgląd',
          it: 'Genera anteprima',
          sk: 'Generuj podgląd',
          ja: 'Generate preview',
          ko: 'Generate preview',
          hi: 'Generate preview',
          nl: 'Generate preview',
          sv: 'Generate preview',
          vi: 'Generate preview',
          id: 'Generate preview',
        }),
        description: t({
          ru: 'Нажмите, чтобы загрузить превью данных и подготовить настройки импорта.',
          en: 'Click to load a data preview and prepare import settings.',
          kk: 'Деректер превьюын жүктеп, импорт баптауларын дайындау үшін басыңыз.',
          de: 'Klicken Sie, um eine Datenvorschau zu laden und Importeinstellungen vorzubereiten.',
          fr: "Cliquez pour charger un aperçu des données et préparer les paramètres d'importation.",
          es: 'Haga clic para cargar una vista previa de datos y preparar la configuración de importación.',
          pt: 'Clique para carregar uma pré-visualização dos dados e preparar as configurações de importação.',
          tr: 'Veri önizlemesi yüklemek ve içe aktarma ayarlarını hazırlamak için tıklayın.',
          uk: 'Натисніть, щоб завантажити попередній перегляд даних та підготувати налаштування імпорту.',
          zh: '单击以加载数据预览并准备导入设置。',
          ar: 'انقر لتحميل معاينة البيانات وإعداد إعدادات الاستيراد.',
          pl: 'Kliknij, aby załadować podgląd danych i przygotować ustawienia importu.',
          it: "Clicca per caricare un'anteprima dei dati e preparare le impostazioni di importazione.",
          sk: 'Kliknij, aby załadować podgląd danych i przygotować ustawienia importu.',
          ja: 'Click to load a data preview and prepare import settings.',
          ko: 'Click to load a data preview and prepare import settings.',
          hi: 'Click to load a data preview and prepare import settings.',
          nl: 'Click to load a data preview and prepare import settings.',
          sv: 'Click to load a data preview and prepare import settings.',
          vi: 'Click to load a data preview and prepare import settings.',
          id: 'Click to load a data preview and prepare import settings.',
        }),
      },
      previewPanel: {
        title: t({
          ru: 'Превью данных',
          en: 'Data preview',
          kk: 'Дерек превьюы',
          de: 'Datenvorschau',
          fr: 'Aperçu des données',
          es: 'Vista previa de datos',
          pt: 'Pré-visualização de dados',
          tr: 'Veri önizlemesi',
          uk: 'Попередній перегляд даних',
          zh: '数据预览',
          ar: 'معاينة البيانات',
          pl: 'Podgląd danych',
          it: 'Anteprima dati',
          sk: 'Podgląd danych',
          ja: 'Data preview',
          ko: 'Data preview',
          hi: 'Data preview',
          nl: 'Data preview',
          sv: 'Data preview',
          vi: 'Data preview',
          id: 'Data preview',
        }),
        description: t({
          ru: 'Здесь отображается превью диапазона и параметры, определенные автоматически.',
          en: 'This panel shows the preview range and detected parameters.',
          kk: 'Мұнда превью диапазоны мен анықталған параметрлер көрсетіледі.',
          de: 'Dieses Panel zeigt den Vorschaubereich und die automatisch erkannten Parameter.',
          fr: "Ce panneau affiche la plage d'aperçu et les paramètres détectés automatiquement.",
          es: 'Este panel muestra el rango de vista previa y los parámetros detectados automáticamente.',
          pt: 'Este painel mostra o intervalo de pré-visualização e os parâmetros detectados automaticamente.',
          tr: 'Bu panel, önizleme aralığını ve otomatik olarak algılanan parametreleri gösterir.',
          uk: 'Тут відображається діапазон попереднього перегляду та автоматично визначені параметри.',
          zh: '此面板显示预览范围和自动检测到的参数。',
          ar: 'تعرض هذه اللوحة نطاق المعاينة والمعلمات المكتشفة تلقائياً.',
          pl: 'Ten panel pokazuje zakres podglądu i automatycznie wykryte parametry.',
          it: "Questo pannello mostra l'intervallo di anteprima e i parametri rilevati automaticamente.",
          sk: 'Ten panel pokazuje zakres podglądu i automatycznie wykryte parametry.',
          ja: 'This panel shows the preview range and detected parameters.',
          ko: 'This panel shows the preview range and detected parameters.',
          hi: 'This panel shows the preview range and detected parameters.',
          nl: 'This panel shows the preview range and detected parameters.',
          sv: 'This panel shows the preview range and detected parameters.',
          vi: 'This panel shows the preview range and detected parameters.',
          id: 'This panel shows the preview range and detected parameters.',
        }),
      },
      columnsPanel: {
        title: t({
          ru: 'Колонки',
          en: 'Columns',
          kk: 'Бағандар',
          de: 'Spalten',
          fr: 'Colonnes',
          es: 'Columnas',
          pt: 'Colunas',
          tr: 'Sütunlar',
          uk: 'Стовпці',
          zh: '列',
          ar: 'الأعمدة',
          pl: 'Kolumny',
          it: 'Colonne',
          sk: 'Kolumny',
          ja: 'Columns',
          ko: 'Columns',
          hi: 'Columns',
          nl: 'Columns',
          sv: 'Columns',
          vi: 'Columns',
          id: 'Columns',
        }),
        description: t({
          ru: 'Настройте какие колонки импортировать и их типы.',
          en: 'Choose which columns to import and their types.',
          kk: 'Импортталатын бағандар мен олардың түрлерін таңдаңыз.',
          de: 'Wählen Sie, welche Spalten importiert werden sollen und ihre Typen.',
          fr: 'Choisissez les colonnes à importer et leurs types.',
          es: 'Elija qué columnas importar y sus tipos.',
          pt: 'Escolha quais colunas importar e seus tipos.',
          tr: 'Hangi sütunların içe aktarılacağını ve türlerini seçin.',
          uk: 'Налаштуйте, які стовпці імпортувати та їх типи.',
          zh: '选择要导入的列及其类型。',
          ar: 'اختر الأعمدة التي تريد استيرادها وأنواعها.',
          pl: 'Wybierz kolumny do zaimportowania i ich typy.',
          it: 'Scegli quali colonne importare e i loro tipi.',
          sk: 'Wybierz kolumny do zaimportowania i ich typy.',
          ja: 'Choose which columns to import and their types.',
          ko: 'Choose which columns to import and their types.',
          hi: 'Choose which columns to import and their types.',
          nl: 'Choose which columns to import and their types.',
          sv: 'Choose which columns to import and their types.',
          vi: 'Choose which columns to import and their types.',
          id: 'Choose which columns to import and their types.',
        }),
      },
      enableAll: {
        title: t({
          ru: 'Включить все',
          en: 'Enable all',
          kk: 'Барлығын қосу',
          de: 'Alle aktivieren',
          fr: 'Tout activer',
          es: 'Habilitar todo',
          pt: 'Habilitar tudo',
          tr: 'Tümünü etkinleştir',
          uk: 'Увімкнути все',
          zh: '启用全部',
          ar: 'تفعيل الكل',
          pl: 'Włącz wszystkie',
          it: 'Abilita tutto',
          sk: 'Włącz wszystkie',
          ja: 'Enable all',
          ko: 'Enable all',
          hi: 'Enable all',
          nl: 'Enable all',
          sv: 'Enable all',
          vi: 'Enable all',
          id: 'Enable all',
        }),
        description: t({
          ru: 'Быстро включить все колонки для импорта.',
          en: 'Quickly enable all columns for import.',
          kk: 'Импорт үшін барлық бағандарды жылдам қосу.',
          de: 'Alle Spalten schnell für den Import aktivieren.',
          fr: "Activer rapidement toutes les colonnes pour l'importation.",
          es: 'Habilitar rápidamente todas las columnas para importación.',
          pt: 'Habilitar rapidamente todas as colunas para importação.',
          tr: 'İçe aktarma için tüm sütunları hızlıca etkinleştirin.',
          uk: 'Швидко увімкнути всі стовпці для імпорту.',
          zh: '快速启用所有列以供导入。',
          ar: 'تفعيل جميع الأعمدة للاستيراد بسرعة.',
          pl: 'Szybko włącz wszystkie kolumny do importu.',
          it: "Abilita rapidamente tutte le colonne per l'importazione.",
          sk: 'Szybko włącz wszystkie kolumny do importu.',
          ja: 'Quickly enable all columns for import.',
          ko: 'Quickly enable all columns for import.',
          hi: 'Quickly enable all columns for import.',
          nl: 'Quickly enable all columns for import.',
          sv: 'Quickly enable all columns for import.',
          vi: 'Quickly enable all columns for import.',
          id: 'Quickly enable all columns for import.',
        }),
      },
      resultCard: {
        title: t({
          ru: 'Результат',
          en: 'Result',
          kk: 'Нәтиже',
          de: 'Ergebnis',
          fr: 'Résultat',
          es: 'Resultado',
          pt: 'Resultado',
          tr: 'Sonuç',
          uk: 'Результат',
          zh: '结果',
          ar: 'النتيجة',
          pl: 'Wynik',
          it: 'Risultato',
          sk: 'Wynik',
          ja: 'Result',
          ko: 'Result',
          hi: 'Result',
          nl: 'Result',
          sv: 'Result',
          vi: 'Result',
          id: 'Result',
        }),
        description: t({
          ru: 'Укажите параметры создаваемой таблицы и запускайте импорт.',
          en: 'Set the table parameters and start the import.',
          kk: 'Кесте параметрлерін орнатып, импортты бастаңыз.',
          de: 'Legen Sie die Tabellenparameter fest und starten Sie den Import.',
          fr: "Définissez les paramètres du tableau et lancez l'importation.",
          es: 'Establezca los parámetros de la tabla e inicie la importación.',
          pt: 'Defina os parâmetros da tabela e inicie a importação.',
          tr: 'Tablo parametrelerini ayarlayın ve içe aktarmayı başlatın.',
          uk: 'Вкажіть параметри таблиці, що створюється, та запустіть імпорт.',
          zh: '设置表格参数并开始导入。',
          ar: 'حدد معلمات الجدول وابدأ الاستيراد.',
          pl: 'Ustaw parametry tabeli i rozpocznij import.',
          it: "Imposta i parametri della tabella e avvia l'importazione.",
          sk: 'Ustaw parametry tabeli i rozpocznij import.',
          ja: 'Set the table parameters and start the import.',
          ko: 'Set the table parameters and start the import.',
          hi: 'Set the table parameters and start the import.',
          nl: 'Set the table parameters and start the import.',
          sv: 'Set the table parameters and start the import.',
          vi: 'Set the table parameters and start the import.',
          id: 'Set the table parameters and start the import.',
        }),
      },
      tableName: {
        title: t({
          ru: 'Название таблицы',
          en: 'Table name',
          kk: 'Кесте атауы',
          de: 'Tabellenname',
          fr: 'Nom du tableau',
          es: 'Nombre de la tabla',
          pt: 'Nome da tabela',
          tr: 'Tablo adı',
          uk: 'Назва таблиці',
          zh: '表格名称',
          ar: 'اسم الجدول',
          pl: 'Nazwa tabeli',
          it: 'Nome tabella',
          sk: 'Nazwa tabeli',
          ja: 'Table name',
          ko: 'Table name',
          hi: 'Table name',
          nl: 'Table name',
          sv: 'Table name',
          vi: 'Table name',
          id: 'Table name',
        }),
        description: t({
          ru: 'Введите название будущей таблицы.',
          en: 'Enter the name for the new table.',
          kk: 'Жаңа кестенің атауын енгізіңіз.',
          de: 'Geben Sie den Namen für die neue Tabelle ein.',
          fr: 'Entrez le nom de la nouvelle table.',
          es: 'Ingrese el nombre de la nueva tabla.',
          pt: 'Digite o nome da nova tabela.',
          tr: 'Yeni tablo için bir ad girin.',
          uk: 'Введіть назву майбутньої таблиці.',
          zh: '输入新表格的名称。',
          ar: 'أدخل اسم الجدول الجديد.',
          pl: 'Podaj nazwę nowej tabeli.',
          it: 'Inserisci il nome per la nuova tabella.',
          sk: 'Podaj nazwę nowej tabeli.',
          ja: 'Enter the name for the new table.',
          ko: 'Enter the name for the new table.',
          hi: 'Enter the name for the new table.',
          nl: 'Enter the name for the new table.',
          sv: 'Enter the name for the new table.',
          vi: 'Enter the name for the new table.',
          id: 'Enter the name for the new table.',
        }),
      },
      category: {
        title: t({
          ru: 'Категория',
          en: 'Category',
          kk: 'Санат',
          de: 'Kategorie',
          fr: 'Catégorie',
          es: 'Categoría',
          pt: 'Categoria',
          tr: 'Kategori',
          uk: 'Категорія',
          zh: '分类',
          ar: 'الفئة',
          pl: 'Kategoria',
          it: 'Categoria',
          sk: 'Kategoria',
          ja: 'Category',
          ko: 'Category',
          hi: 'Category',
          nl: 'Category',
          sv: 'Category',
          vi: 'Category',
          id: 'Category',
        }),
        description: t({
          ru: 'Можно привязать таблицу к категории для удобной навигации.',
          en: 'Optionally link the table to a category for easier navigation.',
          kk: 'Кестені санатқа байланыстыру навигацияны жеңілдетеді.',
          de: 'Optional kann die Tabelle einer Kategorie zugeordnet werden, um die Navigation zu erleichtern.',
          fr: 'Vous pouvez optionnellement lier le tableau à une catégorie pour faciliter la navigation.',
          es: 'Opcionalmente vincule la tabla a una categoría para facilitar la navegación.',
          pt: 'Opcionalmente, vincule a tabela a uma categoria para facilitar a navegação.',
          tr: 'Navigasyonu kolaylaştırmak için tabloyu isteğe bağlı olarak bir kategoriye bağlayın.',
          uk: "За потреби прив'яжіть таблицю до категорії для зручної навігації.",
          zh: '可选择将表格与分类关联以便于导航。',
          ar: 'يمكنك اختياريًا ربط الجدول بفئة لتسهيل التنقل.',
          pl: 'Opcjonalnie powiąż tabelę z kategorią, aby ułatwić nawigację.',
          it: 'Facoltativamente collega la tabella a una categoria per facilitare la navigazione.',
          sk: 'Opcjonalnie powiąż tabelę z kategorią, aby ułatwić nawigację.',
          ja: 'Optionally link the table to a category for easier navigation.',
          ko: 'Optionally link the table to a category for easier navigation.',
          hi: 'Optionally link the table to a category for easier navigation.',
          nl: 'Optionally link the table to a category for easier navigation.',
          sv: 'Optionally link the table to a category for easier navigation.',
          vi: 'Optionally link the table to a category for easier navigation.',
          id: 'Optionally link the table to a category for easier navigation.',
        }),
      },
      importData: {
        title: t({
          ru: 'Импортировать данные',
          en: 'Import data',
          kk: 'Деректерді импорттау',
          de: 'Daten importieren',
          fr: 'Importer les données',
          es: 'Importar datos',
          pt: 'Importar dados',
          tr: 'Verileri içe aktar',
          uk: 'Імпортувати дані',
          zh: '导入数据',
          ar: 'استيراد البيانات',
          pl: 'Importuj dane',
          it: 'Importa dati',
          sk: 'Importuj dane',
          ja: 'Import data',
          ko: 'Import data',
          hi: 'Import data',
          nl: 'Import data',
          sv: 'Import data',
          vi: 'Import data',
          id: 'Import data',
        }),
        description: t({
          ru: 'Определяет, импортировать ли строки (кроме заголовков).',
          en: 'Decides whether to import rows (excluding headers).',
          kk: 'Жолдарды (тақырыптардан басқа) импорттауын анықтайды.',
          de: 'Legt fest, ob Zeilen (ohne Kopfzeilen) importiert werden sollen.',
          fr: 'Détermine si les lignes (hors en-têtes) doivent être importées.',
          es: 'Decide si importar filas (excluyendo encabezados).',
          pt: 'Decide se deve importar linhas (excluindo cabeçalhos).',
          tr: 'Satırların (başlıklar hariç) içe aktarılıp aktarılmayacağını belirler.',
          uk: 'Визначає, чи імпортувати рядки (крім заголовків).',
          zh: '决定是否导入行（不含标题）。',
          ar: 'يحدد ما إذا كان سيتم استيراد الصفوف (باستثناء الرؤوس).',
          pl: 'Określa, czy importować wiersze (z wyłączeniem nagłówków).',
          it: 'Decide se importare le righe (escluse le intestazioni).',
          sk: 'Określa, czy importować wiersze (z wyłączeniem nagłówków).',
          ja: 'Decides whether to import rows (excluding headers).',
          ko: 'Decides whether to import rows (excluding headers).',
          hi: 'Decides whether to import rows (excluding headers).',
          nl: 'Decides whether to import rows (excluding headers).',
          sv: 'Decides whether to import rows (excluding headers).',
          vi: 'Decides whether to import rows (excluding headers).',
          id: 'Decides whether to import rows (excluding headers).',
        }),
      },
      importButton: {
        title: t({
          ru: 'Запустить импорт',
          en: 'Start import',
          kk: 'Импортты бастау',
          de: 'Import starten',
          fr: "Lancer l'importation",
          es: 'Iniciar importación',
          pt: 'Iniciar importação',
          tr: 'İçe aktarmayı başlat',
          uk: 'Запустити імпорт',
          zh: '开始导入',
          ar: 'بدء الاستيراد',
          pl: 'Rozpocznij import',
          it: 'Avvia importazione',
          sk: 'Rozpocznij import',
          ja: 'Start import',
          ko: 'Start import',
          hi: 'Start import',
          nl: 'Start import',
          sv: 'Start import',
          vi: 'Start import',
          id: 'Start import',
        }),
        description: t({
          ru: 'Запускает импорт и создание таблицы Lumio.',
          en: 'Starts the import and creates a Lumio table.',
          kk: 'Импортты іске қосып, Lumio кестесін жасайды.',
          de: 'Startet den Import und erstellt eine Lumio-Tabelle.',
          fr: "Lance l'importation et crée un tableau Lumio.",
          es: 'Inicia la importación y crea una tabla Lumio.',
          pt: 'Inicia a importação e cria uma tabela Lumio.',
          tr: 'İçe aktarmayı başlatır ve bir Lumio tablosu oluşturur.',
          uk: 'Запускає імпорт і створює таблицю Lumio.',
          zh: '开始导入并创建 Lumio 表格。',
          ar: 'يبدأ الاستيراد وينشئ جدول Lumio.',
          pl: 'Uruchamia import i tworzy tabelę Lumio.',
          it: "Avvia l'importazione e crea una tabella Lumio.",
          sk: 'Uruchamia import i tworzy tabelę Lumio.',
          ja: 'Starts the import and creates a Lumio table.',
          ko: 'Starts the import and creates a Lumio table.',
          hi: 'Starts the import and creates a Lumio table.',
          nl: 'Starts the import and creates a Lumio table.',
          sv: 'Starts the import and creates a Lumio table.',
          vi: 'Starts the import and creates a Lumio table.',
          id: 'Starts the import and creates a Lumio table.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'Done',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Concluído',
          tr: 'Tamamlandı',
          uk: 'Готово',
          zh: '完成',
          ar: 'تم',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Gotowe',
          ja: 'Done',
          ko: 'Done',
          hi: 'Done',
          nl: 'Done',
          sv: 'Done',
          vi: 'Done',
          id: 'Done',
        }),
        description: t({
          ru: 'После завершения вы перейдете в созданную таблицу.',
          en: 'After completion you will be taken to the created table.',
          kk: 'Аяқталғаннан кейін жасалған кестеге өтесіз.',
          de: 'Nach Abschluss werden Sie zur erstellten Tabelle weitergeleitet.',
          fr: 'Après la fin, vous serez redirigé vers le tableau créé.',
          es: 'Al finalizar, será redirigido a la tabla creada.',
          pt: 'Após a conclusão, você será redirecionado para a tabela criada.',
          tr: 'Tamamlandıktan sonra oluşturulan tabloya yönlendirileceksiniz.',
          uk: 'Після завершення вас буде переведено до створеної таблиці.',
          zh: '完成后，您将被带到创建的表格。',
          ar: 'بعد الاكتمال ستنتقل إلى الجدول المنشأ.',
          pl: 'Po zakończeniu zostaniesz przeniesiony do utworzonej tabeli.',
          it: 'Al completamento sarai portato alla tabella creata.',
          sk: 'Po zakończeniu zostaniesz przeniesiony do utworzonej tabeli.',
          ja: 'After completion you will be taken to the created table.',
          ko: 'After completion you will be taken to the created table.',
          hi: 'After completion you will be taken to the created table.',
          nl: 'After completion you will be taken to the created table.',
          sv: 'After completion you will be taken to the created table.',
          vi: 'After completion you will be taken to the created table.',
          id: 'After completion you will be taken to the created table.',
        }),
      },
    },
  },
} satisfies Dictionary;

export default content;
