import { type DeclarationContent, t } from 'intlayer';

const integrationsTourContent = {
  key: 'integrations-tour-content',
  content: {
    name: t({
      ru: 'Тур по интеграциям',
      en: 'Integrations Tour',
      kk: 'Интеграциялар туры',
      de: 'Integrationen-Tour',
      fr: 'Visite des intégrations',
      es: 'Tour de integraciones',
      pt: 'Tour de integrações',
      tr: 'Entegrasyonlar Turu',
      uk: 'Тур по інтеграціях',
      zh: '集成导览',
      pl: 'Tour integracji',
      it: 'Tour delle integrazioni',
      sk: 'Prehliadka integrácií',
      ja: '統合ツアー',
      ko: '통합 투어',
      hi: 'एकीकरण यात्रा',
      nl: 'Integraties Tour',
      sv: 'Integrationsturné',
      vi: 'Chuyến tham quan tích hợp',
      id: 'Tur Integrasi',
      da: 'Tur i Integrationer',
      nb: 'Omvisning i Integrasjoner',
      nn: 'Omvising i Integrasjonar',
      fi: 'Integraatioiden kierros',
      is: 'Kynnisferð um Samþættingar',
      fo: 'Umsiting í Samanknýtingum',
      cs: 'Průvodce Integracemi',
      bg: 'Обиколка на Интеграции',
      hr: 'Obilazak Integracija',
      sr: 'Обилазак Интеграција',
      sl: 'Ogled Integracij',
      mk: 'Тура низ Интеграции',
      be: 'Тур па «Інтэграцыях»',
      bs: 'Obilazak Integracija',
      hsb: 'Wodźenje po Integracijach',
    }),
    description: t({
      ru: 'Подключение внешних сервисов к Lumio',
      en: 'Connect external services to Lumio',
      kk: 'Lumio-ға сыртқы сервистерді қосу',
      de: 'Externe Dienste mit Lumio verbinden',
      fr: 'Connecter des services externes à Lumio',
      es: 'Conectar servicios externos a Lumio',
      pt: 'Conectar serviços externos ao Lumio',
      tr: "Harici hizmetleri Lumio'ya bağla",
      uk: 'Підключення зовнішніх сервісів до Lumio',
      zh: '将外部服务连接到 Lumio',
      pl: 'Połącz zewnętrzne usługi z Lumio',
      it: 'Connetti servizi esterni a Lumio',
      sk: 'Pripojte externé služby k Lumio',
      ja: '外部サービスを Lumio に接続する',
      ko: 'Lumio에 외부 서비스 연결',
      hi: 'बाहरी सेवाओं को लुमियो से कनेक्ट करें',
      nl: 'Koppel externe diensten aan Lumio',
      sv: 'Anslut externa tjänster till Lumio',
      vi: 'Kết nối các dịch vụ bên ngoài với Lumio',
      id: 'Hubungkan layanan eksternal ke Lumio',
      da: 'Forbind eksterne tjenester til Lumio',
      nb: 'Koble eksterne tjenester til Lumio',
      nn: 'Kople eksterne tenester til Lumio',
      fi: 'Yhdistä ulkoisia palveluita Lumioon',
      is: 'Tengdu ytri þjónustur við Lumio',
      fo: 'Knýt uttanhýsis tænastur at Lumio',
      cs: 'Připojte externí služby k Lumiu',
      bg: 'Свържете външни услуги с Lumio',
      hr: 'Povežite vanjske usluge s Lumijem',
      sr: 'Повежите спољне услуге са Lumijem',
      sl: 'Povežite zunanje storitve z Lumiom',
      mk: 'Поврзете надворешни услуги со Lumio',
      be: 'Падключайце знешнія сэрвісы да Lumio',
      bs: 'Povežite vanjske usluge s Lumijem',
      hsb: 'Zwjazajće eksterne posłužby z Lumio',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Добро пожаловать в интеграции',
          en: 'Welcome to Integrations',
          kk: 'Интеграцияларға қош келдіңіз',
          de: 'Willkommen bei den Integrationen',
          fr: 'Bienvenue dans les intégrations',
          es: 'Bienvenido a Integraciones',
          pt: 'Bem-vindo às Integrações',
          tr: 'Entegrasyonlara Hoş Geldiniz',
          uk: 'Ласкаво просимо до Інтеграцій',
          zh: '欢迎使用集成',
          pl: 'Witaj w Integracjach',
          it: 'Benvenuto nelle Integrazioni',
          sk: 'Vitajte v Integráciách',
          ja: '統合へようこそ',
          ko: '통합에 오신 것을 환영합니다',
          hi: 'एकीकरण में आपका स्वागत है',
          nl: 'Welkom bij Integraties',
          sv: 'Välkommen till Integrations',
          vi: 'Chào mừng đến với Tích hợp',
          id: 'Selamat datang di Integrasi',
          da: 'Velkommen til Integrationer',
          nb: 'Velkommen til Integrasjoner',
          nn: 'Velkomen til Integrasjonar',
          fi: 'Tervetuloa Integraatioihin',
          is: 'Velkomin á Samþættingar',
          fo: 'Vælkomin til Samanknýtingar',
          cs: 'Vítejte v Integracích',
          bg: 'Добре дошли в Интеграции',
          hr: 'Dobro došli u Integracije',
          sr: 'Добро дошли у Интеграције',
          sl: 'Dobrodošli v Integracijah',
          mk: 'Добредојдовте во Интеграции',
          be: 'Вітаем у «Інтэграцыях»',
          bs: 'Dobro došli u Integracije',
          hsb: 'Witajće k Integracijam',
        }),
        description: t({
          ru: 'На этой странице собраны доступные подключения к внешним сервисам. Здесь вы выбираете нужный инструмент и переходите к его настройке.',
          en: 'This page lists the external services that can connect to Lumio. It is the starting point for choosing a tool and opening its setup flow.',
          kk: 'Бұл бетте Lumio-ға қосыла алатын сыртқы сервистер жиналған. Қажетті құралды таңдап, оны баптау ағынына өтетін негізгі орын осы.',
          de: 'Diese Seite listet die externen Dienste auf, die sich mit Lumio verbinden können. Es ist der Ausgangspunkt für die Auswahl eines Tools und das Öffnen des Einrichtungsablaufs.',
          fr: "Cette page liste les services externes qui peuvent se connecter à Lumio. C'est le point de départ pour choisir un outil et ouvrir son flux de configuration.",
          es: 'Esta página enumera los servicios externos que pueden conectarse a Lumio. Es el punto de partida para elegir una herramienta y abrir su flujo de configuración.',
          pt: 'Esta página lista os serviços externos que podem se conectar ao Lumio. É o ponto de partida para escolher uma ferramenta e abrir seu fluxo de configuração.',
          tr: "Bu sayfa Lumio'ya bağlanabilen harici hizmetleri listeler. Bir araç seçmek ve kurulum akışını açmak için başlangıç noktasıdır.",
          uk: 'На цій сторінці зібрані доступні підключення до зовнішніх сервісів. Тут ви обираєте потрібний інструмент та переходите до його налаштування.',
          zh: '此页面列出可以连接到 Lumio 的外部服务。这是选择工具和打开其设置流程的起点。',
          pl: 'Ta strona wyświetla zewnętrzne usługi, które mogą łączyć się z Lumio. Jest to punkt startowy do wyboru narzędzia i otwarcia jego przepływu konfiguracji.',
          it: 'Questa pagina elenca i servizi esterni che possono connettersi a Lumio. È il punto di partenza per scegliere uno strumento e aprire il suo flusso di configurazione.',
          sk: 'Táto stránka uvádza externé služby, ktoré sa dajú pripojiť k Lumio. Je to východiskový bod na výber nástroja a otvorenie jeho nastavenia.',
          ja: 'このページには、Lumio に接続できる外部サービスがリストされます。これは、ツールを選択し、そのセットアップ フローを開始するための開始点です。',
          ko: '이 페이지에는 Lumio에 연결할 수 있는 외부 서비스가 나열되어 있습니다. 이는 도구를 선택하고 설정 흐름을 시작하는 출발점입니다.',
          hi: 'यह पृष्ठ उन बाहरी सेवाओं को सूचीबद्ध करता है जो लुमियो से जुड़ सकती हैं। यह किसी टूल को चुनने और उसके सेटअप प्रवाह को खोलने के लिए शुरुआती बिंदु है।',
          nl: 'Op deze pagina worden de externe services vermeld die verbinding kunnen maken met Lumio. Het is het startpunt voor het kiezen van een tool en het openen van de set-upstroom.',
          sv: 'Den här sidan listar de externa tjänster som kan ansluta till Lumio. Det är utgångspunkten för att välja ett verktyg och öppna dess inställningsflöde.',
          vi: 'Trang này liệt kê các dịch vụ bên ngoài có thể kết nối với Lumio. Đây là điểm khởi đầu để chọn một công cụ và mở quy trình thiết lập của nó.',
          id: 'Halaman ini mencantumkan layanan eksternal yang dapat terhubung ke Lumio. Ini adalah titik awal untuk memilih alat dan membuka alur penyiapannya.',
          da: 'Denne side viser de eksterne tjenester, der kan forbindes til Lumio. Det er udgangspunktet for at vælge et værktøj og åbne dets opsætning.',
          nb: 'Denne siden lister de eksterne tjenestene som kan kobles til Lumio. Det er utgangspunktet for å velge et verktøy og åpne oppsettet.',
          nn: 'Denne sida listar dei eksterne tenestene som kan koplast til Lumio. Det er utgangspunktet for å velje eit verktøy og opne oppsettet.',
          fi: 'Tämä sivu listaa ulkoiset palvelut, jotka voi yhdistää Lumioon. Se on lähtökohta työkalun valintaan ja sen käyttöönoton avaamiseen.',
          is: 'Þessi síða listar ytri þjónustur sem unnt er að tengja við Lumio. Hún er upphafspunktur til að velja tól og opna uppsetningu þess.',
          fo: 'Henda síða listar uttanhýsis tænasturnar, sum kunnu knýtast at Lumio. Hon er byrjanarstaðurin at velja eitt tól og lata uppsetingina upp.',
          cs: 'Tato stránka vypisuje externí služby, které lze připojit k Lumiu. Je výchozím bodem pro volbu nástroje a otevření jeho nastavení.',
          bg: 'Тази страница изброява външните услуги, които могат да се свържат с Lumio. Това е началната точка за избор на инструмент и отваряне на настройката му.',
          hr: 'Ova stranica navodi vanjske usluge koje je moguće povezati s Lumijem. Polazna je točka za odabir alata i otvaranje njegove postave.',
          sr: 'Ова страница наводи спољне услуге које је могуће повезати са Lumijem. Полазна је точка за избор алата и отварање његовог подешавања.',
          sl: 'Ta stran navaja zunanje storitve, ki jih je mogoče povezati z Lumiom. Je izhodišče za izbiro orodja in odprtje njegove nastavitve.',
          mk: 'Оваа страница ги наведува надворешните услуги што можат да се поврзат со Lumio. Тоа е почетна точка за избор на алатка и отворање на нејзината поставка.',
          be: 'Гэтая старонка пералічвае знешнія сэрвісы, якія можна падключыць да Lumio. Гэта пункт пачатку, каб выбраць інструмент і адкрыць яго наладку.',
          bs: 'Ova stranica navodi vanjske usluge koje je moguće povezati s Lumijem. Polazna je točka za odabir alata i otvaranje njegove postavke.',
          hsb: 'Tuta strona nalistuje eksterne posłužby, kotrež móžeja so z Lumio zwjazać. Je wuchadny dypk za wuzwolenje nastroja a wočinjenje jeho nastajenja.',
        }),
      },
      search: {
        title: t({
          ru: 'Поиск интеграций',
          en: 'Search integrations',
          kk: 'Интеграцияларды іздеу',
          de: 'Integrationen suchen',
          fr: 'Rechercher des intégrations',
          es: 'Buscar integraciones',
          pt: 'Pesquisar integrações',
          tr: 'Entegrasyon ara',
          uk: 'Пошук інтеграцій',
          zh: '搜索集成',
          pl: 'Szukaj integracji',
          it: 'Cerca integrazioni',
          sk: 'Hľadať integrácie',
          ja: '検索の統合',
          ko: '검색 통합',
          hi: 'एकीकरण खोजें',
          nl: 'Zoek integraties',
          sv: 'Sökintegrationer',
          vi: 'Tích hợp tìm kiếm',
          id: 'Integrasi pencarian',
          da: 'Søg i integrationer',
          nb: 'Søk i integrasjoner',
          nn: 'Søk i integrasjonar',
          fi: 'Hae integraatioita',
          is: 'Leita í samþættingum',
          fo: 'Leita í samanknýtingum',
          cs: 'Hledat integrace',
          bg: 'Търсене на интеграции',
          hr: 'Traži integracije',
          sr: 'Тражи интеграције',
          sl: 'Iskanje integracij',
          mk: 'Барај интеграции',
          be: 'Пошук інтэграцый',
          bs: 'Traži integracije',
          hsb: 'Integracije pytać',
        }),
        description: t({
          ru: 'Поиск помогает быстро найти нужную интеграцию по названию или описанию, особенно когда список подключений становится длиннее.',
          en: 'Search helps you quickly find an integration by name or description, especially as the catalog grows.',
          kk: 'Іздеу атауы немесе сипаттамасы бойынша қажетті интеграцияны тез табуға көмектеседі, әсіресе каталог үлкейген кезде.',
          de: 'Die Suche hilft Ihnen, eine Integration schnell nach Name oder Beschreibung zu finden, besonders wenn der Katalog wächst.',
          fr: "La recherche vous aide à trouver rapidement une intégration par nom ou description, surtout à mesure que le catalogue s'agrandit.",
          es: 'La búsqueda le ayuda a encontrar rápidamente una integración por nombre o descripción, especialmente a medida que el catálogo crece.',
          pt: 'A pesquisa ajuda a encontrar rapidamente uma integração por nome ou descrição, especialmente à medida que o catálogo cresce.',
          tr: 'Arama, katalog büyüdükçe bir entegrasyonu ada veya açıklamaya göre hızlıca bulmanıza yardımcı olur.',
          uk: 'Пошук допомагає швидко знайти потрібну інтеграцію за назвою або описом, особливо коли список підключень стає більшим.',
          zh: '搜索可帮助您按名称或描述快速找到集成，尤其是随着目录的增长。',
          pl: 'Wyszukiwanie pomaga szybko znaleźć integrację według nazwy lub opisu, zwłaszcza gdy katalog rośnie.',
          it: "La ricerca ti aiuta a trovare rapidamente un'integrazione per nome o descrizione, soprattutto man mano che il catalogo cresce.",
          sk: 'Vyhľadávanie vám pomôže rýchlo nájsť integráciu podľa názvu alebo popisu, najmä keď katalóg rastie.',
          ja: '検索は、特にカタログが大きくなるにつれて、名前または説明で統合をすばやく見つけるのに役立ちます。',
          ko: '검색을 사용하면 특히 카탈로그가 커짐에 따라 이름이나 설명으로 통합을 빠르게 찾을 수 있습니다.',
          hi: 'खोज आपको नाम या विवरण के आधार पर शीघ्रता से एकीकरण खोजने में मदद करती है, खासकर जैसे-जैसे कैटलॉग बढ़ता है।',
          nl: 'Met Zoeken kunt u snel een integratie vinden op naam of beschrijving, vooral naarmate de catalogus groeit.',
          sv: 'Sökning hjälper dig att snabbt hitta en integration efter namn eller beskrivning, särskilt när katalogen växer.',
          vi: 'Tìm kiếm giúp bạn nhanh chóng tìm thấy tiện ích tích hợp theo tên hoặc mô tả, đặc biệt khi danh mục ngày càng phát triển.',
          id: 'Pencarian membantu Anda menemukan integrasi dengan cepat berdasarkan nama atau deskripsi, terutama seiring dengan berkembangnya katalog.',
          da: 'Søgningen hjælper dig med hurtigt at finde en integration efter navn eller beskrivelse, især når kataloget vokser.',
          nb: 'Søket hjelper deg å finne en integrasjon raskt etter navn eller beskrivelse, særlig når katalogen vokser.',
          nn: 'Søket hjelper deg å finne ein integrasjon raskt etter namn eller skildring, særleg når katalogen veks.',
          fi: 'Haku auttaa löytämään integraation nopeasti nimen tai kuvauksen perusteella, erityisesti kun luettelo kasvaa.',
          is: 'Leitin hjálpar þér að finna samþættingu hratt eftir heiti eða skýringu, sérstaklega þegar safnið stækkar.',
          fo: 'Leitingin hjálpir tær at finna eina samanknýting skjótt eftir navni ella frágreiðing, serliga tá listin veksur.',
          cs: 'Hledání pomáhá rychle najít integraci podle názvu nebo popisu, zvlášť když katalog roste.',
          bg: 'Търсенето помага да намерите интеграция бързо по име или описание, особено когато каталогът расте.',
          hr: 'Pretraživanje pomaže brzo naći integraciju po nazivu ili opisu, posebno kad katalog raste.',
          sr: 'Претрага помаже брзо наћи интеграцију по називу или опису, посебно кад каталог расте.',
          sl: 'Iskanje pomaga hitro najti integracijo po imenu ali opisu, zlasti ko katalog raste.',
          mk: 'Пребарувањето помага брзо да најдете интеграција по име или опис, особено кога каталогот расте.',
          be: 'Пошук дапамагае швідка знайсці інтэграцыю па назве або апісанні, асабліва калі каталог расце.',
          bs: 'Pretraga pomaže brzo naći integraciju po nazivu ili opisu, posebno kad katalog raste.',
          hsb: 'Pytanje pomha integraciju spěšnje po mjenju abo wopisanju namakać, wosebje hdyž katalog rosće.',
        }),
      },
      available: {
        title: t({
          ru: 'Доступные интеграции',
          en: 'Available integrations',
          kk: 'Қолжетімді интеграциялар',
          de: 'Verfügbare Integrationen',
          fr: 'Intégrations disponibles',
          es: 'Integraciones disponibles',
          pt: 'Integrações disponíveis',
          tr: 'Mevcut entegrasyonlar',
          uk: 'Доступні інтеграції',
          zh: '可用集成',
          pl: 'Dostępne integracje',
          it: 'Integrazioni disponibili',
          sk: 'Dostupné integrácie',
          ja: '利用可能な統合',
          ko: '사용 가능한 통합',
          hi: 'उपलब्ध एकीकरण',
          nl: 'Beschikbare integraties',
          sv: 'Tillgängliga integrationer',
          vi: 'Tích hợp có sẵn',
          id: 'Integrasi yang tersedia',
          da: 'Tilgængelige integrationer',
          nb: 'Tilgjengelige integrasjoner',
          nn: 'Tilgjengelege integrasjonar',
          fi: 'Saatavilla olevat integraatiot',
          is: 'Tiltækar samþættingar',
          fo: 'Tøkar samanknýtingar',
          cs: 'Dostupné integrace',
          bg: 'Налични интеграции',
          hr: 'Dostupne integracije',
          sr: 'Доступне интеграције',
          sl: 'Razpoložljive integracije',
          mk: 'Достапни интеграции',
          be: 'Даступныя інтэграцыі',
          bs: 'Dostupne integracije',
          hsb: 'K dispoziciji stejace integracije',
        }),
        description: t({
          ru: 'В этом разделе показаны сервисы, которые можно подключить. Карточки сгруппированы по типу, чтобы проще ориентироваться среди хранилищ, почты и мессенджеров.',
          en: 'This section lists services that are ready to be connected. Cards are grouped by category so it is easier to browse storage, email, and messaging tools.',
          kk: 'Бұл бөлімде қосуға болатын сервистер көрсетіледі. Карточкалар түрі бойынша топталған, сондықтан сақтау, пошта және мессенджерлер арасында жүру оңайырақ.',
          de: 'Dieser Abschnitt listet Dienste auf, die verbunden werden können. Karten sind nach Kategorie gruppiert, um das Durchsuchen von Speicher, E-Mail und Messaging-Tools zu erleichtern.',
          fr: "Cette section liste les services prêts à être connectés. Les cartes sont regroupées par catégorie pour faciliter la navigation parmi les outils de stockage, d'e-mail et de messagerie.",
          es: 'Esta sección enumera los servicios listos para conectarse. Las tarjetas están agrupadas por categoría para facilitar la navegación entre almacenamiento, correo electrónico y herramientas de mensajería.',
          pt: 'Esta seção lista serviços prontos para serem conectados. Os cartões são agrupados por categoria para facilitar a navegação entre armazenamento, email e ferramentas de mensagens.',
          tr: 'Bu bölüm bağlanmaya hazır hizmetleri listeler. Kartlar depolama, e-posta ve mesajlaşma araçları arasında gezinmeyi kolaylaştırmak için kategoriye göre gruplandırılmıştır.',
          uk: 'У цьому розділі показані сервіси, які можна підключити. Картки згруповані за типом для зручної навігації серед сховищ, пошти та месенджерів.',
          zh: '此部分列出了可以连接的服务。卡片按类别分组，便于浏览存储、邮件和消息工具。',
          pl: 'Ta sekcja wyświetla usługi gotowe do połączenia. Karty są pogrupowane według kategorii, aby łatwiej przeglądać magazyny, e-mail i narzędzia do wiadomości.',
          it: 'Questa sezione elenca i servizi pronti per essere connessi. Le schede sono raggruppate per categoria per facilitare la navigazione tra strumenti di storage, email e messaggistica.',
          sk: 'Táto sekcia zobrazuje služby pripravené na pripojenie. Karty sú zoskupené podľa kategórie, aby sa dalo ľahšie prehliadať úložiská, e-mail a nástroje na posielanie správ.',
          ja: 'このセクションには、接続の準備ができているサービスがリストされます。カードはカテゴリごとにグループ化されているため、ストレージ、電子メール、メッセージング ツールを簡単に参照できます。',
          ko: '이 섹션에는 연결할 준비가 된 서비스가 나열되어 있습니다. 카드는 카테고리별로 그룹화되어 저장 공간, 이메일, 메시징 도구를 더 쉽게 찾아볼 수 있습니다.',
          hi: 'यह अनुभाग उन सेवाओं को सूचीबद्ध करता है जो कनेक्ट होने के लिए तैयार हैं। कार्डों को श्रेणी के आधार पर समूहीकृत किया जाता है इसलिए स्टोरेज, ईमेल और मैसेजिंग टूल ब्राउज़ करना आसान होता है।',
          nl: 'In dit gedeelte worden services vermeld die klaar zijn om te worden aangesloten. Kaarten zijn gegroepeerd op categorie, zodat u gemakkelijker door opslag-, e-mail- en berichtentools kunt bladeren.',
          sv: 'Det här avsnittet listar tjänster som är redo att anslutas. Korten är grupperade efter kategori så att det är lättare att bläddra i lagringsutrymme, e-post och meddelandeverktyg.',
          vi: 'Phần này liệt kê các dịch vụ đã sẵn sàng để kết nối. Thẻ được nhóm theo danh mục để duyệt qua các công cụ lưu trữ, email và nhắn tin dễ dàng hơn.',
          id: 'Bagian ini mencantumkan layanan yang siap dihubungkan. Kartu dikelompokkan berdasarkan kategori sehingga lebih mudah menelusuri penyimpanan, email, dan alat perpesanan.',
          da: 'Dette afsnit viser de tjenester, der er klar til at blive forbundet. Kortene er grupperet efter kategori, så det er lettere at gennemse lager-, e-mail- og beskedværktøjer.',
          nb: 'Denne delen lister tjenestene som er klare til å kobles til. Kortene er gruppert etter kategori, slik at det er lettere å bla gjennom lagring, e-post og meldingsverktøy.',
          nn: 'Denne delen listar tenestene som er klare til å koplast til. Korta er grupperte etter kategori, slik at det er lettare å blad gjennom lagring, e-post og meldingsverktøy.',
          fi: 'Tässä osiossa luetellaan palvelut, jotka ovat valmiita yhdistettäväksi. Kortit on ryhmitelty kategorioittain, joten tallennus-, sähköposti- ja viestintyökaluja on helpompi selata.',
          is: 'Þessi hluti listar þjónustur sem eru tilbúnar til tengingar. Kortin eru flokkuð eftir kategoríu svo auðveldara sé að fletta gegnum geymslu-, póst- og skeytatól.',
          fo: 'Hesin parturin listar tænasturnar, sum eru klárar at knýtast. Kortini eru bólkað eftir bólki, so tað er lættari at blaða gjøgnum goymslu-, t-post- og boðtól.',
          cs: 'Tato sekce vypisuje služby připravené k připojení. Karty jsou seskupeny podle kategorie, takže se snadněji prochází nástroje pro úložiště, e-mail a zprávy.',
          bg: 'Този раздел изброява услугите, готови за свързване. Картите са групирани по категория, за да е по-лесно да разгледате инструментите за съхранение, имейл и съобщения.',
          hr: 'Ovaj odjeljak navodi usluge koje su spremne za povezivanje. Kartice su grupirane po kategoriji pa je lakše pregledati alate za pohranu, e-poštu i razmjenu poruka.',
          sr: 'Овај одељак наводи услуге које су спремне за повезивање. Картице су груписане по категорији па је лакше прегледати алате за складиштење, е-пошту и размену порука.',
          sl: 'Ta razdelek navaja storitve, pripravljene za povezavo. Kartice so združene po kategoriji, zato je lažje pregledovati orodja za shrambo, e-pošto in sporočanje.',
          mk: 'Овој дел ги наведува услугите готови за поврзување. Картичките се групирани по категорија, за да е полесно да ги прелистате алатките за складирање, е-пошта и пораки.',
          be: 'Гэты раздзел пералічвае сэрвісы, гатовыя да падключэння. Карткі згрупаваны па катэгорыях, каб было лягчэй праглядаць сховішчы, пошту і мэсэнджары.',
          bs: 'Ovaj odjeljak navodi usluge koje su spremne za povezivanje. Kartice su grupisane po kategoriji pa je lakše pregledati alate za pohranu, e-poštu i razmjenu poruka.',
          hsb: 'Tutón wotrězk nalistuje posłužby, kotrež su hotowe za zwjazanje. Karty su po kategorijach zeskupjene, zo bychu so nastroje za składowanje, e-mejl a powěsće lěpje přehladować dali.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'All set',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Pronto',
          tr: 'Hazır',
          uk: 'Готово',
          zh: '完成',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Všetko pripravené',
          ja: '準備完了',
          ko: '모든 세트',
          hi: 'सब तैयार',
          nl: 'Helemaal klaar',
          sv: 'Allt klart',
          vi: 'Đã hoàn tất',
          id: 'Semua siap',
          da: 'Alt klar',
          nb: 'Alt klart',
          nn: 'Alt klart',
          fi: 'Kaikki valmista',
          is: 'Allt tilbúið',
          fo: 'Alt klárt',
          cs: 'Hotovo',
          bg: 'Готово',
          hr: 'Sve je spremno',
          sr: 'Све је спремно',
          sl: 'Vse je pripravljeno',
          mk: 'Сè е готово',
          be: 'Усё гатова',
          bs: 'Sve je spremno',
          hsb: 'Wšo hotowe',
        }),
        description: t({
          ru: 'Теперь вы знаете, где искать и открывать интеграции. Следующий шаг - перейти в нужную карточку и закончить настройку конкретного сервиса.',
          en: 'You now know where to search and open integrations. The next step is to enter the right card and complete setup for the specific service.',
          kk: 'Енді интеграцияларды қайдан іздеп, қалай ашу керегін білесіз. Келесі қадам - қажетті картаны ашып, нақты сервисті толық баптау.',
          de: 'Sie wissen jetzt, wo Sie Integrationen suchen und öffnen können. Der nächste Schritt ist, die richtige Karte aufzurufen und die Einrichtung für den jeweiligen Dienst abzuschließen.',
          fr: "Vous savez maintenant où rechercher et ouvrir des intégrations. La prochaine étape est d'entrer dans la bonne carte et de compléter la configuration du service spécifique.",
          es: 'Ahora sabe dónde buscar y abrir integraciones. El siguiente paso es entrar en la tarjeta correcta y completar la configuración del servicio específico.',
          pt: 'Agora você sabe onde pesquisar e abrir integrações. O próximo passo é entrar no cartão certo e concluir a configuração do serviço específico.',
          tr: 'Artık entegrasyonları nerede arayacağınızı ve açacağınızı biliyorsunuz. Sonraki adım doğru kartı açmak ve belirli hizmet için kurulumu tamamlamaktır.',
          uk: 'Тепер ви знаєте, де шукати та відкривати інтеграції. Наступний крок - перейти до потрібної картки та завершити налаштування конкретного сервісу.',
          zh: '您现在知道在哪里搜索和打开集成。下一步是进入正确的卡片并完成特定服务的设置。',
          pl: 'Teraz wiesz, gdzie szukać i otwierać integracje. Następny krok to wejście do właściwej karty i ukończenie konfiguracji konkretnej usługi.',
          it: 'Ora sai dove cercare e aprire le integrazioni. Il passo successivo è entrare nella scheda giusta e completare la configurazione del servizio specifico.',
          sk: 'Teraz viete, kde hľadať a otvárať integrácie. Ďalším krokom je otvoriť správnu kartu a dokončiť nastavenie konkrétnej služby.',
          ja: 'これで、統合を検索して開く場所がわかりました。次のステップでは、適切なカードを入力し、特定のサービスのセットアップを完了します。',
          ko: '이제 통합을 검색하고 열 수 있는 위치를 알았습니다. 다음 단계는 올바른 카드를 입력하고 특정 서비스에 대한 설정을 완료하는 것입니다.',
          hi: 'अब आप जानते हैं कि एकीकरण कहां खोजना और खोलना है। अगला कदम सही कार्ड दर्ज करना और विशिष्ट सेवा के लिए सेटअप पूरा करना है।',
          nl: 'Je weet nu waar je integraties moet zoeken en openen. De volgende stap is het invoeren van de juiste kaart en het voltooien van de configuratie voor de specifieke service.',
          sv: 'Du vet nu var du ska söka och öppna integrationer. Nästa steg är att ange rätt kort och slutföra installationen för den specifika tjänsten.',
          vi: 'Bây giờ bạn biết nơi để tìm kiếm và mở tích hợp. Bước tiếp theo là nhập đúng thẻ và hoàn tất thiết lập cho dịch vụ cụ thể.',
          id: 'Anda sekarang tahu di mana harus mencari dan membuka integrasi. Langkah selanjutnya adalah memasukkan kartu yang tepat dan menyelesaikan pengaturan untuk layanan tertentu.',
          da: 'Du ved nu, hvor du søger og åbner integrationer. Næste skridt er at gå ind på det rigtige kort og gennemføre opsætningen for den konkrete tjeneste.',
          nb: 'Du vet nå hvor du søker og åpner integrasjoner. Neste steg er å gå inn på riktig kort og fullføre oppsettet for den aktuelle tjenesten.',
          nn: 'Du veit no kvar du søkjer og opnar integrasjonar. Neste steg er å gå inn på rett kort og fullføre oppsettet for den aktuelle tenesta.',
          fi: 'Tiedät nyt, mistä integraatioita haetaan ja avataan. Seuraava askel on avata oikea kortti ja viimeistellä kyseisen palvelun käyttöönotto.',
          is: 'Þú veist nú hvar samþættingar eru leitaðar og opnaðar. Næsta skref er að fara í rétta kortið og ljúka uppsetningu fyrir tilteknu þjónustuna.',
          fo: 'Tú veitst nú, hvar samanknýtingar verða leitaðar og latnar upp. Næsta stig er at fara inn á rætta kortið og fullføra uppsetingina fyri tann ávísa tænastu.',
          cs: 'Nyní víte, kde integrace hledat a otevírat. Dalším krokem je otevřít správnou kartu a dokončit nastavení konkrétní služby.',
          bg: 'Вече знаете къде да търсите и отваряте интеграции. Следващата стъпка е да влезете в правилната карта и да завършите настройката за конкретната услуга.',
          hr: 'Sada znate gdje tražiti i otvarati integracije. Sljedeći je korak ući u pravu karticu i dovršiti postavu za određenu uslugu.',
          sr: 'Сада знате где тражити и отварати интеграције. Следећи је корак ући у праву картицу и довршити подешавање за одређену услугу.',
          sl: 'Zdaj veste, kje iskati in odpirati integracije. Naslednji korak je odpreti pravo kartico in dokončati nastavitev za določeno storitev.',
          mk: 'Сега знаете каде да барате и отворате интеграции. Следниот чекор е да влезете во вистинската картичка и да ја завршите поставката за конкретната услуга.',
          be: 'Цяпер вы ведаеце, дзе шукаць і адкрываць інтэграцыі. Наступны крок — зайсці ў патрэбную картку і завершыць наладку канкрэтнага сэрвісу.',
          bs: 'Sada znate gdje tražiti i otvarati integracije. Sljedeći je korak ući u pravu karticu i dovršiti postavku za određenu uslugu.',
          hsb: 'Nětko wěsće, hdźež integracije pytaće a wočinjeće. Přichodny krok je prawu kartu wočinić a nastajenje za konkretnu posłužbu dokónčić.',
        }),
      },
    },
  },
} satisfies DeclarationContent;

export default integrationsTourContent;
