import { type DeclarationContent, t } from 'intlayer';

const reportsTourContent = {
  key: 'reports-tour-content',
  content: {
    name: t({
      ru: 'Тур по отчетам',
      en: 'Reports Tour',
      kk: 'Есептер туры',
      de: 'Berichte-Tour',
      fr: 'Visite des rapports',
      es: 'Tour de informes',
      pt: 'Tour de relatórios',
      tr: 'Raporlar Turu',
      uk: 'Тур по звітах',
      zh: '报告导览',
      ar: 'جولة التقارير',
      pl: 'Tour raportów',
      it: 'Tour dei report',
      sk: 'Tour raportów',
      ja: 'Reports Tour',
      ko: 'Reports Tour',
      hi: 'Reports Tour',
      nl: 'Reports Tour',
      sv: 'Reports Tour',
      vi: 'Reports Tour',
      id: 'Reports Tour',
    }),
    description: t({
      ru: 'Создание финансовых отчетов из готовых шаблонов',
      en: 'Create financial reports from ready-made templates',
      kk: 'Дайын үлгілерден қаржылық есептер жасау',
      de: 'Finanzberichte aus vorgefertigten Vorlagen erstellen',
      fr: "Créer des rapports financiers à partir de modèles prêts à l'emploi",
      es: 'Crear informes financieros a partir de plantillas prediseñadas',
      pt: 'Criar relatórios financeiros a partir de modelos prontos',
      tr: 'Hazır şablonlardan finansal raporlar oluşturun',
      uk: 'Створення фінансових звітів із готових шаблонів',
      zh: '从现成模板创建财务报告',
      ar: 'إنشاء تقارير مالية من قوالب جاهزة',
      pl: 'Twórz raporty finansowe z gotowych szablonów',
      it: 'Crea report finanziari da modelli predefiniti',
      sk: 'Twórz raporty finansowe z gotowych szablonów',
      ja: 'Create financial reports from ready-made templates',
      ko: 'Create financial reports from ready-made templates',
      hi: 'Create financial reports from ready-made templates',
      nl: 'Create financial reports from ready-made templates',
      sv: 'Create financial reports from ready-made templates',
      vi: 'Create financial reports from ready-made templates',
      id: 'Create financial reports from ready-made templates',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Добро пожаловать в отчеты',
          en: 'Welcome to Reports',
          kk: 'Есептерге қош келдіңіз',
          de: 'Willkommen bei den Berichten',
          fr: 'Bienvenue dans les rapports',
          es: 'Bienvenido a Informes',
          pt: 'Bem-vindo aos Relatórios',
          tr: 'Raporlara Hoş Geldiniz',
          uk: 'Ласкаво просимо до Звітів',
          zh: '欢迎使用报告',
          ar: 'مرحباً بك في التقارير',
          pl: 'Witaj w Raportach',
          it: 'Benvenuto nei Report',
          sk: 'Witaj w Raportach',
          ja: 'Welcome to Reports',
          ko: 'Welcome to Reports',
          hi: 'Welcome to Reports',
          nl: 'Welcome to Reports',
          sv: 'Welcome to Reports',
          vi: 'Welcome to Reports',
          id: 'Welcome to Reports',
        }),
        description: t({
          ru: 'На этой странице вы выбираете шаблон отчета, задаете период и выгружаете результат в нужном формате. Тур покажет текущий рабочий сценарий.',
          en: 'This page lets you choose a report template, set the period, and export the result in the format you need. This tour walks through the current workflow.',
          kk: 'Бұл бетте есеп үлгісін таңдап, кезеңді орнатып, нәтижені керек форматта жүктейсіз. Тур ағымдағы жұмыс ағынын көрсетеді.',
          de: 'Auf dieser Seite wählen Sie eine Berichtsvorlage, legen den Zeitraum fest und exportieren das Ergebnis im gewünschten Format. Diese Tour führt durch den aktuellen Workflow.',
          fr: "Cette page vous permet de choisir un modèle de rapport, de définir la période et d'exporter le résultat dans le format souhaité. Cette visite parcourt le flux de travail actuel.",
          es: 'Esta página le permite elegir una plantilla de informe, establecer el período y exportar el resultado en el formato que necesite. Este tour recorre el flujo de trabajo actual.',
          pt: 'Esta página permite escolher um modelo de relatório, definir o período e exportar o resultado no formato necessário. Este tour percorre o fluxo de trabalho atual.',
          tr: 'Bu sayfa bir rapor şablonu seçmenize, dönemi ayarlamanıza ve sonucu ihtiyacınız olan formatta dışa aktarmanıza olanak tanır. Bu tur mevcut iş akışını anlatır.',
          uk: 'На цій сторінці ви обираєте шаблон звіту, задаєте період та вивантажуєте результат у потрібному форматі. Тур покаже поточний робочий сценарій.',
          zh: '此页面让您选择报告模板、设置期间并以所需格式导出结果。本导览介绍当前工作流程。',
          ar: 'تتيح لك هذه الصفحة اختيار قالب تقرير وتحديد الفترة وتصدير النتيجة بالتنسيق الذي تحتاجه. تستعرض هذه الجولة سير العمل الحالي.',
          pl: 'Ta strona pozwala wybrać szablon raportu, ustawić okres i wyeksportować wynik w potrzebnym formacie. Ten przewodnik przeprowadza przez bieżący przepływ pracy.',
          it: 'Questa pagina ti permette di scegliere un modello di report, impostare il periodo ed esportare il risultato nel formato necessario. Questo tour percorre il flusso di lavoro attuale.',
          sk: 'Ta strona pozwala wybrać szablon raportu, ustawić okres i wyeksportować wynik w potrzebnym formacie. Ten przewodnik przeprowadza przez bieżący przepływ pracy.',
          ja: 'This page lets you choose a report template, set the period, and export the result in the format you need. This tour walks through the current workflow.',
          ko: 'This page lets you choose a report template, set the period, and export the result in the format you need. This tour walks through the current workflow.',
          hi: 'This page lets you choose a report template, set the period, and export the result in the format you need. This tour walks through the current workflow.',
          nl: 'This page lets you choose a report template, set the period, and export the result in the format you need. This tour walks through the current workflow.',
          sv: 'This page lets you choose a report template, set the period, and export the result in the format you need. This tour walks through the current workflow.',
          vi: 'This page lets you choose a report template, set the period, and export the result in the format you need. This tour walks through the current workflow.',
          id: 'This page lets you choose a report template, set the period, and export the result in the format you need. This tour walks through the current workflow.',
        }),
      },
      tabs: {
        title: t({
          ru: 'Разделы страницы',
          en: 'Page sections',
          kk: 'Бет бөлімдері',
          de: 'Seitenbereiche',
          fr: 'Sections de la page',
          es: 'Secciones de la página',
          pt: 'Seções da página',
          tr: 'Sayfa bölümleri',
          uk: 'Розділи сторінки',
          zh: '页面部分',
          ar: 'أقسام الصفحة',
          pl: 'Sekcje strony',
          it: 'Sezioni della pagina',
          sk: 'Sekcje strony',
          ja: 'Page sections',
          ko: 'Page sections',
          hi: 'Page sections',
          nl: 'Page sections',
          sv: 'Page sections',
          vi: 'Page sections',
          id: 'Page sections',
        }),
        description: t({
          ru: 'Верхние вкладки переключают между шаблонами и историей уже созданных отчетов. Это основная навигация внутри страницы.',
          en: 'These tabs switch between available templates and the history of generated reports. They are the main navigation inside this page.',
          kk: 'Жоғарғы қойындылар қолжетімді үлгілер мен бұрын жасалған есептер тарихы арасында ауыстырады. Бұл осы беттің негізгі навигациясы.',
          de: 'Diese Registerkarten wechseln zwischen verfügbaren Vorlagen und dem Verlauf der generierten Berichte. Sie sind die Hauptnavigation innerhalb dieser Seite.',
          fr: "Ces onglets basculent entre les modèles disponibles et l'historique des rapports générés. Ils constituent la navigation principale dans cette page.",
          es: 'Estas pestañas cambian entre las plantillas disponibles y el historial de informes generados. Son la navegación principal dentro de esta página.',
          pt: 'Estas abas alternam entre os modelos disponíveis e o histórico de relatórios gerados. São a navegação principal dentro desta página.',
          tr: 'Bu sekmeler mevcut şablonlar ve oluşturulan raporların geçmişi arasında geçiş yapar. Bu sayfanın ana navigasyonudur.',
          uk: 'Верхні вкладки перемикають між шаблонами та історією вже створених звітів. Це основна навігація всередині сторінки.',
          zh: '这些选项卡在可用模板和已生成报告的历史记录之间切换。它们是此页面内的主要导航。',
          ar: 'تتبدل هذه علامات التبويب بين القوالب المتاحة وتاريخ التقارير المنشأة. وهي التنقل الرئيسي داخل هذه الصفحة.',
          pl: 'Te zakładki przełączają między dostępnymi szablonami a historią wygenerowanych raportów. Są to główne punkty nawigacji na tej stronie.',
          it: "Queste schede passano tra i modelli disponibili e la cronologia dei report generati. Sono la navigazione principale all'interno di questa pagina.",
          sk: 'Te zakładki przełączają między dostępnymi szablonami a historią wygenerowanych raportów. Są to główne punkty nawigacji na tej stronie.',
          ja: 'These tabs switch between available templates and the history of generated reports. They are the main navigation inside this page.',
          ko: 'These tabs switch between available templates and the history of generated reports. They are the main navigation inside this page.',
          hi: 'These tabs switch between available templates and the history of generated reports. They are the main navigation inside this page.',
          nl: 'These tabs switch between available templates and the history of generated reports. They are the main navigation inside this page.',
          sv: 'These tabs switch between available templates and the history of generated reports. They are the main navigation inside this page.',
          vi: 'These tabs switch between available templates and the history of generated reports. They are the main navigation inside this page.',
          id: 'These tabs switch between available templates and the history of generated reports. They are the main navigation inside this page.',
        }),
      },
      templates: {
        title: t({
          ru: 'Шаблоны отчетов',
          en: 'Report templates',
          kk: 'Есеп үлгілері',
          de: 'Berichtsvorlagen',
          fr: 'Modèles de rapports',
          es: 'Plantillas de informes',
          pt: 'Modelos de relatórios',
          tr: 'Rapor şablonları',
          uk: 'Шаблони звітів',
          zh: '报告模板',
          ar: 'قوالب التقارير',
          pl: 'Szablony raportów',
          it: 'Modelli di report',
          sk: 'Szablony raportów',
          ja: 'Report templates',
          ko: 'Report templates',
          hi: 'Report templates',
          nl: 'Report templates',
          sv: 'Report templates',
          vi: 'Report templates',
          id: 'Report templates',
        }),
        description: t({
          ru: 'Здесь собраны доступные типы отчетов. Выбирайте шаблон в зависимости от того, хотите ли вы посмотреть прибыль и убытки, баланс, движение денег или расходы по категориям.',
          en: 'This grid contains the available report types. Pick a template based on whether you want profit and loss, balance, cash flow, or category spending.',
          kk: 'Мұнда қолжетімді есеп түрлері жиналған. Пайда мен шығынды, балансты, ақша ағынын немесе санаттар бойынша шығыстарды көру үшін сәйкес үлгіні таңдаңыз.',
          de: 'Dieses Raster enthält die verfügbaren Berichtstypen. Wählen Sie eine Vorlage je nachdem, ob Sie Gewinn und Verlust, Bilanz, Cashflow oder Kategorienausgaben anzeigen möchten.',
          fr: 'Cette grille contient les types de rapports disponibles. Choisissez un modèle selon que vous souhaitez voir les profits et pertes, le bilan, les flux de trésorerie ou les dépenses par catégorie.',
          es: 'Esta cuadrícula contiene los tipos de informes disponibles. Elija una plantilla según si desea ver pérdidas y ganancias, balance, flujo de caja o gastos por categoría.',
          pt: 'Esta grade contém os tipos de relatórios disponíveis. Escolha um modelo com base em se você quer lucros e perdas, balanço, fluxo de caixa ou gastos por categoria.',
          tr: 'Bu ızgara mevcut rapor türlerini içerir. Kâr ve zarar, bilanço, nakit akışı veya kategori harcamasını isteyip istemediğinize göre bir şablon seçin.',
          uk: 'Тут зібрані доступні типи звітів. Обирайте шаблон залежно від того, хочете ви побачити прибуток і збиток, баланс, рух грошей чи витрати за категоріями.',
          zh: '此网格包含可用的报告类型。根据您是否需要损益、资产负债、现金流或分类支出来选择模板。',
          ar: 'تحتوي هذه الشبكة على أنواع التقارير المتاحة. اختر قالباً بناءً على ما إذا كنت تريد الأرباح والخسائر أو الميزانية العمومية أو التدفق النقدي أو الإنفاق حسب الفئة.',
          pl: 'Ta siatka zawiera dostępne typy raportów. Wybierz szablon w zależności od tego, czy chcesz zyski i straty, bilans, przepływ gotówki czy wydatki według kategorii.',
          it: 'Questa griglia contiene i tipi di report disponibili. Scegli un modello in base al tipo di report che vuoi: profitti e perdite, bilancio, flusso di cassa o spese per categoria.',
          sk: 'Ta siatka zawiera dostępne typy raportów. Wybierz szablon w zależności od tego, czy chcesz zyski i straty, bilans, przepływ gotówki czy wydatki według kategorii.',
          ja: 'This grid contains the available report types. Pick a template based on whether you want profit and loss, balance, cash flow, or category spending.',
          ko: 'This grid contains the available report types. Pick a template based on whether you want profit and loss, balance, cash flow, or category spending.',
          hi: 'This grid contains the available report types. Pick a template based on whether you want profit and loss, balance, cash flow, or category spending.',
          nl: 'This grid contains the available report types. Pick a template based on whether you want profit and loss, balance, cash flow, or category spending.',
          sv: 'This grid contains the available report types. Pick a template based on whether you want profit and loss, balance, cash flow, or category spending.',
          vi: 'This grid contains the available report types. Pick a template based on whether you want profit and loss, balance, cash flow, or category spending.',
          id: 'This grid contains the available report types. Pick a template based on whether you want profit and loss, balance, cash flow, or category spending.',
        }),
      },
      selectTemplate: {
        title: t({
          ru: 'Выбор шаблона',
          en: 'Select a template',
          kk: 'Үлгіні таңдау',
          de: 'Vorlage auswählen',
          fr: 'Sélectionner un modèle',
          es: 'Seleccionar una plantilla',
          pt: 'Selecionar um modelo',
          tr: 'Şablon seç',
          uk: 'Вибір шаблону',
          zh: '选择模板',
          ar: 'اختر قالباً',
          pl: 'Wybierz szablon',
          it: 'Seleziona un modello',
          sk: 'Wybierz szablon',
          ja: 'Select a template',
          ko: 'Select a template',
          hi: 'Select a template',
          nl: 'Select a template',
          sv: 'Select a template',
          vi: 'Select a template',
          id: 'Select a template',
        }),
        description: t({
          ru: 'Карточка P&L открывает панель настройки отчета. После выбора можно задать период и формат перед генерацией файла.',
          en: 'The P&L card opens the report setup panel. After selecting it, you can configure the period and export format before generating the file.',
          kk: 'P&L картасы есепті баптау панелін ашады. Таңдағаннан кейін файлды жасамас бұрын кезең мен экспорт форматын орната аласыз.',
          de: 'Die P&L-Karte öffnet das Berichtseinrichtungspanel. Nach der Auswahl können Sie den Zeitraum und das Exportformat vor der Dateigenerierung konfigurieren.',
          fr: "La carte P&L ouvre le panneau de configuration du rapport. Après la sélection, vous pouvez configurer la période et le format d'exportation avant de générer le fichier.",
          es: 'La tarjeta P&L abre el panel de configuración del informe. Después de seleccionarla, puede configurar el período y el formato de exportación antes de generar el archivo.',
          pt: 'O cartão P&L abre o painel de configuração do relatório. Após selecioná-lo, você pode configurar o período e o formato de exportação antes de gerar o arquivo.',
          tr: 'P&L kartı rapor kurulum panelini açar. Seçtikten sonra dosyayı oluşturmadan önce dönemi ve dışa aktarma formatını yapılandırabilirsiniz.',
          uk: 'Картка P&L відкриває панель налаштування звіту. Після вибору можна задати період та формат перед генерацією файлу.',
          zh: 'P&L 卡片打开报告设置面板。选择后，您可以在生成文件之前配置期间和导出格式。',
          ar: 'تفتح بطاقة P&L لوحة إعداد التقرير. بعد اختيارها يمكنك ضبط الفترة وتنسيق التصدير قبل إنشاء الملف.',
          pl: 'Karta P&L otwiera panel konfiguracji raportu. Po jej wybraniu możesz skonfigurować okres i format eksportu przed wygenerowaniem pliku.',
          it: 'La scheda P&L apre il pannello di configurazione del report. Dopo averla selezionata, puoi configurare il periodo e il formato di esportazione prima di generare il file.',
          sk: 'Karta P&L otwiera panel konfiguracji raportu. Po jej wybraniu możesz skonfigurować okres i format eksportu przed wygenerowaniem pliku.',
          ja: 'The P&L card opens the report setup panel. After selecting it, you can configure the period and export format before generating the file.',
          ko: 'The P&L card opens the report setup panel. After selecting it, you can configure the period and export format before generating the file.',
          hi: 'The P&L card opens the report setup panel. After selecting it, you can configure the period and export format before generating the file.',
          nl: 'The P&L card opens the report setup panel. After selecting it, you can configure the period and export format before generating the file.',
          sv: 'The P&L card opens the report setup panel. After selecting it, you can configure the period and export format before generating the file.',
          vi: 'The P&L card opens the report setup panel. After selecting it, you can configure the period and export format before generating the file.',
          id: 'The P&L card opens the report setup panel. After selecting it, you can configure the period and export format before generating the file.',
        }),
      },
      generator: {
        title: t({
          ru: 'Панель генерации',
          en: 'Generation panel',
          kk: 'Жасау панелі',
          de: 'Generierungspanel',
          fr: 'Panneau de génération',
          es: 'Panel de generación',
          pt: 'Painel de geração',
          tr: 'Oluşturma paneli',
          uk: 'Панель генерації',
          zh: '生成面板',
          ar: 'لوحة الإنشاء',
          pl: 'Panel generowania',
          it: 'Pannello di generazione',
          sk: 'Panel generowania',
          ja: 'Generation panel',
          ko: 'Generation panel',
          hi: 'Generation panel',
          nl: 'Generation panel',
          sv: 'Generation panel',
          vi: 'Generation panel',
          id: 'Generation panel',
        }),
        description: t({
          ru: 'В этой панели вы задаете период отчета и проверяете, какой шаблон сейчас активен. Это центральная точка перед выгрузкой документа.',
          en: 'This panel is where you set the reporting period and confirm which template is active. It is the main control area before export.',
          kk: 'Осы панельде есеп кезеңін орнатып, қай үлгінің белсенді екенін тексересіз. Бұл экспорт алдында қолданылатын негізгі басқару аймағы.',
          de: 'In diesem Panel legen Sie den Berichtszeitraum fest und bestätigen, welche Vorlage aktiv ist. Es ist der Hauptsteuerungsbereich vor dem Export.',
          fr: "Ce panneau est l'endroit où vous définissez la période de rapport et confirmez quel modèle est actif. C'est la zone de contrôle principale avant l'exportation.",
          es: 'Este panel es donde establece el período de informe y confirma qué plantilla está activa. Es el área de control principal antes de la exportación.',
          pt: 'Este painel é onde você define o período de relatório e confirma qual modelo está ativo. É a área de controle principal antes da exportação.',
          tr: 'Bu panel raporlama dönemini ayarladığınız ve hangi şablonun aktif olduğunu onayladığınız yerdir. Dışa aktarmadan önceki ana kontrol alanıdır.',
          uk: 'У цій панелі ви задаєте період звіту та перевіряєте, який шаблон зараз активний. Це центральна точка перед вивантаженням документа.',
          zh: '此面板是您设置报告期间和确认哪个模板处于活动状态的地方。这是导出前的主要控制区域。',
          ar: 'هذه اللوحة هي المكان الذي تحدد فيه فترة التقرير وتؤكد أي قالب نشط. إنها منطقة التحكم الرئيسية قبل التصدير.',
          pl: 'W tym panelu ustawiasz okres raportowania i potwierdzasz, który szablon jest aktywny. Jest to główny obszar kontrolny przed eksportem.',
          it: "Questo pannello è dove imposti il periodo di reportistica e confermi quale modello è attivo. È l'area di controllo principale prima dell'esportazione.",
          sk: 'W tym panelu ustawiasz okres raportowania i potwierdzasz, który szablon jest aktywny. Jest to główny obszar kontrolny przed eksportem.',
          ja: 'This panel is where you set the reporting period and confirm which template is active. It is the main control area before export.',
          ko: 'This panel is where you set the reporting period and confirm which template is active. It is the main control area before export.',
          hi: 'This panel is where you set the reporting period and confirm which template is active. It is the main control area before export.',
          nl: 'This panel is where you set the reporting period and confirm which template is active. It is the main control area before export.',
          sv: 'This panel is where you set the reporting period and confirm which template is active. It is the main control area before export.',
          vi: 'This panel is where you set the reporting period and confirm which template is active. It is the main control area before export.',
          id: 'This panel is where you set the reporting period and confirm which template is active. It is the main control area before export.',
        }),
      },
      format: {
        title: t({
          ru: 'Формат выгрузки',
          en: 'Export format',
          kk: 'Экспорт форматы',
          de: 'Exportformat',
          fr: "Format d'exportation",
          es: 'Formato de exportación',
          pt: 'Formato de exportação',
          tr: 'Dışa aktarma formatı',
          uk: 'Формат вивантаження',
          zh: '导出格式',
          ar: 'تنسيق التصدير',
          pl: 'Format eksportu',
          it: 'Formato di esportazione',
          sk: 'Format eksportu',
          ja: 'Export format',
          ko: 'Export format',
          hi: 'Export format',
          nl: 'Export format',
          sv: 'Export format',
          vi: 'Export format',
          id: 'Export format',
        }),
        description: t({
          ru: 'Выберите формат под задачу: Excel для дальнейшей работы, PDF для отправки или CSV для обработки данных в других системах.',
          en: 'Choose the output format that fits the job: Excel for further editing, PDF for sharing, or CSV for downstream processing.',
          kk: 'Мақсатқа сай форматты таңдаңыз: әрі қарай өңдеу үшін Excel, жіберу үшін PDF немесе басқа жүйелерде өңдеу үшін CSV.',
          de: 'Wählen Sie das Ausgabeformat, das zur Aufgabe passt: Excel für weitere Bearbeitung, PDF zum Teilen oder CSV für die Nachverarbeitung.',
          fr: 'Choisissez le format de sortie adapté à la tâche : Excel pour une édition ultérieure, PDF pour le partage ou CSV pour un traitement en aval.',
          es: 'Elija el formato de salida que se adapte a la tarea: Excel para edición posterior, PDF para compartir o CSV para procesamiento posterior.',
          pt: 'Escolha o formato de saída que se adapta à tarefa: Excel para edição posterior, PDF para compartilhamento ou CSV para processamento posterior.',
          tr: 'İşe uygun çıktı formatını seçin: daha fazla düzenleme için Excel, paylaşım için PDF veya aşağı akış işleme için CSV.',
          uk: 'Оберіть формат під завдання: Excel для подальшої роботи, PDF для відправки або CSV для обробки даних в інших системах.',
          zh: '选择适合工作的输出格式：Excel 用于进一步编辑，PDF 用于分享，CSV 用于下游处理。',
          ar: 'اختر تنسيق الإخراج المناسب للمهمة: Excel لمزيد من التحرير أو PDF للمشاركة أو CSV للمعالجة اللاحقة.',
          pl: 'Wybierz format wyjściowy odpowiedni do zadania: Excel do dalszej edycji, PDF do udostępniania lub CSV do dalszego przetwarzania.',
          it: "Scegli il formato di output adatto al lavoro: Excel per ulteriori modifiche, PDF per la condivisione o CSV per l'elaborazione successiva.",
          sk: 'Wybierz format wyjściowy odpowiedni do zadania: Excel do dalszej edycji, PDF do udostępniania lub CSV do dalszego przetwarzania.',
          ja: 'Choose the output format that fits the job: Excel for further editing, PDF for sharing, or CSV for downstream processing.',
          ko: 'Choose the output format that fits the job: Excel for further editing, PDF for sharing, or CSV for downstream processing.',
          hi: 'Choose the output format that fits the job: Excel for further editing, PDF for sharing, or CSV for downstream processing.',
          nl: 'Choose the output format that fits the job: Excel for further editing, PDF for sharing, or CSV for downstream processing.',
          sv: 'Choose the output format that fits the job: Excel for further editing, PDF for sharing, or CSV for downstream processing.',
          vi: 'Choose the output format that fits the job: Excel for further editing, PDF for sharing, or CSV for downstream processing.',
          id: 'Choose the output format that fits the job: Excel for further editing, PDF for sharing, or CSV for downstream processing.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'All set',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Pronto',
          tr: 'Hazır',
          uk: 'Готово',
          zh: '完成',
          ar: 'تم',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Gotowe',
          ja: 'All set',
          ko: 'All set',
          hi: 'All set',
          nl: 'All set',
          sv: 'All set',
          vi: 'All set',
          id: 'All set',
        }),
        description: t({
          ru: 'Теперь вы знаете, где выбрать шаблон и как подготовить отчет к выгрузке. Следующий шаг - сгенерировать нужный документ и скачать его.',
          en: 'You now know where to choose a template and how to prepare a report for export. The next step is to generate the document you need and download it.',
          kk: 'Енді сіз үлгіні қайдан таңдап, есепті экспортқа қалай дайындау керегін білесіз. Келесі қадам - қажет құжатты жасап, жүктеп алу.',
          de: 'Sie wissen jetzt, wo Sie eine Vorlage auswählen und wie Sie einen Bericht für den Export vorbereiten. Der nächste Schritt ist, das benötigte Dokument zu generieren und herunterzuladen.',
          fr: "Vous savez maintenant où choisir un modèle et comment préparer un rapport pour l'exportation. La prochaine étape est de générer le document dont vous avez besoin et de le télécharger.",
          es: 'Ahora sabe dónde elegir una plantilla y cómo preparar un informe para exportar. El siguiente paso es generar el documento que necesita y descargarlo.',
          pt: 'Agora você sabe onde escolher um modelo e como preparar um relatório para exportação. O próximo passo é gerar o documento necessário e baixá-lo.',
          tr: 'Artık bir şablon nerede seçileceğini ve bir raporu dışa aktarma için nasıl hazırlayacağınızı biliyorsunuz. Sonraki adım ihtiyacınız olan belgeyi oluşturmak ve indirmektir.',
          uk: 'Тепер ви знаєте, де вибрати шаблон та як підготувати звіт до вивантаження. Наступний крок - згенерувати потрібний документ та завантажити його.',
          zh: '您现在知道在哪里选择模板以及如何准备报告以供导出。下一步是生成所需文档并下载它。',
          ar: 'أنت تعرف الآن أين تختار قالباً وكيف تعد تقريراً للتصدير. الخطوة التالية هي إنشاء المستند الذي تحتاجه وتنزيله.',
          pl: 'Teraz wiesz, gdzie wybrać szablon i jak przygotować raport do eksportu. Następny krok to wygenerowanie potrzebnego dokumentu i pobranie go.',
          it: "Ora sai dove scegliere un modello e come preparare un report per l'esportazione. Il passo successivo è generare il documento di cui hai bisogno e scaricarlo.",
          sk: 'Teraz wiesz, gdzie wybrać szablon i jak przygotować raport do eksportu. Następny krok to wygenerowanie potrzebnego dokumentu i pobranie go.',
          ja: 'You now know where to choose a template and how to prepare a report for export. The next step is to generate the document you need and download it.',
          ko: 'You now know where to choose a template and how to prepare a report for export. The next step is to generate the document you need and download it.',
          hi: 'You now know where to choose a template and how to prepare a report for export. The next step is to generate the document you need and download it.',
          nl: 'You now know where to choose a template and how to prepare a report for export. The next step is to generate the document you need and download it.',
          sv: 'You now know where to choose a template and how to prepare a report for export. The next step is to generate the document you need and download it.',
          vi: 'You now know where to choose a template and how to prepare a report for export. The next step is to generate the document you need and download it.',
          id: 'You now know where to choose a template and how to prepare a report for export. The next step is to generate the document you need and download it.',
        }),
      },
    },
  },
} satisfies DeclarationContent;

export default reportsTourContent;
