/**
 * Content для тура по странице выписок
 */

import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statements-tour',
  content: {
    name: t({
      ru: 'Тур по выпискам',
      en: 'Statements Tour',
      kk: 'Үзінділер турі',
      de: 'Kontoauszüge-Tour',
      fr: 'Visite des relevés',
      es: 'Tour de extractos',
      pt: 'Tour de extratos',
      tr: 'Ekstre Turu',
      uk: 'Тур по виписках',
      zh: '账单导览',
      ar: 'جولة كشوف الحسابات',
      pl: 'Wyciągi — przewodnik',
      it: 'Tour degli estratti conto',
      sk: 'Wyciągi — przewodnik',
      ja: 'ステートメントツアー',
      ko: '성명서 둘러보기',
      hi: 'वक्तव्य यात्रा',
      nl: 'Verklaringen Rondleiding',
      sv: 'Genomgång av kontoutdrag',
      vi: 'Chuyến tham quan báo cáo',
      id: 'Tur Pernyataan',
    }),
    description: t({
      ru: 'Узнайте как загружать и управлять банковскими выписками',
      en: 'Learn how to upload and manage bank statements',
      kk: 'Банк үзінділерін жүктеу және басқару туралы біліңіз',
      de: 'Erfahren Sie, wie Sie Kontoauszüge hochladen und verwalten',
      fr: 'Découvrez comment télécharger et gérer vos relevés bancaires',
      es: 'Aprenda cómo cargar y gestionar extractos bancarios',
      pt: 'Saiba como fazer upload e gerenciar extratos bancários',
      tr: 'Banka ekstrelerini nasıl yükleyeceğinizi ve yöneteceğinizi öğrenin',
      uk: 'Дізнайтеся, як завантажувати банківські виписки та керувати ними',
      zh: '了解如何上传和管理银行账单',
      ar: 'تعرف على كيفية رفع كشوف الحسابات البنكية وإدارتها',
      pl: 'Dowiedz się, jak przesyłać wyciągi bankowe i nimi zarządzać',
      it: 'Scopri come caricare e gestire gli estratti conto bancari',
      sk: 'Dowiedz się, jak przesyłać wyciągi bankowe i nimi zarządzać',
      ja: '銀行取引明細書をアップロードして管理する方法を学ぶ',
      ko: '은행 명세서를 업로드하고 관리하는 방법 알아보기',
      hi: 'जानें कि बैंक विवरण कैसे अपलोड और प्रबंधित करें',
      nl: 'Leer hoe u bankafschriften kunt uploaden en beheren',
      sv: 'Lär dig hur du laddar upp och hanterar kontoutdrag',
      vi: 'Tìm hiểu cách tải lên và quản lý bảng sao kê ngân hàng',
      id: 'Pelajari cara mengunggah dan mengelola laporan bank',
    }),
    steps: {
      welcome: {
        title: t({
          ru: 'Добро пожаловать в Выписки',
          en: 'Welcome to Statements',
          kk: 'Үзінділерге қош келдіңіз',
          de: 'Willkommen bei den Kontoauszügen',
          fr: 'Bienvenue dans les relevés',
          es: 'Bienvenido a Extractos',
          pt: 'Bem-vindo aos Extratos',
          tr: 'Ekstrelere Hoş Geldiniz',
          uk: 'Ласкаво просимо до Виписок',
          zh: '欢迎使用账单',
          ar: 'مرحباً بك في كشوف الحسابات',
          pl: 'Witaj w Wyciągach',
          it: 'Benvenuto negli Estratti conto',
          sk: 'Witaj w Wyciągach',
          ja: 'ステートメントへようこそ',
          ko: '성명서에 오신 것을 환영합니다',
          hi: 'वक्तव्य में आपका स्वागत है',
          nl: 'Welkom bij Verklaringen',
          sv: 'Välkommen till Statements',
          vi: 'Chào mừng đến với Tuyên bố',
          id: 'Selamat datang di Pernyataan',
        }),
        description: t({
          ru: 'На этой странице вы загружаете документы, находите нужные выписки и переходите к их разбору. Коротко пройдемся по текущему интерфейсу.',
          en: "This page is where you upload documents, find the right statements, and jump into review. Let's walk through the current workflow.",
          kk: 'Бұл бетте құжаттарды жүктеп, керек үзінділерді тауып, оларды тексеруге өте аласыз. Қазіргі жұмыс ағынын қысқаша қарап шығайық.',
          de: 'Auf dieser Seite laden Sie Dokumente hoch, finden die richtigen Auszüge und steigen in die Überprüfung ein. Lassen Sie uns den aktuellen Workflow durchgehen.',
          fr: 'Sur cette page, vous téléchargez des documents, trouvez les bons relevés et commencez la révision. Parcourons ensemble le flux de travail actuel.',
          es: 'En esta página sube documentos, encuentra los extractos correctos y comienza la revisión. Recorramos el flujo de trabajo actual.',
          pt: 'Nesta página você faz upload de documentos, encontra os extratos certos e inicia a revisão. Vamos percorrer o fluxo de trabalho atual.',
          tr: 'Bu sayfada belgeleri yükler, doğru ekstreleri bulur ve incelemeye başlarsınız. Mevcut iş akışına birlikte göz atalım.',
          uk: 'На цій сторінці ви завантажуєте документи, знаходите потрібні виписки та переходите до їх аналізу. Коротко розглянемо поточний інтерфейс.',
          zh: '在此页面，您可以上传文档、找到所需账单并开始审核。让我们快速浏览当前工作流程。',
          ar: 'في هذه الصفحة تقوم برفع المستندات والعثور على الكشوفات المناسبة والبدء في مراجعتها. لنستعرض سير العمل الحالي.',
          pl: 'Na tej stronie przesyłasz dokumenty, znajdujesz odpowiednie wyciągi i przechodzisz do ich przeglądu. Przejdźmy razem przez bieżący przepływ pracy.',
          it: 'In questa pagina carichi documenti, trovi gli estratti giusti e inizi la revisione. Facciamo una breve panoramica del flusso di lavoro attuale.',
          sk: 'Na tej stronie przesyłasz dokumenty, znajdujesz odpowiednie wyciągi i przechodzisz do ich przeglądu. Przejdźmy razem przez bieżący przepływ pracy.',
          ja: 'このページでは、ドキュメントをアップロードし、適切なステートメントを見つけて、レビューに進みます。現在のワークフローを見てみましょう。',
          ko: '이 페이지에서는 문서를 업로드하고, 올바른 설명을 찾고, 검토를 시작합니다. 현재 워크플로를 살펴보겠습니다.',
          hi: 'यह पृष्ठ वह है जहां आप दस्तावेज़ अपलोड करते हैं, सही कथन ढूंढते हैं, और समीक्षा में कूदते हैं। आइए वर्तमान वर्कफ़्लो पर चलते हैं।',
          nl: 'Op deze pagina uploadt u documenten, vindt u de juiste verklaringen en begint u met de beoordeling. Laten we door de huidige workflow lopen.',
          sv: 'Den här sidan är där du laddar upp dokument, hittar rätt uttalanden och går in i granskning. Låt oss gå igenom det aktuella arbetsflödet.',
          vi: 'Trang này là nơi bạn tải lên các tài liệu, tìm những tuyên bố phù hợp và bắt đầu xem xét. Hãy cùng tìm hiểu quy trình làm việc hiện tại.',
          id: 'Halaman ini adalah tempat Anda mengunggah dokumen, menemukan pernyataan yang tepat, dan langsung melakukan peninjauan. Mari kita telusuri alur kerja saat ini.',
        }),
      },
      uploadTrigger: {
        title: t({
          ru: 'Загрузка и сканирование',
          en: 'Upload and Scan',
          kk: 'Жүктеу және сканерлеу',
          de: 'Hochladen und Scannen',
          fr: 'Téléchargement et numérisation',
          es: 'Cargar y escanear',
          pt: 'Upload e digitalização',
          tr: 'Yükle ve Tara',
          uk: 'Завантаження та сканування',
          zh: '上传与扫描',
          ar: 'رفع ومسح',
          pl: 'Prześlij i skanuj',
          it: 'Carica e scansiona',
          sk: 'Prześlij i skanuj',
          ja: 'アップロードとスキャン',
          ko: '업로드 및 스캔',
          hi: 'अपलोड करें और स्कैन करें',
          nl: 'Uploaden en scannen',
          sv: 'Ladda upp och skanna',
          vi: 'Tải lên và quét',
          id: 'Unggah dan Pindai',
        }),
        description: t({
          ru: 'Эта кнопка запускает самый быстрый путь добавления новых документов: скан, локальная загрузка, Gmail и облачные источники.',
          en: 'This trigger opens the fastest path for adding new documents: scan, local upload, Gmail, and connected cloud sources.',
          kk: 'Бұл батырма жаңа құжаттарды қосудың ең жылдам жолын ашады: скан, жергілікті жүктеу, Gmail және бұлттық көздер.',
          de: 'Diese Schaltfläche öffnet den schnellsten Weg zum Hinzufügen neuer Dokumente: Scannen, lokaler Upload, Gmail und verbundene Cloud-Quellen.',
          fr: 'Ce bouton ouvre le chemin le plus rapide pour ajouter de nouveaux documents : scan, téléchargement local, Gmail et sources cloud connectées.',
          es: 'Este botón abre el camino más rápido para agregar nuevos documentos: escanear, carga local, Gmail y fuentes en la nube.',
          pt: 'Este botão abre o caminho mais rápido para adicionar novos documentos: digitalizar, upload local, Gmail e fontes na nuvem.',
          tr: 'Bu düğme yeni belge eklemenin en hızlı yolunu açar: tarama, yerel yükleme, Gmail ve bağlı bulut kaynakları.',
          uk: 'Ця кнопка відкриває найшвидший шлях для додавання нових документів: сканування, локальне завантаження, Gmail та хмарні джерела.',
          zh: '此按钮打开添加新文档的最快路径：扫描、本地上传、Gmail 和已连接的云端来源。',
          ar: 'يفتح هذا الزر أسرع طريقة لإضافة مستندات جديدة: المسح الضوئي، الرفع المحلي، Gmail والمصادر السحابية المتصلة.',
          pl: 'Ten przycisk otwiera najszybszą ścieżkę dodawania nowych dokumentów: skanowanie, lokalny upload, Gmail i połączone źródła w chmurze.',
          it: 'Questo pulsante apre il percorso più rapido per aggiungere nuovi documenti: scansione, caricamento locale, Gmail e fonti cloud collegate.',
          sk: 'Ten przycisk otwiera najszybszą ścieżkę dodawania nowych dokumentów: skanowanie, lokalny upload, Gmail i połączone źródła w chmurze.',
          ja: 'このトリガーにより、スキャン、ローカル アップロード、Gmail、接続されたクラウド ソースなど、新しいドキュメントを追加するための最速のパスが開きます。',
          ko: '이 트리거는 스캔, 로컬 업로드, Gmail 및 연결된 클라우드 소스 등 새 문서를 추가하기 위한 가장 빠른 경로를 엽니다.',
          hi: 'यह ट्रिगर नए दस्तावेज़ जोड़ने के लिए सबसे तेज़ पथ खोलता है: स्कैन, स्थानीय अपलोड, जीमेल और कनेक्टेड क्लाउड स्रोत।',
          nl: 'Deze trigger opent het snelste pad voor het toevoegen van nieuwe documenten: scannen, lokaal uploaden, Gmail en verbonden cloudbronnen.',
          sv: 'Den här utlösaren öppnar den snabbaste vägen för att lägga till nya dokument: skanning, lokal uppladdning, Gmail och anslutna molnkällor.',
          vi: 'Trình kích hoạt này mở ra con đường nhanh nhất để thêm tài liệu mới: quét, tải lên cục bộ, Gmail và các nguồn đám mây được kết nối.',
          id: 'Pemicu ini membuka jalur tercepat untuk menambahkan dokumen baru: pemindaian, unggahan lokal, Gmail, dan sumber cloud yang terhubung.',
        }),
      },
      searchBar: {
        title: t({
          ru: 'Поиск по списку',
          en: 'Search the List',
          kk: 'Тізімнен іздеу',
          de: 'Liste durchsuchen',
          fr: 'Rechercher dans la liste',
          es: 'Buscar en la lista',
          pt: 'Pesquisar na lista',
          tr: 'Listede Ara',
          uk: 'Пошук по списку',
          zh: '搜索列表',
          ar: 'البحث في القائمة',
          pl: 'Szukaj na liście',
          it: 'Cerca nella lista',
          sk: 'Szukaj na liście',
          ja: 'リストを検索する',
          ko: '목록 검색',
          hi: 'सूची खोजें',
          nl: 'Zoek in de lijst',
          sv: 'Sök i listan',
          vi: 'Tìm kiếm danh sách',
          id: 'Cari Daftarnya',
        }),
        description: t({
          ru: 'Поиск помогает быстро сузить список по названию файла, теме письма, отправителю или продавцу.',
          en: 'Search quickly narrows the list by file name, email subject, sender, or merchant.',
          kk: 'Іздеу тізімді файл атауы, хат тақырыбы, жіберуші немесе сатушы бойынша тез тарылтады.',
          de: 'Die Suche grenzt die Liste schnell nach Dateiname, E-Mail-Betreff, Absender oder Händler ein.',
          fr: "La recherche réduit rapidement la liste par nom de fichier, objet de l'e-mail, expéditeur ou marchand.",
          es: 'La búsqueda reduce rápidamente la lista por nombre de archivo, asunto del correo, remitente o comerciante.',
          pt: 'A pesquisa reduz rapidamente a lista por nome de arquivo, assunto do e-mail, remetente ou comerciante.',
          tr: 'Arama, listeyi dosya adına, e-posta konusuna, gönderene veya satıcıya göre hızlıca daraltır.',
          uk: 'Пошук швидко звужує список за назвою файлу, темою листа, відправником або продавцем.',
          zh: '搜索可按文件名、邮件主题、发件人或商家快速缩小列表范围。',
          ar: 'يضيّق البحث القائمة بسرعة حسب اسم الملف أو موضوع البريد الإلكتروني أو المرسل أو التاجر.',
          pl: 'Wyszukiwanie szybko zawęża listę według nazwy pliku, tematu wiadomości, nadawcy lub sprzedawcy.',
          it: 'La ricerca restringe rapidamente la lista per nome file, oggetto email, mittente o commerciante.',
          sk: 'Wyszukiwanie szybko zawęża listę według nazwy pliku, tematu wiadomości, nadawcy lub sprzedawcy.',
          ja: '検索では、ファイル名、電子メールの件名、送信者、または販売者によってリストをすばやく絞り込みます。',
          ko: '검색을 통해 파일 이름, 이메일 제목, 보낸 사람 또는 판매자별로 목록을 빠르게 좁힐 수 있습니다.',
          hi: 'खोज फ़ाइल नाम, ईमेल विषय, प्रेषक, या व्यापारी के आधार पर सूची को शीघ्रता से संक्षिप्त कर देती है।',
          nl: 'Zoeken beperkt de lijst snel op bestandsnaam, e-mailonderwerp, afzender of verkoper.',
          sv: 'Sökning begränsar snabbt listan efter filnamn, e-postämne, avsändare eller handlare.',
          vi: 'Tìm kiếm nhanh chóng thu hẹp danh sách theo tên tệp, chủ đề email, người gửi hoặc người bán.',
          id: 'Pencarian dengan cepat mempersempit daftar berdasarkan nama file, subjek email, pengirim, atau pedagang.',
        }),
      },
      filters: {
        title: t({
          ru: 'Фильтры',
          en: 'Filters',
          kk: 'Сүзгілер',
          de: 'Filter',
          fr: 'Filtres',
          es: 'Filtros',
          pt: 'Filtros',
          tr: 'Filtreler',
          uk: 'Фільтри',
          zh: '筛选器',
          ar: 'الفلاتر',
          pl: 'Filtry',
          it: 'Filtri',
          sk: 'Filtry',
          ja: 'フィルター',
          ko: '필터',
          hi: 'फिल्टर',
          nl: 'Filters',
          sv: 'Filter',
          vi: 'Bộ lọc',
          id: 'Filter',
        }),
        description: t({
          ru: 'Здесь собраны быстрые фильтры и доступ к расширенной панели, чтобы оставить в списке только нужные документы.',
          en: 'This area groups the quick filters and the advanced panel so you can keep only the documents you need in view.',
          kk: 'Бұл аймақта жылдам сүзгілер мен кеңейтілген панель бар, сондықтан тізімде тек керек құжаттарды қалдыра аласыз.',
          de: 'Dieser Bereich bündelt die Schnellfilter und das erweiterte Panel, damit Sie nur die benötigten Dokumente in der Ansicht behalten.',
          fr: "Cette zone regroupe les filtres rapides et le panneau avancé pour n'afficher que les documents dont vous avez besoin.",
          es: 'Esta área agrupa los filtros rápidos y el panel avanzado para mostrar solo los documentos que necesita.',
          pt: 'Esta área agrupa os filtros rápidos e o painel avançado para que você veja apenas os documentos necessários.',
          tr: 'Bu alan, yalnızca ihtiyacınız olan belgeleri görüntülemek için hızlı filtreleri ve gelişmiş paneli bir araya getirir.',
          uk: 'Тут зібрані швидкі фільтри та доступ до розширеної панелі, щоб залишити в списку лише потрібні документи.',
          zh: '此区域汇集了快速筛选器和高级面板，让您只保留需要查看的文档。',
          ar: 'تجمع هذه المنطقة الفلاتر السريعة واللوحة المتقدمة حتى تتمكن من إبقاء المستندات التي تحتاجها فقط في العرض.',
          pl: 'Ten obszar grupuje szybkie filtry i panel zaawansowany, dzięki czemu możesz wyświetlać tylko potrzebne dokumenty.',
          it: "Quest'area raggruppa i filtri rapidi e il pannello avanzato per visualizzare solo i documenti necessari.",
          sk: 'Ten obszar grupuje szybkie filtry i panel zaawansowany, dzięki czemu możesz wyświetlać tylko potrzebne dokumenty.',
          ja: 'この領域にはクイック フィルターと詳細パネルがグループ化されているため、必要なドキュメントのみを表示しておくことができます。',
          ko: '이 영역에는 퀵 필터와 고급 패널이 그룹화되어 있어 필요한 문서만 볼 수 있습니다.',
          hi: 'यह क्षेत्र त्वरित फ़िल्टर और उन्नत पैनल को समूहित करता है ताकि आप केवल उन दस्तावेज़ों को ध्यान में रख सकें जिनकी आपको आवश्यकता है।',
          nl: 'In dit gebied zijn de snelle filters en het geavanceerde paneel gegroepeerd, zodat u alleen de documenten kunt zien die u nodig heeft.',
          sv: 'Det här området grupperar snabbfiltren och den avancerade panelen så att du bara kan se de dokument du behöver.',
          vi: 'Khu vực này nhóm các bộ lọc nhanh và bảng nâng cao để bạn chỉ có thể xem những tài liệu bạn cần.',
          id: 'Area ini mengelompokkan filter cepat dan panel lanjutan sehingga Anda hanya dapat melihat dokumen yang Anda perlukan.',
        }),
      },
      statementsList: {
        title: t({
          ru: 'Список выписок',
          en: 'Statements List',
          kk: 'Үзінділер тізімі',
          de: 'Kontoauszugsliste',
          fr: 'Liste des relevés',
          es: 'Lista de extractos',
          pt: 'Lista de extratos',
          tr: 'Ekstre Listesi',
          uk: 'Список виписок',
          zh: '账单列表',
          ar: 'قائمة كشوف الحسابات',
          pl: 'Lista wyciągów',
          it: 'Elenco estratti conto',
          sk: 'Lista wyciągów',
          ja: 'ステートメントリスト',
          ko: '명세서 목록',
          hi: 'कथन सूची',
          nl: 'Lijst met verklaringen',
          sv: 'Uttalanden Lista',
          vi: 'Danh sách báo cáo',
          id: 'Daftar Pernyataan',
        }),
        description: t({
          ru: 'Основная область показывает найденные документы, их даты, суммы и доступные действия без перехода в другие разделы.',
          en: 'The main list shows the matched documents, their dates, amounts, and the actions available without leaving the page.',
          kk: 'Негізгі тізімде табылған құжаттар, олардың күндері, сомалары және беттен шықпай қолжетімді әрекеттер көрсетіледі.',
          de: 'Die Hauptliste zeigt die gefundenen Dokumente, ihre Daten, Beträge und verfügbaren Aktionen, ohne die Seite zu verlassen.',
          fr: 'La liste principale affiche les documents correspondants, leurs dates, montants et actions disponibles sans quitter la page.',
          es: 'La lista principal muestra los documentos encontrados, sus fechas, importes y acciones disponibles sin salir de la página.',
          pt: 'A lista principal mostra os documentos encontrados, suas datas, valores e ações disponíveis sem sair da página.',
          tr: 'Ana liste, sayfadan ayrılmadan eşleşen belgeleri, tarihlerini, tutarlarını ve kullanılabilir eylemleri gösterir.',
          uk: 'Основна область показує знайдені документи, їх дати, суми та доступні дії без переходу на інші сторінки.',
          zh: '主列表显示匹配的文档、日期、金额以及无需离开页面即可执行的操作。',
          ar: 'تعرض القائمة الرئيسية المستندات المطابقة وتواريخها ومبالغها والإجراءات المتاحة دون مغادرة الصفحة.',
          pl: 'Główna lista pokazuje dopasowane dokumenty, ich daty, kwoty i dostępne akcje bez opuszczania strony.',
          it: "L'elenco principale mostra i documenti trovati, le loro date, gli importi e le azioni disponibili senza lasciare la pagina.",
          sk: 'Główna lista pokazuje dopasowane dokumenty, ich daty, kwoty i dostępne akcje bez opuszczania strony.',
          ja: 'メイン リストには、一致したドキュメント、その日付、金額、およびページを離れることなく実行できるアクションが表示されます。',
          ko: '기본 목록에는 일치하는 문서, 날짜, 금액 및 페이지를 떠나지 않고도 사용할 수 있는 작업이 표시됩니다.',
          hi: 'मुख्य सूची मिलान किए गए दस्तावेज़ों, उनकी तिथियों, राशियों और पृष्ठ को छोड़े बिना उपलब्ध कार्रवाइयों को दिखाती है।',
          nl: 'De hoofdlijst toont de gekoppelde documenten, hun datums, bedragen en de beschikbare acties zonder de pagina te verlaten.',
          sv: 'Huvudlistan visar de matchade dokumenten, deras datum, belopp och tillgängliga åtgärder utan att lämna sidan.',
          vi: 'Danh sách chính hiển thị các tài liệu trùng khớp, ngày tháng, số tiền và các hành động có sẵn mà không cần rời khỏi trang.',
          id: 'Daftar utama menunjukkan dokumen yang cocok, tanggal, jumlah, dan tindakan yang tersedia tanpa meninggalkan halaman.',
        }),
      },
      statementRow: {
        title: t({
          ru: 'Карточка выписки',
          en: 'Statement Row',
          kk: 'Үзінді жолы',
          de: 'Kontoauszugszeile',
          fr: 'Ligne de relevé',
          es: 'Fila de extracto',
          pt: 'Linha de extrato',
          tr: 'Ekstre Satırı',
          uk: 'Рядок виписки',
          zh: '账单行',
          ar: 'صف كشف الحساب',
          pl: 'Wiersz wyciągu',
          it: 'Riga estratto conto',
          sk: 'Wiersz wyciągu',
          ja: 'ステートメント行',
          ko: '명세서 행',
          hi: 'कथन पंक्ति',
          nl: 'Verklaring rij',
          sv: 'Statement Rad',
          vi: 'Hàng câu lệnh',
          id: 'Baris Pernyataan',
        }),
        description: t({
          ru: 'Каждая строка показывает ключевые данные по документу: источник, дату, сумму и текущее состояние обработки. Это хороший ориентир для проверки списка перед следующими действиями.',
          en: 'Each row surfaces the key document details: source, date, amount, and current processing state. It is the best place to quickly validate what is in the list before moving on.',
          kk: 'Әр жол құжаттың негізгі деректерін көрсетеді: көзі, күні, сомасы және өңдеу күйі. Бұл келесі әрекетке өтпес бұрын тізімді жылдам тексерудің ең ыңғайлы жері.',
          de: 'Jede Zeile zeigt die wichtigsten Dokumentdetails: Quelle, Datum, Betrag und aktuellen Verarbeitungsstatus. Dies ist der beste Ort, um die Liste schnell zu überprüfen, bevor Sie fortfahren.',
          fr: "Chaque ligne affiche les détails clés du document : source, date, montant et état de traitement actuel. C'est le meilleur endroit pour valider rapidement le contenu de la liste avant de continuer.",
          es: 'Cada fila muestra los detalles clave del documento: origen, fecha, importe y estado de procesamiento actual. Es el mejor lugar para validar rápidamente la lista antes de continuar.',
          pt: 'Cada linha exibe os detalhes principais do documento: origem, data, valor e estado de processamento atual. É o melhor lugar para validar rapidamente a lista antes de prosseguir.',
          tr: 'Her satır, belgenin temel ayrıntılarını gösterir: kaynak, tarih, tutar ve geçerli işleme durumu. Devam etmeden önce listeyi hızlıca doğrulamak için en iyi yerdir.',
          uk: 'Кожен рядок показує ключові дані документа: джерело, дату, суму та поточний стан обробки. Це найзручніше місце для швидкої перевірки списку перед наступними діями.',
          zh: '每行显示文档的关键信息：来源、日期、金额和当前处理状态。这是继续操作前快速验证列表内容的最佳位置。',
          ar: 'يعرض كل صف التفاصيل الرئيسية للمستند: المصدر والتاريخ والمبلغ وحالة المعالجة الحالية. إنه أفضل مكان للتحقق السريع من القائمة قبل المتابعة.',
          pl: 'Każdy wiersz pokazuje kluczowe szczegóły dokumentu: źródło, datę, kwotę i bieżący stan przetwarzania. To najlepsze miejsce do szybkiej weryfikacji listy przed dalszymi działaniami.',
          it: 'Ogni riga mostra i dettagli chiave del documento: fonte, data, importo e stato di elaborazione corrente. È il posto migliore per verificare rapidamente la lista prima di procedere.',
          sk: 'Każdy wiersz pokazuje kluczowe szczegóły dokumentu: źródło, datę, kwotę i bieżący stan przetwarzania. To najlepsze miejsce do szybkiej weryfikacji listy przed dalszymi działaniami.',
          ja: '各行には、ソース、日付、金額、現在の処理状態などの重要な文書の詳細が表示されます。次に進む前に、リストの内容をすぐに確認するのに最適な場所です。',
          ko: '각 행에는 출처, 날짜, 금액, 현재 처리 상태 등 주요 문서 세부정보가 표시됩니다. 계속 진행하기 전에 목록에 있는 내용을 빠르게 확인할 수 있는 가장 좋은 장소입니다.',
          hi: 'प्रत्येक पंक्ति में प्रमुख दस्तावेज़ विवरण सामने आते हैं: स्रोत, दिनांक, राशि और वर्तमान प्रसंस्करण स्थिति। आगे बढ़ने से पहले सूची में जो है उसे तुरंत सत्यापित करने के लिए यह सबसे अच्छी जगह है।',
          nl: 'Elke rij geeft de belangrijkste documentdetails weer: bron, datum, bedrag en huidige verwerkingsstatus. Het is de beste plaats om snel te valideren wat er in de lijst staat voordat u verder gaat.',
          sv: 'Varje rad visar de viktigaste dokumentdetaljerna: källa, datum, mängd och aktuellt bearbetningsläge. Det är det bästa stället att snabbt validera vad som finns i listan innan du går vidare.',
          vi: 'Mỗi hàng hiển thị các chi tiết chính của tài liệu: nguồn, ngày, số tiền và trạng thái xử lý hiện tại. Đây là nơi tốt nhất để nhanh chóng xác nhận những gì có trong danh sách trước khi tiếp tục.',
          id: 'Setiap baris menampilkan detail dokumen utama: sumber, tanggal, jumlah, dan status pemrosesan saat ini. Ini adalah tempat terbaik untuk memvalidasi dengan cepat apa yang ada dalam daftar sebelum melanjutkan.',
        }),
      },
      completed: {
        title: t({
          ru: 'Готово',
          en: 'All Set',
          kk: 'Дайын',
          de: 'Fertig',
          fr: 'Terminé',
          es: 'Listo',
          pt: 'Pronto',
          tr: 'Hazır',
          uk: 'Готово',
          zh: '完成',
          ar: 'تم',
          pl: 'Gotowe',
          it: 'Fatto',
          sk: 'Gotowe',
          ja: 'オールセット',
          ko: '모든 세트',
          hi: 'सब सेट',
          nl: 'Alles ingesteld',
          sv: 'Allt klart',
          vi: 'Tất cả đã được đặt',
          id: 'Semua Siap',
        }),
        description: t({
          ru: 'Теперь тур отражает текущую страницу выписок. Можно загрузить новый документ или открыть любую строку для продолжения.',
          en: 'The tour now matches the current Statements page. You can upload a new document or open any row to continue.',
          kk: 'Бұл тур енді қазіргі Үзінділер бетіне сай келеді. Енді жаңа құжат жүктеп немесе кез келген жолды ашып жалғастыра аласыз.',
          de: 'Die Tour entspricht nun der aktuellen Kontoauszugsseite. Sie können ein neues Dokument hochladen oder eine beliebige Zeile öffnen, um fortzufahren.',
          fr: "La visite correspond maintenant à la page de relevés actuelle. Vous pouvez télécharger un nouveau document ou ouvrir n'importe quelle ligne pour continuer.",
          es: 'El tour ahora coincide con la página de extractos actual. Puede cargar un nuevo documento o abrir cualquier fila para continuar.',
          pt: 'O tour agora corresponde à página de extratos atual. Você pode fazer upload de um novo documento ou abrir qualquer linha para continuar.',
          tr: 'Tur artık mevcut Ekstreler sayfasıyla uyuşuyor. Yeni bir belge yükleyebilir veya devam etmek için herhangi bir satırı açabilirsiniz.',
          uk: 'Тур тепер відповідає поточній сторінці виписок. Ви можете завантажити новий документ або відкрити будь-який рядок для продовження.',
          zh: '导览现已与当前账单页面匹配。您可以上传新文档或打开任意行继续操作。',
          ar: 'تتطابق الجولة الآن مع صفحة كشوف الحسابات الحالية. يمكنك رفع مستند جديد أو فتح أي صف للمتابعة.',
          pl: 'Przewodnik odpowiada teraz bieżącej stronie wyciągów. Możesz przesłać nowy dokument lub otworzyć dowolny wiersz, aby kontynuować.',
          it: 'Il tour corrisponde ora alla pagina degli estratti conto attuale. Puoi caricare un nuovo documento o aprire qualsiasi riga per continuare.',
          sk: 'Przewodnik odpowiada teraz bieżącej stronie wyciągów. Możesz przesłać nowy dokument lub otworzyć dowolny wiersz, aby kontynuować.',
          ja: 'ツアーが現在のステートメント ページと一致するようになりました。新しいドキュメントをアップロードするか、任意の行を開いて続行できます。',
          ko: '이제 둘러보기가 현재 명세서 페이지와 일치합니다. 계속하려면 새 문서를 업로드하거나 아무 행이나 열면 됩니다.',
          hi: 'यह दौरा अब वर्तमान वक्तव्य पृष्ठ से मेल खाता है। आप एक नया दस्तावेज़ अपलोड कर सकते हैं या जारी रखने के लिए कोई भी पंक्ति खोल सकते हैं।',
          nl: 'De tour komt nu overeen met de huidige Statements-pagina. U kunt een nieuw document uploaden of een rij openen om door te gaan.',
          sv: 'Turnén matchar nu den aktuella sidan med uttalanden. Du kan ladda upp ett nytt dokument eller öppna valfri rad för att fortsätta.',
          vi: 'Chuyến tham quan hiện khớp với trang Tuyên bố hiện tại. Bạn có thể tải lên một tài liệu mới hoặc mở bất kỳ hàng nào để tiếp tục.',
          id: 'Tur sekarang cocok dengan halaman Pernyataan saat ini. Anda dapat mengunggah dokumen baru atau membuka baris mana pun untuk melanjutkan.',
        }),
      },
    },
  },
} satisfies Dictionary;

export default content;
