import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'forgotPasswordPage',
  content: {
    title: t({
      ru: 'Забыли пароль?',
      en: 'Forgot your password?',
      kk: 'Құпия сөзді ұмыттыңыз ба?',
      de: 'Passwort vergessen?',
      fr: 'Mot de passe oublié ?',
      es: '¿Olvidaste tu contraseña?',
      pt: 'Esqueceu sua senha?',
      tr: 'Şifrenizi mi unuttunuz?',
      uk: 'Забули пароль?',
      zh: '忘记密码？',
      ar: 'هل نسيت كلمة المرور؟',
      pl: 'Nie pamiętasz hasła?',
      it: 'Password dimenticata?',
      sk: 'Zabudli ste heslo?',
      ja: 'パスワードをお忘れですか？',
      ko: '비밀번호를 잊으셨나요?',
      hi: 'पासवर्ड भूल गए?',
      nl: 'Wachtwoord vergeten?',
      sv: 'Glömt lösenordet?',
      vi: 'Quên mật khẩu?',
      id: 'Lupa kata sandi?',
      da: 'Glemt din adgangskode?',
      nb: 'Glemt passordet?',
      nn: 'Gløymt passordet?',
      fi: 'Unohditko salasanasi?',
      is: 'Gleymdir þú lykilorðinu?',
      fo: 'Gloymt loyniorðið?',
      cs: 'Zapomněli jste heslo?',
      bg: 'Забравена парола?',
      hr: 'Zaboravili ste lozinku?',
      sr: 'Заборавили сте лозинку?',
      sl: 'Ste pozabili geslo?',
      mk: 'Ја заборавивте лозинката?',
      be: 'Забылі пароль?',
      bs: 'Zaboravili ste lozinku?',
      hsb: 'Zapisne słowo zabyte?',
    }),
    subtitle: t({
      ru: 'Укажите адрес почты — пришлём ссылку для выбора нового пароля.',
      en: 'Enter your email and we will send you a link to choose a new password.',
      kk: 'Электрондық поштаңызды енгізіңіз — жаңа құпия сөз таңдау сілтемесін жібереміз.',
      de: 'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link für ein neues Passwort.',
      fr: 'Saisissez votre e-mail et nous vous enverrons un lien pour choisir un nouveau mot de passe.',
      es: 'Introduce tu correo y te enviaremos un enlace para elegir una nueva contraseña.',
      pt: 'Informe seu e-mail e enviaremos um link para escolher uma nova senha.',
      tr: 'E-posta adresinizi girin, yeni şifre belirlemeniz için bir bağlantı gönderelim.',
      uk: 'Вкажіть адресу пошти — надішлемо посилання для вибору нового пароля.',
      zh: '输入您的邮箱，我们会发送重设密码的链接。',
      ar: 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لاختيار كلمة مرور جديدة.',
      pl: 'Podaj adres e-mail, a wyślemy link do ustawienia nowego hasła.',
      it: 'Inserisci la tua email e ti invieremo un link per scegliere una nuova password.',
      sk: 'Zadajte svoj e-mail a pošleme vám odkaz na nastavenie nového hesla.',
      ja: 'メールアドレスを入力してください。新しいパスワードを設定するリンクをお送りします。',
      ko: '이메일을 입력하시면 새 비밀번호를 설정할 수 있는 링크를 보내드립니다.',
      hi: 'अपना ईमेल दर्ज करें, हम नया पासवर्ड चुनने का लिंक भेजेंगे।',
      nl: 'Vul je e-mailadres in en we sturen je een link om een nieuw wachtwoord te kiezen.',
      sv: 'Ange din e-postadress så skickar vi en länk för att välja ett nytt lösenord.',
      vi: 'Nhập email của bạn và chúng tôi sẽ gửi liên kết để chọn mật khẩu mới.',
      id: 'Masukkan email Anda dan kami akan mengirim tautan untuk membuat kata sandi baru.',
      da: 'Indtast din e-mail, og vi sender dig et link til at vælge en ny adgangskode.',
      nb: 'Skriv inn e-postadressen din, og vi sender deg en lenke for å velge et nytt passord.',
      nn: 'Skriv inn e-postadressa di, og vi sender deg ei lenkje for å velje eit nytt passord.',
      fi: 'Anna sähköpostiosoitteesi, niin lähetämme sinulle linkin uuden salasanan valitsemiseen.',
      is: 'Sláðu inn netfangið þitt og við sendum þér hlekk til að velja nýtt lykilorð.',
      fo: 'Skriva t-postadressuna hjá tær, og vit senda tær eitt leinki at velja eitt nýtt loyniorð.',
      cs: 'Zadejte svůj e-mail a my vám pošleme odkaz pro volbu nového hesla.',
      bg: 'Въведете имейла си и ще ви изпратим връзка за избор на нова парола.',
      hr: 'Unesite svoju e-poštu i poslat ćemo vam vezu za odabir nove lozinke.',
      sr: 'Унесите своју е-пошту и послаћемо вам везу за избор нове лозинке.',
      sl: 'Vnesite svoj e-naslov in poslali vam bomo povezavo za izbiro novega gesla.',
      mk: 'Внесете ја вашата е-пошта и ќе ви испратиме врска за избор на нова лозинка.',
      be: 'Увядзіце свой адрас электроннай пошты, і мы дашлем вам спасылку для выбару новага пароля.',
      bs: 'Unesite svoju e-poštu i poslat ćemo vam link za odabir nove lozinke.',
      hsb: 'Zapodajće swoju e-mejlowu adresu a pósćelemy wam wotkaz za wuzwolenje noweho zapisneho słowa.',
    }),
    emailLabel: t({
      ru: 'Электронная почта',
      en: 'Email',
      kk: 'Электрондық пошта',
      de: 'E-Mail',
      fr: 'E-mail',
      es: 'Correo electrónico',
      pt: 'E-mail',
      tr: 'E-posta',
      uk: 'Електронна пошта',
      zh: '邮箱',
      ar: 'البريد الإلكتروني',
      pl: 'E-mail',
      it: 'Email',
      sk: 'Email',
      ja: 'メールアドレス',
      ko: '이메일',
      hi: 'ईमेल',
      nl: 'E-mail',
      sv: 'E-post',
      vi: 'Email',
      id: 'Email',
      da: 'E-mail',
      nb: 'E-post',
      nn: 'E-post',
      fi: 'Sähköposti',
      is: 'Netfang',
      fo: 'T-postur',
      cs: 'E-mail',
      bg: 'Имейл',
      hr: 'E-pošta',
      sr: 'Е-пошта',
      sl: 'E-naslov',
      mk: 'Е-пошта',
      be: 'Эл. пошта',
      bs: 'E-pošta',
      hsb: 'E-mejl',
    }),
    submit: t({
      ru: 'Отправить ссылку',
      en: 'Send reset link',
      kk: 'Сілтеме жіберу',
      de: 'Link senden',
      fr: 'Envoyer le lien',
      es: 'Enviar enlace',
      pt: 'Enviar link',
      tr: 'Bağlantı gönder',
      uk: 'Надіслати посилання',
      zh: '发送链接',
      ar: 'إرسال الرابط',
      pl: 'Wyślij link',
      it: 'Invia link',
      sk: 'Odoslať odkaz',
      ja: 'リンクを送信',
      ko: '링크 보내기',
      hi: 'लिंक भेजें',
      nl: 'Link versturen',
      sv: 'Skicka länk',
      vi: 'Gửi liên kết',
      id: 'Kirim tautan',
      da: 'Send nulstillingslink',
      nb: 'Send tilbakestillingslenke',
      nn: 'Send tilbakestillingslenkje',
      fi: 'Lähetä palautuslinkki',
      is: 'Senda endurstillingarhlekk',
      fo: 'Send endurstillingarleinki',
      cs: 'Odeslat odkaz pro obnovení',
      bg: 'Изпрати връзка за нулиране',
      hr: 'Pošalji vezu za ponovno postavljanje',
      sr: 'Пошаљи везу за ресетовање',
      sl: 'Pošlji povezavo za ponastavitev',
      mk: 'Испрати врска за ресетирање',
      be: 'Даслаць спасылку для скіду',
      bs: 'Pošalji link za resetovanje',
      hsb: 'Wotkaz za wobnowjenje pósłać',
    }),
    sending: t({
      ru: 'Отправляем…',
      en: 'Sending…',
      kk: 'Жіберілуде…',
      de: 'Wird gesendet…',
      fr: 'Envoi…',
      es: 'Enviando…',
      pt: 'Enviando…',
      tr: 'Gönderiliyor…',
      uk: 'Надсилаємо…',
      zh: '发送中…',
      ar: 'جارٍ الإرسال…',
      pl: 'Wysyłanie…',
      it: 'Invio…',
      sk: 'Odosielanie…',
      ja: '送信中…',
      ko: '보내는 중…',
      hi: 'भेजा जा रहा है…',
      nl: 'Versturen…',
      sv: 'Skickar…',
      vi: 'Đang gửi…',
      id: 'Mengirim…',
      da: 'Sender…',
      nb: 'Sender…',
      nn: 'Sender…',
      fi: 'Lähetetään…',
      is: 'Sendi…',
      fo: 'Sendi…',
      cs: 'Odesílání…',
      bg: 'Изпраща се…',
      hr: 'Šaljem…',
      sr: 'Шаљем…',
      sl: 'Pošiljam…',
      mk: 'Се испраќа…',
      be: 'Адпраўляем…',
      bs: 'Šaljem…',
      hsb: 'Sćele so…',
    }),
    sent: t({
      ru: 'Если аккаунт с таким адресом существует, ссылка уже отправлена. Проверьте почту.',
      en: 'If that address has an account, a reset link is on its way. Check your inbox.',
      kk: 'Егер осы мекенжайда есептік жазба болса, сілтеме жіберілді. Поштаңызды тексеріңіз.',
      de: 'Falls zu dieser Adresse ein Konto gehört, ist der Link unterwegs. Prüfen Sie Ihr Postfach.',
      fr: 'Si un compte existe pour cette adresse, le lien est en route. Consultez votre boîte mail.',
      es: 'Si existe una cuenta con esa dirección, el enlace ya está en camino. Revisa tu correo.',
      pt: 'Se houver uma conta com esse endereço, o link já está a caminho. Verifique seu e-mail.',
      tr: 'Bu adrese ait bir hesap varsa bağlantı yolda. Gelen kutunuzu kontrol edin.',
      uk: 'Якщо обліковий запис із такою адресою існує, посилання вже надіслано. Перевірте пошту.',
      zh: '如果该邮箱已注册，链接已发送。请查收邮件。',
      ar: 'إذا كان لهذا العنوان حساب، فالرابط في طريقه إليك. تحقّق من بريدك.',
      pl: 'Jeśli konto z tym adresem istnieje, link został wysłany. Sprawdź skrzynkę.',
      it: 'Se esiste un account con quell’indirizzo, il link è in arrivo. Controlla la posta.',
      sk: 'Ak k tejto adrese patrí účet, odkaz je na ceste. Skontrolujte si schránku.',
      ja: 'そのアドレスのアカウントが存在する場合、リンクを送信しました。メールをご確認ください。',
      ko: '해당 주소로 등록된 계정이 있다면 링크가 발송되었습니다. 메일함을 확인해 주세요.',
      hi: 'यदि उस पते से खाता जुड़ा है, तो लिंक भेज दिया गया है। अपना इनबॉक्स देखें।',
      nl: 'Als er een account bij dat adres hoort, is de link onderweg. Controleer je inbox.',
      sv: 'Om adressen hör till ett konto är länken på väg. Kolla din inkorg.',
      vi: 'Nếu địa chỉ đó có tài khoản, liên kết đã được gửi. Hãy kiểm tra hộp thư.',
      id: 'Jika alamat itu punya akun, tautan sudah dikirim. Periksa kotak masuk Anda.',
      da: 'Hvis der findes en konto med den adresse, er et nulstillingslink på vej. Tjek din indbakke.',
      nb: 'Hvis den adressen har en konto, er en tilbakestillingslenke på vei. Sjekk innboksen din.',
      nn: 'Dersom den adressa har ein konto, er ei tilbakestillingslenkje på veg. Sjekk innboksen din.',
      fi: 'Jos osoitteella on tili, palautuslinkki on tulossa. Tarkista sähköpostisi.',
      is: 'Ef netfangið er með reikning er endurstillingarhlekkur á leiðinni. Athugaðu pósthólfið þitt.',
      fo: 'Um henda adressan hevur eina kontu, er eitt endurstillingarleinki á veg. Kanna postkassan.',
      cs: 'Pokud k této adrese existuje účet, odkaz pro obnovení je na cestě. Zkontrolujte poštu.',
      bg: 'Ако за този адрес има акаунт, връзката за нулиране пътува към вас. Проверете пощата си.',
      hr: 'Ako za tu adresu postoji račun, veza za ponovno postavljanje je na putu. Provjerite poštu.',
      sr: 'Ако за ту адресу постоји рачун, веза за ресетовање је на путу. Проверите пошту.',
      sl: 'Če za ta naslov obstaja račun, je povezava za ponastavitev na poti. Preverite pošto.',
      mk: 'Ако за таа адреса има сметка, врската за ресетирање е на пат. Проверете ја поштата.',
      be: 'Калі для гэтага адраса ёсць акаўнт, спасылка для скіду ўжо ў дарозе. Праверце пошту.',
      bs: 'Ako za tu adresu postoji račun, link za resetovanje je na putu. Provjerite poštu.',
      hsb: 'Jeli za tu adresu konto eksistuje, je wotkaz za wobnowjenje po puću. Pohladajće do swojeho póstoweho kašćika.',
    }),
    backToLogin: t({
      ru: 'Вернуться ко входу',
      en: 'Back to sign in',
      kk: 'Кіру бетіне оралу',
      de: 'Zurück zur Anmeldung',
      fr: 'Retour à la connexion',
      es: 'Volver a iniciar sesión',
      pt: 'Voltar para entrar',
      tr: 'Girişe dön',
      uk: 'Повернутися до входу',
      zh: '返回登录',
      ar: 'العودة لتسجيل الدخول',
      pl: 'Powrót do logowania',
      it: 'Torna all’accesso',
      sk: 'Späť na prihlásenie',
      ja: 'ログインに戻る',
      ko: '로그인으로 돌아가기',
      hi: 'साइन इन पर लौटें',
      nl: 'Terug naar inloggen',
      sv: 'Tillbaka till inloggning',
      vi: 'Quay lại đăng nhập',
      id: 'Kembali ke masuk',
      da: 'Tilbage til login',
      nb: 'Tilbake til innlogging',
      nn: 'Tilbake til innlogging',
      fi: 'Takaisin kirjautumiseen',
      is: 'Til baka í innskráningu',
      fo: 'Aftur til innritan',
      cs: 'Zpět na přihlášení',
      bg: 'Назад към входа',
      hr: 'Natrag na prijavu',
      sr: 'Назад на пријаву',
      sl: 'Nazaj na prijavo',
      mk: 'Назад на најава',
      be: 'Назад да ўваходу',
      bs: 'Nazad na prijavu',
      hsb: 'Wróćo k přizjewjenju',
    }),
    genericError: t({
      ru: 'Не удалось отправить ссылку. Попробуйте ещё раз.',
      en: 'Could not send the reset link. Please try again.',
      kk: 'Сілтемені жіберу мүмкін болмады. Қайталап көріңіз.',
      de: 'Der Link konnte nicht gesendet werden. Bitte erneut versuchen.',
      fr: 'Impossible d’envoyer le lien. Veuillez réessayer.',
      es: 'No se pudo enviar el enlace. Inténtalo de nuevo.',
      pt: 'Não foi possível enviar o link. Tente novamente.',
      tr: 'Bağlantı gönderilemedi. Lütfen tekrar deneyin.',
      uk: 'Не вдалося надіслати посилання. Спробуйте ще раз.',
      zh: '无法发送链接，请重试。',
      ar: 'تعذّر إرسال الرابط. حاول مرة أخرى.',
      pl: 'Nie udało się wysłać linku. Spróbuj ponownie.',
      it: 'Impossibile inviare il link. Riprova.',
      sk: 'Odkaz sa nepodarilo odoslať. Skúste to znova.',
      ja: 'リンクを送信できませんでした。もう一度お試しください。',
      ko: '링크를 보내지 못했습니다. 다시 시도해 주세요.',
      hi: 'लिंक नहीं भेजा जा सका। कृपया पुनः प्रयास करें।',
      nl: 'Kon de link niet versturen. Probeer het opnieuw.',
      sv: 'Kunde inte skicka länken. Försök igen.',
      vi: 'Không gửi được liên kết. Vui lòng thử lại.',
      id: 'Tidak dapat mengirim tautan. Silakan coba lagi.',
      da: 'Nulstillingslinket kunne ikke sendes. Prøv igen.',
      nb: 'Kunne ikke sende tilbakestillingslenken. Prøv igjen.',
      nn: 'Kunne ikkje sende tilbakestillingslenkja. Prøv igjen.',
      fi: 'Palautuslinkin lähettäminen ei onnistunut. Yritä uudelleen.',
      is: 'Ekki var unnt að senda endurstillingarhlekkinn. Reyndu aftur.',
      fo: 'Fekk ikki sent endurstillingarleinkið. Royn aftur.',
      cs: 'Odkaz pro obnovení se nepodařilo odeslat. Zkuste to znovu.',
      bg: 'Връзката за нулиране не можа да бъде изпратена. Опитайте отново.',
      hr: 'Veza za ponovno postavljanje nije poslana. Pokušajte ponovno.',
      sr: 'Веза за ресетовање није послата. Пробајте поново.',
      sl: 'Povezave za ponastavitev ni bilo mogoče poslati. Poskusite znova.',
      mk: 'Врската за ресетирање не можеше да се испрати. Обидете се повторно.',
      be: 'Не ўдалося даслаць спасылку для скіду. Паспрабуйце зноў.',
      bs: 'Link za resetovanje nije poslan. Pokušajte ponovo.',
      hsb: 'Wotkaz za wobnowjenje njeda so pósłać. Spytajće hišće raz.',
    }),
  },
} satisfies Dictionary;

export default content;
