import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'forgotPasswordPage',
  content: {
    title: t({
      ru: 'Забыли пароль?',
      en: 'Forgot your password?',
      kk: 'Құпия сөзді ұмыттыңыз ба?',
      de: 'Passwort vergessen?',
      fr: 'Mot de passe oublié ?',
      es: '¿Olvidaste tu contraseña?',
      pt: 'Esqueceu sua senha?',
      tr: 'Şifrenizi mi unuttunuz?',
      uk: 'Забули пароль?',
      zh: '忘记密码？',
      ar: 'هل نسيت كلمة المرور؟',
      pl: 'Nie pamiętasz hasła?',
      it: 'Password dimenticata?',
      sk: 'Zabudli ste heslo?',
      ja: 'パスワードをお忘れですか？',
      ko: '비밀번호를 잊으셨나요?',
      hi: 'पासवर्ड भूल गए?',
      nl: 'Wachtwoord vergeten?',
      sv: 'Glömt lösenordet?',
      vi: 'Quên mật khẩu?',
      id: 'Lupa kata sandi?',
    }),
    subtitle: t({
      ru: 'Укажите адрес почты — пришлём ссылку для выбора нового пароля.',
      en: 'Enter your email and we will send you a link to choose a new password.',
      kk: 'Электрондық поштаңызды енгізіңіз — жаңа құпия сөз таңдау сілтемесін жібереміз.',
      de: 'Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link für ein neues Passwort.',
      fr: 'Saisissez votre e-mail et nous vous enverrons un lien pour choisir un nouveau mot de passe.',
      es: 'Introduce tu correo y te enviaremos un enlace para elegir una nueva contraseña.',
      pt: 'Informe seu e-mail e enviaremos um link para escolher uma nova senha.',
      tr: 'E-posta adresinizi girin, yeni şifre belirlemeniz için bir bağlantı gönderelim.',
      uk: 'Вкажіть адресу пошти — надішлемо посилання для вибору нового пароля.',
      zh: '输入您的邮箱，我们会发送重设密码的链接。',
      ar: 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لاختيار كلمة مرور جديدة.',
      pl: 'Podaj adres e-mail, a wyślemy link do ustawienia nowego hasła.',
      it: 'Inserisci la tua email e ti invieremo un link per scegliere una nuova password.',
      sk: 'Zadajte svoj e-mail a pošleme vám odkaz na nastavenie nového hesla.',
      ja: 'メールアドレスを入力してください。新しいパスワードを設定するリンクをお送りします。',
      ko: '이메일을 입력하시면 새 비밀번호를 설정할 수 있는 링크를 보내드립니다.',
      hi: 'अपना ईमेल दर्ज करें, हम नया पासवर्ड चुनने का लिंक भेजेंगे।',
      nl: 'Vul je e-mailadres in en we sturen je een link om een nieuw wachtwoord te kiezen.',
      sv: 'Ange din e-postadress så skickar vi en länk för att välja ett nytt lösenord.',
      vi: 'Nhập email của bạn và chúng tôi sẽ gửi liên kết để chọn mật khẩu mới.',
      id: 'Masukkan email Anda dan kami akan mengirim tautan untuk membuat kata sandi baru.',
    }),
    emailLabel: t({
      ru: 'Электронная почта',
      en: 'Email',
      kk: 'Электрондық пошта',
      de: 'E-Mail',
      fr: 'E-mail',
      es: 'Correo electrónico',
      pt: 'E-mail',
      tr: 'E-posta',
      uk: 'Електронна пошта',
      zh: '邮箱',
      ar: 'البريد الإلكتروني',
      pl: 'E-mail',
      it: 'Email',
      sk: 'E-mail',
      ja: 'メールアドレス',
      ko: '이메일',
      hi: 'ईमेल',
      nl: 'E-mail',
      sv: 'E-post',
      vi: 'Email',
      id: 'Email',
    }),
    submit: t({
      ru: 'Отправить ссылку',
      en: 'Send reset link',
      kk: 'Сілтеме жіберу',
      de: 'Link senden',
      fr: 'Envoyer le lien',
      es: 'Enviar enlace',
      pt: 'Enviar link',
      tr: 'Bağlantı gönder',
      uk: 'Надіслати посилання',
      zh: '发送链接',
      ar: 'إرسال الرابط',
      pl: 'Wyślij link',
      it: 'Invia link',
      sk: 'Odoslať odkaz',
      ja: 'リンクを送信',
      ko: '링크 보내기',
      hi: 'लिंक भेजें',
      nl: 'Link versturen',
      sv: 'Skicka länk',
      vi: 'Gửi liên kết',
      id: 'Kirim tautan',
    }),
    sending: t({
      ru: 'Отправляем…',
      en: 'Sending…',
      kk: 'Жіберілуде…',
      de: 'Wird gesendet…',
      fr: 'Envoi…',
      es: 'Enviando…',
      pt: 'Enviando…',
      tr: 'Gönderiliyor…',
      uk: 'Надсилаємо…',
      zh: '发送中…',
      ar: 'جارٍ الإرسال…',
      pl: 'Wysyłanie…',
      it: 'Invio…',
      sk: 'Odosielanie…',
      ja: '送信中…',
      ko: '보내는 중…',
      hi: 'भेजा जा रहा है…',
      nl: 'Versturen…',
      sv: 'Skickar…',
      vi: 'Đang gửi…',
      id: 'Mengirim…',
    }),
    sent: t({
      ru: 'Если аккаунт с таким адресом существует, ссылка уже отправлена. Проверьте почту.',
      en: 'If that address has an account, a reset link is on its way. Check your inbox.',
      kk: 'Егер осы мекенжайда есептік жазба болса, сілтеме жіберілді. Поштаңызды тексеріңіз.',
      de: 'Falls zu dieser Adresse ein Konto gehört, ist der Link unterwegs. Prüfen Sie Ihr Postfach.',
      fr: 'Si un compte existe pour cette adresse, le lien est en route. Consultez votre boîte mail.',
      es: 'Si existe una cuenta con esa dirección, el enlace ya está en camino. Revisa tu correo.',
      pt: 'Se houver uma conta com esse endereço, o link já está a caminho. Verifique seu e-mail.',
      tr: 'Bu adrese ait bir hesap varsa bağlantı yolda. Gelen kutunuzu kontrol edin.',
      uk: 'Якщо обліковий запис із такою адресою існує, посилання вже надіслано. Перевірте пошту.',
      zh: '如果该邮箱已注册，链接已发送。请查收邮件。',
      ar: 'إذا كان لهذا العنوان حساب، فالرابط في طريقه إليك. تحقّق من بريدك.',
      pl: 'Jeśli konto z tym adresem istnieje, link został wysłany. Sprawdź skrzynkę.',
      it: 'Se esiste un account con quell’indirizzo, il link è in arrivo. Controlla la posta.',
      sk: 'Ak k tejto adrese patrí účet, odkaz je na ceste. Skontrolujte si schránku.',
      ja: 'そのアドレスのアカウントが存在する場合、リンクを送信しました。メールをご確認ください。',
      ko: '해당 주소로 등록된 계정이 있다면 링크가 발송되었습니다. 메일함을 확인해 주세요.',
      hi: 'यदि उस पते से खाता जुड़ा है, तो लिंक भेज दिया गया है। अपना इनबॉक्स देखें।',
      nl: 'Als er een account bij dat adres hoort, is de link onderweg. Controleer je inbox.',
      sv: 'Om adressen hör till ett konto är länken på väg. Kolla din inkorg.',
      vi: 'Nếu địa chỉ đó có tài khoản, liên kết đã được gửi. Hãy kiểm tra hộp thư.',
      id: 'Jika alamat itu punya akun, tautan sudah dikirim. Periksa kotak masuk Anda.',
    }),
    backToLogin: t({
      ru: 'Вернуться ко входу',
      en: 'Back to sign in',
      kk: 'Кіру бетіне оралу',
      de: 'Zurück zur Anmeldung',
      fr: 'Retour à la connexion',
      es: 'Volver a iniciar sesión',
      pt: 'Voltar para entrar',
      tr: 'Girişe dön',
      uk: 'Повернутися до входу',
      zh: '返回登录',
      ar: 'العودة لتسجيل الدخول',
      pl: 'Powrót do logowania',
      it: 'Torna all’accesso',
      sk: 'Späť na prihlásenie',
      ja: 'ログインに戻る',
      ko: '로그인으로 돌아가기',
      hi: 'साइन इन पर लौटें',
      nl: 'Terug naar inloggen',
      sv: 'Tillbaka till inloggning',
      vi: 'Quay lại đăng nhập',
      id: 'Kembali ke masuk',
    }),
    genericError: t({
      ru: 'Не удалось отправить ссылку. Попробуйте ещё раз.',
      en: 'Could not send the reset link. Please try again.',
      kk: 'Сілтемені жіберу мүмкін болмады. Қайталап көріңіз.',
      de: 'Der Link konnte nicht gesendet werden. Bitte erneut versuchen.',
      fr: 'Impossible d’envoyer le lien. Veuillez réessayer.',
      es: 'No se pudo enviar el enlace. Inténtalo de nuevo.',
      pt: 'Não foi possível enviar o link. Tente novamente.',
      tr: 'Bağlantı gönderilemedi. Lütfen tekrar deneyin.',
      uk: 'Не вдалося надіслати посилання. Спробуйте ще раз.',
      zh: '无法发送链接，请重试。',
      ar: 'تعذّر إرسال الرابط. حاول مرة أخرى.',
      pl: 'Nie udało się wysłać linku. Spróbuj ponownie.',
      it: 'Impossibile inviare il link. Riprova.',
      sk: 'Odkaz sa nepodarilo odoslať. Skúste to znova.',
      ja: 'リンクを送信できませんでした。もう一度お試しください。',
      ko: '링크를 보내지 못했습니다. 다시 시도해 주세요.',
      hi: 'लिंक नहीं भेजा जा सका। कृपया पुनः प्रयास करें।',
      nl: 'Kon de link niet versturen. Probeer het opnieuw.',
      sv: 'Kunde inte skicka länken. Försök igen.',
      vi: 'Không gửi được liên kết. Vui lòng thử lại.',
      id: 'Tidak dapat mengirim tautan. Silakan coba lagi.',
    }),
  },
} satisfies Dictionary;

export default content;
