/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'bankSyncPanel',
  content: {
    status: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Status',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Status',
      it: 'Stato',
      sk: 'Stav',
      ja: 'ステータス',
      ko: '상태',
      hi: 'स्थिति',
      nl: 'Status',
      sv: 'Status',
      vi: 'Trạng thái',
      id: 'Status',
      da: 'Status',
      nb: 'Status',
      nn: 'Status',
      fi: 'Tila',
      is: 'Staða',
      fo: 'Støða',
      cs: 'Stav',
      bg: 'Статус',
      hr: 'Status',
      sr: 'Статус',
      sl: 'Stanje',
      mk: 'Статус',
      be: 'Статус',
      bs: 'Status',
      hsb: 'Status',
    }),
    statusConnected: t({
      ru: 'Подключено',
      en: 'Connected',
      kk: 'Қосылған',
      de: 'Verbunden',
      fr: 'Connecté',
      es: 'Conectado',
      pt: 'Conectado',
      tr: 'Bağlı',
      uk: 'Підключено',
      zh: '已连接',
      ar: 'متصل',
      pl: 'Połączono',
      it: 'Connesso',
      sk: 'Pripojené',
      ja: '接続済み',
      ko: '연결됨',
      hi: 'कनेक्टेड',
      nl: 'Verbonden',
      sv: 'Ansluten',
      vi: 'Đã kết nối',
      id: 'Terhubung',
      da: 'Forbundet',
      nb: 'Tilkoblet',
      nn: 'Tilkopla',
      fi: 'Yhdistetty',
      is: 'Tengt',
      fo: 'Tengt',
      cs: 'Připojeno',
      bg: 'Свързано',
      hr: 'Povezano',
      sr: 'Повезано',
      sl: 'Povezano',
      mk: 'Поврзано',
      be: 'Падключана',
      bs: 'Povezano',
      hsb: 'Zwjazany',
    }),
    statusDisconnected: t({
      ru: 'Не подключено',
      en: 'Not connected',
      kk: 'Қосылмаған',
      de: 'Nicht verbunden',
      fr: 'Non connecté',
      es: 'No conectado',
      pt: 'Não conectado',
      tr: 'Bağlı değil',
      uk: 'Не підключено',
      zh: '未连接',
      ar: 'غير متصل',
      pl: 'Nie połączono',
      it: 'Non connesso',
      sk: 'Nepripojené',
      ja: '未接続',
      ko: '연결 안 됨',
      hi: 'कनेक्ट नहीं',
      nl: 'Niet verbonden',
      sv: 'Inte ansluten',
      vi: 'Chưa kết nối',
      id: 'Tidak terhubung',
      da: 'Ikke forbundet',
      nb: 'Ikke tilkoblet',
      nn: 'Ikkje tilkopla',
      fi: 'Ei yhdistetty',
      is: 'Ekki tengt',
      fo: 'Ikki tengt',
      cs: 'Nepřipojeno',
      bg: 'Не е свързано',
      hr: 'Nije povezano',
      sr: 'Није повезано',
      sl: 'Ni povezano',
      mk: 'Не е поврзано',
      be: 'Не падключана',
      bs: 'Nije povezano',
      hsb: 'Njezwjazany',
    }),
    needsReauth: t({
      ru: 'Нужен новый токен',
      en: 'Needs a new token',
      kk: 'Жаңа токен қажет',
      de: 'Neues Token nötig',
      fr: 'Nouveau jeton requis',
      es: 'Necesita un token nuevo',
      pt: 'Precisa de um novo token',
      tr: 'Yeni belirteç gerekli',
      uk: 'Потрібен новий токен',
      zh: '需要新令牌',
      ar: 'يلزم رمز جديد',
      pl: 'Potrzebny nowy token',
      it: 'Serve un nuovo token',
      sk: 'Potrebný nový token',
      ja: '新しいトークンが必要',
      ko: '새 토큰 필요',
      hi: 'नया टोकन चाहिए',
      nl: 'Nieuw token nodig',
      sv: 'Ny token krävs',
      vi: 'Cần mã mới',
      id: 'Perlu token baru',
      da: 'Kræver et nyt token',
      nb: 'Trenger et nytt token',
      nn: 'Treng eit nytt token',
      fi: 'Tarvitaan uusi tunnus',
      is: 'Þarf nýjan tóka',
      fo: 'Tørvar nýggjan tekin',
      cs: 'Je potřeba nový token',
      bg: 'Нужен е нов токен',
      hr: 'Potreban je novi token',
      sr: 'Потребан је нови токен',
      sl: 'Potreben je nov žeton',
      mk: 'Потребен е нов токен',
      be: 'Патрэбны новы токен',
      bs: 'Potreban je novi token',
      hsb: 'Trjeba so nowy token',
    }),
    howItWorks: t({
      ru: 'Lumio не держит собственной интеграции с банками. Вы подключаете свой аккаунт SimpleFIN Bridge (отдельная платная услуга SimpleFIN), а Lumio забирает выписки по открытому протоколу и проводит их через обычный импорт: дедупликация, правила, очередь проверки. Доступ хранится зашифрованным, выгрузка каждые шесть часов или по кнопке.',
      en: 'Lumio holds no bank integration of its own. You connect your own SimpleFIN Bridge account (a separate, paid service from SimpleFIN); Lumio pulls statements over the open protocol and runs them through the usual import: dedupe, rules, the review inbox. The credential is stored encrypted; pulls run every six hours or on demand.',
      kk: 'Lumio-ның өз банк интеграциясы жоқ. Сіз өз SimpleFIN Bridge тіркелгіңізді қосасыз (SimpleFIN-нің бөлек ақылы қызметі); Lumio үзінділерді ашық хаттама арқылы алып, әдеттегі импорттан өткізеді: қайталануды алып тастау, ережелер, тексеру кезегі. Қатынау шифрланып сақталады; жүктеу әр алты сағат сайын немесе сұрау бойынша.',
      de: 'Lumio hat keine eigene Bankanbindung. Sie verbinden Ihr eigenes SimpleFIN-Bridge-Konto (ein separater, kostenpflichtiger Dienst von SimpleFIN); Lumio holt Umsätze über das offene Protokoll und schickt sie durch den normalen Import: Dublettenprüfung, Regeln, Prüf-Eingang. Der Zugang wird verschlüsselt gespeichert; abgerufen wird alle sechs Stunden oder auf Knopfdruck.',
      fr: "Lumio n'a pas d'intégration bancaire propre. Vous connectez votre compte SimpleFIN Bridge (service payant distinct de SimpleFIN) ; Lumio récupère les relevés via le protocole ouvert et les passe par l'import habituel : dédoublonnage, règles, boîte de revue. L'accès est stocké chiffré ; récupération toutes les six heures ou à la demande.",
      es: 'Lumio no tiene integración bancaria propia. Conectas tu cuenta de SimpleFIN Bridge (un servicio de pago aparte de SimpleFIN); Lumio descarga los movimientos por el protocolo abierto y los pasa por la importación habitual: deduplicación, reglas, bandeja de revisión. El acceso se guarda cifrado; se descarga cada seis horas o a petición.',
      pt: 'O Lumio não tem integração bancária própria. Você conecta sua conta SimpleFIN Bridge (um serviço pago à parte da SimpleFIN); o Lumio puxa os extratos pelo protocolo aberto e os passa pela importação normal: deduplicação, regras, caixa de revisão. O acesso fica guardado cifrado; a busca roda a cada seis horas ou sob demanda.',
      tr: "Lumio'nun kendi banka entegrasyonu yoktur. Kendi SimpleFIN Bridge hesabınızı bağlarsınız (SimpleFIN'in ayrı, ücretli hizmeti); Lumio ekstreleri açık protokolle çeker ve olağan içe aktarmadan geçirir: yineleme ayıklama, kurallar, inceleme kutusu. Erişim şifreli saklanır; çekim altı saatte bir veya istekle yapılır.",
      uk: 'Lumio не має власної інтеграції з банками. Ви підключаєте свій акаунт SimpleFIN Bridge (окрема платна послуга SimpleFIN); Lumio забирає виписки за відкритим протоколом і проводить їх через звичайний імпорт: дедуплікація, правила, черга перевірки. Доступ зберігається зашифрованим; вивантаження кожні шість годин або за кнопкою.',
      zh: 'Lumio 自身不提供银行集成。您连接自己的 SimpleFIN Bridge 账户（SimpleFIN 的独立付费服务）；Lumio 通过开放协议拉取对账单并走常规导入：去重、规则、审核收件箱。凭据加密保存；每六小时或按需拉取。',
      ar: 'لا يملك Lumio تكاملًا مصرفيًا خاصًا به. تربط حساب SimpleFIN Bridge الخاص بك (خدمة مدفوعة منفصلة من SimpleFIN)؛ يسحب Lumio الكشوف عبر البروتوكول المفتوح ويمررها عبر الاستيراد المعتاد: إزالة التكرار، القواعد، صندوق المراجعة. تُخزَّن بيانات الوصول مشفرة؛ السحب كل ست ساعات أو عند الطلب.',
      pl: 'Lumio nie ma własnej integracji z bankami. Podłączasz własne konto SimpleFIN Bridge (osobna, płatna usługa SimpleFIN); Lumio pobiera wyciągi otwartym protokołem i przepuszcza je przez zwykły import: deduplikację, reguły, skrzynkę przeglądu. Dostęp jest przechowywany w postaci zaszyfrowanej; pobieranie co sześć godzin lub na żądanie.',
      it: "Lumio non ha un'integrazione bancaria propria. Colleghi il tuo account SimpleFIN Bridge (servizio a pagamento separato di SimpleFIN); Lumio scarica gli estratti con il protocollo aperto e li passa dall'import consueto: deduplica, regole, coda di revisione. L'accesso è salvato cifrato; scaricamento ogni sei ore o su richiesta.",
      sk: 'Lumio nemá vlastnú integráciu s bankami. Pripojíte vlastný účet SimpleFIN Bridge (samostatná platená služba SimpleFIN); Lumio stiahne výpisy otvoreným protokolom a prevedie ich bežným importom: deduplikácia, pravidlá, kontrolný priečinok. Prístup je uložený šifrovane; sťahovanie každých šesť hodín alebo na požiadanie.',
      ja: 'Lumio は独自の銀行連携を持ちません。ご自身の SimpleFIN Bridge アカウント（SimpleFIN の別途有料サービス）を接続すると、Lumio がオープンプロトコルで明細を取得し、通常のインポート（重複除去、ルール、レビュー受信箱）を通します。認証情報は暗号化して保存され、取得は 6 時間ごとまたは手動です。',
      ko: 'Lumio는 자체 은행 연동을 두지 않습니다. 본인의 SimpleFIN Bridge 계정(SimpleFIN의 별도 유료 서비스)을 연결하면 Lumio가 개방 프로토콜로 명세를 가져와 일반 가져오기(중복 제거, 규칙, 검토함)를 거칩니다. 자격 증명은 암호화되어 저장되며 6시간마다 또는 요청 시 가져옵니다.',
      hi: 'Lumio का अपना बैंक एकीकरण नहीं है। आप अपना SimpleFIN Bridge खाता जोड़ते हैं (SimpleFIN की अलग, सशुल्क सेवा); Lumio खुले प्रोटोकॉल से स्टेटमेंट लाता है और उन्हें सामान्य इंपोर्ट से गुज़ारता है: डुप्लिकेट हटाना, नियम, समीक्षा इनबॉक्स। एक्सेस एन्क्रिप्टेड रखा जाता है; हर छह घंटे या माँग पर लाया जाता है।',
      nl: 'Lumio heeft geen eigen bankkoppeling. U koppelt uw eigen SimpleFIN Bridge-account (een aparte, betaalde dienst van SimpleFIN); Lumio haalt afschriften op via het open protocol en laat ze door de gewone import lopen: ontdubbelen, regels, de beoordelingsinbox. De toegang wordt versleuteld bewaard; ophalen gebeurt elke zes uur of op verzoek.',
      sv: 'Lumio har ingen egen bankkoppling. Du kopplar ditt eget SimpleFIN Bridge-konto (en separat betaltjänst från SimpleFIN); Lumio hämtar kontoutdrag via det öppna protokollet och kör dem genom den vanliga importen: dubblettkontroll, regler, granskningsinkorgen. Åtkomsten lagras krypterad; hämtning var sjätte timme eller på begäran.',
      vi: 'Lumio không có tích hợp ngân hàng riêng. Bạn kết nối tài khoản SimpleFIN Bridge của mình (dịch vụ trả phí riêng của SimpleFIN); Lumio lấy sao kê qua giao thức mở và đưa qua quy trình nhập thông thường: khử trùng lặp, quy tắc, hộp thư xem xét. Thông tin truy cập được lưu mã hóa; lấy dữ liệu mỗi sáu giờ hoặc theo yêu cầu.',
      id: 'Lumio tidak memiliki integrasi bank sendiri. Anda menghubungkan akun SimpleFIN Bridge Anda (layanan berbayar terpisah dari SimpleFIN); Lumio menarik mutasi lewat protokol terbuka dan memprosesnya melalui impor biasa: deduplikasi, aturan, kotak tinjauan. Kredensial disimpan terenkripsi; penarikan setiap enam jam atau sesuai permintaan.',
      da: 'Lumio har ingen egen bankintegration. Du forbinder din egen SimpleFIN Bridge-konto (en separat, betalt tjeneste fra SimpleFIN); Lumio henter kontoudtog via den åbne protokol og sender dem gennem den almindelige import: dubletkontrol, regler, gennemgangsindbakken. Adgangen gemmes krypteret; der hentes hver sjette time eller efter behov.',
      nb: 'Lumio har ingen egen bankintegrasjon. Du kobler til din egen SimpleFIN Bridge-konto (en separat, betalt tjeneste fra SimpleFIN); Lumio henter kontoutskrifter via den åpne protokollen og sender dem gjennom den vanlige importen: duplikatsjekk, regler, gjennomgangsinnboksen. Tilgangen lagres kryptert; henting skjer hver sjette time eller ved behov.',
      nn: 'Lumio har inga eiga bankintegrasjon. Du koplar til din eigen SimpleFIN Bridge-konto (ei eiga, betalt teneste frå SimpleFIN); Lumio hentar kontoutskrifter via den opne protokollen og sender dei gjennom den vanlege importen: duplikatsjekk, reglar, gjennomgangsinnboksen. Tilgangen blir lagra kryptert; henting skjer kvar sjette time eller ved behov.',
      fi: 'Lumiolla ei ole omaa pankkiyhteyttä. Yhdistät oman SimpleFIN Bridge -tilisi (SimpleFINin erillinen maksullinen palvelu); Lumio hakee tiliotteet avoimella protokollalla ja ajaa ne tavallisen tuonnin läpi: kaksoiskappaleiden poisto, säännöt, tarkistusjono. Tunnistetiedot tallennetaan salattuina; haku tehdään kuuden tunnin välein tai pyynnöstä.',
      is: 'Lumio er ekki með eigin bankatengingu. Þú tengir þinn eigin SimpleFIN Bridge-reikning (sérstök greidd þjónusta frá SimpleFIN); Lumio sækir yfirlit um opna samskiptareglu og keyrir þau í gegnum venjulegan innflutning: tvítekningarleit, reglur, yfirferðarhólfið. Aðgangurinn er geymdur dulkóðaður; sótt er á sex klukkustunda fresti eða eftir þörfum.',
      fo: 'Lumio hevur onga egna bankatenging. Tú tengir tína egnu SimpleFIN Bridge-kontu (ein sær, gjaldandi tænasta frá SimpleFIN); Lumio heintar kontoúrtøk umvegis opnu protokollina og koyrir tey gjøgnum vanliga innflutningin: tvítøkukanning, reglur, gjøgnumgongdarkassan. Atgongdin verður goymd krypterað; heintað verður sjeyndu hvønn tíma ella eftir tørvi.',
      cs: 'Lumio nemá vlastní napojení na banky. Připojíte vlastní účet SimpleFIN Bridge (samostatná placená služba SimpleFIN); Lumio stahuje výpisy otevřeným protokolem a posílá je běžným importem: odstranění duplicit, pravidla, fronta ke kontrole. Přístup je uložen šifrovaně; stahuje se každých šest hodin nebo na požádání.',
      bg: 'Lumio няма собствена банкова интеграция. Свързвате своя акаунт в SimpleFIN Bridge (отделна платена услуга на SimpleFIN); Lumio изтегля извлеченията по отворения протокол и ги прекарва през обичайния импорт: премахване на дубликати, правила, опашката за преглед. Достъпът се съхранява криптиран; изтегляне на всеки шест часа или при поискване.',
      hr: 'Lumio nema vlastitu integraciju s bankama. Povezujete vlastiti SimpleFIN Bridge račun (zasebna plaćena usluga tvrtke SimpleFIN); Lumio preuzima izvode otvorenim protokolom i provodi ih kroz uobičajeni uvoz: uklanjanje duplikata, pravila, red za pregled. Pristup se čuva šifriran; preuzimanje svakih šest sati ili na zahtjev.',
      sr: 'Lumio нема сопствену интеграцију са банкама. Повезујете свој SimpleFIN Bridge налог (засебна плаћена услуга SimpleFIN-а); Lumio преузима изводе отвореним протоколом и проводи их кроз уобичајени увоз: уклањање дупликата, правила, ред за преглед. Приступ се чува шифрован; преузимање на сваких шест сати или на захтев.',
      sl: 'Lumio nima lastne povezave z bankami. Povežete svoj račun SimpleFIN Bridge (ločena plačljiva storitev SimpleFIN); Lumio prenese izpiske prek odprtega protokola in jih pošlje skozi običajni uvoz: odstranjevanje dvojnikov, pravila, čakalna vrsta za pregled. Dostop je shranjen šifrirano; prenos poteka vsakih šest ur ali na zahtevo.',
      mk: 'Lumio нема сопствена банкарска интеграција. Ја поврзувате својата SimpleFIN Bridge сметка (посебна платена услуга на SimpleFIN); Lumio ги презема изводите преку отворениот протокол и ги спроведува низ вообичаениот увоз: отстранување дупликати, правила, редот за преглед. Пристапот се чува шифриран; преземањето е на секои шест часа или на барање.',
      be: 'Lumio не мае ўласнай інтэграцыі з банкамі. Вы падключаеце свой акаўнт SimpleFIN Bridge (асобная платная паслуга SimpleFIN); Lumio забірае выпіскі па адкрытым пратаколе і праводзіць іх праз звычайны імпарт: дэдуплікацыя, правілы, чарга праверкі. Доступ захоўваецца зашыфраваным; выгрузка кожныя шэсць гадзін або па кнопцы.',
      bs: 'Lumio nema vlastitu integraciju s bankama. Povezujete svoj SimpleFIN Bridge račun (zasebna plaćena usluga SimpleFIN-a); Lumio preuzima izvode otvorenim protokolom i provodi ih kroz uobičajeni uvoz: uklanjanje duplikata, pravila, red za pregled. Pristup se čuva šifrovan; preuzimanje svakih šest sati ili na zahtjev.',
      hsb: 'Lumio nima žanu swójsku bankowu integraciju. Zwjazujeće swoje konto SimpleFIN Bridge (separatna płaćena słužba SimpleFIN); Lumio wotwołuje wupisy přez wotewrjeny protokol a wjedźe je přez zwučeny import: wotstronjenje duplikatow, prawidła, rynk za přepruwowanje. Přistup so zaklučowany składuje; wotwołanje kóždych šěsć hodźin abo na žadanje.',
    }),
    connectTitle: t({
      ru: 'Подключить SimpleFIN',
      en: 'Connect SimpleFIN',
      kk: 'SimpleFIN қосу',
      de: 'SimpleFIN verbinden',
      fr: 'Connecter SimpleFIN',
      es: 'Conectar SimpleFIN',
      pt: 'Conectar SimpleFIN',
      tr: "SimpleFIN'i bağla",
      uk: 'Підключити SimpleFIN',
      zh: '连接 SimpleFIN',
      ar: 'ربط SimpleFIN',
      pl: 'Połącz SimpleFIN',
      it: 'Collega SimpleFIN',
      sk: 'Pripojiť SimpleFIN',
      ja: 'SimpleFIN を接続',
      ko: 'SimpleFIN 연결',
      hi: 'SimpleFIN जोड़ें',
      nl: 'SimpleFIN koppelen',
      sv: 'Anslut SimpleFIN',
      vi: 'Kết nối SimpleFIN',
      id: 'Hubungkan SimpleFIN',
      da: 'Forbind SimpleFIN',
      nb: 'Koble til SimpleFIN',
      nn: 'Kople til SimpleFIN',
      fi: 'Yhdistä SimpleFIN',
      is: 'Tengja SimpleFIN',
      fo: 'Tengja SimpleFIN',
      cs: 'Připojit SimpleFIN',
      bg: 'Свързване на SimpleFIN',
      hr: 'Poveži SimpleFIN',
      sr: 'Повежи SimpleFIN',
      sl: 'Poveži SimpleFIN',
      mk: 'Поврзи SimpleFIN',
      be: 'Падключыць SimpleFIN',
      bs: 'Poveži SimpleFIN',
      hsb: 'SimpleFIN zwjazać',
    }),
    tokenHelp: t({
      ru: 'В своём аккаунте SimpleFIN Bridge создайте новое подключение и вставьте сюда setup token. Токен одноразовый: после обмена Lumio хранит только полученный доступ. Аккаунт создаётся на',
      en: 'In your SimpleFIN Bridge account create a new connection and paste the setup token here. A token works once: after the exchange Lumio keeps only the access it received. Get an account at',
      kk: 'SimpleFIN Bridge тіркелгіңізде жаңа қосылым жасап, setup token-ді осында қойыңыз. Токен бір рет қана жұмыс істейді: айырбастан кейін Lumio тек алынған қатынауды сақтайды. Тіркелгі мына жерде жасалады:',
      de: 'Legen Sie in Ihrem SimpleFIN-Bridge-Konto eine neue Verbindung an und fügen Sie das Setup-Token hier ein. Ein Token gilt einmal: nach dem Tausch behält Lumio nur den erhaltenen Zugang. Konto anlegen unter',
      fr: 'Dans votre compte SimpleFIN Bridge, créez une nouvelle connexion et collez ici le jeton de configuration. Un jeton ne sert qu’une fois : après l’échange, Lumio ne garde que l’accès reçu. Créez un compte sur',
      es: 'En tu cuenta de SimpleFIN Bridge crea una conexión nueva y pega aquí el token de configuración. Un token sirve una sola vez: tras el intercambio Lumio guarda solo el acceso recibido. Crea una cuenta en',
      pt: 'Na sua conta SimpleFIN Bridge crie uma nova conexão e cole aqui o token de configuração. Um token vale uma vez: após a troca o Lumio guarda apenas o acesso recebido. Crie uma conta em',
      tr: 'SimpleFIN Bridge hesabınızda yeni bir bağlantı oluşturup kurulum belirtecini buraya yapıştırın. Belirteç bir kez çalışır: değişimden sonra Lumio yalnızca aldığı erişimi saklar. Hesap için:',
      uk: 'У своєму акаунті SimpleFIN Bridge створіть нове підключення і вставте сюди setup token. Токен одноразовий: після обміну Lumio зберігає лише отриманий доступ. Акаунт створюється на',
      zh: '在您的 SimpleFIN Bridge 账户中新建一个连接，并把 setup token 粘贴到这里。令牌只能用一次：交换后 Lumio 只保留获得的访问凭据。注册账户：',
      ar: 'في حساب SimpleFIN Bridge أنشئ اتصالًا جديدًا والصق رمز الإعداد هنا. الرمز يعمل مرة واحدة: بعد التبادل يحتفظ Lumio بالوصول المستلم فقط. أنشئ حسابًا على',
      pl: 'W swoim koncie SimpleFIN Bridge utwórz nowe połączenie i wklej tutaj token konfiguracyjny. Token działa raz: po wymianie Lumio zachowuje tylko otrzymany dostęp. Konto założysz na',
      it: 'Nel tuo account SimpleFIN Bridge crea una nuova connessione e incolla qui il setup token. Un token vale una volta sola: dopo lo scambio Lumio conserva solo l’accesso ricevuto. Crea un account su',
      sk: 'Vo svojom účte SimpleFIN Bridge vytvorte nové pripojenie a vložte sem setup token. Token funguje raz: po výmene si Lumio ponechá len získaný prístup. Účet vytvoríte na',
      ja: 'SimpleFIN Bridge アカウントで新しい接続を作成し、setup token をここに貼り付けてください。トークンは一度だけ有効で、交換後 Lumio は取得したアクセスのみ保持します。アカウント作成：',
      ko: 'SimpleFIN Bridge 계정에서 새 연결을 만들고 setup token을 여기에 붙여넣으세요. 토큰은 한 번만 쓰입니다. 교환 후 Lumio는 받은 액세스만 보관합니다. 계정 만들기:',
      hi: 'अपने SimpleFIN Bridge खाते में नया कनेक्शन बनाएँ और setup token यहाँ पेस्ट करें। टोकन एक बार ही चलता है: बदलने के बाद Lumio सिर्फ़ मिला हुआ एक्सेस रखता है। खाता बनाएँ:',
      nl: 'Maak in uw SimpleFIN Bridge-account een nieuwe verbinding en plak het setup-token hier. Een token werkt één keer: na de uitwisseling bewaart Lumio alleen de ontvangen toegang. Account aanmaken op',
      sv: 'Skapa en ny anslutning i ditt SimpleFIN Bridge-konto och klistra in setup-token här. En token fungerar en gång: efter utbytet behåller Lumio bara den åtkomst som togs emot. Skaffa konto på',
      vi: 'Trong tài khoản SimpleFIN Bridge, tạo kết nối mới và dán setup token vào đây. Mã chỉ dùng một lần: sau khi trao đổi, Lumio chỉ giữ quyền truy cập nhận được. Tạo tài khoản tại',
      id: 'Di akun SimpleFIN Bridge Anda buat koneksi baru dan tempel setup token di sini. Token hanya berlaku sekali: setelah ditukar, Lumio hanya menyimpan akses yang diterima. Buat akun di',
      da: 'Opret en ny forbindelse i din SimpleFIN Bridge-konto, og indsæt opsætningstokenet her. Et token virker én gang: efter udvekslingen beholder Lumio kun den adgang, det fik. Opret en konto på',
      nb: 'Opprett en ny tilkobling i SimpleFIN Bridge-kontoen din, og lim inn oppsettstokenet her. Et token virker én gang: etter utvekslingen beholder Lumio bare tilgangen det fikk. Opprett en konto på',
      nn: 'Opprett ei ny tilkopling i SimpleFIN Bridge-kontoen din, og lim inn oppsettstokenet her. Eit token verkar éin gong: etter utvekslinga held Lumio berre på tilgangen det fekk. Opprett ein konto på',
      fi: 'Luo SimpleFIN Bridge -tililläsi uusi yhteys ja liitä asetustunnus tähän. Tunnus toimii kerran: vaihdon jälkeen Lumio säilyttää vain saamansa käyttöoikeuden. Luo tili osoitteessa',
      is: 'Búðu til nýja tengingu í SimpleFIN Bridge-reikningnum þínum og límdu uppsetningartókann hér. Tóki virkar einu sinni: eftir skiptin heldur Lumio aðeins aðganginum sem það fékk. Stofnaðu reikning á',
      fo: 'Stovna eitt nýtt samband í tínari SimpleFIN Bridge-kontu og set uppsetingartekin inn her. Ein tekin virkar eina ferð: eftir umbýtið varðveitir Lumio bara atgongdina, tað fekk. Stovna kontu á',
      cs: 'Ve svém účtu SimpleFIN Bridge vytvořte nové připojení a vložte sem instalační token. Token funguje jednou: po výměně si Lumio ponechá jen získaný přístup. Účet založíte na',
      bg: 'Във вашия акаунт в SimpleFIN Bridge създайте нова връзка и поставете тук токена за настройка. Токенът работи веднъж: след обмена Lumio пази само получения достъп. Създайте акаунт на',
      hr: 'U svom SimpleFIN Bridge računu stvorite novu vezu i ovdje zalijepite token za postavljanje. Token vrijedi jednom: nakon razmjene Lumio zadržava samo dobiveni pristup. Otvorite račun na',
      sr: 'У свом SimpleFIN Bridge налогу направите нову везу и овде налепите токен за подешавање. Токен важи једном: после размене Lumio задржава само добијени приступ. Отворите налог на',
      sl: 'V svojem računu SimpleFIN Bridge ustvarite novo povezavo in sem prilepite žeton za nastavitev. Žeton deluje enkrat: po izmenjavi Lumio obdrži le pridobljeni dostop. Račun ustvarite na',
      mk: 'Во вашата SimpleFIN Bridge сметка создајте нова врска и тука залепете го токенот за поставување. Токенот важи еднаш: по размената Lumio го задржува само добиениот пристап. Отворете сметка на',
      be: 'У сваім акаўнце SimpleFIN Bridge стварыце новае падключэнне і ўстаўце сюды токен наладкі. Токен дзейнічае адзін раз: пасля абмену Lumio захоўвае толькі атрыманы доступ. Завесці акаўнт можна на',
      bs: 'U svom SimpleFIN Bridge računu napravite novu vezu i ovdje zalijepite token za postavljanje. Token važi jednom: nakon razmjene Lumio zadržava samo dobijeni pristup. Otvorite račun na',
      hsb: 'W swojim konće SimpleFIN Bridge wutworće nowy zwisk a zasadźće tu token za konfiguraciju. Token płaći jónu: po wuměnje wobchowa Lumio jenož dóstaty přistup. Konto załožiće na',
    }),
    setupToken: t({
      ru: 'Setup token',
      en: 'Setup token',
      kk: 'Setup token',
      de: 'Setup-Token',
      fr: 'Jeton de configuration',
      es: 'Token de configuración',
      pt: 'Token de configuração',
      tr: 'Kurulum belirteci',
      uk: 'Setup token',
      zh: 'Setup token',
      ar: 'رمز الإعداد',
      pl: 'Token konfiguracyjny',
      it: 'Setup token',
      sk: 'Setup token',
      ja: 'Setup token',
      ko: 'Setup token',
      hi: 'Setup token',
      nl: 'Setup-token',
      sv: 'Setup-token',
      vi: 'Setup token',
      id: 'Setup token',
      da: 'Opsætningstoken',
      nb: 'Oppsettstoken',
      nn: 'Oppsettstoken',
      fi: 'Asetustunnus',
      is: 'Uppsetningartóki',
      fo: 'Uppsetingartekin',
      cs: 'Instalační token',
      bg: 'Токен за настройка',
      hr: 'Token za postavljanje',
      sr: 'Токен за подешавање',
      sl: 'Žeton za nastavitev',
      mk: 'Токен за поставување',
      be: 'Токен наладкі',
      bs: 'Token za postavljanje',
      hsb: 'Token za konfiguraciju',
    }),
    setupTokenPlaceholder: t({
      ru: 'Вставьте токен из SimpleFIN Bridge',
      en: 'Paste the token from SimpleFIN Bridge',
      kk: 'SimpleFIN Bridge токенін қойыңыз',
      de: 'Token aus SimpleFIN Bridge einfügen',
      fr: 'Collez le jeton de SimpleFIN Bridge',
      es: 'Pega el token de SimpleFIN Bridge',
      pt: 'Cole o token do SimpleFIN Bridge',
      tr: "SimpleFIN Bridge'den belirteci yapıştırın",
      uk: 'Вставте токен із SimpleFIN Bridge',
      zh: '粘贴来自 SimpleFIN Bridge 的令牌',
      ar: 'الصق الرمز من SimpleFIN Bridge',
      pl: 'Wklej token z SimpleFIN Bridge',
      it: 'Incolla il token da SimpleFIN Bridge',
      sk: 'Vložte token zo SimpleFIN Bridge',
      ja: 'SimpleFIN Bridge のトークンを貼り付け',
      ko: 'SimpleFIN Bridge의 토큰 붙여넣기',
      hi: 'SimpleFIN Bridge का टोकन पेस्ट करें',
      nl: 'Plak het token van SimpleFIN Bridge',
      sv: 'Klistra in token från SimpleFIN Bridge',
      vi: 'Dán mã từ SimpleFIN Bridge',
      id: 'Tempel token dari SimpleFIN Bridge',
      da: 'Indsæt tokenet fra SimpleFIN Bridge',
      nb: 'Lim inn tokenet fra SimpleFIN Bridge',
      nn: 'Lim inn tokenet frå SimpleFIN Bridge',
      fi: 'Liitä tunnus SimpleFIN Bridgestä',
      is: 'Límdu tókann úr SimpleFIN Bridge',
      fo: 'Set tekin úr SimpleFIN Bridge inn',
      cs: 'Vložte token ze SimpleFIN Bridge',
      bg: 'Поставете токена от SimpleFIN Bridge',
      hr: 'Zalijepite token iz SimpleFIN Bridgea',
      sr: 'Налепите токен из SimpleFIN Bridge-а',
      sl: 'Prilepite žeton iz SimpleFIN Bridge',
      mk: 'Залепете го токенот од SimpleFIN Bridge',
      be: 'Устаўце токен з SimpleFIN Bridge',
      bs: 'Zalijepite token iz SimpleFIN Bridgea',
      hsb: 'Zasadźće token ze SimpleFIN Bridge',
    }),
    connect: t({
      ru: 'Подключить',
      en: 'Connect',
      kk: 'Қосу',
      de: 'Verbinden',
      fr: 'Connecter',
      es: 'Conectar',
      pt: 'Conectar',
      tr: 'Bağlan',
      uk: 'Підключити',
      zh: '连接',
      ar: 'ربط',
      pl: 'Połącz',
      it: 'Collega',
      sk: 'Pripojiť',
      ja: '接続',
      ko: '연결',
      hi: 'जोड़ें',
      nl: 'Koppelen',
      sv: 'Anslut',
      vi: 'Kết nối',
      id: 'Hubungkan',
      da: 'Forbind',
      nb: 'Koble til',
      nn: 'Kople til',
      fi: 'Yhdistä',
      is: 'Tengja',
      fo: 'Tengja',
      cs: 'Připojit',
      bg: 'Свържи',
      hr: 'Poveži',
      sr: 'Повежи',
      sl: 'Poveži',
      mk: 'Поврзи',
      be: 'Падключыць',
      bs: 'Poveži',
      hsb: 'Zwjazać',
    }),
    connecting: t({
      ru: 'Подключение…',
      en: 'Connecting…',
      kk: 'Қосылуда…',
      de: 'Verbinden…',
      fr: 'Connexion…',
      es: 'Conectando…',
      pt: 'Conectando…',
      tr: 'Bağlanıyor…',
      uk: 'Підключення…',
      zh: '连接中…',
      ar: 'جارٍ الربط…',
      pl: 'Łączenie…',
      it: 'Collegamento…',
      sk: 'Pripája sa…',
      ja: '接続中…',
      ko: '연결 중…',
      hi: 'जोड़ रहे हैं…',
      nl: 'Koppelen…',
      sv: 'Ansluter…',
      vi: 'Đang kết nối…',
      id: 'Menghubungkan…',
      da: 'Forbinder…',
      nb: 'Kobler til…',
      nn: 'Koplar til…',
      fi: 'Yhdistetään…',
      is: 'Tengir…',
      fo: 'Tengir…',
      cs: 'Připojování…',
      bg: 'Свързване…',
      hr: 'Povezivanje…',
      sr: 'Повезивање…',
      sl: 'Povezovanje…',
      mk: 'Поврзување…',
      be: 'Падключэнне…',
      bs: 'Povezivanje…',
      hsb: 'Zwjazuje so…',
    }),
    accounts: t({
      ru: 'Счета',
      en: 'Accounts',
      kk: 'Шоттар',
      de: 'Konten',
      fr: 'Comptes',
      es: 'Cuentas',
      pt: 'Contas',
      tr: 'Hesaplar',
      uk: 'Рахунки',
      zh: '账户',
      ar: 'الحسابات',
      pl: 'Konta',
      it: 'Conti',
      sk: 'Účty',
      ja: '口座',
      ko: '계좌',
      hi: 'खाते',
      nl: 'Rekeningen',
      sv: 'Konton',
      vi: 'Tài khoản',
      id: 'Rekening',
      da: 'Konti',
      nb: 'Kontoer',
      nn: 'Kontoar',
      fi: 'Tilit',
      is: 'Reikningar',
      fo: 'Kontur',
      cs: 'Účty',
      bg: 'Сметки',
      hr: 'Računi',
      sr: 'Рачуни',
      sl: 'Računi',
      mk: 'Сметки',
      be: 'Рахункі',
      bs: 'Računi',
      hsb: 'Konta',
    }),
    noAccounts: t({
      ru: 'Провайдер не вернул ни одного счёта. Добавьте банк в SimpleFIN Bridge и обновите список.',
      en: 'The provider returned no accounts. Add a bank in SimpleFIN Bridge and refresh the list.',
      kk: 'Провайдер бірде-бір шот қайтармады. SimpleFIN Bridge-ке банк қосып, тізімді жаңартыңыз.',
      de: 'Der Anbieter hat keine Konten geliefert. Fügen Sie in SimpleFIN Bridge eine Bank hinzu und aktualisieren Sie die Liste.',
      fr: "Le fournisseur n'a renvoyé aucun compte. Ajoutez une banque dans SimpleFIN Bridge et actualisez la liste.",
      es: 'El proveedor no devolvió cuentas. Añade un banco en SimpleFIN Bridge y actualiza la lista.',
      pt: 'O provedor não retornou contas. Adicione um banco no SimpleFIN Bridge e atualize a lista.',
      tr: 'Sağlayıcı hiç hesap döndürmedi. SimpleFIN Bridge’e bir banka ekleyip listeyi yenileyin.',
      uk: 'Провайдер не повернув жодного рахунку. Додайте банк у SimpleFIN Bridge і оновіть список.',
      zh: '提供方未返回任何账户。请在 SimpleFIN Bridge 中添加银行并刷新列表。',
      ar: 'لم يُرجع المزود أي حسابات. أضف بنكًا في SimpleFIN Bridge وحدّث القائمة.',
      pl: 'Dostawca nie zwrócił żadnych kont. Dodaj bank w SimpleFIN Bridge i odśwież listę.',
      it: 'Il provider non ha restituito conti. Aggiungi una banca in SimpleFIN Bridge e aggiorna l’elenco.',
      sk: 'Poskytovateľ nevrátil žiadne účty. Pridajte banku v SimpleFIN Bridge a obnovte zoznam.',
      ja: 'プロバイダーから口座が返されませんでした。SimpleFIN Bridge で銀行を追加し、一覧を更新してください。',
      ko: '제공자가 계좌를 반환하지 않았습니다. SimpleFIN Bridge에서 은행을 추가하고 목록을 새로 고치세요.',
      hi: 'प्रदाता ने कोई खाता नहीं लौटाया। SimpleFIN Bridge में बैंक जोड़ें और सूची रीफ़्रेश करें।',
      nl: 'De aanbieder gaf geen rekeningen terug. Voeg een bank toe in SimpleFIN Bridge en vernieuw de lijst.',
      sv: 'Leverantören returnerade inga konton. Lägg till en bank i SimpleFIN Bridge och uppdatera listan.',
      vi: 'Nhà cung cấp không trả về tài khoản nào. Hãy thêm ngân hàng trong SimpleFIN Bridge và làm mới danh sách.',
      id: 'Penyedia tidak mengembalikan rekening. Tambahkan bank di SimpleFIN Bridge lalu segarkan daftar.',
      da: 'Udbyderen returnerede ingen konti. Tilføj en bank i SimpleFIN Bridge, og opdater listen.',
      nb: 'Leverandøren returnerte ingen kontoer. Legg til en bank i SimpleFIN Bridge og oppdater listen.',
      nn: 'Leverandøren returnerte ingen kontoar. Legg til ein bank i SimpleFIN Bridge og oppdater lista.',
      fi: 'Palveluntarjoaja ei palauttanut tilejä. Lisää pankki SimpleFIN Bridgessä ja päivitä luettelo.',
      is: 'Þjónustuveitan skilaði engum reikningum. Bættu við banka í SimpleFIN Bridge og endurnýjaðu listann.',
      fo: 'Veitarin sendi ongar kontur. Legg ein banka afturat í SimpleFIN Bridge og dagfør listan.',
      cs: 'Poskytovatel nevrátil žádné účty. Přidejte banku v SimpleFIN Bridge a obnovte seznam.',
      bg: 'Доставчикът не върна сметки. Добавете банка в SimpleFIN Bridge и опреснете списъка.',
      hr: 'Pružatelj nije vratio nijedan račun. Dodajte banku u SimpleFIN Bridgeu i osvježite popis.',
      sr: 'Провајдер није вратио ниједан рачун. Додајте банку у SimpleFIN Bridge-у и освежите листу.',
      sl: 'Ponudnik ni vrnil nobenega računa. Dodajte banko v SimpleFIN Bridge in osvežite seznam.',
      mk: 'Давателот не врати ниедна сметка. Додајте банка во SimpleFIN Bridge и освежете ја листата.',
      be: 'Пастаўшчык не вярнуў рахункаў. Дадайце банк у SimpleFIN Bridge і абнавіце спіс.',
      bs: 'Pružalac nije vratio nijedan račun. Dodajte banku u SimpleFIN Bridgeu i osvježite listu.',
      hsb: 'Poskićowar njeje žane konta wróćił. Přidajće banku w SimpleFIN Bridge a aktualizujće lisćinu.',
    }),
    pull: t({
      ru: 'Забирать',
      en: 'Pull',
      kk: 'Алу',
      de: 'Abrufen',
      fr: 'Récupérer',
      es: 'Descargar',
      pt: 'Puxar',
      tr: 'Çek',
      uk: 'Забирати',
      zh: '拉取',
      ar: 'سحب',
      pl: 'Pobieraj',
      it: 'Scarica',
      sk: 'Sťahovať',
      ja: '取得',
      ko: '가져오기',
      hi: 'लाएँ',
      nl: 'Ophalen',
      sv: 'Hämta',
      vi: 'Lấy',
      id: 'Tarik',
      da: 'Hent',
      nb: 'Hent',
      nn: 'Hent',
      fi: 'Hae',
      is: 'Sækja',
      fo: 'Heinta',
      cs: 'Stahovat',
      bg: 'Изтегляне',
      hr: 'Preuzmi',
      sr: 'Преузми',
      sl: 'Prenesi',
      mk: 'Преземи',
      be: 'Выгружаць',
      bs: 'Preuzmi',
      hsb: 'Wotwołać',
    }),
    wallet: t({
      ru: 'Кошелёк в Lumio',
      en: 'Wallet in Lumio',
      kk: 'Lumio-дағы әмиян',
      de: 'Wallet in Lumio',
      fr: 'Portefeuille dans Lumio',
      es: 'Cartera en Lumio',
      pt: 'Carteira no Lumio',
      tr: "Lumio'daki cüzdan",
      uk: 'Гаманець у Lumio',
      zh: 'Lumio 中的钱包',
      ar: 'المحفظة في Lumio',
      pl: 'Portfel w Lumio',
      it: 'Portafoglio in Lumio',
      sk: 'Peňaženka v Lumio',
      ja: 'Lumio のウォレット',
      ko: 'Lumio 지갑',
      hi: 'Lumio में वॉलेट',
      nl: 'Portemonnee in Lumio',
      sv: 'Plånbok i Lumio',
      vi: 'Ví trong Lumio',
      id: 'Dompet di Lumio',
      da: 'Wallet i Lumio',
      nb: 'Lommebok i Lumio',
      nn: 'Lommebok i Lumio',
      fi: 'Lompakko Lumiossa',
      is: 'Veski í Lumio',
      fo: 'Pungur í Lumio',
      cs: 'Peněženka v Lumio',
      bg: 'Портфейл в Lumio',
      hr: 'Novčanik u Lumiju',
      sr: 'Новчаник у Lumio',
      sl: 'Denarnica v Lumio',
      mk: 'Паричник во Lumio',
      be: 'Гаманец у Lumio',
      bs: 'Novčanik u Lumiju',
      hsb: 'Móšnja w Lumio',
    }),
    noWallet: t({
      ru: 'Не привязывать',
      en: 'Not linked',
      kk: 'Байланыстырмау',
      de: 'Nicht verknüpft',
      fr: 'Non lié',
      es: 'Sin vincular',
      pt: 'Sem vínculo',
      tr: 'Bağlı değil',
      uk: "Не прив'язувати",
      zh: '不关联',
      ar: 'غير مرتبط',
      pl: 'Niepowiązany',
      it: 'Non collegato',
      sk: 'Neprepojené',
      ja: '関連付けない',
      ko: '연결 안 함',
      hi: 'लिंक नहीं',
      nl: 'Niet gekoppeld',
      sv: 'Inte kopplad',
      vi: 'Không liên kết',
      id: 'Tidak ditautkan',
      da: 'Ikke tilknyttet',
      nb: 'Ikke koblet',
      nn: 'Ikkje kopla',
      fi: 'Ei linkitetty',
      is: 'Ekki tengt',
      fo: 'Ikki knýtt',
      cs: 'Nepropojeno',
      bg: 'Не е свързан',
      hr: 'Nije povezano',
      sr: 'Није повезано',
      sl: 'Ni povezano',
      mk: 'Не е поврзано',
      be: 'Не прывязаны',
      bs: 'Nije povezano',
      hsb: 'Njepřiwjazany',
    }),
    balance: t({
      ru: 'Баланс',
      en: 'Balance',
      kk: 'Баланс',
      de: 'Saldo',
      fr: 'Solde',
      es: 'Saldo',
      pt: 'Saldo',
      tr: 'Bakiye',
      uk: 'Баланс',
      zh: '余额',
      ar: 'الرصيد',
      pl: 'Saldo',
      it: 'Saldo',
      sk: 'Zostatok',
      ja: '残高',
      ko: '잔액',
      hi: 'शेष',
      nl: 'Saldo',
      sv: 'Saldo',
      vi: 'Số dư',
      id: 'Saldo',
      da: 'Saldo',
      nb: 'Saldo',
      nn: 'Saldo',
      fi: 'Saldo',
      is: 'Staða',
      fo: 'Støða',
      cs: 'Zůstatek',
      bg: 'Салдо',
      hr: 'Stanje',
      sr: 'Стање',
      sl: 'Stanje',
      mk: 'Салдо',
      be: 'Баланс',
      bs: 'Stanje',
      hsb: 'Staw',
    }),
    lastSync: t({
      ru: 'Последняя выгрузка',
      en: 'Last pull',
      kk: 'Соңғы жүктеу',
      de: 'Letzter Abruf',
      fr: 'Dernière récupération',
      es: 'Última descarga',
      pt: 'Última busca',
      tr: 'Son çekim',
      uk: 'Останнє вивантаження',
      zh: '上次拉取',
      ar: 'آخر سحب',
      pl: 'Ostatnie pobranie',
      it: 'Ultimo scaricamento',
      sk: 'Posledné stiahnutie',
      ja: '最終取得',
      ko: '마지막 가져오기',
      hi: 'अंतिम लाना',
      nl: 'Laatst opgehaald',
      sv: 'Senaste hämtning',
      vi: 'Lần lấy gần nhất',
      id: 'Penarikan terakhir',
      da: 'Seneste hentning',
      nb: 'Siste henting',
      nn: 'Siste henting',
      fi: 'Viimeisin haku',
      is: 'Síðast sótt',
      fo: 'Seinast heintað',
      cs: 'Poslední stažení',
      bg: 'Последно изтегляне',
      hr: 'Zadnje preuzimanje',
      sr: 'Последње преузимање',
      sl: 'Zadnji prenos',
      mk: 'Последно преземање',
      be: 'Апошняя выгрузка',
      bs: 'Zadnje preuzimanje',
      hsb: 'Poslednje wotwołanje',
    }),
    never: t({
      ru: 'ещё не было',
      en: 'never',
      kk: 'әлі жоқ',
      de: 'noch nie',
      fr: 'jamais',
      es: 'nunca',
      pt: 'nunca',
      tr: 'hiç',
      uk: 'ще не було',
      zh: '从未',
      ar: 'لم يحدث',
      pl: 'nigdy',
      it: 'mai',
      sk: 'nikdy',
      ja: 'なし',
      ko: '없음',
      hi: 'कभी नहीं',
      nl: 'nooit',
      sv: 'aldrig',
      vi: 'chưa',
      id: 'belum pernah',
      da: 'aldrig',
      nb: 'aldri',
      nn: 'aldri',
      fi: 'ei koskaan',
      is: 'aldrei',
      fo: 'ongantíð',
      cs: 'nikdy',
      bg: 'никога',
      hr: 'nikad',
      sr: 'никад',
      sl: 'nikoli',
      mk: 'никогаш',
      be: 'ніколі',
      bs: 'nikad',
      hsb: 'ženje',
    }),
    newAccountsOff: t({
      ru: 'Счета, найденные после подключения, добавляются выключенными. Первая выгрузка берёт 90 дней, дальнейшие — с запасом в неделю; строки с известным идентификатором не импортируются повторно.',
      en: 'Accounts found after connecting start switched off. The first pull takes 90 days, later ones overlap the previous by a week; rows whose id is already known are not imported again.',
      kk: 'Қосылғаннан кейін табылған шоттар өшірілген күйде қосылады. Алғашқы жүктеу 90 күнді алады, кейінгілері алдыңғысымен бір аптаға қабаттасады; идентификаторы белгілі жолдар қайта импортталмайды.',
      de: 'Nach dem Verbinden gefundene Konten starten ausgeschaltet. Der erste Abruf umfasst 90 Tage, spätere überlappen den vorigen um eine Woche; Zeilen mit bekannter ID werden nicht erneut importiert.',
      fr: 'Les comptes découverts après la connexion démarrent désactivés. La première récupération couvre 90 jours, les suivantes chevauchent la précédente d’une semaine ; les lignes dont l’identifiant est déjà connu ne sont pas réimportées.',
      es: 'Las cuentas encontradas después de conectar empiezan desactivadas. La primera descarga abarca 90 días; las siguientes se solapan una semana con la anterior; las filas con id ya conocido no se importan de nuevo.',
      pt: 'Contas encontradas depois da conexão começam desligadas. A primeira busca cobre 90 dias; as seguintes sobrepõem a anterior em uma semana; linhas com id já conhecido não são importadas de novo.',
      tr: 'Bağlandıktan sonra bulunan hesaplar kapalı başlar. İlk çekim 90 günü kapsar, sonrakiler öncekiyle bir hafta örtüşür; kimliği bilinen satırlar yeniden içe aktarılmaz.',
      uk: 'Рахунки, знайдені після підключення, додаються вимкненими. Перше вивантаження бере 90 днів, наступні перекривають попереднє на тиждень; рядки з відомим ідентифікатором не імпортуються повторно.',
      zh: '连接后新发现的账户默认关闭。首次拉取覆盖 90 天，之后每次与上次重叠一周；已知 id 的记录不会重复导入。',
      ar: 'الحسابات المكتشفة بعد الربط تبدأ متوقفة. يغطي السحب الأول 90 يومًا، وتتداخل السحوبات التالية مع السابقة بأسبوع؛ لا تُستورد الصفوف ذات المعرّف المعروف مجددًا.',
      pl: 'Konta znalezione po połączeniu zaczynają wyłączone. Pierwsze pobranie obejmuje 90 dni, kolejne nakładają się na poprzednie o tydzień; wiersze o znanym id nie są importowane ponownie.',
      it: 'I conti trovati dopo il collegamento partono disattivati. Il primo scaricamento copre 90 giorni, i successivi si sovrappongono al precedente di una settimana; le righe con id già noto non vengono reimportate.',
      sk: 'Účty nájdené po pripojení začínajú vypnuté. Prvé stiahnutie pokryje 90 dní, ďalšie sa s predošlým prekrývajú o týždeň; riadky so známym id sa znovu neimportujú.',
      ja: '接続後に見つかった口座はオフで始まります。初回取得は 90 日分、以降は前回と 1 週間重ねて取得します。既知の ID を持つ行は再インポートされません。',
      ko: '연결 후 발견된 계좌는 꺼진 상태로 시작합니다. 첫 가져오기는 90일, 이후는 이전과 일주일 겹쳐 가져옵니다. 이미 아는 id의 행은 다시 가져오지 않습니다.',
      hi: 'कनेक्ट करने के बाद मिले खाते बंद शुरू होते हैं। पहली बार 90 दिन लिए जाते हैं, बाद में पिछले से एक हफ़्ता ओवरलैप; जिन पंक्तियों का id पहले से ज्ञात है वे दोबारा इंपोर्ट नहीं होतीं।',
      nl: 'Rekeningen die na het koppelen worden gevonden, beginnen uitgeschakeld. De eerste ophaalronde beslaat 90 dagen, latere overlappen de vorige met een week; rijen met een bekend id worden niet opnieuw geïmporteerd.',
      sv: 'Konton som hittas efter anslutningen börjar avstängda. Första hämtningen tar 90 dagar, senare överlappar den förra med en vecka; rader med känt id importeras inte igen.',
      vi: 'Tài khoản phát hiện sau khi kết nối sẽ tắt sẵn. Lần lấy đầu tiên lấy 90 ngày, các lần sau trùng với lần trước một tuần; dòng có id đã biết không được nhập lại.',
      id: 'Rekening yang ditemukan setelah terhubung dimulai dalam keadaan mati. Penarikan pertama mengambil 90 hari, berikutnya tumpang tindih seminggu dengan sebelumnya; baris dengan id yang sudah dikenal tidak diimpor ulang.',
      da: 'Konti, der findes efter forbindelsen, starter slået fra. Første hentning dækker 90 dage, senere overlapper den forrige med en uge; rækker med et kendt id importeres ikke igen.',
      nb: 'Kontoer som blir funnet etter tilkoblingen, starter avslått. Første henting dekker 90 dager, senere overlapper den forrige med en uke; rader med kjent id importeres ikke på nytt.',
      nn: 'Kontoar som blir funne etter tilkoplinga, startar avslått. Første henting dekkjer 90 dagar, seinare overlappar den førre med ei veke; rader med kjend id blir ikkje importerte på nytt.',
      fi: 'Yhdistämisen jälkeen löydetyt tilit ovat aluksi pois päältä. Ensimmäinen haku kattaa 90 päivää, myöhemmät menevät edellisen päälle viikon verran; rivejä, joiden tunniste on jo tiedossa, ei tuoda uudelleen.',
      is: 'Reikningar sem finnast eftir tengingu byrja óvirkir. Fyrsta sókn nær yfir 90 daga, síðari skarast við þá fyrri um viku; línur með þekkt auðkenni eru ekki fluttar inn aftur.',
      fo: 'Kontur, ið verða funnar eftir sambandið, byrja sløktar. Fyrsta heinting fevnir um 90 dagar, seinni heintingar skarast við ta undanfarnu við eini viku; røðir við kendum id verða ikki innfluttar aftur.',
      cs: 'Účty nalezené po připojení začínají vypnuté. První stažení pokrývá 90 dní, další se s předchozím překrývají o týden; řádky se známým id se znovu neimportují.',
      bg: 'Сметките, открити след свързването, започват изключени. Първото изтегляне обхваща 90 дни, следващите се застъпват с предишното с една седмица; редове с вече известен id не се импортират отново.',
      hr: 'Računi pronađeni nakon povezivanja počinju isključeni. Prvo preuzimanje obuhvaća 90 dana, kasnija se preklapaju s prethodnim za tjedan dana; retci s poznatim id-om ne uvoze se ponovno.',
      sr: 'Рачуни пронађени после повезивања почињу искључени. Прво преузимање обухвата 90 дана, каснија се преклапају са претходним за недељу дана; редови са познатим id-ем се не увозе поново.',
      sl: 'Računi, najdeni po povezavi, so na začetku izklopljeni. Prvi prenos zajame 90 dni, poznejši se s prejšnjim prekrivajo za teden; vrstice z znanim id-jem se ne uvozijo znova.',
      mk: 'Сметките пронајдени по поврзувањето почнуваат исклучени. Првото преземање опфаќа 90 дена, подоцнежните се преклопуваат со претходното за една недела; редовите со познат id не се увезуваат повторно.',
      be: 'Рахункі, знойдзеныя пасля падключэння, пачынаюць выключанымі. Першая выгрузка ахоплівае 90 дзён, наступныя перакрываюць папярэднюю на тыдзень; радкі з ужо вядомым id паўторна не імпартуюцца.',
      bs: 'Računi pronađeni nakon povezivanja počinju isključeni. Prvo preuzimanje obuhvata 90 dana, kasnija se preklapaju s prethodnim za sedmicu; redovi s poznatim id-om ne uvoze se ponovo.',
      hsb: 'Konta namakane po zwjazanju započinaja wupinjene. Prěnje wotwołanje wopřija 90 dnjow, pozdźiše so z předchadnym wo tydźeń překrywaja; linki ze znatym id so znowa njeimportuja.',
    }),
    autoSync: t({
      ru: 'Забирать автоматически каждые 6 часов',
      en: 'Pull automatically every 6 hours',
      kk: 'Әр 6 сағат сайын автоматты түрде алу',
      de: 'Alle 6 Stunden automatisch abrufen',
      fr: 'Récupérer automatiquement toutes les 6 heures',
      es: 'Descargar automáticamente cada 6 horas',
      pt: 'Buscar automaticamente a cada 6 horas',
      tr: 'Her 6 saatte bir otomatik çek',
      uk: 'Забирати автоматично кожні 6 годин',
      zh: '每 6 小时自动拉取',
      ar: 'سحب تلقائي كل 6 ساعات',
      pl: 'Pobieraj automatycznie co 6 godzin',
      it: 'Scarica automaticamente ogni 6 ore',
      sk: 'Sťahovať automaticky každých 6 hodín',
      ja: '6 時間ごとに自動取得',
      ko: '6시간마다 자동 가져오기',
      hi: 'हर 6 घंटे में अपने आप लाएँ',
      nl: 'Elke 6 uur automatisch ophalen',
      sv: 'Hämta automatiskt var sjätte timme',
      vi: 'Tự động lấy mỗi 6 giờ',
      id: 'Tarik otomatis setiap 6 jam',
      da: 'Hent automatisk hver 6. time',
      nb: 'Hent automatisk hver 6. time',
      nn: 'Hent automatisk kvar 6. time',
      fi: 'Hae automaattisesti 6 tunnin välein',
      is: 'Sækja sjálfkrafa á 6 klst. fresti',
      fo: 'Heinta sjálvvirkandi 6. hvønn tíma',
      cs: 'Stahovat automaticky každých 6 hodin',
      bg: 'Автоматично изтегляне на всеки 6 часа',
      hr: 'Automatski preuzimaj svakih 6 sati',
      sr: 'Аутоматски преузимај на сваких 6 сати',
      sl: 'Samodejno prenašaj vsakih 6 ur',
      mk: 'Автоматски преземај на секои 6 часа',
      be: 'Аўтаматычна выгружаць кожныя 6 гадзін',
      bs: 'Automatski preuzimaj svakih 6 sati',
      hsb: 'Awtomatisce kóžde 6 hodźin wotwołać',
    }),
    saveSettings: t({
      ru: 'Сохранить настройки',
      en: 'Save settings',
      kk: 'Параметрлерді сақтау',
      de: 'Einstellungen speichern',
      fr: 'Enregistrer les réglages',
      es: 'Guardar ajustes',
      pt: 'Salvar configurações',
      tr: 'Ayarları kaydet',
      uk: 'Зберегти налаштування',
      zh: '保存设置',
      ar: 'حفظ الإعدادات',
      pl: 'Zapisz ustawienia',
      it: 'Salva impostazioni',
      sk: 'Uložiť nastavenia',
      ja: '設定を保存',
      ko: '설정 저장',
      hi: 'सेटिंग सहेजें',
      nl: 'Instellingen opslaan',
      sv: 'Spara inställningar',
      vi: 'Lưu cài đặt',
      id: 'Simpan pengaturan',
      da: 'Gem indstillinger',
      nb: 'Lagre innstillinger',
      nn: 'Lagre innstillingar',
      fi: 'Tallenna asetukset',
      is: 'Vista stillingar',
      fo: 'Goym stillingar',
      cs: 'Uložit nastavení',
      bg: 'Запазване на настройките',
      hr: 'Spremi postavke',
      sr: 'Сачувај подешавања',
      sl: 'Shrani nastavitve',
      mk: 'Зачувај поставки',
      be: 'Захаваць налады',
      bs: 'Sačuvaj postavke',
      hsb: 'Nastajenja składować',
    }),
    saving: t({
      ru: 'Сохранение…',
      en: 'Saving…',
      kk: 'Сақталуда…',
      de: 'Speichern…',
      fr: 'Enregistrement…',
      es: 'Guardando…',
      pt: 'Salvando…',
      tr: 'Kaydediliyor…',
      uk: 'Збереження…',
      zh: '保存中…',
      ar: 'جارٍ الحفظ…',
      pl: 'Zapisywanie…',
      it: 'Salvataggio…',
      sk: 'Ukladá sa…',
      ja: '保存中…',
      ko: '저장 중…',
      hi: 'सहेज रहे हैं…',
      nl: 'Opslaan…',
      sv: 'Sparar…',
      vi: 'Đang lưu…',
      id: 'Menyimpan…',
      da: 'Gemmer…',
      nb: 'Lagrer…',
      nn: 'Lagrar…',
      fi: 'Tallennetaan…',
      is: 'Vistar…',
      fo: 'Goymir…',
      cs: 'Ukládání…',
      bg: 'Запазване…',
      hr: 'Spremanje…',
      sr: 'Чување…',
      sl: 'Shranjevanje…',
      mk: 'Зачувување…',
      be: 'Захаванне…',
      bs: 'Spašavanje…',
      hsb: 'Składuje so…',
    }),
    syncNow: t({
      ru: 'Забрать сейчас',
      en: 'Pull now',
      kk: 'Қазір алу',
      de: 'Jetzt abrufen',
      fr: 'Récupérer maintenant',
      es: 'Descargar ahora',
      pt: 'Buscar agora',
      tr: 'Şimdi çek',
      uk: 'Забрати зараз',
      zh: '立即拉取',
      ar: 'اسحب الآن',
      pl: 'Pobierz teraz',
      it: 'Scarica ora',
      sk: 'Stiahnuť teraz',
      ja: '今すぐ取得',
      ko: '지금 가져오기',
      hi: 'अभी लाएँ',
      nl: 'Nu ophalen',
      sv: 'Hämta nu',
      vi: 'Lấy ngay',
      id: 'Tarik sekarang',
      da: 'Hent nu',
      nb: 'Hent nå',
      nn: 'Hent no',
      fi: 'Hae nyt',
      is: 'Sækja núna',
      fo: 'Heinta nú',
      cs: 'Stáhnout nyní',
      bg: 'Изтегли сега',
      hr: 'Preuzmi sada',
      sr: 'Преузми сада',
      sl: 'Prenesi zdaj',
      mk: 'Преземи сега',
      be: 'Выгрузіць зараз',
      bs: 'Preuzmi sada',
      hsb: 'Nětko wotwołać',
    }),
    syncing: t({
      ru: 'Выгрузка…',
      en: 'Pulling…',
      kk: 'Жүктелуде…',
      de: 'Abruf läuft…',
      fr: 'Récupération…',
      es: 'Descargando…',
      pt: 'Buscando…',
      tr: 'Çekiliyor…',
      uk: 'Вивантаження…',
      zh: '拉取中…',
      ar: 'جارٍ السحب…',
      pl: 'Pobieranie…',
      it: 'Scaricamento…',
      sk: 'Sťahuje sa…',
      ja: '取得中…',
      ko: '가져오는 중…',
      hi: 'ला रहे हैं…',
      nl: 'Ophalen…',
      sv: 'Hämtar…',
      vi: 'Đang lấy…',
      id: 'Menarik…',
      da: 'Henter…',
      nb: 'Henter…',
      nn: 'Hentar…',
      fi: 'Haetaan…',
      is: 'Sækir…',
      fo: 'Heintar…',
      cs: 'Stahování…',
      bg: 'Изтегляне…',
      hr: 'Preuzimanje…',
      sr: 'Преузимање…',
      sl: 'Prenašanje…',
      mk: 'Преземање…',
      be: 'Выгрузка…',
      bs: 'Preuzimanje…',
      hsb: 'Wotwołuje so…',
    }),
    refreshAccounts: t({
      ru: 'Обновить список счетов',
      en: 'Refresh accounts',
      kk: 'Шоттар тізімін жаңарту',
      de: 'Konten aktualisieren',
      fr: 'Actualiser les comptes',
      es: 'Actualizar cuentas',
      pt: 'Atualizar contas',
      tr: 'Hesapları yenile',
      uk: 'Оновити рахунки',
      zh: '刷新账户',
      ar: 'تحديث الحسابات',
      pl: 'Odśwież konta',
      it: 'Aggiorna conti',
      sk: 'Obnoviť účty',
      ja: '口座を更新',
      ko: '계좌 새로 고침',
      hi: 'खाते रीफ़्रेश करें',
      nl: 'Rekeningen vernieuwen',
      sv: 'Uppdatera konton',
      vi: 'Làm mới tài khoản',
      id: 'Segarkan rekening',
      da: 'Opdater konti',
      nb: 'Oppdater kontoer',
      nn: 'Oppdater kontoar',
      fi: 'Päivitä tilit',
      is: 'Endurnýja reikninga',
      fo: 'Dagfør kontur',
      cs: 'Obnovit účty',
      bg: 'Опресни сметките',
      hr: 'Osvježi račune',
      sr: 'Освежи рачуне',
      sl: 'Osveži račune',
      mk: 'Освежи сметки',
      be: 'Абнавіць рахункі',
      bs: 'Osvježi račune',
      hsb: 'Konta aktualizować',
    }),
    refreshing: t({
      ru: 'Обновление…',
      en: 'Refreshing…',
      kk: 'Жаңартылуда…',
      de: 'Aktualisieren…',
      fr: 'Actualisation…',
      es: 'Actualizando…',
      pt: 'Atualizando…',
      tr: 'Yenileniyor…',
      uk: 'Оновлення…',
      zh: '刷新中…',
      ar: 'جارٍ التحديث…',
      pl: 'Odświeżanie…',
      it: 'Aggiornamento…',
      sk: 'Obnovuje sa…',
      ja: '更新中…',
      ko: '새로 고치는 중…',
      hi: 'रीफ़्रेश हो रहा है…',
      nl: 'Vernieuwen…',
      sv: 'Uppdaterar…',
      vi: 'Đang làm mới…',
      id: 'Menyegarkan…',
      da: 'Opdaterer…',
      nb: 'Oppdaterer…',
      nn: 'Oppdaterer…',
      fi: 'Päivitetään…',
      is: 'Endurnýjar…',
      fo: 'Dagførir…',
      cs: 'Obnovování…',
      bg: 'Опресняване…',
      hr: 'Osvježavanje…',
      sr: 'Освежавање…',
      sl: 'Osveževanje…',
      mk: 'Освежување…',
      be: 'Абнаўленне…',
      bs: 'Osvježavanje…',
      hsb: 'Aktualizuje so…',
    }),
    disconnect: t({
      ru: 'Отключить',
      en: 'Disconnect',
      kk: 'Ажырату',
      de: 'Trennen',
      fr: 'Déconnecter',
      es: 'Desconectar',
      pt: 'Desconectar',
      tr: 'Bağlantıyı kes',
      uk: 'Відключити',
      zh: '断开',
      ar: 'فصل',
      pl: 'Rozłącz',
      it: 'Scollega',
      sk: 'Odpojiť',
      ja: '接続解除',
      ko: '연결 해제',
      hi: 'डिस्कनेक्ट',
      nl: 'Ontkoppelen',
      sv: 'Koppla från',
      vi: 'Ngắt kết nối',
      id: 'Putuskan',
      da: 'Afbryd',
      nb: 'Koble fra',
      nn: 'Kople frå',
      fi: 'Katkaise yhteys',
      is: 'Aftengja',
      fo: 'Skilja frá',
      cs: 'Odpojit',
      bg: 'Изключи',
      hr: 'Odspoji',
      sr: 'Искључи',
      sl: 'Odklopi',
      mk: 'Исклучи',
      be: 'Адключыць',
      bs: 'Odspoji',
      hsb: 'Wotdźělić',
    }),
    disconnecting: t({
      ru: 'Отключение…',
      en: 'Disconnecting…',
      kk: 'Ажыратылуда…',
      de: 'Trennen…',
      fr: 'Déconnexion…',
      es: 'Desconectando…',
      pt: 'Desconectando…',
      tr: 'Bağlantı kesiliyor…',
      uk: 'Відключення…',
      zh: '断开中…',
      ar: 'جارٍ الفصل…',
      pl: 'Rozłączanie…',
      it: 'Scollegamento…',
      sk: 'Odpája sa…',
      ja: '解除中…',
      ko: '해제 중…',
      hi: 'डिस्कनेक्ट हो रहा है…',
      nl: 'Ontkoppelen…',
      sv: 'Kopplar från…',
      vi: 'Đang ngắt…',
      id: 'Memutuskan…',
      da: 'Afbryder…',
      nb: 'Kobler fra…',
      nn: 'Koplar frå…',
      fi: 'Katkaistaan…',
      is: 'Aftengir…',
      fo: 'Skilur frá…',
      cs: 'Odpojování…',
      bg: 'Изключване…',
      hr: 'Odspajanje…',
      sr: 'Искључивање…',
      sl: 'Odklapljanje…',
      mk: 'Исклучување…',
      be: 'Адключэнне…',
      bs: 'Odspajanje…',
      hsb: 'Wotdźěla so…',
    }),
    lastError: t({
      ru: 'Последняя ошибка',
      en: 'Last error',
      kk: 'Соңғы қате',
      de: 'Letzter Fehler',
      fr: 'Dernière erreur',
      es: 'Último error',
      pt: 'Último erro',
      tr: 'Son hata',
      uk: 'Остання помилка',
      zh: '上次错误',
      ar: 'آخر خطأ',
      pl: 'Ostatni błąd',
      it: 'Ultimo errore',
      sk: 'Posledná chyba',
      ja: '最終エラー',
      ko: '마지막 오류',
      hi: 'अंतिम त्रुटि',
      nl: 'Laatste fout',
      sv: 'Senaste fel',
      vi: 'Lỗi gần nhất',
      id: 'Kesalahan terakhir',
      da: 'Seneste fejl',
      nb: 'Siste feil',
      nn: 'Siste feil',
      fi: 'Viimeisin virhe',
      is: 'Síðasta villa',
      fo: 'Seinasti feilur',
      cs: 'Poslední chyba',
      bg: 'Последна грешка',
      hr: 'Zadnja pogreška',
      sr: 'Последња грешка',
      sl: 'Zadnja napaka',
      mk: 'Последна грешка',
      be: 'Апошняя памылка',
      bs: 'Zadnja greška',
      hsb: 'Poslednji zmylk',
    }),
    connected: t({
      ru: 'SimpleFIN подключён. Выберите счета и нажмите «Забрать сейчас».',
      en: 'SimpleFIN connected. Choose the accounts and press "Pull now".',
      kk: 'SimpleFIN қосылды. Шоттарды таңдап, «Қазір алу» түймесін басыңыз.',
      de: 'SimpleFIN verbunden. Wählen Sie die Konten und klicken Sie auf „Jetzt abrufen“.',
      fr: 'SimpleFIN connecté. Choisissez les comptes et cliquez sur « Récupérer maintenant ».',
      es: 'SimpleFIN conectado. Elige las cuentas y pulsa «Descargar ahora».',
      pt: 'SimpleFIN conectado. Escolha as contas e clique em “Buscar agora”.',
      tr: 'SimpleFIN bağlandı. Hesapları seçip “Şimdi çek”e basın.',
      uk: 'SimpleFIN підключено. Виберіть рахунки й натисніть «Забрати зараз».',
      zh: 'SimpleFIN 已连接。选择账户并点击“立即拉取”。',
      ar: 'تم ربط SimpleFIN. اختر الحسابات واضغط «اسحب الآن».',
      pl: 'SimpleFIN połączony. Wybierz konta i kliknij „Pobierz teraz”.',
      it: 'SimpleFIN collegato. Scegli i conti e premi «Scarica ora».',
      sk: 'SimpleFIN pripojený. Vyberte účty a stlačte „Stiahnuť teraz“.',
      ja: 'SimpleFIN を接続しました。口座を選んで「今すぐ取得」を押してください。',
      ko: 'SimpleFIN이 연결되었습니다. 계좌를 고르고 "지금 가져오기"를 누르세요.',
      hi: 'SimpleFIN जुड़ गया। खाते चुनें और "अभी लाएँ" दबाएँ।',
      nl: 'SimpleFIN gekoppeld. Kies de rekeningen en klik op "Nu ophalen".',
      sv: 'SimpleFIN anslutet. Välj konton och tryck på ”Hämta nu”.',
      vi: 'Đã kết nối SimpleFIN. Chọn tài khoản và nhấn "Lấy ngay".',
      id: 'SimpleFIN terhubung. Pilih rekening lalu tekan "Tarik sekarang".',
      da: 'SimpleFIN er forbundet. Vælg konti, og tryk på »Hent nu«.',
      nb: 'SimpleFIN er tilkoblet. Velg kontoene og trykk «Hent nå».',
      nn: 'SimpleFIN er tilkopla. Vel kontoane og trykk «Hent no».',
      fi: 'SimpleFIN on yhdistetty. Valitse tilit ja paina ”Hae nyt”.',
      is: 'SimpleFIN er tengt. Veldu reikningana og ýttu á „Sækja núna“.',
      fo: 'SimpleFIN er tengt. Vel konturnar og trýst á „Heinta nú“.',
      cs: 'SimpleFIN je připojen. Vyberte účty a stiskněte „Stáhnout nyní“.',
      bg: 'SimpleFIN е свързан. Изберете сметките и натиснете „Изтегли сега“.',
      hr: 'SimpleFIN je povezan. Odaberite račune i pritisnite „Preuzmi sada”.',
      sr: 'SimpleFIN је повезан. Изаберите рачуне и притисните „Преузми сада”.',
      sl: 'SimpleFIN je povezan. Izberite račune in pritisnite »Prenesi zdaj«.',
      mk: 'SimpleFIN е поврзан. Изберете ги сметките и притиснете „Преземи сега“.',
      be: 'SimpleFIN падключаны. Выберыце рахункі і націсніце «Выгрузіць зараз».',
      bs: 'SimpleFIN je povezan. Odaberite račune i pritisnite „Preuzmi sada”.',
      hsb: 'SimpleFIN je zwjazany. Wubjerće konta a stłóčće „Nětko wotwołać“.',
    }),
    connectFailed: t({
      ru: 'Не удалось подключить',
      en: 'Could not connect',
      kk: 'Қосу мүмкін болмады',
      de: 'Verbindung fehlgeschlagen',
      fr: 'Connexion impossible',
      es: 'No se pudo conectar',
      pt: 'Não foi possível conectar',
      tr: 'Bağlanılamadı',
      uk: 'Не вдалося підключити',
      zh: '无法连接',
      ar: 'تعذّر الربط',
      pl: 'Nie udało się połączyć',
      it: 'Impossibile collegare',
      sk: 'Nepodarilo sa pripojiť',
      ja: '接続できませんでした',
      ko: '연결할 수 없음',
      hi: 'कनेक्ट नहीं हो सका',
      nl: 'Koppelen mislukt',
      sv: 'Kunde inte ansluta',
      vi: 'Không thể kết nối',
      id: 'Tidak dapat terhubung',
      da: 'Kunne ikke forbinde',
      nb: 'Kunne ikke koble til',
      nn: 'Kunne ikkje kople til',
      fi: 'Yhdistäminen epäonnistui',
      is: 'Tókst ekki að tengja',
      fo: 'Kundi ikki tengja',
      cs: 'Připojení se nezdařilo',
      bg: 'Неуспешно свързване',
      hr: 'Povezivanje nije uspjelo',
      sr: 'Повезивање није успело',
      sl: 'Povezava ni uspela',
      mk: 'Поврзувањето не успеа',
      be: 'Не ўдалося падключыць',
      bs: 'Povezivanje nije uspjelo',
      hsb: 'Zwjazanje njeje so poradźiło',
    }),
    saved: t({
      ru: 'Настройки сохранены',
      en: 'Settings saved',
      kk: 'Параметрлер сақталды',
      de: 'Einstellungen gespeichert',
      fr: 'Réglages enregistrés',
      es: 'Ajustes guardados',
      pt: 'Configurações salvas',
      tr: 'Ayarlar kaydedildi',
      uk: 'Налаштування збережено',
      zh: '设置已保存',
      ar: 'تم حفظ الإعدادات',
      pl: 'Ustawienia zapisane',
      it: 'Impostazioni salvate',
      sk: 'Nastavenia uložené',
      ja: '設定を保存しました',
      ko: '설정이 저장됨',
      hi: 'सेटिंग सहेजी गईं',
      nl: 'Instellingen opgeslagen',
      sv: 'Inställningar sparade',
      vi: 'Đã lưu cài đặt',
      id: 'Pengaturan disimpan',
      da: 'Indstillinger gemt',
      nb: 'Innstillinger lagret',
      nn: 'Innstillingar lagra',
      fi: 'Asetukset tallennettu',
      is: 'Stillingar vistaðar',
      fo: 'Stillingar goymdar',
      cs: 'Nastavení uloženo',
      bg: 'Настройките са запазени',
      hr: 'Postavke spremljene',
      sr: 'Подешавања сачувана',
      sl: 'Nastavitve shranjene',
      mk: 'Поставките се зачувани',
      be: 'Налады захаваны',
      bs: 'Postavke sačuvane',
      hsb: 'Nastajenja składowane',
    }),
    saveFailed: t({
      ru: 'Не удалось сохранить',
      en: 'Could not save',
      kk: 'Сақтау мүмкін болмады',
      de: 'Speichern fehlgeschlagen',
      fr: 'Enregistrement impossible',
      es: 'No se pudo guardar',
      pt: 'Não foi possível salvar',
      tr: 'Kaydedilemedi',
      uk: 'Не вдалося зберегти',
      zh: '无法保存',
      ar: 'تعذّر الحفظ',
      pl: 'Nie udało się zapisać',
      it: 'Impossibile salvare',
      sk: 'Nepodarilo sa uložiť',
      ja: '保存できませんでした',
      ko: '저장할 수 없음',
      hi: 'सहेजा नहीं जा सका',
      nl: 'Opslaan mislukt',
      sv: 'Kunde inte spara',
      vi: 'Không thể lưu',
      id: 'Tidak dapat menyimpan',
      da: 'Kunne ikke gemme',
      nb: 'Kunne ikke lagre',
      nn: 'Kunne ikkje lagre',
      fi: 'Tallennus epäonnistui',
      is: 'Tókst ekki að vista',
      fo: 'Kundi ikki goyma',
      cs: 'Uložení se nezdařilo',
      bg: 'Неуспешно запазване',
      hr: 'Spremanje nije uspjelo',
      sr: 'Чување није успело',
      sl: 'Shranjevanje ni uspelo',
      mk: 'Зачувувањето не успеа',
      be: 'Не ўдалося захаваць',
      bs: 'Spašavanje nije uspjelo',
      hsb: 'Składowanje njeje so poradźiło',
    }),
    accountsRefreshed: t({
      ru: 'Список счетов обновлён',
      en: 'Account list refreshed',
      kk: 'Шоттар тізімі жаңартылды',
      de: 'Kontenliste aktualisiert',
      fr: 'Liste des comptes actualisée',
      es: 'Lista de cuentas actualizada',
      pt: 'Lista de contas atualizada',
      tr: 'Hesap listesi yenilendi',
      uk: 'Список рахунків оновлено',
      zh: '账户列表已刷新',
      ar: 'تم تحديث قائمة الحسابات',
      pl: 'Lista kont odświeżona',
      it: 'Elenco conti aggiornato',
      sk: 'Zoznam účtov obnovený',
      ja: '口座一覧を更新しました',
      ko: '계좌 목록이 새로 고쳐짐',
      hi: 'खाता सूची रीफ़्रेश हुई',
      nl: 'Rekeningenlijst vernieuwd',
      sv: 'Kontolistan uppdaterad',
      vi: 'Đã làm mới danh sách tài khoản',
      id: 'Daftar rekening disegarkan',
      da: 'Kontolisten er opdateret',
      nb: 'Kontolisten er oppdatert',
      nn: 'Kontolista er oppdatert',
      fi: 'Tililuettelo päivitetty',
      is: 'Reikningalisti endurnýjaður',
      fo: 'Kontulistin er dagførdur',
      cs: 'Seznam účtů obnoven',
      bg: 'Списъкът със сметки е опреснен',
      hr: 'Popis računa osvježen',
      sr: 'Листа рачуна освежена',
      sl: 'Seznam računov osvežen',
      mk: 'Листата на сметки е освежена',
      be: 'Спіс рахункаў абноўлены',
      bs: 'Lista računa osvježena',
      hsb: 'Lisćina kontow aktualizowana',
    }),
    synced: t({
      ru: '{rows} строк отправлено в импорт ({statements} выписок)',
      en: '{rows} rows sent to import ({statements} statements)',
      kk: '{rows} жол импортқа жіберілді ({statements} үзінді)',
      de: '{rows} Zeilen an den Import übergeben ({statements} Auszüge)',
      fr: '{rows} lignes envoyées à l’import ({statements} relevés)',
      es: '{rows} filas enviadas a importar ({statements} extractos)',
      pt: '{rows} linhas enviadas à importação ({statements} extratos)',
      tr: '{rows} satır içe aktarmaya gönderildi ({statements} ekstre)',
      uk: '{rows} рядків надіслано в імпорт ({statements} виписок)',
      zh: '已将 {rows} 行送入导入（{statements} 份对账单）',
      ar: 'أُرسل {rows} صفًا إلى الاستيراد ({statements} كشوف)',
      pl: '{rows} wierszy przekazano do importu ({statements} wyciągów)',
      it: '{rows} righe inviate all’import ({statements} estratti)',
      sk: '{rows} riadkov odoslaných do importu ({statements} výpisov)',
      ja: '{rows} 行をインポートに送信（{statements} 明細）',
      ko: '{rows}개 행을 가져오기로 보냄 ({statements}개 명세)',
      hi: '{rows} पंक्तियाँ इंपोर्ट में भेजी गईं ({statements} स्टेटमेंट)',
      nl: '{rows} rijen naar import gestuurd ({statements} afschriften)',
      sv: '{rows} rader skickade till import ({statements} utdrag)',
      vi: 'Đã gửi {rows} dòng vào nhập ({statements} sao kê)',
      id: '{rows} baris dikirim ke impor ({statements} mutasi)',
      da: '{rows} rækker sendt til import ({statements} kontoudtog)',
      nb: '{rows} rader sendt til import ({statements} kontoutskrifter)',
      nn: '{rows} rader sende til import ({statements} kontoutskrifter)',
      fi: '{rows} riviä lähetetty tuontiin ({statements} tiliotetta)',
      is: '{rows} línur sendar í innflutning ({statements} yfirlit)',
      fo: '{rows} røðir sendar til innflutning ({statements} kontoúrtøk)',
      cs: '{rows} řádků odesláno do importu ({statements} výpisů)',
      bg: '{rows} реда изпратени за импорт ({statements} извлечения)',
      hr: '{rows} redaka poslano na uvoz ({statements} izvoda)',
      sr: '{rows} редова послато на увоз ({statements} извода)',
      sl: '{rows} vrstic poslanih v uvoz ({statements} izpiskov)',
      mk: '{rows} редови испратени на увоз ({statements} изводи)',
      be: '{rows} радкоў адпраўлена ў імпарт ({statements} выпісак)',
      bs: '{rows} redova poslano na uvoz ({statements} izvoda)',
      hsb: '{rows} linkow do importa pósłanych ({statements} wupisow)',
    }),
    nothingNew: t({
      ru: 'Новых операций нет',
      en: 'Nothing new',
      kk: 'Жаңа операциялар жоқ',
      de: 'Nichts Neues',
      fr: 'Rien de nouveau',
      es: 'Nada nuevo',
      pt: 'Nada de novo',
      tr: 'Yeni bir şey yok',
      uk: 'Нових операцій немає',
      zh: '没有新记录',
      ar: 'لا جديد',
      pl: 'Nic nowego',
      it: 'Niente di nuovo',
      sk: 'Nič nové',
      ja: '新しい明細はありません',
      ko: '새 내역 없음',
      hi: 'कुछ नया नहीं',
      nl: 'Niets nieuws',
      sv: 'Inget nytt',
      vi: 'Không có gì mới',
      id: 'Tidak ada yang baru',
      da: 'Intet nyt',
      nb: 'Ingenting nytt',
      nn: 'Ingenting nytt',
      fi: 'Ei mitään uutta',
      is: 'Ekkert nýtt',
      fo: 'Einki nýtt',
      cs: 'Nic nového',
      bg: 'Нищо ново',
      hr: 'Ništa novo',
      sr: 'Ништа ново',
      sl: 'Nič novega',
      mk: 'Ништо ново',
      be: 'Нічога новага',
      bs: 'Ništa novo',
      hsb: 'Ničo noweho',
    }),
    syncFailed: t({
      ru: 'Выгрузка не удалась',
      en: 'Pull failed',
      kk: 'Жүктеу сәтсіз',
      de: 'Abruf fehlgeschlagen',
      fr: 'Échec de la récupération',
      es: 'La descarga falló',
      pt: 'A busca falhou',
      tr: 'Çekim başarısız',
      uk: 'Вивантаження не вдалося',
      zh: '拉取失败',
      ar: 'فشل السحب',
      pl: 'Pobieranie nie powiodło się',
      it: 'Scaricamento non riuscito',
      sk: 'Stiahnutie zlyhalo',
      ja: '取得に失敗しました',
      ko: '가져오기 실패',
      hi: 'लाना विफल',
      nl: 'Ophalen mislukt',
      sv: 'Hämtningen misslyckades',
      vi: 'Lấy thất bại',
      id: 'Penarikan gagal',
      da: 'Hentning mislykkedes',
      nb: 'Henting mislyktes',
      nn: 'Henting mislukkast',
      fi: 'Haku epäonnistui',
      is: 'Sókn mistókst',
      fo: 'Heinting miseydnaðist',
      cs: 'Stažení se nezdařilo',
      bg: 'Неуспешно изтегляне',
      hr: 'Preuzimanje nije uspjelo',
      sr: 'Преузимање није успело',
      sl: 'Prenos ni uspel',
      mk: 'Преземањето не успеа',
      be: 'Выгрузка не ўдалася',
      bs: 'Preuzimanje nije uspjelo',
      hsb: 'Wotwołanje njeje so poradźiło',
    }),
    disconnected: t({
      ru: 'Отключено. Доступ удалён, импортированные выписки остались.',
      en: 'Disconnected. The credential is gone; the imported statements stay.',
      kk: 'Ажыратылды. Қатынау жойылды, импортталған үзінділер қалды.',
      de: 'Getrennt. Der Zugang ist gelöscht; die importierten Auszüge bleiben.',
      fr: 'Déconnecté. L’accès est supprimé ; les relevés importés restent.',
      es: 'Desconectado. El acceso se eliminó; los extractos importados se conservan.',
      pt: 'Desconectado. O acesso foi removido; os extratos importados permanecem.',
      tr: 'Bağlantı kesildi. Erişim silindi; içe aktarılan ekstreler kaldı.',
      uk: 'Відключено. Доступ видалено, імпортовані виписки залишилися.',
      zh: '已断开。凭据已删除；已导入的对账单保留。',
      ar: 'تم الفصل. حُذف الوصول؛ الكشوف المستوردة باقية.',
      pl: 'Rozłączono. Dostęp usunięty; zaimportowane wyciągi zostają.',
      it: 'Scollegato. L’accesso è stato rimosso; gli estratti importati restano.',
      sk: 'Odpojené. Prístup je odstránený; importované výpisy zostávajú.',
      ja: '接続を解除しました。認証情報は削除され、インポート済みの明細は残ります。',
      ko: '연결 해제됨. 자격 증명은 삭제되고 가져온 명세는 남습니다.',
      hi: 'डिस्कनेक्ट हो गया। एक्सेस हट गया; इंपोर्ट किए स्टेटमेंट बने रहेंगे।',
      nl: 'Ontkoppeld. De toegang is weg; de geïmporteerde afschriften blijven.',
      sv: 'Frånkopplad. Åtkomsten är borta; de importerade utdragen finns kvar.',
      vi: 'Đã ngắt. Thông tin truy cập đã xóa; các sao kê đã nhập vẫn còn.',
      id: 'Terputus. Kredensial dihapus; mutasi yang sudah diimpor tetap ada.',
      da: 'Afbrudt. Adgangen er slettet; de importerede kontoudtog bliver.',
      nb: 'Koblet fra. Tilgangen er slettet; de importerte kontoutskriftene blir værende.',
      nn: 'Kopla frå. Tilgangen er sletta; dei importerte kontoutskriftene blir verande.',
      fi: 'Yhteys katkaistu. Tunnistetiedot on poistettu; tuodut tiliotteet säilyvät.',
      is: 'Aftengt. Aðgangurinn er horfinn; innfluttu yfirlitin haldast.',
      fo: 'Skilt frá. Atgongdin er strikað; innfluttu kontoúrtøkini verða verandi.',
      cs: 'Odpojeno. Přístup je smazán; importované výpisy zůstávají.',
      bg: 'Изключено. Достъпът е изтрит; импортираните извлечения остават.',
      hr: 'Odspojeno. Pristup je obrisan; uvezeni izvodi ostaju.',
      sr: 'Искључено. Приступ је обрисан; увезени изводи остају.',
      sl: 'Odklopljeno. Dostop je izbrisan; uvoženi izpiski ostanejo.',
      mk: 'Исклучено. Пристапот е избришан; увезените изводи остануваат.',
      be: 'Адключана. Доступ выдалены; імпартаваныя выпіскі застаюцца.',
      bs: 'Odspojeno. Pristup je obrisan; uvezeni izvodi ostaju.',
      hsb: 'Wotdźělene. Přistup je zhašeny; importowane wupisy wostanu.',
    }),
    disconnectFailed: t({
      ru: 'Не удалось отключить',
      en: 'Could not disconnect',
      kk: 'Ажырату мүмкін болмады',
      de: 'Trennen fehlgeschlagen',
      fr: 'Déconnexion impossible',
      es: 'No se pudo desconectar',
      pt: 'Não foi possível desconectar',
      tr: 'Bağlantı kesilemedi',
      uk: 'Не вдалося відключити',
      zh: '无法断开',
      ar: 'تعذّر الفصل',
      pl: 'Nie udało się rozłączyć',
      it: 'Impossibile scollegare',
      sk: 'Nepodarilo sa odpojiť',
      ja: '解除できませんでした',
      ko: '연결 해제 실패',
      hi: 'डिस्कनेक्ट नहीं हो सका',
      nl: 'Ontkoppelen mislukt',
      sv: 'Kunde inte koppla från',
      vi: 'Không thể ngắt',
      id: 'Tidak dapat memutuskan',
      da: 'Kunne ikke afbryde',
      nb: 'Kunne ikke koble fra',
      nn: 'Kunne ikkje kople frå',
      fi: 'Yhteyden katkaisu epäonnistui',
      is: 'Tókst ekki að aftengja',
      fo: 'Kundi ikki skilja frá',
      cs: 'Odpojení se nezdařilo',
      bg: 'Неуспешно изключване',
      hr: 'Odspajanje nije uspjelo',
      sr: 'Искључивање није успело',
      sl: 'Odklop ni uspel',
      mk: 'Исклучувањето не успеа',
      be: 'Не ўдалося адключыць',
      bs: 'Odspajanje nije uspjelo',
      hsb: 'Wotdźělenje njeje so poradźiło',
    }),
    loadFailed: t({
      ru: 'Не удалось загрузить статус',
      en: 'Could not load the status',
      kk: 'Күйді жүктеу мүмкін болмады',
      de: 'Status konnte nicht geladen werden',
      fr: 'Impossible de charger le statut',
      es: 'No se pudo cargar el estado',
      pt: 'Não foi possível carregar o status',
      tr: 'Durum yüklenemedi',
      uk: 'Не вдалося завантажити статус',
      zh: '无法加载状态',
      ar: 'تعذّر تحميل الحالة',
      pl: 'Nie udało się wczytać statusu',
      it: 'Impossibile caricare lo stato',
      sk: 'Nepodarilo sa načítať stav',
      ja: 'ステータスを読み込めませんでした',
      ko: '상태를 불러올 수 없음',
      hi: 'स्थिति लोड नहीं हो सकी',
      nl: 'Status kon niet worden geladen',
      sv: 'Kunde inte läsa in status',
      vi: 'Không tải được trạng thái',
      id: 'Tidak dapat memuat status',
      da: 'Kunne ikke indlæse status',
      nb: 'Kunne ikke laste inn status',
      nn: 'Kunne ikkje laste inn status',
      fi: 'Tilaa ei voitu ladata',
      is: 'Ekki tókst að hlaða stöðu',
      fo: 'Kundi ikki heinta støðuna',
      cs: 'Stav se nepodařilo načíst',
      bg: 'Статусът не можа да се зареди',
      hr: 'Status nije moguće učitati',
      sr: 'Статус није могуће учитати',
      sl: 'Stanja ni bilo mogoče naložiti',
      mk: 'Статусот не можеше да се вчита',
      be: 'Не ўдалося загрузіць статус',
      bs: 'Status nije moguće učitati',
      hsb: 'Status njeda so začitać',
    }),
  },
} satisfies Dictionary;

export default content;
