import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'loginPage',
  content: {
    title: t({
      ru: 'С возвращением',
      en: 'Welcome back',
      kk: 'Қайта келдіңіз',
      de: 'Willkommen zurück',
      fr: 'Bon retour',
      es: 'Bienvenido de nuevo',
      pt: 'Bem-vindo de volta',
      tr: 'Tekrar hoş geldiniz',
      uk: 'З поверненням',
      zh: '欢迎回来',
      ar: 'مرحباً بعودتك',
      pl: 'Witaj ponownie',
      it: 'Bentornato',
      sk: 'Witaj ponownie',
      ja: 'おかえりなさい',
      ko: '다시 오신 것을 환영합니다',
      hi: 'वापस स्वागत है',
      nl: 'Welkom terug',
      sv: 'Välkommen tillbaka',
      vi: 'Chào mừng trở lại',
      id: 'Selamat datang kembali',
    }),
    subtitle: t({
      ru: 'Войдите, чтобы продолжить работу в Lumio',
      en: 'Log in to continue using Lumio',
      kk: 'Lumio қолдануды жалғастыру үшін кіріңіз',
      de: 'Melden Sie sich an, um Lumio weiter zu nutzen',
      fr: 'Connectez-vous pour continuer à utiliser Lumio',
      es: 'Inicia sesión para continuar usando Lumio',
      pt: 'Faça login para continuar usando o Lumio',
      tr: "Lumio'yu kullanmaya devam etmek için giriş yapın",
      uk: 'Увійдіть, щоб продовжити роботу в Lumio',
      zh: '登录以继续使用 Lumio',
      ar: 'سجّل دخولك لمواصلة استخدام Lumio',
      pl: 'Zaloguj się, aby kontynuować korzystanie z Lumio',
      it: 'Accedi per continuare a usare Lumio',
      sk: 'Zaloguj się, aby kontynuować korzystanie z Lumio',
      ja: 'Lumioの使用を続けるにはログインしてください',
      ko: 'Lumio를 계속 사용하려면 로그인하세요',
      hi: 'Lumio का उपयोग जारी रखने के लिए लॉग इन करें',
      nl: 'Log in om Lumio te blijven gebruiken',
      sv: 'Logga in för att fortsätta använda Lumio',
      vi: 'Đăng nhập để tiếp tục sử dụng Lumio',
      id: 'Masuk untuk melanjutkan menggunakan Lumio',
    }),
    passwordLabel: t({
      ru: 'Пароль',
      en: 'Password',
      kk: 'Құпиясөз',
      de: 'Passwort',
      fr: 'Mot de passe',
      es: 'Contraseña',
      pt: 'Senha',
      tr: 'Şifre',
      uk: 'Пароль',
      zh: '密码',
      ar: 'كلمة المرور',
      pl: 'Hasło',
      it: "Parola d'ordine",
      sk: 'Hasło',
      ja: 'パスワード',
      ko: '비밀번호',
      hi: 'पासवर्ड',
      nl: 'Wachtwoord',
      sv: 'Lösenord',
      vi: 'Mật khẩu',
      id: 'Kata sandi',
    }),
    emailLabel: t({
      ru: 'Электронная почта',
      en: 'Email',
      kk: 'Электрондық пошта',
      de: 'E-Mail',
      fr: 'E-mail',
      es: 'Correo electrónico',
      pt: 'E-mail',
      tr: 'E-posta',
      uk: 'Електронна пошта',
      zh: '电子邮件',
      ar: 'البريد الإلكتروني',
      pl: 'E-mail',
      it: 'E-mail',
      sk: 'E-mail',
      ja: 'メール',
      ko: '이메일',
      hi: 'ईमेल',
      nl: 'E-mail',
      sv: 'E-post',
      vi: 'Thư điện tử',
      id: 'Surel',
    }),
    submit: t({
      ru: 'Войти',
      en: 'Log in',
      kk: 'Кіру',
      de: 'Anmelden',
      fr: 'Se connecter',
      es: 'Iniciar sesión',
      pt: 'Entrar',
      tr: 'Giriş yap',
      uk: 'Увійти',
      zh: '登录',
      ar: 'تسجيل الدخول',
      pl: 'Zaloguj się',
      it: 'Accedi',
      sk: 'Zaloguj się',
      ja: 'ログイン',
      ko: '로그인',
      hi: 'लॉग इन करें',
      nl: 'Inloggen',
      sv: 'Logga in',
      vi: 'Đăng nhập',
      id: 'Masuk',
    }),
    noAccount: t({
      ru: 'Нет аккаунта? Зарегистрируйтесь',
      en: "Don't have an account? Sign up",
      kk: 'Аккаунт жоқ па? Тіркеліңіз',
      de: 'Noch kein Konto? Registrieren',
      fr: "Pas de compte ? S'inscrire",
      es: '¿No tienes cuenta? Regístrate',
      pt: 'Não tem uma conta? Cadastre-se',
      tr: 'Hesabınız yok mu? Kaydolun',
      uk: 'Немає акаунту? Зареєструйтесь',
      zh: '没有账号？立即注册',
      ar: 'ليس لديك حساب؟ سجّل الآن',
      pl: 'Nie masz konta? Zarejestruj się',
      it: 'Non hai un account? Registrati',
      sk: 'Nie masz konta? Zarejestruj się',
      ja: 'アカウントをお持ちでないですか？登録する',
      ko: '계정이 없으신가요? 회원가입',
      hi: 'खाता नहीं है? साइन अप करें',
      nl: 'Geen account? Registreer je',
      sv: 'Har du inget konto? Registrera dig',
      vi: 'Chưa có tài khoản? Đăng ký',
      id: 'Belum punya akun? Daftar',
    }),
    rightTagline: t({
      ru: 'Платформа для обработки банковских выписок',
      en: 'A platform for bank statement processing',
      kk: 'Банк үзінділерін өңдеуге арналған платформа',
      de: 'Eine Plattform zur Verarbeitung von Kontoauszügen',
      fr: 'Une plateforme de traitement des relevés bancaires',
      es: 'Una plataforma para el procesamiento de extractos bancarios',
      pt: 'Uma plataforma para processamento de extratos bancários',
      tr: 'Banka ekstresi işleme platformu',
      uk: 'Платформа для обробки банківських виписок',
      zh: '银行对账单处理平台',
      ar: 'منصة لمعالجة كشوف الحسابات البنكية',
      pl: 'Platforma do przetwarzania wyciągów bankowych',
      it: "Una piattaforma per l'elaborazione degli estratti conto bancari",
      sk: 'Platforma do przetwarzania wyciągów bankowych',
      ja: '銀行取引明細書処理プラットフォーム',
      ko: '은행 명세서 처리 플랫폼',
      hi: 'बैंक स्टेटमेंट प्रोसेसिंग के लिए एक प्लेटफॉर्म',
      nl: 'Een platform voor bankrekeningverwerking',
      sv: 'En plattform för bearbetning av kontoutdrag',
      vi: 'Nền tảng xử lý sao kê ngân hàng',
      id: 'Platform untuk pemrosesan rekening koran',
    }),
    twoFactorLabel: t({
      ru: 'Код подтверждения',
      en: 'Verification code',
      kk: 'Растау коды',
      de: 'Bestätigungscode',
      fr: 'Code de vérification',
      es: 'Código de verificación',
      pt: 'Código de verificação',
      tr: 'Doğrulama kodu',
      uk: 'Код підтвердження',
      zh: '验证码',
      ar: 'رمز التحقق',
      pl: 'Kod weryfikacyjny',
      it: 'Codice di verifica',
      sk: 'Overovací kód',
      ja: '確認コード',
      ko: '인증 코드',
      hi: 'सत्यापन कोड',
      nl: 'Verificatiecode',
      sv: 'Verifieringskod',
      vi: 'Mã xác minh',
      id: 'Kode verifikasi',
    }),
    twoFactorHint: t({
      ru: 'Введите код из приложения-аутентификатора или один из резервных кодов.',
      en: 'Enter the code from your authenticator app or one of your recovery codes.',
      kk: 'Аутентификатор қолданбасындағы кодты немесе сақтық кодтардың бірін енгізіңіз.',
      de: 'Geben Sie den Code aus Ihrer Authenticator-App oder einen Wiederherstellungscode ein.',
      fr: "Saisissez le code de votre application d'authentification ou l'un de vos codes de secours.",
      es: 'Introduce el código de tu aplicación de autenticación o uno de tus códigos de recuperación.',
      pt: 'Digite o código do seu aplicativo autenticador ou um dos seus códigos de recuperação.',
      tr: 'Kimlik doğrulama uygulamanızdaki kodu ya da kurtarma kodlarınızdan birini girin.',
      uk: 'Введіть код із застосунку-автентифікатора або один із резервних кодів.',
      zh: '请输入验证器应用中的验证码或一个恢复码。',
      ar: 'أدخل الرمز من تطبيق المصادقة أو أحد رموز الاسترداد.',
      pl: 'Wprowadź kod z aplikacji uwierzytelniającej lub jeden z kodów zapasowych.',
      it: "Inserisci il codice dell'app di autenticazione o uno dei codici di ripristino.",
      sk: 'Zadajte kód z overovacej aplikácie alebo jeden zo záložných kódov.',
      ja: '認証アプリのコード、またはリカバリーコードを入力してください。',
      ko: '인증 앱의 코드 또는 복구 코드 중 하나를 입력하세요.',
      hi: 'अपने ऑथेंटिकेटर ऐप का कोड या अपना कोई रिकवरी कोड दर्ज करें।',
      nl: 'Voer de code uit je authenticator-app of een van je herstelcodes in.',
      sv: 'Ange koden från din autentiseringsapp eller en av dina återställningskoder.',
      vi: 'Nhập mã từ ứng dụng xác thực hoặc một trong các mã khôi phục của bạn.',
      id: 'Masukkan kode dari aplikasi autentikator atau salah satu kode pemulihan Anda.',
    }),
    loginFailed: t({
      ru: 'Не удалось выполнить вход. Попробуйте ещё раз.',
      en: 'Failed to log in. Please try again.',
      kk: 'Кіру мүмкін болмады. Қайтадан көріңіз.',
      de: 'Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.',
      fr: 'Échec de la connexion. Veuillez réessayer.',
      es: 'Error al iniciar sesión. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao fazer login. Por favor, tente novamente.',
      tr: 'Giriş başarısız. Lütfen tekrar deneyin.',
      uk: 'Не вдалося увійти. Спробуйте ще раз.',
      zh: '登录失败，请重试。',
      ar: 'فشل تسجيل الدخول. يرجى المحاولة مرة أخرى.',
      pl: 'Logowanie nie powiodło się. Spróbuj ponownie.',
      it: 'Accesso non riuscito. Per favore riprova.',
      sk: 'Logowanie nie powiodło się. Spróbuj ponownie.',
      ja: 'ログインに失敗しました。もう一度お試しください。',
      ko: '로그인에 실패했습니다. 다시 시도해 주세요.',
      hi: 'लॉग इन करने में विफल। कृपया पुनः प्रयास करें।',
      nl: 'Inloggen mislukt. Probeer het opnieuw.',
      sv: 'Det gick inte att logga in. Försök igen.',
      vi: 'Đăng nhập thất bại. Vui lòng thử lại.',
      id: 'Gagal masuk. Silakan coba lagi.',
    }),
  },
} satisfies Dictionary;

export default content;
