import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'registerPage',
  content: {
    title: t({
      ru: 'Создайте аккаунт',
      en: 'Create an account',
      kk: 'Аккаунт жасаңыз',
      de: 'Konto erstellen',
      fr: 'Créer un compte',
      es: 'Crear una cuenta',
      pt: 'Criar uma conta',
      tr: 'Hesap oluştur',
      uk: 'Створіть акаунт',
      zh: '创建账号',
      ar: 'إنشاء حساب',
      pl: 'Utwórz konto',
      it: 'Crea un account',
      sk: 'Utwórz konto',
      ja: 'アカウントを作成する',
      ko: '계정 만들기',
      hi: 'खाता बनाएं',
      nl: 'Account aanmaken',
      sv: 'Skapa ett konto',
      vi: 'Tạo tài khoản',
      id: 'Buat akun',
    }),
    subtitle: t({
      ru: 'Присоединяйтесь к Lumio',
      en: 'Join Lumio',
      kk: 'Lumio-қа қосылыңыз',
      de: 'Lumio beitreten',
      fr: 'Rejoignez Lumio',
      es: 'Únete a Lumio',
      pt: 'Junte-se ao Lumio',
      tr: "Lumio'ya katılın",
      uk: 'Приєднайтесь до Lumio',
      zh: '加入 Lumio',
      ar: 'انضم إلى Lumio',
      pl: 'Dołącz do Lumio',
      it: 'Unisciti a Lumio',
      sk: 'Dołącz do Lumio',
      ja: 'Lumioに参加する',
      ko: 'Lumio에 가입하세요',
      hi: 'Lumio से जुड़ें',
      nl: 'Word lid van Lumio',
      sv: 'Gå med i Lumio',
      vi: 'Tham gia Lumio',
      id: 'Bergabung dengan Lumio',
    }),
    fullNameLabel: t({
      ru: 'Полное имя',
      en: 'Full name',
      kk: 'Толық аты-жөні',
      de: 'Vollständiger Name',
      fr: 'Nom complet',
      es: 'Nombre completo',
      pt: 'Nome completo',
      tr: 'Tam ad',
      uk: "Повне ім'я",
      zh: '全名',
      ar: 'الاسم الكامل',
      pl: 'Pełne imię i nazwisko',
      it: 'Nome completo',
      sk: 'Pełne imię i nazwisko',
      ja: 'フルネーム',
      ko: '전체 이름',
      hi: 'पूरा नाम',
      nl: 'Volledige naam',
      sv: 'Fullständigt namn',
      vi: 'Họ và tên',
      id: 'Nama lengkap',
    }),
    emailLabel: t({
      ru: 'Электронная почта',
      en: 'Email',
      kk: 'Электрондық пошта',
      de: 'E-Mail',
      fr: 'E-mail',
      es: 'Correo electrónico',
      pt: 'E-mail',
      tr: 'E-posta',
      uk: 'Електронна пошта',
      zh: '电子邮件',
      ar: 'البريد الإلكتروني',
      pl: 'E-mail',
      it: 'Email',
      sk: 'E-mail',
      ja: 'メール',
      ko: '이메일',
      hi: 'ईमेल',
      nl: 'E-mail',
      sv: 'E-post',
      vi: 'Email',
      id: 'Email',
    }),
    passwordLabel: t({
      ru: 'Пароль',
      en: 'Password',
      kk: 'Құпиясөз',
      de: 'Passwort',
      fr: 'Mot de passe',
      es: 'Contraseña',
      pt: 'Senha',
      tr: 'Şifre',
      uk: 'Пароль',
      zh: '密码',
      ar: 'كلمة المرور',
      pl: 'Hasło',
      it: 'Password',
      sk: 'Hasło',
      ja: 'パスワード',
      ko: '비밀번호',
      hi: 'पासवर्ड',
      nl: 'Wachtwoord',
      sv: 'Lösenord',
      vi: 'Mật khẩu',
      id: 'Kata sandi',
    }),
    passwordHelper: t({
      ru: 'Минимум 8 символов',
      en: 'At least 8 characters',
      kk: 'Кемінде 8 таңба',
      de: 'Mindestens 8 Zeichen',
      fr: 'Au moins 8 caractères',
      es: 'Al menos 8 caracteres',
      pt: 'Pelo menos 8 caracteres',
      tr: 'En az 8 karakter',
      uk: 'Мінімум 8 символів',
      zh: '至少 8 个字符',
      ar: '8 أحرف على الأقل',
      pl: 'Co najmniej 8 znaków',
      it: 'Almeno 8 caratteri',
      sk: 'Co najmniej 8 znaków',
      ja: '8文字以上',
      ko: '8자 이상',
      hi: 'कम से कम 8 अक्षर',
      nl: 'Minimaal 8 tekens',
      sv: 'Minst 8 tecken',
      vi: 'Ít nhất 8 ký tự',
      id: 'Minimal 8 karakter',
    }),
    companyLabel: t({
      ru: 'Компания (опционально)',
      en: 'Company (optional)',
      kk: 'Компания (міндетті емес)',
      de: 'Unternehmen (optional)',
      fr: 'Entreprise (facultatif)',
      es: 'Empresa (opcional)',
      pt: 'Empresa (opcional)',
      tr: 'Şirket (isteğe bağlı)',
      uk: "Компанія (необов'язково)",
      zh: '公司（可选）',
      ar: 'الشركة (اختياري)',
      pl: 'Firma (opcjonalnie)',
      it: 'Azienda (facoltativo)',
      sk: 'Firma (opcjonalnie)',
      ja: '会社名（任意）',
      ko: '회사 (선택사항)',
      hi: 'कंपनी (वैकल्पिक)',
      nl: 'Bedrijf (optioneel)',
      sv: 'Företag (valfritt)',
      vi: 'Công ty (tùy chọn)',
      id: 'Perusahaan (opsional)',
    }),
    submit: t({
      ru: 'Зарегистрироваться',
      en: 'Sign up',
      kk: 'Тіркелу',
      de: 'Registrieren',
      fr: "S'inscrire",
      es: 'Registrarse',
      pt: 'Cadastrar-se',
      tr: 'Kaydol',
      uk: 'Зареєструватися',
      zh: '注册',
      ar: 'إنشاء حساب',
      pl: 'Zarejestruj się',
      it: 'Registrati',
      sk: 'Zarejestruj się',
      ja: '登録する',
      ko: '회원가입',
      hi: 'साइन अप करें',
      nl: 'Registreren',
      sv: 'Registrera dig',
      vi: 'Đăng ký',
      id: 'Daftar',
    }),
    haveAccount: t({
      ru: 'Уже есть аккаунт? Войти',
      en: 'Already have an account? Log in',
      kk: 'Аккаунтыңыз бар ма? Кіру',
      de: 'Bereits ein Konto? Anmelden',
      fr: 'Déjà un compte ? Se connecter',
      es: '¿Ya tienes cuenta? Iniciar sesión',
      pt: 'Já tem uma conta? Entrar',
      tr: 'Zaten hesabınız var mı? Giriş yapın',
      uk: 'Вже є акаунт? Увійти',
      zh: '已有账号？登录',
      ar: 'لديك حساب بالفعل؟ تسجيل الدخول',
      pl: 'Masz już konto? Zaloguj się',
      it: 'Hai già un account? Accedi',
      sk: 'Masz już konto? Zaloguj się',
      ja: 'すでにアカウントをお持ちですか？ログイン',
      ko: '이미 계정이 있으신가요? 로그인',
      hi: 'पहले से खाता है? लॉग इन करें',
      nl: 'Al een account? Inloggen',
      sv: 'Har du redan ett konto? Logga in',
      vi: 'Đã có tài khoản? Đăng nhập',
      id: 'Sudah punya akun? Masuk',
    }),
    rightTitle: t({
      ru: 'Присоединяйтесь к Lumio',
      en: 'Join Lumio',
      kk: 'Lumio-қа қосылыңыз',
      de: 'Lumio beitreten',
      fr: 'Rejoignez Lumio',
      es: 'Únete a Lumio',
      pt: 'Junte-se ao Lumio',
      tr: "Lumio'ya katılın",
      uk: 'Приєднайтесь до Lumio',
      zh: '加入 Lumio',
      ar: 'انضم إلى Lumio',
      pl: 'Dołącz do Lumio',
      it: 'Unisciti a Lumio',
      sk: 'Dołącz do Lumio',
      ja: 'Lumioに参加する',
      ko: 'Lumio에 가입하세요',
      hi: 'Lumio से जुड़ें',
      nl: 'Word lid van Lumio',
      sv: 'Gå med i Lumio',
      vi: 'Tham gia Lumio',
      id: 'Bergabung dengan Lumio',
    }),
    rightTagline: t({
      ru: 'Автоматизируйте финансы уже сегодня',
      en: 'Automate your finances today',
      kk: 'Қаржыңызды бүгін автоматтандырыңыз',
      de: 'Automatisieren Sie Ihre Finanzen noch heute',
      fr: "Automatisez vos finances dès aujourd'hui",
      es: 'Automatiza tus finanzas hoy',
      pt: 'Automatize suas finanças hoje',
      tr: 'Finanslarınızı bugün otomatikleştirin',
      uk: 'Автоматизуйте фінанси вже сьогодні',
      zh: '今天就自动化您的财务',
      ar: 'أتمتة أموالك اليوم',
      pl: 'Zautomatyzuj swoje finanse już dziś',
      it: 'Automatizza le tue finanze oggi',
      sk: 'Zautomatyzuj swoje finanse już dziś',
      ja: '今日から財務を自動化しましょう',
      ko: '지금 바로 재무를 자동화하세요',
      hi: 'आज ही अपने वित्त को स्वचालित करें',
      nl: 'Automatiseer vandaag nog uw financiën',
      sv: 'Automatisera din ekonomi idag',
      vi: 'Tự động hóa tài chính của bạn ngay hôm nay',
      id: 'Otomatiskan keuangan Anda hari ini',
    }),
    registerFailed: t({
      ru: 'Не удалось зарегистрироваться. Попробуйте ещё раз.',
      en: 'Failed to sign up. Please try again.',
      kk: 'Тіркелу мүмкін болмады. Қайтадан көріңіз.',
      de: 'Registrierung fehlgeschlagen. Bitte versuchen Sie es erneut.',
      fr: "Échec de l'inscription. Veuillez réessayer.",
      es: 'Error al registrarse. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao se cadastrar. Por favor, tente novamente.',
      tr: 'Kayıt başarısız. Lütfen tekrar deneyin.',
      uk: 'Не вдалося зареєструватися. Спробуйте ще раз.',
      zh: '注册失败，请重试。',
      ar: 'فشل إنشاء الحساب. يرجى المحاولة مرة أخرى.',
      pl: 'Rejestracja nie powiodła się. Spróbuj ponownie.',
      it: 'Registrazione non riuscita. Per favore riprova.',
      sk: 'Rejestracja nie powiodła się. Spróbuj ponownie.',
      ja: '登録に失敗しました。もう一度お試しください。',
      ko: '회원가입에 실패했습니다. 다시 시도해 주세요.',
      hi: 'साइन अप करने में विफल। कृपया पुनः प्रयास करें।',
      nl: 'Registratie mislukt. Probeer het opnieuw.',
      sv: 'Det gick inte att registrera dig. Försök igen.',
      vi: 'Đăng ký thất bại. Vui lòng thử lại.',
      id: 'Gagal mendaftar. Silakan coba lagi.',
    }),
    inviteLoadFailed: t({
      ru: 'Не удалось загрузить данные приглашения. Попробуйте ещё раз.',
      en: 'Failed to load invitation details. Please try again.',
      kk: 'Шақыру деректерін жүктеу мүмкін болмады. Қайтадан көріңіз.',
      de: 'Einladungsdetails konnten nicht geladen werden. Bitte versuchen Sie es erneut.',
      fr: "Impossible de charger les détails de l'invitation. Veuillez réessayer.",
      es: 'Error al cargar los detalles de la invitación. Por favor, inténtalo de nuevo.',
      pt: 'Falha ao carregar detalhes do convite. Por favor, tente novamente.',
      tr: 'Davet ayrıntıları yüklenemedi. Lütfen tekrar deneyin.',
      uk: 'Не вдалося завантажити дані запрошення. Спробуйте ще раз.',
      zh: '无法加载邀请详情，请重试。',
      ar: 'فشل تحميل تفاصيل الدعوة. يرجى المحاولة مرة أخرى.',
      pl: 'Nie udało się załadować szczegółów zaproszenia. Spróbuj ponownie.',
      it: "Impossibile caricare i dettagli dell'invito. Per favore riprova.",
      sk: 'Nie udało się załadować szczegółów zaproszenia. Spróbuj ponownie.',
      ja: '招待の詳細を読み込めませんでした。もう一度お試しください。',
      ko: '초대 세부 정보를 불러오는 데 실패했습니다. 다시 시도해 주세요.',
      hi: 'निमंत्रण विवरण लोड करने में विफल। कृपया पुनः प्रयास करें।',
      nl: 'Kan uitnodigingsgegevens niet laden. Probeer het opnieuw.',
      sv: 'Det gick inte att ladda inbjudningsdetaljer. Försök igen.',
      vi: 'Không thể tải chi tiết lời mời. Vui lòng thử lại.',
      id: 'Gagal memuat detail undangan. Silakan coba lagi.',
    }),
  },
} satisfies Dictionary;

export default content;
