/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'googleSheetsIntegrationPage',
  content: {
    errors: {
      loadConnections: t({
        ru: 'Не удалось загрузить подключённые таблицы',
        en: 'Failed to load connected sheets',
        kk: 'Қосылған кестелерді жүктеу мүмкін болмады',
        de: 'Verbundene Tabellen konnten nicht geladen werden',
        fr: 'Impossible de charger les feuilles connectées',
        es: 'No se pudieron cargar las hojas conectadas',
        pt: 'Falha ao carregar planilhas conectadas',
        tr: 'Bağlı tablolar yüklenemedi',
        uk: 'Не вдалося завантажити підключені таблиці',
        zh: '无法加载已连接的表格',
        ar: 'فشل تحميل الجداول المتصلة',
        pl: 'Nie udało się załadować połączonych arkuszy',
        it: 'Impossibile caricare i fogli connessi',
        sk: 'Nie udało się załadować połączonych arkuszy',
        ja: '接続済みシートの読み込みに失敗しました',
        ko: '연결된 시트를 불러오지 못했습니다',
        hi: 'कनेक्टेड शीट लोड करने में विफल',
        nl: 'Verbonden sheets laden mislukt',
        sv: 'Det gick inte att läsa in anslutna ark',
        vi: 'Không thể tải các trang tính đã kết nối',
        id: 'Gagal memuat lembar yang terhubung',
      }),
      missingAuthUrl: t({
        ru: 'Не удалось получить ссылку для авторизации Google',
        en: 'Failed to get Google authorization URL',
        kk: 'Google авторизация сілтемесін алу мүмкін болмады',
        de: 'Google-Autorisierungs-URL konnte nicht abgerufen werden',
        fr: "Impossible d'obtenir l'URL d'autorisation Google",
        es: 'No se pudo obtener la URL de autorización de Google',
        pt: 'Falha ao obter URL de autorização do Google',
        tr: "Google yetkilendirme URL'si alınamadı",
        uk: 'Не вдалося отримати посилання для авторизації Google',
        zh: '无法获取 Google 授权 URL',
        ar: 'فشل الحصول على رابط تفويض Google',
        pl: 'Nie udało się uzyskać URL autoryzacji Google',
        it: "Impossibile ottenere l'URL di autorizzazione Google",
        sk: 'Nie udało się uzyskać URL autoryzacji Google',
        ja: 'Google認証URLの取得に失敗しました',
        ko: 'Google 인증 URL을 가져오지 못했습니다',
        hi: 'Google प्राधिकरण URL प्राप्त करने में विफल',
        nl: 'Google-autorisatie-URL ophalen mislukt',
        sv: 'Det gick inte att hämta Google-auktoriserings-URL',
        vi: 'Không thể lấy URL xác thực Google',
        id: 'Gagal mendapatkan URL otorisasi Google',
      }),
      sheetIdMissing: t({
        ru: 'Укажите ID или ссылку на таблицу',
        en: 'Provide a spreadsheet ID or URL',
        kk: 'Кестенің ID немесе сілтемесін көрсетіңіз',
        de: 'Geben Sie eine Tabellen-ID oder URL an',
        fr: 'Fournissez un ID ou une URL de feuille de calcul',
        es: 'Proporciona un ID o URL de hoja de cálculo',
        pt: 'Forneça um ID ou URL de planilha',
        tr: "Bir elektronik tablo ID'si veya URL'si girin",
        uk: 'Вкажіть ID або посилання на таблицю',
        zh: '请提供电子表格 ID 或 URL',
        ar: 'أدخل معرّف جدول البيانات أو عنوان URL',
        pl: 'Podaj ID lub URL arkusza',
        it: 'Fornisci un ID o URL del foglio di calcolo',
        sk: 'Podaj ID lub URL arkusza',
        ja: 'スプレッドシートのIDまたはURLを入力してください',
        ko: '스프레드시트 ID 또는 URL을 입력하세요',
        hi: 'स्प्रेडशीट ID या URL प्रदान करें',
        nl: 'Geef een spreadsheet-ID of URL op',
        sv: 'Ange ett kalkylblads-ID eller URL',
        vi: 'Cung cấp ID hoặc URL bảng tính',
        id: 'Berikan ID atau URL spreadsheet',
      }),
      connectFailed: t({
        ru: 'Не удалось подключить таблицу',
        en: 'Failed to connect spreadsheet',
        kk: 'Кестені қосу мүмкін болмады',
        de: 'Tabelle konnte nicht verbunden werden',
        fr: 'Impossible de connecter la feuille de calcul',
        es: 'No se pudo conectar la hoja de cálculo',
        pt: 'Falha ao conectar planilha',
        tr: 'Elektronik tablo bağlanamadı',
        uk: 'Не вдалося підключити таблицю',
        zh: '无法连接电子表格',
        ar: 'فشل توصيل جدول البيانات',
        pl: 'Nie udało się połączyć arkusza',
        it: 'Impossibile connettere il foglio di calcolo',
        sk: 'Nie udało się połączyć arkusza',
        ja: 'スプレッドシートの接続に失敗しました',
        ko: '스프레드시트 연결에 실패했습니다',
        hi: 'स्प्रेडशीट कनेक्ट करने में विफल',
        nl: 'Spreadsheet verbinden mislukt',
        sv: 'Det gick inte att ansluta kalkylbladet',
        vi: 'Không thể kết nối bảng tính',
        id: 'Gagal menghubungkan spreadsheet',
      }),
      loadWorksheets: t({
        ru: 'Не удалось загрузить листы таблицы',
        en: 'Failed to load spreadsheet worksheets',
        kk: 'Кесте парақтарын жүктеу мүмкін болмады',
        de: 'Tabellenblätter konnten nicht geladen werden',
        fr: 'Impossible de charger les feuilles de calcul',
        es: 'No se pudieron cargar las hojas de la hoja de cálculo',
        pt: 'Falha ao carregar planilhas da tabela',
        tr: 'Elektronik tablo sayfaları yüklenemedi',
        uk: 'Не вдалося завантажити аркуші таблиці',
        zh: '无法加载电子表格工作表',
        ar: 'فشل تحميل أوراق جدول البيانات',
        pl: 'Nie udało się załadować arkuszy tabeli',
        it: 'Impossibile caricare i fogli di lavoro',
        sk: 'Nie udało się załadować arkuszy tabeli',
        ja: 'スプレッドシートのワークシートの読み込みに失敗しました',
        ko: '스프레드시트 워크시트를 불러오지 못했습니다',
        hi: 'स्प्रेडशीट वर्कशीट लोड करने में विफल',
        nl: 'Spreadsheet-werkbladen laden mislukt',
        sv: 'Det gick inte att läsa in kalkylbladsark',
        vi: 'Không thể tải các trang tính của bảng tính',
        id: 'Gagal memuat lembar kerja spreadsheet',
      }),
      spreadsheetRequired: t({
        ru: 'Сначала выберите таблицу в Google Picker',
        en: 'Choose a spreadsheet in Google Picker first',
        kk: 'Алдымен Google Picker арқылы кестені таңдаңыз',
        de: 'Wählen Sie zuerst eine Tabelle in Google Picker aus',
        fr: "Choisissez d'abord une feuille de calcul dans Google Picker",
        es: 'Elige primero una hoja de cálculo en Google Picker',
        pt: 'Escolha primeiro uma planilha no Google Picker',
        tr: "Önce Google Picker'da bir elektronik tablo seçin",
        uk: 'Спочатку виберіть таблицю в Google Picker',
        zh: '请先在 Google Picker 中选择电子表格',
        ar: 'اختر جدول بيانات في Google Picker أولاً',
        pl: 'Najpierw wybierz arkusz w Google Picker',
        it: 'Scegli prima un foglio di calcolo in Google Picker',
        sk: 'Najpierw wybierz arkusz w Google Picker',
        ja: 'まずGoogle Pickerでスプレッドシートを選択してください',
        ko: 'Google Picker에서 먼저 스프레드시트를 선택하세요',
        hi: 'पहले Google Picker में एक स्प्रेडशीट चुनें',
        nl: 'Kies eerst een spreadsheet in Google Picker',
        sv: 'Välj ett kalkylblad i Google Picker först',
        vi: 'Trước tiên hãy chọn bảng tính trong Google Picker',
        id: 'Pilih spreadsheet di Google Picker terlebih dahulu',
      }),
      syncFailed: t({
        ru: 'Не удалось синхронизировать',
        en: 'Failed to sync',
        kk: 'Синхрондау мүмкін болмады',
        de: 'Synchronisierung fehlgeschlagen',
        fr: 'Échec de la synchronisation',
        es: 'No se pudo sincronizar',
        pt: 'Falha ao sincronizar',
        tr: 'Senkronizasyon başarısız',
        uk: 'Не вдалося синхронізувати',
        zh: '同步失败',
        ar: 'فشلت المزامنة',
        pl: 'Nie udało się zsynchronizować',
        it: 'Sincronizzazione fallita',
        sk: 'Nie udało się zsynchronizować',
        ja: '同期に失敗しました',
        ko: '동기화에 실패했습니다',
        hi: 'सिंक करने में विफल',
        nl: 'Synchroniseren mislukt',
        sv: 'Det gick inte att synkronisera',
        vi: 'Không thể đồng bộ',
        id: 'Gagal menyinkronkan',
      }),
      removeFailed: t({
        ru: 'Не удалось отключить таблицу',
        en: 'Failed to disconnect sheet',
        kk: 'Кестені ажырату мүмкін болмады',
        de: 'Tabelle konnte nicht getrennt werden',
        fr: 'Impossible de déconnecter la feuille',
        es: 'No se pudo desconectar la hoja',
        pt: 'Falha ao desconectar planilha',
        tr: 'Tablo bağlantısı kesilemedi',
        uk: 'Не вдалося відключити таблицю',
        zh: '无法断开表格连接',
        ar: 'فشل قطع اتصال الجدول',
        pl: 'Nie udało się rozłączyć arkusza',
        it: 'Impossibile disconnettere il foglio',
        sk: 'Nie udało się rozłączyć arkusza',
        ja: 'シートの切断に失敗しました',
        ko: '시트 연결 해제에 실패했습니다',
        hi: 'शीट डिस्कनेक्ट करने में विफल',
        nl: 'Spreadsheet verbreken mislukt',
        sv: 'Det gick inte att koppla från arket',
        vi: 'Không thể ngắt kết nối trang tính',
        id: 'Gagal memutuskan lembar',
      }),
    },
    toasts: {
      openingAuth: t({
        ru: 'Открываем Google авторизацию…',
        en: 'Opening Google authorization…',
        kk: 'Google авторизациясы ашылуда…',
        de: 'Google-Autorisierung wird geöffnet…',
        fr: "Ouverture de l'autorisation Google…",
        es: 'Abriendo autorización de Google…',
        pt: 'Abrindo autorização do Google…',
        tr: 'Google yetkilendirmesi açılıyor…',
        uk: 'Відкриваємо авторизацію Google…',
        zh: '正在打开 Google 授权…',
        ar: 'جارٍ فتح تفويض Google…',
        pl: 'Otwieranie autoryzacji Google…',
        it: 'Apertura autorizzazione Google…',
        sk: 'Otwieranie autoryzacji Google…',
        ja: 'Google認証を開いています…',
        ko: 'Google 인증을 여는 중…',
        hi: 'Google प्राधिकरण खोला जा रहा है…',
        nl: 'Google-autorisatie openen…',
        sv: 'Öppnar Google-auktorisering…',
        vi: 'Đang mở xác thực Google…',
        id: 'Membuka otorisasi Google…',
      }),
      connected: t({
        ru: 'Google Sheets подключен',
        en: 'Google Sheets connected',
        kk: 'Google Sheets қосылды',
        de: 'Google Sheets verbunden',
        fr: 'Google Sheets connecté',
        es: 'Google Sheets conectado',
        pt: 'Google Sheets conectado',
        tr: 'Google Sheets bağlandı',
        uk: 'Google Sheets підключено',
        zh: 'Google Sheets 已连接',
        ar: 'تم توصيل Google Sheets',
        pl: 'Google Sheets połączony',
        it: 'Google Sheets connesso',
        sk: 'Google Sheets połączony',
        ja: 'Google Sheetsが接続されました',
        ko: 'Google Sheets 연결됨',
        hi: 'Google Sheets कनेक्ट हो गया',
        nl: 'Google Sheets verbonden',
        sv: 'Google Sheets ansluten',
        vi: 'Google Sheets đã kết nối',
        id: 'Google Sheets terhubung',
      }),
      syncStarted: t({
        ru: 'Синхронизация запущена',
        en: 'Sync started',
        kk: 'Синхрондау басталды',
        de: 'Synchronisierung gestartet',
        fr: 'Synchronisation démarrée',
        es: 'Sincronización iniciada',
        pt: 'Sincronização iniciada',
        tr: 'Senkronizasyon başlatıldı',
        uk: 'Синхронізацію розпочато',
        zh: '同步已开始',
        ar: 'بدأت المزامنة',
        pl: 'Synchronizacja rozpoczęta',
        it: 'Sincronizzazione avviata',
        sk: 'Synchronizacja rozpoczęta',
        ja: '同期が開始されました',
        ko: '동기화가 시작되었습니다',
        hi: 'सिंक शुरू हो गई',
        nl: 'Synchronisatie gestart',
        sv: 'Synkronisering startad',
        vi: 'Đồng bộ đã bắt đầu',
        id: 'Sinkronisasi dimulai',
      }),
      removed: t({
        ru: 'Подключение отключено',
        en: 'Connection removed',
        kk: 'Қосылым ажыратылды',
        de: 'Verbindung entfernt',
        fr: 'Connexion supprimée',
        es: 'Conexión eliminada',
        pt: 'Conexão removida',
        tr: 'Bağlantı kaldırıldı',
        uk: 'Підключення видалено',
        zh: '连接已移除',
        ar: 'تمت إزالة الاتصال',
        pl: 'Połączenie usunięte',
        it: 'Connessione rimossa',
        sk: 'Połączenie usunięte',
        ja: '接続が削除されました',
        ko: '연결이 제거되었습니다',
        hi: 'कनेक्शन हटाया गया',
        nl: 'Verbinding verwijderd',
        sv: 'Anslutning borttagen',
        vi: 'Kết nối đã bị xóa',
        id: 'Koneksi dihapus',
      }),
    },
    loginRequired: {
      title: t({
        ru: 'Войдите, чтобы подключить Google Sheets',
        en: 'Log in to connect Google Sheets',
        kk: 'Google Sheets қосу үшін кіріңіз',
        de: 'Melden Sie sich an, um Google Sheets zu verbinden',
        fr: 'Connectez-vous pour relier Google Sheets',
        es: 'Inicia sesión para conectar Google Sheets',
        pt: 'Faça login para conectar o Google Sheets',
        tr: "Google Sheets'i bağlamak için giriş yapın",
        uk: 'Увійдіть, щоб підключити Google Sheets',
        zh: '登录以连接 Google Sheets',
        ar: 'سجّل الدخول لتوصيل Google Sheets',
        pl: 'Zaloguj się, aby połączyć Google Sheets',
        it: 'Accedi per connettere Google Sheets',
        sk: 'Zaloguj się, aby połączyć Google Sheets',
        ja: 'Google Sheetsを接続するにはログインしてください',
        ko: 'Google Sheets를 연결하려면 로그인하세요',
        hi: 'Google Sheets कनेक्ट करने के लिए लॉग इन करें',
        nl: 'Log in om Google Sheets te verbinden',
        sv: 'Logga in för att ansluta Google Sheets',
        vi: 'Đăng nhập để kết nối Google Sheets',
        id: 'Masuk untuk menghubungkan Google Sheets',
      }),
      subtitle: t({
        ru: 'Авторизация нужна для создания привязки таблицы к вашему аккаунту.',
        en: 'Authorization is required to link a sheet to your account.',
        kk: 'Кестені аккаунтыңызға байланыстыру үшін авторизация қажет.',
        de: 'Eine Autorisierung ist erforderlich, um eine Tabelle mit Ihrem Konto zu verknüpfen.',
        fr: 'Une autorisation est requise pour lier une feuille à votre compte.',
        es: 'Se requiere autorización para vincular una hoja a tu cuenta.',
        pt: 'Autorização necessária para vincular uma planilha à sua conta.',
        tr: 'Bir sayfayı hesabınıza bağlamak için yetkilendirme gereklidir.',
        uk: "Авторизація потрібна для прив'язки таблиці до вашого облікового запису.",
        zh: '需要授权才能将表格链接到您的账户。',
        ar: 'التفويض مطلوب لربط جدول بيانات بحسابك.',
        pl: 'Autoryzacja jest wymagana do powiązania arkusza z kontem.',
        it: "L'autorizzazione è necessaria per collegare un foglio al tuo account.",
        sk: 'Autoryzacja jest wymagana do powiązania arkusza z kontem.',
        ja: 'シートをアカウントにリンクするには認証が必要です。',
        ko: '시트를 계정에 연결하려면 인증이 필요합니다.',
        hi: 'शीट को आपके खाते से लिंक करने के लिए प्राधिकरण आवश्यक है।',
        nl: 'Autorisatie is vereist om een blad aan uw account te koppelen.',
        sv: 'Auktorisering krävs för att länka ett ark till ditt konto.',
        vi: 'Cần xác thực để liên kết trang tính với tài khoản của bạn.',
        id: 'Otorisasi diperlukan untuk menghubungkan lembar ke akun Anda.',
      }),
    },
    header: {
      title: t({
        ru: 'Подключение Google Sheets',
        en: 'Google Sheets connection',
        kk: 'Google Sheets қосу',
        de: 'Google Sheets-Verbindung',
        fr: 'Connexion Google Sheets',
        es: 'Conexión de Google Sheets',
        pt: 'Conexão do Google Sheets',
        tr: 'Google Sheets bağlantısı',
        uk: 'Підключення Google Sheets',
        zh: 'Google Sheets 连接',
        ar: 'اتصال Google Sheets',
        pl: 'Połączenie Google Sheets',
        it: 'Connessione Google Sheets',
        sk: 'Połączenie Google Sheets',
        ja: 'Google Sheets接続',
        ko: 'Google Sheets 연결',
        hi: 'Google Sheets कनेक्शन',
        nl: 'Google Sheets-verbinding',
        sv: 'Google Sheets-anslutning',
        vi: 'Kết nối Google Sheets',
        id: 'Koneksi Google Sheets',
      }),
      subtitle: t({
        ru: 'Укажите таблицу и лист, куда будут отправляться данные. После подключения вставьте Apps Script из документации для отправки вебхуков.',
        en: 'Specify the spreadsheet and sheet tab for sending data. After connecting, paste the Apps Script from the docs to send webhooks.',
        kk: 'Деректер жіберілетін кесте мен парақты көрсетіңіз. Қосылғаннан кейін вебхук жіберу үшін құжаттамадағы Apps Script-ті қойыңыз.',
        de: 'Geben Sie die Tabelle und das Blatt für den Datenversand an. Fügen Sie nach der Verbindung das Apps Script aus den Docs ein, um Webhooks zu senden.',
        fr: "Spécifiez le tableur et l'onglet pour envoyer les données. Après connexion, collez le script Apps Script de la documentation pour envoyer des webhooks.",
        es: 'Especifica la hoja de cálculo y la pestaña de hoja para enviar datos. Después de conectar, pega el Apps Script de la documentación para enviar webhooks.',
        pt: 'Especifique a planilha e a aba para envio de dados. Após conectar, cole o Apps Script da documentação para enviar webhooks.',
        tr: "Veri gönderimi için elektronik tablo ve sayfa sekmesini belirtin. Bağlandıktan sonra, web kancaları göndermek için belgelerdeki Apps Script'i yapıştırın.",
        uk: 'Вкажіть таблицю та аркуш, куди надсилатимуться дані. Після підключення вставте Apps Script з документації для відправки вебхуків.',
        zh: '指定用于发送数据的电子表格和工作表选项卡。连接后，粘贴文档中的 Apps Script 以发送 Webhook。',
        ar: 'حدد جدول البيانات وعلامة تبويب الورقة لإرسال البيانات. بعد الاتصال، الصق Apps Script من المستندات لإرسال webhooks.',
        pl: 'Określ arkusz kalkulacyjny i kartę arkusza do wysyłania danych. Po połączeniu wklej Apps Script z dokumentacji, aby wysyłać webhooki.',
        it: "Specifica il foglio di calcolo e la scheda per l'invio dei dati. Dopo la connessione, incolla Apps Script dalla documentazione per inviare webhook.",
        sk: 'Określ arkusz kalkulacyjny i kartę arkusza do wysyłania danych. Po połączeniu wklej Apps Script z dokumentacji, aby wysyłać webhooki.',
        ja: 'データ送信用のスプレッドシートとシートタブを指定します。接続後、ドキュメントからApps ScriptをペーストしてWebhookを送信します。',
        ko: '데이터 전송을 위한 스프레드시트와 시트 탭을 지정하세요. 연결 후 문서에서 Apps Script를 붙여넣어 웹훅을 전송하세요.',
        hi: 'डेटा भेजने के लिए स्प्रेडशीट और शीट टैब निर्दिष्ट करें। कनेक्ट करने के बाद, वेबहुक भेजने के लिए दस्तावेज़ से Apps Script पेस्ट करें।',
        nl: 'Geef de spreadsheet en het bladtabblad op voor het verzenden van gegevens. Plak na het verbinden het Apps Script uit de documentatie om webhooks te sturen.',
        sv: 'Ange kalkylbladet och bladfliken för att skicka data. Efter anslutning, klistra in Apps Script från dokumentationen för att skicka webhooks.',
        vi: 'Chỉ định bảng tính và tab trang tính để gửi dữ liệu. Sau khi kết nối, dán Apps Script từ tài liệu để gửi webhook.',
        id: 'Tentukan spreadsheet dan tab lembar untuk mengirim data. Setelah terhubung, tempel Apps Script dari dokumentasi untuk mengirim webhook.',
      }),
    },
    step1: {
      label: t({
        ru: 'Шаг 1',
        en: 'Step 1',
        kk: '1-қадам',
        de: 'Schritt 1',
        fr: 'Étape 1',
        es: 'Paso 1',
        pt: 'Etapa 1',
        tr: 'Adım 1',
        uk: 'Крок 1',
        zh: '第 1 步',
        ar: 'الخطوة 1',
        pl: 'Krok 1',
        it: 'Passaggio 1',
        sk: 'Krok 1',
        ja: 'ステップ 1',
        ko: '단계 1',
        hi: 'चरण 1',
        nl: 'Stap 1',
        sv: 'Steg 1',
        vi: 'Bước 1',
        id: 'Langkah 1',
      }),
      title: t({
        ru: 'Подключить Google Sheets',
        en: 'Connect Google Sheets',
        kk: 'Google Sheets қосу',
        de: 'Google Sheets verbinden',
        fr: 'Connecter Google Sheets',
        es: 'Conectar Google Sheets',
        pt: 'Conectar Google Sheets',
        tr: "Google Sheets'i bağla",
        uk: 'Підключити Google Sheets',
        zh: '连接 Google Sheets',
        ar: 'توصيل Google Sheets',
        pl: 'Połącz Google Sheets',
        it: 'Connetti Google Sheets',
        sk: 'Połącz Google Sheets',
        ja: 'Google Sheetsを接続',
        ko: 'Google Sheets 연결',
        hi: 'Google Sheets कनेक्ट करें',
        nl: 'Google Sheets verbinden',
        sv: 'Anslut Google Sheets',
        vi: 'Kết nối Google Sheets',
        id: 'Hubungkan Google Sheets',
      }),
      accountLabel: t({
        ru: 'Google аккаунт',
        en: 'Google account',
        kk: 'Google аккаунты',
        de: 'Google-Konto',
        fr: 'Compte Google',
        es: 'Cuenta de Google',
        pt: 'Conta Google',
        tr: 'Google hesabı',
        uk: 'Google-акаунт',
        zh: 'Google 账户',
        ar: 'حساب Google',
        pl: 'Konto Google',
        it: 'Account Google',
        sk: 'Konto Google',
        ja: 'Googleアカウント',
        ko: 'Google 계정',
        hi: 'Google खाता',
        nl: 'Google-account',
        sv: 'Google-konto',
        vi: 'Tài khoản Google',
        id: 'Akun Google',
      }),
      accountHelp: t({
        ru: 'Подключите Google аккаунт, чтобы открыть список ваших таблиц.',
        en: 'Connect your Google account to browse your spreadsheets.',
        kk: 'Кестелер тізімін ашу үшін Google аккаунтыңызды қосыңыз.',
        de: 'Verbinden Sie Ihr Google-Konto, um Ihre Tabellen zu durchsuchen.',
        fr: 'Connectez votre compte Google pour parcourir vos feuilles de calcul.',
        es: 'Conecta tu cuenta de Google para explorar tus hojas de cálculo.',
        pt: 'Conecte sua conta Google para navegar pelas suas planilhas.',
        tr: 'Elektronik tablolarınıza göz atmak için Google hesabınızı bağlayın.',
        uk: 'Підключіть Google-акаунт, щоб переглянути список таблиць.',
        zh: '连接您的 Google 账户以浏览您的电子表格。',
        ar: 'قم بتوصيل حساب Google للتصفح بين جداول البيانات.',
        pl: 'Połącz konto Google, aby przeglądać swoje arkusze.',
        it: 'Connetti il tuo account Google per sfogliare i tuoi fogli di calcolo.',
        sk: 'Połącz konto Google, aby przeglądać swoje arkusze.',
        ja: 'スプレッドシートを閲覧するためにGoogleアカウントを接続します。',
        ko: '스프레드시트를 탐색하려면 Google 계정을 연결하세요.',
        hi: 'अपनी स्प्रेडशीट ब्राउज़ करने के लिए अपना Google खाता कनेक्ट करें।',
        nl: 'Verbind uw Google-account om uw spreadsheets te bekijken.',
        sv: 'Anslut ditt Google-konto för att bläddra i dina kalkylblad.',
        vi: 'Kết nối tài khoản Google để duyệt các bảng tính của bạn.',
        id: 'Hubungkan akun Google Anda untuk menelusuri spreadsheet.',
      }),
      connectedAs: t({
        ru: 'Подключено как {email}',
        en: 'Connected as {email}',
        kk: '{email} ретінде қосылған',
        de: 'Verbunden als {email}',
        fr: 'Connecté en tant que {email}',
        es: 'Conectado como {email}',
        pt: 'Conectado como {email}',
        tr: '{email} olarak bağlandı',
        uk: 'Підключено як {email}',
        zh: '已连接为 {email}',
        ar: 'متصل بوصفك {email}',
        pl: 'Połączono jako {email}',
        it: 'Connesso come {email}',
        sk: 'Połączono jako {email}',
        ja: '{email} として接続済み',
        ko: '{email}로 연결됨',
        hi: '{email} के रूप में कनेक्टेड',
        nl: 'Verbonden als {email}',
        sv: 'Ansluten som {email}',
        vi: 'Đã kết nối với tư cách {email}',
        id: 'Terhubung sebagai {email}',
      }),
      connectAccountButton: t({
        ru: 'Войти в Google',
        en: 'Sign in with Google',
        kk: 'Google арқылы кіру',
        de: 'Mit Google anmelden',
        fr: 'Se connecter avec Google',
        es: 'Iniciar sesión con Google',
        pt: 'Entrar com Google',
        tr: 'Google ile giriş yap',
        uk: 'Увійти через Google',
        zh: '使用 Google 登录',
        ar: 'تسجيل الدخول بواسطة Google',
        pl: 'Zaloguj się przez Google',
        it: 'Accedi con Google',
        sk: 'Zaloguj się przez Google',
        ja: 'Googleでサインイン',
        ko: 'Google로 로그인',
        hi: 'Google से साइन इन करें',
        nl: 'Inloggen met Google',
        sv: 'Logga in med Google',
        vi: 'Đăng nhập bằng Google',
        id: 'Masuk dengan Google',
      }),
      reconnectButton: t({
        ru: 'Сменить Google аккаунт',
        en: 'Switch Google account',
        kk: 'Google аккаунтын ауыстыру',
        de: 'Google-Konto wechseln',
        fr: 'Changer de compte Google',
        es: 'Cambiar cuenta de Google',
        pt: 'Trocar conta Google',
        tr: 'Google hesabını değiştir',
        uk: 'Змінити Google-акаунт',
        zh: '切换 Google 账户',
        ar: 'تبديل حساب Google',
        pl: 'Zmień konto Google',
        it: 'Cambia account Google',
        sk: 'Zmień konto Google',
        ja: 'Googleアカウントを切り替え',
        ko: 'Google 계정 전환',
        hi: 'Google खाता बदलें',
        nl: 'Google-account wisselen',
        sv: 'Byt Google-konto',
        vi: 'Chuyển đổi tài khoản Google',
        id: 'Ganti akun Google',
      }),
      spreadsheetLabel: t({
        ru: 'Таблица для импорта',
        en: 'Spreadsheet to import',
        kk: 'Импортталатын кесте',
        de: 'Zu importierende Tabelle',
        fr: 'Feuille de calcul à importer',
        es: 'Hoja de cálculo a importar',
        pt: 'Planilha para importar',
        tr: 'İçe aktarılacak elektronik tablo',
        uk: 'Таблиця для імпорту',
        zh: '要导入的电子表格',
        ar: 'جدول البيانات المراد استيراده',
        pl: 'Arkusz do importu',
        it: 'Foglio di calcolo da importare',
        sk: 'Arkusz do importu',
        ja: 'インポートするスプレッドシート',
        ko: '가져올 스프레드시트',
        hi: 'आयात करने के लिए स्प्रेडशीट',
        nl: 'Te importeren spreadsheet',
        sv: 'Kalkylblad att importera',
        vi: 'Bảng tính để nhập',
        id: 'Spreadsheet untuk diimpor',
      }),
      spreadsheetHelp: t({
        ru: 'Откройте Google Picker и выберите нужную таблицу.',
        en: 'Open Google Picker and choose the spreadsheet you need.',
        kk: 'Google Picker ашып, қажетті кестені таңдаңыз.',
        de: 'Öffnen Sie Google Picker und wählen Sie die benötigte Tabelle.',
        fr: 'Ouvrez Google Picker et choisissez la feuille de calcul souhaitée.',
        es: 'Abre Google Picker y elige la hoja de cálculo que necesitas.',
        pt: 'Abra o Google Picker e escolha a planilha necessária.',
        tr: "Google Picker'ı açın ve ihtiyacınız olan elektronik tabloyu seçin.",
        uk: 'Відкрийте Google Picker та виберіть потрібну таблицю.',
        zh: '打开 Google Picker 并选择所需的电子表格。',
        ar: 'افتح Google Picker واختر جدول البيانات الذي تحتاجه.',
        pl: 'Otwórz Google Picker i wybierz potrzebny arkusz.',
        it: 'Apri Google Picker e scegli il foglio di calcolo di cui hai bisogno.',
        sk: 'Otwórz Google Picker i wybierz potrzebny arkusz.',
        ja: 'Google Pickerを開いて必要なスプレッドシートを選択します。',
        ko: 'Google Picker를 열고 필요한 스프레드시트를 선택하세요.',
        hi: 'Google Picker खोलें और आवश्यक स्प्रेडशीट चुनें।',
        nl: 'Open Google Picker en kies de spreadsheet die u nodig heeft.',
        sv: 'Öppna Google Picker och välj det kalkylblad du behöver.',
        vi: 'Mở Google Picker và chọn bảng tính bạn cần.',
        id: 'Buka Google Picker dan pilih spreadsheet yang Anda butuhkan.',
      }),
      chooseSpreadsheetButton: t({
        ru: 'Выбрать таблицу',
        en: 'Choose spreadsheet',
        kk: 'Кестені таңдау',
        de: 'Tabelle auswählen',
        fr: 'Choisir la feuille de calcul',
        es: 'Elegir hoja de cálculo',
        pt: 'Escolher planilha',
        tr: 'Elektronik tablo seç',
        uk: 'Вибрати таблицю',
        zh: '选择电子表格',
        ar: 'اختر جدول البيانات',
        pl: 'Wybierz arkusz',
        it: 'Scegli foglio di calcolo',
        sk: 'Wybierz arkusz',
        ja: 'スプレッドシートを選択',
        ko: '스프레드시트 선택',
        hi: 'स्प्रेडशीट चुनें',
        nl: 'Spreadsheet kiezen',
        sv: 'Välj kalkylblad',
        vi: 'Chọn bảng tính',
        id: 'Pilih spreadsheet',
      }),
      chooseSpreadsheetLoading: t({
        ru: 'Открываем Picker…',
        en: 'Opening Picker…',
        kk: 'Picker ашылуда…',
        de: 'Picker wird geöffnet…',
        fr: 'Ouverture du Picker…',
        es: 'Abriendo Picker…',
        pt: 'Abrindo Picker…',
        tr: 'Picker açılıyor…',
        uk: 'Відкриваємо Picker…',
        zh: '正在打开 Picker…',
        ar: 'جارٍ فتح Picker…',
        pl: 'Otwieranie Picker…',
        it: 'Apertura Picker…',
        sk: 'Otwieranie Picker…',
        ja: 'Pickerを開いています…',
        ko: 'Picker를 여는 중…',
        hi: 'Picker खोला जा रहा है…',
        nl: 'Picker openen…',
        sv: 'Öppnar Picker…',
        vi: 'Đang mở Picker…',
        id: 'Membuka Picker…',
      }),
      openSpreadsheet: t({
        ru: 'Открыть таблицу',
        en: 'Open spreadsheet',
        kk: 'Кестені ашу',
        de: 'Tabelle öffnen',
        fr: 'Ouvrir la feuille de calcul',
        es: 'Abrir hoja de cálculo',
        pt: 'Abrir planilha',
        tr: 'Elektronik tabloyu aç',
        uk: 'Відкрити таблицю',
        zh: '打开电子表格',
        ar: 'افتح جدول البيانات',
        pl: 'Otwórz arkusz',
        it: 'Apri foglio di calcolo',
        sk: 'Otwórz arkusz',
        ja: 'スプレッドシートを開く',
        ko: '스프레드시트 열기',
        hi: 'स्प्रेडशीट खोलें',
        nl: 'Spreadsheet openen',
        sv: 'Öppna kalkylblad',
        vi: 'Mở bảng tính',
        id: 'Buka spreadsheet',
      }),
      nameLabel: t({
        ru: 'Название в системе',
        en: 'Name in system',
        kk: 'Жүйедегі атауы',
        de: 'Name im System',
        fr: 'Nom dans le système',
        es: 'Nombre en el sistema',
        pt: 'Nome no sistema',
        tr: 'Sistemdeki ad',
        uk: 'Назва в системі',
        zh: '系统中的名称',
        ar: 'الاسم في النظام',
        pl: 'Nazwa w systemie',
        it: 'Nome nel sistema',
        sk: 'Nazwa w systemie',
        ja: 'システム内の名前',
        ko: '시스템 내 이름',
        hi: 'सिस्टम में नाम',
        nl: 'Naam in systeem',
        sv: 'Namn i systemet',
        vi: 'Tên trong hệ thống',
        id: 'Nama dalam sistem',
      }),
      namePlaceholder: t({
        ru: 'Например: Выписки Казахстан',
        en: 'e.g. KZ statements',
        kk: 'Мысалы: Қазақстан үзінділері',
        de: 'z. B. KZ-Kontoauszüge',
        fr: 'ex. : Relevés KZ',
        es: 'p. ej. extractos KZ',
        pt: 'ex.: extratos KZ',
        tr: 'örn. KZ ekstreleri',
        uk: 'Наприклад: Виписки Казахстан',
        zh: '例如：KZ 账单',
        ar: 'مثال: كشوفات KZ',
        pl: 'np. wyciągi KZ',
        it: 'es. estratti KZ',
        sk: 'np. wyciągi KZ',
        ja: '例：KZ 明細',
        ko: '예: KZ 명세서',
        hi: 'उदा. KZ स्टेटमेंट',
        nl: 'bijv. KZ-overzichten',
        sv: 't.ex. KZ-kontoutdrag',
        vi: 'ví dụ: sao kê KZ',
        id: 'mis. laporan KZ',
      }),
      nameHelp: t({
        ru: 'Если оставить пустым — используем название из Google Sheets.',
        en: 'If empty, we will use the name from Google Sheets.',
        kk: 'Бос қалдырсаңыз — Google Sheets атауы қолданылады.',
        de: 'Wenn leer, verwenden wir den Namen aus Google Sheets.',
        fr: 'Si vide, nous utiliserons le nom de Google Sheets.',
        es: 'Si está vacío, usaremos el nombre de Google Sheets.',
        pt: 'Se vazio, usaremos o nome do Google Sheets.',
        tr: "Boş bırakırsanız Google Sheets'teki adı kullanırız.",
        uk: 'Якщо порожнє — використаємо назву з Google Sheets.',
        zh: '如果为空，我们将使用 Google Sheets 中的名称。',
        ar: 'إذا تُرك فارغًا، سنستخدم الاسم من Google Sheets.',
        pl: 'Jeśli puste, użyjemy nazwy z Google Sheets.',
        it: 'Se vuoto, useremo il nome da Google Sheets.',
        sk: 'Jeśli puste, użyjemy nazwy z Google Sheets.',
        ja: '空の場合、Google Sheetsの名前を使用します。',
        ko: '비어 있으면 Google Sheets의 이름을 사용합니다.',
        hi: 'यदि खाली है, तो हम Google Sheets का नाम उपयोग करेंगे।',
        nl: 'Als leeg, gebruiken we de naam uit Google Sheets.',
        sv: 'Om tom, använder vi namnet från Google Sheets.',
        vi: 'Nếu để trống, chúng tôi sẽ dùng tên từ Google Sheets.',
        id: 'Jika kosong, kami akan menggunakan nama dari Google Sheets.',
      }),
      worksheetLabel: t({
        ru: 'Лист',
        en: 'Worksheet',
        kk: 'Парақ',
        de: 'Blatt',
        fr: 'Feuille',
        es: 'Hoja',
        pt: 'Planilha',
        tr: 'Sayfa',
        uk: 'Аркуш',
        zh: '工作表',
        ar: 'ورقة العمل',
        pl: 'Arkusz',
        it: 'Foglio',
        sk: 'Arkusz',
        ja: 'ワークシート',
        ko: '워크시트',
        hi: 'वर्कशीट',
        nl: 'Werkblad',
        sv: 'Arbetsblad',
        vi: 'Trang tính',
        id: 'Lembar kerja',
      }),
      selectWorksheet: t({
        ru: 'Выберите лист',
        en: 'Choose worksheet',
        kk: 'Парақты таңдаңыз',
        de: 'Blatt auswählen',
        fr: 'Choisir une feuille',
        es: 'Elegir hoja',
        pt: 'Escolher planilha',
        tr: 'Sayfa seç',
        uk: 'Виберіть аркуш',
        zh: '选择工作表',
        ar: 'اختر ورقة العمل',
        pl: 'Wybierz arkusz',
        it: 'Scegli foglio',
        sk: 'Wybierz arkusz',
        ja: 'ワークシートを選択',
        ko: '워크시트 선택',
        hi: 'वर्कशीट चुनें',
        nl: 'Werkblad kiezen',
        sv: 'Välj arbetsblad',
        vi: 'Chọn trang tính',
        id: 'Pilih lembar kerja',
      }),
      loadingWorksheets: t({
        ru: 'Загружаем листы…',
        en: 'Loading worksheets…',
        kk: 'Парақтар жүктелуде…',
        de: 'Blätter werden geladen…',
        fr: 'Chargement des feuilles…',
        es: 'Cargando hojas…',
        pt: 'Carregando planilhas…',
        tr: 'Sayfalar yükleniyor…',
        uk: 'Завантажуємо аркуші…',
        zh: '正在加载工作表…',
        ar: 'جارٍ تحميل الأوراق…',
        pl: 'Ładowanie arkuszy…',
        it: 'Caricamento fogli…',
        sk: 'Ładowanie arkuszy…',
        ja: 'ワークシートを読み込んでいます…',
        ko: '워크시트 로딩 중…',
        hi: 'वर्कशीट लोड हो रही हैं…',
        nl: 'Werkbladen laden…',
        sv: 'Laddar arbetsblad…',
        vi: 'Đang tải trang tính…',
        id: 'Memuat lembar kerja…',
      }),
      connectButton: t({
        ru: 'Импортировать из таблицы',
        en: 'Import from spreadsheet',
        kk: 'Кестеден импорттау',
        de: 'Aus Tabelle importieren',
        fr: 'Importer depuis la feuille de calcul',
        es: 'Importar desde la hoja de cálculo',
        pt: 'Importar da planilha',
        tr: 'Elektronik tablodan içe aktar',
        uk: 'Імпортувати з таблиці',
        zh: '从电子表格导入',
        ar: 'استيراد من جدول البيانات',
        pl: 'Importuj z arkusza',
        it: 'Importa dal foglio di calcolo',
        sk: 'Importuj z arkusza',
        ja: 'スプレッドシートからインポート',
        ko: '스프레드시트에서 가져오기',
        hi: 'स्प्रेडशीट से आयात करें',
        nl: 'Importeren uit spreadsheet',
        sv: 'Importera från kalkylblad',
        vi: 'Nhập từ bảng tính',
        id: 'Impor dari spreadsheet',
      }),
      successText: t({
        ru: 'После выбора таблицы Lumio сохранит подключение и сможет использовать лист для импорта и дальнейшей синхронизации.',
        en: 'After selection, Lumio saves the connection and can use the worksheet for import and future sync.',
        kk: 'Таңдаудан кейін Lumio қосылымды сақтап, парақты импорт пен кейінгі синхрон үшін қолдана алады.',
        de: 'Nach der Auswahl speichert Lumio die Verbindung und kann das Blatt für Import und zukünftige Synchronisierung verwenden.',
        fr: "Après la sélection, Lumio enregistre la connexion et peut utiliser la feuille pour l'import et la synchronisation future.",
        es: 'Tras la selección, Lumio guarda la conexión y puede usar la hoja para importar y sincronizar en el futuro.',
        pt: 'Após a seleção, o Lumio salva a conexão e pode usar a planilha para importação e sincronização futura.',
        tr: 'Seçimden sonra Lumio bağlantıyı kaydeder ve sayfayı içe aktarma ve gelecekteki senkronizasyon için kullanabilir.',
        uk: 'Після вибору Lumio збереже підключення і зможе використовувати аркуш для імпорту та подальшої синхронізації.',
        zh: '选择后，Lumio 保存连接，可将工作表用于导入和未来的同步。',
        ar: 'بعد الاختيار، يحفظ Lumio الاتصال ويمكنه استخدام ورقة العمل للاستيراد والمزامنة المستقبلية.',
        pl: 'Po wyborze Lumio zapisuje połączenie i może używać arkusza do importu i przyszłej synchronizacji.',
        it: "Dopo la selezione, Lumio salva la connessione e può usare il foglio per l'importazione e la sincronizzazione futura.",
        sk: 'Po wyborze Lumio zapisuje połączenie i może używać arkusza do importu i przyszłej synchronizacji.',
        ja: '選択後、Lumioは接続を保存し、インポートと将来の同期にワークシートを使用できます。',
        ko: '선택 후 Lumio는 연결을 저장하고 가져오기 및 향후 동기화에 워크시트를 사용할 수 있습니다.',
        hi: 'चयन के बाद, Lumio कनेक्शन सहेजता है और आयात तथा भविष्य की सिंक के लिए वर्कशीट का उपयोग कर सकता है।',
        nl: 'Na selectie slaat Lumio de verbinding op en kan het werkblad gebruiken voor import en toekomstige synchronisatie.',
        sv: 'Efter val sparar Lumio anslutningen och kan använda arbetsbladet för import och framtida synkronisering.',
        vi: 'Sau khi chọn, Lumio lưu kết nối và có thể sử dụng trang tính để nhập và đồng bộ trong tương lai.',
        id: 'Setelah pemilihan, Lumio menyimpan koneksi dan dapat menggunakan lembar kerja untuk impor dan sinkronisasi mendatang.',
      }),
    },
    step2: {
      label: t({
        ru: 'Шаг 2 (Advanced setup)',
        en: 'Step 2 (Advanced setup)',
        kk: '2-қадам (Қосымша баптау)',
        de: 'Schritt 2 (Erweiterte Einrichtung)',
        fr: 'Étape 2 (Configuration avancée)',
        es: 'Paso 2 (Configuración avanzada)',
        pt: 'Etapa 2 (Configuração avançada)',
        tr: 'Adım 2 (Gelişmiş kurulum)',
        uk: 'Крок 2 (Розширені налаштування)',
        zh: '第 2 步（高级设置）',
        ar: 'الخطوة 2 (الإعداد المتقدم)',
        pl: 'Krok 2 (Zaawansowana konfiguracja)',
        it: 'Passaggio 2 (Configurazione avanzata)',
        sk: 'Krok 2 (Zaawansowana konfiguracja)',
        ja: 'ステップ 2（高度な設定）',
        ko: '단계 2 (고급 설정)',
        hi: 'चरण 2 (उन्नत सेटअप)',
        nl: 'Stap 2 (Geavanceerde instelling)',
        sv: 'Steg 2 (Avancerad inställning)',
        vi: 'Bước 2 (Cài đặt nâng cao)',
        id: 'Langkah 2 (Pengaturan lanjutan)',
      }),
      title: t({
        ru: 'Автообновление из Google Sheets (опционально)',
        en: 'Enable automatic updates from Google Sheets (optional)',
        kk: 'Google Sheets-тен авто жаңарту (міндетті емес)',
        de: 'Automatische Updates aus Google Sheets aktivieren (optional)',
        fr: 'Activer les mises à jour automatiques depuis Google Sheets (optionnel)',
        es: 'Habilitar actualizaciones automáticas desde Google Sheets (opcional)',
        pt: 'Habilitar atualizações automáticas do Google Sheets (opcional)',
        tr: "Google Sheets'ten otomatik güncellemeleri etkinleştir (isteğe bağlı)",
        uk: "Автооновлення з Google Sheets (необов'язково)",
        zh: '启用来自 Google Sheets 的自动更新（可选）',
        ar: 'تفعيل التحديثات التلقائية من Google Sheets (اختياري)',
        pl: 'Włącz automatyczne aktualizacje z Google Sheets (opcjonalnie)',
        it: 'Abilita aggiornamenti automatici da Google Sheets (opzionale)',
        sk: 'Włącz automatyczne aktualizacje z Google Sheets (opcjonalnie)',
        ja: 'Google Sheetsからの自動更新を有効にする（オプション）',
        ko: 'Google Sheets에서 자동 업데이트 활성화 (선택 사항)',
        hi: 'Google Sheets से स्वचालित अपडेट सक्षम करें (वैकल्पिक)',
        nl: 'Automatische updates van Google Sheets inschakelen (optioneel)',
        sv: 'Aktivera automatiska uppdateringar från Google Sheets (valfritt)',
        vi: 'Bật cập nhật tự động từ Google Sheets (tùy chọn)',
        id: 'Aktifkan pembaruan otomatis dari Google Sheets (opsional)',
      }),
      description: t({
        ru: 'Скопируйте скрипт из нашей инструкции и поставьте триггер onEdit, чтобы отправлять изменения по вебхуку.',
        en: 'Copy the script from our guide and set an onEdit trigger to send changes via webhook.',
        kk: 'Нұсқаулықтағы скриптті көшіріп, өзгерістерді вебхук арқылы жіберу үшін onEdit триггерін орнатыңыз.',
        de: 'Kopieren Sie das Skript aus unserem Leitfaden und setzen Sie einen onEdit-Trigger, um Änderungen per Webhook zu senden.',
        fr: 'Copiez le script de notre guide et définissez un déclencheur onEdit pour envoyer les modifications via webhook.',
        es: 'Copia el script de nuestra guía y configura un trigger onEdit para enviar cambios por webhook.',
        pt: 'Copie o script do nosso guia e defina um gatilho onEdit para enviar alterações via webhook.',
        tr: 'Kılavuzumuzdaki komut dosyasını kopyalayın ve webhook aracılığıyla değişiklikleri göndermek için bir onEdit tetikleyicisi ayarlayın.',
        uk: 'Скопіюйте скрипт з нашої інструкції та встановіть тригер onEdit для надсилання змін через вебхук.',
        zh: '从我们的指南中复制脚本，并设置 onEdit 触发器通过 Webhook 发送更改。',
        ar: 'انسخ النص البرمجي من دليلنا واضبط مشغّل onEdit لإرسال التغييرات عبر webhook.',
        pl: 'Skopiuj skrypt z naszego przewodnika i ustaw wyzwalacz onEdit, aby wysyłać zmiany przez webhook.',
        it: 'Copia lo script dalla nostra guida e imposta un trigger onEdit per inviare le modifiche tramite webhook.',
        sk: 'Skopiuj skrypt z naszego przewodnika i ustaw wyzwalacz onEdit, aby wysyłać zmiany przez webhook.',
        ja: 'ガイドからスクリプトをコピーし、onEditトリガーを設定してWebhook経由で変更を送信します。',
        ko: '가이드에서 스크립트를 복사하고 onEdit 트리거를 설정하여 웹훅으로 변경 사항을 전송하세요.',
        hi: 'हमारे गाइड से स्क्रिप्ट कॉपी करें और webhook के माध्यम से परिवर्तन भेजने के लिए onEdit ट्रिगर सेट करें।',
        nl: 'Kopieer het script uit onze gids en stel een onEdit-trigger in om wijzigingen via webhook te sturen.',
        sv: 'Kopiera skriptet från vår guide och ställ in en onEdit-trigger för att skicka ändringar via webhook.',
        vi: 'Sao chép script từ hướng dẫn và đặt trigger onEdit để gửi thay đổi qua webhook.',
        id: 'Salin skrip dari panduan kami dan atur trigger onEdit untuk mengirim perubahan melalui webhook.',
      }),
      appsScriptDoc: t({
        ru: 'Инструкция по Apps Script',
        en: 'Apps Script guide',
        kk: 'Apps Script нұсқаулығы',
        de: 'Apps Script-Anleitung',
        fr: 'Guide Apps Script',
        es: 'Guía de Apps Script',
        pt: 'Guia de Apps Script',
        tr: 'Apps Script kılavuzu',
        uk: 'Інструкція з Apps Script',
        zh: 'Apps Script 指南',
        ar: 'دليل Apps Script',
        pl: 'Przewodnik Apps Script',
        it: 'Guida Apps Script',
        sk: 'Przewodnik Apps Script',
        ja: 'Apps Scriptガイド',
        ko: 'Apps Script 가이드',
        hi: 'Apps Script गाइड',
        nl: 'Apps Script-gids',
        sv: 'Apps Script-guide',
        vi: 'Hướng dẫn Apps Script',
        id: 'Panduan Apps Script',
      }),
      openSheets: t({
        ru: 'Открыть Google Sheets',
        en: 'Open Google Sheets',
        kk: 'Google Sheets ашу',
        de: 'Google Sheets öffnen',
        fr: 'Ouvrir Google Sheets',
        es: 'Abrir Google Sheets',
        pt: 'Abrir Google Sheets',
        tr: "Google Sheets'i aç",
        uk: 'Відкрити Google Sheets',
        zh: '打开 Google Sheets',
        ar: 'فتح Google Sheets',
        pl: 'Otwórz Google Sheets',
        it: 'Apri Google Sheets',
        sk: 'Otwórz Google Sheets',
        ja: 'Google Sheetsを開く',
        ko: 'Google Sheets 열기',
        hi: 'Google Sheets खोलें',
        nl: 'Google Sheets openen',
        sv: 'Öppna Google Sheets',
        vi: 'Mở Google Sheets',
        id: 'Buka Google Sheets',
      }),
      webhookEndpointLabel: t({
        ru: 'Эндпоинт вебхука',
        en: 'Webhook endpoint',
        kk: 'Вебхук эндпоинты',
        de: 'Webhook-Endpunkt',
        fr: 'Point de terminaison webhook',
        es: 'Endpoint de webhook',
        pt: 'Endpoint de webhook',
        tr: 'Webhook uç noktası',
        uk: 'Endpoint вебхука',
        zh: 'Webhook 端点',
        ar: 'نقطة نهاية webhook',
        pl: 'Punkt końcowy webhook',
        it: 'Endpoint webhook',
        sk: 'Punkt końcowy webhook',
        ja: 'Webhookエンドポイント',
        ko: 'Webhook 엔드포인트',
        hi: 'Webhook एंडपॉइंट',
        nl: 'Webhook-eindpunt',
        sv: 'Webhook-slutpunkt',
        vi: 'Điểm cuối webhook',
        id: 'Endpoint webhook',
      }),
      webhookHeaderLabel: t({
        ru: 'Заголовок',
        en: 'Header',
        kk: 'Тақырыпша',
        de: 'Kopfzeile',
        fr: 'En-tête',
        es: 'Encabezado',
        pt: 'Cabeçalho',
        tr: 'Başlık',
        uk: 'Заголовок',
        zh: '请求头',
        ar: 'الترويسة',
        pl: 'Nagłówek',
        it: 'Intestazione',
        sk: 'Nagłówek',
        ja: 'ヘッダー',
        ko: '헤더',
        hi: 'हेडर',
        nl: 'Koptekst',
        sv: 'Rubrik',
        vi: 'Tiêu đề',
        id: 'Tajuk',
      }),
      webhookTokenHint: t({
        ru: 'ваш токен',
        en: 'your token',
        kk: 'сіздің токеніңіз',
        de: 'Ihr Token',
        fr: 'votre jeton',
        es: 'tu token',
        pt: 'seu token',
        tr: 'tokenınız',
        uk: 'ваш токен',
        zh: '您的令牌',
        ar: 'رمزك المميز',
        pl: 'twój token',
        it: 'il tuo token',
        sk: 'twój token',
        ja: 'あなたのトークン',
        ko: '당신의 토큰',
        hi: 'आपका टोकन',
        nl: 'uw token',
        sv: 'din token',
        vi: 'token của bạn',
        id: 'token Anda',
      }),
      showTechnicalDetails: t({
        ru: 'Показать технические детали',
        en: 'Show technical details',
        kk: 'Техникалық бөлшектерді көрсету',
        de: 'Technische Details anzeigen',
        fr: 'Afficher les détails techniques',
        es: 'Mostrar detalles técnicos',
        pt: 'Mostrar detalhes técnicos',
        tr: 'Teknik detayları göster',
        uk: 'Показати технічні деталі',
        zh: '显示技术详情',
        ar: 'عرض التفاصيل التقنية',
        pl: 'Pokaż szczegóły techniczne',
        it: 'Mostra dettagli tecnici',
        sk: 'Pokaż szczegóły techniczne',
        ja: '技術的な詳細を表示',
        ko: '기술 세부 정보 표시',
        hi: 'तकनीकी विवरण दिखाएं',
        nl: 'Technische details weergeven',
        sv: 'Visa tekniska detaljer',
        vi: 'Hiển thị chi tiết kỹ thuật',
        id: 'Tampilkan detail teknis',
      }),
    },
    list: {
      title: t({
        ru: 'Подключённые таблицы',
        en: 'Connected sheets',
        kk: 'Қосылған кестелер',
        de: 'Verbundene Tabellen',
        fr: 'Feuilles connectées',
        es: 'Hojas conectadas',
        pt: 'Planilhas conectadas',
        tr: 'Bağlı tablolar',
        uk: 'Підключені таблиці',
        zh: '已连接的表格',
        ar: 'الجداول المتصلة',
        pl: 'Połączone arkusze',
        it: 'Fogli connessi',
        sk: 'Połączone arkusze',
        ja: '接続済みシート',
        ko: '연결된 시트',
        hi: 'कनेक्टेड शीट',
        nl: 'Verbonden sheets',
        sv: 'Anslutna ark',
        vi: 'Trang tính đã kết nối',
        id: 'Lembar yang terhubung',
      }),
      subtitle: t({
        ru: 'Автообновление по вебхуку',
        en: 'Auto updates via webhook',
        kk: 'Вебхук арқылы авто жаңарту',
        de: 'Automatische Updates per Webhook',
        fr: 'Mises à jour automatiques via webhook',
        es: 'Actualizaciones automáticas por webhook',
        pt: 'Atualizações automáticas via webhook',
        tr: 'Webhook aracılığıyla otomatik güncellemeler',
        uk: 'Автооновлення через вебхук',
        zh: '通过 Webhook 自动更新',
        ar: 'تحديثات تلقائية عبر webhook',
        pl: 'Automatyczne aktualizacje przez webhook',
        it: 'Aggiornamenti automatici tramite webhook',
        sk: 'Automatyczne aktualizacje przez webhook',
        ja: 'Webhook経由の自動更新',
        ko: 'webhook을 통한 자동 업데이트',
        hi: 'webhook के माध्यम से स्वचालित अपडेट',
        nl: 'Automatische updates via webhook',
        sv: 'Automatiska uppdateringar via webhook',
        vi: 'Cập nhật tự động qua webhook',
        id: 'Pembaruan otomatis melalui webhook',
      }),
      empty: t({
        ru: 'Пока нет подключений. Добавьте первую таблицу через форму слева.',
        en: 'No connections yet. Add your first sheet using the form on the left.',
        kk: 'Әзірше қосылымдар жоқ. Сол жақтағы форма арқылы бірінші кестені қосыңыз.',
        de: 'Noch keine Verbindungen. Fügen Sie Ihre erste Tabelle über das Formular links hinzu.',
        fr: "Aucune connexion pour l'instant. Ajoutez votre première feuille via le formulaire à gauche.",
        es: 'Aún no hay conexiones. Agrega tu primera hoja usando el formulario de la izquierda.',
        pt: 'Nenhuma conexão ainda. Adicione sua primeira planilha usando o formulário à esquerda.',
        tr: 'Henüz bağlantı yok. Sol taraftaki formu kullanarak ilk tablonuzu ekleyin.',
        uk: 'Поки немає підключень. Додайте першу таблицю через форму зліва.',
        zh: '暂无连接。使用左侧的表单添加您的第一个表格。',
        ar: 'لا توجد اتصالات حتى الآن. أضف أول جدول باستخدام النموذج على اليسار.',
        pl: 'Brak połączeń. Dodaj pierwszy arkusz używając formularza po lewej.',
        it: 'Nessuna connessione ancora. Aggiungi il tuo primo foglio usando il modulo a sinistra.',
        sk: 'Brak połączeń. Dodaj pierwszy arkusz używając formularza po lewej.',
        ja: 'まだ接続がありません。左のフォームを使って最初のシートを追加してください。',
        ko: '아직 연결이 없습니다. 왼쪽 양식을 사용하여 첫 번째 시트를 추가하세요.',
        hi: 'अभी तक कोई कनेक्शन नहीं। बाईं ओर के फ़ॉर्म का उपयोग करके अपनी पहली शीट जोड़ें।',
        nl: 'Nog geen verbindingen. Voeg uw eerste sheet toe met het formulier aan de linkerkant.',
        sv: 'Inga anslutningar ännu. Lägg till ditt första ark med formuläret till vänster.',
        vi: 'Chưa có kết nối nào. Thêm trang tính đầu tiên bằng biểu mẫu ở bên trái.',
        id: 'Belum ada koneksi. Tambahkan lembar pertama Anda menggunakan formulir di sebelah kiri.',
      }),
      badges: {
        oauthNeeded: t({
          ru: 'Нужен OAuth',
          en: 'OAuth needed',
          kk: 'OAuth қажет',
          de: 'OAuth erforderlich',
          fr: 'OAuth requis',
          es: 'Se necesita OAuth',
          pt: 'OAuth necessário',
          tr: 'OAuth gerekli',
          uk: 'Потрібен OAuth',
          zh: '需要 OAuth',
          ar: 'OAuth مطلوب',
          pl: 'Wymagany OAuth',
          it: 'OAuth richiesto',
          sk: 'Wymagany OAuth',
          ja: 'OAuth が必要',
          ko: 'OAuth 필요',
          hi: 'OAuth आवश्यक',
          nl: 'OAuth vereist',
          sv: 'OAuth krävs',
          vi: 'Cần OAuth',
          id: 'OAuth diperlukan',
        }),
        active: t({
          ru: 'Активно',
          en: 'Active',
          kk: 'Белсенді',
          de: 'Aktiv',
          fr: 'Actif',
          es: 'Activo',
          pt: 'Ativo',
          tr: 'Aktif',
          uk: 'Активно',
          zh: '活跃',
          ar: 'نشط',
          pl: 'Aktywne',
          it: 'Attivo',
          sk: 'Aktywne',
          ja: 'アクティブ',
          ko: '활성',
          hi: 'सक्रिय',
          nl: 'Actief',
          sv: 'Aktiv',
          vi: 'Hoạt động',
          id: 'Aktif',
        }),
      },
      fields: {
        idPrefix: t({
          ru: 'ID',
          en: 'ID',
          kk: 'ID',
          de: 'ID',
          fr: 'ID',
          es: 'ID',
          pt: 'ID',
          tr: 'ID',
          uk: 'ID',
          zh: 'ID',
          ar: 'المعرّف',
          pl: 'ID',
          it: 'ID',
          sk: 'ID',
          ja: 'ID',
          ko: 'ID',
          hi: 'ID',
          nl: 'ID',
          sv: 'ID',
          vi: 'ID',
          id: 'ID',
        }),
        worksheetPrefix: t({
          ru: 'Лист',
          en: 'Sheet',
          kk: 'Парақ',
          de: 'Blatt',
          fr: 'Feuille',
          es: 'Hoja',
          pt: 'Planilha',
          tr: 'Sayfa',
          uk: 'Аркуш',
          zh: '工作表',
          ar: 'الورقة',
          pl: 'Arkusz',
          it: 'Foglio',
          sk: 'Arkusz',
          ja: 'シート',
          ko: '시트',
          hi: 'शीट',
          nl: 'Blad',
          sv: 'Blad',
          vi: 'Trang tính',
          id: 'Lembar',
        }),
        lastSyncPrefix: t({
          ru: 'Последняя синхронизация',
          en: 'Last sync',
          kk: 'Соңғы синхрондау',
          de: 'Letzte Synchronisierung',
          fr: 'Dernière synchronisation',
          es: 'Última sincronización',
          pt: 'Última sincronização',
          tr: 'Son senkronizasyon',
          uk: 'Остання синхронізація',
          zh: '最后同步',
          ar: 'آخر مزامنة',
          pl: 'Ostatnia synchronizacja',
          it: 'Ultima sincronizzazione',
          sk: 'Ostatnia synchronizacja',
          ja: '最終同期',
          ko: '마지막 동기화',
          hi: 'अंतिम सिंक',
          nl: 'Laatste synchronisatie',
          sv: 'Senaste synkronisering',
          vi: 'Đồng bộ lần cuối',
          id: 'Sinkronisasi terakhir',
        }),
      },
      actions: {
        authorize: t({
          ru: 'Авторизовать',
          en: 'Authorize',
          kk: 'Авторизация',
          de: 'Autorisieren',
          fr: 'Autoriser',
          es: 'Autorizar',
          pt: 'Autorizar',
          tr: 'Yetkilendir',
          uk: 'Авторизувати',
          zh: '授权',
          ar: 'تفويض',
          pl: 'Autoryzuj',
          it: 'Autorizza',
          sk: 'Autoryzuj',
          ja: '認証する',
          ko: '인증하기',
          hi: 'प्राधिकृत करें',
          nl: 'Autoriseren',
          sv: 'Auktorisera',
          vi: 'Xác thực',
          id: 'Otorisasi',
        }),
        sync: t({
          ru: 'Синхронизировать',
          en: 'Sync',
          kk: 'Синхрондау',
          de: 'Synchronisieren',
          fr: 'Synchroniser',
          es: 'Sincronizar',
          pt: 'Sincronizar',
          tr: 'Senkronize et',
          uk: 'Синхронізувати',
          zh: '同步',
          ar: 'مزامنة',
          pl: 'Synchronizuj',
          it: 'Sincronizza',
          sk: 'Synchronizuj',
          ja: '同期する',
          ko: '동기화',
          hi: 'सिंक करें',
          nl: 'Synchroniseren',
          sv: 'Synkronisera',
          vi: 'Đồng bộ',
          id: 'Sinkronkan',
        }),
        disconnect: t({
          ru: 'Отключить',
          en: 'Disconnect',
          kk: 'Ажырату',
          de: 'Trennen',
          fr: 'Déconnecter',
          es: 'Desconectar',
          pt: 'Desconectar',
          tr: 'Bağlantıyı kes',
          uk: 'Відключити',
          zh: '断开连接',
          ar: 'قطع الاتصال',
          pl: 'Rozłącz',
          it: 'Disconnetti',
          sk: 'Rozłącz',
          ja: '切断',
          ko: '연결 해제',
          hi: 'डिस्कनेक्ट करें',
          nl: 'Verbreken',
          sv: 'Koppla från',
          vi: 'Ngắt kết nối',
          id: 'Putuskan',
        }),
      },
      dash: t({
        ru: '—',
        en: '—',
        kk: '—',
        de: '—',
        fr: '—',
        es: '—',
        pt: '—',
        tr: '—',
        uk: '—',
        zh: '—',
        ar: '—',
        pl: '—',
        it: '—',
        sk: '—',
        ja: '—',
        ko: '—',
        hi: '—',
        nl: '—',
        sv: '—',
        vi: '—',
        id: '—',
      }),
    },
  },
} satisfies Dictionary;

export default content;
