import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'budgetSummaryWidget',
  content: {
    title: t({
      ru: 'Бюджеты',
      en: 'Budgets',
      kk: 'Бюджеттер',
      de: 'Budgets',
      fr: 'Budgets',
      es: 'Presupuestos',
      pt: 'Orçamentos',
      tr: 'Bütçeler',
      uk: 'Бюджети',
      zh: '预算',
      ar: 'الميزانيات',
      pl: 'Budżety',
      it: 'Budget',
      sk: 'Rozpočty',
      ja: '予算',
      ko: '예산',
      hi: 'बजट',
      nl: 'Budgetten',
      sv: 'Budgetar',
      vi: 'Ngân sách',
      id: 'Anggaran',
    }),
    emptyDescription: t({
      ru: 'Настройте бюджеты, чтобы отслеживать расходы по категориям.',
      en: 'Set up budgets to track spending by category.',
      kk: 'Санаттар бойынша шығынды бақылау үшін бюджет орнатыңыз.',
      de: 'Richten Sie Budgets ein, um Ausgaben nach Kategorie zu verfolgen.',
      fr: 'Configurez des budgets pour suivre les dépenses par catégorie.',
      es: 'Configure presupuestos para hacer seguimiento del gasto por categoría.',
      pt: 'Configure orçamentos para acompanhar os gastos por categoria.',
      tr: 'Kategoriye göre harcamaları izlemek için bütçe oluşturun.',
      uk: 'Налаштуйте бюджети, щоб відстежувати витрати за категоріями.',
      zh: '设置预算以按类别跟踪支出。',
      ar: 'أنشئ ميزانيات لتتبع الإنفاق حسب الفئة.',
      pl: 'Skonfiguruj budżety, aby śledzić wydatki według kategorii.',
      it: 'Configura i budget per monitorare la spesa per categoria.',
      sk: 'Nastavte rozpočty na sledovanie výdavkov podľa kategórií.',
      ja: 'カテゴリ別に支出を追跡するために予算を設定しましょう。',
      ko: '카테고리별 지출을 추적하려면 예산을 설정하세요.',
      hi: 'श्रेणी के अनुसार खर्च ट्रैक करने के लिए बजट सेट करें।',
      nl: 'Stel budgetten in om uitgaven per categorie te volgen.',
      sv: 'Skapa budgetar för att följa utgifter per kategori.',
      vi: 'Thiết lập ngân sách để theo dõi chi tiêu theo danh mục.',
      id: 'Siapkan anggaran untuk melacak pengeluaran per kategori.',
    }),
    setUpBudgets: t({
      ru: 'Настроить бюджеты',
      en: 'Set up budgets',
      kk: 'Бюджетті орнату',
      de: 'Budgets einrichten',
      fr: 'Configurer les budgets',
      es: 'Configurar presupuestos',
      pt: 'Configurar orçamentos',
      tr: 'Bütçe oluştur',
      uk: 'Налаштувати бюджети',
      zh: '设置预算',
      ar: 'إعداد الميزانيات',
      pl: 'Skonfiguruj budżety',
      it: 'Configura i budget',
      sk: 'Nastaviť rozpočty',
      ja: '予算を設定',
      ko: '예산 설정',
      hi: 'बजट सेट करें',
      nl: 'Budgetten instellen',
      sv: 'Skapa budgetar',
      vi: 'Thiết lập ngân sách',
      id: 'Siapkan anggaran',
    }),
    viewAll: t({
      ru: 'Все бюджеты',
      en: 'View all',
      kk: 'Барлығын көру',
      de: 'Alle anzeigen',
      fr: 'Tout afficher',
      es: 'Ver todos',
      pt: 'Ver todos',
      tr: 'Tümünü görüntüle',
      uk: 'Переглянути всі',
      zh: '查看全部',
      ar: 'عرض الكل',
      pl: 'Zobacz wszystkie',
      it: 'Vedi tutti',
      sk: 'Zobraziť všetky',
      ja: 'すべて表示',
      ko: '전체 보기',
      hi: 'सभी देखें',
      nl: 'Alles bekijken',
      sv: 'Visa alla',
      vi: 'Xem tất cả',
      id: 'Lihat semua',
    }),
  },
} satisfies Dictionary;

export default content;
