import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'ledgerPage',
  content: {
    title: t({
      ru: 'Бухгалтерский реестр',
      en: 'Ledger',
      kk: 'Бухгалтерлік тізілім',
      de: 'Hauptbuch',
      fr: 'Grand livre',
      es: 'Libro mayor',
      pt: 'Livro-razão',
      tr: 'Defteri kebir',
      uk: 'Бухгалтерський реєстр',
      zh: '总账',
      ar: 'دفتر الأستاذ',
      pl: 'Księga główna',
      it: 'Libro mastro',
      sk: 'Hlavná kniha',
      ja: '総勘定元帳',
      ko: '총계정원장',
      hi: 'खाता बही',
      nl: 'Grootboek',
      sv: 'Huvudbok',
      vi: 'Sổ cái',
      id: 'Buku besar',
    }),
    subtitle: t({
      ru: 'Двойная запись по вашим выпискам и ручным проводкам',
      en: 'Double-entry books built from your statements and manual entries',
      kk: 'Үзінділер мен қолмен енгізілген жазбалар бойынша қос жазба',
      de: 'Doppelte Buchführung aus Ihren Kontoauszügen und manuellen Buchungen',
      fr: 'Comptabilité en partie double issue de vos relevés et écritures manuelles',
      es: 'Contabilidad por partida doble a partir de tus extractos y asientos manuales',
      pt: 'Contabilidade por partidas dobradas a partir dos seus extratos e lançamentos manuais',
      tr: 'Hesap özetlerinizden ve manuel kayıtlardan çift taraflı defter',
      uk: 'Подвійний запис за вашими виписками та ручними проводками',
      zh: '基于对账单和手工分录的复式记账',
      ar: 'قيد مزدوج مبني على كشوفك وقيودك اليدوية',
      pl: 'Podwójny zapis na podstawie wyciągów i ręcznych księgowań',
      it: 'Partita doppia costruita da estratti conto e scritture manuali',
      sk: 'Podvojné účtovníctvo z výpisov a ručných zápisov',
      ja: '明細書と手動仕訳から作成される複式簿記',
      ko: '명세서와 수동 분개로 만든 복식부기',
      hi: 'आपके विवरणों और मैनुअल प्रविष्टियों से बनी दोहरी प्रविष्टि',
      nl: 'Dubbel boekhouden op basis van uw afschriften en handmatige boekingen',
      sv: 'Dubbel bokföring utifrån dina kontoutdrag och manuella verifikationer',
      vi: 'Sổ kế toán kép từ sao kê và bút toán thủ công của bạn',
      id: 'Pembukuan berpasangan dari rekening koran dan jurnal manual Anda',
    }),
    tabAccounts: t({
      ru: 'План счетов',
      en: 'Chart of accounts',
      kk: 'Шоттар жоспары',
      de: 'Kontenplan',
      fr: 'Plan comptable',
      es: 'Plan de cuentas',
      pt: 'Plano de contas',
      tr: 'Hesap planı',
      uk: 'План рахунків',
      zh: '会计科目表',
      ar: 'دليل الحسابات',
      pl: 'Plan kont',
      it: 'Piano dei conti',
      sk: 'Účtový rozvrh',
      ja: '勘定科目表',
      ko: '계정과목표',
      hi: 'खातों का चार्ट',
      nl: 'Rekeningschema',
      sv: 'Kontoplan',
      vi: 'Hệ thống tài khoản',
      id: 'Bagan akun',
    }),
    tabJournal: t({
      ru: 'Журнал',
      en: 'Journal',
      kk: 'Журнал',
      de: 'Journal',
      fr: 'Journal',
      es: 'Diario',
      pt: 'Diário',
      tr: 'Yevmiye',
      uk: 'Журнал',
      zh: '日记账',
      ar: 'دفتر اليومية',
      pl: 'Dziennik',
      it: 'Libro giornale',
      sk: 'Denník',
      ja: '仕訳帳',
      ko: '분개장',
      hi: 'जर्नल',
      nl: 'Dagboek',
      sv: 'Journal',
      vi: 'Nhật ký',
      id: 'Jurnal',
    }),
    tabTrialBalance: t({
      ru: 'Оборотно-сальдовая ведомость',
      en: 'Trial balance',
      kk: 'Айналым-сальдо ведомосы',
      de: 'Summen- und Saldenliste',
      fr: 'Balance générale',
      es: 'Balance de comprobación',
      pt: 'Balancete',
      tr: 'Mizan',
      uk: 'Оборотно-сальдова відомість',
      zh: '试算平衡表',
      ar: 'ميزان المراجعة',
      pl: 'Zestawienie obrotów i sald',
      it: 'Bilancio di verifica',
      sk: 'Obratová súvaha',
      ja: '試算表',
      ko: '시산표',
      hi: 'परीक्षण शेष',
      nl: 'Proef- en saldibalans',
      sv: 'Råbalans',
      vi: 'Bảng cân đối số phát sinh',
      id: 'Neraca saldo',
    }),
    tabAccount: t({
      ru: 'Карточка счёта',
      en: 'Account ledger',
      kk: 'Шот карточкасы',
      de: 'Kontoblatt',
      fr: 'Compte détaillé',
      es: 'Mayor de cuenta',
      pt: 'Razão da conta',
      tr: 'Hesap ekstresi',
      uk: 'Картка рахунку',
      zh: '科目明细账',
      ar: 'كشف الحساب',
      pl: 'Kartoteka konta',
      it: 'Scheda conto',
      sk: 'Karta účtu',
      ja: '勘定元帳',
      ko: '계정별 원장',
      hi: 'खाता विवरण',
      nl: 'Grootboekkaart',
      sv: 'Kontokort',
      vi: 'Sổ chi tiết tài khoản',
      id: 'Buku besar akun',
    }),
    enableTitle: t({
      ru: 'Включите реестр',
      en: 'Switch on the ledger',
      kk: 'Тізілімді қосыңыз',
      de: 'Hauptbuch einschalten',
      fr: 'Activer le grand livre',
      es: 'Activa el libro mayor',
      pt: 'Ative o livro-razão',
      tr: 'Defteri kebiri etkinleştirin',
      uk: 'Увімкніть реєстр',
      zh: '启用总账',
      ar: 'فعّل دفتر الأستاذ',
      pl: 'Włącz księgę główną',
      it: 'Attiva il libro mastro',
      sk: 'Zapnite hlavnú knihu',
      ja: '総勘定元帳を有効にする',
      ko: '총계정원장 켜기',
      hi: 'खाता बही चालू करें',
      nl: 'Grootboek inschakelen',
      sv: 'Slå på huvudboken',
      vi: 'Bật sổ cái',
      id: 'Aktifkan buku besar',
    }),
    enableText: t({
      ru: 'Каждая транзакция будет проведена сбалансированной двойной записью в одной базовой валюте. После появления проводок базовую валюту изменить нельзя.',
      en: 'Every transaction will be posted as a balanced double entry in one base currency. Once entries exist, the base currency cannot change.',
      kk: 'Әр транзакция бір базалық валютада теңгерілген қос жазбамен өткізіледі. Жазбалар пайда болғаннан кейін базалық валютаны өзгерту мүмкін емес.',
      de: 'Jede Transaktion wird als ausgeglichene Doppelbuchung in einer Basiswährung gebucht. Sobald Buchungen existieren, lässt sich die Basiswährung nicht mehr ändern.',
      fr: 'Chaque transaction sera comptabilisée en partie double équilibrée dans une devise de base. Une fois des écritures créées, la devise de base ne peut plus changer.',
      es: 'Cada transacción se registrará como un asiento doble equilibrado en una moneda base. Una vez que existan asientos, la moneda base no podrá cambiar.',
      pt: 'Cada transação será lançada como partida dobrada equilibrada numa moeda base. Depois de existirem lançamentos, a moeda base não pode mudar.',
      tr: 'Her işlem tek bir ana para biriminde dengeli çift taraflı kayıt olarak işlenir. Kayıtlar oluştuktan sonra ana para birimi değiştirilemez.',
      uk: 'Кожну транзакцію буде проведено збалансованим подвійним записом в одній базовій валюті. Після появи проводок базову валюту змінити не можна.',
      zh: '每笔交易都将以同一本位币记为借贷平衡的复式分录。一旦存在分录，本位币将无法更改。',
      ar: 'ستُرحَّل كل معاملة كقيد مزدوج متوازن بعملة أساس واحدة. بعد وجود قيود لا يمكن تغيير عملة الأساس.',
      pl: 'Każda transakcja zostanie zaksięgowana jako zbilansowany zapis podwójny w jednej walucie bazowej. Po pojawieniu się księgowań waluty bazowej nie można zmienić.',
      it: "Ogni transazione sarà registrata come scrittura doppia bilanciata in un'unica valuta di base. Una volta presenti scritture, la valuta di base non può cambiare.",
      sk: 'Každá transakcia sa zaúčtuje ako vyrovnaný podvojný zápis v jednej základnej mene. Keď existujú zápisy, základnú menu už nemožno zmeniť.',
      ja: 'すべての取引は一つの基準通貨で貸借一致の複式仕訳として計上されます。仕訳が存在すると基準通貨は変更できません。',
      ko: '모든 거래는 하나의 기준 통화로 대차가 일치하는 복식 분개로 기록됩니다. 분개가 생기면 기준 통화는 바꿀 수 없습니다.',
      hi: 'हर लेनदेन एक आधार मुद्रा में संतुलित दोहरी प्रविष्टि के रूप में दर्ज होगा। प्रविष्टियाँ बनने के बाद आधार मुद्रा बदली नहीं जा सकती।',
      nl: 'Elke transactie wordt geboekt als een sluitende dubbele boeking in één basisvaluta. Zodra er boekingen zijn, kan de basisvaluta niet meer veranderen.',
      sv: 'Varje transaktion bokförs som en balanserad dubbel verifikation i en basvaluta. När verifikationer finns kan basvalutan inte ändras.',
      vi: 'Mỗi giao dịch sẽ được ghi thành bút toán kép cân bằng trong một đồng tiền gốc. Khi đã có bút toán, không thể đổi đồng tiền gốc.',
      id: 'Setiap transaksi akan dibukukan sebagai jurnal berpasangan yang seimbang dalam satu mata uang dasar. Setelah ada jurnal, mata uang dasar tidak dapat diubah.',
    }),
    baseCurrencyLabel: t({
      ru: 'Базовая валюта',
      en: 'Base currency',
      kk: 'Базалық валюта',
      de: 'Basiswährung',
      fr: 'Devise de base',
      es: 'Moneda base',
      pt: 'Moeda base',
      tr: 'Ana para birimi',
      uk: 'Базова валюта',
      zh: '本位币',
      ar: 'عملة الأساس',
      pl: 'Waluta bazowa',
      it: 'Valuta di base',
      sk: 'Základná mena',
      ja: '基準通貨',
      ko: '기준 통화',
      hi: 'आधार मुद्रा',
      nl: 'Basisvaluta',
      sv: 'Basvaluta',
      vi: 'Đồng tiền gốc',
      id: 'Mata uang dasar',
    }),
    suggestedHint: t({
      ru: 'Чаще всего в ваших транзакциях',
      en: 'Most frequent in your transactions',
      kk: 'Транзакцияларыңызда жиі кездеседі',
      de: 'Am häufigsten in Ihren Transaktionen',
      fr: 'La plus fréquente dans vos transactions',
      es: 'La más frecuente en tus transacciones',
      pt: 'A mais frequente nas suas transações',
      tr: 'İşlemlerinizde en sık kullanılan',
      uk: 'Найчастіше у ваших транзакціях',
      zh: '您的交易中最常用',
      ar: 'الأكثر تكرارًا في معاملاتك',
      pl: 'Najczęstsza w Twoich transakcjach',
      it: 'La più frequente nelle tue transazioni',
      sk: 'Najčastejšia vo vašich transakciách',
      ja: '取引で最も多い通貨',
      ko: '거래에서 가장 많이 쓰인 통화',
      hi: 'आपके लेनदेन में सबसे आम',
      nl: 'Meest gebruikt in uw transacties',
      sv: 'Vanligast i dina transaktioner',
      vi: 'Phổ biến nhất trong giao dịch của bạn',
      id: 'Paling sering di transaksi Anda',
    }),
    historyToPost: t({
      ru: 'Транзакций к проведению',
      en: 'Transactions to post',
      kk: 'Өткізілетін транзакциялар',
      de: 'Zu buchende Transaktionen',
      fr: 'Transactions à comptabiliser',
      es: 'Transacciones por registrar',
      pt: 'Transações a lançar',
      tr: 'İşlenecek işlemler',
      uk: 'Транзакцій до проведення',
      zh: '待过账交易',
      ar: 'معاملات للترحيل',
      pl: 'Transakcje do zaksięgowania',
      it: 'Transazioni da registrare',
      sk: 'Transakcie na zaúčtovanie',
      ja: '計上する取引',
      ko: '기록할 거래',
      hi: 'दर्ज करने के लिए लेनदेन',
      nl: 'Te boeken transacties',
      sv: 'Transaktioner att bokföra',
      vi: 'Giao dịch cần ghi sổ',
      id: 'Transaksi untuk dibukukan',
    }),
    enableButton: t({
      ru: 'Включить',
      en: 'Switch on',
      kk: 'Қосу',
      de: 'Einschalten',
      fr: 'Activer',
      es: 'Activar',
      pt: 'Ativar',
      tr: 'Etkinleştir',
      uk: 'Увімкнути',
      zh: '启用',
      ar: 'تفعيل',
      pl: 'Włącz',
      it: 'Attiva',
      sk: 'Zapnúť',
      ja: '有効にする',
      ko: '켜기',
      hi: 'चालू करें',
      nl: 'Inschakelen',
      sv: 'Slå på',
      vi: 'Bật',
      id: 'Aktifkan',
    }),
    enableForbidden: t({
      ru: 'Включить реестр может владелец или администратор рабочего пространства.',
      en: 'A workspace owner or admin can switch on the ledger.',
      kk: 'Тізілімді жұмыс кеңістігінің иесі немесе әкімшісі қоса алады.',
      de: 'Eine Arbeitsbereichsinhaberin oder ein Admin kann das Hauptbuch einschalten.',
      fr: "Le propriétaire ou un administrateur de l'espace de travail peut activer le grand livre.",
      es: 'El propietario o un administrador del espacio de trabajo puede activar el libro mayor.',
      pt: 'O proprietário ou um administrador do espaço de trabalho pode ativar o livro-razão.',
      tr: 'Defteri kebiri çalışma alanı sahibi veya yöneticisi etkinleştirebilir.',
      uk: 'Увімкнути реєстр може власник або адміністратор робочого простору.',
      zh: '工作区所有者或管理员可以启用总账。',
      ar: 'يمكن لمالك مساحة العمل أو المسؤول تفعيل دفتر الأستاذ.',
      pl: 'Księgę główną może włączyć właściciel lub administrator obszaru roboczego.',
      it: "Il proprietario o un amministratore dell'area di lavoro può attivare il libro mastro.",
      sk: 'Hlavnú knihu môže zapnúť vlastník alebo správca pracovného priestoru.',
      ja: '総勘定元帳はワークスペースのオーナーまたは管理者が有効にできます。',
      ko: '총계정원장은 워크스페이스 소유자나 관리자가 켤 수 있습니다.',
      hi: 'खाता बही को वर्कस्पेस का स्वामी या व्यवस्थापक चालू कर सकता है।',
      nl: 'Een eigenaar of beheerder van de werkruimte kan het grootboek inschakelen.',
      sv: 'En ägare eller administratör av arbetsytan kan slå på huvudboken.',
      vi: 'Chủ sở hữu hoặc quản trị viên không gian làm việc có thể bật sổ cái.',
      id: 'Pemilik atau admin ruang kerja dapat mengaktifkan buku besar.',
    }),
    catchingUp: t({
      ru: 'Реестр догоняет транзакции, осталось',
      en: 'The ledger is catching up with transactions, left',
      kk: 'Тізілім транзакцияларды қуып жетуде, қалды',
      de: 'Das Hauptbuch holt Transaktionen nach, verbleibend',
      fr: 'Le grand livre rattrape les transactions, restantes',
      es: 'El libro mayor se está poniendo al día, quedan',
      pt: 'O livro-razão está a atualizar as transações, faltam',
      tr: 'Defteri kebir işlemleri yakalıyor, kalan',
      uk: 'Реєстр наздоганяє транзакції, залишилось',
      zh: '总账正在同步交易，剩余',
      ar: 'يلحق دفتر الأستاذ بالمعاملات، المتبقي',
      pl: 'Księga nadrabia transakcje, pozostało',
      it: 'Il libro mastro sta recuperando le transazioni, rimanenti',
      sk: 'Hlavná kniha dobieha transakcie, zostáva',
      ja: '元帳は取引を反映中です。残り',
      ko: '원장이 거래를 반영하는 중입니다. 남은 건수',
      hi: 'खाता बही लेनदेन दर्ज कर रही है, शेष',
      nl: 'Het grootboek haalt transacties in, resterend',
      sv: 'Huvudboken kommer ikapp transaktionerna, kvar',
      vi: 'Sổ cái đang cập nhật giao dịch, còn lại',
      id: 'Buku besar sedang mengejar transaksi, tersisa',
    }),
    failingLabel: t({
      ru: 'Не удалось провести транзакций',
      en: 'Transactions that could not be posted',
      kk: 'Өткізілмеген транзакциялар',
      de: 'Nicht buchbare Transaktionen',
      fr: 'Transactions non comptabilisées',
      es: 'Transacciones no registradas',
      pt: 'Transações não lançadas',
      tr: 'İşlenemeyen işlemler',
      uk: 'Не вдалося провести транзакцій',
      zh: '无法过账的交易',
      ar: 'معاملات تعذّر ترحيلها',
      pl: 'Nie udało się zaksięgować transakcji',
      it: 'Transazioni non registrate',
      sk: 'Nezaúčtované transakcie',
      ja: '計上できなかった取引',
      ko: '기록하지 못한 거래',
      hi: 'दर्ज न हो सके लेनदेन',
      nl: 'Niet te boeken transacties',
      sv: 'Transaktioner som inte kunde bokföras',
      vi: 'Giao dịch không ghi sổ được',
      id: 'Transaksi yang gagal dibukukan',
    }),
    failingHint: t({
      ru: 'Обычно не хватает курса валюты. Исправьте транзакцию — она будет проведена автоматически.',
      en: 'Usually an exchange rate is missing. Fix the transaction and it is posted automatically.',
      kk: 'Әдетте валюта бағамы жетіспейді. Транзакцияны түзетіңіз — ол автоматты түрде өткізіледі.',
      de: 'Meist fehlt ein Wechselkurs. Korrigieren Sie die Transaktion, dann wird sie automatisch gebucht.',
      fr: 'Il manque généralement un taux de change. Corrigez la transaction et elle sera comptabilisée automatiquement.',
      es: 'Normalmente falta un tipo de cambio. Corrige la transacción y se registrará automáticamente.',
      pt: 'Normalmente falta uma taxa de câmbio. Corrija a transação e ela será lançada automaticamente.',
      tr: 'Genellikle bir döviz kuru eksiktir. İşlemi düzeltin, otomatik olarak işlenecektir.',
      uk: 'Зазвичай бракує курсу валюти. Виправте транзакцію — її буде проведено автоматично.',
      zh: '通常是缺少汇率。修正交易后会自动过账。',
      ar: 'غالبًا ما يكون سعر الصرف مفقودًا. صحّح المعاملة وستُرحَّل تلقائيًا.',
      pl: 'Zwykle brakuje kursu waluty. Popraw transakcję, a zostanie zaksięgowana automatycznie.',
      it: 'Di solito manca un tasso di cambio. Correggi la transazione e verrà registrata automaticamente.',
      sk: 'Zvyčajne chýba výmenný kurz. Opravte transakciu a zaúčtuje sa automaticky.',
      ja: '多くの場合、為替レートが不足しています。取引を修正すると自動的に計上されます。',
      ko: '대개 환율이 없는 경우입니다. 거래를 수정하면 자동으로 기록됩니다.',
      hi: 'अक्सर विनिमय दर नहीं होती। लेनदेन ठीक करें, वह अपने आप दर्ज हो जाएगा।',
      nl: 'Meestal ontbreekt een wisselkoers. Corrigeer de transactie en ze wordt automatisch geboekt.',
      sv: 'Oftast saknas en växelkurs. Rätta transaktionen så bokförs den automatiskt.',
      vi: 'Thường là thiếu tỷ giá. Sửa giao dịch và nó sẽ được ghi sổ tự động.',
      id: 'Biasanya kurs tidak tersedia. Perbaiki transaksi dan transaksi akan dibukukan otomatis.',
    }),
    loadError: t({
      ru: 'Не удалось загрузить реестр',
      en: 'Could not load the ledger',
      kk: 'Тізілімді жүктеу мүмкін болмады',
      de: 'Hauptbuch konnte nicht geladen werden',
      fr: 'Impossible de charger le grand livre',
      es: 'No se pudo cargar el libro mayor',
      pt: 'Não foi possível carregar o livro-razão',
      tr: 'Defteri kebir yüklenemedi',
      uk: 'Не вдалося завантажити реєстр',
      zh: '无法加载总账',
      ar: 'تعذّر تحميل دفتر الأستاذ',
      pl: 'Nie udało się wczytać księgi',
      it: 'Impossibile caricare il libro mastro',
      sk: 'Hlavnú knihu sa nepodarilo načítať',
      ja: '元帳を読み込めませんでした',
      ko: '원장을 불러오지 못했습니다',
      hi: 'खाता बही लोड नहीं हो सकी',
      nl: 'Grootboek kon niet worden geladen',
      sv: 'Det gick inte att läsa in huvudboken',
      vi: 'Không tải được sổ cái',
      id: 'Gagal memuat buku besar',
    }),
    accAssets: t({
      ru: 'Активы',
      en: 'Assets',
      kk: 'Активтер',
      de: 'Aktiva',
      fr: 'Actifs',
      es: 'Activos',
      pt: 'Ativos',
      tr: 'Varlıklar',
      uk: 'Активи',
      zh: '资产',
      ar: 'الأصول',
      pl: 'Aktywa',
      it: 'Attività',
      sk: 'Aktíva',
      ja: '資産',
      ko: '자산',
      hi: 'परिसंपत्तियाँ',
      nl: 'Activa',
      sv: 'Tillgångar',
      vi: 'Tài sản',
      id: 'Aset',
    }),
    accCash: t({
      ru: 'Денежные средства',
      en: 'Cash and bank',
      kk: 'Ақша қаражаты',
      de: 'Kasse und Bank',
      fr: 'Trésorerie',
      es: 'Caja y bancos',
      pt: 'Caixa e bancos',
      tr: 'Kasa ve banka',
      uk: 'Грошові кошти',
      zh: '货币资金',
      ar: 'النقد والبنوك',
      pl: 'Środki pieniężne',
      it: 'Cassa e banche',
      sk: 'Peňažné prostriedky',
      ja: '現金及び預金',
      ko: '현금 및 예금',
      hi: 'नकद और बैंक',
      nl: 'Kas en bank',
      sv: 'Kassa och bank',
      vi: 'Tiền và ngân hàng',
      id: 'Kas dan bank',
    }),
    accCashUnallocated: t({
      ru: 'Деньги без счёта',
      en: 'Cash, account unknown',
      kk: 'Шоты белгісіз ақша',
      de: 'Geld, Konto unbekannt',
      fr: 'Trésorerie, compte inconnu',
      es: 'Efectivo, cuenta desconocida',
      pt: 'Dinheiro, conta desconhecida',
      tr: 'Nakit, hesap bilinmiyor',
      uk: 'Кошти без рахунку',
      zh: '现金（账户未知）',
      ar: 'نقد، الحساب غير معروف',
      pl: 'Środki, nieznane konto',
      it: 'Liquidità, conto sconosciuto',
      sk: 'Peniaze, neznámy účet',
      ja: '現金（口座不明）',
      ko: '현금(계좌 미상)',
      hi: 'नकद, खाता अज्ञात',
      nl: 'Geld, rekening onbekend',
      sv: 'Pengar, okänt konto',
      vi: 'Tiền, chưa rõ tài khoản',
      id: 'Kas, akun tidak diketahui',
    }),
    accVatReceivable: t({
      ru: 'НДС к возмещению',
      en: 'VAT receivable',
      kk: 'Өтелетін ҚҚС',
      de: 'Vorsteuer',
      fr: 'TVA déductible',
      es: 'IVA soportado',
      pt: 'IVA a recuperar',
      tr: 'İndirilecek KDV',
      uk: 'ПДВ до відшкодування',
      zh: '应收增值税',
      ar: 'ضريبة القيمة المضافة المستردة',
      pl: 'VAT naliczony',
      it: 'IVA a credito',
      sk: 'DPH na odpočet',
      ja: '仮払消費税',
      ko: '부가세 대급금',
      hi: 'प्राप्य जीएसटी/वैट',
      nl: 'Te vorderen btw',
      sv: 'Ingående moms',
      vi: 'Thuế GTGT được khấu trừ',
      id: 'PPN masukan',
    }),
    accSuspense: t({
      ru: 'Невыясненные суммы',
      en: 'Suspense (uncategorised)',
      kk: 'Анықталмаған сомалар',
      de: 'Verrechnungskonto (ohne Kategorie)',
      fr: "Compte d'attente (sans catégorie)",
      es: 'Cuenta transitoria (sin categoría)',
      pt: 'Conta transitória (sem categoria)',
      tr: 'Askı hesabı (kategorisiz)',
      uk: "Нез'ясовані суми",
      zh: '待定款项（未分类）',
      ar: 'حساب معلق (غير مصنف)',
      pl: 'Konto przejściowe (bez kategorii)',
      it: 'Conto sospeso (senza categoria)',
      sk: 'Nezaradené sumy',
      ja: '仮勘定（未分類）',
      ko: '가계정(미분류)',
      hi: 'निलंबित (अवर्गीकृत)',
      nl: 'Tussenrekening (zonder categorie)',
      sv: 'Avräkningskonto (okategoriserat)',
      vi: 'Tài khoản chờ (chưa phân loại)',
      id: 'Akun penampung (tanpa kategori)',
    }),
    accLiabilities: t({
      ru: 'Обязательства',
      en: 'Liabilities',
      kk: 'Міндеттемелер',
      de: 'Verbindlichkeiten',
      fr: 'Passifs',
      es: 'Pasivos',
      pt: 'Passivos',
      tr: 'Yükümlülükler',
      uk: "Зобов'язання",
      zh: '负债',
      ar: 'الخصوم',
      pl: 'Zobowiązania',
      it: 'Passività',
      sk: 'Záväzky',
      ja: '負債',
      ko: '부채',
      hi: 'देनदारियाँ',
      nl: 'Schulden',
      sv: 'Skulder',
      vi: 'Nợ phải trả',
      id: 'Liabilitas',
    }),
    accVatPayable: t({
      ru: 'НДС к уплате',
      en: 'VAT payable',
      kk: 'Төленетін ҚҚС',
      de: 'Umsatzsteuer',
      fr: 'TVA collectée',
      es: 'IVA repercutido',
      pt: 'IVA a pagar',
      tr: 'Ödenecek KDV',
      uk: 'ПДВ до сплати',
      zh: '应交增值税',
      ar: 'ضريبة القيمة المضافة المستحقة',
      pl: 'VAT należny',
      it: 'IVA a debito',
      sk: 'DPH na úhradu',
      ja: '仮受消費税',
      ko: '부가세 예수금',
      hi: 'देय जीएसटी/वैट',
      nl: 'Af te dragen btw',
      sv: 'Utgående moms',
      vi: 'Thuế GTGT phải nộp',
      id: 'PPN keluaran',
    }),
    accPayables: t({
      ru: 'Кредиторская задолженность',
      en: 'Accounts payable',
      kk: 'Кредиторлық берешек',
      de: 'Verbindlichkeiten aus Lieferungen',
      fr: 'Fournisseurs',
      es: 'Cuentas por pagar',
      pt: 'Contas a pagar',
      tr: 'Ticari borçlar',
      uk: 'Кредиторська заборгованість',
      zh: '应付账款',
      ar: 'الذمم الدائنة',
      pl: 'Zobowiązania z tytułu dostaw',
      it: 'Debiti verso fornitori',
      sk: 'Záväzky voči dodávateľom',
      ja: '買掛金',
      ko: '매입채무',
      hi: 'देय खाते',
      nl: 'Crediteuren',
      sv: 'Leverantörsskulder',
      vi: 'Phải trả người bán',
      id: 'Utang usaha',
    }),
    accEquity: t({
      ru: 'Капитал',
      en: 'Equity',
      kk: 'Капитал',
      de: 'Eigenkapital',
      fr: 'Capitaux propres',
      es: 'Patrimonio neto',
      pt: 'Capital próprio',
      tr: 'Özkaynak',
      uk: 'Капітал',
      zh: '所有者权益',
      ar: 'حقوق الملكية',
      pl: 'Kapitał własny',
      it: 'Patrimonio netto',
      sk: 'Vlastné imanie',
      ja: '純資産',
      ko: '자본',
      hi: 'इक्विटी',
      nl: 'Eigen vermogen',
      sv: 'Eget kapital',
      vi: 'Vốn chủ sở hữu',
      id: 'Ekuitas',
    }),
    accOpeningBalance: t({
      ru: 'Входящие остатки',
      en: 'Opening balances',
      kk: 'Кіріс қалдықтар',
      de: 'Eröffnungsbilanzkonto',
      fr: "Soldes d'ouverture",
      es: 'Saldos de apertura',
      pt: 'Saldos iniciais',
      tr: 'Açılış bakiyeleri',
      uk: 'Вхідні залишки',
      zh: '期初余额',
      ar: 'الأرصدة الافتتاحية',
      pl: 'Bilans otwarcia',
      it: 'Saldi di apertura',
      sk: 'Počiatočné zostatky',
      ja: '期首残高',
      ko: '기초 잔액',
      hi: 'प्रारंभिक शेष',
      nl: 'Openingssaldi',
      sv: 'Ingående balanser',
      vi: 'Số dư đầu kỳ',
      id: 'Saldo awal',
    }),
    accRetainedEarnings: t({
      ru: 'Нераспределённая прибыль',
      en: 'Retained earnings',
      kk: 'Бөлінбеген пайда',
      de: 'Gewinnvortrag',
      fr: 'Report à nouveau',
      es: 'Resultados acumulados',
      pt: 'Resultados transitados',
      tr: 'Geçmiş yıl kârları',
      uk: 'Нерозподілений прибуток',
      zh: '留存收益',
      ar: 'الأرباح المحتجزة',
      pl: 'Zyski zatrzymane',
      it: 'Utili a nuovo',
      sk: 'Nerozdelený zisk',
      ja: '繰越利益剰余金',
      ko: '이익잉여금',
      hi: 'प्रतिधारित आय',
      nl: 'Ingehouden winst',
      sv: 'Balanserade vinstmedel',
      vi: 'Lợi nhuận giữ lại',
      id: 'Laba ditahan',
    }),
    accIncome: t({
      ru: 'Доходы',
      en: 'Income',
      kk: 'Кірістер',
      de: 'Erträge',
      fr: 'Produits',
      es: 'Ingresos',
      pt: 'Rendimentos',
      tr: 'Gelirler',
      uk: 'Доходи',
      zh: '收入',
      ar: 'الإيرادات',
      pl: 'Przychody',
      it: 'Ricavi',
      sk: 'Výnosy',
      ja: '収益',
      ko: '수익',
      hi: 'आय',
      nl: 'Opbrengsten',
      sv: 'Intäkter',
      vi: 'Doanh thu',
      id: 'Pendapatan',
    }),
    accFxGain: t({
      ru: 'Курсовые доходы',
      en: 'Foreign exchange gains',
      kk: 'Бағамдық кірістер',
      de: 'Kursgewinne',
      fr: 'Gains de change',
      es: 'Ganancias por tipo de cambio',
      pt: 'Ganhos cambiais',
      tr: 'Kur farkı gelirleri',
      uk: 'Курсові доходи',
      zh: '汇兑收益',
      ar: 'أرباح فروق العملة',
      pl: 'Dodatnie różnice kursowe',
      it: 'Utili su cambi',
      sk: 'Kurzové zisky',
      ja: '為替差益',
      ko: '외환차익',
      hi: 'विनिमय लाभ',
      nl: 'Koerswinsten',
      sv: 'Valutakursvinster',
      vi: 'Lãi chênh lệch tỷ giá',
      id: 'Laba selisih kurs',
    }),
    accExpenses: t({
      ru: 'Расходы',
      en: 'Expenses',
      kk: 'Шығыстар',
      de: 'Aufwendungen',
      fr: 'Charges',
      es: 'Gastos',
      pt: 'Gastos',
      tr: 'Giderler',
      uk: 'Витрати',
      zh: '费用',
      ar: 'المصروفات',
      pl: 'Koszty',
      it: 'Costi',
      sk: 'Náklady',
      ja: '費用',
      ko: '비용',
      hi: 'व्यय',
      nl: 'Kosten',
      sv: 'Kostnader',
      vi: 'Chi phí',
      id: 'Beban',
    }),
    accFxLoss: t({
      ru: 'Курсовые расходы',
      en: 'Foreign exchange losses',
      kk: 'Бағамдық шығыстар',
      de: 'Kursverluste',
      fr: 'Pertes de change',
      es: 'Pérdidas por tipo de cambio',
      pt: 'Perdas cambiais',
      tr: 'Kur farkı giderleri',
      uk: 'Курсові витрати',
      zh: '汇兑损失',
      ar: 'خسائر فروق العملة',
      pl: 'Ujemne różnice kursowe',
      it: 'Perdite su cambi',
      sk: 'Kurzové straty',
      ja: '為替差損',
      ko: '외환차손',
      hi: 'विनिमय हानि',
      nl: 'Koersverliezen',
      sv: 'Valutakursförluster',
      vi: 'Lỗ chênh lệch tỷ giá',
      id: 'Rugi selisih kurs',
    }),
    addAccount: t({
      ru: 'Добавить счёт',
      en: 'Add account',
      kk: 'Шот қосу',
      de: 'Konto hinzufügen',
      fr: 'Ajouter un compte',
      es: 'Añadir cuenta',
      pt: 'Adicionar conta',
      tr: 'Hesap ekle',
      uk: 'Додати рахунок',
      zh: '添加科目',
      ar: 'إضافة حساب',
      pl: 'Dodaj konto',
      it: 'Aggiungi conto',
      sk: 'Pridať účet',
      ja: '勘定科目を追加',
      ko: '계정 추가',
      hi: 'खाता जोड़ें',
      nl: 'Rekening toevoegen',
      sv: 'Lägg till konto',
      vi: 'Thêm tài khoản',
      id: 'Tambah akun',
    }),
    colCode: t({
      ru: 'Код',
      en: 'Code',
      kk: 'Код',
      de: 'Code',
      fr: 'Code',
      es: 'Código',
      pt: 'Código',
      tr: 'Kod',
      uk: 'Код',
      zh: '代码',
      ar: 'الرمز',
      pl: 'Kod',
      it: 'Codice',
      sk: 'Kód',
      ja: 'コード',
      ko: '코드',
      hi: 'कोड',
      nl: 'Code',
      sv: 'Kod',
      vi: 'Mã',
      id: 'Kode',
    }),
    colName: t({
      ru: 'Счёт',
      en: 'Account',
      kk: 'Шот',
      de: 'Konto',
      fr: 'Compte',
      es: 'Cuenta',
      pt: 'Conta',
      tr: 'Hesap',
      uk: 'Рахунок',
      zh: '科目',
      ar: 'الحساب',
      pl: 'Konto',
      it: 'Conto',
      sk: 'Účet',
      ja: '勘定科目',
      ko: '계정',
      hi: 'खाता',
      nl: 'Rekening',
      sv: 'Konto',
      vi: 'Tài khoản',
      id: 'Akun',
    }),
    colType: t({
      ru: 'Тип',
      en: 'Type',
      kk: 'Түрі',
      de: 'Typ',
      fr: 'Type',
      es: 'Tipo',
      pt: 'Tipo',
      tr: 'Tür',
      uk: 'Тип',
      zh: '类型',
      ar: 'النوع',
      pl: 'Typ',
      it: 'Tipo',
      sk: 'Typ',
      ja: '種類',
      ko: '유형',
      hi: 'प्रकार',
      nl: 'Type',
      sv: 'Typ',
      vi: 'Loại',
      id: 'Jenis',
    }),
    colCurrency: t({
      ru: 'Валюта',
      en: 'Currency',
      kk: 'Валюта',
      de: 'Währung',
      fr: 'Devise',
      es: 'Moneda',
      pt: 'Moeda',
      tr: 'Para birimi',
      uk: 'Валюта',
      zh: '币种',
      ar: 'العملة',
      pl: 'Waluta',
      it: 'Valuta',
      sk: 'Mena',
      ja: '通貨',
      ko: '통화',
      hi: 'मुद्रा',
      nl: 'Valuta',
      sv: 'Valuta',
      vi: 'Tiền tệ',
      id: 'Mata uang',
    }),
    typeAsset: t({
      ru: 'Актив',
      en: 'Asset',
      kk: 'Актив',
      de: 'Aktiv',
      fr: 'Actif',
      es: 'Activo',
      pt: 'Ativo',
      tr: 'Varlık',
      uk: 'Актив',
      zh: '资产',
      ar: 'أصل',
      pl: 'Aktywo',
      it: 'Attività',
      sk: 'Aktívum',
      ja: '資産',
      ko: '자산',
      hi: 'परिसंपत्ति',
      nl: 'Activa',
      sv: 'Tillgång',
      vi: 'Tài sản',
      id: 'Aset',
    }),
    typeLiability: t({
      ru: 'Обязательство',
      en: 'Liability',
      kk: 'Міндеттеме',
      de: 'Verbindlichkeit',
      fr: 'Passif',
      es: 'Pasivo',
      pt: 'Passivo',
      tr: 'Yükümlülük',
      uk: "Зобов'язання",
      zh: '负债',
      ar: 'التزام',
      pl: 'Zobowiązanie',
      it: 'Passività',
      sk: 'Záväzok',
      ja: '負債',
      ko: '부채',
      hi: 'देनदारी',
      nl: 'Schuld',
      sv: 'Skuld',
      vi: 'Nợ phải trả',
      id: 'Liabilitas',
    }),
    typeEquity: t({
      ru: 'Капитал',
      en: 'Equity',
      kk: 'Капитал',
      de: 'Eigenkapital',
      fr: 'Capitaux propres',
      es: 'Patrimonio',
      pt: 'Capital próprio',
      tr: 'Özkaynak',
      uk: 'Капітал',
      zh: '权益',
      ar: 'حقوق الملكية',
      pl: 'Kapitał',
      it: 'Patrimonio',
      sk: 'Imanie',
      ja: '純資産',
      ko: '자본',
      hi: 'इक्विटी',
      nl: 'Eigen vermogen',
      sv: 'Eget kapital',
      vi: 'Vốn chủ sở hữu',
      id: 'Ekuitas',
    }),
    typeIncome: t({
      ru: 'Доход',
      en: 'Income',
      kk: 'Кіріс',
      de: 'Ertrag',
      fr: 'Produit',
      es: 'Ingreso',
      pt: 'Rendimento',
      tr: 'Gelir',
      uk: 'Дохід',
      zh: '收入',
      ar: 'إيراد',
      pl: 'Przychód',
      it: 'Ricavo',
      sk: 'Výnos',
      ja: '収益',
      ko: '수익',
      hi: 'आय',
      nl: 'Opbrengst',
      sv: 'Intäkt',
      vi: 'Doanh thu',
      id: 'Pendapatan',
    }),
    typeExpense: t({
      ru: 'Расход',
      en: 'Expense',
      kk: 'Шығыс',
      de: 'Aufwand',
      fr: 'Charge',
      es: 'Gasto',
      pt: 'Gasto',
      tr: 'Gider',
      uk: 'Витрата',
      zh: '费用',
      ar: 'مصروف',
      pl: 'Koszt',
      it: 'Costo',
      sk: 'Náklad',
      ja: '費用',
      ko: '비용',
      hi: 'व्यय',
      nl: 'Kosten',
      sv: 'Kostnad',
      vi: 'Chi phí',
      id: 'Beban',
    }),
    headerBadge: t({
      ru: 'Раздел',
      en: 'Section',
      kk: 'Бөлім',
      de: 'Abschnitt',
      fr: 'Section',
      es: 'Sección',
      pt: 'Secção',
      tr: 'Bölüm',
      uk: 'Розділ',
      zh: '类别',
      ar: 'قسم',
      pl: 'Sekcja',
      it: 'Sezione',
      sk: 'Sekcia',
      ja: '区分',
      ko: '구분',
      hi: 'अनुभाग',
      nl: 'Sectie',
      sv: 'Avsnitt',
      vi: 'Nhóm',
      id: 'Bagian',
    }),
    systemBadge: t({
      ru: 'Системный',
      en: 'System',
      kk: 'Жүйелік',
      de: 'System',
      fr: 'Système',
      es: 'Sistema',
      pt: 'Sistema',
      tr: 'Sistem',
      uk: 'Системний',
      zh: '系统',
      ar: 'نظامي',
      pl: 'Systemowe',
      it: 'Sistema',
      sk: 'Systémový',
      ja: 'システム',
      ko: '시스템',
      hi: 'सिस्टम',
      nl: 'Systeem',
      sv: 'System',
      vi: 'Hệ thống',
      id: 'Sistem',
    }),
    delete: t({
      ru: 'Удалить',
      en: 'Delete',
      kk: 'Жою',
      de: 'Löschen',
      fr: 'Supprimer',
      es: 'Eliminar',
      pt: 'Eliminar',
      tr: 'Sil',
      uk: 'Видалити',
      zh: '删除',
      ar: 'حذف',
      pl: 'Usuń',
      it: 'Elimina',
      sk: 'Odstrániť',
      ja: '削除',
      ko: '삭제',
      hi: 'हटाएँ',
      nl: 'Verwijderen',
      sv: 'Ta bort',
      vi: 'Xóa',
      id: 'Hapus',
    }),
    parentAccount: t({
      ru: 'Раздел',
      en: 'Section',
      kk: 'Бөлім',
      de: 'Abschnitt',
      fr: 'Section',
      es: 'Sección',
      pt: 'Secção',
      tr: 'Bölüm',
      uk: 'Розділ',
      zh: '所属类别',
      ar: 'القسم',
      pl: 'Sekcja',
      it: 'Sezione',
      sk: 'Sekcia',
      ja: '区分',
      ko: '상위 구분',
      hi: 'अनुभाग',
      nl: 'Sectie',
      sv: 'Avsnitt',
      vi: 'Nhóm cha',
      id: 'Bagian induk',
    }),
    noParent: t({
      ru: 'Верхний уровень',
      en: 'Top level',
      kk: 'Жоғарғы деңгей',
      de: 'Oberste Ebene',
      fr: 'Niveau supérieur',
      es: 'Nivel superior',
      pt: 'Nível superior',
      tr: 'Üst düzey',
      uk: 'Верхній рівень',
      zh: '顶级',
      ar: 'المستوى الأعلى',
      pl: 'Najwyższy poziom',
      it: 'Livello superiore',
      sk: 'Najvyššia úroveň',
      ja: '最上位',
      ko: '최상위',
      hi: 'शीर्ष स्तर',
      nl: 'Hoogste niveau',
      sv: 'Översta nivån',
      vi: 'Cấp cao nhất',
      id: 'Tingkat teratas',
    }),
    currencyOptional: t({
      ru: 'Валюта (необязательно)',
      en: 'Currency (optional)',
      kk: 'Валюта (міндетті емес)',
      de: 'Währung (optional)',
      fr: 'Devise (facultatif)',
      es: 'Moneda (opcional)',
      pt: 'Moeda (opcional)',
      tr: 'Para birimi (isteğe bağlı)',
      uk: "Валюта (необов'язково)",
      zh: '币种（可选）',
      ar: 'العملة (اختياري)',
      pl: 'Waluta (opcjonalnie)',
      it: 'Valuta (facoltativa)',
      sk: 'Mena (nepovinné)',
      ja: '通貨（任意）',
      ko: '통화(선택)',
      hi: 'मुद्रा (वैकल्पिक)',
      nl: 'Valuta (optioneel)',
      sv: 'Valuta (valfritt)',
      vi: 'Tiền tệ (tùy chọn)',
      id: 'Mata uang (opsional)',
    }),
    sectionHeader: t({
      ru: 'Раздел (группирует счета, проводок не принимает)',
      en: 'Section header (groups accounts, takes no entries)',
      kk: 'Бөлім (шоттарды топтайды, жазба қабылдамайды)',
      de: 'Abschnitt (gruppiert Konten, keine Buchungen)',
      fr: 'Section (regroupe des comptes, sans écritures)',
      es: 'Sección (agrupa cuentas, sin asientos)',
      pt: 'Secção (agrupa contas, sem lançamentos)',
      tr: 'Bölüm (hesapları gruplar, kayıt almaz)',
      uk: 'Розділ (групує рахунки, проводок не приймає)',
      zh: '类别（归组科目，不可记账）',
      ar: 'قسم (يجمع الحسابات ولا يقبل قيودًا)',
      pl: 'Sekcja (grupuje konta, bez księgowań)',
      it: 'Sezione (raggruppa conti, senza scritture)',
      sk: 'Sekcia (zoskupuje účty, bez zápisov)',
      ja: '区分（勘定をまとめ、仕訳は不可）',
      ko: '구분(계정을 묶으며 분개 불가)',
      hi: 'अनुभाग (खातों को समूहित करता है, प्रविष्टि नहीं)',
      nl: 'Sectie (groepeert rekeningen, geen boekingen)',
      sv: 'Avsnitt (grupperar konton, inga verifikationer)',
      vi: 'Nhóm (gom tài khoản, không nhận bút toán)',
      id: 'Bagian (mengelompokkan akun, tanpa jurnal)',
    }),
    save: t({
      ru: 'Сохранить',
      en: 'Save',
      kk: 'Сақтау',
      de: 'Speichern',
      fr: 'Enregistrer',
      es: 'Guardar',
      pt: 'Guardar',
      tr: 'Kaydet',
      uk: 'Зберегти',
      zh: '保存',
      ar: 'حفظ',
      pl: 'Zapisz',
      it: 'Salva',
      sk: 'Uložiť',
      ja: '保存',
      ko: '저장',
      hi: 'सहेजें',
      nl: 'Opslaan',
      sv: 'Spara',
      vi: 'Lưu',
      id: 'Simpan',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Бас тарту',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      ar: 'إلغاء',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
    }),
    reconTitle: t({
      ru: 'Банковские счета и выписки',
      en: 'Bank accounts against statements',
      kk: 'Банк шоттары мен үзінділер',
      de: 'Bankkonten gegen Kontoauszüge',
      fr: 'Comptes bancaires et relevés',
      es: 'Cuentas bancarias frente a extractos',
      pt: 'Contas bancárias face aos extratos',
      tr: 'Banka hesapları ve ekstreler',
      uk: 'Банківські рахунки та виписки',
      zh: '银行账户与对账单核对',
      ar: 'الحسابات البنكية مقابل الكشوف',
      pl: 'Rachunki bankowe a wyciągi',
      it: 'Conti bancari ed estratti',
      sk: 'Bankové účty a výpisy',
      ja: '銀行口座と明細書の照合',
      ko: '은행 계좌와 명세서 대조',
      hi: 'बैंक खाते बनाम विवरण',
      nl: 'Bankrekeningen tegenover afschriften',
      sv: 'Bankkonton mot kontoutdrag',
      vi: 'Tài khoản ngân hàng đối chiếu sao kê',
      id: 'Rekening bank terhadap rekening koran',
    }),
    colLedger: t({
      ru: 'По реестру',
      en: 'Ledger',
      kk: 'Тізілім бойынша',
      de: 'Hauptbuch',
      fr: 'Grand livre',
      es: 'Libro mayor',
      pt: 'Livro-razão',
      tr: 'Defter',
      uk: 'За реєстром',
      zh: '总账',
      ar: 'الدفتر',
      pl: 'Księga',
      it: 'Libro mastro',
      sk: 'Hlavná kniha',
      ja: '元帳',
      ko: '원장',
      hi: 'बही',
      nl: 'Grootboek',
      sv: 'Huvudbok',
      vi: 'Sổ cái',
      id: 'Buku besar',
    }),
    colStatement: t({
      ru: 'Выписка / кошелёк',
      en: 'Statement / wallet',
      kk: 'Үзінді / әмиян',
      de: 'Auszug / Wallet',
      fr: 'Relevé / portefeuille',
      es: 'Extracto / billetera',
      pt: 'Extrato / carteira',
      tr: 'Ekstre / cüzdan',
      uk: 'Виписка / гаманець',
      zh: '对账单 / 钱包',
      ar: 'كشف الحساب / المحفظة',
      pl: 'Wyciąg / portfel',
      it: 'Estratto / portafoglio',
      sk: 'Výpis / peňaženka',
      ja: '明細 / ウォレット',
      ko: '명세서 / 지갑',
      hi: 'स्टेटमेंट / वॉलेट',
      nl: 'Afschrift / portemonnee',
      sv: 'Kontoutdrag / plånbok',
      vi: 'Sao kê / ví',
      id: 'Rekening koran / dompet',
    }),
    colDifference: t({
      ru: 'Разница',
      en: 'Difference',
      kk: 'Айырма',
      de: 'Differenz',
      fr: 'Écart',
      es: 'Diferencia',
      pt: 'Diferença',
      tr: 'Fark',
      uk: 'Різниця',
      zh: '差额',
      ar: 'الفرق',
      pl: 'Różnica',
      it: 'Differenza',
      sk: 'Rozdiel',
      ja: '差額',
      ko: '차이',
      hi: 'अंतर',
      nl: 'Verschil',
      sv: 'Differens',
      vi: 'Chênh lệch',
      id: 'Selisih',
    }),
    noStatementBalance: t({
      ru: 'нет остатка',
      en: 'no balance',
      kk: 'қалдық жоқ',
      de: 'kein Saldo',
      fr: 'pas de solde',
      es: 'sin saldo',
      pt: 'sem saldo',
      tr: 'bakiye yok',
      uk: 'немає залишку',
      zh: '无余额',
      ar: 'لا رصيد',
      pl: 'brak salda',
      it: 'nessun saldo',
      sk: 'bez zostatku',
      ja: '残高なし',
      ko: '잔액 없음',
      hi: 'शेष नहीं',
      nl: 'geen saldo',
      sv: 'inget saldo',
      vi: 'không có số dư',
      id: 'tanpa saldo',
    }),
    noOpeningBalance: t({
      ru: 'Нет входящего остатка: в первой выписке он не указан',
      en: 'No opening balance: the first statement does not state one',
      kk: 'Кіріс қалдық жоқ: бірінші үзіндіде көрсетілмеген',
      de: 'Kein Anfangssaldo: der erste Auszug nennt keinen',
      fr: "Pas de solde d'ouverture : le premier relevé n'en indique pas",
      es: 'Sin saldo inicial: el primer extracto no lo indica',
      pt: 'Sem saldo inicial: o primeiro extrato não o indica',
      tr: 'Açılış bakiyesi yok: ilk ekstrede belirtilmemiş',
      uk: 'Немає вхідного залишку: у першій виписці його не зазначено',
      zh: '无期初余额：第一份对账单未注明',
      ar: 'لا رصيد افتتاحي: الكشف الأول لا يذكره',
      pl: 'Brak salda otwarcia: pierwszy wyciąg go nie podaje',
      it: 'Nessun saldo iniziale: il primo estratto non lo riporta',
      sk: 'Bez počiatočného zostatku: prvý výpis ho neuvádza',
      ja: '期首残高なし：最初の明細書に記載がありません',
      ko: '기초 잔액 없음: 첫 명세서에 표시되지 않음',
      hi: 'प्रारंभिक शेष नहीं: पहले विवरण में यह नहीं है',
      nl: 'Geen beginsaldo: het eerste afschrift vermeldt er geen',
      sv: 'Inget ingående saldo: första kontoutdraget anger inget',
      vi: 'Không có số dư đầu: sao kê đầu tiên không ghi',
      id: 'Tanpa saldo awal: rekening koran pertama tidak mencantumkannya',
    }),
    newEntry: t({
      ru: 'Новая проводка',
      en: 'New entry',
      kk: 'Жаңа жазба',
      de: 'Neue Buchung',
      fr: 'Nouvelle écriture',
      es: 'Nuevo asiento',
      pt: 'Novo lançamento',
      tr: 'Yeni kayıt',
      uk: 'Нова проводка',
      zh: '新建分录',
      ar: 'قيد جديد',
      pl: 'Nowe księgowanie',
      it: 'Nuova scrittura',
      sk: 'Nový zápis',
      ja: '新規仕訳',
      ko: '새 분개',
      hi: 'नई प्रविष्टि',
      nl: 'Nieuwe boeking',
      sv: 'Ny verifikation',
      vi: 'Bút toán mới',
      id: 'Jurnal baru',
    }),
    filterStatus: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Estado',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Status',
      it: 'Stato',
      sk: 'Stav',
      ja: '状態',
      ko: '상태',
      hi: 'स्थिति',
      nl: 'Status',
      sv: 'Status',
      vi: 'Trạng thái',
      id: 'Status',
    }),
    allStatuses: t({
      ru: 'Все',
      en: 'All',
      kk: 'Барлығы',
      de: 'Alle',
      fr: 'Tous',
      es: 'Todos',
      pt: 'Todos',
      tr: 'Tümü',
      uk: 'Усі',
      zh: '全部',
      ar: 'الكل',
      pl: 'Wszystkie',
      it: 'Tutti',
      sk: 'Všetky',
      ja: 'すべて',
      ko: '전체',
      hi: 'सभी',
      nl: 'Alle',
      sv: 'Alla',
      vi: 'Tất cả',
      id: 'Semua',
    }),
    statusDraft: t({
      ru: 'Черновик',
      en: 'Draft',
      kk: 'Жоба',
      de: 'Entwurf',
      fr: 'Brouillon',
      es: 'Borrador',
      pt: 'Rascunho',
      tr: 'Taslak',
      uk: 'Чернетка',
      zh: '草稿',
      ar: 'مسودة',
      pl: 'Szkic',
      it: 'Bozza',
      sk: 'Koncept',
      ja: '下書き',
      ko: '초안',
      hi: 'मसौदा',
      nl: 'Concept',
      sv: 'Utkast',
      vi: 'Nháp',
      id: 'Draf',
    }),
    statusPosted: t({
      ru: 'Проведена',
      en: 'Posted',
      kk: 'Өткізілді',
      de: 'Gebucht',
      fr: 'Comptabilisée',
      es: 'Registrado',
      pt: 'Lançado',
      tr: 'İşlendi',
      uk: 'Проведено',
      zh: '已过账',
      ar: 'مُرحَّل',
      pl: 'Zaksięgowane',
      it: 'Registrata',
      sk: 'Zaúčtované',
      ja: '計上済み',
      ko: '기록됨',
      hi: 'दर्ज',
      nl: 'Geboekt',
      sv: 'Bokförd',
      vi: 'Đã ghi sổ',
      id: 'Dibukukan',
    }),
    statusReversed: t({
      ru: 'Сторнирована',
      en: 'Reversed',
      kk: 'Сторноланды',
      de: 'Storniert',
      fr: 'Contrepassée',
      es: 'Anulado',
      pt: 'Estornado',
      tr: 'Ters kaydedildi',
      uk: 'Сторновано',
      zh: '已冲销',
      ar: 'معكوس',
      pl: 'Stornowane',
      it: 'Stornata',
      sk: 'Stornované',
      ja: '取消済み',
      ko: '취소됨',
      hi: 'उलटी गई',
      nl: 'Tegengeboekt',
      sv: 'Makulerad',
      vi: 'Đã đảo',
      id: 'Dibalik',
    }),
    filterSource: t({
      ru: 'Источник',
      en: 'Source',
      kk: 'Көзі',
      de: 'Quelle',
      fr: 'Origine',
      es: 'Origen',
      pt: 'Origem',
      tr: 'Kaynak',
      uk: 'Джерело',
      zh: '来源',
      ar: 'المصدر',
      pl: 'Źródło',
      it: 'Origine',
      sk: 'Zdroj',
      ja: '発生元',
      ko: '출처',
      hi: 'स्रोत',
      nl: 'Bron',
      sv: 'Källa',
      vi: 'Nguồn',
      id: 'Sumber',
    }),
    allSources: t({
      ru: 'Все источники',
      en: 'All sources',
      kk: 'Барлық көздер',
      de: 'Alle Quellen',
      fr: 'Toutes les origines',
      es: 'Todos los orígenes',
      pt: 'Todas as origens',
      tr: 'Tüm kaynaklar',
      uk: 'Усі джерела',
      zh: '全部来源',
      ar: 'كل المصادر',
      pl: 'Wszystkie źródła',
      it: 'Tutte le origini',
      sk: 'Všetky zdroje',
      ja: 'すべての発生元',
      ko: '모든 출처',
      hi: 'सभी स्रोत',
      nl: 'Alle bronnen',
      sv: 'Alla källor',
      vi: 'Tất cả nguồn',
      id: 'Semua sumber',
    }),
    sourceTransaction: t({
      ru: 'Транзакция',
      en: 'Transaction',
      kk: 'Транзакция',
      de: 'Transaktion',
      fr: 'Transaction',
      es: 'Transacción',
      pt: 'Transação',
      tr: 'İşlem',
      uk: 'Транзакція',
      zh: '交易',
      ar: 'معاملة',
      pl: 'Transakcja',
      it: 'Transazione',
      sk: 'Transakcia',
      ja: '取引',
      ko: '거래',
      hi: 'लेनदेन',
      nl: 'Transactie',
      sv: 'Transaktion',
      vi: 'Giao dịch',
      id: 'Transaksi',
    }),
    sourceManual: t({
      ru: 'Ручная',
      en: 'Manual',
      kk: 'Қолмен',
      de: 'Manuell',
      fr: 'Manuelle',
      es: 'Manual',
      pt: 'Manual',
      tr: 'Manuel',
      uk: 'Ручна',
      zh: '手工',
      ar: 'يدوي',
      pl: 'Ręczne',
      it: 'Manuale',
      sk: 'Ručný',
      ja: '手動',
      ko: '수동',
      hi: 'मैनुअल',
      nl: 'Handmatig',
      sv: 'Manuell',
      vi: 'Thủ công',
      id: 'Manual',
    }),
    sourceOpening: t({
      ru: 'Входящий остаток',
      en: 'Opening balance',
      kk: 'Кіріс қалдық',
      de: 'Eröffnungssaldo',
      fr: "Solde d'ouverture",
      es: 'Saldo de apertura',
      pt: 'Saldo inicial',
      tr: 'Açılış bakiyesi',
      uk: 'Вхідний залишок',
      zh: '期初余额',
      ar: 'رصيد افتتاحي',
      pl: 'Saldo otwarcia',
      it: 'Saldo di apertura',
      sk: 'Počiatočný zostatok',
      ja: '期首残高',
      ko: '기초 잔액',
      hi: 'प्रारंभिक शेष',
      nl: 'Beginsaldo',
      sv: 'Ingående saldo',
      vi: 'Số dư đầu kỳ',
      id: 'Saldo awal',
    }),
    sourceFx: t({
      ru: 'Переоценка',
      en: 'FX revaluation',
      kk: 'Қайта бағалау',
      de: 'Währungsbewertung',
      fr: 'Réévaluation de change',
      es: 'Revalorización cambiaria',
      pt: 'Reavaliação cambial',
      tr: 'Kur değerlemesi',
      uk: 'Переоцінка',
      zh: '汇率重估',
      ar: 'إعادة تقييم العملة',
      pl: 'Przeszacowanie walut',
      it: 'Rivalutazione cambi',
      sk: 'Kurzové precenenie',
      ja: '為替換算',
      ko: '외화 환산',
      hi: 'विनिमय पुनर्मूल्यांकन',
      nl: 'Valutaherwaardering',
      sv: 'Valutaomvärdering',
      vi: 'Đánh giá lại ngoại tệ',
      id: 'Revaluasi kurs',
    }),
    colNo: t({
      ru: '№',
      en: 'No.',
      kk: '№',
      de: 'Nr.',
      fr: 'N°',
      es: 'N.º',
      pt: 'N.º',
      tr: 'No',
      uk: '№',
      zh: '编号',
      ar: 'رقم',
      pl: 'Nr',
      it: 'N.',
      sk: 'Č.',
      ja: '番号',
      ko: '번호',
      hi: 'क्र.',
      nl: 'Nr.',
      sv: 'Nr',
      vi: 'Số',
      id: 'No.',
    }),
    colDate: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
    }),
    colMemo: t({
      ru: 'Описание',
      en: 'Description',
      kk: 'Сипаттама',
      de: 'Beschreibung',
      fr: 'Libellé',
      es: 'Descripción',
      pt: 'Descrição',
      tr: 'Açıklama',
      uk: 'Опис',
      zh: '摘要',
      ar: 'الوصف',
      pl: 'Opis',
      it: 'Descrizione',
      sk: 'Popis',
      ja: '摘要',
      ko: '적요',
      hi: 'विवरण',
      nl: 'Omschrijving',
      sv: 'Beskrivning',
      vi: 'Diễn giải',
      id: 'Keterangan',
    }),
    colSource: t({
      ru: 'Источник',
      en: 'Source',
      kk: 'Көзі',
      de: 'Quelle',
      fr: 'Origine',
      es: 'Origen',
      pt: 'Origem',
      tr: 'Kaynak',
      uk: 'Джерело',
      zh: '来源',
      ar: 'المصدر',
      pl: 'Źródło',
      it: 'Origine',
      sk: 'Zdroj',
      ja: '発生元',
      ko: '출처',
      hi: 'स्रोत',
      nl: 'Bron',
      sv: 'Källa',
      vi: 'Nguồn',
      id: 'Sumber',
    }),
    colStatus: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Estado',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Status',
      it: 'Stato',
      sk: 'Stav',
      ja: '状態',
      ko: '상태',
      hi: 'स्थिति',
      nl: 'Status',
      sv: 'Status',
      vi: 'Trạng thái',
      id: 'Status',
    }),
    colAmount: t({
      ru: 'Сумма',
      en: 'Amount',
      kk: 'Сома',
      de: 'Betrag',
      fr: 'Montant',
      es: 'Importe',
      pt: 'Montante',
      tr: 'Tutar',
      uk: 'Сума',
      zh: '金额',
      ar: 'المبلغ',
      pl: 'Kwota',
      it: 'Importo',
      sk: 'Suma',
      ja: '金額',
      ko: '금액',
      hi: 'राशि',
      nl: 'Bedrag',
      sv: 'Belopp',
      vi: 'Số tiền',
      id: 'Jumlah',
    }),
    emptyJournal: t({
      ru: 'Проводок пока нет',
      en: 'No entries yet',
      kk: 'Әзірге жазбалар жоқ',
      de: 'Noch keine Buchungen',
      fr: "Aucune écriture pour l'instant",
      es: 'Aún no hay asientos',
      pt: 'Ainda não há lançamentos',
      tr: 'Henüz kayıt yok',
      uk: 'Проводок поки немає',
      zh: '暂无分录',
      ar: 'لا توجد قيود بعد',
      pl: 'Brak księgowań',
      it: 'Nessuna scrittura per ora',
      sk: 'Zatiaľ žiadne zápisy',
      ja: '仕訳はまだありません',
      ko: '아직 분개가 없습니다',
      hi: 'अभी कोई प्रविष्टि नहीं',
      nl: 'Nog geen boekingen',
      sv: 'Inga verifikationer ännu',
      vi: 'Chưa có bút toán',
      id: 'Belum ada jurnal',
    }),
    reversal: t({
      ru: 'Сторно',
      en: 'Reversal',
      kk: 'Сторно',
      de: 'Storno',
      fr: 'Contrepassation',
      es: 'Anulación',
      pt: 'Estorno',
      tr: 'Ters kayıt',
      uk: 'Сторно',
      zh: '冲销',
      ar: 'قيد عكسي',
      pl: 'Storno',
      it: 'Storno',
      sk: 'Storno',
      ja: '取消仕訳',
      ko: '역분개',
      hi: 'उलट प्रविष्टि',
      nl: 'Tegenboeking',
      sv: 'Makulering',
      vi: 'Bút toán đảo',
      id: 'Jurnal balik',
    }),
    entryTitle: t({
      ru: 'Проводка',
      en: 'Entry',
      kk: 'Жазба',
      de: 'Buchung',
      fr: 'Écriture',
      es: 'Asiento',
      pt: 'Lançamento',
      tr: 'Kayıt',
      uk: 'Проводка',
      zh: '分录',
      ar: 'قيد',
      pl: 'Księgowanie',
      it: 'Scrittura',
      sk: 'Zápis',
      ja: '仕訳',
      ko: '분개',
      hi: 'प्रविष्टि',
      nl: 'Boeking',
      sv: 'Verifikation',
      vi: 'Bút toán',
      id: 'Jurnal',
    }),
    draftTitle: t({
      ru: 'Черновик проводки',
      en: 'Draft entry',
      kk: 'Жазба жобасы',
      de: 'Buchungsentwurf',
      fr: "Brouillon d'écriture",
      es: 'Borrador de asiento',
      pt: 'Rascunho de lançamento',
      tr: 'Taslak kayıt',
      uk: 'Чернетка проводки',
      zh: '分录草稿',
      ar: 'مسودة قيد',
      pl: 'Szkic księgowania',
      it: 'Bozza di scrittura',
      sk: 'Koncept zápisu',
      ja: '仕訳の下書き',
      ko: '분개 초안',
      hi: 'मसौदा प्रविष्टि',
      nl: 'Conceptboeking',
      sv: 'Utkast till verifikation',
      vi: 'Bút toán nháp',
      id: 'Draf jurnal',
    }),
    dateLabel: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
    }),
    memoLabel: t({
      ru: 'Описание',
      en: 'Description',
      kk: 'Сипаттама',
      de: 'Beschreibung',
      fr: 'Libellé',
      es: 'Descripción',
      pt: 'Descrição',
      tr: 'Açıklama',
      uk: 'Опис',
      zh: '摘要',
      ar: 'الوصف',
      pl: 'Opis',
      it: 'Descrizione',
      sk: 'Popis',
      ja: '摘要',
      ko: '적요',
      hi: 'विवरण',
      nl: 'Omschrijving',
      sv: 'Beskrivning',
      vi: 'Diễn giải',
      id: 'Keterangan',
    }),
    accountLabel: t({
      ru: 'Счёт',
      en: 'Account',
      kk: 'Шот',
      de: 'Konto',
      fr: 'Compte',
      es: 'Cuenta',
      pt: 'Conta',
      tr: 'Hesap',
      uk: 'Рахунок',
      zh: '科目',
      ar: 'الحساب',
      pl: 'Konto',
      it: 'Conto',
      sk: 'Účet',
      ja: '勘定科目',
      ko: '계정',
      hi: 'खाता',
      nl: 'Rekening',
      sv: 'Konto',
      vi: 'Tài khoản',
      id: 'Akun',
    }),
    selectAccount: t({
      ru: 'Выберите счёт',
      en: 'Select an account',
      kk: 'Шотты таңдаңыз',
      de: 'Konto wählen',
      fr: 'Choisissez un compte',
      es: 'Selecciona una cuenta',
      pt: 'Selecione uma conta',
      tr: 'Hesap seçin',
      uk: 'Виберіть рахунок',
      zh: '选择科目',
      ar: 'اختر حسابًا',
      pl: 'Wybierz konto',
      it: 'Seleziona un conto',
      sk: 'Vyberte účet',
      ja: '勘定科目を選択',
      ko: '계정을 선택하세요',
      hi: 'खाता चुनें',
      nl: 'Kies een rekening',
      sv: 'Välj ett konto',
      vi: 'Chọn tài khoản',
      id: 'Pilih akun',
    }),
    sideLabel: t({
      ru: 'Сторона',
      en: 'Side',
      kk: 'Жағы',
      de: 'Seite',
      fr: 'Sens',
      es: 'Lado',
      pt: 'Lado',
      tr: 'Taraf',
      uk: 'Сторона',
      zh: '方向',
      ar: 'الجانب',
      pl: 'Strona',
      it: 'Lato',
      sk: 'Strana',
      ja: '貸借',
      ko: '차대',
      hi: 'पक्ष',
      nl: 'Zijde',
      sv: 'Sida',
      vi: 'Bên',
      id: 'Sisi',
    }),
    sideDebit: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Debe',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      ar: 'مدين',
      pl: 'Winien',
      it: 'Dare',
      sk: 'Má dať',
      ja: '借方',
      ko: '차변',
      hi: 'नामे',
      nl: 'Debet',
      sv: 'Debet',
      vi: 'Nợ',
      id: 'Debit',
    }),
    sideCredit: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Haber',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      ar: 'دائن',
      pl: 'Ma',
      it: 'Avere',
      sk: 'Dal',
      ja: '貸方',
      ko: '대변',
      hi: 'जमा',
      nl: 'Credit',
      sv: 'Kredit',
      vi: 'Có',
      id: 'Kredit',
    }),
    amountLabel: t({
      ru: 'Сумма',
      en: 'Amount',
      kk: 'Сома',
      de: 'Betrag',
      fr: 'Montant',
      es: 'Importe',
      pt: 'Montante',
      tr: 'Tutar',
      uk: 'Сума',
      zh: '金额',
      ar: 'المبلغ',
      pl: 'Kwota',
      it: 'Importo',
      sk: 'Suma',
      ja: '金額',
      ko: '금액',
      hi: 'राशि',
      nl: 'Bedrag',
      sv: 'Belopp',
      vi: 'Số tiền',
      id: 'Jumlah',
    }),
    currencyLabel: t({
      ru: 'Валюта',
      en: 'Currency',
      kk: 'Валюта',
      de: 'Währung',
      fr: 'Devise',
      es: 'Moneda',
      pt: 'Moeda',
      tr: 'Para birimi',
      uk: 'Валюта',
      zh: '币种',
      ar: 'العملة',
      pl: 'Waluta',
      it: 'Valuta',
      sk: 'Mena',
      ja: '通貨',
      ko: '통화',
      hi: 'मुद्रा',
      nl: 'Valuta',
      sv: 'Valuta',
      vi: 'Tiền tệ',
      id: 'Mata uang',
    }),
    addLine: t({
      ru: 'Добавить строку',
      en: 'Add line',
      kk: 'Жол қосу',
      de: 'Zeile hinzufügen',
      fr: 'Ajouter une ligne',
      es: 'Añadir línea',
      pt: 'Adicionar linha',
      tr: 'Satır ekle',
      uk: 'Додати рядок',
      zh: '添加行',
      ar: 'إضافة سطر',
      pl: 'Dodaj wiersz',
      it: 'Aggiungi riga',
      sk: 'Pridať riadok',
      ja: '行を追加',
      ko: '행 추가',
      hi: 'पंक्ति जोड़ें',
      nl: 'Regel toevoegen',
      sv: 'Lägg till rad',
      vi: 'Thêm dòng',
      id: 'Tambah baris',
    }),
    removeLine: t({
      ru: 'Удалить строку',
      en: 'Remove line',
      kk: 'Жолды жою',
      de: 'Zeile entfernen',
      fr: 'Supprimer la ligne',
      es: 'Quitar línea',
      pt: 'Remover linha',
      tr: 'Satırı kaldır',
      uk: 'Видалити рядок',
      zh: '删除行',
      ar: 'إزالة السطر',
      pl: 'Usuń wiersz',
      it: 'Rimuovi riga',
      sk: 'Odstrániť riadok',
      ja: '行を削除',
      ko: '행 삭제',
      hi: 'पंक्ति हटाएँ',
      nl: 'Regel verwijderen',
      sv: 'Ta bort rad',
      vi: 'Xóa dòng',
      id: 'Hapus baris',
    }),
    difference: t({
      ru: 'Расхождение',
      en: 'Difference',
      kk: 'Айырма',
      de: 'Differenz',
      fr: 'Écart',
      es: 'Diferencia',
      pt: 'Diferença',
      tr: 'Fark',
      uk: 'Розбіжність',
      zh: '差额',
      ar: 'الفرق',
      pl: 'Różnica',
      it: 'Differenza',
      sk: 'Rozdiel',
      ja: '差額',
      ko: '차이',
      hi: 'अंतर',
      nl: 'Verschil',
      sv: 'Differens',
      vi: 'Chênh lệch',
      id: 'Selisih',
    }),
    balanced: t({
      ru: 'Сбалансировано',
      en: 'Balanced',
      kk: 'Теңгерілген',
      de: 'Ausgeglichen',
      fr: 'Équilibrée',
      es: 'Cuadrado',
      pt: 'Equilibrado',
      tr: 'Dengeli',
      uk: 'Збалансовано',
      zh: '已平衡',
      ar: 'متوازن',
      pl: 'Zbilansowane',
      it: 'Bilanciata',
      sk: 'Vyrovnané',
      ja: '一致',
      ko: '대차 일치',
      hi: 'संतुलित',
      nl: 'In balans',
      sv: 'Balanserad',
      vi: 'Cân bằng',
      id: 'Seimbang',
    }),
    foreignNote: t({
      ru: 'Строки в другой валюте пересчитываются при сохранении черновика',
      en: 'Lines in other currencies are converted when the draft is saved',
      kk: 'Басқа валютадағы жолдар жоба сақталғанда қайта есептеледі',
      de: 'Zeilen in anderen Währungen werden beim Speichern umgerechnet',
      fr: "Les lignes en autres devises sont converties à l'enregistrement du brouillon",
      es: 'Las líneas en otras monedas se convierten al guardar el borrador',
      pt: 'As linhas noutras moedas são convertidas ao guardar o rascunho',
      tr: 'Diğer para birimlerindeki satırlar taslak kaydedilince çevrilir',
      uk: 'Рядки в іншій валюті перераховуються під час збереження чернетки',
      zh: '其他币种的行会在保存草稿时换算',
      ar: 'تُحوَّل الأسطر بعملات أخرى عند حفظ المسودة',
      pl: 'Wiersze w innych walutach są przeliczane przy zapisie szkicu',
      it: 'Le righe in altre valute vengono convertite al salvataggio della bozza',
      sk: 'Riadky v iných menách sa prepočítajú pri uložení konceptu',
      ja: '他通貨の行は下書きの保存時に換算されます',
      ko: '다른 통화의 행은 초안 저장 시 환산됩니다',
      hi: 'अन्य मुद्राओं की पंक्तियाँ मसौदा सहेजने पर बदली जाती हैं',
      nl: 'Regels in andere valuta worden omgerekend bij het opslaan',
      sv: 'Rader i andra valutor räknas om när utkastet sparas',
      vi: 'Dòng bằng tiền tệ khác được quy đổi khi lưu bản nháp',
      id: 'Baris dalam mata uang lain dikonversi saat draf disimpan',
    }),
    saveDraft: t({
      ru: 'Сохранить черновик',
      en: 'Save draft',
      kk: 'Жобаны сақтау',
      de: 'Entwurf speichern',
      fr: 'Enregistrer le brouillon',
      es: 'Guardar borrador',
      pt: 'Guardar rascunho',
      tr: 'Taslağı kaydet',
      uk: 'Зберегти чернетку',
      zh: '保存草稿',
      ar: 'حفظ المسودة',
      pl: 'Zapisz szkic',
      it: 'Salva bozza',
      sk: 'Uložiť koncept',
      ja: '下書きを保存',
      ko: '초안 저장',
      hi: 'मसौदा सहेजें',
      nl: 'Concept opslaan',
      sv: 'Spara utkast',
      vi: 'Lưu nháp',
      id: 'Simpan draf',
    }),
    post: t({
      ru: 'Провести',
      en: 'Post',
      kk: 'Өткізу',
      de: 'Buchen',
      fr: 'Comptabiliser',
      es: 'Registrar',
      pt: 'Lançar',
      tr: 'Kaydet ve işle',
      uk: 'Провести',
      zh: '过账',
      ar: 'ترحيل',
      pl: 'Zaksięguj',
      it: 'Registra',
      sk: 'Zaúčtovať',
      ja: '計上',
      ko: '기록',
      hi: 'दर्ज करें',
      nl: 'Boeken',
      sv: 'Bokför',
      vi: 'Ghi sổ',
      id: 'Bukukan',
    }),
    deleteDraft: t({
      ru: 'Удалить черновик',
      en: 'Delete draft',
      kk: 'Жобаны жою',
      de: 'Entwurf löschen',
      fr: 'Supprimer le brouillon',
      es: 'Eliminar borrador',
      pt: 'Eliminar rascunho',
      tr: 'Taslağı sil',
      uk: 'Видалити чернетку',
      zh: '删除草稿',
      ar: 'حذف المسودة',
      pl: 'Usuń szkic',
      it: 'Elimina bozza',
      sk: 'Odstrániť koncept',
      ja: '下書きを削除',
      ko: '초안 삭제',
      hi: 'मसौदा हटाएँ',
      nl: 'Concept verwijderen',
      sv: 'Ta bort utkast',
      vi: 'Xóa nháp',
      id: 'Hapus draf',
    }),
    postHint: t({
      ru: 'Чтобы провести, сохраните сбалансированный черновик',
      en: 'Save a balanced draft to post it',
      kk: 'Өткізу үшін теңгерілген жобаны сақтаңыз',
      de: 'Speichern Sie einen ausgeglichenen Entwurf, um ihn zu buchen',
      fr: 'Enregistrez un brouillon équilibré pour le comptabiliser',
      es: 'Guarda un borrador cuadrado para registrarlo',
      pt: 'Guarde um rascunho equilibrado para o lançar',
      tr: 'İşlemek için dengeli bir taslak kaydedin',
      uk: 'Щоб провести, збережіть збалансовану чернетку',
      zh: '保存一份借贷平衡的草稿后即可过账',
      ar: 'احفظ مسودة متوازنة لترحيلها',
      pl: 'Zapisz zbilansowany szkic, aby go zaksięgować',
      it: 'Salva una bozza bilanciata per registrarla',
      sk: 'Uložte vyrovnaný koncept, aby ste ho mohli zaúčtovať',
      ja: '貸借一致の下書きを保存すると計上できます',
      ko: '대차가 일치하는 초안을 저장하면 기록할 수 있습니다',
      hi: 'दर्ज करने के लिए संतुलित मसौदा सहेजें',
      nl: 'Sla een sluitend concept op om het te boeken',
      sv: 'Spara ett balanserat utkast för att bokföra det',
      vi: 'Lưu bản nháp cân bằng để ghi sổ',
      id: 'Simpan draf yang seimbang untuk membukukannya',
    }),
    unsavedChanges: t({
      ru: 'Есть несохранённые изменения',
      en: 'There are unsaved changes',
      kk: 'Сақталмаған өзгерістер бар',
      de: 'Es gibt ungespeicherte Änderungen',
      fr: 'Des modifications ne sont pas enregistrées',
      es: 'Hay cambios sin guardar',
      pt: 'Há alterações por guardar',
      tr: 'Kaydedilmemiş değişiklikler var',
      uk: 'Є незбережені зміни',
      zh: '有未保存的更改',
      ar: 'توجد تغييرات غير محفوظة',
      pl: 'Są niezapisane zmiany',
      it: 'Ci sono modifiche non salvate',
      sk: 'Sú neuložené zmeny',
      ja: '未保存の変更があります',
      ko: '저장하지 않은 변경 사항이 있습니다',
      hi: 'सहेजे न गए बदलाव हैं',
      nl: 'Er zijn niet-opgeslagen wijzigingen',
      sv: 'Det finns osparade ändringar',
      vi: 'Có thay đổi chưa lưu',
      id: 'Ada perubahan yang belum disimpan',
    }),
    totalsLabel: t({
      ru: 'Итого',
      en: 'Total',
      kk: 'Барлығы',
      de: 'Summe',
      fr: 'Total',
      es: 'Total',
      pt: 'Total',
      tr: 'Toplam',
      uk: 'Разом',
      zh: '合计',
      ar: 'الإجمالي',
      pl: 'Razem',
      it: 'Totale',
      sk: 'Spolu',
      ja: '合計',
      ko: '합계',
      hi: 'कुल',
      nl: 'Totaal',
      sv: 'Summa',
      vi: 'Tổng',
      id: 'Total',
    }),
    reverse: t({
      ru: 'Сторнировать',
      en: 'Reverse',
      kk: 'Сторнолау',
      de: 'Stornieren',
      fr: 'Contrepasser',
      es: 'Anular',
      pt: 'Estornar',
      tr: 'Ters kayıt yap',
      uk: 'Сторнувати',
      zh: '冲销',
      ar: 'عكس القيد',
      pl: 'Stornuj',
      it: 'Storna',
      sk: 'Stornovať',
      ja: '取り消す',
      ko: '역분개',
      hi: 'उलटें',
      nl: 'Tegenboeken',
      sv: 'Makulera',
      vi: 'Đảo bút toán',
      id: 'Balik',
    }),
    reverseConfirm: t({
      ru: 'Провести зеркальную проводку, которая отменит эту?',
      en: 'Post a mirror entry that cancels this one?',
      kk: 'Мұны жоятын айна жазбаны өткізу керек пе?',
      de: 'Eine Gegenbuchung erfassen, die diese aufhebt?',
      fr: 'Passer une écriture miroir qui annule celle-ci ?',
      es: '¿Registrar un asiento espejo que anule este?',
      pt: 'Lançar um lançamento espelho que anula este?',
      tr: 'Bunu iptal eden ayna bir kayıt işlensin mi?',
      uk: 'Провести дзеркальну проводку, яка скасує цю?',
      zh: '过一笔抵消此分录的反向分录？',
      ar: 'ترحيل قيد معاكس يلغي هذا القيد؟',
      pl: 'Zaksięgować zapis lustrzany, który anuluje ten?',
      it: 'Registrare una scrittura speculare che annulli questa?',
      sk: 'Zaúčtovať zrkadlový zápis, ktorý zruší tento?',
      ja: 'この仕訳を打ち消す反対仕訳を計上しますか？',
      ko: '이 분개를 상쇄하는 반대 분개를 기록할까요?',
      hi: 'इसे रद्द करने वाली उलटी प्रविष्टि दर्ज करें?',
      nl: 'Een spiegelboeking maken die deze opheft?',
      sv: 'Bokföra en spegelverifikation som tar ut denna?',
      vi: 'Ghi bút toán đối ứng để hủy bút toán này?',
      id: 'Bukukan jurnal cermin yang membatalkan jurnal ini?',
    }),
    reversedBy: t({
      ru: 'Открыть сторнирующую проводку',
      en: 'Open the reversing entry',
      kk: 'Сторно жазбасын ашу',
      de: 'Stornobuchung öffnen',
      fr: "Ouvrir l'écriture de contrepassation",
      es: 'Abrir el asiento de anulación',
      pt: 'Abrir o lançamento de estorno',
      tr: 'Ters kaydı aç',
      uk: 'Відкрити сторнувальну проводку',
      zh: '打开冲销分录',
      ar: 'فتح القيد العكسي',
      pl: 'Otwórz zapis stornujący',
      it: 'Apri la scrittura di storno',
      sk: 'Otvoriť stornovací zápis',
      ja: '取消仕訳を開く',
      ko: '역분개 열기',
      hi: 'उलट प्रविष्टि खोलें',
      nl: 'Tegenboeking openen',
      sv: 'Öppna makuleringen',
      vi: 'Mở bút toán đảo',
      id: 'Buka jurnal balik',
    }),
    dateFrom: t({
      ru: 'С',
      en: 'From',
      kk: 'Бастап',
      de: 'Von',
      fr: 'Du',
      es: 'Desde',
      pt: 'De',
      tr: 'Başlangıç',
      uk: 'З',
      zh: '从',
      ar: 'من',
      pl: 'Od',
      it: 'Dal',
      sk: 'Od',
      ja: '開始',
      ko: '시작',
      hi: 'से',
      nl: 'Van',
      sv: 'Från',
      vi: 'Từ',
      id: 'Dari',
    }),
    dateTo: t({
      ru: 'По',
      en: 'To',
      kk: 'Дейін',
      de: 'Bis',
      fr: 'Au',
      es: 'Hasta',
      pt: 'Até',
      tr: 'Bitiş',
      uk: 'По',
      zh: '至',
      ar: 'إلى',
      pl: 'Do',
      it: 'Al',
      sk: 'Do',
      ja: '終了',
      ko: '끝',
      hi: 'तक',
      nl: 'Tot',
      sv: 'Till',
      vi: 'Đến',
      id: 'Sampai',
    }),
    colOpening: t({
      ru: 'Сальдо на начало',
      en: 'Opening balance',
      kk: 'Бастапқы сальдо',
      de: 'Anfangssaldo',
      fr: "Solde d'ouverture",
      es: 'Saldo inicial',
      pt: 'Saldo inicial',
      tr: 'Açılış bakiyesi',
      uk: 'Сальдо на початок',
      zh: '期初余额',
      ar: 'الرصيد الافتتاحي',
      pl: 'Saldo początkowe',
      it: 'Saldo iniziale',
      sk: 'Počiatočný stav',
      ja: '期首残高',
      ko: '기초 잔액',
      hi: 'प्रारंभिक शेष',
      nl: 'Beginsaldo',
      sv: 'Ingående saldo',
      vi: 'Số dư đầu kỳ',
      id: 'Saldo awal',
    }),
    colTurnover: t({
      ru: 'Обороты за период',
      en: 'Turnover',
      kk: 'Кезеңдегі айналым',
      de: 'Umsätze',
      fr: 'Mouvements',
      es: 'Movimientos',
      pt: 'Movimentos',
      tr: 'Dönem hareketleri',
      uk: 'Обороти за період',
      zh: '本期发生额',
      ar: 'الحركة',
      pl: 'Obroty',
      it: 'Movimenti',
      sk: 'Obraty',
      ja: '期中取引高',
      ko: '기중 발생액',
      hi: 'कारोबार',
      nl: 'Mutaties',
      sv: 'Omsättning',
      vi: 'Số phát sinh',
      id: 'Mutasi',
    }),
    colClosing: t({
      ru: 'Сальдо на конец',
      en: 'Closing balance',
      kk: 'Соңғы сальдо',
      de: 'Endsaldo',
      fr: 'Solde de clôture',
      es: 'Saldo final',
      pt: 'Saldo final',
      tr: 'Kapanış bakiyesi',
      uk: 'Сальдо на кінець',
      zh: '期末余额',
      ar: 'الرصيد الختامي',
      pl: 'Saldo końcowe',
      it: 'Saldo finale',
      sk: 'Konečný stav',
      ja: '期末残高',
      ko: '기말 잔액',
      hi: 'समापन शेष',
      nl: 'Eindsaldo',
      sv: 'Utgående saldo',
      vi: 'Số dư cuối kỳ',
      id: 'Saldo akhir',
    }),
    totalRow: t({
      ru: 'Итого',
      en: 'Total',
      kk: 'Барлығы',
      de: 'Summe',
      fr: 'Total',
      es: 'Total',
      pt: 'Total',
      tr: 'Toplam',
      uk: 'Разом',
      zh: '合计',
      ar: 'الإجمالي',
      pl: 'Razem',
      it: 'Totale',
      sk: 'Spolu',
      ja: '合計',
      ko: '합계',
      hi: 'कुल',
      nl: 'Totaal',
      sv: 'Summa',
      vi: 'Tổng',
      id: 'Total',
    }),
    balancedBadge: t({
      ru: 'Сходится',
      en: 'Balanced',
      kk: 'Теңгерілген',
      de: 'Ausgeglichen',
      fr: 'Équilibrée',
      es: 'Cuadra',
      pt: 'Equilibrado',
      tr: 'Dengeli',
      uk: 'Сходиться',
      zh: '平衡',
      ar: 'متوازن',
      pl: 'Zbilansowane',
      it: 'Quadra',
      sk: 'Vyrovnané',
      ja: '一致',
      ko: '일치',
      hi: 'संतुलित',
      nl: 'Sluitend',
      sv: 'Balanserad',
      vi: 'Cân bằng',
      id: 'Seimbang',
    }),
    unbalancedBadge: t({
      ru: 'Не сходится',
      en: 'Out of balance',
      kk: 'Теңгерілмеген',
      de: 'Nicht ausgeglichen',
      fr: 'Déséquilibrée',
      es: 'No cuadra',
      pt: 'Desequilibrado',
      tr: 'Dengesiz',
      uk: 'Не сходиться',
      zh: '不平衡',
      ar: 'غير متوازن',
      pl: 'Niezbilansowane',
      it: 'Non quadra',
      sk: 'Nevyrovnané',
      ja: '不一致',
      ko: '불일치',
      hi: 'असंतुलित',
      nl: 'Niet sluitend',
      sv: 'Obalanserad',
      vi: 'Không cân bằng',
      id: 'Tidak seimbang',
    }),
    staleTitle: t({
      ru: 'Реестр ещё догоняет транзакции.',
      en: 'The ledger is still catching up.',
      kk: 'Тізілім әлі транзакцияларды қуып жетуде.',
      de: 'Das Hauptbuch holt noch auf.',
      fr: 'Le grand livre est encore en cours de rattrapage.',
      es: 'El libro mayor aún se está poniendo al día.',
      pt: 'O livro-razão ainda está a atualizar.',
      tr: 'Defteri kebir hâlâ güncelleniyor.',
      uk: 'Реєстр ще наздоганяє транзакції.',
      zh: '总账仍在同步中。',
      ar: 'لا يزال دفتر الأستاذ يلحق بالمعاملات.',
      pl: 'Księga wciąż nadrabia zaległości.',
      it: 'Il libro mastro sta ancora recuperando.',
      sk: 'Hlavná kniha ešte dobieha.',
      ja: '元帳はまだ反映中です。',
      ko: '원장이 아직 반영 중입니다.',
      hi: 'खाता बही अभी अद्यतन हो रही है।',
      nl: 'Het grootboek loopt nog achter.',
      sv: 'Huvudboken håller fortfarande på att komma ikapp.',
      vi: 'Sổ cái vẫn đang cập nhật.',
      id: 'Buku besar masih mengejar.',
    }),
    staleText: t({
      ru: 'Часть транзакций ещё не проведена, поэтому отчёт будет неполным.',
      en: 'Some transactions are not posted yet, so the report would be incomplete.',
      kk: 'Кейбір транзакциялар әлі өткізілмеген, сондықтан есеп толық болмайды.',
      de: 'Einige Transaktionen sind noch nicht gebucht, der Bericht wäre unvollständig.',
      fr: 'Certaines transactions ne sont pas encore comptabilisées : le rapport serait incomplet.',
      es: 'Algunas transacciones aún no están registradas, así que el informe estaría incompleto.',
      pt: 'Algumas transações ainda não foram lançadas, pelo que o relatório ficaria incompleto.',
      tr: 'Bazı işlemler henüz işlenmedi, bu yüzden rapor eksik olur.',
      uk: 'Частину транзакцій ще не проведено, тому звіт буде неповним.',
      zh: '部分交易尚未过账，报表将不完整。',
      ar: 'لم تُرحَّل بعض المعاملات بعد، لذا سيكون التقرير ناقصًا.',
      pl: 'Część transakcji nie jest jeszcze zaksięgowana, więc raport byłby niepełny.',
      it: 'Alcune transazioni non sono ancora registrate: il report sarebbe incompleto.',
      sk: 'Niektoré transakcie ešte nie sú zaúčtované, takže prehľad by bol neúplný.',
      ja: '一部の取引がまだ計上されていないため、レポートは不完全になります。',
      ko: '일부 거래가 아직 기록되지 않아 보고서가 불완전합니다.',
      hi: 'कुछ लेनदेन अभी दर्ज नहीं हुए, इसलिए रिपोर्ट अधूरी होगी।',
      nl: 'Sommige transacties zijn nog niet geboekt, het rapport zou onvolledig zijn.',
      sv: 'Vissa transaktioner är inte bokförda än, så rapporten blir ofullständig.',
      vi: 'Một số giao dịch chưa được ghi sổ nên báo cáo sẽ chưa đầy đủ.',
      id: 'Beberapa transaksi belum dibukukan sehingga laporan belum lengkap.',
    }),
    showAnyway: t({
      ru: 'Всё равно показать',
      en: 'Show anyway',
      kk: 'Бәрібір көрсету',
      de: 'Trotzdem anzeigen',
      fr: 'Afficher quand même',
      es: 'Mostrar de todos modos',
      pt: 'Mostrar mesmo assim',
      tr: 'Yine de göster',
      uk: 'Усе одно показати',
      zh: '仍然显示',
      ar: 'اعرض على أي حال',
      pl: 'Pokaż mimo to',
      it: 'Mostra comunque',
      sk: 'Aj tak zobraziť',
      ja: 'それでも表示',
      ko: '그래도 표시',
      hi: 'फिर भी दिखाएँ',
      nl: 'Toch tonen',
      sv: 'Visa ändå',
      vi: 'Vẫn hiển thị',
      id: 'Tetap tampilkan',
    }),
    staleShown: t({
      ru: 'Показано до проведения всех транзакций',
      en: 'Shown before every transaction was posted',
      kk: 'Барлық транзакциялар өткізілмей тұрып көрсетілді',
      de: 'Angezeigt, bevor alle Transaktionen gebucht waren',
      fr: 'Affiché avant la comptabilisation de toutes les transactions',
      es: 'Mostrado antes de registrar todas las transacciones',
      pt: 'Mostrado antes de todas as transações serem lançadas',
      tr: 'Tüm işlemler işlenmeden gösterildi',
      uk: 'Показано до проведення всіх транзакцій',
      zh: '在全部交易过账前显示',
      ar: 'معروض قبل ترحيل كل المعاملات',
      pl: 'Pokazano przed zaksięgowaniem wszystkich transakcji',
      it: 'Mostrato prima della registrazione di tutte le transazioni',
      sk: 'Zobrazené pred zaúčtovaním všetkých transakcií',
      ja: 'すべての取引の計上前に表示',
      ko: '모든 거래 기록 전에 표시됨',
      hi: 'सभी लेनदेन दर्ज होने से पहले दिखाया गया',
      nl: 'Getoond voordat alle transacties geboekt waren',
      sv: 'Visas innan alla transaktioner bokförts',
      vi: 'Hiển thị trước khi ghi sổ đủ giao dịch',
      id: 'Ditampilkan sebelum semua transaksi dibukukan',
    }),
    openingBalance: t({
      ru: 'Остаток на начало',
      en: 'Opening balance',
      kk: 'Бастапқы қалдық',
      de: 'Anfangssaldo',
      fr: "Solde d'ouverture",
      es: 'Saldo inicial',
      pt: 'Saldo inicial',
      tr: 'Açılış bakiyesi',
      uk: 'Залишок на початок',
      zh: '期初余额',
      ar: 'الرصيد الافتتاحي',
      pl: 'Saldo początkowe',
      it: 'Saldo iniziale',
      sk: 'Počiatočný zostatok',
      ja: '期首残高',
      ko: '기초 잔액',
      hi: 'प्रारंभिक शेष',
      nl: 'Beginsaldo',
      sv: 'Ingående saldo',
      vi: 'Số dư đầu kỳ',
      id: 'Saldo awal',
    }),
    closingBalance: t({
      ru: 'Остаток на конец',
      en: 'Closing balance',
      kk: 'Соңғы қалдық',
      de: 'Endsaldo',
      fr: 'Solde de clôture',
      es: 'Saldo final',
      pt: 'Saldo final',
      tr: 'Kapanış bakiyesi',
      uk: 'Залишок на кінець',
      zh: '期末余额',
      ar: 'الرصيد الختامي',
      pl: 'Saldo końcowe',
      it: 'Saldo finale',
      sk: 'Konečný zostatok',
      ja: '期末残高',
      ko: '기말 잔액',
      hi: 'समापन शेष',
      nl: 'Eindsaldo',
      sv: 'Utgående saldo',
      vi: 'Số dư cuối kỳ',
      id: 'Saldo akhir',
    }),
    colRunning: t({
      ru: 'Остаток',
      en: 'Balance',
      kk: 'Қалдық',
      de: 'Saldo',
      fr: 'Solde',
      es: 'Saldo',
      pt: 'Saldo',
      tr: 'Bakiye',
      uk: 'Залишок',
      zh: '余额',
      ar: 'الرصيد',
      pl: 'Saldo',
      it: 'Saldo',
      sk: 'Zostatok',
      ja: '残高',
      ko: '잔액',
      hi: 'शेष',
      nl: 'Saldo',
      sv: 'Saldo',
      vi: 'Số dư',
      id: 'Saldo',
    }),
    emptyAccount: t({
      ru: 'По этому счёту за период проводок нет',
      en: 'No entries on this account in this period',
      kk: 'Бұл шот бойынша кезеңде жазбалар жоқ',
      de: 'Keine Buchungen auf diesem Konto im Zeitraum',
      fr: 'Aucune écriture sur ce compte pour la période',
      es: 'No hay asientos en esta cuenta en el periodo',
      pt: 'Sem lançamentos nesta conta no período',
      tr: 'Bu dönemde bu hesapta kayıt yok',
      uk: 'За цим рахунком у періоді проводок немає',
      zh: '该科目本期无分录',
      ar: 'لا قيود على هذا الحساب في هذه الفترة',
      pl: 'Brak księgowań na tym koncie w okresie',
      it: 'Nessuna scrittura su questo conto nel periodo',
      sk: 'Na tomto účte nie sú v období žiadne zápisy',
      ja: 'この期間、この勘定に仕訳はありません',
      ko: '이 기간에 이 계정의 분개가 없습니다',
      hi: 'इस अवधि में इस खाते पर कोई प्रविष्टि नहीं',
      nl: 'Geen boekingen op deze rekening in deze periode',
      sv: 'Inga verifikationer på kontot under perioden',
      vi: 'Không có bút toán trên tài khoản này trong kỳ',
      id: 'Tidak ada jurnal pada akun ini dalam periode ini',
    }),
  },
} satisfies Dictionary;

export default content;
