/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'transactionDuplicatesPage',
  content: {
    title: t({
      ru: 'Дубликаты транзакций',
      en: 'Duplicate Transactions',
      kk: 'Қайталанатын транзакциялар',
      de: 'Doppelte Transaktionen',
      fr: 'Transactions en double',
      es: 'Transacciones duplicadas',
      pt: 'Transações duplicadas',
      tr: 'Yinelenen işlemler',
      uk: 'Дублікати транзакцій',
      zh: '重复交易',
      pl: 'Zduplikowane transakcje',
      it: 'Transazioni duplicate',
      sk: 'Duplicitné transakcie',
      ja: '重複した取引',
      ko: '중복 거래',
      hi: 'डुप्लिकेट लेनदेन',
      nl: 'Dubbele transacties',
      sv: 'Dubblerade transaktioner',
      vi: 'Giao dịch trùng lặp',
      id: 'Transaksi duplikat',
      da: 'Dublerede posteringer',
      nb: 'Dupliserte transaksjoner',
      nn: 'Dupliserte transaksjonar',
      fi: 'Kaksoiskappaleet',
      is: 'Tvítaka færslur',
      fo: 'Tvítaknar posteringar',
      cs: 'Duplicitní transakce',
      bg: 'Дублирани транзакции',
      hr: 'Duplicirane transakcije',
      sr: 'Дуплиране трансакције',
      sl: 'Podvojene transakcije',
      mk: 'Дуплирани трансакции',
      be: 'Дубляваныя транзакцыі',
      bs: 'Duplirane transakcije',
      hsb: 'Duplikowane transakcije',
    }),
    subtitle: t({
      ru: 'Проверяйте и управляйте дубликатами транзакций, найденными в выписках',
      en: 'Review and manage duplicate transactions detected across statements',
      kk: 'Үзінділерден табылған қайталанатын транзакцияларды қарап, басқарыңыз',
      de: 'Prüfen und verwalten Sie doppelte Transaktionen aus Ihren Kontoauszügen',
      fr: 'Examinez et gérez les transactions en double détectées dans les relevés',
      es: 'Revisa y gestiona las transacciones duplicadas detectadas en los extractos',
      pt: 'Revise e gerencie transações duplicadas detectadas nos extratos',
      tr: 'Ekstrelerde tespit edilen yinelenen işlemleri inceleyin ve yönetin',
      uk: 'Переглядайте та керуйте дублікатами транзакцій, знайденими у виписках',
      zh: '查看并管理在对账单中检测到的重复交易',
      pl: 'Przeglądaj i zarządzaj zduplikowanymi transakcjami wykrytymi w wyciągach',
      it: 'Esamina e gestisci le transazioni duplicate rilevate negli estratti conto',
      sk: 'Skontrolujte a spravujte duplicitné transakcie zistené vo výpisoch',
      ja: '明細書間で検出された重複取引を確認・管理します',
      ko: '명세서 전반에서 감지된 중복 거래를 검토하고 관리하세요',
      hi: 'विवरणों में पाए गए डुप्लिकेट लेनदेन की समीक्षा और प्रबंधन करें',
      nl: 'Controleer en beheer dubbele transacties uit je afschriften',
      sv: 'Granska och hantera dubblerade transaktioner som hittats i kontoutdrag',
      vi: 'Xem xét và quản lý các giao dịch trùng lặp được phát hiện trong sao kê',
      id: 'Tinjau dan kelola transaksi duplikat yang terdeteksi di mutasi',
      da: 'Gennemgå og håndtér dubletter fundet på tværs af kontoudtog',
      nb: 'Gå gjennom og håndter duplikater funnet på tvers av kontoutskrifter',
      nn: 'Gå gjennom og handter duplikat funne på tvers av kontoutskrifter',
      fi: 'Tarkista ja hallitse tiliotteiden välillä havaittuja kaksoiskappaleita',
      is: 'Skoðaðu og hafðu umsjón með tvítökum sem fundust milli yfirlita',
      fo: 'Gjøgnumgá og stýr tvítøkum, sum eru funnin millum kontoúrtøk',
      cs: 'Zkontrolujte a spravujte duplicity nalezené mezi výpisy',
      bg: 'Прегледайте и управлявайте дубликатите, открити между извлеченията',
      hr: 'Pregledajte i upravljajte duplikatima otkrivenima među izvodima',
      sr: 'Прегледајте и управљајте дупликатима откривеним међу изводима',
      sl: 'Preglejte in upravljajte dvojnike, zaznane med izpiski',
      mk: 'Прегледајте и управувајте со дупликатите откриени меѓу изводите',
      be: 'Прагледзьце і апрацуйце дублікаты, знойдзеныя сярод выпісак',
      bs: 'Pregledajte i upravljajte duplikatima otkrivenim među izvodima',
      hsb: 'Přepruwujće a zarjadujće duplikaty, kotrež buchu mjez wupisami namakane',
    }),
    redetect: t({
      ru: 'Найти заново',
      en: 'Re-detect',
      kk: 'Қайта іздеу',
      de: 'Erneut erkennen',
      fr: 'Relancer la détection',
      es: 'Volver a detectar',
      pt: 'Detectar novamente',
      tr: 'Yeniden tespit et',
      uk: 'Знайти знову',
      zh: '重新检测',
      pl: 'Wykryj ponownie',
      it: 'Rileva di nuovo',
      sk: 'Znova zistiť',
      ja: '再検出',
      ko: '다시 감지',
      hi: 'फिर से पता लगाएँ',
      nl: 'Opnieuw detecteren',
      sv: 'Identifiera igen',
      vi: 'Phát hiện lại',
      id: 'Deteksi ulang',
      da: 'Søg igen',
      nb: 'Søk på nytt',
      nn: 'Søk på nytt',
      fi: 'Etsi uudelleen',
      is: 'Leita aftur',
      fo: 'Leita aftur',
      cs: 'Hledat znovu',
      bg: 'Открий отново',
      hr: 'Otkrij ponovno',
      sr: 'Откриј поново',
      sl: 'Zaznaj znova',
      mk: 'Откриј повторно',
      be: 'Шукаць зноў',
      bs: 'Otkrij ponovo',
      hsb: 'Znowa pytać',
    }),
    detecting: t({
      ru: 'Поиск...',
      en: 'Detecting...',
      kk: 'Іздеу...',
      de: 'Wird erkannt...',
      fr: 'Détection...',
      es: 'Detectando...',
      pt: 'Detectando...',
      tr: 'Tespit ediliyor...',
      uk: 'Пошук...',
      zh: '正在检测...',
      pl: 'Wykrywanie...',
      it: 'Rilevamento...',
      sk: 'Zisťuje sa...',
      ja: '検出中...',
      ko: '감지 중...',
      hi: 'पता लगाया जा रहा है...',
      nl: 'Detecteren...',
      sv: 'Identifierar...',
      vi: 'Đang phát hiện...',
      id: 'Mendeteksi...',
      da: 'Søger...',
      nb: 'Søker...',
      nn: 'Søkjer...',
      fi: 'Etsitään...',
      is: 'Leita...',
      fo: 'Leiti...',
      cs: 'Hledám...',
      bg: 'Открива...',
      hr: 'Otkrivanje...',
      sr: 'Откривање...',
      sl: 'Zaznavam...',
      mk: 'Откривам...',
      be: 'Пошук...',
      bs: 'Otkrivanje...',
      hsb: 'Pyta so...',
    }),
    totalGroups: t({
      ru: 'Всего групп',
      en: 'Total Groups',
      kk: 'Барлық топтар',
      de: 'Gruppen gesamt',
      fr: 'Total des groupes',
      es: 'Total de grupos',
      pt: 'Total de grupos',
      tr: 'Toplam grup',
      uk: 'Усього груп',
      zh: '分组总数',
      pl: 'Łącznie grup',
      it: 'Gruppi totali',
      sk: 'Skupín spolu',
      ja: 'グループ合計',
      ko: '전체 그룹',
      hi: 'कुल समूह',
      nl: 'Totaal groepen',
      sv: 'Totalt antal grupper',
      vi: 'Tổng số nhóm',
      id: 'Total grup',
      da: 'Grupper i alt',
      nb: 'Grupper i alt',
      nn: 'Grupper i alt',
      fi: 'Ryhmiä yhteensä',
      is: 'Hópar í allt',
      fo: 'Bólkar í alt',
      cs: 'Skupin celkem',
      bg: 'Общо групи',
      hr: 'Ukupno grupa',
      sr: 'Укупно група',
      sl: 'Skupin skupaj',
      mk: 'Вкупно групи',
      be: 'Усяго груп',
      bs: 'Ukupno grupa',
      hsb: 'Skupin dohromady',
    }),
    selected: t({
      ru: 'Выбрано',
      en: 'Selected',
      kk: 'Таңдалды',
      de: 'Ausgewählt',
      fr: 'Sélectionnés',
      es: 'Seleccionados',
      pt: 'Selecionados',
      tr: 'Seçilen',
      uk: 'Вибрано',
      zh: '已选择',
      pl: 'Zaznaczone',
      it: 'Selezionati',
      sk: 'Vybrané',
      ja: '選択済み',
      ko: '선택됨',
      hi: 'चयनित',
      nl: 'Geselecteerd',
      sv: 'Markerade',
      vi: 'Đã chọn',
      id: 'Dipilih',
      da: 'Valgt',
      nb: 'Valgt',
      nn: 'Valde',
      fi: 'Valittu',
      is: 'Valið',
      fo: 'Valt',
      cs: 'Vybráno',
      bg: 'Избрани',
      hr: 'Odabrano',
      sr: 'Изабрано',
      sl: 'Izbrano',
      mk: 'Избрани',
      be: 'Выбрана',
      bs: 'Odabrano',
      hsb: 'Wubrane',
    }),
    totalDuplicates: t({
      ru: 'Всего дубликатов',
      en: 'Total Duplicates',
      kk: 'Барлық көшірмелер',
      de: 'Duplikate gesamt',
      fr: 'Total des doublons',
      es: 'Total de duplicados',
      pt: 'Total de duplicados',
      tr: 'Toplam yinelenen',
      uk: 'Усього дублікатів',
      zh: '重复项总数',
      pl: 'Łącznie duplikatów',
      it: 'Duplicati totali',
      sk: 'Duplikátov spolu',
      ja: '重複合計',
      ko: '전체 중복',
      hi: 'कुल डुप्लिकेट',
      nl: 'Totaal duplicaten',
      sv: 'Totalt antal dubbletter',
      vi: 'Tổng số trùng lặp',
      id: 'Total duplikat',
      da: 'Dubletter i alt',
      nb: 'Duplikater i alt',
      nn: 'Duplikat i alt',
      fi: 'Kaksoiskappaleita yhteensä',
      is: 'Tvítök í allt',
      fo: 'Tvítøk í alt',
      cs: 'Duplicit celkem',
      bg: 'Общо дубликати',
      hr: 'Ukupno duplikata',
      sr: 'Укупно дупликата',
      sl: 'Dvojnikov skupaj',
      mk: 'Вкупно дупликати',
      be: 'Усяго дублікатаў',
      bs: 'Ukupno duplikata',
      hsb: 'Duplikatow dohromady',
    }),
    selectAll: t({
      ru: 'Выбрать все',
      en: 'Select All',
      kk: 'Барлығын таңдау',
      de: 'Alle auswählen',
      fr: 'Tout sélectionner',
      es: 'Seleccionar todo',
      pt: 'Selecionar tudo',
      tr: 'Tümünü seç',
      uk: 'Вибрати все',
      zh: '全选',
      pl: 'Zaznacz wszystko',
      it: 'Seleziona tutto',
      sk: 'Vybrať všetko',
      ja: 'すべて選択',
      ko: '모두 선택',
      hi: 'सभी चुनें',
      nl: 'Alles selecteren',
      sv: 'Markera alla',
      vi: 'Chọn tất cả',
      id: 'Pilih semua',
      da: 'Vælg alle',
      nb: 'Velg alle',
      nn: 'Vel alle',
      fi: 'Valitse kaikki',
      is: 'Velja allt',
      fo: 'Vel allar',
      cs: 'Vybrat vše',
      bg: 'Избери всички',
      hr: 'Odaberi sve',
      sr: 'Изабери све',
      sl: 'Izberi vse',
      mk: 'Избери сите',
      be: 'Выбраць усе',
      bs: 'Odaberi sve',
      hsb: 'Wšě wubrać',
    }),
    deselectAll: t({
      ru: 'Снять выбор',
      en: 'Deselect All',
      kk: 'Таңдауды алу',
      de: 'Auswahl aufheben',
      fr: 'Tout désélectionner',
      es: 'Deseleccionar todo',
      pt: 'Desmarcar tudo',
      tr: 'Seçimi kaldır',
      uk: 'Зняти вибір',
      zh: '取消全选',
      pl: 'Odznacz wszystko',
      it: 'Deseleziona tutto',
      sk: 'Zrušiť výber',
      ja: 'すべて選択解除',
      ko: '모두 선택 해제',
      hi: 'सभी का चयन हटाएँ',
      nl: 'Alles deselecteren',
      sv: 'Avmarkera alla',
      vi: 'Bỏ chọn tất cả',
      id: 'Batalkan semua pilihan',
      da: 'Fravælg alle',
      nb: 'Fjern alle valg',
      nn: 'Fjern alle val',
      fi: 'Poista valinnat',
      is: 'Afvelja allt',
      fo: 'Tak allar valin av',
      cs: 'Zrušit výběr',
      bg: 'Отмени избора',
      hr: 'Odznači sve',
      sr: 'Одзначи све',
      sl: 'Počisti izbor',
      mk: 'Отштиклирај сите',
      be: 'Зняць выбар',
      bs: 'Odznači sve',
      hsb: 'Wubranje zběhnyć',
    }),
    marking: t({
      ru: 'Отмечаем...',
      en: 'Marking...',
      kk: 'Белгіленуде...',
      de: 'Wird markiert...',
      fr: 'Marquage...',
      es: 'Marcando...',
      pt: 'Marcando...',
      tr: 'İşaretleniyor...',
      uk: 'Позначаємо...',
      zh: '正在标记...',
      pl: 'Oznaczanie...',
      it: 'Contrassegno in corso...',
      sk: 'Označuje sa...',
      ja: 'マーク中...',
      ko: '표시 중...',
      hi: 'चिह्नित किया जा रहा है...',
      nl: 'Markeren...',
      sv: 'Markerar...',
      vi: 'Đang đánh dấu...',
      id: 'Menandai...',
      da: 'Markerer...',
      nb: 'Merker...',
      nn: 'Merkar...',
      fi: 'Merkitään...',
      is: 'Merki...',
      fo: 'Merki...',
      cs: 'Označuji...',
      bg: 'Маркира...',
      hr: 'Označavam...',
      sr: 'Означавам...',
      sl: 'Označujem...',
      mk: 'Означувам...',
      be: 'Пазначаю...',
      bs: 'Označavam...',
      hsb: 'Markuje so...',
    }),
    markGroupsOne: t({
      ru: 'Пометить {count} группу как дубликат',
      en: 'Mark {count} Group as Duplicate',
      kk: '{count} топты көшірме деп белгілеу',
      de: '{count} Gruppe als Duplikat markieren',
      fr: 'Marquer {count} groupe comme doublon',
      es: 'Marcar {count} grupo como duplicado',
      pt: 'Marcar {count} grupo como duplicado',
      tr: '{count} grubu yinelenen olarak işaretle',
      uk: 'Позначити {count} групу як дублікат',
      zh: '将 {count} 个分组标记为重复',
      pl: 'Oznacz grupy jako duplikaty: {count}',
      it: 'Segna {count} gruppo come duplicato',
      sk: 'Označiť skupiny ako duplikáty: {count}',
      ja: '{count} グループを重複としてマーク',
      ko: '{count}개 그룹을 중복으로 표시',
      hi: '{count} समूह को डुप्लिकेट चिह्नित करें',
      nl: '{count} groep als duplicaat markeren',
      sv: 'Markera {count} grupp som dubblett',
      vi: 'Đánh dấu {count} nhóm là trùng lặp',
      id: 'Tandai {count} grup sebagai duplikat',
      da: 'Markér {count} gruppe som dublet',
      nb: 'Merk {count} gruppe som duplikat',
      nn: 'Merk {count} gruppe som duplikat',
      fi: 'Merkitse {count} ryhmä kaksoiskappaleeksi',
      is: 'Merkja {count} hóp sem tvítak',
      fo: 'Merk {count} bólk sum tvítak',
      cs: 'Označit {count} skupinu jako duplicitu',
      bg: 'Маркирай {count} група като дубликат',
      hr: 'Označi {count} grupu kao duplikat',
      sr: 'Означи {count} групу као дупликат',
      sl: 'Označi {count} skupino kot dvojnik',
      mk: 'Означи {count} група како дупликат',
      be: 'Пазначыць {count} групу як дублікат',
      bs: 'Označi {count} grupu kao duplikat',
      hsb: '{count} skupinu jako duplikat markować',
    }),
    markGroupsOther: t({
      ru: 'Пометить группы как дубликаты: {count}',
      en: 'Mark {count} Groups as Duplicate',
      kk: '{count} топты көшірме деп белгілеу',
      de: '{count} Gruppen als Duplikat markieren',
      fr: 'Marquer {count} groupes comme doublons',
      es: 'Marcar {count} grupos como duplicados',
      pt: 'Marcar {count} grupos como duplicados',
      tr: '{count} grubu yinelenen olarak işaretle',
      uk: 'Позначити групи як дублікати: {count}',
      zh: '将 {count} 个分组标记为重复',
      pl: 'Oznacz grupy jako duplikaty: {count}',
      it: 'Segna {count} gruppi come duplicati',
      sk: 'Označiť skupiny ako duplikáty: {count}',
      ja: '{count} グループを重複としてマーク',
      ko: '{count}개 그룹을 중복으로 표시',
      hi: '{count} समूहों को डुप्लिकेट चिह्नित करें',
      nl: '{count} groepen als duplicaat markeren',
      sv: 'Markera {count} grupper som dubbletter',
      vi: 'Đánh dấu {count} nhóm là trùng lặp',
      id: 'Tandai {count} grup sebagai duplikat',
      da: 'Markér {count} grupper som dubletter',
      nb: 'Merk {count} grupper som duplikater',
      nn: 'Merk {count} grupper som duplikat',
      fi: 'Merkitse {count} ryhmää kaksoiskappaleiksi',
      is: 'Merkja {count} hópa sem tvítök',
      fo: 'Merk {count} bólkar sum tvítøk',
      cs: 'Označit {count} skupin jako duplicity',
      bg: 'Маркирай {count} групи като дубликати',
      hr: 'Označi {count} grupa kao duplikate',
      sr: 'Означи {count} група као дупликате',
      sl: 'Označi {count} skupin kot dvojnike',
      mk: 'Означи {count} групи како дупликати',
      be: 'Пазначыць {count} груп як дублікаты',
      bs: 'Označi {count} grupa kao duplikate',
      hsb: '{count} skupinow jako duplikaty markować',
    }),
    noGroups: t({
      ru: 'Группы дубликатов не найдены',
      en: 'No duplicate groups found',
      kk: 'Қайталанатын топтар табылмады',
      de: 'Keine Duplikatgruppen gefunden',
      fr: 'Aucun groupe de doublons trouvé',
      es: 'No se encontraron grupos de duplicados',
      pt: 'Nenhum grupo de duplicados encontrado',
      tr: 'Yinelenen grup bulunamadı',
      uk: 'Груп дублікатів не знайдено',
      zh: '未找到重复分组',
      pl: 'Nie znaleziono grup duplikatów',
      it: 'Nessun gruppo di duplicati trovato',
      sk: 'Nenašli sa žiadne skupiny duplikátov',
      ja: '重複グループは見つかりませんでした',
      ko: '중복 그룹이 없습니다',
      hi: 'कोई डुप्लिकेट समूह नहीं मिला',
      nl: 'Geen groepen met duplicaten gevonden',
      sv: 'Inga dubblettgrupper hittades',
      vi: 'Không tìm thấy nhóm trùng lặp',
      id: 'Tidak ada grup duplikat',
      da: 'Ingen dubletgrupper fundet',
      nb: 'Ingen duplikatgrupper funnet',
      nn: 'Ingen duplikatgrupper funne',
      fi: 'Kaksoiskappaleryhmiä ei löytynyt',
      is: 'Engir tvítakahópar fundust',
      fo: 'Ongir tvítaksbólkar funnir',
      cs: 'Nebyly nalezeny žádné skupiny duplicit',
      bg: 'Не са намерени групи дубликати',
      hr: 'Nema nađenih grupa duplikata',
      sr: 'Нема нађених група дупликата',
      sl: 'Ni najdenih skupin dvojnikov',
      mk: 'Не се најдени групи дупликати',
      be: 'Груп дублікатаў не знойдзена',
      bs: 'Nema nađenih grupa duplikata',
      hsb: 'Žane skupiny duplikatow namakane',
    }),
    loadFailed: t({
      ru: 'Не удалось загрузить дубликаты',
      en: 'Failed to load duplicates',
      kk: 'Көшірмелерді жүктеу мүмкін болмады',
      de: 'Duplikate konnten nicht geladen werden',
      fr: 'Échec du chargement des doublons',
      es: 'No se pudieron cargar los duplicados',
      pt: 'Falha ao carregar duplicados',
      tr: 'Yinelenenler yüklenemedi',
      uk: 'Не вдалося завантажити дублікати',
      zh: '加载重复项失败',
      pl: 'Nie udało się wczytać duplikatów',
      it: 'Impossibile caricare i duplicati',
      sk: 'Duplikáty sa nepodarilo načítať',
      ja: '重複を読み込めませんでした',
      ko: '중복 항목을 불러오지 못했습니다',
      hi: 'डुप्लिकेट लोड नहीं हो सके',
      nl: 'Duplicaten laden mislukt',
      sv: 'Det gick inte att läsa in dubbletter',
      vi: 'Không thể tải các mục trùng lặp',
      id: 'Gagal memuat duplikat',
      da: 'Dubletterne kunne ikke indlæses',
      nb: 'Kunne ikke laste duplikatene',
      nn: 'Kunne ikkje laste duplikata',
      fi: 'Kaksoiskappaleita ei voitu ladata',
      is: 'Ekki var unnt að hlaða tvítökunum',
      fo: 'Fekk ikki lisið tvítøkini',
      cs: 'Duplicity se nepodařilo načíst',
      bg: 'Дубликатите не можаха да се заредят',
      hr: 'Duplikate nije bilo moguće učitati',
      sr: 'Дупликате није могуће учитати',
      sl: 'Dvojnikov ni bilo mogoče naložiti',
      mk: 'Дупликатите не можеа да се вчитаат',
      be: 'Не ўдалося загрузіць дублікаты',
      bs: 'Duplikate nije moguće učitati',
      hsb: 'Duplikaty njedadźa so začitać',
    }),
    markFailed: t({
      ru: 'Не удалось пометить дубликаты',
      en: 'Failed to mark duplicates',
      kk: 'Көшірмелерді белгілеу мүмкін болмады',
      de: 'Duplikate konnten nicht markiert werden',
      fr: 'Échec du marquage des doublons',
      es: 'No se pudieron marcar los duplicados',
      pt: 'Falha ao marcar duplicados',
      tr: 'Yinelenenler işaretlenemedi',
      uk: 'Не вдалося позначити дублікати',
      zh: '标记重复项失败',
      pl: 'Nie udało się oznaczyć duplikatów',
      it: 'Impossibile contrassegnare i duplicati',
      sk: 'Duplikáty sa nepodarilo označiť',
      ja: '重複をマークできませんでした',
      ko: '중복 항목을 표시하지 못했습니다',
      hi: 'डुप्लिकेट चिह्नित नहीं हो सके',
      nl: 'Duplicaten markeren mislukt',
      sv: 'Det gick inte att markera dubbletter',
      vi: 'Không thể đánh dấu các mục trùng lặp',
      id: 'Gagal menandai duplikat',
      da: 'Dubletterne kunne ikke markeres',
      nb: 'Kunne ikke merke duplikatene',
      nn: 'Kunne ikkje merke duplikata',
      fi: 'Kaksoiskappaleita ei voitu merkitä',
      is: 'Ekki var unnt að merkja tvítökin',
      fo: 'Fekk ikki merkt tvítøkini',
      cs: 'Duplicity se nepodařilo označit',
      bg: 'Дубликатите не можаха да бъдат маркирани',
      hr: 'Duplikate nije bilo moguće označiti',
      sr: 'Дупликате није могуће означити',
      sl: 'Dvojnikov ni bilo mogoče označiti',
      mk: 'Дупликатите не можеа да се означат',
      be: 'Не ўдалося пазначыць дублікаты',
      bs: 'Duplikate nije moguće označiti',
      hsb: 'Duplikaty njedadźa so markować',
    }),
    selectAtLeastOne: t({
      ru: 'Выберите хотя бы одну группу дубликатов',
      en: 'Please select at least one duplicate group to mark',
      kk: 'Кемінде бір қайталанатын топты таңдаңыз',
      de: 'Bitte wählen Sie mindestens eine Duplikatgruppe aus',
      fr: 'Veuillez sélectionner au moins un groupe de doublons',
      es: 'Selecciona al menos un grupo de duplicados',
      pt: 'Selecione pelo menos um grupo de duplicados',
      tr: 'Lütfen en az bir yinelenen grup seçin',
      uk: 'Оберіть хоча б одну групу дублікатів',
      zh: '请至少选择一个要标记的重复分组',
      pl: 'Wybierz co najmniej jedną grupę duplikatów',
      it: 'Seleziona almeno un gruppo di duplicati',
      sk: 'Vyberte aspoň jednu skupinu duplikátov',
      ja: 'マークする重複グループを 1 つ以上選択してください',
      ko: '표시할 중복 그룹을 하나 이상 선택하세요',
      hi: 'कृपया कम से कम एक डुप्लिकेट समूह चुनें',
      nl: 'Selecteer ten minste één groep met duplicaten',
      sv: 'Välj minst en dubblettgrupp',
      vi: 'Vui lòng chọn ít nhất một nhóm trùng lặp',
      id: 'Pilih setidaknya satu grup duplikat',
      da: 'Vælg mindst én dubletgruppe at markere',
      nb: 'Velg minst én duplikatgruppe å merke',
      nn: 'Vel minst éi duplikatgruppe å merke',
      fi: 'Valitse vähintään yksi merkittävä ryhmä',
      is: 'Veldu að minnsta kosti einn hóp til að merkja',
      fo: 'Vel í minsta lagi ein bólk at merkja',
      cs: 'Vyberte alespoň jednu skupinu duplicit k označení',
      bg: 'Изберете поне една група дубликати за маркиране',
      hr: 'Odaberite najmanje jednu grupu duplikata za označavanje',
      sr: 'Изаберите најмање једну групу дупликата за означавање',
      sl: 'Izberite vsaj eno skupino dvojnikov za označitev',
      mk: 'Изберете барем една група дупликати за означување',
      be: 'Выберыце прынамсі адну групу дублікатаў для пазначэння',
      bs: 'Odaberite najmanje jednu grupu duplikata za označavanje',
      hsb: 'Wuzwolće znajmjeńša jednu skupinu duplikatow za markowanje',
    }),
    markSuccess: t({
      ru: 'Помечено как дубликаты транзакций: {count}',
      en: 'Successfully marked {count} transactions as duplicates',
      kk: 'Көшірме деп белгіленген транзакциялар: {count}',
      de: '{count} Transaktionen als Duplikate markiert',
      fr: '{count} transactions marquées comme doublons',
      es: 'Se marcaron {count} transacciones como duplicadas',
      pt: '{count} transações marcadas como duplicadas',
      tr: '{count} işlem yinelenen olarak işaretlendi',
      uk: 'Позначено як дублікати транзакцій: {count}',
      zh: '已将 {count} 笔交易标记为重复',
      pl: 'Oznaczono jako duplikaty transakcji: {count}',
      it: '{count} transazioni segnate come duplicate',
      sk: 'Transakcie označené ako duplikáty: {count}',
      ja: '{count} 件の取引を重複としてマークしました',
      ko: '{count}건의 거래를 중복으로 표시했습니다',
      hi: '{count} लेनदेन डुप्लिकेट के रूप में चिह्नित किए गए',
      nl: '{count} transacties gemarkeerd als duplicaat',
      sv: '{count} transaktioner markerades som dubbletter',
      vi: 'Đã đánh dấu {count} giao dịch là trùng lặp',
      id: '{count} transaksi ditandai sebagai duplikat',
      da: '{count} posteringer er markeret som dubletter',
      nb: '{count} transaksjoner er merket som duplikater',
      nn: '{count} transaksjonar er merkte som duplikat',
      fi: '{count} tapahtumaa merkittiin kaksoiskappaleiksi',
      is: '{count} færslur voru merktar sem tvítök',
      fo: '{count} posteringar vórðu merktar sum tvítøk',
      cs: '{count} transakcí bylo označeno jako duplicity',
      bg: '{count} транзакции са маркирани като дубликати',
      hr: '{count} transakcija označeno je kao duplikati',
      sr: '{count} трансакција је означено као дупликати',
      sl: '{count} transakcij je označenih kot dvojniki',
      mk: '{count} трансакции се означени како дупликати',
      be: '{count} транзакцый пазначана як дублікаты',
      bs: '{count} transakcija označeno je kao duplikati',
      hsb: '{count} transakcijow bu jako duplikaty markowane',
    }),
    card: {
      match: t({
        ru: 'Совпадение {percent}%',
        en: '{percent}% Match',
        kk: 'Сәйкестік {percent}%',
        de: '{percent} % Übereinstimmung',
        fr: 'Correspondance {percent} %',
        es: 'Coincidencia {percent} %',
        pt: 'Correspondência {percent}%',
        tr: '%{percent} eşleşme',
        uk: 'Збіг {percent}%',
        zh: '匹配度 {percent}%',
        pl: 'Zgodność {percent}%',
        it: 'Corrispondenza {percent}%',
        sk: 'Zhoda {percent} %',
        ja: '一致率 {percent}%',
        ko: '{percent}% 일치',
        hi: '{percent}% मिलान',
        nl: '{percent}% overeenkomst',
        sv: '{percent} % matchning',
        vi: 'Khớp {percent}%',
        id: '{percent}% cocok',
        da: '{percent} % match',
        nb: '{percent} % treff',
        nn: '{percent} % treff',
        fi: '{percent} % osuma',
        is: '{percent} % samsvörun',
        fo: '{percent} % samsvar',
        cs: '{percent} % shoda',
        bg: '{percent} % съвпадение',
        hr: '{percent} % podudarnost',
        sr: '{percent} % подударност',
        sl: '{percent} % ujemanje',
        mk: '{percent} % совпаѓање',
        be: '{percent} % супадзенне',
        bs: '{percent} % podudarnost',
        hsb: '{percent} % wotpowědnosć',
      }),
      duplicatesOne: t({
        ru: '{count} дубликат',
        en: '{count} duplicate',
        kk: '{count} көшірме',
        de: '{count} Duplikat',
        fr: '{count} doublon',
        es: '{count} duplicado',
        pt: '{count} duplicado',
        tr: '{count} yinelenen',
        uk: '{count} дублікат',
        zh: '{count} 个重复项',
        pl: 'Duplikaty: {count}',
        it: '{count} duplicato',
        sk: 'Duplikáty: {count}',
        ja: '重複 {count} 件',
        ko: '중복 {count}개',
        hi: '{count} डुप्लिकेट',
        nl: '{count} duplicaat',
        sv: '{count} dubblett',
        vi: '{count} bản trùng lặp',
        id: '{count} duplikat',
        da: '{count} dublet',
        nb: '{count} duplikat',
        nn: '{count} duplikat',
        fi: '{count} kaksoiskappale',
        is: '{count} tvítak',
        fo: '{count} tvítak',
        cs: '{count} duplicita',
        bg: '{count} дубликат',
        hr: '{count} duplikat',
        sr: '{count} дупликат',
        sl: '{count} dvojnik',
        mk: '{count} дупликат',
        be: '{count} дублікат',
        bs: '{count} duplikat',
        hsb: '{count} duplikat',
      }),
      duplicatesOther: t({
        ru: 'Дубликатов: {count}',
        en: '{count} duplicates',
        kk: '{count} көшірме',
        de: '{count} Duplikate',
        fr: '{count} doublons',
        es: '{count} duplicados',
        pt: '{count} duplicados',
        tr: '{count} yinelenen',
        uk: 'Дублікатів: {count}',
        zh: '{count} 个重复项',
        pl: 'Duplikaty: {count}',
        it: '{count} duplicati',
        sk: 'Duplikáty: {count}',
        ja: '重複 {count} 件',
        ko: '중복 {count}개',
        hi: '{count} डुप्लिकेट',
        nl: '{count} duplicaten',
        sv: '{count} dubbletter',
        vi: '{count} bản trùng lặp',
        id: '{count} duplikat',
        da: '{count} dubletter',
        nb: '{count} duplikater',
        nn: '{count} duplikat',
        fi: '{count} kaksoiskappaletta',
        is: '{count} tvítök',
        fo: '{count} tvítøk',
        cs: '{count} duplicit',
        bg: '{count} дубликата',
        hr: '{count} duplikata',
        sr: '{count} дупликата',
        sl: '{count} dvojnikov',
        mk: '{count} дупликати',
        be: '{count} дублікатаў',
        bs: '{count} duplikata',
        hsb: '{count} duplikatow',
      }),
      showDetails: t({
        ru: 'Показать детали',
        en: 'Show Details',
        kk: 'Мәліметтерді көрсету',
        de: 'Details anzeigen',
        fr: 'Afficher les détails',
        es: 'Mostrar detalles',
        pt: 'Mostrar detalhes',
        tr: 'Ayrıntıları göster',
        uk: 'Показати деталі',
        zh: '显示详情',
        pl: 'Pokaż szczegóły',
        it: 'Mostra dettagli',
        sk: 'Zobraziť podrobnosti',
        ja: '詳細を表示',
        ko: '상세 보기',
        hi: 'विवरण दिखाएँ',
        nl: 'Details tonen',
        sv: 'Visa detaljer',
        vi: 'Hiện chi tiết',
        id: 'Tampilkan detail',
        da: 'Vis detaljer',
        nb: 'Vis detaljer',
        nn: 'Vis detaljar',
        fi: 'Näytä tiedot',
        is: 'Sýna nánar',
        fo: 'Vís smálutir',
        cs: 'Zobrazit podrobnosti',
        bg: 'Покажи подробности',
        hr: 'Prikaži detalje',
        sr: 'Прикажи детаље',
        sl: 'Pokaži podrobnosti',
        mk: 'Прикажи детали',
        be: 'Паказаць дэталі',
        bs: 'Prikaži detalje',
        hsb: 'Podrobnosće pokazać',
      }),
      hideDetails: t({
        ru: 'Скрыть детали',
        en: 'Hide Details',
        kk: 'Мәліметтерді жасыру',
        de: 'Details ausblenden',
        fr: 'Masquer les détails',
        es: 'Ocultar detalles',
        pt: 'Ocultar detalhes',
        tr: 'Ayrıntıları gizle',
        uk: 'Приховати деталі',
        zh: '隐藏详情',
        pl: 'Ukryj szczegóły',
        it: 'Nascondi dettagli',
        sk: 'Skryť podrobnosti',
        ja: '詳細を非表示',
        ko: '상세 숨기기',
        hi: 'विवरण छिपाएँ',
        nl: 'Details verbergen',
        sv: 'Dölj detaljer',
        vi: 'Ẩn chi tiết',
        id: 'Sembunyikan detail',
        da: 'Skjul detaljer',
        nb: 'Skjul detaljer',
        nn: 'Skjul detaljar',
        fi: 'Piilota tiedot',
        is: 'Fela nánar',
        fo: 'Fjal smálutir',
        cs: 'Skrýt podrobnosti',
        bg: 'Скрий подробностите',
        hr: 'Sakrij detalje',
        sr: 'Сакрий детаље',
        sl: 'Skrij podrobnosti',
        mk: 'Скрий детали',
        be: 'Схаваць дэталі',
        bs: 'Sakrij detalje',
        hsb: 'Podrobnosće schować',
      }),
      master: t({
        ru: 'Основная',
        en: 'Master',
        kk: 'Негізгі',
        de: 'Original',
        fr: 'Principale',
        es: 'Principal',
        pt: 'Principal',
        tr: 'Ana',
        uk: 'Основна',
        zh: '主记录',
        pl: 'Główna',
        it: 'Principale',
        sk: 'Hlavná',
        ja: 'マスター',
        ko: '원본',
        hi: 'मुख्य',
        nl: 'Origineel',
        sv: 'Original',
        vi: 'Bản gốc',
        id: 'Utama',
        da: 'Original',
        nb: 'Original',
        nn: 'Original',
        fi: 'Alkuperäinen',
        is: 'Upprunalegt',
        fo: 'Upprunaligt',
        cs: 'Originál',
        bg: 'Оригинал',
        hr: 'Original',
        sr: 'Оригинал',
        sl: 'Izvirnik',
        mk: 'Оригинал',
        be: 'Арыгінал',
        bs: 'Original',
        hsb: 'Original',
      }),
      duplicateN: t({
        ru: 'Дубликат {n}',
        en: 'Duplicate {n}',
        kk: 'Көшірме {n}',
        de: 'Duplikat {n}',
        fr: 'Doublon {n}',
        es: 'Duplicado {n}',
        pt: 'Duplicado {n}',
        tr: 'Yinelenen {n}',
        uk: 'Дублікат {n}',
        zh: '重复项 {n}',
        pl: 'Duplikat {n}',
        it: 'Duplicato {n}',
        sk: 'Duplikát {n}',
        ja: '重複 {n}',
        ko: '중복 {n}',
        hi: 'डुप्लिकेट {n}',
        nl: 'Duplicaat {n}',
        sv: 'Dubblett {n}',
        vi: 'Trùng lặp {n}',
        id: 'Duplikat {n}',
        da: 'Dublet {n}',
        nb: 'Duplikat {n}',
        nn: 'Duplikat {n}',
        fi: 'Kaksoiskappale {n}',
        is: 'Tvítak {n}',
        fo: 'Tvítak {n}',
        cs: 'Duplicita {n}',
        bg: 'Дубликат {n}',
        hr: 'Duplikat {n}',
        sr: 'Дупликат {n}',
        sl: 'Dvojnik {n}',
        mk: 'Дупликат {n}',
        be: 'Дублікат {n}',
        bs: 'Duplikat {n}',
        hsb: 'Duplikat {n}',
      }),
      similar: t({
        ru: 'Сходство {percent}%',
        en: '{percent}% similar',
        kk: 'Ұқсастық {percent}%',
        de: '{percent} % ähnlich',
        fr: 'Similaire à {percent} %',
        es: 'Similitud del {percent} %',
        pt: '{percent}% semelhante',
        tr: '%{percent} benzer',
        uk: 'Схожість {percent}%',
        zh: '相似度 {percent}%',
        pl: 'Podobieństwo {percent}%',
        it: 'Simile al {percent}%',
        sk: 'Podobnosť {percent} %',
        ja: '類似度 {percent}%',
        ko: '{percent}% 유사',
        hi: '{percent}% समान',
        nl: '{percent}% vergelijkbaar',
        sv: '{percent} % likhet',
        vi: 'Tương đồng {percent}%',
        id: '{percent}% mirip',
        da: '{percent} % ens',
        nb: '{percent} % like',
        nn: '{percent} % like',
        fi: '{percent} % samanlainen',
        is: '{percent} % líkt',
        fo: '{percent} % líkt',
        cs: '{percent} % podobné',
        bg: '{percent} % сходство',
        hr: '{percent} % slično',
        sr: '{percent} % слично',
        sl: '{percent} % podobno',
        mk: '{percent} % слично',
        be: '{percent} % падабенства',
        bs: '{percent} % slično',
        hsb: '{percent} % podobne',
      }),
      matchedFields: t({
        ru: 'Совпавшие поля:',
        en: 'Matched fields:',
        kk: 'Сәйкес өрістер:',
        de: 'Übereinstimmende Felder:',
        fr: 'Champs correspondants :',
        es: 'Campos coincidentes:',
        pt: 'Campos correspondentes:',
        tr: 'Eşleşen alanlar:',
        uk: 'Збіжні поля:',
        zh: '匹配字段：',
        pl: 'Zgodne pola:',
        it: 'Campi corrispondenti:',
        sk: 'Zhodné polia:',
        ja: '一致したフィールド:',
        ko: '일치한 필드:',
        hi: 'मेल खाते फ़ील्ड:',
        nl: 'Overeenkomende velden:',
        sv: 'Matchande fält:',
        vi: 'Các trường khớp:',
        id: 'Bidang yang cocok:',
        da: 'Matchede felter:',
        nb: 'Felter som traff:',
        nn: 'Felt som traff:',
        fi: 'Täsmäävät kentät:',
        is: 'Svið sem pössuðu:',
        fo: 'Teigar sum samsvara:',
        cs: 'Shodná pole:',
        bg: 'Съвпадащи полета:',
        hr: 'Polja koja se podudaraju:',
        sr: 'Поља која се подударају:',
        sl: 'Ujemajoča se polja:',
        mk: 'Полиња што се совпаѓаат:',
        be: 'Супадаючыя палі:',
        bs: 'Polja koja se podudaraju:',
        hsb: 'Pola, kotrež so kryja:',
      }),
      moreOne: t({
        ru: '+{count} дубликат',
        en: '+{count} more duplicate',
        kk: '+{count} көшірме',
        de: '+{count} weiteres Duplikat',
        fr: '+{count} autre doublon',
        es: '+{count} duplicado más',
        pt: '+{count} duplicado a mais',
        tr: '+{count} yinelenen daha',
        uk: '+{count} дублікат',
        zh: '另有 {count} 个重复项',
        pl: '+{count} kolejny duplikat',
        it: '+{count} altro duplicato',
        sk: '+{count} ďalší duplikát',
        ja: '他に {count} 件の重複',
        ko: '중복 {count}개 더',
        hi: '+{count} और डुप्लिकेट',
        nl: '+{count} extra duplicaat',
        sv: '+{count} dubblett till',
        vi: '+{count} bản trùng lặp khác',
        id: '+{count} duplikat lainnya',
        da: '+{count} dublet mere',
        nb: '+{count} duplikat mer',
        nn: '+{count} duplikat meir',
        fi: '+{count} kaksoiskappale lisää',
        is: '+{count} tvítak til viðbótar',
        fo: '+{count} tvítak meira',
        cs: '+{count} další duplicita',
        bg: '+{count} още дубликат',
        hr: '+{count} još duplikat',
        sr: '+{count} још дупликат',
        sl: '+{count} dvojnik več',
        mk: '+{count} уште дупликат',
        be: '+{count} дублікат яшчэ',
        bs: '+{count} još duplikat',
        hsb: '+{count} duplikat wjace',
      }),
      moreOther: t({
        ru: '+{count} дубликатов',
        en: '+{count} more duplicates',
        kk: '+{count} көшірме',
        de: '+{count} weitere Duplikate',
        fr: '+{count} autres doublons',
        es: '+{count} duplicados más',
        pt: '+{count} duplicados a mais',
        tr: '+{count} yinelenen daha',
        uk: '+{count} дублікатів',
        zh: '另有 {count} 个重复项',
        pl: '+{count} kolejnych duplikatów',
        it: '+{count} altri duplicati',
        sk: '+{count} ďalších duplikátov',
        ja: '他に {count} 件の重複',
        ko: '중복 {count}개 더',
        hi: '+{count} और डुप्लिकेट',
        nl: '+{count} extra duplicaten',
        sv: '+{count} dubbletter till',
        vi: '+{count} bản trùng lặp khác',
        id: '+{count} duplikat lainnya',
        da: '+{count} dubletter mere',
        nb: '+{count} duplikater mer',
        nn: '+{count} duplikat meir',
        fi: '+{count} kaksoiskappaletta lisää',
        is: '+{count} tvítök til viðbótar',
        fo: '+{count} tvítøk meira',
        cs: '+{count} dalších duplicit',
        bg: '+{count} още дубликата',
        hr: '+{count} još duplikata',
        sr: '+{count} још дупликата',
        sl: '+{count} dvojnikov več',
        mk: '+{count} уште дупликати',
        be: '+{count} дублікатаў яшчэ',
        bs: '+{count} još duplikata',
        hsb: '+{count} duplikatow wjace',
      }),
      matchTypes: {
        exact: t({
          ru: 'точное',
          en: 'exact',
          kk: 'дәл',
          de: 'exakt',
          fr: 'exacte',
          es: 'exacta',
          pt: 'exata',
          tr: 'tam',
          uk: 'точний',
          zh: '精确',
          pl: 'dokładne',
          it: 'esatta',
          sk: 'presná',
          ja: '完全一致',
          ko: '정확',
          hi: 'सटीक',
          nl: 'exact',
          sv: 'exakt',
          vi: 'chính xác',
          id: 'persis',
          da: 'præcis',
          nb: 'eksakt',
          nn: 'eksakt',
          fi: 'tarkka',
          is: 'nákvæmt',
          fo: 'neyvt',
          cs: 'přesné',
          bg: 'точно',
          hr: 'točno',
          sr: 'тачно',
          sl: 'točno',
          mk: 'точно',
          be: 'дакладна',
          bs: 'tačno',
          hsb: 'eksaktne',
        }),
        hybrid: t({
          ru: 'гибридное',
          en: 'hybrid',
          kk: 'аралас',
          de: 'hybrid',
          fr: 'hybride',
          es: 'híbrida',
          pt: 'híbrida',
          tr: 'karma',
          uk: 'гібридний',
          zh: '混合',
          pl: 'hybrydowe',
          it: 'ibrida',
          sk: 'hybridná',
          ja: 'ハイブリッド',
          ko: '혼합',
          hi: 'हाइब्रिड',
          nl: 'hybride',
          sv: 'hybrid',
          vi: 'kết hợp',
          id: 'hibrida',
          da: 'hybrid',
          nb: 'hybrid',
          nn: 'hybrid',
          fi: 'hybridi',
          is: 'blandað',
          fo: 'blandað',
          cs: 'hybridní',
          bg: 'хибридно',
          hr: 'hibridno',
          sr: 'хибридно',
          sl: 'hibridno',
          mk: 'хибридно',
          be: 'гібрыдна',
          bs: 'hibridno',
          hsb: 'hybridne',
        }),
        fuzzy: t({
          ru: 'нечёткое',
          en: 'fuzzy',
          kk: 'анық емес',
          de: 'unscharf',
          fr: 'approximative',
          es: 'aproximada',
          pt: 'aproximada',
          tr: 'bulanık',
          uk: 'нечіткий',
          zh: '模糊',
          pl: 'przybliżone',
          it: 'approssimativa',
          sk: 'približná',
          ja: 'あいまい',
          ko: '유사',
          hi: 'अनुमानित',
          nl: 'vaag',
          sv: 'ungefärlig',
          vi: 'gần đúng',
          id: 'mirip',
          da: 'omtrentlig',
          nb: 'tilnærmet',
          nn: 'tilnærma',
          fi: 'sumea',
          is: 'óskýrt',
          fo: 'ógreitt',
          cs: 'přibližné',
          bg: 'приблизително',
          hr: 'približno',
          sr: 'приближно',
          sl: 'približno',
          mk: 'приближно',
          be: 'прыблізна',
          bs: 'približno',
          hsb: 'přibližne',
        }),
        semantic: t({
          ru: 'смысловое',
          en: 'semantic',
          kk: 'мағыналық',
          de: 'semantisch',
          fr: 'sémantique',
          es: 'semántica',
          pt: 'semântica',
          tr: 'anlamsal',
          uk: 'смисловий',
          zh: '语义',
          pl: 'semantyczne',
          it: 'semantica',
          sk: 'sémantická',
          ja: '意味的',
          ko: '의미',
          hi: 'अर्थगत',
          nl: 'semantisch',
          sv: 'semantisk',
          vi: 'ngữ nghĩa',
          id: 'semantik',
          da: 'semantisk',
          nb: 'semantisk',
          nn: 'semantisk',
          fi: 'semanttinen',
          is: 'merkingarlegt',
          fo: 'semantiskt',
          cs: 'sémantické',
          bg: 'семантично',
          hr: 'semantično',
          sr: 'семантично',
          sl: 'pomensko',
          mk: 'семантично',
          be: 'семантычна',
          bs: 'semantično',
          hsb: 'semantiske',
        }),
      },
    },
  },
} satisfies Dictionary;

export default content;
