/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'taxReturnView',
  content: {
    presetThisQuarter: t({
      ru: 'Этот квартал',
      en: 'This quarter',
      kk: 'Осы тоқсан',
      de: 'Dieses Quartal',
      fr: 'Ce trimestre',
      es: 'Este trimestre',
      pt: 'Este trimestre',
      tr: 'Bu çeyrek',
      uk: 'Цей квартал',
      zh: '本季度',
      ar: 'هذا الربع',
      pl: 'Ten kwartał',
      it: 'Questo trimestre',
      sk: 'Tento štvrťrok',
      ja: '今四半期',
      ko: '이번 분기',
      hi: 'यह तिमाही',
      nl: 'Dit kwartaal',
      sv: 'Detta kvartal',
      vi: 'Quý này',
      id: 'Kuartal ini',
    }),
    presetLastQuarter: t({
      ru: 'Прошлый квартал',
      en: 'Last quarter',
      kk: 'Өткен тоқсан',
      de: 'Letztes Quartal',
      fr: 'Trimestre précédent',
      es: 'Trimestre anterior',
      pt: 'Trimestre anterior',
      tr: 'Geçen çeyrek',
      uk: 'Минулий квартал',
      zh: '上季度',
      ar: 'الربع السابق',
      pl: 'Poprzedni kwartał',
      it: 'Trimestre scorso',
      sk: 'Minulý štvrťrok',
      ja: '前四半期',
      ko: '지난 분기',
      hi: 'पिछली तिमाही',
      nl: 'Vorig kwartaal',
      sv: 'Förra kvartalet',
      vi: 'Quý trước',
      id: 'Kuartal lalu',
    }),
    presetThisYear: t({
      ru: 'Этот год',
      en: 'This year',
      kk: 'Осы жыл',
      de: 'Dieses Jahr',
      fr: 'Cette année',
      es: 'Este año',
      pt: 'Este ano',
      tr: 'Bu yıl',
      uk: 'Цей рік',
      zh: '今年',
      ar: 'هذا العام',
      pl: 'Ten rok',
      it: 'Quest’anno',
      sk: 'Tento rok',
      ja: '今年',
      ko: '올해',
      hi: 'यह वर्ष',
      nl: 'Dit jaar',
      sv: 'I år',
      vi: 'Năm nay',
      id: 'Tahun ini',
    }),
    directionOutput: t({
      ru: 'Исходящий',
      en: 'Output',
      kk: 'Шығыс',
      de: 'Umsatzsteuer',
      fr: 'Collectée',
      es: 'Repercutido',
      pt: 'Débito',
      tr: 'Hesaplanan',
      uk: 'Вихідний',
      zh: '销项',
      ar: 'مخرجات',
      pl: 'Należny',
      it: 'A debito',
      sk: 'Výstupná',
      ja: '売上',
      ko: '매출',
      hi: 'आउटपुट',
      nl: 'Af te dragen',
      sv: 'Utgående',
      vi: 'Đầu ra',
      id: 'Keluaran',
    }),
    directionInput: t({
      ru: 'Входящий',
      en: 'Input',
      kk: 'Кіріс',
      de: 'Vorsteuer',
      fr: 'Déductible',
      es: 'Soportado',
      pt: 'Crédito',
      tr: 'İndirilecek',
      uk: 'Вхідний',
      zh: '进项',
      ar: 'مدخلات',
      pl: 'Naliczony',
      it: 'A credito',
      sk: 'Vstupná',
      ja: '仕入',
      ko: '매입',
      hi: 'इनपुट',
      nl: 'Voorbelasting',
      sv: 'Ingående',
      vi: 'Đầu vào',
      id: 'Masukan',
    }),
    directionReverseCharge: t({
      ru: 'Обратное начисление',
      en: 'Reverse charge',
      kk: 'Кері есептеу',
      de: 'Reverse Charge',
      fr: 'Autoliquidation',
      es: 'Inversión del sujeto pasivo',
      pt: 'Autoliquidação',
      tr: 'Sorumlu sıfatıyla',
      uk: 'Зворотне нарахування',
      zh: '反向征收',
      ar: 'الاحتساب العكسي',
      pl: 'Odwrotne obciążenie',
      it: 'Inversione contabile',
      sk: 'Prenesenie daňovej povinnosti',
      ja: 'リバースチャージ',
      ko: '역발행 과세',
      hi: 'रिवर्स चार्ज',
      nl: 'Verlegde btw',
      sv: 'Omvänd skattskyldighet',
      vi: 'Thuế đảo ngược',
      id: 'Reverse charge',
    }),
    fileFailed: t({
      ru: 'Не удалось подать декларацию. Попробуйте ещё раз.',
      en: 'Could not file the return. Please try again.',
      kk: 'Декларацияны тапсыру мүмкін болмады. Қайталап көріңіз.',
      de: 'Die Erklärung konnte nicht eingereicht werden. Bitte versuchen Sie es erneut.',
      fr: 'Impossible de déposer la déclaration. Veuillez réessayer.',
      es: 'No se pudo presentar la declaración. Inténtelo de nuevo.',
      pt: 'Não foi possível enviar a declaração. Tente novamente.',
      tr: 'Beyanname verilemedi. Lütfen tekrar deneyin.',
      uk: 'Не вдалося подати декларацію. Спробуйте ще раз.',
      zh: '无法提交申报表，请重试。',
      ar: 'تعذّر تقديم الإقرار. يرجى المحاولة مرة أخرى.',
      pl: 'Nie udało się złożyć deklaracji. Spróbuj ponownie.',
      it: 'Impossibile presentare la dichiarazione. Riprova.',
      sk: 'Priznanie sa nepodarilo podať. Skúste to znova.',
      ja: '申告を提出できませんでした。もう一度お試しください。',
      ko: '신고서를 제출하지 못했습니다. 다시 시도하세요.',
      hi: 'रिटर्न दाखिल नहीं हो सका। कृपया फिर से प्रयास करें।',
      nl: 'De aangifte kon niet worden ingediend. Probeer het opnieuw.',
      sv: 'Det gick inte att lämna in deklarationen. Försök igen.',
      vi: 'Không thể nộp tờ khai. Vui lòng thử lại.',
      id: 'Tidak dapat mengajukan SPT. Silakan coba lagi.',
    }),
    reopenFailed: t({
      ru: 'Не удалось открыть период заново. Попробуйте ещё раз.',
      en: 'Could not reopen the period. Please try again.',
      kk: 'Кезеңді қайта ашу мүмкін болмады. Қайталап көріңіз.',
      de: 'Der Zeitraum konnte nicht wieder geöffnet werden. Bitte versuchen Sie es erneut.',
      fr: 'Impossible de rouvrir la période. Veuillez réessayer.',
      es: 'No se pudo reabrir el periodo. Inténtelo de nuevo.',
      pt: 'Não foi possível reabrir o período. Tente novamente.',
      tr: 'Dönem yeniden açılamadı. Lütfen tekrar deneyin.',
      uk: 'Не вдалося знову відкрити період. Спробуйте ще раз.',
      zh: '无法重新打开该期间，请重试。',
      ar: 'تعذّر إعادة فتح الفترة. يرجى المحاولة مرة أخرى.',
      pl: 'Nie udało się ponownie otworzyć okresu. Spróbuj ponownie.',
      it: 'Impossibile riaprire il periodo. Riprova.',
      sk: 'Obdobie sa nepodarilo znova otvoriť. Skúste to znova.',
      ja: '期間を再開できませんでした。もう一度お試しください。',
      ko: '기간을 다시 열지 못했습니다. 다시 시도하세요.',
      hi: 'अवधि फिर से नहीं खुल सकी। कृपया फिर से प्रयास करें।',
      nl: 'De periode kon niet worden heropend. Probeer het opnieuw.',
      sv: 'Det gick inte att öppna perioden igen. Försök igen.',
      vi: 'Không thể mở lại kỳ. Vui lòng thử lại.',
      id: 'Tidak dapat membuka kembali periode. Silakan coba lagi.',
    }),
    exportFailed: t({
      ru: 'Не удалось экспортировать декларацию в {format}.',
      en: 'Could not export the return as {format}.',
      kk: 'Декларацияны {format} форматына экспорттау мүмкін болмады.',
      de: 'Die Erklärung konnte nicht als {format} exportiert werden.',
      fr: 'Impossible d’exporter la déclaration en {format}.',
      es: 'No se pudo exportar la declaración como {format}.',
      pt: 'Não foi possível exportar a declaração como {format}.',
      tr: 'Beyanname {format} olarak dışa aktarılamadı.',
      uk: 'Не вдалося експортувати декларацію у {format}.',
      zh: '无法将申报表导出为 {format}。',
      ar: 'تعذّر تصدير الإقرار بصيغة {format}.',
      pl: 'Nie udało się wyeksportować deklaracji jako {format}.',
      it: 'Impossibile esportare la dichiarazione in {format}.',
      sk: 'Priznanie sa nepodarilo exportovať ako {format}.',
      ja: '申告を {format} でエクスポートできませんでした。',
      ko: '신고서를 {format}(으)로 내보내지 못했습니다.',
      hi: 'रिटर्न को {format} के रूप में निर्यात नहीं किया जा सका।',
      nl: 'De aangifte kon niet als {format} worden geëxporteerd.',
      sv: 'Det gick inte att exportera deklarationen som {format}.',
      vi: 'Không thể xuất tờ khai dưới dạng {format}.',
      id: 'Tidak dapat mengekspor SPT sebagai {format}.',
    }),
    from: t({
      ru: 'С',
      en: 'From',
      kk: 'Бастап',
      de: 'Von',
      fr: 'Du',
      es: 'Desde',
      pt: 'De',
      tr: 'Başlangıç',
      uk: 'З',
      zh: '从',
      ar: 'من',
      pl: 'Od',
      it: 'Da',
      sk: 'Od',
      ja: '開始',
      ko: '시작',
      hi: 'से',
      nl: 'Van',
      sv: 'Från',
      vi: 'Từ',
      id: 'Dari',
    }),
    to: t({
      ru: 'По',
      en: 'To',
      kk: 'Дейін',
      de: 'Bis',
      fr: 'Au',
      es: 'Hasta',
      pt: 'Até',
      tr: 'Bitiş',
      uk: 'По',
      zh: '至',
      ar: 'إلى',
      pl: 'Do',
      it: 'A',
      sk: 'Do',
      ja: '終了',
      ko: '종료',
      hi: 'तक',
      nl: 'Tot',
      sv: 'Till',
      vi: 'Đến',
      id: 'Sampai',
    }),
    buildFailed: t({
      ru: 'Не удалось сформировать декларацию. Проверьте, что для этого пространства указана налоговая юрисдикция.',
      en: 'Could not build the return. Check that this workspace has a tax jurisdiction.',
      kk: 'Декларацияны құру мүмкін болмады. Осы жұмыс кеңістігінде салық юрисдикциясы көрсетілгенін тексеріңіз.',
      de: 'Die Erklärung konnte nicht erstellt werden. Prüfen Sie, ob für diesen Workspace eine Steuerhoheit festgelegt ist.',
      fr: 'Impossible de générer la déclaration. Vérifiez que cet espace de travail a une juridiction fiscale.',
      es: 'No se pudo generar la declaración. Compruebe que este espacio de trabajo tenga una jurisdicción fiscal.',
      pt: 'Não foi possível gerar a declaração. Verifique se este espaço de trabalho tem uma jurisdição fiscal.',
      tr: 'Beyanname oluşturulamadı. Bu çalışma alanında bir vergi yetki alanı tanımlı olduğunu kontrol edin.',
      uk: 'Не вдалося сформувати декларацію. Перевірте, що для цього простору вказано податкову юрисдикцію.',
      zh: '无法生成申报表。请检查此工作区是否设置了税务管辖区。',
      ar: 'تعذّر إعداد الإقرار. تحقق من أن مساحة العمل هذه لديها ولاية ضريبية.',
      pl: 'Nie udało się przygotować deklaracji. Sprawdź, czy ten obszar roboczy ma jurysdykcję podatkową.',
      it: 'Impossibile generare la dichiarazione. Verifica che questo spazio di lavoro abbia una giurisdizione fiscale.',
      sk: 'Priznanie sa nepodarilo zostaviť. Skontrolujte, či má tento pracovný priestor nastavenú daňovú jurisdikciu.',
      ja: '申告を作成できませんでした。このワークスペースに税務管轄が設定されているか確認してください。',
      ko: '신고서를 만들지 못했습니다. 이 워크스페이스에 세무 관할이 설정되어 있는지 확인하세요.',
      hi: 'रिटर्न तैयार नहीं हो सका। जाँचें कि इस वर्कस्पेस में कर क्षेत्राधिकार सेट है।',
      nl: 'De aangifte kon niet worden opgesteld. Controleer of deze werkruimte een belastingjurisdictie heeft.',
      sv: 'Det gick inte att ta fram deklarationen. Kontrollera att arbetsytan har en skattejurisdiktion.',
      vi: 'Không thể lập tờ khai. Hãy kiểm tra không gian làm việc này đã có khu vực tài phán thuế chưa.',
      id: 'Tidak dapat menyusun SPT. Pastikan ruang kerja ini memiliki yurisdiksi pajak.',
    }),
    registrationThreshold: t({
      ru: 'Порог регистрации',
      en: 'Registration threshold',
      kk: 'Тіркеу шегі',
      de: 'Registrierungsschwelle',
      fr: 'Seuil d’immatriculation',
      es: 'Umbral de registro',
      pt: 'Limite de registo',
      tr: 'Kayıt eşiği',
      uk: 'Поріг реєстрації',
      zh: '登记门槛',
      ar: 'حد التسجيل',
      pl: 'Próg rejestracji',
      it: 'Soglia di registrazione',
      sk: 'Registračný limit',
      ja: '登録基準額',
      ko: '등록 기준액',
      hi: 'पंजीकरण सीमा',
      nl: 'Registratiedrempel',
      sv: 'Registreringsgräns',
      vi: 'Ngưỡng đăng ký',
      id: 'Ambang pendaftaran',
    }),
    thresholdProgress: t({
      ru: '{turnover} из {threshold} — {percent}%',
      en: '{turnover} of {threshold} — {percent}%',
      kk: '{turnover} / {threshold} — {percent}%',
      de: '{turnover} von {threshold} — {percent} %',
      fr: '{turnover} sur {threshold} — {percent} %',
      es: '{turnover} de {threshold} — {percent}%',
      pt: '{turnover} de {threshold} — {percent}%',
      tr: '{turnover} / {threshold} — %{percent}',
      uk: '{turnover} з {threshold} — {percent}%',
      zh: '{turnover} / {threshold} — {percent}%',
      ar: '{turnover} من {threshold} — {percent}%',
      pl: '{turnover} z {threshold} — {percent}%',
      it: '{turnover} su {threshold} — {percent}%',
      sk: '{turnover} z {threshold} — {percent} %',
      ja: '{turnover} / {threshold} — {percent}%',
      ko: '{turnover} / {threshold} — {percent}%',
      hi: '{threshold} में से {turnover} — {percent}%',
      nl: '{turnover} van {threshold} — {percent}%',
      sv: '{turnover} av {threshold} — {percent} %',
      vi: '{turnover} / {threshold} — {percent}%',
      id: '{turnover} dari {threshold} — {percent}%',
    }),
    outputTax: t({
      ru: 'Исходящий налог',
      en: 'Output tax',
      kk: 'Шығыс салығы',
      de: 'Umsatzsteuer',
      fr: 'TVA collectée',
      es: 'IVA repercutido',
      pt: 'Imposto liquidado',
      tr: 'Hesaplanan vergi',
      uk: 'Вихідний податок',
      zh: '销项税',
      ar: 'ضريبة المخرجات',
      pl: 'Podatek należny',
      it: 'IVA a debito',
      sk: 'Výstupná daň',
      ja: '売上税額',
      ko: '매출세액',
      hi: 'आउटपुट कर',
      nl: 'Af te dragen btw',
      sv: 'Utgående moms',
      vi: 'Thuế đầu ra',
      id: 'Pajak keluaran',
    }),
    inputTax: t({
      ru: 'Входящий налог',
      en: 'Input tax',
      kk: 'Кіріс салығы',
      de: 'Vorsteuer',
      fr: 'TVA déductible',
      es: 'IVA soportado',
      pt: 'Imposto dedutível',
      tr: 'İndirilecek vergi',
      uk: 'Вхідний податок',
      zh: '进项税',
      ar: 'ضريبة المدخلات',
      pl: 'Podatek naliczony',
      it: 'IVA a credito',
      sk: 'Vstupná daň',
      ja: '仕入税額',
      ko: '매입세액',
      hi: 'इनपुट कर',
      nl: 'Voorbelasting',
      sv: 'Ingående moms',
      vi: 'Thuế đầu vào',
      id: 'Pajak masukan',
    }),
    reclaimable: t({
      ru: 'К возврату',
      en: 'Reclaimable',
      kk: 'Қайтаруға',
      de: 'Erstattungsfähig',
      fr: 'Remboursable',
      es: 'Recuperable',
      pt: 'A recuperar',
      tr: 'İade edilebilir',
      uk: 'До повернення',
      zh: '可退还',
      ar: 'قابل للاسترداد',
      pl: 'Do zwrotu',
      it: 'Rimborsabile',
      sk: 'Na vrátenie',
      ja: '還付可能',
      ko: '환급 가능',
      hi: 'वापसी योग्य',
      nl: 'Terug te vorderen',
      sv: 'Återbetalningsbart',
      vi: 'Được hoàn',
      id: 'Dapat dikembalikan',
    }),
    payable: t({
      ru: 'К уплате',
      en: 'Payable',
      kk: 'Төлеуге',
      de: 'Zahllast',
      fr: 'À payer',
      es: 'A pagar',
      pt: 'A pagar',
      tr: 'Ödenecek',
      uk: 'До сплати',
      zh: '应缴',
      ar: 'مستحق الدفع',
      pl: 'Do zapłaty',
      it: 'Da versare',
      sk: 'Na úhradu',
      ja: '納付額',
      ko: '납부액',
      hi: 'देय',
      nl: 'Te betalen',
      sv: 'Att betala',
      vi: 'Phải nộp',
      id: 'Terutang',
    }),
    statusFiled: t({
      ru: 'Подана',
      en: 'Filed',
      kk: 'Тапсырылды',
      de: 'Eingereicht',
      fr: 'Déposée',
      es: 'Presentada',
      pt: 'Enviada',
      tr: 'Verildi',
      uk: 'Подано',
      zh: '已提交',
      ar: 'مقدَّم',
      pl: 'Złożona',
      it: 'Presentata',
      sk: 'Podané',
      ja: '提出済み',
      ko: '제출됨',
      hi: 'दाखिल',
      nl: 'Ingediend',
      sv: 'Inlämnad',
      vi: 'Đã nộp',
      id: 'Diajukan',
    }),
    statusDraft: t({
      ru: 'Черновик',
      en: 'Draft',
      kk: 'Жоба',
      de: 'Entwurf',
      fr: 'Brouillon',
      es: 'Borrador',
      pt: 'Rascunho',
      tr: 'Taslak',
      uk: 'Чернетка',
      zh: '草稿',
      ar: 'مسودة',
      pl: 'Szkic',
      it: 'Bozza',
      sk: 'Koncept',
      ja: '下書き',
      ko: '초안',
      hi: 'ड्राफ़्ट',
      nl: 'Concept',
      sv: 'Utkast',
      vi: 'Bản nháp',
      id: 'Draf',
    }),
    reopenPeriod: t({
      ru: 'Открыть период заново',
      en: 'Reopen period',
      kk: 'Кезеңді қайта ашу',
      de: 'Zeitraum wieder öffnen',
      fr: 'Rouvrir la période',
      es: 'Reabrir periodo',
      pt: 'Reabrir período',
      tr: 'Dönemi yeniden aç',
      uk: 'Знову відкрити період',
      zh: '重新打开期间',
      ar: 'إعادة فتح الفترة',
      pl: 'Otwórz okres ponownie',
      it: 'Riapri periodo',
      sk: 'Znova otvoriť obdobie',
      ja: '期間を再開',
      ko: '기간 다시 열기',
      hi: 'अवधि फिर से खोलें',
      nl: 'Periode heropenen',
      sv: 'Öppna perioden igen',
      vi: 'Mở lại kỳ',
      id: 'Buka kembali periode',
    }),
    fileAndLock: t({
      ru: 'Подать и заблокировать',
      en: 'File and lock',
      kk: 'Тапсыру және бұғаттау',
      de: 'Einreichen und sperren',
      fr: 'Déposer et verrouiller',
      es: 'Presentar y bloquear',
      pt: 'Enviar e bloquear',
      tr: 'Ver ve kilitle',
      uk: 'Подати й заблокувати',
      zh: '提交并锁定',
      ar: 'تقديم وقفل',
      pl: 'Złóż i zablokuj',
      it: 'Presenta e blocca',
      sk: 'Podať a uzamknúť',
      ja: '提出してロック',
      ko: '제출 및 잠금',
      hi: 'दाखिल करें और लॉक करें',
      nl: 'Indienen en vergrendelen',
      sv: 'Lämna in och lås',
      vi: 'Nộp và khóa',
      id: 'Ajukan dan kunci',
    }),
    filedNotice: t({
      ru: 'Этот период подан. Транзакции за ним заблокированы, а показанные цифры — те, что были отправлены.',
      en: 'This period is filed. The transactions behind it are locked, and the figures shown are the ones that were submitted.',
      kk: 'Бұл кезең тапсырылды. Оның транзакциялары бұғатталған, ал көрсетілген сандар — жіберілгендері.',
      de: 'Dieser Zeitraum ist eingereicht. Die zugrunde liegenden Transaktionen sind gesperrt, und die angezeigten Zahlen sind die übermittelten.',
      fr: 'Cette période est déposée. Les transactions qui la composent sont verrouillées et les montants affichés sont ceux qui ont été transmis.',
      es: 'Este periodo está presentado. Las transacciones que lo componen están bloqueadas y las cifras mostradas son las que se enviaron.',
      pt: 'Este período foi enviado. As transações que o compõem estão bloqueadas e os valores mostrados são os que foram submetidos.',
      tr: 'Bu dönem verildi. Arkasındaki işlemler kilitlidir ve gösterilen rakamlar gönderilenlerdir.',
      uk: 'Цей період подано. Транзакції за ним заблоковано, а показані цифри — ті, що були надіслані.',
      zh: '此期间已提交。其中的交易已锁定，显示的数字即为已提交的数字。',
      ar: 'تم تقديم هذه الفترة. المعاملات التي تستند إليها مقفلة، والأرقام المعروضة هي التي قُدِّمت.',
      pl: 'Ten okres został złożony. Transakcje, na których się opiera, są zablokowane, a pokazane kwoty to te, które zostały przesłane.',
      it: 'Questo periodo è stato presentato. Le transazioni su cui si basa sono bloccate e gli importi mostrati sono quelli inviati.',
      sk: 'Toto obdobie je podané. Transakcie, na ktorých stojí, sú uzamknuté a zobrazené sumy sú tie, ktoré boli odoslané.',
      ja: 'この期間は提出済みです。対象の取引はロックされ、表示されている数値は提出したものです。',
      ko: '이 기간은 제출되었습니다. 해당 거래는 잠겨 있으며, 표시된 수치는 제출된 값입니다.',
      hi: 'यह अवधि दाखिल हो चुकी है। इसके पीछे के लेनदेन लॉक हैं, और दिखाए गए आँकड़े वही हैं जो जमा किए गए थे।',
      nl: 'Deze periode is ingediend. De onderliggende transacties zijn vergrendeld en de getoonde bedragen zijn de ingediende.',
      sv: 'Den här perioden är inlämnad. Transaktionerna bakom den är låsta och siffrorna som visas är de som skickades in.',
      vi: 'Kỳ này đã được nộp. Các giao dịch trong kỳ đã bị khóa và số liệu hiển thị là số liệu đã nộp.',
      id: 'Periode ini sudah diajukan. Transaksi di dalamnya dikunci, dan angka yang ditampilkan adalah yang telah dikirim.',
    }),
    colDate: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
    }),
    colCounterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı taraf',
      uk: 'Контрагент',
      zh: '交易对方',
      ar: 'الطرف المقابل',
      pl: 'Kontrahent',
      it: 'Controparte',
      sk: 'Protistrana',
      ja: '取引先',
      ko: '거래 상대방',
      hi: 'प्रतिपक्ष',
      nl: 'Tegenpartij',
      sv: 'Motpart',
      vi: 'Đối tác',
      id: 'Pihak lawan',
    }),
    colKind: t({
      ru: 'Вид',
      en: 'Kind',
      kk: 'Түрі',
      de: 'Art',
      fr: 'Type',
      es: 'Tipo',
      pt: 'Tipo',
      tr: 'Tür',
      uk: 'Вид',
      zh: '类型',
      ar: 'النوع',
      pl: 'Rodzaj',
      it: 'Tipo',
      sk: 'Druh',
      ja: '種類',
      ko: '종류',
      hi: 'प्रकार',
      nl: 'Soort',
      sv: 'Typ',
      vi: 'Loại',
      id: 'Jenis',
    }),
    colTax: t({
      ru: 'Налог',
      en: 'Tax',
      kk: 'Салық',
      de: 'Steuer',
      fr: 'Taxe',
      es: 'Impuesto',
      pt: 'Imposto',
      tr: 'Vergi',
      uk: 'Податок',
      zh: '税额',
      ar: 'الضريبة',
      pl: 'Podatek',
      it: 'Imposta',
      sk: 'Daň',
      ja: '税額',
      ko: '세액',
      hi: 'कर',
      nl: 'Belasting',
      sv: 'Skatt',
      vi: 'Thuế',
      id: 'Pajak',
    }),
    colRate: t({
      ru: 'Курс',
      en: 'Rate',
      kk: 'Бағам',
      de: 'Kurs',
      fr: 'Taux',
      es: 'Tipo de cambio',
      pt: 'Câmbio',
      tr: 'Kur',
      uk: 'Курс',
      zh: '汇率',
      ar: 'سعر الصرف',
      pl: 'Kurs',
      it: 'Cambio',
      sk: 'Kurz',
      ja: 'レート',
      ko: '환율',
      hi: 'दर',
      nl: 'Koers',
      sv: 'Kurs',
      vi: 'Tỷ giá',
      id: 'Kurs',
    }),
    colInCurrency: t({
      ru: 'В {currency}',
      en: 'In {currency}',
      kk: '{currency} бойынша',
      de: 'In {currency}',
      fr: 'En {currency}',
      es: 'En {currency}',
      pt: 'Em {currency}',
      tr: '{currency} cinsinden',
      uk: 'У {currency}',
      zh: '折合 {currency}',
      ar: 'بـ {currency}',
      pl: 'W {currency}',
      it: 'In {currency}',
      sk: 'V {currency}',
      ja: '{currency} 換算',
      ko: '{currency} 기준',
      hi: '{currency} में',
      nl: 'In {currency}',
      sv: 'I {currency}',
      vi: 'Theo {currency}',
      id: 'Dalam {currency}',
    }),
    noLines: t({
      ru: 'В этом периоде нет облагаемых транзакций.',
      en: 'No taxed transactions in this period.',
      kk: 'Бұл кезеңде салық салынатын транзакциялар жоқ.',
      de: 'Keine besteuerten Transaktionen in diesem Zeitraum.',
      fr: 'Aucune transaction taxée sur cette période.',
      es: 'No hay transacciones gravadas en este periodo.',
      pt: 'Não há transações tributadas neste período.',
      tr: 'Bu dönemde vergilendirilmiş işlem yok.',
      uk: 'У цьому періоді немає оподатковуваних транзакцій.',
      zh: '此期间没有应税交易。',
      ar: 'لا توجد معاملات خاضعة للضريبة في هذه الفترة.',
      pl: 'Brak opodatkowanych transakcji w tym okresie.',
      it: 'Nessuna transazione tassata in questo periodo.',
      sk: 'V tomto období nie sú žiadne zdanené transakcie.',
      ja: 'この期間に課税取引はありません。',
      ko: '이 기간에 과세 거래가 없습니다.',
      hi: 'इस अवधि में कोई कर-योग्य लेनदेन नहीं है।',
      nl: 'Geen belaste transacties in deze periode.',
      sv: 'Inga beskattade transaktioner under perioden.',
      vi: 'Không có giao dịch chịu thuế trong kỳ này.',
      id: 'Tidak ada transaksi kena pajak pada periode ini.',
    }),
    disclaimer: t({
      ru: 'Эти цифры рассчитаны по вашим собственным данным с использованием ставок, которые мы поддерживаем, и не заменяют консультацию бухгалтера. Проверьте их, прежде чем что-либо подавать.',
      en: 'These figures are produced from your own data using rates we maintain, and are not a substitute for advice from an accountant. Check them before submitting anything.',
      kk: 'Бұл сандар сіздің деректеріңізден біз жүргізетін мөлшерлемелер бойынша есептеледі және бухгалтер кеңесін алмастырмайды. Бірдеңе тапсырмас бұрын оларды тексеріңіз.',
      de: 'Diese Zahlen werden aus Ihren eigenen Daten mit von uns gepflegten Sätzen berechnet und ersetzen keine Beratung durch eine Steuerberaterin oder einen Steuerberater. Prüfen Sie sie, bevor Sie etwas einreichen.',
      fr: 'Ces montants sont calculés à partir de vos propres données avec des taux que nous tenons à jour, et ne remplacent pas les conseils d’un comptable. Vérifiez-les avant de soumettre quoi que ce soit.',
      es: 'Estas cifras se calculan con sus propios datos y con tipos que mantenemos nosotros, y no sustituyen el asesoramiento de un contable. Revíselas antes de presentar nada.',
      pt: 'Estes valores são calculados a partir dos seus próprios dados com taxas que mantemos e não substituem o aconselhamento de um contabilista. Verifique-os antes de submeter qualquer coisa.',
      tr: 'Bu rakamlar, sizin verilerinizden bizim güncel tuttuğumuz oranlarla hesaplanır ve bir muhasebecinin tavsiyesinin yerini tutmaz. Herhangi bir şey göndermeden önce kontrol edin.',
      uk: 'Ці цифри розраховано з ваших власних даних за ставками, які ми підтримуємо, і вони не замінюють консультацію бухгалтера. Перевірте їх, перш ніж щось подавати.',
      zh: '这些数字根据您自己的数据和我们维护的税率计算得出，不能替代会计师的建议。提交任何内容前请先核对。',
      ar: 'تُحسب هذه الأرقام من بياناتك باستخدام معدلات نحتفظ بها، وهي ليست بديلاً عن استشارة محاسب. راجعها قبل تقديم أي شيء.',
      pl: 'Te kwoty są wyliczane z Twoich danych według stawek, które utrzymujemy, i nie zastępują porady księgowego. Sprawdź je, zanim cokolwiek złożysz.',
      it: 'Questi importi sono calcolati dai tuoi dati con aliquote che manteniamo noi e non sostituiscono il parere di un commercialista. Controllali prima di inviare qualsiasi cosa.',
      sk: 'Tieto sumy sú vypočítané z vašich vlastných údajov podľa sadzieb, ktoré udržiavame, a nenahrádzajú radu účtovníka. Pred akýmkoľvek podaním ich skontrolujte.',
      ja: 'これらの数値は、お客様のデータと当社が管理する税率から算出したもので、会計士の助言に代わるものではありません。提出前に必ず確認してください。',
      ko: '이 수치는 사용자의 데이터와 저희가 관리하는 세율로 산출되며, 회계사의 조언을 대신하지 않습니다. 제출하기 전에 확인하세요.',
      hi: 'ये आँकड़े आपके अपने डेटा से हमारे द्वारा रखी गई दरों पर बनाए जाते हैं, और किसी अकाउंटेंट की सलाह का विकल्प नहीं हैं। कुछ भी जमा करने से पहले इन्हें जाँच लें।',
      nl: 'Deze bedragen worden berekend uit uw eigen gegevens met tarieven die wij bijhouden, en vervangen geen advies van een accountant. Controleer ze voordat u iets indient.',
      sv: 'Siffrorna tas fram ur dina egna data med skattesatser som vi underhåller och ersätter inte råd från en revisor. Kontrollera dem innan du skickar in något.',
      vi: 'Các số liệu này được tính từ dữ liệu của bạn theo thuế suất do chúng tôi duy trì và không thay thế lời khuyên của kế toán. Hãy kiểm tra trước khi nộp bất cứ thứ gì.',
      id: 'Angka-angka ini dihitung dari data Anda sendiri dengan tarif yang kami kelola, dan bukan pengganti saran akuntan. Periksa sebelum mengajukan apa pun.',
    }),
  },
} satisfies Dictionary;

export default content;
