import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'pluginsPage',
  content: {
    title: t({
      ru: 'Плагины',
      en: 'Plugins',
      kk: 'Плагиндер',
      de: 'Plugins',
      fr: 'Plugins',
      es: 'Complementos',
      pt: 'Plug-ins',
      tr: 'Eklentiler',
      uk: 'Плагіни',
      zh: '插件',
      ar: 'الإضافات',
      pl: 'Wtyczki',
      it: 'Plugin',
      sk: 'Doplnky',
      ja: 'プラグイン',
      ko: '플러그인',
      hi: 'प्लगइन',
      nl: 'Plug-ins',
      sv: 'Plugin-program',
      vi: 'Plugin',
      id: 'Plugin',
    }),
    subtitle: t({
      ru: 'Расширяйте возможности Lumio с помощью плагинов.',
      en: 'Extend Lumio with powerful plugins.',
      kk: 'Lumio мүмкіндіктерін плагиндермен кеңейтіңіз.',
      de: 'Erweitern Sie Lumio mit leistungsstarken Plugins.',
      fr: 'Étendez Lumio avec des plugins puissants.',
      es: 'Amplía Lumio con complementos potentes.',
      pt: 'Estenda o Lumio com plugins poderosos.',
      tr: "Lumio'yu güçlü eklentilerle genişletin.",
      uk: 'Розширюйте можливості Lumio за допомогою плагінів.',
      zh: '使用强大的插件扩展 Lumio。',
      ar: 'وسّع Lumio بإضافات قوية.',
      pl: 'Rozszerzaj Lumio za pomocą wtyczek.',
      it: 'Estendi Lumio con potenti plugin.',
      sk: 'Rozšírte Lumio o výkonné doplnky.',
      ja: '強力なプラグインでLumioを拡張しましょう。',
      ko: '강력한 플러그인으로 Lumio를 확장하세요.',
      hi: 'शक्तिशाली प्लगइन के साथ Lumio का विस्तार करें।',
      nl: 'Breid Lumio uit met krachtige plug-ins.',
      sv: 'Utöka Lumio med kraftfulla plugin-program.',
      vi: 'Mở rộng Lumio với các plugin mạnh mẽ.',
      id: 'Perluas Lumio dengan plugin yang powerful.',
    }),
    sections: {
      enabled: t({
        ru: 'Включено',
        en: 'Enabled',
        kk: 'Қосылған',
        de: 'Aktiviert',
        fr: 'Activé',
        es: 'Activado',
        pt: 'Ativado',
        tr: 'Etkin',
        uk: 'Увімкнено',
        zh: '已启用',
        ar: 'مفعّل',
        pl: 'Włączone',
        it: 'Attivato',
        sk: 'Zapnuté',
        ja: '有効',
        ko: '활성화됨',
        hi: 'सक्षम',
        nl: 'Ingeschakeld',
        sv: 'Aktiverade',
        vi: 'Đã bật',
        id: 'Diaktifkan',
      }),
      available: t({
        ru: 'Доступно',
        en: 'Available',
        kk: 'Қолжетімді',
        de: 'Verfügbar',
        fr: 'Disponible',
        es: 'Disponible',
        pt: 'Disponível',
        tr: 'Mevcut',
        uk: 'Доступно',
        zh: '可用',
        ar: 'متاح',
        pl: 'Dostępne',
        it: 'Disponibile',
        sk: 'Dostupné',
        ja: '利用可能',
        ko: '사용 가능',
        hi: 'उपलब्ध',
        nl: 'Beschikbaar',
        sv: 'Tillgängliga',
        vi: 'Có sẵn',
        id: 'Tersedia',
      }),
    },
    enable: t({
      ru: 'Включить',
      en: 'Enable',
      kk: 'Қосу',
      de: 'Aktivieren',
      fr: 'Activer',
      es: 'Activar',
      pt: 'Ativar',
      tr: 'Etkinleştir',
      uk: 'Увімкнути',
      zh: '启用',
      ar: 'تفعيل',
      pl: 'Włącz',
      it: 'Attiva',
      sk: 'Zapnúť',
      ja: '有効にする',
      ko: '활성화',
      hi: 'सक्षम करें',
      nl: 'Inschakelen',
      sv: 'Aktivera',
      vi: 'Bật',
      id: 'Aktifkan',
    }),
    disable: t({
      ru: 'Отключить',
      en: 'Disable',
      kk: 'Өшіру',
      de: 'Deaktivieren',
      fr: 'Désactiver',
      es: 'Desactivar',
      pt: 'Desativar',
      tr: 'Devre dışı bırak',
      uk: 'Вимкнути',
      zh: '禁用',
      ar: 'تعطيل',
      pl: 'Wyłącz',
      it: 'Disattiva',
      sk: 'Vypnúť',
      ja: '無効にする',
      ko: '비활성화',
      hi: 'अक्षम करें',
      nl: 'Uitschakelen',
      sv: 'Inaktivera',
      vi: 'Tắt',
      id: 'Nonaktifkan',
    }),
    cards: {
      aiAssistant: {
        name: t({
          ru: 'AI Ассистент',
          en: 'AI Assistant',
          kk: 'AI Көмекші',
          de: 'KI-Assistent',
          fr: 'Assistant IA',
          es: 'Asistente IA',
          pt: 'Assistente IA',
          tr: 'Yapay Zeka Asistanı',
          uk: 'AI Асистент',
          zh: 'AI 助手',
          ar: 'مساعد الذكاء الاصطناعي',
          pl: 'Asystent AI',
          it: 'Assistente IA',
          sk: 'AI asistent',
          ja: 'AIアシスタント',
          ko: 'AI 어시스턴트',
          hi: 'AI सहायक',
          nl: 'AI-assistent',
          sv: 'AI-assistent',
          vi: 'Trợ lý AI',
          id: 'Asisten AI',
        }),
        description: t({
          ru: 'Анализируйте финансовые данные с помощью ИИ. Подготавливает промпты с вашими данными и передаёт их в ChatGPT.',
          en: 'Analyze financial data with AI. Prepares prompts with your data and hands off to ChatGPT.',
          kk: 'Қаржылық деректерді AI көмегімен талдаңыз. Деректеріңізбен промпттар дайындап, ChatGPT-ге жібереді.',
          de: 'Analysieren Sie Finanzdaten mit KI. Erstellt Prompts mit Ihren Daten und übergibt sie an ChatGPT.',
          fr: "Analysez vos données financières avec l'IA. Prépare des prompts avec vos données et les transmet à ChatGPT.",
          es: 'Analiza datos financieros con IA. Prepara prompts con tus datos y los envía a ChatGPT.',
          pt: 'Analise dados financeiros com IA. Prepara prompts com seus dados e envia ao ChatGPT.',
          tr: "Finansal verileri yapay zeka ile analiz edin. Verilerinizle promptlar hazırlar ve ChatGPT'ye aktarır.",
          uk: 'Аналізуйте фінансові дані за допомогою ШІ. Готує промпти з вашими даними та передає їх у ChatGPT.',
          zh: '使用 AI 分析财务数据。准备包含您数据的提示并移交给 ChatGPT。',
          ar: 'حلّل البيانات المالية بالذكاء الاصطناعي. يُعدّ المطالبات ببياناتك ويرسلها إلى ChatGPT.',
          pl: 'Analizuj dane finansowe z pomocą AI. Przygotowuje prompty z Twoimi danymi i przekazuje do ChatGPT.',
          it: "Analizza i dati finanziari con l'IA. Prepara prompt con i tuoi dati e li invia a ChatGPT.",
          sk: 'Analyzujte finančné údaje pomocou AI. Pripraví prompty s vašimi údajmi a odovzdá ich do ChatGPT.',
          ja: 'AIで財務データを分析します。あなたのデータでプロンプトを準備してChatGPTに渡します。',
          ko: 'AI로 재무 데이터를 분석합니다. 데이터로 프롬프트를 준비하고 ChatGPT에 전달합니다.',
          hi: 'AI के साथ वित्तीय डेटा का विश्लेषण करें। आपके डेटा के साथ प्रॉम्प्ट तैयार करता है और ChatGPT को भेजता है।',
          nl: 'Analyseer financiële gegevens met AI. Bereidt prompts voor met uw gegevens en stuurt deze door naar ChatGPT.',
          sv: 'Analysera finansiell data med AI. Förbereder uppmaningar med dina data och skickar vidare till ChatGPT.',
          vi: 'Phân tích dữ liệu tài chính bằng AI. Chuẩn bị các gợi ý với dữ liệu của bạn và chuyển sang ChatGPT.',
          id: 'Analisis data keuangan dengan AI. Menyiapkan prompt dengan data Anda dan meneruskan ke ChatGPT.',
        }),
      },
      webhooks: {
        description: t({
          ru: 'Входящие вебхуки для загрузок и исходящие уведомления о событиях.',
          en: 'Inbound webhooks for uploads and outbound notifications for events.',
          kk: 'Жүктеулерге арналған кіріс вебхуктар және оқиғалар туралы шығыс хабарландырулар.',
          de: 'Eingehende Webhooks für Uploads und ausgehende Benachrichtigungen zu Ereignissen.',
          fr: 'Webhooks entrants pour les imports et notifications sortantes pour les événements.',
          es: 'Webhooks entrantes para subidas y notificaciones salientes de eventos.',
          pt: 'Webhooks de entrada para envios e notificações de saída para eventos.',
          tr: 'Yüklemeler için gelen webhook’lar ve olaylar için giden bildirimler.',
          uk: 'Вхідні вебхуки для завантажень і вихідні сповіщення про події.',
          zh: '用于上传的入站 Webhook 和用于事件的出站通知。',
          ar: 'خطافات ويب واردة للرفع وإشعارات صادرة للأحداث.',
          pl: 'Webhooki przychodzące do przesyłania plików i powiadomienia wychodzące o zdarzeniach.',
          it: 'Webhook in entrata per i caricamenti e notifiche in uscita per gli eventi.',
          sk: 'Prichádzajúce webhooky na nahrávanie a odchádzajúce upozornenia na udalosti.',
          ja: 'アップロード用の受信 Webhook と、イベント用の送信通知。',
          ko: '업로드용 수신 웹훅과 이벤트용 발신 알림.',
          hi: 'अपलोड के लिए इनबाउंड वेबहुक और इवेंट के लिए आउटबाउंड सूचनाएँ।',
          nl: 'Inkomende webhooks voor uploads en uitgaande meldingen voor gebeurtenissen.',
          sv: 'Inkommande webhooks för uppladdningar och utgående aviseringar om händelser.',
          vi: 'Webhook đến cho tải lên và thông báo đi cho sự kiện.',
          id: 'Webhook masuk untuk unggahan dan notifikasi keluar untuk peristiwa.',
        }),
      },
      mcpServer: {
        description: t({
          ru: 'Позвольте ИИ-агентам работать с Lumio по протоколу Model Context Protocol.',
          en: 'Let AI agents work with Lumio over the Model Context Protocol.',
          kk: 'ЖИ агенттеріне Lumio-мен Model Context Protocol арқылы жұмыс істеуге мүмкіндік беріңіз.',
          de: 'Lassen Sie KI-Agenten über das Model Context Protocol mit Lumio arbeiten.',
          fr: 'Permettez aux agents IA de travailler avec Lumio via le Model Context Protocol.',
          es: 'Permite que los agentes de IA trabajen con Lumio mediante el Model Context Protocol.',
          pt: 'Permita que agentes de IA trabalhem com o Lumio pelo Model Context Protocol.',
          tr: 'Yapay zeka ajanlarının Model Context Protocol üzerinden Lumio ile çalışmasını sağlayın.',
          uk: 'Дозвольте ШІ-агентам працювати з Lumio через Model Context Protocol.',
          zh: '让 AI 代理通过 Model Context Protocol 使用 Lumio。',
          ar: 'اسمح لوكلاء الذكاء الاصطناعي بالعمل مع Lumio عبر Model Context Protocol.',
          pl: 'Pozwól agentom AI pracować z Lumio przez Model Context Protocol.',
          it: 'Consenti agli agenti IA di lavorare con Lumio tramite il Model Context Protocol.',
          sk: 'Umožnite AI agentom pracovať s Lumio cez Model Context Protocol.',
          ja: 'AI エージェントが Model Context Protocol 経由で Lumio を操作できるようにします。',
          ko: 'AI 에이전트가 Model Context Protocol로 Lumio와 작업하도록 하세요.',
          hi: 'AI एजेंट को Model Context Protocol के ज़रिए Lumio के साथ काम करने दें।',
          nl: 'Laat AI-agents met Lumio werken via het Model Context Protocol.',
          sv: 'Låt AI-agenter arbeta med Lumio via Model Context Protocol.',
          vi: 'Cho phép tác nhân AI làm việc với Lumio qua Model Context Protocol.',
          id: 'Biarkan agen AI bekerja dengan Lumio melalui Model Context Protocol.',
        }),
      },
    },
    toggle: t({
      ru: 'Переключить: {name}',
      en: 'Toggle {name}',
      kk: 'Ауыстыру: {name}',
      de: '{name} umschalten',
      fr: 'Activer/désactiver {name}',
      es: 'Activar o desactivar {name}',
      pt: 'Ativar/desativar {name}',
      tr: '{name} aç/kapat',
      uk: 'Перемкнути: {name}',
      zh: '切换 {name}',
      ar: 'تبديل {name}',
      pl: 'Przełącz: {name}',
      it: 'Attiva/disattiva {name}',
      sk: 'Prepnúť: {name}',
      ja: '{name} を切り替え',
      ko: '{name} 전환',
      hi: '{name} टॉगल करें',
      nl: '{name} in-/uitschakelen',
      sv: 'Växla {name}',
      vi: 'Bật/tắt {name}',
      id: 'Alihkan {name}',
    }),
  },
} satisfies Dictionary;

export default content;
