import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'settingsSyncSection',
  content: {
    title: t({
      ru: 'Экспорт в файловую систему',
      en: 'Export to filesystem',
      kk: 'Файлдық жүйеге экспорттау',
      de: 'Export ins Dateisystem',
      fr: 'Exporter vers le système de fichiers',
      es: 'Exportar al sistema de archivos',
      pt: 'Exportar para o sistema de arquivos',
      tr: 'Dosya sistemine aktar',
      uk: 'Експорт у файлову систему',
      zh: '导出到文件系统',
      ar: 'تصدير إلى نظام الملفات',
      pl: 'Eksport do systemu plików',
      it: 'Esporta nel file system',
      sk: 'Export do súborového systému',
      ja: 'ファイルシステムへエクスポート',
      ko: '파일 시스템으로 내보내기',
      hi: 'फ़ाइल सिस्टम में निर्यात करें',
      nl: 'Exporteren naar bestandssysteem',
      sv: 'Exportera till filsystemet',
      vi: 'Xuất ra hệ thống tệp',
      id: 'Ekspor ke sistem file',
    }),
    intro: t({
      ru: 'Скачайте все свои файлы ZIP-архивом, упорядоченным по банкам и типам файлов. Распакуйте его локально, чтобы синхронизировать с файловой системой.',
      en: 'Download all your files as a ZIP archive organized by bank and file type. Unpack it locally to sync with your filesystem.',
      kk: 'Барлық файлдарыңызды банк пен файл түрі бойынша реттелген ZIP мұрағаты ретінде жүктеп алыңыз. Файлдық жүйемен синхрондау үшін оны жергілікті түрде ашыңыз.',
      de: 'Laden Sie alle Ihre Dateien als ZIP-Archiv herunter, sortiert nach Bank und Dateityp. Entpacken Sie es lokal, um es mit Ihrem Dateisystem zu synchronisieren.',
      fr: 'Téléchargez tous vos fichiers dans une archive ZIP classée par banque et par type de fichier. Décompressez-la en local pour la synchroniser avec votre système de fichiers.',
      es: 'Descarga todos tus archivos en un ZIP organizado por banco y tipo de archivo. Descomprímelo en local para sincronizarlo con tu sistema de archivos.',
      pt: 'Baixe todos os seus arquivos em um ZIP organizado por banco e tipo de arquivo. Descompacte-o localmente para sincronizar com seu sistema de arquivos.',
      tr: 'Tüm dosyalarınızı bankaya ve dosya türüne göre düzenlenmiş bir ZIP arşivi olarak indirin. Dosya sisteminizle eşitlemek için yerel olarak açın.',
      uk: 'Завантажте всі свої файли ZIP-архівом, упорядкованим за банками й типами файлів. Розпакуйте його локально, щоб синхронізувати з файловою системою.',
      zh: '将所有文件下载为按银行和文件类型整理的 ZIP 压缩包。在本地解压即可与文件系统同步。',
      ar: 'نزّل جميع ملفاتك كأرشيف ZIP منظّم حسب البنك ونوع الملف. فك ضغطه محليًا لمزامنته مع نظام ملفاتك.',
      pl: 'Pobierz wszystkie pliki jako archiwum ZIP uporządkowane według banku i typu pliku. Rozpakuj je lokalnie, aby zsynchronizować z systemem plików.',
      it: 'Scarica tutti i tuoi file in un archivio ZIP organizzato per banca e tipo di file. Estrailo in locale per sincronizzarlo con il file system.',
      sk: 'Stiahnite všetky svoje súbory ako archív ZIP usporiadaný podľa banky a typu súboru. Rozbaľte ho lokálne a synchronizujte so súborovým systémom.',
      ja: 'すべてのファイルを、銀行とファイル種別ごとに整理された ZIP アーカイブとしてダウンロードします。ローカルで展開してファイルシステムと同期してください。',
      ko: '모든 파일을 은행과 파일 유형별로 정리된 ZIP 아카이브로 다운로드하세요. 로컬에서 압축을 풀어 파일 시스템과 동기화할 수 있습니다.',
      hi: 'अपनी सभी फ़ाइलें बैंक और फ़ाइल प्रकार के अनुसार व्यवस्थित ZIP आर्काइव के रूप में डाउनलोड करें। फ़ाइल सिस्टम से सिंक करने के लिए इसे लोकल रूप से अनज़िप करें।',
      nl: 'Download al je bestanden als ZIP-archief, geordend per bank en bestandstype. Pak het lokaal uit om te synchroniseren met je bestandssysteem.',
      sv: 'Ladda ned alla dina filer som ett ZIP-arkiv sorterat efter bank och filtyp. Packa upp det lokalt för att synkronisera med ditt filsystem.',
      vi: 'Tải xuống tất cả tệp của bạn dưới dạng tệp ZIP được sắp xếp theo ngân hàng và loại tệp. Giải nén cục bộ để đồng bộ với hệ thống tệp.',
      id: 'Unduh semua file Anda sebagai arsip ZIP yang disusun menurut bank dan jenis file. Ekstrak secara lokal untuk menyinkronkan dengan sistem file Anda.',
    }),
    foldersIntro: t({
      ru: 'Файлы будут разложены по папкам:',
      en: 'Files will be organized into folders:',
      kk: 'Файлдар қалталарға бөлінеді:',
      de: 'Die Dateien werden in Ordnern abgelegt:',
      fr: 'Les fichiers seront classés dans des dossiers :',
      es: 'Los archivos se organizarán en carpetas:',
      pt: 'Os arquivos serão organizados em pastas:',
      tr: 'Dosyalar klasörlere ayrılacak:',
      uk: 'Файли буде розкладено по теках:',
      zh: '文件将按以下文件夹整理：',
      ar: 'سيتم تنظيم الملفات في مجلدات:',
      pl: 'Pliki zostaną uporządkowane w folderach:',
      it: 'I file verranno organizzati in cartelle:',
      sk: 'Súbory budú usporiadané do priečinkov:',
      ja: 'ファイルは次のフォルダーに整理されます：',
      ko: '파일은 다음 폴더로 정리됩니다:',
      hi: 'फ़ाइलें इन फ़ोल्डरों में व्यवस्थित होंगी:',
      nl: 'Bestanden worden in mappen geordend:',
      sv: 'Filerna ordnas i mappar:',
      vi: 'Tệp sẽ được sắp xếp vào các thư mục:',
      id: 'File akan disusun ke dalam folder:',
    }),
    loadingStructure: t({
      ru: 'Загрузка структуры…',
      en: 'Loading structure…',
      kk: 'Құрылым жүктелуде…',
      de: 'Struktur wird geladen…',
      fr: 'Chargement de la structure…',
      es: 'Cargando estructura…',
      pt: 'Carregando estrutura…',
      tr: 'Yapı yükleniyor…',
      uk: 'Завантаження структури…',
      zh: '正在加载结构…',
      ar: 'جارٍ تحميل البنية…',
      pl: 'Wczytywanie struktury…',
      it: 'Caricamento della struttura…',
      sk: 'Načítava sa štruktúra…',
      ja: '構成を読み込み中…',
      ko: '구조를 불러오는 중…',
      hi: 'संरचना लोड हो रही है…',
      nl: 'Structuur laden…',
      sv: 'Läser in strukturen…',
      vi: 'Đang tải cấu trúc…',
      id: 'Memuat struktur…',
    }),
    noFilesYet: t({
      ru: '(файлов пока нет)',
      en: '(no files yet)',
      kk: '(әзірге файлдар жоқ)',
      de: '(noch keine Dateien)',
      fr: '(aucun fichier pour le moment)',
      es: '(aún no hay archivos)',
      pt: '(ainda não há arquivos)',
      tr: '(henüz dosya yok)',
      uk: '(файлів поки немає)',
      zh: '（暂无文件）',
      ar: '(لا توجد ملفات بعد)',
      pl: '(brak plików)',
      it: '(ancora nessun file)',
      sk: '(zatiaľ žiadne súbory)',
      ja: '（ファイルはまだありません）',
      ko: '(아직 파일 없음)',
      hi: '(अभी कोई फ़ाइल नहीं)',
      nl: '(nog geen bestanden)',
      sv: '(inga filer ännu)',
      vi: '(chưa có tệp nào)',
      id: '(belum ada file)',
    }),
    exporting: t({
      ru: 'Экспорт…',
      en: 'Exporting…',
      kk: 'Экспортталуда…',
      de: 'Wird exportiert…',
      fr: 'Exportation…',
      es: 'Exportando…',
      pt: 'Exportando…',
      tr: 'Dışa aktarılıyor…',
      uk: 'Експорт…',
      zh: '正在导出…',
      ar: 'جارٍ التصدير…',
      pl: 'Eksportowanie…',
      it: 'Esportazione…',
      sk: 'Exportuje sa…',
      ja: 'エクスポート中…',
      ko: '내보내는 중…',
      hi: 'निर्यात हो रहा है…',
      nl: 'Bezig met exporteren…',
      sv: 'Exporterar…',
      vi: 'Đang xuất…',
      id: 'Mengekspor…',
    }),
    exportZip: t({
      ru: 'Экспорт ZIP',
      en: 'Export ZIP',
      kk: 'ZIP экспорттау',
      de: 'ZIP exportieren',
      fr: 'Exporter en ZIP',
      es: 'Exportar ZIP',
      pt: 'Exportar ZIP',
      tr: "ZIP'e aktar",
      uk: 'Експорт ZIP',
      zh: '导出 ZIP',
      ar: 'تصدير ZIP',
      pl: 'Eksportuj ZIP',
      it: 'Esporta ZIP',
      sk: 'Exportovať ZIP',
      ja: 'ZIP をエクスポート',
      ko: 'ZIP 내보내기',
      hi: 'ZIP निर्यात करें',
      nl: 'ZIP exporteren',
      sv: 'Exportera ZIP',
      vi: 'Xuất ZIP',
      id: 'Ekspor ZIP',
    }),
    exportZipCount: t({
      ru: 'Экспорт ZIP (файлов: {count})',
      en: 'Export ZIP ({count} files)',
      kk: 'ZIP экспорттау (файлдар: {count})',
      de: 'ZIP exportieren ({count} Dateien)',
      fr: 'Exporter en ZIP ({count} fichiers)',
      es: 'Exportar ZIP ({count} archivos)',
      pt: 'Exportar ZIP ({count} arquivos)',
      tr: "ZIP'e aktar ({count} dosya)",
      uk: 'Експорт ZIP (файлів: {count})',
      zh: '导出 ZIP（{count} 个文件）',
      ar: 'تصدير ZIP (الملفات: {count})',
      pl: 'Eksportuj ZIP (pliki: {count})',
      it: 'Esporta ZIP ({count} file)',
      sk: 'Exportovať ZIP (súbory: {count})',
      ja: 'ZIP をエクスポート（{count} ファイル）',
      ko: 'ZIP 내보내기(파일 {count}개)',
      hi: 'ZIP निर्यात करें ({count} फ़ाइलें)',
      nl: 'ZIP exporteren ({count} bestanden)',
      sv: 'Exportera ZIP ({count} filer)',
      vi: 'Xuất ZIP ({count} tệp)',
      id: 'Ekspor ZIP ({count} file)',
    }),
    noFilesToExport: t({
      ru: 'Нет файлов для экспорта',
      en: 'No files to export',
      kk: 'Экспорттайтын файлдар жоқ',
      de: 'Keine Dateien zum Exportieren',
      fr: 'Aucun fichier à exporter',
      es: 'No hay archivos para exportar',
      pt: 'Não há arquivos para exportar',
      tr: 'Dışa aktarılacak dosya yok',
      uk: 'Немає файлів для експорту',
      zh: '没有可导出的文件',
      ar: 'لا توجد ملفات للتصدير',
      pl: 'Brak plików do eksportu',
      it: 'Nessun file da esportare',
      sk: 'Žiadne súbory na export',
      ja: 'エクスポートするファイルがありません',
      ko: '내보낼 파일이 없습니다',
      hi: 'निर्यात के लिए कोई फ़ाइल नहीं',
      nl: 'Geen bestanden om te exporteren',
      sv: 'Inga filer att exportera',
      vi: 'Không có tệp để xuất',
      id: 'Tidak ada file untuk diekspor',
    }),
  },
} satisfies Dictionary;

export default content;
