/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementsSpendOverTime',
  content: {
    previousMonth: t({
      ru: 'Предыдущий месяц',
      en: 'Previous month',
      kk: 'Алдыңғы ай',
      de: 'Vorheriger Monat',
      fr: 'Mois précédent',
      es: 'Mes anterior',
      pt: 'Mês anterior',
      tr: 'Önceki ay',
      uk: 'Попередній місяць',
      zh: '上个月',
      ar: 'الشهر السابق',
      pl: 'Poprzedni miesiąc',
      it: 'Mese precedente',
      sk: 'Predchádzajúci mesiac',
      ja: '前月',
      ko: '이전 달',
      hi: 'पिछला महीना',
      nl: 'Vorige maand',
      sv: 'Föregående månad',
      vi: 'Tháng trước',
      id: 'Bulan sebelumnya',
    }),
    nextMonth: t({
      ru: 'Следующий месяц',
      en: 'Next month',
      kk: 'Келесі ай',
      de: 'Nächster Monat',
      fr: 'Mois suivant',
      es: 'Mes siguiente',
      pt: 'Próximo mês',
      tr: 'Sonraki ay',
      uk: 'Наступний місяць',
      zh: '下个月',
      ar: 'الشهر التالي',
      pl: 'Następny miesiąc',
      it: 'Mese successivo',
      sk: 'Nasledujúci mesiac',
      ja: '翌月',
      ko: '다음 달',
      hi: 'अगला महीना',
      nl: 'Volgende maand',
      sv: 'Nästa månad',
      vi: 'Tháng sau',
      id: 'Bulan berikutnya',
    }),
    latest: t({
      ru: 'Последний',
      en: 'Latest',
      kk: 'Соңғы',
      de: 'Neuester',
      fr: 'Dernier',
      es: 'Último',
      pt: 'Mais recente',
      tr: 'En son',
      uk: 'Останній',
      zh: '最新',
      ar: 'الأحدث',
      pl: 'Najnowszy',
      it: 'Più recente',
      sk: 'Najnovší',
      ja: '最新',
      ko: '최신',
      hi: 'नवीनतम',
      nl: 'Nieuwste',
      sv: 'Senaste',
      vi: 'Mới nhất',
      id: 'Terbaru',
    }),
    moreCount: t({
      ru: 'ещё {count}',
      en: '+{count} more',
      kk: 'тағы {count}',
      de: '+{count} weitere',
      fr: '+{count} de plus',
      es: '+{count} más',
      pt: '+{count} mais',
      tr: '+{count} daha',
      uk: 'ще {count}',
      zh: '还有 {count} 项',
      ar: '+{count} أخرى',
      pl: '+{count} więcej',
      it: '+{count} altri',
      sk: '+{count} ďalších',
      ja: '他 {count} 件',
      ko: '+{count}개 더',
      hi: '+{count} और',
      nl: '+{count} meer',
      sv: '+{count} till',
      vi: '+{count} khác',
      id: '+{count} lainnya',
    }),
    groupByPrefix: t({
      ru: 'Группировка:',
      en: 'Group by:',
      kk: 'Топтау:',
      de: 'Gruppieren nach:',
      fr: 'Grouper par :',
      es: 'Agrupar por:',
      pt: 'Agrupar por:',
      tr: 'Grupla:',
      uk: 'Групування:',
      zh: '分组：',
      ar: 'التجميع حسب:',
      pl: 'Grupuj według:',
      it: 'Raggruppa per:',
      sk: 'Zoskupiť podľa:',
      ja: 'グループ化:',
      ko: '그룹 기준:',
      hi: 'समूह:',
      nl: 'Groeperen op:',
      sv: 'Gruppera efter:',
      vi: 'Nhóm theo:',
      id: 'Kelompokkan:',
    }),
    viewPrefix: t({
      ru: 'Вид:',
      en: 'View:',
      kk: 'Көрініс:',
      de: 'Ansicht:',
      fr: 'Vue :',
      es: 'Vista:',
      pt: 'Visualização:',
      tr: 'Görünüm:',
      uk: 'Вигляд:',
      zh: '视图：',
      ar: 'العرض:',
      pl: 'Widok:',
      it: 'Vista:',
      sk: 'Zobrazenie:',
      ja: '表示:',
      ko: '보기:',
      hi: 'दृश्य:',
      nl: 'Weergave:',
      sv: 'Vy:',
      vi: 'Chế độ xem:',
      id: 'Tampilan:',
    }),
    merchant: t({
      ru: 'Продавец',
      en: 'Merchant',
      kk: 'Сатушы',
      de: 'Händler',
      fr: 'Marchand',
      es: 'Comercio',
      pt: 'Estabelecimento',
      tr: 'Satıcı',
      uk: 'Продавець',
      zh: '商户',
      ar: 'التاجر',
      pl: 'Sprzedawca',
      it: 'Esercente',
      sk: 'Obchodník',
      ja: '加盟店',
      ko: '가맹점',
      hi: 'व्यापारी',
      nl: 'Handelaar',
      sv: 'Handlare',
      vi: 'Người bán',
      id: 'Merchant',
    }),
    avgBadge: t({
      ru: 'СР',
      en: 'AVG',
      kk: 'ОРТ',
      de: 'Ø',
      fr: 'MOY',
      es: 'PROM',
      pt: 'MÉD',
      tr: 'ORT',
      uk: 'СЕР',
      zh: '均',
      ar: 'متوسط',
      pl: 'ŚR',
      it: 'MED',
      sk: 'PRIEM',
      ja: '平均',
      ko: '평균',
      hi: 'औसत',
      nl: 'GEM',
      sv: 'SNITT',
      vi: 'TB',
      id: 'RATA',
    }),
    groupByDay: t({
      ru: 'День',
      en: 'Day',
      kk: 'Күн',
      de: 'Tag',
      fr: 'Jour',
      es: 'Día',
      pt: 'Dia',
      tr: 'Gün',
      uk: 'День',
      zh: '日',
      ar: 'يوم',
      pl: 'Dzień',
      it: 'Giorno',
      sk: 'Deň',
      ja: '日',
      ko: '일',
      hi: 'दिन',
      nl: 'Dag',
      sv: 'Dag',
      vi: 'Ngày',
      id: 'Hari',
    }),
    groupByWeek: t({
      ru: 'Неделя',
      en: 'Week',
      kk: 'Апта',
      de: 'Woche',
      fr: 'Semaine',
      es: 'Semana',
      pt: 'Semana',
      tr: 'Hafta',
      uk: 'Тиждень',
      zh: '周',
      ar: 'أسبوع',
      pl: 'Tydzień',
      it: 'Settimana',
      sk: 'Týždeň',
      ja: '週',
      ko: '주',
      hi: 'सप्ताह',
      nl: 'Week',
      sv: 'Vecka',
      vi: 'Tuần',
      id: 'Minggu',
    }),
    groupByMonth: t({
      ru: 'Месяц',
      en: 'Month',
      kk: 'Ай',
      de: 'Monat',
      fr: 'Mois',
      es: 'Mes',
      pt: 'Mês',
      tr: 'Ay',
      uk: 'Місяць',
      zh: '月',
      ar: 'شهر',
      pl: 'Miesiąc',
      it: 'Mese',
      sk: 'Mesiac',
      ja: '月',
      ko: '월',
      hi: 'महीना',
      nl: 'Maand',
      sv: 'Månad',
      vi: 'Tháng',
      id: 'Bulan',
    }),
    groupByQuarter: t({
      ru: 'Квартал',
      en: 'Quarter',
      kk: 'Тоқсан',
      de: 'Quartal',
      fr: 'Trimestre',
      es: 'Trimestre',
      pt: 'Trimestre',
      tr: 'Çeyrek',
      uk: 'Квартал',
      zh: '季度',
      ar: 'ربع سنة',
      pl: 'Kwartał',
      it: 'Trimestre',
      sk: 'Štvrťrok',
      ja: '四半期',
      ko: '분기',
      hi: 'तिमाही',
      nl: 'Kwartaal',
      sv: 'Kvartal',
      vi: 'Quý',
      id: 'Kuartal',
    }),
    groupByYear: t({
      ru: 'Год',
      en: 'Year',
      kk: 'Жыл',
      de: 'Jahr',
      fr: 'Année',
      es: 'Año',
      pt: 'Ano',
      tr: 'Yıl',
      uk: 'Рік',
      zh: '年',
      ar: 'سنة',
      pl: 'Rok',
      it: 'Anno',
      sk: 'Rok',
      ja: '年',
      ko: '연',
      hi: 'वर्ष',
      nl: 'Jaar',
      sv: 'År',
      vi: 'Năm',
      id: 'Tahun',
    }),
    viewCalendar: t({
      ru: 'Календарь',
      en: 'Calendar',
      kk: 'Күнтізбе',
      de: 'Kalender',
      fr: 'Calendrier',
      es: 'Calendario',
      pt: 'Calendário',
      tr: 'Takvim',
      uk: 'Календар',
      zh: '日历',
      ar: 'التقويم',
      pl: 'Kalendarz',
      it: 'Calendario',
      sk: 'Kalendár',
      ja: 'カレンダー',
      ko: '캘린더',
      hi: 'कैलेंडर',
      nl: 'Kalender',
      sv: 'Kalender',
      vi: 'Lịch',
      id: 'Kalender',
    }),
    viewLine: t({
      ru: 'Линейный',
      en: 'Line',
      kk: 'Сызықтық',
      de: 'Linie',
      fr: 'Courbe',
      es: 'Líneas',
      pt: 'Linhas',
      tr: 'Çizgi',
      uk: 'Лінійний',
      zh: '折线图',
      ar: 'خطي',
      pl: 'Liniowy',
      it: 'Linee',
      sk: 'Čiarový',
      ja: '折れ線',
      ko: '선형',
      hi: 'रेखा',
      nl: 'Lijn',
      sv: 'Linje',
      vi: 'Đường',
      id: 'Garis',
    }),
    viewBar: t({
      ru: 'Столбцы',
      en: 'Bar',
      kk: 'Бағандар',
      de: 'Balken',
      fr: 'Barres',
      es: 'Barras',
      pt: 'Barras',
      tr: 'Çubuk',
      uk: 'Стовпці',
      zh: '柱状图',
      ar: 'أعمدة',
      pl: 'Słupkowy',
      it: 'Barre',
      sk: 'Stĺpcový',
      ja: '棒グラフ',
      ko: '막대',
      hi: 'बार',
      nl: 'Staaf',
      sv: 'Stapel',
      vi: 'Cột',
      id: 'Batang',
    }),
    viewStacked: t({
      ru: 'С накоплением',
      en: 'Stacked',
      kk: 'Жинақталған',
      de: 'Gestapelt',
      fr: 'Empilé',
      es: 'Apilado',
      pt: 'Empilhado',
      tr: 'Yığılmış',
      uk: 'З накопиченням',
      zh: '堆叠图',
      ar: 'مكدس',
      pl: 'Skumulowany',
      it: 'In pila',
      sk: 'Skladaný',
      ja: '積み上げ',
      ko: '누적',
      hi: 'स्टैक्ड',
      nl: 'Gestapeld',
      sv: 'Staplad',
      vi: 'Chồng',
      id: 'Bertumpuk',
    }),
  },
} satisfies Dictionary;

export default content;
