import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'budgetsPage',
  content: {
    emptyDescription: t({
      ru: 'Бюджетов пока нет. Создайте первый, чтобы отслеживать расходы.',
      en: 'No budgets yet. Create one to start tracking your spending.',
      kk: 'Әзірге бюджет жоқ. Шығыстарды бақылау үшін алғашқысын жасаңыз.',
      de: 'Noch keine Budgets. Erstellen Sie eines, um Ihre Ausgaben zu verfolgen.',
      fr: 'Aucun budget pour le moment. Créez-en un pour suivre vos dépenses.',
      es: 'Aún no hay presupuestos. Cree uno para empezar a controlar sus gastos.',
      pt: 'Ainda não há orçamentos. Crie um para começar a acompanhar as despesas.',
      tr: 'Henüz bütçe yok. Harcamalarınızı takip etmek için bir tane oluşturun.',
      uk: 'Бюджетів поки немає. Створіть перший, щоб відстежувати витрати.',
      zh: '还没有预算。创建一个以开始跟踪支出。',
      pl: 'Brak budżetów. Utwórz pierwszy, aby śledzić wydatki.',
      it: 'Nessun budget ancora. Creane uno per iniziare a monitorare le spese.',
      sk: 'Zatiaľ žiadne rozpočty. Vytvorte prvý a sledujte svoje výdavky.',
      ja: 'まだ予算がありません。作成して支出の追跡を始めましょう。',
      ko: '아직 예산이 없습니다. 지출 추적을 시작하려면 예산을 만드세요.',
      hi: 'अभी कोई बजट नहीं है। खर्च ट्रैक करना शुरू करने के लिए एक बनाएँ।',
      nl: 'Nog geen budgetten. Maak er een om uw uitgaven bij te houden.',
      sv: 'Inga budgetar ännu. Skapa en för att börja följa dina utgifter.',
      vi: 'Chưa có ngân sách. Tạo một ngân sách để bắt đầu theo dõi chi tiêu.',
      id: 'Belum ada anggaran. Buat satu untuk mulai melacak pengeluaran Anda.',
      da: 'Ingen budgetter endnu. Opret et for at begynde at følge dine udgifter.',
      nb: 'Ingen budsjetter ennå. Opprett ett for å begynne å følge utgiftene dine.',
      nn: 'Ingen budsjett enno. Opprett eitt for å byrje å følgje utgiftene dine.',
      fi: 'Ei vielä budjetteja. Luo budjetti, niin pääset seuraamaan kulujasi.',
      is: 'Engar fjárhagsáætlanir enn. Búðu til eina til að fara að fylgjast með útgjöldunum.',
      fo: 'Ongar fíggjarætlanir enn. Stovna eina fyri at fara at fylgja við útgjøldunum.',
      cs: 'Zatím žádné rozpočty. Vytvořte jeden a začněte sledovat své výdaje.',
      bg: 'Още няма бюджети. Създайте един, за да започнете да следите разходите си.',
      hr: 'Još nema proračuna. Napravite jedan da počnete prati svoje troškove.',
      sr: 'Још нема буџета. Направите један да почнете да пратите своје трошкове.',
      sl: 'Še ni proračunov. Ustvarite enega in začnite spremljati svoje izdatke.',
      mk: 'Сè уште нема буџети. Создајте еден за да почнете да ги следите трошоците.',
      be: 'Бюджэтаў пакуль няма. Створыце адзін, каб пачаць сачыць за выдаткамі.',
      bs: 'Još nema budžeta. Napravite jedan da počnete pratiti svoje troškove.',
      hsb: 'Hišće žane budgety. Załožće jedyn, zo byšće swoje wudawki slědował.',
    }),
    createFirst: t({
      ru: 'Создать первый бюджет',
      en: 'Create your first budget',
      kk: 'Алғашқы бюджетті жасау',
      de: 'Erstes Budget erstellen',
      fr: 'Créer votre premier budget',
      es: 'Crear su primer presupuesto',
      pt: 'Criar o primeiro orçamento',
      tr: 'İlk bütçenizi oluşturun',
      uk: 'Створити перший бюджет',
      zh: '创建第一个预算',
      pl: 'Utwórz pierwszy budżet',
      it: 'Crea il tuo primo budget',
      sk: 'Vytvoriť prvý rozpočet',
      ja: '最初の予算を作成',
      ko: '첫 예산 만들기',
      hi: 'अपना पहला बजट बनाएँ',
      nl: 'Maak uw eerste budget',
      sv: 'Skapa din första budget',
      vi: 'Tạo ngân sách đầu tiên',
      id: 'Buat anggaran pertama Anda',
      da: 'Opret dit første budget',
      nb: 'Opprett ditt første budsjett',
      nn: 'Opprett ditt første budsjett',
      fi: 'Luo ensimmäinen budjettisi',
      is: 'Búðu til fyrstu fjárhagsáætlunina',
      fo: 'Stovna tína fyrstu fíggjarætlan',
      cs: 'Vytvořte svůj první rozpočet',
      bg: 'Създайте първия си бюджет',
      hr: 'Napravite svoj prvi proračun',
      sr: 'Направите свој први буџет',
      sl: 'Ustvarite svoj prvi proračun',
      mk: 'Создајте го вашиот прв буџет',
      be: 'Створыце свой першы бюджэт',
      bs: 'Napravite svoj prvi budžet',
      hsb: 'Załožće swój prěni budget',
    }),
    previousMonth: t({
      ru: 'Предыдущий месяц',
      en: 'Previous month',
      kk: 'Алдыңғы ай',
      de: 'Vorheriger Monat',
      fr: 'Mois précédent',
      es: 'Mes anterior',
      pt: 'Mês anterior',
      tr: 'Önceki ay',
      uk: 'Попередній місяць',
      zh: '上个月',
      pl: 'Poprzedni miesiąc',
      it: 'Mese precedente',
      sk: 'Predchádzajúci mesiac',
      ja: '前の月',
      ko: '이전 달',
      hi: 'पिछला महीना',
      nl: 'Vorige maand',
      sv: 'Föregående månad',
      vi: 'Tháng trước',
      id: 'Bulan sebelumnya',
      da: 'Forrige måned',
      nb: 'Forrige måned',
      nn: 'Førre månad',
      fi: 'Edellinen kuukausi',
      is: 'Fyrri mánuður',
      fo: 'Seinasti mánaði',
      cs: 'Předchozí měsíc',
      bg: 'Предишен месец',
      hr: 'Prethodni mjesec',
      sr: 'Претходни месец',
      sl: 'Prejšnji mesec',
      mk: 'Претходен месец',
      be: 'Папярэдні месяц',
      bs: 'Prethodni mjesec',
      hsb: 'Předchadny měsac',
    }),
    nextMonth: t({
      ru: 'Следующий месяц',
      en: 'Next month',
      kk: 'Келесі ай',
      de: 'Nächster Monat',
      fr: 'Mois suivant',
      es: 'Mes siguiente',
      pt: 'Mês seguinte',
      tr: 'Sonraki ay',
      uk: 'Наступний місяць',
      zh: '下个月',
      pl: 'Następny miesiąc',
      it: 'Mese successivo',
      sk: 'Nasledujúci mesiac',
      ja: '次の月',
      ko: '다음 달',
      hi: 'अगला महीना',
      nl: 'Volgende maand',
      sv: 'Nästa månad',
      vi: 'Tháng sau',
      id: 'Bulan berikutnya',
      da: 'Næste måned',
      nb: 'Neste måned',
      nn: 'Neste månad',
      fi: 'Seuraava kuukausi',
      is: 'Næsti mánuður',
      fo: 'Næsti mánaði',
      cs: 'Následující měsíc',
      bg: 'Следващ месец',
      hr: 'Sljedeći mjesec',
      sr: 'Следећи месец',
      sl: 'Naslednji mesec',
      mk: 'Следен месец',
      be: 'Наступны месяц',
      bs: 'Sljedeći mjesec',
      hsb: 'Přichodny měsac',
    }),
    stoicTitle: t({
      ru: 'Стоический баланс',
      en: 'Stoic balance',
      kk: 'Стоикалық баланс',
      de: 'Stoische Balance',
      fr: 'Équilibre stoïcien',
      es: 'Equilibrio estoico',
      pt: 'Equilíbrio estoico',
      tr: 'Stoacı denge',
      uk: 'Стоїчний баланс',
      zh: '斯多葛平衡',
      pl: 'Stoicka równowaga',
      it: 'Equilibrio stoico',
      sk: 'Stoická rovnováha',
      ja: 'ストア派のバランス',
      ko: '스토아식 균형',
      hi: 'स्टोइक संतुलन',
      nl: 'Stoïcijnse balans',
      sv: 'Stoisk balans',
      vi: 'Cân bằng khắc kỷ',
      id: 'Keseimbangan Stoik',
      da: 'Stoisk balance',
      nb: 'Stoisk balanse',
      nn: 'Stoisk balanse',
      fi: 'Stoalainen tasapaino',
      is: 'Stóískt jafnvægi',
      fo: 'Stoisk javnvág',
      cs: 'Stoická rovnováha',
      bg: 'Стоически баланс',
      hr: 'Stoička ravnoteža',
      sr: 'Стоичка равнотежа',
      sl: 'Stoično ravnovesje',
      mk: 'Стоичка рамнотежа',
      be: 'Стаічны баланс',
      bs: 'Stoička ravnoteža',
      hsb: 'Stoiska runowaha',
    }),
    stoicSubtitle: t({
      ru: 'На что вы собирались тратить в этом месяце — и на что потратили.',
      en: 'What you meant to spend on this month, against what you spent.',
      kk: 'Осы айда неге жұмсамақ болдыңыз — және неге жұмсадыңыз.',
      de: 'Wofür Sie diesen Monat ausgeben wollten — und wofür Sie ausgegeben haben.',
      fr: 'Ce que vous comptiez dépenser ce mois-ci, face à ce que vous avez dépensé.',
      es: 'En qué pensaba gastar este mes, frente a lo que gastó.',
      pt: 'No que pretendia gastar este mês, comparado com o que gastou.',
      tr: 'Bu ay neye harcamayı düşündüğünüz ve neye harcadığınız.',
      uk: 'На що ви збиралися витрачати цього місяця — і на що витратили.',
      zh: '本月您打算把钱花在哪里，对比实际花在了哪里。',
      pl: 'Zamierzone wydatki w tym miesiącu wobec faktycznych.',
      it: 'Su cosa volevi spendere questo mese, rispetto a quanto hai speso.',
      sk: 'Na čo ste chceli tento mesiac míňať — a na čo ste minuli.',
      ja: '今月何に使うつもりだったか、実際に何に使ったか。',
      ko: '이번 달 쓰려고 했던 곳과 실제로 쓴 곳.',
      hi: 'इस महीने आप किस पर खर्च करना चाहते थे, और वास्तव में किस पर किया।',
      nl: 'Waar u deze maand aan wilde uitgeven, tegenover waar u aan uitgaf.',
      sv: 'Vad du tänkte lägga pengar på den här månaden, mot vad du faktiskt lade dem på.',
      vi: 'Bạn định chi vào đâu trong tháng này, so với thực tế đã chi.',
      id: 'Rencana pengeluaran Anda bulan ini, dibandingkan dengan yang benar-benar dibelanjakan.',
      da: 'Det du ville bruge denne måned, holdt op mod det du brugte.',
      nb: 'Det du ville bruke denne måneden, målt mot det du brukte.',
      nn: 'Det du ville bruke denne månaden, målt mot det du brukte.',
      fi: 'Mihin aioit käyttää rahaa tässä kuussa, verrattuna siihen mihin käytit.',
      is: 'Það sem þú ætlaðir að eyða í þessum mánuði, á móti því sem þú eyddir.',
      fo: 'Tað tú ætlaði at brúka henda mánaðin, mótvegis tí tú brúkti.',
      cs: 'Co jste tento měsíc utratit chtěli, proti tomu, co jste utratili.',
      bg: 'Онова, което възнамерявахте да похарчите този месец, срещу онова, което похарчихте.',
      hr: 'Ono što ste ovaj mjesec namjeravali potrošiti, prema onome što ste potrošili.',
      sr: 'Оно што сте овог месеца намеравали да потрошите, према оном што сте потрошили.',
      sl: 'Kar ste ta mesec nameravali porabiti, proti temu, kar ste porabili.',
      mk: 'Она што планиравте да потрошите овој месец, наспрема она што потрошивте.',
      be: 'Тое, што вы збіраліся выдаткаваць гэтым месяцам, супраць таго, што выдаткавалі.',
      bs: 'Ono što ste ovaj mjesec namjeravali potrošiti, prema onome što ste potrošili.',
      hsb: 'To, kajž sće tutón měsac wudać chcył, přećiwo tomu, kajž sće wudał.',
    }),
    planned: t({
      ru: 'План',
      en: 'Planned',
      kk: 'Жоспар',
      de: 'Plan',
      fr: 'Prévu',
      es: 'Plan',
      pt: 'Plano',
      tr: 'Plan',
      uk: 'План',
      zh: '计划',
      pl: 'Plan',
      it: 'Piano',
      sk: 'Plán',
      ja: '計画',
      ko: '계획',
      hi: 'योजना',
      nl: 'Plan',
      sv: 'Plan',
      vi: 'Kế hoạch',
      id: 'Rencana',
      da: 'Planlagt',
      nb: 'Planlagt',
      nn: 'Planlagt',
      fi: 'Suunniteltu',
      is: 'Áætlað',
      fo: 'Ætlað',
      cs: 'Plán',
      bg: 'Планирано',
      hr: 'Planirano',
      sr: 'Планирано',
      sl: 'Načrtovano',
      mk: 'Планирано',
      be: 'Запланавана',
      bs: 'Planirano',
      hsb: 'Planowane',
    }),
    actual: t({
      ru: 'Факт',
      en: 'Actual',
      kk: 'Нақты',
      de: 'Ist',
      fr: 'Réel',
      es: 'Real',
      pt: 'Real',
      tr: 'Gerçekleşen',
      uk: 'Факт',
      zh: '实际',
      pl: 'Rzeczywiste',
      it: 'Effettivo',
      sk: 'Skutočnosť',
      ja: '実績',
      ko: '실제',
      hi: 'वास्तविक',
      nl: 'Werkelijk',
      sv: 'Utfall',
      vi: 'Thực tế',
      id: 'Aktual',
      da: 'Faktisk',
      nb: 'Faktisk',
      nn: 'Faktisk',
      fi: 'Toteutunut',
      is: 'Raunverulegt',
      fo: 'Veruligt',
      cs: 'Skutečnost',
      bg: 'Реално',
      hr: 'Stvarno',
      sr: 'Стварно',
      sl: 'Dejansko',
      mk: 'Реално',
      be: 'Фактычна',
      bs: 'Stvarno',
      hsb: 'Woprawdźite',
    }),
    classNecessity: t({
      ru: 'Необходимое',
      en: 'Necessity',
      kk: 'Қажеттілік',
      de: 'Notwendiges',
      fr: 'Nécessité',
      es: 'Necesidad',
      pt: 'Necessidade',
      tr: 'Zorunluluk',
      uk: 'Необхідне',
      zh: '必需',
      pl: 'Konieczność',
      it: 'Necessità',
      sk: 'Nevyhnutnosť',
      ja: '必需',
      ko: '필수',
      hi: 'आवश्यकता',
      nl: 'Noodzaak',
      sv: 'Nödvändighet',
      vi: 'Thiết yếu',
      id: 'Kebutuhan',
      da: 'Nødvendighed',
      nb: 'Nødvendighet',
      nn: 'Nødvendigheit',
      fi: 'Välttämättömyys',
      is: 'Nauðsyn',
      fo: 'Neyðsyn',
      cs: 'Nutnost',
      bg: 'Необходимост',
      hr: 'Nužnost',
      sr: 'Нужност',
      sl: 'Nujnost',
      mk: 'Неопходност',
      be: 'Неабходнасць',
      bs: 'Nužnost',
      hsb: 'Potrjeba',
    }),
    classWork: t({
      ru: 'Дело',
      en: 'Work',
      kk: 'Іс',
      de: 'Arbeit',
      fr: 'Travail',
      es: 'Trabajo',
      pt: 'Trabalho',
      tr: 'İş',
      uk: 'Справа',
      zh: '工作',
      pl: 'Praca',
      it: 'Lavoro',
      sk: 'Práca',
      ja: '仕事',
      ko: '일',
      hi: 'काम',
      nl: 'Werk',
      sv: 'Arbete',
      vi: 'Công việc',
      id: 'Pekerjaan',
      da: 'Arbejde',
      nb: 'Arbeid',
      nn: 'Arbeid',
      fi: 'Työ',
      is: 'Vinna',
      fo: 'Arbeiði',
      cs: 'Práce',
      bg: 'Работа',
      hr: 'Rad',
      sr: 'Рад',
      sl: 'Delo',
      mk: 'Работа',
      be: 'Праца',
      bs: 'Rad',
      hsb: 'Dźěło',
    }),
    classVirtue: t({
      ru: 'Добродетель',
      en: 'Virtue',
      kk: 'Ізгілік',
      de: 'Tugend',
      fr: 'Vertu',
      es: 'Virtud',
      pt: 'Virtude',
      tr: 'Erdem',
      uk: 'Чеснота',
      zh: '美德',
      pl: 'Cnota',
      it: 'Virtù',
      sk: 'Cnosť',
      ja: '徳',
      ko: '덕',
      hi: 'सद्गुण',
      nl: 'Deugd',
      sv: 'Dygd',
      vi: 'Đức hạnh',
      id: 'Kebajikan',
      da: 'Dyd',
      nb: 'Dyd',
      nn: 'Dygd',
      fi: 'Hyve',
      is: 'Dygð',
      fo: 'Dygd',
      cs: 'Ctnost',
      bg: 'Добродетел',
      hr: 'Krepost',
      sr: 'Врлина',
      sl: 'Krepost',
      mk: 'Добродетел',
      be: 'Цнота',
      bs: 'Vrlina',
      hsb: 'Čestnosć',
    }),
    classLeisure: t({
      ru: 'Досуг',
      en: 'Leisure',
      kk: 'Демалыс',
      de: 'Freizeit',
      fr: 'Loisir',
      es: 'Ocio',
      pt: 'Lazer',
      tr: 'Eğlence',
      uk: 'Дозвілля',
      zh: '休闲',
      pl: 'Rozrywka',
      it: 'Svago',
      sk: 'Zábava',
      ja: '余暇',
      ko: '여가',
      hi: 'मनोरंजन',
      nl: 'Vrije tijd',
      sv: 'Nöje',
      vi: 'Giải trí',
      id: 'Hiburan',
      da: 'Fritid',
      nb: 'Fritid',
      nn: 'Fritid',
      fi: 'Vapaa-aika',
      is: 'Afþreying',
      fo: 'Frítíð',
      cs: 'Volný čas',
      bg: 'Свободно време',
      hr: 'Slobodno vrijeme',
      sr: 'Слободно време',
      sl: 'Prosti čas',
      mk: 'Слободно време',
      be: 'Адпачынак',
      bs: 'Slobodno vrijeme',
      hsb: 'Wotpočink',
    }),
    unclassified: t({
      ru: 'Не оценено',
      en: 'Not judged',
      kk: 'Бағаланбаған',
      de: 'Nicht beurteilt',
      fr: 'Non jugé',
      es: 'Sin juzgar',
      pt: 'Não avaliado',
      tr: 'Tartılmadı',
      uk: 'Не оцінено',
      zh: '未评判',
      pl: 'Nieocenione',
      it: 'Non giudicato',
      sk: 'Neposúdené',
      ja: '未判断',
      ko: '판단 안 됨',
      hi: 'आकलन नहीं हुआ',
      nl: 'Niet beoordeeld',
      sv: 'Ej bedömt',
      vi: 'Chưa đánh giá',
      id: 'Belum dinilai',
      da: 'Ikke bedømt',
      nb: 'Ikke vurdert',
      nn: 'Ikkje vurdert',
      fi: 'Ei arvioitu',
      is: 'Ekki metið',
      fo: 'Ikki mett',
      cs: 'Neohodnoceno',
      bg: 'Без оценка',
      hr: 'Bez ocjene',
      sr: 'Без оцене',
      sl: 'Brez ocene',
      mk: 'Без оцена',
      be: 'Без ацэнкі',
      bs: 'Bez ocjene',
      hsb: 'Njepohódnoćene',
    }),
    hintNecessity: t({
      ru: 'Жильё, еда, налоги — то, чего требует жизнь',
      en: 'Housing, food, taxes — what life requires',
      kk: 'Тұрғын үй, тамақ, салықтар — өмір талап ететін нәрсе',
      de: 'Wohnen, Essen, Steuern — was das Leben verlangt',
      fr: 'Logement, nourriture, impôts — ce que la vie exige',
      es: 'Vivienda, comida, impuestos — lo que la vida exige',
      pt: 'Moradia, comida, impostos — o que a vida exige',
      tr: 'Konut, yemek, vergiler — hayatın gerektirdikleri',
      uk: 'Житло, їжа, податки — те, чого вимагає життя',
      zh: '住房、食物、税费——生活所需',
      pl: 'Mieszkanie, jedzenie, podatki — to, czego wymaga życie',
      it: 'Casa, cibo, tasse — ciò che la vita richiede',
      sk: 'Bývanie, jedlo, dane — čo si žiada život',
      ja: '住まい、食事、税金 — 生活に必要なもの',
      ko: '주거, 식비, 세금 — 삶에 필요한 것',
      hi: 'आवास, भोजन, कर — जो जीवन के लिए ज़रूरी है',
      nl: 'Wonen, eten, belastingen — wat het leven vraagt',
      sv: 'Boende, mat, skatter — det livet kräver',
      vi: 'Nhà ở, ăn uống, thuế — những gì cuộc sống đòi hỏi',
      id: 'Tempat tinggal, makanan, pajak — yang dibutuhkan hidup',
      da: 'Bolig, mad, skatter — hvad livet kræver',
      nb: 'Bolig, mat, skatter — det livet krever',
      nn: 'Bustad, mat, skattar — det livet krev',
      fi: 'Asuminen, ruoka, verot — se mitä elämä vaatii',
      is: 'Húsnæði, matur, skattar — það sem lífið krefst',
      fo: 'Bústaður, matur, skattir — tað lívið krevur',
      cs: 'Bydlení, jídlo, daně — co život vyžaduje',
      bg: 'Жилище, храна, данъци — каквото животът изисква',
      hr: 'Stanovanje, hrana, porezi — ono što život zahtijeva',
      sr: 'Становање, храна, порези — оно што живот захтева',
      sl: 'Stanovanje, hrana, davki — kar zahteva življenje',
      mk: 'Живеење, храна, даноци — она што животот бара',
      be: 'Жыллё, ежа, падаткі — тое, што патрабуе жыццё',
      bs: 'Stanovanje, hrana, porezi — ono što život zahtijeva',
      hsb: 'Bydlenje, jědź, dawki — što žiwjenje žada',
    }),
    hintWork: t({
      ru: 'Инструменты, сервисы, люди — то, чего требует дело',
      en: 'Tools, services, people — what your work requires',
      kk: 'Құралдар, қызметтер, адамдар — ісіңіз талап ететін нәрсе',
      de: 'Werkzeuge, Dienste, Menschen — was Ihre Arbeit verlangt',
      fr: 'Outils, services, personnes — ce que votre travail exige',
      es: 'Herramientas, servicios, personas — lo que su trabajo exige',
      pt: 'Ferramentas, serviços, pessoas — o que o seu trabalho exige',
      tr: 'Araçlar, hizmetler, insanlar — işinizin gerektirdikleri',
      uk: 'Інструменти, сервіси, люди — те, чого вимагає справа',
      zh: '工具、服务、人员——工作所需',
      pl: 'Narzędzia, usługi, ludzie — to, czego wymaga praca',
      it: 'Strumenti, servizi, persone — ciò che il tuo lavoro richiede',
      sk: 'Nástroje, služby, ľudia — čo si žiada vaša práca',
      ja: 'ツール、サービス、人 — 仕事に必要なもの',
      ko: '도구, 서비스, 사람 — 일에 필요한 것',
      hi: 'उपकरण, सेवाएँ, लोग — जो आपके काम के लिए ज़रूरी है',
      nl: 'Gereedschap, diensten, mensen — wat uw werk vraagt',
      sv: 'Verktyg, tjänster, människor — det ditt arbete kräver',
      vi: 'Công cụ, dịch vụ, con người — những gì công việc đòi hỏi',
      id: 'Alat, layanan, orang — yang dibutuhkan pekerjaan Anda',
      da: 'Værktøj, tjenester, mennesker — hvad dit arbejde kræver',
      nb: 'Verktøy, tjenester, mennesker — det arbeidet ditt krever',
      nn: 'Verktøy, tenester, menneske — det arbeidet ditt krev',
      fi: 'Työkalut, palvelut, ihmiset — se mitä työsi vaatii',
      is: 'Verkfæri, þjónusta, fólk — það sem starfið þitt krefst',
      fo: 'Tól, tænastur, fólk — tað arbeiðið títt krevur',
      cs: 'Nástroje, služby, lidé — co vyžaduje vaše práce',
      bg: 'Инструменти, услуги, хора — каквото изисква работата ви',
      hr: 'Alati, usluge, ljudi — ono što zahtijeva vaš rad',
      sr: 'Алати, услуге, људи — оно што захтева ваш рад',
      sl: 'Orodja, storitve, ljudje — kar zahteva vaše delo',
      mk: 'Алатки, услуги, луѓе — она што го бара вашата работа',
      be: 'Інструменты, паслугі, людзі — тое, што патрабуе ваша праца',
      bs: 'Alati, usluge, ljudi — ono što zahtijeva vaš rad',
      hsb: 'Nastroje, posłužby, ludźo — što waše dźěło žada',
    }),
    hintVirtue: t({
      ru: 'Здоровье, учёба, помощь другим, накопления на цель',
      en: 'Health, learning, helping others, saving for a goal',
      kk: 'Денсаулық, оқу, өзгелерге көмек, мақсатқа жинақ',
      de: 'Gesundheit, Lernen, anderen helfen, für ein Ziel sparen',
      fr: 'Santé, apprentissage, aide aux autres, épargne pour un objectif',
      es: 'Salud, aprendizaje, ayudar a otros, ahorrar para una meta',
      pt: 'Saúde, aprendizado, ajudar os outros, poupar para uma meta',
      tr: 'Sağlık, öğrenme, başkalarına yardım, bir hedef için birikim',
      uk: 'Здоровʼя, навчання, допомога іншим, заощадження на ціль',
      zh: '健康、学习、帮助他人、为目标储蓄',
      pl: 'Zdrowie, nauka, pomoc innym, oszczędzanie na cel',
      it: 'Salute, studio, aiutare gli altri, risparmiare per un obiettivo',
      sk: 'Zdravie, vzdelávanie, pomoc iným, sporenie na cieľ',
      ja: '健康、学び、人助け、目標への貯蓄',
      ko: '건강, 배움, 남을 돕기, 목표를 위한 저축',
      hi: 'स्वास्थ्य, सीखना, दूसरों की मदद, किसी लक्ष्य के लिए बचत',
      nl: 'Gezondheid, leren, anderen helpen, sparen voor een doel',
      sv: 'Hälsa, lärande, hjälpa andra, spara till ett mål',
      vi: 'Sức khỏe, học tập, giúp đỡ người khác, tiết kiệm cho mục tiêu',
      id: 'Kesehatan, belajar, membantu orang lain, menabung untuk tujuan',
      da: 'Helbred, læring, hjælp til andre, opsparing til et mål',
      nb: 'Helse, læring, hjelp til andre, sparing til et mål',
      nn: 'Helse, læring, hjelp til andre, sparing til eit mål',
      fi: 'Terveys, oppiminen, muiden auttaminen, säästäminen tavoitteeseen',
      is: 'Heilsa, lærdómur, hjálp við aðra, sparnaður fyrir markmið',
      fo: 'Heilsa, læring, hjálp til onnur, sparing til eitt mál',
      cs: 'Zdraví, učení, pomoc druhým, spoření na cíl',
      bg: 'Здраве, учене, помощ на другите, спестяване за цел',
      hr: 'Zdravlje, učenje, pomoć drugima, štednja za cilj',
      sr: 'Здравље, учење, помоћ другима, штедња за циљ',
      sl: 'Zdravje, učenje, pomoč drugim, varčevanje za cilj',
      mk: 'Здравје, учење, помош на другите, штедење за цел',
      be: 'Здароўе, навучанне, дапамога іншым, заашчаджэнне на мэту',
      bs: 'Zdravlje, učenje, pomoć drugima, štednja za cilj',
      hsb: 'Strowota, wuknjenje, pomoc druhim, lutowanje na cil',
    }),
    hintLeisure: t({
      ru: 'Отдых и удовольствия — желанны, но не главные',
      en: 'Rest and pleasure — welcome, but not in charge',
      kk: 'Демалыс пен ләззат — құптарлық, бірақ басты емес',
      de: 'Erholung und Vergnügen — willkommen, aber nicht bestimmend',
      fr: 'Repos et plaisir — bienvenus, mais pas aux commandes',
      es: 'Descanso y placer — bienvenidos, pero no al mando',
      pt: 'Descanso e prazer — bem-vindos, mas sem comandar',
      tr: 'Dinlenme ve keyif — hoş karşılanır, ama söz sahibi değil',
      uk: 'Відпочинок і задоволення — бажані, але не головні',
      zh: '休息与享乐——欢迎，但不做主',
      pl: 'Odpoczynek i przyjemności — mile widziane, ale nie rządzą',
      it: 'Riposo e piacere — benvenuti, ma non al comando',
      sk: 'Oddych a pôžitok — vítané, ale nie rozhodujúce',
      ja: '休息と楽しみ — 歓迎だが主役ではない',
      ko: '휴식과 즐거움 — 환영하지만 주인은 아님',
      hi: 'आराम और आनंद — स्वागत योग्य, पर मालिक नहीं',
      nl: 'Rust en plezier — welkom, maar niet de baas',
      sv: 'Vila och nöje — välkommet, men inte det som styr',
      vi: 'Nghỉ ngơi và niềm vui — đáng hoan nghênh, nhưng không làm chủ',
      id: 'Istirahat dan kesenangan — disambut, tapi tidak berkuasa',
      da: 'Hvile og nydelse — velkomne, men ikke styrende',
      nb: 'Hvile og nytelse — velkomne, men ikke styrende',
      nn: 'Kvile og nyting — velkomne, men ikkje styrande',
      fi: 'Lepo ja nautinto — tervetulleita, mutta ei ohjaksissa',
      is: 'Hvíld og ánægja — velkomnar, en ekki við stjórnvölinn',
      fo: 'Hvíld og nøgdsemi — vælkomin, men ikki við stýrið',
      cs: 'Odpočinek a radost — vítané, ale ne u kormidla',
      bg: 'Почивка и удоволствие — добре дошли, но не на кормилото',
      hr: 'Odmor i užitak — dobrodošli, ali ne za kormilom',
      sr: 'Одмор и задовољство — добродошли, али не за кормилом',
      sl: 'Počitek in užitek — dobrodošla, a ne za krmilom',
      mk: 'Одмор и задоволство — добредојдени, но не на кормило',
      be: 'Спачын і прыемнасці — вітаюцца, але не за рулём',
      bs: 'Odmor i užitak — dobrodošli, ali ne za kormilom',
      hsb: 'Wotpočink a wjesełosć — witane, ale nic za sćěhom',
    }),
    classifyTitle: t({
      ru: 'Оцените свои траты',
      en: 'Judge your spending',
      kk: 'Шығындарыңызды бағалаңыз',
      de: 'Beurteilen Sie Ihre Ausgaben',
      fr: 'Jugez vos dépenses',
      es: 'Juzgue sus gastos',
      pt: 'Avalie os seus gastos',
      tr: 'Harcamalarınızı tartın',
      uk: 'Оцініть свої витрати',
      zh: '评判您的支出',
      pl: 'Oceń swoje wydatki',
      it: 'Giudica le tue spese',
      sk: 'Posúďte svoje výdavky',
      ja: '支出を判断する',
      ko: '지출 판단하기',
      hi: 'अपने खर्च का आकलन करें',
      nl: 'Beoordeel uw uitgaven',
      sv: 'Bedöm dina utgifter',
      vi: 'Đánh giá chi tiêu của bạn',
      id: 'Nilai pengeluaran Anda',
      da: 'Bedøm dine udgifter',
      nb: 'Vurder utgiftene dine',
      nn: 'Vurder utgiftene dine',
      fi: 'Arvioi kulusi',
      is: 'Leggðu mat á útgjöldin þín',
      fo: 'Mat útgjøldini tín',
      cs: 'Ohodnoťte své výdaje',
      bg: 'Оценете разходите си',
      hr: 'Ocijenite svoje troškove',
      sr: 'Оцените своје трошкове',
      sl: 'Ocenite svoje izdatke',
      mk: 'Оценете ги вашите трошоци',
      be: 'Ацэніце свае выдаткі',
      bs: 'Ocijenite svoje troškove',
      hsb: 'Pohódnoćće swoje wudawki',
    }),
    classifyHint: t({
      ru: 'Lumio предлагает класс по названию категории, но решаете вы.',
      en: 'Lumio suggests a class from the category name, but the decision is yours.',
      kk: 'Lumio санат атауы бойынша сынып ұсынады, бірақ шешім сізде.',
      de: 'Lumio schlägt anhand des Kategorienamens eine Klasse vor, aber die Entscheidung liegt bei Ihnen.',
      fr: "Lumio propose une classe d'après le nom de la catégorie, mais la décision vous revient.",
      es: 'Lumio sugiere una clase según el nombre de la categoría, pero la decisión es suya.',
      pt: 'O Lumio sugere uma classe pelo nome da categoria, mas a decisão é sua.',
      tr: 'Lumio kategori adına göre bir sınıf önerir, ama karar sizindir.',
      uk: 'Lumio пропонує клас за назвою категорії, але вирішуєте ви.',
      zh: 'Lumio 会根据类别名称建议归类，但决定权在您。',
      pl: 'Lumio proponuje klasę na podstawie nazwy kategorii, ale decyzja należy do Ciebie.',
      it: 'Lumio suggerisce una classe dal nome della categoria, ma la decisione è tua.',
      sk: 'Lumio navrhne triedu podľa názvu kategórie, ale rozhodnutie je na vás.',
      ja: 'Lumio はカテゴリ名からクラスを提案しますが、決めるのはあなたです。',
      ko: 'Lumio가 카테고리 이름으로 분류를 제안하지만, 결정은 당신의 몫입니다.',
      hi: 'Lumio श्रेणी के नाम से एक वर्ग सुझाता है, पर निर्णय आपका है।',
      nl: 'Lumio stelt een klasse voor op basis van de categorienaam, maar u beslist.',
      sv: 'Lumio föreslår en klass utifrån kategorinamnet, men beslutet är ditt.',
      vi: 'Lumio gợi ý phân loại dựa trên tên danh mục, nhưng quyết định là của bạn.',
      id: 'Lumio menyarankan kelas dari nama kategori, tetapi keputusan ada di tangan Anda.',
      da: 'Lumio foreslår en klasse ud fra kategoriens navn, men beslutningen er din.',
      nb: 'Lumio foreslår en klasse ut fra kategorinavnet, men avgjørelsen er din.',
      nn: 'Lumio føreslår ein klasse ut frå kategorinamnet, men avgjerda er di.',
      fi: 'Lumio ehdottaa luokkaa kategorian nimen perusteella, mutta päätös on sinun.',
      is: 'Lumio stingur upp á flokki eftir heiti kategoríunnar, en ákvörðunin er þín.',
      fo: 'Lumio skjýtur upp ein flokk eftir navninum á bólkinum, men avgerðin er tín.',
      cs: 'Lumio navrhuje třídu podle názvu kategorie, rozhodnutí je ale vaše.',
      bg: 'Lumio предлага клас според името на категорията, но решението е ваше.',
      hr: 'Lumio predlaže razred po nazivu kategorije, ali odluka je vaša.',
      sr: 'Lumio предлаже разред по називу категорије, али одлука је ваша.',
      sl: 'Lumio predlaga razred po imenu kategorije, odločitev pa je vaša.',
      mk: 'Lumio предлага класа според името на категоријата, но одлуката е ваша.',
      be: 'Lumio прапануе клас па назве катэгорыі, але вырашаеце вы.',
      bs: 'Lumio predlaže razred po nazivu kategorije, ali odluka je vaša.',
      hsb: 'Lumio poradźuje klasu po mjenje kategorije, rozsud pak je waš.',
    }),
    suggested: t({
      ru: 'предложено',
      en: 'suggested',
      kk: 'ұсынылған',
      de: 'vorgeschlagen',
      fr: 'suggéré',
      es: 'sugerido',
      pt: 'sugerido',
      tr: 'önerilen',
      uk: 'запропоновано',
      zh: '建议',
      pl: 'sugerowane',
      it: 'suggerito',
      sk: 'navrhnuté',
      ja: '提案',
      ko: '제안됨',
      hi: 'सुझाया गया',
      nl: 'voorgesteld',
      sv: 'föreslagen',
      vi: 'gợi ý',
      id: 'disarankan',
      da: 'foreslået',
      nb: 'foreslått',
      nn: 'føreslått',
      fi: 'ehdotus',
      is: 'tillaga',
      fo: 'uppskot',
      cs: 'návrh',
      bg: 'предложено',
      hr: 'predloženo',
      sr: 'предложено',
      sl: 'predlagano',
      mk: 'предложено',
      be: 'прапанова',
      bs: 'predloženo',
      hsb: 'poradźene',
    }),
    chooseClass: t({
      ru: 'Выберите класс',
      en: 'Choose a class',
      kk: 'Сыныпты таңдаңыз',
      de: 'Klasse wählen',
      fr: 'Choisir une classe',
      es: 'Elegir una clase',
      pt: 'Escolher uma classe',
      tr: 'Bir sınıf seçin',
      uk: 'Оберіть клас',
      zh: '选择归类',
      pl: 'Wybierz klasę',
      it: 'Scegli una classe',
      sk: 'Vyberte triedu',
      ja: 'クラスを選択',
      ko: '분류 선택',
      hi: 'वर्ग चुनें',
      nl: 'Kies een klasse',
      sv: 'Välj en klass',
      vi: 'Chọn phân loại',
      id: 'Pilih kelas',
      da: 'Vælg en klasse',
      nb: 'Velg en klasse',
      nn: 'Vel ein klasse',
      fi: 'Valitse luokka',
      is: 'Veldu flokk',
      fo: 'Vel ein flokk',
      cs: 'Zvolte třídu',
      bg: 'Изберете клас',
      hr: 'Odaberite razred',
      sr: 'Изаберите разред',
      sl: 'Izberite razred',
      mk: 'Изберете класа',
      be: 'Выберыце клас',
      bs: 'Odaberite razred',
      hsb: 'Wuzwolće klasu',
    }),
    noPlan: t({
      ru: 'Задайте бюджеты, чтобы обозначить намерение: полоса «План» строится из их лимитов.',
      en: 'Set budgets to state your intent — the Planned bar is built from their limits.',
      kk: 'Ниетіңізді белгілеу үшін бюджеттер қойыңыз: «Жоспар» жолағы олардың лимиттерінен құрылады.',
      de: 'Legen Sie Budgets fest, um Ihre Absicht zu benennen — der Balken „Plan“ entsteht aus ihren Limits.',
      fr: 'Définissez des budgets pour affirmer votre intention — la barre « Prévu » est construite à partir de leurs plafonds.',
      es: 'Defina presupuestos para fijar su intención: la barra «Plan» se construye con sus límites.',
      pt: 'Defina orçamentos para declarar a sua intenção — a barra «Plano» é feita a partir dos limites.',
      tr: 'Niyetinizi belirtmek için bütçe belirleyin — “Plan” çubuğu bunların limitlerinden oluşur.',
      uk: 'Задайте бюджети, щоб позначити намір: смуга «План» будується з їхніх лімітів.',
      zh: '设置预算来表明您的意图——“计划”条由预算限额构成。',
      pl: 'Ustal budżety, aby określić zamiar — pasek „Plan” powstaje z ich limitów.',
      it: 'Imposta i budget per dichiarare la tua intenzione: la barra «Piano» nasce dai loro limiti.',
      sk: 'Nastavte rozpočty, aby ste vyjadrili zámer — pruh „Plán“ sa zostavuje z ich limitov.',
      ja: '予算を設定して意図を示しましょう。「計画」バーは予算の上限から作られます。',
      ko: '예산을 설정해 의도를 정하세요. ‘계획’ 막대는 예산 한도로 만들어집니다.',
      hi: 'अपना इरादा तय करने के लिए बजट सेट करें — “योजना” पट्टी उनकी सीमाओं से बनती है।',
      nl: 'Stel budgetten in om uw voornemen vast te leggen — de balk ‘Plan’ wordt opgebouwd uit hun limieten.',
      sv: 'Sätt budgetar för att ange din avsikt — stapeln ”Plan” byggs av deras gränser.',
      vi: 'Đặt ngân sách để nêu rõ ý định — thanh “Kế hoạch” được tạo từ hạn mức của chúng.',
      id: 'Tetapkan anggaran untuk menyatakan niat Anda — batang “Rencana” dibuat dari batasnya.',
      da: 'Sæt budgetter for at udtrykke din hensigt — søjlen Planlagt bygges af deres grænser.',
      nb: 'Sett budsjetter for å uttrykke hensikten din — søylen Planlagt bygges av grensene deres.',
      nn: 'Set budsjett for å uttrykke hensikta di — søyla Planlagt blir bygd av grensene deira.',
      fi: 'Aseta budjetit kertomaan aikomuksesi — Suunniteltu-palkki rakentuu niiden rajoista.',
      is: 'Settu fjárhagsáætlanir til að lýsa ætlun þinni — súlan Áætlað er byggð á mörkum þeirra.',
      fo: 'Set fíggjarætlanir fyri at siga ætlan tína — súlan Ætlað verður bygd av markunum teirra.',
      cs: 'Nastavte rozpočty a vyjádřete svůj záměr — pruh Plán se staví z jejich limitů.',
      bg: 'Задайте бюджети, за да заявите намерението си — лентата Планирано се изгражда от техните лимити.',
      hr: 'Postavite proračune da izrazite svoju namjeru — stupac Planirano gradi se iz njihovih ograničenja.',
      sr: 'Поставите буџете да изразите своју намеру — трака Планирано гради се из њихових ограничења.',
      sl: 'Nastavite proračune in izrazite svoj namen — stolpec Načrtovano se zgradi iz njihovih omejitev.',
      mk: 'Поставете буџети за да ја изразите намерата — лентата Планирано се гради од нивните лимити.',
      be: 'Задайце бюджэты, каб выказаць свой намер — слупок «Запланавана» будуецца з іх лімітаў.',
      bs: 'Postavite budžete da izrazite svoju namjeru — stupac Planirano gradi se iz njihovih ograničenja.',
      hsb: 'Nastajće budgety, zo byšće swój zaměr wuprajił — stołpik Planowane so z jich limitow zestaja.',
    }),
    noSpending: t({
      ru: 'В этом месяце трат пока нет.',
      en: 'No spending this month yet.',
      kk: 'Бұл айда әзірге шығын жоқ.',
      de: 'Diesen Monat noch keine Ausgaben.',
      fr: "Aucune dépense ce mois-ci pour l'instant.",
      es: 'Aún no hay gastos este mes.',
      pt: 'Ainda não há gastos este mês.',
      tr: 'Bu ay henüz harcama yok.',
      uk: 'Цього місяця витрат поки немає.',
      zh: '本月还没有支出。',
      pl: 'W tym miesiącu nie ma jeszcze wydatków.',
      it: 'Nessuna spesa questo mese, per ora.',
      sk: 'Tento mesiac zatiaľ žiadne výdavky.',
      ja: '今月の支出はまだありません。',
      ko: '이번 달 지출이 아직 없습니다.',
      hi: 'इस महीने अभी तक कोई खर्च नहीं।',
      nl: 'Nog geen uitgaven deze maand.',
      sv: 'Inga utgifter den här månaden ännu.',
      vi: 'Tháng này chưa có chi tiêu nào.',
      id: 'Belum ada pengeluaran bulan ini.',
      da: 'Ingen udgifter denne måned endnu.',
      nb: 'Ingen utgifter denne måneden ennå.',
      nn: 'Ingen utgifter denne månaden enno.',
      fi: 'Tässä kuussa ei ole vielä kuluja.',
      is: 'Engin útgjöld í þessum mánuði enn.',
      fo: 'Ongar útgjøld henda mánaðin enn.',
      cs: 'Tento měsíc zatím žádné výdaje.',
      bg: 'Този месец още няма разходи.',
      hr: 'Ovaj mjesec još nema troškova.',
      sr: 'Овог месеца још нема трошкова.',
      sl: 'Ta mesec še ni izdatkov.',
      mk: 'Овој месец сè уште нема трошоци.',
      be: 'Выдаткаў гэтым месяцам пакуль няма.',
      bs: 'Ovaj mjesec još nema troškova.',
      hsb: 'Tutón měsac hišće žane wudawki.',
    }),
    showInactive: t({
      ru: 'Показать категории без трат',
      en: 'Show categories with no spending',
      kk: 'Шығыны жоқ санаттарды көрсету',
      de: 'Kategorien ohne Ausgaben anzeigen',
      fr: 'Afficher les catégories sans dépenses',
      es: 'Mostrar categorías sin gastos',
      pt: 'Mostrar categorias sem gastos',
      tr: 'Harcaması olmayan kategorileri göster',
      uk: 'Показати категорії без витрат',
      zh: '显示无支出的类别',
      pl: 'Pokaż kategorie bez wydatków',
      it: 'Mostra categorie senza spese',
      sk: 'Zobraziť kategórie bez výdavkov',
      ja: '支出のないカテゴリを表示',
      ko: '지출 없는 카테고리 표시',
      hi: 'बिना खर्च वाली श्रेणियाँ दिखाएँ',
      nl: 'Categorieën zonder uitgaven tonen',
      sv: 'Visa kategorier utan utgifter',
      vi: 'Hiện danh mục không có chi tiêu',
      id: 'Tampilkan kategori tanpa pengeluaran',
      da: 'Vis kategorier uden udgifter',
      nb: 'Vis kategorier uten utgifter',
      nn: 'Vis kategoriar utan utgifter',
      fi: 'Näytä kategoriat ilman kuluja',
      is: 'Sýna kategoríur án útgjalda',
      fo: 'Vís bólkar uttan útgjøld',
      cs: 'Zobrazit kategorie bez výdajů',
      bg: 'Покажи категориите без разходи',
      hr: 'Prikaži kategorije bez troškova',
      sr: 'Прикажи категорије без трошкова',
      sl: 'Pokaži kategorije brez izdatkov',
      mk: 'Прикажи категории без трошоци',
      be: 'Паказваць катэгорыі без выдаткаў',
      bs: 'Prikaži kategorije bez troškova',
      hsb: 'Kategorije bjez wudawkow pokazać',
    }),
    hideInactive: t({
      ru: 'Скрыть категории без трат',
      en: 'Hide categories with no spending',
      kk: 'Шығыны жоқ санаттарды жасыру',
      de: 'Kategorien ohne Ausgaben ausblenden',
      fr: 'Masquer les catégories sans dépenses',
      es: 'Ocultar categorías sin gastos',
      pt: 'Ocultar categorias sem gastos',
      tr: 'Harcaması olmayan kategorileri gizle',
      uk: 'Приховати категорії без витрат',
      zh: '隐藏无支出的类别',
      pl: 'Ukryj kategorie bez wydatków',
      it: 'Nascondi categorie senza spese',
      sk: 'Skryť kategórie bez výdavkov',
      ja: '支出のないカテゴリを非表示',
      ko: '지출 없는 카테고리 숨기기',
      hi: 'बिना खर्च वाली श्रेणियाँ छिपाएँ',
      nl: 'Categorieën zonder uitgaven verbergen',
      sv: 'Dölj kategorier utan utgifter',
      vi: 'Ẩn danh mục không có chi tiêu',
      id: 'Sembunyikan kategori tanpa pengeluaran',
      da: 'Skjul kategorier uden udgifter',
      nb: 'Skjul kategorier uten utgifter',
      nn: 'Skjul kategoriar utan utgifter',
      fi: 'Piilota kategoriat ilman kuluja',
      is: 'Fela kategoríur án útgjalda',
      fo: 'Fjal bólkar uttan útgjøld',
      cs: 'Skrýt kategorie bez výdajů',
      bg: 'Скрий категориите без разходи',
      hr: 'Sakrij kategorije bez troškova',
      sr: 'Сакриј категорије без трошкова',
      sl: 'Skrij kategorije brez izdatkov',
      mk: 'Скрий категории без трошоци',
      be: 'Хаваць катэгорыі без выдаткаў',
      bs: 'Sakrij kategorije bez troškova',
      hsb: 'Kategorije bjez wudawkow schować',
    }),
    classLabel: t({
      ru: 'Класс',
      en: 'Class',
      kk: 'Сынып',
      de: 'Klasse',
      fr: 'Classe',
      es: 'Clase',
      pt: 'Classe',
      tr: 'Sınıf',
      uk: 'Клас',
      zh: '归类',
      pl: 'Klasa',
      it: 'Classe',
      sk: 'Trieda',
      ja: 'クラス',
      ko: '분류',
      hi: 'वर्ग',
      nl: 'Klasse',
      sv: 'Klass',
      vi: 'Phân loại',
      id: 'Kelas',
      da: 'Klasse',
      nb: 'Klasse',
      nn: 'Klasse',
      fi: 'Luokka',
      is: 'Flokkur',
      fo: 'Flokkur',
      cs: 'Třída',
      bg: 'Клас',
      hr: 'Razred',
      sr: 'Разред',
      sl: 'Razred',
      mk: 'Класа',
      be: 'Клас',
      bs: 'Razred',
      hsb: 'Klasa',
    }),
    helpsOthers: t({
      ru: 'Помощь другим',
      en: 'Helps others',
      kk: 'Басқаларға көмек',
      de: 'Hilft anderen',
      fr: 'Aide les autres',
      es: 'Ayuda a otros',
      pt: 'Ajuda os outros',
      tr: 'Başkalarına yardım',
      uk: 'Допомога іншим',
      zh: '帮助他人',
      pl: 'Pomoc innym',
      it: 'Aiuta gli altri',
      sk: 'Pomoc iným',
      ja: '人の役に立つ',
      ko: '남을 돕기',
      hi: 'दूसरों की मदद',
      nl: 'Helpt anderen',
      sv: 'Hjälper andra',
      vi: 'Giúp đỡ người khác',
      id: 'Membantu orang lain',
      da: 'Hjælper andre',
      nb: 'Hjelper andre',
      nn: 'Hjelper andre',
      fi: 'Auttaa muita',
      is: 'Hjálpar öðrum',
      fo: 'Hjálpir øðrum',
      cs: 'Pomáhá druhým',
      bg: 'Помага на другите',
      hr: 'Pomaže drugima',
      sr: 'Помаже другима',
      sl: 'Pomaga drugim',
      mk: 'Помага на другите',
      be: 'Дапамагае іншым',
      bs: 'Pomaže drugima',
      hsb: 'Pomha druhim',
    }),
    helpsOthersHint: t({
      ru: 'Благотворительность, пожертвования, подарки. По таким категориям советы видят вашу щедрость.',
      en: 'Charity, donations, gifts. The advice reads these categories to see how generous you are.',
      kk: 'Қайырымдылық, садақа, сыйлықтар. Кеңестер сіздің жомарттығыңызды осындай санаттар арқылы көреді.',
      de: 'Wohltätigkeit, Spenden, Geschenke. Anhand dieser Kategorien erkennen die Ratschläge, wie großzügig Sie sind.',
      fr: 'Charité, dons, cadeaux. Les conseils s’appuient sur ces catégories pour voir votre générosité.',
      es: 'Caridad, donaciones, regalos. Los consejos se fijan en estas categorías para ver cuán generoso es usted.',
      pt: 'Caridade, doações, presentes. Os conselhos usam estas categorias para ver a sua generosidade.',
      tr: 'Hayır işleri, bağışlar, hediyeler. Öneriler cömertliğinizi bu kategorilerden görür.',
      uk: 'Благодійність, пожертви, подарунки. За такими категоріями поради бачать вашу щедрість.',
      zh: '慈善、捐赠、礼物。建议会通过这类类别了解您的慷慨程度。',
      pl: 'Dobroczynność, darowizny, prezenty. Na podstawie takich kategorii porady widzą Twoją hojność.',
      it: 'Beneficenza, donazioni, regali. I consigli leggono queste categorie per vedere quanto sei generoso.',
      sk: 'Charita, dary, darčeky. Podľa takých kategórií rady vidia vašu štedrosť.',
      ja: '慈善、寄付、贈り物。アドバイスはこうしたカテゴリから、あなたの寛大さを読み取ります。',
      ko: '자선, 기부, 선물. 조언은 이런 카테고리를 보고 당신의 너그러움을 파악합니다.',
      hi: 'दान, चंदा, उपहार। सलाह इन श्रेणियों से आपकी उदारता को देखती है।',
      nl: 'Liefdadigheid, donaties, cadeaus. Het advies leest deze categorieën om te zien hoe vrijgevig u bent.',
      sv: 'Välgörenhet, donationer, gåvor. Råden läser de här kategorierna för att se hur generös du är.',
      vi: 'Từ thiện, quyên góp, quà tặng. Phần lời khuyên dựa vào các danh mục này để thấy bạn rộng lượng đến đâu.',
      id: 'Amal, donasi, hadiah. Saran membaca kategori seperti ini untuk melihat kemurahan hati Anda.',
      da: 'Velgørenhed, donationer, gaver. Rådene læser disse kategorier for at se, hvor gavmild du er.',
      nb: 'Veldedighet, donasjoner, gaver. Rådene leser disse kategoriene for å se hvor gavmild du er.',
      nn: 'Velgjerd, gåver, donasjonar. Råda les desse kategoriane for å sjå kor gåvmild du er.',
      fi: 'Hyväntekeisyys, lahjoitukset, lahjat. Neuvot lukevat näitä kategorioita nähdäkseen, kuinka antelias olet.',
      is: 'Góðgerðir, framlög, gjafir. Ráðin lesa þessar kategoríur til að sjá hve gjafmildur þú ert.',
      fo: 'Góðgerð, gávur, stuðul. Ráðini lesa hesar bólkar fyri at síggja hvussu gávumildur tú ert.',
      cs: 'Dobročinnost, dary, dárky. Doporučení čtou tyto kategorie, aby viděla, jak jste velkorysí.',
      bg: 'Благотворителност, дарения, подаръци. Съветите четат тези категории, за да видят колко сте щедри.',
      hr: 'Dobrotvorni rad, donacije, darovi. Savjeti čitaju te kategorije da vide koliko ste darežljivi.',
      sr: 'Добротворни рад, донације, дарови. Савети читају те категорије да виде колико сте дарежљиви.',
      sl: 'Dobrodelnost, donacije, darila. Nasveti berejo te kategorije, da vidijo, kako radodarni ste.',
      mk: 'Добротворност, донации, подароци. Советите ги читаат овие категории за да видат колку сте дарежливи.',
      be: 'Дабрачыннасць, данаты, падарункі. Парады чытаюць гэтыя катэгорыі, каб бачыць, наколькі вы шчодрыя.',
      bs: 'Dobrotvorni rad, donacije, darovi. Savjeti čitaju te kategorije da vide koliko ste darežljivi.',
      hsb: 'Dobroćinstwo, dary, darčiki. Porady čitaja tute kategorije, zo bychu widźeli, kak dawkomócny sće.',
    }),
    pageTitle: t({
      ru: 'Бюджеты',
      en: 'Budgets',
      kk: 'Бюджеттер',
      de: 'Budgets',
      fr: 'Budgets',
      es: 'Presupuestos',
      pt: 'Orçamentos',
      tr: 'Bütçeler',
      uk: 'Бюджети',
      zh: '预算',
      pl: 'Budżety',
      it: 'Budget',
      sk: 'Rozpočty',
      ja: '予算',
      ko: '예산',
      hi: 'बजट',
      nl: 'Budgetten',
      sv: 'Budgetar',
      vi: 'Ngân sách',
      id: 'Anggaran',
      da: 'Budgetter',
      nb: 'Budsjetter',
      nn: 'Budsjett',
      fi: 'Budjetit',
      is: 'Fjárhagsáætlanir',
      fo: 'Fíggjarætlanir',
      cs: 'Rozpočty',
      bg: 'Бюджети',
      hr: 'Proračuni',
      sr: 'Буџети',
      sl: 'Proračuni',
      mk: 'Буџети',
      be: 'Бюджэты',
      bs: 'Budžeti',
      hsb: 'Budgety',
    }),
    newBudget: t({
      ru: 'Новый бюджет',
      en: 'New Budget',
      kk: 'Жаңа бюджет',
      de: 'Neues Budget',
      fr: 'Nouveau budget',
      es: 'Nuevo presupuesto',
      pt: 'Novo orçamento',
      tr: 'Yeni bütçe',
      uk: 'Новий бюджет',
      zh: '新建预算',
      pl: 'Nowy budżet',
      it: 'Nuovo budget',
      sk: 'Nový rozpočet',
      ja: '新しい予算',
      ko: '새 예산',
      hi: 'नया बजट',
      nl: 'Nieuw budget',
      sv: 'Ny budget',
      vi: 'Ngân sách mới',
      id: 'Anggaran baru',
      da: 'Nyt budget',
      nb: 'Nytt budsjett',
      nn: 'Nytt budsjett',
      fi: 'Uusi budjetti',
      is: 'Ný fjárhagsáætlun',
      fo: 'Nýggj fíggjarætlan',
      cs: 'Nový rozpočet',
      bg: 'Нов бюджет',
      hr: 'Novi proračun',
      sr: 'Нови буџет',
      sl: 'Nov proračun',
      mk: 'Нов буџет',
      be: 'Новы бюджэт',
      bs: 'Novi budžet',
      hsb: 'Nowy budget',
    }),
    editBudget: t({
      ru: 'Редактировать бюджет',
      en: 'Edit Budget',
      kk: 'Бюджетті өңдеу',
      de: 'Budget bearbeiten',
      fr: 'Modifier le budget',
      es: 'Editar presupuesto',
      pt: 'Editar orçamento',
      tr: 'Bütçeyi düzenle',
      uk: 'Редагувати бюджет',
      zh: '编辑预算',
      pl: 'Edytuj budżet',
      it: 'Modifica budget',
      sk: 'Upraviť rozpočet',
      ja: '予算を編集',
      ko: '예산 편집',
      hi: 'बजट संपादित करें',
      nl: 'Budget bewerken',
      sv: 'Redigera budget',
      vi: 'Sửa ngân sách',
      id: 'Edit anggaran',
      da: 'Redigér budget',
      nb: 'Rediger budsjett',
      nn: 'Rediger budsjett',
      fi: 'Muokkaa budjettia',
      is: 'Breyta fjárhagsáætlun',
      fo: 'Broyt fíggjarætlan',
      cs: 'Upravit rozpočet',
      bg: 'Редактиране на бюджет',
      hr: 'Uredi proračun',
      sr: 'Уреди буџет',
      sl: 'Uredi proračun',
      mk: 'Уреди буџет',
      be: 'Рэдагаваць бюджэт',
      bs: 'Uredi budžet',
      hsb: 'Budget wobdźěłać',
    }),
    unknownCategory: t({
      ru: 'Неизвестная категория',
      en: 'Unknown category',
      kk: 'Белгісіз санат',
      de: 'Unbekannte Kategorie',
      fr: 'Catégorie inconnue',
      es: 'Categoría desconocida',
      pt: 'Categoria desconhecida',
      tr: 'Bilinmeyen kategori',
      uk: 'Невідома категорія',
      zh: '未知类别',
      pl: 'Nieznana kategoria',
      it: 'Categoria sconosciuta',
      sk: 'Neznáma kategória',
      ja: '不明なカテゴリ',
      ko: '알 수 없는 카테고리',
      hi: 'अज्ञात श्रेणी',
      nl: 'Onbekende categorie',
      sv: 'Okänd kategori',
      vi: 'Danh mục không xác định',
      id: 'Kategori tidak dikenal',
      da: 'Ukendt kategori',
      nb: 'Ukjent kategori',
      nn: 'Ukjend kategori',
      fi: 'Tuntematon kategoria',
      is: 'Óþekkt kategoría',
      fo: 'Ókendur bólkur',
      cs: 'Neznámá kategorie',
      bg: 'Неизвестна категория',
      hr: 'Nepoznata kategorija',
      sr: 'Непозната категорија',
      sl: 'Neznana kategorija',
      mk: 'Непозната категорија',
      be: 'Невядомая катэгорыя',
      bs: 'Nepoznata kategorija',
      hsb: 'Njeznata kategorija',
    }),
    periodWeekly: t({
      ru: 'Еженедельно',
      en: 'Weekly',
      kk: 'Апта сайын',
      de: 'Wöchentlich',
      fr: 'Hebdomadaire',
      es: 'Semanal',
      pt: 'Semanal',
      tr: 'Haftalık',
      uk: 'Щотижня',
      zh: '每周',
      pl: 'Tygodniowo',
      it: 'Settimanale',
      sk: 'Týždenne',
      ja: '毎週',
      ko: '매주',
      hi: 'साप्ताहिक',
      nl: 'Wekelijks',
      sv: 'Veckovis',
      vi: 'Hàng tuần',
      id: 'Mingguan',
      da: 'Ugentligt',
      nb: 'Ukentlig',
      nn: 'Vekentleg',
      fi: 'Viikoittain',
      is: 'Vikulega',
      fo: 'Vikuliga',
      cs: 'Týdně',
      bg: 'Седмично',
      hr: 'Tjedno',
      sr: 'Недељно',
      sl: 'Tedensko',
      mk: 'Неделно',
      be: 'Штотыдзень',
      bs: 'Nedjeljno',
      hsb: 'Tydźensce',
    }),
    periodMonthly: t({
      ru: 'Ежемесячно',
      en: 'Monthly',
      kk: 'Ай сайын',
      de: 'Monatlich',
      fr: 'Mensuel',
      es: 'Mensual',
      pt: 'Mensal',
      tr: 'Aylık',
      uk: 'Щомісяця',
      zh: '每月',
      pl: 'Miesięcznie',
      it: 'Mensile',
      sk: 'Mesačne',
      ja: '毎月',
      ko: '매월',
      hi: 'मासिक',
      nl: 'Maandelijks',
      sv: 'Månadsvis',
      vi: 'Hàng tháng',
      id: 'Bulanan',
      da: 'Månedligt',
      nb: 'Månedlig',
      nn: 'Månadleg',
      fi: 'Kuukausittain',
      is: 'Mánaðarlega',
      fo: 'Mánaðarliga',
      cs: 'Měsíčně',
      bg: 'Месечно',
      hr: 'Mjesečno',
      sr: 'Месечно',
      sl: 'Mesečno',
      mk: 'Месечно',
      be: 'Штомесяц',
      bs: 'Mjesečno',
      hsb: 'Měsačnje',
    }),
    periodQuarterly: t({
      ru: 'Ежеквартально',
      en: 'Quarterly',
      kk: 'Тоқсан сайын',
      de: 'Vierteljährlich',
      fr: 'Trimestriel',
      es: 'Trimestral',
      pt: 'Trimestral',
      tr: 'Üç aylık',
      uk: 'Щокварталу',
      zh: '每季度',
      pl: 'Kwartalnie',
      it: 'Trimestrale',
      sk: 'Štvrťročne',
      ja: '四半期ごと',
      ko: '분기별',
      hi: 'त्रैमासिक',
      nl: 'Elk kwartaal',
      sv: 'Kvartalsvis',
      vi: 'Hàng quý',
      id: 'Kuartalan',
      da: 'Kvartalsvis',
      nb: 'Kvartalsvis',
      nn: 'Kvartalsvis',
      fi: 'Neljännesvuosittain',
      is: 'Á fjórðungi',
      fo: 'Fjórðingsliga',
      cs: 'Čtvrtletně',
      bg: 'Тримесечно',
      hr: 'Kvartalno',
      sr: 'Квартално',
      sl: 'Četrtletno',
      mk: 'Квартално',
      be: 'Штоквартал',
      bs: 'Kvartalno',
      hsb: 'Kwartalnje',
    }),
    periodAnnual: t({
      ru: 'Ежегодно',
      en: 'Annual',
      kk: 'Жыл сайын',
      de: 'Jährlich',
      fr: 'Annuel',
      es: 'Anual',
      pt: 'Anual',
      tr: 'Yıllık',
      uk: 'Щороку',
      zh: '每年',
      pl: 'Rocznie',
      it: 'Annuale',
      sk: 'Ročne',
      ja: '毎年',
      ko: '매년',
      hi: 'वार्षिक',
      nl: 'Jaarlijks',
      sv: 'Årsvis',
      vi: 'Hàng năm',
      id: 'Tahunan',
      da: 'Årligt',
      nb: 'Årlig',
      nn: 'Årleg',
      fi: 'Vuosittain',
      is: 'Árlega',
      fo: 'Árliga',
      cs: 'Ročně',
      bg: 'Годишно',
      hr: 'Godišnje',
      sr: 'Годишње',
      sl: 'Letno',
      mk: 'Годишно',
      be: 'Штогод',
      bs: 'Godišnje',
      hsb: 'Lětnje',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Болдырмау',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
      da: 'Annuller',
      nb: 'Avbryt',
      nn: 'Avbryt',
      fi: 'Peruuta',
      is: 'Hætta',
      fo: 'Avbrót',
      cs: 'Zrušit',
      bg: 'Отказ',
      hr: 'Odustani',
      sr: 'Откажи',
      sl: 'Prekliči',
      mk: 'Откажи',
      be: 'Скасаваць',
      bs: 'Otkaži',
      hsb: 'Přetorhnyć',
    }),
    save: t({
      ru: 'Сохранить',
      en: 'Save',
      kk: 'Сақтау',
      de: 'Speichern',
      fr: 'Enregistrer',
      es: 'Guardar',
      pt: 'Salvar',
      tr: 'Kaydet',
      uk: 'Зберегти',
      zh: '保存',
      pl: 'Zapisz',
      it: 'Salva',
      sk: 'Uložiť',
      ja: '保存',
      ko: '저장',
      hi: 'सहेजें',
      nl: 'Opslaan',
      sv: 'Spara',
      vi: 'Lưu',
      id: 'Simpan',
      da: 'Gem',
      nb: 'Lagre',
      nn: 'Lagre',
      fi: 'Tallenna',
      is: 'Vista',
      fo: 'Goym',
      cs: 'Uložit',
      bg: 'Запази',
      hr: 'Spremi',
      sr: 'Сачувај',
      sl: 'Shrani',
      mk: 'Зачувај',
      be: 'Захаваць',
      bs: 'Sačuvaj',
      hsb: 'Składować',
    }),
    saving: t({
      ru: 'Сохранение...',
      en: 'Saving...',
      kk: 'Сақталуда...',
      de: 'Wird gespeichert...',
      fr: 'Enregistrement...',
      es: 'Guardando...',
      pt: 'Salvando...',
      tr: 'Kaydediliyor...',
      uk: 'Збереження...',
      zh: '正在保存...',
      pl: 'Zapisywanie...',
      it: 'Salvataggio...',
      sk: 'Ukladá sa...',
      ja: '保存中...',
      ko: '저장 중...',
      hi: 'सहेजा जा रहा है...',
      nl: 'Opslaan...',
      sv: 'Sparar...',
      vi: 'Đang lưu...',
      id: 'Menyimpan...',
      da: 'Gemmer...',
      nb: 'Lagrer...',
      nn: 'Lagrar...',
      fi: 'Tallennetaan...',
      is: 'Vista...',
      fo: 'Goymi...',
      cs: 'Ukládání...',
      bg: 'Запазва се...',
      hr: 'Spremanje...',
      sr: 'Чување...',
      sl: 'Shranjujem...',
      mk: 'Се зачувува...',
      be: 'Захаванне...',
      bs: 'Čuvanje...',
      hsb: 'Składuje so...',
    }),
    fieldName: t({
      ru: 'Название',
      en: 'Name',
      kk: 'Атауы',
      de: 'Name',
      fr: 'Nom',
      es: 'Nombre',
      pt: 'Nome',
      tr: 'Ad',
      uk: 'Назва',
      zh: '名称',
      pl: 'Nazwa',
      it: 'Nome',
      sk: 'Názov',
      ja: '名前',
      ko: '이름',
      hi: 'नाम',
      nl: 'Naam',
      sv: 'Namn',
      vi: 'Tên',
      id: 'Nama',
      da: 'Navn',
      nb: 'Navn',
      nn: 'Namn',
      fi: 'Nimi',
      is: 'Nafn',
      fo: 'Navn',
      cs: 'Název',
      bg: 'Име',
      hr: 'Naziv',
      sr: 'Назив',
      sl: 'Ime',
      mk: 'Име',
      be: 'Назва',
      bs: 'Naziv',
      hsb: 'Mjeno',
    }),
    fieldCategory: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '类别',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategória',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
      da: 'Kategori',
      nb: 'Kategori',
      nn: 'Kategori',
      fi: 'Kategoria',
      is: 'Kategoría',
      fo: 'Bólkur',
      cs: 'Kategorie',
      bg: 'Категория',
      hr: 'Kategorija',
      sr: 'Категорија',
      sl: 'Kategorija',
      mk: 'Категорија',
      be: 'Катэгорыя',
      bs: 'Kategorija',
      hsb: 'Kategorija',
    }),
    fieldLimitAmount: t({
      ru: 'Сумма лимита',
      en: 'Limit Amount',
      kk: 'Лимит сомасы',
      de: 'Limitbetrag',
      fr: 'Montant du plafond',
      es: 'Importe del límite',
      pt: 'Valor do limite',
      tr: 'Limit tutarı',
      uk: 'Сума ліміту',
      zh: '限额',
      pl: 'Kwota limitu',
      it: 'Importo limite',
      sk: 'Výška limitu',
      ja: '上限額',
      ko: '한도 금액',
      hi: 'सीमा राशि',
      nl: 'Limietbedrag',
      sv: 'Gränsbelopp',
      vi: 'Hạn mức',
      id: 'Jumlah batas',
      da: 'Grænsebeløb',
      nb: 'Grensebeløp',
      nn: 'Grensebeløp',
      fi: 'Rajasumma',
      is: 'Hámarksfjárhæð',
      fo: 'Markssum',
      cs: 'Limitní částka',
      bg: 'Лимитна сума',
      hr: 'Granični iznos',
      sr: 'Гранични износ',
      sl: 'Mejni znesek',
      mk: 'Гранична сума',
      be: 'Сума ліміту',
      bs: 'Granični iznos',
      hsb: 'Limitna suma',
    }),
    fieldRollover: t({
      ru: 'Остаток периода',
      en: 'Unspent money',
      kk: 'Жұмсалмаған қалдық',
      de: 'Nicht ausgegebenes Geld',
      fr: 'Argent non dépensé',
      es: 'Dinero no gastado',
      pt: 'Dinheiro não gasto',
      tr: 'Harcanmayan para',
      uk: 'Залишок періоду',
      zh: '未花完的钱',
      pl: 'Niewydane pieniądze',
      it: 'Denaro non speso',
      sk: 'Nevyčerpaný zostatok',
      ja: '使わなかったお金',
      ko: '남은 금액',
      hi: 'बचा हुआ पैसा',
      nl: 'Niet-uitgegeven geld',
      sv: 'Oanvända pengar',
      vi: 'Tiền chưa tiêu',
      id: 'Uang yang tidak terpakai',
      da: 'Ubrugte penge',
      nb: 'Ubrukte penger',
      nn: 'Ubrukte pengar',
      fi: 'Käyttämättä jääneet rahat',
      is: 'Óeytt fé',
      fo: 'Ónýttur peningur',
      cs: 'Nevyčerpané peníze',
      bg: 'Неизразходвани средства',
      hr: 'Nepotrošeni novac',
      sr: 'Непотрошен новац',
      sl: 'Neporabljen denar',
      mk: 'Непотрошени пари',
      be: 'Нявыдаткаваныя грошы',
      bs: 'Nepotrošen novac',
      hsb: 'Njewudate pjenjezy',
    }),
    rolloverNone: t({
      ru: 'Сгорает — каждый период начинается с лимита',
      en: 'Resets — every period starts at the limit',
      kk: 'Жанады — әр кезең лимиттен басталады',
      de: 'Verfällt – jeder Zeitraum beginnt beim Limit',
      fr: 'Perdu – chaque période repart de la limite',
      es: 'Se pierde: cada periodo empieza en el límite',
      pt: 'Perde-se: cada período começa no limite',
      tr: 'Sıfırlanır – her dönem limitten başlar',
      uk: 'Згорає — кожен період починається з ліміту',
      zh: '清零：每个周期从限额开始',
      pl: 'Przepada – każdy okres zaczyna się od limitu',
      it: 'Si azzera: ogni periodo riparte dal limite',
      sk: 'Prepadne – každé obdobie začína na limite',
      ja: 'リセット：毎期限度額から始まる',
      ko: '초기화 — 매 기간 한도에서 시작',
      hi: 'रीसेट — हर अवधि सीमा से शुरू होती है',
      nl: 'Vervalt – elke periode begint bij de limiet',
      sv: 'Nollställs – varje period börjar på gränsen',
      vi: 'Mất đi — mỗi kỳ bắt đầu từ hạn mức',
      id: 'Hangus — tiap periode mulai dari batas',
      da: 'Nulstilles — hver periode starter ved grænsen',
      nb: 'Nullstilles — hver periode starter på grensen',
      nn: 'Blir nullstilt — kvar periode startar på grensa',
      fi: 'Nollautuu — jokainen jakso alkaa rajasta',
      is: 'Endurstillist — hvert tímabil byrjar við hámarkið',
      fo: 'Nullstillast — hvørt tíðarskeið byrjar við markið',
      cs: 'Resetuje se — každé období začíná na limitu',
      bg: 'Нулира се — всеки период започва от лимита',
      hr: 'Poništava se — svako razdoblje počinje od ograničenja',
      sr: 'Поништава се — сваки период почиње од ограничења',
      sl: 'Ponastavi se — vsako obdobje se začne pri limitu',
      mk: 'Се ресетира — секој период започнува од лимитот',
      be: 'Абнуляецца — кожны перыяд пачынаецца з ліміту',
      bs: 'Poništava se — svaki period počinje od limita',
      hsb: 'Wróći so — kóžda doba započina z limitom',
    }),
    rolloverCarry: t({
      ru: 'Переносится — остаток и перерасход идут в следующий период',
      en: 'Carries over — leftover and overspend move to the next period',
      kk: 'Ауысады — қалдық пен артық шығын келесі кезеңге өтеді',
      de: 'Übertrag – Rest und Überziehung wandern in den nächsten Zeitraum',
      fr: 'Reporté – le reste et le dépassement passent à la période suivante',
      es: 'Se traslada: el sobrante y el exceso pasan al siguiente periodo',
      pt: 'Transita: o resto e o excesso passam para o período seguinte',
      tr: 'Devredilir – kalan ve aşım sonraki döneme geçer',
      uk: 'Переноситься — залишок і перевитрата йдуть у наступний період',
      zh: '结转：剩余和超支进入下一个周期',
      pl: 'Przenosi się – reszta i przekroczenie trafiają do następnego okresu',
      it: 'Si riporta: avanzo e sforamento passano al periodo successivo',
      sk: 'Prenáša sa – zvyšok aj prečerpanie idú do ďalšieho obdobia',
      ja: '繰り越し：残りも超過分も次の期に',
      ko: '이월 — 남은 금액과 초과분이 다음 기간으로',
      hi: 'आगे बढ़ता है — बचा और अधिक खर्च अगली अवधि में',
      nl: 'Gaat mee – rest en overschrijding gaan naar de volgende periode',
      sv: 'Förs över – rest och överdrag går till nästa period',
      vi: 'Chuyển tiếp — phần dư và phần vượt sang kỳ sau',
      id: 'Dibawa — sisa dan kelebihan ke periode berikutnya',
      da: 'Overføres — rest og overforbrug flyttes til næste periode',
      nb: 'Overføres — rest og overforbruk flyttes til neste periode',
      nn: 'Blir overført — rest og overforbruk flyttar til neste periode',
      fi: 'Siirtyy — jäännös ja ylitys siirtyvät seuraavaan jaksoon',
      is: 'Flyst yfir — afgangur og umframeyðsla flytjast á næsta tímabil',
      fo: 'Flytur — restur og umfarnýtsla flyta til næsta tíðarskeið',
      cs: 'Převádí se — zůstatek i přečerpání přechází do dalšího období',
      bg: 'Прехвърля се — остатъкът и преразходът минават в следващия период',
      hr: 'Prenosi se — ostatak i prekoračenje prelaze u sljedeće razdoblje',
      sr: 'Преноси се — остатак и прекорачење прелазе у наредни период',
      sl: 'Prenese se — ostanek in prekoračitev preideta v naslednje obdobje',
      mk: 'Се пренесува — остатокот и пречекорувањето преминуваат во следниот период',
      be: 'Пераносіцца — рэшта і перарасход пераходзяць у наступны перыяд',
      bs: 'Prenosi se — ostatak i prekoračenje prelaze u sljedeći period',
      hsb: 'Přenošuje so — zbytk a překročenje přeńdźetej do přichodneje doby',
    }),
    rolloverRefill: t({
      ru: 'Пополняется до лимита — остаток не копится выше лимита, перерасход вычитается',
      en: 'Refills to the limit — leftover never stacks above it, overspend is deducted',
      kk: 'Лимитке дейін толады — қалдық лимиттен асып жиналмайды, артық шығын шегеріледі',
      de: 'Auffüllen bis zum Limit – kein Ansparen darüber, Überziehung wird abgezogen',
      fr: 'Recomplété jusqu’à la limite – pas d’accumulation au-delà, le dépassement est déduit',
      es: 'Se repone hasta el límite: no se acumula por encima, el exceso se descuenta',
      pt: 'Repõe até ao limite: não acumula acima, o excesso é descontado',
      tr: 'Limite kadar dolar – üstüne birikmez, aşım düşülür',
      uk: 'Поповнюється до ліміту — залишок не копиться вище, перевитрата віднімається',
      zh: '补足到限额：剩余不超过限额累积，超支扣除',
      pl: 'Uzupełnia się do limitu – nie kumuluje się powyżej, przekroczenie jest odejmowane',
      it: 'Si ricarica fino al limite: non si accumula oltre, lo sforamento viene detratto',
      sk: 'Doplní sa po limit – nad limit sa nehromadí, prečerpanie sa odpočíta',
      ja: '限度額まで補充：それ以上は貯まらず、超過分は差し引き',
      ko: '한도까지 보충 — 한도 이상 쌓이지 않고 초과분은 차감',
      hi: 'सीमा तक भरता है — उससे ऊपर जमा नहीं, अधिक खर्च घटता है',
      nl: 'Aanvullen tot de limiet – stapelt niet daarboven, overschrijding wordt afgetrokken',
      sv: 'Fylls på till gränsen – samlas inte över den, överdrag dras av',
      vi: 'Bù đến hạn mức — không dồn vượt hạn mức, phần vượt bị trừ',
      id: 'Diisi sampai batas — tidak menumpuk di atasnya, kelebihan dipotong',
      da: 'Fyldes op til grænsen — rest hober sig aldrig op over den, overforbrug trækkes fra',
      nb: 'Fylles opp til grensen — rest hoper seg aldri opp over den, overforbruk trekkes fra',
      nn: 'Blir fylt opp til grensa — rest hopar seg aldri opp over ho, overforbruk blir trekt frå',
      fi: 'Täyttyy rajaan — jäännös ei kerry rajan yli, ylitys vähennetään',
      is: 'Fyllist upp að hámarki — afgangur safnast aldrei upp yfir það, umframeyðsla er dregin frá',
      fo: 'Fyllist upp til markið — restur savnast ongantíð yvir tað, umfarnýtsla verður drigin frá',
      cs: 'Doplňuje se do limitu — zůstatek se nad něj nikdy nehromadí, přečerpání se odečte',
      bg: 'Допълва се до лимита — остатъкът никога не се натрупва над него, преразходът се приспада',
      hr: 'Nadopunjuje se do ograničenja — ostatak se nikad ne gomila iznad njega, prekoračenje se oduzima',
      sr: 'Допуњује се до ограничења — остатак се никад не гомила изнад њега, прекорачење се одузима',
      sl: 'Dopolni se do limita — ostanek se nikoli ne nabira nad njim, prekoračitev se odšteje',
      mk: 'Се дополнува до лимитот — остатокот никогаш не се натрупува над него, пречекорувањето се одзема',
      be: 'Папаўняецца да ліміту — рэшта ніколі не назапашваецца звыш яго, перарасход вылічваецца',
      bs: 'Dopunjava se do limita — ostatak se nikad ne gomila iznad njega, prekoračenje se oduzima',
      hsb: 'Wupjelnja so hač k limitej — zbytk so ženje nad nim njenahromadźi, překročenje so wotćehnje',
    }),
    carriedIn: t({
      ru: '{{amount}} перенесено с прошлых периодов',
      en: '{{amount}} carried in from earlier periods',
      kk: 'Өткен кезеңдерден {{amount}} ауысты',
      de: '{{amount}} aus früheren Zeiträumen übertragen',
      fr: '{{amount}} reporté des périodes précédentes',
      es: '{{amount}} trasladado de periodos anteriores',
      pt: '{{amount}} transitado de períodos anteriores',
      tr: 'Önceki dönemlerden {{amount}} devredildi',
      uk: '{{amount}} перенесено з минулих періодів',
      zh: '从之前周期结转 {{amount}}',
      pl: '{{amount}} przeniesione z poprzednich okresów',
      it: '{{amount}} riportato dai periodi precedenti',
      sk: '{{amount}} prenesené z predchádzajúcich období',
      ja: '前期から {{amount}} 繰り越し',
      ko: '이전 기간에서 {{amount}} 이월',
      hi: 'पिछली अवधियों से {{amount}} आगे बढ़ा',
      nl: '{{amount}} meegenomen uit eerdere periodes',
      sv: '{{amount}} överfört från tidigare perioder',
      vi: '{{amount}} chuyển từ các kỳ trước',
      id: '{{amount}} dibawa dari periode sebelumnya',
      da: '{{amount}} overført fra tidligere perioder',
      nb: '{{amount}} overført fra tidligere perioder',
      nn: '{{amount}} overført frå tidlegare periodar',
      fi: '{{amount}} siirretty aiemmista jaksoista',
      is: '{{amount}} flutt frá fyrri tímabilum',
      fo: '{{amount}} flutt frá fyrri tíðarskeiðum',
      cs: '{{amount}} převedeno z dřívějších období',
      bg: '{{amount}} прехвърлени от предишни периоди',
      hr: '{{amount}} preneseno iz ranijih razdoblja',
      sr: '{{amount}} пренето из ранијих периода',
      sl: '{{amount}} preneseno iz prejšnjih obdobij',
      mk: '{{amount}} пренесено од претходни периоди',
      be: '{{amount}} перанесена з ранейшых перыядаў',
      bs: '{{amount}} preneseno iz ranijih perioda',
      hsb: '{{amount}} přenjesene z prjedawšich dobow',
    }),
    overspendCarriedIn: t({
      ru: 'Перерасход {{amount}} вычтен из этого периода',
      en: 'Overspend of {{amount}} deducted from this period',
      kk: '{{amount}} артық шығын осы кезеңнен шегерілді',
      de: 'Überziehung von {{amount}} von diesem Zeitraum abgezogen',
      fr: 'Dépassement de {{amount}} déduit de cette période',
      es: 'Exceso de {{amount}} descontado de este periodo',
      pt: 'Excesso de {{amount}} descontado deste período',
      tr: '{{amount}} aşım bu dönemden düşüldü',
      uk: 'Перевитрату {{amount}} віднято з цього періоду',
      zh: '本周期已扣除超支 {{amount}}',
      pl: 'Przekroczenie {{amount}} odjęte od tego okresu',
      it: 'Sforamento di {{amount}} detratto da questo periodo',
      sk: 'Prečerpanie {{amount}} odpočítané z tohto obdobia',
      ja: '超過分 {{amount}} を今期から差し引き',
      ko: '초과분 {{amount}}이(가) 이번 기간에서 차감됨',
      hi: '{{amount}} का अधिक खर्च इस अवधि से घटाया गया',
      nl: 'Overschrijding van {{amount}} afgetrokken van deze periode',
      sv: 'Överdrag på {{amount}} avdraget från denna period',
      vi: 'Phần vượt {{amount}} đã trừ khỏi kỳ này',
      id: 'Kelebihan {{amount}} dipotong dari periode ini',
      da: 'Overforbrug på {{amount}} trukket fra denne periode',
      nb: 'Overforbruk på {{amount}} trukket fra denne perioden',
      nn: 'Overforbruk på {{amount}} trekt frå denne perioden',
      fi: 'Ylitys {{amount}} vähennetty tästä jaksosta',
      is: 'Umframeyðsla upp á {{amount}} dregin frá þessu tímabili',
      fo: 'Umfarnýtsla upp á {{amount}} drigin frá hesum tíðarskeiði',
      cs: 'Přečerpání {{amount}} odečteno z tohoto období',
      bg: 'Преразход от {{amount}} е приспаднат от този период',
      hr: 'Prekoračenje od {{amount}} oduzeto od ovog razdoblja',
      sr: 'Прекорачење од {{amount}} одузето од овог периода',
      sl: 'Prekoračitev v višini {{amount}} odšteta od tega obdobja',
      mk: 'Пречекорување од {{amount}} одземено од овој период',
      be: 'Перарасход {{amount}} вылічаны з гэтага перыяду',
      bs: 'Prekoračenje od {{amount}} oduzeto od ovog perioda',
      hsb: 'Překročenje wo {{amount}} z tuteje doby wotćehnjene',
    }),
    fieldPeriod: t({
      ru: 'Период',
      en: 'Period',
      kk: 'Кезең',
      de: 'Zeitraum',
      fr: 'Période',
      es: 'Periodo',
      pt: 'Período',
      tr: 'Dönem',
      uk: 'Період',
      zh: '周期',
      pl: 'Okres',
      it: 'Periodo',
      sk: 'Obdobie',
      ja: '期間',
      ko: '기간',
      hi: 'अवधि',
      nl: 'Periode',
      sv: 'Period',
      vi: 'Kỳ',
      id: 'Periode',
      da: 'Periode',
      nb: 'Periode',
      nn: 'Periode',
      fi: 'Jakso',
      is: 'Tímabil',
      fo: 'Tíðarskeið',
      cs: 'Období',
      bg: 'Период',
      hr: 'Razdoblje',
      sr: 'Период',
      sl: 'Obdobje',
      mk: 'Период',
      be: 'Перыяд',
      bs: 'Period',
      hsb: 'Perioda',
    }),
    fieldGoal: t({
      ru: 'Цель',
      en: 'Goal',
      kk: 'Мақсат',
      de: 'Ziel',
      fr: 'Objectif',
      es: 'Meta',
      pt: 'Meta',
      tr: 'Hedef',
      uk: 'Ціль',
      zh: '目标',
      pl: 'Cel',
      it: 'Obiettivo',
      sk: 'Cieľ',
      ja: '目標',
      ko: '목표',
      hi: 'लक्ष्य',
      nl: 'Doel',
      sv: 'Mål',
      vi: 'Mục tiêu',
      id: 'Tujuan',
      da: 'Mål',
      nb: 'Mål',
      nn: 'Mål',
      fi: 'Tavoite',
      is: 'Markmið',
      fo: 'Mál',
      cs: 'Cíl',
      bg: 'Цел',
      hr: 'Cilj',
      sr: 'Циљ',
      sl: 'Cilj',
      mk: 'Цел',
      be: 'Мэта',
      bs: 'Cilj',
      hsb: 'Cil',
    }),
    noGoal: t({
      ru: 'Без цели',
      en: 'No goal',
      kk: 'Мақсатсыз',
      de: 'Kein Ziel',
      fr: 'Aucun objectif',
      es: 'Sin meta',
      pt: 'Sem meta',
      tr: 'Hedef yok',
      uk: 'Без цілі',
      zh: '无目标',
      pl: 'Bez celu',
      it: 'Nessun obiettivo',
      sk: 'Bez cieľa',
      ja: '目標なし',
      ko: '목표 없음',
      hi: 'कोई लक्ष्य नहीं',
      nl: 'Geen doel',
      sv: 'Inget mål',
      vi: 'Không có mục tiêu',
      id: 'Tanpa tujuan',
      da: 'Intet mål',
      nb: 'Ingen mål',
      nn: 'Ingen mål',
      fi: 'Ei tavoitetta',
      is: 'Ekkert markmið',
      fo: 'Ikki nakað mál',
      cs: 'Bez cíle',
      bg: 'Без цел',
      hr: 'Bez cilja',
      sr: 'Без циља',
      sl: 'Brez cilja',
      mk: 'Без цел',
      be: 'Без мэты',
      bs: 'Bez cilja',
      hsb: 'Bjez cila',
    }),
    noGoalsYet: t({
      ru: 'Целей пока нет —',
      en: 'No goals yet —',
      kk: 'Әзірге мақсат жоқ —',
      de: 'Noch keine Ziele —',
      fr: 'Aucun objectif pour l’instant —',
      es: 'Aún no hay metas —',
      pt: 'Ainda não há metas —',
      tr: 'Henüz hedef yok —',
      uk: 'Цілей поки немає —',
      zh: '还没有目标 —',
      pl: 'Brak celów —',
      it: 'Nessun obiettivo ancora —',
      sk: 'Zatiaľ žiadne ciele —',
      ja: '目標はまだありません —',
      ko: '아직 목표가 없습니다 —',
      hi: 'अभी कोई लक्ष्य नहीं —',
      nl: 'Nog geen doelen —',
      sv: 'Inga mål ännu —',
      vi: 'Chưa có mục tiêu —',
      id: 'Belum ada tujuan —',
      da: 'Ingen mål endnu —',
      nb: 'Ingen mål ennå —',
      nn: 'Ingen mål enno —',
      fi: 'Ei vielä tavoitteita —',
      is: 'Engin markmið enn —',
      fo: 'Ongin mál enn —',
      cs: 'Zatím žádné cíle —',
      bg: 'Още няма цели —',
      hr: 'Još nema ciljeva —',
      sr: 'Још нема циљева —',
      sl: 'Še ni ciljev —',
      mk: 'Сè уште нема цели —',
      be: 'Мэтаў пакуль няма —',
      bs: 'Još nema ciljeva —',
      hsb: 'Hišće žane cile —',
    }),
    createGoalLink: t({
      ru: 'создайте цель на странице «Цели»',
      en: 'create one on the Goals page',
      kk: '«Мақсаттар» бетінде жасаңыз',
      de: 'erstellen Sie eines auf der Seite „Ziele“',
      fr: 'créez-en un sur la page Objectifs',
      es: 'cree una en la página Metas',
      pt: 'crie uma na página Metas',
      tr: 'Hedefler sayfasında bir tane oluşturun',
      uk: 'створіть ціль на сторінці «Цілі»',
      zh: '在“目标”页面创建一个',
      pl: 'utwórz go na stronie Cele',
      it: 'creane uno nella pagina Obiettivi',
      sk: 'vytvorte ho na stránke Ciele',
      ja: '「目標」ページで作成しましょう',
      ko: '목표 페이지에서 만드세요',
      hi: 'लक्ष्य पेज पर एक बनाएँ',
      nl: 'maak er een aan op de pagina Doelen',
      sv: 'skapa ett på sidan Mål',
      vi: 'tạo một mục tiêu trên trang Mục tiêu',
      id: 'buat di halaman Tujuan',
      da: 'opret et på siden Mål',
      nb: 'opprett ett på Mål-siden',
      nn: 'opprett eitt på Mål-sida',
      fi: 'luo yksi Tavoitteet-sivulla',
      is: 'búðu til eitt á Markmið-síðunni',
      fo: 'stovna eitt á Mál-síðuni',
      cs: 'vytvořte jeden na stránce Cíle',
      bg: 'създайте една на страницата Цели',
      hr: 'napravite jedan na stranici Ciljevi',
      sr: 'направите један на страници Циљеви',
      sl: 'ustvarite enega na strani Cilji',
      mk: 'создајте една на страницата Цели',
      be: 'створыце адну на старонцы «Мэты»',
      bs: 'napravite jedan na stranici Ciljevi',
      hsb: 'załožće jedyn na stronje Cile',
    }),
    fieldStartsOn: t({
      ru: 'Начало',
      en: 'Starts on',
      kk: 'Басталуы',
      de: 'Beginnt am',
      fr: 'Débute le',
      es: 'Empieza el',
      pt: 'Começa em',
      tr: 'Başlangıç',
      uk: 'Початок',
      zh: '开始日期',
      pl: 'Początek',
      it: 'Inizia il',
      sk: 'Začína',
      ja: '開始日',
      ko: '시작일',
      hi: 'आरंभ तिथि',
      nl: 'Begint op',
      sv: 'Börjar',
      vi: 'Bắt đầu từ',
      id: 'Mulai pada',
      da: 'Starter',
      nb: 'Starter',
      nn: 'Startar',
      fi: 'Alkaa',
      is: 'Byrjar',
      fo: 'Byrjar',
      cs: 'Začíná',
      bg: 'Започва на',
      hr: 'Počinje',
      sr: 'Почиње',
      sl: 'Začne se',
      mk: 'Почнува на',
      be: 'Пачынаецца',
      bs: 'Počinje',
      hsb: 'Započina so',
    }),
    fieldEndsOn: t({
      ru: 'Окончание',
      en: 'Ends on',
      kk: 'Аяқталуы',
      de: 'Endet am',
      fr: 'Se termine le',
      es: 'Termina el',
      pt: 'Termina em',
      tr: 'Bitiş',
      uk: 'Закінчення',
      zh: '结束日期',
      pl: 'Koniec',
      it: 'Termina il',
      sk: 'Končí',
      ja: '終了日',
      ko: '종료일',
      hi: 'समाप्ति तिथि',
      nl: 'Eindigt op',
      sv: 'Slutar',
      vi: 'Kết thúc vào',
      id: 'Berakhir pada',
      da: 'Slutter',
      nb: 'Slutter',
      nn: 'Sluttar',
      fi: 'Päättyy',
      is: 'Lýkur',
      fo: 'Endar',
      cs: 'Končí',
      bg: 'Завършва на',
      hr: 'Završava',
      sr: 'Завршава',
      sl: 'Konča se',
      mk: 'Завршува на',
      be: 'Сканчаецца',
      bs: 'Završava',
      hsb: 'Kónči so',
    }),
    endBeforeStart: t({
      ru: 'Не может быть раньше даты начала',
      en: 'Must not be earlier than the start date',
      kk: 'Басталу күнінен ерте болмауы керек',
      de: 'Darf nicht vor dem Startdatum liegen',
      fr: 'Ne doit pas être antérieure à la date de début',
      es: 'No puede ser anterior a la fecha de inicio',
      pt: 'Não pode ser anterior à data de início',
      tr: 'Başlangıç tarihinden önce olamaz',
      uk: 'Не може бути раніше за дату початку',
      zh: '不能早于开始日期',
      pl: 'Nie może być wcześniejsza niż data początku',
      it: 'Non può essere precedente alla data di inizio',
      sk: 'Nesmie byť skôr ako dátum začiatku',
      ja: '開始日より前にはできません',
      ko: '시작일보다 이전일 수 없습니다',
      hi: 'आरंभ तिथि से पहले नहीं हो सकती',
      nl: 'Mag niet eerder zijn dan de startdatum',
      sv: 'Får inte vara före startdatumet',
      vi: 'Không được sớm hơn ngày bắt đầu',
      id: 'Tidak boleh lebih awal dari tanggal mulai',
      da: 'Må ikke være tidligere end startdatoen',
      nb: 'Kan ikke være tidligere enn startdatoen',
      nn: 'Kan ikkje vere tidlegare enn startdatoen',
      fi: 'Ei voi olla aloituspäivää aiemmin',
      is: 'Má ekki vera fyrr en upphafsdagsetningin',
      fo: 'Má ikki vera fyrr enn byrjunardagurin',
      cs: 'Nesmí být dříve než datum začátku',
      bg: 'Не може да е по-рано от началната дата',
      hr: 'Ne smije biti ranije od datuma početka',
      sr: 'Не сме бити раније од датума почетка',
      sl: 'Ne sme biti pred datumom začetka',
      mk: 'Не смее да биде пред датумот на почеток',
      be: 'Не можа быць раней за дату пачатку',
      bs: 'Ne smije biti ranije od datuma početka',
      hsb: 'Njesmě do datuma započatka być',
    }),
    toastDeleted: t({
      ru: 'Бюджет удалён',
      en: 'Budget deleted',
      kk: 'Бюджет жойылды',
      de: 'Budget gelöscht',
      fr: 'Budget supprimé',
      es: 'Presupuesto eliminado',
      pt: 'Orçamento excluído',
      tr: 'Bütçe silindi',
      uk: 'Бюджет видалено',
      zh: '预算已删除',
      pl: 'Budżet usunięty',
      it: 'Budget eliminato',
      sk: 'Rozpočet odstránený',
      ja: '予算を削除しました',
      ko: '예산이 삭제되었습니다',
      hi: 'बजट हटाया गया',
      nl: 'Budget verwijderd',
      sv: 'Budget borttagen',
      vi: 'Đã xóa ngân sách',
      id: 'Anggaran dihapus',
      da: 'Budgettet er slettet',
      nb: 'Budsjettet er slettet',
      nn: 'Budsjettet er sletta',
      fi: 'Budjetti poistettu',
      is: 'Fjárhagsáætlun eytt',
      fo: 'Fíggjarætlanin er strikað',
      cs: 'Rozpočet smazán',
      bg: 'Бюджетът е изтрит',
      hr: 'Proračun je izbrisan',
      sr: 'Буџет је избрисан',
      sl: 'Proračun je izbrisan',
      mk: 'Буџетот е избришан',
      be: 'Бюджэт выдалены',
      bs: 'Budžet je izbrisan',
      hsb: 'Budget je zhašany',
    }),
    toastDeleteFailed: t({
      ru: 'Не удалось удалить бюджет',
      en: 'Failed to delete budget',
      kk: 'Бюджетті жою мүмкін болмады',
      de: 'Budget konnte nicht gelöscht werden',
      fr: 'Impossible de supprimer le budget',
      es: 'No se pudo eliminar el presupuesto',
      pt: 'Não foi possível excluir o orçamento',
      tr: 'Bütçe silinemedi',
      uk: 'Не вдалося видалити бюджет',
      zh: '删除预算失败',
      pl: 'Nie udało się usunąć budżetu',
      it: 'Impossibile eliminare il budget',
      sk: 'Rozpočet sa nepodarilo odstrániť',
      ja: '予算を削除できませんでした',
      ko: '예산을 삭제하지 못했습니다',
      hi: 'बजट हटाया नहीं जा सका',
      nl: 'Budget verwijderen mislukt',
      sv: 'Det gick inte att ta bort budgeten',
      vi: 'Không thể xóa ngân sách',
      id: 'Gagal menghapus anggaran',
      da: 'Budgettet kunne ikke slettes',
      nb: 'Kunne ikke slette budsjettet',
      nn: 'Kunne ikkje slette budsjettet',
      fi: 'Budjetin poisto ei onnistunut',
      is: 'Ekki var unnt að eyða fjárhagsáætluninni',
      fo: 'Fekk ikki strikað fíggjarætlanina',
      cs: 'Rozpočet se nepodařilo smazat',
      bg: 'Бюджетът не можа да бъде изтрит',
      hr: 'Proračun nije moguće izbrisati',
      sr: 'Буџет није могуће избрисати',
      sl: 'Proračuna ni bilo mogoče izbrisati',
      mk: 'Буџетот не можеше да се избрише',
      be: 'Не ўдалося выдаліць бюджэт',
      bs: 'Budžet nije moguće izbrisati',
      hsb: 'Budget njeda so zhašeć',
    }),
    toastUpdated: t({
      ru: 'Бюджет обновлён',
      en: 'Budget updated',
      kk: 'Бюджет жаңартылды',
      de: 'Budget aktualisiert',
      fr: 'Budget mis à jour',
      es: 'Presupuesto actualizado',
      pt: 'Orçamento atualizado',
      tr: 'Bütçe güncellendi',
      uk: 'Бюджет оновлено',
      zh: '预算已更新',
      pl: 'Budżet zaktualizowany',
      it: 'Budget aggiornato',
      sk: 'Rozpočet aktualizovaný',
      ja: '予算を更新しました',
      ko: '예산이 업데이트되었습니다',
      hi: 'बजट अपडेट किया गया',
      nl: 'Budget bijgewerkt',
      sv: 'Budget uppdaterad',
      vi: 'Đã cập nhật ngân sách',
      id: 'Anggaran diperbarui',
      da: 'Budgettet er opdateret',
      nb: 'Budsjettet er oppdatert',
      nn: 'Budsjettet er oppdatert',
      fi: 'Budjetti päivitetty',
      is: 'Fjárhagsáætlun uppfærð',
      fo: 'Fíggjarætlanin er dagførd',
      cs: 'Rozpočet upraven',
      bg: 'Бюджетът е обновен',
      hr: 'Proračun je ažuriran',
      sr: 'Буџет је ажуриран',
      sl: 'Proračun je posodobljen',
      mk: 'Буџетот е ажуриран',
      be: 'Бюджэт абноўлены',
      bs: 'Budžet je ažuriran',
      hsb: 'Budget je aktualizowany',
    }),
    toastCreated: t({
      ru: 'Бюджет создан',
      en: 'Budget created',
      kk: 'Бюджет жасалды',
      de: 'Budget erstellt',
      fr: 'Budget créé',
      es: 'Presupuesto creado',
      pt: 'Orçamento criado',
      tr: 'Bütçe oluşturuldu',
      uk: 'Бюджет створено',
      zh: '预算已创建',
      pl: 'Budżet utworzony',
      it: 'Budget creato',
      sk: 'Rozpočet vytvorený',
      ja: '予算を作成しました',
      ko: '예산이 생성되었습니다',
      hi: 'बजट बनाया गया',
      nl: 'Budget aangemaakt',
      sv: 'Budget skapad',
      vi: 'Đã tạo ngân sách',
      id: 'Anggaran dibuat',
      da: 'Budgettet er oprettet',
      nb: 'Budsjettet er opprettet',
      nn: 'Budsjettet er oppretta',
      fi: 'Budjetti luotu',
      is: 'Fjárhagsáætlun búin til',
      fo: 'Fíggjarætlanin er stovnað',
      cs: 'Rozpočet vytvořen',
      bg: 'Бюджетът е създаден',
      hr: 'Proračun je napravljen',
      sr: 'Буџет је направљен',
      sl: 'Proračun je ustvarjen',
      mk: 'Буџетот е создаден',
      be: 'Бюджэт створаны',
      bs: 'Budžet je napravljen',
      hsb: 'Budget je załoženy',
    }),
    toastSaveFailed: t({
      ru: 'Не удалось сохранить бюджет',
      en: 'Failed to save budget',
      kk: 'Бюджетті сақтау мүмкін болмады',
      de: 'Budget konnte nicht gespeichert werden',
      fr: 'Impossible d’enregistrer le budget',
      es: 'No se pudo guardar el presupuesto',
      pt: 'Não foi possível salvar o orçamento',
      tr: 'Bütçe kaydedilemedi',
      uk: 'Не вдалося зберегти бюджет',
      zh: '保存预算失败',
      pl: 'Nie udało się zapisać budżetu',
      it: 'Impossibile salvare il budget',
      sk: 'Rozpočet sa nepodarilo uložiť',
      ja: '予算を保存できませんでした',
      ko: '예산을 저장하지 못했습니다',
      hi: 'बजट सहेजा नहीं जा सका',
      nl: 'Budget opslaan mislukt',
      sv: 'Det gick inte att spara budgeten',
      vi: 'Không thể lưu ngân sách',
      id: 'Gagal menyimpan anggaran',
      da: 'Budgettet kunne ikke gemmes',
      nb: 'Kunne ikke lagre budsjettet',
      nn: 'Kunne ikkje lagre budsjettet',
      fi: 'Budjetin tallennus ei onnistunut',
      is: 'Ekki var unnt að vista fjárhagsáætlunina',
      fo: 'Fekk ikki goymt fíggjarætlanina',
      cs: 'Rozpočet se nepodařilo uložit',
      bg: 'Бюджетът не можа да бъде запазен',
      hr: 'Proračun nije moguće spremiti',
      sr: 'Буџет није могуће сачувати',
      sl: 'Proračuna ni bilo mogoče shraniti',
      mk: 'Буџетот не можеше да се зачува',
      be: 'Не ўдалося захаваць бюджэт',
      bs: 'Budžet nije moguće sačuvati',
      hsb: 'Budget njeda so składować',
    }),
    loadFailed: t({
      ru: 'Не удалось загрузить бюджеты',
      en: 'Failed to load budgets',
      kk: 'Бюджеттерді жүктеу мүмкін болмады',
      de: 'Budgets konnten nicht geladen werden',
      fr: 'Impossible de charger les budgets',
      es: 'No se pudieron cargar los presupuestos',
      pt: 'Não foi possível carregar os orçamentos',
      tr: 'Bütçeler yüklenemedi',
      uk: 'Не вдалося завантажити бюджети',
      zh: '加载预算失败',
      pl: 'Nie udało się wczytać budżetów',
      it: 'Impossibile caricare i budget',
      sk: 'Rozpočty sa nepodarilo načítať',
      ja: '予算を読み込めませんでした',
      ko: '예산을 불러오지 못했습니다',
      hi: 'बजट लोड नहीं हो सके',
      nl: 'Budgetten laden mislukt',
      sv: 'Det gick inte att läsa in budgetar',
      vi: 'Không thể tải ngân sách',
      id: 'Gagal memuat anggaran',
      da: 'Budgetterne kunne ikke indlæses',
      nb: 'Kunne ikke laste budsjettene',
      nn: 'Kunne ikkje laste budsjetta',
      fi: 'Budjettien lataus ei onnistunut',
      is: 'Ekki var unnt að hlaða fjárhagsáætlunum',
      fo: 'Fekk ikki lisið fíggjarætlanirnar',
      cs: 'Rozpočty se nepodařilo načíst',
      bg: 'Бюджетите не можаха да се заредят',
      hr: 'Proračune nije moguće učitati',
      sr: 'Буџете није могуће учитати',
      sl: 'Proračunov ni bilo mogoče naložiti',
      mk: 'Буџетите не можеа да се вчитаат',
      be: 'Не ўдалося загрузіць бюджэты',
      bs: 'Budžete nije moguće učitati',
      hsb: 'Budgety njedadźa so začitać',
    }),
    savingsGoals: t({
      ru: 'Цели накоплений',
      en: 'Savings goals',
      kk: 'Жинақтау мақсаттары',
      de: 'Sparziele',
      fr: 'Objectifs d’épargne',
      es: 'Metas de ahorro',
      pt: 'Objetivos de poupança',
      tr: 'Birikim hedefleri',
      uk: 'Цілі накопичень',
      zh: '储蓄目标',
      pl: 'Cele oszczędnościowe',
      it: 'Obiettivi di risparmio',
      sk: 'Sporiace ciele',
      ja: '貯蓄目標',
      ko: '저축 목표',
      hi: 'बचत लक्ष्य',
      nl: 'Spaardoelen',
      sv: 'Sparmål',
      vi: 'Mục tiêu tiết kiệm',
      id: 'Target tabungan',
      da: 'Opsparingsmål',
      nb: 'Sparemål',
      nn: 'Sparemål',
      fi: 'Säästötavoitteet',
      is: 'Sparnaðarmarkmið',
      fo: 'Sparimál',
      cs: 'Spořicí cíle',
      bg: 'Цели за спестяване',
      hr: 'Ciljevi štednje',
      sr: 'Циљеви штедње',
      sl: 'Cilji varčevanja',
      mk: 'Цели за штедење',
      be: 'Мэты заашчаджэння',
      bs: 'Ciljevi štednje',
      hsb: 'Lutowanske cile',
    }),
  },
} satisfies Dictionary;

export default content;
