/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'localCategorizationPanel',
  content: {
    status: t({
      ru: 'Статус',
      en: 'Status',
      kk: 'Күйі',
      de: 'Status',
      fr: 'Statut',
      es: 'Estado',
      pt: 'Status',
      tr: 'Durum',
      uk: 'Статус',
      zh: '状态',
      ar: 'الحالة',
      pl: 'Status',
      it: 'Stato',
      sk: 'Stav',
      ja: 'ステータス',
      ko: '상태',
      hi: 'स्थिति',
      nl: 'Status',
      sv: 'Status',
      vi: 'Trạng thái',
      id: 'Status',
      da: 'Status',
      nb: 'Status',
      nn: 'Status',
      fi: 'Tila',
      is: 'Staða',
      fo: 'Støða',
      cs: 'Stav',
      bg: 'Статус',
      hr: 'Status',
      sr: 'Статус',
      sl: 'Stanje',
      mk: 'Статус',
      be: 'Стан',
      bs: 'Status',
      hsb: 'Status',
    }),
    modelReady: t({
      ru: 'Модель готова',
      en: 'Model ready',
      kk: 'Модель дайын',
      de: 'Modell bereit',
      fr: 'Modèle prêt',
      es: 'Modelo listo',
      pt: 'Modelo pronto',
      tr: 'Model hazır',
      uk: 'Модель готова',
      zh: '模型已就绪',
      ar: 'النموذج جاهز',
      pl: 'Model gotowy',
      it: 'Modello pronto',
      sk: 'Model je pripravený',
      ja: 'モデル準備完了',
      ko: '모델 준비됨',
      hi: 'मॉडल तैयार है',
      nl: 'Model gereed',
      sv: 'Modellen är klar',
      vi: 'Mô hình đã sẵn sàng',
      id: 'Model siap',
      da: 'Modellen er klar',
      nb: 'Modellen er klar',
      nn: 'Modellen er klar',
      fi: 'Malli on valmis',
      is: 'Gerðin er tilbúin',
      fo: 'Mynstrið er klárt',
      cs: 'Model je připraven',
      bg: 'Моделът е готов',
      hr: 'Model je spreman',
      sr: 'Модел је спреман',
      sl: 'Model je pripravljen',
      mk: 'Моделот е готов',
      be: 'Мадэль гатовая',
      bs: 'Model je spreman',
      hsb: 'Model je hotowy',
    }),
    modelMissing: t({
      ru: 'Модель не установлена',
      en: 'Model missing',
      kk: 'Модель орнатылмаған',
      de: 'Modell fehlt',
      fr: 'Modèle manquant',
      es: 'Falta el modelo',
      pt: 'Modelo ausente',
      tr: 'Model eksik',
      uk: 'Модель не встановлено',
      zh: '缺少模型',
      ar: 'النموذج غير موجود',
      pl: 'Brak modelu',
      it: 'Modello mancante',
      sk: 'Model chýba',
      ja: 'モデルがありません',
      ko: '모델 없음',
      hi: 'मॉडल उपलब्ध नहीं है',
      nl: 'Model ontbreekt',
      sv: 'Modell saknas',
      vi: 'Thiếu mô hình',
      id: 'Model belum ada',
      da: 'Modellen mangler',
      nb: 'Modellen mangler',
      nn: 'Modellen manglar',
      fi: 'Malli puuttuu',
      is: 'Gerðin vantar',
      fo: 'Mynstrið manglar',
      cs: 'Model chybí',
      bg: 'Моделът липсва',
      hr: 'Model manjka',
      sr: 'Модел недостаје',
      sl: 'Model manjka',
      mk: 'Моделот недостига',
      be: 'Мадэлі не хапае',
      bs: 'Model manjka',
      hsb: 'Model pobrachuje',
    }),
    runsLocally: t({
      ru: 'Категоризация выполняется локально. Архив модели хранится на сервере, а загрузка удалённых моделей во время проверки отключена.',
      en: 'Categorization runs locally. The model archive is stored by the backend and remote model loading stays disabled during tests.',
      kk: 'Санаттау жергілікті түрде орындалады. Модель мұрағаты серверде сақталады, ал тексеру кезінде қашықтағы модельдерді жүктеу өшірулі.',
      de: 'Die Kategorisierung läuft lokal. Das Modellarchiv wird im Backend gespeichert, und das Laden entfernter Modelle bleibt bei Tests deaktiviert.',
      fr: "La catégorisation s'exécute localement. L'archive du modèle est stockée par le serveur et le chargement de modèles distants reste désactivé pendant les tests.",
      es: 'La categorización se ejecuta localmente. El archivo del modelo se guarda en el servidor y la carga de modelos remotos permanece desactivada durante las pruebas.',
      pt: 'A categorização é executada localmente. O arquivo do modelo é armazenado pelo servidor e o carregamento de modelos remotos fica desativado durante os testes.',
      tr: 'Kategorilendirme yerel olarak çalışır. Model arşivi sunucuda saklanır ve testler sırasında uzak model yükleme kapalı kalır.',
      uk: 'Категоризація виконується локально. Архів моделі зберігається на сервері, а завантаження віддалених моделей під час перевірки вимкнено.',
      zh: '分类在本地运行。模型压缩包由后端保存，测试期间不会加载远程模型。',
      ar: 'يتم التصنيف محليًا. يُخزَّن أرشيف النموذج على الخادم ويبقى تحميل النماذج البعيدة معطّلًا أثناء الاختبار.',
      pl: 'Kategoryzacja działa lokalnie. Archiwum modelu jest przechowywane na serwerze, a ładowanie zdalnych modeli pozostaje wyłączone podczas testów.',
      it: "La categorizzazione avviene in locale. L'archivio del modello è conservato dal backend e il caricamento di modelli remoti resta disattivato durante i test.",
      sk: 'Kategorizácia prebieha lokálne. Archív modelu je uložený na serveri a načítanie vzdialených modelov zostáva počas testov vypnuté.',
      ja: '分類はローカルで実行されます。モデルのアーカイブはバックエンドに保存され、テスト中はリモートモデルの読み込みが無効になります。',
      ko: '분류는 로컬에서 실행됩니다. 모델 아카이브는 백엔드에 저장되며 테스트 중에는 원격 모델 로딩이 비활성화됩니다.',
      hi: 'वर्गीकरण स्थानीय रूप से चलता है। मॉडल आर्काइव बैकएंड पर संग्रहीत होता है और परीक्षण के दौरान रिमोट मॉडल लोड करना बंद रहता है।',
      nl: 'Categorisatie draait lokaal. Het modelarchief wordt door de backend opgeslagen en het laden van externe modellen blijft uitgeschakeld tijdens tests.',
      sv: 'Kategoriseringen körs lokalt. Modellarkivet lagras av servern och inläsning av fjärrmodeller är avstängd under tester.',
      vi: 'Việc phân loại chạy cục bộ. Tệp lưu trữ mô hình được lưu trên máy chủ và việc tải mô hình từ xa bị tắt trong khi kiểm tra.',
      id: 'Kategorisasi berjalan secara lokal. Arsip model disimpan oleh server dan pemuatan model jarak jauh tetap dinonaktifkan selama pengujian.',
      da: 'Kategoriseringen kører lokalt. Modelarkivet gemmes af backend, og fjernindlæsning af modeller er slået fra under test.',
      nb: 'Kategoriseringen kjører lokalt. Modellarkivet lagres av backend, og fjernlasting av modeller er slått av under testing.',
      nn: 'Kategoriseringa køyrer lokalt. Modellarkivet vert lagra av backend, og fjernlasting av modellar er slått av under testing.',
      fi: 'Luokittelu suoritetaan paikallisesti. Taustajärjestelmä säilyttää malliarkiston, ja mallien etälataus pysyy pois käytöstä testien aikana.',
      is: 'Flokkun er framkvæmd staðbundið. Bakendinn vistar gerðarsafnið og fjarhleðsla gerða er óvirk á meðan prófanir eru í gangi.',
      fo: 'Bólkingin verður gjørd staðbundið. Bakendin goymir mynsturskjalasavnið, og fjarlesting av mynstrum er sløkt undir royndum.',
      cs: 'Kategorizace běží lokálně. Archiv modelu ukládá backend a vzdálené načítání modelů zůstává během testů vypnuté.',
      bg: 'Категоризирането се изпълнява локално. Архивът на модела се пази от бекенда, а зареждането на отдалечени модели остава изключено по време на тестове.',
      hr: 'Kategorizacija se izvodi lokalno. Arhivu modela čuva pozadinski servis, a udaljeno učitavanje modela ostaje isključeno tijekom testova.',
      sr: 'Категоризација се изводи локално. Архиву модела чува позадински сервис, а удаљено учитавање модела остаје искључено током тестова.',
      sl: 'Razvrščanje poteka lokalno. Arhiv modela hrani zaledje, oddaljeno nalaganje modelov pa med testi ostane izklopljeno.',
      mk: 'Категоризирањето се изведува локално. Архивата на моделот ја чува заднинскиот сервис, а далечинското вчитување модели останува исклучено при тестовите.',
      be: 'Катэгарызацыя выконваецца лакальна. Архіў мадэлі зберагае бэкенд, а аддаленая загрузка мадэлей застаецца выключанай пад час тэстаў.',
      bs: 'Kategorizacija se izvodi lokalno. Arhivu modela čuva pozadinski servis, a udaljeno učitavanje modela ostaje isključeno tokom testova.',
      hsb: 'Kategorizowanje běži lokalnje. Archiw modela składuje backend, a zdaleny začitak modelow wostanje za testy wupnjeny.',
    }),
    installedPath: t({
      ru: 'Путь установки: {path}',
      en: 'Installed path: {path}',
      kk: 'Орнату жолы: {path}',
      de: 'Installationspfad: {path}',
      fr: "Chemin d'installation : {path}",
      es: 'Ruta de instalación: {path}',
      pt: 'Caminho de instalação: {path}',
      tr: 'Kurulum yolu: {path}',
      uk: 'Шлях встановлення: {path}',
      zh: '安装路径：{path}',
      ar: 'مسار التثبيت: {path}',
      pl: 'Ścieżka instalacji: {path}',
      it: 'Percorso di installazione: {path}',
      sk: 'Cesta inštalácie: {path}',
      ja: 'インストール先: {path}',
      ko: '설치 경로: {path}',
      hi: 'इंस्टॉल पथ: {path}',
      nl: 'Installatiepad: {path}',
      sv: 'Installationssökväg: {path}',
      vi: 'Đường dẫn cài đặt: {path}',
      id: 'Jalur instalasi: {path}',
      da: 'Installeret sti: {path}',
      nb: 'Installert bane: {path}',
      nn: 'Installert bane: {path}',
      fi: 'Asennuspolku: {path}',
      is: 'Uppsett slóð: {path}',
      fo: 'Innsett leið: {path}',
      cs: 'Nainstalovaná cesta: {path}',
      bg: 'Инсталиран път: {path}',
      hr: 'Instalirana staza: {path}',
      sr: 'Инсталирана стаза: {path}',
      sl: 'Namestitvena pot: {path}',
      mk: 'Инсталирана патека: {path}',
      be: 'Шлях устаноўкі: {path}',
      bs: 'Instalirana staza: {path}',
      hsb: 'Instalowany puć: {path}',
    }),
    settings: t({
      ru: 'Настройки',
      en: 'Settings',
      kk: 'Баптаулар',
      de: 'Einstellungen',
      fr: 'Paramètres',
      es: 'Configuración',
      pt: 'Configurações',
      tr: 'Ayarlar',
      uk: 'Налаштування',
      zh: '设置',
      ar: 'الإعدادات',
      pl: 'Ustawienia',
      it: 'Impostazioni',
      sk: 'Nastavenia',
      ja: '設定',
      ko: '설정',
      hi: 'सेटिंग्स',
      nl: 'Instellingen',
      sv: 'Inställningar',
      vi: 'Cài đặt',
      id: 'Pengaturan',
      da: 'Indstillinger',
      nb: 'Innstillinger',
      nn: 'Innstillingar',
      fi: 'Asetukset',
      is: 'Stillingar',
      fo: 'Innstillingar',
      cs: 'Nastavení',
      bg: 'Настройки',
      hr: 'Postavke',
      sr: 'Поставке',
      sl: 'Nastavitve',
      mk: 'Поставки',
      be: 'Налады',
      bs: 'Postavke',
      hsb: 'Nastajenja',
    }),
    saving: t({
      ru: 'Сохранение...',
      en: 'Saving...',
      kk: 'Сақталуда...',
      de: 'Wird gespeichert...',
      fr: 'Enregistrement...',
      es: 'Guardando...',
      pt: 'Salvando...',
      tr: 'Kaydediliyor...',
      uk: 'Збереження...',
      zh: '正在保存...',
      ar: 'جارٍ الحفظ...',
      pl: 'Zapisywanie...',
      it: 'Salvataggio...',
      sk: 'Ukladá sa...',
      ja: '保存中...',
      ko: '저장 중...',
      hi: 'सहेजा जा रहा है...',
      nl: 'Opslaan...',
      sv: 'Sparar...',
      vi: 'Đang lưu...',
      id: 'Menyimpan...',
      da: 'Gemmer...',
      nb: 'Lagrer...',
      nn: 'Lagrar...',
      fi: 'Tallennetaan...',
      is: 'Vista...',
      fo: 'Goymi...',
      cs: 'Ukládání...',
      bg: 'Запазва се...',
      hr: 'Spremanje...',
      sr: 'Чување...',
      sl: 'Shranjujem...',
      mk: 'Се зачувува...',
      be: 'Захаванне...',
      bs: 'Čuvanje...',
      hsb: 'Składuje so...',
    }),
    saveSettings: t({
      ru: 'Сохранить настройки',
      en: 'Save settings',
      kk: 'Баптауларды сақтау',
      de: 'Einstellungen speichern',
      fr: 'Enregistrer les paramètres',
      es: 'Guardar configuración',
      pt: 'Salvar configurações',
      tr: 'Ayarları kaydet',
      uk: 'Зберегти налаштування',
      zh: '保存设置',
      ar: 'حفظ الإعدادات',
      pl: 'Zapisz ustawienia',
      it: 'Salva impostazioni',
      sk: 'Uložiť nastavenia',
      ja: '設定を保存',
      ko: '설정 저장',
      hi: 'सेटिंग्स सहेजें',
      nl: 'Instellingen opslaan',
      sv: 'Spara inställningar',
      vi: 'Lưu cài đặt',
      id: 'Simpan pengaturan',
      da: 'Gem indstillinger',
      nb: 'Lagre innstillinger',
      nn: 'Lagre innstillingar',
      fi: 'Tallenna asetukset',
      is: 'Vista stillingar',
      fo: 'Goym innstillingar',
      cs: 'Uložit nastavení',
      bg: 'Запазване на настройките',
      hr: 'Spremi postavke',
      sr: 'Сачувај подешавања',
      sl: 'Shrani nastavitve',
      mk: 'Зачувај ги поставките',
      be: 'Захаваць налады',
      bs: 'Sačuvaj postavke',
      hsb: 'Nastajenja składować',
    }),
    model: t({
      ru: 'Модель',
      en: 'Model',
      kk: 'Модель',
      de: 'Modell',
      fr: 'Modèle',
      es: 'Modelo',
      pt: 'Modelo',
      tr: 'Model',
      uk: 'Модель',
      zh: '模型',
      ar: 'النموذج',
      pl: 'Model',
      it: 'Modello',
      sk: 'Model',
      ja: 'モデル',
      ko: '모델',
      hi: 'मॉडल',
      nl: 'Model',
      sv: 'Modell',
      vi: 'Mô hình',
      id: 'Model',
      da: 'Model',
      nb: 'Modell',
      nn: 'Modell',
      fi: 'Malli',
      is: 'Líkan',
      fo: 'Modell',
      cs: 'Model',
      bg: 'Модел',
      hr: 'Model',
      sr: 'Модел',
      sl: 'Model',
      mk: 'Модел',
      be: 'Мадэль',
      bs: 'Model',
      hsb: 'Model',
    }),
    threshold: t({
      ru: 'Порог',
      en: 'Threshold',
      kk: 'Шекті мән',
      de: 'Schwellenwert',
      fr: 'Seuil',
      es: 'Umbral',
      pt: 'Limite',
      tr: 'Eşik',
      uk: 'Поріг',
      zh: '阈值',
      ar: 'الحد',
      pl: 'Próg',
      it: 'Soglia',
      sk: 'Prah',
      ja: 'しきい値',
      ko: '임계값',
      hi: 'सीमा',
      nl: 'Drempel',
      sv: 'Tröskel',
      vi: 'Ngưỡng',
      id: 'Ambang batas',
      da: 'Tærskel',
      nb: 'Terskel',
      nn: 'Terskel',
      fi: 'Kynnysarvo',
      is: 'Þröskuldur',
      fo: 'Tredskul',
      cs: 'Prah',
      bg: 'Праг',
      hr: 'Prag',
      sr: 'Праг',
      sl: 'Mejna vrednost',
      mk: 'Праг',
      be: 'Парог',
      bs: 'Prag',
      hsb: 'Hrańca',
    }),
    enable: t({
      ru: 'Включить локальную категоризацию',
      en: 'Enable local categorization',
      kk: 'Жергілікті санаттауды қосу',
      de: 'Lokale Kategorisierung aktivieren',
      fr: 'Activer la catégorisation locale',
      es: 'Activar la categorización local',
      pt: 'Ativar a categorização local',
      tr: 'Yerel kategorilendirmeyi etkinleştir',
      uk: 'Увімкнути локальну категоризацію',
      zh: '启用本地分类',
      ar: 'تفعيل التصنيف المحلي',
      pl: 'Włącz lokalną kategoryzację',
      it: 'Attiva la categorizzazione locale',
      sk: 'Zapnúť lokálnu kategorizáciu',
      ja: 'ローカル分類を有効にする',
      ko: '로컬 분류 사용',
      hi: 'स्थानीय वर्गीकरण सक्षम करें',
      nl: 'Lokale categorisatie inschakelen',
      sv: 'Aktivera lokal kategorisering',
      vi: 'Bật phân loại cục bộ',
      id: 'Aktifkan kategorisasi lokal',
      da: 'Slå lokal kategorisering til',
      nb: 'Slå på lokal kategorisering',
      nn: 'Slå på lokal kategorisering',
      fi: 'Ota paikallinen luokittelu käyttöön',
      is: 'Kveikja á staðbundinni flokkun',
      fo: 'Tendra staðbundna bólking',
      cs: 'Zapnout lokální kategorizaci',
      bg: 'Включване на локалното категоризиране',
      hr: 'Uključi lokalnu kategorizaciju',
      sr: 'Укључи локалну категоризацију',
      sl: 'Vklopi lokalno razvrščanje',
      mk: 'Вклучи локално категоризирање',
      be: 'Уключыць лакальную катэгарызацыю',
      bs: 'Uključi lokalnu kategorizaciju',
      hsb: 'Lokalne kategorizowanje zmóžnić',
    }),
    modelArchive: t({
      ru: 'Архив модели',
      en: 'Model archive',
      kk: 'Модель мұрағаты',
      de: 'Modellarchiv',
      fr: 'Archive du modèle',
      es: 'Archivo del modelo',
      pt: 'Arquivo do modelo',
      tr: 'Model arşivi',
      uk: 'Архів моделі',
      zh: '模型压缩包',
      ar: 'أرشيف النموذج',
      pl: 'Archiwum modelu',
      it: 'Archivio del modello',
      sk: 'Archív modelu',
      ja: 'モデルアーカイブ',
      ko: '모델 아카이브',
      hi: 'मॉडल आर्काइव',
      nl: 'Modelarchief',
      sv: 'Modellarkiv',
      vi: 'Tệp lưu trữ mô hình',
      id: 'Arsip model',
      da: 'Modelarkiv',
      nb: 'Modellarkiv',
      nn: 'Modellarkiv',
      fi: 'Malliarkisto',
      is: 'Gerðarsafn',
      fo: 'Mynsturskjalasavn',
      cs: 'Archiv modelu',
      bg: 'Архив на модела',
      hr: 'Arhiva modela',
      sr: 'Архива модела',
      sl: 'Arhiv modela',
      mk: 'Архива на моделот',
      be: 'Архіў мадэлі',
      bs: 'Arhiva modela',
      hsb: 'Archiw modela',
    }),
    installing: t({
      ru: 'Установка...',
      en: 'Installing...',
      kk: 'Орнатылуда...',
      de: 'Wird installiert...',
      fr: 'Installation...',
      es: 'Instalando...',
      pt: 'Instalando...',
      tr: 'Yükleniyor...',
      uk: 'Встановлення...',
      zh: '正在安装...',
      ar: 'جارٍ التثبيت...',
      pl: 'Instalowanie...',
      it: 'Installazione...',
      sk: 'Inštaluje sa...',
      ja: 'インストール中...',
      ko: '설치 중...',
      hi: 'इंस्टॉल हो रहा है...',
      nl: 'Installeren...',
      sv: 'Installerar...',
      vi: 'Đang cài đặt...',
      id: 'Memasang...',
      da: 'Installerer ...',
      nb: 'Installerer ...',
      nn: 'Installerer ...',
      fi: 'Asennetaan ...',
      is: 'Set upp ...',
      fo: 'Setir upp ...',
      cs: 'Instaluje se ...',
      bg: 'Инсталира се ...',
      hr: 'Instalira se ...',
      sr: 'Инсталира се ...',
      sl: 'Nameščanje ...',
      mk: 'Се инсталира ...',
      be: 'Устаноўка ...',
      bs: 'Instalira se ...',
      hsb: 'Instaluje so ...',
    }),
    uploadZip: t({
      ru: 'Загрузить ZIP',
      en: 'Upload ZIP',
      kk: 'ZIP жүктеу',
      de: 'ZIP hochladen',
      fr: 'Importer un ZIP',
      es: 'Subir ZIP',
      pt: 'Enviar ZIP',
      tr: 'ZIP yükle',
      uk: 'Завантажити ZIP',
      zh: '上传 ZIP',
      ar: 'رفع ملف ZIP',
      pl: 'Prześlij ZIP',
      it: 'Carica ZIP',
      sk: 'Nahrať ZIP',
      ja: 'ZIP をアップロード',
      ko: 'ZIP 업로드',
      hi: 'ZIP अपलोड करें',
      nl: 'ZIP uploaden',
      sv: 'Ladda upp ZIP',
      vi: 'Tải lên ZIP',
      id: 'Unggah ZIP',
      da: 'Upload ZIP',
      nb: 'Last opp ZIP',
      nn: 'Last opp ZIP',
      fi: 'Lataa ZIP',
      is: 'Senda inn ZIP',
      fo: 'Send ZIP inn',
      cs: 'Nahrát ZIP',
      bg: 'Качване на ZIP',
      hr: 'Učitaj ZIP',
      sr: 'Учитај ZIP',
      sl: 'Naloži ZIP',
      mk: 'Постави ZIP',
      be: 'Загрузіць ZIP',
      bs: 'Učitaj ZIP',
      hsb: 'ZIP nahrać',
    }),
    uploadHint: t({
      ru: 'Загрузите ZIP с моделью Transformers.js, содержащий config.json и файл модели onnx. Приложение установит её в папку моделей рабочего пространства.',
      en: 'Upload a ZIP that contains a Transformers.js model with config.json and an onnx model file. The app will install it into the workspace model folder.',
      kk: 'config.json және onnx модель файлы бар Transformers.js моделінің ZIP мұрағатын жүктеңіз. Қолданба оны жұмыс кеңістігінің модельдер қалтасына орнатады.',
      de: 'Laden Sie ein ZIP mit einem Transformers.js-Modell hoch, das config.json und eine onnx-Modelldatei enthält. Die App installiert es im Modellordner des Workspace.',
      fr: "Importez un ZIP contenant un modèle Transformers.js avec config.json et un fichier de modèle onnx. L'application l'installera dans le dossier des modèles de l'espace de travail.",
      es: 'Sube un ZIP que contenga un modelo de Transformers.js con config.json y un archivo de modelo onnx. La aplicación lo instalará en la carpeta de modelos del espacio de trabajo.',
      pt: 'Envie um ZIP com um modelo Transformers.js contendo config.json e um arquivo de modelo onnx. O app o instalará na pasta de modelos do espaço de trabalho.',
      tr: 'config.json ve bir onnx model dosyası içeren Transformers.js modelini ZIP olarak yükleyin. Uygulama onu çalışma alanının model klasörüne kurar.',
      uk: 'Завантажте ZIP із моделлю Transformers.js, що містить config.json і файл моделі onnx. Застосунок встановить її в папку моделей робочого простору.',
      zh: '上传包含 config.json 和 onnx 模型文件的 Transformers.js 模型 ZIP。应用会将其安装到工作区的模型文件夹中。',
      ar: 'ارفع ملف ZIP يحتوي على نموذج Transformers.js مع config.json وملف نموذج onnx. سيثبّته التطبيق في مجلد نماذج مساحة العمل.',
      pl: 'Prześlij ZIP z modelem Transformers.js zawierający config.json i plik modelu onnx. Aplikacja zainstaluje go w folderze modeli obszaru roboczego.',
      it: "Carica uno ZIP con un modello Transformers.js contenente config.json e un file di modello onnx. L'app lo installerà nella cartella dei modelli dell'area di lavoro.",
      sk: 'Nahrajte ZIP s modelom Transformers.js, ktorý obsahuje config.json a súbor modelu onnx. Aplikácia ho nainštaluje do priečinka modelov pracovného priestoru.',
      ja: 'config.json と onnx モデルファイルを含む Transformers.js モデルの ZIP をアップロードしてください。アプリがワークスペースのモデルフォルダーにインストールします。',
      ko: 'config.json과 onnx 모델 파일이 포함된 Transformers.js 모델 ZIP을 업로드하세요. 앱이 워크스페이스 모델 폴더에 설치합니다.',
      hi: 'config.json और onnx मॉडल फ़ाइल वाला Transformers.js मॉडल ZIP अपलोड करें। ऐप इसे वर्कस्पेस के मॉडल फ़ोल्डर में इंस्टॉल करेगा।',
      nl: 'Upload een ZIP met een Transformers.js-model met config.json en een onnx-modelbestand. De app installeert het in de modelmap van de werkruimte.',
      sv: 'Ladda upp en ZIP med en Transformers.js-modell som innehåller config.json och en onnx-modellfil. Appen installerar den i arbetsytans modellmapp.',
      vi: 'Tải lên tệp ZIP chứa mô hình Transformers.js với config.json và tệp mô hình onnx. Ứng dụng sẽ cài đặt nó vào thư mục mô hình của không gian làm việc.',
      id: 'Unggah ZIP berisi model Transformers.js dengan config.json dan file model onnx. Aplikasi akan memasangnya ke folder model ruang kerja.',
      da: 'Upload en ZIP, der indeholder en Transformers.js-model med config.json og en onnx-modelfil. Appen installerer den i arbejdsområdets modelmappe.',
      nb: 'Last opp en ZIP som inneholder en Transformers.js-modell med config.json og en onnx-modellfil. Appen installerer den i modellmappen til arbeidsområdet.',
      nn: 'Last opp ein ZIP som inneheld ein Transformers.js-modell med config.json og ei onnx-modellfil. Appen installerer han i modellmappa til arbeidsområdet.',
      fi: 'Lataa ZIP, joka sisältää Transformers.js-mallin sekä tiedostot config.json ja onnx-mallitiedoston. Sovellus asentaa sen työtilan mallikansioon.',
      is: 'Sendu inn ZIP sem inniheldur Transformers.js-gerð með config.json og onnx-gerðarskrá. Forritið setur hana upp í gerðarmöppu vinnurýmisins.',
      fo: 'Send eina ZIP inn, sum inniheldur eitt Transformers.js-mynstur við config.json og eina onnx-mynsturfílu. Appurin setur tað upp í mynsturmappuni hjá arbeiðsøkinum.',
      cs: 'Nahrajte ZIP, který obsahuje model Transformers.js s config.json a soubor modelu onnx. Aplikace jej nainstaluje do složky modelů pracovního prostoru.',
      bg: 'Качете ZIP, който съдържа модел на Transformers.js с config.json и файл на onnx модел. Приложението ще го инсталира в папката с модели на работното пространство.',
      hr: 'Učitajte ZIP koji sadrži model Transformers.js s config.json i datotekom onnx modela. Aplikacija će ga instalirati u mapu modela radnog prostora.',
      sr: 'Учитајте ZIP који садржи модел Transformers.js с config.json и датотеком onnx модела. Апликација ће га инсталирати у фасциклу модела радног простора.',
      sl: 'Naložite ZIP, ki vsebuje model Transformers.js s config.json in datoteko modela onnx. Aplikacija ga bo namestila v mapo modelov delovnega prostora.',
      mk: 'Поставете ZIP што содржи модел Transformers.js со config.json и податотека на onnx модел. Апликацијата ќе го инсталира во папката со модели на работниот простор.',
      be: 'Загрузіце ZIP, які ўтрымлівае мадэль Transformers.js з config.json і файлам мадэлі onnx. Праграма ўстановіць яе ў папку мадэлей працоўнай прасторы.',
      bs: 'Učitajte ZIP koji sadrži model Transformers.js s config.json i datotekom onnx modela. Aplikacija će ga instalirati u folder modela radnog prostora.',
      hsb: 'Nahrajće ZIP, kotryž model Transformers.js z config.json a dataju modela onnx wobsahuje. Aplikacija jón do zarjadnika modelow dźěłoweho ruma instaluje.',
    }),
    testMerchant: t({
      ru: 'Проверить продавца',
      en: 'Test merchant',
      kk: 'Сатушыны тексеру',
      de: 'Händler testen',
      fr: 'Tester un marchand',
      es: 'Probar comercio',
      pt: 'Testar estabelecimento',
      tr: 'Satıcıyı test et',
      uk: 'Перевірити продавця',
      zh: '测试商户',
      ar: 'اختبار التاجر',
      pl: 'Testuj sprzedawcę',
      it: 'Prova esercente',
      sk: 'Otestovať obchodníka',
      ja: '加盟店をテスト',
      ko: '가맹점 테스트',
      hi: 'व्यापारी जाँचें',
      nl: 'Handelaar testen',
      sv: 'Testa handlare',
      vi: 'Kiểm tra người bán',
      id: 'Uji merchant',
      da: 'Testforretning',
      nb: 'Testforretning',
      nn: 'Testforretning',
      fi: 'Testikauppa',
      is: 'Prófunarverslun',
      fo: 'Royndarhandil',
      cs: 'Testovací obchodník',
      bg: 'Тестов търговец',
      hr: 'Probni trgovac',
      sr: 'Пробни трговац',
      sl: 'Preizkusni trgovec',
      mk: 'Пробен трговец',
      be: 'Тэставы прадавец',
      bs: 'Probni trgovac',
      hsb: 'Testowy předawar',
    }),
    testing: t({
      ru: 'Проверка...',
      en: 'Testing...',
      kk: 'Тексерілуде...',
      de: 'Wird getestet...',
      fr: 'Test en cours...',
      es: 'Probando...',
      pt: 'Testando...',
      tr: 'Test ediliyor...',
      uk: 'Перевірка...',
      zh: '正在测试...',
      ar: 'جارٍ الاختبار...',
      pl: 'Testowanie...',
      it: 'Test in corso...',
      sk: 'Testuje sa...',
      ja: 'テスト中...',
      ko: '테스트 중...',
      hi: 'जाँच हो रही है...',
      nl: 'Testen...',
      sv: 'Testar...',
      vi: 'Đang kiểm tra...',
      id: 'Menguji...',
      da: 'Tester ...',
      nb: 'Tester ...',
      nn: 'Testar ...',
      fi: 'Testataan ...',
      is: 'Prófa ...',
      fo: 'Royni ...',
      cs: 'Testuje se ...',
      bg: 'Тества се ...',
      hr: 'Testira se ...',
      sr: 'Тестира се ...',
      sl: 'Preizkušanje ...',
      mk: 'Се тестира ...',
      be: 'Тэставанне ...',
      bs: 'Testira se ...',
      hsb: 'Testuje so ...',
    }),
    merchantName: t({
      ru: 'Название продавца',
      en: 'Merchant name',
      kk: 'Сатушы атауы',
      de: 'Händlername',
      fr: 'Nom du marchand',
      es: 'Nombre del comercio',
      pt: 'Nome do estabelecimento',
      tr: 'Satıcı adı',
      uk: 'Назва продавця',
      zh: '商户名称',
      ar: 'اسم التاجر',
      pl: 'Nazwa sprzedawcy',
      it: "Nome dell'esercente",
      sk: 'Názov obchodníka',
      ja: '加盟店名',
      ko: '가맹점 이름',
      hi: 'व्यापारी का नाम',
      nl: 'Naam handelaar',
      sv: 'Handlarens namn',
      vi: 'Tên người bán',
      id: 'Nama merchant',
      da: 'Forretningens navn',
      nb: 'Navn på forretning',
      nn: 'Namn på forretning',
      fi: 'Kaupan nimi',
      is: 'Heiti verslunar',
      fo: 'Navn á handli',
      cs: 'Název obchodníka',
      bg: 'Име на търговеца',
      hr: 'Naziv trgovca',
      sr: 'Назив трговца',
      sl: 'Ime trgovca',
      mk: 'Име на трговецот',
      be: 'Назва прадаўца',
      bs: 'Naziv trgovca',
      hsb: 'Mjeno předawarja',
    }),
    categories: t({
      ru: 'Категории',
      en: 'Categories',
      kk: 'Санаттар',
      de: 'Kategorien',
      fr: 'Catégories',
      es: 'Categorías',
      pt: 'Categorias',
      tr: 'Kategoriler',
      uk: 'Категорії',
      zh: '类别',
      ar: 'الفئات',
      pl: 'Kategorie',
      it: 'Categorie',
      sk: 'Kategórie',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणियाँ',
      nl: 'Categorieën',
      sv: 'Kategorier',
      vi: 'Danh mục',
      id: 'Kategori',
      da: 'Kategorier',
      nb: 'Kategorier',
      nn: 'Kategoriar',
      fi: 'Kategoriat',
      is: 'Kategoríur',
      fo: 'Bólkar',
      cs: 'Kategorie',
      bg: 'Категории',
      hr: 'Kategorije',
      sr: 'Категорије',
      sl: 'Kategorije',
      mk: 'Категории',
      be: 'Катэгорыі',
      bs: 'Kategorije',
      hsb: 'Kategorije',
    }),
    result: t({
      ru: 'Результат: {category}',
      en: 'Result: {category}',
      kk: 'Нәтиже: {category}',
      de: 'Ergebnis: {category}',
      fr: 'Résultat : {category}',
      es: 'Resultado: {category}',
      pt: 'Resultado: {category}',
      tr: 'Sonuç: {category}',
      uk: 'Результат: {category}',
      zh: '结果：{category}',
      ar: 'النتيجة: {category}',
      pl: 'Wynik: {category}',
      it: 'Risultato: {category}',
      sk: 'Výsledok: {category}',
      ja: '結果: {category}',
      ko: '결과: {category}',
      hi: 'परिणाम: {category}',
      nl: 'Resultaat: {category}',
      sv: 'Resultat: {category}',
      vi: 'Kết quả: {category}',
      id: 'Hasil: {category}',
      da: 'Resultat: {category}',
      nb: 'Resultat: {category}',
      nn: 'Resultat: {category}',
      fi: 'Tulos: {category}',
      is: 'Niðurstaða: {category}',
      fo: 'Úrslit: {category}',
      cs: 'Výsledek: {category}',
      bg: 'Резултат: {category}',
      hr: 'Rezultat: {category}',
      sr: 'Резултат: {category}',
      sl: 'Rezultat: {category}',
      mk: 'Резултат: {category}',
      be: 'Вынік: {category}',
      bs: 'Rezultat: {category}',
      hsb: 'Wuslědk: {category}',
    }),
    notDetermined: t({
      ru: 'Не определено',
      en: 'Not determined',
      kk: 'Анықталмады',
      de: 'Nicht bestimmt',
      fr: 'Non déterminé',
      es: 'No determinado',
      pt: 'Não determinado',
      tr: 'Belirlenemedi',
      uk: 'Не визначено',
      zh: '未确定',
      ar: 'غير محدد',
      pl: 'Nie ustalono',
      it: 'Non determinato',
      sk: 'Neurčené',
      ja: '判定できません',
      ko: '확인되지 않음',
      hi: 'निर्धारित नहीं',
      nl: 'Niet bepaald',
      sv: 'Ej fastställd',
      vi: 'Chưa xác định',
      id: 'Tidak ditentukan',
      da: 'Ikke bestemt',
      nb: 'Ikke bestemt',
      nn: 'Ikkje fastsett',
      fi: 'Ei määritetty',
      is: 'Ekki ákvarðað',
      fo: 'Ikki avgjørt',
      cs: 'Neurčeno',
      bg: 'Не е определено',
      hr: 'Nije utvrđeno',
      sr: 'Није утврђено',
      sl: 'Ni določeno',
      mk: 'Не е утврдено',
      be: 'Не вызначана',
      bs: 'Nije utvrđeno',
      hsb: 'Njepostajene',
    }),
    messages: {
      loadFailed: t({
        ru: 'Не удалось загрузить настройки локальной категоризации.',
        en: 'Unable to load local categorization settings.',
        kk: 'Жергілікті санаттау баптауларын жүктеу мүмкін болмады.',
        de: 'Einstellungen der lokalen Kategorisierung konnten nicht geladen werden.',
        fr: 'Impossible de charger les paramètres de catégorisation locale.',
        es: 'No se pudo cargar la configuración de categorización local.',
        pt: 'Não foi possível carregar as configurações de categorização local.',
        tr: 'Yerel kategorilendirme ayarları yüklenemedi.',
        uk: 'Не вдалося завантажити налаштування локальної категоризації.',
        zh: '无法加载本地分类设置。',
        ar: 'تعذّر تحميل إعدادات التصنيف المحلي.',
        pl: 'Nie udało się wczytać ustawień lokalnej kategoryzacji.',
        it: 'Impossibile caricare le impostazioni di categorizzazione locale.',
        sk: 'Nastavenia lokálnej kategorizácie sa nepodarilo načítať.',
        ja: 'ローカル分類の設定を読み込めませんでした。',
        ko: '로컬 분류 설정을 불러올 수 없습니다.',
        hi: 'स्थानीय वर्गीकरण सेटिंग्स लोड नहीं हो सकीं।',
        nl: 'Instellingen voor lokale categorisatie konden niet worden geladen.',
        sv: 'Det gick inte att läsa in inställningarna för lokal kategorisering.',
        vi: 'Không thể tải cài đặt phân loại cục bộ.',
        id: 'Tidak dapat memuat pengaturan kategorisasi lokal.',
        da: 'Indstillingerne for lokal kategorisering kunne ikke indlæses.',
        nb: 'Kunne ikke laste innstillingene for lokal kategorisering.',
        nn: 'Kunne ikkje laste innstillingane for lokal kategorisering.',
        fi: 'Paikallisen luokittelun asetuksia ei voitu ladata.',
        is: 'Ekki var hægt að hlaða stillingar staðbundinnar flokkunar.',
        fo: 'Innstillingarnar fyri staðbundna bólking kundu ikki lesast inn.',
        cs: 'Nastavení lokální kategorizace se nepodařilo načíst.',
        bg: 'Настройките за локално категоризиране не можаха да се заредят.',
        hr: 'Postavke lokalne kategorizacije nije bilo moguće učitati.',
        sr: 'Подешавања локалне категоризације није било могуће учитати.',
        sl: 'Nastavitev lokalnega razvrščanja ni bilo mogoče naložiti.',
        mk: 'Поставките за локално категоризирање не можеа да се вчитаат.',
        be: 'Не ўдалося загрузіць налады лакальнай катэгарызацыі.',
        bs: 'Postavke lokalne kategorizacije nije bilo moguće učitati.',
        hsb: 'Nastajenja lokalneho kategorizowanja njedachu so začitać.',
      }),
      saved: t({
        ru: 'Настройки сохранены.',
        en: 'Settings saved.',
        kk: 'Баптаулар сақталды.',
        de: 'Einstellungen gespeichert.',
        fr: 'Paramètres enregistrés.',
        es: 'Configuración guardada.',
        pt: 'Configurações salvas.',
        tr: 'Ayarlar kaydedildi.',
        uk: 'Налаштування збережено.',
        zh: '设置已保存。',
        ar: 'تم حفظ الإعدادات.',
        pl: 'Ustawienia zapisane.',
        it: 'Impostazioni salvate.',
        sk: 'Nastavenia boli uložené.',
        ja: '設定を保存しました。',
        ko: '설정이 저장되었습니다.',
        hi: 'सेटिंग्स सहेजी गईं।',
        nl: 'Instellingen opgeslagen.',
        sv: 'Inställningarna har sparats.',
        vi: 'Đã lưu cài đặt.',
        id: 'Pengaturan disimpan.',
        da: 'Indstillingerne er gemt.',
        nb: 'Innstillingene er lagret.',
        nn: 'Innstillingane er lagra.',
        fi: 'Asetukset tallennettiin.',
        is: 'Stillingar vistaðar.',
        fo: 'Innstillingarnar eru goymdar.',
        cs: 'Nastavení bylo uloženo.',
        bg: 'Настройките са запазени.',
        hr: 'Postavke su spremljene.',
        sr: 'Подешавања су сачувана.',
        sl: 'Nastavitve so shranjene.',
        mk: 'Поставките се зачувани.',
        be: 'Налады захаваны.',
        bs: 'Postavke su sačuvane.',
        hsb: 'Nastajenja su składowane.',
      }),
      saveFailed: t({
        ru: 'Не удалось сохранить настройки.',
        en: 'Unable to save settings.',
        kk: 'Баптауларды сақтау мүмкін болмады.',
        de: 'Einstellungen konnten nicht gespeichert werden.',
        fr: "Impossible d'enregistrer les paramètres.",
        es: 'No se pudo guardar la configuración.',
        pt: 'Não foi possível salvar as configurações.',
        tr: 'Ayarlar kaydedilemedi.',
        uk: 'Не вдалося зберегти налаштування.',
        zh: '无法保存设置。',
        ar: 'تعذّر حفظ الإعدادات.',
        pl: 'Nie udało się zapisać ustawień.',
        it: 'Impossibile salvare le impostazioni.',
        sk: 'Nastavenia sa nepodarilo uložiť.',
        ja: '設定を保存できませんでした。',
        ko: '설정을 저장할 수 없습니다.',
        hi: 'सेटिंग्स सहेजी नहीं जा सकीं।',
        nl: 'Instellingen konden niet worden opgeslagen.',
        sv: 'Det gick inte att spara inställningarna.',
        vi: 'Không thể lưu cài đặt.',
        id: 'Tidak dapat menyimpan pengaturan.',
        da: 'Indstillingerne kunne ikke gemmes.',
        nb: 'Kunne ikke lagre innstillingene.',
        nn: 'Kunne ikkje lagre innstillingane.',
        fi: 'Asetuksia ei voitu tallentaa.',
        is: 'Ekki var hægt að vista stillingar.',
        fo: 'Innstillingarnar kundu ikki goymast.',
        cs: 'Nastavení se nepodařilo uložit.',
        bg: 'Настройките не можаха да се запазят.',
        hr: 'Postavke nije bilo moguće spremiti.',
        sr: 'Подешавања није било могуће сачувати.',
        sl: 'Nastavitev ni bilo mogoče shraniti.',
        mk: 'Поставките не можеа да се зачуваат.',
        be: 'Не ўдалося захаваць налады.',
        bs: 'Postavke nije bilo moguće sačuvati.',
        hsb: 'Nastajenja njedachu so składować.',
      }),
      modelInstalled: t({
        ru: 'Модель установлена.',
        en: 'Model installed.',
        kk: 'Модель орнатылды.',
        de: 'Modell installiert.',
        fr: 'Modèle installé.',
        es: 'Modelo instalado.',
        pt: 'Modelo instalado.',
        tr: 'Model kuruldu.',
        uk: 'Модель встановлено.',
        zh: '模型已安装。',
        ar: 'تم تثبيت النموذج.',
        pl: 'Model zainstalowany.',
        it: 'Modello installato.',
        sk: 'Model bol nainštalovaný.',
        ja: 'モデルをインストールしました。',
        ko: '모델이 설치되었습니다.',
        hi: 'मॉडल इंस्टॉल हो गया।',
        nl: 'Model geïnstalleerd.',
        sv: 'Modellen har installerats.',
        vi: 'Đã cài đặt mô hình.',
        id: 'Model terpasang.',
        da: 'Modellen er installeret.',
        nb: 'Modellen er installert.',
        nn: 'Modellen er installert.',
        fi: 'Malli asennettiin.',
        is: 'Gerðin var sett upp.',
        fo: 'Mynstrið er innsett.',
        cs: 'Model byl nainstalován.',
        bg: 'Моделът е инсталиран.',
        hr: 'Model je instaliran.',
        sr: 'Модел је инсталиран.',
        sl: 'Model je nameščen.',
        mk: 'Моделот е инсталиран.',
        be: 'Мадэль устаноўлена.',
        bs: 'Model je instaliran.',
        hsb: 'Model je instalowany.',
      }),
      installFailed: t({
        ru: 'Не удалось установить архив модели.',
        en: 'Unable to install model archive.',
        kk: 'Модель мұрағатын орнату мүмкін болмады.',
        de: 'Modellarchiv konnte nicht installiert werden.',
        fr: "Impossible d'installer l'archive du modèle.",
        es: 'No se pudo instalar el archivo del modelo.',
        pt: 'Não foi possível instalar o arquivo do modelo.',
        tr: 'Model arşivi kurulamadı.',
        uk: 'Не вдалося встановити архів моделі.',
        zh: '无法安装模型压缩包。',
        ar: 'تعذّر تثبيت أرشيف النموذج.',
        pl: 'Nie udało się zainstalować archiwum modelu.',
        it: "Impossibile installare l'archivio del modello.",
        sk: 'Archív modelu sa nepodarilo nainštalovať.',
        ja: 'モデルアーカイブをインストールできませんでした。',
        ko: '모델 아카이브를 설치할 수 없습니다.',
        hi: 'मॉडल आर्काइव इंस्टॉल नहीं हो सका।',
        nl: 'Modelarchief kon niet worden geïnstalleerd.',
        sv: 'Det gick inte att installera modellarkivet.',
        vi: 'Không thể cài đặt tệp lưu trữ mô hình.',
        id: 'Tidak dapat memasang arsip model.',
        da: 'Modelarkivet kunne ikke installeres.',
        nb: 'Kunne ikke installere modellarkivet.',
        nn: 'Kunne ikkje installere modellarkivet.',
        fi: 'Malliarkistoa ei voitu asentaa.',
        is: 'Ekki var hægt að setja upp gerðarsafnið.',
        fo: 'Mynsturskjalasavnið kundi ikki setast upp.',
        cs: 'Archiv modelu se nepodařilo nainstalovat.',
        bg: 'Архивът на модела не можа да се инсталира.',
        hr: 'Arhivu modela nije bilo moguće instalirati.',
        sr: 'Архиву модела није било могуће инсталирати.',
        sl: 'Arhiva modela ni bilo mogoče namestiti.',
        mk: 'Архивата на моделот не можеше да се инсталира.',
        be: 'Не ўдалося ўстанавіць архіў мадэлі.',
        bs: 'Arhivu modela nije bilo moguće instalirati.',
        hsb: 'Archiw modela njeda so instalować.',
      }),
      testFailed: t({
        ru: 'Не удалось проверить локальную категоризацию.',
        en: 'Unable to test local categorization.',
        kk: 'Жергілікті санаттауды тексеру мүмкін болмады.',
        de: 'Lokale Kategorisierung konnte nicht getestet werden.',
        fr: 'Impossible de tester la catégorisation locale.',
        es: 'No se pudo probar la categorización local.',
        pt: 'Não foi possível testar a categorização local.',
        tr: 'Yerel kategorilendirme test edilemedi.',
        uk: 'Не вдалося перевірити локальну категоризацію.',
        zh: '无法测试本地分类。',
        ar: 'تعذّر اختبار التصنيف المحلي.',
        pl: 'Nie udało się przetestować lokalnej kategoryzacji.',
        it: 'Impossibile testare la categorizzazione locale.',
        sk: 'Lokálnu kategorizáciu sa nepodarilo otestovať.',
        ja: 'ローカル分類をテストできませんでした。',
        ko: '로컬 분류를 테스트할 수 없습니다.',
        hi: 'स्थानीय वर्गीकरण की जाँच नहीं हो सकी।',
        nl: 'Lokale categorisatie kon niet worden getest.',
        sv: 'Det gick inte att testa lokal kategorisering.',
        vi: 'Không thể kiểm tra phân loại cục bộ.',
        id: 'Tidak dapat menguji kategorisasi lokal.',
        da: 'Den lokale kategorisering kunne ikke testes.',
        nb: 'Kunne ikke teste den lokale kategoriseringen.',
        nn: 'Kunne ikkje teste den lokale kategoriseringa.',
        fi: 'Paikallista luokittelua ei voitu testata.',
        is: 'Ekki var hægt að prófa staðbundna flokkun.',
        fo: 'Staðbundna bólkingin kundi ikki royndast.',
        cs: 'Lokální kategorizaci se nepodařilo otestovat.',
        bg: 'Локалното категоризиране не можа да се тества.',
        hr: 'Lokalnu kategorizaciju nije bilo moguće testirati.',
        sr: 'Локалну категоризацију није било могуће тестирати.',
        sl: 'Lokalnega razvrščanja ni bilo mogoče preizkusiti.',
        mk: 'Локалното категоризирање не можеше да се тестира.',
        be: 'Не ўдалося праверыць лакальную катэгарызацыю.',
        bs: 'Lokalnu kategorizaciju nije bilo moguće testirati.',
        hsb: 'Lokalne kategorizowanje njeda so testować.',
      }),
    },
  },
} satisfies Dictionary;

export default content;
