import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'rowComments',
  content: {
    placeholder: t({
      ru: 'Комментарий к строке',
      en: 'Comment on this row',
      kk: 'Жолға пікір',
      de: 'Kommentar zu dieser Zeile',
      fr: 'Commentaire sur cette ligne',
      es: 'Comentario sobre esta fila',
      pt: 'Comentário sobre esta linha',
      tr: 'Bu satıra yorum',
      uk: 'Коментар до рядка',
      zh: '对此行的评论',
      ar: 'تعليق على هذا الصف',
      pl: 'Komentarz do wiersza',
      it: 'Commento su questa riga',
      sk: 'Komentár k tomuto riadku',
      ja: 'この行へのコメント',
      ko: '이 행에 대한 댓글',
      hi: 'इस पंक्ति पर टिप्पणी',
      nl: 'Opmerking bij deze rij',
      sv: 'Kommentar till raden',
      vi: 'Bình luận cho hàng này',
      id: 'Komentar untuk baris ini',
    }),
    empty: t({
      ru: 'Комментариев пока нет',
      en: 'No comments yet',
      kk: 'Әзірге пікір жоқ',
      de: 'Noch keine Kommentare',
      fr: 'Aucun commentaire pour le moment',
      es: 'Aún no hay comentarios',
      pt: 'Ainda não há comentários',
      tr: 'Henüz yorum yok',
      uk: 'Коментарів поки немає',
      zh: '暂无评论',
      ar: 'لا توجد تعليقات بعد',
      pl: 'Brak komentarzy',
      it: 'Ancora nessun commento',
      sk: 'Zatiaľ žiadne komentáre',
      ja: 'まだコメントはありません',
      ko: '아직 댓글이 없습니다',
      hi: 'अभी तक कोई टिप्पणी नहीं',
      nl: 'Nog geen opmerkingen',
      sv: 'Inga kommentarer ännu',
      vi: 'Chưa có bình luận',
      id: 'Belum ada komentar',
    }),
    addFailed: t({
      ru: 'Не удалось добавить комментарий',
      en: 'Could not add the comment',
      kk: 'Пікір қосу мүмкін болмады',
      de: 'Kommentar konnte nicht hinzugefügt werden',
      fr: 'Impossible d’ajouter le commentaire',
      es: 'No se pudo añadir el comentario',
      pt: 'Não foi possível adicionar o comentário',
      tr: 'Yorum eklenemedi',
      uk: 'Не вдалося додати коментар',
      zh: '无法添加评论',
      ar: 'تعذّر إضافة التعليق',
      pl: 'Nie udało się dodać komentarza',
      it: 'Impossibile aggiungere il commento',
      sk: 'Komentár sa nepodarilo pridať',
      ja: 'コメントを追加できませんでした',
      ko: '댓글을 추가하지 못했습니다',
      hi: 'टिप्पणी नहीं जोड़ी जा सकी',
      nl: 'Kan de opmerking niet toevoegen',
      sv: 'Det gick inte att lägga till kommentaren',
      vi: 'Không thể thêm bình luận',
      id: 'Gagal menambahkan komentar',
    }),
    submit: t({
      ru: 'Отправить',
      en: 'Send',
      kk: 'Жіберу',
      de: 'Senden',
      fr: 'Envoyer',
      es: 'Enviar',
      pt: 'Enviar',
      tr: 'Gönder',
      uk: 'Надіслати',
      zh: '发送',
      ar: 'إرسال',
      pl: 'Wyślij',
      it: 'Invia',
      sk: 'Odoslať',
      ja: '送信',
      ko: '보내기',
      hi: 'भेजें',
      nl: 'Verzenden',
      sv: 'Skicka',
      vi: 'Gửi',
      id: 'Kirim',
    }),
    reopen: t({
      ru: 'Вернуть в работу',
      en: 'Reopen',
      kk: 'Қайта ашу',
      de: 'Wieder öffnen',
      fr: 'Rouvrir',
      es: 'Reabrir',
      pt: 'Reabrir',
      tr: 'Yeniden aç',
      uk: 'Повернути в роботу',
      zh: '重新打开',
      ar: 'إعادة فتح',
      pl: 'Otwórz ponownie',
      it: 'Riapri',
      sk: 'Znovu otvoriť',
      ja: '再開',
      ko: '다시 열기',
      hi: 'फिर से खोलें',
      nl: 'Heropenen',
      sv: 'Återöppna',
      vi: 'Mở lại',
      id: 'Buka kembali',
    }),
    markResolved: t({
      ru: 'Отметить решённым',
      en: 'Mark resolved',
      kk: 'Шешілді деп белгілеу',
      de: 'Als erledigt markieren',
      fr: 'Marquer comme résolu',
      es: 'Marcar como resuelto',
      pt: 'Marcar como resolvido',
      tr: 'Çözüldü olarak işaretle',
      uk: 'Позначити вирішеним',
      zh: '标记为已解决',
      ar: 'وضع علامة كمحلول',
      pl: 'Oznacz jako rozwiązane',
      it: 'Segna come risolto',
      sk: 'Označiť ako vyriešené',
      ja: '解決済みにする',
      ko: '해결됨으로 표시',
      hi: 'हल किया गया चिह्नित करें',
      nl: 'Markeren als opgelost',
      sv: 'Markera som löst',
      vi: 'Đánh dấu đã giải quyết',
      id: 'Tandai selesai',
    }),
  },
} satisfies Dictionary;

export default content;
