import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'invitePage',
  content: {
    invalidLink: t({
      ru: 'Некорректная ссылка приглашения',
      en: 'Invalid invitation link',
      kk: 'Шақыру сілтемесі дұрыс емес',
      de: 'Ungültiger Einladungslink',
      fr: "Lien d'invitation invalide",
      es: 'Enlace de invitación inválido',
      pt: 'Link de convite inválido',
      tr: 'Geçersiz davet bağlantısı',
      uk: 'Некоректне посилання запрошення',
      zh: '无效的邀请链接',
      ar: 'رابط الدعوة غير صالح',
      pl: 'Nieprawidłowy link zaproszenia',
      it: 'Link di invito non valido',
      sk: 'Nieprawidłowy link zaproszenia',
      ja: '無効な招待リンクです',
      ko: '잘못된 초대 링크',
      hi: 'अमान्य आमंत्रण लिंक',
      nl: 'Ongeldige uitnodigingslink',
      sv: 'Ogiltig inbjudningslänk',
      vi: 'Liên kết lời mời không hợp lệ',
      id: 'Tautan undangan tidak valid',
    }),
    title: t({
      ru: 'Приглашение в рабочее пространство',
      en: 'Workspace invitation',
      kk: 'Жұмыс кеңістігіне шақыру',
      de: 'Einladung zum Arbeitsbereich',
      fr: "Invitation à l'espace de travail",
      es: 'Invitación al espacio de trabajo',
      pt: 'Convite para o workspace',
      tr: 'Çalışma alanı daveti',
      uk: 'Запрошення до робочого простору',
      zh: '工作区邀请',
      ar: 'دعوة مساحة العمل',
      pl: 'Zaproszenie do przestrzeni roboczej',
      it: "Invito all'area di lavoro",
      sk: 'Zaproszenie do przestrzeni roboczej',
      ja: 'ワークスペースへの招待',
      ko: '워크스페이스 초대',
      hi: 'कार्यस्थल आमंत्रण',
      nl: 'Uitnodiging voor werkruimte',
      sv: 'Arbetsyta inbjudan',
      vi: 'Lời mời không gian làm việc',
      id: 'Undangan ruang kerja',
    }),
    subtitle: t({
      ru: 'Чтобы принять приглашение, войдите или зарегистрируйтесь под указанным email.',
      en: 'To accept the invitation, log in or sign up with the invited email.',
      kk: 'Шақыруды қабылдау үшін көрсетілген email арқылы кіріңіз немесе тіркеліңіз.',
      de: 'Um die Einladung anzunehmen, melden Sie sich mit der angegebenen E-Mail an oder registrieren Sie sich.',
      fr: "Pour accepter l'invitation, connectez-vous ou inscrivez-vous avec l'e-mail invité.",
      es: 'Para aceptar la invitación, inicia sesión o regístrate con el correo electrónico invitado.',
      pt: 'Para aceitar o convite, faça login ou cadastre-se com o e-mail convidado.',
      tr: 'Daveti kabul etmek için davet edilen e-posta ile giriş yapın veya kaydolun.',
      uk: 'Щоб прийняти запрошення, увійдіть або зареєструйтесь із зазначеним email.',
      zh: '要接受邀请，请使用受邀的电子邮件登录或注册。',
      ar: 'لقبول الدعوة، سجّل الدخول أو أنشئ حسابًا بالبريد الإلكتروني المدعو.',
      pl: 'Aby zaakceptować zaproszenie, zaloguj się lub zarejestruj się podanym adresem e-mail.',
      it: "Per accettare l'invito, accedi o registrati con l'e-mail invitata.",
      sk: 'Aby zaakceptować zaproszenie, zaloguj się lub zarejestruj się podanym adresem e-mail.',
      ja: '招待を受け入れるには、ログインするか、招待されたメールでサインアップします。',
      ko: '초대를 수락하려면 초대된 이메일로 로그인하거나 가입하세요.',
      hi: 'निमंत्रण स्वीकार करने के लिए, लॉग इन करें या आमंत्रित ईमेल से साइन अप करें।',
      nl: 'Om de uitnodiging te accepteren, logt u in of meld u zich aan met de uitgenodigde e-mail.',
      sv: 'För att acceptera inbjudan, logga in eller registrera dig med det inbjudna e-postmeddelandet.',
      vi: 'Để chấp nhận lời mời, hãy đăng nhập hoặc đăng ký bằng email được mời.',
      id: 'Untuk menerima undangan, masuk atau daftar dengan email yang diundang.',
    }),
    details: {
      workspace: t({
        ru: 'Рабочее пространство',
        en: 'Workspace',
        kk: 'Жұмыс кеңістігі',
        de: 'Arbeitsbereich',
        fr: 'Espace de travail',
        es: 'Espacio de trabajo',
        pt: 'Espaço de trabalho',
        tr: 'Çalışma alanı',
        uk: 'Робочий простір',
        zh: '工作区',
        ar: 'مساحة العمل',
        pl: 'Przestrzeń robocza',
        it: 'Area di lavoro',
        sk: 'Przestrzeń robocza',
        ja: 'ワークスペース',
        ko: '작업공간',
        hi: 'कार्यक्षेत्र',
        nl: 'Werkruimte',
        sv: 'Arbetsyta',
        vi: 'Không gian làm việc',
        id: 'Ruang kerja',
      }),
      role: t({
        ru: 'Роль',
        en: 'Role',
        kk: 'Рөл',
        de: 'Rolle',
        fr: 'Rôle',
        es: 'Rol',
        pt: 'Função',
        tr: 'Rol',
        uk: 'Роль',
        zh: '角色',
        ar: 'الدور',
        pl: 'Rola',
        it: 'Ruolo',
        sk: 'Rola',
        ja: '役割',
        ko: '역할',
        hi: 'भूमिका',
        nl: 'Rol',
        sv: 'Roll',
        vi: 'Vai trò',
        id: 'Peran',
      }),
      expiresAt: t({
        ru: 'Действует до',
        en: 'Expires at',
        kk: 'Дейін жарамды',
        de: 'Läuft ab am',
        fr: 'Expire le',
        es: 'Expira el',
        pt: 'Expira em',
        tr: 'Sona erme tarihi',
        uk: 'Діє до',
        zh: '到期时间',
        ar: 'ينتهي في',
        pl: 'Wygasa dnia',
        it: 'Scade il',
        sk: 'Wygasa dnia',
        ja: '有効期限は次のとおりです',
        ko: '만료 시간:',
        hi: 'पर समाप्त होता है',
        nl: 'Verloopt op',
        sv: 'Går ut kl',
        vi: 'Hết hạn vào lúc',
        id: 'Berakhir pada',
      }),
      email: t({
        ru: 'Кому отправлено',
        en: 'Sent to',
        kk: 'Кімге жіберілді',
        de: 'Gesendet an',
        fr: 'Envoyé à',
        es: 'Enviado a',
        pt: 'Enviado para',
        tr: 'Gönderildi',
        uk: 'Кому надіслано',
        zh: '发送至',
        ar: 'أُرسل إلى',
        pl: 'Wysłano do',
        it: 'Inviato a',
        sk: 'Wysłano do',
        ja: '送信先',
        ko: '보낸 사람',
        hi: 'को भेजा गया',
        nl: 'Verzonden naar',
        sv: 'Skickat till',
        vi: 'Đã gửi tới',
        id: 'Dikirim ke',
      }),
    },
    statusMessages: {
      accepted: t({
        ru: 'Это приглашение уже принято.',
        en: 'This invitation has already been accepted.',
        kk: 'Бұл шақыру қабылданған.',
        de: 'Diese Einladung wurde bereits angenommen.',
        fr: 'Cette invitation a déjà été acceptée.',
        es: 'Esta invitación ya ha sido aceptada.',
        pt: 'Este convite já foi aceito.',
        tr: 'Bu davet zaten kabul edildi.',
        uk: 'Це запрошення вже прийнято.',
        zh: '此邀请已被接受。',
        ar: 'تم قبول هذه الدعوة بالفعل.',
        pl: 'To zaproszenie zostało już zaakceptowane.',
        it: 'Questo invito è già stato accettato.',
        sk: 'To zaproszenie zostało już zaakceptowane.',
        ja: 'この招待はすでに受諾されています。',
        ko: '이 초대는 이미 수락되었습니다.',
        hi: 'यह निमंत्रण पहले ही स्वीकार कर लिया गया है.',
        nl: 'Deze uitnodiging is al geaccepteerd.',
        sv: 'Denna inbjudan har redan accepterats.',
        vi: 'Lời mời này đã được chấp nhận.',
        id: 'Undangan ini telah diterima.',
      }),
      expired: t({
        ru: 'Срок действия приглашения истёк.',
        en: 'This invitation has expired.',
        kk: 'Шақырудың мерзімі аяқталды.',
        de: 'Diese Einladung ist abgelaufen.',
        fr: 'Cette invitation a expiré.',
        es: 'Esta invitación ha caducado.',
        pt: 'Este convite expirou.',
        tr: 'Bu davet süresi doldu.',
        uk: 'Термін дії запрошення минув.',
        zh: '此邀请已过期。',
        ar: 'انتهت صلاحية هذه الدعوة.',
        pl: 'To zaproszenie wygasło.',
        it: 'Questo invito è scaduto.',
        sk: 'To zaproszenie wygasło.',
        ja: 'この招待状の有効期限は切れています。',
        ko: '이 초대는 만료되었습니다.',
        hi: 'यह आमंत्रण समाप्त हो गया है.',
        nl: 'Deze uitnodiging is verlopen.',
        sv: 'Denna inbjudan har löpt ut.',
        vi: 'Lời mời này đã hết hạn.',
        id: 'Undangan ini telah kedaluwarsa.',
      }),
      cancelled: t({
        ru: 'Это приглашение было отозвано.',
        en: 'This invitation was revoked.',
        kk: 'Бұл шақыру кері қайтарылды.',
        de: 'Diese Einladung wurde widerrufen.',
        fr: 'Cette invitation a été révoquée.',
        es: 'Esta invitación fue revocada.',
        pt: 'Este convite foi revogado.',
        tr: 'Bu davet iptal edildi.',
        uk: 'Це запрошення було відкликано.',
        zh: '此邀请已被撤销。',
        ar: 'تم إلغاء هذه الدعوة.',
        pl: 'To zaproszenie zostało odwołane.',
        it: 'Questo invito è stato revocato.',
        sk: 'To zaproszenie zostało odwołane.',
        ja: 'この招待は取り消されました。',
        ko: '이 초대는 취소되었습니다.',
        hi: 'यह निमंत्रण रद्द कर दिया गया.',
        nl: 'Deze uitnodiging is ingetrokken.',
        sv: 'Denna inbjudan återkallades.',
        vi: 'Lời mời này đã bị thu hồi.',
        id: 'Undangan ini dicabut.',
      }),
      pending: t({
        ru: 'Приглашение активно.',
        en: 'Invitation is active.',
        kk: 'Шақыру белсенді.',
        de: 'Einladung ist aktiv.',
        fr: "L'invitation est active.",
        es: 'La invitación está activa.',
        pt: 'O convite está ativo.',
        tr: 'Davet aktif.',
        uk: 'Запрошення активне.',
        zh: '邀请处于有效状态。',
        ar: 'الدعوة نشطة.',
        pl: 'Zaproszenie jest aktywne.',
        it: "L'invito è attivo.",
        sk: 'Zaproszenie jest aktywne.',
        ja: '招待はアクティブです。',
        ko: '초대가 활성화되었습니다.',
        hi: 'आमंत्रण सक्रिय है.',
        nl: 'Uitnodiging is actief.',
        sv: 'Inbjudan är aktiv.',
        vi: 'Lời mời đang hoạt động.',
        id: 'Undangan aktif.',
      }),
    },
    actions: {
      login: t({
        ru: 'Войти',
        en: 'Log in',
        kk: 'Кіру',
        de: 'Anmelden',
        fr: 'Se connecter',
        es: 'Iniciar sesión',
        pt: 'Entrar',
        tr: 'Giriş yap',
        uk: 'Увійти',
        zh: '登录',
        ar: 'تسجيل الدخول',
        pl: 'Zaloguj się',
        it: 'Accedi',
        sk: 'Zaloguj się',
        ja: 'ログイン',
        ko: '로그인',
        hi: 'लॉग इन करें',
        nl: 'Inloggen',
        sv: 'Logga in',
        vi: 'Đăng nhập',
        id: 'Masuk',
      }),
      register: t({
        ru: 'Зарегистрироваться',
        en: 'Sign up',
        kk: 'Тіркелу',
        de: 'Registrieren',
        fr: "S'inscrire",
        es: 'Registrarse',
        pt: 'Cadastrar-se',
        tr: 'Kaydol',
        uk: 'Зареєструватися',
        zh: '注册',
        ar: 'إنشاء حساب',
        pl: 'Zarejestruj się',
        it: 'Registrati',
        sk: 'Zarejestruj się',
        ja: 'サインアップ',
        ko: '가입',
        hi: 'साइन अप करें',
        nl: 'Schrijf je in',
        sv: 'Anmäl dig',
        vi: 'Đăng ký',
        id: 'Daftar',
      }),
      accept: t({
        ru: 'Принять приглашение',
        en: 'Accept invitation',
        kk: 'Шақыруды қабылдау',
        de: 'Einladung annehmen',
        fr: "Accepter l'invitation",
        es: 'Aceptar invitación',
        pt: 'Aceitar convite',
        tr: 'Daveti kabul et',
        uk: 'Прийняти запрошення',
        zh: '接受邀请',
        ar: 'قبول الدعوة',
        pl: 'Przyjmij zaproszenie',
        it: 'Accetta invito',
        sk: 'Przyjmij zaproszenie',
        ja: '招待を承諾する',
        ko: '초대 수락',
        hi: 'निमंत्रण स्वीकार करें',
        nl: 'Accepteer de uitnodiging',
        sv: 'Acceptera inbjudan',
        vi: 'Chấp nhận lời mời',
        id: 'Terima undangan',
      }),
      loginAnother: t({
        ru: 'Войти другим аккаунтом',
        en: 'Log in with another account',
        kk: 'Басқа аккаунтпен кіру',
        de: 'Mit einem anderen Konto anmelden',
        fr: 'Se connecter avec un autre compte',
        es: 'Iniciar sesión con otra cuenta',
        pt: 'Entrar com outra conta',
        tr: 'Başka hesapla giriş yap',
        uk: 'Увійти з іншого облікового запису',
        zh: '使用其他账号登录',
        ar: 'تسجيل الدخول بحساب آخر',
        pl: 'Zaloguj się innym kontem',
        it: 'Accedi con un altro account',
        sk: 'Zaloguj się innym kontem',
        ja: '別のアカウントでログインする',
        ko: '다른 계정으로 로그인',
        hi: 'दूसरे खाते से लॉग इन करें',
        nl: 'Log in met een ander account',
        sv: 'Logga in med ett annat konto',
        vi: 'Đăng nhập bằng tài khoản khác',
        id: 'Masuk dengan akun lain',
      }),
      goToApp: t({
        ru: 'Перейти в приложение',
        en: 'Go to app',
        kk: 'Қосымшаға өту',
        de: 'Zur App gehen',
        fr: "Aller à l'application",
        es: 'Ir a la aplicación',
        pt: 'Ir para o app',
        tr: 'Uygulamaya git',
        uk: 'Перейти до додатку',
        zh: '前往应用',
        ar: 'الذهاب إلى التطبيق',
        pl: 'Przejdź do aplikacji',
        it: "Vai all'app",
        sk: 'Przejdź do aplikacji',
        ja: 'アプリに移動',
        ko: '앱으로 이동',
        hi: 'ऐप पर जाएं',
        nl: 'Ga naar app',
        sv: 'Gå till appen',
        vi: 'Đi đến ứng dụng',
        id: 'Buka aplikasi',
      }),
    },
    messages: {
      acceptedFallback: t({
        ru: 'Приглашение принято. Добро пожаловать!',
        en: 'Invitation accepted. Welcome!',
        kk: 'Шақыру қабылданды. Қош келдіңіз!',
        de: 'Einladung angenommen. Willkommen!',
        fr: 'Invitation acceptée. Bienvenue!',
        es: 'Invitación aceptada. ¡Bienvenido!',
        pt: 'Convite aceito. Bem-vindo!',
        tr: 'Davet kabul edildi. Hoş geldiniz!',
        uk: 'Запрошення прийнято. Ласкаво просимо!',
        zh: '邀请已接受。欢迎！',
        ar: 'تم قبول الدعوة. مرحبًا!',
        pl: 'Zaproszenie zaakceptowane. Witamy!',
        it: 'Invito accettato. Benvenuto!',
        sk: 'Zaproszenie zaakceptowane. Witamy!',
        ja: '招待を受け入れました。いらっしゃいませ！',
        ko: '초대가 수락되었습니다. 환영!',
        hi: 'निमंत्रण स्वीकार किया गया. स्वागत!',
        nl: 'Uitnodiging geaccepteerd. Welkom!',
        sv: 'Inbjudan accepterad. Välkomna!',
        vi: 'Lời mời đã được chấp nhận. Chào mừng!',
        id: 'Undangan diterima. Selamat datang!',
      }),
      wrongAccount: t({
        ru: 'Вам нужно войти как',
        en: 'You need to log in as',
        kk: 'Кіру қажет аккаунт',
        de: 'Sie müssen sich anmelden als',
        fr: 'Vous devez vous connecter en tant que',
        es: 'Debes iniciar sesión como',
        pt: 'Você precisa entrar como',
        tr: 'Şu kullanıcı olarak giriş yapmalısınız:',
        uk: 'Вам потрібно увійти як',
        zh: '您需要以以下身份登录',
        ar: 'تحتاج إلى تسجيل الدخول بوصفك',
        pl: 'Musisz zalogować się jako',
        it: 'Devi accedere come',
        sk: 'Musisz zalogować się jako',
        ja: '次のようにログインする必要があります',
        ko: '다음 계정으로 로그인해야 합니다.',
        hi: 'आपको इस रूप में लॉग इन करना होगा',
        nl: 'U dient in te loggen als',
        sv: 'Du måste logga in som',
        vi: 'Bạn cần đăng nhập với tư cách',
        id: 'Anda harus masuk sebagai',
      }),
    },
    errors: {
      loadFailed: t({
        ru: 'Не удалось загрузить приглашение',
        en: 'Failed to load invitation',
        kk: 'Шақыруды жүктеу мүмкін болмады',
        de: 'Einladung konnte nicht geladen werden',
        fr: "Impossible de charger l'invitation",
        es: 'No se pudo cargar la invitación',
        pt: 'Falha ao carregar o convite',
        tr: 'Davet yüklenemedi',
        uk: 'Не вдалося завантажити запрошення',
        zh: '无法加载邀请',
        ar: 'فشل تحميل الدعوة',
        pl: 'Nie udało się załadować zaproszenia',
        it: "Impossibile caricare l'invito",
        sk: 'Nie udało się załadować zaproszenia',
        ja: '招待状を読み込めませんでした',
        ko: '초대장을 로드하지 못했습니다.',
        hi: 'आमंत्रण लोड करने में विफल',
        nl: 'Kan de uitnodiging niet laden',
        sv: 'Det gick inte att läsa in inbjudan',
        vi: 'Không tải được lời mời',
        id: 'Gagal memuat undangan',
      }),
      acceptFailed: t({
        ru: 'Не удалось принять приглашение',
        en: 'Failed to accept invitation',
        kk: 'Шақыруды қабылдау мүмкін болмады',
        de: 'Einladung konnte nicht angenommen werden',
        fr: "Impossible d'accepter l'invitation",
        es: 'No se pudo aceptar la invitación',
        pt: 'Falha ao aceitar o convite',
        tr: 'Davet kabul edilemedi',
        uk: 'Не вдалося прийняти запрошення',
        zh: '无法接受邀请',
        ar: 'فشل قبول الدعوة',
        pl: 'Nie udało się zaakceptować zaproszenia',
        it: "Impossibile accettare l'invito",
        sk: 'Nie udało się zaakceptować zaproszenia',
        ja: '招待を承諾できませんでした',
        ko: '초대를 수락하지 못했습니다.',
        hi: 'निमंत्रण स्वीकार करने में विफल',
        nl: 'Kan de uitnodiging niet accepteren',
        sv: 'Det gick inte att acceptera inbjudan',
        vi: 'Không thể chấp nhận lời mời',
        id: 'Gagal menerima undangan',
      }),
    },
  },
} satisfies Dictionary;

export default content;
