import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'invitePage',
  content: {
    invalidLink: t({
      ru: 'Некорректная ссылка приглашения',
      en: 'Invalid invitation link',
      kk: 'Шақыру сілтемесі дұрыс емес',
      de: 'Ungültiger Einladungslink',
      fr: "Lien d'invitation invalide",
      es: 'Enlace de invitación inválido',
      pt: 'Link de convite inválido',
      tr: 'Geçersiz davet bağlantısı',
      uk: 'Некоректне посилання запрошення',
      zh: '无效的邀请链接',
      ar: 'رابط الدعوة غير صالح',
      pl: 'Nieprawidłowy link zaproszenia',
      it: 'Link di invito non valido',
      sk: 'Nieprawidłowy link zaproszenia',
      ja: 'Invalid invitation link',
      ko: 'Invalid invitation link',
      hi: 'Invalid invitation link',
      nl: 'Invalid invitation link',
      sv: 'Invalid invitation link',
      vi: 'Invalid invitation link',
      id: 'Invalid invitation link',
    }),
    title: t({
      ru: 'Приглашение в рабочее пространство',
      en: 'Workspace invitation',
      kk: 'Жұмыс кеңістігіне шақыру',
      de: 'Einladung zum Arbeitsbereich',
      fr: "Invitation à l'espace de travail",
      es: 'Invitación al espacio de trabajo',
      pt: 'Convite para o workspace',
      tr: 'Çalışma alanı daveti',
      uk: 'Запрошення до робочого простору',
      zh: '工作区邀请',
      ar: 'دعوة مساحة العمل',
      pl: 'Zaproszenie do przestrzeni roboczej',
      it: "Invito all'area di lavoro",
      sk: 'Zaproszenie do przestrzeni roboczej',
      ja: 'Workspace invitation',
      ko: 'Workspace invitation',
      hi: 'Workspace invitation',
      nl: 'Workspace invitation',
      sv: 'Workspace invitation',
      vi: 'Workspace invitation',
      id: 'Workspace invitation',
    }),
    subtitle: t({
      ru: 'Чтобы принять приглашение, войдите или зарегистрируйтесь под указанным email.',
      en: 'To accept the invitation, log in or sign up with the invited email.',
      kk: 'Шақыруды қабылдау үшін көрсетілген email арқылы кіріңіз немесе тіркеліңіз.',
      de: 'Um die Einladung anzunehmen, melden Sie sich mit der angegebenen E-Mail an oder registrieren Sie sich.',
      fr: "Pour accepter l'invitation, connectez-vous ou inscrivez-vous avec l'e-mail invité.",
      es: 'Para aceptar la invitación, inicia sesión o regístrate con el correo electrónico invitado.',
      pt: 'Para aceitar o convite, faça login ou cadastre-se com o e-mail convidado.',
      tr: 'Daveti kabul etmek için davet edilen e-posta ile giriş yapın veya kaydolun.',
      uk: 'Щоб прийняти запрошення, увійдіть або зареєструйтесь із зазначеним email.',
      zh: '要接受邀请，请使用受邀的电子邮件登录或注册。',
      ar: 'لقبول الدعوة، سجّل الدخول أو أنشئ حسابًا بالبريد الإلكتروني المدعو.',
      pl: 'Aby zaakceptować zaproszenie, zaloguj się lub zarejestruj się podanym adresem e-mail.',
      it: "Per accettare l'invito, accedi o registrati con l'e-mail invitata.",
      sk: 'Aby zaakceptować zaproszenie, zaloguj się lub zarejestruj się podanym adresem e-mail.',
      ja: 'To accept the invitation, log in or sign up with the invited email.',
      ko: 'To accept the invitation, log in or sign up with the invited email.',
      hi: 'To accept the invitation, log in or sign up with the invited email.',
      nl: 'To accept the invitation, log in or sign up with the invited email.',
      sv: 'To accept the invitation, log in or sign up with the invited email.',
      vi: 'To accept the invitation, log in or sign up with the invited email.',
      id: 'To accept the invitation, log in or sign up with the invited email.',
    }),
    details: {
      workspace: t({
        ru: 'Рабочее пространство',
        en: 'Workspace',
        kk: 'Workspace',
        de: 'Arbeitsbereich',
        fr: 'Espace de travail',
        es: 'Espacio de trabajo',
        pt: 'Workspace',
        tr: 'Çalışma alanı',
        uk: 'Робочий простір',
        zh: '工作区',
        ar: 'مساحة العمل',
        pl: 'Przestrzeń robocza',
        it: 'Area di lavoro',
        sk: 'Przestrzeń robocza',
        ja: 'Workspace',
        ko: 'Workspace',
        hi: 'Workspace',
        nl: 'Workspace',
        sv: 'Workspace',
        vi: 'Workspace',
        id: 'Workspace',
      }),
      role: t({
        ru: 'Роль',
        en: 'Role',
        kk: 'Рөл',
        de: 'Rolle',
        fr: 'Rôle',
        es: 'Rol',
        pt: 'Função',
        tr: 'Rol',
        uk: 'Роль',
        zh: '角色',
        ar: 'الدور',
        pl: 'Rola',
        it: 'Ruolo',
        sk: 'Rola',
        ja: 'Role',
        ko: 'Role',
        hi: 'Role',
        nl: 'Role',
        sv: 'Role',
        vi: 'Role',
        id: 'Role',
      }),
      expiresAt: t({
        ru: 'Действует до',
        en: 'Expires at',
        kk: 'Дейін жарамды',
        de: 'Läuft ab am',
        fr: 'Expire le',
        es: 'Expira el',
        pt: 'Expira em',
        tr: 'Sona erme tarihi',
        uk: 'Діє до',
        zh: '到期时间',
        ar: 'ينتهي في',
        pl: 'Wygasa dnia',
        it: 'Scade il',
        sk: 'Wygasa dnia',
        ja: 'Expires at',
        ko: 'Expires at',
        hi: 'Expires at',
        nl: 'Expires at',
        sv: 'Expires at',
        vi: 'Expires at',
        id: 'Expires at',
      }),
      email: t({
        ru: 'Кому отправлено',
        en: 'Sent to',
        kk: 'Кімге жіберілді',
        de: 'Gesendet an',
        fr: 'Envoyé à',
        es: 'Enviado a',
        pt: 'Enviado para',
        tr: 'Gönderildi',
        uk: 'Кому надіслано',
        zh: '发送至',
        ar: 'أُرسل إلى',
        pl: 'Wysłano do',
        it: 'Inviato a',
        sk: 'Wysłano do',
        ja: 'Sent to',
        ko: 'Sent to',
        hi: 'Sent to',
        nl: 'Sent to',
        sv: 'Sent to',
        vi: 'Sent to',
        id: 'Sent to',
      }),
    },
    statusMessages: {
      accepted: t({
        ru: 'Это приглашение уже принято.',
        en: 'This invitation has already been accepted.',
        kk: 'Бұл шақыру қабылданған.',
        de: 'Diese Einladung wurde bereits angenommen.',
        fr: 'Cette invitation a déjà été acceptée.',
        es: 'Esta invitación ya ha sido aceptada.',
        pt: 'Este convite já foi aceito.',
        tr: 'Bu davet zaten kabul edildi.',
        uk: 'Це запрошення вже прийнято.',
        zh: '此邀请已被接受。',
        ar: 'تم قبول هذه الدعوة بالفعل.',
        pl: 'To zaproszenie zostało już zaakceptowane.',
        it: 'Questo invito è già stato accettato.',
        sk: 'To zaproszenie zostało już zaakceptowane.',
        ja: 'This invitation has already been accepted.',
        ko: 'This invitation has already been accepted.',
        hi: 'This invitation has already been accepted.',
        nl: 'This invitation has already been accepted.',
        sv: 'This invitation has already been accepted.',
        vi: 'This invitation has already been accepted.',
        id: 'This invitation has already been accepted.',
      }),
      expired: t({
        ru: 'Срок действия приглашения истёк.',
        en: 'This invitation has expired.',
        kk: 'Шақырудың мерзімі аяқталды.',
        de: 'Diese Einladung ist abgelaufen.',
        fr: 'Cette invitation a expiré.',
        es: 'Esta invitación ha caducado.',
        pt: 'Este convite expirou.',
        tr: 'Bu davet süresi doldu.',
        uk: 'Термін дії запрошення минув.',
        zh: '此邀请已过期。',
        ar: 'انتهت صلاحية هذه الدعوة.',
        pl: 'To zaproszenie wygasło.',
        it: 'Questo invito è scaduto.',
        sk: 'To zaproszenie wygasło.',
        ja: 'This invitation has expired.',
        ko: 'This invitation has expired.',
        hi: 'This invitation has expired.',
        nl: 'This invitation has expired.',
        sv: 'This invitation has expired.',
        vi: 'This invitation has expired.',
        id: 'This invitation has expired.',
      }),
      cancelled: t({
        ru: 'Это приглашение было отозвано.',
        en: 'This invitation was revoked.',
        kk: 'Бұл шақыру кері қайтарылды.',
        de: 'Diese Einladung wurde widerrufen.',
        fr: 'Cette invitation a été révoquée.',
        es: 'Esta invitación fue revocada.',
        pt: 'Este convite foi revogado.',
        tr: 'Bu davet iptal edildi.',
        uk: 'Це запрошення було відкликано.',
        zh: '此邀请已被撤销。',
        ar: 'تم إلغاء هذه الدعوة.',
        pl: 'To zaproszenie zostało odwołane.',
        it: 'Questo invito è stato revocato.',
        sk: 'To zaproszenie zostało odwołane.',
        ja: 'This invitation was revoked.',
        ko: 'This invitation was revoked.',
        hi: 'This invitation was revoked.',
        nl: 'This invitation was revoked.',
        sv: 'This invitation was revoked.',
        vi: 'This invitation was revoked.',
        id: 'This invitation was revoked.',
      }),
      pending: t({
        ru: 'Приглашение активно.',
        en: 'Invitation is active.',
        kk: 'Шақыру белсенді.',
        de: 'Einladung ist aktiv.',
        fr: "L'invitation est active.",
        es: 'La invitación está activa.',
        pt: 'O convite está ativo.',
        tr: 'Davet aktif.',
        uk: 'Запрошення активне.',
        zh: '邀请处于有效状态。',
        ar: 'الدعوة نشطة.',
        pl: 'Zaproszenie jest aktywne.',
        it: "L'invito è attivo.",
        sk: 'Zaproszenie jest aktywne.',
        ja: 'Invitation is active.',
        ko: 'Invitation is active.',
        hi: 'Invitation is active.',
        nl: 'Invitation is active.',
        sv: 'Invitation is active.',
        vi: 'Invitation is active.',
        id: 'Invitation is active.',
      }),
    },
    actions: {
      login: t({
        ru: 'Войти',
        en: 'Log in',
        kk: 'Кіру',
        de: 'Anmelden',
        fr: 'Se connecter',
        es: 'Iniciar sesión',
        pt: 'Entrar',
        tr: 'Giriş yap',
        uk: 'Увійти',
        zh: '登录',
        ar: 'تسجيل الدخول',
        pl: 'Zaloguj się',
        it: 'Accedi',
        sk: 'Zaloguj się',
        ja: 'Log in',
        ko: 'Log in',
        hi: 'Log in',
        nl: 'Log in',
        sv: 'Log in',
        vi: 'Log in',
        id: 'Log in',
      }),
      register: t({
        ru: 'Зарегистрироваться',
        en: 'Sign up',
        kk: 'Тіркелу',
        de: 'Registrieren',
        fr: "S'inscrire",
        es: 'Registrarse',
        pt: 'Cadastrar-se',
        tr: 'Kaydol',
        uk: 'Зареєструватися',
        zh: '注册',
        ar: 'إنشاء حساب',
        pl: 'Zarejestruj się',
        it: 'Registrati',
        sk: 'Zarejestruj się',
        ja: 'Sign up',
        ko: 'Sign up',
        hi: 'Sign up',
        nl: 'Sign up',
        sv: 'Sign up',
        vi: 'Sign up',
        id: 'Sign up',
      }),
      accept: t({
        ru: 'Принять приглашение',
        en: 'Accept invitation',
        kk: 'Шақыруды қабылдау',
        de: 'Einladung annehmen',
        fr: "Accepter l'invitation",
        es: 'Aceptar invitación',
        pt: 'Aceitar convite',
        tr: 'Daveti kabul et',
        uk: 'Прийняти запрошення',
        zh: '接受邀请',
        ar: 'قبول الدعوة',
        pl: 'Przyjmij zaproszenie',
        it: 'Accetta invito',
        sk: 'Przyjmij zaproszenie',
        ja: 'Accept invitation',
        ko: 'Accept invitation',
        hi: 'Accept invitation',
        nl: 'Accept invitation',
        sv: 'Accept invitation',
        vi: 'Accept invitation',
        id: 'Accept invitation',
      }),
      loginAnother: t({
        ru: 'Войти другим аккаунтом',
        en: 'Log in with another account',
        kk: 'Басқа аккаунтпен кіру',
        de: 'Mit einem anderen Konto anmelden',
        fr: 'Se connecter avec un autre compte',
        es: 'Iniciar sesión con otra cuenta',
        pt: 'Entrar com outra conta',
        tr: 'Başka hesapla giriş yap',
        uk: 'Увійти з іншого облікового запису',
        zh: '使用其他账号登录',
        ar: 'تسجيل الدخول بحساب آخر',
        pl: 'Zaloguj się innym kontem',
        it: 'Accedi con un altro account',
        sk: 'Zaloguj się innym kontem',
        ja: 'Log in with another account',
        ko: 'Log in with another account',
        hi: 'Log in with another account',
        nl: 'Log in with another account',
        sv: 'Log in with another account',
        vi: 'Log in with another account',
        id: 'Log in with another account',
      }),
      goToApp: t({
        ru: 'Перейти в приложение',
        en: 'Go to app',
        kk: 'Қосымшаға өту',
        de: 'Zur App gehen',
        fr: "Aller à l'application",
        es: 'Ir a la aplicación',
        pt: 'Ir para o app',
        tr: 'Uygulamaya git',
        uk: 'Перейти до додатку',
        zh: '前往应用',
        ar: 'الذهاب إلى التطبيق',
        pl: 'Przejdź do aplikacji',
        it: "Vai all'app",
        sk: 'Przejdź do aplikacji',
        ja: 'Go to app',
        ko: 'Go to app',
        hi: 'Go to app',
        nl: 'Go to app',
        sv: 'Go to app',
        vi: 'Go to app',
        id: 'Go to app',
      }),
    },
    messages: {
      acceptedFallback: t({
        ru: 'Приглашение принято. Добро пожаловать!',
        en: 'Invitation accepted. Welcome!',
        kk: 'Шақыру қабылданды. Қош келдіңіз!',
        de: 'Einladung angenommen. Willkommen!',
        fr: 'Invitation acceptée. Bienvenue!',
        es: 'Invitación aceptada. ¡Bienvenido!',
        pt: 'Convite aceito. Bem-vindo!',
        tr: 'Davet kabul edildi. Hoş geldiniz!',
        uk: 'Запрошення прийнято. Ласкаво просимо!',
        zh: '邀请已接受。欢迎！',
        ar: 'تم قبول الدعوة. مرحبًا!',
        pl: 'Zaproszenie zaakceptowane. Witamy!',
        it: 'Invito accettato. Benvenuto!',
        sk: 'Zaproszenie zaakceptowane. Witamy!',
        ja: 'Invitation accepted. Welcome!',
        ko: 'Invitation accepted. Welcome!',
        hi: 'Invitation accepted. Welcome!',
        nl: 'Invitation accepted. Welcome!',
        sv: 'Invitation accepted. Welcome!',
        vi: 'Invitation accepted. Welcome!',
        id: 'Invitation accepted. Welcome!',
      }),
      wrongAccount: t({
        ru: 'Вам нужно войти как',
        en: 'You need to log in as',
        kk: 'Кіру қажет аккаунт',
        de: 'Sie müssen sich anmelden als',
        fr: 'Vous devez vous connecter en tant que',
        es: 'Debes iniciar sesión como',
        pt: 'Você precisa entrar como',
        tr: 'Şu kullanıcı olarak giriş yapmalısınız:',
        uk: 'Вам потрібно увійти як',
        zh: '您需要以以下身份登录',
        ar: 'تحتاج إلى تسجيل الدخول بوصفك',
        pl: 'Musisz zalogować się jako',
        it: 'Devi accedere come',
        sk: 'Musisz zalogować się jako',
        ja: 'You need to log in as',
        ko: 'You need to log in as',
        hi: 'You need to log in as',
        nl: 'You need to log in as',
        sv: 'You need to log in as',
        vi: 'You need to log in as',
        id: 'You need to log in as',
      }),
    },
    errors: {
      loadFailed: t({
        ru: 'Не удалось загрузить приглашение',
        en: 'Failed to load invitation',
        kk: 'Шақыруды жүктеу мүмкін болмады',
        de: 'Einladung konnte nicht geladen werden',
        fr: "Impossible de charger l'invitation",
        es: 'No se pudo cargar la invitación',
        pt: 'Falha ao carregar o convite',
        tr: 'Davet yüklenemedi',
        uk: 'Не вдалося завантажити запрошення',
        zh: '无法加载邀请',
        ar: 'فشل تحميل الدعوة',
        pl: 'Nie udało się załadować zaproszenia',
        it: "Impossibile caricare l'invito",
        sk: 'Nie udało się załadować zaproszenia',
        ja: 'Failed to load invitation',
        ko: 'Failed to load invitation',
        hi: 'Failed to load invitation',
        nl: 'Failed to load invitation',
        sv: 'Failed to load invitation',
        vi: 'Failed to load invitation',
        id: 'Failed to load invitation',
      }),
      acceptFailed: t({
        ru: 'Не удалось принять приглашение',
        en: 'Failed to accept invitation',
        kk: 'Шақыруды қабылдау мүмкін болмады',
        de: 'Einladung konnte nicht angenommen werden',
        fr: "Impossible d'accepter l'invitation",
        es: 'No se pudo aceptar la invitación',
        pt: 'Falha ao aceitar o convite',
        tr: 'Davet kabul edilemedi',
        uk: 'Не вдалося прийняти запрошення',
        zh: '无法接受邀请',
        ar: 'فشل قبول الدعوة',
        pl: 'Nie udało się zaakceptować zaproszenia',
        it: "Impossibile accettare l'invito",
        sk: 'Nie udało się zaakceptować zaproszenia',
        ja: 'Failed to accept invitation',
        ko: 'Failed to accept invitation',
        hi: 'Failed to accept invitation',
        nl: 'Failed to accept invitation',
        sv: 'Failed to accept invitation',
        vi: 'Failed to accept invitation',
        id: 'Failed to accept invitation',
      }),
    },
  },
} satisfies Dictionary;

export default content;
