import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'customTableDetailPageOperations',
  content: {
    paste: {
      titlePrefix: t({
      ru: 'Вставка ',
      en: 'Paste ',
      kk: 'Қою ',
      zh: 'Paste ',
      de: 'Paste ',
      fr: 'Paste ',
      es: 'Paste ',
      uk: 'Paste ',
      pl: 'Paste ',
      sk: 'Paste ',
      pt: 'Paste ',
      tr: 'Paste ',
      ar: 'Paste ',
      it: 'Paste ',
      ja: 'Paste ',
      ko: 'Paste ',
      hi: 'Paste ',
      nl: 'Paste ',
      sv: 'Paste ',
      vi: 'Paste ',
      id: 'Paste ',
    }),
      titleSuffix: t({
      ru: ' строк',
      en: ' rows',
      kk: ' жол',
      zh: ' rows',
      de: ' rows',
      fr: ' rows',
      es: ' rows',
      uk: ' rows',
      pl: ' rows',
      sk: ' rows',
      pt: ' rows',
      tr: ' rows',
      ar: ' rows',
      it: ' rows',
      ja: ' rows',
      ko: ' rows',
      hi: ' rows',
      nl: ' rows',
      sv: ' rows',
      vi: ' rows',
      id: ' rows',
    }),
      titleFallback: t({
      ru: 'Вставка строк',
      en: 'Paste rows',
      kk: 'Жолдарды қою',
      zh: 'Paste rows',
      de: 'Paste rows',
      fr: 'Paste rows',
      es: 'Paste rows',
      uk: 'Paste rows',
      pl: 'Paste rows',
      sk: 'Paste rows',
      pt: 'Paste rows',
      tr: 'Paste rows',
      ar: 'Paste rows',
      it: 'Paste rows',
      ja: 'Paste rows',
      ko: 'Paste rows',
      hi: 'Paste rows',
      nl: 'Paste rows',
      sv: 'Paste rows',
      vi: 'Paste rows',
      id: 'Paste rows',
    }),
      headersToggle: t({
        ru: 'Первая строка — заголовки',
        en: 'First row is headers',
        kk: 'Бірінші жол — тақырыптар',
        zh: 'First row is headers',
        de: 'First row is headers',
        fr: 'First row is headers',
        es: 'First row is headers',
        uk: 'First row is headers',
        pl: 'First row is headers',
        sk: 'First row is headers',
        pt: 'First row is headers',
        tr: 'First row is headers',
        ar: 'First row is headers',
        it: 'First row is headers',
        ja: 'First row is headers',
        ko: 'First row is headers',
        hi: 'First row is headers',
        nl: 'First row is headers',
        sv: 'First row is headers',
        vi: 'First row is headers',
        id: 'First row is headers',
      }),
      parsing: t({
        ru: 'Подготовка превью...',
        en: 'Preparing preview...',
        kk: 'Алдын ала көру дайындалуда...',
        zh: 'Preparing preview...',
        de: 'Preparing preview...',
        fr: 'Preparing preview...',
        es: 'Preparing preview...',
        uk: 'Preparing preview...',
        pl: 'Preparing preview...',
        sk: 'Preparing preview...',
        pt: 'Preparing preview...',
        tr: 'Preparing preview...',
        ar: 'Preparing preview...',
        it: 'Preparing preview...',
        ja: 'Preparing preview...',
        ko: 'Preparing preview...',
        hi: 'Preparing preview...',
        nl: 'Preparing preview...',
        sv: 'Preparing preview...',
        vi: 'Preparing preview...',
        id: 'Preparing preview...',
      }),
      add: t({
      ru: 'Добавить',
      en: 'Add',
      kk: 'Қосу',
      zh: 'Add',
      de: 'Add',
      fr: 'Add',
      es: 'Add',
      uk: 'Add',
      pl: 'Add',
      sk: 'Add',
      pt: 'Add',
      tr: 'Add',
      ar: 'Add',
      it: 'Add',
      ja: 'Add',
      ko: 'Add',
      hi: 'Add',
      nl: 'Add',
      sv: 'Add',
      vi: 'Add',
      id: 'Add',
    }),
      cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Болдырмау',
      zh: 'Cancel',
      de: 'Cancel',
      fr: 'Cancel',
      es: 'Cancel',
      uk: 'Cancel',
      pl: 'Cancel',
      sk: 'Cancel',
      pt: 'Cancel',
      tr: 'Cancel',
      ar: 'Cancel',
      it: 'Cancel',
      ja: 'Cancel',
      ko: 'Cancel',
      hi: 'Cancel',
      nl: 'Cancel',
      sv: 'Cancel',
      vi: 'Cancel',
      id: 'Cancel',
    }),
      noRows: t({
      ru: 'Нет строк для вставки',
      en: 'No rows to insert',
      kk: 'Қоюға жол жоқ',
      zh: 'No rows to insert',
      de: 'No rows to insert',
      fr: 'No rows to insert',
      es: 'No rows to insert',
      uk: 'No rows to insert',
      pl: 'No rows to insert',
      sk: 'No rows to insert',
      pt: 'No rows to insert',
      tr: 'No rows to insert',
      ar: 'No rows to insert',
      it: 'No rows to insert',
      ja: 'No rows to insert',
      ko: 'No rows to insert',
      hi: 'No rows to insert',
      nl: 'No rows to insert',
      sv: 'No rows to insert',
      vi: 'No rows to insert',
      id: 'No rows to insert',
    }),
      errorsTitle: t({
      ru: 'Есть ошибки',
      en: 'Errors found',
      kk: 'Қателер бар',
      zh: 'Errors found',
      de: 'Errors found',
      fr: 'Errors found',
      es: 'Errors found',
      uk: 'Errors found',
      pl: 'Errors found',
      sk: 'Errors found',
      pt: 'Errors found',
      tr: 'Errors found',
      ar: 'Errors found',
      it: 'Errors found',
      ja: 'Errors found',
      ko: 'Errors found',
      hi: 'Errors found',
      nl: 'Errors found',
      sv: 'Errors found',
      vi: 'Errors found',
      id: 'Errors found',
    }),
      errors: {
        date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      zh: 'Date',
      de: 'Date',
      fr: 'Date',
      es: 'Date',
      uk: 'Date',
      pl: 'Date',
      sk: 'Date',
      pt: 'Date',
      tr: 'Date',
      ar: 'Date',
      it: 'Date',
      ja: 'Date',
      ko: 'Date',
      hi: 'Date',
      nl: 'Date',
      sv: 'Date',
      vi: 'Date',
      id: 'Date',
    }),
        amount: t({
      ru: 'Сумма',
      en: 'Amount',
      kk: 'Сома',
      zh: 'Amount',
      de: 'Amount',
      fr: 'Amount',
      es: 'Amount',
      uk: 'Amount',
      pl: 'Amount',
      sk: 'Amount',
      pt: 'Amount',
      tr: 'Amount',
      ar: 'Amount',
      it: 'Amount',
      ja: 'Amount',
      ko: 'Amount',
      hi: 'Amount',
      nl: 'Amount',
      sv: 'Amount',
      vi: 'Amount',
      id: 'Amount',
    }),
        currency: t({
      ru: 'Валюта',
      en: 'Currency',
      kk: 'Валюта',
      zh: 'Currency',
      de: 'Currency',
      fr: 'Currency',
      es: 'Currency',
      uk: 'Currency',
      pl: 'Currency',
      sk: 'Currency',
      pt: 'Currency',
      tr: 'Currency',
      ar: 'Currency',
      it: 'Currency',
      ja: 'Currency',
      ko: 'Currency',
      hi: 'Currency',
      nl: 'Currency',
      sv: 'Currency',
      vi: 'Currency',
      id: 'Currency',
    }),
        paid: t({
      ru: 'Paid',
      en: 'Paid',
      kk: 'Төленді',
      zh: 'Paid',
      de: 'Paid',
      fr: 'Paid',
      es: 'Paid',
      uk: 'Paid',
      pl: 'Paid',
      sk: 'Paid',
      pt: 'Paid',
      tr: 'Paid',
      ar: 'Paid',
      it: 'Paid',
      ja: 'Paid',
      ko: 'Paid',
      hi: 'Paid',
      nl: 'Paid',
      sv: 'Paid',
      vi: 'Paid',
      id: 'Paid',
    }),
      },
      addedPrefix: t({
      ru: 'Добавлено ',
      en: 'Added ',
      kk: 'Қосылды ',
      zh: 'Added ',
      de: 'Added ',
      fr: 'Added ',
      es: 'Added ',
      uk: 'Added ',
      pl: 'Added ',
      sk: 'Added ',
      pt: 'Added ',
      tr: 'Added ',
      ar: 'Added ',
      it: 'Added ',
      ja: 'Added ',
      ko: 'Added ',
      hi: 'Added ',
      nl: 'Added ',
      sv: 'Added ',
      vi: 'Added ',
      id: 'Added ',
    }),
      addedSuffix: t({
      ru: ' строк',
      en: ' rows',
      kk: ' жол',
      zh: ' rows',
      de: ' rows',
      fr: ' rows',
      es: ' rows',
      uk: ' rows',
      pl: ' rows',
      sk: ' rows',
      pt: ' rows',
      tr: ' rows',
      ar: ' rows',
      it: ' rows',
      ja: ' rows',
      ko: ' rows',
      hi: ' rows',
      nl: ' rows',
      sv: ' rows',
      vi: ' rows',
      id: ' rows',
    }),
      undo: t({
      ru: 'Отменить',
      en: 'Undo',
      kk: 'Болдырмау',
      zh: 'Undo',
      de: 'Undo',
      fr: 'Undo',
      es: 'Undo',
      uk: 'Undo',
      pl: 'Undo',
      sk: 'Undo',
      pt: 'Undo',
      tr: 'Undo',
      ar: 'Undo',
      it: 'Undo',
      ja: 'Undo',
      ko: 'Undo',
      hi: 'Undo',
      nl: 'Undo',
      sv: 'Undo',
      vi: 'Undo',
      id: 'Undo',
    }),
      insertFailed: t({
        ru: 'Не удалось добавить строки',
        en: 'Failed to add rows',
        kk: 'Жолдарды қосу мүмкін болмады',
        zh: 'Failed to add rows',
        de: 'Failed to add rows',
        fr: 'Failed to add rows',
        es: 'Failed to add rows',
        uk: 'Failed to add rows',
        pl: 'Failed to add rows',
        sk: 'Failed to add rows',
        pt: 'Failed to add rows',
        tr: 'Failed to add rows',
        ar: 'Failed to add rows',
        it: 'Failed to add rows',
        ja: 'Failed to add rows',
        ko: 'Failed to add rows',
        hi: 'Failed to add rows',
        nl: 'Failed to add rows',
        sv: 'Failed to add rows',
        vi: 'Failed to add rows',
        id: 'Failed to add rows',
      }),
      undoFailed: t({
        ru: 'Не удалось отменить вставку',
        en: 'Failed to undo insert',
        kk: 'Қоюды болдырмау мүмкін болмады',
        zh: 'Failed to undo insert',
        de: 'Failed to undo insert',
        fr: 'Failed to undo insert',
        es: 'Failed to undo insert',
        uk: 'Failed to undo insert',
        pl: 'Failed to undo insert',
        sk: 'Failed to undo insert',
        pt: 'Failed to undo insert',
        tr: 'Failed to undo insert',
        ar: 'Failed to undo insert',
        it: 'Failed to undo insert',
        ja: 'Failed to undo insert',
        ko: 'Failed to undo insert',
        hi: 'Failed to undo insert',
        nl: 'Failed to undo insert',
        sv: 'Failed to undo insert',
        vi: 'Failed to undo insert',
        id: 'Failed to undo insert',
      }),
      moreRowsPrefix: t({
      ru: 'И ещё ',
      en: 'And ',
      kk: 'Тағы ',
      zh: 'And ',
      de: 'And ',
      fr: 'And ',
      es: 'And ',
      uk: 'And ',
      pl: 'And ',
      sk: 'And ',
      pt: 'And ',
      tr: 'And ',
      ar: 'And ',
      it: 'And ',
      ja: 'And ',
      ko: 'And ',
      hi: 'And ',
      nl: 'And ',
      sv: 'And ',
      vi: 'And ',
      id: 'And ',
    }),
      moreRowsSuffix: t({
      ru: ' строк',
      en: ' more rows',
      kk: ' жол',
      zh: ' more rows',
      de: ' more rows',
      fr: ' more rows',
      es: ' more rows',
      uk: ' more rows',
      pl: ' more rows',
      sk: ' more rows',
      pt: ' more rows',
      tr: ' more rows',
      ar: ' more rows',
      it: ' more rows',
      ja: ' more rows',
      ko: ' more rows',
      hi: ' more rows',
      nl: ' more rows',
      sv: ' more rows',
      vi: ' more rows',
      id: ' more rows',
    }),
      mappingTitle: t({
        ru: 'Сопоставление колонок',
        en: 'Column mapping',
        kk: 'Бағандарды сәйкестендіру',
        zh: 'Column mapping',
        de: 'Column mapping',
        fr: 'Column mapping',
        es: 'Column mapping',
        uk: 'Column mapping',
        pl: 'Column mapping',
        sk: 'Column mapping',
        pt: 'Column mapping',
        tr: 'Column mapping',
        ar: 'Column mapping',
        it: 'Column mapping',
        ja: 'Column mapping',
        ko: 'Column mapping',
        hi: 'Column mapping',
        nl: 'Column mapping',
        sv: 'Column mapping',
        vi: 'Column mapping',
        id: 'Column mapping',
      }),
      mappingIgnore: t({
      ru: 'Не импортировать',
      en: 'Ignore',
      kk: 'Импорттамау',
      zh: 'Ignore',
      de: 'Ignore',
      fr: 'Ignore',
      es: 'Ignore',
      uk: 'Ignore',
      pl: 'Ignore',
      sk: 'Ignore',
      pt: 'Ignore',
      tr: 'Ignore',
      ar: 'Ignore',
      it: 'Ignore',
      ja: 'Ignore',
      ko: 'Ignore',
      hi: 'Ignore',
      nl: 'Ignore',
      sv: 'Ignore',
      vi: 'Ignore',
      id: 'Ignore',
    }),
      mappingNew: t({
      ru: 'Новая колонка',
      en: 'New column',
      kk: 'Жаңа баған',
      zh: 'New column',
      de: 'New column',
      fr: 'New column',
      es: 'New column',
      uk: 'New column',
      pl: 'New column',
      sk: 'New column',
      pt: 'New column',
      tr: 'New column',
      ar: 'New column',
      it: 'New column',
      ja: 'New column',
      ko: 'New column',
      hi: 'New column',
      nl: 'New column',
      sv: 'New column',
      vi: 'New column',
      id: 'New column',
    }),
      mappingNewPlaceholder: t({
      ru: 'Название колонки',
      en: 'Column name',
      kk: 'Баған атауы',
      zh: 'Column name',
      de: 'Column name',
      fr: 'Column name',
      es: 'Column name',
      uk: 'Column name',
      pl: 'Column name',
      sk: 'Column name',
      pt: 'Column name',
      tr: 'Column name',
      ar: 'Column name',
      it: 'Column name',
      ja: 'Column name',
      ko: 'Column name',
      hi: 'Column name',
      nl: 'Column name',
      sv: 'Column name',
      vi: 'Column name',
      id: 'Column name',
    }),
      missingColumnTitle: t({
        ru: 'Укажите название новой колонки',
        en: 'Provide a name for the new column',
        kk: 'Жаңа баған атауын енгізіңіз',
        zh: 'Provide a name for the new column',
        de: 'Provide a name for the new column',
        fr: 'Provide a name for the new column',
        es: 'Provide a name for the new column',
        uk: 'Provide a name for the new column',
        pl: 'Provide a name for the new column',
        sk: 'Provide a name for the new column',
        pt: 'Provide a name for the new column',
        tr: 'Provide a name for the new column',
        ar: 'Provide a name for the new column',
        it: 'Provide a name for the new column',
        ja: 'Provide a name for the new column',
        ko: 'Provide a name for the new column',
        hi: 'Provide a name for the new column',
        nl: 'Provide a name for the new column',
        sv: 'Provide a name for the new column',
        vi: 'Provide a name for the new column',
        id: 'Provide a name for the new column',
      }),
      mappingTypeLabel: t({
      ru: 'Тип',
      en: 'Type',
      kk: 'Түрі',
      zh: 'Type',
      de: 'Type',
      fr: 'Type',
      es: 'Type',
      uk: 'Type',
      pl: 'Type',
      sk: 'Type',
      pt: 'Type',
      tr: 'Type',
      ar: 'Type',
      it: 'Type',
      ja: 'Type',
      ko: 'Type',
      hi: 'Type',
      nl: 'Type',
      sv: 'Type',
      vi: 'Type',
      id: 'Type',
    }),
      defaults: {
        date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      zh: 'Date',
      de: 'Date',
      fr: 'Date',
      es: 'Date',
      uk: 'Date',
      pl: 'Date',
      sk: 'Date',
      pt: 'Date',
      tr: 'Date',
      ar: 'Date',
      it: 'Date',
      ja: 'Date',
      ko: 'Date',
      hi: 'Date',
      nl: 'Date',
      sv: 'Date',
      vi: 'Date',
      id: 'Date',
    }),
        type: t({
      ru: 'Тип',
      en: 'Type',
      kk: 'Түрі',
      zh: 'Type',
      de: 'Type',
      fr: 'Type',
      es: 'Type',
      uk: 'Type',
      pl: 'Type',
      sk: 'Type',
      pt: 'Type',
      tr: 'Type',
      ar: 'Type',
      it: 'Type',
      ja: 'Type',
      ko: 'Type',
      hi: 'Type',
      nl: 'Type',
      sv: 'Type',
      vi: 'Type',
      id: 'Type',
    }),
        amount: t({
      ru: 'Сумма',
      en: 'Amount',
      kk: 'Сома',
      zh: 'Amount',
      de: 'Amount',
      fr: 'Amount',
      es: 'Amount',
      uk: 'Amount',
      pl: 'Amount',
      sk: 'Amount',
      pt: 'Amount',
      tr: 'Amount',
      ar: 'Amount',
      it: 'Amount',
      ja: 'Amount',
      ko: 'Amount',
      hi: 'Amount',
      nl: 'Amount',
      sv: 'Amount',
      vi: 'Amount',
      id: 'Amount',
    }),
        currency: t({
      ru: 'Валюта',
      en: 'Currency',
      kk: 'Валюта',
      zh: 'Currency',
      de: 'Currency',
      fr: 'Currency',
      es: 'Currency',
      uk: 'Currency',
      pl: 'Currency',
      sk: 'Currency',
      pt: 'Currency',
      tr: 'Currency',
      ar: 'Currency',
      it: 'Currency',
      ja: 'Currency',
      ko: 'Currency',
      hi: 'Currency',
      nl: 'Currency',
      sv: 'Currency',
      vi: 'Currency',
      id: 'Currency',
    }),
        comment: t({
      ru: 'Комментарий',
      en: 'Comment',
      kk: 'Түсініктеме',
      zh: 'Comment',
      de: 'Comment',
      fr: 'Comment',
      es: 'Comment',
      uk: 'Comment',
      pl: 'Comment',
      sk: 'Comment',
      pt: 'Comment',
      tr: 'Comment',
      ar: 'Comment',
      it: 'Comment',
      ja: 'Comment',
      ko: 'Comment',
      hi: 'Comment',
      nl: 'Comment',
      sv: 'Comment',
      vi: 'Comment',
      id: 'Comment',
    }),
        paid: t({
      ru: 'Оплачено',
      en: 'Paid',
      kk: 'Төленді',
      zh: 'Paid',
      de: 'Paid',
      fr: 'Paid',
      es: 'Paid',
      uk: 'Paid',
      pl: 'Paid',
      sk: 'Paid',
      pt: 'Paid',
      tr: 'Paid',
      ar: 'Paid',
      it: 'Paid',
      ja: 'Paid',
      ko: 'Paid',
      hi: 'Paid',
      nl: 'Paid',
      sv: 'Paid',
      vi: 'Paid',
      id: 'Paid',
    }),
        columnPrefix: t({
      ru: 'Колонка',
      en: 'Column',
      kk: 'Баған',
      zh: 'Column',
      de: 'Column',
      fr: 'Column',
      es: 'Column',
      uk: 'Column',
      pl: 'Column',
      sk: 'Column',
      pt: 'Column',
      tr: 'Column',
      ar: 'Column',
      it: 'Column',
      ja: 'Column',
      ko: 'Column',
      hi: 'Column',
      nl: 'Column',
      sv: 'Column',
      vi: 'Column',
      id: 'Column',
    }),
      },
    },
    addRow: {
      loading: t({
      ru: 'Добавление строки...',
      en: 'Adding row...',
      kk: 'Жол қосылуда...',
      zh: 'Adding row...',
      de: 'Adding row...',
      fr: 'Adding row...',
      es: 'Adding row...',
      uk: 'Adding row...',
      pl: 'Adding row...',
      sk: 'Adding row...',
      pt: 'Adding row...',
      tr: 'Adding row...',
      ar: 'Adding row...',
      it: 'Adding row...',
      ja: 'Adding row...',
      ko: 'Adding row...',
      hi: 'Adding row...',
      nl: 'Adding row...',
      sv: 'Adding row...',
      vi: 'Adding row...',
      id: 'Adding row...',
    }),
      success: t({
      ru: 'Строка добавлена',
      en: 'Row added',
      kk: 'Жол қосылды',
      zh: 'Row added',
      de: 'Row added',
      fr: 'Row added',
      es: 'Row added',
      uk: 'Row added',
      pl: 'Row added',
      sk: 'Row added',
      pt: 'Row added',
      tr: 'Row added',
      ar: 'Row added',
      it: 'Row added',
      ja: 'Row added',
      ko: 'Row added',
      hi: 'Row added',
      nl: 'Row added',
      sv: 'Row added',
      vi: 'Row added',
      id: 'Row added',
    }),
      failed: t({
        ru: 'Не удалось добавить строку',
        en: 'Failed to add row',
        kk: 'Жол қосу мүмкін болмады',
        zh: 'Failed to add row',
        de: 'Failed to add row',
        fr: 'Failed to add row',
        es: 'Failed to add row',
        uk: 'Failed to add row',
        pl: 'Failed to add row',
        sk: 'Failed to add row',
        pt: 'Failed to add row',
        tr: 'Failed to add row',
        ar: 'Failed to add row',
        it: 'Failed to add row',
        ja: 'Failed to add row',
        ko: 'Failed to add row',
        hi: 'Failed to add row',
        nl: 'Failed to add row',
        sv: 'Failed to add row',
        vi: 'Failed to add row',
        id: 'Failed to add row',
      }),
    },
  },
} satisfies Dictionary;

export default content;
