/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'customTableDetailPageOperations',
  content: {
    paste: {
      titlePrefix: t({
        ru: 'Вставка ',
        en: 'Paste ',
        kk: 'Қою ',
        de: 'Einfügen ',
        fr: 'Coller ',
        es: 'Pegar ',
        pt: 'Colar ',
        tr: 'Yapıştır ',
        uk: 'Вставити ',
        zh: '粘贴 ',
        ar: 'لصق ',
        pl: 'Wklej ',
        it: 'Incolla ',
        sk: 'Vložiť ',
        ja: 'ペースト ',
        ko: '붙여넣기 ',
        hi: 'चिपकाएँ ',
        nl: 'Plakken ',
        sv: 'Klistra in ',
        vi: 'Dán ',
        id: 'Tempel ',
      }),
      titleSuffix: t({
        ru: ' строк',
        en: ' rows',
        kk: ' жол',
        de: ' Reihen',
        fr: ' lignes',
        es: ' filas',
        pt: ' linhas',
        tr: ' satırlar',
        uk: ' рядки',
        zh: ' 行',
        ar: ' صفوف',
        pl: ' rzędy',
        it: ' righe',
        sk: ' riadkov',
        ja: ' 行',
        ko: ' 행',
        hi: ' पंक्तियाँ',
        nl: ' rijen',
        sv: ' rader',
        vi: ' hàng',
        id: ' baris',
      }),
      titleFallback: t({
        ru: 'Вставка строк',
        en: 'Paste rows',
        kk: 'Жолдарды қою',
        de: 'Zeilen einfügen',
        fr: 'Coller les lignes',
        es: 'Pegar filas',
        pt: 'Colar linhas',
        tr: 'Satırları yapıştır',
        uk: 'Вставити рядки',
        zh: '粘贴行',
        ar: 'لصق الصفوف',
        pl: 'Wklej wiersze',
        it: 'Incolla righe',
        sk: 'Prilepiť riadky',
        ja: '行を貼り付ける',
        ko: '행 붙여넣기',
        hi: 'पंक्तियाँ चिपकाएँ',
        nl: 'Rijen plakken',
        sv: 'Klistra in rader',
        vi: 'Dán hàng',
        id: 'Tempel baris',
      }),
      headersToggle: t({
        ru: 'Первая строка — заголовки',
        en: 'First row is headers',
        kk: 'Бірінші жол — тақырыптар',
        de: 'Die erste Zeile enthält Überschriften',
        fr: 'La première ligne correspond aux en-têtes',
        es: 'La primera fila son los encabezados.',
        pt: 'A primeira linha são cabeçalhos',
        tr: 'İlk satır başlıklardır',
        uk: 'Перший рядок - заголовки',
        zh: '第一行是标题',
        ar: 'الصف الأول هو الرؤوس',
        pl: 'Pierwszy wiersz to nagłówki',
        it: 'La prima riga contiene intestazioni',
        sk: 'Prvý riadok sú hlavičky',
        ja: '1行目はヘッダーです',
        ko: '첫 번째 행은 헤더입니다.',
        hi: 'पहली पंक्ति हेडर है',
        nl: 'De eerste rij bestaat uit headers',
        sv: 'Första raden är rubriker',
        vi: 'Hàng đầu tiên là tiêu đề',
        id: 'Baris pertama adalah header',
      }),
      parsing: t({
        ru: 'Подготовка превью...',
        en: 'Preparing preview...',
        kk: 'Алдын ала көру дайындалуда...',
        de: 'Vorschau wird vorbereitet...',
        fr: 'Préparation de l\'aperçu...',
        es: 'Preparando vista previa...',
        pt: 'Preparando visualização...',
        tr: 'Önizleme hazırlanıyor...',
        uk: 'Підготовка попереднього перегляду...',
        zh: '正在准备预览...',
        ar: 'جارٍ تحضير المعاينة...',
        pl: 'Przygotowuję podgląd...',
        it: 'Preparazione dell\'anteprima...',
        sk: 'Pripravuje sa ukážka...',
        ja: 'プレビューを準備しています...',
        ko: '미리보기 준비 중...',
        hi: 'पूर्वावलोकन तैयार किया जा रहा है...',
        nl: 'Voorbeeld voorbereiden...',
        sv: 'Förbereder förhandsvisning...',
        vi: 'Đang chuẩn bị xem trước...',
        id: 'Mempersiapkan pratinjau...',
      }),
      add: t({
        ru: 'Добавить',
        en: 'Add',
        kk: 'Қосу',
        de: 'Hinzufügen',
        fr: 'Ajouter',
        es: 'Añadir',
        pt: 'Adicionar',
        tr: 'Ekle',
        uk: 'додати',
        zh: '添加',
        ar: 'أضف',
        pl: 'Dodaj',
        it: 'Aggiungi',
        sk: 'Pridať',
        ja: '追加',
        ko: '추가',
        hi: 'जोड़ें',
        nl: 'Toevoegen',
        sv: 'Lägg till',
        vi: 'Thêm',
        id: 'Tambahkan',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Zrušiť',
        ja: 'キャンセル',
        ko: '취소',
        hi: 'रद्द करें',
        nl: 'Annuleer',
        sv: 'Avbryt',
        vi: 'Hủy bỏ',
        id: 'Batalkan',
      }),
      noRows: t({
        ru: 'Нет строк для вставки',
        en: 'No rows to insert',
        kk: 'Қоюға жол жоқ',
        de: 'Keine Zeilen zum Einfügen',
        fr: 'Aucune ligne à insérer',
        es: 'No hay filas para insertar',
        pt: 'Nenhuma linha para inserir',
        tr: 'Eklenecek satır yok',
        uk: 'Немає рядків для вставки',
        zh: '没有要插入的行',
        ar: 'لا توجد صفوف لإدراجها',
        pl: 'Brak wierszy do wstawienia',
        it: 'Nessuna riga da inserire',
        sk: 'Žiadne riadky na vloženie',
        ja: '挿入する行がありません',
        ko: '삽입할 행이 없습니다.',
        hi: 'सम्मिलित करने के लिए कोई पंक्तियाँ नहीं',
        nl: 'Er zijn geen rijen om in te voegen',
        sv: 'Inga rader att infoga',
        vi: 'Không có hàng để chèn',
        id: 'Tidak ada baris untuk disisipkan',
      }),
      errorsTitle: t({
        ru: 'Есть ошибки',
        en: 'Errors found',
        kk: 'Қателер бар',
        de: 'Fehler gefunden',
        fr: 'Erreurs trouvées',
        es: 'Errores encontrados',
        pt: 'Erros encontrados',
        tr: 'Bulunan hatalar',
        uk: 'Знайдено помилки',
        zh: '发现错误',
        ar: 'تم العثور على أخطاء',
        pl: 'Znaleziono błędy',
        it: 'Errori rilevati',
        sk: 'Našli sa chyby',
        ja: 'エラーが見つかりました',
        ko: '오류가 발견되었습니다',
        hi: 'त्रुटियाँ पाई गईं',
        nl: 'Fouten gevonden',
        sv: 'Fel hittades',
        vi: 'Đã tìm thấy lỗi',
        id: 'Kesalahan ditemukan',
      }),
      errors: {
        date: t({
          ru: 'Дата',
          en: 'Date',
          kk: 'Күні',
          de: 'Datum',
          fr: 'Date',
          es: 'Fecha',
          pt: 'Data',
          tr: 'Tarih',
          uk: 'Дата',
          zh: '日期',
          ar: 'التاريخ',
          pl: 'Data',
          it: 'Data',
          sk: 'Dátum',
          ja: '日付',
          ko: '날짜',
          hi: 'दिनांक',
          nl: 'Datum',
          sv: 'Datum',
          vi: 'Ngày',
          id: 'Tanggal',
        }),
        amount: t({
          ru: 'Сумма',
          en: 'Amount',
          kk: 'Сома',
          de: 'Betrag',
          fr: 'Montant',
          es: 'Cantidad',
          pt: 'Quantidade',
          tr: 'Tutar',
          uk: 'Сума',
          zh: '金额',
          ar: 'المبلغ',
          pl: 'Kwota',
          it: 'Importo',
          sk: 'Suma',
          ja: '金額',
          ko: '금액',
          hi: 'रकम',
          nl: 'Bedrag',
          sv: 'Belopp',
          vi: 'Số tiền',
          id: 'Jumlah',
        }),
        currency: t({
          ru: 'Валюта',
          en: 'Currency',
          kk: 'Валюта',
          de: 'Währung',
          fr: 'Devise',
          es: 'Moneda',
          pt: 'Moeda',
          tr: 'Para birimi',
          uk: 'Валюта',
          zh: '货币',
          ar: 'العملة',
          pl: 'Waluta',
          it: 'Valuta',
          sk: 'mena',
          ja: '通貨',
          ko: '통화',
          hi: 'मुद्रा',
          nl: 'Valuta',
          sv: 'Valuta',
          vi: 'Tiền tệ',
          id: 'Mata uang',
        }),
        paid: t({
          ru: 'Платный',
          en: 'Paid',
          kk: 'Төленді',
          de: 'Bezahlt',
          fr: 'Payé',
          es: 'Pagado',
          pt: 'Pago',
          tr: 'Ücretli',
          uk: 'Платний',
          zh: '付费',
          ar: 'مدفوعة',
          pl: 'Płatny',
          it: 'Pagato',
          sk: 'Zaplatené',
          ja: '有料',
          ko: '유료',
          hi: 'भुगतान किया गया',
          nl: 'Betaald',
          sv: 'Betalt',
          vi: 'Đã trả tiền',
          id: 'Dibayar',
        }),
      },
      addedPrefix: t({
        ru: 'Добавлено ',
        en: 'Added ',
        kk: 'Қосылды ',
        de: 'Hinzugefügt ',
        fr: 'Ajouté ',
        es: 'Añadido ',
        pt: 'Adicionado ',
        tr: 'Eklendi ',
        uk: 'Додано ',
        zh: '已添加 ',
        ar: 'تمت الإضافة ',
        pl: 'Dodano ',
        it: 'Aggiunto ',
        sk: 'Pridané ',
        ja: '追加されました ',
        ko: '추가됨 ',
        hi: 'जोड़ा गया ',
        nl: 'Toegevoegd ',
        sv: 'Tillagd ',
        vi: 'Đã thêm ',
        id: 'Ditambahkan ',
      }),
      addedSuffix: t({
        ru: ' строк',
        en: ' rows',
        kk: ' жол',
        de: ' Reihen',
        fr: ' lignes',
        es: ' filas',
        pt: ' linhas',
        tr: ' satırlar',
        uk: ' рядки',
        zh: ' 行',
        ar: ' صفوف',
        pl: ' rzędy',
        it: ' righe',
        sk: ' riadkov',
        ja: ' 行',
        ko: ' 행',
        hi: ' पंक्तियाँ',
        nl: ' rijen',
        sv: ' rader',
        vi: ' hàng',
        id: ' baris',
      }),
      undo: t({
        ru: 'Отменить',
        en: 'Undo',
        kk: 'Болдырмау',
        de: 'Rückgängig machen',
        fr: 'Annuler',
        es: 'Deshacer',
        pt: 'Desfazer',
        tr: 'Geri al',
        uk: 'Скасувати',
        zh: '撤消',
        ar: 'تراجع',
        pl: 'Cofnij',
        it: 'Annulla',
        sk: 'Vrátiť späť',
        ja: '元に戻す',
        ko: '실행 취소',
        hi: 'पूर्ववत करें',
        nl: 'Ongedaan maken',
        sv: 'Ångra',
        vi: 'Hoàn tác',
        id: 'Membatalkan',
      }),
      insertFailed: t({
        ru: 'Не удалось добавить строки',
        en: 'Failed to add rows',
        kk: 'Жолдарды қосу мүмкін болмады',
        de: 'Das Hinzufügen von Zeilen ist fehlgeschlagen',
        fr: 'Échec de l\'ajout de lignes',
        es: 'No se pudieron agregar filas',
        pt: 'Falha ao adicionar linhas',
        tr: 'Satır eklenemedi',
        uk: 'Не вдалося додати рядки',
        zh: '添加行失败',
        ar: 'فشلت إضافة صفوف',
        pl: 'Nie udało się dodać wierszy',
        it: 'Impossibile aggiungere righe',
        sk: 'Nepodarilo sa pridať riadky',
        ja: '行の追加に失敗しました',
        ko: '행을 추가하지 못했습니다.',
        hi: 'पंक्तियाँ जोड़ने में विफल',
        nl: 'Kan rijen niet toevoegen',
        sv: 'Det gick inte att lägga till rader',
        vi: 'Không thêm được hàng',
        id: 'Gagal menambahkan baris',
      }),
      undoFailed: t({
        ru: 'Не удалось отменить вставку',
        en: 'Failed to undo insert',
        kk: 'Қоюды болдырмау мүмкін болмады',
        de: 'Einfügung konnte nicht rückgängig gemacht werden',
        fr: 'Échec de l\'annulation de l\'insertion',
        es: 'No se pudo deshacer la inserción',
        pt: 'Falha ao desfazer inserção',
        tr: 'Ekleme işlemi geri alınamadı',
        uk: 'Не вдалося скасувати вставку',
        zh: '撤消插入失败',
        ar: 'فشل التراجع عن الإدراج',
        pl: 'Nie udało się cofnąć wstawienia',
        it: 'Impossibile annullare l\'inserimento',
        sk: 'Vloženie zlyhalo',
        ja: '挿入を元に戻すことができませんでした',
        ko: '삽입을 실행취소하지 못했습니다.',
        hi: 'सम्मिलित करना पूर्ववत करने में विफल',
        nl: 'Kan het invoegen niet ongedaan maken',
        sv: 'Det gick inte att ångra infogningen',
        vi: 'Không thể hoàn tác thao tác chèn',
        id: 'Gagal membatalkan penyisipan',
      }),
      moreRowsPrefix: t({
        ru: 'И ещё ',
        en: 'And ',
        kk: 'Тағы ',
        de: 'Und ',
        fr: 'Et ',
        es: 'y ',
        pt: 'E ',
        tr: 'Ve ',
        uk: 'І ',
        zh: '并且 ',
        ar: 'و ',
        pl: 'I ',
        it: 'E ',
        sk: 'A ',
        ja: 'そして ',
        ko: '그리고 ',
        hi: 'और ',
        nl: 'En ',
        sv: 'Och ',
        vi: 'Và ',
        id: 'Dan ',
      }),
      moreRowsSuffix: t({
        ru: ' строк',
        en: ' more rows',
        kk: ' жол',
        de: ' mehr Reihen',
        fr: ' plus de lignes',
        es: ' más filas',
        pt: ' mais linhas',
        tr: ' daha fazla satır',
        uk: ' більше рядків',
        zh: ' 更多行',
        ar: ' المزيد من الصفوف',
        pl: ' więcej rzędów',
        it: ' più righe',
        sk: ' viac riadkov',
        ja: ' より多くの行',
        ko: ' 더 많은 행',
        hi: ' अधिक पंक्तियाँ',
        nl: ' meer rijen',
        sv: ' fler rader',
        vi: ' nhiều hàng hơn',
        id: ' lebih banyak baris',
      }),
      mappingTitle: t({
        ru: 'Сопоставление колонок',
        en: 'Column mapping',
        kk: 'Бағандарды сәйкестендіру',
        de: 'Spaltenzuordnung',
        fr: 'Mappage de colonnes',
        es: 'Mapeo de columnas',
        pt: 'Mapeamento de coluna',
        tr: 'Sütun eşleme',
        uk: 'Відображення стовпців',
        zh: '列映射',
        ar: 'تعيين العمود',
        pl: 'Mapowanie kolumn',
        it: 'Mappatura delle colonne',
        sk: 'Mapovanie stĺpcov',
        ja: '列のマッピング',
        ko: '열 매핑',
        hi: 'कॉलम मैपिंग',
        nl: 'Kolomtoewijzing',
        sv: 'Kolumnmappning',
        vi: 'Ánh xạ cột',
        id: 'Pemetaan kolom',
      }),
      mappingIgnore: t({
        ru: 'Не импортировать',
        en: 'Ignore',
        kk: 'Импорттамау',
        de: 'Ignorieren',
        fr: 'Ignorer',
        es: 'ignorar',
        pt: 'Ignorar',
        tr: 'Yoksay',
        uk: 'Ігнорувати',
        zh: '忽略',
        ar: 'تجاهل',
        pl: 'Ignoruj',
        it: 'Ignora',
        sk: 'Ignorovať',
        ja: '無視する',
        ko: '무시',
        hi: 'नजरअंदाज करें',
        nl: 'Negeer',
        sv: 'Ignorera',
        vi: 'Bỏ qua',
        id: 'Abaikan',
      }),
      mappingNew: t({
        ru: 'Новая колонка',
        en: 'New column',
        kk: 'Жаңа баған',
        de: 'Neue Kolumne',
        fr: 'Nouvelle colonne',
        es: 'Nueva columna',
        pt: 'Nova coluna',
        tr: 'Yeni sütun',
        uk: 'Нова колонка',
        zh: '新专栏',
        ar: 'عمود جديد',
        pl: 'Nowa kolumna',
        it: 'Nuova rubrica',
        sk: 'Nový stĺpec',
        ja: '新しいコラム',
        ko: '새 열',
        hi: 'नया कॉलम',
        nl: 'Nieuwe kolom',
        sv: 'Ny kolumn',
        vi: 'Cột mới',
        id: 'Kolom baru',
      }),
      mappingNewPlaceholder: t({
        ru: 'Название колонки',
        en: 'Column name',
        kk: 'Баған атауы',
        de: 'Spaltenname',
        fr: 'Nom de la colonne',
        es: 'Nombre de columna',
        pt: 'Nome da coluna',
        tr: 'Sütun adı',
        uk: 'Назва стовпця',
        zh: '栏目名称',
        ar: 'اسم العمود',
        pl: 'Nazwa kolumny',
        it: 'Nome della colonna',
        sk: 'Názov stĺpca',
        ja: '列名',
        ko: '열 이름',
        hi: 'स्तम्भ का नाम',
        nl: 'Kolomnaam',
        sv: 'Kolumnnamn',
        vi: 'Tên cột',
        id: 'Nama kolom',
      }),
      missingColumnTitle: t({
        ru: 'Укажите название новой колонки',
        en: 'Provide a name for the new column',
        kk: 'Жаңа баған атауын енгізіңіз',
        de: 'Geben Sie einen Namen für die neue Spalte ein',
        fr: 'Donnez un nom à la nouvelle colonne',
        es: 'Proporcione un nombre para la nueva columna.',
        pt: 'Forneça um nome para a nova coluna',
        tr: 'Yeni sütun için bir ad girin',
        uk: 'Введіть назву для нового стовпця',
        zh: '为新列提供名称',
        ar: 'توفير اسم للعمود الجديد',
        pl: 'Podaj nazwę nowej kolumny',
        it: 'Fornire un nome per la nuova colonna',
        sk: 'Zadajte názov pre nový stĺpec',
        ja: '新しい列の名前を指定します',
        ko: '새 열의 이름을 입력하세요.',
        hi: 'नए कॉलम के लिए एक नाम प्रदान करें',
        nl: 'Geef een naam op voor de nieuwe kolom',
        sv: 'Ange ett namn för den nya kolumnen',
        vi: 'Đặt tên cho cột mới',
        id: 'Berikan nama untuk kolom baru',
      }),
      mappingTypeLabel: t({
        ru: 'Тип',
        en: 'Type',
        kk: 'Түрі',
        de: 'Typ',
        fr: 'Tapez',
        es: 'Tipo',
        pt: 'Tipo',
        tr: 'Tür',
        uk: 'Тип',
        zh: '类型',
        ar: 'اكتب',
        pl: 'Wpisz',
        it: 'Digitare',
        sk: 'Typ',
        ja: '種類',
        ko: '유형',
        hi: 'प्रकार',
        nl: 'Typ',
        sv: 'Typ',
        vi: 'loại',
        id: 'Ketik',
      }),
      defaults: {
        date: t({
          ru: 'Дата',
          en: 'Date',
          kk: 'Күні',
          de: 'Datum',
          fr: 'Date',
          es: 'Fecha',
          pt: 'Data',
          tr: 'Tarih',
          uk: 'Дата',
          zh: '日期',
          ar: 'التاريخ',
          pl: 'Data',
          it: 'Data',
          sk: 'Dátum',
          ja: '日付',
          ko: '날짜',
          hi: 'दिनांक',
          nl: 'Datum',
          sv: 'Datum',
          vi: 'Ngày',
          id: 'Tanggal',
        }),
        type: t({
          ru: 'Тип',
          en: 'Type',
          kk: 'Түрі',
          de: 'Typ',
          fr: 'Tapez',
          es: 'Tipo',
          pt: 'Tipo',
          tr: 'Tür',
          uk: 'Тип',
          zh: '类型',
          ar: 'اكتب',
          pl: 'Wpisz',
          it: 'Digitare',
          sk: 'Typ',
          ja: '種類',
          ko: '유형',
          hi: 'प्रकार',
          nl: 'Typ',
          sv: 'Typ',
          vi: 'loại',
          id: 'Ketik',
        }),
        amount: t({
          ru: 'Сумма',
          en: 'Amount',
          kk: 'Сома',
          de: 'Betrag',
          fr: 'Montant',
          es: 'Cantidad',
          pt: 'Quantidade',
          tr: 'Tutar',
          uk: 'Сума',
          zh: '金额',
          ar: 'المبلغ',
          pl: 'Kwota',
          it: 'Importo',
          sk: 'Suma',
          ja: '金額',
          ko: '금액',
          hi: 'रकम',
          nl: 'Bedrag',
          sv: 'Belopp',
          vi: 'Số tiền',
          id: 'Jumlah',
        }),
        currency: t({
          ru: 'Валюта',
          en: 'Currency',
          kk: 'Валюта',
          de: 'Währung',
          fr: 'Devise',
          es: 'Moneda',
          pt: 'Moeda',
          tr: 'Para birimi',
          uk: 'Валюта',
          zh: '货币',
          ar: 'العملة',
          pl: 'Waluta',
          it: 'Valuta',
          sk: 'mena',
          ja: '通貨',
          ko: '통화',
          hi: 'मुद्रा',
          nl: 'Valuta',
          sv: 'Valuta',
          vi: 'Tiền tệ',
          id: 'Mata uang',
        }),
        comment: t({
          ru: 'Комментарий',
          en: 'Comment',
          kk: 'Түсініктеме',
          de: 'Kommentar',
          fr: 'Commentaire',
          es: 'Comentario',
          pt: 'Comentário',
          tr: 'Yorum',
          uk: 'коментар',
          zh: '评论',
          ar: 'التعليق',
          pl: 'Komentarz',
          it: 'Commento',
          sk: 'Komentujte',
          ja: 'コメント',
          ko: '댓글',
          hi: 'टिप्पणी करें',
          nl: 'Commentaar',
          sv: 'Kommentera',
          vi: 'Bình luận',
          id: 'Komentar',
        }),
        paid: t({
          ru: 'Оплачено',
          en: 'Paid',
          kk: 'Төленді',
          de: 'Bezahlt',
          fr: 'Payé',
          es: 'Pagado',
          pt: 'Pago',
          tr: 'Ücretli',
          uk: 'Платний',
          zh: '付费',
          ar: 'مدفوعة',
          pl: 'Płatny',
          it: 'Pagato',
          sk: 'Zaplatené',
          ja: '有料',
          ko: '유료',
          hi: 'भुगतान किया गया',
          nl: 'Betaald',
          sv: 'Betalt',
          vi: 'Đã trả tiền',
          id: 'Dibayar',
        }),
        columnPrefix: t({
          ru: 'Колонка',
          en: 'Column',
          kk: 'Баған',
          de: 'Spalte',
          fr: 'Colonne',
          es: 'columna',
          pt: 'Coluna',
          tr: 'Sütun',
          uk: 'Колонка',
          zh: '专栏',
          ar: 'العمود',
          pl: 'Kolumna',
          it: 'Colonna',
          sk: 'Stĺpec',
          ja: 'コラム',
          ko: '칼럼',
          hi: 'स्तम्भ',
          nl: 'Kolom',
          sv: 'Kolumn',
          vi: 'Cột',
          id: 'Kolom',
        }),
      },
    },
    addRow: {
      loading: t({
        ru: 'Добавление строки...',
        en: 'Adding row...',
        kk: 'Жол қосылуда...',
        de: 'Zeile wird hinzugefügt...',
        fr: 'Ajout d\'une ligne...',
        es: 'Agregando fila...',
        pt: 'Adicionando linha...',
        tr: 'Satır ekleniyor...',
        uk: 'Додавання рядка...',
        zh: '添加行...',
        ar: 'جارٍ إضافة صف...',
        pl: 'Dodawanie wiersza...',
        it: 'Aggiunta riga...',
        sk: 'Pridáva sa riadok...',
        ja: '行を追加しています...',
        ko: '행 추가 중...',
        hi: 'पंक्ति जोड़ी जा रही है...',
        nl: 'Rij toevoegen...',
        sv: 'Lägger till rad...',
        vi: 'Đang thêm hàng...',
        id: 'Menambahkan baris...',
      }),
      success: t({
        ru: 'Строка добавлена',
        en: 'Row added',
        kk: 'Жол қосылды',
        de: 'Zeile hinzugefügt',
        fr: 'Ligne ajoutée',
        es: 'Fila agregada',
        pt: 'Linha adicionada',
        tr: 'Satır eklendi',
        uk: 'Рядок додано',
        zh: '添加行',
        ar: 'تمت إضافة الصف',
        pl: 'Dodano wiersz',
        it: 'Riga aggiunta',
        sk: 'Pridaný riadok',
        ja: '行が追加されました',
        ko: '행이 추가됨',
        hi: 'पंक्ति जोड़ी गई',
        nl: 'Rij toegevoegd',
        sv: 'Rad tillagd',
        vi: 'Đã thêm hàng',
        id: 'Baris ditambahkan',
      }),
      failed: t({
        ru: 'Не удалось добавить строку',
        en: 'Failed to add row',
        kk: 'Жол қосу мүмкін болмады',
        de: 'Zeile konnte nicht hinzugefügt werden',
        fr: 'Échec de l\'ajout d\'une ligne',
        es: 'No se pudo agregar la fila',
        pt: 'Falha ao adicionar linha',
        tr: 'Satır eklenemedi',
        uk: 'Не вдалося додати рядок',
        zh: '添加行失败',
        ar: 'فشلت إضافة صف',
        pl: 'Nie udało się dodać wiersza',
        it: 'Impossibile aggiungere la riga',
        sk: 'Nepodarilo sa pridať riadok',
        ja: '行の追加に失敗しました',
        ko: '행을 추가하지 못했습니다.',
        hi: 'पंक्ति जोड़ने में विफल',
        nl: 'Kan rij niet toevoegen',
        sv: 'Det gick inte att lägga till rad',
        vi: 'Không thêm được hàng',
        id: 'Gagal menambahkan baris',
      }),
    },
  },
} satisfies Dictionary;

export default content;
