/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'customTableDetailPageModals',
  content: {
    renameColumn: {
      success: t({
        ru: 'Название колонки обновлено',
        en: 'Column renamed',
        kk: 'Баған атауы жаңартылды',
        de: 'Spalte umbenannt',
        fr: 'Colonne renommée',
        es: 'Columna renombrada',
        pt: 'Coluna renomeada',
        tr: 'Sütun yeniden adlandırıldı',
        uk: 'Стовпець перейменовано',
        zh: '栏目已重命名',
        ar: 'تمت إعادة تسمية العمود',
        pl: 'Zmieniono nazwę kolumny',
        it: 'Colonna rinominata',
        sk: 'Stĺpec bol premenovaný',
        ja: '列の名前が変更されました',
        ko: '열 이름이 변경됨',
        hi: 'कॉलम का नाम बदला गया',
        nl: 'Kolom hernoemd',
        sv: 'Kolumn bytt namn',
        vi: 'Đã đổi tên cột',
        id: 'Kolom diganti namanya',
      }),
      failed: t({
        ru: 'Не удалось переименовать колонку',
        en: 'Failed to rename column',
        kk: 'Баған атын өзгерту мүмкін болмады',
        de: 'Spalte konnte nicht umbenannt werden',
        fr: 'Échec du renommage de la colonne',
        es: 'No se pudo cambiar el nombre de la columna',
        pt: 'Falha ao renomear coluna',
        tr: 'Sütun yeniden adlandırılamadı',
        uk: 'Не вдалося перейменувати стовпець',
        zh: '重命名列失败',
        ar: 'فشلت إعادة تسمية العمود',
        pl: 'Nie udało się zmienić nazwy kolumny',
        it: 'Impossibile rinominare la colonna',
        sk: 'Premenovanie stĺpca zlyhalo',
        ja: '列の名前を変更できませんでした',
        ko: '열 이름을 바꾸지 못했습니다.',
        hi: 'कॉलम का नाम बदलने में विफल',
        nl: 'Kan de naam van de kolom niet wijzigen',
        sv: 'Det gick inte att byta namn på kolumnen',
        vi: 'Không đổi tên được cột',
        id: 'Gagal mengganti nama kolom',
      }),
    },
    deleteColumn: {
      loading: t({
        ru: 'Удаление колонки...',
        en: 'Deleting column...',
        kk: 'Баған жойылуда...',
        de: 'Spalte wird gelöscht...',
        fr: 'Suppression de la colonne...',
        es: 'Eliminando columna...',
        pt: 'Excluindo coluna...',
        tr: 'Sütun siliniyor...',
        uk: 'Видалення стовпця...',
        zh: '正在删除列...',
        ar: 'جارٍ حذف العمود...',
        pl: 'Usuwanie kolumny...',
        it: 'Eliminazione colonna...',
        sk: 'Odstraňuje sa stĺpec...',
        ja: '列を削除しています...',
        ko: '열 삭제 중...',
        hi: 'कॉलम हटाया जा रहा है...',
        nl: 'Kolom verwijderen...',
        sv: 'Raderar kolumn...',
        vi: 'Đang xóa cột...',
        id: 'Menghapus kolom...',
      }),
      success: t({
        ru: 'Колонка удалена',
        en: 'Column deleted',
        kk: 'Баған жойылды',
        de: 'Spalte gelöscht',
        fr: 'Colonne supprimée',
        es: 'Columna eliminada',
        pt: 'Coluna excluída',
        tr: 'Sütun silindi',
        uk: 'Колонку видалено',
        zh: '列已删除',
        ar: 'تم حذف العمود',
        pl: 'Kolumna została usunięta',
        it: 'Colonna eliminata',
        sk: 'Stĺpec bol odstránený',
        ja: '列が削除されました',
        ko: '열이 삭제되었습니다.',
        hi: 'कॉलम हटा दिया गया',
        nl: 'Kolom verwijderd',
        sv: 'Kolumn raderad',
        vi: 'Cột đã bị xóa',
        id: 'Kolom dihapus',
      }),
      failed: t({
        ru: 'Не удалось удалить колонку',
        en: 'Failed to delete column',
        kk: 'Бағанды жою мүмкін болмады',
        de: 'Spalte konnte nicht gelöscht werden',
        fr: 'Échec de la suppression de la colonne',
        es: 'No se pudo eliminar la columna',
        pt: 'Falha ao excluir coluna',
        tr: 'Sütun silinemedi',
        uk: 'Не вдалося видалити стовпець',
        zh: '删除列失败',
        ar: 'فشل حذف العمود',
        pl: 'Nie udało się usunąć kolumny',
        it: 'Impossibile eliminare la colonna',
        sk: 'Stĺpec sa nepodarilo odstrániť',
        ja: '列の削除に失敗しました',
        ko: '열을 삭제하지 못했습니다.',
        hi: 'कॉलम हटाने में विफल',
        nl: 'Kan kolom niet verwijderen',
        sv: 'Det gick inte att ta bort kolumnen',
        vi: 'Không thể xóa cột',
        id: 'Gagal menghapus kolom',
      }),
      confirmTitle: t({
        ru: 'Удалить колонку?',
        en: 'Delete column?',
        kk: 'Бағанды жою керек пе?',
        de: 'Spalte löschen?',
        fr: 'Supprimer la colonne ?',
        es: '¿Eliminar columna?',
        pt: 'Excluir coluna?',
        tr: 'Sütun silinsin mi?',
        uk: 'Видалити стовпець?',
        zh: '删除列？',
        ar: 'هل تريد حذف العمود؟',
        pl: 'Usunąć kolumnę?',
        it: 'Eliminare la colonna?',
        sk: 'Odstrániť stĺpec?',
        ja: '列を削除しますか?',
        ko: '열을 삭제하시겠습니까?',
        hi: 'कॉलम हटाएं?',
        nl: 'Kolom verwijderen?',
        sv: 'Ta bort kolumn?',
        vi: 'Xóa cột?',
        id: 'Hapus kolom?',
      }),
      confirmWithNamePrefix: t({
        ru: 'Колонка "',
        en: 'Column "',
        kk: 'Баған "',
        de: 'Spalte "',
        fr: 'Colonne "',
        es: 'Columna "',
        pt: 'Coluna "',
        tr: 'Sütun "',
        uk: 'Колонка "',
        zh: '专栏》',
        ar: 'العمود "',
        pl: 'Kolumna "',
        it: 'Colonna "',
        sk: 'stĺpec "',
        ja: 'コラム「',
        ko: '칼럼 "',
        hi: 'कॉलम "',
        nl: 'Kolom "',
        sv: 'kolumn "',
        vi: 'Cột "',
        id: 'Kolom "',
      }),
      confirmWithNameSuffix: t({
        ru: '" будет удалена. Значения в строках останутся в данных, но не будут отображаться (пока не добавите колонку снова).',
        en: '" will be deleted. Values will remain in data but won\'t be shown (until you add the column again).',
        kk: '" жойылады. Мәндер деректе қалады, бірақ көрсетілмейді (бағанды қайта қоспайынша).',
        de: '" wird gelöscht. Die Werte bleiben in den Daten erhalten, werden jedoch nicht angezeigt (bis Sie die Spalte erneut hinzufügen).',
        fr: '" sera supprimé. Les valeurs resteront dans les données mais ne seront pas affichées (jusqu\'à ce que vous ajoutiez à nouveau la colonne).',
        es: '"será eliminado. Los valores permanecerán en los datos pero no se mostrarán (hasta que vuelva a agregar la columna).',
        pt: '" será excluído. Os valores permanecerão nos dados, mas não serão mostrados (até que você adicione a coluna novamente).',
        tr: '"silinecek. Değerler verilerde kalacak ancak gösterilmeyecektir (siz sütunu tekrar ekleyene kadar).',
        uk: '" буде видалено. Значення залишаться в даних, але не відображатимуться (доки ви знову не додасте стовпець).',
        zh: '” 将被删除。值将保留在数据中，但不会显示（直到您再次添加列）。',
        ar: '" سيتم حذفه. ستظل القيم موجودة في البيانات ولكن لن يتم عرضها (حتى تقوم بإضافة العمود مرة أخرى).',
        pl: '„zostanie usunięty. Wartości pozostaną w danych, ale nie będą wyświetlane (do czasu ponownego dodania kolumny).',
        it: '" verrà cancellato. I valori rimarranno nei dati ma non verranno visualizzati (finché non aggiungerai nuovamente la colonna).',
        sk: '“ bude odstránený. Hodnoty zostanú v údajoch, ale nezobrazia sa (kým znova nepridáte stĺpec).',
        ja: '」は削除されます。値はデータ内に残りますが、(列を再度追加するまで) 表示されません。',
        ko: '"는 삭제됩니다. 값은 데이터에 남아 있지만 표시되지 않습니다(열을 다시 추가할 때까지).',
        hi: '"हटा दिया जाएगा. मान डेटा में बने रहेंगे लेकिन दिखाए नहीं जाएंगे (जब तक आप कॉलम दोबारा नहीं जोड़ते)।',
        nl: '" zal worden verwijderd. Waarden blijven in de gegevens staan, maar worden niet weergegeven (totdat u de kolom opnieuw toevoegt).',
        sv: '" kommer att raderas. Värden kommer att finnas kvar i data men kommer inte att visas (förrän du lägger till kolumnen igen).',
        vi: '" sẽ bị xóa. Các giá trị sẽ vẫn còn trong dữ liệu nhưng sẽ không được hiển thị (cho đến khi bạn thêm lại cột).',
        id: '" akan dihapus. Nilai akan tetap ada dalam data tetapi tidak akan ditampilkan (sampai Anda menambahkan kolom lagi).',
      }),
      confirmNoName: t({
        ru: 'Колонка будет удалена.',
        en: 'Column will be deleted.',
        kk: 'Баған жойылады.',
        de: 'Spalte wird gelöscht.',
        fr: 'La colonne sera supprimée.',
        es: 'La columna será eliminada.',
        pt: 'A coluna será excluída.',
        tr: 'Sütun silinecek.',
        uk: 'Стовпець буде видалено.',
        zh: '列将被删除。',
        ar: 'سيتم حذف العمود.',
        pl: 'Kolumna zostanie usunięta.',
        it: 'La colonna verrà eliminata.',
        sk: 'Stĺpec bude vymazaný.',
        ja: '列が削除されます。',
        ko: '열이 삭제됩니다.',
        hi: 'कॉलम हटा दिया जाएगा.',
        nl: 'Kolom wordt verwijderd.',
        sv: 'Kolumnen kommer att raderas.',
        vi: 'Cột sẽ bị xóa.',
        id: 'Kolom akan dihapus.',
      }),
      confirm: t({
        ru: 'Удалить',
        en: 'Delete',
        kk: 'Жою',
        de: 'Löschen',
        fr: 'Supprimer',
        es: 'Eliminar',
        pt: 'Excluir',
        tr: 'Sil',
        uk: 'Видалити',
        zh: '删除',
        ar: 'حذف',
        pl: 'Usuń',
        it: 'Elimina',
        sk: 'Odstrániť',
        ja: '削除',
        ko: '삭제',
        hi: 'हटाएँ',
        nl: 'Verwijderen',
        sv: 'Ta bort',
        vi: 'Xóa',
        id: 'Hapus',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Zrušiť',
        ja: 'キャンセル',
        ko: '취소',
        hi: 'रद्द करें',
        nl: 'Annuleer',
        sv: 'Avbryt',
        vi: 'Hủy bỏ',
        id: 'Batalkan',
      }),
    },
    deleteRow: {
      loading: t({
        ru: 'Удаление строки...',
        en: 'Deleting row...',
        kk: 'Жол жойылуда...',
        de: 'Zeile wird gelöscht...',
        fr: 'Suppression de la ligne...',
        es: 'Eliminando fila...',
        pt: 'Excluindo linha...',
        tr: 'Satır siliniyor...',
        uk: 'Видалення рядка...',
        zh: '正在删除行...',
        ar: 'جارٍ حذف الصف...',
        pl: 'Usuwanie wiersza...',
        it: 'Eliminazione riga...',
        sk: 'Odstraňuje sa riadok...',
        ja: '行を削除しています...',
        ko: '행 삭제 중...',
        hi: 'पंक्ति हटाई जा रही है...',
        nl: 'Rij verwijderen...',
        sv: 'Raderar rad...',
        vi: 'Đang xóa hàng...',
        id: 'Menghapus baris...',
      }),
      success: t({
        ru: 'Строка удалена',
        en: 'Row deleted',
        kk: 'Жол жойылды',
        de: 'Zeile gelöscht',
        fr: 'Ligne supprimée',
        es: 'Fila eliminada',
        pt: 'Linha excluída',
        tr: 'Satır silindi',
        uk: 'Рядок видалено',
        zh: '行已删除',
        ar: 'تم حذف الصف',
        pl: 'Wiersz usunięty',
        it: 'Riga eliminata',
        sk: 'Riadok bol odstránený',
        ja: '行が削除されました',
        ko: '행이 삭제되었습니다.',
        hi: 'पंक्ति हटा दी गई',
        nl: 'Rij verwijderd',
        sv: 'Rad raderad',
        vi: 'Đã xóa hàng',
        id: 'Baris dihapus',
      }),
      failed: t({
        ru: 'Не удалось удалить строку',
        en: 'Failed to delete row',
        kk: 'Жолды жою мүмкін болмады',
        de: 'Zeile konnte nicht gelöscht werden',
        fr: 'Échec de la suppression de la ligne',
        es: 'No se pudo eliminar la fila',
        pt: 'Falha ao excluir linha',
        tr: 'Satır silinemedi',
        uk: 'Не вдалося видалити рядок',
        zh: '删除行失败',
        ar: 'فشل حذف الصف',
        pl: 'Nie udało się usunąć wiersza',
        it: 'Impossibile eliminare la riga',
        sk: 'Nepodarilo sa odstrániť riadok',
        ja: '行の削除に失敗しました',
        ko: '행을 삭제하지 못했습니다.',
        hi: 'पंक्ति हटाने में विफल',
        nl: 'Kan rij niet verwijderen',
        sv: 'Det gick inte att ta bort raden',
        vi: 'Không thể xóa hàng',
        id: 'Gagal menghapus baris',
      }),
      confirmTitle: t({
        ru: 'Удалить строку?',
        en: 'Delete row?',
        kk: 'Жолды жою керек пе?',
        de: 'Zeile löschen?',
        fr: 'Supprimer la ligne ?',
        es: '¿Eliminar fila?',
        pt: 'Excluir linha?',
        tr: 'Satır silinsin mi?',
        uk: 'Видалити рядок?',
        zh: '删除行？',
        ar: 'هل تريد حذف الصف؟',
        pl: 'Usunąć wiersz?',
        it: 'Eliminare la riga?',
        sk: 'Odstrániť riadok?',
        ja: '行を削除しますか?',
        ko: '행을 삭제하시겠습니까?',
        hi: 'पंक्ति हटाएँ?',
        nl: 'Rij verwijderen?',
        sv: 'Ta bort rad?',
        vi: 'Xóa hàng?',
        id: 'Hapus baris?',
      }),
      confirmWithNumberPrefix: t({
        ru: 'Строка #',
        en: 'Row #',
        kk: 'Жол #',
        de: 'Zeile Nr.',
        fr: 'Numéro de ligne',
        es: 'Fila #',
        pt: 'Linha #',
        tr: 'Satır #',
        uk: 'рядок #',
        zh: '行号',
        ar: 'الصف #',
        pl: 'Wiersz #',
        it: 'Riga n.',
        sk: 'riadok č.',
        ja: '行番号',
        ko: '행 #',
        hi: 'पंक्ति #',
        nl: 'Rij #',
        sv: 'rad #',
        vi: 'Hàng #',
        id: 'Baris #',
      }),
      confirmWithNumberSuffix: t({
        ru: ' будет удалена.',
        en: ' will be deleted.',
        kk: ' жойылады.',
        de: ' wird gelöscht.',
        fr: ' sera supprimé.',
        es: ' será eliminado.',
        pt: ' será excluído.',
        tr: ' silinecek.',
        uk: ' буде видалено.',
        zh: ' 将被删除。',
        ar: ' سيتم حذفها.',
        pl: ' zostaną usunięte.',
        it: ' verrà eliminato.',
        sk: ' budú odstránené.',
        ja: ' 削除されます。',
        ko: ' 삭제됩니다.',
        hi: ' हटा दिया जाएगा.',
        nl: ' zal worden verwijderd.',
        sv: ' kommer att raderas.',
        vi: ' sẽ bị xóa.',
        id: ' akan dihapus.',
      }),
      confirmNoNumber: t({
        ru: 'Строка будет удалена.',
        en: 'Row will be deleted.',
        kk: 'Жол жойылады.',
        de: 'Zeile wird gelöscht.',
        fr: 'La ligne sera supprimée.',
        es: 'Se eliminará la fila.',
        pt: 'A linha será excluída.',
        tr: 'Satır silinecek.',
        uk: 'Рядок буде видалено.',
        zh: '行将被删除。',
        ar: 'سيتم حذف الصف.',
        pl: 'Wiersz zostanie usunięty.',
        it: 'La riga verrà eliminata.',
        sk: 'Riadok bude odstránený.',
        ja: '行が削除されます。',
        ko: '행이 삭제됩니다.',
        hi: 'पंक्ति हटा दी जाएगी.',
        nl: 'Rij wordt verwijderd.',
        sv: 'Raden kommer att raderas.',
        vi: 'Hàng sẽ bị xóa.',
        id: 'Baris akan dihapus.',
      }),
      confirm: t({
        ru: 'Удалить',
        en: 'Delete',
        kk: 'Жою',
        de: 'Löschen',
        fr: 'Supprimer',
        es: 'Eliminar',
        pt: 'Excluir',
        tr: 'Sil',
        uk: 'Видалити',
        zh: '删除',
        ar: 'حذف',
        pl: 'Usuń',
        it: 'Elimina',
        sk: 'Odstrániť',
        ja: '削除',
        ko: '삭제',
        hi: 'हटाएँ',
        nl: 'Verwijderen',
        sv: 'Ta bort',
        vi: 'Xóa',
        id: 'Hapus',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Zrušiť',
        ja: 'キャンセル',
        ko: '취소',
        hi: 'रद्द करें',
        nl: 'Annuleer',
        sv: 'Avbryt',
        vi: 'Hủy bỏ',
        id: 'Batalkan',
      }),
    },
    bulkDeleteRows: {
      loading: t({
        ru: 'Удаление строк...',
        en: 'Deleting rows...',
        kk: 'Жолдар жойылуда...',
        de: 'Zeilen werden gelöscht...',
        fr: 'Suppression de lignes...',
        es: 'Eliminando filas...',
        pt: 'Excluindo linhas...',
        tr: 'Satırlar siliniyor...',
        uk: 'Видалення рядків...',
        zh: '正在删除行...',
        ar: 'جارٍ حذف الصفوف...',
        pl: 'Usuwanie wierszy...',
        it: 'Eliminazione righe...',
        sk: 'Odstraňujú sa riadky...',
        ja: '行を削除しています...',
        ko: '행 삭제 중...',
        hi: 'पंक्तियाँ हटाई जा रही हैं...',
        nl: 'Rijen verwijderen...',
        sv: 'Raderar rader...',
        vi: 'Đang xóa hàng...',
        id: 'Menghapus baris...',
      }),
      success: t({
        ru: 'Строки удалены',
        en: 'Rows deleted',
        kk: 'Жолдар жойылды',
        de: 'Zeilen gelöscht',
        fr: 'Lignes supprimées',
        es: 'Filas eliminadas',
        pt: 'Linhas excluídas',
        tr: 'Satırlar silindi',
        uk: 'Рядки видалено',
        zh: '已删除行',
        ar: 'تم حذف الصفوف',
        pl: 'Wiersze usunięte',
        it: 'Righe cancellate',
        sk: 'Riadky boli odstránené',
        ja: '削除された行',
        ko: '삭제된 행',
        hi: 'पंक्तियाँ हटा दी गईं',
        nl: 'Rijen verwijderd',
        sv: 'Rader raderade',
        vi: 'Đã xóa hàng',
        id: 'Baris dihapus',
      }),
      failed: t({
        ru: 'Не удалось удалить некоторые строки',
        en: 'Failed to delete some rows',
        kk: 'Кейбір жолдарды жою мүмкін болмады',
        de: 'Einige Zeilen konnten nicht gelöscht werden',
        fr: 'Échec de la suppression de certaines lignes',
        es: 'No se pudieron eliminar algunas filas',
        pt: 'Falha ao excluir algumas linhas',
        tr: 'Bazı satırlar silinemedi',
        uk: 'Не вдалося видалити деякі рядки',
        zh: '删除某些行失败',
        ar: 'فشل في حذف بعض الصفوف',
        pl: 'Nie udało się usunąć niektórych wierszy',
        it: 'Impossibile eliminare alcune righe',
        sk: 'Niektoré riadky sa nepodarilo odstrániť',
        ja: '一部の行の削除に失敗しました',
        ko: '일부 행을 삭제하지 못했습니다.',
        hi: 'कुछ पंक्तियाँ हटाने में विफल',
        nl: 'Kan sommige rijen niet verwijderen',
        sv: 'Det gick inte att ta bort några rader',
        vi: 'Không thể xóa một số hàng',
        id: 'Gagal menghapus beberapa baris',
      }),
      confirmTitle: t({
        ru: 'Удалить строки?',
        en: 'Delete rows?',
        kk: 'Жолдарды жою керек пе?',
        de: 'Zeilen löschen?',
        fr: 'Supprimer des lignes ?',
        es: '¿Eliminar filas?',
        pt: 'Excluir linhas?',
        tr: 'Satırları silmek istiyor musunuz?',
        uk: 'Видалити рядки?',
        zh: '删除行？',
        ar: 'هل تريد حذف الصفوف؟',
        pl: 'Usunąć wiersze?',
        it: 'Eliminare righe?',
        sk: 'Odstrániť riadky?',
        ja: '行を削除しますか?',
        ko: '행을 삭제하시겠습니까?',
        hi: 'पंक्तियाँ हटाएँ?',
        nl: 'Rijen verwijderen?',
        sv: 'Ta bort rader?',
        vi: 'Xóa hàng?',
        id: 'Hapus baris?',
      }),
      confirmMessagePrefix: t({
        ru: 'Будут удалены ',
        en: 'Delete ',
        kk: 'Жойылады ',
        de: 'Löschen ',
        fr: 'Supprimer ',
        es: 'Eliminar ',
        pt: 'Excluir ',
        tr: 'Sil ',
        uk: 'Видалити ',
        zh: '删除 ',
        ar: 'حذف ',
        pl: 'Usuń ',
        it: 'Elimina ',
        sk: 'Odstrániť ',
        ja: '削除 ',
        ko: '삭제 ',
        hi: 'हटाएँ ',
        nl: 'Verwijderen ',
        sv: 'Ta bort ',
        vi: 'Xóa ',
        id: 'Hapus ',
      }),
      confirmMessageSuffix: t({
        ru: ' выбранных строк.',
        en: ' selected rows?',
        kk: ' таңдалған жол.',
        de: ' ausgewählte Zeilen?',
        fr: ' lignes sélectionnées ?',
        es: ' filas seleccionadas?',
        pt: ' linhas selecionadas?',
        tr: ' seçilen satırlar?',
        uk: ' вибрані рядки?',
        zh: ' 选定的行？',
        ar: ' الصفوف المختارة؟',
        pl: ' wybrane wiersze?',
        it: ' righe selezionate?',
        sk: ' vybrané riadky?',
        ja: ' 選択された行?',
        ko: ' 선택한 행?',
        hi: ' चयनित पंक्तियाँ?',
        nl: ' geselecteerde rijen?',
        sv: ' valda rader?',
        vi: ' hàng đã chọn?',
        id: ' baris yang dipilih?',
      }),
      confirm: t({
        ru: 'Удалить',
        en: 'Delete',
        kk: 'Жою',
        de: 'Löschen',
        fr: 'Supprimer',
        es: 'Eliminar',
        pt: 'Excluir',
        tr: 'Sil',
        uk: 'Видалити',
        zh: '删除',
        ar: 'حذف',
        pl: 'Usuń',
        it: 'Elimina',
        sk: 'Odstrániť',
        ja: '削除',
        ko: '삭제',
        hi: 'हटाएँ',
        nl: 'Verwijderen',
        sv: 'Ta bort',
        vi: 'Xóa',
        id: 'Hapus',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Zrušiť',
        ja: 'キャンセル',
        ko: '취소',
        hi: 'रद्द करें',
        nl: 'Annuleer',
        sv: 'Avbryt',
        vi: 'Hủy bỏ',
        id: 'Batalkan',
      }),
    },
    columnIcon: {
      uploaded: t({
        ru: 'Иконка загружена',
        en: 'Icon uploaded',
        kk: 'Иконка жүктелді',
        de: 'Symbol hochgeladen',
        fr: 'Icône téléchargée',
        es: 'Icono subido',
        pt: 'Ícone enviado',
        tr: 'Simge yüklendi',
        uk: 'Значок завантажено',
        zh: '图标已上传',
        ar: 'تم تحميل الأيقونة',
        pl: 'Ikona przesłana',
        it: 'Icona caricata',
        sk: 'Ikona bola nahraná',
        ja: 'アイコンがアップロードされました',
        ko: '아이콘이 업로드되었습니다.',
        hi: 'आइकन अपलोड किया गया',
        nl: 'Pictogram geüpload',
        sv: 'Ikon uppladdad',
        vi: 'Biểu tượng đã được tải lên',
        id: 'Ikon diunggah',
      }),
      uploadFailed: t({
        ru: 'Не удалось загрузить иконку',
        en: 'Failed to upload icon',
        kk: 'Иконканы жүктеу мүмкін болмады',
        de: 'Symbol konnte nicht hochgeladen werden',
        fr: 'Échec du téléchargement de l\'icône',
        es: 'No se pudo cargar el ícono',
        pt: 'Falha ao carregar o ícone',
        tr: 'Simge yüklenemedi',
        uk: 'Не вдалося завантажити значок',
        zh: '图标上传失败',
        ar: 'فشل تحميل الأيقونة',
        pl: 'Nie udało się przesłać ikony',
        it: 'Impossibile caricare l\'icona',
        sk: 'Ikonu sa nepodarilo odovzdať',
        ja: 'アイコンのアップロードに失敗しました',
        ko: '아이콘을 업로드하지 못했습니다.',
        hi: 'आइकन अपलोड करने में विफल',
        nl: 'Kan het pictogram niet uploaden',
        sv: 'Det gick inte att ladda upp ikonen',
        vi: 'Không thể tải lên biểu tượng',
        id: 'Gagal mengunggah ikon',
      }),
    },
    addColumn: {
      modalTitle: t({
        ru: 'Новая колонка',
        en: 'New column',
        kk: 'Жаңа баған',
        de: 'Neue Kolumne',
        fr: 'Nouvelle colonne',
        es: 'Nueva columna',
        pt: 'Nova coluna',
        tr: 'Yeni sütun',
        uk: 'Нова колонка',
        zh: '新专栏',
        ar: 'عمود جديد',
        pl: 'Nowa kolumna',
        it: 'Nuova rubrica',
        sk: 'Nový stĺpec',
        ja: '新しいコラム',
        ko: '새 열',
        hi: 'नया कॉलम',
        nl: 'Nieuwe kolom',
        sv: 'Ny kolumn',
        vi: 'Cột mới',
        id: 'Kolom baru',
      }),
      loading: t({
        ru: 'Добавление колонки...',
        en: 'Adding column...',
        kk: 'Баған қосылуда...',
        de: 'Spalte wird hinzugefügt...',
        fr: 'Ajout d\'une colonne...',
        es: 'Agregando columna...',
        pt: 'Adicionando coluna...',
        tr: 'Sütun ekleniyor...',
        uk: 'Додавання стовпця...',
        zh: '添加列...',
        ar: 'إضافة عمود...',
        pl: 'Dodawanie kolumny...',
        it: 'Aggiunta colonna...',
        sk: 'Pridáva sa stĺpec...',
        ja: '列を追加しています...',
        ko: '열 추가 중...',
        hi: 'कॉलम जोड़ा जा रहा है...',
        nl: 'Kolom toevoegen...',
        sv: 'Lägger till kolumn...',
        vi: 'Đang thêm cột...',
        id: 'Menambahkan kolom...',
      }),
      success: t({
        ru: 'Колонка добавлена',
        en: 'Column added',
        kk: 'Баған қосылды',
        de: 'Spalte hinzugefügt',
        fr: 'Colonne ajoutée',
        es: 'Columna agregada',
        pt: 'Coluna adicionada',
        tr: 'Sütun eklendi',
        uk: 'Стовпець додано',
        zh: '已添加栏目',
        ar: 'تمت إضافة العمود',
        pl: 'Dodano kolumnę',
        it: 'Colonna aggiunta',
        sk: 'Stĺpec bol pridaný',
        ja: 'コラムを追加しました',
        ko: '열이 추가됨',
        hi: 'कॉलम जोड़ा गया',
        nl: 'Kolom toegevoegd',
        sv: 'Kolumn tillagd',
        vi: 'Đã thêm cột',
        id: 'Kolom ditambahkan',
      }),
      failed: t({
        ru: 'Не удалось добавить колонку',
        en: 'Failed to add column',
        kk: 'Баған қосу мүмкін болмады',
        de: 'Spalte konnte nicht hinzugefügt werden',
        fr: 'Échec de l\'ajout d\'une colonne',
        es: 'No se pudo agregar la columna',
        pt: 'Falha ao adicionar coluna',
        tr: 'Sütun eklenemedi',
        uk: 'Не вдалося додати стовпець',
        zh: '添加列失败',
        ar: 'فشلت إضافة عمود',
        pl: 'Nie udało się dodać kolumny',
        it: 'Impossibile aggiungere la colonna',
        sk: 'Stĺpec sa nepodarilo pridať',
        ja: '列の追加に失敗しました',
        ko: '열을 추가하지 못했습니다.',
        hi: 'कॉलम जोड़ने में विफल',
        nl: 'Kan kolom niet toevoegen',
        sv: 'Det gick inte att lägga till kolumn',
        vi: 'Không thể thêm cột',
        id: 'Gagal menambahkan kolom',
      }),
      titleLabel: t({
        ru: 'Название колонки',
        en: 'Column name',
        kk: 'Баған атауы',
        de: 'Spaltenname',
        fr: 'Nom de la colonne',
        es: 'Nombre de columna',
        pt: 'Nome da coluna',
        tr: 'Sütun adı',
        uk: 'Назва стовпця',
        zh: '栏目名称',
        ar: 'اسم العمود',
        pl: 'Nazwa kolumny',
        it: 'Nome della colonna',
        sk: 'Názov stĺpca',
        ja: '列名',
        ko: '열 이름',
        hi: 'स्तम्भ का नाम',
        nl: 'Kolomnaam',
        sv: 'Kolumnnamn',
        vi: 'Tên cột',
        id: 'Nama kolom',
      }),
      titlePlaceholder: t({
        ru: 'Например: Сумма, Дата, Контрагент',
        en: 'e.g. Amount, Date, Counterparty',
        kk: 'Мысалы: Сома, Күні, Контрагент',
        de: 'z.B. Betrag, Datum, Gegenpartei',
        fr: 'par ex. Montant, Date, Contrepartie',
        es: 'por ej. Importe, Fecha, Contraparte',
        pt: 'por exemplo Montante, Data, Contraparte',
        tr: 'örneğin Tutar, Tarih, Karşı Taraf',
        uk: 'напр. Сума, Дата, Контрагент',
        zh: '例如金额、日期、交易对手',
        ar: 'على سبيل المثال المبلغ، التاريخ، الطرف المقابل',
        pl: 'np. Kwota, data, kontrahent',
        it: 'ad es. Importo, Data, Controparte',
        sk: 'napr. Suma, dátum, protistrana',
        ja: '例:金額、日付、取引先',
        ko: '예를 들어 금액, 날짜, 거래상대방',
        hi: 'जैसे राशि, तिथि, प्रतिपक्ष',
        nl: 'bijv. Bedrag, datum, tegenpartij',
        sv: 't.ex. Belopp, Datum, Motpart',
        vi: 'ví dụ: Số tiền, Ngày, Đối tác',
        id: 'misalnya Jumlah, Tanggal, Pihak Rekanan',
      }),
      typeLabel: t({
        ru: 'Тип',
        en: 'Type',
        kk: 'Түрі',
        de: 'Typ',
        fr: 'Tapez',
        es: 'Tipo',
        pt: 'Tipo',
        tr: 'Tür',
        uk: 'Тип',
        zh: '类型',
        ar: 'اكتب',
        pl: 'Wpisz',
        it: 'Digitare',
        sk: 'Typ',
        ja: '種類',
        ko: '유형',
        hi: 'प्रकार',
        nl: 'Typ',
        sv: 'Typ',
        vi: 'loại',
        id: 'Ketik',
      }),
      iconLabel: t({
        ru: 'Иконка',
        en: 'Icon',
        kk: 'Иконка',
        de: 'Symbol',
        fr: 'Icône',
        es: 'Icono',
        pt: 'Ícone',
        tr: 'Simge',
        uk: 'значок',
        zh: '图标',
        ar: 'أيقونة',
        pl: 'Ikona',
        it: 'Icona',
        sk: 'Ikona',
        ja: 'アイコン',
        ko: '아이콘',
        hi: 'चिह्न',
        nl: 'Icoon',
        sv: 'Ikon',
        vi: 'Biểu tượng',
        id: 'Ikon',
      }),
      choose: t({
        ru: 'Выбрать',
        en: 'Choose',
        kk: 'Таңдау',
        de: 'Wählen Sie',
        fr: 'Choisissez',
        es: 'Elige',
        pt: 'Escolha',
        tr: 'Seç',
        uk: 'Виберіть',
        zh: '选择',
        ar: 'اختر',
        pl: 'Wybierz',
        it: 'Scegli',
        sk: 'Vyberte si',
        ja: '選択してください',
        ko: '선택',
        hi: 'चुनें',
        nl: 'Kies',
        sv: 'Välj',
        vi: 'chọn',
        id: 'Pilih',
      }),
      uploadIcon: t({
        ru: 'Загрузить иконку',
        en: 'Upload icon',
        kk: 'Иконканы жүктеу',
        de: 'Hochladen-Symbol',
        fr: 'Icône de téléchargement',
        es: 'Icono de carga',
        pt: 'Ícone de upload',
        tr: 'Yükleme simgesi',
        uk: 'Завантажити значок',
        zh: '上传图标',
        ar: 'رمز التحميل',
        pl: 'Prześlij ikonę',
        it: 'Icona Carica',
        sk: 'Ikona nahrávania',
        ja: 'アップロードアイコン',
        ko: '업로드 아이콘',
        hi: 'अपलोड आइकन',
        nl: 'Uploadpictogram',
        sv: 'Ladda upp ikon',
        vi: 'Biểu tượng tải lên',
        id: 'Ikon unggah',
      }),
      uploading: t({
        ru: 'Загрузка...',
        en: 'Uploading...',
        kk: 'Жүктелуде...',
        de: 'Hochladen...',
        fr: 'Téléchargement...',
        es: 'Subiendo...',
        pt: 'Fazendo upload...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '正在上传...',
        ar: 'جارٍ التحميل...',
        pl: 'Przesyłanie...',
        it: 'Caricamento...',
        sk: 'Nahráva sa...',
        ja: 'アップロード中...',
        ko: '업로드 중...',
        hi: 'अपलोड हो रहा है...',
        nl: 'Uploaden...',
        sv: 'Laddar upp...',
        vi: 'Đang tải lên...',
        id: 'Mengunggah...',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Zrušiť',
        ja: 'キャンセル',
        ko: '취소',
        hi: 'रद्द करें',
        nl: 'Annuleer',
        sv: 'Avbryt',
        vi: 'Hủy bỏ',
        id: 'Batalkan',
      }),
      save: t({
        ru: 'Сохранить',
        en: 'Save',
        kk: 'Сақтау',
        de: 'Speichern',
        fr: 'Enregistrer',
        es: 'Guardar',
        pt: 'Salvar',
        tr: 'Kaydet',
        uk: 'зберегти',
        zh: '保存',
        ar: 'حفظ',
        pl: 'Zapisz',
        it: 'Salva',
        sk: 'Uložiť',
        ja: '保存',
        ko: '저장',
        hi: 'सहेजें',
        nl: 'Opslaan',
        sv: 'Spara',
        vi: 'Lưu',
        id: 'Simpan',
      }),
    },
  },
} satisfies Dictionary;

export default content;
