import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'receiptPlaceFollowup',
  content: {
    promptTitle: t({
      ru: 'Где вы купили это?',
      en: 'Where did you buy this?',
      kk: 'Мұны қайдан сатып алдыңыз?',
      de: 'Wo haben Sie das gekauft?',
      fr: 'Où avez-vous acheté ceci ?',
      es: '¿Dónde lo compraste?',
      pt: 'Onde comprou isto?',
      tr: 'Bunu nereden aldınız?',
      uk: 'Де ви це купили?',
      zh: '您在哪里购买的？',
      ar: 'من أين اشتريت هذا؟',
      pl: 'Gdzie to kupiono?',
      it: 'Dove l’hai comprato?',
      sk: 'Kde ste to kúpili?',
      ja: 'どこで購入しましたか？',
      ko: '어디에서 구매하셨나요?',
      hi: 'आपने यह कहाँ खरीदा?',
      nl: 'Waar heeft u dit gekocht?',
      sv: 'Var köpte du detta?',
      vi: 'Bạn đã mua món này ở đâu?',
      id: 'Di mana Anda membelinya?',
    }),
    promptBody: t({
      ru: 'GPS снова доступен. Уточните магазин для этого чека.',
      en: 'GPS is back. Pick the shop for this receipt.',
      kk: 'GPS қайта қолжетімді. Осы чектің дүкенін нақтылаңыз.',
      de: 'GPS ist wieder da. Wählen Sie das Geschäft für diesen Beleg.',
      fr: 'Le GPS est revenu. Choisissez le magasin de ce reçu.',
      es: 'El GPS ha vuelto. Elige la tienda de este recibo.',
      pt: 'O GPS voltou. Escolha a loja deste recibo.',
      tr: 'GPS geri geldi. Bu fişin mağazasını seçin.',
      uk: 'GPS знову доступний. Уточніть магазин для цього чека.',
      zh: 'GPS 已恢复。请为这张收据选择商店。',
      ar: 'عاد نظام GPS. اختر المتجر لهذا الإيصال.',
      pl: 'GPS wrócił. Wybierz sklep dla tego paragonu.',
      it: 'Il GPS è tornato. Scegli il negozio di questo scontrino.',
      sk: 'GPS je späť. Vyberte obchod pre tento doklad.',
      ja: 'GPS が回復しました。このレシートの店舗を選んでください。',
      ko: 'GPS가 다시 연결되었습니다. 이 영수증의 매장을 선택하세요.',
      hi: 'GPS वापस आ गया है। इस रसीद की दुकान चुनें।',
      nl: 'GPS is terug. Kies de winkel voor dit bonnetje.',
      sv: 'GPS är tillbaka. Välj butiken för det här kvittot.',
      vi: 'GPS đã có lại. Hãy chọn cửa hàng cho hóa đơn này.',
      id: 'GPS sudah kembali. Pilih toko untuk struk ini.',
    }),
    choosePlace: t({
      ru: 'Выбрать магазин',
      en: 'Choose shop',
      kk: 'Дүкенді таңдау',
      de: 'Geschäft wählen',
      fr: 'Choisir le magasin',
      es: 'Elegir tienda',
      pt: 'Escolher loja',
      tr: 'Mağaza seç',
      uk: 'Вибрати магазин',
      zh: '选择商店',
      ar: 'اختيار المتجر',
      pl: 'Wybierz sklep',
      it: 'Scegli negozio',
      sk: 'Vybrať obchod',
      ja: '店舗を選ぶ',
      ko: '매장 선택',
      hi: 'दुकान चुनें',
      nl: 'Winkel kiezen',
      sv: 'Välj butik',
      vi: 'Chọn cửa hàng',
      id: 'Pilih toko',
    }),
    close: t({
      ru: 'Закрыть',
      en: 'Close',
      kk: 'Жабу',
      de: 'Schließen',
      fr: 'Fermer',
      es: 'Cerrar',
      pt: 'Fechar',
      tr: 'Kapat',
      uk: 'Закрити',
      zh: '关闭',
      ar: 'إغلاق',
      pl: 'Zamknij',
      it: 'Chiudi',
      sk: 'Zavrieť',
      ja: '閉じる',
      ko: '닫기',
      hi: 'बंद करें',
      nl: 'Sluiten',
      sv: 'Stäng',
      vi: 'Đóng',
      id: 'Tutup',
    }),
    dontShowAgain: t({
      ru: 'Больше не показывать',
      en: 'Don’t show again',
      kk: 'Қайта көрсетпеу',
      de: 'Nicht mehr anzeigen',
      fr: 'Ne plus afficher',
      es: 'No volver a mostrar',
      pt: 'Não mostrar novamente',
      tr: 'Bir daha gösterme',
      uk: 'Більше не показувати',
      zh: '不再显示',
      ar: 'عدم الإظهار مجددًا',
      pl: 'Nie pokazuj więcej',
      it: 'Non mostrare più',
      sk: 'Už nezobrazovať',
      ja: '今後表示しない',
      ko: '다시 표시 안 함',
      hi: 'फिर न दिखाएँ',
      nl: 'Niet meer tonen',
      sv: 'Visa inte igen',
      vi: 'Không hiển thị lại',
      id: 'Jangan tampilkan lagi',
    }),
    turnedOff: t({
      ru: 'Больше не спросим. Включить можно в Настройки → Данные.',
      en: 'We won’t ask again. You can turn it back on in Settings → Data.',
      kk: 'Енді сұрамаймыз. Параметрлер → Деректер бөлімінде қайта қосуға болады.',
      de: 'Wir fragen nicht mehr. Sie können es unter Einstellungen → Daten wieder einschalten.',
      fr: 'Nous ne demanderons plus. Vous pouvez le réactiver dans Paramètres → Données.',
      es: 'No volveremos a preguntar. Puedes reactivarlo en Ajustes → Datos.',
      pt: 'Não voltaremos a perguntar. Pode reativar em Definições → Dados.',
      tr: 'Bir daha sormayacağız. Ayarlar → Veriler bölümünden yeniden açabilirsiniz.',
      uk: 'Більше не запитаємо. Увімкнути можна в Налаштування → Дані.',
      zh: '我们不会再询问。您可以在“设置 → 数据”中重新开启。',
      ar: 'لن نسأل مجددًا. يمكنك إعادة التشغيل من الإعدادات ← البيانات.',
      pl: 'Nie zapytamy ponownie. Możesz to włączyć w Ustawienia → Dane.',
      it: 'Non lo chiederemo più. Puoi riattivarlo in Impostazioni → Dati.',
      sk: 'Už sa nespýtame. Znova to zapnete v Nastavenia → Údaje.',
      ja: '今後は確認しません。設定 → データで再度オンにできます。',
      ko: '다시 묻지 않습니다. 설정 → 데이터에서 다시 켤 수 있습니다.',
      hi: 'हम फिर नहीं पूछेंगे। आप इसे सेटिंग्स → डेटा में फिर से चालू कर सकते हैं।',
      nl: 'We vragen het niet meer. U kunt het weer inschakelen via Instellingen → Gegevens.',
      sv: 'Vi frågar inte igen. Du kan slå på det igen under Inställningar → Data.',
      vi: 'Chúng tôi sẽ không hỏi lại. Bạn có thể bật lại trong Cài đặt → Dữ liệu.',
      id: 'Kami tidak akan bertanya lagi. Anda dapat mengaktifkannya kembali di Pengaturan → Data.',
    }),
    drawerTitle: t({
      ru: 'В каком магазине вы были?',
      en: 'Which shop was it?',
      kk: 'Қай дүкенде болдыңыз?',
      de: 'Welches Geschäft war es?',
      fr: 'Quel magasin était-ce ?',
      es: '¿Qué tienda era?',
      pt: 'Que loja era?',
      tr: 'Hangi mağazaydı?',
      uk: 'У якому магазині ви були?',
      zh: '是哪家商店？',
      ar: 'أي متجر كان؟',
      pl: 'Który to był sklep?',
      it: 'Quale negozio era?',
      sk: 'Ktorý obchod to bol?',
      ja: 'どの店舗でしたか？',
      ko: '어느 매장이었나요?',
      hi: 'यह कौन सी दुकान थी?',
      nl: 'Welke winkel was het?',
      sv: 'Vilken butik var det?',
      vi: 'Đó là cửa hàng nào?',
      id: 'Toko mana itu?',
    }),
    drawerHint: t({
      ru: 'Места рядом с точкой, где телефон снова поймал GPS после съёмки.',
      en: 'Places near where your phone found GPS again after the photo.',
      kk: 'Суреттен кейін телефон GPS-ті қайта ұстаған нүктеге жақын орындар.',
      de: 'Orte in der Nähe der Stelle, an der Ihr Telefon nach dem Foto wieder GPS hatte.',
      fr: 'Lieux proches de l’endroit où votre téléphone a retrouvé le GPS après la photo.',
      es: 'Lugares cerca de donde tu teléfono recuperó el GPS después de la foto.',
      pt: 'Locais perto de onde o telemóvel voltou a ter GPS depois da foto.',
      tr: 'Fotoğraftan sonra telefonunuzun GPS’i yeniden bulduğu yerin yakınındaki mekânlar.',
      uk: 'Місця поруч із точкою, де телефон знову впіймав GPS після зйомки.',
      zh: '拍照后手机重新获得 GPS 的位置附近的地点。',
      ar: 'أماكن قريبة من الموضع الذي استعاد فيه هاتفك إشارة GPS بعد التصوير.',
      pl: 'Miejsca w pobliżu punktu, w którym telefon po zdjęciu znów złapał GPS.',
      it: 'Luoghi vicini a dove il telefono ha ritrovato il GPS dopo la foto.',
      sk: 'Miesta blízko bodu, kde telefón po fotke znova zachytil GPS.',
      ja: '撮影後にスマートフォンが GPS を再取得した地点の近くの場所です。',
      ko: '촬영 후 휴대폰이 GPS를 다시 잡은 위치 근처의 장소입니다.',
      hi: 'फ़ोटो के बाद जहाँ आपके फ़ोन को फिर से GPS मिला, उसके पास की जगहें।',
      nl: 'Plaatsen in de buurt van waar uw telefoon na de foto weer GPS had.',
      sv: 'Platser nära där telefonen fick GPS igen efter bilden.',
      vi: 'Các địa điểm gần nơi điện thoại có lại GPS sau khi chụp.',
      id: 'Tempat di dekat lokasi ponsel Anda mendapat GPS lagi setelah foto.',
    }),
    placesNearby: t({
      ru: 'Места рядом',
      en: 'Places nearby',
      kk: 'Жақын маңдағы орындар',
      de: 'Orte in der Nähe',
      fr: 'Lieux à proximité',
      es: 'Lugares cercanos',
      pt: 'Locais próximos',
      tr: 'Yakındaki yerler',
      uk: 'Місця поруч',
      zh: '附近地点',
      ar: 'أماكن قريبة',
      pl: 'Miejsca w pobliżu',
      it: 'Luoghi vicini',
      sk: 'Miesta v okolí',
      ja: '近くの場所',
      ko: '주변 장소',
      hi: 'आस-पास की जगहें',
      nl: 'Plaatsen in de buurt',
      sv: 'Platser i närheten',
      vi: 'Địa điểm lân cận',
      id: 'Tempat terdekat',
    }),
    matchesReceipt: t({
      ru: 'Совпадает с чеком',
      en: 'Matches the receipt',
      kk: 'Чекпен сәйкес',
      de: 'Passt zum Beleg',
      fr: 'Correspond au reçu',
      es: 'Coincide con el recibo',
      pt: 'Corresponde ao recibo',
      tr: 'Fişle eşleşiyor',
      uk: 'Збігається з чеком',
      zh: '与收据一致',
      ar: 'يطابق الإيصال',
      pl: 'Pasuje do paragonu',
      it: 'Corrisponde allo scontrino',
      sk: 'Zhoduje sa s dokladom',
      ja: 'レシートと一致',
      ko: '영수증과 일치',
      hi: 'रसीद से मेल खाता है',
      nl: 'Komt overeen met het bonnetje',
      sv: 'Stämmer med kvittot',
      vi: 'Khớp với hóa đơn',
      id: 'Cocok dengan struk',
    }),
    metres: t({
      ru: 'м',
      en: 'm',
      kk: 'м',
      de: 'm',
      fr: 'm',
      es: 'm',
      pt: 'm',
      tr: 'm',
      uk: 'м',
      zh: '米',
      ar: 'م',
      pl: 'm',
      it: 'm',
      sk: 'm',
      ja: 'm',
      ko: 'm',
      hi: 'मी',
      nl: 'm',
      sv: 'm',
      vi: 'm',
      id: 'm',
    }),
    save: t({
      ru: 'Сохранить',
      en: 'Save',
      kk: 'Сақтау',
      de: 'Speichern',
      fr: 'Enregistrer',
      es: 'Guardar',
      pt: 'Guardar',
      tr: 'Kaydet',
      uk: 'Зберегти',
      zh: '保存',
      ar: 'حفظ',
      pl: 'Zapisz',
      it: 'Salva',
      sk: 'Uložiť',
      ja: '保存',
      ko: '저장',
      hi: 'सहेजें',
      nl: 'Opslaan',
      sv: 'Spara',
      vi: 'Lưu',
      id: 'Simpan',
    }),
    notInList: t({
      ru: 'Нет в списке — указать на карте',
      en: 'Not in the list — set it on the map',
      kk: 'Тізімде жоқ — картада көрсету',
      de: 'Nicht in der Liste – auf der Karte setzen',
      fr: 'Absent de la liste — le placer sur la carte',
      es: 'No está en la lista: márcalo en el mapa',
      pt: 'Não está na lista — marcar no mapa',
      tr: 'Listede yok — haritada işaretle',
      uk: 'Немає в списку — вказати на мапі',
      zh: '列表中没有——在地图上标记',
      ar: 'غير موجود في القائمة — حدّده على الخريطة',
      pl: 'Nie ma na liście — wskaż na mapie',
      it: 'Non è in elenco: indicalo sulla mappa',
      sk: 'Nie je v zozname — označiť na mape',
      ja: '一覧にない場合は地図で指定',
      ko: '목록에 없음 — 지도에서 지정',
      hi: 'सूची में नहीं है — मानचित्र पर चुनें',
      nl: 'Niet in de lijst — op de kaart aanwijzen',
      sv: 'Finns inte i listan – markera på kartan',
      vi: 'Không có trong danh sách — chọn trên bản đồ',
      id: 'Tidak ada di daftar — tandai di peta',
    }),
    saved: t({
      ru: 'Магазин сохранён',
      en: 'Shop saved',
      kk: 'Дүкен сақталды',
      de: 'Geschäft gespeichert',
      fr: 'Magasin enregistré',
      es: 'Tienda guardada',
      pt: 'Loja guardada',
      tr: 'Mağaza kaydedildi',
      uk: 'Магазин збережено',
      zh: '商店已保存',
      ar: 'تم حفظ المتجر',
      pl: 'Sklep zapisany',
      it: 'Negozio salvato',
      sk: 'Obchod uložený',
      ja: '店舗を保存しました',
      ko: '매장이 저장되었습니다',
      hi: 'दुकान सहेजी गई',
      nl: 'Winkel opgeslagen',
      sv: 'Butiken har sparats',
      vi: 'Đã lưu cửa hàng',
      id: 'Toko disimpan',
    }),
    saveFailed: t({
      ru: 'Не удалось сохранить магазин',
      en: 'Could not save the shop',
      kk: 'Дүкенді сақтау мүмкін болмады',
      de: 'Das Geschäft konnte nicht gespeichert werden',
      fr: 'Impossible d’enregistrer le magasin',
      es: 'No se pudo guardar la tienda',
      pt: 'Não foi possível guardar a loja',
      tr: 'Mağaza kaydedilemedi',
      uk: 'Не вдалося зберегти магазин',
      zh: '无法保存商店',
      ar: 'تعذّر حفظ المتجر',
      pl: 'Nie udało się zapisać sklepu',
      it: 'Impossibile salvare il negozio',
      sk: 'Obchod sa nepodarilo uložiť',
      ja: '店舗を保存できませんでした',
      ko: '매장을 저장하지 못했습니다',
      hi: 'दुकान सहेजी नहीं जा सकी',
      nl: 'Kan de winkel niet opslaan',
      sv: 'Det gick inte att spara butiken',
      vi: 'Không thể lưu cửa hàng',
      id: 'Tidak dapat menyimpan toko',
    }),
  },
} satisfies Dictionary;

export default content;
