#!/bin/bash

set -e

echo "Lumio environment setup"
echo ""
echo "Note: env files are optional in development."
echo "This script generates local overrides with custom JWT secrets."
echo ""

if command -v openssl >/dev/null 2>&1; then
  JWT_SECRET=$(openssl rand -base64 32 | tr -d '\n')
  JWT_REFRESH_SECRET=$(openssl rand -base64 32 | tr -d '\n')
  echo "Generated JWT secrets."
else
  JWT_SECRET="lumio-dev-jwt-secret-do-not-use-in-production-abc123"
  JWT_REFRESH_SECRET="lumio-dev-jwt-refresh-secret-do-not-use-in-production-xyz789"
  echo "OpenSSL not found. Using deterministic development JWT secrets."
fi

if [ ! -f ".env" ]; then
  if [ -f ".env.example" ]; then
    cp .env.example .env
  else
    touch .env
  fi
  echo "Created .env"
else
  echo ".env already exists, skipping"
fi

if [ ! -f "backend/.env" ]; then
  cat > backend/.env << EOF
# Generated by scripts/generate-env.sh
NODE_ENV=development
DATABASE_URL=postgresql://lumio:lumio@localhost:5432/lumio
REDIS_URL=redis://localhost:6379
JWT_SECRET=${JWT_SECRET}
JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
EOF
  echo "Created backend/.env"
else
  echo "backend/.env already exists, skipping"
fi

if [ ! -f "frontend/.env.local" ]; then
  cat > frontend/.env.local << EOF
# Generated by scripts/generate-env.sh
NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
NEXT_PUBLIC_ENV=development
EOF
  echo "Created frontend/.env.local"
else
  echo "frontend/.env.local already exists, skipping"
fi

echo ""
echo "Setup complete."
echo ""
echo "Next steps:"
echo "  Docker mode: make quick-dev"
echo "  Local mode:  make db-start && npm install && npm run dev && make seed-demo"
echo ""
