import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'reviewInbox',
  content: {
    title: t({
      ru: 'Разбор',
      en: 'Review inbox',
      kk: 'Қарау',
      de: 'Prüf-Posteingang',
      fr: 'Boîte de revue',
      es: 'Bandeja de revisión',
      pt: 'Caixa de revisão',
      tr: 'İnceleme gelen kutusu',
      uk: 'Розбір',
      zh: '审核收件箱',
      pl: 'Skrzynka przeglądu',
      it: 'Posta di revisione',
      sk: 'Schránka na kontrolu',
      ja: '確認用受信箱',
      ko: '검토함',
      hi: 'समीक्षा इनबॉक्स',
      nl: 'Beoordelingspostvak',
      sv: 'Granskningsinkorg',
      vi: 'Hộp thư xem xét',
      id: 'Kotak masuk peninjauan',
      da: 'Gennemgang',
      nb: 'Gjennomgang',
      nn: 'Gjennomgang',
      fi: 'Tarkastettavat',
      is: 'Yfirferð',
      fo: 'Gjøgnumgongd',
      cs: 'Ke kontrole',
      bg: 'За преглед',
      hr: 'Za pregled',
      sr: 'За преглед',
      sl: 'Za pregled',
      mk: 'За преглед',
      be: 'Разбор',
      bs: 'Za pregled',
      hsb: 'K přepruwowanju',
    }),
    subtitle: t({
      ru: 'Всё, что ждёт вашего решения: без категории или с категорией от ИИ, чеки без суммы, похожие на дубли, найденные подписки.',
      en: 'Everything waiting for your decision: uncategorised or AI-categorised rows, receipts without an amount, suspected duplicates, detected subscriptions.',
      kk: 'Шешіміңізді күтетіннің бәрі: санатсыз немесе ЖИ санаттаған жолдар, сомасыз чектер, болжамды қайталаулар, табылған жазылымдар.',
      de: 'Alles, was auf Ihre Entscheidung wartet: unkategorisierte oder KI-kategorisierte Buchungen, Belege ohne Betrag, mögliche Duplikate, erkannte Abos.',
      fr: 'Tout ce qui attend votre décision : lignes sans catégorie ou catégorisées par l’IA, reçus sans montant, doublons présumés, abonnements détectés.',
      es: 'Todo lo que espera tu decisión: filas sin categoría o categorizadas por IA, recibos sin importe, posibles duplicados, suscripciones detectadas.',
      pt: 'Tudo o que espera a sua decisão: linhas sem categoria ou categorizadas pela IA, recibos sem valor, possíveis duplicados, subscrições detetadas.',
      tr: 'Kararınızı bekleyen her şey: kategorisiz veya yapay zekâ ile kategorilenmiş satırlar, tutarı olmayan fişler, olası kopyalar, tespit edilen abonelikler.',
      uk: 'Усе, що чекає на ваше рішення: без категорії або з категорією від ШІ, чеки без суми, ймовірні дублі, знайдені підписки.',
      zh: '所有等待您决定的内容：未分类或 AI 分类的记录、无金额的收据、疑似重复项、检测到的订阅。',
      pl: 'Wszystko, co czeka na Twoją decyzję: wiersze bez kategorii lub skategoryzowane przez AI, paragony bez kwoty, podejrzane duplikaty, wykryte subskrypcje.',
      it: 'Tutto ciò che attende la tua decisione: righe senza categoria o categorizzate dall’IA, scontrini senza importo, possibili duplicati, abbonamenti rilevati.',
      sk: 'Všetko, čo čaká na vaše rozhodnutie: riadky bez kategórie alebo kategorizované AI, účtenky bez sumy, podozrivé duplicity, zistené predplatné.',
      ja: '判断待ちのすべて：未分類または AI 分類の行、金額のないレシート、重複の疑い、検出されたサブスクリプション。',
      ko: '결정을 기다리는 모든 항목: 미분류 또는 AI 분류 행, 금액 없는 영수증, 중복 의심, 감지된 구독.',
      hi: 'आपके निर्णय की प्रतीक्षा में सब कुछ: अवर्गीकृत या AI-वर्गीकृत पंक्तियाँ, बिना राशि की रसीदें, संदिग्ध डुप्लिकेट, पहचानी गई सदस्यताएँ।',
      nl: 'Alles wat op uw beslissing wacht: niet of door AI gecategoriseerde regels, bonnen zonder bedrag, vermoedelijke duplicaten, gedetecteerde abonnementen.',
      sv: 'Allt som väntar på ditt beslut: okategoriserade eller AI-kategoriserade rader, kvitton utan belopp, misstänkta dubbletter, upptäckta prenumerationer.',
      vi: 'Mọi thứ đang chờ bạn quyết định: dòng chưa phân loại hoặc do AI phân loại, hóa đơn không có số tiền, nghi trùng lặp, đăng ký được phát hiện.',
      id: 'Semua yang menunggu keputusan Anda: baris tanpa kategori atau dikategorikan AI, struk tanpa jumlah, dugaan duplikat, langganan yang terdeteksi.',
      da: 'Alt, der venter på din beslutning: rækker uden kategori eller kategoriseret af AI, kvitteringer uden beløb, mulige dubletter, fundne abonnementer.',
      nb: 'Alt som venter på din beslutning: rader uten kategori eller kategorisert av KI, kvitteringer uten beløp, mulige duplikater, oppdagede abonnementer.',
      nn: 'Alt som ventar på avgjerda di: rader utan kategori eller kategoriserte av KI, kvitteringar utan beløp, moglege duplikat, oppdaga abonnement.',
      fi: 'Kaikki päätöstäsi odottava: luokittelemattomat tai tekoälyn luokittelemat rivit, kuitit ilman summaa, epäillyt kaksoiskappaleet, havaitut tilaukset.',
      is: 'Allt sem bíður ákvörðunar þinnar: óflokkaðar línur eða flokkaðar af gervigreind, kvittanir án fjárhæðar, mögulegar tvíteknar færslur, greindar áskriftir.',
      fo: 'Alt, sum bíðar eftir tínari avgerð: raðir uttan bólk ella bólkaðar av KV, kvittanir uttan upphædd, møguligar tvífaldingar, funnin hald.',
      cs: 'Vše, co čeká na vaše rozhodnutí: řádky bez kategorie nebo s kategorií od AI, účtenky bez částky, podezřelé duplikáty, nalezená předplatná.',
      bg: 'Всичко, което чака вашето решение: редове без категория или с категория от ИИ, касови бележки без сума, възможни дубликати, открити абонаменти.',
      hr: 'Sve što čeka vašu odluku: retci bez kategorije ili s kategorijom od AI-ja, računi bez iznosa, mogući duplikati, otkrivene pretplate.',
      sr: 'Све што чека вашу одлуку: редови без категорије или са категоријом од ВИ, рачуни без износа, могући дупликати, откривене претплате.',
      sl: 'Vse, kar čaka na vašo odločitev: vrstice brez kategorije ali s kategorijo od UI, računi brez zneska, morebitni dvojniki, zaznane naročnine.',
      mk: 'Сè што чека ваша одлука: редови без категорија или со категорија од ВИ, сметки без износ, можни дупликати, откриени претплати.',
      be: 'Усё, што чакае вашага рашэння: радкі без катэгорыі або з катэгорыяй ад ШІ, чэкі без сумы, магчымыя дублікаты, знойдзеныя падпіскі.',
      bs: 'Sve što čeka vašu odluku: redovi bez kategorije ili s kategorijom od AI-ja, računi bez iznosa, mogući duplikati, otkrivene pretplate.',
      hsb: 'Wšitko, štož na wašu rozsud čaka: rjadki bjez kategorije abo z kategoriju wot KI, zličbowanki bjez sumy, móžne dwójniki, namakane abonementy.',
    }),
    tabTransactions: t({
      ru: 'Категории',
      en: 'Categories',
      kk: 'Санаттар',
      de: 'Kategorien',
      fr: 'Catégories',
      es: 'Categorías',
      pt: 'Categorias',
      tr: 'Kategoriler',
      uk: 'Категорії',
      zh: '类别',
      pl: 'Kategorie',
      it: 'Categorie',
      sk: 'Kategórie',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणियाँ',
      nl: 'Categorieën',
      sv: 'Kategorier',
      vi: 'Danh mục',
      id: 'Kategori',
      da: 'Kategorier',
      nb: 'Kategorier',
      nn: 'Kategoriar',
      fi: 'Luokat',
      is: 'Flokkar',
      fo: 'Bólkar',
      cs: 'Kategorie',
      bg: 'Категории',
      hr: 'Kategorije',
      sr: 'Категорије',
      sl: 'Kategorije',
      mk: 'Категории',
      be: 'Катэгорыі',
      bs: 'Kategorije',
      hsb: 'Kategorije',
    }),
    tabReceipts: t({
      ru: 'Чеки',
      en: 'Receipts',
      kk: 'Чектер',
      de: 'Belege',
      fr: 'Reçus',
      es: 'Recibos',
      pt: 'Recibos',
      tr: 'Fişler',
      uk: 'Чеки',
      zh: '收据',
      pl: 'Paragony',
      it: 'Scontrini',
      sk: 'Účtenky',
      ja: 'レシート',
      ko: '영수증',
      hi: 'रसीदें',
      nl: 'Bonnen',
      sv: 'Kvitton',
      vi: 'Hóa đơn',
      id: 'Struk',
      da: 'Kvitteringer',
      nb: 'Kvitteringer',
      nn: 'Kvitteringar',
      fi: 'Kuitit',
      is: 'Kvittanir',
      fo: 'Kvittanir',
      cs: 'Účtenky',
      bg: 'Касови бележки',
      hr: 'Računi',
      sr: 'Рачуни',
      sl: 'Računi',
      mk: 'Сметки',
      be: 'Чэкі',
      bs: 'Računi',
      hsb: 'Zličbowanki',
    }),
    tabDuplicates: t({
      ru: 'Дубли',
      en: 'Duplicates',
      kk: 'Қайталаулар',
      de: 'Duplikate',
      fr: 'Doublons',
      es: 'Duplicados',
      pt: 'Duplicados',
      tr: 'Kopyalar',
      uk: 'Дублі',
      zh: '重复项',
      pl: 'Duplikaty',
      it: 'Duplicati',
      sk: 'Duplicity',
      ja: '重複',
      ko: '중복',
      hi: 'डुप्लिकेट',
      nl: 'Duplicaten',
      sv: 'Dubbletter',
      vi: 'Trùng lặp',
      id: 'Duplikat',
      da: 'Dubletter',
      nb: 'Duplikater',
      nn: 'Duplikat',
      fi: 'Kaksoiskappaleet',
      is: 'Tvítök',
      fo: 'Tvífaldingar',
      cs: 'Duplikáty',
      bg: 'Дубликати',
      hr: 'Duplikati',
      sr: 'Дупликати',
      sl: 'Dvojniki',
      mk: 'Дупликати',
      be: 'Дублікаты',
      bs: 'Duplikati',
      hsb: 'Dwójniki',
    }),
    tabSubscriptions: t({
      ru: 'Подписки',
      en: 'Subscriptions',
      kk: 'Жазылымдар',
      de: 'Abos',
      fr: 'Abonnements',
      es: 'Suscripciones',
      pt: 'Subscrições',
      tr: 'Abonelikler',
      uk: 'Підписки',
      zh: '订阅',
      pl: 'Subskrypcje',
      it: 'Abbonamenti',
      sk: 'Predplatné',
      ja: 'サブスク',
      ko: '구독',
      hi: 'सदस्यताएँ',
      nl: 'Abonnementen',
      sv: 'Prenumerationer',
      vi: 'Đăng ký',
      id: 'Langganan',
      da: 'Abonnementer',
      nb: 'Abonnementer',
      nn: 'Abonnement',
      fi: 'Tilaukset',
      is: 'Áskriftir',
      fo: 'Hald',
      cs: 'Předplatné',
      bg: 'Абонаменти',
      hr: 'Pretplate',
      sr: 'Претплате',
      sl: 'Naročnine',
      mk: 'Претплати',
      be: 'Падпіскі',
      bs: 'Pretplate',
      hsb: 'Abonementy',
    }),
    empty: t({
      ru: 'Здесь пусто. Всё разобрано.',
      en: 'Nothing here. All caught up.',
      kk: 'Бос. Бәрі қаралды.',
      de: 'Nichts zu tun. Alles erledigt.',
      fr: 'Rien ici. Tout est à jour.',
      es: 'Nada aquí. Todo al día.',
      pt: 'Nada aqui. Tudo em dia.',
      tr: 'Burada bir şey yok. Her şey tamam.',
      uk: 'Тут порожньо. Усе розібрано.',
      zh: '这里没有内容，全部处理完毕。',
      pl: 'Pusto. Wszystko ogarnięte.',
      it: 'Niente qui. Tutto a posto.',
      sk: 'Nič tu nie je. Všetko hotové.',
      ja: '何もありません。すべて完了です。',
      ko: '비어 있습니다. 모두 처리했습니다.',
      hi: 'यहाँ कुछ नहीं है। सब पूरा हो गया।',
      nl: 'Niets hier. Alles bijgewerkt.',
      sv: 'Inget här. Allt klart.',
      vi: 'Không có gì ở đây. Đã xử lý xong.',
      id: 'Tidak ada apa-apa. Semua beres.',
      da: 'Intet her. Alt er gennemgået.',
      nb: 'Ingenting her. Alt er gjennomgått.',
      nn: 'Ingenting her. Alt er gjennomgått.',
      fi: 'Täällä ei ole mitään. Kaikki on käyty läpi.',
      is: 'Ekkert hér. Allt er yfirfarið.',
      fo: 'Einki her. Alt er gjøgnumgingið.',
      cs: 'Nic tu není. Vše je vyřízeno.',
      bg: 'Тук няма нищо. Всичко е прегледано.',
      hr: 'Ovdje nema ničega. Sve je pregledano.',
      sr: 'Овде нема ничега. Све је прегледано.',
      sl: 'Tu ni ničesar. Vse je pregledano.',
      mk: 'Тука нема ништо. Сè е прегледано.',
      be: 'Тут пуста. Усё разабрана.',
      bs: 'Ovdje nema ničega. Sve je pregledano.',
      hsb: 'Tu ničo njeje. Wšitko je přepruwowane.',
    }),
    groupByPayee: t({
      ru: 'Группировать по контрагенту',
      en: 'Group by payee',
      kk: 'Контрагент бойынша топтау',
      de: 'Nach Empfänger gruppieren',
      fr: 'Grouper par bénéficiaire',
      es: 'Agrupar por beneficiario',
      pt: 'Agrupar por beneficiário',
      tr: 'Alıcıya göre grupla',
      uk: 'Групувати за контрагентом',
      zh: '按收款方分组',
      pl: 'Grupuj według odbiorcy',
      it: 'Raggruppa per beneficiario',
      sk: 'Zoskupiť podľa príjemcu',
      ja: '取引先でグループ化',
      ko: '거래처별 그룹',
      hi: 'प्राप्तकर्ता के अनुसार समूह',
      nl: 'Groeperen op begunstigde',
      sv: 'Gruppera efter mottagare',
      vi: 'Nhóm theo đối tác',
      id: 'Kelompokkan per penerima',
      da: 'Gruppér efter modtager',
      nb: 'Grupper etter mottaker',
      nn: 'Grupper etter mottakar',
      fi: 'Ryhmittele saajan mukaan',
      is: 'Flokka eftir viðtakanda',
      fo: 'Bólka eftir móttakara',
      cs: 'Seskupit podle příjemce',
      bg: 'Групиране по получател',
      hr: 'Grupiraj po primatelju',
      sr: 'Групиши по примаоцу',
      sl: 'Združi po prejemniku',
      mk: 'Групирај по примач',
      be: 'Групаваць па атрымальніку',
      bs: 'Grupiši po primaocu',
      hsb: 'Po přijimarju zeskupić',
    }),
    selectAll: t({
      ru: 'Выбрать все',
      en: 'Select all',
      kk: 'Барлығын таңдау',
      de: 'Alle auswählen',
      fr: 'Tout sélectionner',
      es: 'Seleccionar todo',
      pt: 'Selecionar tudo',
      tr: 'Tümünü seç',
      uk: 'Вибрати всі',
      zh: '全选',
      pl: 'Zaznacz wszystko',
      it: 'Seleziona tutto',
      sk: 'Vybrať všetko',
      ja: 'すべて選択',
      ko: '모두 선택',
      hi: 'सभी चुनें',
      nl: 'Alles selecteren',
      sv: 'Markera alla',
      vi: 'Chọn tất cả',
      id: 'Pilih semua',
      da: 'Vælg alle',
      nb: 'Velg alle',
      nn: 'Vel alle',
      fi: 'Valitse kaikki',
      is: 'Velja allt',
      fo: 'Vel øll',
      cs: 'Vybrat vše',
      bg: 'Избери всички',
      hr: 'Odaberi sve',
      sr: 'Изабери све',
      sl: 'Izberi vse',
      mk: 'Избери ги сите',
      be: 'Выбраць усе',
      bs: 'Odaberi sve',
      hsb: 'Wšě wubrać',
    }),
    selectGroup: t({
      ru: 'Выбрать группу',
      en: 'Select group',
      kk: 'Топты таңдау',
      de: 'Gruppe auswählen',
      fr: 'Sélectionner le groupe',
      es: 'Seleccionar grupo',
      pt: 'Selecionar grupo',
      tr: 'Grubu seç',
      uk: 'Вибрати групу',
      zh: '选择此组',
      pl: 'Zaznacz grupę',
      it: 'Seleziona gruppo',
      sk: 'Vybrať skupinu',
      ja: 'グループを選択',
      ko: '그룹 선택',
      hi: 'समूह चुनें',
      nl: 'Groep selecteren',
      sv: 'Markera grupp',
      vi: 'Chọn nhóm',
      id: 'Pilih grup',
      da: 'Vælg gruppe',
      nb: 'Velg gruppe',
      nn: 'Vel gruppe',
      fi: 'Valitse ryhmä',
      is: 'Velja hóp',
      fo: 'Vel bólk',
      cs: 'Vybrat skupinu',
      bg: 'Избери група',
      hr: 'Odaberi grupu',
      sr: 'Изабери групу',
      sl: 'Izberi skupino',
      mk: 'Избери група',
      be: 'Выбраць групу',
      bs: 'Odaberi grupu',
      hsb: 'Skupinu wubrać',
    }),
    selected: t({
      ru: 'Выбрано: {{count}}',
      en: '{{count}} selected',
      kk: 'Таңдалды: {{count}}',
      de: '{{count}} ausgewählt',
      fr: '{{count}} sélectionné(s)',
      es: '{{count}} seleccionados',
      pt: '{{count}} selecionados',
      tr: '{{count}} seçildi',
      uk: 'Вибрано: {{count}}',
      zh: '已选择 {{count}} 项',
      pl: 'Wybrano: {{count}}',
      it: '{{count}} selezionati',
      sk: 'Vybraté: {{count}}',
      ja: '{{count}} 件選択中',
      ko: '{{count}}개 선택됨',
      hi: '{{count}} चयनित',
      nl: '{{count}} geselecteerd',
      sv: '{{count}} valda',
      vi: 'Đã chọn {{count}}',
      id: '{{count}} dipilih',
      da: '{{count}} valgt',
      nb: '{{count}} valgt',
      nn: '{{count}} vald',
      fi: '{{count}} valittu',
      is: '{{count}} valið',
      fo: '{{count}} valt',
      cs: 'Vybráno: {{count}}',
      bg: 'Избрани: {{count}}',
      hr: 'Odabrano: {{count}}',
      sr: 'Изабрано: {{count}}',
      sl: 'Izbrano: {{count}}',
      mk: 'Избрани: {{count}}',
      be: 'Выбрана: {{count}}',
      bs: 'Odabrano: {{count}}',
      hsb: 'Wubrane: {{count}}',
    }),
    categoryPlaceholder: t({
      ru: 'Категория…',
      en: 'Category…',
      kk: 'Санат…',
      de: 'Kategorie…',
      fr: 'Catégorie…',
      es: 'Categoría…',
      pt: 'Categoria…',
      tr: 'Kategori…',
      uk: 'Категорія…',
      zh: '类别…',
      pl: 'Kategoria…',
      it: 'Categoria…',
      sk: 'Kategória…',
      ja: 'カテゴリ…',
      ko: '카테고리…',
      hi: 'श्रेणी…',
      nl: 'Categorie…',
      sv: 'Kategori…',
      vi: 'Danh mục…',
      id: 'Kategori…',
      da: 'Kategori…',
      nb: 'Kategori…',
      nn: 'Kategori…',
      fi: 'Luokka…',
      is: 'Flokkur…',
      fo: 'Bólkur…',
      cs: 'Kategorie…',
      bg: 'Категория…',
      hr: 'Kategorija…',
      sr: 'Категорија…',
      sl: 'Kategorija…',
      mk: 'Категорија…',
      be: 'Катэгорыя…',
      bs: 'Kategorija…',
      hsb: 'Kategorija…',
    }),
    approveWithCategory: t({
      ru: 'Утвердить с категорией',
      en: 'Approve with category',
      kk: 'Санатпен бекіту',
      de: 'Mit Kategorie bestätigen',
      fr: 'Approuver avec la catégorie',
      es: 'Aprobar con categoría',
      pt: 'Aprovar com categoria',
      tr: 'Kategoriyle onayla',
      uk: 'Затвердити з категорією',
      zh: '按所选类别批准',
      pl: 'Zatwierdź z kategorią',
      it: 'Approva con categoria',
      sk: 'Schváliť s kategóriou',
      ja: 'カテゴリを付けて承認',
      ko: '카테고리와 함께 승인',
      hi: 'श्रेणी के साथ स्वीकृत करें',
      nl: 'Goedkeuren met categorie',
      sv: 'Godkänn med kategori',
      vi: 'Duyệt với danh mục',
      id: 'Setujui dengan kategori',
      da: 'Godkend med kategori',
      nb: 'Godkjenn med kategori',
      nn: 'Godkjenn med kategori',
      fi: 'Hyväksy luokan kanssa',
      is: 'Samþykkja með flokki',
      fo: 'Góðkenn við bólki',
      cs: 'Schválit s kategorií',
      bg: 'Одобряване с категория',
      hr: 'Odobri s kategorijom',
      sr: 'Одобри са категоријом',
      sl: 'Odobri s kategorijo',
      mk: 'Одобри со категорија',
      be: 'Ухваліць з катэгорыяй',
      bs: 'Odobri s kategorijom',
      hsb: 'Z kategoriju přizwolić',
    }),
    approveAsIs: t({
      ru: 'Утвердить как есть',
      en: 'Approve as is',
      kk: 'Сол күйінде бекіту',
      de: 'So bestätigen',
      fr: 'Approuver tel quel',
      es: 'Aprobar tal cual',
      pt: 'Aprovar como está',
      tr: 'Olduğu gibi onayla',
      uk: 'Затвердити як є',
      zh: '按原样批准',
      pl: 'Zatwierdź bez zmian',
      it: 'Approva così com’è',
      sk: 'Schváliť ako je',
      ja: 'そのまま承認',
      ko: '그대로 승인',
      hi: 'जैसा है वैसा स्वीकृत करें',
      nl: 'Goedkeuren zoals het is',
      sv: 'Godkänn som det är',
      vi: 'Duyệt như hiện tại',
      id: 'Setujui apa adanya',
      da: 'Godkend som den er',
      nb: 'Godkjenn som den er',
      nn: 'Godkjenn som han er',
      fi: 'Hyväksy sellaisenaan',
      is: 'Samþykkja óbreytt',
      fo: 'Góðkenn óbroytt',
      cs: 'Schválit beze změn',
      bg: 'Одобряване без промени',
      hr: 'Odobri bez promjena',
      sr: 'Одобри без измена',
      sl: 'Odobri brez sprememb',
      mk: 'Одобри без промени',
      be: 'Ухваліць як ёсць',
      bs: 'Odobri bez promjena',
      hsb: 'Bjez změnow přizwolić',
    }),
    keep: t({
      ru: 'Это не дубль',
      en: 'Keep',
      kk: 'Қайталау емес',
      de: 'Behalten',
      fr: 'Garder',
      es: 'Conservar',
      pt: 'Manter',
      tr: 'Koru',
      uk: 'Це не дубль',
      zh: '保留',
      pl: 'Zachowaj',
      it: 'Mantieni',
      sk: 'Ponechať',
      ja: '重複ではない',
      ko: '유지',
      hi: 'रखें',
      nl: 'Behouden',
      sv: 'Behåll',
      vi: 'Giữ lại',
      id: 'Simpan',
      da: 'Behold',
      nb: 'Behold',
      nn: 'Behald',
      fi: 'Säilytä',
      is: 'Halda',
      fo: 'Varðveit',
      cs: 'Ponechat',
      bg: 'Запази',
      hr: 'Zadrži',
      sr: 'Задржи',
      sl: 'Obdrži',
      mk: 'Задржи',
      be: 'Пакінуць',
      bs: 'Zadrži',
      hsb: 'Wobchować',
    }),
    confirmDuplicate: t({
      ru: 'Да, дубль',
      en: 'Yes, a duplicate',
      kk: 'Иә, қайталау',
      de: 'Ja, Duplikat',
      fr: 'Oui, un doublon',
      es: 'Sí, duplicado',
      pt: 'Sim, duplicado',
      tr: 'Evet, kopya',
      uk: 'Так, дубль',
      zh: '是重复项',
      pl: 'Tak, duplikat',
      it: 'Sì, duplicato',
      sk: 'Áno, duplicita',
      ja: 'はい、重複です',
      ko: '네, 중복입니다',
      hi: 'हाँ, डुप्लिकेट',
      nl: 'Ja, een duplicaat',
      sv: 'Ja, en dubblett',
      vi: 'Đúng, trùng lặp',
      id: 'Ya, duplikat',
      da: 'Ja, en dublet',
      nb: 'Ja, et duplikat',
      nn: 'Ja, eit duplikat',
      fi: 'Kyllä, kaksoiskappale',
      is: 'Já, tvítekið',
      fo: 'Ja, ein tvífalding',
      cs: 'Ano, duplikát',
      bg: 'Да, дубликат',
      hr: 'Da, duplikat',
      sr: 'Да, дупликат',
      sl: 'Da, dvojnik',
      mk: 'Да, дупликат',
      be: 'Так, дублікат',
      bs: 'Da, duplikat',
      hsb: 'Haj, dwójnik',
    }),
    confirmSubscription: t({
      ru: 'Это подписка',
      en: 'Confirm subscription',
      kk: 'Бұл жазылым',
      de: 'Abo bestätigen',
      fr: 'Confirmer l’abonnement',
      es: 'Confirmar suscripción',
      pt: 'Confirmar subscrição',
      tr: 'Aboneliği onayla',
      uk: 'Це підписка',
      zh: '确认订阅',
      pl: 'Potwierdź subskrypcję',
      it: 'Conferma abbonamento',
      sk: 'Potvrdiť predplatné',
      ja: 'サブスクを確認',
      ko: '구독 확인',
      hi: 'सदस्यता की पुष्टि करें',
      nl: 'Abonnement bevestigen',
      sv: 'Bekräfta prenumeration',
      vi: 'Xác nhận đăng ký',
      id: 'Konfirmasi langganan',
      da: 'Bekræft abonnement',
      nb: 'Bekreft abonnement',
      nn: 'Stadfest abonnement',
      fi: 'Vahvista tilaus',
      is: 'Staðfesta áskrift',
      fo: 'Vátta hald',
      cs: 'Potvrdit předplatné',
      bg: 'Потвърди абонамент',
      hr: 'Potvrdi pretplatu',
      sr: 'Потврди претплату',
      sl: 'Potrdi naročnino',
      mk: 'Потврди претплата',
      be: 'Пацвердзіць падпіску',
      bs: 'Potvrdi pretplatu',
      hsb: 'Abonement wobkrućić',
    }),
    dismissSubscription: t({
      ru: 'Не подписка',
      en: 'Not a subscription',
      kk: 'Жазылым емес',
      de: 'Kein Abo',
      fr: 'Pas un abonnement',
      es: 'No es suscripción',
      pt: 'Não é subscrição',
      tr: 'Abonelik değil',
      uk: 'Не підписка',
      zh: '不是订阅',
      pl: 'To nie subskrypcja',
      it: 'Non è un abbonamento',
      sk: 'Nie je predplatné',
      ja: 'サブスクではない',
      ko: '구독 아님',
      hi: 'सदस्यता नहीं',
      nl: 'Geen abonnement',
      sv: 'Ingen prenumeration',
      vi: 'Không phải đăng ký',
      id: 'Bukan langganan',
      da: 'Ikke et abonnement',
      nb: 'Ikke et abonnement',
      nn: 'Ikkje eit abonnement',
      fi: 'Ei tilaus',
      is: 'Ekki áskrift',
      fo: 'Ikki eitt hald',
      cs: 'Není předplatné',
      bg: 'Не е абонамент',
      hr: 'Nije pretplata',
      sr: 'Није претплата',
      sl: 'Ni naročnina',
      mk: 'Не е претплата',
      be: 'Не падпіска',
      bs: 'Nije pretplata',
      hsb: 'Žadyn abonement',
    }),
    openReceipt: t({
      ru: 'Открыть чек',
      en: 'Open receipt',
      kk: 'Чекті ашу',
      de: 'Beleg öffnen',
      fr: 'Ouvrir le reçu',
      es: 'Abrir recibo',
      pt: 'Abrir recibo',
      tr: 'Fişi aç',
      uk: 'Відкрити чек',
      zh: '打开收据',
      pl: 'Otwórz paragon',
      it: 'Apri scontrino',
      sk: 'Otvoriť účtenku',
      ja: 'レシートを開く',
      ko: '영수증 열기',
      hi: 'रसीद खोलें',
      nl: 'Bon openen',
      sv: 'Öppna kvitto',
      vi: 'Mở hóa đơn',
      id: 'Buka struk',
      da: 'Åbn kvittering',
      nb: 'Åpne kvittering',
      nn: 'Opne kvittering',
      fi: 'Avaa kuitti',
      is: 'Opna kvittun',
      fo: 'Opna kvittan',
      cs: 'Otevřít účtenku',
      bg: 'Отвори касовата бележка',
      hr: 'Otvori račun',
      sr: 'Отвори рачун',
      sl: 'Odpri račun',
      mk: 'Отвори сметка',
      be: 'Адкрыць чэк',
      bs: 'Otvori račun',
      hsb: 'Zličbowanku wočinić',
    }),
    approveReceipt: t({
      ru: 'Утвердить чек',
      en: 'Approve receipt',
      kk: 'Чекті бекіту',
      de: 'Beleg bestätigen',
      fr: 'Approuver le reçu',
      es: 'Aprobar recibo',
      pt: 'Aprovar recibo',
      tr: 'Fişi onayla',
      uk: 'Затвердити чек',
      zh: '批准收据',
      pl: 'Zatwierdź paragon',
      it: 'Approva scontrino',
      sk: 'Schváliť účtenku',
      ja: 'レシートを承認',
      ko: '영수증 승인',
      hi: 'रसीद स्वीकृत करें',
      nl: 'Bon goedkeuren',
      sv: 'Godkänn kvitto',
      vi: 'Duyệt hóa đơn',
      id: 'Setujui struk',
      da: 'Godkend kvittering',
      nb: 'Godkjenn kvittering',
      nn: 'Godkjenn kvittering',
      fi: 'Hyväksy kuitti',
      is: 'Samþykkja kvittun',
      fo: 'Góðkenn kvittan',
      cs: 'Schválit účtenku',
      bg: 'Одобряване на касовата бележка',
      hr: 'Odobri račun',
      sr: 'Одобри рачун',
      sl: 'Odobri račun',
      mk: 'Одобри сметка',
      be: 'Ухваліць чэк',
      bs: 'Odobri račun',
      hsb: 'Zličbowanku přizwolić',
    }),
    issueMissingAmount: t({
      ru: 'нет суммы',
      en: 'no amount',
      kk: 'сома жоқ',
      de: 'kein Betrag',
      fr: 'pas de montant',
      es: 'sin importe',
      pt: 'sem valor',
      tr: 'tutar yok',
      uk: 'немає суми',
      zh: '无金额',
      pl: 'brak kwoty',
      it: 'nessun importo',
      sk: 'chýba suma',
      ja: '金額なし',
      ko: '금액 없음',
      hi: 'राशि नहीं',
      nl: 'geen bedrag',
      sv: 'inget belopp',
      vi: 'không có số tiền',
      id: 'tidak ada jumlah',
      da: 'intet beløb',
      nb: 'ingen beløp',
      nn: 'ingen beløp',
      fi: 'ei summaa',
      is: 'engin fjárhæð',
      fo: 'eingin upphædd',
      cs: 'chybí částka',
      bg: 'няма сума',
      hr: 'nema iznosa',
      sr: 'нема износа',
      sl: 'ni zneska',
      mk: 'нема износ',
      be: 'няма сумы',
      bs: 'nema iznosa',
      hsb: 'žana suma',
    }),
    issueMissingDate: t({
      ru: 'нет даты',
      en: 'no date',
      kk: 'күні жоқ',
      de: 'kein Datum',
      fr: 'pas de date',
      es: 'sin fecha',
      pt: 'sem data',
      tr: 'tarih yok',
      uk: 'немає дати',
      zh: '无日期',
      pl: 'brak daty',
      it: 'nessuna data',
      sk: 'chýba dátum',
      ja: '日付なし',
      ko: '날짜 없음',
      hi: 'तारीख नहीं',
      nl: 'geen datum',
      sv: 'inget datum',
      vi: 'không có ngày',
      id: 'tidak ada tanggal',
      da: 'ingen dato',
      nb: 'ingen dato',
      nn: 'ingen dato',
      fi: 'ei päivämäärää',
      is: 'engin dagsetning',
      fo: 'eingin dagfesting',
      cs: 'chybí datum',
      bg: 'няма дата',
      hr: 'nema datuma',
      sr: 'нема датума',
      sl: 'ni datuma',
      mk: 'нема датум',
      be: 'няма даты',
      bs: 'nema datuma',
      hsb: 'žadyn datum',
    }),
    issuePotentialDuplicate: t({
      ru: 'возможно дубль',
      en: 'possible duplicate',
      kk: 'қайталау болуы мүмкін',
      de: 'mögliches Duplikat',
      fr: 'doublon possible',
      es: 'posible duplicado',
      pt: 'possível duplicado',
      tr: 'olası kopya',
      uk: 'можливо дубль',
      zh: '可能重复',
      pl: 'możliwy duplikat',
      it: 'possibile duplicato',
      sk: 'možná duplicita',
      ja: '重複の可能性',
      ko: '중복 가능성',
      hi: 'संभावित डुप्लिकेट',
      nl: 'mogelijk duplicaat',
      sv: 'möjlig dubblett',
      vi: 'có thể trùng lặp',
      id: 'kemungkinan duplikat',
      da: 'mulig dublet',
      nb: 'mulig duplikat',
      nn: 'mogleg duplikat',
      fi: 'mahdollinen kaksoiskappale',
      is: 'mögulega tvítekið',
      fo: 'møguligur tvífalding',
      cs: 'možný duplikát',
      bg: 'възможен дубликат',
      hr: 'mogući duplikat',
      sr: 'могући дупликат',
      sl: 'morebitni dvojnik',
      mk: 'можен дупликат',
      be: 'магчымы дублікат',
      bs: 'mogući duplikat',
      hsb: 'móžny dwójnik',
    }),
    duplicateOf: t({
      ru: 'похоже на операцию',
      en: 'looks like',
      kk: 'ұқсас',
      de: 'ähnelt',
      fr: 'ressemble à',
      es: 'se parece a',
      pt: 'parece-se com',
      tr: 'benziyor',
      uk: 'схоже на',
      zh: '疑似',
      pl: 'przypomina',
      it: 'somiglia a',
      sk: 'podobá sa',
      ja: '類似',
      ko: '유사',
      hi: 'जैसा दिखता है',
      nl: 'lijkt op',
      sv: 'liknar',
      vi: 'giống',
      id: 'mirip dengan',
      da: 'ligner',
      nb: 'ligner',
      nn: 'liknar',
      fi: 'muistuttaa',
      is: 'líkist',
      fo: 'líkist',
      cs: 'podobá se',
      bg: 'прилича на',
      hr: 'nalikuje',
      sr: 'личи на',
      sl: 'spominja na',
      mk: 'личи на',
      be: 'падобна на',
      bs: 'liči na',
      hsb: 'podobny',
    }),
    confidence: t({
      ru: 'уверенность {{value}}%',
      en: '{{value}}% confidence',
      kk: 'сенімділік {{value}}%',
      de: '{{value}} % Sicherheit',
      fr: 'confiance {{value}} %',
      es: 'confianza {{value}}%',
      pt: 'confiança {{value}}%',
      tr: '%{{value}} güven',
      uk: 'упевненість {{value}}%',
      zh: '置信度 {{value}}%',
      pl: 'pewność {{value}}%',
      it: 'affidabilità {{value}}%',
      sk: 'istota {{value}}%',
      ja: '確度 {{value}}%',
      ko: '신뢰도 {{value}}%',
      hi: '{{value}}% विश्वास',
      nl: '{{value}}% zekerheid',
      sv: '{{value}} % säkerhet',
      vi: 'độ tin cậy {{value}}%',
      id: 'keyakinan {{value}}%',
      da: '{{value}} % sikkerhed',
      nb: '{{value}} % sikkerhet',
      nn: '{{value}} % tryggleik',
      fi: '{{value}} % varmuus',
      is: '{{value}} % öryggi',
      fo: '{{value}} % vissa',
      cs: 'jistota {{value}} %',
      bg: 'сигурност {{value}} %',
      hr: 'pouzdanost {{value}} %',
      sr: 'поузданост {{value}} %',
      sl: 'zanesljivost {{value}} %',
      mk: 'сигурност {{value}} %',
      be: 'упэўненасць {{value}} %',
      bs: 'pouzdanost {{value}} %',
      hsb: 'wěstosć {{value}} %',
    }),
    shortcuts: t({
      ru: 'Клавиши: j/k — вниз/вверх, x — выбрать, a — утвердить, c — категория, Esc — снять выбор',
      en: 'Keys: j/k move, x select, a approve, c category, Esc clear',
      kk: 'Пернелер: j/k — жоғары/төмен, x — таңдау, a — бекіту, c — санат, Esc — тазалау',
      de: 'Tasten: j/k bewegen, x auswählen, a bestätigen, c Kategorie, Esc aufheben',
      fr: 'Touches : j/k déplacer, x sélectionner, a approuver, c catégorie, Échap effacer',
      es: 'Teclas: j/k mover, x seleccionar, a aprobar, c categoría, Esc limpiar',
      pt: 'Teclas: j/k mover, x selecionar, a aprovar, c categoria, Esc limpar',
      tr: 'Tuşlar: j/k hareket, x seç, a onayla, c kategori, Esc temizle',
      uk: 'Клавіші: j/k — рух, x — вибрати, a — затвердити, c — категорія, Esc — зняти',
      zh: '快捷键：j/k 移动，x 选择，a 批准，c 类别，Esc 清除',
      pl: 'Klawisze: j/k ruch, x zaznacz, a zatwierdź, c kategoria, Esc wyczyść',
      it: 'Tasti: j/k sposta, x seleziona, a approva, c categoria, Esc annulla',
      sk: 'Klávesy: j/k pohyb, x vybrať, a schváliť, c kategória, Esc zrušiť',
      ja: 'キー：j/k 移動、x 選択、a 承認、c カテゴリ、Esc 解除',
      ko: '키: j/k 이동, x 선택, a 승인, c 카테고리, Esc 해제',
      hi: 'कुंजियाँ: j/k चलें, x चुनें, a स्वीकृत, c श्रेणी, Esc हटाएँ',
      nl: 'Toetsen: j/k bewegen, x selecteren, a goedkeuren, c categorie, Esc wissen',
      sv: 'Tangenter: j/k flytta, x markera, a godkänn, c kategori, Esc rensa',
      vi: 'Phím: j/k di chuyển, x chọn, a duyệt, c danh mục, Esc bỏ chọn',
      id: 'Tombol: j/k pindah, x pilih, a setujui, c kategori, Esc hapus',
      da: 'Taster: j/k flyt, x vælg, a godkend, c kategori, Esc ryd',
      nb: 'Taster: j/k flytt, x velg, a godkjenn, c kategori, Esc tøm',
      nn: 'Tastar: j/k flytt, x vel, a godkjenn, c kategori, Esc tøm',
      fi: 'Näppäimet: j/k siirrä, x valitse, a hyväksy, c luokka, Esc tyhjennä',
      is: 'Lyklar: j/k færa, x velja, a samþykkja, c flokkur, Esc hreinsa',
      fo: 'Knappar: j/k flyt, x vel, a góðkenn, c bólkur, Esc strika',
      cs: 'Klávesy: j/k pohyb, x vybrat, a schválit, c kategorie, Esc zrušit',
      bg: 'Клавиши: j/k движение, x избор, a одобряване, c категория, Esc изчистване',
      hr: 'Tipke: j/k pomak, x odaberi, a odobri, c kategorija, Esc poništi',
      sr: 'Тастери: j/k померање, x изабери, a одобри, c категорија, Esc поништи',
      sl: 'Tipke: j/k premik, x izberi, a odobri, c kategorija, Esc počisti',
      mk: 'Копчиња: j/k движење, x избери, a одобри, c категорија, Esc исчисти',
      be: 'Клавішы: j/k рух, x выбраць, a ухваліць, c катэгорыя, Esc ачысціць',
      bs: 'Tipke: j/k pomak, x odaberi, a odobri, c kategorija, Esc poništi',
      hsb: 'Tasty: j/k přesunyć, x wubrać, a přizwolić, c kategorija, Esc zhašeć',
    }),
    swipeHint: t({
      ru: 'Свайп вправо — утвердить, влево — пропустить',
      en: 'Swipe right to approve, left to skip',
      kk: 'Оңға сырғыту — бекіту, солға — өткізу',
      de: 'Nach rechts wischen: bestätigen, nach links: überspringen',
      fr: 'Glisser à droite pour approuver, à gauche pour passer',
      es: 'Desliza a la derecha para aprobar, a la izquierda para saltar',
      pt: 'Deslize para a direita para aprovar, para a esquerda para saltar',
      tr: 'Onaylamak için sağa, atlamak için sola kaydır',
      uk: 'Свайп праворуч — затвердити, ліворуч — пропустити',
      zh: '右滑批准，左滑跳过',
      pl: 'Przesuń w prawo, by zatwierdzić, w lewo, by pominąć',
      it: 'Scorri a destra per approvare, a sinistra per saltare',
      sk: 'Potiahnite doprava na schválenie, doľava na preskočenie',
      ja: '右スワイプで承認、左スワイプでスキップ',
      ko: '오른쪽으로 밀어 승인, 왼쪽으로 밀어 건너뛰기',
      hi: 'स्वीकृत करने के लिए दाएँ, छोड़ने के लिए बाएँ स्वाइप करें',
      nl: 'Veeg naar rechts om goed te keuren, naar links om over te slaan',
      sv: 'Svep höger för att godkänna, vänster för att hoppa över',
      vi: 'Vuốt phải để duyệt, vuốt trái để bỏ qua',
      id: 'Geser kanan untuk menyetujui, kiri untuk melewati',
      da: 'Stryg til højre for at godkende, til venstre for at springe over',
      nb: 'Sveip til høyre for å godkjenne, til venstre for å hoppe over',
      nn: 'Sveip til høgre for å godkjenne, til venstre for å hoppe over',
      fi: 'Pyyhkäise oikealle hyväksyäksesi, vasemmalle ohittaaksesi',
      is: 'Strjúktu til hægri til að samþykkja, til vinstri til að sleppa',
      fo: 'Strúka til høgru fyri at góðkenna, til vinstru fyri at leypa um',
      cs: 'Přejeďte doprava pro schválení, doleva pro přeskočení',
      bg: 'Плъзнете надясно за одобряване, наляво за пропускане',
      hr: 'Povucite udesno za odobrenje, ulijevo za preskakanje',
      sr: 'Превуците удесно за одобрење, улево за прескакање',
      sl: 'Povlecite desno za odobritev, levo za preskok',
      mk: 'Повлечете десно за одобрување, лево за прескокнување',
      be: 'Правядзіце ўправа, каб ухваліць, улева, каб прапусціць',
      bs: 'Povucite udesno za odobrenje, ulijevo za preskakanje',
      hsb: 'Doprawa śahnyć za přizwolenje, dolěwa za přeskočenje',
    }),
    dateFrom: t({
      ru: 'С',
      en: 'From',
      kk: 'Бастап',
      de: 'Von',
      fr: 'Du',
      es: 'Desde',
      pt: 'De',
      tr: 'Başlangıç',
      uk: 'З',
      zh: '从',
      pl: 'Od',
      it: 'Dal',
      sk: 'Od',
      ja: '開始',
      ko: '시작',
      hi: 'से',
      nl: 'Van',
      sv: 'Från',
      vi: 'Từ',
      id: 'Dari',
      da: 'Fra',
      nb: 'Fra',
      nn: 'Frå',
      fi: 'Alkaen',
      is: 'Frá',
      fo: 'Frá',
      cs: 'Od',
      bg: 'От',
      hr: 'Od',
      sr: 'Од',
      sl: 'Od',
      mk: 'Од',
      be: 'З',
      bs: 'Od',
      hsb: 'Wot',
    }),
    dateTo: t({
      ru: 'По',
      en: 'To',
      kk: 'Дейін',
      de: 'Bis',
      fr: 'Au',
      es: 'Hasta',
      pt: 'Até',
      tr: 'Bitiş',
      uk: 'По',
      zh: '到',
      pl: 'Do',
      it: 'Al',
      sk: 'Do',
      ja: '終了',
      ko: '종료',
      hi: 'तक',
      nl: 'Tot',
      sv: 'Till',
      vi: 'Đến',
      id: 'Sampai',
      da: 'Til',
      nb: 'Til',
      nn: 'Til',
      fi: 'Asti',
      is: 'Til',
      fo: 'Til',
      cs: 'Do',
      bg: 'До',
      hr: 'Do',
      sr: 'До',
      sl: 'Do',
      mk: 'До',
      be: 'Па',
      bs: 'Do',
      hsb: 'Do',
    }),
    loadError: t({
      ru: 'Не удалось загрузить очередь',
      en: 'Failed to load the inbox',
      kk: 'Кезекті жүктеу мүмкін болмады',
      de: 'Posteingang konnte nicht geladen werden',
      fr: 'Échec du chargement de la boîte',
      es: 'No se pudo cargar la bandeja',
      pt: 'Falha ao carregar a caixa',
      tr: 'Gelen kutusu yüklenemedi',
      uk: 'Не вдалося завантажити чергу',
      zh: '加载收件箱失败',
      pl: 'Nie udało się załadować skrzynki',
      it: 'Impossibile caricare la posta',
      sk: 'Nepodarilo sa načítať schránku',
      ja: '受信箱を読み込めませんでした',
      ko: '검토함을 불러오지 못했습니다',
      hi: 'इनबॉक्स लोड नहीं हो सका',
      nl: 'Postvak laden mislukt',
      sv: 'Det gick inte att läsa in inkorgen',
      vi: 'Không tải được hộp thư',
      id: 'Gagal memuat kotak masuk',
      da: 'Indbakken kunne ikke indlæses',
      nb: 'Kunne ikke laste innboksen',
      nn: 'Kunne ikkje laste innboksen',
      fi: 'Saapuneiden lataaminen epäonnistui',
      is: 'Ekki tókst að hlaða innhólfinu',
      fo: 'Tað eydnaðist ikki at heinta innbakkan',
      cs: 'Schránku se nepodařilo načíst',
      bg: 'Опашката не можа да се зареди',
      hr: 'Učitavanje sandučića nije uspjelo',
      sr: 'Учитавање сандучета није успело',
      sl: 'Nabiralnika ni bilo mogoče naložiti',
      mk: 'Сандачето не може да се вчита',
      be: 'Не ўдалося загрузіць чаргу',
      bs: 'Učitavanje sandučeta nije uspjelo',
      hsb: 'Dochadny póst njeda so začitać',
    }),
    toastApproved: t({
      ru: 'Утверждено: {{count}}',
      en: 'Approved {{count}}',
      kk: 'Бекітілді: {{count}}',
      de: '{{count}} bestätigt',
      fr: '{{count}} approuvé(s)',
      es: '{{count}} aprobados',
      pt: '{{count}} aprovados',
      tr: '{{count}} onaylandı',
      uk: 'Затверджено: {{count}}',
      zh: '已批准 {{count}} 项',
      pl: 'Zatwierdzono: {{count}}',
      it: '{{count}} approvati',
      sk: 'Schválené: {{count}}',
      ja: '{{count}} 件を承認しました',
      ko: '{{count}}개 승인됨',
      hi: '{{count}} स्वीकृत',
      nl: '{{count}} goedgekeurd',
      sv: '{{count}} godkända',
      vi: 'Đã duyệt {{count}}',
      id: '{{count}} disetujui',
      da: 'Godkendt: {{count}}',
      nb: 'Godkjent: {{count}}',
      nn: 'Godkjent: {{count}}',
      fi: 'Hyväksytty: {{count}}',
      is: 'Samþykkt: {{count}}',
      fo: 'Góðkent: {{count}}',
      cs: 'Schváleno: {{count}}',
      bg: 'Одобрени: {{count}}',
      hr: 'Odobreno: {{count}}',
      sr: 'Одобрено: {{count}}',
      sl: 'Odobreno: {{count}}',
      mk: 'Одобрени: {{count}}',
      be: 'Ухвалена: {{count}}',
      bs: 'Odobreno: {{count}}',
      hsb: 'Přizwolene: {{count}}',
    }),
    toastDone: t({
      ru: 'Готово',
      en: 'Done',
      kk: 'Дайын',
      de: 'Erledigt',
      fr: 'Terminé',
      es: 'Hecho',
      pt: 'Feito',
      tr: 'Tamam',
      uk: 'Готово',
      zh: '完成',
      pl: 'Gotowe',
      it: 'Fatto',
      sk: 'Hotovo',
      ja: '完了',
      ko: '완료',
      hi: 'हो गया',
      nl: 'Klaar',
      sv: 'Klart',
      vi: 'Xong',
      id: 'Selesai',
      da: 'Færdig',
      nb: 'Ferdig',
      nn: 'Ferdig',
      fi: 'Valmis',
      is: 'Lokið',
      fo: 'Liðugt',
      cs: 'Hotovo',
      bg: 'Готово',
      hr: 'Gotovo',
      sr: 'Готово',
      sl: 'Končano',
      mk: 'Готово',
      be: 'Гатова',
      bs: 'Gotovo',
      hsb: 'Hotowe',
    }),
    toastFailed: t({
      ru: 'Не получилось, попробуйте ещё раз',
      en: 'Something went wrong, try again',
      kk: 'Сәтсіз, қайталап көріңіз',
      de: 'Fehlgeschlagen, bitte erneut versuchen',
      fr: 'Échec, réessayez',
      es: 'Algo falló, inténtalo de nuevo',
      pt: 'Algo correu mal, tente novamente',
      tr: 'Bir şeyler ters gitti, tekrar deneyin',
      uk: 'Не вдалося, спробуйте ще раз',
      zh: '出错了，请重试',
      pl: 'Coś poszło nie tak, spróbuj ponownie',
      it: 'Qualcosa è andato storto, riprova',
      sk: 'Niečo sa pokazilo, skúste znova',
      ja: '問題が発生しました。もう一度お試しください',
      ko: '문제가 발생했습니다. 다시 시도하세요',
      hi: 'कुछ गलत हुआ, फिर से प्रयास करें',
      nl: 'Er ging iets mis, probeer opnieuw',
      sv: 'Något gick fel, försök igen',
      vi: 'Có lỗi xảy ra, thử lại',
      id: 'Terjadi kesalahan, coba lagi',
      da: 'Noget gik galt, prøv igen',
      nb: 'Noe gikk galt, prøv igjen',
      nn: 'Noko gjekk gale, prøv igjen',
      fi: 'Jokin meni vikaan, yritä uudelleen',
      is: 'Eitthvað fór úrskeiðis, reyndu aftur',
      fo: 'Okkurt gekk galið, royn aftur',
      cs: 'Něco se pokazilo, zkuste to znovu',
      bg: 'Нещо се обърка, опитайте отново',
      hr: 'Nešto je pošlo po zlu, pokušajte ponovno',
      sr: 'Нешто је пошло наопако, покушајте поново',
      sl: 'Nekaj je šlo narobe, poskusite znova',
      mk: 'Нешто тргна наопаку, обидете се повторно',
      be: 'Нешта пайшло не так, паспрабуйце яшчэ раз',
      bs: 'Nešto je pošlo po zlu, pokušajte ponovo',
      hsb: 'Něšto je so nimokuliło, spytajće hišće raz',
    }),
    uncategorized: t({
      ru: 'Без категории',
      en: 'Uncategorized',
      kk: 'Санатсыз',
      de: 'Nicht kategorisiert',
      fr: 'Non catégorisé',
      es: 'Sin categoría',
      pt: 'Sem categoria',
      tr: 'Kategorisiz',
      uk: 'Без категорії',
      zh: '未分类',
      pl: 'Bez kategorii',
      it: 'Senza categoria',
      sk: 'Bez kategórie',
      ja: '未分類',
      ko: '미분류',
      hi: 'अवर्गीकृत',
      nl: 'Niet gecategoriseerd',
      sv: 'Okategoriserat',
      vi: 'Chưa phân loại',
      id: 'Belum dikategorikan',
      da: 'Ukategoriseret',
      nb: 'Ukategorisert',
      nn: 'Ukategorisert',
      fi: 'Luokittelematon',
      is: 'Óflokkað',
      fo: 'Óbólkað',
      cs: 'Nezařazeno',
      bg: 'Некатегоризирано',
      hr: 'Nekategorizirano',
      sr: 'Некатегоризовано',
      sl: 'Nerazvrščeno',
      mk: 'Некатегоризирано',
      be: 'Некатэгарызавана',
      bs: 'Nekategorizirano',
      hsb: 'Nikategorizowane',
    }),
  },
} satisfies Dictionary;

export default content;
