import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'verifyEmailPage',
  content: {
    title: t({
      ru: 'Подтверждение адреса',
      en: 'Confirming your email',
      kk: 'Мекенжайды растау',
      de: 'E-Mail wird bestätigt',
      fr: 'Confirmation de votre e-mail',
      es: 'Confirmando tu correo',
      pt: 'Confirmando seu e-mail',
      tr: 'E-postanız doğrulanıyor',
      uk: 'Підтвердження адреси',
      zh: '正在确认邮箱',
      ar: 'تأكيد بريدك الإلكتروني',
      pl: 'Potwierdzanie adresu',
      it: 'Conferma della tua email',
      sk: 'Potvrdzovanie adresy',
      ja: 'メールアドレスの確認',
      ko: '이메일 확인 중',
      hi: 'ईमेल की पुष्टि',
      nl: 'E-mailadres bevestigen',
      sv: 'Bekräftar din e-post',
      vi: 'Đang xác nhận email',
      id: 'Mengonfirmasi email Anda',
    }),
    checking: t({
      ru: 'Проверяем ссылку…',
      en: 'Checking the link…',
      kk: 'Сілтеме тексерілуде…',
      de: 'Link wird geprüft…',
      fr: 'Vérification du lien…',
      es: 'Comprobando el enlace…',
      pt: 'Verificando o link…',
      tr: 'Bağlantı kontrol ediliyor…',
      uk: 'Перевіряємо посилання…',
      zh: '正在检查链接…',
      ar: 'جارٍ التحقق من الرابط…',
      pl: 'Sprawdzanie linku…',
      it: 'Verifica del link…',
      sk: 'Kontrolujeme odkaz…',
      ja: 'リンクを確認しています…',
      ko: '링크를 확인하는 중…',
      hi: 'लिंक जाँची जा रही है…',
      nl: 'Link controleren…',
      sv: 'Kontrollerar länken…',
      vi: 'Đang kiểm tra liên kết…',
      id: 'Memeriksa tautan…',
    }),
    success: t({
      ru: 'Адрес подтверждён. Теперь он используется для входа.',
      en: 'Address confirmed. It is now the email for your account.',
      kk: 'Мекенжай расталды. Ол енді есептік жазбаңыздың поштасы.',
      de: 'Adresse bestätigt. Sie ist jetzt die E-Mail Ihres Kontos.',
      fr: 'Adresse confirmée. C’est désormais l’e-mail de votre compte.',
      es: 'Dirección confirmada. Ahora es el correo de tu cuenta.',
      pt: 'Endereço confirmado. Agora é o e-mail da sua conta.',
      tr: 'Adres doğrulandı. Artık hesabınızın e-postası bu.',
      uk: 'Адресу підтверджено. Тепер це пошта вашого облікового запису.',
      zh: '邮箱已确认，现已成为您账户的邮箱。',
      ar: 'تم تأكيد العنوان. أصبح الآن بريد حسابك.',
      pl: 'Adres potwierdzony. To teraz e-mail Twojego konta.',
      it: 'Indirizzo confermato. Ora è l’email del tuo account.',
      sk: 'Adresa potvrdená. Teraz je to e-mail vášho účtu.',
      ja: 'アドレスを確認しました。これがアカウントのメールアドレスになります。',
      ko: '주소가 확인되었습니다. 이제 계정 이메일입니다.',
      hi: 'पता पुष्ट हो गया। अब यही आपके खाते का ईमेल है।',
      nl: 'Adres bevestigd. Dit is nu het e-mailadres van je account.',
      sv: 'Adressen är bekräftad. Det är nu kontots e-post.',
      vi: 'Đã xác nhận địa chỉ. Đây là email tài khoản của bạn.',
      id: 'Alamat dikonfirmasi. Kini menjadi email akun Anda.',
    }),
    missingToken: t({
      ru: 'Ссылка неполная. Запросите смену адреса заново.',
      en: 'This link is incomplete. Request the change again.',
      kk: 'Сілтеме толық емес. Өзгертуді қайта сұраңыз.',
      de: 'Dieser Link ist unvollständig. Fordern Sie die Änderung erneut an.',
      fr: 'Ce lien est incomplet. Redemandez le changement.',
      es: 'Este enlace está incompleto. Solicita el cambio de nuevo.',
      pt: 'Este link está incompleto. Solicite a alteração novamente.',
      tr: 'Bu bağlantı eksik. Değişikliği yeniden isteyin.',
      uk: 'Посилання неповне. Запросіть зміну ще раз.',
      zh: '此链接不完整，请重新申请更改。',
      ar: 'هذا الرابط غير مكتمل. اطلب التغيير مرة أخرى.',
      pl: 'Ten link jest niepełny. Poproś o zmianę ponownie.',
      it: 'Questo link è incompleto. Richiedi di nuovo la modifica.',
      sk: 'Tento odkaz je neúplný. Vyžiadajte si zmenu znova.',
      ja: 'このリンクは不完全です。変更をもう一度リクエストしてください。',
      ko: '이 링크가 올바르지 않습니다. 변경을 다시 요청해 주세요.',
      hi: 'यह लिंक अधूरा है। बदलाव का अनुरोध दोबारा करें।',
      nl: 'Deze link is onvolledig. Vraag de wijziging opnieuw aan.',
      sv: 'Länken är ofullständig. Begär ändringen igen.',
      vi: 'Liên kết này không đầy đủ. Hãy yêu cầu thay đổi lại.',
      id: 'Tautan ini tidak lengkap. Minta perubahan lagi.',
    }),
    genericError: t({
      ru: 'Не удалось подтвердить адрес. Возможно, ссылка устарела.',
      en: 'Could not confirm the address. The link may have expired.',
      kk: 'Мекенжайды растау мүмкін болмады. Сілтеме ескірген болуы мүмкін.',
      de: 'Die Adresse konnte nicht bestätigt werden. Der Link ist möglicherweise abgelaufen.',
      fr: 'Impossible de confirmer l’adresse. Le lien a peut-être expiré.',
      es: 'No se pudo confirmar la dirección. Es posible que el enlace haya caducado.',
      pt: 'Não foi possível confirmar o endereço. O link pode ter expirado.',
      tr: 'Adres doğrulanamadı. Bağlantının süresi dolmuş olabilir.',
      uk: 'Не вдалося підтвердити адресу. Можливо, посилання застаріло.',
      zh: '无法确认邮箱，链接可能已过期。',
      ar: 'تعذّر تأكيد العنوان. ربما انتهت صلاحية الرابط.',
      pl: 'Nie udało się potwierdzić adresu. Link mógł wygasnąć.',
      it: 'Impossibile confermare l’indirizzo. Il link potrebbe essere scaduto.',
      sk: 'Adresu sa nepodarilo potvrdiť. Odkaz mohol vypršať.',
      ja: 'アドレスを確認できませんでした。リンクの有効期限が切れている可能性があります。',
      ko: '주소를 확인하지 못했습니다. 링크가 만료되었을 수 있습니다.',
      hi: 'पता पुष्ट नहीं हो सका। लिंक की अवधि समाप्त हो सकती है।',
      nl: 'Kon het adres niet bevestigen. De link is mogelijk verlopen.',
      sv: 'Kunde inte bekräfta adressen. Länken kan ha gått ut.',
      vi: 'Không xác nhận được địa chỉ. Liên kết có thể đã hết hạn.',
      id: 'Tidak dapat mengonfirmasi alamat. Tautan mungkin sudah kedaluwarsa.',
    }),
    backToLogin: t({
      ru: 'Перейти ко входу',
      en: 'Go to sign in',
      kk: 'Кіру бетіне өту',
      de: 'Zur Anmeldung',
      fr: 'Aller à la connexion',
      es: 'Ir a iniciar sesión',
      pt: 'Ir para entrar',
      tr: 'Girişe git',
      uk: 'Перейти до входу',
      zh: '前往登录',
      ar: 'الانتقال لتسجيل الدخول',
      pl: 'Przejdź do logowania',
      it: 'Vai all’accesso',
      sk: 'Prejsť na prihlásenie',
      ja: 'ログインへ',
      ko: '로그인으로 이동',
      hi: 'साइन इन पर जाएँ',
      nl: 'Naar inloggen',
      sv: 'Gå till inloggning',
      vi: 'Đến trang đăng nhập',
      id: 'Ke halaman masuk',
    }),
  },
} satisfies Dictionary;

export default content;
