/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'receiptParsedDataForm',
  content: {
    vendor: t({
      ru: 'Продавец',
      en: 'Vendor',
      kk: 'Сатушы',
      de: 'Händler',
      fr: 'Commerçant',
      es: 'Comercio',
      pt: 'Fornecedor',
      tr: 'Satıcı',
      uk: 'Продавець',
      zh: '商家',
      pl: 'Sprzedawca',
      it: 'Esercente',
      sk: 'Predajca',
      ja: '店舗',
      ko: '판매처',
      hi: 'विक्रेता',
      nl: 'Verkoper',
      sv: 'Säljare',
      vi: 'Người bán',
      id: 'Penjual',
      da: 'Leverandør',
      nb: 'Leverandør',
      nn: 'Leverandør',
      fi: 'Toimittaja',
      is: 'Seljandi',
      fo: 'Veitari',
      cs: 'Dodavatel',
      bg: 'Доставчик',
      hr: 'Dobavljač',
      sr: 'Добављач',
      sl: 'Dobavitelj',
      mk: 'Доставувач',
      be: 'Пастаўшчык',
      bs: 'Dobavljač',
      hsb: 'Dodawar',
    }),
    date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
      da: 'Dato',
      nb: 'Dato',
      nn: 'Dato',
      fi: 'Päivämäärä',
      is: 'Dagsetning',
      fo: 'Dato',
      cs: 'Datum',
      bg: 'Дата',
      hr: 'Datum',
      sr: 'Датум',
      sl: 'Datum',
      mk: 'Датум',
      be: 'Дата',
      bs: 'Datum',
      hsb: 'Datum',
    }),
    amount: t({
      ru: 'Сумма',
      en: 'Amount',
      kk: 'Сома',
      de: 'Betrag',
      fr: 'Montant',
      es: 'Importe',
      pt: 'Valor',
      tr: 'Tutar',
      uk: 'Сума',
      zh: '金额',
      pl: 'Kwota',
      it: 'Importo',
      sk: 'Suma',
      ja: '金額',
      ko: '금액',
      hi: 'राशि',
      nl: 'Bedrag',
      sv: 'Belopp',
      vi: 'Số tiền',
      id: 'Jumlah',
      da: 'Beløb',
      nb: 'Beløp',
      nn: 'Beløp',
      fi: 'Summa',
      is: 'Fjárhæð',
      fo: 'Sum',
      cs: 'Částka',
      bg: 'Сума',
      hr: 'Iznos',
      sr: 'Износ',
      sl: 'Znesek',
      mk: 'Сума',
      be: 'Сума',
      bs: 'Iznos',
      hsb: 'Suma',
    }),
    currency: t({
      ru: 'Валюта',
      en: 'Currency',
      kk: 'Валюта',
      de: 'Währung',
      fr: 'Devise',
      es: 'Moneda',
      pt: 'Moeda',
      tr: 'Para birimi',
      uk: 'Валюта',
      zh: '货币',
      pl: 'Waluta',
      it: 'Valuta',
      sk: 'Mena',
      ja: '通貨',
      ko: '통화',
      hi: 'मुद्रा',
      nl: 'Valuta',
      sv: 'Valuta',
      vi: 'Tiền tệ',
      id: 'Mata uang',
      da: 'Valuta',
      nb: 'Valuta',
      nn: 'Valuta',
      fi: 'Valuutta',
      is: 'Mynt',
      fo: 'Gjaldoyra',
      cs: 'Měna',
      bg: 'Валута',
      hr: 'Valuta',
      sr: 'Валута',
      sl: 'Valuta',
      mk: 'Валута',
      be: 'Валюта',
      bs: 'Valuta',
      hsb: 'Waluta',
    }),
    tax: t({
      ru: 'Налог',
      en: 'Tax',
      kk: 'Салық',
      de: 'Steuer',
      fr: 'Taxe',
      es: 'Impuesto',
      pt: 'Imposto',
      tr: 'Vergi',
      uk: 'Податок',
      zh: '税额',
      pl: 'Podatek',
      it: 'Imposta',
      sk: 'Daň',
      ja: '税額',
      ko: '세금',
      hi: 'कर',
      nl: 'Belasting',
      sv: 'Skatt',
      vi: 'Thuế',
      id: 'Pajak',
      da: 'Moms',
      nb: 'Mva',
      nn: 'Mva',
      fi: 'Vero',
      is: 'Skattur',
      fo: 'Skattur',
      cs: 'Daň',
      bg: 'Данък',
      hr: 'Porez',
      sr: 'Порез',
      sl: 'Davek',
      mk: 'Данок',
      be: 'Падатак',
      bs: 'Porez',
      hsb: 'Dawk',
    }),
    paymentMethod: t({
      ru: 'Способ оплаты',
      en: 'Payment method',
      kk: 'Төлем тәсілі',
      de: 'Zahlungsmethode',
      fr: 'Moyen de paiement',
      es: 'Método de pago',
      pt: 'Forma de pagamento',
      tr: 'Ödeme yöntemi',
      uk: 'Спосіб оплати',
      zh: '支付方式',
      pl: 'Metoda płatności',
      it: 'Metodo di pagamento',
      sk: 'Spôsob platby',
      ja: '支払い方法',
      ko: '결제 수단',
      hi: 'भुगतान का तरीका',
      nl: 'Betaalmethode',
      sv: 'Betalningsmetod',
      vi: 'Phương thức thanh toán',
      id: 'Metode pembayaran',
      da: 'Betalingsmetode',
      nb: 'Betalingsmåte',
      nn: 'Betalingsmåte',
      fi: 'Maksutapa',
      is: 'Greiðslumáti',
      fo: 'Gjaldingarmáti',
      cs: 'Způsob platby',
      bg: 'Начин на плащане',
      hr: 'Način plaćanja',
      sr: 'Начин плаћања',
      sl: 'Način plačila',
      mk: 'Начин на плаќање',
      be: 'Спосаб аплаты',
      bs: 'Način plaćanja',
      hsb: 'Wašnja zapłaćenja',
    }),
    selectPaymentMethod: t({
      ru: 'Выберите способ оплаты',
      en: 'Select payment method',
      kk: 'Төлем тәсілін таңдаңыз',
      de: 'Zahlungsmethode auswählen',
      fr: 'Choisissez un moyen de paiement',
      es: 'Seleccione el método de pago',
      pt: 'Selecione a forma de pagamento',
      tr: 'Ödeme yöntemi seçin',
      uk: 'Виберіть спосіб оплати',
      zh: '选择支付方式',
      pl: 'Wybierz metodę płatności',
      it: 'Seleziona il metodo di pagamento',
      sk: 'Vyberte spôsob platby',
      ja: '支払い方法を選択',
      ko: '결제 수단 선택',
      hi: 'भुगतान का तरीका चुनें',
      nl: 'Selecteer betaalmethode',
      sv: 'Välj betalningsmetod',
      vi: 'Chọn phương thức thanh toán',
      id: 'Pilih metode pembayaran',
      da: 'Vælg betalingsmetode',
      nb: 'Velg betalingsmåte',
      nn: 'Vel betalingsmåte',
      fi: 'Valitse maksutapa',
      is: 'Veldu greiðslumáta',
      fo: 'Vel gjaldingarmáta',
      cs: 'Vyberte způsob platby',
      bg: 'Изберете начин на плащане',
      hr: 'Odaberite način plaćanja',
      sr: 'Изаберите начин плаћања',
      sl: 'Izberite način plačila',
      mk: 'Изберете начин на плаќање',
      be: 'Выберыце спосаб аплаты',
      bs: 'Odaberite način plaćanja',
      hsb: 'Wubjerće wašnju zapłaćenja',
    }),
    paymentCard: t({
      ru: 'Карта',
      en: 'Card',
      kk: 'Карта',
      de: 'Karte',
      fr: 'Carte',
      es: 'Tarjeta',
      pt: 'Cartão',
      tr: 'Kart',
      uk: 'Картка',
      zh: '银行卡',
      pl: 'Karta',
      it: 'Carta',
      sk: 'Karta',
      ja: 'カード',
      ko: '카드',
      hi: 'कार्ड',
      nl: 'Kaart',
      sv: 'Kort',
      vi: 'Thẻ',
      id: 'Kartu',
      da: 'Kort',
      nb: 'Kort',
      nn: 'Kort',
      fi: 'Kortti',
      is: 'Kort',
      fo: 'Kort',
      cs: 'Karta',
      bg: 'Карта',
      hr: 'Kartica',
      sr: 'Картица',
      sl: 'Kartica',
      mk: 'Картичка',
      be: 'Карта',
      bs: 'Kartica',
      hsb: 'Karta',
    }),
    paymentCash: t({
      ru: 'Наличные',
      en: 'Cash',
      kk: 'Қолма-қол ақша',
      de: 'Bargeld',
      fr: 'Espèces',
      es: 'Efectivo',
      pt: 'Dinheiro',
      tr: 'Nakit',
      uk: 'Готівка',
      zh: '现金',
      pl: 'Gotówka',
      it: 'Contanti',
      sk: 'Hotovosť',
      ja: '現金',
      ko: '현금',
      hi: 'नकद',
      nl: 'Contant',
      sv: 'Kontanter',
      vi: 'Tiền mặt',
      id: 'Tunai',
      da: 'Kontant',
      nb: 'Kontant',
      nn: 'Kontant',
      fi: 'Käteinen',
      is: 'Reiðufé',
      fo: 'Reiðan pening',
      cs: 'Hotově',
      bg: 'В брой',
      hr: 'Gotovina',
      sr: 'Готовина',
      sl: 'Gotovina',
      mk: 'Готовина',
      be: 'Наяўныя',
      bs: 'Gotovina',
      hsb: 'Hotownosć',
    }),
    paymentBankTransfer: t({
      ru: 'Банковский перевод',
      en: 'Bank transfer',
      kk: 'Банк аударымы',
      de: 'Banküberweisung',
      fr: 'Virement bancaire',
      es: 'Transferencia bancaria',
      pt: 'Transferência bancária',
      tr: 'Banka havalesi',
      uk: 'Банківський переказ',
      zh: '银行转账',
      pl: 'Przelew bankowy',
      it: 'Bonifico bancario',
      sk: 'Bankový prevod',
      ja: '銀行振込',
      ko: '계좌 이체',
      hi: 'बैंक ट्रांसफ़र',
      nl: 'Bankoverschrijving',
      sv: 'Banköverföring',
      vi: 'Chuyển khoản ngân hàng',
      id: 'Transfer bank',
      da: 'Bankoverførsel',
      nb: 'Bankoverføring',
      nn: 'Bankoverføring',
      fi: 'Pankkisiirto',
      is: 'Millifærsla',
      fo: 'Bankaflyting',
      cs: 'Bankovní převod',
      bg: 'Банков превод',
      hr: 'Bankovni prijenos',
      sr: 'Банковни пренос',
      sl: 'Bančno nakazilo',
      mk: 'Банкарски пренос',
      be: 'Банкаўскі пераказ',
      bs: 'Bankovni prenos',
      hsb: 'Bankowe přenjesenje',
    }),
    paymentOther: t({
      ru: 'Другое',
      en: 'Other',
      kk: 'Басқа',
      de: 'Sonstiges',
      fr: 'Autre',
      es: 'Otro',
      pt: 'Outro',
      tr: 'Diğer',
      uk: 'Інше',
      zh: '其他',
      pl: 'Inne',
      it: 'Altro',
      sk: 'Iné',
      ja: 'その他',
      ko: '기타',
      hi: 'अन्य',
      nl: 'Overig',
      sv: 'Övrigt',
      vi: 'Khác',
      id: 'Lainnya',
      da: 'Andet',
      nb: 'Annet',
      nn: 'Anna',
      fi: 'Muu',
      is: 'Annað',
      fo: 'Annað',
      cs: 'Jiný',
      bg: 'Друго',
      hr: 'Drugo',
      sr: 'Друго',
      sl: 'Drugo',
      mk: 'Друго',
      be: 'Іншае',
      bs: 'Drugo',
      hsb: 'Druhe',
    }),
    category: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '类别',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategória',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
      da: 'Kategori',
      nb: 'Kategori',
      nn: 'Kategori',
      fi: 'Kategoria',
      is: 'Kategoría',
      fo: 'Bólkur',
      cs: 'Kategorie',
      bg: 'Категория',
      hr: 'Kategorija',
      sr: 'Категорија',
      sl: 'Kategorija',
      mk: 'Категорија',
      be: 'Катэгорыя',
      bs: 'Kategorija',
      hsb: 'Kategorija',
    }),
    selectCategory: t({
      ru: 'Выберите категорию',
      en: 'Select category',
      kk: 'Санатты таңдаңыз',
      de: 'Kategorie auswählen',
      fr: 'Choisissez une catégorie',
      es: 'Seleccione una categoría',
      pt: 'Selecione a categoria',
      tr: 'Kategori seçin',
      uk: 'Виберіть категорію',
      zh: '选择类别',
      pl: 'Wybierz kategorię',
      it: 'Seleziona una categoria',
      sk: 'Vyberte kategóriu',
      ja: 'カテゴリを選択',
      ko: '카테고리 선택',
      hi: 'श्रेणी चुनें',
      nl: 'Selecteer categorie',
      sv: 'Välj kategori',
      vi: 'Chọn danh mục',
      id: 'Pilih kategori',
      da: 'Vælg kategori',
      nb: 'Velg kategori',
      nn: 'Vel kategori',
      fi: 'Valitse luokka',
      is: 'Veldu flokk',
      fo: 'Vel bólk',
      cs: 'Vyberte kategorii',
      bg: 'Изберете категория',
      hr: 'Odaberite kategoriju',
      sr: 'Изаберите категорију',
      sl: 'Izberite kategorijo',
      mk: 'Изберете категорија',
      be: 'Выберыце катэгорыю',
      bs: 'Odaberite kategoriju',
      hsb: 'Wubjerće kategoriju',
    }),
    transactionType: t({
      ru: 'Тип операции',
      en: 'Transaction type',
      kk: 'Операция түрі',
      de: 'Transaktionsart',
      fr: 'Type de transaction',
      es: 'Tipo de transacción',
      pt: 'Tipo de transação',
      tr: 'İşlem türü',
      uk: 'Тип операції',
      zh: '交易类型',
      pl: 'Typ transakcji',
      it: 'Tipo di transazione',
      sk: 'Typ transakcie',
      ja: '取引の種類',
      ko: '거래 유형',
      hi: 'लेनदेन का प्रकार',
      nl: 'Transactietype',
      sv: 'Transaktionstyp',
      vi: 'Loại giao dịch',
      id: 'Jenis transaksi',
      da: 'Transaktionstype',
      nb: 'Transaksjonstype',
      nn: 'Transaksjonstype',
      fi: 'Tapahtuman tyyppi',
      is: 'Tegund færslu',
      fo: 'Slag av postering',
      cs: 'Typ transakce',
      bg: 'Вид транзакция',
      hr: 'Vrsta transakcije',
      sr: 'Врста трансакције',
      sl: 'Vrsta transakcije',
      mk: 'Вид трансакција',
      be: 'Тып транзакцыі',
      bs: 'Vrsta transakcije',
      hsb: 'Typ transakcije',
    }),
    typeExpense: t({
      ru: 'Расход',
      en: 'Expense',
      kk: 'Шығыс',
      de: 'Ausgabe',
      fr: 'Dépense',
      es: 'Gasto',
      pt: 'Despesa',
      tr: 'Gider',
      uk: 'Витрата',
      zh: '支出',
      pl: 'Wydatek',
      it: 'Spesa',
      sk: 'Výdavok',
      ja: '支出',
      ko: '지출',
      hi: 'खर्च',
      nl: 'Uitgave',
      sv: 'Utgift',
      vi: 'Chi tiêu',
      id: 'Pengeluaran',
      da: 'Udgift',
      nb: 'Utgift',
      nn: 'Utgift',
      fi: 'Meno',
      is: 'Útgjöld',
      fo: 'Útgjald',
      cs: 'Výdaj',
      bg: 'Разход',
      hr: 'Rashod',
      sr: 'Расход',
      sl: 'Izdatek',
      mk: 'Трошок',
      be: 'Выдатак',
      bs: 'Rashod',
      hsb: 'Wudawk',
    }),
    typeIncome: t({
      ru: 'Доход',
      en: 'Income',
      kk: 'Кіріс',
      de: 'Einnahme',
      fr: 'Revenu',
      es: 'Ingreso',
      pt: 'Receita',
      tr: 'Gelir',
      uk: 'Дохід',
      zh: '收入',
      pl: 'Przychód',
      it: 'Entrata',
      sk: 'Príjem',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomsten',
      sv: 'Inkomst',
      vi: 'Thu nhập',
      id: 'Pemasukan',
      da: 'Indtægt',
      nb: 'Inntekt',
      nn: 'Inntekt',
      fi: 'Tulo',
      is: 'Tekjur',
      fo: 'Inntøka',
      cs: 'Příjem',
      bg: 'Приход',
      hr: 'Prihod',
      sr: 'Приход',
      sl: 'Prihodek',
      mk: 'Приход',
      be: 'Прыбытак',
      bs: 'Prihod',
      hsb: 'Dochod',
    }),
    typeTransfer: t({
      ru: 'Перевод',
      en: 'Transfer',
      kk: 'Аударым',
      de: 'Umbuchung',
      fr: 'Virement',
      es: 'Transferencia',
      pt: 'Transferência',
      tr: 'Transfer',
      uk: 'Переказ',
      zh: '转账',
      pl: 'Przelew',
      it: 'Trasferimento',
      sk: 'Prevod',
      ja: '振替',
      ko: '이체',
      hi: 'ट्रांसफ़र',
      nl: 'Overboeking',
      sv: 'Överföring',
      vi: 'Chuyển khoản',
      id: 'Transfer',
      da: 'Overførsel',
      nb: 'Overføring',
      nn: 'Overføring',
      fi: 'Siirto',
      is: 'Millifærsla',
      fo: 'Flyting',
      cs: 'Převod',
      bg: 'Превод',
      hr: 'Prijenos',
      sr: 'Пренос',
      sl: 'Prenos',
      mk: 'Пренос',
      be: 'Пераказ',
      bs: 'Prenos',
      hsb: 'Přenjesenje',
    }),
    typeUnknown: t({
      ru: 'Неизвестно',
      en: 'Unknown',
      kk: 'Белгісіз',
      de: 'Unbekannt',
      fr: 'Inconnu',
      es: 'Desconocido',
      pt: 'Desconhecido',
      tr: 'Bilinmiyor',
      uk: 'Невідомо',
      zh: '未知',
      pl: 'Nieznany',
      it: 'Sconosciuto',
      sk: 'Neznámy',
      ja: '不明',
      ko: '알 수 없음',
      hi: 'अज्ञात',
      nl: 'Onbekend',
      sv: 'Okänd',
      vi: 'Không xác định',
      id: 'Tidak diketahui',
      da: 'Filtre',
      nb: 'Filtre',
      nn: 'Filter',
      fi: 'Suodattimet',
      is: 'Síur',
      fo: 'Síur',
      cs: 'Filtry',
      bg: 'Филтри',
      hr: 'Filtri',
      sr: 'Филтери',
      sl: 'Filtri',
      mk: 'Филтри',
      be: 'Фільтры',
      bs: 'Filteri',
      hsb: 'Filtry',
    }),
    lineItems: t({
      ru: 'Позиции',
      en: 'Line items',
      kk: 'Позициялар',
      de: 'Positionen',
      fr: 'Articles',
      es: 'Artículos',
      pt: 'Itens',
      tr: 'Kalemler',
      uk: 'Позиції',
      zh: '明细项目',
      pl: 'Pozycje',
      it: 'Voci',
      sk: 'Položky',
      ja: '明細',
      ko: '품목',
      hi: 'मदें',
      nl: 'Regels',
      sv: 'Rader',
      vi: 'Các mục',
      id: 'Item',
      da: 'Varelinjer',
      nb: 'Varelinjer',
      nn: 'Varelinjer',
      fi: 'Rivit',
      is: 'Línur',
      fo: 'Vørulinjur',
      cs: 'Položky',
      bg: 'Позиции',
      hr: 'Stavke',
      sr: 'Ставке',
      sl: 'Postavke',
      mk: 'Ставки',
      be: 'Пазіцыі',
      bs: 'Stavke',
      hsb: 'Pozicije',
    }),
    addItem: t({
      ru: 'Добавить позицию',
      en: 'Add item',
      kk: 'Позиция қосу',
      de: 'Position hinzufügen',
      fr: 'Ajouter un article',
      es: 'Añadir artículo',
      pt: 'Adicionar item',
      tr: 'Kalem ekle',
      uk: 'Додати позицію',
      zh: '添加项目',
      pl: 'Dodaj pozycję',
      it: 'Aggiungi voce',
      sk: 'Pridať položku',
      ja: '明細を追加',
      ko: '품목 추가',
      hi: 'मद जोड़ें',
      nl: 'Regel toevoegen',
      sv: 'Lägg till rad',
      vi: 'Thêm mục',
      id: 'Tambah item',
      da: 'Tilføj vare',
      nb: 'Legg til vare',
      nn: 'Legg til vare',
      fi: 'Lisää rivi',
      is: 'Bæta línu við',
      fo: 'Legg vøru til',
      cs: 'Přidat položku',
      bg: 'Добавяне на позиция',
      hr: 'Dodaj stavku',
      sr: 'Додај ставку',
      sl: 'Dodaj postavko',
      mk: 'Додај ставка',
      be: 'Дадаць пазіцыю',
      bs: 'Dodaj stavku',
      hsb: 'Poziciju přidać',
    }),
    description: t({
      ru: 'Описание',
      en: 'Description',
      kk: 'Сипаттама',
      de: 'Beschreibung',
      fr: 'Description',
      es: 'Descripción',
      pt: 'Descrição',
      tr: 'Açıklama',
      uk: 'Опис',
      zh: '描述',
      pl: 'Opis',
      it: 'Descrizione',
      sk: 'Popis',
      ja: '説明',
      ko: '설명',
      hi: 'विवरण',
      nl: 'Omschrijving',
      sv: 'Beskrivning',
      vi: 'Mô tả',
      id: 'Deskripsi',
      da: 'Beskrivelse',
      nb: 'Beskrivelse',
      nn: 'Skildring',
      fi: 'Kuvaus',
      is: 'Skýring',
      fo: 'Frágreiðing',
      cs: 'Popis',
      bg: 'Описание',
      hr: 'Opis',
      sr: 'Опис',
      sl: 'Opis',
      mk: 'Опис',
      be: 'Апісанне',
      bs: 'Opis',
      hsb: 'Wopisanje',
    }),
    price: t({
      ru: 'Цена',
      en: 'Price',
      kk: 'Баға',
      de: 'Preis',
      fr: 'Prix',
      es: 'Precio',
      pt: 'Preço',
      tr: 'Fiyat',
      uk: 'Ціна',
      zh: '价格',
      pl: 'Cena',
      it: 'Prezzo',
      sk: 'Cena',
      ja: '価格',
      ko: '가격',
      hi: 'कीमत',
      nl: 'Prijs',
      sv: 'Pris',
      vi: 'Giá',
      id: 'Harga',
      da: 'Pris',
      nb: 'Pris',
      nn: 'Pris',
      fi: 'Hinta',
      is: 'Verð',
      fo: 'Prísur',
      cs: 'Cena',
      bg: 'Цена',
      hr: 'Cijena',
      sr: 'Цена',
      sl: 'Cena',
      mk: 'Цена',
      be: 'Цана',
      bs: 'Cijena',
      hsb: 'Płaćizna',
    }),
    lineItemDescriptionLabel: t({
      ru: 'Описание позиции',
      en: 'Line item description',
      kk: 'Позиция сипаттамасы',
      de: 'Beschreibung der Position',
      fr: "Description de l'article",
      es: 'Descripción del artículo',
      pt: 'Descrição do item',
      tr: 'Kalem açıklaması',
      uk: 'Опис позиції',
      zh: '项目描述',
      pl: 'Opis pozycji',
      it: 'Descrizione della voce',
      sk: 'Popis položky',
      ja: '明細の説明',
      ko: '품목 설명',
      hi: 'मद का विवरण',
      nl: 'Omschrijving van de regel',
      sv: 'Radbeskrivning',
      vi: 'Mô tả mục',
      id: 'Deskripsi item',
      da: 'Beskrivelse af varelinje',
      nb: 'Beskrivelse av varelinje',
      nn: 'Skildring av varelinje',
      fi: 'Rivin kuvaus',
      is: 'Lýsing línu',
      fo: 'Frágreiðing um vørulinju',
      cs: 'Popis položky',
      bg: 'Описание на позицията',
      hr: 'Opis stavke',
      sr: 'Опис ставке',
      sl: 'Opis postavke',
      mk: 'Опис на ставката',
      be: 'Апісанне пазіцыі',
      bs: 'Opis stavke',
      hsb: 'Wopisanje pozicije',
    }),
    lineItemAmountLabel: t({
      ru: 'Сумма позиции',
      en: 'Line item amount',
      kk: 'Позиция сомасы',
      de: 'Betrag der Position',
      fr: "Montant de l'article",
      es: 'Importe del artículo',
      pt: 'Valor do item',
      tr: 'Kalem tutarı',
      uk: 'Сума позиції',
      zh: '项目金额',
      pl: 'Kwota pozycji',
      it: 'Importo della voce',
      sk: 'Suma položky',
      ja: '明細の金額',
      ko: '품목 금액',
      hi: 'मद की राशि',
      nl: 'Bedrag van de regel',
      sv: 'Radbelopp',
      vi: 'Số tiền của mục',
      id: 'Jumlah item',
      da: 'Beløb for varelinje',
      nb: 'Beløp for varelinje',
      nn: 'Beløp for varelinje',
      fi: 'Rivin summa',
      is: 'Fjárhæð línu',
      fo: 'Summa fyri vørulinju',
      cs: 'Částka položky',
      bg: 'Сума на позицията',
      hr: 'Iznos stavke',
      sr: 'Износ ставке',
      sl: 'Znesek postavke',
      mk: 'Сума на ставката',
      be: 'Сума пазіцыі',
      bs: 'Iznos stavke',
      hsb: 'Suma pozicije',
    }),
    removeLineItem: t({
      ru: 'Удалить позицию {name}',
      en: 'Remove line item {name}',
      kk: '{name} позициясын жою',
      de: 'Position {name} entfernen',
      fr: "Supprimer l'article {name}",
      es: 'Eliminar el artículo {name}',
      pt: 'Remover o item {name}',
      tr: '{name} kalemini kaldır',
      uk: 'Видалити позицію {name}',
      zh: '删除项目 {name}',
      pl: 'Usuń pozycję {name}',
      it: 'Rimuovi la voce {name}',
      sk: 'Odstrániť položku {name}',
      ja: '明細 {name} を削除',
      ko: '품목 {name} 삭제',
      hi: 'मद {name} हटाएँ',
      nl: 'Regel {name} verwijderen',
      sv: 'Ta bort rad {name}',
      vi: 'Xóa mục {name}',
      id: 'Hapus item {name}',
      da: 'Fjern varelinje {name}',
      nb: 'Fjern varelinje {name}',
      nn: 'Fjern varelinje {name}',
      fi: 'Poista rivi {name}',
      is: 'Fjarlægja línu {name}',
      fo: 'Tak vørulinju {name} av',
      cs: 'Odebrat položku {name}',
      bg: 'Премахване на позиция {name}',
      hr: 'Ukloni stavku {name}',
      sr: 'Уклони ставку {name}',
      sl: 'Odstrani postavko {name}',
      mk: 'Отстрани ставка {name}',
      be: 'Выдаліць пазіцыю {name}',
      bs: 'Ukloni stavku {name}',
      hsb: 'Poziciju {name} wotstronić',
    }),
  },
} satisfies Dictionary;

export default content;
