import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'gmailIntegrationPage',
  content: {
    header: {
      title: t({
        ru: 'Gmail',
        en: 'Gmail',
        kk: 'Gmail',
        de: 'Google Mail',
        fr: 'Gmail',
        es: 'Gmail',
        pt: 'Gmail',
        tr: 'Gmail',
        uk: 'Gmail',
        zh: '邮箱',
        ar: 'بريد جوجل',
        pl: 'Gmaila',
        it: 'Gmail',
        sk: 'Gmail',
        ja: 'Gメール',
        ko: '지메일',
        hi: 'जीमेल',
        nl: 'Gmail',
        sv: 'Gmail',
        vi: 'Gmail',
        id: 'Gmail',
      }),
      subtitle: t({
        ru: 'Подключите Gmail, чтобы автоматически импортировать чеки и счета',
        en: 'Connect Gmail to automatically import receipts and invoices',
        kk: 'Чек пен шоттарды автоматты импорттау үшін Gmail қосыңыз',
        de: 'Verbinden Sie Gmail, um Belege und Rechnungen automatisch zu importieren',
        fr: 'Connectez Gmail pour importer automatiquement les reçus et factures',
        es: 'Conecta Gmail para importar automáticamente recibos y facturas',
        pt: 'Conecte o Gmail para importar automaticamente recibos e faturas',
        tr: "Makbuz ve faturaları otomatik içe aktarmak için Gmail'i bağlayın",
        uk: 'Підключіть Gmail для автоматичного імпорту чеків та рахунків',
        zh: '连接 Gmail 以自动导入收据和发票',
        ar: 'قم بتوصيل Gmail لاستيراد الإيصالات والفواتير تلقائيًا',
        pl: 'Połącz Gmail, aby automatycznie importować paragony i faktury',
        it: 'Collega Gmail per importare automaticamente ricevute e fatture',
        sk: 'Połącz Gmail, aby automatycznie importować paragony i faktury',
        ja: 'Gmailを接続してレシートと請求書を自動的にインポートします',
        ko: 'Gmail을 연결하여 영수증과 청구서를 자동으로 가져오세요',
        hi: 'रसीदें और चालान स्वचालित रूप से आयात करने के लिए Gmail कनेक्ट करें',
        nl: 'Verbind Gmail om automatisch bonnen en facturen te importeren',
        sv: 'Anslut Gmail för att automatiskt importera kvitton och fakturor',
        vi: 'Kết nối Gmail để tự động nhập biên lai và hóa đơn',
        id: 'Hubungkan Gmail untuk mengimpor tanda terima dan faktur secara otomatis',
      }),
    },
    status: {
      connected: t({
        ru: 'Подключено',
        en: 'Connected',
        kk: 'Қосылған',
        de: 'Verbunden',
        fr: 'Connecté',
        es: 'Conectado',
        pt: 'Conectado',
        tr: 'Bağlı',
        uk: 'Підключено',
        zh: '已连接',
        ar: 'متصل',
        pl: 'Połączone',
        it: 'Connesso',
        sk: 'Połączone',
        ja: '接続済み',
        ko: '연결됨',
        hi: 'कनेक्टेड',
        nl: 'Verbonden',
        sv: 'Ansluten',
        vi: 'Đã kết nối',
        id: 'Terhubung',
      }),
      disconnected: t({
        ru: 'Не подключено',
        en: 'Disconnected',
        kk: 'Қосылмаған',
        de: 'Getrennt',
        fr: 'Déconnecté',
        es: 'Desconectado',
        pt: 'Desconectado',
        tr: 'Bağlı değil',
        uk: 'Відключено',
        zh: '未连接',
        ar: 'غير متصل',
        pl: 'Rozłączone',
        it: 'Disconnesso',
        sk: 'Rozłączone',
        ja: '切断済み',
        ko: '연결 끊김',
        hi: 'डिस्कनेक्टेड',
        nl: 'Verbroken',
        sv: 'Frånkopplad',
        vi: 'Đã ngắt kết nối',
        id: 'Terputus',
      }),
      needsReauth: t({
        ru: 'Требуется повторная авторизация',
        en: 'Needs re-authentication',
        kk: 'Қайта авторизация қажет',
        de: 'Erneute Authentifizierung erforderlich',
        fr: 'Réauthentification requise',
        es: 'Requiere reautenticación',
        pt: 'Reautenticação necessária',
        tr: 'Yeniden kimlik doğrulama gerekiyor',
        uk: 'Потрібна повторна авторизація',
        zh: '需要重新认证',
        ar: 'يتطلب إعادة المصادقة',
        pl: 'Wymagane ponowne uwierzytelnienie',
        it: 'Richiesta nuova autenticazione',
        sk: 'Wymagane ponowne uwierzytelnienie',
        ja: '再認証が必要です',
        ko: '재인증 필요',
        hi: 'पुनः प्रमाणीकरण आवश्यक है',
        nl: 'Herverificatie vereist',
        sv: 'Behöver omautentisering',
        vi: 'Cần xác thực lại',
        id: 'Perlu autentikasi ulang',
      }),
      active: t({
        ru: 'Активно',
        en: 'Active',
        kk: 'Белсенді',
        de: 'Aktiv',
        fr: 'Actif',
        es: 'Activo',
        pt: 'Ativo',
        tr: 'Aktif',
        uk: 'Активно',
        zh: '活跃',
        ar: 'نشط',
        pl: 'Aktywne',
        it: 'Attivo',
        sk: 'Aktywne',
        ja: 'アクティブ',
        ko: '활성',
        hi: 'सक्रिय',
        nl: 'Actief',
        sv: 'Aktiv',
        vi: 'Hoạt động',
        id: 'Aktif',
      }),
      inactive: t({
        ru: 'Неактивно',
        en: 'Inactive',
        kk: 'Белсенді емес',
        de: 'Inaktiv',
        fr: 'Inactif',
        es: 'Inactivo',
        pt: 'Inativo',
        tr: 'Pasif',
        uk: 'Неактивно',
        zh: '非活跃',
        ar: 'غير نشط',
        pl: 'Nieaktywne',
        it: 'Inattivo',
        sk: 'Nieaktywne',
        ja: '非アクティブ',
        ko: '비활성',
        hi: 'निष्क्रिय',
        nl: 'Inactief',
        sv: 'Inaktiv',
        vi: 'Không hoạt động',
        id: 'Tidak aktif',
      }),
      enabled: t({
        ru: 'Включено',
        en: 'Enabled',
        kk: 'Қосулы',
        de: 'Aktiviert',
        fr: 'Activé',
        es: 'Habilitado',
        pt: 'Habilitado',
        tr: 'Etkin',
        uk: 'Увімкнено',
        zh: '已启用',
        ar: 'مفعّل',
        pl: 'Włączone',
        it: 'Abilitato',
        sk: 'Włączone',
        ja: '有効',
        ko: '활성화됨',
        hi: 'सक्षम',
        nl: 'Ingeschakeld',
        sv: 'Aktiverad',
        vi: 'Đã bật',
        id: 'Diaktifkan',
      }),
      disabled: t({
        ru: 'Выключено',
        en: 'Disabled',
        kk: 'Өшірулі',
        de: 'Deaktiviert',
        fr: 'Désactivé',
        es: 'Deshabilitado',
        pt: 'Desabilitado',
        tr: 'Devre dışı',
        uk: 'Вимкнено',
        zh: '已禁用',
        ar: 'معطّل',
        pl: 'Wyłączone',
        it: 'Disabilitato',
        sk: 'Wyłączone',
        ja: '無効',
        ko: '비활성화됨',
        hi: 'अक्षम',
        nl: 'Uitgeschakeld',
        sv: 'Inaktiverad',
        vi: 'Đã tắt',
        id: 'Dinonaktifkan',
      }),
    },
    actions: {
      connect: t({
        ru: 'Подключить Gmail',
        en: 'Connect Gmail',
        kk: 'Gmail қосу',
        de: 'Gmail verbinden',
        fr: 'Connecter Gmail',
        es: 'Conectar Gmail',
        pt: 'Conectar Gmail',
        tr: "Gmail'i bağla",
        uk: 'Підключити Gmail',
        zh: '连接 Gmail',
        ar: 'توصيل Gmail',
        pl: 'Połącz Gmail',
        it: 'Connetti Gmail',
        sk: 'Połącz Gmail',
        ja: 'Gmailを接続',
        ko: 'Gmail 연결',
        hi: 'Gmail कनेक्ट करें',
        nl: 'Gmail verbinden',
        sv: 'Anslut Gmail',
        vi: 'Kết nối Gmail',
        id: 'Hubungkan Gmail',
      }),
      reconnect: t({
        ru: 'Переподключить',
        en: 'Reconnect',
        kk: 'Қайта қосу',
        de: 'Erneut verbinden',
        fr: 'Reconnecter',
        es: 'Reconectar',
        pt: 'Reconectar',
        tr: 'Yeniden bağlan',
        uk: 'Перепідключити',
        zh: '重新连接',
        ar: 'إعادة الاتصال',
        pl: 'Połącz ponownie',
        it: 'Riconnetti',
        sk: 'Połącz ponownie',
        ja: '再接続',
        ko: '재연결',
        hi: 'पुनः कनेक्ट करें',
        nl: 'Opnieuw verbinden',
        sv: 'Återanslut',
        vi: 'Kết nối lại',
        id: 'Hubungkan ulang',
      }),
      disconnect: t({
        ru: 'Отключить',
        en: 'Disconnect',
        kk: 'Ажырату',
        de: 'Trennen',
        fr: 'Déconnecter',
        es: 'Desconectar',
        pt: 'Desconectar',
        tr: 'Bağlantıyı kes',
        uk: 'Відключити',
        zh: '断开连接',
        ar: 'قطع الاتصال',
        pl: 'Rozłącz',
        it: 'Disconnetti',
        sk: 'Rozłącz',
        ja: '切断',
        ko: '연결 해제',
        hi: 'डिस्कनेक्ट करें',
        nl: 'Verbinding verbreken',
        sv: 'Koppla från',
        vi: 'Ngắt kết nối',
        id: 'Putuskan',
      }),
      sync: t({
        ru: 'Синхронизировать Gmail',
        en: 'Sync Gmail',
        kk: 'Gmail синхрондау',
        de: 'Gmail synchronisieren',
        fr: 'Synchroniser Gmail',
        es: 'Sincronizar Gmail',
        pt: 'Sincronizar Gmail',
        tr: "Gmail'i senkronize et",
        uk: 'Синхронізувати Gmail',
        zh: '同步 Gmail',
        ar: 'مزامنة Gmail',
        pl: 'Synchronizuj Gmail',
        it: 'Sincronizza Gmail',
        sk: 'Synchronizuj Gmail',
        ja: 'Gmailを同期',
        ko: 'Gmail 동기화',
        hi: 'Gmail सिंक करें',
        nl: 'Gmail synchroniseren',
        sv: 'Synkronisera Gmail',
        vi: 'Đồng bộ Gmail',
        id: 'Sinkronkan Gmail',
      }),
    },
    settings: {
      title: t({
        ru: 'Настройки',
        en: 'Settings',
        kk: 'Баптаулар',
        de: 'Einstellungen',
        fr: 'Paramètres',
        es: 'Configuración',
        pt: 'Configurações',
        tr: 'Ayarlar',
        uk: 'Налаштування',
        zh: '设置',
        ar: 'الإعدادات',
        pl: 'Ustawienia',
        it: 'Impostazioni',
        sk: 'Ustawienia',
        ja: '設定',
        ko: '설정',
        hi: 'सेटिंग्स',
        nl: 'Instellingen',
        sv: 'Inställningar',
        vi: 'Cài đặt',
        id: 'Pengaturan',
      }),
      labelName: t({
        ru: 'Название ярлыка',
        en: 'Label name',
        kk: 'Белгі атауы',
        de: 'Label-Name',
        fr: 'Nom du libellé',
        es: 'Nombre de etiqueta',
        pt: 'Nome do rótulo',
        tr: 'Etiket adı',
        uk: 'Назва мітки',
        zh: '标签名称',
        ar: 'اسم التسمية',
        pl: 'Nazwa etykiety',
        it: 'Nome etichetta',
        sk: 'Nazwa etykiety',
        ja: 'ラベル名',
        ko: '라벨 이름',
        hi: 'लेबल नाम',
        nl: 'Labelnaam',
        sv: 'Etikettnamn',
        vi: 'Tên nhãn',
        id: 'Nama label',
      }),
      lastSync: t({
        ru: 'Последняя синхронизация',
        en: 'Last sync',
        kk: 'Соңғы синхрондау',
        de: 'Letzte Synchronisierung',
        fr: 'Dernière synchronisation',
        es: 'Última sincronización',
        pt: 'Última sincronização',
        tr: 'Son senkronizasyon',
        uk: 'Остання синхронізація',
        zh: '最后同步',
        ar: 'آخر مزامنة',
        pl: 'Ostatnia synchronizacja',
        it: 'Ultima sincronizzazione',
        sk: 'Ostatnia synchronizacja',
        ja: '最終同期',
        ko: '마지막 동기화',
        hi: 'अंतिम सिंक',
        nl: 'Laatste synchronisatie',
        sv: 'Senaste synkronisering',
        vi: 'Đồng bộ lần cuối',
        id: 'Sinkronisasi terakhir',
      }),
      filterEnabled: t({
        ru: 'Включить автоматическую фильтрацию',
        en: 'Enable automatic filtering',
        kk: 'Автоматты сүзуді қосу',
        de: 'Automatische Filterung aktivieren',
        fr: 'Activer le filtrage automatique',
        es: 'Habilitar filtrado automático',
        pt: 'Habilitar filtragem automática',
        tr: 'Otomatik filtrelemeyi etkinleştir',
        uk: 'Увімкнути автоматичне фільтрування',
        zh: '启用自动筛选',
        ar: 'تفعيل التصفية التلقائية',
        pl: 'Włącz automatyczne filtrowanie',
        it: 'Abilita filtro automatico',
        sk: 'Włącz automatyczne filtrowanie',
        ja: '自動フィルタリングを有効にする',
        ko: '자동 필터링 활성화',
        hi: 'स्वचालित फ़िल्टरिंग सक्षम करें',
        nl: 'Automatisch filteren inschakelen',
        sv: 'Aktivera automatisk filtrering',
        vi: 'Bật lọc tự động',
        id: 'Aktifkan penyaringan otomatis',
      }),
      watchStatus: t({
        ru: 'Статус отслеживания',
        en: 'Watch status',
        kk: 'Бақылау статусы',
        de: 'Überwachungsstatus',
        fr: 'Statut de surveillance',
        es: 'Estado de seguimiento',
        pt: 'Status de monitoramento',
        tr: 'İzleme durumu',
        uk: 'Статус відстеження',
        zh: '监控状态',
        ar: 'حالة المراقبة',
        pl: 'Status śledzenia',
        it: 'Stato monitoraggio',
        sk: 'Status śledzenia',
        ja: '監視ステータス',
        ko: '감시 상태',
        hi: 'वॉच स्टेटस',
        nl: 'Bewakingsstatus',
        sv: 'Övervakningsstatus',
        vi: 'Trạng thái theo dõi',
        id: 'Status pemantauan',
      }),
      expires: t({
        ru: 'Истекает',
        en: 'Expires',
        kk: 'Аяқталады',
        de: 'Läuft ab',
        fr: 'Expire',
        es: 'Expira',
        pt: 'Expira',
        tr: 'Sona eriyor',
        uk: 'Закінчується',
        zh: '到期',
        ar: 'تنتهي صلاحيته',
        pl: 'Wygasa',
        it: 'Scade',
        sk: 'Wygasa',
        ja: '有効期限',
        ko: '만료',
        hi: 'समाप्त होता है',
        nl: 'Verloopt',
        sv: 'Upphör',
        vi: 'Hết hạn',
        id: 'Kedaluwarsa',
      }),
      keywords: t({
        ru: 'Ключевые слова',
        en: 'Filter keywords',
        kk: 'Сүзгі сөздері',
        de: 'Schlüsselwörter',
        fr: 'Mots-clés de filtre',
        es: 'Palabras clave de filtro',
        pt: 'Palavras-chave de filtro',
        tr: 'Filtre anahtar kelimeleri',
        uk: 'Ключові слова фільтра',
        zh: '筛选关键词',
        ar: 'كلمات مفتاح التصفية',
        pl: 'Słowa kluczowe filtra',
        it: 'Parole chiave filtro',
        sk: 'Słowa kluczowe filtra',
        ja: 'フィルターキーワード',
        ko: '필터 키워드',
        hi: 'फ़िल्टर कीवर्ड',
        nl: 'Filtersleutelwoorden',
        sv: 'Filterord',
        vi: 'Từ khóa lọc',
        id: 'Kata kunci filter',
      }),
      keywordsPlaceholder: t({
        ru: 'чек, счет, подтверждение заказа',
        en: 'receipt, invoice, order confirmation',
        kk: 'чек, шот, тапсырыс растауы',
        de: 'Beleg, Rechnung, Bestellbestätigung',
        fr: 'reçu, facture, confirmation de commande',
        es: 'recibo, factura, confirmación de pedido',
        pt: 'recibo, fatura, confirmação de pedido',
        tr: 'makbuz, fatura, sipariş onayı',
        uk: 'чек, рахунок, підтвердження замовлення',
        zh: '收据, 发票, 订单确认',
        ar: 'إيصال، فاتورة، تأكيد الطلب',
        pl: 'paragon, faktura, potwierdzenie zamówienia',
        it: 'ricevuta, fattura, conferma ordine',
        sk: 'paragon, faktura, potwierdzenie zamówienia',
        ja: 'レシート、請求書、注文確認',
        ko: '영수증, 청구서, 주문 확인',
        hi: 'रसीद, चालान, ऑर्डर पुष्टि',
        nl: 'bon, factuur, orderbevestiging',
        sv: 'kvitto, faktura, orderbekräftelse',
        vi: 'biên lai, hóa đơn, xác nhận đơn hàng',
        id: 'tanda terima, faktur, konfirmasi pesanan',
      }),
      keywordsHelp: t({
        ru: 'Ключевые слова через запятую для фильтрации писем',
        en: 'Comma-separated keywords for filtering emails',
        kk: 'Электрондық хаттарды сүзуге арналған үтірмен бөлінген сөздер',
        de: 'Durch Komma getrennte Schlüsselwörter zur E-Mail-Filterung',
        fr: 'Mots-clés séparés par des virgules pour filtrer les e-mails',
        es: 'Palabras clave separadas por comas para filtrar correos',
        pt: 'Palavras-chave separadas por vírgula para filtrar e-mails',
        tr: 'E-postaları filtrelemek için virgülle ayrılmış anahtar kelimeler',
        uk: 'Ключові слова через кому для фільтрації листів',
        zh: '用逗号分隔的关键词用于过滤邮件',
        ar: 'كلمات مفتاحية مفصولة بفواصل لتصفية الرسائل',
        pl: 'Słowa kluczowe oddzielone przecinkami do filtrowania e-maili',
        it: 'Parole chiave separate da virgola per filtrare le email',
        sk: 'Słowa kluczowe oddzielone przecinkami do filtrowania e-maili',
        ja: 'メールをフィルタリングするためのカンマ区切りのキーワード',
        ko: '이메일 필터링을 위한 쉼표로 구분된 키워드',
        hi: 'ईमेल फ़िल्टर करने के लिए अल्पविराम से अलग किए गए कीवर्ड',
        nl: "Door komma's gescheiden sleutelwoorden voor het filteren van e-mails",
        sv: 'Kommaseparerade nyckelord för filtrering av e-post',
        vi: 'Từ khóa phân tách bằng dấu phẩy để lọc email',
        id: 'Kata kunci yang dipisahkan koma untuk memfilter email',
      }),
      hasAttachment: t({
        ru: 'Только письма с вложениями',
        en: 'Only emails with attachments',
        kk: 'Тек тіркемесі бар хаттар',
        de: 'Nur E-Mails mit Anhängen',
        fr: 'Uniquement les e-mails avec pièces jointes',
        es: 'Solo correos con archivos adjuntos',
        pt: 'Apenas e-mails com anexos',
        tr: 'Yalnızca ekli e-postalar',
        uk: 'Тільки листи з вкладеннями',
        zh: '仅含附件的邮件',
        ar: 'رسائل البريد التي تحتوي على مرفقات فقط',
        pl: 'Tylko e-maile z załącznikami',
        it: 'Solo email con allegati',
        sk: 'Tylko e-maile z załącznikami',
        ja: '添付ファイルのあるメールのみ',
        ko: '첨부 파일이 있는 이메일만',
        hi: 'केवल अटैचमेंट वाले ईमेल',
        nl: 'Alleen e-mails met bijlagen',
        sv: 'Endast e-post med bilagor',
        vi: 'Chỉ email có tệp đính kèm',
        id: 'Hanya email dengan lampiran',
      }),
    },
    toasts: {
      connecting: t({
        ru: 'Подключение к Gmail...',
        en: 'Connecting to Gmail...',
        kk: 'Gmail қосылуда...',
        de: 'Verbindung zu Gmail wird hergestellt...',
        fr: 'Connexion à Gmail en cours...',
        es: 'Conectando a Gmail...',
        pt: 'Conectando ao Gmail...',
        tr: "Gmail'e bağlanılıyor...",
        uk: 'Підключення до Gmail...',
        zh: '正在连接 Gmail...',
        ar: 'جارٍ الاتصال بـ Gmail...',
        pl: 'Łączenie z Gmail...',
        it: 'Connessione a Gmail in corso...',
        sk: 'Łączenie z Gmail...',
        ja: 'Gmailに接続中...',
        ko: 'Gmail에 연결 중...',
        hi: 'Gmail से कनेक्ट हो रहा है...',
        nl: 'Verbinding maken met Gmail...',
        sv: 'Ansluter till Gmail...',
        vi: 'Đang kết nối với Gmail...',
        id: 'Menghubungkan ke Gmail...',
      }),
      connected: t({
        ru: 'Gmail подключен',
        en: 'Gmail connected successfully!',
        kk: 'Gmail сәтті қосылды!',
        de: 'Gmail erfolgreich verbunden!',
        fr: 'Gmail connecté avec succès !',
        es: '¡Gmail conectado correctamente!',
        pt: 'Gmail conectado com sucesso!',
        tr: 'Gmail başarıyla bağlandı!',
        uk: 'Gmail успішно підключено!',
        zh: 'Gmail 连接成功！',
        ar: 'تم توصيل Gmail بنجاح!',
        pl: 'Gmail połączony pomyślnie!',
        it: 'Gmail connesso con successo!',
        sk: 'Gmail połączony pomyślnie!',
        ja: 'Gmailが正常に接続されました！',
        ko: 'Gmail이 성공적으로 연결되었습니다!',
        hi: 'Gmail सफलतापूर्वक कनेक्ट हो गया!',
        nl: 'Gmail succesvol verbonden!',
        sv: 'Gmail ansluten!',
        vi: 'Gmail đã kết nối thành công!',
        id: 'Gmail berhasil terhubung!',
      }),
      disconnected: t({
        ru: 'Gmail отключен',
        en: 'Gmail disconnected',
        kk: 'Gmail ажыратылды',
        de: 'Gmail getrennt',
        fr: 'Gmail déconnecté',
        es: 'Gmail desconectado',
        pt: 'Gmail desconectado',
        tr: 'Gmail bağlantısı kesildi',
        uk: 'Gmail відключено',
        zh: 'Gmail 已断开连接',
        ar: 'تم قطع اتصال Gmail',
        pl: 'Gmail rozłączony',
        it: 'Gmail disconnesso',
        sk: 'Gmail rozłączony',
        ja: 'Gmailの接続が切断されました',
        ko: 'Gmail 연결이 해제되었습니다',
        hi: 'Gmail डिस्कनेक्ट हो गया',
        nl: 'Gmail verbroken',
        sv: 'Gmail frånkopplad',
        vi: 'Gmail đã ngắt kết nối',
        id: 'Gmail terputus',
      }),
      settingsSaved: t({
        ru: 'Настройки сохранены',
        en: 'Settings saved',
        kk: 'Баптаулар сақталды',
        de: 'Einstellungen gespeichert',
        fr: 'Paramètres enregistrés',
        es: 'Configuración guardada',
        pt: 'Configurações salvas',
        tr: 'Ayarlar kaydedildi',
        uk: 'Налаштування збережено',
        zh: '设置已保存',
        ar: 'تم حفظ الإعدادات',
        pl: 'Ustawienia zapisane',
        it: 'Impostazioni salvate',
        sk: 'Ustawienia zapisane',
        ja: '設定が保存されました',
        ko: '설정이 저장되었습니다',
        hi: 'सेटिंग्स सहेजी गई',
        nl: 'Instellingen opgeslagen',
        sv: 'Inställningar sparade',
        vi: 'Đã lưu cài đặt',
        id: 'Pengaturan disimpan',
      }),
      syncStarted: t({
        ru: 'Синхронизация запущена',
        en: 'Gmail sync started',
        kk: 'Синхрондау басталды',
        de: 'Gmail-Synchronisierung gestartet',
        fr: 'Synchronisation Gmail démarrée',
        es: 'Sincronización de Gmail iniciada',
        pt: 'Sincronização do Gmail iniciada',
        tr: 'Gmail senkronizasyonu başlatıldı',
        uk: 'Синхронізацію Gmail розпочато',
        zh: 'Gmail 同步已开始',
        ar: 'بدأت مزامنة Gmail',
        pl: 'Synchronizacja Gmail rozpoczęta',
        it: 'Sincronizzazione Gmail avviata',
        sk: 'Synchronizacja Gmail rozpoczęta',
        ja: 'Gmailの同期が開始されました',
        ko: 'Gmail 동기화가 시작되었습니다',
        hi: 'Gmail सिंक शुरू हो गया',
        nl: 'Gmail synchronisatie gestart',
        sv: 'Gmail-synkronisering startad',
        vi: 'Đồng bộ Gmail đã bắt đầu',
        id: 'Sinkronisasi Gmail dimulai',
      }),
    },
    errors: {
      loadStatus: t({
        ru: 'Не удалось загрузить статус Gmail',
        en: 'Failed to load Gmail integration status',
        kk: 'Gmail статусын жүктеу мүмкін болмады',
        de: 'Gmail-Integrationsstatus konnte nicht geladen werden',
        fr: "Impossible de charger le statut d'intégration Gmail",
        es: 'No se pudo cargar el estado de integración de Gmail',
        pt: 'Falha ao carregar o status de integração do Gmail',
        tr: 'Gmail entegrasyon durumu yüklenemedi',
        uk: 'Не вдалося завантажити статус Gmail',
        zh: '无法加载 Gmail 集成状态',
        ar: 'فشل تحميل حالة تكامل Gmail',
        pl: 'Nie udało się załadować statusu integracji Gmail',
        it: 'Impossibile caricare lo stato di integrazione Gmail',
        sk: 'Nie udało się załadować statusu integracji Gmail',
        ja: 'Gmailの統合ステータスの読み込みに失敗しました',
        ko: 'Gmail 통합 상태를 불러오지 못했습니다',
        hi: 'Gmail एकीकरण स्थिति लोड करने में विफल',
        nl: 'Gmail-integratiestatus laden mislukt',
        sv: 'Det gick inte att läsa in Gmail-integrationsstatus',
        vi: 'Không thể tải trạng thái tích hợp Gmail',
        id: 'Gagal memuat status integrasi Gmail',
      }),
      connectFailed: t({
        ru: 'Не удалось подключить Gmail',
        en: 'Failed to connect Gmail',
        kk: 'Gmail қосу мүмкін болмады',
        de: 'Gmail konnte nicht verbunden werden',
        fr: 'Impossible de connecter Gmail',
        es: 'No se pudo conectar Gmail',
        pt: 'Falha ao conectar o Gmail',
        tr: 'Gmail bağlanamadı',
        uk: 'Не вдалося підключити Gmail',
        zh: '无法连接 Gmail',
        ar: 'فشل الاتصال بـ Gmail',
        pl: 'Nie udało się połączyć Gmail',
        it: 'Impossibile connettere Gmail',
        sk: 'Nie udało się połączyć Gmail',
        ja: 'Gmailの接続に失敗しました',
        ko: 'Gmail 연결에 실패했습니다',
        hi: 'Gmail कनेक्ट करने में विफल',
        nl: 'Gmail verbinden mislukt',
        sv: 'Det gick inte att ansluta Gmail',
        vi: 'Không thể kết nối Gmail',
        id: 'Gagal menghubungkan Gmail',
      }),
      missingOauthUrl: t({
        ru: 'Не удалось получить OAuth ссылку Gmail',
        en: 'Failed to get Gmail OAuth URL',
        kk: 'Gmail OAuth сілтемесін алу мүмкін болмады',
        de: 'Gmail OAuth-URL konnte nicht abgerufen werden',
        fr: "Impossible d'obtenir l'URL OAuth Gmail",
        es: 'No se pudo obtener la URL de OAuth de Gmail',
        pt: 'Falha ao obter URL OAuth do Gmail',
        tr: "Gmail OAuth URL'si alınamadı",
        uk: 'Не вдалося отримати OAuth-посилання Gmail',
        zh: '无法获取 Gmail OAuth URL',
        ar: 'فشل الحصول على رابط OAuth الخاص بـ Gmail',
        pl: 'Nie udało się uzyskać adresu OAuth Gmail',
        it: "Impossibile ottenere l'URL OAuth di Gmail",
        sk: 'Nie udało się uzyskać adresu OAuth Gmail',
        ja: 'Gmail OAuth URLの取得に失敗しました',
        ko: 'Gmail OAuth URL을 가져오지 못했습니다',
        hi: 'Gmail OAuth URL प्राप्त करने में विफल',
        nl: 'Gmail OAuth-URL ophalen mislukt',
        sv: 'Det gick inte att hämta Gmail OAuth-URL',
        vi: 'Không thể lấy URL OAuth của Gmail',
        id: 'Gagal mendapatkan URL OAuth Gmail',
      }),
      disconnectFailed: t({
        ru: 'Не удалось отключить Gmail',
        en: 'Failed to disconnect Gmail',
        kk: 'Gmail ажырату мүмкін болмады',
        de: 'Gmail konnte nicht getrennt werden',
        fr: 'Impossible de déconnecter Gmail',
        es: 'No se pudo desconectar Gmail',
        pt: 'Falha ao desconectar o Gmail',
        tr: 'Gmail bağlantısı kesilemedi',
        uk: 'Не вдалося відключити Gmail',
        zh: '无法断开 Gmail 连接',
        ar: 'فشل قطع اتصال Gmail',
        pl: 'Nie udało się rozłączyć Gmail',
        it: 'Impossibile disconnettere Gmail',
        sk: 'Nie udało się rozłączyć Gmail',
        ja: 'Gmailの切断に失敗しました',
        ko: 'Gmail 연결 해제에 실패했습니다',
        hi: 'Gmail डिस्कनेक्ट करने में विफल',
        nl: 'Gmail verbreken mislukt',
        sv: 'Det gick inte att koppla från Gmail',
        vi: 'Không thể ngắt kết nối Gmail',
        id: 'Gagal memutuskan Gmail',
      }),
      saveFailed: t({
        ru: 'Не удалось сохранить настройки',
        en: 'Failed to save settings',
        kk: 'Баптауларды сақтау мүмкін болмады',
        de: 'Einstellungen konnten nicht gespeichert werden',
        fr: "Impossible d'enregistrer les paramètres",
        es: 'No se pudo guardar la configuración',
        pt: 'Falha ao salvar configurações',
        tr: 'Ayarlar kaydedilemedi',
        uk: 'Не вдалося зберегти налаштування',
        zh: '无法保存设置',
        ar: 'فشل حفظ الإعدادات',
        pl: 'Nie udało się zapisać ustawień',
        it: 'Impossibile salvare le impostazioni',
        sk: 'Nie udało się zapisać ustawień',
        ja: '設定の保存に失敗しました',
        ko: '설정 저장에 실패했습니다',
        hi: 'सेटिंग्स सहेजने में विफल',
        nl: 'Instellingen opslaan mislukt',
        sv: 'Det gick inte att spara inställningar',
        vi: 'Không thể lưu cài đặt',
        id: 'Gagal menyimpan pengaturan',
      }),
      syncFailed: t({
        ru: 'Не удалось синхронизировать Gmail',
        en: 'Failed to sync Gmail',
        kk: 'Gmail синхрондау мүмкін болмады',
        de: 'Gmail konnte nicht synchronisiert werden',
        fr: 'Impossible de synchroniser Gmail',
        es: 'No se pudo sincronizar Gmail',
        pt: 'Falha ao sincronizar o Gmail',
        tr: 'Gmail senkronize edilemedi',
        uk: 'Не вдалося синхронізувати Gmail',
        zh: '无法同步 Gmail',
        ar: 'فشلت مزامنة Gmail',
        pl: 'Nie udało się zsynchronizować Gmail',
        it: 'Impossibile sincronizzare Gmail',
        sk: 'Nie udało się zsynchronizować Gmail',
        ja: 'Gmailの同期に失敗しました',
        ko: 'Gmail 동기화에 실패했습니다',
        hi: 'Gmail सिंक करने में विफल',
        nl: 'Gmail synchroniseren mislukt',
        sv: 'Det gick inte att synkronisera Gmail',
        vi: 'Không thể đồng bộ Gmail',
        id: 'Gagal menyinkronkan Gmail',
      }),
      noMatches: t({
        ru: 'Подходящие письма не найдены',
        en: 'No matching emails found in Gmail',
        kk: 'Сәйкес хаттар табылмады',
        de: 'Keine passenden E-Mails in Gmail gefunden',
        fr: 'Aucun e-mail correspondant trouvé dans Gmail',
        es: 'No se encontraron correos coincidentes en Gmail',
        pt: 'Nenhum e-mail correspondente encontrado no Gmail',
        tr: "Gmail'de eşleşen e-posta bulunamadı",
        uk: 'Відповідні листи не знайдено',
        zh: 'Gmail 中未找到匹配的邮件',
        ar: 'لم يتم العثور على رسائل بريد مطابقة في Gmail',
        pl: 'Nie znaleziono pasujących wiadomości w Gmail',
        it: 'Nessuna email corrispondente trovata in Gmail',
        sk: 'Nie znaleziono pasujących wiadomości w Gmail',
        ja: 'Gmailに一致するメールが見つかりませんでした',
        ko: 'Gmail에서 일치하는 이메일을 찾지 못했습니다',
        hi: 'Gmail में कोई मेल खाने वाला ईमेल नहीं मिला',
        nl: 'Geen overeenkomende e-mails gevonden in Gmail',
        sv: 'Inga matchande e-postmeddelanden hittades i Gmail',
        vi: 'Không tìm thấy email nào khớp trong Gmail',
        id: 'Tidak ada email yang cocok di Gmail',
      }),
      allSynced: t({
        ru: 'Все доступные чеки уже синхронизированы',
        en: 'All receipts available in Gmail are already synced',
        kk: 'Барлық чек синхрондалған',
        de: 'Alle in Gmail verfügbaren Belege sind bereits synchronisiert',
        fr: 'Tous les reçus disponibles dans Gmail sont déjà synchronisés',
        es: 'Todos los recibos disponibles en Gmail ya están sincronizados',
        pt: 'Todos os recibos disponíveis no Gmail já estão sincronizados',
        tr: "Gmail'deki tüm makbuzlar zaten senkronize edildi",
        uk: 'Всі доступні чеки вже синхронізовані',
        zh: 'Gmail 中所有可用的收据已同步',
        ar: 'جميع الإيصالات المتاحة في Gmail متزامنة بالفعل',
        pl: 'Wszystkie paragony dostępne w Gmail są już zsynchronizowane',
        it: 'Tutte le ricevute disponibili in Gmail sono già sincronizzate',
        sk: 'Wszystkie paragony dostępne w Gmail są już zsynchronizowane',
        ja: 'Gmailで利用可能なすべてのレシートはすでに同期されています',
        ko: 'Gmail에서 사용 가능한 모든 영수증이 이미 동기화되었습니다',
        hi: 'Gmail में उपलब्ध सभी रसीदें पहले से ही सिंक हैं',
        nl: 'Alle beschikbare bonnen in Gmail zijn al gesynchroniseerd',
        sv: 'Alla kvitton i Gmail är redan synkroniserade',
        vi: 'Tất cả biên lai có sẵn trong Gmail đã được đồng bộ',
        id: 'Semua tanda terima yang tersedia di Gmail sudah disinkronkan',
      }),
      syncNoNew: t({
        ru: 'Синхронизация завершена без новых чеков',
        en: 'Gmail sync finished with no new receipts',
        kk: 'Жаңа чек табылмады',
        de: 'Gmail-Synchronisierung ohne neue Belege abgeschlossen',
        fr: 'Synchronisation Gmail terminée sans nouveaux reçus',
        es: 'Sincronización de Gmail finalizada sin nuevos recibos',
        pt: 'Sincronização do Gmail concluída sem novos recibos',
        tr: 'Gmail senkronizasyonu yeni makbuz olmadan tamamlandı',
        uk: 'Синхронізація Gmail завершена без нових чеків',
        zh: 'Gmail 同步完成，无新收据',
        ar: 'اكتملت مزامنة Gmail دون إيصالات جديدة',
        pl: 'Synchronizacja Gmail zakończona bez nowych paragonów',
        it: 'Sincronizzazione Gmail completata senza nuove ricevute',
        sk: 'Synchronizacja Gmail zakończona bez nowych paragonów',
        ja: 'Gmailの同期が新しいレシートなしで完了しました',
        ko: 'Gmail 동기화가 새 영수증 없이 완료되었습니다',
        hi: 'Gmail सिंक बिना नई रसीदों के पूरा हुआ',
        nl: 'Gmail-synchronisatie voltooid zonder nieuwe bonnen',
        sv: 'Gmail-synkronisering avslutad utan nya kvitton',
        vi: 'Đồng bộ Gmail hoàn tất mà không có biên lai mới',
        id: 'Sinkronisasi Gmail selesai tanpa tanda terima baru',
      }),
      loginRequired: t({
        ru: 'Войдите, чтобы подключить Gmail',
        en: 'Please sign in to connect Gmail',
        kk: 'Gmail қосу үшін кіріңіз',
        de: 'Bitte melden Sie sich an, um Gmail zu verbinden',
        fr: 'Veuillez vous connecter pour relier Gmail',
        es: 'Inicia sesión para conectar Gmail',
        pt: 'Faça login para conectar o Gmail',
        tr: "Gmail'i bağlamak için giriş yapın",
        uk: 'Увійдіть, щоб підключити Gmail',
        zh: '请登录以连接 Gmail',
        ar: 'يرجى تسجيل الدخول لتوصيل Gmail',
        pl: 'Zaloguj się, aby połączyć Gmail',
        it: 'Accedi per connettere Gmail',
        sk: 'Zaloguj się, aby połączyć Gmail',
        ja: 'Gmailを接続するにはサインインしてください',
        ko: 'Gmail을 연결하려면 로그인하세요',
        hi: 'Gmail कनेक्ट करने के लिए साइन इन करें',
        nl: 'Log in om Gmail te verbinden',
        sv: 'Logga in för att ansluta Gmail',
        vi: 'Vui lòng đăng nhập để kết nối Gmail',
        id: 'Silakan masuk untuk menghubungkan Gmail',
      }),
      authFailed: t({
        ru: 'Не удалось подключить Gmail',
        en: 'Failed to connect Gmail',
        kk: 'Gmail қосу мүмкін болмады',
        de: 'Gmail konnte nicht verbunden werden',
        fr: 'Impossible de connecter Gmail',
        es: 'No se pudo conectar Gmail',
        pt: 'Falha ao conectar o Gmail',
        tr: 'Gmail bağlanamadı',
        uk: 'Не вдалося підключити Gmail',
        zh: '无法连接 Gmail',
        ar: 'فشل الاتصال بـ Gmail',
        pl: 'Nie udało się połączyć Gmail',
        it: 'Impossibile connettere Gmail',
        sk: 'Nie udało się połączyć Gmail',
        ja: 'Gmailの接続に失敗しました',
        ko: 'Gmail 연결에 실패했습니다',
        hi: 'Gmail कनेक्ट करने में विफल',
        nl: 'Gmail verbinden mislukt',
        sv: 'Det gick inte att ansluta Gmail',
        vi: 'Không thể kết nối Gmail',
        id: 'Gagal menghubungkan Gmail',
      }),
    },
    info: {
      title: t({
        ru: 'Как это работает',
        en: 'How it works',
        kk: 'Бұл қалай жұмыс істейді',
        de: 'So funktioniert es',
        fr: 'Comment ça marche',
        es: 'Cómo funciona',
        pt: 'Como funciona',
        tr: 'Nasıl çalışır',
        uk: 'Як це працює',
        zh: '工作原理',
        ar: 'كيف يعمل',
        pl: 'Jak to działa',
        it: 'Come funziona',
        sk: 'Jak to działa',
        ja: '仕組み',
        ko: '작동 방식',
        hi: 'यह कैसे काम करता है',
        nl: 'Hoe het werkt',
        sv: 'Hur det fungerar',
        vi: 'Cách hoạt động',
        id: 'Cara kerjanya',
      }),
      step1: t({
        ru: '1. Подключите Gmail с доступом только на чтение',
        en: '1. Connect your Gmail account with read-only access',
        kk: '1. Gmail аккаунтын тек оқу рұқсатымен қосыңыз',
        de: '1. Verbinden Sie Ihr Gmail-Konto mit Lesezugriff',
        fr: '1. Connectez votre compte Gmail en accès lecture seule',
        es: '1. Conecta tu cuenta de Gmail con acceso de solo lectura',
        pt: '1. Conecte sua conta do Gmail com acesso somente leitura',
        tr: '1. Gmail hesabınızı salt okunur erişimle bağlayın',
        uk: '1. Підключіть Gmail з доступом лише для читання',
        zh: '1. 以只读权限连接您的 Gmail 账户',
        ar: '1. قم بتوصيل حساب Gmail بصلاحية القراءة فقط',
        pl: '1. Połącz konto Gmail z dostępem tylko do odczytu',
        it: '1. Connetti il tuo account Gmail con accesso in sola lettura',
        sk: '1. Połącz konto Gmail z dostępem tylko do odczytu',
        ja: '1. 読み取り専用アクセスでGmailアカウントを接続します',
        ko: '1. 읽기 전용 액세스로 Gmail 계정을 연결하세요',
        hi: '1. केवल-पढ़ने की पहुंच के साथ अपना Gmail खाता कनेक्ट करें',
        nl: '1. Verbind uw Gmail-account met alleen-lezen toegang',
        sv: '1. Anslut ditt Gmail-konto med skrivskyddad åtkomst',
        vi: '1. Kết nối tài khoản Gmail của bạn với quyền chỉ đọc',
        id: '1. Hubungkan akun Gmail Anda dengan akses hanya-baca',
      }),
      step2: t({
        ru: '2. Мы автоматически создадим ярлык "Lumio/Receipts"',
        en: '2. We automatically create a "Lumio/Receipts" label',
        kk: '2. Біз "Lumio/Receipts" белгісін автоматты жасаймыз',
        de: '2. Wir erstellen automatisch ein Label „Lumio/Receipts"',
        fr: '2. Nous créons automatiquement un libellé « Lumio/Receipts »',
        es: '2. Creamos automáticamente una etiqueta "Lumio/Receipts"',
        pt: '2. Criamos automaticamente um rótulo "Lumio/Receipts"',
        tr: '2. Otomatik olarak "Lumio/Receipts" etiketi oluşturuyoruz',
        uk: '2. Ми автоматично створимо мітку "Lumio/Receipts"',
        zh: '2. 我们自动创建 "Lumio/Receipts" 标签',
        ar: '2. نقوم تلقائيًا بإنشاء تسمية "Lumio/Receipts"',
        pl: '2. Automatycznie tworzymy etykietę "Lumio/Receipts"',
        it: '2. Creiamo automaticamente un\'etichetta "Lumio/Receipts"',
        sk: '2. Automatycznie tworzymy etykietę "Lumio/Receipts"',
        ja: '2. "Lumio/Receipts"ラベルを自動的に作成します',
        ko: '2. "Lumio/Receipts" 라벨을 자동으로 생성합니다',
        hi: '2. हम स्वचालित रूप से "Lumio/Receipts" लेबल बनाते हैं',
        nl: '2. We maken automatisch een "Lumio/Receipts" label',
        sv: '2. Vi skapar automatiskt en "Lumio/Receipts" etikett',
        vi: '2. Chúng tôi tự động tạo nhãn "Lumio/Receipts"',
        id: '2. Kami secara otomatis membuat label "Lumio/Receipts"',
      }),
      step3: t({
        ru: '3. Письма по фильтрам будут импортироваться автоматически',
        en: '3. Emails matching your filters are automatically imported',
        kk: '3. Сүзгіге сай хаттар автоматты импортталады',
        de: '3. E-Mails, die Ihren Filtern entsprechen, werden automatisch importiert',
        fr: '3. Les e-mails correspondant à vos filtres sont automatiquement importés',
        es: '3. Los correos que coinciden con tus filtros se importan automáticamente',
        pt: '3. E-mails que correspondem aos seus filtros são importados automaticamente',
        tr: '3. Filtrelerinizle eşleşen e-postalar otomatik olarak içe aktarılır',
        uk: '3. Листи за фільтрами будуть автоматично імпортовані',
        zh: '3. 符合筛选条件的邮件将自动导入',
        ar: '3. يتم استيراد رسائل البريد المطابقة لمرشحاتك تلقائيًا',
        pl: '3. E-maile pasujące do filtrów są automatycznie importowane',
        it: '3. Le email corrispondenti ai tuoi filtri vengono importate automaticamente',
        sk: '3. E-maile pasujące do filtrów są automatycznie importowane',
        ja: '3. フィルターに一致するメールは自動的にインポートされます',
        ko: '3. 필터에 맞는 이메일이 자동으로 가져옵니다',
        hi: '3. आपके फ़िल्टर से मेल खाने वाले ईमेल स्वचालित रूप से आयात होते हैं',
        nl: '3. E-mails die overeenkomen met uw filters worden automatisch geïmporteerd',
        sv: '3. E-postmeddelanden som matchar dina filter importeras automatiskt',
        vi: '3. Email khớp với bộ lọc của bạn được nhập tự động',
        id: '3. Email yang cocok dengan filter Anda diimpor secara otomatis',
      }),
      step4: t({
        ru: '4. Проверяйте и подтверждайте чеки на странице Receipts',
        en: '4. Review and approve receipts in the Receipts page',
        kk: '4. Receipts бетінде чектерді тексеріп растаңыз',
        de: '4. Überprüfen und genehmigen Sie Belege auf der Seite „Receipts"',
        fr: '4. Vérifiez et approuvez les reçus sur la page Receipts',
        es: '4. Revisa y aprueba recibos en la página Receipts',
        pt: '4. Revise e aprove recibos na página Receipts',
        tr: '4. Makbuzları Receipts sayfasında inceleyin ve onaylayın',
        uk: '4. Перевіряйте та підтверджуйте чеки на сторінці Receipts',
        zh: '4. 在收据页面查看并确认收据',
        ar: '4. راجع الإيصالات وافتح صفحة Receipts للموافقة عليها',
        pl: '4. Przeglądaj i zatwierdzaj paragony na stronie Receipts',
        it: '4. Revisiona e approva le ricevute nella pagina Receipts',
        sk: '4. Przeglądaj i zatwierdzaj paragony na stronie Receipts',
        ja: '4. レシートページでレシートを確認・承認してください',
        ko: '4. 영수증 페이지에서 영수증을 검토하고 승인하세요',
        hi: '4. Receipts पेज पर रसीदों की समीक्षा करें और अनुमोदन करें',
        nl: '4. Bekijk en goedkeur bonnen op de Receipts-pagina',
        sv: '4. Granska och godkänn kvitton på Receipts-sidan',
        vi: '4. Xem xét và phê duyệt biên lai trên trang Receipts',
        id: '4. Tinjau dan setujui tanda terima di halaman Receipts',
      }),
    },
    common: {
      loading: t({
        ru: 'Загрузка...',
        en: 'Loading...',
        kk: 'Жүктелуде...',
        de: 'Laden...',
        fr: 'Chargement...',
        es: 'Cargando...',
        pt: 'Carregando...',
        tr: 'Yükleniyor...',
        uk: 'Завантаження...',
        zh: '加载中...',
        ar: 'جارٍ التحميل...',
        pl: 'Ładowanie...',
        it: 'Caricamento...',
        sk: 'Ładowanie...',
        ja: '読み込み中...',
        ko: '로딩 중...',
        hi: 'लोड हो रहा है...',
        nl: 'Laden...',
        sv: 'Laddar...',
        vi: 'Đang tải...',
        id: 'Memuat...',
      }),
      notConnected: t({
        ru: 'Не подключено',
        en: 'Not connected',
        kk: 'Қосылмаған',
        de: 'Nicht verbunden',
        fr: 'Non connecté',
        es: 'No conectado',
        pt: 'Não conectado',
        tr: 'Bağlı değil',
        uk: 'Не підключено',
        zh: '未连接',
        ar: 'غير متصل',
        pl: 'Niepołączone',
        it: 'Non connesso',
        sk: 'Niepołączone',
        ja: '未接続',
        ko: '연결되지 않음',
        hi: 'कनेक्टेड नहीं',
        nl: 'Niet verbonden',
        sv: 'Inte ansluten',
        vi: 'Chưa kết nối',
        id: 'Tidak terhubung',
      }),
      unknownDate: t({
        ru: '—',
        en: '—',
        kk: '—',
        de: '—',
        fr: '—',
        es: '—',
        pt: '—',
        tr: '—',
        uk: '—',
        zh: '—',
        ar: '—',
        pl: '—',
        it: '—',
        sk: '—',
        ja: '—',
        ko: '—',
        hi: '—',
        nl: '—',
        sv: '—',
        vi: '—',
        id: '—',
      }),
    },
  },
} satisfies Dictionary;

export default content;
