/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'auditEventDrawer',
  content: {
    rollbackChange: t({
      ru: 'Откатить изменение',
      en: 'Roll back change',
      kk: 'Өзгерісті қайтару',
      de: 'Änderung zurücksetzen',
      fr: 'Annuler la modification',
      es: 'Revertir el cambio',
      pt: 'Reverter alteração',
      tr: 'Değişikliği geri al',
      uk: 'Відкотити зміну',
      zh: '回滚更改',
      ar: 'التراجع عن التغيير',
      pl: 'Cofnij zmianę',
      it: 'Ripristina la modifica',
      sk: 'Vrátiť zmenu',
      ja: '変更をロールバック',
      ko: '변경 되돌리기',
      hi: 'बदलाव वापस लें',
      nl: 'Wijziging terugdraaien',
      sv: 'Återställ ändringen',
      vi: 'Hoàn tác thay đổi',
      id: 'Kembalikan perubahan',
    }),
    title: t({
      ru: 'Событие аудита',
      en: 'Audit event',
      kk: 'Аудит оқиғасы',
      de: 'Audit-Ereignis',
      fr: "Événement d'audit",
      es: 'Evento de auditoría',
      pt: 'Evento de auditoria',
      tr: 'Denetim olayı',
      uk: 'Подія аудиту',
      zh: '审计事件',
      ar: 'حدث التدقيق',
      pl: 'Zdarzenie audytu',
      it: 'Evento di audit',
      sk: 'Udalosť auditu',
      ja: '監査イベント',
      ko: '감사 이벤트',
      hi: 'ऑडिट इवेंट',
      nl: 'Auditgebeurtenis',
      sv: 'Granskningshändelse',
      vi: 'Sự kiện kiểm toán',
      id: 'Peristiwa audit',
    }),
    timestamp: t({
      ru: 'Время',
      en: 'Timestamp',
      kk: 'Уақыты',
      de: 'Zeitpunkt',
      fr: 'Horodatage',
      es: 'Fecha y hora',
      pt: 'Data e hora',
      tr: 'Zaman',
      uk: 'Час',
      zh: '时间',
      ar: 'الوقت',
      pl: 'Czas',
      it: 'Data e ora',
      sk: 'Čas',
      ja: '日時',
      ko: '시간',
      hi: 'समय',
      nl: 'Tijdstip',
      sv: 'Tidpunkt',
      vi: 'Thời gian',
      id: 'Waktu',
    }),
    actor: t({
      ru: 'Автор',
      en: 'Actor',
      kk: 'Орындаушы',
      de: 'Akteur',
      fr: 'Auteur',
      es: 'Autor',
      pt: 'Autor',
      tr: 'Yapan',
      uk: 'Виконавець',
      zh: '执行者',
      ar: 'المنفذ',
      pl: 'Wykonawca',
      it: 'Autore',
      sk: 'Vykonal',
      ja: '実行者',
      ko: '수행자',
      hi: 'कर्ता',
      nl: 'Uitvoerder',
      sv: 'Utförare',
      vi: 'Người thực hiện',
      id: 'Pelaku',
    }),
    action: t({
      ru: 'Действие',
      en: 'Action',
      kk: 'Әрекет',
      de: 'Aktion',
      fr: 'Action',
      es: 'Acción',
      pt: 'Ação',
      tr: 'İşlem',
      uk: 'Дія',
      zh: '操作',
      ar: 'الإجراء',
      pl: 'Działanie',
      it: 'Azione',
      sk: 'Akcia',
      ja: '操作',
      ko: '작업',
      hi: 'कार्रवाई',
      nl: 'Actie',
      sv: 'Åtgärd',
      vi: 'Hành động',
      id: 'Tindakan',
    }),
    entity: t({
      ru: 'Объект',
      en: 'Entity',
      kk: 'Нысан',
      de: 'Objekt',
      fr: 'Objet',
      es: 'Objeto',
      pt: 'Objeto',
      tr: 'Nesne',
      uk: "Об'єкт",
      zh: '对象',
      ar: 'الكيان',
      pl: 'Obiekt',
      it: 'Oggetto',
      sk: 'Objekt',
      ja: '対象',
      ko: '대상',
      hi: 'इकाई',
      nl: 'Object',
      sv: 'Objekt',
      vi: 'Đối tượng',
      id: 'Objek',
    }),
    entityId: t({
      ru: 'ID объекта',
      en: 'Entity ID',
      kk: 'Нысан ID',
      de: 'Objekt-ID',
      fr: "ID de l'objet",
      es: 'ID del objeto',
      pt: 'ID do objeto',
      tr: 'Nesne kimliği',
      uk: "ID об'єкта",
      zh: '对象 ID',
      ar: 'معرّف الكيان',
      pl: 'ID obiektu',
      it: "ID dell'oggetto",
      sk: 'ID objektu',
      ja: '対象 ID',
      ko: '대상 ID',
      hi: 'इकाई ID',
      nl: 'Object-ID',
      sv: 'Objekt-ID',
      vi: 'ID đối tượng',
      id: 'ID objek',
    }),
    severity: t({
      ru: 'Важность',
      en: 'Severity',
      kk: 'Маңыздылығы',
      de: 'Schweregrad',
      fr: 'Gravité',
      es: 'Gravedad',
      pt: 'Gravidade',
      tr: 'Önem',
      uk: 'Важливість',
      zh: '严重程度',
      ar: 'الخطورة',
      pl: 'Ważność',
      it: 'Gravità',
      sk: 'Závažnosť',
      ja: '重要度',
      ko: '심각도',
      hi: 'गंभीरता',
      nl: 'Ernst',
      sv: 'Allvarlighetsgrad',
      vi: 'Mức độ',
      id: 'Tingkat keparahan',
    }),
    batch: t({
      ru: 'Пакет',
      en: 'Batch',
      kk: 'Пакет',
      de: 'Stapel',
      fr: 'Lot',
      es: 'Lote',
      pt: 'Lote',
      tr: 'Toplu işlem',
      uk: 'Пакет',
      zh: '批次',
      ar: 'دفعة',
      pl: 'Pakiet',
      it: 'Lotto',
      sk: 'Dávka',
      ja: 'バッチ',
      ko: '일괄 작업',
      hi: 'बैच',
      nl: 'Batch',
      sv: 'Batch',
      vi: 'Lô',
      id: 'Batch',
    }),
    diff: t({
      ru: 'Изменения',
      en: 'Diff',
      kk: 'Өзгерістер',
      de: 'Änderungen',
      fr: 'Modifications',
      es: 'Cambios',
      pt: 'Alterações',
      tr: 'Değişiklikler',
      uk: 'Зміни',
      zh: '变更',
      ar: 'التغييرات',
      pl: 'Zmiany',
      it: 'Modifiche',
      sk: 'Zmeny',
      ja: '変更内容',
      ko: '변경 사항',
      hi: 'बदलाव',
      nl: 'Wijzigingen',
      sv: 'Ändringar',
      vi: 'Thay đổi',
      id: 'Perubahan',
    }),
    metadata: t({
      ru: 'Метаданные',
      en: 'Metadata',
      kk: 'Метадеректер',
      de: 'Metadaten',
      fr: 'Métadonnées',
      es: 'Metadatos',
      pt: 'Metadados',
      tr: 'Meta veriler',
      uk: 'Метадані',
      zh: '元数据',
      ar: 'البيانات الوصفية',
      pl: 'Metadane',
      it: 'Metadati',
      sk: 'Metadáta',
      ja: 'メタデータ',
      ko: '메타데이터',
      hi: 'मेटाडेटा',
      nl: 'Metadata',
      sv: 'Metadata',
      vi: 'Siêu dữ liệu',
      id: 'Metadata',
    }),
    noMetadata: t({
      ru: 'Нет метаданных',
      en: 'No metadata',
      kk: 'Метадеректер жоқ',
      de: 'Keine Metadaten',
      fr: 'Aucune métadonnée',
      es: 'Sin metadatos',
      pt: 'Sem metadados',
      tr: 'Meta veri yok',
      uk: 'Немає метаданих',
      zh: '无元数据',
      ar: 'لا توجد بيانات وصفية',
      pl: 'Brak metadanych',
      it: 'Nessun metadato',
      sk: 'Žiadne metadáta',
      ja: 'メタデータなし',
      ko: '메타데이터 없음',
      hi: 'कोई मेटाडेटा नहीं',
      nl: 'Geen metadata',
      sv: 'Inga metadata',
      vi: 'Không có siêu dữ liệu',
      id: 'Tidak ada metadata',
    }),
    rollbackOf: t({
      ru: 'Связанное событие (откат):',
      en: 'Related event (rollback of):',
      kk: 'Байланысты оқиға (қайтару):',
      de: 'Zugehöriges Ereignis (Rücknahme von):',
      fr: 'Événement lié (annulation de) :',
      es: 'Evento relacionado (reversión de):',
      pt: 'Evento relacionado (reversão de):',
      tr: 'İlgili olay (geri alınan):',
      uk: "Пов'язана подія (відкат):",
      zh: '相关事件（回滚自）：',
      ar: 'حدث مرتبط (تراجع عن):',
      pl: 'Powiązane zdarzenie (cofnięcie):',
      it: 'Evento correlato (ripristino di):',
      sk: 'Súvisiaca udalosť (vrátenie):',
      ja: '関連イベント（ロールバック元）：',
      ko: '관련 이벤트(되돌린 대상):',
      hi: 'संबंधित इवेंट (वापस लिया गया):',
      nl: 'Gerelateerde gebeurtenis (terugdraaiing van):',
      sv: 'Relaterad händelse (återställning av):',
      vi: 'Sự kiện liên quan (hoàn tác của):',
      id: 'Peristiwa terkait (pengembalian dari):',
    }),
  },
} satisfies Dictionary;

export default content;
