import { type Dictionary, t } from 'intlayer';

/**
 * Localised rendering of the backend's locale-independent audit descriptors
 * (`meta.auditDescription`). A key missing here falls back to the English
 * sentence the backend already stores in `description`.
 */
const content = {
  key: 'auditDescriptions',
  content: {
    templates: {
      create: t({
        ru: 'Создание: {{entity}}',
        en: 'Created: {{entity}}',
        kk: 'Жасалды: {{entity}}',
        de: 'Erstellt: {{entity}}',
        fr: 'Créé : {{entity}}',
        es: 'Creado: {{entity}}',
        pt: 'Criado: {{entity}}',
        tr: 'Oluşturuldu: {{entity}}',
        uk: 'Створено: {{entity}}',
        zh: '已创建：{{entity}}',
        ar: 'تم الإنشاء: {{entity}}',
        pl: 'Utworzono: {{entity}}',
        it: 'Creato: {{entity}}',
        sk: 'Vytvorené: {{entity}}',
        ja: '作成: {{entity}}',
        ko: '생성됨: {{entity}}',
        hi: 'बनाया गया: {{entity}}',
        nl: 'Aangemaakt: {{entity}}',
        sv: 'Skapad: {{entity}}',
        vi: 'Đã tạo: {{entity}}',
        id: 'Dibuat: {{entity}}',
      }),
      createNamed: t({
        ru: 'Создание: {{entity}} «{{name}}»',
        en: 'Created: {{entity}} "{{name}}"',
        kk: 'Жасалды: {{entity}} «{{name}}»',
        de: 'Erstellt: {{entity}} „{{name}}“',
        fr: 'Créé : {{entity}} « {{name}} »',
        es: 'Creado: {{entity}} «{{name}}»',
        pt: 'Criado: {{entity}} "{{name}}"',
        tr: 'Oluşturuldu: {{entity}} "{{name}}"',
        uk: 'Створено: {{entity}} «{{name}}»',
        zh: '已创建：{{entity}}“{{name}}”',
        ar: 'تم الإنشاء: {{entity}} "{{name}}"',
        pl: 'Utworzono: {{entity}} „{{name}}”',
        it: 'Creato: {{entity}} "{{name}}"',
        sk: 'Vytvorené: {{entity}} „{{name}}“',
        ja: '作成: {{entity}}「{{name}}」',
        ko: '생성됨: {{entity}} "{{name}}"',
        hi: 'बनाया गया: {{entity}} "{{name}}"',
        nl: 'Aangemaakt: {{entity}} "{{name}}"',
        sv: 'Skapad: {{entity}} ”{{name}}”',
        vi: 'Đã tạo: {{entity}} “{{name}}”',
        id: 'Dibuat: {{entity}} "{{name}}"',
      }),
      update: t({
        ru: 'Изменение: {{entity}}',
        en: 'Changed: {{entity}}',
        kk: 'Өзгертілді: {{entity}}',
        de: 'Geändert: {{entity}}',
        fr: 'Modifié : {{entity}}',
        es: 'Modificado: {{entity}}',
        pt: 'Alterado: {{entity}}',
        tr: 'Değiştirildi: {{entity}}',
        uk: 'Змінено: {{entity}}',
        zh: '已更改：{{entity}}',
        ar: 'تم التغيير: {{entity}}',
        pl: 'Zmieniono: {{entity}}',
        it: 'Modificato: {{entity}}',
        sk: 'Zmenené: {{entity}}',
        ja: '変更: {{entity}}',
        ko: '변경됨: {{entity}}',
        hi: 'बदला गया: {{entity}}',
        nl: 'Gewijzigd: {{entity}}',
        sv: 'Ändrad: {{entity}}',
        vi: 'Đã thay đổi: {{entity}}',
        id: 'Diubah: {{entity}}',
      }),
      updateOneField: t({
        ru: 'Изменение: {{field}}',
        en: 'Changed: {{field}}',
        kk: 'Өзгертілді: {{field}}',
        de: 'Geändert: {{field}}',
        fr: 'Modifié : {{field}}',
        es: 'Modificado: {{field}}',
        pt: 'Alterado: {{field}}',
        tr: 'Değiştirildi: {{field}}',
        uk: 'Змінено: {{field}}',
        zh: '已更改：{{field}}',
        ar: 'تم التغيير: {{field}}',
        pl: 'Zmieniono: {{field}}',
        it: 'Modificato: {{field}}',
        sk: 'Zmenené: {{field}}',
        ja: '変更: {{field}}',
        ko: '변경됨: {{field}}',
        hi: 'बदला गया: {{field}}',
        nl: 'Gewijzigd: {{field}}',
        sv: 'Ändrad: {{field}}',
        vi: 'Đã thay đổi: {{field}}',
        id: 'Diubah: {{field}}',
      }),
      updateManyFields: t({
        ru: 'Изменение — {{entity}}: {{fields}}',
        en: 'Changed {{entity}}: {{fields}}',
        kk: 'Өзгертілді — {{entity}}: {{fields}}',
        de: 'Geändert – {{entity}}: {{fields}}',
        fr: 'Modifié — {{entity}} : {{fields}}',
        es: 'Modificado — {{entity}}: {{fields}}',
        pt: 'Alterado — {{entity}}: {{fields}}',
        tr: 'Değiştirildi — {{entity}}: {{fields}}',
        uk: 'Змінено — {{entity}}: {{fields}}',
        zh: '已更改 {{entity}}：{{fields}}',
        ar: 'تم التغيير — {{entity}}: {{fields}}',
        pl: 'Zmieniono — {{entity}}: {{fields}}',
        it: 'Modificato — {{entity}}: {{fields}}',
        sk: 'Zmenené — {{entity}}: {{fields}}',
        ja: '変更 — {{entity}}: {{fields}}',
        ko: '변경됨 — {{entity}}: {{fields}}',
        hi: 'बदला गया — {{entity}}: {{fields}}',
        nl: 'Gewijzigd — {{entity}}: {{fields}}',
        sv: 'Ändrad — {{entity}}: {{fields}}',
        vi: 'Đã thay đổi — {{entity}}: {{fields}}',
        id: 'Diubah — {{entity}}: {{fields}}',
      }),
      updateManyFieldsMore: t({
        ru: 'Изменение — {{entity}}: {{fields}} и ещё {{more}}',
        en: 'Changed {{entity}}: {{fields}} and {{more}} more',
        kk: 'Өзгертілді — {{entity}}: {{fields}} және тағы {{more}}',
        de: 'Geändert – {{entity}}: {{fields}} und {{more}} weitere',
        fr: 'Modifié — {{entity}} : {{fields}} et {{more}} de plus',
        es: 'Modificado — {{entity}}: {{fields}} y {{more}} más',
        pt: 'Alterado — {{entity}}: {{fields}} e mais {{more}}',
        tr: 'Değiştirildi — {{entity}}: {{fields}} ve {{more}} tane daha',
        uk: 'Змінено — {{entity}}: {{fields}} і ще {{more}}',
        zh: '已更改 {{entity}}：{{fields}} 等另外 {{more}} 项',
        ar: 'تم التغيير — {{entity}}: {{fields}} و{{more}} أخرى',
        pl: 'Zmieniono — {{entity}}: {{fields}} i jeszcze {{more}}',
        it: 'Modificato — {{entity}}: {{fields}} e altri {{more}}',
        sk: 'Zmenené — {{entity}}: {{fields}} a ďalších {{more}}',
        ja: '変更 — {{entity}}: {{fields}} ほか {{more}} 件',
        ko: '변경됨 — {{entity}}: {{fields}} 외 {{more}}개',
        hi: 'बदला गया — {{entity}}: {{fields}} और {{more}} अन्य',
        nl: 'Gewijzigd — {{entity}}: {{fields}} en nog {{more}}',
        sv: 'Ändrad — {{entity}}: {{fields}} och {{more}} till',
        vi: 'Đã thay đổi — {{entity}}: {{fields}} và {{more}} mục nữa',
        id: 'Diubah — {{entity}}: {{fields}} dan {{more}} lainnya',
      }),
      delete: t({
        ru: 'Удаление: {{entity}}',
        en: 'Deleted: {{entity}}',
        kk: 'Жойылды: {{entity}}',
        de: 'Gelöscht: {{entity}}',
        fr: 'Supprimé : {{entity}}',
        es: 'Eliminado: {{entity}}',
        pt: 'Excluído: {{entity}}',
        tr: 'Silindi: {{entity}}',
        uk: 'Видалено: {{entity}}',
        zh: '已删除：{{entity}}',
        ar: 'تم الحذف: {{entity}}',
        pl: 'Usunięto: {{entity}}',
        it: 'Eliminato: {{entity}}',
        sk: 'Odstránené: {{entity}}',
        ja: '削除: {{entity}}',
        ko: '삭제됨: {{entity}}',
        hi: 'हटाया गया: {{entity}}',
        nl: 'Verwijderd: {{entity}}',
        sv: 'Borttagen: {{entity}}',
        vi: 'Đã xóa: {{entity}}',
        id: 'Dihapus: {{entity}}',
      }),
      deleteNamed: t({
        ru: 'Удаление: {{entity}} «{{name}}»',
        en: 'Deleted: {{entity}} "{{name}}"',
        kk: 'Жойылды: {{entity}} «{{name}}»',
        de: 'Gelöscht: {{entity}} „{{name}}“',
        fr: 'Supprimé : {{entity}} « {{name}} »',
        es: 'Eliminado: {{entity}} «{{name}}»',
        pt: 'Excluído: {{entity}} "{{name}}"',
        tr: 'Silindi: {{entity}} "{{name}}"',
        uk: 'Видалено: {{entity}} «{{name}}»',
        zh: '已删除：{{entity}}“{{name}}”',
        ar: 'تم الحذف: {{entity}} "{{name}}"',
        pl: 'Usunięto: {{entity}} „{{name}}”',
        it: 'Eliminato: {{entity}} "{{name}}"',
        sk: 'Odstránené: {{entity}} „{{name}}“',
        ja: '削除: {{entity}}「{{name}}」',
        ko: '삭제됨: {{entity}} "{{name}}"',
        hi: 'हटाया गया: {{entity}} "{{name}}"',
        nl: 'Verwijderd: {{entity}} "{{name}}"',
        sv: 'Borttagen: {{entity}} ”{{name}}”',
        vi: 'Đã xóa: {{entity}} “{{name}}”',
        id: 'Dihapus: {{entity}} "{{name}}"',
      }),
      rollbackCreate: t({
        ru: 'Откат: создание — {{entity}}',
        en: 'Rolled back: creation of {{entity}}',
        kk: 'Қайтару: жасау — {{entity}}',
        de: 'Zurückgesetzt: Erstellung von {{entity}}',
        fr: 'Annulé : création de {{entity}}',
        es: 'Revertido: creación de {{entity}}',
        pt: 'Revertido: criação de {{entity}}',
        tr: 'Geri alındı: {{entity}} oluşturma',
        uk: 'Відкат: створення — {{entity}}',
        zh: '已回滚：{{entity}} 的创建',
        ar: 'تم التراجع: إنشاء {{entity}}',
        pl: 'Cofnięto: utworzenie {{entity}}',
        it: 'Ripristinato: creazione di {{entity}}',
        sk: 'Vrátené: vytvorenie {{entity}}',
        ja: 'ロールバック: {{entity}} の作成',
        ko: '되돌림: {{entity}} 생성',
        hi: 'वापस लिया: {{entity}} का निर्माण',
        nl: 'Teruggedraaid: aanmaken van {{entity}}',
        sv: 'Återställd: skapande av {{entity}}',
        vi: 'Đã hoàn tác: tạo {{entity}}',
        id: 'Dikembalikan: pembuatan {{entity}}',
      }),
      rollbackUpdate: t({
        ru: 'Откат: изменение — {{entity}}',
        en: 'Rolled back: change to {{entity}}',
        kk: 'Қайтару: өзгеріс — {{entity}}',
        de: 'Zurückgesetzt: Änderung an {{entity}}',
        fr: 'Annulé : modification de {{entity}}',
        es: 'Revertido: cambio en {{entity}}',
        pt: 'Revertido: alteração em {{entity}}',
        tr: 'Geri alındı: {{entity}} değişikliği',
        uk: 'Відкат: зміна — {{entity}}',
        zh: '已回滚：{{entity}} 的更改',
        ar: 'تم التراجع: تغيير {{entity}}',
        pl: 'Cofnięto: zmianę {{entity}}',
        it: 'Ripristinato: modifica di {{entity}}',
        sk: 'Vrátené: zmena {{entity}}',
        ja: 'ロールバック: {{entity}} の変更',
        ko: '되돌림: {{entity}} 변경',
        hi: 'वापस लिया: {{entity}} में बदलाव',
        nl: 'Teruggedraaid: wijziging van {{entity}}',
        sv: 'Återställd: ändring av {{entity}}',
        vi: 'Đã hoàn tác: thay đổi {{entity}}',
        id: 'Dikembalikan: perubahan {{entity}}',
      }),
      rollbackDelete: t({
        ru: 'Откат: удаление — {{entity}}',
        en: 'Rolled back: deletion of {{entity}}',
        kk: 'Қайтару: жою — {{entity}}',
        de: 'Zurückgesetzt: Löschung von {{entity}}',
        fr: 'Annulé : suppression de {{entity}}',
        es: 'Revertido: eliminación de {{entity}}',
        pt: 'Revertido: exclusão de {{entity}}',
        tr: 'Geri alındı: {{entity}} silme',
        uk: 'Відкат: видалення — {{entity}}',
        zh: '已回滚：{{entity}} 的删除',
        ar: 'تم التراجع: حذف {{entity}}',
        pl: 'Cofnięto: usunięcie {{entity}}',
        it: 'Ripristinato: eliminazione di {{entity}}',
        sk: 'Vrátené: odstránenie {{entity}}',
        ja: 'ロールバック: {{entity}} の削除',
        ko: '되돌림: {{entity}} 삭제',
        hi: 'वापस लिया: {{entity}} का विलोपन',
        nl: 'Teruggedraaid: verwijdering van {{entity}}',
        sv: 'Återställd: borttagning av {{entity}}',
        vi: 'Đã hoàn tác: xóa {{entity}}',
        id: 'Dikembalikan: penghapusan {{entity}}',
      }),
      importSourceRows: t({
        ru: 'Импорт из {{source}}: {{rows}} записей',
        en: 'Imported from {{source}}: {{rows}} records',
        kk: '{{source}} көзінен импорт: {{rows}} жазба',
        de: 'Import aus {{source}}: {{rows}} Datensätze',
        fr: 'Importé depuis {{source}} : {{rows}} enregistrements',
        es: 'Importado desde {{source}}: {{rows}} registros',
        pt: 'Importado de {{source}}: {{rows}} registros',
        tr: '{{source}} kaynağından içe aktarıldı: {{rows}} kayıt',
        uk: 'Імпорт із {{source}}: {{rows}} записів',
        zh: '已从 {{source}} 导入：{{rows}} 条记录',
        ar: 'تم الاستيراد من {{source}}: {{rows}} سجل',
        pl: 'Zaimportowano z {{source}}: {{rows}} rekordów',
        it: 'Importato da {{source}}: {{rows}} record',
        sk: 'Importované z {{source}}: {{rows}} záznamov',
        ja: '{{source}} からインポート: {{rows}} 件',
        ko: '{{source}}에서 가져옴: {{rows}}건',
        hi: '{{source}} से आयातित: {{rows}} रिकॉर्ड',
        nl: 'Geïmporteerd uit {{source}}: {{rows}} records',
        sv: 'Importerad från {{source}}: {{rows}} poster',
        vi: 'Đã nhập từ {{source}}: {{rows}} bản ghi',
        id: 'Diimpor dari {{source}}: {{rows}} catatan',
      }),
    },
    entities: {
      transaction: t({
        ru: 'транзакция',
        en: 'transaction',
        kk: 'транзакция',
        de: 'Transaktion',
        fr: 'transaction',
        es: 'transacción',
        pt: 'transação',
        tr: 'işlem',
        uk: 'транзакція',
        zh: '交易',
        ar: 'معاملة',
        pl: 'transakcja',
        it: 'transazione',
        sk: 'transakcia',
        ja: '取引',
        ko: '거래',
        hi: 'लेनदेन',
        nl: 'transactie',
        sv: 'transaktion',
        vi: 'giao dịch',
        id: 'transaksi',
      }),
      statement: t({
        ru: 'выписка',
        en: 'statement',
        kk: 'үзінді',
        de: 'Kontoauszug',
        fr: 'relevé',
        es: 'extracto',
        pt: 'extrato',
        tr: 'ekstre',
        uk: 'виписка',
        zh: '对账单',
        ar: 'كشف حساب',
        pl: 'wyciąg',
        it: 'estratto conto',
        sk: 'výpis',
        ja: '明細',
        ko: '거래내역서',
        hi: 'विवरण',
        nl: 'afschrift',
        sv: 'kontoutdrag',
        vi: 'sao kê',
        id: 'rekening koran',
      }),
      receipt: t({
        ru: 'чек',
        en: 'receipt',
        kk: 'чек',
        de: 'Beleg',
        fr: 'reçu',
        es: 'recibo',
        pt: 'recibo',
        tr: 'fiş',
        uk: 'чек',
        zh: '收据',
        ar: 'إيصال',
        pl: 'paragon',
        it: 'ricevuta',
        sk: 'doklad',
        ja: 'レシート',
        ko: '영수증',
        hi: 'रसीद',
        nl: 'bon',
        sv: 'kvitto',
        vi: 'biên lai',
        id: 'struk',
      }),
      payable: t({
        ru: 'задолженность',
        en: 'payable',
        kk: 'берешек',
        de: 'Verbindlichkeit',
        fr: 'dette fournisseur',
        es: 'cuenta por pagar',
        pt: 'conta a pagar',
        tr: 'borç',
        uk: 'заборгованість',
        zh: '应付款',
        ar: 'ذمم دائنة',
        pl: 'zobowiązanie',
        it: 'debito',
        sk: 'záväzok',
        ja: '買掛金',
        ko: '미지급금',
        hi: 'देय राशि',
        nl: 'schuld',
        sv: 'skuld',
        vi: 'khoản phải trả',
        id: 'utang',
      }),
      category: t({
        ru: 'категория',
        en: 'category',
        kk: 'санат',
        de: 'Kategorie',
        fr: 'catégorie',
        es: 'categoría',
        pt: 'categoria',
        tr: 'kategori',
        uk: 'категорія',
        zh: '类别',
        ar: 'فئة',
        pl: 'kategoria',
        it: 'categoria',
        sk: 'kategória',
        ja: 'カテゴリ',
        ko: '카테고리',
        hi: 'श्रेणी',
        nl: 'categorie',
        sv: 'kategori',
        vi: 'danh mục',
        id: 'kategori',
      }),
      rule: t({
        ru: 'правило',
        en: 'rule',
        kk: 'ереже',
        de: 'Regel',
        fr: 'règle',
        es: 'regla',
        pt: 'regra',
        tr: 'kural',
        uk: 'правило',
        zh: '规则',
        ar: 'قاعدة',
        pl: 'reguła',
        it: 'regola',
        sk: 'pravidlo',
        ja: 'ルール',
        ko: '규칙',
        hi: 'नियम',
        nl: 'regel',
        sv: 'regel',
        vi: 'quy tắc',
        id: 'aturan',
      }),
      workspace: t({
        ru: 'рабочее пространство',
        en: 'workspace',
        kk: 'жұмыс кеңістігі',
        de: 'Arbeitsbereich',
        fr: 'espace de travail',
        es: 'espacio de trabajo',
        pt: 'espaço de trabalho',
        tr: 'çalışma alanı',
        uk: 'робочий простір',
        zh: '工作区',
        ar: 'مساحة عمل',
        pl: 'przestrzeń robocza',
        it: 'spazio di lavoro',
        sk: 'pracovný priestor',
        ja: 'ワークスペース',
        ko: '워크스페이스',
        hi: 'कार्यक्षेत्र',
        nl: 'werkruimte',
        sv: 'arbetsyta',
        vi: 'không gian làm việc',
        id: 'ruang kerja',
      }),
      integration: t({
        ru: 'интеграция',
        en: 'integration',
        kk: 'интеграция',
        de: 'Integration',
        fr: 'intégration',
        es: 'integración',
        pt: 'integração',
        tr: 'entegrasyon',
        uk: 'інтеграція',
        zh: '集成',
        ar: 'تكامل',
        pl: 'integracja',
        it: 'integrazione',
        sk: 'integrácia',
        ja: '連携',
        ko: '통합',
        hi: 'एकीकरण',
        nl: 'integratie',
        sv: 'integration',
        vi: 'tích hợp',
        id: 'integrasi',
      }),
      table_row: t({
        ru: 'строка таблицы',
        en: 'table row',
        kk: 'кесте жолы',
        de: 'Tabellenzeile',
        fr: 'ligne de tableau',
        es: 'fila de tabla',
        pt: 'linha da tabela',
        tr: 'tablo satırı',
        uk: 'рядок таблиці',
        zh: '表格行',
        ar: 'صف الجدول',
        pl: 'wiersz tabeli',
        it: 'riga della tabella',
        sk: 'riadok tabuľky',
        ja: 'テーブル行',
        ko: '테이블 행',
        hi: 'तालिका पंक्ति',
        nl: 'tabelrij',
        sv: 'tabellrad',
        vi: 'hàng bảng',
        id: 'baris tabel',
      }),
      table_cell: t({
        ru: 'ячейка таблицы',
        en: 'table cell',
        kk: 'кесте ұяшығы',
        de: 'Tabellenzelle',
        fr: 'cellule de tableau',
        es: 'celda de tabla',
        pt: 'célula da tabela',
        tr: 'tablo hücresi',
        uk: 'комірка таблиці',
        zh: '表格单元格',
        ar: 'خلية الجدول',
        pl: 'komórka tabeli',
        it: 'cella della tabella',
        sk: 'bunka tabuľky',
        ja: 'テーブルセル',
        ko: '테이블 셀',
        hi: 'तालिका सेल',
        nl: 'tabelcel',
        sv: 'tabellcell',
        vi: 'ô bảng',
        id: 'sel tabel',
      }),
      branch: t({
        ru: 'филиал',
        en: 'branch',
        kk: 'филиал',
        de: 'Filiale',
        fr: 'succursale',
        es: 'sucursal',
        pt: 'filial',
        tr: 'şube',
        uk: 'філія',
        zh: '分支机构',
        ar: 'فرع',
        pl: 'oddział',
        it: 'filiale',
        sk: 'pobočka',
        ja: '支店',
        ko: '지점',
        hi: 'शाखा',
        nl: 'filiaal',
        sv: 'filial',
        vi: 'chi nhánh',
        id: 'cabang',
      }),
      wallet: t({
        ru: 'кошелёк',
        en: 'wallet',
        kk: 'әмиян',
        de: 'Wallet',
        fr: 'portefeuille',
        es: 'billetera',
        pt: 'carteira',
        tr: 'cüzdan',
        uk: 'гаманець',
        zh: '钱包',
        ar: 'محفظة',
        pl: 'portfel',
        it: 'portafoglio',
        sk: 'peňaženka',
        ja: 'ウォレット',
        ko: '지갑',
        hi: 'वॉलेट',
        nl: 'portemonnee',
        sv: 'plånbok',
        vi: 'ví',
        id: 'dompet',
      }),
      custom_table: t({
        ru: 'таблица',
        en: 'table',
        kk: 'кесте',
        de: 'Tabelle',
        fr: 'tableau',
        es: 'tabla',
        pt: 'tabela',
        tr: 'tablo',
        uk: 'таблиця',
        zh: '表格',
        ar: 'جدول',
        pl: 'tabela',
        it: 'tabella',
        sk: 'tabuľka',
        ja: 'テーブル',
        ko: '테이블',
        hi: 'तालिका',
        nl: 'tabel',
        sv: 'tabell',
        vi: 'bảng',
        id: 'tabel',
      }),
      custom_table_column: t({
        ru: 'колонка таблицы',
        en: 'table column',
        kk: 'кесте бағаны',
        de: 'Tabellenspalte',
        fr: 'colonne de tableau',
        es: 'columna de tabla',
        pt: 'coluna da tabela',
        tr: 'tablo sütunu',
        uk: 'стовпець таблиці',
        zh: '表格列',
        ar: 'عمود الجدول',
        pl: 'kolumna tabeli',
        it: 'colonna della tabella',
        sk: 'stĺpec tabuľky',
        ja: 'テーブル列',
        ko: '테이블 열',
        hi: 'तालिका कॉलम',
        nl: 'tabelkolom',
        sv: 'tabellkolumn',
        vi: 'cột bảng',
        id: 'kolom tabel',
      }),
      budget: t({
        ru: 'бюджет',
        en: 'budget',
        kk: 'бюджет',
        de: 'Budget',
        fr: 'budget',
        es: 'presupuesto',
        pt: 'orçamento',
        tr: 'bütçe',
        uk: 'бюджет',
        zh: '预算',
        ar: 'ميزانية',
        pl: 'budżet',
        it: 'budget',
        sk: 'rozpočet',
        ja: '予算',
        ko: '예산',
        hi: 'बजट',
        nl: 'budget',
        sv: 'budget',
        vi: 'ngân sách',
        id: 'anggaran',
      }),
      subscription: t({
        ru: 'подписка',
        en: 'subscription',
        kk: 'жазылым',
        de: 'Abonnement',
        fr: 'abonnement',
        es: 'suscripción',
        pt: 'assinatura',
        tr: 'abonelik',
        uk: 'підписка',
        zh: '订阅',
        ar: 'اشتراك',
        pl: 'subskrypcja',
        it: 'abbonamento',
        sk: 'predplatné',
        ja: 'サブスクリプション',
        ko: '구독',
        hi: 'सदस्यता',
        nl: 'abonnement',
        sv: 'prenumeration',
        vi: 'đăng ký',
        id: 'langganan',
      }),
    },
    actions: {
      create: t({
        ru: 'Создание',
        en: 'Create',
        kk: 'Құру',
        de: 'Erstellen',
        fr: 'Création',
        es: 'Crear',
        pt: 'Criar',
        tr: 'Oluşturma',
        uk: 'Створення',
        zh: '创建',
        ar: 'إنشاء',
        pl: 'Utworzenie',
        it: 'Creazione',
        sk: 'Vytvorenie',
        ja: '作成',
        ko: '생성',
        hi: 'बनाना',
        nl: 'Aanmaken',
        sv: 'Skapa',
        vi: 'Tạo',
        id: 'Buat',
      }),
      update: t({
        ru: 'Изменение',
        en: 'Change',
        kk: 'Өзгерту',
        de: 'Änderung',
        fr: 'Modification',
        es: 'Cambio',
        pt: 'Alteração',
        tr: 'Değişiklik',
        uk: 'Зміна',
        zh: '更改',
        ar: 'تغيير',
        pl: 'Zmiana',
        it: 'Modifica',
        sk: 'Zmena',
        ja: '変更',
        ko: '변경',
        hi: 'बदलाव',
        nl: 'Wijziging',
        sv: 'Ändring',
        vi: 'Thay đổi',
        id: 'Ubah',
      }),
      delete: t({
        ru: 'Удаление',
        en: 'Delete',
        kk: 'Жою',
        de: 'Löschen',
        fr: 'Suppression',
        es: 'Eliminar',
        pt: 'Excluir',
        tr: 'Silme',
        uk: 'Видалення',
        zh: '删除',
        ar: 'حذف',
        pl: 'Usunięcie',
        it: 'Eliminazione',
        sk: 'Odstránenie',
        ja: '削除',
        ko: '삭제',
        hi: 'हटाना',
        nl: 'Verwijderen',
        sv: 'Radera',
        vi: 'Xóa',
        id: 'Hapus',
      }),
      import: t({
        ru: 'Импорт',
        en: 'Import',
        kk: 'Импорт',
        de: 'Import',
        fr: 'Import',
        es: 'Importar',
        pt: 'Importar',
        tr: 'İçe aktarma',
        uk: 'Імпорт',
        zh: '导入',
        ar: 'استيراد',
        pl: 'Import',
        it: 'Importazione',
        sk: 'Import',
        ja: 'インポート',
        ko: '가져오기',
        hi: 'आयात',
        nl: 'Import',
        sv: 'Import',
        vi: 'Nhập',
        id: 'Impor',
      }),
      link: t({
        ru: 'Связывание',
        en: 'Link',
        kk: 'Байланыстыру',
        de: 'Verknüpfen',
        fr: 'Liaison',
        es: 'Vincular',
        pt: 'Vincular',
        tr: 'Bağlama',
        uk: 'Зв’язування',
        zh: '关联',
        ar: 'ربط',
        pl: 'Powiązanie',
        it: 'Collegamento',
        sk: 'Prepojenie',
        ja: 'リンク',
        ko: '연결',
        hi: 'लिंक करना',
        nl: 'Koppelen',
        sv: 'Länka',
        vi: 'Liên kết',
        id: 'Tautkan',
      }),
      unlink: t({
        ru: 'Отвязка',
        en: 'Unlink',
        kk: 'Байланысты ажырату',
        de: 'Verknüpfung lösen',
        fr: 'Dissociation',
        es: 'Desvincular',
        pt: 'Desvincular',
        tr: 'Bağlantıyı kaldırma',
        uk: 'Відв’язування',
        zh: '取消关联',
        ar: 'إلغاء الربط',
        pl: 'Odłączenie',
        it: 'Scollegamento',
        sk: 'Zrušenie prepojenia',
        ja: 'リンク解除',
        ko: '연결 해제',
        hi: 'अनलिंक करना',
        nl: 'Ontkoppelen',
        sv: 'Ta bort länk',
        vi: 'Hủy liên kết',
        id: 'Lepas tautan',
      }),
      match: t({
        ru: 'Объединение',
        en: 'Match',
        kk: 'Біріктіру',
        de: 'Zusammenführen',
        fr: 'Fusion',
        es: 'Combinar',
        pt: 'Mesclar',
        tr: 'Birleştirme',
        uk: 'Об’єднання',
        zh: '合并',
        ar: 'دمج',
        pl: 'Scalenie',
        it: 'Unione',
        sk: 'Zlúčenie',
        ja: '統合',
        ko: '병합',
        hi: 'मिलान',
        nl: 'Samenvoegen',
        sv: 'Sammanfoga',
        vi: 'Hợp nhất',
        id: 'Gabungkan',
      }),
      unmatch: t({
        ru: 'Разъединение',
        en: 'Unmatch',
        kk: 'Бөлу',
        de: 'Trennen',
        fr: 'Séparation',
        es: 'Separar',
        pt: 'Separar',
        tr: 'Ayırma',
        uk: 'Роз’єднання',
        zh: '取消合并',
        ar: 'إلغاء الدمج',
        pl: 'Rozdzielenie',
        it: 'Separazione',
        sk: 'Rozdelenie',
        ja: '統合解除',
        ko: '병합 해제',
        hi: 'मिलान हटाना',
        nl: 'Scheiden',
        sv: 'Separera',
        vi: 'Tách',
        id: 'Pisahkan',
      }),
      apply_rule: t({
        ru: 'Применение правила',
        en: 'Apply Rule',
        kk: 'Ережені қолдану',
        de: 'Regel anwenden',
        fr: 'Application de règle',
        es: 'Aplicar regla',
        pt: 'Aplicar regra',
        tr: 'Kural uygulama',
        uk: 'Застосування правила',
        zh: '应用规则',
        ar: 'تطبيق قاعدة',
        pl: 'Zastosowanie reguły',
        it: 'Applicazione regola',
        sk: 'Použitie pravidla',
        ja: 'ルール適用',
        ko: '규칙 적용',
        hi: 'नियम लागू करना',
        nl: 'Regel toepassen',
        sv: 'Tillämpa regel',
        vi: 'Áp dụng quy tắc',
        id: 'Terapkan aturan',
      }),
      rollback: t({
        ru: 'Откат',
        en: 'Rollback',
        kk: 'Кері қайтару',
        de: 'Rücksetzung',
        fr: 'Annulation',
        es: 'Reversión',
        pt: 'Reversão',
        tr: 'Geri alma',
        uk: 'Відкат',
        zh: '回滚',
        ar: 'تراجع',
        pl: 'Wycofanie',
        it: 'Ripristino',
        sk: 'Vrátenie',
        ja: 'ロールバック',
        ko: '롤백',
        hi: 'रोलबैक',
        nl: 'Terugdraaien',
        sv: 'Återställning',
        vi: 'Hoàn tác',
        id: 'Kembalikan',
      }),
      export: t({
        ru: 'Экспорт',
        en: 'Export',
        kk: 'Экспорт',
        de: 'Export',
        fr: 'Export',
        es: 'Exportar',
        pt: 'Exportar',
        tr: 'Dışa aktarma',
        uk: 'Експорт',
        zh: '导出',
        ar: 'تصدير',
        pl: 'Eksport',
        it: 'Esportazione',
        sk: 'Export',
        ja: 'エクスポート',
        ko: '내보내기',
        hi: 'निर्यात',
        nl: 'Export',
        sv: 'Export',
        vi: 'Xuất',
        id: 'Ekspor',
      }),
    },
    verbs: {
      create: t({
        ru: 'создал(а)',
        en: 'created',
        kk: 'құрды',
        de: 'hat erstellt',
        fr: 'a créé',
        es: 'creó',
        pt: 'criou',
        tr: 'oluşturdu',
        uk: 'створив(ла)',
        zh: '创建了',
        ar: 'أنشأ',
        pl: 'utworzył(a)',
        it: 'ha creato',
        sk: 'vytvoril(a)',
        ja: 'が作成',
        ko: '님이 생성',
        hi: 'ने बनाया',
        nl: 'heeft aangemaakt',
        sv: 'skapade',
        vi: 'đã tạo',
        id: 'membuat',
      }),
      update: t({
        ru: 'изменил(а)',
        en: 'updated',
        kk: 'өзгертті',
        de: 'hat geändert',
        fr: 'a modifié',
        es: 'actualizó',
        pt: 'atualizou',
        tr: 'güncelledi',
        uk: 'змінив(ла)',
        zh: '更新了',
        ar: 'حدّث',
        pl: 'zmienił(a)',
        it: 'ha modificato',
        sk: 'upravil(a)',
        ja: 'が更新',
        ko: '님이 수정',
        hi: 'ने अपडेट किया',
        nl: 'heeft bijgewerkt',
        sv: 'uppdaterade',
        vi: 'đã cập nhật',
        id: 'memperbarui',
      }),
      delete: t({
        ru: 'удалил(а)',
        en: 'deleted',
        kk: 'жойды',
        de: 'hat gelöscht',
        fr: 'a supprimé',
        es: 'eliminó',
        pt: 'excluiu',
        tr: 'sildi',
        uk: 'видалив(ла)',
        zh: '删除了',
        ar: 'حذف',
        pl: 'usunął(-ęła)',
        it: 'ha eliminato',
        sk: 'odstránil(a)',
        ja: 'が削除',
        ko: '님이 삭제',
        hi: 'ने हटाया',
        nl: 'heeft verwijderd',
        sv: 'raderade',
        vi: 'đã xóa',
        id: 'menghapus',
      }),
      import: t({
        ru: 'импортировал(а)',
        en: 'imported',
        kk: 'импорттады',
        de: 'hat importiert',
        fr: 'a importé',
        es: 'importó',
        pt: 'importou',
        tr: 'içe aktardı',
        uk: 'імпортував(ла)',
        zh: '导入了',
        ar: 'استورد',
        pl: 'zaimportował(a)',
        it: 'ha importato',
        sk: 'importoval(a)',
        ja: 'がインポート',
        ko: '님이 가져옴',
        hi: 'ने आयात किया',
        nl: 'heeft geïmporteerd',
        sv: 'importerade',
        vi: 'đã nhập',
        id: 'mengimpor',
      }),
      link: t({
        ru: 'связал(а)',
        en: 'linked',
        kk: 'байланыстырды',
        de: 'hat verknüpft',
        fr: 'a lié',
        es: 'vinculó',
        pt: 'vinculou',
        tr: 'bağladı',
        uk: 'зв’язав(ла)',
        zh: '关联了',
        ar: 'ربط',
        pl: 'powiązał(a)',
        it: 'ha collegato',
        sk: 'prepojil(a)',
        ja: 'がリンク',
        ko: '님이 연결',
        hi: 'ने लिंक किया',
        nl: 'heeft gekoppeld',
        sv: 'länkade',
        vi: 'đã liên kết',
        id: 'menautkan',
      }),
      unlink: t({
        ru: 'отвязал(а)',
        en: 'unlinked',
        kk: 'байланысын ажыратты',
        de: 'hat die Verknüpfung gelöst',
        fr: 'a dissocié',
        es: 'desvinculó',
        pt: 'desvinculou',
        tr: 'bağlantısını kaldırdı',
        uk: 'відв’язав(ла)',
        zh: '取消关联了',
        ar: 'ألغى ربط',
        pl: 'odłączył(a)',
        it: 'ha scollegato',
        sk: 'zrušil(a) prepojenie',
        ja: 'がリンク解除',
        ko: '님이 연결 해제',
        hi: 'ने अनलिंक किया',
        nl: 'heeft ontkoppeld',
        sv: 'tog bort länken till',
        vi: 'đã hủy liên kết',
        id: 'melepas tautan',
      }),
      match: t({
        ru: 'объединил(а)',
        en: 'merged',
        kk: 'біріктірді',
        de: 'hat zusammengeführt',
        fr: 'a fusionné',
        es: 'combinó',
        pt: 'mesclou',
        tr: 'birleştirdi',
        uk: 'об’єднав(ла)',
        zh: '合并了',
        ar: 'دمج',
        pl: 'scalił(a)',
        it: 'ha unito',
        sk: 'zlúčil(a)',
        ja: 'が統合',
        ko: '님이 병합',
        hi: 'ने मिलाया',
        nl: 'heeft samengevoegd',
        sv: 'sammanfogade',
        vi: 'đã hợp nhất',
        id: 'menggabungkan',
      }),
      unmatch: t({
        ru: 'разъединил(а)',
        en: 'unmatched',
        kk: 'бөлді',
        de: 'hat getrennt',
        fr: 'a séparé',
        es: 'separó',
        pt: 'separou',
        tr: 'ayırdı',
        uk: 'роз’єднав(ла)',
        zh: '取消合并了',
        ar: 'ألغى دمج',
        pl: 'rozdzielił(a)',
        it: 'ha separato',
        sk: 'rozdelil(a)',
        ja: 'が統合解除',
        ko: '님이 병합 해제',
        hi: 'ने अलग किया',
        nl: 'heeft gescheiden',
        sv: 'separerade',
        vi: 'đã tách',
        id: 'memisahkan',
      }),
      apply_rule: t({
        ru: 'категоризировал(а)',
        en: 'categorized',
        kk: 'санаттады',
        de: 'hat kategorisiert',
        fr: 'a catégorisé',
        es: 'categorizó',
        pt: 'categorizou',
        tr: 'kategorilendirdi',
        uk: 'категоризував(ла)',
        zh: '分类了',
        ar: 'صنّف',
        pl: 'skategoryzował(a)',
        it: 'ha categorizzato',
        sk: 'kategorizoval(a)',
        ja: 'が分類',
        ko: '님이 분류',
        hi: 'ने वर्गीकृत किया',
        nl: 'heeft gecategoriseerd',
        sv: 'kategoriserade',
        vi: 'đã phân loại',
        id: 'mengategorikan',
      }),
      rollback: t({
        ru: 'откатил(а)',
        en: 'rolled back',
        kk: 'кері қайтарды',
        de: 'hat zurückgesetzt',
        fr: 'a annulé',
        es: 'revirtió',
        pt: 'reverteu',
        tr: 'geri aldı',
        uk: 'відкотив(ла)',
        zh: '回滚了',
        ar: 'تراجع عن',
        pl: 'wycofał(a)',
        it: 'ha ripristinato',
        sk: 'vrátil(a)',
        ja: 'がロールバック',
        ko: '님이 롤백',
        hi: 'ने रोलबैक किया',
        nl: 'heeft teruggedraaid',
        sv: 'återställde',
        vi: 'đã hoàn tác',
        id: 'mengembalikan',
      }),
      export: t({
        ru: 'экспортировал(а)',
        en: 'exported',
        kk: 'экспорттады',
        de: 'hat exportiert',
        fr: 'a exporté',
        es: 'exportó',
        pt: 'exportou',
        tr: 'dışa aktardı',
        uk: 'експортував(ла)',
        zh: '导出了',
        ar: 'صدّر',
        pl: 'wyeksportował(a)',
        it: 'ha esportato',
        sk: 'exportoval(a)',
        ja: 'がエクスポート',
        ko: '님이 내보냄',
        hi: 'ने निर्यात किया',
        nl: 'heeft geëxporteerd',
        sv: 'exporterade',
        vi: 'đã xuất',
        id: 'mengekspor',
      }),
    },
    diff: {
      field: t({
        ru: 'Поле: {{field}}',
        en: 'Field: {{field}}',
        kk: 'Өріс: {{field}}',
        de: 'Feld: {{field}}',
        fr: 'Champ : {{field}}',
        es: 'Campo: {{field}}',
        pt: 'Campo: {{field}}',
        tr: 'Alan: {{field}}',
        uk: 'Поле: {{field}}',
        zh: '字段：{{field}}',
        ar: 'الحقل: {{field}}',
        pl: 'Pole: {{field}}',
        it: 'Campo: {{field}}',
        sk: 'Pole: {{field}}',
        ja: 'フィールド: {{field}}',
        ko: '필드: {{field}}',
        hi: 'फ़ील्ड: {{field}}',
        nl: 'Veld: {{field}}',
        sv: 'Fält: {{field}}',
        vi: 'Trường: {{field}}',
        id: 'Bidang: {{field}}',
      }),
      fields: t({
        ru: 'Поля: {{fields}}',
        en: 'Fields: {{fields}}',
        kk: 'Өрістер: {{fields}}',
        de: 'Felder: {{fields}}',
        fr: 'Champs : {{fields}}',
        es: 'Campos: {{fields}}',
        pt: 'Campos: {{fields}}',
        tr: 'Alanlar: {{fields}}',
        uk: 'Поля: {{fields}}',
        zh: '字段：{{fields}}',
        ar: 'الحقول: {{fields}}',
        pl: 'Pola: {{fields}}',
        it: 'Campi: {{fields}}',
        sk: 'Polia: {{fields}}',
        ja: 'フィールド: {{fields}}',
        ko: '필드: {{fields}}',
        hi: 'फ़ील्ड: {{fields}}',
        nl: 'Velden: {{fields}}',
        sv: 'Fält: {{fields}}',
        vi: 'Các trường: {{fields}}',
        id: 'Bidang: {{fields}}',
      }),
      fieldsMore: t({
        ru: 'Поля: {{fields}} и ещё {{count}}',
        en: 'Fields: {{fields}} +{{count}} more',
        kk: 'Өрістер: {{fields}} және тағы {{count}}',
        de: 'Felder: {{fields}} +{{count}} weitere',
        fr: 'Champs : {{fields}} +{{count}} autres',
        es: 'Campos: {{fields}} +{{count}} más',
        pt: 'Campos: {{fields}} +{{count}} outros',
        tr: 'Alanlar: {{fields}} +{{count}} daha',
        uk: 'Поля: {{fields}} і ще {{count}}',
        zh: '字段：{{fields}} 等另外 {{count}} 个',
        ar: 'الحقول: {{fields}} و{{count}} أخرى',
        pl: 'Pola: {{fields}} +{{count}} więcej',
        it: 'Campi: {{fields}} +{{count}} altri',
        sk: 'Polia: {{fields}} +{{count}} ďalšie',
        ja: 'フィールド: {{fields}} 他 {{count}} 件',
        ko: '필드: {{fields}} 외 {{count}}개',
        hi: 'फ़ील्ड: {{fields}} +{{count}} और',
        nl: 'Velden: {{fields}} +{{count}} meer',
        sv: 'Fält: {{fields}} +{{count}} till',
        vi: 'Các trường: {{fields}} và {{count}} trường khác',
        id: 'Bidang: {{fields}} +{{count}} lainnya',
      }),
    },
  },
} satisfies Dictionary;

export default content;
