import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'chatMode',
  content: {
    confirm: t({
      ru: 'Подтвердить',
      en: 'Confirm',
      kk: 'Растау',
      de: 'Bestätigen',
      fr: 'Confirmer',
      es: 'Confirmar',
      pt: 'Confirmar',
      tr: 'Onayla',
      uk: 'Підтвердити',
      zh: '确认',
      ar: 'تأكيد',
      pl: 'Potwierdź',
      it: 'Conferma',
      sk: 'Potvrdiť',
      ja: '確認',
      ko: '확인',
      hi: 'पुष्टि करें',
      nl: 'Bevestigen',
      sv: 'Bekräfta',
      vi: 'Xác nhận',
      id: 'Konfirmasi',
    }),
    cancel: t({
      ru: 'Отменить',
      en: 'Cancel',
      kk: 'Болдырмау',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      ar: 'إلغاء',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
    }),
    working: t({
      ru: 'Выполняю…',
      en: 'Working…',
      kk: 'Орындалуда…',
      de: 'Wird ausgeführt…',
      fr: 'En cours…',
      es: 'Ejecutando…',
      pt: 'Executando…',
      tr: 'Çalışıyor…',
      uk: 'Виконую…',
      zh: '执行中…',
      ar: 'جارٍ التنفيذ…',
      pl: 'Wykonywanie…',
      it: 'In esecuzione…',
      sk: 'Vykonáva sa…',
      ja: '実行中…',
      ko: '실행 중…',
      hi: 'चल रहा है…',
      nl: 'Bezig…',
      sv: 'Arbetar…',
      vi: 'Đang thực hiện…',
      id: 'Sedang berjalan…',
    }),
    actionDone: t({
      ru: 'Готово',
      en: 'Done',
      kk: 'Дайын',
      de: 'Fertig',
      fr: 'Terminé',
      es: 'Hecho',
      pt: 'Concluído',
      tr: 'Tamamlandı',
      uk: 'Готово',
      zh: '完成',
      ar: 'تم',
      pl: 'Gotowe',
      it: 'Fatto',
      sk: 'Hotovo',
      ja: '完了',
      ko: '완료',
      hi: 'हो गया',
      nl: 'Klaar',
      sv: 'Klart',
      vi: 'Xong',
      id: 'Selesai',
    }),
    actionError: t({
      ru: 'Не получилось выполнить действие',
      en: 'The action failed',
      kk: 'Әрекет орындалмады',
      de: 'Aktion fehlgeschlagen',
      fr: "L'action a échoué",
      es: 'La acción falló',
      pt: 'A ação falhou',
      tr: 'İşlem başarısız oldu',
      uk: 'Не вдалося виконати дію',
      zh: '操作失败',
      ar: 'فشل الإجراء',
      pl: 'Akcja nie powiodła się',
      it: "L'azione non è riuscita",
      sk: 'Akcia zlyhala',
      ja: '操作に失敗しました',
      ko: '작업이 실패했습니다',
      hi: 'कार्रवाई विफल रही',
      nl: 'De actie is mislukt',
      sv: 'Åtgärden misslyckades',
      vi: 'Hành động thất bại',
      id: 'Tindakan gagal',
    }),
    actionCancelled: t({
      ru: 'Отменено',
      en: 'Cancelled',
      kk: 'Болдырылмады',
      de: 'Abgebrochen',
      fr: 'Annulé',
      es: 'Cancelado',
      pt: 'Cancelado',
      tr: 'İptal edildi',
      uk: 'Скасовано',
      zh: '已取消',
      ar: 'أُلغي',
      pl: 'Anulowano',
      it: 'Annullato',
      sk: 'Zrušené',
      ja: 'キャンセルされました',
      ko: '취소됨',
      hi: 'रद्द किया गया',
      nl: 'Geannuleerd',
      sv: 'Avbrutet',
      vi: 'Đã hủy',
      id: 'Dibatalkan',
    }),
    title: t({
      ru: 'Чат с Lumio',
      en: 'Chat with Lumio',
      kk: 'Lumio-мен чат',
      de: 'Chat mit Lumio',
      fr: 'Discuter avec Lumio',
      es: 'Chatear con Lumio',
      pt: 'Conversar com Lumio',
      tr: 'Lumio ile sohbet',
      uk: 'Чат із Lumio',
      zh: '与 Lumio 聊天',
      ar: 'الدردشة مع Lumio',
      pl: 'Czat z Lumio',
      it: 'Chatta con Lumio',
      sk: 'Chat s Lumio',
      ja: 'Lumio とチャット',
      ko: 'Lumio와 채팅',
      hi: 'Lumio से चैट करें',
      nl: 'Chatten met Lumio',
      sv: 'Chatta med Lumio',
      vi: 'Trò chuyện với Lumio',
      id: 'Ngobrol dengan Lumio',
    }),
    welcome: t({
      ru: 'Опишите, что нужно сделать, — я запишу расход, найду транзакции или покажу, куда уходят деньги.',
      en: 'Tell me what you need — I can record an expense, find transactions, or show where your money goes.',
      kk: 'Не істеу керегін айтыңыз — шығысты жазамын, транзакцияларды табамын немесе ақша қайда кеткенін көрсетемін.',
      de: 'Sagen Sie mir, was Sie brauchen — ich erfasse Ausgaben, finde Transaktionen oder zeige, wohin Ihr Geld fließt.',
      fr: "Dites-moi ce qu'il vous faut — j'enregistre une dépense, trouve des transactions ou montre où va votre argent.",
      es: 'Dime qué necesitas: registro un gasto, busco transacciones o te muestro adónde va tu dinero.',
      pt: 'Diga o que precisa — registro uma despesa, encontro transações ou mostro para onde vai seu dinheiro.',
      tr: 'Ne gerektiğini söyleyin — gider kaydederim, işlem bulurum veya paranızın nereye gittiğini gösteririm.',
      uk: 'Опишіть, що потрібно, — я запишу витрату, знайду транзакції або покажу, куди йдуть гроші.',
      zh: '告诉我您需要什么——我可以记录支出、查找交易或展示您的钱花在哪里。',
      ar: 'أخبرني بما تحتاجه — أسجّل مصروفًا أو أبحث عن معاملات أو أعرض أين تذهب أموالك.',
      pl: 'Powiedz, czego potrzebujesz — zapiszę wydatek, znajdę transakcje lub pokażę, gdzie idą pieniądze.',
      it: 'Dimmi cosa ti serve: registro una spesa, trovo transazioni o mostro dove vanno i tuoi soldi.',
      sk: 'Povedzte, čo potrebujete — zapíšem výdavok, nájdem transakcie alebo ukážem, kam idú peniaze.',
      ja: '必要なことを教えてください。支出の記録、取引の検索、お金の流れの表示ができます。',
      ko: '필요한 것을 말씀하세요 — 지출 기록, 거래 찾기, 돈의 흐름 보여드리기가 가능합니다.',
      hi: 'बताएं क्या चाहिए — मैं खर्च दर्ज करूँगा, लेन-देन खोजूँगा या दिखाऊँगा कि पैसा कहाँ जा रहा है।',
      nl: 'Vertel wat u nodig hebt — ik registreer een uitgave, vind transacties of laat zien waar uw geld heen gaat.',
      sv: 'Berätta vad du behöver — jag registrerar utgifter, hittar transaktioner eller visar vart pengarna går.',
      vi: 'Cho tôi biết bạn cần gì — tôi có thể ghi chi tiêu, tìm giao dịch hoặc cho biết tiền đi đâu.',
      id: 'Beri tahu kebutuhan Anda — saya bisa mencatat pengeluaran, mencari transaksi, atau menunjukkan ke mana uang Anda pergi.',
    }),
    exitMode: t({
      ru: 'Полный интерфейс',
      en: 'Full interface',
      kk: 'Толық интерфейс',
      de: 'Vollständige Oberfläche',
      fr: 'Interface complète',
      es: 'Interfaz completa',
      pt: 'Interface completa',
      tr: 'Tam arayüz',
      uk: 'Повний інтерфейс',
      zh: '完整界面',
      ar: 'الواجهة الكاملة',
      pl: 'Pełny interfejs',
      it: 'Interfaccia completa',
      sk: 'Plné rozhranie',
      ja: 'フル画面表示',
      ko: '전체 인터페이스',
      hi: 'पूर्ण इंटरफ़ेस',
      nl: 'Volledige interface',
      sv: 'Fullständigt gränssnitt',
      vi: 'Giao diện đầy đủ',
      id: 'Antarmuka lengkap',
    }),
    modelNeeded: t({
      ru: 'Для чата нужна локальная модель. Загрузите рекомендованную — данные не покидают устройство.',
      en: 'Chat needs a local model. Load the recommended one — your data never leaves the device.',
      kk: 'Чатқа жергілікті модель қажет. Ұсынылғанды жүктеңіз — деректер құрылғыдан шықпайды.',
      de: 'Der Chat benötigt ein lokales Modell. Laden Sie das empfohlene — Ihre Daten verlassen das Gerät nicht.',
      fr: "Le chat nécessite un modèle local. Chargez le modèle recommandé — vos données restent sur l'appareil.",
      es: 'El chat necesita un modelo local. Carga el recomendado: tus datos no salen del dispositivo.',
      pt: 'O chat precisa de um modelo local. Carregue o recomendado — seus dados não saem do dispositivo.',
      tr: 'Sohbet için yerel bir model gerekir. Önerileni yükleyin — verileriniz cihazdan çıkmaz.',
      uk: 'Для чату потрібна локальна модель. Завантажте рекомендовану — дані не залишають пристрій.',
      zh: '聊天需要本地模型。加载推荐模型——数据不会离开设备。',
      ar: 'تحتاج الدردشة إلى نموذج محلي. حمّل النموذج الموصى به — بياناتك لا تغادر الجهاز.',
      pl: 'Czat wymaga lokalnego modelu. Wczytaj zalecany — dane nie opuszczają urządzenia.',
      it: 'La chat richiede un modello locale. Carica quello consigliato: i dati non lasciano il dispositivo.',
      sk: 'Chat potrebuje lokálny model. Načítajte odporúčaný — dáta neopustia zariadenie.',
      ja: 'チャットにはローカルモデルが必要です。推奨モデルを読み込んでください。データは端末から出ません。',
      ko: '채팅에는 로컬 모델이 필요합니다. 권장 모델을 로드하세요 — 데이터는 기기를 떠나지 않습니다.',
      hi: 'चैट के लिए लोकल मॉडल चाहिए। अनुशंसित मॉडल लोड करें — डेटा डिवाइस से बाहर नहीं जाता।',
      nl: 'Chat vereist een lokaal model. Laad het aanbevolen model — uw gegevens verlaten het apparaat niet.',
      sv: 'Chatten kräver en lokal modell. Ladda den rekommenderade — dina data lämnar aldrig enheten.',
      vi: 'Trò chuyện cần mô hình cục bộ. Hãy tải mô hình được đề xuất — dữ liệu không rời khỏi thiết bị.',
      id: 'Obrolan memerlukan model lokal. Muat model yang direkomendasikan — data Anda tidak meninggalkan perangkat.',
    }),
    loadModel: t({
      ru: 'Загрузить модель',
      en: 'Load model',
      kk: 'Модельді жүктеу',
      de: 'Modell laden',
      fr: 'Charger le modèle',
      es: 'Cargar modelo',
      pt: 'Carregar modelo',
      tr: 'Modeli yükle',
      uk: 'Завантажити модель',
      zh: '加载模型',
      ar: 'تحميل النموذج',
      pl: 'Wczytaj model',
      it: 'Carica modello',
      sk: 'Načítať model',
      ja: 'モデルを読み込む',
      ko: '모델 로드',
      hi: 'मॉडल लोड करें',
      nl: 'Model laden',
      sv: 'Ladda modell',
      vi: 'Tải mô hình',
      id: 'Muat model',
    }),
    manageModels: t({
      ru: 'Управление моделями',
      en: 'Manage models',
      kk: 'Модельдерді басқару',
      de: 'Modelle verwalten',
      fr: 'Gérer les modèles',
      es: 'Gestionar modelos',
      pt: 'Gerenciar modelos',
      tr: 'Modelleri yönet',
      uk: 'Керування моделями',
      zh: '管理模型',
      ar: 'إدارة النماذج',
      pl: 'Zarządzaj modelami',
      it: 'Gestisci modelli',
      sk: 'Spravovať modely',
      ja: 'モデルを管理',
      ko: '모델 관리',
      hi: 'मॉडल प्रबंधित करें',
      nl: 'Modellen beheren',
      sv: 'Hantera modeller',
      vi: 'Quản lý mô hình',
      id: 'Kelola model',
    }),
    placeholder: t({
      ru: 'Напишите сообщение…',
      en: 'Type a message…',
      kk: 'Хабарлама жазыңыз…',
      de: 'Nachricht eingeben…',
      fr: 'Écrivez un message…',
      es: 'Escribe un mensaje…',
      pt: 'Digite uma mensagem…',
      tr: 'Bir mesaj yazın…',
      uk: 'Напишіть повідомлення…',
      zh: '输入消息…',
      ar: 'اكتب رسالة…',
      pl: 'Napisz wiadomość…',
      it: 'Scrivi un messaggio…',
      sk: 'Napíšte správu…',
      ja: 'メッセージを入力…',
      ko: '메시지를 입력하세요…',
      hi: 'संदेश लिखें…',
      nl: 'Typ een bericht…',
      sv: 'Skriv ett meddelande…',
      vi: 'Nhập tin nhắn…',
      id: 'Ketik pesan…',
    }),
    send: t({
      ru: 'Отправить',
      en: 'Send',
      kk: 'Жіберу',
      de: 'Senden',
      fr: 'Envoyer',
      es: 'Enviar',
      pt: 'Enviar',
      tr: 'Gönder',
      uk: 'Надіслати',
      zh: '发送',
      ar: 'إرسال',
      pl: 'Wyślij',
      it: 'Invia',
      sk: 'Odoslať',
      ja: '送信',
      ko: '보내기',
      hi: 'भेजें',
      nl: 'Versturen',
      sv: 'Skicka',
      vi: 'Gửi',
      id: 'Kirim',
    }),
    stop: t({
      ru: 'Стоп',
      en: 'Stop',
      kk: 'Тоқтату',
      de: 'Stopp',
      fr: 'Stop',
      es: 'Detener',
      pt: 'Parar',
      tr: 'Durdur',
      uk: 'Стоп',
      zh: '停止',
      ar: 'إيقاف',
      pl: 'Stop',
      it: 'Stop',
      sk: 'Stop',
      ja: '停止',
      ko: '중지',
      hi: 'रोकें',
      nl: 'Stop',
      sv: 'Stoppa',
      vi: 'Dừng',
      id: 'Berhenti',
    }),
    newChat: t({
      ru: 'Новый чат',
      en: 'New chat',
      kk: 'Жаңа чат',
      de: 'Neuer Chat',
      fr: 'Nouvelle discussion',
      es: 'Nuevo chat',
      pt: 'Novo chat',
      tr: 'Yeni sohbet',
      uk: 'Новий чат',
      zh: '新聊天',
      ar: 'محادثة جديدة',
      pl: 'Nowy czat',
      it: 'Nuova chat',
      sk: 'Nový chat',
      ja: '新しいチャット',
      ko: '새 채팅',
      hi: 'नई चैट',
      nl: 'Nieuwe chat',
      sv: 'Ny chatt',
      vi: 'Cuộc trò chuyện mới',
      id: 'Obrolan baru',
    }),
    chipExpense: t({
      ru: 'Добавить расход',
      en: 'Add an expense',
      kk: 'Шығыс қосу',
      de: 'Ausgabe hinzufügen',
      fr: 'Ajouter une dépense',
      es: 'Añadir un gasto',
      pt: 'Adicionar despesa',
      tr: 'Gider ekle',
      uk: 'Додати витрату',
      zh: '添加支出',
      ar: 'إضافة مصروف',
      pl: 'Dodaj wydatek',
      it: 'Aggiungi una spesa',
      sk: 'Pridať výdavok',
      ja: '支出を追加',
      ko: '지출 추가',
      hi: 'खर्च जोड़ें',
      nl: 'Uitgave toevoegen',
      sv: 'Lägg till utgift',
      vi: 'Thêm chi tiêu',
      id: 'Tambah pengeluaran',
    }),
    chipUpload: t({
      ru: 'Загрузить выписку',
      en: 'Upload a statement',
      kk: 'Үзінді жүктеу',
      de: 'Kontoauszug hochladen',
      fr: 'Importer un relevé',
      es: 'Subir un extracto',
      pt: 'Enviar um extrato',
      tr: 'Hesap özeti yükle',
      uk: 'Завантажити виписку',
      zh: '上传对账单',
      ar: 'رفع كشف حساب',
      pl: 'Wgraj wyciąg',
      it: 'Carica un estratto conto',
      sk: 'Nahrať výpis',
      ja: '明細をアップロード',
      ko: '명세서 업로드',
      hi: 'स्टेटमेंट अपलोड करें',
      nl: 'Afschrift uploaden',
      sv: 'Ladda upp kontoutdrag',
      vi: 'Tải lên sao kê',
      id: 'Unggah laporan',
    }),
    chipSpend: t({
      ru: 'Сколько я потратил в этом месяце?',
      en: 'How much did I spend this month?',
      kk: 'Осы айда қанша жұмсадым?',
      de: 'Wie viel habe ich diesen Monat ausgegeben?',
      fr: 'Combien ai-je dépensé ce mois-ci ?',
      es: '¿Cuánto gasté este mes?',
      pt: 'Quanto gastei este mês?',
      tr: 'Bu ay ne kadar harcadım?',
      uk: 'Скільки я витратив цього місяця?',
      zh: '这个月我花了多少钱？',
      ar: 'كم أنفقت هذا الشهر؟',
      pl: 'Ile wydałem w tym miesiącu?',
      it: 'Quanto ho speso questo mese?',
      sk: 'Koľko som minul tento mesiac?',
      ja: '今月いくら使いましたか？',
      ko: '이번 달에 얼마나 썼나요?',
      hi: 'इस महीने मैंने कितना खर्च किया?',
      nl: 'Hoeveel heb ik deze maand uitgegeven?',
      sv: 'Hur mycket spenderade jag denna månad?',
      vi: 'Tháng này tôi đã chi bao nhiêu?',
      id: 'Berapa pengeluaran saya bulan ini?',
    }),
    cloudModel: t({
      ru: 'Облачная модель',
      en: 'Cloud model',
      kk: 'Бұлттық модель',
      de: 'Cloud-Modell',
      fr: 'Modèle cloud',
      es: 'Modelo en la nube',
      pt: 'Modelo na nuvem',
      tr: 'Bulut modeli',
      uk: 'Хмарна модель',
      zh: '云端模型',
      ar: 'نموذج سحابي',
      pl: 'Model w chmurze',
      it: 'Modello cloud',
      sk: 'Cloudový model',
      ja: 'クラウドモデル',
      ko: '클라우드 모델',
      hi: 'क्लाउड मॉडल',
      nl: 'Cloudmodel',
      sv: 'Molnmodell',
      vi: 'Mô hình đám mây',
      id: 'Model cloud',
    }),
    cloudNotice: t({
      ru: 'Запросы обрабатывает внешний провайдер — данные покидают ваш инстанс.',
      en: 'Requests are served by an external provider — data leaves your instance.',
      kk: 'Сұраныстарды сыртқы провайдер өңдейді — деректер инстансыңыздан шығады.',
      de: 'Anfragen werden von einem externen Anbieter verarbeitet — Daten verlassen Ihre Instanz.',
      fr: 'Les requêtes sont traitées par un fournisseur externe — les données quittent votre instance.',
      es: 'Las solicitudes las atiende un proveedor externo: los datos salen de tu instancia.',
      pt: 'As solicitações são atendidas por um provedor externo — os dados saem da sua instância.',
      tr: 'İstekler harici bir sağlayıcı tarafından işlenir — veriler örneğinizden çıkar.',
      uk: 'Запити обробляє зовнішній провайдер — дані залишають ваш інстанс.',
      zh: '请求由外部提供商处理——数据会离开您的实例。',
      ar: 'تُعالج الطلبات عبر مزوّد خارجي — تغادر البيانات خادمك.',
      pl: 'Żądania obsługuje zewnętrzny dostawca — dane opuszczają twoją instancję.',
      it: 'Le richieste sono gestite da un provider esterno: i dati lasciano la tua istanza.',
      sk: 'Požiadavky spracúva externý poskytovateľ — dáta opúšťajú vašu inštanciu.',
      ja: 'リクエストは外部プロバイダーが処理します。データはインスタンスの外に送信されます。',
      ko: '요청은 외부 제공업체가 처리합니다 — 데이터가 인스턴스를 벗어납니다.',
      hi: 'अनुरोध बाहरी प्रदाता द्वारा संसाधित होते हैं — डेटा आपके इंस्टेंस से बाहर जाता है।',
      nl: 'Verzoeken worden verwerkt door een externe provider — gegevens verlaten uw instantie.',
      sv: 'Förfrågningar hanteras av en extern leverantör — data lämnar din instans.',
      vi: 'Yêu cầu được xử lý bởi nhà cung cấp bên ngoài — dữ liệu rời khỏi phiên bản của bạn.',
      id: 'Permintaan dilayani penyedia eksternal — data keluar dari instans Anda.',
    }),
    configureCloud: t({
      ru: 'Настроить облачную модель',
      en: 'Set up a cloud model',
      kk: 'Бұлттық модельді баптау',
      de: 'Cloud-Modell einrichten',
      fr: 'Configurer un modèle cloud',
      es: 'Configurar un modelo en la nube',
      pt: 'Configurar um modelo na nuvem',
      tr: 'Bulut modeli ayarla',
      uk: 'Налаштувати хмарну модель',
      zh: '设置云端模型',
      ar: 'إعداد نموذج سحابي',
      pl: 'Skonfiguruj model w chmurze',
      it: 'Configura un modello cloud',
      sk: 'Nastaviť cloudový model',
      ja: 'クラウドモデルを設定',
      ko: '클라우드 모델 설정',
      hi: 'क्लाउड मॉडल सेट करें',
      nl: 'Cloudmodel instellen',
      sv: 'Konfigurera molnmodell',
      vi: 'Thiết lập mô hình đám mây',
      id: 'Siapkan model cloud',
    }),
    confirmPrompt: t({
      ru: 'Подтвердите действие:',
      en: 'Confirm this action:',
      kk: 'Әрекетті растаңыз:',
      de: 'Aktion bestätigen:',
      fr: 'Confirmez cette action :',
      es: 'Confirma esta acción:',
      pt: 'Confirme esta ação:',
      tr: 'Bu işlemi onaylayın:',
      uk: 'Підтвердьте дію:',
      zh: '请确认此操作：',
      ar: 'أكّد هذا الإجراء:',
      pl: 'Potwierdź tę akcję:',
      it: 'Conferma questa azione:',
      sk: 'Potvrďte túto akciu:',
      ja: 'この操作を確認してください：',
      ko: '이 작업을 확인하세요:',
      hi: 'इस कार्रवाई की पुष्टि करें:',
      nl: 'Bevestig deze actie:',
      sv: 'Bekräfta denna åtgärd:',
      vi: 'Xác nhận hành động này:',
      id: 'Konfirmasi tindakan ini:',
    }),
  },
} satisfies Dictionary;

export default content;
