import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementDroppedSampleForm',
  content: {
    date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      ar: 'التاريخ',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
    }),
    counterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı taraf',
      uk: 'Контрагент',
      zh: '交易对方',
      ar: 'الطرف المقابل',
      pl: 'Kontrahent',
      it: 'Controparte',
      sk: 'Protistrana',
      ja: '取引先',
      ko: '거래 상대방',
      hi: 'प्रतिपक्ष',
      nl: 'Tegenpartij',
      sv: 'Motpart',
      vi: 'Đối tác',
      id: 'Pihak lawan',
    }),
    paymentPurpose: t({
      ru: 'Назначение платежа',
      en: 'Payment purpose',
      kk: 'Төлем мақсаты',
      de: 'Verwendungszweck',
      fr: 'Motif du paiement',
      es: 'Concepto del pago',
      pt: 'Finalidade do pagamento',
      tr: 'Ödeme amacı',
      uk: 'Призначення платежу',
      zh: '付款用途',
      ar: 'الغرض من الدفع',
      pl: 'Tytuł płatności',
      it: 'Causale del pagamento',
      sk: 'Účel platby',
      ja: '支払目的',
      ko: '결제 목적',
      hi: 'भुगतान का उद्देश्य',
      nl: 'Omschrijving betaling',
      sv: 'Betalningsändamål',
      vi: 'Mục đích thanh toán',
      id: 'Tujuan pembayaran',
    }),
    currency: t({
      ru: 'Валюта',
      en: 'Currency',
      kk: 'Валюта',
      de: 'Währung',
      fr: 'Devise',
      es: 'Moneda',
      pt: 'Moeda',
      tr: 'Para birimi',
      uk: 'Валюта',
      zh: '货币',
      ar: 'العملة',
      pl: 'Waluta',
      it: 'Valuta',
      sk: 'Mena',
      ja: '通貨',
      ko: '통화',
      hi: 'मुद्रा',
      nl: 'Valuta',
      sv: 'Valuta',
      vi: 'Tiền tệ',
      id: 'Mata uang',
    }),
    debit: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Débito',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      ar: 'مدين',
      pl: 'Obciążenie',
      it: 'Addebito',
      sk: 'Debet',
      ja: '借方',
      ko: '차변',
      hi: 'डेबिट',
      nl: 'Debet',
      sv: 'Debet',
      vi: 'Ghi nợ',
      id: 'Debit',
    }),
    credit: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Crédito',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      ar: 'دائن',
      pl: 'Uznanie',
      it: 'Accredito',
      sk: 'Kredit',
      ja: '貸方',
      ko: '대변',
      hi: 'क्रेडिट',
      nl: 'Credit',
      sv: 'Kredit',
      vi: 'Ghi có',
      id: 'Kredit',
    }),
    hint: t({
      ru: 'Укажите корректную дату и дебет или кредит, чтобы преобразовать эту строку.',
      en: 'Fill in a valid date and either debit or credit to convert this row.',
      kk: 'Бұл жолды түрлендіру үшін дұрыс күнді және дебетті немесе кредитті толтырыңыз.',
      de: 'Gib ein gültiges Datum und entweder Soll oder Haben ein, um diese Zeile umzuwandeln.',
      fr: 'Renseignez une date valide et un débit ou un crédit pour convertir cette ligne.',
      es: 'Introduce una fecha válida y un débito o un crédito para convertir esta fila.',
      pt: 'Preencha uma data válida e um débito ou crédito para converter esta linha.',
      tr: 'Bu satırı dönüştürmek için geçerli bir tarih ve borç ya da alacak girin.',
      uk: 'Вкажіть коректну дату та дебет або кредит, щоб перетворити цей рядок.',
      zh: '请填写有效日期以及借方或贷方金额，以转换此行。',
      ar: 'أدخل تاريخًا صالحًا ومبلغًا مدينًا أو دائنًا لتحويل هذا الصف.',
      pl: 'Podaj prawidłową datę oraz obciążenie lub uznanie, aby przekształcić ten wiersz.',
      it: 'Inserisci una data valida e un addebito o un accredito per convertire questa riga.',
      sk: 'Vyplňte platný dátum a buď debet, alebo kredit, aby ste tento riadok previedli.',
      ja: 'この行を変換するには、有効な日付と借方または貸方を入力してください。',
      ko: '이 행을 변환하려면 유효한 날짜와 차변 또는 대변을 입력하세요.',
      hi: 'इस पंक्ति को बदलने के लिए एक मान्य तारीख और डेबिट या क्रेडिट भरें।',
      nl: 'Vul een geldige datum en een debet- of creditbedrag in om deze rij om te zetten.',
      sv: 'Ange ett giltigt datum och antingen debet eller kredit för att konvertera raden.',
      vi: 'Nhập ngày hợp lệ và ghi nợ hoặc ghi có để chuyển đổi dòng này.',
      id: 'Isi tanggal yang valid dan debit atau kredit untuk mengonversi baris ini.',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Бас тарту',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      ar: 'إلغاء',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
    }),
    convert: t({
      ru: 'Преобразовать в транзакцию',
      en: 'Convert to transaction',
      kk: 'Транзакцияға түрлендіру',
      de: 'In Transaktion umwandeln',
      fr: 'Convertir en transaction',
      es: 'Convertir en transacción',
      pt: 'Converter em transação',
      tr: 'İşleme dönüştür',
      uk: 'Перетворити на транзакцію',
      zh: '转换为交易',
      ar: 'تحويل إلى معاملة',
      pl: 'Przekształć w transakcję',
      it: 'Converti in transazione',
      sk: 'Previesť na transakciu',
      ja: '取引に変換',
      ko: '거래로 변환',
      hi: 'लेनदेन में बदलें',
      nl: 'Omzetten naar transactie',
      sv: 'Konvertera till transaktion',
      vi: 'Chuyển thành giao dịch',
      id: 'Konversi ke transaksi',
    }),
    dialogTitle: t({
      ru: 'Преобразовать пропущенную строку',
      en: 'Convert dropped row',
      kk: 'Өткізілген жолды түрлендіру',
      de: 'Übersprungene Zeile umwandeln',
      fr: 'Convertir la ligne ignorée',
      es: 'Convertir la fila omitida',
      pt: 'Converter linha ignorada',
      tr: 'Atlanan satırı dönüştür',
      uk: 'Перетворити пропущений рядок',
      zh: '转换被跳过的行',
      ar: 'تحويل الصف المُسقَط',
      pl: 'Przekształć pominięty wiersz',
      it: 'Converti la riga scartata',
      sk: 'Previesť vynechaný riadok',
      ja: '除外された行を変換',
      ko: '누락된 행 변환',
      hi: 'छोड़ी गई पंक्ति बदलें',
      nl: 'Overgeslagen rij omzetten',
      sv: 'Konvertera överhoppad rad',
      vi: 'Chuyển đổi dòng bị bỏ qua',
      id: 'Konversi baris yang dilewati',
    }),
  },
} satisfies Dictionary;

export default content;
