import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementDroppedSampleForm',
  content: {
    date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
      da: 'Dato',
      nb: 'Dato',
      nn: 'Dato',
      fi: 'Päivämäärä',
      is: 'Dagsetning',
      fo: 'Dato',
      cs: 'Datum',
      bg: 'Дата',
      hr: 'Datum',
      sr: 'Датум',
      sl: 'Datum',
      mk: 'Датум',
      be: 'Дата',
      bs: 'Datum',
      hsb: 'Datum',
    }),
    counterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı taraf',
      uk: 'Контрагент',
      zh: '交易对方',
      pl: 'Kontrahent',
      it: 'Controparte',
      sk: 'Protistrana',
      ja: '取引先',
      ko: '거래 상대방',
      hi: 'प्रतिपक्ष',
      nl: 'Tegenpartij',
      sv: 'Motpart',
      vi: 'Đối tác',
      id: 'Pihak lawan',
      da: 'Modpart',
      nb: 'Motpart',
      nn: 'Motpart',
      fi: 'Vastapuoli',
      is: 'Gagnaðili',
      fo: 'Mótpartur',
      cs: 'Protistrana',
      bg: 'Контрагент',
      hr: 'Druga strana',
      sr: 'Друга страна',
      sl: 'Nasprotna stranka',
      mk: 'Другата страна',
      be: 'Кантрагент',
      bs: 'Druga strana',
      hsb: 'Přećiwna strona',
    }),
    paymentPurpose: t({
      ru: 'Назначение платежа',
      en: 'Payment purpose',
      kk: 'Төлем мақсаты',
      de: 'Verwendungszweck',
      fr: 'Motif du paiement',
      es: 'Concepto del pago',
      pt: 'Finalidade do pagamento',
      tr: 'Ödeme amacı',
      uk: 'Призначення платежу',
      zh: '付款用途',
      pl: 'Tytuł płatności',
      it: 'Causale del pagamento',
      sk: 'Účel platby',
      ja: '支払目的',
      ko: '결제 목적',
      hi: 'भुगतान का उद्देश्य',
      nl: 'Omschrijving betaling',
      sv: 'Betalningsändamål',
      vi: 'Mục đích thanh toán',
      id: 'Tujuan pembayaran',
      da: 'Betalingsformål',
      nb: 'Betalingsformål',
      nn: 'Betalingsformål',
      fi: 'Maksun tarkoitus',
      is: 'Tilgangur greiðslu',
      fo: 'Endamál við gjaldinum',
      cs: 'Účel platby',
      bg: 'Основание за плащане',
      hr: 'Namjena plaćanja',
      sr: 'Намена плаћања',
      sl: 'Namen plačila',
      mk: 'Намена на плаќањето',
      be: 'Прызначэнне плацяжу',
      bs: 'Namjena plaćanja',
      hsb: 'Zaměr zapłaćenja',
    }),
    currency: t({
      ru: 'Валюта',
      en: 'Currency',
      kk: 'Валюта',
      de: 'Währung',
      fr: 'Devise',
      es: 'Moneda',
      pt: 'Moeda',
      tr: 'Para birimi',
      uk: 'Валюта',
      zh: '货币',
      pl: 'Waluta',
      it: 'Valuta',
      sk: 'Mena',
      ja: '通貨',
      ko: '통화',
      hi: 'मुद्रा',
      nl: 'Valuta',
      sv: 'Valuta',
      vi: 'Tiền tệ',
      id: 'Mata uang',
      da: 'Valuta',
      nb: 'Valuta',
      nn: 'Valuta',
      fi: 'Valuutta',
      is: 'Mynt',
      fo: 'Gjaldoyra',
      cs: 'Měna',
      bg: 'Валута',
      hr: 'Valuta',
      sr: 'Валута',
      sl: 'Valuta',
      mk: 'Валута',
      be: 'Валюта',
      bs: 'Valuta',
      hsb: 'Waluta',
    }),
    debit: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Débito',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      pl: 'Obciążenie',
      it: 'Addebito',
      sk: 'Debet',
      ja: '借方',
      ko: '차변',
      hi: 'डेबिट',
      nl: 'Debet',
      sv: 'Debet',
      vi: 'Ghi nợ',
      id: 'Debit',
      da: 'Debet',
      nb: 'Debet',
      nn: 'Debet',
      fi: 'Debet',
      is: 'Debet',
      fo: 'Debet',
      cs: 'Debet',
      bg: 'Дебит',
      hr: 'Duguje',
      sr: 'Дугује',
      sl: 'Debet',
      mk: 'Должи',
      be: 'Дэбет',
      bs: 'Duguje',
      hsb: 'Debet',
    }),
    credit: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Crédito',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      pl: 'Uznanie',
      it: 'Accredito',
      sk: 'Kredit',
      ja: '貸方',
      ko: '대변',
      hi: 'क्रेडिट',
      nl: 'Credit',
      sv: 'Kredit',
      vi: 'Ghi có',
      id: 'Kredit',
      da: 'Kredit',
      nb: 'Kredit',
      nn: 'Kredit',
      fi: 'Kredit',
      is: 'Kredit',
      fo: 'Kredit',
      cs: 'Kredit',
      bg: 'Кредит',
      hr: 'Potražuje',
      sr: 'Потражује',
      sl: 'Kredit',
      mk: 'Побарува',
      be: 'Крэдыт',
      bs: 'Potražuje',
      hsb: 'Kredit',
    }),
    hint: t({
      ru: 'Укажите корректную дату и дебет или кредит, чтобы преобразовать эту строку.',
      en: 'Fill in a valid date and either debit or credit to convert this row.',
      kk: 'Бұл жолды түрлендіру үшін дұрыс күнді және дебетті немесе кредитті толтырыңыз.',
      de: 'Gib ein gültiges Datum und entweder Soll oder Haben ein, um diese Zeile umzuwandeln.',
      fr: 'Renseignez une date valide et un débit ou un crédit pour convertir cette ligne.',
      es: 'Introduce una fecha válida y un débito o un crédito para convertir esta fila.',
      pt: 'Preencha uma data válida e um débito ou crédito para converter esta linha.',
      tr: 'Bu satırı dönüştürmek için geçerli bir tarih ve borç ya da alacak girin.',
      uk: 'Вкажіть коректну дату та дебет або кредит, щоб перетворити цей рядок.',
      zh: '请填写有效日期以及借方或贷方金额，以转换此行。',
      pl: 'Podaj prawidłową datę oraz obciążenie lub uznanie, aby przekształcić ten wiersz.',
      it: 'Inserisci una data valida e un addebito o un accredito per convertire questa riga.',
      sk: 'Vyplňte platný dátum a buď debet, alebo kredit, aby ste tento riadok previedli.',
      ja: 'この行を変換するには、有効な日付と借方または貸方を入力してください。',
      ko: '이 행을 변환하려면 유효한 날짜와 차변 또는 대변을 입력하세요.',
      hi: 'इस पंक्ति को बदलने के लिए एक मान्य तारीख और डेबिट या क्रेडिट भरें।',
      nl: 'Vul een geldige datum en een debet- of creditbedrag in om deze rij om te zetten.',
      sv: 'Ange ett giltigt datum och antingen debet eller kredit för att konvertera raden.',
      vi: 'Nhập ngày hợp lệ và ghi nợ hoặc ghi có để chuyển đổi dòng này.',
      id: 'Isi tanggal yang valid dan debit atau kredit untuk mengonversi baris ini.',
      da: 'Udfyld en gyldig dato og enten debet eller kredit for at konvertere denne række.',
      nb: 'Fyll inn en gyldig dato og enten debet eller kredit for å konvertere denne raden.',
      nn: 'Fyll inn ein gyldig dato og anten debet eller kredit for å konvertere denne rada.',
      fi: 'Täytä kelvollinen päivämäärä ja joko debet tai kredit, niin voit muuntaa tämän rivin.',
      is: 'Fylltu út gilda dagsetningu og annaðhvort debet eða kredit til að umbreyta þessari röð.',
      fo: 'Fyll eina galdandi dato út og antin debet ella kredit fyri at umskapa hesa røð.',
      cs: 'Zadejte platné datum a buď debet, nebo kredit, abyste tento řádek převedli.',
      bg: 'Попълнете валидна дата и дебит или кредит, за да преобразувате този ред.',
      hr: 'Ispunite ispravan datum i duguje ili potražuje da pretvorite ovaj red.',
      sr: 'Унесите исправан датум и дугује или потражује да претворите овај ред.',
      sl: 'Vnesite veljaven datum in debet ali kredit, da pretvorite to vrstico.',
      mk: 'Внесете валиден датум и должи или побарува за да го претворите овој ред.',
      be: 'Увядзіце карэктную дату і дэбет або крэдыт, каб пераўтварыць гэты радок.',
      bs: 'Ispunite ispravan datum i duguje ili potražuje da pretvorite ovaj red.',
      hsb: 'Zapodajće płaćiwy datum a pak debet pak kredit, zo byšće tutu linku konwertował.',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Бас тарту',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
      da: 'Annuller',
      nb: 'Avbryt',
      nn: 'Avbryt',
      fi: 'Peruuta',
      is: 'Hætta',
      fo: 'Avbrót',
      cs: 'Zrušit',
      bg: 'Отказ',
      hr: 'Odustani',
      sr: 'Откажи',
      sl: 'Prekliči',
      mk: 'Откажи',
      be: 'Скасаваць',
      bs: 'Otkaži',
      hsb: 'Přetorhnyć',
    }),
    convert: t({
      ru: 'Преобразовать в транзакцию',
      en: 'Convert to transaction',
      kk: 'Транзакцияға түрлендіру',
      de: 'In Transaktion umwandeln',
      fr: 'Convertir en transaction',
      es: 'Convertir en transacción',
      pt: 'Converter em transação',
      tr: 'İşleme dönüştür',
      uk: 'Перетворити на транзакцію',
      zh: '转换为交易',
      pl: 'Przekształć w transakcję',
      it: 'Converti in transazione',
      sk: 'Previesť na transakciu',
      ja: '取引に変換',
      ko: '거래로 변환',
      hi: 'लेनदेन में बदलें',
      nl: 'Omzetten naar transactie',
      sv: 'Konvertera till transaktion',
      vi: 'Chuyển thành giao dịch',
      id: 'Konversi ke transaksi',
      da: 'Konvertér til postering',
      nb: 'Konverter til transaksjon',
      nn: 'Konverter til transaksjon',
      fi: 'Muunna tapahtumaksi',
      is: 'Umbreyta í færslu',
      fo: 'Umskapa til postering',
      cs: 'Převést na transakci',
      bg: 'Преобразувай в транзакция',
      hr: 'Pretvori u transakciju',
      sr: 'Претвори у трансакцију',
      sl: 'Pretvori v transakcijo',
      mk: 'Претвори во трансакција',
      be: 'Пераўтварыць у транзакцыю',
      bs: 'Pretvori u transakciju',
      hsb: 'Do transakcije konwertować',
    }),
    dialogTitle: t({
      ru: 'Преобразовать пропущенную строку',
      en: 'Convert dropped row',
      kk: 'Өткізілген жолды түрлендіру',
      de: 'Übersprungene Zeile umwandeln',
      fr: 'Convertir la ligne ignorée',
      es: 'Convertir la fila omitida',
      pt: 'Converter linha ignorada',
      tr: 'Atlanan satırı dönüştür',
      uk: 'Перетворити пропущений рядок',
      zh: '转换被跳过的行',
      pl: 'Przekształć pominięty wiersz',
      it: 'Converti la riga scartata',
      sk: 'Previesť vynechaný riadok',
      ja: '除外された行を変換',
      ko: '누락된 행 변환',
      hi: 'छोड़ी गई पंक्ति बदलें',
      nl: 'Overgeslagen rij omzetten',
      sv: 'Konvertera överhoppad rad',
      vi: 'Chuyển đổi dòng bị bỏ qua',
      id: 'Konversi baris yang dilewati',
      da: 'Konvertér udeladt række',
      nb: 'Konverter utelatt rad',
      nn: 'Konverter utelaten rad',
      fi: 'Muunna hylätty rivi',
      is: 'Umbreyta sleppti röð',
      fo: 'Umskapa útihýsta røð',
      cs: 'Převést vynechaný řádek',
      bg: 'Преобразуване на пропуснат ред',
      hr: 'Pretvori izostavljeni red',
      sr: 'Претвори изостављени ред',
      sl: 'Pretvori izpuščeno vrstico',
      mk: 'Претвори изоставен ред',
      be: 'Пераўтварыць прапушчаны радок',
      bs: 'Pretvori izostavljeni red',
      hsb: 'Wuwostajenu linku konwertować',
    }),
  },
} satisfies Dictionary;

export default content;
