import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'statementEditPageColumns',
  content: {
    date: t({
      ru: 'Дата',
      en: 'Date',
      kk: 'Күні',
      de: 'Datum',
      fr: 'Date',
      es: 'Fecha',
      pt: 'Data',
      tr: 'Tarih',
      uk: 'Дата',
      zh: '日期',
      pl: 'Data',
      it: 'Data',
      sk: 'Dátum',
      ja: '日付',
      ko: '날짜',
      hi: 'तारीख',
      nl: 'Datum',
      sv: 'Datum',
      vi: 'Ngày',
      id: 'Tanggal',
      da: 'Dato',
      nb: 'Dato',
      nn: 'Dato',
      fi: 'Päivämäärä',
      is: 'Dagsetning',
      fo: 'Dato',
      cs: 'Datum',
      bg: 'Дата',
      hr: 'Datum',
      sr: 'Датум',
      sl: 'Datum',
      mk: 'Датум',
      be: 'Дата',
      bs: 'Datum',
      hsb: 'Datum',
    }),
    counterparty: t({
      ru: 'Контрагент',
      en: 'Counterparty',
      kk: 'Контрагент',
      de: 'Gegenpartei',
      fr: 'Contrepartie',
      es: 'Contraparte',
      pt: 'Contraparte',
      tr: 'Karşı Taraf',
      uk: 'Контрагент',
      zh: '对手方',
      pl: 'Kontrahent',
      it: 'Controparte',
      sk: 'Protistrana',
      ja: '取引相手',
      ko: '상대방',
      hi: 'प्रतिपक्ष',
      nl: 'Tegenpartij',
      sv: 'Motpart',
      vi: 'Đối tác',
      id: 'Pihak Lawan',
      da: 'Modpart',
      nb: 'Motpart',
      nn: 'Motpart',
      fi: 'Vastapuoli',
      is: 'Gagnaðili',
      fo: 'Mótpartur',
      cs: 'Protistrana',
      bg: 'Контрагент',
      hr: 'Druga strana',
      sr: 'Друга страна',
      sl: 'Nasprotna stranka',
      mk: 'Другата страна',
      be: 'Кантрагент',
      bs: 'Druga strana',
      hsb: 'Přećiwna strona',
    }),
    paymentPurposeShort: t({
      ru: 'Назначение платежа',
      en: 'Payment purpose',
      kk: 'Төлем мақсаты',
      de: 'Zahlungszweck',
      fr: 'Objet du paiement',
      es: 'Propósito del pago',
      pt: 'Finalidade do pagamento',
      tr: 'Ödeme amacı',
      uk: 'Призначення платежу',
      zh: '付款用途',
      pl: 'Cel płatności',
      it: 'Scopo del pagamento',
      sk: 'Účel platby',
      ja: '支払目的',
      ko: '결제 목적',
      hi: 'भुगतान का उद्देश्य',
      nl: 'Betalingsdoel',
      sv: 'Betalningssyfte',
      vi: 'Mục đích thanh toán',
      id: 'Tujuan pembayaran',
      da: 'Betalingsformål',
      nb: 'Betalingsformål',
      nn: 'Betalingsformål',
      fi: 'Maksun tarkoitus',
      is: 'Tilgangur greiðslu',
      fo: 'Endamál við gjaldinum',
      cs: 'Účel platby',
      bg: 'Основание за плащане',
      hr: 'Namjena plaćanja',
      sr: 'Намена плаћања',
      sl: 'Namen plačila',
      mk: 'Намена на плаќањето',
      be: 'Прызначэнне плацяжу',
      bs: 'Namjena plaćanja',
      hsb: 'Zaměr zapłaćenja',
    }),
    expense: t({
      ru: 'Расход',
      en: 'Expense',
      kk: 'Шығыс',
      de: 'Ausgabe',
      fr: 'Dépense',
      es: 'Gasto',
      pt: 'Despesa',
      tr: 'Gider',
      uk: 'Витрата',
      zh: '支出',
      pl: 'Wydatek',
      it: 'Spesa',
      sk: 'Výdavok',
      ja: '支出',
      ko: '지출',
      hi: 'व्यय',
      nl: 'Uitgave',
      sv: 'Utgift',
      vi: 'Chi phí',
      id: 'Pengeluaran',
      da: 'Udgift',
      nb: 'Utgift',
      nn: 'Utgift',
      fi: 'Meno',
      is: 'Útgjöld',
      fo: 'Útgjald',
      cs: 'Výdaj',
      bg: 'Разход',
      hr: 'Rashod',
      sr: 'Расход',
      sl: 'Izdatek',
      mk: 'Трошок',
      be: 'Выдатак',
      bs: 'Rashod',
      hsb: 'Wudawk',
    }),
    income: t({
      ru: 'Доход',
      en: 'Income',
      kk: 'Кіріс',
      de: 'Einnahme',
      fr: 'Revenu',
      es: 'Ingreso',
      pt: 'Receita',
      tr: 'Gelir',
      uk: 'Дохід',
      zh: '收入',
      pl: 'Przychód',
      it: 'Entrata',
      sk: 'Príjem',
      ja: '収入',
      ko: '수입',
      hi: 'आय',
      nl: 'Inkomsten',
      sv: 'Inkomst',
      vi: 'Thu nhập',
      id: 'Pendapatan',
      da: 'Indtægt',
      nb: 'Inntekt',
      nn: 'Inntekt',
      fi: 'Tulo',
      is: 'Tekjur',
      fo: 'Inntøka',
      cs: 'Příjem',
      bg: 'Приход',
      hr: 'Prihod',
      sr: 'Приход',
      sl: 'Prihodek',
      mk: 'Приход',
      be: 'Прыбытак',
      bs: 'Prihod',
      hsb: 'Dochod',
    }),
    category: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '类别',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategória',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
      da: 'Kategori',
      nb: 'Kategori',
      nn: 'Kategori',
      fi: 'Kategoria',
      is: 'Kategoría',
      fo: 'Bólkur',
      cs: 'Kategorie',
      bg: 'Категория',
      hr: 'Kategorija',
      sr: 'Категорија',
      sl: 'Kategorija',
      mk: 'Категорија',
      be: 'Катэгорыя',
      bs: 'Kategorija',
      hsb: 'Kategorija',
    }),
    actions: t({
      ru: 'Действия',
      en: 'Actions',
      kk: 'Әрекеттер',
      de: 'Aktionen',
      fr: 'Actions',
      es: 'Acciones',
      pt: 'Ações',
      tr: 'Eylemler',
      uk: 'Дії',
      zh: '操作',
      pl: 'Akcje',
      it: 'Azioni',
      sk: 'Akcie',
      ja: 'アクション',
      ko: '작업',
      hi: 'क्रियाएं',
      nl: 'Acties',
      sv: 'Åtgärder',
      vi: 'Hành động',
      id: 'Tindakan',
      da: 'Handlinger',
      nb: 'Handlinger',
      nn: 'Handlingar',
      fi: 'Toiminnot',
      is: 'Aðgerðir',
      fo: 'Handlingar',
      cs: 'Akce',
      bg: 'Действия',
      hr: 'Radnje',
      sr: 'Радње',
      sl: 'Dejanja',
      mk: 'Дејства',
      be: 'Дзеянні',
      bs: 'Radnje',
      hsb: 'Akcije',
    }),
    transactionDate: t({
      ru: 'Дата операции',
      en: 'Transaction date',
      kk: 'Операция күні',
      de: 'Transaktionsdatum',
      fr: 'Date de transaction',
      es: 'Fecha de transacción',
      pt: 'Data da transação',
      tr: 'İşlem tarihi',
      uk: 'Дата операції',
      zh: '交易日期',
      pl: 'Data transakcji',
      it: 'Data transazione',
      sk: 'Dátum transakcie',
      ja: '取引日',
      ko: '거래 날짜',
      hi: 'लेनदेन की तारीख',
      nl: 'Transactiedatum',
      sv: 'Transaktionsdatum',
      vi: 'Ngày giao dịch',
      id: 'Tanggal transaksi',
      da: 'Posteringsdato',
      nb: 'Transaksjonsdato',
      nn: 'Transaksjonsdato',
      fi: 'Tapahtumapäivä',
      is: 'Dagsetning færslu',
      fo: 'Posteringsdato',
      cs: 'Datum transakce',
      bg: 'Дата на транзакцията',
      hr: 'Datum transakcije',
      sr: 'Датум трансакције',
      sl: 'Datum transakcije',
      mk: 'Датум на трансакција',
      be: 'Дата транзакцыі',
      bs: 'Datum transakcije',
      hsb: 'Datum transakcije',
    }),
    documentNumber: t({
      ru: 'Номер документа',
      en: 'Document number',
      kk: 'Құжат нөмірі',
      de: 'Dokumentnummer',
      fr: 'Numéro de document',
      es: 'Número de documento',
      pt: 'Número do documento',
      tr: 'Belge numarası',
      uk: 'Номер документа',
      zh: '单据编号',
      pl: 'Numer dokumentu',
      it: 'Numero documento',
      sk: 'Číslo dokladu',
      ja: '書類番号',
      ko: '문서 번호',
      hi: 'दस्तावेज़ संख्या',
      nl: 'Documentnummer',
      sv: 'Dokumentnummer',
      vi: 'Số tài liệu',
      id: 'Nomor dokumen',
      da: 'Dokumentnummer',
      nb: 'Dokumentnummer',
      nn: 'Dokumentnummer',
      fi: 'Tositenumero',
      is: 'Skjalsnúmer',
      fo: 'Skjalanummar',
      cs: 'Číslo dokladu',
      bg: 'Номер на документ',
      hr: 'Broj dokumenta',
      sr: 'Број документа',
      sl: 'Številka dokumenta',
      mk: 'Број на документ',
      be: 'Нумар дакумента',
      bs: 'Broj dokumenta',
      hsb: 'Čisło dokumenta',
    }),
    counterpartyName: t({
      ru: 'Наименование контрагента',
      en: 'Counterparty name',
      kk: 'Контрагент атауы',
      de: 'Name der Gegenpartei',
      fr: 'Nom de la contrepartie',
      es: 'Nombre de la contraparte',
      pt: 'Nome da contraparte',
      tr: 'Karşı taraf adı',
      uk: 'Найменування контрагента',
      zh: '对手方名称',
      pl: 'Nazwa kontrahenta',
      it: 'Nome della controparte',
      sk: 'Názov protistrany',
      ja: '取引相手名',
      ko: '상대방 이름',
      hi: 'प्रतिपक्ष का नाम',
      nl: 'Naam tegenpartij',
      sv: 'Motpartens namn',
      vi: 'Tên đối tác',
      id: 'Nama pihak lawan',
      da: 'Modpartens navn',
      nb: 'Motpartens navn',
      nn: 'Namnet til motparten',
      fi: 'Vastapuolen nimi',
      is: 'Nafn gagnaðila',
      fo: 'Navn á mótparti',
      cs: 'Název protistrany',
      bg: 'Име на контрагента',
      hr: 'Naziv druge strane',
      sr: 'Назив друге стране',
      sl: 'Naziv nasprotne stranke',
      mk: 'Име на другата страна',
      be: 'Назва кантрагента',
      bs: 'Naziv druge strane',
      hsb: 'Mjeno přećiwneje strony',
    }),
    counterpartyBin: t({
      ru: 'БИН/номер счёта контрагента',
      en: 'Counterparty BIN/account',
      kk: 'Контрагент БСН/есепшот',
      de: 'BIN/Kontonummer der Gegenpartei',
      fr: 'BIN/compte de la contrepartie',
      es: 'BIN/cuenta de la contraparte',
      pt: 'BIN/conta da contraparte',
      tr: 'Karşı taraf BIN/hesap',
      uk: 'БІН/номер рахунку контрагента',
      zh: '对手方BIN/账户',
      pl: 'BIN/numer konta kontrahenta',
      it: 'BIN/conto della controparte',
      sk: 'BIN/účet protistrany',
      ja: '取引相手BIN/口座',
      ko: '상대방 BIN/계좌',
      hi: 'प्रतिपक्ष BIN/खाता',
      nl: 'BIN/rekening tegenpartij',
      sv: 'Motpart BIN/konto',
      vi: 'BIN/tài khoản đối tác',
      id: 'BIN/akun pihak lawan',
      da: 'Modpartens reg.nr./konto',
      nb: 'Motpartens org.nr./konto',
      nn: 'Org.nr./konto til motparten',
      fi: 'Vastapuolen tunnus/tili',
      is: 'Kennitala/reikningur gagnaðila',
      fo: 'V-tal/konta hjá mótparti',
      cs: 'IČO/účet protistrany',
      bg: 'ЕИК/сметка на контрагента',
      hr: 'OIB/račun druge strane',
      sr: 'ПИБ/рачун друге стране',
      sl: 'Davčna št./račun nasprotne stranke',
      mk: 'Даночен број/сметка на другата страна',
      be: 'УНП/рахунак кантрагента',
      bs: 'ID broj/račun druge strane',
      hsb: 'Dawkowe čisło/konto přećiwneje strony',
    }),
    counterpartyBank: t({
      ru: 'Реквизиты банка контрагента',
      en: 'Counterparty bank details',
      kk: 'Контрагент банк реквизиттері',
      de: 'Bankdaten der Gegenpartei',
      fr: 'Coordonnées bancaires de la contrepartie',
      es: 'Datos bancarios de la contraparte',
      pt: 'Dados bancários da contraparte',
      tr: 'Karşı taraf banka bilgileri',
      uk: 'Реквізити банку контрагента',
      zh: '对手方银行信息',
      pl: 'Dane bankowe kontrahenta',
      it: 'Coordinate bancarie della controparte',
      sk: 'Bankové údaje protistrany',
      ja: '取引相手の銀行情報',
      ko: '상대방 은행 정보',
      hi: 'प्रतिपक्ष के बैंक विवरण',
      nl: 'Bankgegevens tegenpartij',
      sv: 'Motpartens bankuppgifter',
      vi: 'Chi tiết ngân hàng đối tác',
      id: 'Detail bank pihak lawan',
      da: 'Modpartens bankoplysninger',
      nb: 'Motpartens bankopplysninger',
      nn: 'Bankopplysningar til motparten',
      fi: 'Vastapuolen pankkitiedot',
      is: 'Bankaupplýsingar gagnaðila',
      fo: 'Bankaupplýsingar hjá mótparti',
      cs: 'Bankovní údaje protistrany',
      bg: 'Банкови данни на контрагента',
      hr: 'Bankovni podaci druge strane',
      sr: 'Банковни подаци друге стране',
      sl: 'Bančni podatki nasprotne stranke',
      mk: 'Банкарски податоци на другата страна',
      be: 'Банкаўскія рэквізіты кантрагента',
      bs: 'Bankovni podaci druge strane',
      hsb: 'Bankowe daty přećiwneje strony',
    }),
    debit: t({
      ru: 'Дебет',
      en: 'Debit',
      kk: 'Дебет',
      de: 'Soll',
      fr: 'Débit',
      es: 'Débito',
      pt: 'Débito',
      tr: 'Borç',
      uk: 'Дебет',
      zh: '借方',
      pl: 'Debet',
      it: 'Dare',
      sk: 'Debet',
      ja: '借方',
      ko: '차변',
      hi: 'डेबिट',
      nl: 'Debet',
      sv: 'Debet',
      vi: 'Ghi nợ',
      id: 'Debit',
      da: 'Debet',
      nb: 'Debet',
      nn: 'Debet',
      fi: 'Debet',
      is: 'Debet',
      fo: 'Debet',
      cs: 'Debet',
      bg: 'Дебит',
      hr: 'Duguje',
      sr: 'Дугује',
      sl: 'Debet',
      mk: 'Должи',
      be: 'Дэбет',
      bs: 'Duguje',
      hsb: 'Debet',
    }),
    credit: t({
      ru: 'Кредит',
      en: 'Credit',
      kk: 'Кредит',
      de: 'Haben',
      fr: 'Crédit',
      es: 'Crédito',
      pt: 'Crédito',
      tr: 'Alacak',
      uk: 'Кредит',
      zh: '贷方',
      pl: 'Kredyt',
      it: 'Avere',
      sk: 'Kredit',
      ja: '貸方',
      ko: '대변',
      hi: 'क्रेडिट',
      nl: 'Krediet',
      sv: 'Kredit',
      vi: 'Ghi có',
      id: 'Kredit',
      da: 'Kredit',
      nb: 'Kredit',
      nn: 'Kredit',
      fi: 'Kredit',
      is: 'Kredit',
      fo: 'Kredit',
      cs: 'Kredit',
      bg: 'Кредит',
      hr: 'Potražuje',
      sr: 'Потражује',
      sl: 'Kredit',
      mk: 'Побарува',
      be: 'Крэдыт',
      bs: 'Potražuje',
      hsb: 'Kredit',
    }),
    paymentPurpose: t({
      ru: 'Назначение платежа',
      en: 'Payment purpose',
      kk: 'Төлем мақсаты',
      de: 'Zahlungszweck',
      fr: 'Objet du paiement',
      es: 'Propósito del pago',
      pt: 'Finalidade do pagamento',
      tr: 'Ödeme amacı',
      uk: 'Призначення платежу',
      zh: '付款用途',
      pl: 'Cel płatności',
      it: 'Scopo del pagamento',
      sk: 'Účel platby',
      ja: '支払目的',
      ko: '결제 목적',
      hi: 'भुगतान का उद्देश्य',
      nl: 'Betalingsdoel',
      sv: 'Betalningssyfte',
      vi: 'Mục đích thanh toán',
      id: 'Tujuan pembayaran',
      da: 'Betalingsformål',
      nb: 'Betalingsformål',
      nn: 'Betalingsformål',
      fi: 'Maksun tarkoitus',
      is: 'Tilgangur greiðslu',
      fo: 'Endamál við gjaldinum',
      cs: 'Účel platby',
      bg: 'Основание за плащане',
      hr: 'Namjena plaćanja',
      sr: 'Намена плаћања',
      sl: 'Namen plačila',
      mk: 'Намена на плаќањето',
      be: 'Прызначэнне плацяжу',
      bs: 'Namjena plaćanja',
      hsb: 'Zaměr zapłaćenja',
    }),
    categoryId: t({
      ru: 'Категория',
      en: 'Category',
      kk: 'Санат',
      de: 'Kategorie',
      fr: 'Catégorie',
      es: 'Categoría',
      pt: 'Categoria',
      tr: 'Kategori',
      uk: 'Категорія',
      zh: '类别',
      pl: 'Kategoria',
      it: 'Categoria',
      sk: 'Kategória',
      ja: 'カテゴリ',
      ko: '카테고리',
      hi: 'श्रेणी',
      nl: 'Categorie',
      sv: 'Kategori',
      vi: 'Danh mục',
      id: 'Kategori',
      da: 'Kategori',
      nb: 'Kategori',
      nn: 'Kategori',
      fi: 'Kategoria',
      is: 'Kategoría',
      fo: 'Bólkur',
      cs: 'Kategorie',
      bg: 'Категория',
      hr: 'Kategorija',
      sr: 'Категорија',
      sl: 'Kategorija',
      mk: 'Категорија',
      be: 'Катэгорыя',
      bs: 'Kategorija',
      hsb: 'Kategorija',
    }),
    branchId: t({
      ru: 'Филиал',
      en: 'Branch',
      kk: 'Филиал',
      de: 'Filiale',
      fr: 'Agence',
      es: 'Sucursal',
      pt: 'Filial',
      tr: 'Şube',
      uk: 'Філія',
      zh: '分支机构',
      pl: 'Oddział',
      it: 'Filiale',
      sk: 'Pobočka',
      ja: '支店',
      ko: '지점',
      hi: 'शाखा',
      nl: 'Filiaal',
      sv: 'Filial',
      vi: 'Chi nhánh',
      id: 'Cabang',
      da: 'Filial',
      nb: 'Filial',
      nn: 'Filial',
      fi: 'Konttori',
      is: 'Afgreiðsla',
      fo: 'Avdeiling',
      cs: 'Pobočka',
      bg: 'Клон',
      hr: 'Poslovnica',
      sr: 'Филијала',
      sl: 'Poslovalnica',
      mk: 'Филијала',
      be: 'Філіял',
      bs: 'Filijala',
      hsb: 'Filiala',
    }),
    walletId: t({
      ru: 'Кошелек',
      en: 'Wallet',
      kk: 'Әмиян',
      de: 'Geldbörse',
      fr: 'Portefeuille',
      es: 'Cartera',
      pt: 'Carteira',
      tr: 'Cüzdan',
      uk: 'Гаманець',
      zh: '钱包',
      pl: 'Portfel',
      it: 'Portafoglio',
      sk: 'Peňaženka',
      ja: 'ウォレット',
      ko: '지갑',
      hi: 'वॉलेट',
      nl: 'Portemonnee',
      sv: 'Plånbok',
      vi: 'Ví',
      id: 'Dompet',
      da: 'Wallet',
      nb: 'Lommebok',
      nn: 'Lommebok',
      fi: 'Lompakko',
      is: 'Veski',
      fo: 'Pungur',
      cs: 'Peněženka',
      bg: 'Портфейл',
      hr: 'Novčanik',
      sr: 'Новчаник',
      sl: 'Denarnica',
      mk: 'Паричник',
      be: 'Гаманец',
      bs: 'Novčanik',
      hsb: 'Móšnja',
    }),
  },
} satisfies Dictionary;

export default content;
