import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'receiptCurrencyDrawer',
  content: {
    closeDrawer: t({
      ru: 'Закрыть выбор валюты',
      en: 'Close currency drawer',
      kk: 'Валюта таңдауын жабу',
      de: 'Währungsauswahl schließen',
      fr: 'Fermer le choix de la devise',
      es: 'Cerrar selección de moneda',
      pt: 'Fechar seleção de moeda',
      tr: 'Para birimi seçimini kapat',
      uk: 'Закрити вибір валюти',
      zh: '关闭货币选择',
      ar: 'إغلاق اختيار العملة',
      pl: 'Zamknij wybór waluty',
      it: 'Chiudi selezione valuta',
      sk: 'Zavrieť výber meny',
      ja: '通貨の選択を閉じる',
      ko: '통화 선택 닫기',
      hi: 'मुद्रा चयन बंद करें',
      nl: 'Valutakeuze sluiten',
      sv: 'Stäng valutaval',
      vi: 'Đóng chọn tiền tệ',
      id: 'Tutup pilihan mata uang',
      da: 'Luk valutaskuffen',
      nb: 'Lukk valutaskuffen',
      nn: 'Lukk valutaskuffa',
      fi: 'Sulje valuuttalaatikko',
      is: 'Loka myntskúffu',
      fo: 'Lat valutuskúffuna aftur',
      cs: 'Zavřít panel měn',
      bg: 'Затваряне на панела с валути',
      hr: 'Zatvori ladicu valuta',
      sr: 'Затвори фиоку валута',
      sl: 'Zapri predal valut',
      mk: 'Затвори ја фиоката со валути',
      be: 'Закрыць шуфляду валют',
      bs: 'Zatvori fioku valuta',
      hsb: 'Kašćik walutow začinić',
    }),
    title: t({
      ru: 'Выберите валюту',
      en: 'Select a currency',
      kk: 'Валютаны таңдаңыз',
      de: 'Währung auswählen',
      fr: 'Sélectionnez une devise',
      es: 'Seleccione una moneda',
      pt: 'Selecione uma moeda',
      tr: 'Para birimi seçin',
      uk: 'Виберіть валюту',
      zh: '选择货币',
      ar: 'اختر عملة',
      pl: 'Wybierz walutę',
      it: 'Seleziona una valuta',
      sk: 'Vyberte menu',
      ja: '通貨を選択',
      ko: '통화 선택',
      hi: 'मुद्रा चुनें',
      nl: 'Selecteer een valuta',
      sv: 'Välj en valuta',
      vi: 'Chọn tiền tệ',
      id: 'Pilih mata uang',
      da: 'Vælg en valuta',
      nb: 'Velg en valuta',
      nn: 'Vel ein valuta',
      fi: 'Valitse valuutta',
      is: 'Veldu mynt',
      fo: 'Vel eina valutu',
      cs: 'Vyberte měnu',
      bg: 'Изберете валута',
      hr: 'Odaberite valutu',
      sr: 'Изаберите валуту',
      sl: 'Izberite valuto',
      mk: 'Изберете валута',
      be: 'Выберыце валюту',
      bs: 'Odaberite valutu',
      hsb: 'Wubjerće walutu',
    }),
    searchPlaceholder: t({
      ru: 'Поиск',
      en: 'Search',
      kk: 'Іздеу',
      de: 'Suchen',
      fr: 'Rechercher',
      es: 'Buscar',
      pt: 'Pesquisar',
      tr: 'Ara',
      uk: 'Пошук',
      zh: '搜索',
      ar: 'بحث',
      pl: 'Szukaj',
      it: 'Cerca',
      sk: 'Hľadať',
      ja: '検索',
      ko: '검색',
      hi: 'खोजें',
      nl: 'Zoeken',
      sv: 'Sök',
      vi: 'Tìm kiếm',
      id: 'Cari',
      da: 'Søg',
      nb: 'Søk',
      nn: 'Søk',
      fi: 'Hae',
      is: 'Leita',
      fo: 'Leita',
      cs: 'Hledat',
      bg: 'Търсене',
      hr: 'Traži',
      sr: 'Тражи',
      sl: 'Iskanje',
      mk: 'Пребарај',
      be: 'Шукаць',
      bs: 'Traži',
      hsb: 'Pytać',
    }),
    recents: t({
      ru: 'Недавние',
      en: 'Recents',
      kk: 'Соңғылар',
      de: 'Zuletzt verwendet',
      fr: 'Récentes',
      es: 'Recientes',
      pt: 'Recentes',
      tr: 'Son kullanılanlar',
      uk: 'Нещодавні',
      zh: '最近使用',
      ar: 'الأخيرة',
      pl: 'Ostatnie',
      it: 'Recenti',
      sk: 'Nedávne',
      ja: '最近使用',
      ko: '최근 항목',
      hi: 'हाल के',
      nl: 'Recent',
      sv: 'Senaste',
      vi: 'Gần đây',
      id: 'Terbaru',
      da: 'Senest brugte',
      nb: 'Nylig brukte',
      nn: 'Nyleg brukte',
      fi: 'Viimeksi käytetyt',
      is: 'Nýlega notað',
      fo: 'Nýliga nýtt',
      cs: 'Naposledy použité',
      bg: 'Последно използвани',
      hr: 'Nedavno korišteno',
      sr: 'Недавно коришћено',
      sl: 'Nedavno uporabljeno',
      mk: 'Неодамна користени',
      be: 'Нядаўна выкарыстаныя',
      bs: 'Nedavno korišteno',
      hsb: 'Njedawno wužite',
    }),
    all: t({
      ru: 'Все',
      en: 'All',
      kk: 'Барлығы',
      de: 'Alle',
      fr: 'Toutes',
      es: 'Todas',
      pt: 'Todas',
      tr: 'Tümü',
      uk: 'Усі',
      zh: '全部',
      ar: 'الكل',
      pl: 'Wszystkie',
      it: 'Tutte',
      sk: 'Všetky',
      ja: 'すべて',
      ko: '전체',
      hi: 'सभी',
      nl: 'Alle',
      sv: 'Alla',
      vi: 'Tất cả',
      id: 'Semua',
      da: 'Alle',
      nb: 'Alle',
      nn: 'Alle',
      fi: 'Kaikki',
      is: 'Allt',
      fo: 'Allar',
      cs: 'Vše',
      bg: 'Всички',
      hr: 'Sve',
      sr: 'Све',
      sl: 'Vse',
      mk: 'Сите',
      be: 'Усе',
      bs: 'Sve',
      hsb: 'Wšě',
    }),
    noResults: t({
      ru: 'Валюты не найдены',
      en: 'No currencies found',
      kk: 'Валюталар табылмады',
      de: 'Keine Währungen gefunden',
      fr: 'Aucune devise trouvée',
      es: 'No se encontraron monedas',
      pt: 'Nenhuma moeda encontrada',
      tr: 'Para birimi bulunamadı',
      uk: 'Валюти не знайдено',
      zh: '未找到货币',
      ar: 'لم يتم العثور على عملات',
      pl: 'Nie znaleziono walut',
      it: 'Nessuna valuta trovata',
      sk: 'Nenašli sa žiadne meny',
      ja: '通貨が見つかりません',
      ko: '통화를 찾을 수 없습니다',
      hi: 'कोई मुद्रा नहीं मिली',
      nl: 'Geen valuta gevonden',
      sv: 'Inga valutor hittades',
      vi: 'Không tìm thấy tiền tệ',
      id: 'Mata uang tidak ditemukan',
      da: 'Der blev ikke fundet nogen valutaer',
      nb: 'Fant ingen valutaer',
      nn: 'Fann ingen valutaer',
      fi: 'Valuuttoja ei löytynyt',
      is: 'Engar myntir fundust',
      fo: 'Eingar valutur funnar',
      cs: 'Nebyly nalezeny žádné měny',
      bg: 'Няма намерени валути',
      hr: 'Nema nađenih valuta',
      sr: 'Нема нађених валута',
      sl: 'Ni najdenih valut',
      mk: 'Нема најдени валути',
      be: 'Валют не знойдзена',
      bs: 'Nema nađenih valuta',
      hsb: 'Žane waluty namakane',
    }),
  },
} satisfies Dictionary;

export default content;
