import { type Dictionary, t } from 'intlayer';

// Intro, controls and outro of the welcome tutorial. Page names come from the
// `navigation` dictionary; the per-page texts live in welcome-tutorial-steps.content.ts.

const content = {
  key: 'welcomeTutorial',
  content: {
    intro: {
      eyebrow: t({
        ru: 'Добро пожаловать',
        en: 'Getting started',
        kk: 'Қош келдіңіз',
        de: 'Los geht’s',
        fr: 'Premiers pas',
        es: 'Primeros pasos',
        pt: 'Primeiros passos',
        tr: 'Başlarken',
        uk: 'Ласкаво просимо',
        zh: '快速上手',
        ar: 'لنبدأ',
        pl: 'Na start',
        it: 'Per iniziare',
        sk: 'Začíname',
        ja: 'はじめに',
        ko: '시작하기',
        hi: 'शुरुआत',
        nl: 'Aan de slag',
        sv: 'Kom igång',
        vi: 'Bắt đầu',
        id: 'Mulai',
        da: 'Kom godt i gang',
        nb: 'Kom i gang',
        nn: 'Kom i gang',
        fi: 'Aloitus',
        is: 'Fyrstu skrefin',
        fo: 'Byrja her',
        cs: 'Začínáme',
        bg: 'Първи стъпки',
        hr: 'Prvi koraci',
        sr: 'Први кораци',
        sl: 'Prvi koraki',
        mk: 'Први чекори',
        be: 'Першыя крокі',
        bs: 'Prvi koraci',
        hsb: 'Prěnje kroki',
      }),
      title: t({
        ru: 'Добро пожаловать в Lumio, {{name}}',
        en: 'Welcome to Lumio, {{name}}',
        kk: 'Lumio-ға қош келдіңіз, {{name}}',
        de: 'Willkommen bei Lumio, {{name}}',
        fr: 'Bienvenue sur Lumio, {{name}}',
        es: 'Te damos la bienvenida a Lumio, {{name}}',
        pt: 'Boas-vindas ao Lumio, {{name}}',
        tr: 'Lumio’ya hoş geldin, {{name}}',
        uk: 'Вітаємо в Lumio, {{name}}',
        zh: '欢迎使用 Lumio，{{name}}',
        ar: 'مرحبًا بك في Lumio، {{name}}',
        pl: 'Witaj w Lumio, {{name}}',
        it: 'Benvenuto in Lumio, {{name}}',
        sk: 'Vitajte v Lumio, {{name}}',
        ja: 'Lumio へようこそ、{{name}} さん',
        ko: 'Lumio에 오신 것을 환영합니다, {{name}}님',
        hi: 'Lumio में आपका स्वागत है, {{name}}',
        nl: 'Welkom bij Lumio, {{name}}',
        sv: 'Välkommen till Lumio, {{name}}',
        vi: 'Chào mừng đến với Lumio, {{name}}',
        id: 'Selamat datang di Lumio, {{name}}',
        da: 'Velkommen til Lumio, {{name}}',
        nb: 'Velkommen til Lumio, {{name}}',
        nn: 'Velkomen til Lumio, {{name}}',
        fi: 'Tervetuloa Lumioon, {{name}}',
        is: 'Velkomin í Lumio, {{name}}',
        fo: 'Vælkomin til Lumio, {{name}}',
        cs: 'Vítejte v Lumio, {{name}}',
        bg: 'Добре дошли в Lumio, {{name}}',
        hr: 'Dobro došli u Lumio, {{name}}',
        sr: 'Добро дошли у Lumio, {{name}}',
        sl: 'Dobrodošli v Lumio, {{name}}',
        mk: 'Добре дојдовте во Lumio, {{name}}',
        be: 'Вітаем у Lumio, {{name}}',
        bs: 'Dobro došli u Lumio, {{name}}',
        hsb: 'Witajće do Lumio, {{name}}',
      }),
      titleNoName: t({
        ru: 'Добро пожаловать в Lumio',
        en: 'Welcome to Lumio',
        kk: 'Lumio-ға қош келдіңіз',
        de: 'Willkommen bei Lumio',
        fr: 'Bienvenue sur Lumio',
        es: 'Te damos la bienvenida a Lumio',
        pt: 'Boas-vindas ao Lumio',
        tr: 'Lumio’ya hoş geldin',
        uk: 'Вітаємо в Lumio',
        zh: '欢迎使用 Lumio',
        ar: 'مرحبًا بك في Lumio',
        pl: 'Witaj w Lumio',
        it: 'Benvenuto in Lumio',
        sk: 'Vitajte v Lumio',
        ja: 'Lumio へようこそ',
        ko: 'Lumio에 오신 것을 환영합니다',
        hi: 'Lumio में आपका स्वागत है',
        nl: 'Welkom bij Lumio',
        sv: 'Välkommen till Lumio',
        vi: 'Chào mừng đến với Lumio',
        id: 'Selamat datang di Lumio',
        da: 'Velkommen til Lumio',
        nb: 'Velkommen til Lumio',
        nn: 'Velkomen til Lumio',
        fi: 'Tervetuloa Lumioon',
        is: 'Velkomin í Lumio',
        fo: 'Vælkomin til Lumio',
        cs: 'Vítejte v Lumio',
        bg: 'Добре дошли в Lumio',
        hr: 'Dobro došli u Lumio',
        sr: 'Добро дошли у Lumio',
        sl: 'Dobrodošli v Lumio',
        mk: 'Добре дојдовте во Lumio',
        be: 'Вітаем у Lumio',
        bs: 'Dobro došli u Lumio',
        hsb: 'Witajće do Lumio',
      }),
      subtitle: t({
        ru: 'Двухминутный обзор страниц в боковом меню: зачем нужна каждая и с чего начать.',
        en: 'A two-minute tour of the pages in your sidebar: what each one is for and where to start.',
        kk: 'Бүйірлік мәзірдегі беттерге екі минуттық шолу: әрқайсысы не үшін керек және неден бастау керек.',
        de: 'Eine zweiminütige Tour durch die Seiten in der Seitenleiste: wofür jede da ist und wo du anfängst.',
        fr: 'Un tour de deux minutes des pages de la barre latérale : à quoi sert chacune et par où commencer.',
        es: 'Un recorrido de dos minutos por las páginas de la barra lateral: para qué sirve cada una y por dónde empezar.',
        pt: 'Um tour de dois minutos pelas páginas da barra lateral: para que serve cada uma e por onde começar.',
        tr: 'Kenar çubuğundaki sayfalarda iki dakikalık bir tur: her biri ne işe yarar ve nereden başlamalı.',
        uk: 'Двохвилинний огляд сторінок у бічному меню: для чого кожна з них і з чого почати.',
        zh: '两分钟了解侧边栏中的各个页面：每个页面的用途，以及从哪里开始。',
        ar: 'جولة مدتها دقيقتان في صفحات الشريط الجانبي: فيمَ تفيد كل صفحة ومن أين تبدأ.',
        pl: 'Dwuminutowy przegląd stron z paska bocznego: do czego służy każda z nich i od czego zacząć.',
        it: 'Un tour di due minuti tra le pagine della barra laterale: a cosa serve ciascuna e da dove iniziare.',
        sk: 'Dvojminútová prehliadka stránok v bočnom paneli: na čo slúži každá z nich a kde začať.',
        ja: 'サイドバーの各ページを2分でご紹介します。それぞれの役割と、どこから始めればよいかがわかります。',
        ko: '사이드바의 페이지를 2분 만에 둘러보세요. 각 페이지의 용도와 어디서 시작하면 좋은지 알려 드립니다.',
        hi: 'साइडबार के पेजों का दो मिनट का परिचय: हर पेज किस काम का है और शुरुआत कहाँ से करें।',
        nl: 'Een rondleiding van twee minuten langs de pagina’s in de zijbalk: waar elke pagina voor is en waar je begint.',
        sv: 'En tvåminuters rundtur bland sidorna i sidofältet: vad varje sida är till för och var du börjar.',
        vi: 'Hai phút giới thiệu các trang trong thanh bên: mỗi trang dùng để làm gì và nên bắt đầu từ đâu.',
        id: 'Tur dua menit melihat halaman-halaman di bilah sisi: fungsi tiap halaman dan dari mana memulai.',
        da: 'En to-minutters tur gennem siderne i din sidebjælke: hvad hver af dem er til, og hvor du begynder.',
        nb: 'En totminutters tur gjennom sidene i sidepanelet ditt: hva hver av dem er til, og hvor du begynner.',
        nn: 'Ei totminutts omvising gjennom sidene i sidepanelet ditt: kva kvar av dei er til, og kvar du byrjar.',
        fi: 'Kahden minuutin kierros sivupalkkisi sivuihin: mihin kukin on tarkoitettu ja mistä kannattaa aloittaa.',
        is: 'Tveggja mínútna kynning á síðunum í hliðarstikunni þinni: til hvers hver þeirra er og hvar á að byrja.',
        fo: 'Ein tveyminuttaferð gjøgnum síðurnar í síðubjálkanum tínum: hvat hvør av teimum er til, og hvar tú byrjar.',
        cs: 'Dvouminutová prohlídka stránek ve vašem postranním panelu: k čemu každá z nich je a kde začít.',
        bg: 'Двуминутна обиколка на страниците в страничната лента: за какво е всяка от тях и откъде да започнете.',
        hr: 'Dvominutni obilazak stranica u vašoj bočnoj traci: za što je svaka od njih i gdje početi.',
        sr: 'Двоминутни обилазак страница у вашој бочној траци: за шта је свака од њих и где почети.',
        sl: 'Dvominutni ogled strani v vaši stranski vrstici: za kaj je vsaka od njih in kje začeti.',
        mk: 'Двоминутна обиколка на страниците во вашата странична лента: за што е секоја од нив и од каде да почнете.',
        be: 'Двуххвілінная экскурсія па сторонках у вашай бакавой панэлі: для чаго кожная з іх і адкуль пачаць.',
        bs: 'Dvominutni obilazak stranica u vašoj bočnoj traci: za šta je svaka od njih i gdje početi.',
        hsb: 'Dwuminutowe wodźenje po stronach we wašej bóčnej lajsće: za čož kóžda z nich je a hdźež započnjeće.',
      }),
      start: t({
        ru: 'Начать обзор',
        en: 'Start the tour',
        kk: 'Шолуды бастау',
        de: 'Tour starten',
        fr: 'Commencer la visite',
        es: 'Empezar el recorrido',
        pt: 'Começar o tour',
        tr: 'Tura başla',
        uk: 'Почати огляд',
        zh: '开始导览',
        ar: 'ابدأ الجولة',
        pl: 'Rozpocznij przegląd',
        it: 'Inizia il tour',
        sk: 'Spustiť prehliadku',
        ja: 'ツアーを始める',
        ko: '둘러보기 시작',
        hi: 'टूर शुरू करें',
        nl: 'Start de rondleiding',
        sv: 'Starta rundturen',
        vi: 'Bắt đầu',
        id: 'Mulai tur',
        da: 'Start turen',
        nb: 'Start omvisningen',
        nn: 'Start omvisinga',
        fi: 'Aloita kierros',
        is: 'Byrja kynninguna',
        fo: 'Byrja ferðina',
        cs: 'Spustit prohlídku',
        bg: 'Започване на обиколката',
        hr: 'Započni obilazak',
        sr: 'Почни обилазак',
        sl: 'Začni ogled',
        mk: 'Почни обиколка',
        be: 'Пачаць экскурсію',
        bs: 'Započni obilazak',
        hsb: 'Wodźenje započeć',
      }),
      skip: t({
        ru: 'Пропустить',
        en: 'Skip for now',
        kk: 'Қазір өткізіп жіберу',
        de: 'Später',
        fr: 'Plus tard',
        es: 'Ahora no',
        pt: 'Agora não',
        tr: 'Şimdilik geç',
        uk: 'Пропустити',
        zh: '暂时跳过',
        ar: 'تخطَّ الآن',
        pl: 'Pomiń',
        it: 'Salta per ora',
        sk: 'Preskočiť',
        ja: '今はスキップ',
        ko: '나중에 하기',
        hi: 'अभी छोड़ें',
        nl: 'Nu overslaan',
        sv: 'Hoppa över',
        vi: 'Để sau',
        id: 'Lewati dulu',
        da: 'Spring over for nu',
        nb: 'Hopp over for nå',
        nn: 'Hopp over for no',
        fi: 'Ohita toistaiseksi',
        is: 'Sleppa í þetta sinn',
        fo: 'Leyp um í hesum sinni',
        cs: 'Teď přeskočit',
        bg: 'Пропускане за сега',
        hr: 'Preskoči za sada',
        sr: 'Прескочи за сада',
        sl: 'Preskoči za zdaj',
        mk: 'Прескокни за сега',
        be: 'Прапусціць пакуль',
        bs: 'Preskoči za sada',
        hsb: 'Nětko přeskočić',
      }),
      reopenHint: t({
        ru: 'Открыть его снова можно в любой момент из меню аватара.',
        en: 'You can open it again any time from your avatar menu.',
        kk: 'Оны кез келген уақытта аватар мәзірінен қайта ашуға болады.',
        de: 'Du kannst sie jederzeit über das Menü deines Avatars wieder öffnen.',
        fr: 'Vous pourrez la rouvrir à tout moment depuis le menu de votre avatar.',
        es: 'Puedes volver a abrirlo cuando quieras desde el menú de tu avatar.',
        pt: 'Você pode abri-lo de novo a qualquer momento pelo menu do seu avatar.',
        tr: 'İstediğin zaman avatar menüsünden yeniden açabilirsin.',
        uk: 'Відкрити його знову можна будь-коли з меню аватара.',
        zh: '之后可随时从头像菜单中再次打开。',
        ar: 'يمكنك فتحها مرة أخرى في أي وقت من قائمة الصورة الرمزية.',
        pl: 'Możesz go ponownie otworzyć w każdej chwili z menu awatara.',
        it: 'Puoi riaprirlo quando vuoi dal menu del tuo avatar.',
        sk: 'Kedykoľvek ho znova otvoríte z ponuky avatara.',
        ja: 'アバターのメニューからいつでも再表示できます。',
        ko: '아바타 메뉴에서 언제든지 다시 열 수 있습니다.',
        hi: 'आप इसे कभी भी अपने अवतार मेन्यू से फिर खोल सकते हैं।',
        nl: 'Je kunt hem altijd opnieuw openen via het menu van je avatar.',
        sv: 'Du kan öppna den igen när som helst från menyn under din avatar.',
        vi: 'Bạn có thể mở lại bất cứ lúc nào từ menu ảnh đại diện.',
        id: 'Kamu bisa membukanya lagi kapan saja dari menu avatar.',
        da: 'Du kan åbne den igen når som helst fra menuen under din avatar.',
        nb: 'Du kan åpne den igjen når som helst fra menyen under avataren din.',
        nn: 'Du kan opne henne igjen når som helst frå menyen under avataren din.',
        fi: 'Voit avata sen uudelleen milloin tahansa avatarvalikosta.',
        is: 'Þú getur opnað hana aftur hvenær sem er úr valmyndinni undir notandamyndinni þinni.',
        fo: 'Tú kanst lata hana upp aftur hvørja tíð úr valmyndini undir vangamyndini tíni.',
        cs: 'Kdykoli ji můžete znovu otevřít z nabídky pod svým avatarem.',
        bg: 'Можете да я отворите отново по всяко време от менюто под аватара си.',
        hr: 'Možete ga ponovno otvoriti u svakom trenutku iz izbornika pod svojim avatarom.',
        sr: 'Можете га поново отворити у сваком тренутку из менија под својим аватаром.',
        sl: 'Znova ga lahko odprete kadar koli iz menija pod svojim avatarjem.',
        mk: 'Можете да ја отворите повторно во секое време од менито под вашиот аватар.',
        be: 'Вы можаце адкрыць яе зноў у любы час з меню пад сваім аватарам.',
        bs: 'Možete ga ponovo otvoriti u svakom trenutku iz menija pod svojim avatarom.',
        hsb: 'Móžeće jo kóždy čas znowa z menija pod swojim awatarom wotewrěć.',
      }),
    },
    controls: {
      back: t({
        ru: 'Назад',
        en: 'Back',
        kk: 'Артқа',
        de: 'Zurück',
        fr: 'Retour',
        es: 'Atrás',
        pt: 'Voltar',
        tr: 'Geri',
        uk: 'Назад',
        zh: '上一步',
        ar: 'السابق',
        pl: 'Wstecz',
        it: 'Indietro',
        sk: 'Späť',
        ja: '戻る',
        ko: '이전',
        hi: 'पीछे',
        nl: 'Terug',
        sv: 'Tillbaka',
        vi: 'Quay lại',
        id: 'Kembali',
        da: 'Tilbage',
        nb: 'Tilbake',
        nn: 'Tilbake',
        fi: 'Takaisin',
        is: 'Til baka',
        fo: 'Aftur',
        cs: 'Zpět',
        bg: 'Назад',
        hr: 'Natrag',
        sr: 'Назад',
        sl: 'Nazaj',
        mk: 'Назад',
        be: 'Назад',
        bs: 'Nazad',
        hsb: 'Wróćo',
      }),
      next: t({
        ru: 'Далее',
        en: 'Next',
        kk: 'Келесі',
        de: 'Weiter',
        fr: 'Suivant',
        es: 'Siguiente',
        pt: 'Próximo',
        tr: 'İleri',
        uk: 'Далі',
        zh: '下一步',
        ar: 'التالي',
        pl: 'Dalej',
        it: 'Avanti',
        sk: 'Ďalej',
        ja: '次へ',
        ko: '다음',
        hi: 'आगे',
        nl: 'Volgende',
        sv: 'Nästa',
        vi: 'Tiếp',
        id: 'Berikutnya',
        da: 'Næste',
        nb: 'Neste',
        nn: 'Neste',
        fi: 'Seuraava',
        is: 'Næsta',
        fo: 'Næsta',
        cs: 'Další',
        bg: 'Напред',
        hr: 'Sljedeće',
        sr: 'Следеће',
        sl: 'Naslednje',
        mk: 'Следно',
        be: 'Далей',
        bs: 'Sljedeće',
        hsb: 'Přichodne',
      }),
      finish: t({
        ru: 'Готово',
        en: 'Finish',
        kk: 'Дайын',
        de: 'Fertig',
        fr: 'Terminer',
        es: 'Terminar',
        pt: 'Concluir',
        tr: 'Bitir',
        uk: 'Готово',
        zh: '完成',
        ar: 'إنهاء',
        pl: 'Zakończ',
        it: 'Fine',
        sk: 'Hotovo',
        ja: '完了',
        ko: '완료',
        hi: 'पूरा करें',
        nl: 'Klaar',
        sv: 'Klar',
        vi: 'Hoàn tất',
        id: 'Selesai',
        da: 'Afslut',
        nb: 'Avslutt',
        nn: 'Avslutt',
        fi: 'Valmis',
        is: 'Ljúka',
        fo: 'Enda',
        cs: 'Dokončit',
        bg: 'Завършване',
        hr: 'Završi',
        sr: 'Заврши',
        sl: 'Končaj',
        mk: 'Заврши',
        be: 'Завяршыць',
        bs: 'Završi',
        hsb: 'Skónčić',
      }),
      hide: t({
        ru: 'Скрыть туториал',
        en: 'Hide tutorial',
        kk: 'Нұсқаулықты жасыру',
        de: 'Tutorial ausblenden',
        fr: 'Masquer le tutoriel',
        es: 'Ocultar tutorial',
        pt: 'Ocultar tutorial',
        tr: 'Eğitimi gizle',
        uk: 'Сховати туторіал',
        zh: '隐藏教程',
        ar: 'إخفاء الدليل',
        pl: 'Ukryj samouczek',
        it: 'Nascondi tutorial',
        sk: 'Skryť návod',
        ja: 'チュートリアルを閉じる',
        ko: '튜토리얼 숨기기',
        hi: 'ट्यूटोरियल छिपाएँ',
        nl: 'Tutorial verbergen',
        sv: 'Dölj guiden',
        vi: 'Ẩn hướng dẫn',
        id: 'Sembunyikan tutorial',
        da: 'Skjul vejledningen',
        nb: 'Skjul veiledningen',
        nn: 'Skjul rettleiinga',
        fi: 'Piilota esittely',
        is: 'Fela kynninguna',
        fo: 'Fjal vegleiðingina',
        cs: 'Skrýt průvodce',
        bg: 'Скриване на въведението',
        hr: 'Sakrij vodič',
        sr: 'Сакриј водич',
        sl: 'Skrij vodnik',
        mk: 'Скриј го водичот',
        be: 'Схаваць даведнік',
        bs: 'Sakrij vodič',
        hsb: 'Nawod schować',
      }),
      close: t({
        ru: 'Закрыть туториал',
        en: 'Close tutorial',
        kk: 'Нұсқаулықты жабу',
        de: 'Tutorial schließen',
        fr: 'Fermer le tutoriel',
        es: 'Cerrar tutorial',
        pt: 'Fechar tutorial',
        tr: 'Eğitimi kapat',
        uk: 'Закрити туторіал',
        zh: '关闭教程',
        ar: 'إغلاق الدليل',
        pl: 'Zamknij samouczek',
        it: 'Chiudi tutorial',
        sk: 'Zavrieť návod',
        ja: 'チュートリアルを閉じる',
        ko: '튜토리얼 닫기',
        hi: 'ट्यूटोरियल बंद करें',
        nl: 'Tutorial sluiten',
        sv: 'Stäng guiden',
        vi: 'Đóng hướng dẫn',
        id: 'Tutup tutorial',
        da: 'Luk vejledningen',
        nb: 'Lukk veiledningen',
        nn: 'Lukk rettleiinga',
        fi: 'Sulje esittely',
        is: 'Loka kynningunni',
        fo: 'Lat vegleiðingina aftur',
        cs: 'Zavřít průvodce',
        bg: 'Затваряне на въведението',
        hr: 'Zatvori vodič',
        sr: 'Затвори водич',
        sl: 'Zapri vodnik',
        mk: 'Затвори го водичот',
        be: 'Закрыць даведнік',
        bs: 'Zatvori vodič',
        hsb: 'Nawod začinić',
      }),
      progress: t({
        ru: '{{current}} из {{total}}',
        en: '{{current}} of {{total}}',
        kk: '{{current}} / {{total}}',
        de: '{{current}} von {{total}}',
        fr: '{{current}} sur {{total}}',
        es: '{{current}} de {{total}}',
        pt: '{{current}} de {{total}}',
        tr: '{{current}} / {{total}}',
        uk: '{{current}} з {{total}}',
        zh: '第 {{current}} 步，共 {{total}} 步',
        ar: '{{current}} من {{total}}',
        pl: '{{current}} z {{total}}',
        it: '{{current}} di {{total}}',
        sk: '{{current}} z {{total}}',
        ja: '{{current}} / {{total}}',
        ko: '{{current}} / {{total}}',
        hi: '{{total}} में से {{current}}',
        nl: '{{current}} van {{total}}',
        sv: '{{current}} av {{total}}',
        vi: '{{current}} / {{total}}',
        id: '{{current}} dari {{total}}',
        da: '{{current}} af {{total}}',
        nb: '{{current}} av {{total}}',
        nn: '{{current}} av {{total}}',
        fi: '{{current}} / {{total}}',
        is: '{{current}} af {{total}}',
        fo: '{{current}} av {{total}}',
        cs: '{{current}} z {{total}}',
        bg: '{{current}} от {{total}}',
        hr: '{{current}} od {{total}}',
        sr: '{{current}} од {{total}}',
        sl: '{{current}} od {{total}}',
        mk: '{{current}} од {{total}}',
        be: '{{current}} з {{total}}',
        bs: '{{current}} od {{total}}',
        hsb: '{{current}} z {{total}}',
      }),
      stepsLabel: t({
        ru: 'Шаги туториала',
        en: 'Tutorial steps',
        kk: 'Нұсқаулық қадамдары',
        de: 'Schritte des Tutorials',
        fr: 'Étapes du tutoriel',
        es: 'Pasos del tutorial',
        pt: 'Etapas do tutorial',
        tr: 'Eğitim adımları',
        uk: 'Кроки туторіалу',
        zh: '教程步骤',
        ar: 'خطوات الدليل',
        pl: 'Kroki samouczka',
        it: 'Passaggi del tutorial',
        sk: 'Kroky návodu',
        ja: 'チュートリアルのステップ',
        ko: '튜토리얼 단계',
        hi: 'ट्यूटोरियल के चरण',
        nl: 'Stappen van de tutorial',
        sv: 'Guidens steg',
        vi: 'Các bước hướng dẫn',
        id: 'Langkah tutorial',
        da: 'Trin i vejledningen',
        nb: 'Trinn i veiledningen',
        nn: 'Steg i rettleiinga',
        fi: 'Esittelyn vaiheet',
        is: 'Þrep kynningarinnar',
        fo: 'Stig í vegleiðingini',
        cs: 'Kroky průvodce',
        bg: 'Стъпки на въведението',
        hr: 'Koraci vodiča',
        sr: 'Кораци водича',
        sl: 'Koraki vodnika',
        mk: 'Чекори на водичот',
        be: 'Крокі даведніка',
        bs: 'Koraci vodiča',
        hsb: 'Kroki nawoda',
      }),
      dialogLabel: t({
        ru: 'Приветственный туториал',
        en: 'Welcome tutorial',
        kk: 'Кіріспе нұсқаулық',
        de: 'Willkommens-Tutorial',
        fr: 'Tutoriel de bienvenue',
        es: 'Tutorial de bienvenida',
        pt: 'Tutorial de boas-vindas',
        tr: 'Hoş geldin eğitimi',
        uk: 'Вітальний туторіал',
        zh: '欢迎教程',
        ar: 'دليل الترحيب',
        pl: 'Samouczek powitalny',
        it: 'Tutorial di benvenuto',
        sk: 'Uvítací návod',
        ja: 'ウェルカムチュートリアル',
        ko: '환영 튜토리얼',
        hi: 'स्वागत ट्यूटोरियल',
        nl: 'Welkomsttutorial',
        sv: 'Välkomstguide',
        vi: 'Hướng dẫn chào mừng',
        id: 'Tutorial sambutan',
        da: 'Velkomstvejledning',
        nb: 'Velkomstveiledning',
        nn: 'Velkomstrettleiing',
        fi: 'Tervetuloesittely',
        is: 'Velkomin-kynning',
        fo: 'Vælkomuvegleiðing',
        cs: 'Úvodní průvodce',
        bg: 'Въведение за добре дошли',
        hr: 'Vodič za dobrodošlicu',
        sr: 'Водич за добродошлицу',
        sl: 'Uvodni vodnik',
        mk: 'Водич за добредојде',
        be: 'Прывітальны даведнік',
        bs: 'Vodič za dobrodošlicu',
        hsb: 'Witanski nawod',
      }),
      demoNote: t({
        ru: 'На скриншотах — демо-воркспейс Keller Design Studio.',
        en: 'Screenshots show the demo workspace Keller Design Studio.',
        kk: 'Скриншоттарда — Keller Design Studio демо жұмыс кеңістігі.',
        de: 'Die Screenshots zeigen den Demo-Workspace Keller Design Studio.',
        fr: 'Les captures montrent l’espace de démonstration Keller Design Studio.',
        es: 'Las capturas muestran el espacio de demostración Keller Design Studio.',
        pt: 'As capturas mostram o espaço de demonstração Keller Design Studio.',
        tr: 'Ekran görüntüleri Keller Design Studio demo çalışma alanını gösterir.',
        uk: 'На знімках — демо-воркспейс Keller Design Studio.',
        zh: '截图来自演示工作区 Keller Design Studio。',
        ar: 'تعرض اللقطات مساحة العمل التجريبية Keller Design Studio.',
        pl: 'Zrzuty ekranu pokazują demonstracyjny obszar roboczy Keller Design Studio.',
        it: 'Gli screenshot mostrano lo spazio di lavoro dimostrativo Keller Design Studio.',
        sk: 'Snímky zobrazujú ukážkový pracovný priestor Keller Design Studio.',
        ja: 'スクリーンショットはデモ用ワークスペース「Keller Design Studio」のものです。',
        ko: '스크린샷은 데모 워크스페이스 Keller Design Studio의 화면입니다.',
        hi: 'स्क्रीनशॉट डेमो वर्कस्पेस Keller Design Studio के हैं।',
        nl: 'De screenshots tonen de demo-workspace Keller Design Studio.',
        sv: 'Skärmbilderna visar demoarbetsytan Keller Design Studio.',
        vi: 'Ảnh chụp màn hình lấy từ không gian làm việc mẫu Keller Design Studio.',
        id: 'Tangkapan layar menampilkan ruang kerja demo Keller Design Studio.',
        da: 'Skærmbillederne viser demoarbejdsområdet Keller Design Studio.',
        nb: 'Skjermbildene viser demoarbeidsområdet Keller Design Studio.',
        nn: 'Skjermbileta viser demoarbeidsområdet Keller Design Studio.',
        fi: 'Kuvakaappaukset näyttävät demotyötilan Keller Design Studio.',
        is: 'Skjáskotin sýna sýnivinnurýmið Keller Design Studio.',
        fo: 'Skermmyndirnar vísa dømisarbeiðsøkið Keller Design Studio.',
        cs: 'Snímky obrazovky ukazují ukázkový pracovní prostor Keller Design Studio.',
        bg: 'Снимките на екрана показват демонстрационното работно пространство Keller Design Studio.',
        hr: 'Snimke zaslona prikazuju demo radni prostor Keller Design Studio.',
        sr: 'Снимци екрана приказују демо радни простор Keller Design Studio.',
        sl: 'Zaslonske slike prikazujejo predstavitveni delovni prostor Keller Design Studio.',
        mk: 'Снимките од екранот го прикажуваат демо работниот простор Keller Design Studio.',
        be: 'Здымкі экрана паказваюць дэма-прастору Keller Design Studio.',
        bs: 'Snimci ekrana prikazuju demo radni prostor Keller Design Studio.',
        hsb: 'Wobrazy wobrazowki pokazuja demo-dźěłowy rum Keller Design Studio.',
      }),
    },
    outro: {
      eyebrow: t({
        ru: 'Обзор завершён',
        en: 'That’s the tour',
        kk: 'Шолу аяқталды',
        de: 'Das war die Tour',
        fr: 'Fin de la visite',
        es: 'Fin del recorrido',
        pt: 'Fim do tour',
        tr: 'Tur bitti',
        uk: 'Огляд завершено',
        zh: '导览结束',
        ar: 'انتهت الجولة',
        pl: 'To już wszystko',
        it: 'Il tour è finito',
        sk: 'Prehliadka skončila',
        ja: 'ツアーは以上です',
        ko: '둘러보기 끝',
        hi: 'टूर पूरा हुआ',
        nl: 'Dat was de rondleiding',
        sv: 'Rundturen är klar',
        vi: 'Hết phần giới thiệu',
        id: 'Tur selesai',
        da: 'Det var turen',
        nb: 'Det var omvisningen',
        nn: 'Det var omvisinga',
        fi: 'Siinä kierros',
        is: 'Þetta var kynningin',
        fo: 'Tað var ferðin',
        cs: 'To byla prohlídka',
        bg: 'Това беше обиколката',
        hr: 'To je bio obilazak',
        sr: 'То је био обилазак',
        sl: 'To je bil ogled',
        mk: 'Тоа беше обиколката',
        be: 'Вось і ўся экскурсія',
        bs: 'To je bio obilazak',
        hsb: 'To bě wodźenje',
      }),
      title: t({
        ru: 'Всё готово',
        en: 'You’re all set',
        kk: 'Бәрі дайын',
        de: 'Alles bereit',
        fr: 'Tout est prêt',
        es: 'Todo listo',
        pt: 'Tudo pronto',
        tr: 'Her şey hazır',
        uk: 'Усе готово',
        zh: '一切就绪',
        ar: 'كل شيء جاهز',
        pl: 'Wszystko gotowe',
        it: 'Tutto pronto',
        sk: 'Všetko je pripravené',
        ja: '準備完了です',
        ko: '준비가 끝났습니다',
        hi: 'सब तैयार है',
        nl: 'Je bent er klaar voor',
        sv: 'Allt är klart',
        vi: 'Mọi thứ đã sẵn sàng',
        id: 'Semua siap',
        da: 'Nu er du klar',
        nb: 'Nå er du klar',
        nn: 'No er du klar',
        fi: 'Nyt olet valmis',
        is: 'Nú ertu klár',
        fo: 'Nú ert tú klárur',
        cs: 'Všechno je připraveno',
        bg: 'Готови сте',
        hr: 'Sve je spremno',
        sr: 'Све је спремно',
        sl: 'Vse je pripravljeno',
        mk: 'Сè е готово',
        be: 'Усё гатова',
        bs: 'Sve je spremno',
        hsb: 'Wšo je hotowe',
      }),
      text: t({
        ru: 'Начните с банковской выписки: Lumio прочитает её и заполнит страницы, которые вы только что видели.',
        en: 'Start with a bank statement: Lumio reads it and fills in the pages you’ve just seen.',
        kk: 'Банк үзінділерінен бастаңыз: Lumio оны оқып, жаңа ғана көрген беттеріңізді толтырады.',
        de: 'Fang mit einem Kontoauszug an: Lumio liest ihn und füllt die Seiten, die du gerade gesehen hast.',
        fr: 'Commencez par un relevé bancaire : Lumio le lit et remplit les pages que vous venez de voir.',
        es: 'Empieza con un extracto bancario: Lumio lo lee y rellena las páginas que acabas de ver.',
        pt: 'Comece com um extrato bancário: o Lumio lê o arquivo e preenche as páginas que você acabou de ver.',
        tr: 'Bir banka ekstresiyle başla: Lumio onu okur ve az önce gördüğün sayfaları doldurur.',
        uk: 'Почніть із банківської виписки: Lumio прочитає її та заповнить сторінки, які ви щойно бачили.',
        zh: '从一份银行对账单开始：Lumio 会读取它，并填充你刚才看到的这些页面。',
        ar: 'ابدأ بكشف حساب بنكي: يقرؤه Lumio ويملأ الصفحات التي رأيتها للتو.',
        pl: 'Zacznij od wyciągu bankowego: Lumio go odczyta i wypełni strony, które właśnie zobaczyłeś.',
        it: 'Inizia da un estratto conto: Lumio lo legge e compila le pagine che hai appena visto.',
        sk: 'Začnite bankovým výpisom: Lumio ho prečíta a vyplní stránky, ktoré ste práve videli.',
        ja: 'まずは銀行の明細書から。Lumio が読み取り、いま見たページにデータを入れていきます。',
        ko: '은행 거래 내역서로 시작해 보세요. Lumio가 내용을 읽고 방금 본 페이지들을 채워 줍니다.',
        hi: 'बैंक स्टेटमेंट से शुरू करें: Lumio उसे पढ़कर वे पेज भर देता है जो आपने अभी देखे।',
        nl: 'Begin met een bankafschrift: Lumio leest het en vult de pagina’s die je net hebt gezien.',
        sv: 'Börja med ett kontoutdrag: Lumio läser det och fyller sidorna du just har sett.',
        vi: 'Hãy bắt đầu với một sao kê ngân hàng: Lumio sẽ đọc và điền dữ liệu vào các trang bạn vừa xem.',
        id: 'Mulailah dengan rekening koran: Lumio membacanya dan mengisi halaman-halaman yang baru kamu lihat.',
        da: 'Begynd med et kontoudtog: Lumio læser det og udfylder de sider, du lige har set.',
        nb: 'Begynn med en kontoutskrift: Lumio leser den og fyller ut sidene du nettopp har sett.',
        nn: 'Byrj med ei kontoutskrift: Lumio les henne og fyller ut sidene du nett har sett.',
        fi: 'Aloita tiliotteesta: Lumio lukee sen ja täyttää juuri näkemäsi sivut.',
        is: 'Byrjaðu á bankayfirliti: Lumio les það og fyllir út síðurnar sem þú sást núna.',
        fo: 'Byrja við einum bankakontoyvirliti: Lumio lesur tað og fyllir út síðurnar, sum tú júst hevur sæð.',
        cs: 'Začněte bankovním výpisem: Lumio ho přečte a vyplní stránky, které jste právě viděli.',
        bg: 'Започнете с банково извлечение: Lumio го разчита и попълва страниците, които току-що видяхте.',
        hr: 'Počnite s bankovnim izvodom: Lumio ga pročita i ispuni stranice koje ste upravo vidjeli.',
        sr: 'Почните с банковним изводом: Lumio га прочита и испуни странице које сте управо видели.',
        sl: 'Začnite z bančnim izpiskom: Lumio ga prebere in izpolni strani, ki ste jih pravkar videli.',
        mk: 'Почнете со банкарски извадок: Lumio го чита и ги пополнува страниците што штотуку ги видовте.',
        be: 'Пачніце з банкаўскай выпіскі: Lumio прачытае яе і запоўніць сторонкі, якія вы толькі што бачылі.',
        bs: 'Počnite s bankovnim izvodom: Lumio ga pročita i ispuni stranice koje ste upravo vidjeli.',
        hsb: 'Započńće z bankowym wupisom: Lumio jón čita a wupjelni strony, kotrež sće runje widźał.',
      }),
      upload: t({
        ru: 'Загрузить выписку',
        en: 'Upload a statement',
        kk: 'Үзінді жүктеу',
        de: 'Kontoauszug hochladen',
        fr: 'Importer un relevé',
        es: 'Subir un extracto',
        pt: 'Enviar um extrato',
        tr: 'Ekstre yükle',
        uk: 'Завантажити виписку',
        zh: '上传对账单',
        ar: 'رفع كشف حساب',
        pl: 'Prześlij wyciąg',
        it: 'Carica un estratto conto',
        sk: 'Nahrať výpis',
        ja: '明細書をアップロード',
        ko: '거래 내역서 업로드',
        hi: 'स्टेटमेंट अपलोड करें',
        nl: 'Afschrift uploaden',
        sv: 'Ladda upp ett kontoutdrag',
        vi: 'Tải sao kê lên',
        id: 'Unggah rekening koran',
        da: 'Upload et kontoudtog',
        nb: 'Last opp en kontoutskrift',
        nn: 'Last opp ei kontoutskrift',
        fi: 'Lataa tiliote',
        is: 'Sendu inn yfirlit',
        fo: 'Send eitt kontoyvirlit inn',
        cs: 'Nahrát výpis',
        bg: 'Качване на извлечение',
        hr: 'Učitaj izvod',
        sr: 'Учитај извод',
        sl: 'Naloži izpisek',
        mk: 'Постави извадок',
        be: 'Загрузіць выпіску',
        bs: 'Učitaj izvod',
        hsb: 'Wupis nahrać',
      }),
      dashboard: t({
        ru: 'Перейти на дашборд',
        en: 'Go to the dashboard',
        kk: 'Басқару тақтасына өту',
        de: 'Zum Dashboard',
        fr: 'Aller au tableau de bord',
        es: 'Ir al panel',
        pt: 'Ir para o painel',
        tr: 'Panoya git',
        uk: 'Перейти до дашборду',
        zh: '前往仪表盘',
        ar: 'الانتقال إلى لوحة المعلومات',
        pl: 'Przejdź do pulpitu',
        it: 'Vai alla dashboard',
        sk: 'Prejsť na nástenku',
        ja: 'ダッシュボードへ',
        ko: '대시보드로 이동',
        hi: 'डैशबोर्ड पर जाएँ',
        nl: 'Naar het dashboard',
        sv: 'Gå till översikten',
        vi: 'Đến trang tổng quan',
        id: 'Ke dasbor',
        da: 'Gå til overblikket',
        nb: 'Gå til oversikten',
        nn: 'Gå til oversynet',
        fi: 'Siirry yleisnäkymään',
        is: 'Fara á yfirlitið',
        fo: 'Far til yvirlitið',
        cs: 'Přejít na přehled',
        bg: 'Към таблото',
        hr: 'Idi na nadzornu ploču',
        sr: 'Иди на контролну таблу',
        sl: 'Pojdi na nadzorno ploščo',
        mk: 'Оди на контролната табла',
        be: 'Перайсці на панэль',
        bs: 'Idi na kontrolnu tablu',
        hsb: 'K přehladnej desce',
      }),
      avatarHint: t({
        ru: 'Открыть этот туториал снова можно из меню аватара.',
        en: 'Open this tutorial again from your avatar menu.',
        kk: 'Бұл нұсқаулықты аватар мәзірінен қайта ашуға болады.',
        de: 'Du findest dieses Tutorial jederzeit im Menü deines Avatars.',
        fr: 'Rouvrez ce tutoriel depuis le menu de votre avatar.',
        es: 'Vuelve a abrir este tutorial desde el menú de tu avatar.',
        pt: 'Abra este tutorial de novo pelo menu do seu avatar.',
        tr: 'Bu eğitimi avatar menüsünden yeniden açabilirsin.',
        uk: 'Відкрити цей туторіал знову можна з меню аватара.',
        zh: '可从头像菜单再次打开本教程。',
        ar: 'افتح هذا الدليل مجددًا من قائمة الصورة الرمزية.',
        pl: 'Ten samouczek otworzysz ponownie z menu awatara.',
        it: 'Riapri questo tutorial dal menu del tuo avatar.',
        sk: 'Tento návod znova otvoríte z ponuky avatara.',
        ja: 'このチュートリアルはアバターのメニューから再表示できます。',
        ko: '이 튜토리얼은 아바타 메뉴에서 다시 열 수 있습니다.',
        hi: 'यह ट्यूटोरियल अवतार मेन्यू से फिर खोलें।',
        nl: 'Open deze tutorial opnieuw via het menu van je avatar.',
        sv: 'Öppna guiden igen från menyn under din avatar.',
        vi: 'Mở lại hướng dẫn này từ menu ảnh đại diện.',
        id: 'Buka tutorial ini lagi dari menu avatar.',
        da: 'Åbn denne vejledning igen fra menuen under din avatar.',
        nb: 'Åpne denne veiledningen igjen fra menyen under avataren din.',
        nn: 'Opne denne rettleiinga igjen frå menyen under avataren din.',
        fi: 'Avaa tämä esittely uudelleen avatarvalikosta.',
        is: 'Opnaðu þessa kynningu aftur úr valmyndinni undir notandamyndinni þinni.',
        fo: 'Lat hesa vegleiðing upp aftur úr valmyndini undir vangamyndini tíni.',
        cs: 'Tohoto průvodce znovu otevřete z nabídky pod svým avatarem.',
        bg: 'Отворете това въведение отново от менюто под аватара си.',
        hr: 'Ovaj vodič ponovno otvorite iz izbornika pod svojim avatarom.',
        sr: 'Овај водич поново отворите из менија под својим аватаром.',
        sl: 'Ta vodnik znova odprite iz menija pod svojim avatarjem.',
        mk: 'Овој водич отворете го повторно од менито под вашиот аватар.',
        be: 'Адкрыйце гэты даведнік зноў з меню пад сваім аватарам.',
        bs: 'Ovaj vodič ponovo otvorite iz menija pod svojim avatarom.',
        hsb: 'Wotewrće tutón nawod znowa z menija pod swojim awatarom.',
      }),
      toursHint: t({
        ru: 'Застряли на странице? Кнопка «?» в шапке запускает пошаговые туры.',
        en: 'Stuck on a page? The ? button in the header has step-by-step tours.',
        kk: 'Бетте тұрып қалдыңыз ба? Тақырыптағы «?» түймесі қадамдық турларды ашады.',
        de: 'Nicht weiter? Der ?-Button oben bietet Touren Schritt für Schritt.',
        fr: 'Bloqué sur une page ? Le bouton ? en haut propose des visites pas à pas.',
        es: '¿Atascado en una página? El botón ? de la cabecera tiene recorridos paso a paso.',
        pt: 'Travou em alguma página? O botão ? no topo tem tours passo a passo.',
        tr: 'Bir sayfada takıldın mı? Üstteki ? düğmesinde adım adım turlar var.',
        uk: 'Застрягли на сторінці? Кнопка «?» у шапці запускає покрокові тури.',
        zh: '在某个页面卡住了？页头的 ? 按钮提供分步导览。',
        ar: 'هل تواجه صعوبة في صفحة ما؟ يحتوي زر ? في الأعلى على جولات خطوة بخطوة.',
        pl: 'Utknąłeś na jakiejś stronie? Przycisk ? w nagłówku uruchamia przewodniki krok po kroku.',
        it: 'Bloccato su una pagina? Il pulsante ? in alto offre tour passo passo.',
        sk: 'Neviete si rady na stránke? Tlačidlo ? v hlavičke spúšťa prehliadky krok za krokom.',
        ja: 'ページで迷ったら、ヘッダーの ? ボタンからステップごとのツアーを開けます。',
        ko: '페이지에서 막히셨나요? 상단의 ? 버튼에서 단계별 안내를 볼 수 있습니다.',
        hi: 'किसी पेज पर अटक गए? हेडर का ? बटन कदम-दर-कदम टूर दिखाता है।',
        nl: 'Kom je ergens niet uit? De ?-knop bovenaan heeft rondleidingen stap voor stap.',
        sv: 'Fastnat på en sida? Knappen ? i sidhuvudet har steg-för-steg-turer.',
        vi: 'Gặp khó ở một trang? Nút ? trên đầu trang có hướng dẫn từng bước.',
        id: 'Bingung di suatu halaman? Tombol ? di bagian atas punya tur langkah demi langkah.',
        da: 'Sidder du fast på en side? Knappen ? i toppen giver trin-for-trin-ture.',
        nb: 'Står du fast på en side? Knappen ? øverst har trinnvise omvisninger.',
        nn: 'Står du fast på ei side? Knappen ? øvst har stegvise omvisingar.',
        fi: 'Jumitatko jollakin sivulla? Yläpalkin ?-painikkeesta löytyy vaiheittaiset kierrokset.',
        is: 'Ertu fastur á einhverri síðu? Hnappurinn ? efst er með kynningar skref fyrir skref.',
        fo: 'Stendur tú fastur á eini síðu? Knappurin ? ovast hevur ferðir stig fyri stig.',
        cs: 'Zaseknete se na nějaké stránce? Tlačítko ? v záhlaví nabízí prohlídky krok za krokem.',
        bg: 'Затруднявате се на някоя страница? Бутонът ? в заглавната лента предлага обиколки стъпка по стъпка.',
        hr: 'Zapeli ste na nekoj stranici? Gumb ? u zaglavlju nudi obilaske korak po korak.',
        sr: 'Заглавили сте на некој страници? Дугме ? у заглављу нуди обиласке корак по корак.',
        sl: 'Obtičali ste na kakšni strani? Gumb ? v glavi ponuja oglede korak za korakom.',
        mk: 'Заглавивте на некоја страница? Копчето ? во заглавјето нуди обиколки чекор по чекор.',
        be: 'Заселі на якой сторонцы? Кнопка ? у шапцы дае экскурсіі крок за крокам.',
        bs: 'Zapeli ste na nekoj stranici? Dugme ? u zaglavlju nudi obilaske korak po korak.',
        hsb: 'Zastajeny na někajkej stronje? Tastka ? w hłowje poskićuje wodźenja krok po kroku.',
      }),
    },
  },
} satisfies Dictionary;

export default content;
