import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'receiptLocationConsent',
  content: {
    title: t({
      ru: 'Сохранять место съёмки чеков?',
      en: 'Save where receipts are photographed?',
      kk: 'Чектер түсірілген орынды сақтау керек пе?',
      de: 'Aufnahmeort von Belegen speichern?',
      fr: 'Enregistrer le lieu où les reçus sont photographiés ?',
      es: '¿Guardar dónde se fotografían los recibos?',
      pt: 'Guardar onde os recibos são fotografados?',
      tr: 'Fişlerin çekildiği yer kaydedilsin mi?',
      uk: 'Зберігати місце зйомки чеків?',
      zh: '保存收据的拍摄地点吗？',
      ar: 'هل تريد حفظ مكان تصوير الإيصالات؟',
      pl: 'Zapisywać miejsce fotografowania paragonów?',
      it: 'Salvare il luogo in cui fotografi gli scontrini?',
      sk: 'Ukladať miesto, kde boli bločky odfotené?',
      ja: 'レシートを撮影した場所を保存しますか？',
      ko: '영수증을 촬영한 위치를 저장할까요?',
      hi: 'क्या रसीदों की फ़ोटो लेने की जगह सहेजें?',
      nl: 'Opslaan waar bonnetjes worden gefotografeerd?',
      sv: 'Spara var kvitton fotograferas?',
      vi: 'Lưu nơi chụp hóa đơn?',
      id: 'Simpan lokasi pemotretan struk?',
    }),
    body: t({
      ru: 'Lumio сохранит место, где вы сфотографировали чек камерой, и покажет его на карте в деталях чека. Фото из галереи не привязываются.',
      en: 'Lumio will save the place where you photograph a receipt with the camera and show it on the receipt map. Photos from the gallery are never tagged.',
      kk: 'Lumio чекті камерамен түсірген орынды сақтап, оны чек картасында көрсетеді. Галереядағы фотолар байланыстырылмайды.',
      de: 'Lumio speichert, wo Sie einen Beleg mit der Kamera fotografieren, und zeigt den Ort auf der Belegkarte. Fotos aus der Galerie werden nie markiert.',
      fr: 'Lumio enregistre l’endroit où vous photographiez un reçu avec l’appareil photo et l’affiche sur la carte du reçu. Les photos de la galerie ne sont jamais localisées.',
      es: 'Lumio guardará dónde fotografías un recibo con la cámara y lo mostrará en el mapa del recibo. Las fotos de la galería nunca se etiquetan.',
      pt: 'O Lumio guarda o local onde fotografa um recibo com a câmara e mostra-o no mapa do recibo. As fotografias da galeria nunca são marcadas.',
      tr: 'Lumio, fişi kamerayla çektiğiniz yeri kaydeder ve fiş haritasında gösterir. Galeriden seçilen fotoğraflar asla işaretlenmez.',
      uk: 'Lumio збереже місце, де ви сфотографували чек камерою, і покаже його на карті в деталях чека. Фото з галереї не прив’язуються.',
      zh: 'Lumio 会保存您用相机拍摄收据的地点，并在收据地图上显示。从相册选择的照片不会被标记位置。',
      ar: 'سيحفظ Lumio المكان الذي تصوّر فيه الإيصال بالكاميرا ويعرضه على خريطة الإيصال. لا تُضاف أي مواقع إلى الصور من المعرض.',
      pl: 'Lumio zapisze miejsce, w którym fotografujesz paragon aparatem, i pokaże je na mapie paragonu. Zdjęcia z galerii nigdy nie są oznaczane.',
      it: 'Lumio salva il luogo in cui fotografi uno scontrino con la fotocamera e lo mostra sulla mappa dello scontrino. Le foto dalla galleria non vengono mai contrassegnate.',
      sk: 'Lumio uloží miesto, kde ste bloček odfotili fotoaparátom, a zobrazí ho na mape bločku. Fotky z galérie sa nikdy neoznačujú.',
      ja: 'カメラでレシートを撮影した場所を保存し、レシートの地図に表示します。ギャラリーから選んだ写真には位置情報を付けません。',
      ko: '카메라로 영수증을 촬영한 위치를 저장하고 영수증 지도에 표시합니다. 갤러리에서 고른 사진에는 위치를 붙이지 않습니다.',
      hi: 'Lumio कैमरे से रसीद की फ़ोटो लेने की जगह सहेजेगा और उसे रसीद के मानचित्र पर दिखाएगा। गैलरी की फ़ोटो पर कभी स्थान नहीं जोड़ा जाता।',
      nl: 'Lumio slaat op waar je een bonnetje met de camera fotografeert en toont dat op de kaart van het bonnetje. Foto’s uit de galerij krijgen nooit een locatie.',
      sv: 'Lumio sparar var du fotograferar ett kvitto med kameran och visar platsen på kvittots karta. Foton från galleriet märks aldrig.',
      vi: 'Lumio sẽ lưu nơi bạn chụp hóa đơn bằng camera và hiển thị trên bản đồ của hóa đơn. Ảnh từ thư viện không bao giờ được gắn vị trí.',
      id: 'Lumio akan menyimpan tempat Anda memotret struk dengan kamera dan menampilkannya di peta struk. Foto dari galeri tidak pernah diberi lokasi.',
    }),
    privacy: t({
      ru: 'Место хранится только вместе с чеком в вашем рабочем пространстве. Изменить выбор можно в настройках.',
      en: 'The place is stored only with the receipt in your workspace. You can change this in Settings.',
      kk: 'Орын тек жұмыс кеңістігіңіздегі чекпен бірге сақталады. Таңдауды баптаулардан өзгертуге болады.',
      de: 'Der Ort wird nur zusammen mit dem Beleg in Ihrem Workspace gespeichert. Sie können das in den Einstellungen ändern.',
      fr: 'Le lieu est enregistré uniquement avec le reçu dans votre espace de travail. Vous pouvez changer ce choix dans les paramètres.',
      es: 'La ubicación solo se guarda con el recibo en tu espacio de trabajo. Puedes cambiarlo en Ajustes.',
      pt: 'O local é guardado apenas com o recibo no seu espaço de trabalho. Pode alterar isto nas Definições.',
      tr: 'Konum yalnızca çalışma alanınızdaki fişle birlikte saklanır. Bunu Ayarlar’dan değiştirebilirsiniz.',
      uk: 'Місце зберігається лише разом із чеком у вашому робочому просторі. Змінити вибір можна в налаштуваннях.',
      zh: '地点只会随收据保存在您的工作区中。您可以在设置中更改此选项。',
      ar: 'يُحفظ المكان مع الإيصال فقط داخل مساحة عملك. يمكنك تغيير ذلك من الإعدادات.',
      pl: 'Miejsce jest zapisywane tylko razem z paragonem w Twoim obszarze roboczym. Możesz to zmienić w Ustawieniach.',
      it: 'Il luogo viene salvato solo insieme allo scontrino nel tuo spazio di lavoro. Puoi cambiarlo nelle Impostazioni.',
      sk: 'Miesto sa ukladá iba spolu s bločkom vo vašom pracovnom priestore. Zmeniť to môžete v Nastaveniach.',
      ja: '場所はワークスペース内のレシートと一緒にのみ保存されます。設定でいつでも変更できます。',
      ko: '위치는 워크스페이스의 영수증과 함께만 저장됩니다. 설정에서 변경할 수 있습니다.',
      hi: 'स्थान केवल आपके वर्कस्पेस में रसीद के साथ सहेजा जाता है। आप इसे सेटिंग्स में बदल सकते हैं।',
      nl: 'De plaats wordt alleen bij het bonnetje in je werkruimte opgeslagen. Je kunt dit wijzigen in Instellingen.',
      sv: 'Platsen sparas bara tillsammans med kvittot i din arbetsyta. Du kan ändra detta i Inställningar.',
      vi: 'Vị trí chỉ được lưu cùng hóa đơn trong không gian làm việc của bạn. Bạn có thể thay đổi trong Cài đặt.',
      id: 'Lokasi hanya disimpan bersama struk di ruang kerja Anda. Anda dapat mengubahnya di Pengaturan.',
    }),
    allow: t({
      ru: 'Разрешить',
      en: 'Allow',
      kk: 'Рұқсат беру',
      de: 'Erlauben',
      fr: 'Autoriser',
      es: 'Permitir',
      pt: 'Permitir',
      tr: 'İzin ver',
      uk: 'Дозволити',
      zh: '允许',
      ar: 'السماح',
      pl: 'Zezwól',
      it: 'Consenti',
      sk: 'Povoliť',
      ja: '許可する',
      ko: '허용',
      hi: 'अनुमति दें',
      nl: 'Toestaan',
      sv: 'Tillåt',
      vi: 'Cho phép',
      id: 'Izinkan',
    }),
    notNow: t({
      ru: 'Не сейчас',
      en: 'Not now',
      kk: 'Қазір емес',
      de: 'Nicht jetzt',
      fr: 'Pas maintenant',
      es: 'Ahora no',
      pt: 'Agora não',
      tr: 'Şimdi değil',
      uk: 'Не зараз',
      zh: '暂不',
      ar: 'ليس الآن',
      pl: 'Nie teraz',
      it: 'Non ora',
      sk: 'Teraz nie',
      ja: '今はしない',
      ko: '나중에',
      hi: 'अभी नहीं',
      nl: 'Niet nu',
      sv: 'Inte nu',
      vi: 'Để sau',
      id: 'Nanti saja',
    }),
    requesting: t({
      ru: 'Ждём ответа браузера…',
      en: 'Waiting for your browser…',
      kk: 'Браузер жауабын күтудеміз…',
      de: 'Warte auf die Antwort des Browsers …',
      fr: 'En attente de la réponse du navigateur…',
      es: 'Esperando la respuesta del navegador…',
      pt: 'À espera da resposta do navegador…',
      tr: 'Tarayıcının yanıtı bekleniyor…',
      uk: 'Чекаємо відповіді браузера…',
      zh: '正在等待浏览器响应…',
      ar: 'في انتظار رد المتصفح…',
      pl: 'Czekamy na odpowiedź przeglądarki…',
      it: 'In attesa della risposta del browser…',
      sk: 'Čaká sa na odpoveď prehliadača…',
      ja: 'ブラウザーの応答を待っています…',
      ko: '브라우저 응답을 기다리는 중…',
      hi: 'ब्राउज़र के जवाब का इंतज़ार है…',
      nl: 'Wachten op antwoord van de browser…',
      sv: 'Väntar på svar från webbläsaren…',
      vi: 'Đang chờ trình duyệt phản hồi…',
      id: 'Menunggu jawaban browser…',
    }),
    grantedTitle: t({
      ru: 'Геолокация включена',
      en: 'Location is on',
      kk: 'Геолокация қосылды',
      de: 'Standort ist aktiviert',
      fr: 'La localisation est activée',
      es: 'La ubicación está activada',
      pt: 'A localização está ativada',
      tr: 'Konum açık',
      uk: 'Геолокацію увімкнено',
      zh: '位置功能已开启',
      ar: 'الموقع مُفعّل',
      pl: 'Lokalizacja jest włączona',
      it: 'La posizione è attiva',
      sk: 'Poloha je zapnutá',
      ja: '位置情報がオンになりました',
      ko: '위치가 켜졌습니다',
      hi: 'स्थान चालू है',
      nl: 'Locatie staat aan',
      sv: 'Platsen är på',
      vi: 'Đã bật vị trí',
      id: 'Lokasi aktif',
    }),
    grantedBody: t({
      ru: 'Сфотографированные чеки будут автоматически отмечаться на карте.',
      en: 'Receipts you photograph will be placed on the map automatically.',
      kk: 'Түсірілген чектер картада автоматты түрде белгіленеді.',
      de: 'Fotografierte Belege werden automatisch auf der Karte markiert.',
      fr: 'Les reçus photographiés seront placés automatiquement sur la carte.',
      es: 'Los recibos que fotografíes aparecerán en el mapa automáticamente.',
      pt: 'Os recibos que fotografar serão colocados no mapa automaticamente.',
      tr: 'Çektiğiniz fişler haritaya otomatik olarak yerleştirilecek.',
      uk: 'Сфотографовані чеки автоматично позначатимуться на карті.',
      zh: '您拍摄的收据会自动显示在地图上。',
      ar: 'ستظهر الإيصالات التي تصوّرها على الخريطة تلقائيًا.',
      pl: 'Sfotografowane paragony będą automatycznie oznaczane na mapie.',
      it: 'Gli scontrini che fotografi verranno posizionati automaticamente sulla mappa.',
      sk: 'Odfotené bločky sa automaticky označia na mape.',
      ja: '撮影したレシートは自動的に地図に表示されます。',
      ko: '촬영한 영수증이 지도에 자동으로 표시됩니다.',
      hi: 'आपकी खींची गई रसीदें अपने आप मानचित्र पर दिखेंगी।',
      nl: 'Gefotografeerde bonnetjes worden automatisch op de kaart gezet.',
      sv: 'Kvitton du fotograferar placeras automatiskt på kartan.',
      vi: 'Hóa đơn bạn chụp sẽ tự động được đặt trên bản đồ.',
      id: 'Struk yang Anda potret akan otomatis ditandai di peta.',
    }),
    deniedTitle: t({
      ru: 'Доступ к геолокации запрещён',
      en: 'Location access is blocked',
      kk: 'Геолокацияға рұқсат жоқ',
      de: 'Standortzugriff ist blockiert',
      fr: 'L’accès à la localisation est bloqué',
      es: 'El acceso a la ubicación está bloqueado',
      pt: 'O acesso à localização está bloqueado',
      tr: 'Konum erişimi engellendi',
      uk: 'Доступ до геолокації заборонено',
      zh: '位置访问已被阻止',
      ar: 'الوصول إلى الموقع محظور',
      pl: 'Dostęp do lokalizacji jest zablokowany',
      it: 'L’accesso alla posizione è bloccato',
      sk: 'Prístup k polohe je zablokovaný',
      ja: '位置情報へのアクセスがブロックされています',
      ko: '위치 접근이 차단되었습니다',
      hi: 'स्थान की पहुँच अवरुद्ध है',
      nl: 'Locatietoegang is geblokkeerd',
      sv: 'Åtkomst till plats är blockerad',
      vi: 'Quyền truy cập vị trí bị chặn',
      id: 'Akses lokasi diblokir',
    }),
    deniedBody: t({
      ru: 'Чеки будут сохраняться без места съёмки. Чтобы включить, разрешите геолокацию для сайта в браузере и в настройках Lumio.',
      en: 'Receipts will be saved without the place they were photographed. To turn it on, allow location for this site in your browser and in Lumio settings.',
      kk: 'Чектер түсірілген орынсыз сақталады. Қосу үшін браузерде және Lumio баптауларында сайтқа геолокацияға рұқсат беріңіз.',
      de: 'Belege werden ohne Aufnahmeort gespeichert. Erlauben Sie zum Aktivieren den Standort für diese Website im Browser und in den Lumio-Einstellungen.',
      fr: 'Les reçus seront enregistrés sans le lieu de la photo. Pour l’activer, autorisez la localisation pour ce site dans le navigateur et dans les paramètres de Lumio.',
      es: 'Los recibos se guardarán sin el lugar donde se fotografiaron. Para activarlo, permite la ubicación para este sitio en el navegador y en los ajustes de Lumio.',
      pt: 'Os recibos serão guardados sem o local onde foram fotografados. Para ativar, permita a localização para este site no navegador e nas definições do Lumio.',
      tr: 'Fişler çekildikleri yer olmadan kaydedilecek. Açmak için tarayıcıda ve Lumio ayarlarında bu siteye konum izni verin.',
      uk: 'Чеки зберігатимуться без місця зйомки. Щоб увімкнути, дозвольте геолокацію для сайту в браузері та в налаштуваннях Lumio.',
      zh: '收据将不带拍摄地点保存。如需开启，请在浏览器和 Lumio 设置中允许此网站使用位置。',
      ar: 'ستُحفظ الإيصالات دون مكان التصوير. لتفعيل ذلك، اسمح لهذا الموقع باستخدام الموقع الجغرافي في المتصفح وفي إعدادات Lumio.',
      pl: 'Paragony będą zapisywane bez miejsca wykonania zdjęcia. Aby to włączyć, zezwól tej witrynie na lokalizację w przeglądarce i w ustawieniach Lumio.',
      it: 'Gli scontrini verranno salvati senza il luogo della foto. Per attivarlo, consenti la posizione per questo sito nel browser e nelle impostazioni di Lumio.',
      sk: 'Bločky sa uložia bez miesta odfotenia. Ak to chcete zapnúť, povoľte polohu pre túto stránku v prehliadači a v nastaveniach Lumio.',
      ja: 'レシートは撮影場所なしで保存されます。オンにするには、ブラウザーと Lumio の設定でこのサイトの位置情報を許可してください。',
      ko: '영수증은 촬영 위치 없이 저장됩니다. 켜려면 브라우저와 Lumio 설정에서 이 사이트의 위치 접근을 허용하세요.',
      hi: 'रसीदें फ़ोटो लेने की जगह के बिना सहेजी जाएँगी। चालू करने के लिए ब्राउज़र और Lumio सेटिंग्स में इस साइट को स्थान की अनुमति दें।',
      nl: 'Bonnetjes worden opgeslagen zonder de plek van de foto. Sta locatie voor deze site toe in je browser en in de Lumio-instellingen om dit aan te zetten.',
      sv: 'Kvitton sparas utan platsen där de fotograferades. Tillåt plats för den här webbplatsen i webbläsaren och i Lumios inställningar för att slå på det.',
      vi: 'Hóa đơn sẽ được lưu mà không có nơi chụp. Để bật, hãy cho phép vị trí cho trang này trong trình duyệt và trong cài đặt Lumio.',
      id: 'Struk akan disimpan tanpa lokasi pemotretan. Untuk mengaktifkannya, izinkan lokasi untuk situs ini di browser dan di pengaturan Lumio.',
    }),
    openCamera: t({
      ru: 'Открыть камеру',
      en: 'Open camera',
      kk: 'Камераны ашу',
      de: 'Kamera öffnen',
      fr: 'Ouvrir l’appareil photo',
      es: 'Abrir la cámara',
      pt: 'Abrir a câmara',
      tr: 'Kamerayı aç',
      uk: 'Відкрити камеру',
      zh: '打开相机',
      ar: 'فتح الكاميرا',
      pl: 'Otwórz aparat',
      it: 'Apri la fotocamera',
      sk: 'Otvoriť fotoaparát',
      ja: 'カメラを開く',
      ko: '카메라 열기',
      hi: 'कैमरा खोलें',
      nl: 'Camera openen',
      sv: 'Öppna kameran',
      vi: 'Mở camera',
      id: 'Buka kamera',
    }),
    settingsTitle: t({
      ru: 'Геолокация чеков',
      en: 'Receipt location',
      kk: 'Чектердің геолокациясы',
      de: 'Belegstandort',
      fr: 'Localisation des reçus',
      es: 'Ubicación de recibos',
      pt: 'Localização dos recibos',
      tr: 'Fiş konumu',
      uk: 'Геолокація чеків',
      zh: '收据位置',
      ar: 'موقع الإيصالات',
      pl: 'Lokalizacja paragonów',
      it: 'Posizione degli scontrini',
      sk: 'Poloha bločkov',
      ja: 'レシートの位置情報',
      ko: '영수증 위치',
      hi: 'रसीद का स्थान',
      nl: 'Locatie van bonnetjes',
      sv: 'Kvittoplats',
      vi: 'Vị trí hóa đơn',
      id: 'Lokasi struk',
    }),
    settingsDescription: t({
      ru: 'Отмечать место съёмки чеков на этом устройстве',
      en: 'Tag receipts photographed on this device with the place',
      kk: 'Осы құрылғыда түсірілген чектердің орнын белгілеу',
      de: 'Aufnahmeort von Belegen auf diesem Gerät speichern',
      fr: 'Localiser les reçus photographiés sur cet appareil',
      es: 'Etiquetar con la ubicación los recibos fotografiados en este dispositivo',
      pt: 'Marcar com o local os recibos fotografados neste dispositivo',
      tr: 'Bu cihazda çekilen fişlere konum ekle',
      uk: 'Позначати місце зйомки чеків на цьому пристрої',
      zh: '为在此设备上拍摄的收据标记地点',
      ar: 'إضافة المكان إلى الإيصالات المصوّرة على هذا الجهاز',
      pl: 'Oznaczaj miejscem paragony fotografowane na tym urządzeniu',
      it: 'Aggiungi il luogo agli scontrini fotografati su questo dispositivo',
      sk: 'Označovať miestom bločky odfotené na tomto zariadení',
      ja: 'この端末で撮影したレシートに場所を記録',
      ko: '이 기기에서 촬영한 영수증에 위치 표시',
      hi: 'इस डिवाइस पर खींची गई रसीदों में स्थान जोड़ें',
      nl: 'Bonnetjes die op dit apparaat worden gefotografeerd voorzien van een locatie',
      sv: 'Märk kvitton som fotograferas på den här enheten med plats',
      vi: 'Gắn vị trí cho hóa đơn chụp trên thiết bị này',
      id: 'Tandai lokasi pada struk yang dipotret di perangkat ini',
    }),
    toggleLabel: t({
      ru: 'Сохранять место съёмки чеков',
      en: 'Save where receipts are photographed',
      kk: 'Чектер түсірілген орынды сақтау',
      de: 'Aufnahmeort von Belegen speichern',
      fr: 'Enregistrer le lieu où les reçus sont photographiés',
      es: 'Guardar dónde se fotografían los recibos',
      pt: 'Guardar onde os recibos são fotografados',
      tr: 'Fişlerin çekildiği yeri kaydet',
      uk: 'Зберігати місце зйомки чеків',
      zh: '保存收据的拍摄地点',
      ar: 'حفظ مكان تصوير الإيصالات',
      pl: 'Zapisuj miejsce fotografowania paragonów',
      it: 'Salva il luogo in cui fotografi gli scontrini',
      sk: 'Ukladať miesto odfotenia bločkov',
      ja: 'レシートを撮影した場所を保存',
      ko: '영수증 촬영 위치 저장',
      hi: 'रसीदों की फ़ोटो लेने की जगह सहेजें',
      nl: 'Opslaan waar bonnetjes worden gefotografeerd',
      sv: 'Spara var kvitton fotograferas',
      vi: 'Lưu nơi chụp hóa đơn',
      id: 'Simpan lokasi pemotretan struk',
    }),
    toggleHelp: t({
      ru: 'Только на этом устройстве и только для фото с камеры.',
      en: 'Only on this device and only for photos taken with the camera.',
      kk: 'Тек осы құрылғыда және тек камерамен түсірілген фотолар үшін.',
      de: 'Nur auf diesem Gerät und nur für Fotos mit der Kamera.',
      fr: 'Uniquement sur cet appareil et pour les photos prises avec l’appareil photo.',
      es: 'Solo en este dispositivo y solo para fotos tomadas con la cámara.',
      pt: 'Apenas neste dispositivo e apenas para fotografias tiradas com a câmara.',
      tr: 'Yalnızca bu cihazda ve yalnızca kamerayla çekilen fotoğraflar için.',
      uk: 'Лише на цьому пристрої й лише для фото з камери.',
      zh: '仅限此设备，且仅适用于相机拍摄的照片。',
      ar: 'على هذا الجهاز فقط وللصور الملتقطة بالكاميرا فقط.',
      pl: 'Tylko na tym urządzeniu i tylko dla zdjęć z aparatu.',
      it: 'Solo su questo dispositivo e solo per le foto scattate con la fotocamera.',
      sk: 'Iba na tomto zariadení a iba pre fotky z fotoaparátu.',
      ja: 'この端末で、カメラで撮影した写真のみが対象です。',
      ko: '이 기기에서 카메라로 촬영한 사진에만 적용됩니다.',
      hi: 'केवल इस डिवाइस पर और केवल कैमरे से ली गई फ़ोटो के लिए।',
      nl: 'Alleen op dit apparaat en alleen voor foto’s met de camera.',
      sv: 'Bara på den här enheten och bara för foton tagna med kameran.',
      vi: 'Chỉ trên thiết bị này và chỉ với ảnh chụp bằng camera.',
      id: 'Hanya di perangkat ini dan hanya untuk foto dari kamera.',
    }),
    unsupported: t({
      ru: 'Геолокация недоступна в этом браузере.',
      en: 'Location is not available in this browser.',
      kk: 'Бұл браузерде геолокация қолжетімсіз.',
      de: 'In diesem Browser ist der Standort nicht verfügbar.',
      fr: 'La localisation n’est pas disponible dans ce navigateur.',
      es: 'La ubicación no está disponible en este navegador.',
      pt: 'A localização não está disponível neste navegador.',
      tr: 'Bu tarayıcıda konum kullanılamıyor.',
      uk: 'Геолокація недоступна в цьому браузері.',
      zh: '此浏览器无法使用位置功能。',
      ar: 'الموقع غير متاح في هذا المتصفح.',
      pl: 'Lokalizacja nie jest dostępna w tej przeglądarce.',
      it: 'La posizione non è disponibile in questo browser.',
      sk: 'Poloha nie je v tomto prehliadači dostupná.',
      ja: 'このブラウザーでは位置情報を利用できません。',
      ko: '이 브라우저에서는 위치를 사용할 수 없습니다.',
      hi: 'इस ब्राउज़र में स्थान उपलब्ध नहीं है।',
      nl: 'Locatie is niet beschikbaar in deze browser.',
      sv: 'Plats är inte tillgänglig i den här webbläsaren.',
      vi: 'Trình duyệt này không hỗ trợ vị trí.',
      id: 'Lokasi tidak tersedia di browser ini.',
    }),
    browserBlocked: t({
      ru: 'Браузер запрещает геолокацию для этого сайта. Разрешите её в настройках браузера и включите снова.',
      en: 'Your browser blocks location for this site. Allow it in the browser settings, then turn this on again.',
      kk: 'Браузер бұл сайт үшін геолокацияға тыйым салады. Браузер баптауларында рұқсат беріп, қайта қосыңыз.',
      de: 'Ihr Browser blockiert den Standort für diese Website. Erlauben Sie ihn in den Browsereinstellungen und aktivieren Sie die Option erneut.',
      fr: 'Votre navigateur bloque la localisation pour ce site. Autorisez-la dans ses paramètres, puis réactivez cette option.',
      es: 'Tu navegador bloquea la ubicación para este sitio. Permítela en los ajustes del navegador y vuelve a activar esta opción.',
      pt: 'O navegador bloqueia a localização para este site. Permita-a nas definições do navegador e volte a ativar esta opção.',
      tr: 'Tarayıcınız bu site için konumu engelliyor. Tarayıcı ayarlarından izin verin ve bunu yeniden açın.',
      uk: 'Браузер забороняє геолокацію для цього сайту. Дозвольте її в налаштуваннях браузера й увімкніть знову.',
      zh: '您的浏览器已阻止此网站使用位置。请在浏览器设置中允许，然后重新开启此选项。',
      ar: 'يحظر متصفحك الموقع لهذا الموقع الإلكتروني. اسمح به في إعدادات المتصفح ثم فعّل هذا الخيار مرة أخرى.',
      pl: 'Przeglądarka blokuje lokalizację dla tej witryny. Zezwól na nią w ustawieniach przeglądarki i włącz tę opcję ponownie.',
      it: 'Il browser blocca la posizione per questo sito. Consentila nelle impostazioni del browser e riattiva questa opzione.',
      sk: 'Prehliadač blokuje polohu pre túto stránku. Povoľte ju v nastaveniach prehliadača a zapnite túto možnosť znova.',
      ja: 'ブラウザーがこのサイトの位置情報をブロックしています。ブラウザーの設定で許可してから、もう一度オンにしてください。',
      ko: '브라우저가 이 사이트의 위치 접근을 차단하고 있습니다. 브라우저 설정에서 허용한 뒤 다시 켜세요.',
      hi: 'आपका ब्राउज़र इस साइट के लिए स्थान को रोक रहा है। ब्राउज़र सेटिंग्स में अनुमति दें, फिर इसे दोबारा चालू करें।',
      nl: 'Je browser blokkeert locatie voor deze site. Sta het toe in de browserinstellingen en zet dit daarna opnieuw aan.',
      sv: 'Webbläsaren blockerar plats för den här webbplatsen. Tillåt det i webbläsarens inställningar och slå sedan på det igen.',
      vi: 'Trình duyệt đang chặn vị trí cho trang này. Hãy cho phép trong cài đặt trình duyệt rồi bật lại.',
      id: 'Browser Anda memblokir lokasi untuk situs ini. Izinkan di pengaturan browser, lalu aktifkan lagi.',
    }),
  },
} satisfies Dictionary;

export default content;
