import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'receiptLocation',
  content: {
    title: t({
      ru: 'Местоположение',
      en: 'Location',
      kk: 'Орналасқан жері',
      de: 'Standort',
      fr: 'Emplacement',
      es: 'Ubicación',
      pt: 'Localização',
      tr: 'Konum',
      uk: 'Місцезнаходження',
      zh: '位置',
      ar: 'الموقع',
      pl: 'Lokalizacja',
      it: 'Posizione',
      sk: 'Poloha',
      ja: '場所',
      ko: '위치',
      hi: 'स्थान',
      nl: 'Locatie',
      sv: 'Plats',
      vi: 'Vị trí',
      id: 'Lokasi',
    }),
    sourceMerchantAddress: t({
      ru: 'По адресу продавца',
      en: 'From merchant address',
      kk: 'Сатушының мекенжайы бойынша',
      de: 'Aus der Händleradresse',
      fr: 'D’après l’adresse du commerçant',
      es: 'Según la dirección del comercio',
      pt: 'Pela morada do comerciante',
      tr: 'Satıcı adresinden',
      uk: 'За адресою продавця',
      zh: '根据商家地址',
      ar: 'من عنوان التاجر',
      pl: 'Z adresu sprzedawcy',
      it: 'Dall’indirizzo del negozio',
      sk: 'Z adresy predajcu',
      ja: '店舗の住所から',
      ko: '판매처 주소 기준',
      hi: 'विक्रेता के पते से',
      nl: 'Op basis van het winkeladres',
      sv: 'Från butikens adress',
      vi: 'Theo địa chỉ cửa hàng',
      id: 'Dari alamat penjual',
    }),
    sourceExif: t({
      ru: 'По данным фото',
      en: 'From photo',
      kk: 'Фото деректері бойынша',
      de: 'Aus dem Foto',
      fr: 'D’après la photo',
      es: 'Según la foto',
      pt: 'Pela fotografia',
      tr: 'Fotoğraftan',
      uk: 'За даними фото',
      zh: '根据照片',
      ar: 'من الصورة',
      pl: 'Ze zdjęcia',
      it: 'Dalla foto',
      sk: 'Z fotografie',
      ja: '写真から',
      ko: '사진 기준',
      hi: 'फ़ोटो से',
      nl: 'Op basis van de foto',
      sv: 'Från fotot',
      vi: 'Theo ảnh',
      id: 'Dari foto',
    }),
    sourceDevice: t({
      ru: 'По геолокации устройства',
      en: 'From device',
      kk: 'Құрылғы геолокациясы бойынша',
      de: 'Vom Gerätestandort',
      fr: 'D’après la position de l’appareil',
      es: 'Según la ubicación del dispositivo',
      pt: 'Pela localização do dispositivo',
      tr: 'Cihaz konumundan',
      uk: 'За геолокацією пристрою',
      zh: '根据设备位置',
      ar: 'من موقع الجهاز',
      pl: 'Z lokalizacji urządzenia',
      it: 'Dalla posizione del dispositivo',
      sk: 'Z polohy zariadenia',
      ja: '端末の位置情報から',
      ko: '기기 위치 기준',
      hi: 'डिवाइस के स्थान से',
      nl: 'Op basis van de apparaatlocatie',
      sv: 'Från enhetens plats',
      vi: 'Theo vị trí thiết bị',
      id: 'Dari lokasi perangkat',
    }),
    sourceManual: t({
      ru: 'Указано вручную',
      en: 'Set manually',
      kk: 'Қолмен көрсетілген',
      de: 'Manuell festgelegt',
      fr: 'Défini manuellement',
      es: 'Establecida manualmente',
      pt: 'Definida manualmente',
      tr: 'Elle belirlendi',
      uk: 'Вказано вручну',
      zh: '手动设置',
      ar: 'محدد يدويًا',
      pl: 'Ustawiono ręcznie',
      it: 'Impostata manualmente',
      sk: 'Nastavené ručne',
      ja: '手動で設定',
      ko: '직접 지정함',
      hi: 'मैन्युअल रूप से सेट',
      nl: 'Handmatig ingesteld',
      sv: 'Angiven manuellt',
      vi: 'Đặt thủ công',
      id: 'Diatur secara manual',
    }),
    sourceFiscalQr: t({
      ru: 'По данным налоговой',
      en: 'From tax receipt',
      kk: 'Салық деректері бойынша',
      de: 'Aus dem Steuerbeleg',
      fr: 'D’après le reçu fiscal',
      es: 'Según el recibo fiscal',
      pt: 'Pelo recibo fiscal',
      tr: 'Vergi fişinden',
      uk: 'За даними податкової',
      zh: '根据税务收据',
      ar: 'من الإيصال الضريبي',
      pl: 'Z paragonu fiskalnego',
      it: 'Dallo scontrino fiscale',
      sk: 'Z daňového dokladu',
      ja: '税務レシートから',
      ko: '세무 영수증 기준',
      hi: 'कर रसीद से',
      nl: 'Op basis van het fiscale bonnetje',
      sv: 'Från skattekvittot',
      vi: 'Theo hóa đơn thuế',
      id: 'Dari struk pajak',
    }),
    unsavedPoint: t({
      ru: 'Точка не сохранена',
      en: 'Unsaved point',
      kk: 'Нүкте сақталмаған',
      de: 'Nicht gespeicherter Punkt',
      fr: 'Point non enregistré',
      es: 'Punto sin guardar',
      pt: 'Ponto não guardado',
      tr: 'Kaydedilmemiş nokta',
      uk: 'Точку не збережено',
      zh: '未保存的位置点',
      ar: 'نقطة غير محفوظة',
      pl: 'Niezapisany punkt',
      it: 'Punto non salvato',
      sk: 'Neuložený bod',
      ja: '未保存の地点',
      ko: '저장되지 않은 지점',
      hi: 'बिना सहेजा बिंदु',
      nl: 'Niet-opgeslagen punt',
      sv: 'Osparad punkt',
      vi: 'Điểm chưa lưu',
      id: 'Titik belum disimpan',
    }),
    noLocation: t({
      ru: 'Местоположение не указано',
      en: 'No location yet',
      kk: 'Орналасқан жері көрсетілмеген',
      de: 'Noch kein Standort',
      fr: 'Aucun emplacement pour l’instant',
      es: 'Aún sin ubicación',
      pt: 'Ainda sem localização',
      tr: 'Henüz konum yok',
      uk: 'Місцезнаходження не вказано',
      zh: '暂无位置',
      ar: 'لا يوجد موقع بعد',
      pl: 'Brak lokalizacji',
      it: 'Nessuna posizione',
      sk: 'Zatiaľ bez polohy',
      ja: '場所はまだありません',
      ko: '아직 위치가 없습니다',
      hi: 'अभी कोई स्थान नहीं',
      nl: 'Nog geen locatie',
      sv: 'Ingen plats ännu',
      vi: 'Chưa có vị trí',
      id: 'Belum ada lokasi',
    }),
    cancel: t({
      ru: 'Отмена',
      en: 'Cancel',
      kk: 'Болдырмау',
      de: 'Abbrechen',
      fr: 'Annuler',
      es: 'Cancelar',
      pt: 'Cancelar',
      tr: 'İptal',
      uk: 'Скасувати',
      zh: '取消',
      ar: 'إلغاء',
      pl: 'Anuluj',
      it: 'Annulla',
      sk: 'Zrušiť',
      ja: 'キャンセル',
      ko: '취소',
      hi: 'रद्द करें',
      nl: 'Annuleren',
      sv: 'Avbryt',
      vi: 'Hủy',
      id: 'Batal',
    }),
    saveLocation: t({
      ru: 'Сохранить точку',
      en: 'Save location',
      kk: 'Нүктені сақтау',
      de: 'Standort speichern',
      fr: 'Enregistrer l’emplacement',
      es: 'Guardar ubicación',
      pt: 'Guardar localização',
      tr: 'Konumu kaydet',
      uk: 'Зберегти точку',
      zh: '保存位置',
      ar: 'حفظ الموقع',
      pl: 'Zapisz lokalizację',
      it: 'Salva posizione',
      sk: 'Uložiť polohu',
      ja: '場所を保存',
      ko: '위치 저장',
      hi: 'स्थान सहेजें',
      nl: 'Locatie opslaan',
      sv: 'Spara plats',
      vi: 'Lưu vị trí',
      id: 'Simpan lokasi',
    }),
    resetToAutomatic: t({
      ru: 'Вернуть автоматическую',
      en: 'Reset to automatic',
      kk: 'Автоматтыға қайтару',
      de: 'Auf automatisch zurücksetzen',
      fr: 'Revenir à l’emplacement automatique',
      es: 'Volver a la automática',
      pt: 'Repor a automática',
      tr: 'Otomatiğe sıfırla',
      uk: 'Повернути автоматичну',
      zh: '恢复自动定位',
      ar: 'إعادة التحديد التلقائي',
      pl: 'Przywróć automatyczną',
      it: 'Ripristina automatica',
      sk: 'Obnoviť automatickú',
      ja: '自動に戻す',
      ko: '자동으로 되돌리기',
      hi: 'स्वचालित पर लौटाएँ',
      nl: 'Automatisch herstellen',
      sv: 'Återställ till automatisk',
      vi: 'Khôi phục tự động',
      id: 'Kembalikan ke otomatis',
    }),
    mapUnavailable: t({
      ru: 'Карта сейчас недоступна',
      en: 'Map is unavailable right now',
      kk: 'Карта қазір қолжетімсіз',
      de: 'Die Karte ist gerade nicht verfügbar',
      fr: 'La carte est indisponible pour le moment',
      es: 'El mapa no está disponible ahora',
      pt: 'O mapa está indisponível de momento',
      tr: 'Harita şu anda kullanılamıyor',
      uk: 'Карта зараз недоступна',
      zh: '地图暂时不可用',
      ar: 'الخريطة غير متاحة حاليًا',
      pl: 'Mapa jest teraz niedostępna',
      it: 'La mappa non è disponibile al momento',
      sk: 'Mapa momentálne nie je dostupná',
      ja: '現在地図を表示できません',
      ko: '지금은 지도를 사용할 수 없습니다',
      hi: 'मानचित्र अभी उपलब्ध नहीं है',
      nl: 'De kaart is nu niet beschikbaar',
      sv: 'Kartan är inte tillgänglig just nu',
      vi: 'Bản đồ hiện không khả dụng',
      id: 'Peta sedang tidak tersedia',
    }),
    tilesNotConfigured: t({
      ru: 'Картографический сервер не настроен',
      en: 'Map tiles are not configured',
      kk: 'Карта сервері бапталмаған',
      de: 'Kartenkacheln sind nicht eingerichtet',
      fr: 'Les tuiles de carte ne sont pas configurées',
      es: 'Los mosaicos del mapa no están configurados',
      pt: 'Os mosaicos do mapa não estão configurados',
      tr: 'Harita katmanları yapılandırılmamış',
      uk: 'Картографічний сервер не налаштовано',
      zh: '尚未配置地图瓦片',
      ar: 'لم يتم إعداد مربعات الخريطة',
      pl: 'Kafelki mapy nie są skonfigurowane',
      it: 'I riquadri della mappa non sono configurati',
      sk: 'Mapové dlaždice nie sú nastavené',
      ja: '地図タイルが設定されていません',
      ko: '지도 타일이 구성되지 않았습니다',
      hi: 'मानचित्र टाइलें कॉन्फ़िगर नहीं हैं',
      nl: 'Kaarttegels zijn niet ingesteld',
      sv: 'Kartrutor är inte konfigurerade',
      vi: 'Chưa cấu hình ô bản đồ',
      id: 'Ubin peta belum dikonfigurasi',
    }),
    moveHint: t({
      ru: 'Перетащите метку или кликните по карте, чтобы переместить её.',
      en: 'Drag the pin or click the map to move it.',
      kk: 'Жылжыту үшін белгіні сүйреңіз немесе картаны басыңыз.',
      de: 'Ziehen Sie die Markierung oder klicken Sie auf die Karte, um sie zu verschieben.',
      fr: 'Faites glisser le repère ou cliquez sur la carte pour le déplacer.',
      es: 'Arrastra el marcador o haz clic en el mapa para moverlo.',
      pt: 'Arraste o marcador ou clique no mapa para o mover.',
      tr: 'Taşımak için işareti sürükleyin veya haritaya tıklayın.',
      uk: 'Перетягніть мітку або клацніть на карті, щоб перемістити її.',
      zh: '拖动标记或点击地图来移动位置。',
      ar: 'اسحب العلامة أو انقر على الخريطة لتحريكها.',
      pl: 'Przeciągnij pinezkę lub kliknij mapę, aby ją przesunąć.',
      it: 'Trascina il segnaposto o fai clic sulla mappa per spostarlo.',
      sk: 'Presuňte špendlík alebo kliknite do mapy.',
      ja: 'ピンをドラッグするか、地図をクリックして移動します。',
      ko: '핀을 끌거나 지도를 클릭해 옮기세요.',
      hi: 'इसे हिलाने के लिए पिन खींचें या मानचित्र पर क्लिक करें।',
      nl: 'Sleep de speld of klik op de kaart om hem te verplaatsen.',
      sv: 'Dra nålen eller klicka på kartan för att flytta den.',
      vi: 'Kéo ghim hoặc nhấp vào bản đồ để di chuyển.',
      id: 'Seret pin atau klik peta untuk memindahkannya.',
    }),
    placeHint: t({
      ru: 'Кликните по карте, чтобы отметить место покупки.',
      en: 'Click the map to place the point where this purchase was made.',
      kk: 'Сатып алу орнын белгілеу үшін картаны басыңыз.',
      de: 'Klicken Sie auf die Karte, um den Ort des Kaufs zu markieren.',
      fr: 'Cliquez sur la carte pour indiquer le lieu de l’achat.',
      es: 'Haz clic en el mapa para marcar dónde se hizo la compra.',
      pt: 'Clique no mapa para marcar onde foi feita a compra.',
      tr: 'Alışverişin yapıldığı yeri işaretlemek için haritaya tıklayın.',
      uk: 'Клацніть на карті, щоб позначити місце покупки.',
      zh: '点击地图，标记本次购买的地点。',
      ar: 'انقر على الخريطة لتحديد مكان الشراء.',
      pl: 'Kliknij mapę, aby zaznaczyć miejsce zakupu.',
      it: 'Fai clic sulla mappa per indicare dove è stato fatto l’acquisto.',
      sk: 'Kliknutím do mapy označte miesto nákupu.',
      ja: '地図をクリックして、購入した場所を指定します。',
      ko: '지도를 클릭해 구매한 장소를 표시하세요.',
      hi: 'खरीदारी की जगह चिह्नित करने के लिए मानचित्र पर क्लिक करें।',
      nl: 'Klik op de kaart om aan te geven waar de aankoop is gedaan.',
      sv: 'Klicka på kartan för att markera var köpet gjordes.',
      vi: 'Nhấp vào bản đồ để đánh dấu nơi mua hàng.',
      id: 'Klik peta untuk menandai tempat pembelian.',
    }),
    saveFailed: t({
      ru: 'Не удалось сохранить точку',
      en: 'Failed to save location',
      kk: 'Нүктені сақтау мүмкін болмады',
      de: 'Standort konnte nicht gespeichert werden',
      fr: 'Impossible d’enregistrer l’emplacement',
      es: 'No se pudo guardar la ubicación',
      pt: 'Não foi possível guardar a localização',
      tr: 'Konum kaydedilemedi',
      uk: 'Не вдалося зберегти точку',
      zh: '无法保存位置',
      ar: 'تعذر حفظ الموقع',
      pl: 'Nie udało się zapisać lokalizacji',
      it: 'Impossibile salvare la posizione',
      sk: 'Polohu sa nepodarilo uložiť',
      ja: '場所を保存できませんでした',
      ko: '위치를 저장하지 못했습니다',
      hi: 'स्थान सहेजा नहीं जा सका',
      nl: 'Locatie opslaan is mislukt',
      sv: 'Det gick inte att spara platsen',
      vi: 'Không thể lưu vị trí',
      id: 'Gagal menyimpan lokasi',
    }),
    resetFailed: t({
      ru: 'Не удалось вернуть автоматическую точку',
      en: 'Failed to reset location',
      kk: 'Автоматты нүктені қайтару мүмкін болмады',
      de: 'Standort konnte nicht zurückgesetzt werden',
      fr: 'Impossible de réinitialiser l’emplacement',
      es: 'No se pudo restablecer la ubicación',
      pt: 'Não foi possível repor a localização',
      tr: 'Konum sıfırlanamadı',
      uk: 'Не вдалося повернути автоматичну точку',
      zh: '无法恢复自动定位',
      ar: 'تعذرت إعادة تعيين الموقع',
      pl: 'Nie udało się przywrócić lokalizacji',
      it: 'Impossibile ripristinare la posizione',
      sk: 'Polohu sa nepodarilo obnoviť',
      ja: '場所をリセットできませんでした',
      ko: '위치를 되돌리지 못했습니다',
      hi: 'स्थान रीसेट नहीं हो सका',
      nl: 'Locatie herstellen is mislukt',
      sv: 'Det gick inte att återställa platsen',
      vi: 'Không thể khôi phục vị trí',
      id: 'Gagal mengembalikan lokasi',
    }),
    mapStyle: t({
      ru: 'Стиль карты',
      en: 'Map style',
      kk: 'Карта стилі',
      de: 'Kartenstil',
      fr: 'Style de carte',
      es: 'Estilo del mapa',
      pt: 'Estilo do mapa',
      tr: 'Harita stili',
      uk: 'Стиль карти',
      zh: '地图样式',
      ar: 'نمط الخريطة',
      pl: 'Styl mapy',
      it: 'Stile mappa',
      sk: 'Štýl mapy',
      ja: '地図のスタイル',
      ko: '지도 스타일',
      hi: 'मानचित्र शैली',
      nl: 'Kaartstijl',
      sv: 'Kartstil',
      vi: 'Kiểu bản đồ',
      id: 'Gaya peta',
    }),
    styleSaveFailed: t({
      ru: 'Не удалось сохранить стиль карты',
      en: 'Failed to save map style',
      kk: 'Карта стилін сақтау мүмкін болмады',
      de: 'Kartenstil konnte nicht gespeichert werden',
      fr: 'Impossible d’enregistrer le style de carte',
      es: 'No se pudo guardar el estilo del mapa',
      pt: 'Não foi possível guardar o estilo do mapa',
      tr: 'Harita stili kaydedilemedi',
      uk: 'Не вдалося зберегти стиль карти',
      zh: '无法保存地图样式',
      ar: 'تعذر حفظ نمط الخريطة',
      pl: 'Nie udało się zapisać stylu mapy',
      it: 'Impossibile salvare lo stile della mappa',
      sk: 'Štýl mapy sa nepodarilo uložiť',
      ja: '地図のスタイルを保存できませんでした',
      ko: '지도 스타일을 저장하지 못했습니다',
      hi: 'मानचित्र शैली सहेजी नहीं जा सकी',
      nl: 'Kaartstijl opslaan is mislukt',
      sv: 'Det gick inte att spara kartstilen',
      vi: 'Không thể lưu kiểu bản đồ',
      id: 'Gagal menyimpan gaya peta',
    }),
  },
} satisfies Dictionary;

export default content;
