import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'reportsPage',
  content: {
    errors: {
      loadReport: t({
        ru: 'Не удалось загрузить отчёт',
        en: 'Failed to load report',
        kk: 'Есепті жүктеу мүмкін болмады',
        de: 'Bericht konnte nicht geladen werden',
        fr: 'Impossible de charger le rapport',
        es: 'Error al cargar el informe',
        pt: 'Falha ao carregar o relatório',
        tr: 'Rapor yüklenemedi',
        uk: 'Не вдалося завантажити звіт',
        zh: '无法加载报告',
        ar: 'فشل تحميل التقرير',
        pl: 'Nie udało się załadować raportu',
        it: 'Impossibile caricare il report',
        sk: 'Nie udało się załadować raportu',
        ja: 'レポートの読み込みに失敗しました',
        ko: '보고서를 불러오지 못했습니다',
        hi: 'रिपोर्ट लोड करने में विफल',
        nl: 'Kon rapport niet laden',
        sv: 'Misslyckades med att ladda rapport',
        vi: 'Không thể tải báo cáo',
        id: 'Gagal memuat laporan',
      }),
    },
    labels: {
      // Page
      title: t({
        ru: 'Отчёты',
        en: 'Reports',
        kk: 'Есептер',
        de: 'Berichte',
        fr: 'Rapports',
        es: 'Informes',
        pt: 'Relatórios',
        tr: 'Raporlar',
        uk: 'Звіти',
        zh: '报告',
        ar: 'التقارير',
        pl: 'Raporty',
        it: 'Report',
        sk: 'Raporty',
        ja: 'レポート',
        ko: '보고서',
        hi: 'रिपोर्ट',
        nl: 'Rapporten',
        sv: 'Rapporter',
        vi: 'Báo cáo',
        id: 'Laporan',
      }),
      subtitle: t({
        ru: 'Создавайте финансовые отчёты и экспортируйте документы',
        en: 'Generate financial reports and export documents',
        kk: 'Қаржылық есептерді жасаңыз және құжаттарды экспорттаңыз',
        de: 'Erstellen Sie Finanzberichte und exportieren Sie Dokumente',
        fr: 'Générez des rapports financiers et exportez des documents',
        es: 'Genere informes financieros y exporte documentos',
        pt: 'Gere relatórios financeiros e exporte documentos',
        tr: 'Finansal raporlar oluşturun ve belgeler dışa aktarın',
        uk: 'Створюйте фінансові звіти та експортуйте документи',
        zh: '生成财务报告并导出文档',
        ar: 'أنشئ تقارير مالية وصدّر المستندات',
        pl: 'Generuj raporty finansowe i eksportuj dokumenty',
        it: 'Genera report finanziari ed esporta documenti',
        sk: 'Generuj raporty finansowe i eksportuj dokumenty',
        ja: '財務レポートを生成し、ドキュメントをエクスポートします',
        ko: '재무 보고서를 생성하고 문서를 내보냅니다',
        hi: 'वित्तीय रिपोर्ट बनाएं और दस्तावेज़ निर्यात करें',
        nl: 'Genereer financiële rapporten en exporteer documenten',
        sv: 'Generera finansiella rapporter och exportera dokument',
        vi: 'Tạo báo cáo tài chính và xuất tài liệu',
        id: 'Buat laporan keuangan dan ekspor dokumen',
      }),

      // Tabs
      tabTemplates: t({
        ru: 'Шаблоны',
        en: 'Templates',
        kk: 'Үлгілер',
        de: 'Vorlagen',
        fr: 'Modèles',
        es: 'Plantillas',
        pt: 'Modelos',
        tr: 'Şablonlar',
        uk: 'Шаблони',
        zh: '模板',
        ar: 'القوالب',
        pl: 'Szablony',
        it: 'Modelli',
        sk: 'Szablony',
        ja: 'テンプレート',
        ko: '템플릿',
        hi: 'टेम्पलेट',
        nl: 'Sjablonen',
        sv: 'Mallar',
        vi: 'Mẫu',
        id: 'Template',
      }),
      tabHistory: t({
        ru: 'История',
        en: 'History',
        kk: 'Тарих',
        de: 'Verlauf',
        fr: 'Historique',
        es: 'Historial',
        pt: 'Histórico',
        tr: 'Geçmiş',
        uk: 'Історія',
        zh: '历史',
        ar: 'السجل',
        pl: 'Historia',
        it: 'Cronologia',
        sk: 'Historia',
        ja: '履歴',
        ko: '기록',
        hi: 'इतिहास',
        nl: 'Geschiedenis',
        sv: 'Historik',
        vi: 'Lịch sử',
        id: 'Riwayat',
      }),

      // Templates
      templatePnlName: t({
        ru: 'Прибыли и убытки (P&L)',
        en: 'Profit & Loss (P&L)',
        kk: 'Пайда мен шығын (P&L)',
        de: 'Gewinn und Verlust (G&V)',
        fr: 'Profits et pertes (P&L)',
        es: 'Ganancias y pérdidas (P&L)',
        pt: 'Lucros e perdas (P&L)',
        tr: 'Kâr ve Zarar (P&L)',
        uk: 'Прибутки та збитки (P&L)',
        zh: '损益表 (P&L)',
        ar: 'الأرباح والخسائر (P&L)',
        pl: 'Zyski i straty (P&L)',
        it: 'Profitti e perdite (P&L)',
        sk: 'Zyski i straty (P&L)',
        ja: '損益計算書 (P&L)',
        ko: '손익 계산서 (P&L)',
        hi: 'लाभ और हानि (P&L)',
        nl: 'Winst en verlies (W&V)',
        sv: 'Resultaträkning (P&L)',
        vi: 'Lãi và lỗ (P&L)',
        id: 'Laba Rugi (P&L)',
      }),
      templatePnlDescription: t({
        ru: 'Сводка доходов и расходов с чистой прибылью за период',
        en: 'Income and expenses summary with net profit for a period',
        kk: 'Кезеңдегі таза пайдамен кіріс пен шығыс қорытындысы',
        de: 'Zusammenfassung der Einnahmen und Ausgaben mit Nettogewinn für einen Zeitraum',
        fr: 'Résumé des revenus et dépenses avec bénéfice net pour une période',
        es: 'Resumen de ingresos y gastos con beneficio neto para un período',
        pt: 'Resumo de receitas e despesas com lucro líquido para um período',
        tr: 'Bir dönem için net kârla birlikte gelir ve gider özeti',
        uk: 'Зведення доходів та витрат з чистим прибутком за період',
        zh: '期间净利润的收入和支出摘要',
        ar: 'ملخص الإيرادات والمصروفات مع صافي الربح لفترة',
        pl: 'Podsumowanie przychodów i wydatków z zyskiem netto za okres',
        it: 'Riepilogo di entrate e uscite con utile netto per un periodo',
        sk: 'Podsumowanie przychodów i wydatków z zyskiem netto za okres',
        ja: '期間の純利益を含む収入と支出のまとめ',
        ko: '기간 순이익이 포함된 수입 및 지출 요약',
        hi: 'अवधि के लिए शुद्ध लाभ सहित आय और व्यय सारांश',
        nl: 'Overzicht van inkomsten en uitgaven met nettowinst voor een periode',
        sv: 'Sammanfattning av intäkter och kostnader med nettovinst för en period',
        vi: 'Tóm tắt thu nhập và chi phí với lợi nhuận ròng trong kỳ',
        id: 'Ringkasan pendapatan dan pengeluaran dengan laba bersih untuk suatu periode',
      }),
      templateBalanceName: t({
        ru: 'Баланс',
        en: 'Balance Sheet',
        kk: 'Баланс парағы',
        de: 'Bilanz',
        fr: 'Bilan',
        es: 'Balance General',
        pt: 'Balanço Patrimonial',
        tr: 'Bilanço',
        uk: 'Баланс',
        zh: '资产负债表',
        ar: 'الميزانية العمومية',
        pl: 'Bilans',
        it: 'Stato Patrimoniale',
        sk: 'Bilans',
        ja: '貸借対照表',
        ko: '대차 대조표',
        hi: 'बैलेंस शीट',
        nl: 'Balans',
        sv: 'Balansräkning',
        vi: 'Bảng cân đối kế toán',
        id: 'Neraca',
      }),
      templateBalanceDescription: t({
        ru: 'Снимок активов, обязательств и капитала',
        en: 'Assets, liabilities and equity snapshot',
        kk: 'Активтер, міндеттемелер және капитал суреті',
        de: 'Momentaufnahme von Vermögenswerten, Verbindlichkeiten und Eigenkapital',
        fr: 'Instantané des actifs, passifs et capitaux propres',
        es: 'Instantánea de activos, pasivos y patrimonio',
        pt: 'Instantâneo de ativos, passivos e patrimônio líquido',
        tr: 'Varlıklar, yükümlülükler ve özkaynak anlık görüntüsü',
        uk: "Знімок активів, зобов'язань та капіталу",
        zh: '资产、负债和权益快照',
        ar: 'لقطة للأصول والخصوم وحقوق الملكية',
        pl: 'Zdjęcie aktywów, zobowiązań i kapitału własnego',
        it: 'Istantanea di attività, passività e patrimonio netto',
        sk: 'Zdjęcie aktywów, zobowiązań i kapitału własnego',
        ja: '資産、負債、資本のスナップショット',
        ko: '자산, 부채 및 자본 스냅샷',
        hi: 'संपत्ति, देनदारियों और इक्विटी का स्नैपशॉट',
        nl: 'Momentopname van activa, passiva en eigen vermogen',
        sv: 'Ögonblicksbild av tillgångar, skulder och eget kapital',
        vi: 'Ảnh chụp tài sản, nợ phải trả và vốn chủ sở hữu',
        id: 'Gambaran aset, kewajiban, dan ekuitas',
      }),
      templateCashFlowName: t({
        ru: 'Отчёт о движении денежных средств',
        en: 'Cash Flow Statement',
        kk: 'Ақша ағыны туралы есеп',
        de: 'Kapitalflussrechnung',
        fr: 'Tableau des flux de trésorerie',
        es: 'Estado de Flujo de Efectivo',
        pt: 'Demonstração de Fluxo de Caixa',
        tr: 'Nakit Akış Tablosu',
        uk: 'Звіт про рух грошових коштів',
        zh: '现金流量表',
        ar: 'قائمة التدفقات النقدية',
        pl: 'Rachunek przepływów pieniężnych',
        it: 'Rendiconto Finanziario',
        sk: 'Rachunek przepływów pieniężnych',
        ja: 'キャッシュフロー計算書',
        ko: '현금 흐름표',
        hi: 'नकदी प्रवाह विवरण',
        nl: 'Kasstroomoverzicht',
        sv: 'Kassaflödesanalys',
        vi: 'Báo cáo lưu chuyển tiền tệ',
        id: 'Laporan Arus Kas',
      }),
      templateCashFlowDescription: t({
        ru: 'Притоки и оттоки денежных средств за период',
        en: 'Cash inflows and outflows over a period',
        kk: 'Кезеңдегі ақша ағындары мен кетулері',
        de: 'Mittelzuflüsse und -abflüsse über einen Zeitraum',
        fr: 'Entrées et sorties de trésorerie sur une période',
        es: 'Entradas y salidas de efectivo durante un período',
        pt: 'Entradas e saídas de caixa ao longo de um período',
        tr: 'Bir dönem boyunca nakit girişleri ve çıkışları',
        uk: 'Надходження та відтоки грошових коштів за період',
        zh: '期间现金流入和流出',
        ar: 'التدفقات النقدية الداخلة والخارجة خلال فترة',
        pl: 'Wpływy i wydatki pieniężne w danym okresie',
        it: 'Flussi di cassa in entrata e in uscita in un periodo',
        sk: 'Wpływy i wydatki pieniężne w danym okresie',
        ja: '期間中の現金流入と流出',
        ko: '기간 동안의 현금 유입 및 유출',
        hi: 'अवधि में नकदी प्रवाह और बहिर्वाह',
        nl: 'Kasinstroom en -uitstroom over een periode',
        sv: 'Kassainflöden och -utflöden under en period',
        vi: 'Dòng tiền vào và ra trong kỳ',
        id: 'Arus masuk dan keluar kas dalam suatu periode',
      }),
      templateExpenseByCategoryName: t({
        ru: 'Расходы по категориям',
        en: 'Expense by Category',
        kk: 'Санаттар бойынша шығыстар',
        de: 'Ausgaben nach Kategorie',
        fr: 'Dépenses par catégorie',
        es: 'Gastos por categoría',
        pt: 'Despesas por categoria',
        tr: 'Kategoriye göre gider',
        uk: 'Витрати за категоріями',
        zh: '按类别分列支出',
        ar: 'المصروفات حسب الفئة',
        pl: 'Wydatki według kategorii',
        it: 'Spese per categoria',
        sk: 'Wydatki według kategorii',
        ja: 'カテゴリ別支出',
        ko: '카테고리별 지출',
        hi: 'श्रेणी के अनुसार व्यय',
        nl: 'Uitgaven per categorie',
        sv: 'Utgifter per kategori',
        vi: 'Chi phí theo danh mục',
        id: 'Pengeluaran per Kategori',
      }),
      templateExpenseByCategoryDescription: t({
        ru: 'Разбивка расходов по категориям с итогами',
        en: 'Breakdown of expenses by category with totals',
        kk: 'Жалпы сомалармен санаттар бойынша шығыстардың бөлінуі',
        de: 'Aufschlüsselung der Ausgaben nach Kategorien mit Gesamtsummen',
        fr: 'Ventilation des dépenses par catégorie avec totaux',
        es: 'Desglose de gastos por categoría con totales',
        pt: 'Detalhamento de despesas por categoria com totais',
        tr: 'Toplamlarla birlikte kategoriye göre gider dökümü',
        uk: 'Розбивка витрат за категоріями із підсумками',
        zh: '按类别分列支出明细及合计',
        ar: 'تفصيل المصروفات حسب الفئة مع الإجماليات',
        pl: 'Podział wydatków według kategorii z sumami',
        it: 'Ripartizione delle spese per categoria con totali',
        sk: 'Podział wydatków według kategorii z sumami',
        ja: '合計付きカテゴリ別支出の内訳',
        ko: '합계가 포함된 카테고리별 지출 내역',
        hi: 'योग सहित श्रेणी के अनुसार व्यय का विवरण',
        nl: 'Uitsplitsing van uitgaven per categorie met totalen',
        sv: 'Uppdelning av utgifter per kategori med totaler',
        vi: 'Phân tích chi phí theo danh mục với tổng cộng',
        id: 'Rincian pengeluaran per kategori dengan total',
      }),

      templateTransactionRegisterName: t({
        ru: 'Реестр операций',
        en: 'Transaction Register',
        kk: 'Операциялар тізілімі',
        de: 'Transaktionsjournal',
        fr: 'Registre des transactions',
        es: 'Registro de transacciones',
        pt: 'Registo de transações',
        tr: 'İşlem kaydı',
        uk: 'Реєстр операцій',
        zh: '交易明细表',
        ar: 'سجل المعاملات',
        pl: 'Rejestr transakcji',
        it: 'Registro delle transazioni',
        sk: 'Register transakcií',
        ja: '取引明細',
        ko: '거래 내역서',
        hi: 'लेन-देन रजिस्टर',
        nl: 'Transactieregister',
        sv: 'Transaktionsregister',
        vi: 'Sổ giao dịch',
        id: 'Register transaksi',
      }),
      templateTransactionRegisterDescription: t({
        ru: 'Все операции за период с суммой в валюте воркспейса и исходной',
        en: 'Every transaction in the period with converted and original amounts',
        kk: 'Кезеңдегі барлық операциялар: аударылған және бастапқы сомамен',
        de: 'Alle Transaktionen des Zeitraums mit umgerechnetem und Originalbetrag',
        fr: 'Toutes les transactions de la période avec montants convertis et d’origine',
        es: 'Todas las transacciones del período con importes convertidos y originales',
        pt: 'Todas as transações do período com valores convertidos e originais',
        tr: 'Dönemdeki tüm işlemler, çevrilmiş ve orijinal tutarlarla',
        uk: 'Усі операції за період із конвертованою та початковою сумою',
        zh: '期间内所有交易，含折算金额与原始金额',
        ar: 'جميع المعاملات في الفترة بالمبالغ المحوّلة والأصلية',
        pl: 'Wszystkie transakcje z okresu z kwotą przeliczoną i oryginalną',
        it: 'Tutte le transazioni del periodo con importi convertiti e originali',
        sk: 'Všetky transakcie za obdobie s prepočítanou a pôvodnou sumou',
        ja: '期間内の全取引（換算額と元の金額）',
        ko: '기간 내 모든 거래와 환산 금액 및 원래 금액',
        hi: 'अवधि के सभी लेन-देन, परिवर्तित और मूल राशि सहित',
        nl: 'Alle transacties in de periode met omgerekend en oorspronkelijk bedrag',
        sv: 'Alla transaktioner i perioden med omräknat och ursprungligt belopp',
        vi: 'Mọi giao dịch trong kỳ kèm số tiền quy đổi và gốc',
        id: 'Semua transaksi dalam periode dengan jumlah terkonversi dan asli',
      }),
      templateMonthlySummaryName: t({
        ru: 'Сводка за период',
        en: 'Monthly Summary',
        kk: 'Кезең қорытындысы',
        de: 'Periodenübersicht',
        fr: 'Synthèse de la période',
        es: 'Resumen del período',
        pt: 'Resumo do período',
        tr: 'Dönem özeti',
        uk: 'Зведення за період',
        zh: '期间汇总',
        ar: 'ملخص الفترة',
        pl: 'Podsumowanie okresu',
        it: 'Riepilogo del periodo',
        sk: 'Súhrn obdobia',
        ja: '期間サマリー',
        ko: '기간 요약',
        hi: 'अवधि सारांश',
        nl: 'Periodeoverzicht',
        sv: 'Periodsammanfattning',
        vi: 'Tóm tắt kỳ',
        id: 'Ringkasan periode',
      }),
      templateMonthlySummaryDescription: t({
        ru: 'Доходы, расходы, норма сбережений и топ категорий на одной странице',
        en: 'Income, expenses, savings rate and top categories on one page',
        kk: 'Кірістер, шығыстар, жинақ нормасы және үздік санаттар бір бетте',
        de: 'Einnahmen, Ausgaben, Sparquote und Top-Kategorien auf einer Seite',
        fr: 'Revenus, dépenses, taux d’épargne et principales catégories sur une page',
        es: 'Ingresos, gastos, tasa de ahorro y categorías principales en una página',
        pt: 'Receitas, despesas, taxa de poupança e principais categorias numa página',
        tr: 'Gelir, gider, tasarruf oranı ve en büyük kategoriler tek sayfada',
        uk: 'Доходи, витрати, норма заощаджень і топ категорій на одній сторінці',
        zh: '收入、支出、储蓄率与主要类别，一页呈现',
        ar: 'الإيرادات والمصروفات ومعدل الادخار وأهم الفئات في صفحة واحدة',
        pl: 'Przychody, wydatki, stopa oszczędności i główne kategorie na jednej stronie',
        it: 'Entrate, uscite, tasso di risparmio e categorie principali in una pagina',
        sk: 'Príjmy, výdavky, miera úspor a hlavné kategórie na jednej strane',
        ja: '収入・支出・貯蓄率・主要カテゴリを1ページに',
        ko: '수입, 지출, 저축률, 주요 카테고리를 한 페이지에',
        hi: 'आय, व्यय, बचत दर और शीर्ष श्रेणियाँ एक पृष्ठ पर',
        nl: 'Inkomsten, uitgaven, spaarquote en topcategorieën op één pagina',
        sv: 'Intäkter, utgifter, sparkvot och toppkategorier på en sida',
        vi: 'Thu, chi, tỷ lệ tiết kiệm và nhóm chi lớn nhất trên một trang',
        id: 'Pemasukan, pengeluaran, rasio tabungan, dan kategori teratas dalam satu halaman',
      }),

      tabSchedules: t({
        ru: 'Расписания',
        en: 'Schedules',
        kk: 'Кестелер',
        de: 'Zeitpläne',
        fr: 'Planifications',
        es: 'Programaciones',
        pt: 'Agendamentos',
        tr: 'Zamanlamalar',
        uk: 'Розклади',
        zh: '定时任务',
        ar: 'الجدولة',
        pl: 'Harmonogramy',
        it: 'Pianificazioni',
        sk: 'Plány',
        ja: 'スケジュール',
        ko: '예약',
        hi: 'शेड्यूल',
        nl: 'Planningen',
        sv: 'Scheman',
        vi: 'Lịch',
        id: 'Jadwal',
      }),
      scheduleNewTitle: t({
        ru: 'Запланировать отчёт',
        en: 'Schedule a report',
        kk: 'Есепті жоспарлау',
        de: 'Bericht planen',
        fr: 'Planifier un rapport',
        es: 'Programar un informe',
        pt: 'Agendar um relatório',
        tr: 'Rapor zamanla',
        uk: 'Запланувати звіт',
        zh: '安排报表',
        ar: 'جدولة تقرير',
        pl: 'Zaplanuj raport',
        it: 'Pianifica un report',
        sk: 'Naplánovať report',
        ja: 'レポートを予約',
        ko: '보고서 예약',
        hi: 'रिपोर्ट शेड्यूल करें',
        nl: 'Rapport plannen',
        sv: 'Schemalägg rapport',
        vi: 'Lên lịch báo cáo',
        id: 'Jadwalkan laporan',
      }),
      scheduleNewSubtitle: t({
        ru: 'Приходит на почту в 06:00 UTC и охватывает последний завершённый период',
        en: 'Delivered by email at 06:00 UTC, covering the last completed period',
        kk: '06:00 UTC-те поштаға келеді, соңғы аяқталған кезеңді қамтиды',
        de: 'Kommt per E-Mail um 06:00 UTC und deckt die letzte abgeschlossene Periode ab',
        fr: 'Envoyé par e-mail à 06:00 UTC, couvrant la dernière période achevée',
        es: 'Se envía por correo a las 06:00 UTC y cubre el último período completo',
        pt: 'Enviado por email às 06:00 UTC, cobrindo o último período completo',
        tr: '06:00 UTC’de e-posta ile gelir ve son tamamlanan dönemi kapsar',
        uk: 'Надходить на пошту о 06:00 UTC і охоплює останній завершений період',
        zh: '于 UTC 06:00 通过邮件发送，覆盖最近一个完整周期',
        ar: 'يُرسل بالبريد عند 06:00 UTC ويغطي آخر فترة مكتملة',
        pl: 'Wysyłany e-mailem o 06:00 UTC i obejmuje ostatni zakończony okres',
        it: 'Inviato via email alle 06:00 UTC, copre l’ultimo periodo concluso',
        sk: 'Odosiela sa e-mailom o 06:00 UTC a pokrýva posledné ukončené obdobie',
        ja: 'UTC 06:00 にメールで送信され、直前の完了期間を対象とします',
        ko: 'UTC 06:00에 이메일로 발송되며 마지막으로 완료된 기간을 다룹니다',
        hi: '06:00 UTC पर ईमेल से भेजा जाता है, अंतिम पूर्ण अवधि को कवर करते हुए',
        nl: 'Wordt om 06:00 UTC gemaild en dekt de laatst afgeronde periode',
        sv: 'Skickas via e-post 06:00 UTC och täcker den senast avslutade perioden',
        vi: 'Gửi qua email lúc 06:00 UTC, bao trùm kỳ hoàn tất gần nhất',
        id: 'Dikirim lewat email pukul 06.00 UTC, mencakup periode lengkap terakhir',
      }),
      scheduleTemplate: t({
        ru: 'Отчёт',
        en: 'Report',
        kk: 'Есеп',
        de: 'Bericht',
        fr: 'Rapport',
        es: 'Informe',
        pt: 'Relatório',
        tr: 'Rapor',
        uk: 'Звіт',
        zh: '报表',
        ar: 'التقرير',
        pl: 'Raport',
        it: 'Report',
        sk: 'Report',
        ja: 'レポート',
        ko: '보고서',
        hi: 'रिपोर्ट',
        nl: 'Rapport',
        sv: 'Rapport',
        vi: 'Báo cáo',
        id: 'Laporan',
      }),
      scheduleCadence: t({
        ru: 'Периодичность',
        en: 'Frequency',
        kk: 'Кезеңділік',
        de: 'Häufigkeit',
        fr: 'Fréquence',
        es: 'Frecuencia',
        pt: 'Frequência',
        tr: 'Sıklık',
        uk: 'Періодичність',
        zh: '频率',
        ar: 'التكرار',
        pl: 'Częstotliwość',
        it: 'Frequenza',
        sk: 'Frekvencia',
        ja: '頻度',
        ko: '주기',
        hi: 'आवृत्ति',
        nl: 'Frequentie',
        sv: 'Frekvens',
        vi: 'Tần suất',
        id: 'Frekuensi',
      }),
      cadence_daily: t({
        ru: 'Ежедневно',
        en: 'Daily',
        kk: 'Күн сайын',
        de: 'Täglich',
        fr: 'Quotidien',
        es: 'Diario',
        pt: 'Diário',
        tr: 'Günlük',
        uk: 'Щодня',
        zh: '每日',
        ar: 'يومي',
        pl: 'Codziennie',
        it: 'Giornaliero',
        sk: 'Denne',
        ja: '毎日',
        ko: '매일',
        hi: 'दैनिक',
        nl: 'Dagelijks',
        sv: 'Dagligen',
        vi: 'Hằng ngày',
        id: 'Harian',
      }),
      cadence_weekly: t({
        ru: 'Еженедельно',
        en: 'Weekly',
        kk: 'Апта сайын',
        de: 'Wöchentlich',
        fr: 'Hebdomadaire',
        es: 'Semanal',
        pt: 'Semanal',
        tr: 'Haftalık',
        uk: 'Щотижня',
        zh: '每周',
        ar: 'أسبوعي',
        pl: 'Co tydzień',
        it: 'Settimanale',
        sk: 'Týždenne',
        ja: '毎週',
        ko: '매주',
        hi: 'साप्ताहिक',
        nl: 'Wekelijks',
        sv: 'Varje vecka',
        vi: 'Hằng tuần',
        id: 'Mingguan',
      }),
      cadence_monthly: t({
        ru: 'Ежемесячно',
        en: 'Monthly',
        kk: 'Ай сайын',
        de: 'Monatlich',
        fr: 'Mensuel',
        es: 'Mensual',
        pt: 'Mensal',
        tr: 'Aylık',
        uk: 'Щомісяця',
        zh: '每月',
        ar: 'شهري',
        pl: 'Co miesiąc',
        it: 'Mensile',
        sk: 'Mesačne',
        ja: '毎月',
        ko: '매월',
        hi: 'मासिक',
        nl: 'Maandelijks',
        sv: 'Varje månad',
        vi: 'Hằng tháng',
        id: 'Bulanan',
      }),
      scheduleRecipients: t({
        ru: 'Получатели',
        en: 'Recipients',
        kk: 'Алушылар',
        de: 'Empfänger',
        fr: 'Destinataires',
        es: 'Destinatarios',
        pt: 'Destinatários',
        tr: 'Alıcılar',
        uk: 'Одержувачі',
        zh: '收件人',
        ar: 'المستلمون',
        pl: 'Odbiorcy',
        it: 'Destinatari',
        sk: 'Príjemcovia',
        ja: '宛先',
        ko: '수신자',
        hi: 'प्राप्तकर्ता',
        nl: 'Ontvangers',
        sv: 'Mottagare',
        vi: 'Người nhận',
        id: 'Penerima',
      }),
      scheduleCreate: t({
        ru: 'Создать расписание',
        en: 'Create schedule',
        kk: 'Кесте құру',
        de: 'Zeitplan erstellen',
        fr: 'Créer la planification',
        es: 'Crear programación',
        pt: 'Criar agendamento',
        tr: 'Zamanlama oluştur',
        uk: 'Створити розклад',
        zh: '创建定时任务',
        ar: 'إنشاء جدولة',
        pl: 'Utwórz harmonogram',
        it: 'Crea pianificazione',
        sk: 'Vytvoriť plán',
        ja: 'スケジュールを作成',
        ko: '예약 만들기',
        hi: 'शेड्यूल बनाएँ',
        nl: 'Planning maken',
        sv: 'Skapa schema',
        vi: 'Tạo lịch',
        id: 'Buat jadwal',
      }),
      scheduleEmpty: t({
        ru: 'Пока нет запланированных отчётов',
        en: 'No scheduled reports yet',
        kk: 'Әзірге жоспарланған есеп жоқ',
        de: 'Noch keine geplanten Berichte',
        fr: 'Aucun rapport planifié pour l’instant',
        es: 'Aún no hay informes programados',
        pt: 'Ainda não há relatórios agendados',
        tr: 'Henüz zamanlanmış rapor yok',
        uk: 'Поки немає запланованих звітів',
        zh: '还没有定时报表',
        ar: 'لا توجد تقارير مجدولة بعد',
        pl: 'Brak zaplanowanych raportów',
        it: 'Nessun report pianificato',
        sk: 'Zatiaľ žiadne plánované reporty',
        ja: '予約されたレポートはありません',
        ko: '예약된 보고서가 없습니다',
        hi: 'अभी कोई शेड्यूल्ड रिपोर्ट नहीं',
        nl: 'Nog geen geplande rapporten',
        sv: 'Inga schemalagda rapporter än',
        vi: 'Chưa có báo cáo theo lịch',
        id: 'Belum ada laporan terjadwal',
      }),
      scheduleNextRun: t({
        ru: 'следующий запуск',
        en: 'next run',
        kk: 'келесі іске қосу',
        de: 'nächster Lauf',
        fr: 'prochaine exécution',
        es: 'próxima ejecución',
        pt: 'próxima execução',
        tr: 'sonraki çalışma',
        uk: 'наступний запуск',
        zh: '下次运行',
        ar: 'التشغيل التالي',
        pl: 'następne uruchomienie',
        it: 'prossima esecuzione',
        sk: 'ďalšie spustenie',
        ja: '次回実行',
        ko: '다음 실행',
        hi: 'अगला रन',
        nl: 'volgende uitvoering',
        sv: 'nästa körning',
        vi: 'lần chạy kế tiếp',
        id: 'jalan berikutnya',
      }),
      scheduleActive: t({
        ru: 'Активно',
        en: 'Active',
        kk: 'Белсенді',
        de: 'Aktiv',
        fr: 'Actif',
        es: 'Activo',
        pt: 'Ativo',
        tr: 'Etkin',
        uk: 'Активно',
        zh: '启用',
        ar: 'نشط',
        pl: 'Aktywne',
        it: 'Attivo',
        sk: 'Aktívne',
        ja: '有効',
        ko: '활성',
        hi: 'सक्रिय',
        nl: 'Actief',
        sv: 'Aktiv',
        vi: 'Đang bật',
        id: 'Aktif',
      }),
      scheduleDelete: t({
        ru: 'Удалить расписание',
        en: 'Delete schedule',
        kk: 'Кестені жою',
        de: 'Zeitplan löschen',
        fr: 'Supprimer la planification',
        es: 'Eliminar programación',
        pt: 'Eliminar agendamento',
        tr: 'Zamanlamayı sil',
        uk: 'Видалити розклад',
        zh: '删除定时任务',
        ar: 'حذف الجدولة',
        pl: 'Usuń harmonogram',
        it: 'Elimina pianificazione',
        sk: 'Odstrániť plán',
        ja: 'スケジュールを削除',
        ko: '예약 삭제',
        hi: 'शेड्यूल हटाएँ',
        nl: 'Planning verwijderen',
        sv: 'Ta bort schema',
        vi: 'Xoá lịch',
        id: 'Hapus jadwal',
      }),
      scheduleNeedsRecipient: t({
        ru: 'Укажите хотя бы один email',
        en: 'Add at least one email address',
        kk: 'Кемінде бір email көрсетіңіз',
        de: 'Mindestens eine E-Mail-Adresse angeben',
        fr: 'Ajoutez au moins une adresse e-mail',
        es: 'Añade al menos una dirección de correo',
        pt: 'Adicione pelo menos um endereço de email',
        tr: 'En az bir e-posta adresi ekleyin',
        uk: 'Вкажіть хоча б один email',
        zh: '请至少填写一个邮箱地址',
        ar: 'أضف عنوان بريد إلكتروني واحدًا على الأقل',
        pl: 'Podaj co najmniej jeden adres e-mail',
        it: 'Aggiungi almeno un indirizzo email',
        sk: 'Zadajte aspoň jednu e-mailovú adresu',
        ja: 'メールアドレスを1つ以上入力してください',
        ko: '이메일 주소를 하나 이상 입력하세요',
        hi: 'कम से कम एक ईमेल पता जोड़ें',
        nl: 'Voeg minstens één e-mailadres toe',
        sv: 'Ange minst en e-postadress',
        vi: 'Nhập ít nhất một địa chỉ email',
        id: 'Tambahkan setidaknya satu alamat email',
      }),
      scheduleCreateFailed: t({
        ru: 'Не удалось сохранить расписание',
        en: 'Could not save the schedule',
        kk: 'Кестені сақтау мүмкін болмады',
        de: 'Zeitplan konnte nicht gespeichert werden',
        fr: 'Impossible d’enregistrer la planification',
        es: 'No se pudo guardar la programación',
        pt: 'Não foi possível guardar o agendamento',
        tr: 'Zamanlama kaydedilemedi',
        uk: 'Не вдалося зберегти розклад',
        zh: '无法保存定时任务',
        ar: 'تعذّر حفظ الجدولة',
        pl: 'Nie udało się zapisać harmonogramu',
        it: 'Impossibile salvare la pianificazione',
        sk: 'Plán sa nepodarilo uložiť',
        ja: 'スケジュールを保存できませんでした',
        ko: '예약을 저장하지 못했습니다',
        hi: 'शेड्यूल सहेजा नहीं जा सका',
        nl: 'Kon de planning niet opslaan',
        sv: 'Kunde inte spara schemat',
        vi: 'Không thể lưu lịch',
        id: 'Tidak dapat menyimpan jadwal',
      }),

      // Generator
      preview: t({
        ru: 'Предпросмотр',
        en: 'Preview',
        kk: 'Алдын ала қарау',
        de: 'Vorschau',
        fr: 'Aperçu',
        es: 'Vista previa',
        pt: 'Pré-visualizar',
        tr: 'Önizleme',
        uk: 'Попередній перегляд',
        zh: '预览',
        ar: 'معاينة',
        pl: 'Podgląd',
        it: 'Anteprima',
        sk: 'Náhľad',
        ja: 'プレビュー',
        ko: '미리 보기',
        hi: 'पूर्वावलोकन',
        nl: 'Voorbeeld',
        sv: 'Förhandsgranska',
        vi: 'Xem trước',
        id: 'Pratinjau',
      }),
      previewLoading: t({
        ru: 'Строим предпросмотр…',
        en: 'Building preview…',
        kk: 'Алдын ала қарау дайындалуда…',
        de: 'Vorschau wird erstellt…',
        fr: 'Création de l’aperçu…',
        es: 'Generando vista previa…',
        pt: 'A criar pré-visualização…',
        tr: 'Önizleme hazırlanıyor…',
        uk: 'Готуємо перегляд…',
        zh: '正在生成预览…',
        ar: 'جارٍ إنشاء المعاينة…',
        pl: 'Tworzenie podglądu…',
        it: 'Creazione anteprima…',
        sk: 'Vytvára sa náhľad…',
        ja: 'プレビューを作成中…',
        ko: '미리 보기 생성 중…',
        hi: 'पूर्वावलोकन बन रहा है…',
        nl: 'Voorbeeld maken…',
        sv: 'Skapar förhandsvisning…',
        vi: 'Đang tạo bản xem trước…',
        id: 'Membuat pratinjau…',
      }),
      previewEmpty: t({
        ru: 'Нет данных за этот период и фильтр',
        en: 'No data for this period and filter',
        kk: 'Осы кезең мен сүзгі бойынша дерек жоқ',
        de: 'Keine Daten für diesen Zeitraum und Filter',
        fr: 'Aucune donnée pour cette période et ce filtre',
        es: 'Sin datos para este período y filtro',
        pt: 'Sem dados para este período e filtro',
        tr: 'Bu dönem ve filtre için veri yok',
        uk: 'Немає даних за цей період і фільтр',
        zh: '此期间与筛选条件下没有数据',
        ar: 'لا توجد بيانات لهذه الفترة وهذا المرشّح',
        pl: 'Brak danych dla tego okresu i filtra',
        it: 'Nessun dato per questo periodo e filtro',
        sk: 'Žiadne údaje pre toto obdobie a filter',
        ja: 'この期間・条件のデータはありません',
        ko: '이 기간과 필터에 해당하는 데이터가 없습니다',
        hi: 'इस अवधि और फ़िल्टर के लिए कोई डेटा नहीं',
        nl: 'Geen gegevens voor deze periode en filter',
        sv: 'Inga data för denna period och filter',
        vi: 'Không có dữ liệu cho kỳ và bộ lọc này',
        id: 'Tidak ada data untuk periode dan filter ini',
      }),
      previewTruncated: t({
        ru: 'В предпросмотре только первые строки — в файле будет всё',
        en: 'Preview shows the first rows; the file contains everything.',
        kk: 'Алдын ала қарауда алғашқы жолдар ғана — файлда бәрі болады',
        de: 'Die Vorschau zeigt nur die ersten Zeilen; die Datei enthält alles.',
        fr: 'L’aperçu ne montre que les premières lignes ; le fichier contient tout.',
        es: 'La vista previa muestra las primeras filas; el archivo contiene todo.',
        pt: 'A pré-visualização mostra as primeiras linhas; o ficheiro contém tudo.',
        tr: 'Önizleme yalnızca ilk satırları gösterir; dosyada tümü yer alır.',
        uk: 'У перегляді лише перші рядки — у файлі буде все',
        zh: '预览仅显示前几行，文件包含全部内容。',
        ar: 'تعرض المعاينة الصفوف الأولى فقط؛ يحتوي الملف على كل شيء.',
        pl: 'Podgląd pokazuje pierwsze wiersze; plik zawiera wszystko.',
        it: 'L’anteprima mostra solo le prime righe; il file contiene tutto.',
        sk: 'Náhľad zobrazuje len prvé riadky; súbor obsahuje všetko.',
        ja: 'プレビューは先頭の行のみです。ファイルにはすべて含まれます。',
        ko: '미리 보기는 처음 몇 행만 표시하며 파일에는 전체가 담깁니다.',
        hi: 'पूर्वावलोकन में केवल पहली पंक्तियाँ हैं; फ़ाइल में सब कुछ होगा।',
        nl: 'Het voorbeeld toont de eerste rijen; het bestand bevat alles.',
        sv: 'Förhandsvisningen visar de första raderna; filen innehåller allt.',
        vi: 'Bản xem trước chỉ hiện những dòng đầu; tệp chứa toàn bộ.',
        id: 'Pratinjau menampilkan baris pertama; file berisi semuanya.',
      }),
      previewFailed: t({
        ru: 'Не удалось построить предпросмотр',
        en: 'Could not build the preview',
        kk: 'Алдын ала қарауды жасау мүмкін болмады',
        de: 'Vorschau konnte nicht erstellt werden',
        fr: 'Impossible de créer l’aperçu',
        es: 'No se pudo generar la vista previa',
        pt: 'Não foi possível criar a pré-visualização',
        tr: 'Önizleme oluşturulamadı',
        uk: 'Не вдалося побудувати перегляд',
        zh: '无法生成预览',
        ar: 'تعذّر إنشاء المعاينة',
        pl: 'Nie udało się utworzyć podglądu',
        it: 'Impossibile creare l’anteprima',
        sk: 'Náhľad sa nepodarilo vytvoriť',
        ja: 'プレビューを作成できませんでした',
        ko: '미리 보기를 만들지 못했습니다',
        hi: 'पूर्वावलोकन नहीं बनाया जा सका',
        nl: 'Kon het voorbeeld niet maken',
        sv: 'Kunde inte skapa förhandsvisningen',
        vi: 'Không thể tạo bản xem trước',
        id: 'Tidak dapat membuat pratinjau',
      }),
      filterAccounts: t({
        ru: 'Счета',
        en: 'Accounts',
        kk: 'Шоттар',
        de: 'Konten',
        fr: 'Comptes',
        es: 'Cuentas',
        pt: 'Contas',
        tr: 'Hesaplar',
        uk: 'Рахунки',
        zh: '账户',
        ar: 'الحسابات',
        pl: 'Konta',
        it: 'Conti',
        sk: 'Účty',
        ja: '口座',
        ko: '계좌',
        hi: 'खाते',
        nl: 'Rekeningen',
        sv: 'Konton',
        vi: 'Tài khoản',
        id: 'Akun',
      }),
      filterAllAccounts: t({
        ru: 'Все счета',
        en: 'All accounts',
        kk: 'Барлық шоттар',
        de: 'Alle Konten',
        fr: 'Tous les comptes',
        es: 'Todas las cuentas',
        pt: 'Todas as contas',
        tr: 'Tüm hesaplar',
        uk: 'Усі рахунки',
        zh: '全部账户',
        ar: 'كل الحسابات',
        pl: 'Wszystkie konta',
        it: 'Tutti i conti',
        sk: 'Všetky účty',
        ja: 'すべての口座',
        ko: '모든 계좌',
        hi: 'सभी खाते',
        nl: 'Alle rekeningen',
        sv: 'Alla konton',
        vi: 'Tất cả tài khoản',
        id: 'Semua akun',
      }),
      filterCategories: t({
        ru: 'Категории',
        en: 'Categories',
        kk: 'Санаттар',
        de: 'Kategorien',
        fr: 'Catégories',
        es: 'Categorías',
        pt: 'Categorias',
        tr: 'Kategoriler',
        uk: 'Категорії',
        zh: '类别',
        ar: 'الفئات',
        pl: 'Kategorie',
        it: 'Categorie',
        sk: 'Kategórie',
        ja: 'カテゴリ',
        ko: '카테고리',
        hi: 'श्रेणियाँ',
        nl: 'Categorieën',
        sv: 'Kategorier',
        vi: 'Danh mục',
        id: 'Kategori',
      }),
      filterAllCategories: t({
        ru: 'Все категории',
        en: 'All categories',
        kk: 'Барлық санаттар',
        de: 'Alle Kategorien',
        fr: 'Toutes les catégories',
        es: 'Todas las categorías',
        pt: 'Todas as categorias',
        tr: 'Tüm kategoriler',
        uk: 'Усі категорії',
        zh: '全部类别',
        ar: 'كل الفئات',
        pl: 'Wszystkie kategorie',
        it: 'Tutte le categorie',
        sk: 'Všetky kategórie',
        ja: 'すべてのカテゴリ',
        ko: '모든 카테고리',
        hi: 'सभी श्रेणियाँ',
        nl: 'Alle categorieën',
        sv: 'Alla kategorier',
        vi: 'Tất cả danh mục',
        id: 'Semua kategori',
      }),
      presetThisMonth: t({
        ru: 'Этот месяц',
        en: 'This month',
        kk: 'Осы ай',
        de: 'Dieser Monat',
        fr: 'Ce mois-ci',
        es: 'Este mes',
        pt: 'Este mês',
        tr: 'Bu ay',
        uk: 'Цей місяць',
        zh: '本月',
        ar: 'هذا الشهر',
        pl: 'Ten miesiąc',
        it: 'Questo mese',
        sk: 'Tento mesiac',
        ja: '今月',
        ko: '이번 달',
        hi: 'इस महीने',
        nl: 'Deze maand',
        sv: 'Denna månad',
        vi: 'Tháng này',
        id: 'Bulan ini',
      }),
      presetLastMonth: t({
        ru: 'Прошлый месяц',
        en: 'Last month',
        kk: 'Өткен ай',
        de: 'Letzter Monat',
        fr: 'Le mois dernier',
        es: 'El mes pasado',
        pt: 'Mês passado',
        tr: 'Geçen ay',
        uk: 'Минулий місяць',
        zh: '上个月',
        ar: 'الشهر الماضي',
        pl: 'Poprzedni miesiąc',
        it: 'Il mese scorso',
        sk: 'Minulý mesiac',
        ja: '先月',
        ko: '지난달',
        hi: 'पिछले महीने',
        nl: 'Vorige maand',
        sv: 'Förra månaden',
        vi: 'Tháng trước',
        id: 'Bulan lalu',
      }),
      presetThisQuarter: t({
        ru: 'Этот квартал',
        en: 'This quarter',
        kk: 'Осы тоқсан',
        de: 'Dieses Quartal',
        fr: 'Ce trimestre',
        es: 'Este trimestre',
        pt: 'Este trimestre',
        tr: 'Bu çeyrek',
        uk: 'Цей квартал',
        zh: '本季度',
        ar: 'هذا الربع',
        pl: 'Ten kwartał',
        it: 'Questo trimestre',
        sk: 'Tento štvrťrok',
        ja: '今四半期',
        ko: '이번 분기',
        hi: 'इस तिमाही',
        nl: 'Dit kwartaal',
        sv: 'Detta kvartal',
        vi: 'Quý này',
        id: 'Kuartal ini',
      }),
      presetYearToDate: t({
        ru: 'С начала года',
        en: 'Year to date',
        kk: 'Жыл басынан',
        de: 'Seit Jahresbeginn',
        fr: 'Depuis le début de l’année',
        es: 'Lo que va de año',
        pt: 'No ano até hoje',
        tr: 'Yıl başından bugüne',
        uk: 'Від початку року',
        zh: '年初至今',
        ar: 'منذ بداية السنة',
        pl: 'Od początku roku',
        it: 'Da inizio anno',
        sk: 'Od začiatku roka',
        ja: '年初来',
        ko: '연초 이후',
        hi: 'वर्ष प्रारंभ से अब तक',
        nl: 'Sinds begin dit jaar',
        sv: 'Hittills i år',
        vi: 'Từ đầu năm',
        id: 'Sejak awal tahun',
      }),
      groupBy: t({
        ru: 'Группировка',
        en: 'Group by',
        kk: 'Топтау',
        de: 'Gruppieren nach',
        fr: 'Grouper par',
        es: 'Agrupar por',
        pt: 'Agrupar por',
        tr: 'Grupla',
        uk: 'Групування',
        zh: '分组方式',
        ar: 'التجميع حسب',
        pl: 'Grupuj według',
        it: 'Raggruppa per',
        sk: 'Zoskupiť podľa',
        ja: 'グループ化',
        ko: '그룹화 기준',
        hi: 'समूहीकरण',
        nl: 'Groeperen op',
        sv: 'Gruppera efter',
        vi: 'Nhóm theo',
        id: 'Kelompokkan menurut',
      }),
      groupByDay: t({
        ru: 'День',
        en: 'Day',
        kk: 'Күн',
        de: 'Tag',
        fr: 'Jour',
        es: 'Día',
        pt: 'Dia',
        tr: 'Gün',
        uk: 'День',
        zh: '日',
        ar: 'يوم',
        pl: 'Dzień',
        it: 'Giorno',
        sk: 'Deň',
        ja: '日',
        ko: '일',
        hi: 'दिन',
        nl: 'Dag',
        sv: 'Dag',
        vi: 'Ngày',
        id: 'Hari',
      }),
      groupByWeek: t({
        ru: 'Неделя',
        en: 'Week',
        kk: 'Апта',
        de: 'Woche',
        fr: 'Semaine',
        es: 'Semana',
        pt: 'Semana',
        tr: 'Hafta',
        uk: 'Тиждень',
        zh: '周',
        ar: 'أسبوع',
        pl: 'Tydzień',
        it: 'Settimana',
        sk: 'Týždeň',
        ja: '週',
        ko: '주',
        hi: 'सप्ताह',
        nl: 'Week',
        sv: 'Vecka',
        vi: 'Tuần',
        id: 'Minggu',
      }),
      groupByMonth: t({
        ru: 'Месяц',
        en: 'Month',
        kk: 'Ай',
        de: 'Monat',
        fr: 'Mois',
        es: 'Mes',
        pt: 'Mês',
        tr: 'Ay',
        uk: 'Місяць',
        zh: '月',
        ar: 'شهر',
        pl: 'Miesiąc',
        it: 'Mese',
        sk: 'Mesiac',
        ja: '月',
        ko: '월',
        hi: 'महीना',
        nl: 'Maand',
        sv: 'Månad',
        vi: 'Tháng',
        id: 'Bulan',
      }),
      dateFrom: t({
        ru: 'Дата с',
        en: 'Date from',
        kk: 'Бастап күні',
        de: 'Datum von',
        fr: 'Date de début',
        es: 'Fecha desde',
        pt: 'Data de início',
        tr: 'Başlangıç tarihi',
        uk: 'Дата з',
        zh: '开始日期',
        ar: 'التاريخ من',
        pl: 'Data od',
        it: 'Data da',
        sk: 'Data od',
        ja: '開始日',
        ko: '시작 날짜',
        hi: 'तारीख से',
        nl: 'Datum van',
        sv: 'Datum från',
        vi: 'Từ ngày',
        id: 'Tanggal dari',
      }),
      dateTo: t({
        ru: 'Дата по',
        en: 'Date to',
        kk: 'Дейін күні',
        de: 'Datum bis',
        fr: 'Date de fin',
        es: 'Fecha hasta',
        pt: 'Data de fim',
        tr: 'Bitiş tarihi',
        uk: 'Дата по',
        zh: '结束日期',
        ar: 'التاريخ إلى',
        pl: 'Data do',
        it: 'Data fino a',
        sk: 'Data do',
        ja: '終了日',
        ko: '종료 날짜',
        hi: 'तारीख तक',
        nl: 'Datum tot',
        sv: 'Datum till',
        vi: 'Đến ngày',
        id: 'Tanggal sampai',
      }),
      format: t({
        ru: 'Формат',
        en: 'Format',
        kk: 'Формат',
        de: 'Formatieren',
        fr: 'Formater',
        es: 'Formato',
        pt: 'Formato',
        tr: 'Biçim',
        uk: 'Формат',
        zh: '格式',
        ar: 'الصيغة',
        pl: 'Sformatuj',
        it: 'Formato',
        sk: 'Formátovať',
        ja: 'フォーマット',
        ko: '형식',
        hi: 'प्रारूप',
        nl: 'Formaat',
        sv: 'Format',
        vi: 'Định dạng',
        id: 'Format',
      }),
      generate: t({
        ru: 'Сформировать отчёт',
        en: 'Generate report',
        kk: 'Есеп жасау',
        de: 'Bericht erstellen',
        fr: 'Générer le rapport',
        es: 'Generar informe',
        pt: 'Gerar relatório',
        tr: 'Rapor oluştur',
        uk: 'Сформувати звіт',
        zh: '生成报告',
        ar: 'إنشاء تقرير',
        pl: 'Generuj raport',
        it: 'Genera report',
        sk: 'Generuj raport',
        ja: 'レポートを生成',
        ko: '보고서 생성',
        hi: 'रिपोर्ट बनाएं',
        nl: 'Rapport genereren',
        sv: 'Generera rapport',
        vi: 'Tạo báo cáo',
        id: 'Buat laporan',
      }),
      generating: t({
        ru: 'Формирование…',
        en: 'Generating…',
        kk: 'Жасалуда…',
        de: 'Wird erstellt…',
        fr: 'Génération en cours…',
        es: 'Generando…',
        pt: 'Gerando…',
        tr: 'Oluşturuluyor…',
        uk: 'Формування…',
        zh: '生成中…',
        ar: 'جارٍ الإنشاء…',
        pl: 'Generowanie…',
        it: 'Generazione in corso…',
        sk: 'Generowanie…',
        ja: '生成中…',
        ko: '생성 중…',
        hi: 'बनाया जा रहा है…',
        nl: 'Genereren…',
        sv: 'Genererar…',
        vi: 'Đang tạo…',
        id: 'Membuat…',
      }),
      backToTemplates: t({
        ru: 'К шаблонам',
        en: 'Back to templates',
        kk: 'Үлгілерге қайту',
        de: 'Zurück zu Vorlagen',
        fr: 'Retour aux modèles',
        es: 'Volver a plantillas',
        pt: 'Voltar aos modelos',
        tr: 'Şablonlara dön',
        uk: 'До шаблонів',
        zh: '返回模板',
        ar: 'العودة إلى القوالب',
        pl: 'Wróć do szablonów',
        it: 'Torna ai modelli',
        sk: 'Wróć do szablonów',
        ja: 'テンプレートに戻る',
        ko: '템플릿으로 돌아가기',
        hi: 'टेम्पलेट पर वापस जाएं',
        nl: 'Terug naar sjablonen',
        sv: 'Tillbaka till mallar',
        vi: 'Quay lại mẫu',
        id: 'Kembali ke template',
      }),

      // History table headers
      historyTemplate: t({
        ru: 'Шаблон',
        en: 'Template',
        kk: 'Үлгі',
        de: 'Vorlage',
        fr: 'Modèle',
        es: 'Plantilla',
        pt: 'Modelo',
        tr: 'Şablon',
        uk: 'Шаблон',
        zh: '模板',
        ar: 'القالب',
        pl: 'Szablon',
        it: 'Modello',
        sk: 'Szablon',
        ja: 'テンプレート',
        ko: '템플릿',
        hi: 'टेम्पलेट',
        nl: 'Sjabloon',
        sv: 'Mall',
        vi: 'Mẫu',
        id: 'Templat',
      }),
      historyPeriod: t({
        ru: 'Период',
        en: 'Period',
        kk: 'Кезең',
        de: 'Zeitraum',
        fr: 'Période',
        es: 'Período',
        pt: 'Período',
        tr: 'Dönem',
        uk: 'Період',
        zh: '期间',
        ar: 'الفترة',
        pl: 'Okres',
        it: 'Periodo',
        sk: 'Okres',
        ja: '期間',
        ko: '기간',
        hi: 'अवधि',
        nl: 'Periode',
        sv: 'Period',
        vi: 'Kỳ',
        id: 'Periode',
      }),
      historyFormat: t({
        ru: 'Формат',
        en: 'Format',
        kk: 'Формат',
        de: 'Formatieren',
        fr: 'Formater',
        es: 'Formato',
        pt: 'Formato',
        tr: 'Biçim',
        uk: 'Формат',
        zh: '格式',
        ar: 'الصيغة',
        pl: 'Sformatuj',
        it: 'Formato',
        sk: 'Formátovať',
        ja: 'フォーマット',
        ko: '형식',
        hi: 'प्रारूप',
        nl: 'Formaat',
        sv: 'Format',
        vi: 'Định dạng',
        id: 'Format',
      }),
      historyGeneratedBy: t({
        ru: 'Кем создан',
        en: 'Generated by',
        kk: 'Кім жасаған',
        de: 'Erstellt von',
        fr: 'Généré par',
        es: 'Generado por',
        pt: 'Gerado por',
        tr: 'Oluşturan',
        uk: 'Ким створено',
        zh: '生成者',
        ar: 'أنشأ بواسطة',
        pl: 'Wygenerowany przez',
        it: 'Generato da',
        sk: 'Wygenerowany przez',
        ja: '生成者',
        ko: '생성자',
        hi: 'किसके द्वारा बनाया गया',
        nl: 'Gegenereerd door',
        sv: 'Genererad av',
        vi: 'Được tạo bởi',
        id: 'Dibuat oleh',
      }),
      historyGeneratedAt: t({
        ru: 'Дата создания',
        en: 'Generated at',
        kk: 'Жасалған күні',
        de: 'Erstellt am',
        fr: 'Généré le',
        es: 'Generado el',
        pt: 'Gerado em',
        tr: 'Oluşturulma tarihi',
        uk: 'Дата створення',
        zh: '生成时间',
        ar: 'تاريخ الإنشاء',
        pl: 'Data wygenerowania',
        it: 'Generato il',
        sk: 'Data wygenerowania',
        ja: '生成日時',
        ko: '생성 시간',
        hi: 'बनाने की तारीख',
        nl: 'Gegenereerd op',
        sv: 'Genererad den',
        vi: 'Được tạo lúc',
        id: 'Dibuat pada',
      }),
      historySize: t({
        ru: 'Размер',
        en: 'Size',
        kk: 'Өлшем',
        de: 'Größe',
        fr: 'Taille',
        es: 'Tamaño',
        pt: 'Tamanho',
        tr: 'Boyut',
        uk: 'Розмір',
        zh: '大小',
        ar: 'الحجم',
        pl: 'Rozmiar',
        it: 'Dimensione',
        sk: 'Rozmiar',
        ja: 'サイズ',
        ko: '크기',
        hi: 'आकार',
        nl: 'Grootte',
        sv: 'Storlek',
        vi: 'Kích thước',
        id: 'Ukuran',
      }),
      historyDownload: t({
        ru: 'Скачать',
        en: 'Download',
        kk: 'Жүктеу',
        de: 'Herunterladen',
        fr: 'Télécharger',
        es: 'Descargar',
        pt: 'Baixar',
        tr: 'İndir',
        uk: 'Завантажити',
        zh: '下载',
        ar: 'تنزيل',
        pl: 'Pobierz',
        it: 'Scarica',
        sk: 'Pobierz',
        ja: 'ダウンロード',
        ko: '다운로드',
        hi: 'डाउनलोड',
        nl: 'Downloaden',
        sv: 'Ladda ner',
        vi: 'Tải xuống',
        id: 'Unduh',
      }),
      historyEmpty: t({
        ru: 'История отчётов пуста',
        en: 'No reports generated yet',
        kk: 'Есептер тарихы бос',
        de: 'Noch keine Berichte erstellt',
        fr: "Aucun rapport généré pour l'instant",
        es: 'Aún no se han generado informes',
        pt: 'Nenhum relatório gerado ainda',
        tr: 'Henüz rapor oluşturulmadı',
        uk: 'Історія звітів порожня',
        zh: '尚未生成任何报告',
        ar: 'لم يتم إنشاء أي تقارير بعد',
        pl: 'Historia raportów jest pusta',
        it: 'Nessun report generato ancora',
        sk: 'Historia raportów jest pusta',
        ja: 'まだレポートが生成されていません',
        ko: '아직 생성된 보고서가 없습니다',
        hi: 'अभी तक कोई रिपोर्ट नहीं बनाई गई',
        nl: 'Nog geen rapporten gegenereerd',
        sv: 'Inga rapporter genererade än',
        vi: 'Chưa có báo cáo nào được tạo',
        id: 'Belum ada laporan yang dibuat',
      }),
      historyReport: t({
        ru: 'Отчёт',
        en: 'Report',
        kk: 'Есеп',
        de: 'Bericht',
        fr: 'Rapport',
        es: 'Informe',
        pt: 'Relatório',
        tr: 'Rapor',
        uk: 'Звіт',
        zh: '报告',
        ar: 'تقرير',
        pl: 'Raport',
        it: 'Rapporto',
        sk: 'Raport',
        ja: 'レポート',
        ko: '보고서',
        hi: 'रिपोर्ट',
        nl: 'Rapport',
        sv: 'Rapport',
        vi: 'Báo cáo',
        id: 'Laporan',
      }),
      historyGenerated: t({
        ru: 'Создан',
        en: 'Generated',
        kk: 'Жасалған',
        de: 'Erstellt',
        fr: 'Généré',
        es: 'Generado',
        pt: 'Gerado',
        tr: 'Oluşturuldu',
        uk: 'Створено',
        zh: '已生成',
        ar: 'تم الإنشاء',
        pl: 'Wygenerowany',
        it: 'Generato',
        sk: 'Wygenerowany',
        ja: '生成済み',
        ko: '생성됨',
        hi: 'बनाया गया',
        nl: 'Gegenereerd',
        sv: 'Genererad',
        vi: 'Đã tạo',
        id: 'Dibuat',
      }),
      historyEmptyHint: t({
        ru: 'Выберите шаблон и создайте первый отчёт.',
        en: 'Select a template and generate your first report.',
        kk: 'Үлгіні таңдап, бірінші есепті жасаңыз.',
        de: 'Wählen Sie eine Vorlage und erstellen Sie Ihren ersten Bericht.',
        fr: 'Sélectionnez un modèle et générez votre premier rapport.',
        es: 'Seleccione una plantilla y genere su primer informe.',
        pt: 'Selecione um modelo e gere seu primeiro relatório.',
        tr: 'Bir şablon seçin ve ilk raporunuzu oluşturun.',
        uk: 'Виберіть шаблон та створіть перший звіт.',
        zh: '选择一个模板并生成您的第一份报告。',
        ar: 'اختر قالباً وأنشئ تقريرك الأول.',
        pl: 'Wybierz szablon i wygeneruj swój pierwszy raport.',
        it: 'Seleziona un modello e genera il tuo primo report.',
        sk: 'Wybierz szablon i wygeneruj swój pierwszy raport.',
        ja: 'テンプレートを選択して最初のレポートを生成してください。',
        ko: '템플릿을 선택하고 첫 번째 보고서를 생성하세요.',
        hi: 'एक टेम्पलेट चुनें और अपनी पहली रिपोर्ट बनाएं।',
        nl: 'Selecteer een sjabloon en genereer uw eerste rapport.',
        sv: 'Välj en mall och generera din första rapport.',
        vi: 'Chọn mẫu và tạo báo cáo đầu tiên của bạn.',
        id: 'Pilih template dan buat laporan pertama Anda.',
      }),
      justNow: t({
        ru: 'Только что',
        en: 'Just now',
        kk: 'Жаңа ғана',
        de: 'Gerade eben',
        fr: "À l'instant",
        es: 'Ahora mismo',
        pt: 'Agora mesmo',
        tr: 'Az önce',
        uk: 'Щойно',
        zh: '刚刚',
        ar: 'للتو',
        pl: 'Przed chwilą',
        it: 'Proprio ora',
        sk: 'Przed chwilą',
        ja: 'たった今',
        ko: '방금',
        hi: 'अभी-अभी',
        nl: 'Zojuist',
        sv: 'Just nu',
        vi: 'Vừa xong',
        id: 'Baru saja',
      }),
      minutesAgo: t({
        ru: 'м назад',
        en: 'm ago',
        kk: 'мин бұрын',
        de: 'Min. zuvor',
        fr: 'min',
        es: 'min',
        pt: 'min atrás',
        tr: 'dk önce',
        uk: 'хв тому',
        zh: '分钟前',
        ar: 'د مضت',
        pl: 'min temu',
        it: 'min fa',
        sk: 'min temu',
        ja: '分前',
        ko: '분 전',
        hi: 'मिनट पहले',
        nl: 'min geleden',
        sv: 'min sedan',
        vi: 'phút trước',
        id: 'menit lalu',
      }),
      hoursAgo: t({
        ru: 'ч назад',
        en: 'h ago',
        kk: 'сағ бұрын',
        de: 'Std. zuvor',
        fr: 'h',
        es: 'h',
        pt: 'h atrás',
        tr: 'sa önce',
        uk: 'год тому',
        zh: '小时前',
        ar: 'س مضت',
        pl: 'godz. temu',
        it: 'h fa',
        sk: 'godz. temu',
        ja: '時間前',
        ko: '시간 전',
        hi: 'घंटे पहले',
        nl: 'uur geleden',
        sv: 'tim sedan',
        vi: 'giờ trước',
        id: 'jam lalu',
      }),
      yesterday: t({
        ru: 'Вчера',
        en: 'Yesterday',
        kk: 'Кеше',
        de: 'Gestern',
        fr: 'Hier',
        es: 'Ayer',
        pt: 'Ontem',
        tr: 'Dün',
        uk: 'Вчора',
        zh: '昨天',
        ar: 'أمس',
        pl: 'Wczoraj',
        it: 'Ieri',
        sk: 'Wczoraj',
        ja: '昨日',
        ko: '어제',
        hi: 'कल',
        nl: 'Gisteren',
        sv: 'Igår',
        vi: 'Hôm qua',
        id: 'Kemarin',
      }),
      daysAgo: t({
        ru: 'дн. назад',
        en: 'days ago',
        kk: 'күн бұрын',
        de: 'Tage zuvor',
        fr: 'jours',
        es: 'días',
        pt: 'dias atrás',
        tr: 'gün önce',
        uk: 'дн. тому',
        zh: '天前',
        ar: 'أيام مضت',
        pl: 'dni temu',
        it: 'giorni fa',
        sk: 'dni temu',
        ja: '日前',
        ko: '일 전',
        hi: 'दिन पहले',
        nl: 'dagen geleden',
        sv: 'dagar sedan',
        vi: 'ngày trước',
        id: 'hari lalu',
      }),

      // Balance Sheet labels (kept for BalanceSheet.tsx compatibility)
      balanceSheetTitle: t({
        ru: 'Баланс',
        en: 'Balance Sheet',
        kk: 'Баланс парағы',
        de: 'Bilanz',
        fr: 'Bilan',
        es: 'Balance General',
        pt: 'Balanço Patrimonial',
        tr: 'Bilanço',
        uk: 'Баланс',
        zh: '资产负债表',
        ar: 'الميزانية العمومية',
        pl: 'Bilans',
        it: 'Stato Patrimoniale',
        sk: 'Bilans',
        ja: '貸借対照表',
        ko: '대차 대조표',
        hi: 'बैलेंस शीट',
        nl: 'Balans',
        sv: 'Balansräkning',
        vi: 'Bảng cân đối kế toán',
        id: 'Neraca',
      }),
      assets: t({
        ru: 'Активы',
        en: 'Assets',
        kk: 'Активтер',
        de: 'Vermögenswerte',
        fr: 'Actifs',
        es: 'Activos',
        pt: 'Ativos',
        tr: 'Varlıklar',
        uk: 'Активи',
        zh: '资产',
        ar: 'الأصول',
        pl: 'Aktywa',
        it: 'Attività',
        sk: 'Aktywa',
        ja: '資産',
        ko: '자산',
        hi: 'संपत्ति',
        nl: 'Activa',
        sv: 'Tillgångar',
        vi: 'Tài sản',
        id: 'Aset',
      }),
      liabilities: t({
        ru: 'Пассивы',
        en: 'Liabilities',
        kk: 'Пассивтер',
        de: 'Verbindlichkeiten',
        fr: 'Passifs',
        es: 'Pasivos',
        pt: 'Passivos',
        tr: 'Yükümlülükler',
        uk: 'Пасиви',
        zh: '负债',
        ar: 'الخصوم',
        pl: 'Pasywa',
        it: 'Passività',
        sk: 'Pasywa',
        ja: '負債',
        ko: '부채',
        hi: 'देनदारियां',
        nl: 'Passiva',
        sv: 'Skulder',
        vi: 'Nợ phải trả',
        id: 'Kewajiban',
      }),
      asOfNow: t({
        ru: 'На данный момент',
        en: 'As of now',
        kk: 'Қазіргі уақытта',
        de: 'Zum jetzigen Zeitpunkt',
        fr: 'À ce jour',
        es: 'A partir de ahora',
        pt: 'A partir de agora',
        tr: 'Şu itibariyle',
        uk: 'На даний момент',
        zh: '截至目前',
        ar: 'اعتباراً من الآن',
        pl: 'Na chwilę obecną',
        it: 'A partire da ora',
        sk: 'Na chwilę obecną',
        ja: '現時点',
        ko: '현재 기준',
        hi: 'अभी की स्थिति',
        nl: 'Vanaf nu',
        sv: 'Per nu',
        vi: 'Tính đến hiện tại',
        id: 'Per sekarang',
      }),
      asOfDate: t({
        ru: 'На дату',
        en: 'As of date',
        kk: 'Күніне',
        de: 'Zum Datum',
        fr: 'À la date du',
        es: 'A la fecha',
        pt: 'Na data',
        tr: 'Tarihe göre',
        uk: 'На дату',
        zh: '截至日期',
        ar: 'اعتباراً من التاريخ',
        pl: 'Na dzień',
        it: 'Alla data',
        sk: 'Na dzień',
        ja: '日付基準',
        ko: '날짜 기준',
        hi: 'तारीख पर',
        nl: 'Per datum',
        sv: 'Per datum',
        vi: 'Tính đến ngày',
        id: 'Per tanggal',
      }),
      savingBalance: t({
        ru: 'Сохранение...',
        en: 'Saving...',
        kk: 'Сақталуда...',
        de: 'Wird gespeichert...',
        fr: 'Enregistrement...',
        es: 'Guardando...',
        pt: 'Salvando...',
        tr: 'Kaydediliyor...',
        uk: 'Збереження...',
        zh: '保存中...',
        ar: 'جارٍ الحفظ...',
        pl: 'Zapisywanie...',
        it: 'Salvataggio...',
        sk: 'Zapisywanie...',
        ja: '保存中...',
        ko: '저장 중...',
        hi: 'सहेजा जा रहा है...',
        nl: 'Opslaan...',
        sv: 'Sparar...',
        vi: 'Đang lưu...',
        id: 'Menyimpan...',
      }),
      balanceSaved: t({
        ru: 'Баланс сохранён',
        en: 'Balance saved',
        kk: 'Баланс сақталды',
        de: 'Saldo gespeichert',
        fr: 'Solde enregistré',
        es: 'Balance guardado',
        pt: 'Saldo salvo',
        tr: 'Bakiye kaydedildi',
        uk: 'Баланс збережено',
        zh: '余额已保存',
        ar: 'تم حفظ الرصيد',
        pl: 'Saldo zapisane',
        it: 'Saldo salvato',
        sk: 'Saldo zapisane',
        ja: '残高を保存しました',
        ko: '잔액이 저장되었습니다',
        hi: 'शेष राशि सहेजी गई',
        nl: 'Saldo opgeslagen',
        sv: 'Saldo sparat',
        vi: 'Số dư đã được lưu',
        id: 'Saldo tersimpan',
      }),
      exportBalance: t({
        ru: 'Экспорт баланса',
        en: 'Export balance',
        kk: 'Балансты экспорттау',
        de: 'Saldo exportieren',
        fr: 'Exporter le solde',
        es: 'Exportar balance',
        pt: 'Exportar saldo',
        tr: 'Bakiyeyi dışa aktar',
        uk: 'Експорт балансу',
        zh: '导出余额',
        ar: 'تصدير الرصيد',
        pl: 'Eksportuj saldo',
        it: 'Esporta saldo',
        sk: 'Eksportuj saldo',
        ja: '残高をエクスポート',
        ko: '잔액 내보내기',
        hi: 'शेष राशि निर्यात करें',
        nl: 'Saldo exporteren',
        sv: 'Exportera saldo',
        vi: 'Xuất số dư',
        id: 'Ekspor saldo',
      }),
      exportExcel: t({
        ru: 'Эксель',
        en: 'Excel',
        kk: 'Excel',
        de: 'Excel',
        fr: 'Exceller',
        es: 'excel',
        pt: 'Excel',
        tr: 'excel',
        uk: 'Excel',
        zh: 'Excel',
        ar: 'اكسل',
        pl: 'Excela',
        it: 'Eccellere',
        sk: 'Excel',
        ja: 'エクセル',
        ko: '엑셀',
        hi: 'एक्सेल',
        nl: 'Excel',
        sv: 'Excel',
        vi: 'Excel',
        id: 'Unggul',
      }),
      exportPdf: t({
        ru: 'PDF',
        en: 'PDF',
        kk: 'PDF',
        de: 'PDF',
        fr: 'PDF',
        es: 'PDF',
        pt: 'PDF',
        tr: 'PDF',
        uk: 'PDF',
        zh: 'PDF',
        ar: 'PDF',
        pl: 'PDF',
        it: 'PDF',
        sk: 'PDF',
        ja: 'PDF',
        ko: 'PDF',
        hi: 'PDF',
        nl: 'PDF',
        sv: 'PDF',
        vi: 'PDF',
        id: 'PDF',
      }),
      balanceDifference: t({
        ru: 'Разница баланса',
        en: 'Balance difference',
        kk: 'Баланс айырмасы',
        de: 'Saldodifferenz',
        fr: 'Différence de solde',
        es: 'Diferencia de balance',
        pt: 'Diferença de saldo',
        tr: 'Bakiye farkı',
        uk: 'Різниця балансу',
        zh: '余额差异',
        ar: 'فرق الرصيد',
        pl: 'Różnica salda',
        it: 'Differenza di saldo',
        sk: 'Różnica salda',
        ja: '残高差',
        ko: '잔액 차이',
        hi: 'शेष राशि का अंतर',
        nl: 'Saldoverschil',
        sv: 'Saldoskillnad',
        vi: 'Chênh lệch số dư',
        id: 'Selisih saldo',
      }),
      loadingEllipsis: t({
        ru: 'Загрузка…',
        en: 'Loading…',
        kk: 'Жүктелуде…',
        de: 'Wird geladen…',
        fr: 'Chargement…',
        es: 'Cargando…',
        pt: 'Carregando…',
        tr: 'Yükleniyor…',
        uk: 'Завантаження…',
        zh: '加载中…',
        ar: 'جارٍ التحميل…',
        pl: 'Ładowanie…',
        it: 'Caricamento…',
        sk: 'Ładowanie…',
        ja: '読み込み中…',
        ko: '로딩 중…',
        hi: 'लोड हो रहा है…',
        nl: 'Laden…',
        sv: 'Laddar…',
        vi: 'Đang tải…',
        id: 'Memuat…',
      }),
      noData: t({
        ru: 'Нет данных',
        en: 'No data',
        kk: 'Деректер жоқ',
        de: 'Keine Daten',
        fr: 'Aucune donnée',
        es: 'Sin datos',
        pt: 'Sem dados',
        tr: 'Veri yok',
        uk: 'Немає даних',
        zh: '无数据',
        ar: 'لا توجد بيانات',
        pl: 'Brak danych',
        it: 'Nessun dato',
        sk: 'Brak danych',
        ja: 'データなし',
        ko: '데이터 없음',
        hi: 'कोई डेटा नहीं',
        nl: 'Geen gegevens',
        sv: 'Inga data',
        vi: 'Không có dữ liệu',
        id: 'Tidak ada data',
      }),
      refresh: t({
        ru: 'Обновить',
        en: 'Refresh',
        kk: 'Жаңарту',
        de: 'Aktualisieren',
        fr: 'Actualiser',
        es: 'Actualizar',
        pt: 'Atualizar',
        tr: 'Yenile',
        uk: 'Оновити',
        zh: '刷新',
        ar: 'تحديث',
        pl: 'Odśwież',
        it: 'Aggiorna',
        sk: 'Odśwież',
        ja: '更新',
        ko: '새로 고침',
        hi: 'रिफ्रेश',
        nl: 'Vernieuwen',
        sv: 'Uppdatera',
        vi: 'Làm mới',
        id: 'Segarkan',
      }),
      generateAndDownload: t({
        ru: 'Сформировать и скачать',
        en: 'Generate & Download',
        kk: 'Жасау және жүктеу',
        de: 'Erstellen und herunterladen',
        fr: 'Générer et télécharger',
        es: 'Generar y descargar',
        pt: 'Gerar e baixar',
        tr: 'Oluştur ve indir',
        uk: 'Сформувати та завантажити',
        zh: '生成并下载',
        ar: 'إنشاء وتنزيل',
        pl: 'Generuj i pobierz',
        it: 'Genera e scarica',
        sk: 'Generuj i pobierz',
        ja: '生成してダウンロード',
        ko: '생성 및 다운로드',
        hi: 'बनाएं और डाउनलोड करें',
        nl: 'Genereren en downloaden',
        sv: 'Generera och ladda ner',
        vi: 'Tạo và tải xuống',
        id: 'Buat & Unduh',
      }),
      cancel: t({
        ru: 'Отмена',
        en: 'Cancel',
        kk: 'Болдырмау',
        de: 'Abbrechen',
        fr: 'Annuler',
        es: 'Cancelar',
        pt: 'Cancelar',
        tr: 'İptal',
        uk: 'Скасувати',
        zh: '取消',
        ar: 'إلغاء',
        pl: 'Anuluj',
        it: 'Annulla',
        sk: 'Anuluj',
        ja: 'キャンセル',
        ko: '취소',
        hi: 'रद्द करें',
        nl: 'Annuleren',
        sv: 'Avbryt',
        vi: 'Hủy',
        id: 'Batal',
      }),
    },
  },
} satisfies Dictionary;

export default content;
