import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'createWorkspaceModal',
  content: {
    profileLabel: t({
      ru: 'Для чего этот воркспейс?',
      en: 'What is this workspace for?',
      kk: 'Бұл кеңістік не үшін?',
      de: 'Wofür ist dieser Workspace?',
      fr: 'À quoi sert cet espace ?',
      es: '¿Para qué es este espacio?',
      pt: 'Para que serve este espaço?',
      tr: 'Bu çalışma alanı ne için?',
      uk: 'Для чого цей воркспейс?',
      zh: '这个工作区用于什么？',
      ar: 'ما الغرض من مساحة العمل هذه؟',
      pl: 'Do czego służy ta przestrzeń?',
      it: 'A cosa serve questo spazio?',
      sk: 'Na čo je tento priestor?',
      ja: 'このワークスペースの用途は？',
      ko: '이 워크스페이스의 용도는?',
      hi: 'यह वर्कस्पेस किसलिए है?',
      nl: 'Waar is deze werkruimte voor?',
      sv: 'Vad är arbetsytan till för?',
      vi: 'Không gian này dùng để làm gì?',
      id: 'Ruang kerja ini untuk apa?',
    }),
    profileHome: t({
      ru: 'Дом',
      en: 'Home',
      kk: 'Үй',
      de: 'Privat',
      fr: 'Maison',
      es: 'Hogar',
      pt: 'Casa',
      tr: 'Ev',
      uk: 'Дім',
      zh: '家庭',
      ar: 'منزل',
      pl: 'Dom',
      it: 'Casa',
      sk: 'Domácnosť',
      ja: 'ホーム',
      ko: '홈',
      hi: 'होम',
      nl: 'Thuis',
      sv: 'Hem',
      vi: 'Gia đình',
      id: 'Rumah',
    }),
    profileHomeHint: t({
      ru: 'Личные или семейные деньги: без счетов, леджера и налогов в меню',
      en: 'Personal or family money: no invoices, ledger or tax in the menu',
      kk: 'Жеке немесе отбасылық қаржы: мәзірде инвойс, леджер және салық жоқ',
      de: 'Privates oder Familiengeld: ohne Rechnungen, Hauptbuch und Steuern im Menü',
      fr: 'Argent personnel ou familial : ni factures, ni grand livre, ni impôts dans le menu',
      es: 'Dinero personal o familiar: sin facturas, libro mayor ni impuestos en el menú',
      pt: 'Dinheiro pessoal ou da família: sem faturas, razão nem impostos no menu',
      tr: 'Kişisel veya aile parası: menüde fatura, defter ve vergi yok',
      uk: 'Особисті або сімейні гроші: без рахунків, леджера і податків у меню',
      zh: '个人或家庭财务：菜单中不显示发票、总账和税务',
      ar: 'مال شخصي أو عائلي: بلا فواتير أو دفتر أستاذ أو ضرائب في القائمة',
      pl: 'Pieniądze osobiste lub rodzinne: bez faktur, księgi i podatków w menu',
      it: 'Denaro personale o familiare: senza fatture, libro mastro e tasse nel menu',
      sk: 'Osobné alebo rodinné peniaze: bez faktúr, účtovnej knihy a daní v menu',
      ja: '個人や家族のお金：メニューに請求書・元帳・税は出ません',
      ko: '개인 또는 가족 자금: 메뉴에 인보이스, 원장, 세금 없음',
      hi: 'व्यक्तिगत या पारिवारिक पैसा: मेनू में इनवॉइस, लेजर और टैक्स नहीं',
      nl: 'Persoonlijk of gezinsgeld: geen facturen, grootboek of belasting in het menu',
      sv: 'Privata eller familjens pengar: inga fakturor, huvudbok eller skatt i menyn',
      vi: 'Tiền cá nhân hoặc gia đình: menu không có hóa đơn, sổ cái, thuế',
      id: 'Uang pribadi atau keluarga: tanpa faktur, buku besar, dan pajak di menu',
    }),
    profileBusiness: t({
      ru: 'Бизнес',
      en: 'Business',
      kk: 'Бизнес',
      de: 'Geschäft',
      fr: 'Entreprise',
      es: 'Negocio',
      pt: 'Negócio',
      tr: 'İşletme',
      uk: 'Бізнес',
      zh: '企业',
      ar: 'عمل',
      pl: 'Firma',
      it: 'Azienda',
      sk: 'Firma',
      ja: 'ビジネス',
      ko: '비즈니스',
      hi: 'बिज़नेस',
      nl: 'Zakelijk',
      sv: 'Företag',
      vi: 'Doanh nghiệp',
      id: 'Bisnis',
    }),
    profileBusinessHint: t({
      ru: 'Счета, кредиторка, леджер, налоговая декларация, таблицы',
      en: 'Invoices, payables, ledger, tax declaration, tables',
      kk: 'Инвойстар, төлемдер, леджер, салық декларациясы, кестелер',
      de: 'Rechnungen, Verbindlichkeiten, Hauptbuch, Steuererklärung, Tabellen',
      fr: 'Factures, dettes, grand livre, déclaration fiscale, tableaux',
      es: 'Facturas, pagos, libro mayor, declaración fiscal, tablas',
      pt: 'Faturas, contas a pagar, razão, declaração fiscal, tabelas',
      tr: 'Faturalar, borçlar, defter, vergi beyannamesi, tablolar',
      uk: 'Рахунки, кредиторка, леджер, податкова декларація, таблиці',
      zh: '发票、应付款、总账、报税、表格',
      ar: 'فواتير ومستحقات ودفتر أستاذ وإقرار ضريبي وجداول',
      pl: 'Faktury, zobowiązania, księga, deklaracja podatkowa, tabele',
      it: 'Fatture, debiti, libro mastro, dichiarazione fiscale, tabelle',
      sk: 'Faktúry, záväzky, účtovná kniha, daňové priznanie, tabuľky',
      ja: '請求書・買掛・元帳・税申告・テーブル',
      ko: '인보이스, 미지급금, 원장, 세금 신고, 표',
      hi: 'इनवॉइस, देय, लेजर, टैक्स घोषणा, टेबल',
      nl: 'Facturen, crediteuren, grootboek, belastingaangifte, tabellen',
      sv: 'Fakturor, skulder, huvudbok, deklaration, tabeller',
      vi: 'Hóa đơn, phải trả, sổ cái, khai thuế, bảng',
      id: 'Faktur, utang, buku besar, laporan pajak, tabel',
    }),
  },
} satisfies Dictionary;

export default content;
