/* eslint-disable max-lines */
import { type Dictionary, t } from 'intlayer';

const content = {
  key: 'workspacesListView',
  content: {
    empty: {
      subtitle: t({
        ru: 'Создайте первое рабочее пространство, чтобы начать',
        en: 'Create your first workspace to get started',
        kk: 'Бастау үшін алғашқы жұмыс кеңістігін жасаңыз',
        de: 'Erstellen Sie Ihren ersten Arbeitsbereich, um loszulegen',
        fr: 'Créez votre premier espace de travail pour commencer',
        es: 'Crea tu primer espacio de trabajo para empezar',
        pt: 'Crie seu primeiro espaço de trabalho para começar',
        tr: 'Başlamak için ilk çalışma alanınızı oluşturun',
        uk: 'Створіть перший робочий простір, щоб почати',
        zh: '创建您的第一个工作区以开始使用',
        ar: 'أنشئ مساحة العمل الأولى للبدء',
        pl: 'Utwórz pierwszy obszar roboczy, aby zacząć',
        it: 'Crea la tua prima area di lavoro per iniziare',
        sk: 'Vytvorte si prvý pracovný priestor a začnite',
        ja: '最初のワークスペースを作成して始めましょう',
        ko: '첫 워크스페이스를 만들어 시작하세요',
        hi: 'शुरू करने के लिए अपना पहला कार्यक्षेत्र बनाएं',
        nl: 'Maak je eerste werkruimte aan om te beginnen',
        sv: 'Skapa din första arbetsyta för att komma igång',
        vi: 'Tạo không gian làm việc đầu tiên để bắt đầu',
        id: 'Buat ruang kerja pertama Anda untuk memulai',
        da: 'Opret dit første arbejdsrum for at komme i gang',
        nb: 'Opprett det første arbeidsrommet ditt for å komme i gang',
        nn: 'Opprett det første arbeidsrommet ditt for å kome i gang',
        fi: 'Luo ensimmäinen työtilasi päästäksesi alkuun',
        is: 'Búðu til fyrsta vinnurýmið þitt til að byrja',
        fo: 'Stovna títt fyrsta arbeiðsrúm fyri at koma í gongd',
        cs: 'Pro začátek vytvořte svůj první pracovní prostor',
        bg: 'Създайте първото си работно пространство, за да започнете',
        hr: 'Stvorite svoj prvi radni prostor i možete započeti',
        sr: 'Направите свој први радни простор и можете започети',
        sl: 'Ustvarite svoj prvi delovni prostor in lahko začnete',
        mk: 'Создајте го вашиот прв работен простор за да започнете',
        be: 'Стварыце сваю першую працоўную прастору, каб пачаць',
        bs: 'Napravite svoj prvi radni prostor i možete započeti',
        hsb: 'Wutworće swój prěni dźěłowy rum a móžeće startować',
      }),
    },
    noResults: {
      title: t({
        ru: 'Рабочие пространства не найдены',
        en: 'No workspaces found',
        kk: 'Жұмыс кеңістіктері табылмады',
        de: 'Keine Arbeitsbereiche gefunden',
        fr: 'Aucun espace de travail trouvé',
        es: 'No se encontraron espacios de trabajo',
        pt: 'Nenhum espaço de trabalho encontrado',
        tr: 'Çalışma alanı bulunamadı',
        uk: 'Робочі простори не знайдено',
        zh: '未找到工作区',
        ar: 'لم يتم العثور على مساحات عمل',
        pl: 'Nie znaleziono obszarów roboczych',
        it: 'Nessuna area di lavoro trovata',
        sk: 'Nenašli sa žiadne pracovné priestory',
        ja: 'ワークスペースが見つかりません',
        ko: '워크스페이스를 찾을 수 없습니다',
        hi: 'कोई कार्यक्षेत्र नहीं मिला',
        nl: 'Geen werkruimtes gevonden',
        sv: 'Inga arbetsytor hittades',
        vi: 'Không tìm thấy không gian làm việc',
        id: 'Tidak ada ruang kerja ditemukan',
        da: 'Ingen arbejdsrum fundet',
        nb: 'Ingen arbeidsrom funnet',
        nn: 'Ingen arbeidsrom funne',
        fi: 'Työtiloja ei löytynyt',
        is: 'Engin vinnurými fundust',
        fo: 'Eingi arbeiðsrúm funnin',
        cs: 'Žádné pracovní prostory nenalezeny',
        bg: 'Няма намерени работни пространства',
        hr: 'Nema pronađenih radnih prostora',
        sr: 'Нема пронађених радних простора',
        sl: 'Ni najdenih delovnih prostorov',
        mk: 'Нема најдени работни простори',
        be: 'Працоўных прастор не знойдзена',
        bs: 'Nema pronađenih radnih prostora',
        hsb: 'Žane dźěłowe rumy namakane',
      }),
      subtitle: t({
        ru: 'Попробуйте изменить поисковый запрос',
        en: 'Try adjusting your search query',
        kk: 'Іздеу сұрауын өзгертіп көріңіз',
        de: 'Versuchen Sie, Ihre Suchanfrage anzupassen',
        fr: 'Essayez de modifier votre recherche',
        es: 'Prueba a ajustar tu búsqueda',
        pt: 'Tente ajustar sua pesquisa',
        tr: 'Arama sorgunuzu değiştirmeyi deneyin',
        uk: 'Спробуйте змінити пошуковий запит',
        zh: '请尝试调整搜索词',
        ar: 'جرّب تعديل عبارة البحث',
        pl: 'Spróbuj zmienić zapytanie',
        it: 'Prova a modificare la ricerca',
        sk: 'Skúste upraviť vyhľadávanie',
        ja: '検索キーワードを変更してみてください',
        ko: '검색어를 조정해 보세요',
        hi: 'अपनी खोज बदलकर देखें',
        nl: 'Pas je zoekopdracht aan',
        sv: 'Försök justera din sökning',
        vi: 'Hãy thử điều chỉnh từ khóa tìm kiếm',
        id: 'Coba ubah kata kunci pencarian',
        da: 'Prøv at justere din søgning',
        nb: 'Prøv å justere søket ditt',
        nn: 'Prøv å justere søket ditt',
        fi: 'Kokeile muuttaa hakuasi',
        is: 'Prófaðu að breyta leitinni þinni',
        fo: 'Royn at broyta tína leiting',
        cs: 'Zkuste upravit svůj dotaz',
        bg: 'Опитайте да промените търсенето си',
        hr: 'Pokušajte promijeniti svoj upit',
        sr: 'Покушајте да промените свој упит',
        sl: 'Poskusite spremeniti svoje iskanje',
        mk: 'Обидете се да го промените вашето барање',
        be: 'Паспрабуйце змяніць свой запыт',
        bs: 'Pokušajte promijeniti svoj upit',
        hsb: 'Spytajće swoje pytanje změnić',
      }),
    },
    sort: {
      button: t({
        ru: 'Сортировка',
        en: 'Sort options',
        kk: 'Сұрыптау',
        de: 'Sortieroptionen',
        fr: 'Options de tri',
        es: 'Opciones de orden',
        pt: 'Opções de ordenação',
        tr: 'Sıralama seçenekleri',
        uk: 'Сортування',
        zh: '排序选项',
        ar: 'خيارات الترتيب',
        pl: 'Opcje sortowania',
        it: 'Opzioni di ordinamento',
        sk: 'Možnosti zoradenia',
        ja: '並べ替えオプション',
        ko: '정렬 옵션',
        hi: 'क्रम विकल्प',
        nl: 'Sorteeropties',
        sv: 'Sorteringsalternativ',
        vi: 'Tùy chọn sắp xếp',
        id: 'Opsi urutan',
        da: 'Sorteringsmuligheder',
        nb: 'Sorteringsvalg',
        nn: 'Sorteringsval',
        fi: 'Järjestysvaihtoehdot',
        is: 'Röðunarvalkostir',
        fo: 'Raðfestingarmøguleikar',
        cs: 'Možnosti řazení',
        bg: 'Опции за подреждане',
        hr: 'Mogućnosti sortiranja',
        sr: 'Могућности сортирања',
        sl: 'Možnosti razvrščanja',
        mk: 'Опции за сортирање',
        be: 'Варыянты сартавання',
        bs: 'Opcije sortiranja',
        hsb: 'Móžnosće rjadowanja',
      }),
      favorites: t({
        ru: 'Сначала избранные',
        en: 'Favorites First',
        kk: 'Алдымен таңдаулылар',
        de: 'Favoriten zuerst',
        fr: 'Favoris en premier',
        es: 'Favoritos primero',
        pt: 'Favoritos primeiro',
        tr: 'Önce favoriler',
        uk: 'Спочатку обрані',
        zh: '收藏优先',
        ar: 'المفضلة أولاً',
        pl: 'Najpierw ulubione',
        it: 'Prima i preferiti',
        sk: 'Najprv obľúbené',
        ja: 'お気に入りを先頭に',
        ko: '즐겨찾기 먼저',
        hi: 'पहले पसंदीदा',
        nl: 'Favorieten eerst',
        sv: 'Favoriter först',
        vi: 'Yêu thích trước',
        id: 'Favorit dulu',
        da: 'Favoritter først',
        nb: 'Favoritter først',
        nn: 'Favorittar først',
        fi: 'Suosikit ensin',
        is: 'Eftirlæti fyrst',
        fo: 'Yndislutir fyrst',
        cs: 'Nejdřív oblíbené',
        bg: 'Първо любимите',
        hr: 'Najprije favoriti',
        sr: 'Најпре омиљени',
        sl: 'Najprej priljubljeni',
        mk: 'Најпрвин омилените',
        be: 'Спярша ўлюбёныя',
        bs: 'Najprije favoriti',
        hsb: 'Najprjedy fawority',
      }),
      alphabetical: t({
        ru: 'По алфавиту',
        en: 'Alphabetical',
        kk: 'Әліпби бойынша',
        de: 'Alphabetisch',
        fr: 'Alphabétique',
        es: 'Alfabético',
        pt: 'Alfabética',
        tr: 'Alfabetik',
        uk: 'За алфавітом',
        zh: '按字母顺序',
        ar: 'أبجدياً',
        pl: 'Alfabetycznie',
        it: 'Alfabetico',
        sk: 'Abecedne',
        ja: 'アルファベット順',
        ko: '가나다순',
        hi: 'वर्णानुक्रम',
        nl: 'Alfabetisch',
        sv: 'Alfabetiskt',
        vi: 'Theo bảng chữ cái',
        id: 'Abjad',
        da: 'Alfabetisk',
        nb: 'Alfabetisk',
        nn: 'Alfabetisk',
        fi: 'Aakkosjärjestys',
        is: 'Í stafrófsröð',
        fo: 'Í stavraðfylgju',
        cs: 'Abecedně',
        bg: 'По азбучен ред',
        hr: 'Abecedno',
        sr: 'Абецедно',
        sl: 'Po abecedi',
        mk: 'По азбучен ред',
        be: 'Па алфавіце',
        bs: 'Abecedno',
        hsb: 'Po alfabeće',
      }),
      recent: t({
        ru: 'Недавно созданные',
        en: 'Recently Created',
        kk: 'Жақында жасалғандар',
        de: 'Zuletzt erstellt',
        fr: 'Créés récemment',
        es: 'Creados recientemente',
        pt: 'Criados recentemente',
        tr: 'Yeni oluşturulanlar',
        uk: 'Нещодавно створені',
        zh: '最近创建',
        ar: 'المنشأة مؤخراً',
        pl: 'Ostatnio utworzone',
        it: 'Creati di recente',
        sk: 'Nedávno vytvorené',
        ja: '最近作成',
        ko: '최근 생성',
        hi: 'हाल ही में बनाए गए',
        nl: 'Recent aangemaakt',
        sv: 'Nyligen skapade',
        vi: 'Tạo gần đây',
        id: 'Baru dibuat',
        da: 'Senest oprettet',
        nb: 'Sist opprettet',
        nn: 'Sist oppretta',
        fi: 'Viimeksi luodut',
        is: 'Nýjast búið til',
        fo: 'Nýggjast stovnað',
        cs: 'Naposledy vytvořené',
        bg: 'Последно създадени',
        hr: 'Nedavno stvoreni',
        sr: 'Недавно направљени',
        sl: 'Nazadnje ustvarjeni',
        mk: 'Неодамна создадени',
        be: 'Нядаўна створаныя',
        bs: 'Nedavno napravljeni',
        hsb: 'Najnowše wutworjene',
      }),
    },
    view: {
      grid: t({
        ru: 'Плитка',
        en: 'Grid view',
        kk: 'Тор көрінісі',
        de: 'Rasteransicht',
        fr: 'Vue en grille',
        es: 'Vista de cuadrícula',
        pt: 'Visualização em grade',
        tr: 'Izgara görünümü',
        uk: 'Плитка',
        zh: '网格视图',
        ar: 'عرض الشبكة',
        pl: 'Widok siatki',
        it: 'Vista a griglia',
        sk: 'Mriežkové zobrazenie',
        ja: 'グリッド表示',
        ko: '그리드 보기',
        hi: 'ग्रिड दृश्य',
        nl: 'Rasterweergave',
        sv: 'Rutnätsvy',
        vi: 'Dạng lưới',
        id: 'Tampilan kisi',
        da: 'Gittervisning',
        nb: 'Rutenettvisning',
        nn: 'Rutenettvising',
        fi: 'Ruudukkonäkymä',
        is: 'Rúðunetssýn',
        fo: 'Rutunetsvísing',
        cs: 'Zobrazení v mřížce',
        bg: 'Изглед в мрежа',
        hr: 'Prikaz u rešetki',
        sr: 'Приказ у мрежи',
        sl: 'Prikaz v mreži',
        mk: 'Приказ во мрежа',
        be: 'Выгляд сеткай',
        bs: 'Prikaz u rešetki',
        hsb: 'Napohlad w sigi',
      }),
      list: t({
        ru: 'Список',
        en: 'List view',
        kk: 'Тізім көрінісі',
        de: 'Listenansicht',
        fr: 'Vue en liste',
        es: 'Vista de lista',
        pt: 'Visualização em lista',
        tr: 'Liste görünümü',
        uk: 'Список',
        zh: '列表视图',
        ar: 'عرض القائمة',
        pl: 'Widok listy',
        it: 'Vista a elenco',
        sk: 'Zobrazenie zoznamu',
        ja: 'リスト表示',
        ko: '목록 보기',
        hi: 'सूची दृश्य',
        nl: 'Lijstweergave',
        sv: 'Listvy',
        vi: 'Dạng danh sách',
        id: 'Tampilan daftar',
        da: 'Listevisning',
        nb: 'Listevisning',
        nn: 'Listevising',
        fi: 'Luettelonäkymä',
        is: 'Listasýn',
        fo: 'Listavísing',
        cs: 'Zobrazení v seznamu',
        bg: 'Изглед в списък',
        hr: 'Prikaz u popisu',
        sr: 'Приказ у списку',
        sl: 'Prikaz v seznamu',
        mk: 'Приказ во список',
        be: 'Выгляд спісам',
        bs: 'Prikaz u spisku',
        hsb: 'Napohlad w lisćinje',
      }),
    },
    list: {
      you: t({
        ru: 'Вы',
        en: 'You',
        kk: 'Сіз',
        de: 'Sie',
        fr: 'Vous',
        es: 'Tú',
        pt: 'Você',
        tr: 'Siz',
        uk: 'Ви',
        zh: '您',
        ar: 'أنت',
        pl: 'Ty',
        it: 'Tu',
        sk: 'Vy',
        ja: 'あなた',
        ko: '나',
        hi: 'आप',
        nl: 'Jij',
        sv: 'Du',
        vi: 'Bạn',
        id: 'Anda',
        da: 'Dig',
        nb: 'Deg',
        nn: 'Deg',
        fi: 'Sinä',
        is: 'Þú',
        fo: 'Tú',
        cs: 'Vy',
        bg: 'Вие',
        hr: 'Vi',
        sr: 'Ви',
        sl: 'Vi',
        mk: 'Вие',
        be: 'Вы',
        bs: 'Vi',
        hsb: 'Wy',
      }),
      currentMember: t({
        ru: 'Текущий участник',
        en: 'Current member',
        kk: 'Ағымдағы мүше',
        de: 'Aktuelles Mitglied',
        fr: 'Membre actuel',
        es: 'Miembro actual',
        pt: 'Membro atual',
        tr: 'Mevcut üye',
        uk: 'Поточний учасник',
        zh: '当前成员',
        ar: 'العضو الحالي',
        pl: 'Obecny członek',
        it: 'Membro attuale',
        sk: 'Aktuálny člen',
        ja: '現在のメンバー',
        ko: '현재 멤버',
        hi: 'वर्तमान सदस्य',
        nl: 'Huidig lid',
        sv: 'Nuvarande medlem',
        vi: 'Thành viên hiện tại',
        id: 'Anggota saat ini',
        da: 'Nuværende medlem',
        nb: 'Nåværende medlem',
        nn: 'Noverande medlem',
        fi: 'Nykyinen jäsen',
        is: 'Núverandi meðlimur',
        fo: 'Núverandi limur',
        cs: 'Aktuální člen',
        bg: 'Текущ член',
        hr: 'Trenutni član',
        sr: 'Тренутни члан',
        sl: 'Trenutni član',
        mk: 'Тековен член',
        be: 'Цяперашні ўдзельнік',
        bs: 'Trenutni član',
        hsb: 'Aktualny čłon',
      }),
      default: t({
        ru: 'По умолчанию',
        en: 'Default',
        kk: 'Әдепкі',
        de: 'Standard',
        fr: 'Par défaut',
        es: 'Predeterminado',
        pt: 'Padrão',
        tr: 'Varsayılan',
        uk: 'За замовчуванням',
        zh: '默认',
        ar: 'افتراضي',
        pl: 'Domyślny',
        it: 'Predefinito',
        sk: 'Predvolený',
        ja: 'デフォルト',
        ko: '기본',
        hi: 'डिफ़ॉल्ट',
        nl: 'Standaard',
        sv: 'Standard',
        vi: 'Mặc định',
        id: 'Default',
        da: 'Standard',
        nb: 'Standard',
        nn: 'Standard',
        fi: 'Oletus',
        is: 'Sjálfgefið',
        fo: 'Standard',
        cs: 'Výchozí',
        bg: 'По подразбиране',
        hr: 'Zadano',
        sr: 'Подразумевано',
        sl: 'Privzeto',
        mk: 'Стандардно',
        be: 'Прадвызначана',
        bs: 'Podrazumijevano',
        hsb: 'Standard',
      }),
      workspaceFallback: t({
        ru: 'Рабочее пространство',
        en: 'Workspace',
        kk: 'Жұмыс кеңістігі',
        de: 'Arbeitsbereich',
        fr: 'Espace de travail',
        es: 'Espacio de trabajo',
        pt: 'Espaço de trabalho',
        tr: 'Çalışma alanı',
        uk: 'Робочий простір',
        zh: '工作区',
        ar: 'مساحة العمل',
        pl: 'Obszar roboczy',
        it: 'Area di lavoro',
        sk: 'Pracovný priestor',
        ja: 'ワークスペース',
        ko: '워크스페이스',
        hi: 'कार्यक्षेत्र',
        nl: 'Werkruimte',
        sv: 'Arbetsyta',
        vi: 'Không gian làm việc',
        id: 'Ruang kerja',
        da: 'Gennemsnit',
        nb: 'Gjennomsnitt',
        nn: 'Gjennomsnitt',
        fi: 'Keskiarvo',
        is: 'Meðaltal',
        fo: 'Miðal',
        cs: 'Průměr',
        bg: 'Средно',
        hr: 'Prosjek',
        sr: 'Просек',
        sl: 'Povprečje',
        mk: 'Просек',
        be: 'Сярэдняе',
        bs: 'Prosjek',
        hsb: 'Přerězk',
      }),
    },
    columns: {
      name: t({
        ru: 'Название пространства',
        en: 'Workspace name',
        kk: 'Жұмыс кеңістігінің атауы',
        de: 'Name des Arbeitsbereichs',
        fr: "Nom de l'espace de travail",
        es: 'Nombre del espacio de trabajo',
        pt: 'Nome do espaço de trabalho',
        tr: 'Çalışma alanı adı',
        uk: 'Назва простору',
        zh: '工作区名称',
        ar: 'اسم مساحة العمل',
        pl: 'Nazwa obszaru roboczego',
        it: "Nome dell'area di lavoro",
        sk: 'Názov pracovného priestoru',
        ja: 'ワークスペース名',
        ko: '워크스페이스 이름',
        hi: 'कार्यक्षेत्र का नाम',
        nl: 'Naam werkruimte',
        sv: 'Arbetsytans namn',
        vi: 'Tên không gian làm việc',
        id: 'Nama ruang kerja',
        da: 'Arbejdsområdets navn',
        nb: 'Navn på arbeidsområdet',
        nn: 'Namn på arbeidsområdet',
        fi: 'Työtilan nimi',
        is: 'Heiti vinnusvæðis',
        fo: 'Navn á arbeiðsøki',
        cs: 'Název pracovního prostoru',
        bg: 'Име на работното пространство',
        hr: 'Naziv radnog prostora',
        sr: 'Назив радног простора',
        sl: 'Ime delovnega prostora',
        mk: 'Име на работниот простор',
        be: 'Назва працоўнай прасторы',
        bs: 'Naziv radnog prostora',
        hsb: 'Mjeno dźěłoweho ruma',
      }),
      owner: t({
        ru: 'Владелец',
        en: 'Owner',
        kk: 'Иесі',
        de: 'Eigentümer',
        fr: 'Propriétaire',
        es: 'Propietario',
        pt: 'Proprietário',
        tr: 'Sahip',
        uk: 'Власник',
        zh: '所有者',
        ar: 'المالك',
        pl: 'Właściciel',
        it: 'Proprietario',
        sk: 'Vlastník',
        ja: 'オーナー',
        ko: '소유자',
        hi: 'स्वामी',
        nl: 'Eigenaar',
        sv: 'Ägare',
        vi: 'Chủ sở hữu',
        id: 'Pemilik',
        da: 'Ejer',
        nb: 'Eier',
        nn: 'Eigar',
        fi: 'Omistaja',
        is: 'Eigandi',
        fo: 'Eigari',
        cs: 'Vlastník',
        bg: 'Собственик',
        hr: 'Vlasnik',
        sr: 'Власник',
        sl: 'Lastnik',
        mk: 'Сопственик',
        be: 'Уладальнік',
        bs: 'Vlasnik',
        hsb: 'Wobsedźer',
      }),
      type: t({
        ru: 'Тип пространства',
        en: 'Workspace type',
        kk: 'Жұмыс кеңістігінің түрі',
        de: 'Art des Arbeitsbereichs',
        fr: "Type d'espace de travail",
        es: 'Tipo de espacio de trabajo',
        pt: 'Tipo de espaço de trabalho',
        tr: 'Çalışma alanı türü',
        uk: 'Тип простору',
        zh: '工作区类型',
        ar: 'نوع مساحة العمل',
        pl: 'Typ obszaru roboczego',
        it: 'Tipo di area di lavoro',
        sk: 'Typ pracovného priestoru',
        ja: 'ワークスペースの種類',
        ko: '워크스페이스 유형',
        hi: 'कार्यक्षेत्र का प्रकार',
        nl: 'Type werkruimte',
        sv: 'Typ av arbetsyta',
        vi: 'Loại không gian làm việc',
        id: 'Jenis ruang kerja',
        da: 'Type arbejdsrum',
        nb: 'Arbeidsromstype',
        nn: 'Arbeidsromstype',
        fi: 'Työtilan tyyppi',
        is: 'Tegund vinnurýmis',
        fo: 'Arbeiðsrúmsslag',
        cs: 'Typ pracovního prostoru',
        bg: 'Тип работно пространство',
        hr: 'Vrsta radnog prostora',
        sr: 'Врста радног простора',
        sl: 'Vrsta delovnega prostora',
        mk: 'Вид на работен простор',
        be: 'Тып працоўнай прасторы',
        bs: 'Vrsta radnog prostora',
        hsb: 'Typ dźěłoweho ruma',
      }),
      actions: t({
        ru: 'Действия',
        en: 'Actions',
        kk: 'Әрекеттер',
        de: 'Aktionen',
        fr: 'Actions',
        es: 'Acciones',
        pt: 'Ações',
        tr: 'İşlemler',
        uk: 'Дії',
        zh: '操作',
        ar: 'الإجراءات',
        pl: 'Akcje',
        it: 'Azioni',
        sk: 'Akcie',
        ja: '操作',
        ko: '작업',
        hi: 'कार्रवाइयाँ',
        nl: 'Acties',
        sv: 'Åtgärder',
        vi: 'Thao tác',
        id: 'Tindakan',
        da: 'Handlinger',
        nb: 'Handlinger',
        nn: 'Handlingar',
        fi: 'Toiminnot',
        is: 'Aðgerðir',
        fo: 'Handlingar',
        cs: 'Akce',
        bg: 'Действия',
        hr: 'Radnje',
        sr: 'Радње',
        sl: 'Dejanja',
        mk: 'Дејства',
        be: 'Дзеянні',
        bs: 'Radnje',
        hsb: 'Akcije',
      }),
    },
    roles: {
      owner: t({
        ru: 'Владелец',
        en: 'Owner',
        kk: 'Иесі',
        de: 'Eigentümer',
        fr: 'Propriétaire',
        es: 'Propietario',
        pt: 'Proprietário',
        tr: 'Sahip',
        uk: 'Власник',
        zh: '所有者',
        ar: 'المالك',
        pl: 'Właściciel',
        it: 'Proprietario',
        sk: 'Vlastník',
        ja: 'オーナー',
        ko: '소유자',
        hi: 'स्वामी',
        nl: 'Eigenaar',
        sv: 'Ägare',
        vi: 'Chủ sở hữu',
        id: 'Pemilik',
        da: 'Ejer',
        nb: 'Eier',
        nn: 'Eigar',
        fi: 'Omistaja',
        is: 'Eigandi',
        fo: 'Eigari',
        cs: 'Vlastník',
        bg: 'Собственик',
        hr: 'Vlasnik',
        sr: 'Власник',
        sl: 'Lastnik',
        mk: 'Сопственик',
        be: 'Уладальнік',
        bs: 'Vlasnik',
        hsb: 'Wobsedźer',
      }),
      admin: t({
        ru: 'Администратор',
        en: 'Admin',
        kk: 'Әкімші',
        de: 'Administrator',
        fr: 'Administrateur',
        es: 'Administrador',
        pt: 'Administrador',
        tr: 'Yönetici',
        uk: 'Адміністратор',
        zh: '管理员',
        ar: 'مسؤول',
        pl: 'Administrator',
        it: 'Amministratore',
        sk: 'Administrátor',
        ja: '管理者',
        ko: '관리자',
        hi: 'व्यवस्थापक',
        nl: 'Beheerder',
        sv: 'Administratör',
        vi: 'Quản trị viên',
        id: 'Admin',
        da: 'Administrator',
        nb: 'Administrator',
        nn: 'Administrator',
        fi: 'Ylläpitäjä',
        is: 'Kerfisstjóri',
        fo: 'Umsitari',
        cs: 'Správce',
        bg: 'Администратор',
        hr: 'Administrator',
        sr: 'Администратор',
        sl: 'Skrbnik',
        mk: 'Администратор',
        be: 'Адміністратар',
        bs: 'Administrator',
        hsb: 'Administrator',
      }),
      member: t({
        ru: 'Участник',
        en: 'Member',
        kk: 'Мүше',
        de: 'Mitglied',
        fr: 'Membre',
        es: 'Miembro',
        pt: 'Membro',
        tr: 'Üye',
        uk: 'Учасник',
        zh: '成员',
        ar: 'عضو',
        pl: 'Członek',
        it: 'Membro',
        sk: 'Člen',
        ja: 'メンバー',
        ko: '멤버',
        hi: 'सदस्य',
        nl: 'Lid',
        sv: 'Medlem',
        vi: 'Thành viên',
        id: 'Anggota',
        da: 'Medlem',
        nb: 'Medlem',
        nn: 'Medlem',
        fi: 'Jäsen',
        is: 'Meðlimur',
        fo: 'Limur',
        cs: 'Člen',
        bg: 'Член',
        hr: 'Član',
        sr: 'Члан',
        sl: 'Član',
        mk: 'Член',
        be: 'Удзельнік',
        bs: 'Član',
        hsb: 'Čłon',
      }),
      viewer: t({
        ru: 'Наблюдатель',
        en: 'Viewer',
        kk: 'Қараушы',
        de: 'Betrachter',
        fr: 'Observateur',
        es: 'Observador',
        pt: 'Visualizador',
        tr: 'İzleyici',
        uk: 'Спостерігач',
        zh: '查看者',
        ar: 'مشاهد',
        pl: 'Obserwator',
        it: 'Visualizzatore',
        sk: 'Pozorovateľ',
        ja: '閲覧者',
        ko: '뷰어',
        hi: 'दर्शक',
        nl: 'Kijker',
        sv: 'Visare',
        vi: 'Người xem',
        id: 'Pengamat',
        da: 'Læser',
        nb: 'Leser',
        nn: 'Lesar',
        fi: 'Katsoja',
        is: 'Lesandi',
        fo: 'Lesari',
        cs: 'Čtenář',
        bg: 'Четец',
        hr: 'Čitatelj',
        sr: 'Читач',
        sl: 'Bralec',
        mk: 'Читач',
        be: 'Чытач',
        bs: 'Čitalac',
        hsb: 'Čitar',
      }),
    },
    tabs: {
      sections: t({
        ru: 'Разделы рабочего пространства',
        en: 'Workspace sections',
        kk: 'Жұмыс кеңістігінің бөлімдері',
        de: 'Bereiche des Arbeitsbereichs',
        fr: "Sections de l'espace de travail",
        es: 'Secciones del espacio de trabajo',
        pt: 'Seções do espaço de trabalho',
        tr: 'Çalışma alanı bölümleri',
        uk: 'Розділи робочого простору',
        zh: '工作区分区',
        ar: 'أقسام مساحة العمل',
        pl: 'Sekcje obszaru roboczego',
        it: "Sezioni dell'area di lavoro",
        sk: 'Sekcie pracovného priestoru',
        ja: 'ワークスペースのセクション',
        ko: '워크스페이스 섹션',
        hi: 'कार्यक्षेत्र के अनुभाग',
        nl: 'Onderdelen van de werkruimte',
        sv: 'Arbetsytans avsnitt',
        vi: 'Các mục của không gian làm việc',
        id: 'Bagian ruang kerja',
        da: 'Arbejdsrummets afsnit',
        nb: 'Arbeidsrommets deler',
        nn: 'Delane i arbeidsrommet',
        fi: 'Työtilan osiot',
        is: 'Hlutar vinnurýmisins',
        fo: 'Partar í arbeiðsrúminum',
        cs: 'Sekce pracovního prostoru',
        bg: 'Раздели на работното пространство',
        hr: 'Dijelovi radnog prostora',
        sr: 'Делови радног простора',
        sl: 'Razdelki delovnega prostora',
        mk: 'Делови на работниот простор',
        be: 'Раздзелы працоўнай прасторы',
        bs: 'Dijelovi radnog prostora',
        hsb: 'Wotrězki dźěłoweho ruma',
      }),
      allWorkspaces: t({
        ru: 'Все пространства',
        en: 'All Workspaces',
        kk: 'Барлық кеңістіктер',
        de: 'Alle Arbeitsbereiche',
        fr: 'Tous les espaces de travail',
        es: 'Todos los espacios de trabajo',
        pt: 'Todos os espaços de trabalho',
        tr: 'Tüm çalışma alanları',
        uk: 'Усі простори',
        zh: '所有工作区',
        ar: 'جميع مساحات العمل',
        pl: 'Wszystkie obszary robocze',
        it: 'Tutte le aree di lavoro',
        sk: 'Všetky pracovné priestory',
        ja: 'すべてのワークスペース',
        ko: '모든 워크스페이스',
        hi: 'सभी कार्यक्षेत्र',
        nl: 'Alle werkruimtes',
        sv: 'Alla arbetsytor',
        vi: 'Tất cả không gian làm việc',
        id: 'Semua ruang kerja',
        da: 'Alle arbejdsrum',
        nb: 'Alle arbeidsrom',
        nn: 'Alle arbeidsrom',
        fi: 'Kaikki työtilat',
        is: 'Öll vinnurými',
        fo: 'Øll arbeiðsrúm',
        cs: 'Všechny pracovní prostory',
        bg: 'Всички работни пространства',
        hr: 'Svi radni prostori',
        sr: 'Сви радни простори',
        sl: 'Vsi delovni prostori',
        mk: 'Сите работни простори',
        be: 'Усе працоўныя прасторы',
        bs: 'Svi radni prostori',
        hsb: 'Wšě dźěłowe rumy',
      }),
    },
  },
} satisfies Dictionary;

export default content;
